OOPS Documentation: oops::HybridCovariance< MODEL > Class Template Reference
oops::HybridCovariance< MODEL > Class Template Reference
Generic hybrid static-ensemble model space error covariance.
#include <HybridCovariance.h>
Public Member Functions
HybridCovariance (const Geometry_ &, const Variables_ &, const eckit::Configuration &, const State_ &)
Constructor, destructor.
~HybridCovariance ()
void linearize (const State_ &, const Geometry_ &) override
Set up the inner loop resolution B matrix.
void multiply (const Increment_ &, Increment_ &) const override
\(dx_1 = B dx_2 \)
void inverseMultiply (const Increment_ &, Increment_ &) const override
\(dx_1 = B^{-1} dx_2 \)
void multiplySqrt (const IncrCtlVec_ &, Increment_ &) const override
\(dx = B^{1/2} dv \)
void multiplySqrtTrans (const Increment_ &, IncrCtlVec_ &) const override
\(dv = [B^{1/2}]^T dx \)
void randomize (Increment_ &) const override
\(dx = B^{1/2} dv_{random} \)
IncrModCtlVec_ * newIncrModCtlVec () const override
IncrEnsCtlVec_ * newIncrEnsCtlVec () const override
Public Member Functions inherited from oops::ModelSpaceCovarianceBase< MODEL >
virtual ~ModelSpaceCovarianceBase ()
Destructor.
virtual void linearize (const State_ &xx, const Geometry_ &geom, const eckit::Configuration &)
Private Types
using Geometry_ = Geometry< MODEL >
using Increment_ = Increment< MODEL >
using IncrCtlVec_ = IncrCtlVec< MODEL >
using IncrEnsCtlVec_ = IncrEnsCtlVec< MODEL >
using IncrModCtlVec_ = IncrModCtlVec< MODEL >
using State_ = State< MODEL >
using Variables_ = Variables< MODEL >
Private Attributes
std::unique_ptr< ModelSpaceCovarianceBase< MODEL > > static_
Static component.
std::unique_ptr< EnsembleCovariance< MODEL > > ensemble_
Ensemble component.
double ensWeight_
Weight.
Detailed Description
template<typename MODEL>
class oops::HybridCovariance< MODEL >
Generic hybrid static-ensemble model space error covariance.
Definition at line 40 of file HybridCovariance.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::HybridCovariance< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 41 of file HybridCovariance.h.
IncrCtlVec_
template<typename MODEL > using oops::HybridCovariance< MODEL >::IncrCtlVec_ = IncrCtlVec<MODEL> private
Definition at line 43 of file HybridCovariance.h.
Increment_
template<typename MODEL > using oops::HybridCovariance< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 42 of file HybridCovariance.h.
IncrEnsCtlVec_
template<typename MODEL > using oops::HybridCovariance< MODEL >::IncrEnsCtlVec_ = IncrEnsCtlVec<MODEL> private
Definition at line 44 of file HybridCovariance.h.
IncrModCtlVec_
template<typename MODEL > using oops::HybridCovariance< MODEL >::IncrModCtlVec_ = IncrModCtlVec<MODEL> private
Definition at line 45 of file HybridCovariance.h.
State_
template<typename MODEL > using oops::HybridCovariance< MODEL >::State_ = State<MODEL> private
Definition at line 46 of file HybridCovariance.h.
Variables_
template<typename MODEL > using oops::HybridCovariance< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 47 of file HybridCovariance.h.
Constructor & Destructor Documentation
HybridCovariance()
template<typename MODEL > oops::HybridCovariance< MODEL >::HybridCovariance (const Geometry_ & resol, const Variables_ & vars, const eckit::Configuration & config, const State_ & xb)
Constructor, destructor.
Definition at line 84 of file HybridCovariance.h.
     : static_(CovarianceFactory<MODEL>::create(
           eckit::LocalConfiguration(config, "static"), resol, vars, xb)) {
   const eckit::LocalConfiguration ensConf(config, "ensemble");
   ensemble_.reset(new EnsembleCovariance<MODEL>(resol, vars, ensConf, xb));
   ensWeight_ = config.getDouble("ensemble_weight");
   ASSERT(ensWeight_ > 0.0 && ensWeight_ <= 1.0);
   Log::trace() << "HybridCovariance created." << std::endl;
 }
References oops::HybridCovariance< MODEL >::ensemble_, and oops::HybridCovariance< MODEL >::ensWeight_.
~HybridCovariance()
template<typename MODEL > oops::HybridCovariance< MODEL >::~HybridCovariance
Definition at line 99 of file HybridCovariance.h.
{
   Log::trace() << "HybridCovariance destructed" << std::endl;
 }
Member Function Documentation
inverseMultiply()
template<typename MODEL > void oops::HybridCovariance< MODEL >::inverseMultiply (const Increment_ & , Increment_ &) const override virtual
\(dx_1 = B^{-1} dx_2 \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 122 of file HybridCovariance.h.
{
   IdentityMatrix<Increment_> Id;
   dxo.zero();
   GMRESR(dxo, dxi, *this, Id, 10, 1.0e-3);
 }
References oops::GMRESR(), and oops::Increment< MODEL >::zero().
linearize()
template<typename MODEL > void oops::HybridCovariance< MODEL >::linearize (const State_ & , const Geometry_ &) override virtual
Set up the inner loop resolution B matrix.
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 104 of file HybridCovariance.h.
{
   static_->linearize(xb, resol);
   ensemble_->linearize(xb, resol);
   Log::trace() << "HybridCovariance linearized." << std::endl;
 }
multiply()
template<typename MODEL > void oops::HybridCovariance< MODEL >::multiply (const Increment_ & , Increment_ &) const override virtual
\(dx_1 = B dx_2 \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 112 of file HybridCovariance.h.
{
   static_->multiply(dxi, dxo);
   dxo *= (1.0 - ensWeight_);
   Increment_ tmp(dxo);
   ensemble_->multiply(dxi, tmp);
   dxo.axpy(ensWeight_, tmp);
 }
References oops::Increment< MODEL >::axpy().
multiplySqrt()
template<typename MODEL > void oops::HybridCovariance< MODEL >::multiplySqrt (const IncrCtlVec_ & , Increment_ &) const override virtual
\(dx = B^{1/2} dv \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 130 of file HybridCovariance.h.
{
   static_->multiplySqrt(dv, dx);
   dx *= std::sqrt(1.0 - ensWeight_);
   Increment_ dxe(dx);
   dxe.zero();
   ensemble_->multiplySqrt(dv, dxe);
   dx.axpy(std::sqrt(ensWeight_), dxe);
 }
References oops::Increment< MODEL >::axpy(), and oops::Increment< MODEL >::zero().
multiplySqrtTrans()
template<typename MODEL > void oops::HybridCovariance< MODEL >::multiplySqrtTrans (const Increment_ & , IncrCtlVec_ &) const override virtual
\(dv = [B^{1/2}]^T dx \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 141 of file HybridCovariance.h.
{
   Increment_ dxm(dx);
   dxm *= std::sqrt(1.0 - ensWeight_);
   static_->multiplySqrtTrans(dxm, dv);
   Increment_ dxe(dx);
   dxe *= std::sqrt(ensWeight_);
   ensemble_->multiplySqrtTrans(dxe, dv);
 }
newIncrEnsCtlVec()
template<typename MODEL > IncrEnsCtlVec_* oops::HybridCovariance< MODEL >::newIncrEnsCtlVec () const inline override virtual
Return a new control vector corresponding to the localised sampled component of a B matrix
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 67 of file HybridCovariance.h.
{
     return ensemble_->newIncrEnsCtlVec();
   }
References oops::HybridCovariance< MODEL >::ensemble_.
newIncrModCtlVec()
template<typename MODEL > IncrModCtlVec_* oops::HybridCovariance< MODEL >::newIncrModCtlVec () const inline override virtual
Return a new control vector corresponding to the modelled component of a B matrix
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 64 of file HybridCovariance.h.
{
     return static_->newIncrModCtlVec();
   }
References oops::HybridCovariance< MODEL >::static_.
randomize()
template<typename MODEL > void oops::HybridCovariance< MODEL >::randomize (Increment_ &) const override virtual
\(dx = B^{1/2} dv_{random} \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 152 of file HybridCovariance.h.
{
   ABORT("HybridCovariance::randomize: Would it make sense?");
 }
References ABORT.
Member Data Documentation
ensemble_
template<typename MODEL > std::unique_ptr<EnsembleCovariance<MODEL> > oops::HybridCovariance< MODEL >::ensemble_ private
Ensemble component.
Definition at line 75 of file HybridCovariance.h.
Referenced by oops::HybridCovariance< MODEL >::HybridCovariance(), and oops::HybridCovariance< MODEL >::newIncrEnsCtlVec().
ensWeight_
template<typename MODEL > double oops::HybridCovariance< MODEL >::ensWeight_ private
Weight.
Definition at line 76 of file HybridCovariance.h.
Referenced by oops::HybridCovariance< MODEL >::HybridCovariance().
static_
template<typename MODEL > std::unique_ptr<ModelSpaceCovarianceBase<MODEL> > oops::HybridCovariance< MODEL >::static_ private
Static component.
Definition at line 73 of file HybridCovariance.h.
Referenced by oops::HybridCovariance< MODEL >::newIncrModCtlVec().
The documentation for this class was generated from the following file:
src/oops/base/HybridCovariance.h