OOPS Documentation: oops::Localization< MODEL > Class Template Reference
oops::Localization< MODEL > Class Template Reference
#include <IncrEnsCtlVec.h>
Public Member Functions
Localization (const Geometry_ &, const eckit::Configuration &)
virtual ~Localization ()
void multiply (Increment_ &) const
void multiplySqrt (const IncrEnsCtlVec_ &, Increment_ &) const
void multiplySqrtTrans (const Increment_ &, IncrEnsCtlVec_ &) const
Localization_ & localization ()
const Localization_ & localization () const
Static Public Member Functions
static const std::string classname ()
Private Types
using Localization_ = typename MODEL::LocalizationMatrix
using Geometry_ = Geometry< MODEL >
using IncrEnsCtlVec_ = IncrEnsCtlVec< MODEL >
using Increment_ = Increment< MODEL >
Private Member Functions
void print (std::ostream &) const
Private Attributes
std::unique_ptr< Localization_ > local_
Detailed Description
template<typename MODEL>
class oops::Localization< MODEL >
Definition at line 29 of file IncrEnsCtlVec.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::Localization< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 43 of file Localization.h.
Increment_
template<typename MODEL > using oops::Localization< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 45 of file Localization.h.
IncrEnsCtlVec_
template<typename MODEL > using oops::Localization< MODEL >::IncrEnsCtlVec_ = IncrEnsCtlVec<MODEL> private
Definition at line 44 of file Localization.h.
Localization_
template<typename MODEL > using oops::Localization< MODEL >::Localization_ = typename MODEL::LocalizationMatrix private
Definition at line 42 of file Localization.h.
Constructor & Destructor Documentation
Localization()
template<typename MODEL > oops::Localization< MODEL >::Localization (const Geometry_ & resol, const eckit::Configuration & conf)
Definition at line 69 of file Localization.h.
     : local_() {
   Log::trace() << "Localization<MODEL>::Localization starting" << std::endl;
   util::Timer timer(classname(), "Localization");
   local_.reset(new Localization_(resol.geometry(), conf));
   Log::trace() << "Localization<MODEL>::Localization done" << std::endl;
 }
References oops::Localization< MODEL >::classname(), oops::Geometry< MODEL >::geometry(), and oops::Localization< MODEL >::local_.
~Localization()
template<typename MODEL > oops::Localization< MODEL >::~Localization virtual
Definition at line 81 of file Localization.h.
{
   Log::trace() << "Localization<MODEL>::~Localization starting" << std::endl;
   util::Timer timer(classname(), "~Localization");
   local_.reset();
   Log::trace() << "Localization<MODEL>::~Localization done" << std::endl;
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::Localization< MODEL >::classname () inline static
Definition at line 48 of file Localization.h.
 { return "oops::Localization"; }
Referenced by oops::Localization< MODEL >::Localization().
localization() [1/2]
template<typename MODEL > Localization_& oops::Localization< MODEL >::localization () inline
Definition at line 58 of file Localization.h.
 { return *local_; }
References oops::Localization< MODEL >::local_.
Referenced by oops::IncrEnsCtlVec< MODEL >::IncrEnsCtlVec().
localization() [2/2]
template<typename MODEL > const Localization_& oops::Localization< MODEL >::localization () const inline
Definition at line 59 of file Localization.h.
 { return *local_; }
References oops::Localization< MODEL >::local_.
multiply()
template<typename MODEL > void oops::Localization< MODEL >::multiply (Increment_ & dx) const
Definition at line 91 of file Localization.h.
{
   Log::trace() << "Localization<MODEL>::mult starting" << std::endl;
   util::Timer timer(classname(), "mult");
   local_->multiply(dx.increment());
   Log::trace() << "Localization<MODEL>::mult done" << std::endl;
 }
References oops::Increment< MODEL >::increment().
multiplySqrt()
template<typename MODEL > void oops::Localization< MODEL >::multiplySqrt (const IncrEnsCtlVec_ & dv, Increment_ & dx) const
Definition at line 101 of file Localization.h.
{
   Log::trace() << "Localization<MODEL>::multSqrt starting" << std::endl;
   util::Timer timer(classname(), "multSqrt");
   local_->multiplySqrt(dv.ctlVec(), dx.increment());
   Log::trace() << "Localization<MODEL>::multSqrt done" << std::endl;
 }
References oops::IncrEnsCtlVec< MODEL >::ctlVec(), and oops::Increment< MODEL >::increment().
multiplySqrtTrans()
template<typename MODEL > void oops::Localization< MODEL >::multiplySqrtTrans (const Increment_ & dx, IncrEnsCtlVec_ & dv) const
Definition at line 112 of file Localization.h.
{
   Log::trace() << "Localization<MODEL>::multSqrtTrans starting" << std::endl;
   util::Timer timer(classname(), "multSqrtTrans");
   local_->multiplySqrtTrans(dx.increment(), dv.ctlVec());
   Log::trace() << "Localization<MODEL>::multSqrtTrans done" << std::endl;
 }
References oops::IncrEnsCtlVec< MODEL >::ctlVec(), and oops::Increment< MODEL >::increment().
print()
template<typename MODEL > void oops::Localization< MODEL >::print (std::ostream & os) const private
Definition at line 123 of file Localization.h.
{
   Log::trace() << "Localization<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   os << *local_;
   Log::trace() << "Localization<MODEL>::print done" << std::endl;
 }
Member Data Documentation
local_
template<typename MODEL > std::unique_ptr<Localization_> oops::Localization< MODEL >::local_ private
Definition at line 63 of file Localization.h.
Referenced by oops::Localization< MODEL >::Localization(), and oops::Localization< MODEL >::localization().
The documentation for this class was generated from the following files:
src/oops/interface/IncrEnsCtlVec.h
src/oops/interface/Localization.h