OOPS Documentation: oops::DualMinimizer< MODEL > Class Template Reference
oops::DualMinimizer< MODEL > Class Template Reference abstract
Dual Minimizer.
#include <DualMinimizer.h>
Public Member Functions
virtual const std::string classname () const override=0
DualMinimizer (const CostFct_ &J)
~DualMinimizer ()
void checkpoint (eckit::LocalConfiguration &) const
Checkpoint the minimizer (virtual method)
void restart (const eckit::Configuration &)
Restart the minimizer (virtual method)
void warmStart (const eckit::Configuration &)
Warm start the minimizer (virtual method)
Public Member Functions inherited from oops::Minimizer< MODEL >
Minimizer (const CostFct_ &J)
Construct a minimizer.
virtual ~Minimizer ()
Destroy a minimizer.
ControlIncrement< MODEL > * minimize (const eckit::Configuration &)
Orchestrate the minimization of a quadratic cost function.
Private Types
using CtrlInc_ = ControlIncrement< MODEL >
using CostFct_ = CostFunction< MODEL >
using Bmat_ = BMatrix< MODEL >
using Dual_ = DualVector< MODEL >
using HBHt_ = HBHtMatrix< MODEL >
using Minimizer_ = Minimizer< MODEL >
using Rinv_ = RinvMatrix< MODEL >
Private Member Functions
CtrlInc_ * doMinimize (const eckit::Configuration &) override
Minimizer the quadratic cost function (virtual method)
virtual double solve (Dual_ &, double &, Dual_ &, const HBHt_ &, const Rinv_ &, const int &, const double &, Dual_ &, const double &)=0
Private Attributes
const CostFct_ & J_
std::unique_ptr< CtrlInc_ > gradJb_
Detailed Description
template<typename MODEL>
class oops::DualMinimizer< MODEL >
Dual Minimizer.
Base class for all dual (observation) space minimizers.
Definition at line 43 of file DualMinimizer.h.
Member Typedef Documentation
Bmat_
template<typename MODEL > using oops::DualMinimizer< MODEL >::Bmat_ = BMatrix<MODEL> private
Definition at line 46 of file DualMinimizer.h.
CostFct_
template<typename MODEL > using oops::DualMinimizer< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 45 of file DualMinimizer.h.
CtrlInc_
template<typename MODEL > using oops::DualMinimizer< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 44 of file DualMinimizer.h.
Dual_
template<typename MODEL > using oops::DualMinimizer< MODEL >::Dual_ = DualVector<MODEL> private
Definition at line 47 of file DualMinimizer.h.
HBHt_
template<typename MODEL > using oops::DualMinimizer< MODEL >::HBHt_ = HBHtMatrix<MODEL> private
Definition at line 48 of file DualMinimizer.h.
Minimizer_
template<typename MODEL > using oops::DualMinimizer< MODEL >::Minimizer_ = Minimizer<MODEL> private
Definition at line 49 of file DualMinimizer.h.
Rinv_
template<typename MODEL > using oops::DualMinimizer< MODEL >::Rinv_ = RinvMatrix<MODEL> private
Definition at line 50 of file DualMinimizer.h.
Constructor & Destructor Documentation
DualMinimizer()
template<typename MODEL > oops::DualMinimizer< MODEL >::DualMinimizer (const CostFct_ & J) inline explicit
Definition at line 55 of file DualMinimizer.h.
 : Minimizer_(J), J_(J), gradJb_() {}
~DualMinimizer()
template<typename MODEL > oops::DualMinimizer< MODEL >::~DualMinimizer () inline
Definition at line 56 of file DualMinimizer.h.
 {}
Member Function Documentation
checkpoint()
template<typename MODEL > void oops::DualMinimizer< MODEL >::checkpoint (eckit::LocalConfiguration &) const inline virtual
Checkpoint the minimizer (virtual method)
Implements oops::Minimizer< MODEL >.
Definition at line 58 of file DualMinimizer.h.
 {}
classname()
template<typename MODEL > virtual const std::string oops::DualMinimizer< MODEL >::classname () const override pure virtual
Implements oops::Minimizer< MODEL >.
Implemented in oops::RPLanczosMinimizer< MODEL >, and oops::RPCGMinimizer< MODEL >.
doMinimize()
template<typename MODEL > ControlIncrement< MODEL > * oops::DualMinimizer< MODEL >::doMinimize (const eckit::Configuration &) override private virtual
Minimizer the quadratic cost function (virtual method)
Implements oops::Minimizer< MODEL >.
Definition at line 75 of file DualMinimizer.h.
{
   int ninner = config.getInt("ninner");
   double gnreduc = config.getDouble("gradient_norm_reduction");
   bool lauxMinDiags = false;
   if (config.has("onlineDiagnostics")) {
     const eckit::LocalConfiguration onlineDiag(config, "onlineDiagnostics");
     lauxMinDiags = onlineDiag.getBool("auxMinDiags");
   }
   if (gradJb_ == 0) {
     gradJb_.reset(new CtrlInc_(J_.jb()));
   } else {
     gradJb_.reset(new CtrlInc_(J_.jb().resolution(), *gradJb_));
   }
   Log::info() << std::endl;
   Log::info() << classname() << ": max iter = " << ninner
               << ", requested norm reduction = " << gnreduc << std::endl;
   // Define the matrices
   const Bmat_ B(J_);
   const HBHt_ HBHt(J_, lauxMinDiags);
   const Rinv_ Rinv(J_);
   const HMatrix<MODEL> H(J_);
   const HtMatrix<MODEL> Ht(J_);
   // Define minimisation starting point in dual space
   Dual_ vv;
   for (unsigned jj = 0; jj < J_.nterms(); ++jj) {
     vv.append(J_.jterm(jj).newDualVector());
   }
   double vvp = 0.0;
   // Get R^{-1} d
   Dual_ rr;
   for (unsigned jj = 0; jj < J_.nterms(); ++jj) {
     rr.append(J_.jterm(jj).newGradientFG());
   }
   // Update rr if initial dx in model space is not a zero vector
   // rr = rr - Rinv H dx0
   // Compute a = H (xb - xk)
   Dual_ dy;
   CtrlInc_ hdxfg(J_.jb().getFirstGuessIncrement());
   H.multiply(hdxfg, dy);
   dy *= -1.0;
   // Compute sigma = (xb - xk)^T Binv (xb - xk)
   CtrlInc_ g0(J_.jb());
   J_.jb().addGradientFG(g0, *gradJb_);
   double sigma = -1.0 * dot_product(J_.jb().getFirstGuessIncrement(), g0);
   // Solve the linear system
   double reduc =
       this->solve(vv, vvp, rr, HBHt, Rinv, ninner, gnreduc, dy, sigma);
   Log::test() << classname() << ": reduction in residual norm = " << reduc
               << std::endl;
   // Recover solution in primal space
   CtrlInc_ dh(J_.jb());
   J_.zeroAD(dh);
   Ht.multiply(vv, dh);
   dh.axpy(vvp, g0);
   CtrlInc_ *dx = new CtrlInc_(J_.jb());
   B.multiply(dh, *dx);  // BHtaug vvaug
   Log::info() << classname()
               << ": Estimated Final Jb = " << 0.5 * dot_product(*dx, dh)
               << std::endl;
   Log::info() << classname() << " output" << *dx << std::endl;
   // Update gradient Jb
   *gradJb_ += dh;
   return dx;
 }
References oops::DualVector< MODEL >::append(), oops::ControlIncrement< MODEL >::axpy(), dot_product(), oops::BMatrix< MODEL >::multiply(), oops::HtMatrix< MODEL >::multiply(), and oops::HMatrix< MODEL >::multiply().
restart()
template<typename MODEL > void oops::DualMinimizer< MODEL >::restart (const eckit::Configuration &) inline virtual
Restart the minimizer (virtual method)
Implements oops::Minimizer< MODEL >.
Definition at line 59 of file DualMinimizer.h.
 {}
solve()
template<typename MODEL > virtual double oops::DualMinimizer< MODEL >::solve (Dual_ & , double & , Dual_ & , const HBHt_ & , const Rinv_ & , const int & , const double & , Dual_ & , const double &) private pure virtual
Implemented in oops::RPLanczosMinimizer< MODEL >, and oops::RPCGMinimizer< MODEL >.
warmStart()
template<typename MODEL > void oops::DualMinimizer< MODEL >::warmStart (const eckit::Configuration &) inline virtual
Warm start the minimizer (virtual method)
Implements oops::Minimizer< MODEL >.
Definition at line 60 of file DualMinimizer.h.
 {}
Member Data Documentation
gradJb_
template<typename MODEL > std::unique_ptr<CtrlInc_> oops::DualMinimizer< MODEL >::gradJb_ private
Definition at line 69 of file DualMinimizer.h.
J_
template<typename MODEL > const CostFct_& oops::DualMinimizer< MODEL >::J_ private
Definition at line 68 of file DualMinimizer.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/DualMinimizer.h