OOPS Documentation: oops::GenEnsPertB< MODEL > Class Template Reference
oops::GenEnsPertB< MODEL > Class Template Reference
#include <GenEnsPertB.h>
Public Member Functions
GenEnsPertB ()
virtual ~GenEnsPertB ()
int execute (const eckit::Configuration &fullConfig) const
Public Member Functions inherited from oops::Application
Application ()
virtual ~Application ()
Private Types
using Geometry_ = Geometry< MODEL >
using Model_ = Model< MODEL >
using ModelAux_ = ModelAuxControl< MODEL >
using Increment_ = Increment< MODEL >
using State_ = State< MODEL >
using Variables_ = Variables< MODEL >
Private Member Functions
std::string appname () const
Detailed Description
template<typename MODEL>
class oops::GenEnsPertB< MODEL >
Definition at line 40 of file GenEnsPertB.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::GenEnsPertB< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 41 of file GenEnsPertB.h.
Increment_
template<typename MODEL > using oops::GenEnsPertB< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 44 of file GenEnsPertB.h.
Model_
template<typename MODEL > using oops::GenEnsPertB< MODEL >::Model_ = Model<MODEL> private
Definition at line 42 of file GenEnsPertB.h.
ModelAux_
template<typename MODEL > using oops::GenEnsPertB< MODEL >::ModelAux_ = ModelAuxControl<MODEL> private
Definition at line 43 of file GenEnsPertB.h.
State_
template<typename MODEL > using oops::GenEnsPertB< MODEL >::State_ = State<MODEL> private
Definition at line 45 of file GenEnsPertB.h.
Variables_
template<typename MODEL > using oops::GenEnsPertB< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 46 of file GenEnsPertB.h.
Constructor & Destructor Documentation
GenEnsPertB()
template<typename MODEL > oops::GenEnsPertB< MODEL >::GenEnsPertB () inline
Definition at line 50 of file GenEnsPertB.h.
 { instantiateCovarFactory<MODEL>(); }
~GenEnsPertB()
template<typename MODEL > virtual oops::GenEnsPertB< MODEL >::~GenEnsPertB () inline virtual
Definition at line 52 of file GenEnsPertB.h.
 {}
Member Function Documentation
appname()
template<typename MODEL > std::string oops::GenEnsPertB< MODEL >::appname () const inline private virtual
Implements oops::Application.
Definition at line 117 of file GenEnsPertB.h.
{
     return "oops::GenEnsPertB<" + MODEL::name() + ">";
   }
execute()
template<typename MODEL > int oops::GenEnsPertB< MODEL >::execute (const eckit::Configuration & fullConfig) const inline virtual
Implements oops::Application.
Definition at line 54 of file GenEnsPertB.h.
{
     //  Setup resolution
     const eckit::LocalConfiguration resolConfig(fullConfig, "resolution");
     const Geometry_ resol(resolConfig);
     //  Setup variables
     const eckit::LocalConfiguration varConfig(fullConfig, "variables");
     const Variables_ vars(varConfig);
     //  Setup Model
     const eckit::LocalConfiguration modelConfig(fullConfig, "model");
     const Model_ model(resol, modelConfig);
     //  Setup initial state
     const eckit::LocalConfiguration initialConfig(fullConfig, "initial");
     const State_ xx(resol, model, initialConfig);
     Log::test() << "Initial state: " << xx.norm() << std::endl;
     //  Setup augmented state
     const ModelAux_ moderr(resol, model, initialConfig);
     //  Setup times
     const util::Duration fclength(fullConfig.getString("forecast_length"));
     const util::DateTime bgndate(xx.validTime());
     const util::DateTime enddate(bgndate + fclength);
     Log::info() << "Running forecast from " << bgndate << " to " << enddate
                 << std::endl;
     //  Setup B matrix
     const eckit::LocalConfiguration covar(fullConfig, "Covariance");
     std::unique_ptr<ModelSpaceCovarianceBase<MODEL> > Bmat(
         CovarianceFactory<MODEL>::create(covar, resol, vars, xx));
     Bmat->linearize(xx, resol);
     //  Generate perturbed states
     Increment_ dx(resol, vars, bgndate);
     const int members = fullConfig.getInt("members");
     for (int jm = 0; jm < members; ++jm) {
       Bmat->randomize(dx);
       Log::debug() << "before copy xx:" << xx << std::endl;
       State_ xp(xx);
       Log::debug() << "after copy xx:" << xx << std::endl;
       Log::debug() << "after copy xp:" << xp << std::endl;
       xp += dx;
       //    Setup forecast outputs
       PostProcessor<State_> post;
       eckit::LocalConfiguration outConfig(fullConfig, "output");
       outConfig.set("member", long(jm + 1));
       post.enrollProcessor(new StateWriter<State_>(bgndate, outConfig));
       //    Run forecast
       model.forecast(xp, moderr, fclength, post);
       Log::test() << "Member " << jm << " final state: " << xp.norm()
                   << std::endl;
     }
     return 0;
   }
References oops::PostProcessor< FLDS >::enrollProcessor(), oops::Model< MODEL >::forecast(), oops::State< MODEL >::norm(), and oops::State< MODEL >::validTime().
The documentation for this class was generated from the following file:
src/oops/runs/GenEnsPertB.h