OOPS Documentation: oops::CostFct4DEnsVar< MODEL > Class Template Reference
oops::CostFct4DEnsVar< MODEL > Class Template Reference
4D-Ens-Var Cost Function
#include <CostFct4DEnsVar.h>
Public Member Functions
CostFct4DEnsVar (const eckit::Configuration &, const Geometry_ &, const Model_ &)
~CostFct4DEnsVar ()
void runTL (CtrlInc_ &, PostProcessorTL< Increment_ > &, PostProcessor< Increment_ >, const bool idModel=false) const override
Run the tangent linear model (virtual method)
void runAD (CtrlInc_ &, PostProcessorAD< Increment_ > &, PostProcessor< Increment_ >, const bool idModel=false) const override
Run the adjoint model (virtual method)
void zeroAD (CtrlInc_ &) const override
Nullify the increment prior to running the adjoint model (virtual method)
void runNL (CtrlVar_ &, PostProcessor< State_ > &) const override
Run the non-linear model (virtual method)
Public Member Functions inherited from oops::CostFunction< MODEL >
CostFunction (const eckit::Configuration &, const Geometry_ &, const Model_ &)
Construct a cost function.
virtual ~CostFunction ()
Destroy a cost function.
virtual double evaluate (const CtrlVar_ &, const eckit::Configuration &config=eckit::LocalConfiguration(), PostProcessor< State_ > post=PostProcessor< State_ >()) const
Evaluate the non-linear cost function.
virtual double linearize (const CtrlVar_ &, const eckit::Configuration &, PostProcessor< State_ > post=PostProcessor< State_ >())
Linearise the cost function: set up the quadratic cost function.
virtual void runNL (CtrlVar_ &xx, const Model_ &, PostProcessor< State_ > &pp)
Run the non-linear model (virtual method)
void addIncrement (CtrlVar_ &, const CtrlInc_ &, PostProcessor< Increment_ > post=PostProcessor< Increment_ >()) const
Add increment to the first guess.
void resetLinearization ()
Rest the quadratic cost function.
void computeGradientFG (CtrlInc_ &) const
Compute the cost function gradient at first guess (without Jb)
double computeGradientFG (const CtrlVec_ &, CtrlInc_ &) const
Compute the cost function gradient at first guess (without Jb)
void checkpoint (eckit::LocalConfiguration &) const
Checkpoint.
void restart (const eckit::Configuration &)
Restart.
const JbTotal_ & jb () const
Access \(J_b\).
const CostBase_ & jterm (const unsigned ii) const
Access terms of the cost function other than \(J_b\).
unsigned nterms () const
Return the numer of other cost function terms \(J_o, J_c, ..\).
virtual const double & getCostJb () const
Get the Jb cost function value.
virtual const double & getCostJoJc () const
Get the JoJc cost function value.
Private Types
using Increment_ = Increment< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using CtrlVar_ = ControlVariable< MODEL >
using CostFct_ = CostFunction< MODEL >
using Geometry_ = Geometry< MODEL >
using State_ = State< MODEL >
using Model_ = Model< MODEL >
using Variables_ = Variables< MODEL >
Private Member Functions
void addIncr (CtrlVar_ &, const CtrlInc_ &, PostProcessor< Increment_ > &) const override
Virtual method to add the increment to the state.
CostJb4D< MODEL > * newJb (const eckit::Configuration &, const Geometry_ &, const CtrlVar_ &) const override
Create the \(J_b, J_q\) term of the cost function (virtual method)
CostJo< MODEL > * newJo (const eckit::Configuration &) const override
Create the \(J_o\) term of the cost function (virtual method)
CostTermBase< MODEL > * newJc (const eckit::Configuration &, const Geometry_ &) const override
Create other terms of the cost function \(J_c, ..\) (virtual method)
Private Attributes
util::Duration windowLength_
util::DateTime windowBegin_
util::DateTime windowEnd_
util::Duration windowSub_
util::Duration zero_
unsigned int ncontrol_
const Geometry_ & geom_
const Variables_ ctlvars_
Additional Inherited Members
Static Public Member Functions inherited from oops::CostFunction< MODEL >
static const std::string classname ()
Protected Member Functions inherited from oops::CostFunction< MODEL >
void setupTerms (const eckit::Configuration &)
Set up terms of the cost function \(J_b, J_q, J_o, J_c, ..\).
const Model_ & getModel () const
Access the non-linear model.
const LinearModel_ & getTLM (const unsigned isub=0) const
Access the linear model.
void recentreBackground (const eckit::Configuration &)
Re-centre the background.
CostBase_ & getJterm (const unsigned ii) const
Non const access to JTerms for linearize() method in concrete cost-functions.
JbTotal_ & getJb () const
Non const access to Jb for linearize() method in concrete cost-functions
std::vector< std::unique_ptr< LinearModel_ > > & getTLMs ()
Non const access to TL Model for linearize() method in concrete cost-functions
Detailed Description
template<typename MODEL>
class oops::CostFct4DEnsVar< MODEL >
4D-Ens-Var Cost Function
Although so far only used for 4D-Ens-Var this cost function can be interpreted more generally as a four dimensional 3D-Var in the sense that the control variable is 4D (like weak-constraint 4D-Var) but the observation operator is 3D (does not involve the forecast model).
Definition at line 51 of file CostFct4DEnsVar.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::CostFct4DEnsVar< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 55 of file CostFct4DEnsVar.h.
CtrlInc_
template<typename MODEL > using oops::CostFct4DEnsVar< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 53 of file CostFct4DEnsVar.h.
CtrlVar_
template<typename MODEL > using oops::CostFct4DEnsVar< MODEL >::CtrlVar_ = ControlVariable<MODEL> private
Definition at line 54 of file CostFct4DEnsVar.h.
Geometry_
template<typename MODEL > using oops::CostFct4DEnsVar< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 56 of file CostFct4DEnsVar.h.
Increment_
template<typename MODEL > using oops::CostFct4DEnsVar< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 52 of file CostFct4DEnsVar.h.
Model_
template<typename MODEL > using oops::CostFct4DEnsVar< MODEL >::Model_ = Model<MODEL> private
Definition at line 58 of file CostFct4DEnsVar.h.
State_
template<typename MODEL > using oops::CostFct4DEnsVar< MODEL >::State_ = State<MODEL> private
Definition at line 57 of file CostFct4DEnsVar.h.
Variables_
template<typename MODEL > using oops::CostFct4DEnsVar< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 59 of file CostFct4DEnsVar.h.
Constructor & Destructor Documentation
CostFct4DEnsVar()
template<typename MODEL > oops::CostFct4DEnsVar< MODEL >::CostFct4DEnsVar (const eckit::Configuration & config, const Geometry_ & geom, const Model_ & model)
Definition at line 99 of file CostFct4DEnsVar.h.
     : CostFunction<MODEL>::CostFunction(config, geom, model),
       zero_(0),
       geom_(geom),
       ctlvars_(config) {
   windowLength_ = util::Duration(config.getString("window_length"));
   windowBegin_ = util::DateTime(config.getString("window_begin"));
   windowEnd_ = windowBegin_ + windowLength_;
   windowSub_ = util::Duration(config.getString("window_sub"));
   ncontrol_ = windowLength_.toSeconds() / windowSub_.toSeconds();
   ASSERT(windowLength_.toSeconds() == windowSub_.toSeconds() * ncontrol_);
   this->setupTerms(config);
   Log::trace() << "CostFct4DEnsVar constructed" << std::endl;
 }
References oops::CostFct4DEnsVar< MODEL >::ncontrol_, oops::CostFunction< MODEL >::setupTerms(), oops::CostFct4DEnsVar< MODEL >::windowBegin_, oops::CostFct4DEnsVar< MODEL >::windowEnd_, oops::CostFct4DEnsVar< MODEL >::windowLength_, and oops::CostFct4DEnsVar< MODEL >::windowSub_.
~CostFct4DEnsVar()
template<typename MODEL > oops::CostFct4DEnsVar< MODEL >::~CostFct4DEnsVar () inline
Definition at line 64 of file CostFct4DEnsVar.h.
 {}
Member Function Documentation
addIncr()
template<typename MODEL > void oops::CostFct4DEnsVar< MODEL >::addIncr (CtrlVar_ & , const CtrlInc_ & , PostProcessor< Increment_ > &) const override private virtual
Virtual method to add the increment to the state.
Implements oops::CostFunction< MODEL >.
Definition at line 211 of file CostFct4DEnsVar.h.
{
   for (unsigned jsub = 0; jsub <= ncontrol_; ++jsub) {
     xx.state()[jsub] += dx.state()[jsub];
   }
 }
References oops::ControlVariable< MODEL >::state(), and oops::ControlIncrement< MODEL >::state().
newJb()
template<typename MODEL > CostJb4D< MODEL > * oops::CostFct4DEnsVar< MODEL >::newJb (const eckit::Configuration & , const Geometry_ & , const CtrlVar_ &) const override private virtual
Create the \(J_b, J_q\) term of the cost function (virtual method)
Implements oops::CostFunction< MODEL >.
Definition at line 121 of file CostFct4DEnsVar.h.
{
   return new CostJb4D<MODEL>(jbConf, geom, ctlvars_, zero_, xb.state());
 }
References oops::ControlVariable< MODEL >::state().
newJc()
template<typename MODEL > CostTermBase< MODEL > * oops::CostFct4DEnsVar< MODEL >::newJc (const eckit::Configuration & , const Geometry_ &) const override private virtual
Create other terms of the cost function \(J_c, ..\) (virtual method)
Implements oops::CostFunction< MODEL >.
Definition at line 139 of file CostFct4DEnsVar.h.
{
   const eckit::LocalConfiguration jcdfi(jcConf, "jcdfi");
   const util::DateTime vt(windowBegin_ + windowLength_ / 2);
   return new CostJcDFI<MODEL>(jcdfi, geom, vt, windowLength_, windowSub_);
 }
newJo()
template<typename MODEL > CostJo< MODEL > * oops::CostFct4DEnsVar< MODEL >::newJo (const eckit::Configuration &) const override private virtual
Create the \(J_o\) term of the cost function (virtual method)
Implements oops::CostFunction< MODEL >.
Definition at line 130 of file CostFct4DEnsVar.h.
{
   return new CostJo<MODEL>(joConf, geom_, windowBegin_, windowEnd_, windowSub_,
                            true);
 }
runAD()
template<typename MODEL > void oops::CostFct4DEnsVar< MODEL >::runAD (CtrlInc_ & , PostProcessorAD< Increment_ > & , PostProcessor< Increment_ > post, const bool idModel = false) const override virtual
Run the adjoint model (virtual method)
Implements oops::CostFunction< MODEL >.
Definition at line 194 of file CostFct4DEnsVar.h.
{
   for (int jsub = ncontrol_; jsub >= 0; --jsub) {
     util::DateTime now(windowBegin_ + jsub * windowSub_);
     ASSERT(dx.state()[jsub].validTime() == now);
     CostFct_::getTLM(jsub).forecastAD(dx.state()[jsub], dx.modVar(),
                                       util::Duration(0), post, cost);
     ASSERT(dx.state()[jsub].validTime() == now);
   }
 }
References oops::ControlIncrement< MODEL >::modVar(), and oops::ControlIncrement< MODEL >::state().
runNL()
template<typename MODEL > void oops::CostFct4DEnsVar< MODEL >::runNL (CtrlVar_ & , PostProcessor< State_ > &) const override virtual
Run the non-linear model (virtual method)
Implements oops::CostFunction< MODEL >.
Definition at line 149 of file CostFct4DEnsVar.h.
{
   for (unsigned int jsub = 0; jsub <= ncontrol_; ++jsub) {
     util::DateTime now(windowBegin_ + jsub * windowSub_);
     ASSERT(xx.state()[jsub].validTime() == now);
     CostFct_::getModel().forecast(xx.state()[jsub], xx.modVar(),
                                   util::Duration(0), post);
     ASSERT(xx.state()[jsub].validTime() == now);
   }
 }
References oops::ControlVariable< MODEL >::modVar(), and oops::ControlVariable< MODEL >::state().
runTL()
template<typename MODEL > void oops::CostFct4DEnsVar< MODEL >::runTL (CtrlInc_ & , PostProcessorTL< Increment_ > & , PostProcessor< Increment_ > post, const bool idModel = false) const override virtual
Run the tangent linear model (virtual method)
Implements oops::CostFunction< MODEL >.
Definition at line 164 of file CostFct4DEnsVar.h.
{
   for (unsigned int jsub = 0; jsub <= ncontrol_; ++jsub) {
     util::DateTime now(windowBegin_ + jsub * windowSub_);
     ASSERT(dx.state()[jsub].validTime() == now);
     CostFct_::getTLM(jsub).forecastTL(dx.state()[jsub], dx.modVar(),
                                       util::Duration(0), post, cost);
     ASSERT(dx.state()[jsub].validTime() == now);
   }
 }
References oops::ControlIncrement< MODEL >::modVar(), and oops::ControlIncrement< MODEL >::state().
zeroAD()
template<typename MODEL > void oops::CostFct4DEnsVar< MODEL >::zeroAD (CtrlInc_ &) const override virtual
Nullify the increment prior to running the adjoint model (virtual method)
Implements oops::CostFunction< MODEL >.
Definition at line 181 of file CostFct4DEnsVar.h.
{
   util::DateTime now(windowBegin_);
   for (unsigned int jsub = 0; jsub <= ncontrol_; ++jsub) {
     dx.state()[jsub].zero(now);
     now += windowSub_;
   }
   dx.modVar().zero();
   dx.obsVar().zero();
 }
References oops::ControlIncrement< MODEL >::modVar(), oops::ControlIncrement< MODEL >::obsVar(), oops::ControlIncrement< MODEL >::state(), oops::ObsAuxIncrements< MODEL >::zero(), oops::ModelAuxIncrement< MODEL >::zero(), and oops::Increment4D< MODEL >::zero().
Member Data Documentation
ctlvars_
template<typename MODEL > const Variables_ oops::CostFct4DEnsVar< MODEL >::ctlvars_ private
Definition at line 93 of file CostFct4DEnsVar.h.
geom_
template<typename MODEL > const Geometry_& oops::CostFct4DEnsVar< MODEL >::geom_ private
Definition at line 92 of file CostFct4DEnsVar.h.
ncontrol_
template<typename MODEL > unsigned int oops::CostFct4DEnsVar< MODEL >::ncontrol_ private
Definition at line 91 of file CostFct4DEnsVar.h.
Referenced by oops::CostFct4DEnsVar< MODEL >::CostFct4DEnsVar().
windowBegin_
template<typename MODEL > util::DateTime oops::CostFct4DEnsVar< MODEL >::windowBegin_ private
Definition at line 87 of file CostFct4DEnsVar.h.
Referenced by oops::CostFct4DEnsVar< MODEL >::CostFct4DEnsVar().
windowEnd_
template<typename MODEL > util::DateTime oops::CostFct4DEnsVar< MODEL >::windowEnd_ private
Definition at line 88 of file CostFct4DEnsVar.h.
Referenced by oops::CostFct4DEnsVar< MODEL >::CostFct4DEnsVar().
windowLength_
template<typename MODEL > util::Duration oops::CostFct4DEnsVar< MODEL >::windowLength_ private
Definition at line 86 of file CostFct4DEnsVar.h.
Referenced by oops::CostFct4DEnsVar< MODEL >::CostFct4DEnsVar().
windowSub_
template<typename MODEL > util::Duration oops::CostFct4DEnsVar< MODEL >::windowSub_ private
Definition at line 89 of file CostFct4DEnsVar.h.
Referenced by oops::CostFct4DEnsVar< MODEL >::CostFct4DEnsVar().
zero_
template<typename MODEL > util::Duration oops::CostFct4DEnsVar< MODEL >::zero_ private
Definition at line 90 of file CostFct4DEnsVar.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/CostFct4DEnsVar.h