OOPS Documentation: oops::EnsembleCovariance4DScaleDependent< MODEL > Class Template Reference
oops::EnsembleCovariance4DScaleDependent< MODEL > Class Template Reference
Wraps the model space error covariance.
#include <EnsembleCovariance4DScaleDependent.h>
Public Member Functions
EnsembleCovariance4DScaleDependent (const Geometry_ &, const Variables_ &, const eckit::Configuration &, const State4D_ &)
~EnsembleCovariance4DScaleDependent ()
void advectedLinearize (const State4D_ &, const Geometry_ &)
void advectedLinearize (const State4D_ &, const Geometry_ &, const eckit::Configuration &)
void advectedMultiply (const Increment4D_ &, Increment4D_ &) const
void advectedMultiplySqrt (const IncrCtlVec_ &, Increment4D_ &) const
void advectedMultiplySqrtTrans (const Increment4D_ &, IncrCtlVec_ &) const
void advectedInverseMultiply (const Increment4D_ &, Increment4D_ &) const
const ModelSpaceCovarianceBase< MODEL > & covar () const
IncrModCtlVec_ * newIncrModCtlVec () const override
IncrEnsCtlVec_ * newIncrEnsCtlVec () const override
Public Member Functions inherited from oops::ModelSpaceCovariance4DBase< MODEL >
ModelSpaceCovariance4DBase (const Geometry_ &, const eckit::Configuration &config)
virtual ~ModelSpaceCovariance4DBase ()
void linearize (const State4D_ &xb, const Geometry_ &resol)
void linearize (const State4D_ &xb, const Geometry_ &resol, const eckit::Configuration &config)
virtual void multiply (const Increment4D_ &dxi, Increment4D_ &dxo) const
virtual void multiplySqrt (const IncrCtlVec_ &dvi, Increment4D_ &dxo) const
virtual void multiplySqrtTrans (const Increment4D_ &dxi, IncrCtlVec_ &dvo) const
void inverseMultiply (const Increment4D_ &dxi, Increment4D_ &dxo) const
virtual void randomize (Increment4D_ &) const
Private Types
using Ensemble_ = Ensemble< MODEL >
using EnsemblePtr_ = std::shared_ptr< Ensemble< MODEL > >
using EnsemblesCollection_ = EnsemblesCollection< MODEL >
using Geometry_ = Geometry< MODEL >
using Increment_ = Increment< MODEL >
using Localization_ = Localization< MODEL >
using State4D_ = State4D< MODEL >
using Increment4D_ = Increment4D< MODEL >
using IncrCtlVec_ = IncrCtlVec< MODEL >
using IncrEnsCtlVec_ = IncrEnsCtlVec< MODEL >
using IncrModCtlVec_ = IncrModCtlVec< MODEL >
using Variables_ = Variables< MODEL >
using HorizScaleDecomposition_ = HorizScaleDecomposition< MODEL >
Private Member Functions
void schur_add (const Increment_ &, const Increment_ &dxi, Increment_ &dxo, Increment_ &tmp) const
Private Attributes
const eckit::LocalConfiguration config_
std::vector< std::unique_ptr< Localization_ > > loc_
std::unique_ptr< Geometry_ > geom_
std::unique_ptr< ModelSpaceCovarianceBase< MODEL > > static_
unsigned nsubwin_
int nhorizBand_
int SDLtype_
Detailed Description
template<typename MODEL>
class oops::EnsembleCovariance4DScaleDependent< MODEL >
Wraps the model space error covariance.
Definition at line 36 of file EnsembleCovariance4DScaleDependent.h.
Member Typedef Documentation
Ensemble_
template<typename MODEL > using oops::EnsembleCovariance4DScaleDependent< MODEL >::Ensemble_ = Ensemble<MODEL> private
Definition at line 38 of file EnsembleCovariance4DScaleDependent.h.
EnsemblePtr_
template<typename MODEL > using oops::EnsembleCovariance4DScaleDependent< MODEL >::EnsemblePtr_ = std::shared_ptr<Ensemble<MODEL> > private
Definition at line 39 of file EnsembleCovariance4DScaleDependent.h.
EnsemblesCollection_
template<typename MODEL > using oops::EnsembleCovariance4DScaleDependent< MODEL >::EnsemblesCollection_ = EnsemblesCollection<MODEL> private
Definition at line 40 of file EnsembleCovariance4DScaleDependent.h.
Geometry_
template<typename MODEL > using oops::EnsembleCovariance4DScaleDependent< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 41 of file EnsembleCovariance4DScaleDependent.h.
HorizScaleDecomposition_
template<typename MODEL > using oops::EnsembleCovariance4DScaleDependent< MODEL >::HorizScaleDecomposition_ = HorizScaleDecomposition<MODEL> private
Definition at line 50 of file EnsembleCovariance4DScaleDependent.h.
IncrCtlVec_
template<typename MODEL > using oops::EnsembleCovariance4DScaleDependent< MODEL >::IncrCtlVec_ = IncrCtlVec<MODEL> private
Definition at line 46 of file EnsembleCovariance4DScaleDependent.h.
Increment4D_
template<typename MODEL > using oops::EnsembleCovariance4DScaleDependent< MODEL >::Increment4D_ = Increment4D<MODEL> private
Definition at line 45 of file EnsembleCovariance4DScaleDependent.h.
Increment_
template<typename MODEL > using oops::EnsembleCovariance4DScaleDependent< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 42 of file EnsembleCovariance4DScaleDependent.h.
IncrEnsCtlVec_
template<typename MODEL > using oops::EnsembleCovariance4DScaleDependent< MODEL >::IncrEnsCtlVec_ = IncrEnsCtlVec<MODEL> private
Definition at line 47 of file EnsembleCovariance4DScaleDependent.h.
IncrModCtlVec_
template<typename MODEL > using oops::EnsembleCovariance4DScaleDependent< MODEL >::IncrModCtlVec_ = IncrModCtlVec<MODEL> private
Definition at line 48 of file EnsembleCovariance4DScaleDependent.h.
Localization_
template<typename MODEL > using oops::EnsembleCovariance4DScaleDependent< MODEL >::Localization_ = Localization<MODEL> private
Definition at line 43 of file EnsembleCovariance4DScaleDependent.h.
State4D_
template<typename MODEL > using oops::EnsembleCovariance4DScaleDependent< MODEL >::State4D_ = State4D<MODEL> private
Definition at line 44 of file EnsembleCovariance4DScaleDependent.h.
Variables_
template<typename MODEL > using oops::EnsembleCovariance4DScaleDependent< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 49 of file EnsembleCovariance4DScaleDependent.h.
Constructor & Destructor Documentation
EnsembleCovariance4DScaleDependent()
template<typename MODEL > oops::EnsembleCovariance4DScaleDependent< MODEL >::EnsembleCovariance4DScaleDependent (const Geometry_ & resol, const Variables_ & , const eckit::Configuration & config, const State4D_ &)
Definition at line 91 of file EnsembleCovariance4DScaleDependent.h.
     : ModelSpaceCovariance4DBase<MODEL>::ModelSpaceCovariance4DBase(resol,
                                                                     config),
       config_(config) {
   Log::trace() << "EnsembleCovariance4DScaleDependent created.";
 }
~EnsembleCovariance4DScaleDependent()
template<typename MODEL > oops::EnsembleCovariance4DScaleDependent< MODEL >::~EnsembleCovariance4DScaleDependent
Definition at line 102 of file EnsembleCovariance4DScaleDependent.h.
{
   Log::trace() << "EnsembleCovariance4DScaleDependent destructed";
 }
Member Function Documentation
advectedInverseMultiply()
template<typename MODEL > void oops::EnsembleCovariance4DScaleDependent< MODEL >::advectedInverseMultiply (const Increment4D_ & dxi, Increment4D_ & dxo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 354 of file EnsembleCovariance4DScaleDependent.h.
{
   dxo.zero();
 }
References oops::Increment4D< MODEL >::zero().
advectedLinearize() [1/2]
template<typename MODEL > void oops::EnsembleCovariance4DScaleDependent< MODEL >::advectedLinearize (const State4D_ & xb, const Geometry_ & resol) virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 107 of file EnsembleCovariance4DScaleDependent.h.
{
   const eckit::LocalConfiguration conf(config_, "localization");
   const eckit::LocalConfiguration confScaleDecomposition(config_,
                                                          "scale_decomposition");
   // What type of SDL is demanded
   SDLtype_ = confScaleDecomposition.getInt("formulation");
   // How many horizontal bands do we have?
   nhorizBand_ = confScaleDecomposition.getInt("nb_wave_band_peaks");
   // How many localization lenghts do we have?
   std::vector<eckit::LocalConfiguration> confHorizBand;
   confScaleDecomposition.get("horiz_band", confHorizBand);
   int nband = confHorizBand.size();
   // Make sure that the above two numbers are equal
   ASSERT(nband == nhorizBand_);
   geom_.reset(new Geometry_(resol));
   for (int horizBandIndex = 0; horizBandIndex < nhorizBand_ ; ++horizBandIndex) {
     loc_.emplace_back(new Localization_(*geom_, confHorizBand[horizBandIndex]));
   }
   /*
    * Build ensemble
    */
   std::vector<eckit::LocalConfiguration> confEnsemble;
   config_.get("ensemble", confEnsemble);
   nsubwin_ = confEnsemble.size();
   for (unsigned jsub = 0; jsub < nsubwin_; ++jsub) {
     EnsemblePtr_ ens_k(new Ensemble_(xb[jsub].validTime(), confEnsemble[jsub]));
     ens_k->build(xb[jsub], resol);
     EnsemblesCollection_::getInstance().put(xb[jsub].validTime(), ens_k);
   }
   /*
    * Read files
    */
   for (unsigned jsub = 0; jsub < nsubwin_; ++jsub) {
     EnsemblePtr_ ens =
         EnsemblesCollection_::getInstance()[xb[jsub].validTime()];
     ens->read();
   }
   /*
    * Calculate mean
    */
   for (unsigned jsub = 0; jsub < nsubwin_; ++jsub) {
     EnsemblePtr_ ens =
         EnsemblesCollection_::getInstance()[xb[jsub].validTime()];
     ens->to_perturbations();
   }
   /*
    * Performed a horizontal scale decomposition of the perturbations
    */
   Log::info() << "Scale decomposition of the perturbation object";
   HorizScaleDecomposition_ fltbg(confScaleDecomposition);
   for (unsigned jsub = 0; jsub < nsubwin_; ++jsub) {  // loop on ensemble time
     Log::info() << " > treating ensemble time # " << jsub + 1;
     EnsemblePtr_ e = EnsemblesCollection_::getInstance()[xb[jsub].validTime()];
     for (int horizBandIndex = 0; horizBandIndex < nhorizBand_;
          ++horizBandIndex) {
       EnsemblePtr_ ens(new Ensemble_(*e));
       EnsembleKey k(xb[jsub].validTime(), horizBandIndex);
       EnsemblesCollection_::getInstance().put(k, ens);
     }
     for (unsigned l = 0; l < e->size(); ++l) {  // loop on ensemble member
       Log::info()
           << " >> calling horiz_scale_decomposition for ensemble member # "
           << l + 1;
       for (int horizBandIndex = 0; horizBandIndex < nhorizBand_;
            ++horizBandIndex) {
         EnsembleKey k(xb[jsub].validTime(), horizBandIndex);
         EnsemblePtr_ horizBandEns = EnsemblesCollection_::getInstance()[k];
         fltbg.collect((*horizBandEns)[l], horizBandIndex);
       }
       fltbg.decompose((*e)[l], SDLtype_);
     }
   }
   Log::trace() << "EnsembleCovariance4DScaleDependent linearized.";
 }
References oops::HorizScaleDecomposition< MODEL >::collect(), and oops::HorizScaleDecomposition< MODEL >::decompose().
advectedLinearize() [2/2]
template<typename MODEL > void oops::EnsembleCovariance4DScaleDependent< MODEL >::advectedLinearize (const State4D_ & xb, const Geometry_ & resol, const eckit::Configuration &) virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 200 of file EnsembleCovariance4DScaleDependent.h.
{
   Log::info() << "EnsembleCovariance4DScaleDependent advectedLinearize not implemented";
   ASSERT(false);
 }
advectedMultiply()
template<typename MODEL > void oops::EnsembleCovariance4DScaleDependent< MODEL >::advectedMultiply (const Increment4D_ & dxi, Increment4D_ & dxo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 209 of file EnsembleCovariance4DScaleDependent.h.
{
   Increment_ ensAmplitude(dxo[0]);
   Increment_ tmp(dxo[0]);
   EnsemblePtr_ e = EnsemblesCollection_::getInstance()[dxi[0].validTime()];
   unsigned ksiIndex;
   // Note on the scale-dependent localization (SDL) formulation...
   // We use here a B^1/2 approach to save computational cost, since:
   // With B^1/2, the cost of the SDL approach is proportional to the number of
   // scale-bands
   // With B    , the cost of the SDL approach is proportional to the SQUARE of
   // the number of scale-bands
   //
   // --- Apply B^T/2 ---
   //
   Log::info() << "Aplying B^T/2";
   std::vector<std::unique_ptr<IncrEnsCtlVec_>> aksi;
   if (SDLtype_ == 1) {
     // Create one Ksi per ensemble member
     for (unsigned l = 0; l < e->size(); ++l) {
       IncrEnsCtlVec_ *ksi = new IncrEnsCtlVec_(*geom_, *loc_[0]);
       aksi.emplace_back(ksi);
     }
   } else {
     // Create one Ksi per ensemble member and per horizontal waveband
     for (int horizBandIndex = 0; horizBandIndex < nhorizBand_;
          ++horizBandIndex) {
       for (unsigned l = 0; l < e->size(); ++l) {
         IncrEnsCtlVec_ *ksi = new IncrEnsCtlVec_(*geom_, *loc_[0]);
         aksi.emplace_back(ksi);
       }
     }
   }
   // loop on horizontal scale band
   for (int horizBandIndex = 0; horizBandIndex < nhorizBand_; ++horizBandIndex) {
     // loop on ensemble members
     for (unsigned memberIndex = 0; memberIndex < e->size(); ++memberIndex) {
       ensAmplitude.zero();
       // loop on time
       for (unsigned timeIndex = 0; timeIndex < nsubwin_; ++timeIndex) {
         EnsembleKey k(dxi[timeIndex].validTime(), horizBandIndex);
         EnsemblePtr_ e_t = EnsemblesCollection_::getInstance()[k];
         schur_add((*e_t)[memberIndex], dxi[timeIndex], ensAmplitude, tmp);
       }
       if (SDLtype_ == 1) {
         ksiIndex = memberIndex;
       } else {
         ksiIndex = horizBandIndex * e->size() + memberIndex;
       }
       loc_[horizBandIndex]->multiplySqrtTrans(ensAmplitude, *aksi[ksiIndex]);
     }
   }
   //
   // --- Apply B^1/2 ---
   //
   Log::info() << "Aplying B^1/2";
   dxo.zero();
   // loop on horizontal scale band
   for (int horizBandIndex = 0; horizBandIndex < nhorizBand_; ++horizBandIndex) {
     // loop on ensemble members
     for (unsigned memberIndex = 0; memberIndex < e->size(); ++memberIndex) {
       ensAmplitude.zero();
       if (SDLtype_ == 1) {
         ksiIndex = memberIndex;
       } else {
         ksiIndex = horizBandIndex * e->size() + memberIndex;
       }
       loc_[horizBandIndex]->multiplySqrt(*aksi[ksiIndex], ensAmplitude);
       // loop on time
       for (unsigned timeIndex = 0; timeIndex < nsubwin_; ++timeIndex) {
         EnsembleKey k(dxi[timeIndex].validTime(), horizBandIndex);
         EnsemblePtr_ e_t = EnsemblesCollection_::getInstance()[k];
         schur_add((*e_t)[memberIndex], ensAmplitude, dxo[timeIndex], tmp);
       }
     }
   }
 }
References oops::Increment4D< MODEL >::zero(), and oops::Increment< MODEL >::zero().
advectedMultiplySqrt()
template<typename MODEL > void oops::EnsembleCovariance4DScaleDependent< MODEL >::advectedMultiplySqrt (const IncrCtlVec_ & dvi, Increment4D_ & dxo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 298 of file EnsembleCovariance4DScaleDependent.h.
{
   Increment_ ensAmplitude(dxo[0]);
   Increment_ tmp(dxo[0]);
   EnsemblePtr_ e = EnsemblesCollection_::getInstance()[dxo[0].validTime()];
   Log::info() << "Aplying B^1/2";
   dxo.zero();
   // loop on horizontal scale band
   for (int horizBandIndex = 0; horizBandIndex < nhorizBand_; ++horizBandIndex) {
     // loop on ensemble members
     for (unsigned memberIndex = 0; memberIndex < e->size(); ++memberIndex) {
       ensAmplitude.zero();
       loc_[horizBandIndex]->multiplySqrt(dvi.ensCtlVec(memberIndex),
                                          ensAmplitude);
       // loop on time
       for (unsigned timeIndex = 0; timeIndex < nsubwin_; ++timeIndex) {
         EnsembleKey k(dxo[timeIndex].validTime(), horizBandIndex);
         EnsemblePtr_ e_t = EnsemblesCollection_::getInstance()[k];
         schur_add((*e_t)[memberIndex], ensAmplitude, dxo[timeIndex], tmp);
       }
     }
   }
 }
References oops::IncrCtlVec< MODEL >::ensCtlVec(), oops::Increment4D< MODEL >::zero(), and oops::Increment< MODEL >::zero().
advectedMultiplySqrtTrans()
template<typename MODEL > void oops::EnsembleCovariance4DScaleDependent< MODEL >::advectedMultiplySqrtTrans (const Increment4D_ & dxi, IncrCtlVec_ & dvo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 327 of file EnsembleCovariance4DScaleDependent.h.
{
   Increment_ ensAmplitude(dxi[0]);
   Increment_ tmp(dxi[0]);
   EnsemblePtr_ e = EnsemblesCollection_::getInstance()[dxi[0].validTime()];
   Log::info() << "Aplying B^T/2";
   // loop on horizontal scale band
   for (int horizBandIndex = 0; horizBandIndex < nhorizBand_; ++horizBandIndex) {
     // loop on ensemble members
     for (unsigned memberIndex = 0; memberIndex < e->size(); ++memberIndex) {
       ensAmplitude.zero();
       // loop on time
       for (unsigned timeIndex = 0; timeIndex < nsubwin_; ++timeIndex) {
         EnsembleKey k(dxi[timeIndex].validTime(), horizBandIndex);
         EnsemblePtr_ e_t = EnsemblesCollection_::getInstance()[k];
         schur_add((*e_t)[memberIndex], dxi[timeIndex], ensAmplitude, tmp);
       }
       loc_[horizBandIndex]->multiplySqrtTrans(ensAmplitude,
                                               dvo.ensCtlVec(memberIndex));
     }
   }
 }
References oops::IncrCtlVec< MODEL >::ensCtlVec(), and oops::Increment< MODEL >::zero().
covar()
template<typename MODEL > const ModelSpaceCovarianceBase<MODEL>& oops::EnsembleCovariance4DScaleDependent< MODEL >::covar () const inline virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 64 of file EnsembleCovariance4DScaleDependent.h.
 { return *static_; }
References oops::EnsembleCovariance4DScaleDependent< MODEL >::static_.
newIncrEnsCtlVec()
template<typename MODEL > IncrEnsCtlVec_* oops::EnsembleCovariance4DScaleDependent< MODEL >::newIncrEnsCtlVec () const inline override virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 70 of file EnsembleCovariance4DScaleDependent.h.
{
     return new IncrEnsCtlVec_(*geom_, *loc_[0]);
   }
References oops::EnsembleCovariance4DScaleDependent< MODEL >::geom_, and oops::EnsembleCovariance4DScaleDependent< MODEL >::loc_.
newIncrModCtlVec()
template<typename MODEL > IncrModCtlVec_* oops::EnsembleCovariance4DScaleDependent< MODEL >::newIncrModCtlVec () const inline override virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 67 of file EnsembleCovariance4DScaleDependent.h.
{
     return new IncrModCtlVec_();
   }
schur_add()
template<typename MODEL > void oops::EnsembleCovariance4DScaleDependent< MODEL >::schur_add (const Increment_ & pert, const Increment_ & dxi, Increment_ & dxo, Increment_ & tmp) const private
Definition at line 361 of file EnsembleCovariance4DScaleDependent.h.
{
   tmp_schur = pert;
   tmp_schur.schur_product_with(dxi);
   dxo.axpy(1.0, tmp_schur, false);
 }
References oops::Increment< MODEL >::axpy(), and oops::Increment< MODEL >::schur_product_with().
Member Data Documentation
config_
template<typename MODEL > const eckit::LocalConfiguration oops::EnsembleCovariance4DScaleDependent< MODEL >::config_ private
Definition at line 78 of file EnsembleCovariance4DScaleDependent.h.
geom_
template<typename MODEL > std::unique_ptr<Geometry_> oops::EnsembleCovariance4DScaleDependent< MODEL >::geom_ private
Definition at line 80 of file EnsembleCovariance4DScaleDependent.h.
Referenced by oops::EnsembleCovariance4DScaleDependent< MODEL >::newIncrEnsCtlVec().
loc_
template<typename MODEL > std::vector<std::unique_ptr<Localization_> > oops::EnsembleCovariance4DScaleDependent< MODEL >::loc_ private
Definition at line 79 of file EnsembleCovariance4DScaleDependent.h.
Referenced by oops::EnsembleCovariance4DScaleDependent< MODEL >::newIncrEnsCtlVec().
nhorizBand_
template<typename MODEL > int oops::EnsembleCovariance4DScaleDependent< MODEL >::nhorizBand_ private
Definition at line 83 of file EnsembleCovariance4DScaleDependent.h.
nsubwin_
template<typename MODEL > unsigned oops::EnsembleCovariance4DScaleDependent< MODEL >::nsubwin_ private
Definition at line 82 of file EnsembleCovariance4DScaleDependent.h.
SDLtype_
template<typename MODEL > int oops::EnsembleCovariance4DScaleDependent< MODEL >::SDLtype_ private
Definition at line 84 of file EnsembleCovariance4DScaleDependent.h.
static_
template<typename MODEL > std::unique_ptr<ModelSpaceCovarianceBase<MODEL> > oops::EnsembleCovariance4DScaleDependent< MODEL >::static_ private
Definition at line 81 of file EnsembleCovariance4DScaleDependent.h.
Referenced by oops::EnsembleCovariance4DScaleDependent< MODEL >::covar().
The documentation for this class was generated from the following file:
src/oops/base/EnsembleCovariance4DScaleDependent.h