OOPS Documentation: oops::ModelSpaceCovariance4DBase< MODEL > Class Template Reference
oops::ModelSpaceCovariance4DBase< MODEL > Class Template Reference abstract
Abstract base class for model space error covariances.
#include <ModelSpaceCovariance4DBase.h>
Public Member Functions
ModelSpaceCovariance4DBase (const Geometry_ &, const eckit::Configuration &config)
virtual ~ModelSpaceCovariance4DBase ()
void linearize (const State4D_ &xb, const Geometry_ &resol)
void linearize (const State4D_ &xb, const Geometry_ &resol, const eckit::Configuration &config)
virtual void multiply (const Increment4D_ &dxi, Increment4D_ &dxo) const
virtual void multiplySqrt (const IncrCtlVec_ &dvi, Increment4D_ &dxo) const
virtual void multiplySqrtTrans (const Increment4D_ &dxi, IncrCtlVec_ &dvo) const
void inverseMultiply (const Increment4D_ &dxi, Increment4D_ &dxo) const
virtual void randomize (Increment4D_ &) const
virtual void advectedLinearize (const State4D_ &, const Geometry_ &)=0
virtual void advectedLinearize (const State4D_ &, const Geometry_ &, const eckit::Configuration &)=0
virtual void advectedMultiply (const Increment4D_ &, Increment4D_ &) const =0
virtual void advectedMultiplySqrt (const IncrCtlVec_ &, Increment4D_ &) const =0
virtual void advectedMultiplySqrtTrans (const Increment4D_ &, IncrCtlVec_ &) const =0
virtual void advectedInverseMultiply (const Increment4D_ &, Increment4D_ &) const =0
virtual const ModelSpaceCovarianceBase< MODEL > & covar () const =0
virtual IncrModCtlVec_ * newIncrModCtlVec () const =0
virtual IncrEnsCtlVec_ * newIncrEnsCtlVec () const =0
Private Types
using Geometry_ = Geometry< MODEL >
using State4D_ = State4D< MODEL >
using Increment4D_ = Increment4D< MODEL >
using Variables_ = Variables< MODEL >
using Advector_ = AdvectorHandler< MODEL >
using IncrCtlVec_ = IncrCtlVec< MODEL >
using IncrEnsCtlVec_ = IncrEnsCtlVec< MODEL >
using IncrModCtlVec_ = IncrModCtlVec< MODEL >
Private Attributes
std::shared_ptr< Advector_ > adv_
bool isAdvected_
Detailed Description
template<typename MODEL>
class oops::ModelSpaceCovariance4DBase< MODEL >
Abstract base class for model space error covariances.
Definition at line 51 of file ModelSpaceCovariance4DBase.h.
Member Typedef Documentation
Advector_
template<typename MODEL > using oops::ModelSpaceCovariance4DBase< MODEL >::Advector_ = AdvectorHandler<MODEL> private
Definition at line 56 of file ModelSpaceCovariance4DBase.h.
Geometry_
template<typename MODEL > using oops::ModelSpaceCovariance4DBase< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 52 of file ModelSpaceCovariance4DBase.h.
IncrCtlVec_
template<typename MODEL > using oops::ModelSpaceCovariance4DBase< MODEL >::IncrCtlVec_ = IncrCtlVec<MODEL> private
Definition at line 57 of file ModelSpaceCovariance4DBase.h.
Increment4D_
template<typename MODEL > using oops::ModelSpaceCovariance4DBase< MODEL >::Increment4D_ = Increment4D<MODEL> private
Definition at line 54 of file ModelSpaceCovariance4DBase.h.
IncrEnsCtlVec_
template<typename MODEL > using oops::ModelSpaceCovariance4DBase< MODEL >::IncrEnsCtlVec_ = IncrEnsCtlVec<MODEL> private
Definition at line 58 of file ModelSpaceCovariance4DBase.h.
IncrModCtlVec_
template<typename MODEL > using oops::ModelSpaceCovariance4DBase< MODEL >::IncrModCtlVec_ = IncrModCtlVec<MODEL> private
Definition at line 59 of file ModelSpaceCovariance4DBase.h.
State4D_
template<typename MODEL > using oops::ModelSpaceCovariance4DBase< MODEL >::State4D_ = State4D<MODEL> private
Definition at line 53 of file ModelSpaceCovariance4DBase.h.
Variables_
template<typename MODEL > using oops::ModelSpaceCovariance4DBase< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 55 of file ModelSpaceCovariance4DBase.h.
Constructor & Destructor Documentation
ModelSpaceCovariance4DBase()
template<typename MODEL > oops::ModelSpaceCovariance4DBase< MODEL >::ModelSpaceCovariance4DBase (const Geometry_ & , const eckit::Configuration & config) inline
Definition at line 62 of file ModelSpaceCovariance4DBase.h.
                                         : isAdvected_(config.has("advection")) {
     if (isAdvected_) {
       eckit::LocalConfiguration cfgAdv(config, "advection");
       adv_.reset(new Advector_(cfgAdv));
       Advector_::setup(adv_);
     }
   }
References oops::ModelSpaceCovariance4DBase< MODEL >::adv_, oops::ModelSpaceCovariance4DBase< MODEL >::isAdvected_, and oops::AdvectorHandler< MODEL >::setup().
~ModelSpaceCovariance4DBase()
template<typename MODEL > virtual oops::ModelSpaceCovariance4DBase< MODEL >::~ModelSpaceCovariance4DBase () inline virtual
Definition at line 71 of file ModelSpaceCovariance4DBase.h.
{
     if (isAdvected_) {
       std::shared_ptr<Advector_> noadv;
       Advector_::setup(noadv);
     }
   }
References oops::ModelSpaceCovariance4DBase< MODEL >::isAdvected_, and oops::AdvectorHandler< MODEL >::setup().
Member Function Documentation
advectedInverseMultiply()
template<typename MODEL > virtual void oops::ModelSpaceCovariance4DBase< MODEL >::advectedInverseMultiply (const Increment4D_ & , Increment4D_ &) const pure virtual
Implemented in oops::StaticWithTLModelCovariance4D< MODEL >, oops::EnsembleCovariance4DDistributed< MODEL >, oops::EnsembleCovsInterpol4D< MODEL >, oops::EnsembleCovariance4DScaleDependent< MODEL >, oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >, oops::EnsembleCovariance4D< MODEL >, oops::HybridCovariance4D< MODEL >, and oops::StaticCovariance4D< MODEL >.
Referenced by oops::ModelSpaceCovariance4DBase< MODEL >::inverseMultiply().
advectedLinearize() [1/2]
template<typename MODEL > virtual void oops::ModelSpaceCovariance4DBase< MODEL >::advectedLinearize (const State4D_ & , const Geometry_ &) pure virtual
Implemented in oops::StaticWithTLModelCovariance4D< MODEL >, oops::EnsembleCovariance4DDistributed< MODEL >, oops::EnsembleCovsInterpol4D< MODEL >, oops::EnsembleCovariance4DScaleDependent< MODEL >, oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >, oops::EnsembleCovariance4D< MODEL >, oops::HybridCovariance4D< MODEL >, and oops::StaticCovariance4D< MODEL >.
Referenced by oops::ModelSpaceCovariance4DBase< MODEL >::linearize().
advectedLinearize() [2/2]
template<typename MODEL > virtual void oops::ModelSpaceCovariance4DBase< MODEL >::advectedLinearize (const State4D_ & , const Geometry_ & , const eckit::Configuration &) pure virtual
Implemented in oops::StaticWithTLModelCovariance4D< MODEL >, oops::EnsembleCovariance4DDistributed< MODEL >, oops::EnsembleCovsInterpol4D< MODEL >, oops::EnsembleCovariance4DScaleDependent< MODEL >, oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >, oops::EnsembleCovariance4D< MODEL >, oops::HybridCovariance4D< MODEL >, and oops::StaticCovariance4D< MODEL >.
advectedMultiply()
template<typename MODEL > virtual void oops::ModelSpaceCovariance4DBase< MODEL >::advectedMultiply (const Increment4D_ & , Increment4D_ &) const pure virtual
Implemented in oops::StaticWithTLModelCovariance4D< MODEL >, oops::EnsembleCovariance4DDistributed< MODEL >, oops::EnsembleCovsInterpol4D< MODEL >, oops::EnsembleCovariance4DScaleDependent< MODEL >, oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >, oops::EnsembleCovariance4D< MODEL >, oops::HybridCovariance4D< MODEL >, and oops::StaticCovariance4D< MODEL >.
Referenced by oops::ModelSpaceCovariance4DBase< MODEL >::multiply().
advectedMultiplySqrt()
template<typename MODEL > virtual void oops::ModelSpaceCovariance4DBase< MODEL >::advectedMultiplySqrt (const IncrCtlVec_ & , Increment4D_ &) const pure virtual
Implemented in oops::StaticWithTLModelCovariance4D< MODEL >, oops::EnsembleCovariance4DDistributed< MODEL >, oops::EnsembleCovsInterpol4D< MODEL >, oops::EnsembleCovariance4DScaleDependent< MODEL >, oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >, oops::EnsembleCovariance4D< MODEL >, oops::HybridCovariance4D< MODEL >, and oops::StaticCovariance4D< MODEL >.
Referenced by oops::ModelSpaceCovariance4DBase< MODEL >::multiplySqrt().
advectedMultiplySqrtTrans()
template<typename MODEL > virtual void oops::ModelSpaceCovariance4DBase< MODEL >::advectedMultiplySqrtTrans (const Increment4D_ & , IncrCtlVec_ &) const pure virtual
Implemented in oops::StaticWithTLModelCovariance4D< MODEL >, oops::EnsembleCovariance4DDistributed< MODEL >, oops::EnsembleCovsInterpol4D< MODEL >, oops::EnsembleCovariance4DScaleDependent< MODEL >, oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >, oops::EnsembleCovariance4D< MODEL >, oops::HybridCovariance4D< MODEL >, and oops::StaticCovariance4D< MODEL >.
Referenced by oops::ModelSpaceCovariance4DBase< MODEL >::multiplySqrtTrans().
covar()
template<typename MODEL > virtual const ModelSpaceCovarianceBase<MODEL>& oops::ModelSpaceCovariance4DBase< MODEL >::covar () const pure virtual
Implemented in oops::StaticWithTLModelCovariance4D< MODEL >, oops::EnsembleCovariance4DDistributed< MODEL >, oops::EnsembleCovsInterpol4D< MODEL >, oops::EnsembleCovariance4DScaleDependent< MODEL >, oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >, oops::EnsembleCovariance4D< MODEL >, oops::HybridCovariance4D< MODEL >, and oops::StaticCovariance4D< MODEL >.
inverseMultiply()
template<typename MODEL > void oops::ModelSpaceCovariance4DBase< MODEL >::inverseMultiply (const Increment4D_ & dxi, Increment4D_ & dxo) const inline
Definition at line 113 of file ModelSpaceCovariance4DBase.h.
{
     Increment4D_ dxadv(dxi);
     if (isAdvected_) adv_->mult_ad(dxi, dxadv);
     advectedInverseMultiply(dxadv, dxo);
     if (isAdvected_) adv_->mult(dxo, dxo);
   }
References oops::ModelSpaceCovariance4DBase< MODEL >::adv_, oops::ModelSpaceCovariance4DBase< MODEL >::advectedInverseMultiply(), and oops::ModelSpaceCovariance4DBase< MODEL >::isAdvected_.
linearize() [1/2]
template<typename MODEL > void oops::ModelSpaceCovariance4DBase< MODEL >::linearize (const State4D_ & xb, const Geometry_ & resol) inline
Definition at line 78 of file ModelSpaceCovariance4DBase.h.
{
     advectedLinearize(xb, resol);
   }
References oops::ModelSpaceCovariance4DBase< MODEL >::advectedLinearize().
linearize() [2/2]
template<typename MODEL > void oops::ModelSpaceCovariance4DBase< MODEL >::linearize (const State4D_ & xb, const Geometry_ & resol, const eckit::Configuration & config) inline
Definition at line 81 of file ModelSpaceCovariance4DBase.h.
{
     advectedLinearize(xb, resol, config);
   }
References oops::ModelSpaceCovariance4DBase< MODEL >::advectedLinearize().
multiply()
template<typename MODEL > virtual void oops::ModelSpaceCovariance4DBase< MODEL >::multiply (const Increment4D_ & dxi, Increment4D_ & dxo) const inline virtual
Definition at line 85 of file ModelSpaceCovariance4DBase.h.
{
     if (isAdvected_) {
       Increment4D_ dxadv(dxi);
       adv_->mult_ad(dxi, dxadv);
       advectedMultiply(dxadv, dxo);
       adv_->mult(dxo, dxo);
     }
     else {
       advectedMultiply(dxi, dxo);
     }
   }
References oops::ModelSpaceCovariance4DBase< MODEL >::adv_, oops::ModelSpaceCovariance4DBase< MODEL >::advectedMultiply(), and oops::ModelSpaceCovariance4DBase< MODEL >::isAdvected_.
multiplySqrt()
template<typename MODEL > virtual void oops::ModelSpaceCovariance4DBase< MODEL >::multiplySqrt (const IncrCtlVec_ & dvi, Increment4D_ & dxo) const inline virtual
Definition at line 97 of file ModelSpaceCovariance4DBase.h.
{
     advectedMultiplySqrt(dvi, dxo);
     if (isAdvected_) adv_->mult(dxo, dxo);
   }
References oops::ModelSpaceCovariance4DBase< MODEL >::adv_, oops::ModelSpaceCovariance4DBase< MODEL >::advectedMultiplySqrt(), and oops::ModelSpaceCovariance4DBase< MODEL >::isAdvected_.
multiplySqrtTrans()
template<typename MODEL > virtual void oops::ModelSpaceCovariance4DBase< MODEL >::multiplySqrtTrans (const Increment4D_ & dxi, IncrCtlVec_ & dvo) const inline virtual
Definition at line 102 of file ModelSpaceCovariance4DBase.h.
{
     if (isAdvected_) {
       Increment4D_ dxadv(dxi);
       adv_->mult_ad(dxi, dxadv);
       advectedMultiplySqrtTrans(dxadv, dvo);
     }
     else {
       advectedMultiplySqrtTrans(dxi, dvo);
     }
   }
References oops::ModelSpaceCovariance4DBase< MODEL >::adv_, oops::ModelSpaceCovariance4DBase< MODEL >::advectedMultiplySqrtTrans(), and oops::ModelSpaceCovariance4DBase< MODEL >::isAdvected_.
newIncrEnsCtlVec()
template<typename MODEL > virtual IncrEnsCtlVec_* oops::ModelSpaceCovariance4DBase< MODEL >::newIncrEnsCtlVec () const pure virtual
Implemented in oops::EnsembleCovariance4DDistributed< MODEL >, oops::EnsembleCovsInterpol4D< MODEL >, oops::EnsembleCovariance4DScaleDependent< MODEL >, oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >, oops::EnsembleCovariance4D< MODEL >, oops::HybridCovariance4D< MODEL >, oops::StaticWithTLModelCovariance4D< MODEL >, and oops::StaticCovariance4D< MODEL >.
newIncrModCtlVec()
template<typename MODEL > virtual IncrModCtlVec_* oops::ModelSpaceCovariance4DBase< MODEL >::newIncrModCtlVec () const pure virtual
Implemented in oops::EnsembleCovariance4DDistributed< MODEL >, oops::EnsembleCovsInterpol4D< MODEL >, oops::EnsembleCovariance4DScaleDependent< MODEL >, oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >, oops::EnsembleCovariance4D< MODEL >, oops::HybridCovariance4D< MODEL >, oops::StaticWithTLModelCovariance4D< MODEL >, and oops::StaticCovariance4D< MODEL >.
randomize()
template<typename MODEL > virtual void oops::ModelSpaceCovariance4DBase< MODEL >::randomize (Increment4D_ &) const inline virtual
Definition at line 120 of file ModelSpaceCovariance4DBase.h.
 {}
Member Data Documentation
adv_
template<typename MODEL > std::shared_ptr<Advector_> oops::ModelSpaceCovariance4DBase< MODEL >::adv_ private
Definition at line 138 of file ModelSpaceCovariance4DBase.h.
Referenced by oops::ModelSpaceCovariance4DBase< MODEL >::inverseMultiply(), oops::ModelSpaceCovariance4DBase< MODEL >::ModelSpaceCovariance4DBase(), oops::ModelSpaceCovariance4DBase< MODEL >::multiply(), oops::ModelSpaceCovariance4DBase< MODEL >::multiplySqrt(), and oops::ModelSpaceCovariance4DBase< MODEL >::multiplySqrtTrans().
isAdvected_
template<typename MODEL > bool oops::ModelSpaceCovariance4DBase< MODEL >::isAdvected_ private
Definition at line 139 of file ModelSpaceCovariance4DBase.h.
Referenced by oops::ModelSpaceCovariance4DBase< MODEL >::inverseMultiply(), oops::ModelSpaceCovariance4DBase< MODEL >::ModelSpaceCovariance4DBase(), oops::ModelSpaceCovariance4DBase< MODEL >::multiply(), oops::ModelSpaceCovariance4DBase< MODEL >::multiplySqrt(), oops::ModelSpaceCovariance4DBase< MODEL >::multiplySqrtTrans(), and oops::ModelSpaceCovariance4DBase< MODEL >::~ModelSpaceCovariance4DBase().
The documentation for this class was generated from the following file:
src/oops/base/ModelSpaceCovariance4DBase.h