OOPS Documentation: oops::ControlIncrement< MODEL > Class Template Reference
oops::ControlIncrement< MODEL > Class Template Reference
Control Increment.
#include <ControlIncrement.h>
Public Member Functions
ControlIncrement (const JbTotal_ &)
Constructor (using the B matrix to define shape/components)
ControlIncrement (const ControlIncrement &, const bool copy=true)
Copy constructor.
ControlIncrement (const ControlIncrement &, const eckit::Configuration &)
Copy constructor with additional configuration.
ControlIncrement (const Geometry_ &, const ControlIncrement &)
Copy constructor with interpolation.
~ControlIncrement ()
Destructor.
void zero ()
\(dx_1 = 0 \)
ControlIncrement & operator= (const ControlIncrement &)
\(dx_1 = dx_2 \)
ControlIncrement & operator+= (const ControlIncrement &)
\(dx_1 = dx_1 + dx_2 \)
ControlIncrement & operator-= (const ControlIncrement &)
\(dx_1 = dx_1 - dx_2 \)
ControlIncrement & operator*= (const double)
\(dx_1 = dx_1 * c \)
void axpy (const double, const ControlIncrement &)
\(dx_1 = dx_1 * c dx_2 \)
double dot_product_with (const ControlIncrement &) const
\(<dx_1,dx_1> = dx_1^T dx_1 \)
void read (const eckit::Configuration &)
Read control increment.
void write (const eckit::Configuration &) const
Write control increment.
Geometry_ geometry () const
Get geometry.
Increment4D_ & state ()
Get state control increment.
const Increment4D_ & state () const
Get constant state control increment.
ModelAuxIncr_ & modVar ()
Get augmented model control increment.
const ModelAuxIncr_ & modVar () const
Get constant augmented model control increment.
ObsAuxIncrs_ & obsVar ()
Get augmented observation control increment.
const ObsAuxIncrs_ & obsVar () const
Get constant augmented observation control increment.
Static Public Member Functions
static const std::string classname ()
Private Types
using JbTotal_ = CostJbTotal< MODEL >
using Geometry_ = Geometry< MODEL >
using Increment4D_ = Increment4D< MODEL >
using ModelAuxIncr_ = ModelAuxIncrement< MODEL >
using ObsAuxIncrs_ = ObsAuxIncrements< MODEL >
Private Member Functions
void print (std::ostream &) const
Private Attributes
Increment4D_ incrm4d_
4D increment component
ModelAuxIncr_ modbias_
Auxiliary model space component.
ObsAuxIncrs_ obsbias_
Auxiliary observation space component.
Detailed Description
template<typename MODEL>
class oops::ControlIncrement< MODEL >
Control Increment.
The control variable acts as a container for the inputs of the variational data assimilation cost functions in physical space. That includes the states at the start the assimilation window or of each sub-window but also additional variables such as model bias, VarBC coefficients, or other control variables for algorithms that use them. The control variable increment contains variations of the control variable.
The control increment \(dx \) has the following structure
\[ dx = \begin{bmatrix} dx_{state4D} \\ dx_{modaux} \\ dx_{obsaux} \end{bmatrix} \]
where
\[ dx_{state4D} = \begin{bmatrix} dx^0 \\ dx^1 \\ .. \\ dx^N \end{bmatrix} \]
and \f$ N \f$ is the number of sub-windows.
 ->  \f$ dx_{state4D} \f$ is implemented by Increment4D containing a vector
    of Increment objects
\f[  dx_{modaux} = \begin{bmatrix} dx_{modaux}^0 \end{bmatrix} \f]
 ->  \f$ dx_{modaux} \f$ is implemented by ModelAuxIncrement
\f[
     dx_{obsaux} = \begin{bmatrix} dx_{obsaux}^0 \\ dx_{obsaux}^1 \\
                                    ..           \\ dx_{obsaux}^K
                   \end{bmatrix}
\f]
 ->  \f$ dx_{obsaux} \f$ is implemented by ObsAuxIncrements which contains
    a vector of ObsAuxIncrement objects (\f$ dx_{obsaux}^i \f$), which in
    turn contain a map of ObsAuxIncrementBase objects
    (e.g \f$ dx_{VarBC}, dx_{TOVSCV} \f$):
 \f[
   dx_{obsaux}^i = \begin{bmatrix} dx_{obsaux,i}^0 \\
                            ..  \\ dx_{obsaux,i}^L
                  \end{bmatrix}
 \f]
 ->  IFS: K=0, L=1:
 \f[
   dx_{obsaux}= \begin{bmatrix}
                 \begin{bmatrix}
                  dx_{VarBC} \\ dx_{TOVSCV}
                 \end{bmatrix}
                \end{bmatrix}
 \f]
Definition at line 97 of file ControlIncrement.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::ControlIncrement< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 100 of file ControlIncrement.h.
Increment4D_
template<typename MODEL > using oops::ControlIncrement< MODEL >::Increment4D_ = Increment4D<MODEL> private
Definition at line 101 of file ControlIncrement.h.
JbTotal_
template<typename MODEL > using oops::ControlIncrement< MODEL >::JbTotal_ = CostJbTotal<MODEL> private
Definition at line 99 of file ControlIncrement.h.
ModelAuxIncr_
template<typename MODEL > using oops::ControlIncrement< MODEL >::ModelAuxIncr_ = ModelAuxIncrement<MODEL> private
Definition at line 102 of file ControlIncrement.h.
ObsAuxIncrs_
template<typename MODEL > using oops::ControlIncrement< MODEL >::ObsAuxIncrs_ = ObsAuxIncrements<MODEL> private
Definition at line 103 of file ControlIncrement.h.
Constructor & Destructor Documentation
ControlIncrement() [1/4]
template<typename MODEL > oops::ControlIncrement< MODEL >::ControlIncrement (const JbTotal_ & jb) explicit
Constructor (using the B matrix to define shape/components)
Definition at line 170 of file ControlIncrement.h.
     : incrm4d_(jb.jbState()),
       modbias_(jb.resolution(), jb.jbModBias().config()),
       obsbias_(jb.jbObsBias().obspaces(), jb.jbObsBias().config()) {
   Log::trace() << "ControlIncrement:ControlIncrement created." << std::endl;
 }
ControlIncrement() [2/4]
template<typename MODEL > oops::ControlIncrement< MODEL >::ControlIncrement (const ControlIncrement< MODEL > & other, const bool copy = true)
Copy constructor.
Definition at line 178 of file ControlIncrement.h.
     : incrm4d_(other.incrm4d_, copy),
       modbias_(other.modbias_, copy),
       obsbias_(other.obsbias_, copy) {
   Log::trace() << "ControlIncrement:ControlIncrement copied." << std::endl;
 }
ControlIncrement() [3/4]
template<typename MODEL > oops::ControlIncrement< MODEL >::ControlIncrement (const ControlIncrement< MODEL > & other, const eckit::Configuration & tlConf)
Copy constructor with additional configuration.
Definition at line 187 of file ControlIncrement.h.
     : incrm4d_(other.incrm4d_, tlConf),
       modbias_(other.modbias_, tlConf),
       obsbias_(other.obsbias_, tlConf) {
   Log::trace() << "ControlIncrement:ControlIncrement copied." << std::endl;
 }
ControlIncrement() [4/4]
template<typename MODEL > oops::ControlIncrement< MODEL >::ControlIncrement (const Geometry_ & geom, const ControlIncrement< MODEL > & other)
Copy constructor with interpolation.
Definition at line 196 of file ControlIncrement.h.
     : incrm4d_(geom, other.incrm4d_),
       modbias_(other.modbias_, true),
       obsbias_(other.obsbias_, true) {
   Log::trace() << "ControlIncrement:ControlIncrement copied." << std::endl;
 }
~ControlIncrement()
template<typename MODEL > oops::ControlIncrement< MODEL >::~ControlIncrement
Destructor.
Definition at line 205 of file ControlIncrement.h.
 {}
Member Function Documentation
axpy()
template<typename MODEL > void oops::ControlIncrement< MODEL >::axpy (const double zz, const ControlIncrement< MODEL > & rhs)
\(dx_1 = dx_1 * c dx_2 \)
Definition at line 250 of file ControlIncrement.h.
{
   incrm4d_.axpy(zz, rhs.incrm4d_);
   modbias_.axpy(zz, rhs.modbias_);
   obsbias_.axpy(zz, rhs.obsbias_);
 }
References oops::ControlIncrement< MODEL >::incrm4d_, oops::ControlIncrement< MODEL >::modbias_, and oops::ControlIncrement< MODEL >::obsbias_.
Referenced by oops::DualMinimizer< MODEL >::doMinimize(), oops::SaddlePointLMPMatrix< MODEL >::Rmultiply(), oops::DRPFOMMinimizer< MODEL >::solve(), oops::DRPLanczosMinimizer< MODEL >::solve(), oops::DRIPCGMinimizer< MODEL >::solve(), oops::DRGMRESRMinimizer< MODEL >::solve(), and oops::DRPCGMinimizer< MODEL >::solve().
classname()
template<typename MODEL > static const std::string oops::ControlIncrement< MODEL >::classname () inline static
Definition at line 106 of file ControlIncrement.h.
 { return "oops::ControlIncrement"; }
dot_product_with()
template<typename MODEL > double oops::ControlIncrement< MODEL >::dot_product_with (const ControlIncrement< MODEL > & x2) const
\(<dx_1,dx_1> = dx_1^T dx_1 \)
Definition at line 279 of file ControlIncrement.h.
{
   double zz = 0.0;
   zz += dot_product(incrm4d_, x2.incrm4d_);
   zz += dot_product(modbias_, x2.modbias_);
   zz += dot_product(obsbias_, x2.obsbias_);
   return zz;
 }
References dot_product(), oops::ControlIncrement< MODEL >::incrm4d_, oops::ControlIncrement< MODEL >::modbias_, and oops::ControlIncrement< MODEL >::obsbias_.
geometry()
template<typename MODEL > Geometry_ oops::ControlIncrement< MODEL >::geometry () const inline
Get geometry.
Definition at line 142 of file ControlIncrement.h.
 { return incrm4d_.geometry(); }
References oops::Increment4D< MODEL >::geometry(), and oops::ControlIncrement< MODEL >::incrm4d_.
Referenced by oops::DRMinimizer< MODEL >::doMinimize().
modVar() [1/2]
template<typename MODEL > ModelAuxIncr_& oops::ControlIncrement< MODEL >::modVar () inline
Get augmented model control increment.
Definition at line 150 of file ControlIncrement.h.
 { return modbias_; }
References oops::ControlIncrement< MODEL >::modbias_.
Referenced by oops::CostJbTotal< MODEL >::addGradientFG(), oops::CostFctWeak< MODEL >::addIncr(), oops::CostFunction< MODEL >::addIncrement(), oops::CostJbTotal< MODEL >::evaluate(), oops::CostJbTotal< MODEL >::finalize(), oops::BMatrix< MODEL >::multiplyB(), oops::CostJbTotal< MODEL >::multiplyB(), oops::CostJbTotal< MODEL >::multiplyBinv(), oops::CostJbTotal< MODEL >::multiplyBsqrt(), oops::CostJbTotal< MODEL >::multiplyBsqrtTrans(), oops::BMatrix< MODEL >::multiplyId(), oops::CostJbTotal< MODEL >::randomize(), oops::CostFct3DVar< MODEL >::runAD(), oops::CostFctWeak< MODEL >::runAD(), oops::CostFct4DVar< MODEL >::runAD(), oops::CostFct4DVarHyb4D< MODEL >::runAD(), oops::CostFct4DEnsVar< MODEL >::runAD(), oops::CostFct4DEnVar< MODEL >::runAD(), oops::CostFct4DVarMF< MODEL >::runAD(), oops::CostFct3DVar< MODEL >::runTL(), oops::CostFct4DVarHyb4D< MODEL >::runTL(), oops::CostFctWeak< MODEL >::runTL(), oops::CostFct4DVar< MODEL >::runTL(), oops::CostFct4DEnsVar< MODEL >::runTL(), oops::CostFct4DEnVar< MODEL >::runTL(), oops::CostFct4DVarMF< MODEL >::runTL(), oops::CostJbTotal< MODEL >::writeIncrement(), oops::CostFct3DVar< MODEL >::zeroAD(), oops::CostFct4DVar< MODEL >::zeroAD(), oops::CostFctWeak< MODEL >::zeroAD(), oops::CostFct4DVarHyb4D< MODEL >::zeroAD(), oops::CostFct4DEnsVar< MODEL >::zeroAD(), oops::CostFct4DEnVar< MODEL >::zeroAD(), and oops::CostFct4DVarMF< MODEL >::zeroAD().
modVar() [2/2]
template<typename MODEL > const ModelAuxIncr_& oops::ControlIncrement< MODEL >::modVar () const inline
Get constant augmented model control increment.
Definition at line 152 of file ControlIncrement.h.
 { return modbias_; }
References oops::ControlIncrement< MODEL >::modbias_.
obsVar() [1/2]
template<typename MODEL > ObsAuxIncrs_& oops::ControlIncrement< MODEL >::obsVar () inline
Get augmented observation control increment.
Definition at line 155 of file ControlIncrement.h.
 { return obsbias_; }
References oops::ControlIncrement< MODEL >::obsbias_.
Referenced by oops::CostJbTotal< MODEL >::addGradientFG(), oops::CostFunction< MODEL >::addIncrement(), oops::CostJbTotal< MODEL >::evaluate(), oops::CostJbTotal< MODEL >::finalize(), oops::BMatrix< MODEL >::multiplyB(), oops::CostJbTotal< MODEL >::multiplyB(), oops::CostJbTotal< MODEL >::multiplyBinv(), oops::CostJbTotal< MODEL >::multiplyBsqrt(), oops::CostJbTotal< MODEL >::multiplyBsqrtTrans(), oops::BMatrix< MODEL >::multiplyId(), oops::CostJbTotal< MODEL >::randomize(), oops::CostJo< MODEL >::setupAD(), oops::CostJo< MODEL >::setupTL(), oops::CostJbTotal< MODEL >::writeIncrement(), oops::CostFct3DVar< MODEL >::zeroAD(), oops::CostFctWeak< MODEL >::zeroAD(), oops::CostFct4DVar< MODEL >::zeroAD(), oops::CostFct4DVarHyb4D< MODEL >::zeroAD(), oops::CostFct4DEnsVar< MODEL >::zeroAD(), oops::CostFct4DEnVar< MODEL >::zeroAD(), and oops::CostFct4DVarMF< MODEL >::zeroAD().
obsVar() [2/2]
template<typename MODEL > const ObsAuxIncrs_& oops::ControlIncrement< MODEL >::obsVar () const inline
Get constant augmented observation control increment.
Definition at line 157 of file ControlIncrement.h.
 { return obsbias_; }
References oops::ControlIncrement< MODEL >::obsbias_.
operator*=()
template<typename MODEL > ControlIncrement< MODEL > & oops::ControlIncrement< MODEL >::operator*= (const double zz)
\(dx_1 = dx_1 * c \)
Definition at line 235 of file ControlIncrement.h.
{
   incrm4d_ *= zz;
   modbias_ *= zz;
   obsbias_ *= zz;
   return *this;
 }
operator+=()
template<typename MODEL > ControlIncrement< MODEL > & oops::ControlIncrement< MODEL >::operator+= (const ControlIncrement< MODEL > & rhs)
\(dx_1 = dx_1 + dx_2 \)
Definition at line 217 of file ControlIncrement.h.
{
   incrm4d_ += rhs.incrm4d_;
   modbias_ += rhs.modbias_;
   obsbias_ += rhs.obsbias_;
   return *this;
 }
References oops::ControlIncrement< MODEL >::incrm4d_, oops::ControlIncrement< MODEL >::modbias_, and oops::ControlIncrement< MODEL >::obsbias_.
operator-=()
template<typename MODEL > ControlIncrement< MODEL > & oops::ControlIncrement< MODEL >::operator-= (const ControlIncrement< MODEL > & rhs)
\(dx_1 = dx_1 - dx_2 \)
Definition at line 226 of file ControlIncrement.h.
{
   incrm4d_ -= rhs.incrm4d_;
   modbias_ -= rhs.modbias_;
   obsbias_ -= rhs.obsbias_;
   return *this;
 }
References oops::ControlIncrement< MODEL >::incrm4d_, oops::ControlIncrement< MODEL >::modbias_, and oops::ControlIncrement< MODEL >::obsbias_.
operator=()
template<typename MODEL > ControlIncrement< MODEL > & oops::ControlIncrement< MODEL >::operator= (const ControlIncrement< MODEL > & rhs)
\(dx_1 = dx_2 \)
Definition at line 208 of file ControlIncrement.h.
{
   incrm4d_ = rhs.incrm4d_;
   modbias_ = rhs.modbias_;
   obsbias_ = rhs.obsbias_;
   return *this;
 }
References oops::ControlIncrement< MODEL >::incrm4d_, oops::ControlIncrement< MODEL >::modbias_, and oops::ControlIncrement< MODEL >::obsbias_.
print()
template<typename MODEL > void oops::ControlIncrement< MODEL >::print (std::ostream & outs) const private
Definition at line 272 of file ControlIncrement.h.
{
   outs << incrm4d_;
   outs << modbias_;
   outs << obsbias_;
 }
read()
template<typename MODEL > void oops::ControlIncrement< MODEL >::read (const eckit::Configuration & config)
Read control increment.
Definition at line 258 of file ControlIncrement.h.
{
   if (config.has("increment")) incrm4d_.read(config);
   if (config.has("incrementModAux")) modbias_.read(config);
   if (config.has("incrementsObsAux")) obsbias_.read(config);
 }
Referenced by oops::DRMinimizer< MODEL >::restart().
state() [1/2]
template<typename MODEL > Increment4D_& oops::ControlIncrement< MODEL >::state () inline
Get state control increment.
Definition at line 145 of file ControlIncrement.h.
 { return incrm4d_; }
References oops::ControlIncrement< MODEL >::incrm4d_.
Referenced by oops::CostJbTotal< MODEL >::addGradientFG(), oops::CostFct3DVar< MODEL >::addIncr(), oops::CostFct4DVar< MODEL >::addIncr(), oops::CostFctWeak< MODEL >::addIncr(), oops::CostFct4DEnsVar< MODEL >::addIncr(), oops::CostFct4DEnVar< MODEL >::addIncr(), oops::CostFct4DVarTrajHR< MODEL >::addIncr(), oops::CostFct4DVarMF< MODEL >::addIncr(), oops::Minimizer< MODEL >::adjModelTest(), oops::CostJbTotal< MODEL >::evaluate(), oops::CostJbTotal< MODEL >::finalize(), oops::CostJbTotal< MODEL >::finalizeTL(), oops::CostJbTotal< MODEL >::initializeAD(), oops::BMatrix< MODEL >::multiplyB(), oops::CostJbTotal< MODEL >::multiplyB(), oops::CostJbTotal< MODEL >::multiplyBinv(), oops::CostJbTotal< MODEL >::multiplyBsqrt(), oops::CostJbTotal< MODEL >::multiplyBsqrtTrans(), oops::BMatrix< MODEL >::multiplyId(), oops::CostJbTotal< MODEL >::randomize(), oops::CostFct3DVar< MODEL >::runAD(), oops::CostFctWeak< MODEL >::runAD(), oops::CostFct4DVar< MODEL >::runAD(), oops::CostFct4DVarHyb4D< MODEL >::runAD(), oops::CostFct4DEnsVar< MODEL >::runAD(), oops::CostFct4DEnVar< MODEL >::runAD(), oops::CostFct4DVarMF< MODEL >::runAD(), oops::CostFct3DVar< MODEL >::runTL(), oops::CostFct4DVarHyb4D< MODEL >::runTL(), oops::CostFct4DVar< MODEL >::runTL(), oops::CostFctWeak< MODEL >::runTL(), oops::CostFct4DEnsVar< MODEL >::runTL(), oops::CostFct4DEnVar< MODEL >::runTL(), oops::CostFct4DVarMF< MODEL >::runTL(), oops::Minimizer< MODEL >::tlmTaylorTest(), oops::CostJbTotal< MODEL >::writeIncrement(), oops::CostFct3DVar< MODEL >::zeroAD(), oops::CostFct4DVar< MODEL >::zeroAD(), oops::CostFctWeak< MODEL >::zeroAD(), oops::CostFct4DVarHyb4D< MODEL >::zeroAD(), oops::CostFct4DEnsVar< MODEL >::zeroAD(), oops::CostFct4DEnVar< MODEL >::zeroAD(), and oops::CostFct4DVarMF< MODEL >::zeroAD().
state() [2/2]
template<typename MODEL > const Increment4D_& oops::ControlIncrement< MODEL >::state () const inline
Get constant state control increment.
Definition at line 147 of file ControlIncrement.h.
 { return incrm4d_; }
References oops::ControlIncrement< MODEL >::incrm4d_.
write()
template<typename MODEL > void oops::ControlIncrement< MODEL >::write (const eckit::Configuration & config) const
Write control increment.
Definition at line 265 of file ControlIncrement.h.
{
   if (config.has("increment")) incrm4d_.write(config);
   if (config.has("incrementModAux")) modbias_.write(config);
   if (config.has("incrementsObsAux")) obsbias_.write(config);
 }
zero()
template<typename MODEL > void oops::ControlIncrement< MODEL >::zero
\(dx_1 = 0 \)
Definition at line 243 of file ControlIncrement.h.
{
   incrm4d_.zero();
   modbias_.zero();
   obsbias_.zero();
 }
Referenced by oops::HessianMatrix< MODEL >::multiply(), oops::LBHessianMatrix< MODEL >::multiply(), oops::SaddlePointLMPMatrix< MODEL >::Rmultiply(), oops::LBGMRESRMinimizer< MODEL >::solve(), oops::DRPLanczosMinimizer< MODEL >::solve(), and oops::DRPCGMinimizer< MODEL >::solve().
Member Data Documentation
incrm4d_
template<typename MODEL > Increment4D_ oops::ControlIncrement< MODEL >::incrm4d_ private
4D increment component
Definition at line 162 of file ControlIncrement.h.
Referenced by oops::ControlIncrement< MODEL >::axpy(), oops::ControlIncrement< MODEL >::dot_product_with(), oops::ControlIncrement< MODEL >::geometry(), oops::ControlIncrement< MODEL >::operator+=(), oops::ControlIncrement< MODEL >::operator-=(), oops::ControlIncrement< MODEL >::operator=(), and oops::ControlIncrement< MODEL >::state().
modbias_
template<typename MODEL > ModelAuxIncr_ oops::ControlIncrement< MODEL >::modbias_ private
Auxiliary model space component.
Definition at line 163 of file ControlIncrement.h.
Referenced by oops::ControlIncrement< MODEL >::axpy(), oops::ControlIncrement< MODEL >::dot_product_with(), oops::ControlIncrement< MODEL >::modVar(), oops::ControlIncrement< MODEL >::operator+=(), oops::ControlIncrement< MODEL >::operator-=(), and oops::ControlIncrement< MODEL >::operator=().
obsbias_
template<typename MODEL > ObsAuxIncrs_ oops::ControlIncrement< MODEL >::obsbias_ private
Auxiliary observation space component.
Definition at line 164 of file ControlIncrement.h.
Referenced by oops::ControlIncrement< MODEL >::axpy(), oops::ControlIncrement< MODEL >::dot_product_with(), oops::ControlIncrement< MODEL >::obsVar(), oops::ControlIncrement< MODEL >::operator+=(), oops::ControlIncrement< MODEL >::operator-=(), and oops::ControlIncrement< MODEL >::operator=().
The documentation for this class was generated from the following file:
src/oops/assimilation/ControlIncrement.h