OOPS Documentation: oops::CostFct3DVar< MODEL > Class Template Reference
oops::CostFct3DVar< MODEL > Class Template Reference
3D-Var Cost Function
#include <CostFct3DVar.h>
Public Member Functions
CostFct3DVar (const eckit::Configuration &, const Geometry_ &, const Model_ &)
~CostFct3DVar ()
void runTL (CtrlInc_ &, PostProcessorTL< Increment_ > &, PostProcessor< Increment_ >, const bool idModel=false) const override
Run the tangent linear model (virtual method)
void runAD (CtrlInc_ &, PostProcessorAD< Increment_ > &, PostProcessor< Increment_ >, const bool idModel=false) const override
Run the adjoint model (virtual method)
void zeroAD (CtrlInc_ &) const override
Nullify the increment prior to running the adjoint model (virtual method)
void runNL (CtrlVar_ &, PostProcessor< State_ > &) const override
Run the non-linear model (virtual method)
Public Member Functions inherited from oops::CostFunction< MODEL >
CostFunction (const eckit::Configuration &, const Geometry_ &, const Model_ &)
Construct a cost function.
virtual ~CostFunction ()
Destroy a cost function.
virtual double evaluate (const CtrlVar_ &, const eckit::Configuration &config=eckit::LocalConfiguration(), PostProcessor< State_ > post=PostProcessor< State_ >()) const
Evaluate the non-linear cost function.
virtual double linearize (const CtrlVar_ &, const eckit::Configuration &, PostProcessor< State_ > post=PostProcessor< State_ >())
Linearise the cost function: set up the quadratic cost function.
virtual void runNL (CtrlVar_ &xx, const Model_ &, PostProcessor< State_ > &pp)
Run the non-linear model (virtual method)
void addIncrement (CtrlVar_ &, const CtrlInc_ &, PostProcessor< Increment_ > post=PostProcessor< Increment_ >()) const
Add increment to the first guess.
void resetLinearization ()
Rest the quadratic cost function.
void computeGradientFG (CtrlInc_ &) const
Compute the cost function gradient at first guess (without Jb)
double computeGradientFG (const CtrlVec_ &, CtrlInc_ &) const
Compute the cost function gradient at first guess (without Jb)
void checkpoint (eckit::LocalConfiguration &) const
Checkpoint.
void restart (const eckit::Configuration &)
Restart.
const JbTotal_ & jb () const
Access \(J_b\).
const CostBase_ & jterm (const unsigned ii) const
Access terms of the cost function other than \(J_b\).
unsigned nterms () const
Return the numer of other cost function terms \(J_o, J_c, ..\).
virtual const double & getCostJb () const
Get the Jb cost function value.
virtual const double & getCostJoJc () const
Get the JoJc cost function value.
Private Types
using Increment_ = Increment< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using CtrlVar_ = ControlVariable< MODEL >
using CostFct_ = CostFunction< MODEL >
using Geometry_ = Geometry< MODEL >
using State_ = State< MODEL >
using Model_ = Model< MODEL >
using Variables_ = Variables< MODEL >
Private Member Functions
void addIncr (CtrlVar_ &, const CtrlInc_ &, PostProcessor< Increment_ > &) const override
Virtual method to add the increment to the state.
CostJb3D< MODEL > * newJb (const eckit::Configuration &, const Geometry_ &, const CtrlVar_ &) const override
Create the \(J_b, J_q\) term of the cost function (virtual method)
CostJo< MODEL > * newJo (const eckit::Configuration &) const override
Create the \(J_o\) term of the cost function (virtual method)
CostTermBase< MODEL > * newJc (const eckit::Configuration &, const Geometry_ &) const override
Create other terms of the cost function \(J_c, ..\) (virtual method)
Private Attributes
util::Duration windowLength_
util::DateTime windowBegin_
util::DateTime windowEnd_
util::DateTime windowHalf_
util::Duration zero_
const Geometry_ & geom_
const Variables_ ctlvars_
Additional Inherited Members
Static Public Member Functions inherited from oops::CostFunction< MODEL >
static const std::string classname ()
Protected Member Functions inherited from oops::CostFunction< MODEL >
void setupTerms (const eckit::Configuration &)
Set up terms of the cost function \(J_b, J_q, J_o, J_c, ..\).
const Model_ & getModel () const
Access the non-linear model.
const LinearModel_ & getTLM (const unsigned isub=0) const
Access the linear model.
void recentreBackground (const eckit::Configuration &)
Re-centre the background.
CostBase_ & getJterm (const unsigned ii) const
Non const access to JTerms for linearize() method in concrete cost-functions.
JbTotal_ & getJb () const
Non const access to Jb for linearize() method in concrete cost-functions
std::vector< std::unique_ptr< LinearModel_ > > & getTLMs ()
Non const access to TL Model for linearize() method in concrete cost-functions
Detailed Description
template<typename MODEL>
class oops::CostFct3DVar< MODEL >
3D-Var Cost Function
This class is not really necessary since it is only a special case of the more general 4D-Var cost function. It is provided for readability.
Definition at line 45 of file CostFct3DVar.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::CostFct3DVar< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 49 of file CostFct3DVar.h.
CtrlInc_
template<typename MODEL > using oops::CostFct3DVar< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 47 of file CostFct3DVar.h.
CtrlVar_
template<typename MODEL > using oops::CostFct3DVar< MODEL >::CtrlVar_ = ControlVariable<MODEL> private
Definition at line 48 of file CostFct3DVar.h.
Geometry_
template<typename MODEL > using oops::CostFct3DVar< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 50 of file CostFct3DVar.h.
Increment_
template<typename MODEL > using oops::CostFct3DVar< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 46 of file CostFct3DVar.h.
Model_
template<typename MODEL > using oops::CostFct3DVar< MODEL >::Model_ = Model<MODEL> private
Definition at line 52 of file CostFct3DVar.h.
State_
template<typename MODEL > using oops::CostFct3DVar< MODEL >::State_ = State<MODEL> private
Definition at line 51 of file CostFct3DVar.h.
Variables_
template<typename MODEL > using oops::CostFct3DVar< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 53 of file CostFct3DVar.h.
Constructor & Destructor Documentation
CostFct3DVar()
template<typename MODEL > oops::CostFct3DVar< MODEL >::CostFct3DVar (const eckit::Configuration & config, const Geometry_ & geom, const Model_ & model)
Definition at line 91 of file CostFct3DVar.h.
     : CostFunction<MODEL>::CostFunction(config, geom, model),
       windowLength_(),
       windowHalf_(),
       zero_(0),
       geom_(geom),
       ctlvars_(config) {
   windowLength_ = util::Duration(config.getString("window_length"));
   windowBegin_ = util::DateTime(config.getString("window_begin"));
   windowEnd_ = windowBegin_ + windowLength_;
   windowHalf_ = windowBegin_ + windowLength_ / 2;
   this->setupTerms(config);
   Log::trace() << "CostFct3DVar constructed" << std::endl;
 }
References oops::CostFunction< MODEL >::setupTerms(), oops::CostFct3DVar< MODEL >::windowBegin_, oops::CostFct3DVar< MODEL >::windowEnd_, oops::CostFct3DVar< MODEL >::windowHalf_, and oops::CostFct3DVar< MODEL >::windowLength_.
~CostFct3DVar()
template<typename MODEL > oops::CostFct3DVar< MODEL >::~CostFct3DVar () inline
Definition at line 57 of file CostFct3DVar.h.
 {}
Member Function Documentation
addIncr()
template<typename MODEL > void oops::CostFct3DVar< MODEL >::addIncr (CtrlVar_ & , const CtrlInc_ & , PostProcessor< Increment_ > &) const override private virtual
Virtual method to add the increment to the state.
Implements oops::CostFunction< MODEL >.
Definition at line 183 of file CostFct3DVar.h.
{
   ASSERT(xx.state().checkStatesNumber(1));
   ASSERT(xx.state()[0].validTime() == windowHalf_);
   ASSERT(dx.state()[0].validTime() == windowHalf_);
   xx.state()[0] += dx.state()[0];
 }
References oops::State4D< MODEL >::checkStatesNumber(), oops::ControlVariable< MODEL >::state(), and oops::ControlIncrement< MODEL >::state().
newJb()
template<typename MODEL > CostJb3D< MODEL > * oops::CostFct3DVar< MODEL >::newJb (const eckit::Configuration & , const Geometry_ & , const CtrlVar_ &) const override private virtual
Create the \(J_b, J_q\) term of the cost function (virtual method)
Implements oops::CostFunction< MODEL >.
Definition at line 110 of file CostFct3DVar.h.
{
   ASSERT(xb.state().checkStatesNumber(1));
   return new CostJb3D<MODEL>(jbConf, geom, ctlvars_, zero_, xb.state()[0]);
 }
References oops::State4D< MODEL >::checkStatesNumber(), and oops::ControlVariable< MODEL >::state().
newJc()
template<typename MODEL > CostTermBase< MODEL > * oops::CostFct3DVar< MODEL >::newJc (const eckit::Configuration & , const Geometry_ &) const override private virtual
Create other terms of the cost function \(J_c, ..\) (virtual method)
Implements oops::CostFunction< MODEL >.
Definition at line 129 of file CostFct3DVar.h.
{
   // For now there is no Jc that can work with 3D-Var
   CostTermBase<MODEL> *pjc = 0;
   return pjc;
 }
newJo()
template<typename MODEL > CostJo< MODEL > * oops::CostFct3DVar< MODEL >::newJo (const eckit::Configuration &) const override private virtual
Create the \(J_o\) term of the cost function (virtual method)
Implements oops::CostFunction< MODEL >.
Definition at line 120 of file CostFct3DVar.h.
{
   return new CostJo<MODEL>(joConf, geom_, windowBegin_, windowEnd_,
                            util::Duration(0));
 }
runAD()
template<typename MODEL > void oops::CostFct3DVar< MODEL >::runAD (CtrlInc_ & , PostProcessorAD< Increment_ > & , PostProcessor< Increment_ > post, const bool idModel = false) const override virtual
Run the adjoint model (virtual method)
Implements oops::CostFunction< MODEL >.
Definition at line 171 of file CostFct3DVar.h.
{
   ASSERT(dx.state()[0].validTime() == windowHalf_);
   CostFct_::getTLM().forecastAD(dx.state()[0], dx.modVar(), util::Duration(0),
                                 post, cost);
   ASSERT(dx.state()[0].validTime() == windowHalf_);
 }
References oops::ControlIncrement< MODEL >::modVar(), and oops::ControlIncrement< MODEL >::state().
runNL()
template<typename MODEL > void oops::CostFct3DVar< MODEL >::runNL (CtrlVar_ & , PostProcessor< State_ > &) const override virtual
Run the non-linear model (virtual method)
Implements oops::CostFunction< MODEL >.
Definition at line 139 of file CostFct3DVar.h.
{
   ASSERT(xx.state().checkStatesNumber(1));
   ASSERT(xx.state()[0].validTime() == windowHalf_);
   CostFct_::getModel().forecast(xx.state()[0], xx.modVar(), util::Duration(0),
                                 post);
 }
References oops::State4D< MODEL >::checkStatesNumber(), oops::ControlVariable< MODEL >::modVar(), and oops::ControlVariable< MODEL >::state().
runTL()
template<typename MODEL > void oops::CostFct3DVar< MODEL >::runTL (CtrlInc_ & , PostProcessorTL< Increment_ > & , PostProcessor< Increment_ > post, const bool idModel = false) const override virtual
Run the tangent linear model (virtual method)
Implements oops::CostFunction< MODEL >.
Definition at line 150 of file CostFct3DVar.h.
{
   ASSERT(dx.state()[0].validTime() == windowHalf_);
   CostFct_::getTLM().forecastTL(dx.state()[0], dx.modVar(), util::Duration(0),
                                 post, cost);
   ASSERT(dx.state()[0].validTime() == windowHalf_);
 }
References oops::ControlIncrement< MODEL >::modVar(), and oops::ControlIncrement< MODEL >::state().
zeroAD()
template<typename MODEL > void oops::CostFct3DVar< MODEL >::zeroAD (CtrlInc_ &) const override virtual
Nullify the increment prior to running the adjoint model (virtual method)
Implements oops::CostFunction< MODEL >.
Definition at line 162 of file CostFct3DVar.h.
{
   dx.state()[0].zero(windowHalf_);
   dx.modVar().zero();
   dx.obsVar().zero();
 }
References oops::ControlIncrement< MODEL >::modVar(), oops::ControlIncrement< MODEL >::obsVar(), oops::ControlIncrement< MODEL >::state(), oops::ObsAuxIncrements< MODEL >::zero(), oops::ModelAuxIncrement< MODEL >::zero(), and oops::Increment4D< MODEL >::zero().
Member Data Documentation
ctlvars_
template<typename MODEL > const Variables_ oops::CostFct3DVar< MODEL >::ctlvars_ private
Definition at line 85 of file CostFct3DVar.h.
geom_
template<typename MODEL > const Geometry_& oops::CostFct3DVar< MODEL >::geom_ private
Definition at line 84 of file CostFct3DVar.h.
windowBegin_
template<typename MODEL > util::DateTime oops::CostFct3DVar< MODEL >::windowBegin_ private
Definition at line 80 of file CostFct3DVar.h.
Referenced by oops::CostFct3DVar< MODEL >::CostFct3DVar().
windowEnd_
template<typename MODEL > util::DateTime oops::CostFct3DVar< MODEL >::windowEnd_ private
Definition at line 81 of file CostFct3DVar.h.
Referenced by oops::CostFct3DVar< MODEL >::CostFct3DVar().
windowHalf_
template<typename MODEL > util::DateTime oops::CostFct3DVar< MODEL >::windowHalf_ private
Definition at line 82 of file CostFct3DVar.h.
Referenced by oops::CostFct3DVar< MODEL >::CostFct3DVar().
windowLength_
template<typename MODEL > util::Duration oops::CostFct3DVar< MODEL >::windowLength_ private
Definition at line 79 of file CostFct3DVar.h.
Referenced by oops::CostFct3DVar< MODEL >::CostFct3DVar().
zero_
template<typename MODEL > util::Duration oops::CostFct3DVar< MODEL >::zero_ private
Definition at line 83 of file CostFct3DVar.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/CostFct3DVar.h