OOPS Documentation: oops::PostProcessor< FLDS > Class Template Reference
oops::PostProcessor< FLDS > Class Template Reference
Control model post processing.
#include <PostProcessor.h>
Public Member Functions
PostProcessor ()
Constructor.
PostProcessor (const PostProcessor &pp)
Copy constructor.
~PostProcessor ()
Destructor.
void enrollProcessor (PostBase_ *pp)
Adds a post processor to the vector of post-processors.
void enrollProcessor (std::shared_ptr< PostBase_ > pp)
Adds a post processor to the vector of post-processors.
void initialize (const FLDS &xx, const util::DateTime &end, const util::Duration &step)
Calls initialize method of individual processors.
void initialize (FLDS &xx, const util::DateTime &end, const util::Duration &step)
void process (const FLDS &xx)
Calls process method of individual processors.
void process (FLDS &xx)
void finalize (const FLDS &xx)
Calls finalize method of individual processors.
Private Types
using PostBase_ = PostBase< FLDS >
Private Member Functions
PostProcessor operator= (const PostProcessor &)
Private Attributes
std::vector< std::shared_ptr< PostBase_ > > processors_
Vector of shared pointers to individual processors.
Detailed Description
template<typename FLDS>
class oops::PostProcessor< FLDS >
Control model post processing.
Controls model post processing
This class controls model post processing in the most general sense, ie all diagnostics computations that do not affect the model integration. It contains a vector of PostBase objects. It just calls all the individual processors one by one.
Post-processing is organized in three stages/methods: initialize (called prior to time-stepping), process (called during the forecast at each time step) and finalize (called once the time-stepping is finished).
Methods initialize, process and finalize simply call the initialize, process and finalize methods, respectively, of the enrolled individual processors.
See the documentation of PostBase for the details of implementation of processors and the list of available processors.
Definition at line 43 of file PostProcessor.h.
Member Typedef Documentation
PostBase_
template<typename FLDS > using oops::PostProcessor< FLDS >::PostBase_ = PostBase<FLDS> private
Definition at line 44 of file PostProcessor.h.
Constructor & Destructor Documentation
PostProcessor() [1/2]
template<typename FLDS > oops::PostProcessor< FLDS >::PostProcessor () inline
Constructor.
Definition at line 48 of file PostProcessor.h.
 : processors_() {}
PostProcessor() [2/2]
template<typename FLDS > oops::PostProcessor< FLDS >::PostProcessor (const PostProcessor< FLDS > & pp) inline
Copy constructor.
Definition at line 50 of file PostProcessor.h.
 : processors_(pp.processors_) {}
~PostProcessor()
template<typename FLDS > oops::PostProcessor< FLDS >::~PostProcessor () inline
Destructor.
Definition at line 52 of file PostProcessor.h.
 {}
Member Function Documentation
enrollProcessor() [1/2]
template<typename FLDS > void oops::PostProcessor< FLDS >::enrollProcessor (PostBase_ * pp) inline
Adds a post processor to the vector of post-processors.
Definition at line 55 of file PostProcessor.h.
{
     if (pp != 0) {
       std::shared_ptr<PostBase_> sp(pp);
       processors_.push_back(sp);
     }
   }
References oops::PostProcessor< FLDS >::processors_.
Referenced by oops::StaticWithTLModelCovariance4D< MODEL >::advectedLinearize(), oops::IncrementalAssimilation< MODEL >::assimilate(), oops::CostFct4DVarTrajHR< MODEL >::evaluate(), oops::CostFct4DVarMF< MODEL >::evaluate(), oops::CostFunction< MODEL >::evaluate(), oops::DualResForecast< MODEL >::execute(), oops::EnsForecast< MODEL >::execute(), oops::Forecast< MODEL >::execute(), oops::ExternalDFI< MODEL >::execute(), oops::GenEnsPertB< MODEL >::execute(), oops::HofX< MODEL >::execute(), oops::MakeObs< MODEL >::execute(), oops::Variational< MODEL >::execute(), oops::IncrementalAssimilation< MODEL >::late4Dstart(), oops::CostFct4DVarTrajHR< MODEL >::linearize(), oops::CostFct4DVarMF< MODEL >::linearize(), and oops::CostFunction< MODEL >::linearize().
enrollProcessor() [2/2]
template<typename FLDS > void oops::PostProcessor< FLDS >::enrollProcessor (std::shared_ptr< PostBase_ > pp) inline
Adds a post processor to the vector of post-processors.
Definition at line 63 of file PostProcessor.h.
{
     if (pp != 0) processors_.push_back(pp);
   }
References oops::PostProcessor< FLDS >::processors_.
finalize()
template<typename FLDS > void oops::PostProcessor< FLDS >::finalize (const FLDS & xx) inline
Calls finalize method of individual processors.
Definition at line 90 of file PostProcessor.h.
{
     for (std::shared_ptr<PostBase_> jp : processors_) jp->finalize(xx);
   }
References oops::PostProcessor< FLDS >::processors_.
Referenced by oops::Model< MODEL >::forecast(), oops::LinearModel< MODEL >::forecastAD(), oops::LinearModel< MODEL >::forecastTL(), and oops::CostFct4DEnVar< MODEL >::runNL().
initialize() [1/2]
template<typename FLDS > void oops::PostProcessor< FLDS >::initialize (const FLDS & xx, const util::DateTime & end, const util::Duration & step) inline
Calls initialize method of individual processors.
Definition at line 68 of file PostProcessor.h.
{
     for (std::shared_ptr<PostBase_> jp : processors_)
       jp->initialize(xx, end, step);
   }
References oops::PostProcessor< FLDS >::processors_.
Referenced by oops::Model< MODEL >::forecast(), oops::LinearModel< MODEL >::forecastAD(), oops::LinearModel< MODEL >::forecastTL(), and oops::CostFct4DEnVar< MODEL >::runNL().
initialize() [2/2]
template<typename FLDS > void oops::PostProcessor< FLDS >::initialize (FLDS & xx, const util::DateTime & end, const util::Duration & step) inline
Definition at line 74 of file PostProcessor.h.
{
     for (std::shared_ptr<PostBase_> jp : processors_)
       jp->initialize(xx, end, step);
   }
References oops::PostProcessor< FLDS >::processors_.
operator=()
template<typename FLDS > PostProcessor oops::PostProcessor< FLDS >::operator= (const PostProcessor< FLDS > &) private
process() [1/2]
template<typename FLDS > void oops::PostProcessor< FLDS >::process (const FLDS & xx) inline
Calls process method of individual processors.
Definition at line 81 of file PostProcessor.h.
{
     for (std::shared_ptr<PostBase_> jp : processors_) jp->process(xx);
   }
References oops::PostProcessor< FLDS >::processors_.
Referenced by oops::Model< MODEL >::forecast(), oops::LinearModel< MODEL >::forecastAD(), oops::LinearModel< MODEL >::forecastTL(), and oops::CostFct4DEnVar< MODEL >::runNL().
process() [2/2]
template<typename FLDS > void oops::PostProcessor< FLDS >::process (FLDS & xx) inline
Definition at line 85 of file PostProcessor.h.
{
     for (std::shared_ptr<PostBase_> jp : processors_) jp->process(xx);
   }
References oops::PostProcessor< FLDS >::processors_.
Member Data Documentation
processors_
template<typename FLDS > std::vector<std::shared_ptr<PostBase_> > oops::PostProcessor< FLDS >::processors_ private
Vector of shared pointers to individual processors.
Definition at line 98 of file PostProcessor.h.
Referenced by oops::PostProcessor< FLDS >::enrollProcessor(), oops::PostProcessor< FLDS >::finalize(), oops::PostProcessor< FLDS >::initialize(), and oops::PostProcessor< FLDS >::process().
The documentation for this class was generated from the following file:
src/oops/base/PostProcessor.h