OOPS Documentation: oops::SaddlePointMatrix< MODEL > Class Template Reference
oops::SaddlePointMatrix< MODEL > Class Template Reference
The Saddle-point matrix.
#include <SaddlePointMatrix.h>
Public Member Functions
SaddlePointMatrix (const CostFct_ &j)
void multiply (const SPVector_ &, SPVector_ &) const
Private Types
using Increment_ = Increment< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using CostFct_ = CostFunction< MODEL >
using SPVector_ = SaddlePointVector< MODEL >
using JqTermAD_ = JqTermAD< MODEL >
using JqTermTL_ = JqTermTL< MODEL >
Private Attributes
const CostFct_ & j_
Detailed Description
template<typename MODEL>
class oops::SaddlePointMatrix< MODEL >
The Saddle-point matrix.
The solvers represent matrices as objects that implement a "multiply" method. This class defines objects that apply the saddle-point matrix.
Definition at line 38 of file SaddlePointMatrix.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::SaddlePointMatrix< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 41 of file SaddlePointMatrix.h.
CtrlInc_
template<typename MODEL > using oops::SaddlePointMatrix< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 40 of file SaddlePointMatrix.h.
Increment_
template<typename MODEL > using oops::SaddlePointMatrix< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 39 of file SaddlePointMatrix.h.
JqTermAD_
template<typename MODEL > using oops::SaddlePointMatrix< MODEL >::JqTermAD_ = JqTermAD<MODEL> private
Definition at line 43 of file SaddlePointMatrix.h.
JqTermTL_
template<typename MODEL > using oops::SaddlePointMatrix< MODEL >::JqTermTL_ = JqTermTL<MODEL> private
Definition at line 44 of file SaddlePointMatrix.h.
SPVector_
template<typename MODEL > using oops::SaddlePointMatrix< MODEL >::SPVector_ = SaddlePointVector<MODEL> private
Definition at line 42 of file SaddlePointMatrix.h.
Constructor & Destructor Documentation
SaddlePointMatrix()
template<typename MODEL > oops::SaddlePointMatrix< MODEL >::SaddlePointMatrix (const CostFct_ & j) inline explicit
Definition at line 47 of file SaddlePointMatrix.h.
 : j_(j) {}
Member Function Documentation
multiply()
template<typename MODEL > void oops::SaddlePointMatrix< MODEL >::multiply (const SPVector_ & x, SPVector_ & z) const
Definition at line 57 of file SaddlePointMatrix.h.
{
   CtrlInc_ ww(j_.jb());
   // The three blocks below could be done in parallel
   // ADJ block
   PostProcessorAD<Increment_> costad;
   j_.zeroAD(ww);
   z.dx(new CtrlInc_(j_.jb()));
   JqTermAD_ *jqad = j_.jb().initializeAD(z.dx(), x.lambda().dx());
   costad.enrollProcessor(jqad);
   for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
     costad.enrollProcessor(j_.jterm(jj).setupAD(x.lambda().getv(jj), ww));
   }
   j_.runAD(ww, costad);
   z.dx() += ww;
   // TLM block
   PostProcessorTL<Increment_> costtl;
   JqTermTL_ *jqtl = j_.jb().initializeTL();
   costtl.enrollProcessor(jqtl);
   for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
     costtl.enrollProcessor(j_.jterm(jj).setupTL(x.dx()));
   }
   CtrlInc_ mdx(x.dx());
   j_.runTL(mdx, costtl);
   z.lambda().clear();
   z.lambda().dx(new CtrlInc_(j_.jb()));
   j_.jb().finalizeTL(jqtl, x.dx(), z.lambda().dx());
   for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
     z.lambda().append(costtl.releaseOutputFromTL(jj + 1));
   }
   // Diagonal block
   DualVector<MODEL> diag;
   diag.dx(new CtrlInc_(j_.jb()));
   j_.jb().multiplyB(x.lambda().dx(), diag.dx());
   for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
     diag.append(j_.jterm(jj).multiplyCovar(*x.lambda().getv(jj)));
   }
   // The three blocks above could be done in parallel
   z.lambda() += diag;
 }
References oops::DualVector< MODEL >::append(), oops::DualVector< MODEL >::clear(), oops::DualVector< MODEL >::dx(), oops::SaddlePointVector< MODEL >::dx(), oops::PostProcessorAD< INCR >::enrollProcessor(), oops::PostProcessorTL< INCR >::enrollProcessor(), oops::DualVector< MODEL >::getv(), oops::SaddlePointVector< MODEL >::lambda(), and oops::PostProcessorTL< INCR >::releaseOutputFromTL().
Member Data Documentation
j_
template<typename MODEL > const CostFct_& oops::SaddlePointMatrix< MODEL >::j_ private
Definition at line 51 of file SaddlePointMatrix.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/SaddlePointMatrix.h