OOPS Documentation: oops::IncrEnsCtlVec< MODEL > Class Template Reference
oops::IncrEnsCtlVec< MODEL > Class Template Reference
IncrEnsCtlVec class.
#include <CostJbState.h>
Public Member Functions
IncrEnsCtlVec ()
Constructor.
IncrEnsCtlVec (const Geometry_ &, const Localization_ &)
Constructor.
IncrEnsCtlVec (const Geometry_ &, const Localization_ &, const IncrEnsCtlVec &)
Constructor with copy initialization.
IncrEnsCtlVec (const IncrEnsCtlVec &, const bool copy=true)
Copy constructor.
virtual ~IncrEnsCtlVec ()
Destructor.
void zero ()
\(dv_1 = 0 \)
IncrEnsCtlVec & operator= (const IncrEnsCtlVec &)
\(dv_1 = dv_2 \)
IncrEnsCtlVec & operator+= (const IncrEnsCtlVec &)
\(dv_1 = dv_1 + dv_2 \)
IncrEnsCtlVec & operator-= (const IncrEnsCtlVec &)
\(dv_1 = dv_1 - dv_2 \)
IncrEnsCtlVec & operator*= (const double &)
\(dv_1 = dv_1 * c \)
void axpy (const double &, const IncrEnsCtlVec &, const bool check=true)
\(dv_1 = dv_1 * c dv_2 \)
double dot_product_with (const IncrEnsCtlVec &, const bool local=false) const
\(<dv_1,dv_1> = dv_1^T dv_1 \)
void schur_product_with (const IncrEnsCtlVec &)
Hadamard product (element-wise)
void random ()
Random control vector.
void read (const eckit::Configuration &)
Read control vector.
void write (const eckit::Configuration &) const
Write control vector.
double norm () const
L-2 norm.
IncrEnsCtlVec_ & ctlVec ()
Get ensemble control vector.
const IncrEnsCtlVec_ & ctlVec () const
Get constant ensemble control vector.
Static Public Member Functions
static const std::string classname ()
Private Types
using IncrEnsCtlVec_ = typename MODEL::IncrEnsCtlVec
using Localization_ = Localization< MODEL >
using Geometry_ = Geometry< MODEL >
Private Member Functions
void print (std::ostream &) const
Private Attributes
std::unique_ptr< IncrEnsCtlVec_ > incrEnsCtlVec_
Model specific implementation.
Detailed Description
template<typename MODEL>
class oops::IncrEnsCtlVec< MODEL >
IncrEnsCtlVec class.
Part of the control vector (acted upon by the localized ensemble B matrix). Consider a general formulation of the state component of the control vector for a particular sub-window \(K \), having two components corresponding to the modelled and ensemble based covariance matrices:
\[ dv^K = \begin{bmatrix} dv^K_{mod} \\ dv^K_{ens} \end{bmatrix} \]
-> \(dv^K \) is implemented by IncrCtlVec
The component corresponding to the localized ensemble B matrix is defined as:
\[ dv^K_{ens} = \begin{bmatrix} dv^K_{ens_{1}} \\ .. \\ dv^K_{ens_{L}} \end{bmatrix} \]
-> \(dv^K_{ens_m} \) is implemented by IncrEnsCtlVec, L is the number of ensemble perturbations used to construct the localized sampled covariance matrix;
Definition at line 40 of file CostJbState.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::IncrEnsCtlVec< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 69 of file IncrEnsCtlVec.h.
IncrEnsCtlVec_
template<typename MODEL > using oops::IncrEnsCtlVec< MODEL >::IncrEnsCtlVec_ = typename MODEL::IncrEnsCtlVec private
Definition at line 67 of file IncrEnsCtlVec.h.
Localization_
template<typename MODEL > using oops::IncrEnsCtlVec< MODEL >::Localization_ = Localization<MODEL> private
Definition at line 68 of file IncrEnsCtlVec.h.
Constructor & Destructor Documentation
IncrEnsCtlVec() [1/4]
template<typename MODEL > oops::IncrEnsCtlVec< MODEL >::IncrEnsCtlVec () inline
Constructor.
Definition at line 75 of file IncrEnsCtlVec.h.
 : incrEnsCtlVec_() {}
IncrEnsCtlVec() [2/4]
template<typename MODEL > oops::IncrEnsCtlVec< MODEL >::IncrEnsCtlVec (const Geometry_ & resol, const Localization_ & loc)
Constructor.
Constructor, destructor.
Dimensions of the ensemble control vector are determined by the geometry and localization matrix.
Definition at line 132 of file IncrEnsCtlVec.h.
     : incrEnsCtlVec_() {
   Log::trace() << "IncrEnsCtlVec<MODEL>::IncrEnsCtlVec starting" << std::endl;
   util::Timer timer(classname(), "Incr");
   incrEnsCtlVec_.reset(
       new IncrEnsCtlVec_(resol.geometry(), loc.localization()));
   Log::trace() << "IncrEnsCtlVec<MODEL>::IncrEnsCtlVec done" << std::endl;
 }
References oops::IncrEnsCtlVec< MODEL >::classname(), oops::Geometry< MODEL >::geometry(), oops::IncrEnsCtlVec< MODEL >::incrEnsCtlVec_, and oops::Localization< MODEL >::localization().
IncrEnsCtlVec() [3/4]
template<typename MODEL > oops::IncrEnsCtlVec< MODEL >::IncrEnsCtlVec (const Geometry_ & resol, const Localization_ & loc, const IncrEnsCtlVec< MODEL > & other)
Constructor with copy initialization.
Definition at line 149 of file IncrEnsCtlVec.h.
     : incrEnsCtlVec_() {
   Log::trace() << "IncrEnsCtlVec<MODEL>::IncrEnsCtlVec starting" << std::endl;
   util::Timer timer(classname(), "Incr");
   if (other.incrEnsCtlVec_ != 0) {
     incrEnsCtlVec_.reset(new IncrEnsCtlVec_(
         resol.geometry(), loc.localization(), *other.incrEnsCtlVec_));
   }
   Log::trace() << "IncrEnsCtlVec<MODEL>::IncrEnsCtlVec done" << std::endl;
 }
References oops::IncrEnsCtlVec< MODEL >::classname(), oops::Geometry< MODEL >::geometry(), oops::IncrEnsCtlVec< MODEL >::incrEnsCtlVec_, and oops::Localization< MODEL >::localization().
IncrEnsCtlVec() [4/4]
template<typename MODEL > oops::IncrEnsCtlVec< MODEL >::IncrEnsCtlVec (const IncrEnsCtlVec< MODEL > & other, const bool copy = true)
Copy constructor.
Definition at line 165 of file IncrEnsCtlVec.h.
     : incrEnsCtlVec_() {
   Log::trace() << "IncrEnsCtlVec<MODEL>::IncrEnsCtlVec copy starting"
                << std::endl;
   util::Timer timer(classname(), "Incr");
   if (other.incrEnsCtlVec_ != 0)
     incrEnsCtlVec_.reset(new IncrEnsCtlVec_(*other.incrEnsCtlVec_, copy));
   Log::trace() << "IncrEnsCtlVec<MODEL>::IncrEnsCtlVec copy done" << std::endl;
 }
References oops::IncrEnsCtlVec< MODEL >::classname(), and oops::IncrEnsCtlVec< MODEL >::incrEnsCtlVec_.
~IncrEnsCtlVec()
template<typename MODEL > oops::IncrEnsCtlVec< MODEL >::~IncrEnsCtlVec virtual
Destructor.
Definition at line 178 of file IncrEnsCtlVec.h.
{
   Log::trace() << "IncrEnsCtlVec<MODEL>::~IncrEnsCtlVec starting" << std::endl;
   util::Timer timer(classname(), "~Incr");
   incrEnsCtlVec_.reset();
   Log::trace() << "IncrEnsCtlVec<MODEL>::~IncrEnsCtlVec done" << std::endl;
 }
Member Function Documentation
axpy()
template<typename MODEL > void oops::IncrEnsCtlVec< MODEL >::axpy (const double & zz, const IncrEnsCtlVec< MODEL > & dx, const bool check = true)
\(dv_1 = dv_1 * c dv_2 \)
Definition at line 245 of file IncrEnsCtlVec.h.
{
   Log::trace() << "IncrEnsCtlVec<MODEL>::axpy starting" << std::endl;
   util::Timer timer(classname(), "axpy");
   if (incrEnsCtlVec_ != 0) incrEnsCtlVec_->axpy(zz, *dx.incrEnsCtlVec_, check);
   Log::trace() << "IncrEnsCtlVec<MODEL>::axpy done" << std::endl;
 }
References oops::IncrEnsCtlVec< MODEL >::incrEnsCtlVec_.
classname()
template<typename MODEL > static const std::string oops::IncrEnsCtlVec< MODEL >::classname () inline static
Definition at line 72 of file IncrEnsCtlVec.h.
 { return "oops::IncrEnsCtlVec"; }
Referenced by oops::IncrEnsCtlVec< MODEL >::IncrEnsCtlVec().
ctlVec() [1/2]
template<typename MODEL > IncrEnsCtlVec_& oops::IncrEnsCtlVec< MODEL >::ctlVec () inline
Get ensemble control vector.
Definition at line 116 of file IncrEnsCtlVec.h.
 { return *incrEnsCtlVec_; }
References oops::IncrEnsCtlVec< MODEL >::incrEnsCtlVec_.
Referenced by oops::Localization< MODEL >::multiplySqrt(), and oops::Localization< MODEL >::multiplySqrtTrans().
ctlVec() [2/2]
template<typename MODEL > const IncrEnsCtlVec_& oops::IncrEnsCtlVec< MODEL >::ctlVec () const inline
Get constant ensemble control vector.
Definition at line 118 of file IncrEnsCtlVec.h.
 { return *incrEnsCtlVec_; }
References oops::IncrEnsCtlVec< MODEL >::incrEnsCtlVec_.
dot_product_with()
template<typename MODEL > double oops::IncrEnsCtlVec< MODEL >::dot_product_with (const IncrEnsCtlVec< MODEL > & dx, const bool local = false) const
\(<dv_1,dv_1> = dv_1^T dv_1 \)
Definition at line 256 of file IncrEnsCtlVec.h.
{
   Log::trace() << "IncrEnsCtlVec<MODEL>::dot_product_with starting"
                << std::endl;
   util::Timer timer(classname(), "dot_product_with");
   double zz = 0;
   if (incrEnsCtlVec_ != 0)
     zz = incrEnsCtlVec_->dot_product_with(*dx.incrEnsCtlVec_, local);
   Log::trace() << "IncrEnsCtlVec<MODEL>::dot_product_with done" << std::endl;
   return zz;
 }
References oops::IncrEnsCtlVec< MODEL >::incrEnsCtlVec_.
norm()
template<typename MODEL > double oops::IncrEnsCtlVec< MODEL >::norm
L-2 norm.
Definition at line 312 of file IncrEnsCtlVec.h.
{
   Log::trace() << "IncrEnsCtlVec<MODEL>::norm starting" << std::endl;
   util::Timer timer(classname(), "norm");
   double zz = 0;
   if (incrEnsCtlVec_ != 0) incrEnsCtlVec_->norm();
   Log::trace() << "IncrEnsCtlVec<MODEL>::norm done" << std::endl;
   return zz;
 }
operator*=()
template<typename MODEL > IncrEnsCtlVec< MODEL > & oops::IncrEnsCtlVec< MODEL >::operator*= (const double & zz)
\(dv_1 = dv_1 * c \)
Definition at line 234 of file IncrEnsCtlVec.h.
{
   Log::trace() << "IncrEnsCtlVec<MODEL>::operator*= starting" << std::endl;
   util::Timer timer(classname(), "operator*=");
   if (incrEnsCtlVec_ != 0) *incrEnsCtlVec_ *= zz;
   Log::trace() << "IncrEnsCtlVec<MODEL>::operator*= done" << std::endl;
   return *this;
 }
operator+=()
template<typename MODEL > IncrEnsCtlVec< MODEL > & oops::IncrEnsCtlVec< MODEL >::operator+= (const IncrEnsCtlVec< MODEL > & rhs)
\(dv_1 = dv_1 + dv_2 \)
Definition at line 210 of file IncrEnsCtlVec.h.
{
   Log::trace() << "IncrEnsCtlVec<MODEL>::operator+= starting" << std::endl;
   util::Timer timer(classname(), "operator+=");
   if (incrEnsCtlVec_ != 0) *incrEnsCtlVec_ += *rhs.incrEnsCtlVec_;
   Log::trace() << "IncrEnsCtlVec<MODEL>::operator+= done" << std::endl;
   return *this;
 }
References oops::IncrEnsCtlVec< MODEL >::incrEnsCtlVec_.
operator-=()
template<typename MODEL > IncrEnsCtlVec< MODEL > & oops::IncrEnsCtlVec< MODEL >::operator-= (const IncrEnsCtlVec< MODEL > & rhs)
\(dv_1 = dv_1 - dv_2 \)
Definition at line 222 of file IncrEnsCtlVec.h.
{
   Log::trace() << "IncrEnsCtlVec<MODEL>::operator-= starting" << std::endl;
   util::Timer timer(classname(), "operator-=");
   if (incrEnsCtlVec_ != 0) *incrEnsCtlVec_ -= *rhs.incrEnsCtlVec_;
   Log::trace() << "IncrEnsCtlVec<MODEL>::operator-= done" << std::endl;
   return *this;
 }
References oops::IncrEnsCtlVec< MODEL >::incrEnsCtlVec_.
operator=()
template<typename MODEL > IncrEnsCtlVec< MODEL > & oops::IncrEnsCtlVec< MODEL >::operator= (const IncrEnsCtlVec< MODEL > & rhs)
\(dv_1 = dv_2 \)
Definition at line 198 of file IncrEnsCtlVec.h.
{
   Log::trace() << "IncrEnsCtlVec<MODEL>::operator= starting" << std::endl;
   util::Timer timer(classname(), "operator=");
   if (incrEnsCtlVec_ != 0) *incrEnsCtlVec_ = *rhs.incrEnsCtlVec_;
   Log::trace() << "IncrEnsCtlVec<MODEL>::operator= done" << std::endl;
   return *this;
 }
References oops::IncrEnsCtlVec< MODEL >::incrEnsCtlVec_.
print()
template<typename MODEL > void oops::IncrEnsCtlVec< MODEL >::print (std::ostream & os) const private
Definition at line 324 of file IncrEnsCtlVec.h.
{
   Log::trace() << "IncrEnsCtlVec<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   if (incrEnsCtlVec_ != 0) os << *incrEnsCtlVec_;
   Log::trace() << "IncrEnsCtlVec<MODEL>::print done" << std::endl;
 }
random()
template<typename MODEL > void oops::IncrEnsCtlVec< MODEL >::random
Random control vector.
Definition at line 282 of file IncrEnsCtlVec.h.
{
   Log::trace() << "IncrEnsCtlVec<MODEL>::random starting" << std::endl;
   util::Timer timer(classname(), "random");
   if (incrEnsCtlVec_ != 0) incrEnsCtlVec_->random();
   Log::trace() << "IncrEnsCtlVec<MODEL>::random done" << std::endl;
 }
read()
template<typename MODEL > void oops::IncrEnsCtlVec< MODEL >::read (const eckit::Configuration & conf)
Read control vector.
Definition at line 292 of file IncrEnsCtlVec.h.
{
   Log::trace() << "IncrEnsCtlVec<MODEL>::read starting" << std::endl;
   util::Timer timer(classname(), "read");
   if (incrEnsCtlVec_ != 0) incrEnsCtlVec_->read(conf);
   Log::trace() << "IncrEnsCtlVec<MODEL>::read done" << std::endl;
 }
schur_product_with()
template<typename MODEL > void oops::IncrEnsCtlVec< MODEL >::schur_product_with (const IncrEnsCtlVec< MODEL > & dx)
Hadamard product (element-wise)
Definition at line 270 of file IncrEnsCtlVec.h.
{
   Log::trace() << "IncrEnsCtlVec<MODEL>::schur_product_with starting"
                << std::endl;
   util::Timer timer(classname(), "schur_product_with");
   if (incrEnsCtlVec_ != 0)
     incrEnsCtlVec_->schur_product_with(*dx.incrEnsCtlVec_);
   Log::trace() << "IncrEnsCtlVec<MODEL>::schur_product_with done" << std::endl;
 }
References oops::IncrEnsCtlVec< MODEL >::incrEnsCtlVec_.
write()
template<typename MODEL > void oops::IncrEnsCtlVec< MODEL >::write (const eckit::Configuration & conf) const
Write control vector.
Definition at line 302 of file IncrEnsCtlVec.h.
{
   Log::trace() << "IncrEnsCtlVec<MODEL>::write starting" << std::endl;
   util::Timer timer(classname(), "write");
   if (incrEnsCtlVec_ != 0) incrEnsCtlVec_->write(conf);
   Log::trace() << "IncrEnsCtlVec<MODEL>::write done" << std::endl;
 }
zero()
template<typename MODEL > void oops::IncrEnsCtlVec< MODEL >::zero
\(dv_1 = 0 \)
Definition at line 188 of file IncrEnsCtlVec.h.
{
   Log::trace() << "IncrEnsCtlVec<MODEL>::zero starting" << std::endl;
   util::Timer timer(classname(), "zero");
   if (incrEnsCtlVec_ != 0) incrEnsCtlVec_->zero();
   Log::trace() << "IncrEnsCtlVec<MODEL>::zero done" << std::endl;
 }
Referenced by oops::EnsembleCovariance4D< MODEL >::advectedMultiplySqrtTrans(), oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::advectedMultiplySqrtTrans(), oops::EnsembleCovariance4DDistributed< MODEL >::advectedMultiplySqrtTrans(), oops::EnsembleCovsInterpol< MODEL >::multiplySqrtTrans(), and oops::EnsembleCovariance< MODEL >::multiplySqrtTrans().
Member Data Documentation
incrEnsCtlVec_
template<typename MODEL > std::unique_ptr<IncrEnsCtlVec_> oops::IncrEnsCtlVec< MODEL >::incrEnsCtlVec_ private
Model specific implementation.
Definition at line 124 of file IncrEnsCtlVec.h.
Referenced by oops::IncrEnsCtlVec< MODEL >::axpy(), oops::IncrEnsCtlVec< MODEL >::ctlVec(), oops::IncrEnsCtlVec< MODEL >::dot_product_with(), oops::IncrEnsCtlVec< MODEL >::IncrEnsCtlVec(), oops::IncrEnsCtlVec< MODEL >::operator+=(), oops::IncrEnsCtlVec< MODEL >::operator-=(), oops::IncrEnsCtlVec< MODEL >::operator=(), and oops::IncrEnsCtlVec< MODEL >::schur_product_with().
The documentation for this class was generated from the following files:
src/oops/assimilation/CostJbState.h
src/oops/interface/IncrEnsCtlVec.h