OOPS Documentation: oops::PostProcessorAD< INCR > Class Template Reference
oops::PostProcessorAD< INCR > Class Template Reference
Control model post processing.
#include <PostProcessorAD.h>
Public Member Functions
PostProcessorAD ()
PostProcessorAD (const PostProcessorAD &pp)
~PostProcessorAD ()
void enrollProcessor (PostBaseAD_ *pp)
void enrollProcessor (std::shared_ptr< PostBaseAD_ > pp)
void initializeAD (INCR &dx, const util::DateTime &bgn, const util::Duration &step)
void processAD (INCR &dx)
void finalizeAD (INCR &dx)
Private Types
using PostBaseAD_ = PostBaseAD< INCR >
Private Member Functions
PostProcessorAD operator= (const PostProcessorAD &)
Private Attributes
std::vector< std::shared_ptr< PostBaseAD_ > > processors_
Detailed Description
template<typename INCR>
class oops::PostProcessorAD< INCR >
Control model post processing.
This class controls model post processing in the most general sense, ie all diagnostics computations that do not affect the model integration. It just calls all the individual processors one by one.
Definition at line 30 of file PostProcessorAD.h.
Member Typedef Documentation
PostBaseAD_
template<typename INCR > using oops::PostProcessorAD< INCR >::PostBaseAD_ = PostBaseAD<INCR> private
Definition at line 31 of file PostProcessorAD.h.
Constructor & Destructor Documentation
PostProcessorAD() [1/2]
template<typename INCR > oops::PostProcessorAD< INCR >::PostProcessorAD () inline
Definition at line 34 of file PostProcessorAD.h.
 {}
PostProcessorAD() [2/2]
template<typename INCR > oops::PostProcessorAD< INCR >::PostProcessorAD (const PostProcessorAD< INCR > & pp) inline
Definition at line 35 of file PostProcessorAD.h.
 : processors_(pp.processors_) {}
~PostProcessorAD()
template<typename INCR > oops::PostProcessorAD< INCR >::~PostProcessorAD () inline
Definition at line 36 of file PostProcessorAD.h.
 {}
Member Function Documentation
enrollProcessor() [1/2]
template<typename INCR > void oops::PostProcessorAD< INCR >::enrollProcessor (PostBaseAD_ * pp) inline
Definition at line 38 of file PostProcessorAD.h.
{
     if (pp != 0) {
       std::shared_ptr<PostBaseAD_> sp(pp);
       processors_.push_back(sp);
     }
   }
References oops::PostProcessorAD< INCR >::processors_.
Referenced by oops::StaticWithTLModelCovariance4D< MODEL >::advectedMultiply(), oops::StaticWithTLModelCovariance4D< MODEL >::advectedMultiplySqrtTrans(), oops::HtRinvHdxFG< MODEL >::compute(), oops::CostFunction< MODEL >::computeGradientFG(), oops::HtMatrix< MODEL >::multiply(), oops::HBHtMatrix< MODEL >::multiply(), oops::SaddlePointMatrix< MODEL >::multiply(), oops::HtRinvHMatrix< MODEL >::multiply(), oops::LBHessianMatrix< MODEL >::multiply(), oops::HessianMatrix< MODEL >::multiply(), and oops::UtHtRinvHUMatrix< MODEL >::multiply().
enrollProcessor() [2/2]
template<typename INCR > void oops::PostProcessorAD< INCR >::enrollProcessor (std::shared_ptr< PostBaseAD_ > pp) inline
Definition at line 45 of file PostProcessorAD.h.
{
     if (pp != 0) processors_.push_back(pp);
   }
References oops::PostProcessorAD< INCR >::processors_.
finalizeAD()
template<typename INCR > void oops::PostProcessorAD< INCR >::finalizeAD (INCR & dx) inline
Definition at line 60 of file PostProcessorAD.h.
{
     for (std::shared_ptr<PostBaseAD_> jp : processors_) jp->finalizeAD(dx);
   }
References oops::PostProcessorAD< INCR >::processors_.
Referenced by oops::LinearModel< MODEL >::forecastAD(), oops::CostFct4DVarHyb4D< MODEL >::runAD(), and oops::CostFct4DEnVar< MODEL >::runAD().
initializeAD()
template<typename INCR > void oops::PostProcessorAD< INCR >::initializeAD (INCR & dx, const util::DateTime & bgn, const util::Duration & step) inline
Definition at line 49 of file PostProcessorAD.h.
{
     for (std::shared_ptr<PostBaseAD_> jp : processors_) {
       jp->initializeAD(dx, bgn, step);
     }
   }
References oops::PostProcessorAD< INCR >::processors_.
Referenced by oops::LinearModel< MODEL >::forecastAD(), oops::CostFct4DVarHyb4D< MODEL >::runAD(), and oops::CostFct4DEnVar< MODEL >::runAD().
operator=()
template<typename INCR > PostProcessorAD oops::PostProcessorAD< INCR >::operator= (const PostProcessorAD< INCR > &) private
processAD()
template<typename INCR > void oops::PostProcessorAD< INCR >::processAD (INCR & dx) inline
Definition at line 56 of file PostProcessorAD.h.
{
     for (std::shared_ptr<PostBaseAD_> jp : processors_) jp->processAD(dx);
   }
References oops::PostProcessorAD< INCR >::processors_.
Referenced by oops::LinearModel< MODEL >::forecastAD(), oops::CostFct4DVarHyb4D< MODEL >::runAD(), and oops::CostFct4DEnVar< MODEL >::runAD().
Member Data Documentation
processors_
template<typename INCR > std::vector<std::shared_ptr<PostBaseAD_> > oops::PostProcessorAD< INCR >::processors_ private
Definition at line 65 of file PostProcessorAD.h.
Referenced by oops::PostProcessorAD< INCR >::enrollProcessor(), oops::PostProcessorAD< INCR >::finalizeAD(), oops::PostProcessorAD< INCR >::initializeAD(), and oops::PostProcessorAD< INCR >::processAD().
The documentation for this class was generated from the following file:
src/oops/base/PostProcessorAD.h