OOPS Documentation: oops::EnsembleCovsInterpol< MODEL > Class Template Reference
oops::EnsembleCovsInterpol< MODEL > Class Template Reference
Generic ensemble based model space error covariance.
#include <EnsembleCovsInterpol.h>
Public Member Functions
EnsembleCovsInterpol (const Geometry_ &, const Variables_ &, const eckit::Configuration &, const State_ &)
Constructor, destructor.
~EnsembleCovsInterpol ()
void linearize (const State_ &, const Geometry_ &) override
Set up the inner loop resolution B matrix.
void linearize (const State_ &, const Geometry_ &, const eckit::Configuration &) override
void multiply (const Increment_ &, Increment_ &) const override
\(dx_1 = B dx_2 \)
void inverseMultiply (const Increment_ &, Increment_ &) const override
\(dx_1 = B^{-1} dx_2 \)
void multiplySqrt (const IncrCtlVec_ &, Increment_ &) const override
\(dx = B^{1/2} dv \)
void multiplySqrtTrans (const Increment_ &, IncrCtlVec_ &) const override
\(dv = [B^{1/2}]^T dx \)
void randomize (Increment_ &) const override
\(dx = B^{1/2} dv_{random} \)
IncrModCtlVec_ * newIncrModCtlVec () const override
IncrEnsCtlVec_ * newIncrEnsCtlVec () const override
Public Member Functions inherited from oops::ModelSpaceCovarianceBase< MODEL >
virtual ~ModelSpaceCovarianceBase ()
Destructor.
Private Types
typedef Ensemble< MODEL > Ensemble_
typedef std::shared_ptr< Ensemble< MODEL > > EnsemblePtr_
typedef EnsemblesCollection< MODEL > EnsemblesCollection_
typedef Geometry< MODEL > Geometry_
typedef Increment< MODEL > Increment_
typedef IncrCtlVec< MODEL > IncrCtlVec_
typedef IncrEnsCtlVec< MODEL > IncrEnsCtlVec_
typedef IncrModCtlVec< MODEL > IncrModCtlVec_
typedef Localization< MODEL > Localization_
typedef State< MODEL > State_
typedef Variables< MODEL > Variables_
typedef Interpolator< MODEL > Interpolator_
Private Member Functions
void schur_add (const Increment_ &, const Increment_ &dxi, Increment_ &dxo, Increment_ &tmp) const
Private Attributes
const eckit::LocalConfiguration config_
const util::DateTime time_
std::unique_ptr< Localization_ > loc_
std::unique_ptr< Interpolator_ > intdir_
std::unique_ptr< Interpolator_ > intadj_
std::unique_ptr< Geometry_ > resol_ens_
Detailed Description
template<typename MODEL>
class oops::EnsembleCovsInterpol< MODEL >
Generic ensemble based model space error covariance.
Definition at line 43 of file EnsembleCovsInterpol.h.
Member Typedef Documentation
Ensemble_
template<typename MODEL > typedef Ensemble<MODEL> oops::EnsembleCovsInterpol< MODEL >::Ensemble_ private
Definition at line 44 of file EnsembleCovsInterpol.h.
EnsemblePtr_
template<typename MODEL > typedef std::shared_ptr<Ensemble<MODEL> > oops::EnsembleCovsInterpol< MODEL >::EnsemblePtr_ private
Definition at line 45 of file EnsembleCovsInterpol.h.
EnsemblesCollection_
template<typename MODEL > typedef EnsemblesCollection<MODEL> oops::EnsembleCovsInterpol< MODEL >::EnsemblesCollection_ private
Definition at line 46 of file EnsembleCovsInterpol.h.
Geometry_
template<typename MODEL > typedef Geometry<MODEL> oops::EnsembleCovsInterpol< MODEL >::Geometry_ private
Definition at line 47 of file EnsembleCovsInterpol.h.
IncrCtlVec_
template<typename MODEL > typedef IncrCtlVec<MODEL> oops::EnsembleCovsInterpol< MODEL >::IncrCtlVec_ private
Definition at line 49 of file EnsembleCovsInterpol.h.
Increment_
template<typename MODEL > typedef Increment<MODEL> oops::EnsembleCovsInterpol< MODEL >::Increment_ private
Definition at line 48 of file EnsembleCovsInterpol.h.
IncrEnsCtlVec_
template<typename MODEL > typedef IncrEnsCtlVec<MODEL> oops::EnsembleCovsInterpol< MODEL >::IncrEnsCtlVec_ private
Definition at line 50 of file EnsembleCovsInterpol.h.
IncrModCtlVec_
template<typename MODEL > typedef IncrModCtlVec<MODEL> oops::EnsembleCovsInterpol< MODEL >::IncrModCtlVec_ private
Definition at line 51 of file EnsembleCovsInterpol.h.
Interpolator_
template<typename MODEL > typedef Interpolator<MODEL> oops::EnsembleCovsInterpol< MODEL >::Interpolator_ private
Definition at line 55 of file EnsembleCovsInterpol.h.
Localization_
template<typename MODEL > typedef Localization<MODEL> oops::EnsembleCovsInterpol< MODEL >::Localization_ private
Definition at line 52 of file EnsembleCovsInterpol.h.
State_
template<typename MODEL > typedef State<MODEL> oops::EnsembleCovsInterpol< MODEL >::State_ private
Definition at line 53 of file EnsembleCovsInterpol.h.
Variables_
template<typename MODEL > typedef Variables<MODEL> oops::EnsembleCovsInterpol< MODEL >::Variables_ private
Definition at line 54 of file EnsembleCovsInterpol.h.
Constructor & Destructor Documentation
EnsembleCovsInterpol()
template<typename MODEL > oops::EnsembleCovsInterpol< MODEL >::EnsembleCovsInterpol (const Geometry_ & resol, const Variables_ & , const eckit::Configuration & config, const State_ &)
Constructor, destructor.
Definition at line 92 of file EnsembleCovsInterpol.h.
   : config_(config), time_(config_.getString("date"))
 {
   Log::trace() << "EnsembleCovsInterpol created." << std::endl;
 }
~EnsembleCovsInterpol()
template<typename MODEL > oops::EnsembleCovsInterpol< MODEL >::~EnsembleCovsInterpol
Definition at line 100 of file EnsembleCovsInterpol.h.
{
   loc_.reset();
   Log::trace() << "EnsembleCovsInterpol destructed." << std::endl;
 }
Member Function Documentation
inverseMultiply()
template<typename MODEL > void oops::EnsembleCovsInterpol< MODEL >::inverseMultiply (const Increment_ & , Increment_ &) const override virtual
\(dx_1 = B^{-1} dx_2 \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 191 of file EnsembleCovsInterpol.h.
{
   dxo.zero();
 }
References oops::Increment< MODEL >::zero().
linearize() [1/2]
template<typename MODEL > void oops::EnsembleCovsInterpol< MODEL >::linearize (const State_ & , const Geometry_ &) override virtual
Set up the inner loop resolution B matrix.
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 106 of file EnsembleCovsInterpol.h.
{
   linearize(xb, resol, config_);
 }
linearize() [2/2]
template<typename MODEL > void oops::EnsembleCovsInterpol< MODEL >::linearize (const State_ & xb, const Geometry_ & resol, const eckit::Configuration & config) override virtual
Reimplemented from oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 113 of file EnsembleCovsInterpol.h.
{
   /*
    * Build Geometry of the Ensemble
    */
   const eckit::LocalConfiguration confNewGeo(config_, "ensemble_resol");
   resol_ens_.reset(new Geometry_(confNewGeo));
   /*
    * Build localization
    */
   const eckit::LocalConfiguration conf(config_, "localization");
   loc_.reset(new Localization_(*resol_ens_, conf));
   /*
    * Build Interpolation operators
    */
   const eckit::LocalConfiguration confInterpol(config_, "interpol");
   intdir_.reset(new Interpolator_(xb,*resol_ens_,confInterpol, false));
   intadj_.reset(new Interpolator_(xb,*resol_ens_,confInterpol, true));
   /*
    * Build ensemble
    */
   std::vector < eckit::LocalConfiguration > confEnsemble;
   config_.get("ensemble", confEnsemble);
   EnsemblePtr_ ens_k(new Ensemble_(xb.validTime(), confEnsemble[0]));
   ens_k->build(xb, *resol_ens_);
   EnsemblesCollection_::getInstance().put(xb.validTime(), ens_k);
   /*
    * Read files, calculate mean
    */
   EnsemblePtr_ ens = EnsemblesCollection_::getInstance()[xb.validTime()];
   ens->read();
   int nb_sub_ens=confEnsemble[0].getInt("sub_ens",1);
   ens->to_perturbations(nb_sub_ens);
   Log::trace() << "EnsembleCovsInterpol linearized.";
 }
References oops::State< MODEL >::validTime().
multiply()
template<typename MODEL > void oops::EnsembleCovsInterpol< MODEL >::multiply (const Increment_ & , Increment_ &) const override virtual
\(dx_1 = B dx_2 \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 157 of file EnsembleCovsInterpol.h.
{
   EnsemblePtr_ e = EnsemblesCollection_::getInstance()[dxi.validTime()];
   dxo.zero();
   // Adjoint interpolation to the resolution of the perturbations
   const eckit::LocalConfiguration confInterpol(config_, "interpol");
   const Variables_ var(confInterpol);
   Increment_ dx_lr(*resol_ens_, var, dxi.validTime(), dxi.validTime());
   dx_lr.zero();
   Log::trace() <<  "Adjoint Interpolation (HR -> LR) of the increment";
   intadj_->interpolate(dxi, var, dx_lr);
   Increment_ dx_lr_loc(dx_lr);
   Increment_ tmp(dx_lr);
   Increment_ dxo_lr(dx_lr);
   dxo_lr.zero();
   for (unsigned l = 0; l < e->size(); ++l) {
     dx_lr_loc.zero();
     schur_add((*e)[l], dx_lr, dx_lr_loc, tmp);
     loc_->multiply(dx_lr_loc);
     schur_add((*e)[l], dx_lr_loc, dxo_lr, tmp);
   }
   // Back to HR
   Log::trace() << "Direct interpolation (LR -> HR) of the increment";
   intdir_->interpolate(dxo_lr, var , dxo);
 }
References oops::Increment< MODEL >::validTime(), and oops::Increment< MODEL >::zero().
multiplySqrt()
template<typename MODEL > void oops::EnsembleCovsInterpol< MODEL >::multiplySqrt (const IncrCtlVec_ & , Increment_ &) const override virtual
\(dx = B^{1/2} dv \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 197 of file EnsembleCovsInterpol.h.
{
   EnsemblePtr_ e = EnsemblesCollection_::getInstance()[dxo.validTime()];
   // Interpolation to the resolution of the increment
   const eckit::LocalConfiguration confInterpol(config_, "interpol");
   const Variables_ var(confInterpol);
   Increment_ dx_lr(*resol_ens_, var, dxo.validTime(), dxo.validTime());
   Increment_ dx_lr_loc(dx_lr);
   Increment_ tmp(dx_lr_loc);
   Increment_ dxo_lr(dx_lr);
   dxo_lr.zero();
   dxo.zero();
   for (unsigned l = 0; l < e->size(); ++l) {
     loc_->multiplySqrt(dv.ensCtlVec(l), dx_lr_loc);
     schur_add((*e)[l], dx_lr_loc, dxo_lr, tmp);
   }
   // Back to HR
   Log::trace() << "Direct interpolation (LR -> HR) of the increment";
   intdir_->interpolate(dxo_lr, var , dxo);
 }
References oops::IncrCtlVec< MODEL >::ensCtlVec(), oops::Increment< MODEL >::validTime(), and oops::Increment< MODEL >::zero().
multiplySqrtTrans()
template<typename MODEL > void oops::EnsembleCovsInterpol< MODEL >::multiplySqrtTrans (const Increment_ & , IncrCtlVec_ &) const override virtual
\(dv = [B^{1/2}]^T dx \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 223 of file EnsembleCovsInterpol.h.
{
   EnsemblePtr_ e = EnsemblesCollection_::getInstance()[dxi.validTime()];
   // Adjoint interpolation to the resolution of the increment
   const eckit::LocalConfiguration confInterpol(config_, "interpol");
   const Variables_ var(confInterpol);
   Increment_ dx_lr(*resol_ens_, var, dxi.validTime(), dxi.validTime());
   dx_lr.zero();
   Log::trace() <<  "Adjoint Interpolation (HR -> LR) of the increment";
   intadj_->interpolate(dxi, var, dx_lr);
   Increment_ dx_lr_loc(dx_lr);
   Increment_ tmp(dx_lr);
   for (unsigned l = 0; l < e->size(); ++l) {
     dv.ensCtlVec(l).zero();
     dx_lr_loc.zero();
     schur_add((*e)[l], dx_lr, dx_lr_loc, tmp);
     loc_->multiplySqrtTrans(dx_lr_loc, dv.ensCtlVec(l));
   }
 }
References oops::IncrCtlVec< MODEL >::ensCtlVec(), oops::Increment< MODEL >::validTime(), oops::IncrEnsCtlVec< MODEL >::zero(), and oops::Increment< MODEL >::zero().
newIncrEnsCtlVec()
template<typename MODEL > IncrEnsCtlVec_* oops::EnsembleCovsInterpol< MODEL >::newIncrEnsCtlVec () const inline override virtual
Return a new control vector corresponding to the localised sampled component of a B matrix
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 73 of file EnsembleCovsInterpol.h.
 {return new IncrEnsCtlVec_(*resol_ens_, *loc_);}
References oops::EnsembleCovsInterpol< MODEL >::loc_, and oops::EnsembleCovsInterpol< MODEL >::resol_ens_.
newIncrModCtlVec()
template<typename MODEL > IncrModCtlVec_* oops::EnsembleCovsInterpol< MODEL >::newIncrModCtlVec () const inline override virtual
Return a new control vector corresponding to the modelled component of a B matrix
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 72 of file EnsembleCovsInterpol.h.
 {return new IncrModCtlVec_();}
randomize()
template<typename MODEL > void oops::EnsembleCovsInterpol< MODEL >::randomize (Increment_ &) const override virtual
\(dx = B^{1/2} dv_{random} \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 248 of file EnsembleCovsInterpol.h.
{
   dxo.zero();
 }
References oops::Increment< MODEL >::zero().
schur_add()
template<typename MODEL > void oops::EnsembleCovsInterpol< MODEL >::schur_add (const Increment_ & pert, const Increment_ & dxi, Increment_ & dxo, Increment_ & tmp) const private
Definition at line 254 of file EnsembleCovsInterpol.h.
{
   tmp_schur = pert;
   tmp_schur.schur_product_with(dxi);
   dxo.axpy(1.0, tmp_schur, false);
 }
References oops::Increment< MODEL >::axpy(), and oops::Increment< MODEL >::schur_product_with().
Member Data Documentation
config_
template<typename MODEL > const eckit::LocalConfiguration oops::EnsembleCovsInterpol< MODEL >::config_ private
Definition at line 78 of file EnsembleCovsInterpol.h.
intadj_
template<typename MODEL > std::unique_ptr<Interpolator_> oops::EnsembleCovsInterpol< MODEL >::intadj_ private
Definition at line 82 of file EnsembleCovsInterpol.h.
intdir_
template<typename MODEL > std::unique_ptr<Interpolator_> oops::EnsembleCovsInterpol< MODEL >::intdir_ private
Definition at line 81 of file EnsembleCovsInterpol.h.
loc_
template<typename MODEL > std::unique_ptr<Localization_> oops::EnsembleCovsInterpol< MODEL >::loc_ private
Definition at line 80 of file EnsembleCovsInterpol.h.
Referenced by oops::EnsembleCovsInterpol< MODEL >::newIncrEnsCtlVec().
resol_ens_
template<typename MODEL > std::unique_ptr<Geometry_> oops::EnsembleCovsInterpol< MODEL >::resol_ens_ private
Definition at line 83 of file EnsembleCovsInterpol.h.
Referenced by oops::EnsembleCovsInterpol< MODEL >::newIncrEnsCtlVec().
time_
template<typename MODEL > const util::DateTime oops::EnsembleCovsInterpol< MODEL >::time_ private
Definition at line 79 of file EnsembleCovsInterpol.h.
The documentation for this class was generated from the following file:
src/oops/base/EnsembleCovsInterpol.h