OOPS Documentation: oops::ErrorCovariance< MODEL > Class Template Reference
oops::ErrorCovariance< MODEL > Class Template Reference
Wrapper for model space error covariances.
#include <ErrorCovariance.h>
Public Member Functions
ErrorCovariance (const Geometry_ &, const Variables_ &, const eckit::Configuration &, const State_ &)
virtual ~ErrorCovariance ()
void linearize (const State_ &, const Geometry_ &) override
Set up the inner loop resolution B matrix.
void multiply (const Increment_ &, Increment_ &) const override
\(dx_1 = B dx_2 \)
void inverseMultiply (const Increment_ &, Increment_ &) const override
\(dx_1 = B^{-1} dx_2 \)
void multiplySqrt (const IncrCtlVec_ &, Increment_ &) const override
\(dx = B^{1/2} dv \)
void multiplySqrtTrans (const Increment_ &, IncrCtlVec_ &) const override
\(dv = [B^{1/2}]^T dx \)
void randomize (Increment_ &) const override
\(dx = B^{1/2} dv_{random} \)
const Covariance_ & errorCovariance () const
Return a constant reference to the model-specific error covariance matrix.
Covariance_ & errorCovariance ()
Return a reference to the model-specific error covariance matrix.
IncrModCtlVec_ * newIncrModCtlVec () const
IncrEnsCtlVec_ * newIncrEnsCtlVec () const
Public Member Functions inherited from oops::ModelSpaceCovarianceBase< MODEL >
virtual ~ModelSpaceCovarianceBase ()
Destructor.
virtual void linearize (const State_ &xx, const Geometry_ &geom, const eckit::Configuration &)
Static Public Member Functions
static const std::string classname ()
Private Types
using Covariance_ = typename MODEL::Covariance
using Geometry_ = Geometry< MODEL >
using Increment_ = Increment< MODEL >
using IncrCtlVec_ = IncrCtlVec< MODEL >
using IncrEnsCtlVec_ = IncrEnsCtlVec< MODEL >
using IncrModCtlVec_ = IncrModCtlVec< MODEL >
using State_ = State< MODEL >
using Variables_ = Variables< MODEL >
Private Member Functions
void print (std::ostream &) const override
Private Attributes
std::unique_ptr< Covariance_ > covariance_
Pointer to a model-specific covariance.
std::unique_ptr< Geometry_ > geom_
Pointer to a geometry object.
Detailed Description
template<typename MODEL>
class oops::ErrorCovariance< MODEL >
Wrapper for model space error covariances.
This class provides the operations associated with the modelled model space error covariance matrices (B or Q). It wraps the actual model specific error covariance matrix.
Definition at line 47 of file ErrorCovariance.h.
Member Typedef Documentation
Covariance_
template<typename MODEL > using oops::ErrorCovariance< MODEL >::Covariance_ = typename MODEL::Covariance private
Definition at line 51 of file ErrorCovariance.h.
Geometry_
template<typename MODEL > using oops::ErrorCovariance< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 52 of file ErrorCovariance.h.
IncrCtlVec_
template<typename MODEL > using oops::ErrorCovariance< MODEL >::IncrCtlVec_ = IncrCtlVec<MODEL> private
Definition at line 54 of file ErrorCovariance.h.
Increment_
template<typename MODEL > using oops::ErrorCovariance< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 53 of file ErrorCovariance.h.
IncrEnsCtlVec_
template<typename MODEL > using oops::ErrorCovariance< MODEL >::IncrEnsCtlVec_ = IncrEnsCtlVec<MODEL> private
Definition at line 55 of file ErrorCovariance.h.
IncrModCtlVec_
template<typename MODEL > using oops::ErrorCovariance< MODEL >::IncrModCtlVec_ = IncrModCtlVec<MODEL> private
Definition at line 56 of file ErrorCovariance.h.
State_
template<typename MODEL > using oops::ErrorCovariance< MODEL >::State_ = State<MODEL> private
Definition at line 57 of file ErrorCovariance.h.
Variables_
template<typename MODEL > using oops::ErrorCovariance< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 58 of file ErrorCovariance.h.
Constructor & Destructor Documentation
ErrorCovariance()
template<typename MODEL > oops::ErrorCovariance< MODEL >::ErrorCovariance (const Geometry_ & resol, const Variables_ & vars, const eckit::Configuration & conf, const State_ & xb)
Definition at line 97 of file ErrorCovariance.h.
     : covariance_(), geom_() {
   Log::trace() << "ErrorCovariance<MODEL>::ErrorCovariance starting"
                << std::endl;
   util::Timer timer(classname(), "ErrorCovariance");
   covariance_.reset(
       new Covariance_(resol.geometry(), vars.variables(), conf, xb.state()));
   geom_.reset(new Geometry_(resol));
   Log::trace() << "ErrorCovariance<MODEL>::ErrorCovariance done" << std::endl;
 }
References oops::ErrorCovariance< MODEL >::classname(), oops::ErrorCovariance< MODEL >::covariance_, oops::ErrorCovariance< MODEL >::geom_, oops::Geometry< MODEL >::geometry(), oops::State< MODEL >::state(), and oops::Variables< MODEL >::variables().
~ErrorCovariance()
template<typename MODEL > oops::ErrorCovariance< MODEL >::~ErrorCovariance virtual
Definition at line 114 of file ErrorCovariance.h.
{
   Log::trace() << "ErrorCovariance<MODEL>::~ErrorCovariance starting"
                << std::endl;
   util::Timer timer(classname(), "~ErrorCovariance");
   covariance_.reset();
   geom_.reset();
   Log::trace() << "ErrorCovariance<MODEL>::~ErrorCovariance done" << std::endl;
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::ErrorCovariance< MODEL >::classname () inline static
Definition at line 61 of file ErrorCovariance.h.
 { return "oops::ErrorCovariance"; }
Referenced by oops::ErrorCovariance< MODEL >::ErrorCovariance().
errorCovariance() [1/2]
template<typename MODEL > Covariance_& oops::ErrorCovariance< MODEL >::errorCovariance () inline
Return a reference to the model-specific error covariance matrix.
Definition at line 80 of file ErrorCovariance.h.
 { return *covariance_; }
References oops::ErrorCovariance< MODEL >::covariance_.
errorCovariance() [2/2]
template<typename MODEL > const Covariance_& oops::ErrorCovariance< MODEL >::errorCovariance () const inline
Return a constant reference to the model-specific error covariance matrix.
Definition at line 78 of file ErrorCovariance.h.
 { return *covariance_; }
References oops::ErrorCovariance< MODEL >::covariance_.
Referenced by oops::IncrModCtlVec< MODEL >::IncrModCtlVec().
inverseMultiply()
template<typename MODEL > void oops::ErrorCovariance< MODEL >::inverseMultiply (const Increment_ & , Increment_ &) const override virtual
\(dx_1 = B^{-1} dx_2 \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 148 of file ErrorCovariance.h.
{
   Log::trace() << "ErrorCovariance<MODEL>::inverseMultiply starting"
                << std::endl;
   util::Timer timer(classname(), "inverseMultiply");
   covariance_->inverseMultiply(dx1.increment(), dx2.increment());
   Log::trace() << "ErrorCovariance<MODEL>::inverseMultiply done" << std::endl;
 }
References oops::Increment< MODEL >::increment().
linearize()
template<typename MODEL > void oops::ErrorCovariance< MODEL >::linearize (const State_ & , const Geometry_ &) override virtual
Set up the inner loop resolution B matrix.
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 126 of file ErrorCovariance.h.
{
   Log::trace() << "ErrorCovariance<MODEL>::linearize starting" << std::endl;
   util::Timer timer(classname(), "linearize");
   covariance_->linearize(xx.state(), resol.geometry());
   Log::trace() << "ErrorCovariance<MODEL>::linearize done" << std::endl;
 }
References oops::Geometry< MODEL >::geometry(), and oops::State< MODEL >::state().
multiply()
template<typename MODEL > void oops::ErrorCovariance< MODEL >::multiply (const Increment_ & , Increment_ &) const override virtual
\(dx_1 = B dx_2 \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 137 of file ErrorCovariance.h.
{
   Log::trace() << "ErrorCovariance<MODEL>::multiply starting" << std::endl;
   util::Timer timer(classname(), "multiply");
   covariance_->multiply(dx1.increment(), dx2.increment());
   Log::trace() << "ErrorCovariance<MODEL>::multiply done" << std::endl;
 }
References oops::Increment< MODEL >::increment().
multiplySqrt()
template<typename MODEL > void oops::ErrorCovariance< MODEL >::multiplySqrt (const IncrCtlVec_ & , Increment_ &) const override virtual
\(dx = B^{1/2} dv \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 160 of file ErrorCovariance.h.
{
   Log::trace() << "ErrorCovariance<MODEL>::multiplySqrt starting" << std::endl;
   util::Timer timer(classname(), "multiplySqrt");
   covariance_->multiplySqrt(dv.modCtlVec().ctlVec(), dx.increment());
   Log::trace() << "ErrorCovariance<MODEL>::multiplySqrt done" << std::endl;
 }
References oops::IncrModCtlVec< MODEL >::ctlVec(), oops::Increment< MODEL >::increment(), and oops::IncrCtlVec< MODEL >::modCtlVec().
multiplySqrtTrans()
template<typename MODEL > void oops::ErrorCovariance< MODEL >::multiplySqrtTrans (const Increment_ & , IncrCtlVec_ &) const override virtual
\(dv = [B^{1/2}]^T dx \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 171 of file ErrorCovariance.h.
{
   Log::trace() << "ErrorCovariance<MODEL>::multiplySqrtTrans starting"
                << std::endl;
   util::Timer timer(classname(), "multiplySqrtTrans");
   covariance_->multiplySqrtTrans(dx.increment(), dv.modCtlVec().ctlVec());
   Log::trace() << "ErrorCovariance<MODEL>::multiplySqrtTrans done" << std::endl;
 }
References oops::IncrModCtlVec< MODEL >::ctlVec(), oops::Increment< MODEL >::increment(), and oops::IncrCtlVec< MODEL >::modCtlVec().
newIncrEnsCtlVec()
template<typename MODEL > IncrEnsCtlVec_* oops::ErrorCovariance< MODEL >::newIncrEnsCtlVec () const inline virtual
Return a new control vector corresponding to the localised sampled component of a B matrix
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 84 of file ErrorCovariance.h.
 { return new IncrEnsCtlVec_(); }
newIncrModCtlVec()
template<typename MODEL > IncrModCtlVec_* oops::ErrorCovariance< MODEL >::newIncrModCtlVec () const inline virtual
Return a new control vector corresponding to the modelled component of a B matrix
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 83 of file ErrorCovariance.h.
 { return new IncrModCtlVec_(*this); }
print()
template<typename MODEL > void oops::ErrorCovariance< MODEL >::print (std::ostream & os) const override private
Definition at line 193 of file ErrorCovariance.h.
{
   Log::trace() << "ErrorCovariance<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   os << *covariance_;
   Log::trace() << "ErrorCovariance<MODEL>::print done" << std::endl;
 }
randomize()
template<typename MODEL > void oops::ErrorCovariance< MODEL >::randomize (Increment_ &) const override virtual
\(dx = B^{1/2} dv_{random} \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 183 of file ErrorCovariance.h.
{
   Log::trace() << "ErrorCovariance<MODEL>::randomize starting" << std::endl;
   util::Timer timer(classname(), "randomize");
   covariance_->randomize(dx.increment());
   Log::trace() << "ErrorCovariance<MODEL>::randomize done" << std::endl;
 }
References oops::Increment< MODEL >::increment().
Member Data Documentation
covariance_
template<typename MODEL > std::unique_ptr<Covariance_> oops::ErrorCovariance< MODEL >::covariance_ private
Pointer to a model-specific covariance.
Definition at line 90 of file ErrorCovariance.h.
Referenced by oops::ErrorCovariance< MODEL >::ErrorCovariance(), and oops::ErrorCovariance< MODEL >::errorCovariance().
geom_
template<typename MODEL > std::unique_ptr<Geometry_> oops::ErrorCovariance< MODEL >::geom_ private
Pointer to a geometry object.
Definition at line 91 of file ErrorCovariance.h.
Referenced by oops::ErrorCovariance< MODEL >::ErrorCovariance().
The documentation for this class was generated from the following file:
src/oops/interface/ErrorCovariance.h