OOPS Documentation: oops::SaddlePointVector< MODEL > Class Template Reference
oops::SaddlePointVector< MODEL > Class Template Reference
Control vector for the saddle point formulation.
#include <SaddlePointVector.h>
Public Member Functions
SaddlePointVector (CtrlInc_ *, Multipliers_ *)
SaddlePointVector (const SaddlePointVector &)
const Multipliers_ & lambda () const
Accessor method to get the lambda_ component.
Multipliers_ & lambda ()
void lambda (Multipliers_ *lambda)
Accessor method to set the lambda_ component.
const CtrlInc_ & dx () const
Accessor method to get the dx_ component.
CtrlInc_ & dx ()
void dx (CtrlInc_ *dx)
Accessor method to set the dx_ component.
SaddlePointVector & operator= (const SaddlePointVector &)
SaddlePointVector & operator+= (const SaddlePointVector &)
SaddlePointVector & operator-= (const SaddlePointVector &)
SaddlePointVector & operator*= (const double)
void zero ()
void axpy (const double, const SaddlePointVector &)
double dot_product_with (const SaddlePointVector &) const
Private Types
using CtrlInc_ = ControlIncrement< MODEL >
using Multipliers_ = DualVector< MODEL >
Private Attributes
std::unique_ptr< Multipliers_ > lambda_
std::unique_ptr< CtrlInc_ > dx_
Detailed Description
template<typename MODEL>
class oops::SaddlePointVector< MODEL >
Control vector for the saddle point formulation.
Control vector for the saddle point formulation. The vector contains two ControlIncrements and one Departure, and knows how to do basic linear algebra.
Definition at line 33 of file SaddlePointVector.h.
Member Typedef Documentation
CtrlInc_
template<typename MODEL > using oops::SaddlePointVector< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 34 of file SaddlePointVector.h.
Multipliers_
template<typename MODEL > using oops::SaddlePointVector< MODEL >::Multipliers_ = DualVector<MODEL> private
Definition at line 35 of file SaddlePointVector.h.
Constructor & Destructor Documentation
SaddlePointVector() [1/2]
template<typename MODEL > oops::SaddlePointVector< MODEL >::SaddlePointVector (CtrlInc_ * dx, Multipliers_ * lambda)
Definition at line 71 of file SaddlePointVector.h.
     : lambda_(lambda), dx_(dx) {}
SaddlePointVector() [2/2]
template<typename MODEL > oops::SaddlePointVector< MODEL >::SaddlePointVector (const SaddlePointVector< MODEL > & other)
Definition at line 77 of file SaddlePointVector.h.
     : lambda_(new Multipliers_(*other.lambda_)),
       dx_(new CtrlInc_(*other.dx_)) {}
Member Function Documentation
axpy()
template<typename MODEL > void oops::SaddlePointVector< MODEL >::axpy (const double zz, const SaddlePointVector< MODEL > & rhs)
Definition at line 132 of file SaddlePointVector.h.
{
   lambda_->axpy(zz, *rhs.lambda_);
   dx_->axpy(zz, *rhs.dx_);
 }
References oops::SaddlePointVector< MODEL >::dx_, and oops::SaddlePointVector< MODEL >::lambda_.
dot_product_with()
template<typename MODEL > double oops::SaddlePointVector< MODEL >::dot_product_with (const SaddlePointVector< MODEL > & x2) const
Definition at line 141 of file SaddlePointVector.h.
{
   return dot_product(*lambda_, *x2.lambda_) + dot_product(*dx_, *x2.dx_);
 }
References dot_product(), oops::SaddlePointVector< MODEL >::dx_, and oops::SaddlePointVector< MODEL >::lambda_.
dx() [1/3]
template<typename MODEL > CtrlInc_& oops::SaddlePointVector< MODEL >::dx () inline
Definition at line 50 of file SaddlePointVector.h.
 { return *dx_; }
References oops::SaddlePointVector< MODEL >::dx_.
dx() [2/3]
template<typename MODEL > const CtrlInc_& oops::SaddlePointVector< MODEL >::dx () const inline
Accessor method to get the dx_ component.
Definition at line 49 of file SaddlePointVector.h.
 { return *dx_; }
References oops::SaddlePointVector< MODEL >::dx_.
Referenced by oops::SaddlePointMinimizer< MODEL >::doMinimize(), oops::SaddlePointVector< MODEL >::dx(), oops::SaddlePointLMPMatrix< MODEL >::Gmultiply(), oops::SaddlePointPrecondMatrix< MODEL >::multiply(), oops::SaddlePointMatrix< MODEL >::multiply(), oops::SaddlePointLMPMatrix< MODEL >::Pinitmultiply(), oops::SaddlePointLMPMatrix< MODEL >::Rmultiply(), and oops::SaddlePointLMPMatrix< MODEL >::setup().
dx() [3/3]
template<typename MODEL > void oops::SaddlePointVector< MODEL >::dx (CtrlInc_ * dx) inline
Accessor method to set the dx_ component.
Definition at line 53 of file SaddlePointVector.h.
 { dx_.reset(dx); }
References oops::SaddlePointVector< MODEL >::dx(), and oops::SaddlePointVector< MODEL >::dx_.
lambda() [1/3]
template<typename MODEL > Multipliers_& oops::SaddlePointVector< MODEL >::lambda () inline
Definition at line 43 of file SaddlePointVector.h.
 { return *lambda_; }
References oops::SaddlePointVector< MODEL >::lambda_.
lambda() [2/3]
template<typename MODEL > const Multipliers_& oops::SaddlePointVector< MODEL >::lambda () const inline
Accessor method to get the lambda_ component.
Definition at line 42 of file SaddlePointVector.h.
 { return *lambda_; }
References oops::SaddlePointVector< MODEL >::lambda_.
Referenced by oops::SaddlePointLMPMatrix< MODEL >::Gmultiply(), oops::SaddlePointVector< MODEL >::lambda(), oops::SaddlePointPrecondMatrix< MODEL >::multiply(), oops::SaddlePointMatrix< MODEL >::multiply(), oops::SaddlePointLMPMatrix< MODEL >::Pinitmultiply(), oops::SaddlePointLMPMatrix< MODEL >::Rmultiply(), and oops::SaddlePointLMPMatrix< MODEL >::setup().
lambda() [3/3]
template<typename MODEL > void oops::SaddlePointVector< MODEL >::lambda (Multipliers_ * lambda) inline
Accessor method to set the lambda_ component.
Definition at line 46 of file SaddlePointVector.h.
 { lambda_.reset(lambda); }
References oops::SaddlePointVector< MODEL >::lambda(), and oops::SaddlePointVector< MODEL >::lambda_.
operator*=()
template<typename MODEL > SaddlePointVector< MODEL > & oops::SaddlePointVector< MODEL >::operator*= (const double rhs)
Definition at line 114 of file SaddlePointVector.h.
                       {
   *lambda_ *= rhs;
   *dx_ *= rhs;
   return *this;
 }
operator+=()
template<typename MODEL > SaddlePointVector< MODEL > & oops::SaddlePointVector< MODEL >::operator+= (const SaddlePointVector< MODEL > & rhs)
Definition at line 94 of file SaddlePointVector.h.
{
   *lambda_ += *rhs.lambda_;
   *dx_ += *rhs.dx_;
   return *this;
 }
References oops::SaddlePointVector< MODEL >::dx_, and oops::SaddlePointVector< MODEL >::lambda_.
operator-=()
template<typename MODEL > SaddlePointVector< MODEL > & oops::SaddlePointVector< MODEL >::operator-= (const SaddlePointVector< MODEL > & rhs)
Definition at line 104 of file SaddlePointVector.h.
{
   *lambda_ -= *rhs.lambda_;
   *dx_ -= *rhs.dx_;
   return *this;
 }
References oops::SaddlePointVector< MODEL >::dx_, and oops::SaddlePointVector< MODEL >::lambda_.
operator=()
template<typename MODEL > SaddlePointVector< MODEL > & oops::SaddlePointVector< MODEL >::operator= (const SaddlePointVector< MODEL > & rhs)
Definition at line 84 of file SaddlePointVector.h.
{
   *lambda_ = *rhs.lambda_;
   *dx_ = *rhs.dx_;
   return *this;
 }
References oops::SaddlePointVector< MODEL >::dx_, and oops::SaddlePointVector< MODEL >::lambda_.
zero()
template<typename MODEL > void oops::SaddlePointVector< MODEL >::zero
Definition at line 124 of file SaddlePointVector.h.
{
   lambda_->zero();
   dx_->zero();
 }
Member Data Documentation
dx_
template<typename MODEL > std::unique_ptr<CtrlInc_> oops::SaddlePointVector< MODEL >::dx_ private
Definition at line 65 of file SaddlePointVector.h.
Referenced by oops::SaddlePointVector< MODEL >::axpy(), oops::SaddlePointVector< MODEL >::dot_product_with(), oops::SaddlePointVector< MODEL >::dx(), oops::SaddlePointVector< MODEL >::operator+=(), oops::SaddlePointVector< MODEL >::operator-=(), and oops::SaddlePointVector< MODEL >::operator=().
lambda_
template<typename MODEL > std::unique_ptr<Multipliers_> oops::SaddlePointVector< MODEL >::lambda_ private
Definition at line 64 of file SaddlePointVector.h.
Referenced by oops::SaddlePointVector< MODEL >::axpy(), oops::SaddlePointVector< MODEL >::dot_product_with(), oops::SaddlePointVector< MODEL >::lambda(), oops::SaddlePointVector< MODEL >::operator+=(), oops::SaddlePointVector< MODEL >::operator-=(), and oops::SaddlePointVector< MODEL >::operator=().
The documentation for this class was generated from the following file:
src/oops/assimilation/SaddlePointVector.h