OOPS Documentation: oops::ObsOperator< MODEL > Class Template Reference
oops::ObsOperator< MODEL > Class Template Reference
Encapsulates the observation operator.
#include <ObsOperator.h>
Public Member Functions
ObsOperator (const ObsSpace_ &)
Constructor.
~ObsOperator ()
Destructor.
const ObsOperatorBase_ & obsoperator () const
Interfacing.
void obsEquiv (const GeoVaLs_ &, ObsVector_ &, const ObsAuxControl_ &) const
Evaluate the non-linear observation operator \({\cal \bar{H}} \).
void obsBiasEquiv (const GeoVaLs_ &, ObsVector_ &, const ObsAuxControl_ &) const
Evaluate the non-linear bias operator \({\cal \tilde{P}} \).
Variables_ variables () const
Retrun variables (required input variables from Model)
Static Public Member Functions
static const std::string classname ()
Private Types
using ObsOperatorBase_ = ObsOperatorBase< MODEL >
using GeoVaLs_ = GeoVaLs< MODEL >
using ObsAuxControl_ = ObsAuxControl< MODEL >
using ObsVector_ = ObsVector< MODEL >
using ObsSpace_ = ObservationSpace< MODEL >
using Variables_ = Variables< MODEL >
Private Member Functions
void print (std::ostream &) const
Private Attributes
std::unique_ptr< ObsOperatorBase_ > oper_
Pointer to a ObsOperatorBase object.
Detailed Description
template<typename MODEL>
class oops::ObsOperator< MODEL >
Encapsulates the observation operator.
This class provides the operations associated with the observation operator. It wraps the actual observation operator which is derived from the operator base class ObsOperatorBase. The interface for the observation operator comprises two levels because we want run time polymorphism. Note that it may be desirable to define an observation operator for each individual observation type rather than a single composite operator (which is the case the IFS). ObsOperatorFactory produces concrete objects of ObsOperatorBase children classes.
ObsOperators class contains a vector of ObsOperator objects. Refer to the documentation of CostJo class to understand the structure of the \(J_o \) term.
Definition at line 53 of file ObsOperator.h.
Member Typedef Documentation
GeoVaLs_
template<typename MODEL > using oops::ObsOperator< MODEL >::GeoVaLs_ = GeoVaLs<MODEL> private
Definition at line 57 of file ObsOperator.h.
ObsAuxControl_
template<typename MODEL > using oops::ObsOperator< MODEL >::ObsAuxControl_ = ObsAuxControl<MODEL> private
Definition at line 58 of file ObsOperator.h.
ObsOperatorBase_
template<typename MODEL > using oops::ObsOperator< MODEL >::ObsOperatorBase_ = ObsOperatorBase<MODEL> private
Definition at line 56 of file ObsOperator.h.
ObsSpace_
template<typename MODEL > using oops::ObsOperator< MODEL >::ObsSpace_ = ObservationSpace<MODEL> private
Definition at line 60 of file ObsOperator.h.
ObsVector_
template<typename MODEL > using oops::ObsOperator< MODEL >::ObsVector_ = ObsVector<MODEL> private
Definition at line 59 of file ObsOperator.h.
Variables_
template<typename MODEL > using oops::ObsOperator< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 61 of file ObsOperator.h.
Constructor & Destructor Documentation
ObsOperator()
template<typename MODEL > oops::ObsOperator< MODEL >::ObsOperator (const ObsSpace_ & os) explicit
Constructor.
Definition at line 95 of file ObsOperator.h.
                                                    : oper_() {
   Log::trace() << "ObsOperator<MODEL>::ObsOperator starting" << std::endl;
   util::Timer timer(classname(), "ObsOperator");
   oper_.reset(
       ObsOperatorFactory<MODEL>::create(os.observationspace(), os.config()));
   Log::trace() << "ObsOperator<MODEL>::ObsOperator done" << std::endl;
 }
References oops::ObsOperator< MODEL >::classname(), oops::ObservationSpace< MODEL >::config(), oops::ObservationSpace< MODEL >::observationspace(), and oops::ObsOperator< MODEL >::oper_.
~ObsOperator()
template<typename MODEL > oops::ObsOperator< MODEL >::~ObsOperator
Destructor.
Definition at line 106 of file ObsOperator.h.
{
   Log::trace() << "ObsOperator<MODEL>::~ObsOperator starting" << std::endl;
   util::Timer timer(classname(), "~ObsOperator");
   oper_.reset();
   Log::trace() << "ObsOperator<MODEL>::~ObsOperator done" << std::endl;
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::ObsOperator< MODEL >::classname () inline static
Definition at line 64 of file ObsOperator.h.
 { return "oops::ObsOperator"; }
Referenced by oops::ObsOperator< MODEL >::ObsOperator().
obsBiasEquiv()
template<typename MODEL > void oops::ObsOperator< MODEL >::obsBiasEquiv (const GeoVaLs_ & gvals, ObsVector_ & yybias, const ObsAuxControl_ & aux) const
Evaluate the non-linear bias operator \({\cal \tilde{P}} \).
Definition at line 133 of file ObsOperator.h.
{
   Log::trace() << "ObsOperator<MODEL>::obsEquiv starting" << std::endl;
   util::Timer timer(classname(), "ObsBiasEquiv");
   oper_->obsBiasEquiv(gvals.geovals(), yybias.obsvector(), aux.obsauxcontrol());
   Log::trace() << "ObsOperator<MODEL>::obsBiasEquiv done" << std::endl;
 }
References oops::GeoVaLs< MODEL >::geovals(), oops::ObsAuxControl< MODEL >::obsauxcontrol(), and oops::ObsVector< MODEL >::obsvector().
obsEquiv()
template<typename MODEL > void oops::ObsOperator< MODEL >::obsEquiv (const GeoVaLs_ & gvals, ObsVector_ & yy, const ObsAuxControl_ & aux) const
Evaluate the non-linear observation operator \({\cal \bar{H}} \).
\[ \begin{bmatrix} {\cal \tilde{H}} && {\cal \tilde{P}} \end{bmatrix} \begin{bmatrix} {\cal I} (x) \\ x_{obsaux} \end{bmatrix} \]
Note: -> \({\cal I} (x) \) is stored by GeoVaLs.
Definition at line 116 of file ObsOperator.h.
{
   Log::trace() << "ObsOperator<MODEL>::obsEquiv starting" << std::endl;
   util::Timer timer(classname(), "ObsEquiv");
   oper_->obsEquiv(gvals.geovals(), yy.obsvector(), aux.obsauxcontrol());
   Log::trace() << "ObsOperator<MODEL>::obsEquiv done" << std::endl;
 }
References oops::GeoVaLs< MODEL >::geovals(), oops::ObsAuxControl< MODEL >::obsauxcontrol(), and oops::ObsVector< MODEL >::obsvector().
obsoperator()
template<typename MODEL > const ObsOperatorBase_& oops::ObsOperator< MODEL >::obsoperator () const inline
Interfacing.
Definition at line 72 of file ObsOperator.h.
 { return *oper_; }
References oops::ObsOperator< MODEL >::oper_.
print()
template<typename MODEL > void oops::ObsOperator< MODEL >::print (std::ostream & os) const private
Definition at line 155 of file ObsOperator.h.
{
   Log::trace() << "ObsOperator<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   os << *oper_;
   Log::trace() << "ObsOperator<MODEL>::print done" << std::endl;
 }
variables()
template<typename MODEL > Variables< MODEL > oops::ObsOperator< MODEL >::variables
Retrun variables (required input variables from Model)
Definition at line 144 of file ObsOperator.h.
{
   Log::trace() << "ObsOperator<MODEL>::variables starting" << std::endl;
   util::Timer timer(classname(), "variables");
   Variables<MODEL> var(oper_->variables());
   Log::trace() << "ObsOperator<MODEL>::variables done" << std::endl;
   return var;
 }
Member Data Documentation
oper_
template<typename MODEL > std::unique_ptr<ObsOperatorBase_> oops::ObsOperator< MODEL >::oper_ private
Pointer to a ObsOperatorBase object.
Definition at line 89 of file ObsOperator.h.
Referenced by oops::ObsOperator< MODEL >::ObsOperator(), and oops::ObsOperator< MODEL >::obsoperator().
The documentation for this class was generated from the following file:
src/oops/interface/ObsOperator.h