OOPS Documentation: oops::ObsAuxCtlVecs< MODEL > Class Template Reference
oops::ObsAuxCtlVecs< MODEL > Class Template Reference
Encapsulates a vector of ObsAuxCtlVec objects.
#include <ObsAuxCtlVecs.h>
Public Member Functions
ObsAuxCtlVecs (const ObsAuxCovariances_ &)
Constructor.
ObsAuxCtlVecs (const ObsAuxCovariances_ &, const ObsAuxCtlVecs &)
Constructor with copy initialization.
ObsAuxCtlVecs (const ObsAuxCtlVecs &, const bool copy=true)
Copy constructor.
~ObsAuxCtlVecs ()
Destructor.
const ObsAuxCtlVec_ & operator[] (const std::size_t ii) const
Return a constant reference to the i-th ObsAuxControl object.
ObsAuxCtlVec_ & operator[] (const std::size_t ii)
Return a reference to the i-th ObsAuxControl object.
std::size_t size () const
Return the size.
void zero ()
\(dv_1 = 0 \)
ObsAuxCtlVecs & operator= (const ObsAuxCtlVecs &)
\(dv_1 = dv_2 \)
ObsAuxCtlVecs & operator+= (const ObsAuxCtlVecs &)
\(dv_1 = dv_1 + dv_2 \)
ObsAuxCtlVecs & operator-= (const ObsAuxCtlVecs &)
\(dv_1 = dv_1 - dv_2 \)
ObsAuxCtlVecs & operator*= (const double &)
\(dv_1 = dv_1 * c \)
void axpy (const double &, const ObsAuxCtlVecs &)
\(dv_1 = dv_1 * c dv_2 \)
double dot_product_with (const ObsAuxCtlVecs &) const
\(<dv_1,dv_1> = dv_1^T dv_1 \)
void read (const eckit::Configuration &)
Read control vector.
void write (const eckit::Configuration &) const
Write control vector.
double norm () const
L-2 norm.
Static Public Member Functions
static const std::string classname ()
Private Types
using ObsAuxCtlVec_ = ObsAuxCtlVec< MODEL >
using ObsAuxCovariances_ = ObsAuxCovariances< MODEL >
Private Member Functions
void print (std::ostream &) const
Private Attributes
std::vector< std::shared_ptr< ObsAuxCtlVec_ > > ctlvecs_
Vector of shared pointers to ObsAuxCtlVec objects.
Detailed Description
template<typename MODEL>
class oops::ObsAuxCtlVecs< MODEL >
Encapsulates a vector of ObsAuxCtlVec objects.
An object of ObsAuxCtlVecs class is part of ControlVector. The class contains a vector of ObsAuxCtlVec objects. Refer to the documentation of ControlVector and CostJo to understand the structure.
Definition at line 38 of file ObsAuxCtlVecs.h.
Member Typedef Documentation
ObsAuxCovariances_
template<typename MODEL > using oops::ObsAuxCtlVecs< MODEL >::ObsAuxCovariances_ = ObsAuxCovariances<MODEL> private
Definition at line 40 of file ObsAuxCtlVecs.h.
ObsAuxCtlVec_
template<typename MODEL > using oops::ObsAuxCtlVecs< MODEL >::ObsAuxCtlVec_ = ObsAuxCtlVec<MODEL> private
Definition at line 39 of file ObsAuxCtlVecs.h.
Constructor & Destructor Documentation
ObsAuxCtlVecs() [1/3]
template<typename MODEL > oops::ObsAuxCtlVecs< MODEL >::ObsAuxCtlVecs (const ObsAuxCovariances_ & covs) explicit
Constructor.
Definition at line 98 of file ObsAuxCtlVecs.h.
     : ctlvecs_(0) {
   for (std::size_t jobs = 0; jobs < covs.size(); ++jobs) {
     std::shared_ptr<ObsAuxCtlVec_> tmp(new ObsAuxCtlVec_(covs[jobs]));
     ctlvecs_.push_back(tmp);
   }
 }
References oops::ObsAuxCtlVecs< MODEL >::ctlvecs_, and oops::ObsAuxCovariances< MODEL >::size().
ObsAuxCtlVecs() [2/3]
template<typename MODEL > oops::ObsAuxCtlVecs< MODEL >::ObsAuxCtlVecs (const ObsAuxCovariances_ & covs, const ObsAuxCtlVecs< MODEL > & other)
Constructor with copy initialization.
Definition at line 107 of file ObsAuxCtlVecs.h.
     : ctlvecs_(0) {
   ASSERT(covs.size() == other.size());
   for (std::size_t jobs = 0; jobs < covs.size(); ++jobs) {
     std::shared_ptr<ObsAuxCtlVec_> tmp(
         new ObsAuxCtlVec_(covs[jobs], other[jobs]));
     ctlvecs_.push_back(tmp);
   }
 }
References oops::ObsAuxCtlVecs< MODEL >::ctlvecs_, oops::ObsAuxCovariances< MODEL >::size(), and oops::ObsAuxCtlVecs< MODEL >::size().
ObsAuxCtlVecs() [3/3]
template<typename MODEL > oops::ObsAuxCtlVecs< MODEL >::ObsAuxCtlVecs (const ObsAuxCtlVecs< MODEL > & other, const bool copy = true)
Copy constructor.
Definition at line 119 of file ObsAuxCtlVecs.h.
     : ctlvecs_(other.size()) {
   Log::trace() << "ObsAuxCtlVecs<MODEL>::ObsAuxCtlVecs copy starting"
                << std::endl;
   ASSERT(size() == other.size());
   for (std::size_t jobs = 0; jobs < other.size(); ++jobs) {
     ctlvecs_[jobs].reset(new ObsAuxCtlVec_(other[jobs], copy));
   }
   Log::trace() << "ObsAuxCtlVecs<MODEL>::ObsAuxCtlVecs copy done" << std::endl;
 }
References oops::ObsAuxCtlVecs< MODEL >::ctlvecs_, and oops::ObsAuxCtlVecs< MODEL >::size().
~ObsAuxCtlVecs()
template<typename MODEL > oops::ObsAuxCtlVecs< MODEL >::~ObsAuxCtlVecs
Destructor.
Definition at line 131 of file ObsAuxCtlVecs.h.
{
   Log::trace() << "ObsAuxCtlVecs<MODEL>::~ObsAuxCtlVecs starting" << std::endl;
   for (std::size_t jobs = 0; jobs < ctlvecs_.size(); ++jobs)
     ctlvecs_[jobs].reset();
   Log::trace() << "ObsAuxCtlVecs<MODEL>::~ObsAuxCtlVecs done" << std::endl;
 }
Member Function Documentation
axpy()
template<typename MODEL > void oops::ObsAuxCtlVecs< MODEL >::axpy (const double & zz, const ObsAuxCtlVecs< MODEL > & dx)
\(dv_1 = dv_1 * c dv_2 \)
Definition at line 194 of file ObsAuxCtlVecs.h.
{
   Log::trace() << "ObsAuxCtlVecs<MODEL>::axpy starting" << std::endl;
   ASSERT(size() == dx.size());
   for (std::size_t jobs = 0; jobs < size(); ++jobs) {
     ctlvecs_[jobs]->axpy(zz, dx[jobs]);
   }
   Log::trace() << "ObsAuxCtlVecs<MODEL>::axpy done" << std::endl;
 }
References oops::ObsAuxCtlVecs< MODEL >::size().
classname()
template<typename MODEL > static const std::string oops::ObsAuxCtlVecs< MODEL >::classname () inline static
Definition at line 43 of file ObsAuxCtlVecs.h.
 { return "oops::ObsAuxCtlVecs"; }
dot_product_with()
template<typename MODEL > double oops::ObsAuxCtlVecs< MODEL >::dot_product_with (const ObsAuxCtlVecs< MODEL > & dx) const
\(<dv_1,dv_1> = dv_1^T dv_1 \)
Definition at line 204 of file ObsAuxCtlVecs.h.
{
   Log::trace() << "ObsAuxCtlVecs<MODEL>::dot_product_with starting"
                << std::endl;
   ASSERT(size() == dx.size());
   double zz = static_cast<double>(0.0);
   for (std::size_t jobs = 0; jobs < size(); ++jobs) {
     zz += ctlvecs_[jobs]->dot_product_with(dx[jobs]);
   }
   Log::trace() << "ObsAuxCtlVecs<MODEL>::dot_product_with done" << std::endl;
   return zz;
 }
References oops::ObsAuxCtlVecs< MODEL >::size().
norm()
template<typename MODEL > double oops::ObsAuxCtlVecs< MODEL >::norm
L-2 norm.
Definition at line 239 of file ObsAuxCtlVecs.h.
{
   Log::trace() << "ObsAuxCtlVecs<MODEL>::norm starting" << std::endl;
   double zz = static_cast<double>(0.0);
   for (std::size_t jobs = 0; jobs < size(); ++jobs) {
     double norm = ctlvecs_[jobs]->norm();
     zz += norm * norm;
   }
   Log::trace() << "ObsAuxCtlVecs<MODEL>::norm done" << std::endl;
   return zz;
 }
operator*=()
template<typename MODEL > ObsAuxCtlVecs< MODEL > & oops::ObsAuxCtlVecs< MODEL >::operator*= (const double & zz)
\(dv_1 = dv_1 * c \)
Definition at line 184 of file ObsAuxCtlVecs.h.
{
   Log::trace() << "ObsAuxCtlVecs<MODEL>::operator*= starting" << std::endl;
   for (std::size_t jobs = 0; jobs < size(); ++jobs) {
     *ctlvecs_[jobs] *= zz;
   }
   Log::trace() << "ObsAuxCtlVecs<MODEL>::operator*= done" << std::endl;
   return *this;
 }
operator+=()
template<typename MODEL > ObsAuxCtlVecs< MODEL > & oops::ObsAuxCtlVecs< MODEL >::operator+= (const ObsAuxCtlVecs< MODEL > & rhs)
\(dv_1 = dv_1 + dv_2 \)
Definition at line 160 of file ObsAuxCtlVecs.h.
{
   Log::trace() << "ObsAuxCtlVecs<MODEL>::operator+= starting" << std::endl;
   ASSERT(size() == rhs.size());
   for (std::size_t jobs = 0; jobs < size(); ++jobs) {
     *ctlvecs_[jobs] += rhs[jobs];
   }
   Log::trace() << "ObsAuxCtlVecs<MODEL>::operator+= done" << std::endl;
   return *this;
 }
References oops::ObsAuxCtlVecs< MODEL >::size().
operator-=()
template<typename MODEL > ObsAuxCtlVecs< MODEL > & oops::ObsAuxCtlVecs< MODEL >::operator-= (const ObsAuxCtlVecs< MODEL > & rhs)
\(dv_1 = dv_1 - dv_2 \)
Definition at line 172 of file ObsAuxCtlVecs.h.
{
   Log::trace() << "ObsAuxCtlVecs<MODEL>::operator-= starting" << std::endl;
   ASSERT(size() == rhs.size());
   for (std::size_t jobs = 0; jobs < size(); ++jobs) {
     *ctlvecs_[jobs] -= rhs[jobs];
   }
   Log::trace() << "ObsAuxCtlVecs<MODEL>::operator-= done" << std::endl;
   return *this;
 }
References oops::ObsAuxCtlVecs< MODEL >::size().
operator=()
template<typename MODEL > ObsAuxCtlVecs< MODEL > & oops::ObsAuxCtlVecs< MODEL >::operator= (const ObsAuxCtlVecs< MODEL > & rhs)
\(dv_1 = dv_2 \)
Definition at line 148 of file ObsAuxCtlVecs.h.
{
   Log::trace() << "ObsAuxCtlVecs<MODEL>::operator= starting" << std::endl;
   ASSERT(size() == rhs.size());
   for (std::size_t jobs = 0; jobs < size(); ++jobs) {
     *ctlvecs_[jobs] = rhs[jobs];
   }
   Log::trace() << "ObsAuxCtlVecs<MODEL>::operator= done" << std::endl;
   return *this;
 }
References oops::ObsAuxCtlVecs< MODEL >::size().
operator[]() [1/2]
template<typename MODEL > ObsAuxCtlVec_& oops::ObsAuxCtlVecs< MODEL >::operator[] (const std::size_t ii) inline
Return a reference to the i-th ObsAuxControl object.
Definition at line 60 of file ObsAuxCtlVecs.h.
 { return *ctlvecs_.at(ii); }
References oops::ObsAuxCtlVecs< MODEL >::ctlvecs_.
operator[]() [2/2]
template<typename MODEL > const ObsAuxCtlVec_& oops::ObsAuxCtlVecs< MODEL >::operator[] (const std::size_t ii) const inline
Return a constant reference to the i-th ObsAuxControl object.
Definition at line 56 of file ObsAuxCtlVecs.h.
{
     return *ctlvecs_.at(ii);
   }
References oops::ObsAuxCtlVecs< MODEL >::ctlvecs_.
print()
template<typename MODEL > void oops::ObsAuxCtlVecs< MODEL >::print (std::ostream & os) const private
Definition at line 251 of file ObsAuxCtlVecs.h.
{
   for (std::size_t jobs = 0; jobs < ctlvecs_.size(); ++jobs)
     os << *ctlvecs_[jobs];
 }
read()
template<typename MODEL > void oops::ObsAuxCtlVecs< MODEL >::read (const eckit::Configuration & conf)
Read control vector.
Definition at line 217 of file ObsAuxCtlVecs.h.
{
   Log::trace() << "ObsAuxCtlVecs<MODEL>::read starting" << std::endl;
   std::vector<eckit::LocalConfiguration> obsconfs;
   conf.get("ctlvecsObsAux", obsconfs);
   ASSERT(ctlvecs_.size() >= obsconfs.size());
   for (std::size_t jobs = 0; jobs < obsconfs.size(); ++jobs)
     ctlvecs_[jobs]->read(obsconfs[jobs]);
   Log::trace() << "ObsAuxCtlVecs<MODEL>::read done" << std::endl;
 }
size()
template<typename MODEL > std::size_t oops::ObsAuxCtlVecs< MODEL >::size () const inline
Return the size.
Definition at line 62 of file ObsAuxCtlVecs.h.
 { return ctlvecs_.size(); }
References oops::ObsAuxCtlVecs< MODEL >::ctlvecs_.
Referenced by oops::ObsAuxCtlVecs< MODEL >::axpy(), oops::ObsAuxCtlVecs< MODEL >::dot_product_with(), oops::SQRTMinimizer< MODEL >::enforceObsAuxFormulation(), oops::ObsAuxCovariances< MODEL >::multiplySqrt(), oops::ObsAuxCovariances< MODEL >::multiplySqrtTrans(), oops::ObsAuxCtlVecs< MODEL >::ObsAuxCtlVecs(), oops::ObsAuxCtlVecs< MODEL >::operator+=(), oops::ObsAuxCtlVecs< MODEL >::operator-=(), and oops::ObsAuxCtlVecs< MODEL >::operator=().
write()
template<typename MODEL > void oops::ObsAuxCtlVecs< MODEL >::write (const eckit::Configuration & conf) const
Write control vector.
Definition at line 228 of file ObsAuxCtlVecs.h.
{
   Log::trace() << "ObsAuxCtlVecs<MODEL>::write starting" << std::endl;
   std::vector<eckit::LocalConfiguration> obsconfs;
   conf.get("ctlvecsObsAux", obsconfs);
   ASSERT(ctlvecs_.size() >= obsconfs.size());
   for (std::size_t jobs = 0; jobs < obsconfs.size(); ++jobs)
     ctlvecs_[jobs]->write(obsconfs[jobs]);
   Log::trace() << "ObsAuxCtlVecs<MODEL>::write done" << std::endl;
 }
zero()
template<typename MODEL > void oops::ObsAuxCtlVecs< MODEL >::zero
\(dv_1 = 0 \)
Definition at line 139 of file ObsAuxCtlVecs.h.
{
   Log::trace() << "ObsAuxCtlVecs<MODEL>::zero starting" << std::endl;
   for (std::size_t jobs = 0; jobs < size(); ++jobs) {
     ctlvecs_[jobs]->zero();
   }
   Log::trace() << "ObsAuxCtlVecs<MODEL>::zero done" << std::endl;
 }
Referenced by oops::SQRTMinimizer< MODEL >::enforceObsAuxFormulation(), oops::BMatrix< MODEL >::multiplyB(), and oops::BMatrix< MODEL >::multiplyId().
Member Data Documentation
ctlvecs_
template<typename MODEL > std::vector<std::shared_ptr<ObsAuxCtlVec_> > oops::ObsAuxCtlVecs< MODEL >::ctlvecs_ private
Vector of shared pointers to ObsAuxCtlVec objects.
Definition at line 92 of file ObsAuxCtlVecs.h.
Referenced by oops::ObsAuxCtlVecs< MODEL >::ObsAuxCtlVecs(), oops::ObsAuxCtlVecs< MODEL >::operator[](), and oops::ObsAuxCtlVecs< MODEL >::size().
The documentation for this class was generated from the following file:
src/oops/base/ObsAuxCtlVecs.h