OOPS Documentation: oops::ObsAuxControl< MODEL > Class Template Reference
oops::ObsAuxControl< MODEL > Class Template Reference
Encapsulates auxiliary observation space components of ControlVariable.
#include <ObsAuxControl.h>
Public Member Functions
ObsAuxControl (const ObservationSpace_ &, const eckit::Configuration &)
Constructor.
ObsAuxControl (const ObsAuxControl &, const bool copy=true)
Copy constructor.
~ObsAuxControl ()
Destructor.
void reset (const ObservationSpace_ &, const std::string &, const eckit::Configuration &)
Reset.
void read (const eckit::Configuration &)
Read control variable.
void write (const eckit::Configuration &) const
Write control variable.
double norm () const
L-2 norm.
const ObsAuxControlBase_ & obsauxcontrol (const std::string &id) const
Return a constant reference to the model specific object.
ObsAuxControlBase_ & obsauxcontrol (const std::string &id)
Return a reference to the model specific object.
const ObsAuxControlPtrMap_ & obsauxcontrol () const
Return a constant reference to the map of model specific objects.
ObsAuxControlPtrMap_ & obsauxcontrol ()
Return a reference to the map of model specific objects.
Static Public Member Functions
static const std::string classname ()
Private Types
using ObsAuxControlBase_ = ObsAuxControlBase< MODEL >
using ObservationSpace_ = ObservationSpace< MODEL >
using ObsAuxControlPtrMap_ = std::map< std::string, std::unique_ptr< ObsAuxControlBase_ > >
using iter_ = typename ObsAuxControlPtrMap_::iterator
using icst_ = typename ObsAuxControlPtrMap_::const_iterator
Private Member Functions
ObsAuxControl & operator= (const ObsAuxControl &)
const ObsAuxControlBase_ & get (const std::string &) const
Return a constant reference to the model specific object.
ObsAuxControlBase_ & get (const std::string &)
Return a reference to the model specific object.
void print (std::ostream &) const
Private Attributes
size_t size_
Number of model specific objects.
ObsAuxControlPtrMap_ ctls_
Map of pointers to model specific objects.
Detailed Description
template<typename MODEL>
class oops::ObsAuxControl< MODEL >
Encapsulates auxiliary observation space components of ControlVariable.
This class provides operations associated with the auxiliary observation
space components (e.g. VarBC, TOVSC) of ControlVariable. It contains a vector of ObsAuxControlBase objects, where ObsAuxControlBase is a base class for model specific (or potentially generic) classes.
ObsAuxControls class wraps around a vector of ObsAuxControl objects and is part of ControlVariable. Refer to the documentation of ControlVariable and CostJo to understand the structure.
Definition at line 52 of file ObsAuxControl.h.
Member Typedef Documentation
icst_
template<typename MODEL > using oops::ObsAuxControl< MODEL >::icst_ = typename ObsAuxControlPtrMap_::const_iterator private
Definition at line 59 of file ObsAuxControl.h.
iter_
template<typename MODEL > using oops::ObsAuxControl< MODEL >::iter_ = typename ObsAuxControlPtrMap_::iterator private
Definition at line 58 of file ObsAuxControl.h.
ObsAuxControlBase_
template<typename MODEL > using oops::ObsAuxControl< MODEL >::ObsAuxControlBase_ = ObsAuxControlBase<MODEL> private
Definition at line 54 of file ObsAuxControl.h.
ObsAuxControlPtrMap_
template<typename MODEL > using oops::ObsAuxControl< MODEL >::ObsAuxControlPtrMap_ = std::map<std::string, std::unique_ptr<ObsAuxControlBase_> > private
Definition at line 57 of file ObsAuxControl.h.
ObservationSpace_
template<typename MODEL > using oops::ObsAuxControl< MODEL >::ObservationSpace_ = ObservationSpace<MODEL> private
Definition at line 55 of file ObsAuxControl.h.
Constructor & Destructor Documentation
ObsAuxControl() [1/2]
template<typename MODEL > oops::ObsAuxControl< MODEL >::ObsAuxControl (const ObservationSpace_ & os, const eckit::Configuration & conf)
Constructor.
Definition at line 113 of file ObsAuxControl.h.
     : size_(0), ctls_() {
   Log::trace() << "ObsAuxControl<MODEL>::ObsAuxControl starting" << std::endl;
   util::Timer timer(classname(), "ObsAuxControl");
   std::vector<eckit::LocalConfiguration> confs;
   if (conf.has("stateObsAux")) conf.get("stateObsAux", confs);
   size_ = confs.size();
   for (auto const &config : confs) {
     std::string key(config.getString("type"));
     std::unique_ptr<ObsAuxControlBase<MODEL>> auxctl(
         ObsAuxControlFactory<MODEL>::create(os, config));
     ctls_.emplace(key, std::move(auxctl));
   }
   Log::trace() << "ObsAuxControl<MODEL>::ObsAuxControl done" << std::endl;
 }
References oops::ObsAuxControl< MODEL >::classname(), oops::ObsAuxControl< MODEL >::ctls_, and oops::ObsAuxControl< MODEL >::size_.
ObsAuxControl() [2/2]
template<typename MODEL > oops::ObsAuxControl< MODEL >::ObsAuxControl (const ObsAuxControl< MODEL > & other, const bool copy = true) explicit
Copy constructor.
Definition at line 135 of file ObsAuxControl.h.
     : size_(other.size_), ctls_() {
   Log::trace() << "ObsAuxControl<MODEL>::ObsAuxControl starting" << std::endl;
   util::Timer timer(classname(), "ObsAuxControl");
   for (icst_ it = other.ctls_.begin(); it != other.ctls_.end(); ++it) {
     std::string incname = it->first;
     std::unique_ptr<ObsAuxControlBase<MODEL>> auxctl(it->second->clone(copy));
     ctls_.emplace(incname, std::move(auxctl));
   }
   Log::trace() << "ObsAuxControl<MODEL>::ObsAuxControl done" << std::endl;
 }
References oops::ObsAuxControl< MODEL >::classname(), and oops::ObsAuxControl< MODEL >::ctls_.
~ObsAuxControl()
template<typename MODEL > oops::ObsAuxControl< MODEL >::~ObsAuxControl
Destructor.
Definition at line 150 of file ObsAuxControl.h.
{
   Log::trace() << "ObsAuxControl<MODEL>::~ObsAuxControl starting" << std::endl;
   util::Timer timer(classname(), "~ObsAuxControl");
   Log::trace() << "ObsAuxControl<MODEL>::~ObsAuxControl done" << std::endl;
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::ObsAuxControl< MODEL >::classname () inline static
Definition at line 62 of file ObsAuxControl.h.
 { return "oops::ObsAuxControl"; }
Referenced by oops::ObsAuxControl< MODEL >::ObsAuxControl().
get() [1/2]
template<typename MODEL > ObsAuxControlBase< MODEL > & oops::ObsAuxControl< MODEL >::get (const std::string & id) private
Return a reference to the model specific object.
Definition at line 159 of file ObsAuxControl.h.
{
   iter_ it = ctls_.find(id);
   ASSERT(it != ctls_.end());
   return *it->second;
 }
get() [2/2]
template<typename MODEL > const ObsAuxControlBase< MODEL > & oops::ObsAuxControl< MODEL >::get (const std::string & id) const private
Return a constant reference to the model specific object.
Definition at line 168 of file ObsAuxControl.h.
{
   icst_ it = ctls_.find(id);
   ASSERT(it != ctls_.end());
   return *it->second;
 }
Referenced by oops::ObsAuxControl< MODEL >::obsauxcontrol().
norm()
template<typename MODEL > double oops::ObsAuxControl< MODEL >::norm
L-2 norm.
Definition at line 237 of file ObsAuxControl.h.
{
   Log::trace() << "ObsAuxControl<MODEL>::norm starting" << std::endl;
   util::Timer timer(classname(), "norm");
   double zz = 0.0;
   for (icst_ it = ctls_.begin(); it != ctls_.end(); ++it) {
     double norm = it->second->norm();
     zz += norm * norm;
   }
   Log::trace() << "ObsAuxControl<MODEL>::norm done" << std::endl;
   return std::sqrt(zz);
 }
obsauxcontrol() [1/4]
template<typename MODEL > ObsAuxControlPtrMap_& oops::ObsAuxControl< MODEL >::obsauxcontrol () inline
Return a reference to the map of model specific objects.
Definition at line 96 of file ObsAuxControl.h.
 { return ctls_; }
References oops::ObsAuxControl< MODEL >::ctls_.
obsauxcontrol() [2/4]
template<typename MODEL > const ObsAuxControlPtrMap_& oops::ObsAuxControl< MODEL >::obsauxcontrol () const inline
Return a constant reference to the map of model specific objects.
Definition at line 94 of file ObsAuxControl.h.
 { return ctls_; }
References oops::ObsAuxControl< MODEL >::ctls_.
obsauxcontrol() [3/4]
template<typename MODEL > ObsAuxControlBase_& oops::ObsAuxControl< MODEL >::obsauxcontrol (const std::string & id) inline
Return a reference to the model specific object.
Definition at line 89 of file ObsAuxControl.h.
{
     return this->get(id);
   }
References oops::ObsAuxControl< MODEL >::get().
obsauxcontrol() [4/4]
template<typename MODEL > const ObsAuxControlBase_& oops::ObsAuxControl< MODEL >::obsauxcontrol (const std::string & id) const inline
Return a constant reference to the model specific object.
Definition at line 85 of file ObsAuxControl.h.
{
     return this->get(id);
   }
References oops::ObsAuxControl< MODEL >::get().
Referenced by oops::ObsAuxIncrement< MODEL >::diff(), oops::ObsAuxCovariance< MODEL >::linearize(), oops::ObsOperator< MODEL >::obsBiasEquiv(), oops::ObsOperator< MODEL >::obsEquiv(), oops::operator+=(), oops::LinearObsOperator< MODEL >::setTrajectory(), and oops::ObsAuxCovariance< MODEL >::update().
operator=()
template<typename MODEL > ObsAuxControl& oops::ObsAuxControl< MODEL >::operator= (const ObsAuxControl< MODEL > &) private
print()
template<typename MODEL > void oops::ObsAuxControl< MODEL >::print (std::ostream & os) const private
Definition at line 252 of file ObsAuxControl.h.
{
   Log::trace() << "ObsAuxControl<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   for (icst_ it = ctls_.begin(); it != ctls_.end(); ++it) {
     os << it->first << ": " << *it->second;
   }
   Log::trace() << "ObsAuxControl<MODEL>::print done" << std::endl;
 }
read()
template<typename MODEL > void oops::ObsAuxControl< MODEL >::read (const eckit::Configuration & conf)
Read control variable.
Definition at line 201 of file ObsAuxControl.h.
{
   Log::trace() << "ObsAuxControl<MODEL>::read starting" << std::endl;
   util::Timer timer(classname(), "read");
   std::vector<eckit::LocalConfiguration> confs;
   if (conf.has("stateObsAux")) conf.get("stateObsAux", confs);
   for (iter_ it = ctls_.begin(); it != ctls_.end(); ++it) {
     for (auto const &config : confs) {
       if (config.getString("type") == it->first) it->second->read(config);
     }
   }
   Log::trace() << "ObsAuxControl<MODEL>::read done" << std::endl;
 }
reset()
template<typename MODEL > void oops::ObsAuxControl< MODEL >::reset (const ObservationSpace_ & os, const std::string & stateid, const eckit::Configuration & conf)
Reset.
Definition at line 178 of file ObsAuxControl.h.
{
   Log::trace() << "ObsAuxControl<MODEL>::reset starting" << std::endl;
   util::Timer timer(classname(), "reset");
   std::vector<eckit::LocalConfiguration> confs;
   if (conf.has("stateObsAuxReset")) {
     conf.get("stateObsAuxReset", confs);
   }
   for (iter_ it = ctls_.begin(); it != ctls_.end(); ++it) {
     for (auto const &config : confs) {
       if (config.getString("type") == it->first)
         it->second->reset(os, stateid, config);
     }
   }
   Log::trace() << "ObsAuxControl<MODEL>::reset done" << std::endl;
 }
write()
template<typename MODEL > void oops::ObsAuxControl< MODEL >::write (const eckit::Configuration & conf) const
Write control variable.
Definition at line 219 of file ObsAuxControl.h.
{
   Log::trace() << "ObsAuxControl<MODEL>::write starting" << std::endl;
   util::Timer timer(classname(), "write");
   std::vector<eckit::LocalConfiguration> confs;
   if (conf.has("stateObsAux")) conf.get("stateObsAux", confs);
   for (icst_ it = ctls_.begin(); it != ctls_.end(); ++it) {
     for (auto const &config : confs) {
       if (config.getString("type") == it->first) it->second->write(config);
     }
   }
   Log::trace() << "ObsAuxControl<MODEL>::write done" << std::endl;
 }
Member Data Documentation
ctls_
template<typename MODEL > ObsAuxControlPtrMap_ oops::ObsAuxControl< MODEL >::ctls_ private
Map of pointers to model specific objects.
Definition at line 107 of file ObsAuxControl.h.
Referenced by oops::ObsAuxControl< MODEL >::ObsAuxControl(), and oops::ObsAuxControl< MODEL >::obsauxcontrol().
size_
template<typename MODEL > size_t oops::ObsAuxControl< MODEL >::size_ mutable private
Number of model specific objects.
Definition at line 106 of file ObsAuxControl.h.
Referenced by oops::ObsAuxControl< MODEL >::ObsAuxControl().
The documentation for this class was generated from the following file:
src/oops/interface/ObsAuxControl.h