OOPS Documentation: oops::HBHtMatrix< MODEL > Class Template Reference
oops::HBHtMatrix< MODEL > Class Template Reference
The \(H B H^T \) matrix.
#include <HBHtMatrix.h>
Public Member Functions
HBHtMatrix (const CostFct_ &j, const bool test=false)
void multiply (const Dual_ &dy, Dual_ &dz) const
Private Types
using Increment_ = Increment< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using CostFct_ = CostFunction< MODEL >
using Dual_ = DualVector< MODEL >
Private Attributes
CostFct_ const & j_
bool test_
int iter_
Detailed Description
template<typename MODEL>
class oops::HBHtMatrix< MODEL >
The \(H B H^T \) matrix.
The solvers represent matrices as objects that implement a "multiply" method. This class defines objects that apply a generalized \(H B H ^T\) matrix which includes \(H \) and the equivalent operators for the other terms of the cost function.
Definition at line 36 of file HBHtMatrix.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::HBHtMatrix< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 39 of file HBHtMatrix.h.
CtrlInc_
template<typename MODEL > using oops::HBHtMatrix< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 38 of file HBHtMatrix.h.
Dual_
template<typename MODEL > using oops::HBHtMatrix< MODEL >::Dual_ = DualVector<MODEL> private
Definition at line 40 of file HBHtMatrix.h.
Increment_
template<typename MODEL > using oops::HBHtMatrix< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 37 of file HBHtMatrix.h.
Constructor & Destructor Documentation
HBHtMatrix()
template<typename MODEL > oops::HBHtMatrix< MODEL >::HBHtMatrix (const CostFct_ & j, const bool test = false) explicit
Definition at line 56 of file HBHtMatrix.h.
     : j_(j), test_(test), iter_(0) {}
Member Function Documentation
multiply()
template<typename MODEL > void oops::HBHtMatrix< MODEL >::multiply (const Dual_ & dy, Dual_ & dz) const
Definition at line 62 of file HBHtMatrix.h.
{
   // Increment counter
   iter_++;
   // Run ADJ
   CtrlInc_ ww(j_.jb());
   j_.zeroAD(ww);
   PostProcessorAD<Increment_> costad;
   for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
     costad.enrollProcessor(j_.jterm(jj).setupAD(dy.getv(jj), ww));
   }
   j_.runAD(ww, costad);
   // Multiply by B
   CtrlInc_ zz(j_.jb());
   j_.jb().multiplyB(ww, zz);
   // Run TLM
   PostProcessorTL<Increment_> costtl;
   for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
     costtl.enrollProcessor(j_.jterm(jj).setupTL(zz));
   }
   CtrlInc_ mzz(zz);
   j_.runTL(mzz, costtl);
   // Get TLM outputs
   dz.clear();
   for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
     dz.append(costtl.releaseOutputFromTL(jj));
   }
   if (test_) {
     // <G dx, dy >, where dx = B Gt dy
     double adj_tst_fwd = dot_product(dz, dy);
     // <  dx, Gt dy>, where dx = B Gt dy
     double adj_tst_bwd = dot_product(zz, ww);
     Log::info() << "Online adjoint test, iteration: " << iter_ << std::endl
                 << util::PrintAdjTest(adj_tst_fwd, adj_tst_bwd, "G")
                 << std::endl;
   }
 }
References oops::DualVector< MODEL >::append(), oops::DualVector< MODEL >::clear(), dot_product(), oops::PostProcessorAD< INCR >::enrollProcessor(), oops::PostProcessorTL< INCR >::enrollProcessor(), oops::DualVector< MODEL >::getv(), and oops::PostProcessorTL< INCR >::releaseOutputFromTL().
Referenced by oops::RPCGMinimizer< MODEL >::solve(), and oops::RPLanczosMinimizer< MODEL >::solve().
Member Data Documentation
iter_
template<typename MODEL > int oops::HBHtMatrix< MODEL >::iter_ mutable private
Definition at line 50 of file HBHtMatrix.h.
j_
template<typename MODEL > CostFct_ const& oops::HBHtMatrix< MODEL >::j_ private
Definition at line 48 of file HBHtMatrix.h.
test_
template<typename MODEL > bool oops::HBHtMatrix< MODEL >::test_ private
Definition at line 49 of file HBHtMatrix.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/HBHtMatrix.h