OOPS Documentation: oops::CostJcDFI< MODEL > Class Template Reference
oops::CostJcDFI< MODEL > Class Template Reference
Jc DFI Cost Function.
#include <CostJcDFI.h>
Public Member Functions
const std::string classname () const override
CostJcDFI (const eckit::Configuration &, const Geometry_ &, const util::DateTime &, const util::Duration &, const util::Duration &tstep=util::Duration(0))
Construct \(J_c\).
virtual ~CostJcDFI ()
Destructor.
std::shared_ptr< PostBase< State_ > > initialize (const CtrlVar_ &, const eckit::Configuration &) const override
Initialize before nonlinear model integration.
std::shared_ptr< PostBase< State_ > > initializeTraj (const CtrlVar_ &, const Geometry_ &, const eckit::Configuration &) override
double finalize (const eckit::Configuration &) const override
Finalize computation after nonlinear model integration.
double finalizeTraj (const eckit::Configuration &) override
Perform computation after the linearisation trajectory computation.
std::shared_ptr< PostBaseTL< Increment_ > > setupTL (const CtrlInc_ &) const override
Initialize \(J_c\) before starting the TL run.
std::shared_ptr< PostBaseAD< Increment_ > > setupAD (std::shared_ptr< const GeneralizedDepartures >, CtrlInc_ &) const override
Initialize \(J_c\) before starting the AD run.
Increment_ * multiplyCovar (const GeneralizedDepartures &) const override
Multiply by \(C\) and \(C^{-1}\).
Increment_ * multiplyCoInv (const GeneralizedDepartures &) const override
Multiply by inverse covariance (or weight) matrix.
Increment_ * newDualVector () const override
Provide new increment.
Increment_ * newDepartures () const override
Provide new departures (not relevant to JcDFI).
Increment_ * newGradientFG () const override
Gradient of \(J_c\) at first guess.
void resetLinearization () override
Reset trajectory.
void checkpoint (eckit::LocalConfiguration &) const
Checkpoint.
void restart (const eckit::Configuration &)
Restart.
Public Member Functions inherited from oops::CostTermBase< MODEL >
virtual ~CostTermBase ()
Destructor.
Private Types
using CtrlInc_ = ControlIncrement< MODEL >
using CtrlVar_ = ControlVariable< MODEL >
using Geometry_ = Geometry< MODEL >
using Increment_ = Increment< MODEL >
using JcCovar_ = JcCovar< MODEL >
using State_ = State< MODEL >
using Variables_ = Variables< MODEL >
Private Attributes
const eckit::LocalConfiguration conf_
const Geometry_ resol_
std::unique_ptr< Geometry_ > tlres_
bool ltraj_
util::DateTime vt_
util::Duration span_
const util::Duration tstep_
util::Duration tlstep_
double alpha_
std::unique_ptr< Increment_ > xdep_
std::unique_ptr< Increment_ > gradFG_
std::unique_ptr< WeightingFct > wfct_
std::unique_ptr< WeightingFct > wfcttraj_
std::shared_ptr< WeightedDiff< MODEL, Increment_, State_ > > filter_
std::shared_ptr< WeightedDiff< MODEL, Increment_, State_ > > filtertraj_
std::unique_ptr< JcCovar_ > jccov_
std::unique_ptr< eckit::LocalConfiguration > jcovconf_
Detailed Description
template<typename MODEL>
class oops::CostJcDFI< MODEL >
Jc DFI Cost Function.
Digital filter based constraint term for the cost function.
Definition at line 49 of file CostJcDFI.h.
Member Typedef Documentation
CtrlInc_
template<typename MODEL > using oops::CostJcDFI< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 50 of file CostJcDFI.h.
CtrlVar_
template<typename MODEL > using oops::CostJcDFI< MODEL >::CtrlVar_ = ControlVariable<MODEL> private
Definition at line 51 of file CostJcDFI.h.
Geometry_
template<typename MODEL > using oops::CostJcDFI< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 52 of file CostJcDFI.h.
Increment_
template<typename MODEL > using oops::CostJcDFI< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 53 of file CostJcDFI.h.
JcCovar_
template<typename MODEL > using oops::CostJcDFI< MODEL >::JcCovar_ = JcCovar<MODEL> private
Definition at line 54 of file CostJcDFI.h.
State_
template<typename MODEL > using oops::CostJcDFI< MODEL >::State_ = State<MODEL> private
Definition at line 55 of file CostJcDFI.h.
Variables_
template<typename MODEL > using oops::CostJcDFI< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 56 of file CostJcDFI.h.
Constructor & Destructor Documentation
CostJcDFI()
template<typename MODEL > oops::CostJcDFI< MODEL >::CostJcDFI (const eckit::Configuration & conf, const Geometry_ & resol, const util::DateTime & vt, const util::Duration & span, const util::Duration & tstep = util::Duration(0))
Construct \(J_c\).
Definition at line 140 of file CostJcDFI.h.
     : conf_(conf),
       resol_(resol),
       tlres_(),
       ltraj_(false),
       vt_(vt),
       span_(span),
       tstep_(tstep),
       tlstep_(),
       alpha_(0),
       xdep_(),
       gradFG_(),
       wfct_(),
       wfcttraj_(),
       filter_(),
       filtertraj_() {
   alpha_ = conf.getDouble("alpha");
   if (conf.has("ftime")) vt_ = util::DateTime(conf.getString("ftime"));
   if (conf.has("span")) span_ = util::Duration(conf.getString("span"));
   if (conf.has("covariance"))
     jcovconf_.reset(new eckit::LocalConfiguration(conf, "covariance"));
   //  wfct_.reset(WeightFactory::create(config)); YT
   wfct_.reset(new DolphChebyshev(conf_));
   wfcttraj_.reset(new DolphChebyshev(conf_));
   Log::debug() << "CostJcDFI created vt = " << vt_ << ", span = " << span_
                << std::endl;
   Log::trace() << "CostJcDFI created" << std::endl;
 }
References oops::CostJcDFI< MODEL >::alpha_, oops::CostJcDFI< MODEL >::conf_, oops::CostJcDFI< MODEL >::jcovconf_, oops::CostJcDFI< MODEL >::span_, oops::CostJcDFI< MODEL >::vt_, oops::CostJcDFI< MODEL >::wfct_, and oops::CostJcDFI< MODEL >::wfcttraj_.
~CostJcDFI()
template<typename MODEL > virtual oops::CostJcDFI< MODEL >::~CostJcDFI () inline virtual
Destructor.
Definition at line 67 of file CostJcDFI.h.
 {}
Member Function Documentation
checkpoint()
template<typename MODEL > void oops::CostJcDFI< MODEL >::checkpoint (eckit::LocalConfiguration &) const inline virtual
Checkpoint.
Implements oops::CostTermBase< MODEL >.
Definition at line 107 of file CostJcDFI.h.
 {}
classname()
template<typename MODEL > const std::string oops::CostJcDFI< MODEL >::classname () const inline override virtual
Implements oops::CostTermBase< MODEL >.
Definition at line 59 of file CostJcDFI.h.
 { return "JcDFI"; }
finalize()
template<typename MODEL > double oops::CostJcDFI< MODEL >::finalize (const eckit::Configuration &) const override virtual
Finalize computation after nonlinear model integration.
Implements oops::CostTermBase< MODEL >.
Definition at line 188 of file CostJcDFI.h.
{
   double zz = 0.5 * alpha_;
   std::unique_ptr<Increment_> dx(filter_->releaseDiff());
   std::unique_ptr<Increment_> dxnorm(new Increment_(*dx));
   if (jcovconf_) {
     jccov_->inverseMultiply(*dx, *dxnorm);
   }
   zz *= dot_product(*dx, *dxnorm);
   filter_.reset();
   Log::test() << "CostJcDFI: Nonlinear Jc = " << zz << std::endl;
   return zz;
 }
References dot_product().
finalizeTraj()
template<typename MODEL > double oops::CostJcDFI< MODEL >::finalizeTraj (const eckit::Configuration &) override virtual
Perform computation after the linearisation trajectory computation.
Implements oops::CostTermBase< MODEL >.
Definition at line 222 of file CostJcDFI.h.
{
   ASSERT(ltraj_ == true);
   xdep_.reset(filtertraj_->releaseDiff());
   bool lresetGradFG = false;
   if (conf_.has("resetGradFG")) lresetGradFG = conf_.getBool("resetGradFG");
   double zz = 0.;
   if (lresetGradFG) {
     gradFG_.reset(new Increment_(*xdep_));
     xdep_->zero();
     gradFG_->zero();
   } else {
     *xdep_ *= -1.0;
     gradFG_.reset(this->multiplyCoInv(*xdep_));
     zz = 0.5 * dot_product(*xdep_, *gradFG_);
   }
   ltraj_ = false;
   filtertraj_.reset();
   Log::info() << "CostJcDFI: Nonlinear Jc (traj) = " << zz << std::endl;
   return zz;
 }
References dot_product().
initialize()
template<typename MODEL > std::shared_ptr< PostBase< State< MODEL > > > oops::CostJcDFI< MODEL >::initialize (const CtrlVar_ & x, const eckit::Configuration &) const override virtual
Initialize before nonlinear model integration.
Implements oops::CostTermBase< MODEL >.
Definition at line 175 of file CostJcDFI.h.
{
   filter_.reset(new WeightedDiff<MODEL, Increment_, State_>(
       vt_, span_, resol_, conf_, tstep_, *wfct_));
   if (jcovconf_)
     jccov_.reset(
         new JcCovar_(x.state()[0], x.state()[0].geometry(), *jcovconf_));
   return filter_;
 }
References oops::ControlVariable< MODEL >::state().
initializeTraj()
template<typename MODEL > std::shared_ptr< PostBase< State< MODEL > > > oops::CostJcDFI< MODEL >::initializeTraj (const CtrlVar_ & , const Geometry_ & , const eckit::Configuration &) override virtual
Return a post-processor to be attached to the linearisation trajectory computation
Implements oops::CostTermBase< MODEL >.
Definition at line 204 of file CostJcDFI.h.
{
   ltraj_ = true;
   tlres_.reset(new Geometry_(tlres));
   tlstep_ = util::Duration(innerConf.getString("linearmodel.tstep"));
   filtertraj_.reset(new WeightedDiff<MODEL, Increment_, State_>(vt_, span_, *tlres_,
                                                                 conf_, tlstep_, *wfcttraj_));
   if (jcovconf_) {
     if (!jccov_.get()) jccov_.reset(new JcCovar_(x.state()[0], x.state()[0].geometry(), *jcovconf_));
     jccov_->linearize(x.state()[0], tlres);
   }
   return filtertraj_;
 }
References oops::ControlVariable< MODEL >::state().
multiplyCoInv()
template<typename MODEL > Increment< MODEL > * oops::CostJcDFI< MODEL >::multiplyCoInv (const GeneralizedDepartures &) const override virtual
Multiply by inverse covariance (or weight) matrix.
Implements oops::CostTermBase< MODEL >.
Definition at line 291 of file CostJcDFI.h.
{
   const Increment_ &dx1 = dynamic_cast<const Increment_ &>(dv1);
   Increment_ *dx2 = new Increment_(dx1);
   if (jcovconf_) jccov_->inverseMultiply(dx1, *dx2);
   *dx2 *= alpha_;
   double zz = dot_product(dx1, *dx2);
   Log::info() << "CostJcDFI: multiplyCoInv norm = " << zz << std::endl;
   return dx2;
 }
References dot_product().
multiplyCovar()
template<typename MODEL > Increment< MODEL > * oops::CostJcDFI< MODEL >::multiplyCovar (const GeneralizedDepartures & dv1) const override virtual
Multiply by \(C\) and \(C^{-1}\).
Implements oops::CostTermBase< MODEL >.
Definition at line 278 of file CostJcDFI.h.
{
   const Increment_ &dx1 = dynamic_cast<const Increment_ &>(dv1);
   Increment_ *dx2 = new Increment_(dx1);
   if (jcovconf_) jccov_->multiply(dx1, *dx2);
   const double za = 1.0 / alpha_;
   *dx2 *= za;
   return dx2;
 }
newDepartures()
template<typename MODEL > Increment_* oops::CostJcDFI< MODEL >::newDepartures () const inline override virtual
Provide new departures (not relevant to JcDFI).
Implements oops::CostTermBase< MODEL >.
Definition at line 96 of file CostJcDFI.h.
 { return new Increment_(*xdep_); }
References oops::CostJcDFI< MODEL >::xdep_.
newDualVector()
template<typename MODEL > Increment< MODEL > * oops::CostJcDFI< MODEL >::newDualVector override virtual
Provide new increment.
Implements oops::CostTermBase< MODEL >.
Definition at line 246 of file CostJcDFI.h.
{
   Variables_ vars(conf_);
   Increment_ *dx = new Increment_(*tlres_, vars, vt_);
   return dx;
 }
newGradientFG()
template<typename MODEL > Increment_* oops::CostJcDFI< MODEL >::newGradientFG () const inline override virtual
Gradient of \(J_c\) at first guess.
Implements oops::CostTermBase< MODEL >.
Definition at line 99 of file CostJcDFI.h.
{
     return new Increment_(*gradFG_);
   }
References oops::CostJcDFI< MODEL >::gradFG_.
resetLinearization()
template<typename MODEL > void oops::CostJcDFI< MODEL >::resetLinearization override virtual
Reset trajectory.
Implements oops::CostTermBase< MODEL >.
Definition at line 305 of file CostJcDFI.h.
{
   gradFG_.reset();
 }
restart()
template<typename MODEL > void oops::CostJcDFI< MODEL >::restart (const eckit::Configuration &) inline virtual
Restart.
Implements oops::CostTermBase< MODEL >.
Definition at line 110 of file CostJcDFI.h.
 {}
setupAD()
template<typename MODEL > std::shared_ptr< PostBaseAD< Increment< MODEL > > > oops::CostJcDFI< MODEL >::setupAD (std::shared_ptr< const GeneralizedDepartures > pv, CtrlInc_ &) const override virtual
Initialize \(J_c\) before starting the AD run.
Implements oops::CostTermBase< MODEL >.
Definition at line 266 of file CostJcDFI.h.
{
   std::shared_ptr<const Increment_> dx =
       std::dynamic_pointer_cast<const Increment_>(pv);
   std::shared_ptr<WeightedDiffAD<Increment_> > filterAD(
       new WeightedDiffAD<Increment_>(vt_, span_, tlstep_, *wfcttraj_, dx));
   return filterAD;
 }
setupTL()
template<typename MODEL > std::shared_ptr< PostBaseTL< Increment< MODEL > > > oops::CostJcDFI< MODEL >::setupTL (const CtrlInc_ &) const override virtual
Initialize \(J_c\) before starting the TL run.
Implements oops::CostTermBase< MODEL >.
Definition at line 255 of file CostJcDFI.h.
{
   std::shared_ptr<WeightedDiffTL<MODEL, Increment_> > filterTL(
       new WeightedDiffTL<MODEL, Increment_>(vt_, span_, *tlres_, conf_, tlstep_,
                                             *wfcttraj_));
   return filterTL;
 }
Member Data Documentation
alpha_
template<typename MODEL > double oops::CostJcDFI< MODEL >::alpha_ private
Definition at line 124 of file CostJcDFI.h.
Referenced by oops::CostJcDFI< MODEL >::CostJcDFI().
conf_
template<typename MODEL > const eckit::LocalConfiguration oops::CostJcDFI< MODEL >::conf_ private
Definition at line 113 of file CostJcDFI.h.
Referenced by oops::CostJcDFI< MODEL >::CostJcDFI().
filter_
template<typename MODEL > std::shared_ptr<WeightedDiff<MODEL, Increment_, State_> > oops::CostJcDFI< MODEL >::filter_ mutable private
Definition at line 131 of file CostJcDFI.h.
filtertraj_
template<typename MODEL > std::shared_ptr<WeightedDiff<MODEL, Increment_, State_> > oops::CostJcDFI< MODEL >::filtertraj_ mutable private
Definition at line 132 of file CostJcDFI.h.
gradFG_
template<typename MODEL > std::unique_ptr<Increment_> oops::CostJcDFI< MODEL >::gradFG_ mutable private
Definition at line 127 of file CostJcDFI.h.
Referenced by oops::CostJcDFI< MODEL >::newGradientFG().
jccov_
template<typename MODEL > std::unique_ptr<JcCovar_> oops::CostJcDFI< MODEL >::jccov_ mutable private
Definition at line 133 of file CostJcDFI.h.
jcovconf_
template<typename MODEL > std::unique_ptr<eckit::LocalConfiguration> oops::CostJcDFI< MODEL >::jcovconf_ private
Definition at line 134 of file CostJcDFI.h.
Referenced by oops::CostJcDFI< MODEL >::CostJcDFI().
ltraj_
template<typename MODEL > bool oops::CostJcDFI< MODEL >::ltraj_ private
Definition at line 117 of file CostJcDFI.h.
resol_
template<typename MODEL > const Geometry_ oops::CostJcDFI< MODEL >::resol_ private
Definition at line 114 of file CostJcDFI.h.
span_
template<typename MODEL > util::Duration oops::CostJcDFI< MODEL >::span_ private
Definition at line 120 of file CostJcDFI.h.
Referenced by oops::CostJcDFI< MODEL >::CostJcDFI().
tlres_
template<typename MODEL > std::unique_ptr<Geometry_> oops::CostJcDFI< MODEL >::tlres_ private
Definition at line 115 of file CostJcDFI.h.
tlstep_
template<typename MODEL > util::Duration oops::CostJcDFI< MODEL >::tlstep_ private
Definition at line 122 of file CostJcDFI.h.
tstep_
template<typename MODEL > const util::Duration oops::CostJcDFI< MODEL >::tstep_ private
Definition at line 121 of file CostJcDFI.h.
vt_
template<typename MODEL > util::DateTime oops::CostJcDFI< MODEL >::vt_ private
Definition at line 119 of file CostJcDFI.h.
Referenced by oops::CostJcDFI< MODEL >::CostJcDFI().
wfct_
template<typename MODEL > std::unique_ptr<WeightingFct> oops::CostJcDFI< MODEL >::wfct_ private
Definition at line 129 of file CostJcDFI.h.
Referenced by oops::CostJcDFI< MODEL >::CostJcDFI().
wfcttraj_
template<typename MODEL > std::unique_ptr<WeightingFct> oops::CostJcDFI< MODEL >::wfcttraj_ private
Definition at line 130 of file CostJcDFI.h.
Referenced by oops::CostJcDFI< MODEL >::CostJcDFI().
xdep_
template<typename MODEL > std::unique_ptr<Increment_> oops::CostJcDFI< MODEL >::xdep_ mutable private
Definition at line 126 of file CostJcDFI.h.
Referenced by oops::CostJcDFI< MODEL >::newDepartures().
The documentation for this class was generated from the following file:
src/oops/assimilation/CostJcDFI.h