OOPS Documentation: oops::EnsembleCovariance4DWithChangeOfVariable< MODEL > Class Template Reference
oops::EnsembleCovariance4DWithChangeOfVariable< MODEL > Class Template Reference
#include <EnsembleCovariance4DWithChangeOfVariable.h>
Public Member Functions
EnsembleCovariance4DWithChangeOfVariable (const Geometry_ &, const Variables_ &, const eckit::Configuration &, const State4D_ &)
void advectedLinearize (const State4D_ &, const Geometry_ &, const eckit::Configuration &)
void advectedMultiply (const Increment4D_ &, Increment4D_ &) const
void advectedMultiplySqrt (const IncrCtlVec_ &, Increment4D_ &) const
void advectedMultiplySqrtTrans (const Increment4D_ &, IncrCtlVec_ &) const
void advectedInverseMultiply (const Increment4D_ &, Increment4D_ &) const
const ModelSpaceCovarianceBase< MODEL > & covar () const
IncrModCtlVec_ * newIncrModCtlVec () const override
IncrEnsCtlVec_ * newIncrEnsCtlVec () const override
Public Member Functions inherited from oops::ModelSpaceCovariance4DBase< MODEL >
ModelSpaceCovariance4DBase (const Geometry_ &, const eckit::Configuration &config)
virtual ~ModelSpaceCovariance4DBase ()
void linearize (const State4D_ &xb, const Geometry_ &resol, const eckit::Configuration &config)
virtual void multiply (const Increment4D_ &dxi, Increment4D_ &dxo) const
virtual void multiplySqrt (const IncrCtlVec_ &dvi, Increment4D_ &dxo) const
virtual void multiplySqrtTrans (const Increment4D_ &dxi, IncrCtlVec_ &dvo) const
void inverseMultiply (const Increment4D_ &dxi, Increment4D_ &dxo) const
virtual void randomize (Increment4D_ &) const
Private Types
using Geometry_ = Geometry< MODEL >
using Variables_ = Variables< MODEL >
using Increment_ = Increment< MODEL >
using State4D_ = State4D< MODEL >
using Increment4D_ = Increment4D< MODEL >
using IncrCtlVec_ = IncrCtlVec< MODEL >
using IncrEnsCtlVec_ = IncrEnsCtlVec< MODEL >
using IncrModCtlVec_ = IncrModCtlVec< MODEL >
using Ensemble_ = Ensemble< MODEL >
using Localization_ = Localization< MODEL >
using EnsemblePtr_ = std::shared_ptr< Ensemble< MODEL > >
using EnsemblesCollection_ = EnsemblesCollection< MODEL >
using GenericMatrix_ = GenericMatrix< MODEL >
using MatrixFactory_ = GenericMatrixFactory< MODEL >
Private Member Functions
void schur_add (const Increment_ &, const Increment_ &dxi, Increment_ &dxo, Increment_ &tmp) const
void assign_no_date_ctrl (const Increment_ &, Increment_ &) const
void toControlVariableTimes (const Increment4D_ &, Increment4D_ &) const
void toControlVariableTimes_ad (const Increment4D_ &, Increment4D_ &) const
unsigned ntslots () const
Private Attributes
std::unique_ptr< Geometry_ > geom_
std::unique_ptr< ModelSpaceCovarianceBase< MODEL > > static_
std::unique_ptr< Localization_ > loc_
std::vector< util::DateTime > time_
std::unique_ptr< GenericMatrix_ > change_of_variable_
int id_
Detailed Description
template<typename MODEL>
class oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >
Definition at line 36 of file EnsembleCovariance4DWithChangeOfVariable.h.
Member Typedef Documentation
Ensemble_
template<typename MODEL > using oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::Ensemble_ = Ensemble<MODEL> private
Definition at line 46 of file EnsembleCovariance4DWithChangeOfVariable.h.
EnsemblePtr_
template<typename MODEL > using oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::EnsemblePtr_ = std::shared_ptr<Ensemble<MODEL> > private
Definition at line 48 of file EnsembleCovariance4DWithChangeOfVariable.h.
EnsemblesCollection_
template<typename MODEL > using oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::EnsemblesCollection_ = EnsemblesCollection<MODEL> private
Definition at line 49 of file EnsembleCovariance4DWithChangeOfVariable.h.
GenericMatrix_
template<typename MODEL > using oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::GenericMatrix_ = GenericMatrix<MODEL> private
Definition at line 50 of file EnsembleCovariance4DWithChangeOfVariable.h.
Geometry_
template<typename MODEL > using oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 38 of file EnsembleCovariance4DWithChangeOfVariable.h.
IncrCtlVec_
template<typename MODEL > using oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::IncrCtlVec_ = IncrCtlVec<MODEL> private
Definition at line 43 of file EnsembleCovariance4DWithChangeOfVariable.h.
Increment4D_
template<typename MODEL > using oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::Increment4D_ = Increment4D<MODEL> private
Definition at line 42 of file EnsembleCovariance4DWithChangeOfVariable.h.
Increment_
template<typename MODEL > using oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 40 of file EnsembleCovariance4DWithChangeOfVariable.h.
IncrEnsCtlVec_
template<typename MODEL > using oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::IncrEnsCtlVec_ = IncrEnsCtlVec<MODEL> private
Definition at line 44 of file EnsembleCovariance4DWithChangeOfVariable.h.
IncrModCtlVec_
template<typename MODEL > using oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::IncrModCtlVec_ = IncrModCtlVec<MODEL> private
Definition at line 45 of file EnsembleCovariance4DWithChangeOfVariable.h.
Localization_
template<typename MODEL > using oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::Localization_ = Localization<MODEL> private
Definition at line 47 of file EnsembleCovariance4DWithChangeOfVariable.h.
MatrixFactory_
template<typename MODEL > using oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::MatrixFactory_ = GenericMatrixFactory<MODEL> private
Definition at line 51 of file EnsembleCovariance4DWithChangeOfVariable.h.
State4D_
template<typename MODEL > using oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::State4D_ = State4D<MODEL> private
Definition at line 41 of file EnsembleCovariance4DWithChangeOfVariable.h.
Variables_
template<typename MODEL > using oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 39 of file EnsembleCovariance4DWithChangeOfVariable.h.
Constructor & Destructor Documentation
EnsembleCovariance4DWithChangeOfVariable()
template<typename MODEL > oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::EnsembleCovariance4DWithChangeOfVariable (const Geometry_ & resol, const Variables_ & , const eckit::Configuration & config, const State4D_ &)
Definition at line 94 of file EnsembleCovariance4DWithChangeOfVariable.h.
     : ModelSpaceCovariance4DBase<MODEL>::ModelSpaceCovariance4DBase(resol,
                                                                     config) {
   id_ = 0;
   if (config.has("id"))
     id_ = config.getInt("id");
   Log::trace() << "EnsembleCovariance4DWithChangeOfVariable created.";
 }
References oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::id_.
Member Function Documentation
advectedInverseMultiply()
template<typename MODEL > void oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::advectedInverseMultiply (const Increment4D_ & dxi, Increment4D_ & dxo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 311 of file EnsembleCovariance4DWithChangeOfVariable.h.
{
   dxo.zero();
 }
References oops::Increment4D< MODEL >::zero().
advectedLinearize()
template<typename MODEL > void oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::advectedLinearize (const State4D_ & xb, const Geometry_ & resol, const eckit::Configuration & config) virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 109 of file EnsembleCovariance4DWithChangeOfVariable.h.
{
   unsigned nbtslots;
   std::vector < eckit::LocalConfiguration > confEnsemble;
   config.get("ensemble", confEnsemble);
   nbtslots = confEnsemble.size();
   /*
    * Build localization
    */
   const eckit::LocalConfiguration conf(config, "localization");
   if (conf.has("resolution")) {
     const eckit::LocalConfiguration resolConfig(conf, "resolution");
     geom_.reset(new Geometry_(resolConfig));
   }
   else {
     geom_.reset(new Geometry_(resol));
   }
   loc_.reset(new Localization_(*geom_, conf));
   /*
    * Build ensemble
    */
   time_.clear();
   for (unsigned jsub = 0; jsub < nbtslots; ++jsub) {
     util::DateTime dt(confEnsemble[jsub].getString("reference_time"));
     EnsembleKey id(dt, id_);
     EnsemblePtr_ ens_k(new Ensemble_(dt, confEnsemble[jsub]));
     ens_k->build(xb[0], resol);
     EnsemblesCollection_::getInstance().put(id, ens_k);
     time_.push_back(dt);
   }
   /*
    * Read files
    */
   for (unsigned jsub = 0; jsub < ntslots(); ++jsub) {
     EnsembleKey id(time_[jsub], id_);
     EnsemblePtr_ ens = EnsemblesCollection_::getInstance()[id];
     ens->read();
   }
   change_of_variable_.reset(
       MatrixFactory_::create(eckit::LocalConfiguration(config, "change_of_variable")));
   for (unsigned jsub = 0; jsub < ntslots(); ++jsub) {
     EnsembleKey id(time_[jsub], id_);
     EnsemblePtr_ ens = EnsemblesCollection_::getInstance()[id];
     for (unsigned l = 0; l < ens->size(); ++l) {
       change_of_variable_->multiply((*ens)[l]);
     }
   }
   /*
    * Calculate mean
    */
   int nb_sub_ens;
   for (unsigned jsub = 0; jsub < ntslots(); ++jsub) {
     EnsembleKey id(time_[jsub], id_);
     nb_sub_ens = confEnsemble[jsub].getInt("sub_ens");
     EnsemblePtr_ ens = EnsemblesCollection_::getInstance()[id];
     ens->to_perturbations(nb_sub_ens);
   }
   Log::trace() << "EnsembleCovariance4DWithChangeOfVariable linearized.";
 }
advectedMultiply()
template<typename MODEL > void oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::advectedMultiply (const Increment4D_ & dxi, Increment4D_ & dxo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 178 of file EnsembleCovariance4DWithChangeOfVariable.h.
{
   dxo.zero();
   Increment_ dx_loc(dxo[0]);
   Increment4D_ dxi_tmp(dxi);
   Increment4D_ dxo_tmp(dxo);
   Increment_ tmp(dxo[0]);
   EnsembleKey id0(time_[0], id_);
   EnsemblePtr_ e = EnsemblesCollection_::getInstance()[id0];
   /*
    * Change variable in dxi
    */
   toControlVariableTimes_ad(dxi, dxi_tmp);
   for (unsigned k = 0; k < ntslots(); ++k) {
     change_of_variable_->transposeInverseMultiply(dxi_tmp[k]);
   }
   for (unsigned l = 0; l < e->size(); ++l) {
     dx_loc.zero();
     for (unsigned k2 = 0; k2 < ntslots(); ++k2) {
       EnsembleKey idk2(time_[k2], id_);
       EnsemblePtr_ e_k2 = EnsemblesCollection_::getInstance()[idk2];
       schur_add((*e_k2)[l], dxi_tmp[k2], dx_loc, tmp);
     }
     loc_->multiply(dx_loc);
     for (unsigned k1 = 0; k1 < ntslots(); ++k1) {
       EnsembleKey idk1(time_[k1], id_);
       EnsemblePtr_ e_k1 = EnsemblesCollection_::getInstance()[idk1];
       schur_add((*e_k1)[l], dx_loc, dxo_tmp[k1], tmp);
     }
     /*
      * Version without any localization ... for testing and debugging
      *
      dxo.zero();
      for (unsigned l = 0; l < e->size(); ++l) {
      for (unsigned k1 = 0; k1 < ntslots(); ++k1) {
      EnsemblePtr_ e_k1 =
      EnsemblesCollection_::getInstance()[dxi[k1].validTime()];
      for (unsigned k2 = 0; k2 < ntslots(); ++k2) {
      EnsemblePtr_ e_k2 =
      EnsemblesCollection_::getInstance()[dxi[k2].validTime()];
      double zz = (*e_k2)[l].dot_product_with(dxi[k2]);
      dxo[k1].axpy(zz, (*e_k1)[l]);
      }
      }*/
   }
   /*
    * Go back to the right variables
    */
   for (unsigned k = 0; k < ntslots(); ++k) {
     change_of_variable_->inverseMultiply(dxo_tmp[k]);
   }
   toControlVariableTimes(dxo_tmp, dxo);
 }
References oops::Increment4D< MODEL >::zero(), and oops::Increment< MODEL >::zero().
advectedMultiplySqrt()
template<typename MODEL > void oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::advectedMultiplySqrt (const IncrCtlVec_ & dvi, Increment4D_ & dxo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 240 of file EnsembleCovariance4DWithChangeOfVariable.h.
{
   dxo.zero();
   Increment_ dx_loc(dxo[0]);
   Increment4D_ dxo_tmp(dxo);
   Increment_ tmp(dxo[0]);
   EnsembleKey id0(time_[0], id_);
   EnsemblePtr_ e = EnsemblesCollection_::getInstance()[id0];
   for (unsigned l = 0; l < e->size(); ++l) {
     loc_->multiplySqrt(dvi.ensCtlVec(l), dx_loc);
     for (unsigned k1 = 0; k1 < ntslots(); ++k1) {
       EnsembleKey idk1(time_[k1], id_);
       EnsemblePtr_ e_k1 = EnsemblesCollection_::getInstance()[idk1];
       schur_add((*e_k1)[l], dx_loc, dxo_tmp[k1], tmp);
     }
   }
   /*
    * Go back to the right variables
    */
   for (unsigned k = 0; k < ntslots(); ++k) {
     change_of_variable_->inverseMultiply(dxo_tmp[k]);
   }
   toControlVariableTimes(dxo_tmp, dxo);
 }
References oops::IncrCtlVec< MODEL >::ensCtlVec(), and oops::Increment4D< MODEL >::zero().
advectedMultiplySqrtTrans()
template<typename MODEL > void oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::advectedMultiplySqrtTrans (const Increment4D_ & dxi, IncrCtlVec_ & dvo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 270 of file EnsembleCovariance4DWithChangeOfVariable.h.
{
   Increment_ dx_loc(dxi[0]);
   Increment4D_ dxi_tmp(dxi);
   Increment_ tmp(dxi[0]);
   EnsembleKey id0(time_[0], id_);
   EnsemblePtr_ e = EnsemblesCollection_::getInstance()[id0];
   /*
    * Change variable in dxi
    */
   toControlVariableTimes_ad(dxi, dxi_tmp);
   for (unsigned k = 0; k < ntslots(); ++k) {
     change_of_variable_->transposeInverseMultiply(dxi_tmp[k]);
   }
   for (unsigned l = 0; l < e->size(); ++l) {
     dx_loc.zero();
     dvo.ensCtlVec(l).zero();
     for (unsigned k2 = 0; k2 < ntslots(); ++k2) {
       EnsembleKey idk2(time_[k2], id_);
       EnsemblePtr_ e_k2 = EnsemblesCollection_::getInstance()[idk2];
       schur_add((*e_k2)[l], dxi_tmp[k2], dx_loc, tmp);
     }
     loc_->multiplySqrtTrans(dx_loc, dvo.ensCtlVec(l));
   }
 }
References oops::IncrCtlVec< MODEL >::ensCtlVec(), oops::IncrEnsCtlVec< MODEL >::zero(), and oops::Increment< MODEL >::zero().
assign_no_date_ctrl()
template<typename MODEL > void oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::assign_no_date_ctrl (const Increment_ & dxi, Increment_ & dxo) const private
Definition at line 369 of file EnsembleCovariance4DWithChangeOfVariable.h.
{
   dxo.zero();
   dxo.axpy(1.0, dxi, false);
 }
References oops::Increment< MODEL >::axpy(), and oops::Increment< MODEL >::zero().
covar()
template<typename MODEL > const ModelSpaceCovarianceBase<MODEL>& oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::covar () const inline virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 63 of file EnsembleCovariance4DWithChangeOfVariable.h.
 { return *static_; }
References oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::static_.
newIncrEnsCtlVec()
template<typename MODEL > IncrEnsCtlVec_* oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::newIncrEnsCtlVec () const inline override virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 69 of file EnsembleCovariance4DWithChangeOfVariable.h.
{
     return new IncrEnsCtlVec_(*geom_, *loc_);
   }
References oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::geom_, and oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::loc_.
newIncrModCtlVec()
template<typename MODEL > IncrModCtlVec_* oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::newIncrModCtlVec () const inline override virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 66 of file EnsembleCovariance4DWithChangeOfVariable.h.
{
     return new IncrModCtlVec_();
   }
ntslots()
template<typename MODEL > unsigned oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::ntslots () const inline private
Definition at line 79 of file EnsembleCovariance4DWithChangeOfVariable.h.
 { return time_.size(); }
References oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::time_.
schur_add()
template<typename MODEL > void oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::schur_add (const Increment_ & pert, const Increment_ & dxi, Increment_ & dxo, Increment_ & tmp) const private
Definition at line 301 of file EnsembleCovariance4DWithChangeOfVariable.h.
{
   tmp_schur = pert;
   tmp_schur.schur_product_with(dxi);
   dxo.axpy(1.0, tmp_schur, false);
 }
References oops::Increment< MODEL >::axpy(), and oops::Increment< MODEL >::schur_product_with().
toControlVariableTimes()
template<typename MODEL > void oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::toControlVariableTimes (const Increment4D_ & dxi, Increment4D_ & dxo) const private
Definition at line 318 of file EnsembleCovariance4DWithChangeOfVariable.h.
{
   if (ntslots() != (dxi.last()-dxi.first()+1)) {
     assign_no_date_ctrl(dxi[0], dxo[0]); //dxo[0] = dxi[0];
     for (unsigned k = 1; k < ntslots(); ++k) {
       assign_no_date_ctrl(dxi[k - 1],
                           dxo[2 * k - 1]);  // dxo[2 * k - 1] = dxi[k - 1];
       dxo[2 * k - 1] *= 0.5;
       dxo[2 * k - 1].axpy(0.5, dxi[k], false);
       assign_no_date_ctrl(dxi[k], dxo[2 * k]);  // dxo[2 * k] = dxi[k];
     }
   } else {
     dxo = dxi;
   }
 }
References oops::Increment4D< MODEL >::axpy(), oops::Increment4D< MODEL >::first(), and oops::Increment4D< MODEL >::last().
toControlVariableTimes_ad()
template<typename MODEL > void oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::toControlVariableTimes_ad (const Increment4D_ & dxi, Increment4D_ & dxo) const private
Definition at line 339 of file EnsembleCovariance4DWithChangeOfVariable.h.
{
   // Check times
   int envar_times = dxi.last()-dxi.first()+1;
   unsigned nb = ntslots();
   if (nb != envar_times) {
     ASSERT(envar_times == (2 * nb - 1));
     assign_no_date_ctrl(dxi[0], dxo[0]);  // dxo[0] = dxi[0];
     dxo[0].axpy(0.5, dxi[1], false);
     for (unsigned k = 1; k < (nb - 1); ++k) {
       assign_no_date_ctrl(dxi[2 * k], dxo[k]);  // dxo[k] = dxi[2 * k];
       dxo[k].axpy(0.5, dxi[2 * k - 1], false);
       dxo[k].axpy(0.5, dxi[2 * k + 1], false);
     }
     assign_no_date_ctrl(dxi[2 * nb - 2],
                         dxo[nb - 1]);  // dxo[nb - 1] = dxi[2 * nb - 2];
     dxo[nb - 1].axpy(0.5, dxi[2 * nb - 3], false);
   } else {
     dxo = dxi;
   }
 }
References oops::Increment4D< MODEL >::axpy(), oops::Increment4D< MODEL >::first(), and oops::Increment4D< MODEL >::last().
Member Data Documentation
change_of_variable_
template<typename MODEL > std::unique_ptr<GenericMatrix_> oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::change_of_variable_ private
Definition at line 85 of file EnsembleCovariance4DWithChangeOfVariable.h.
geom_
template<typename MODEL > std::unique_ptr<Geometry_> oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::geom_ private
Definition at line 81 of file EnsembleCovariance4DWithChangeOfVariable.h.
Referenced by oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::newIncrEnsCtlVec().
id_
template<typename MODEL > int oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::id_ private
Definition at line 86 of file EnsembleCovariance4DWithChangeOfVariable.h.
Referenced by oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::EnsembleCovariance4DWithChangeOfVariable().
loc_
template<typename MODEL > std::unique_ptr<Localization_> oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::loc_ private
Definition at line 83 of file EnsembleCovariance4DWithChangeOfVariable.h.
Referenced by oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::newIncrEnsCtlVec().
static_
template<typename MODEL > std::unique_ptr<ModelSpaceCovarianceBase<MODEL> > oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::static_ private
Definition at line 82 of file EnsembleCovariance4DWithChangeOfVariable.h.
Referenced by oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::covar().
time_
template<typename MODEL > std::vector<util::DateTime> oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::time_ private
Definition at line 84 of file EnsembleCovariance4DWithChangeOfVariable.h.
Referenced by oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::ntslots().
The documentation for this class was generated from the following file:
src/oops/base/EnsembleCovariance4DWithChangeOfVariable.h