OOPS Documentation: oops::EnsembleCovsInterpolSDL< MODEL > Class Template Reference
oops::EnsembleCovsInterpolSDL< MODEL > Class Template Reference
Wraps the model space error covariance.
#include <EnsembleCovsInterpolSDL.h>
Public Member Functions
EnsembleCovsInterpolSDL (const Geometry_ &, const Variables_ &, const eckit::Configuration &, const State_ &)
Constructor, destructor.
~EnsembleCovsInterpolSDL ()
void linearize (const State_ &, const Geometry_ &, const eckit::Configuration &) override
Set up the inner loop resolution B matrix.
void multiply (const Increment_ &, Increment_ &) const override
\(dx_1 = B dx_2 \)
void inverseMultiply (const Increment_ &, Increment_ &) const override
\(dx_1 = B^{-1} dx_2 \)
void multiplySqrt (const IncrCtlVec_ &, Increment_ &) const override
\(dx = B^{1/2} dv \)
void multiplySqrtTrans (const Increment_ &, IncrCtlVec_ &) const override
\(dv = [B^{1/2}]^T dx \)
void randomize (Increment_ &) const override
\(dx = B^{1/2} dv_{random} \)
IncrModCtlVec_ * newIncrModCtlVec () const override
IncrEnsCtlVec_ * newIncrEnsCtlVec () const override
Public Member Functions inherited from oops::ModelSpaceCovarianceBase< MODEL >
virtual ~ModelSpaceCovarianceBase ()
Destructor.
Private Types
typedef Ensemble< MODEL > Ensemble_
typedef std::shared_ptr< Ensemble< MODEL > > EnsemblePtr_
typedef EnsemblesCollection< MODEL > EnsemblesCollection_
typedef Geometry< MODEL > Geometry_
typedef Increment< MODEL > Increment_
typedef IncrCtlVec< MODEL > IncrCtlVec_
typedef IncrEnsCtlVec< MODEL > IncrEnsCtlVec_
typedef IncrModCtlVec< MODEL > IncrModCtlVec_
typedef Localization< MODEL > Localization_
typedef State< MODEL > State_
typedef Variables< MODEL > Variables_
typedef Interpolator< MODEL > Interpolator_
typedef HorizScaleDecomposition< MODEL > HorizScaleDecomposition_
typedef std::pair< util::DateTime, int > Key_
Private Attributes
const eckit::LocalConfiguration config_
const util::DateTime time_
std::vector< std::unique_ptr< Localization_ > > loc_
std::unique_ptr< Interpolator_ > intdir_
std::unique_ptr< Interpolator_ > intadj_
std::unique_ptr< Geometry_ > resol_ens_
int nhorizBand_
int SDLtype_
Detailed Description
template<typename MODEL>
class oops::EnsembleCovsInterpolSDL< MODEL >
Wraps the model space error covariance.
Definition at line 31 of file EnsembleCovsInterpolSDL.h.
Member Typedef Documentation
Ensemble_
template<typename MODEL > typedef Ensemble<MODEL> oops::EnsembleCovsInterpolSDL< MODEL >::Ensemble_ private
Definition at line 32 of file EnsembleCovsInterpolSDL.h.
EnsemblePtr_
template<typename MODEL > typedef std::shared_ptr<Ensemble<MODEL> > oops::EnsembleCovsInterpolSDL< MODEL >::EnsemblePtr_ private
Definition at line 33 of file EnsembleCovsInterpolSDL.h.
EnsemblesCollection_
template<typename MODEL > typedef EnsemblesCollection<MODEL> oops::EnsembleCovsInterpolSDL< MODEL >::EnsemblesCollection_ private
Definition at line 34 of file EnsembleCovsInterpolSDL.h.
Geometry_
template<typename MODEL > typedef Geometry<MODEL> oops::EnsembleCovsInterpolSDL< MODEL >::Geometry_ private
Definition at line 35 of file EnsembleCovsInterpolSDL.h.
HorizScaleDecomposition_
template<typename MODEL > typedef HorizScaleDecomposition<MODEL> oops::EnsembleCovsInterpolSDL< MODEL >::HorizScaleDecomposition_ private
Definition at line 44 of file EnsembleCovsInterpolSDL.h.
IncrCtlVec_
template<typename MODEL > typedef IncrCtlVec<MODEL> oops::EnsembleCovsInterpolSDL< MODEL >::IncrCtlVec_ private
Definition at line 37 of file EnsembleCovsInterpolSDL.h.
Increment_
template<typename MODEL > typedef Increment<MODEL> oops::EnsembleCovsInterpolSDL< MODEL >::Increment_ private
Definition at line 36 of file EnsembleCovsInterpolSDL.h.
IncrEnsCtlVec_
template<typename MODEL > typedef IncrEnsCtlVec<MODEL> oops::EnsembleCovsInterpolSDL< MODEL >::IncrEnsCtlVec_ private
Definition at line 38 of file EnsembleCovsInterpolSDL.h.
IncrModCtlVec_
template<typename MODEL > typedef IncrModCtlVec<MODEL> oops::EnsembleCovsInterpolSDL< MODEL >::IncrModCtlVec_ private
Definition at line 39 of file EnsembleCovsInterpolSDL.h.
Interpolator_
template<typename MODEL > typedef Interpolator<MODEL> oops::EnsembleCovsInterpolSDL< MODEL >::Interpolator_ private
Definition at line 43 of file EnsembleCovsInterpolSDL.h.
Key_
template<typename MODEL > typedef std::pair<util::DateTime, int> oops::EnsembleCovsInterpolSDL< MODEL >::Key_ private
Definition at line 45 of file EnsembleCovsInterpolSDL.h.
Localization_
template<typename MODEL > typedef Localization<MODEL> oops::EnsembleCovsInterpolSDL< MODEL >::Localization_ private
Definition at line 40 of file EnsembleCovsInterpolSDL.h.
State_
template<typename MODEL > typedef State<MODEL> oops::EnsembleCovsInterpolSDL< MODEL >::State_ private
Definition at line 41 of file EnsembleCovsInterpolSDL.h.
Variables_
template<typename MODEL > typedef Variables<MODEL> oops::EnsembleCovsInterpolSDL< MODEL >::Variables_ private
Definition at line 42 of file EnsembleCovsInterpolSDL.h.
Constructor & Destructor Documentation
EnsembleCovsInterpolSDL()
template<typename MODEL > oops::EnsembleCovsInterpolSDL< MODEL >::EnsembleCovsInterpolSDL (const Geometry_ & , const Variables_ & , const eckit::Configuration & config, const State_ &)
Constructor, destructor.
Definition at line 83 of file EnsembleCovsInterpolSDL.h.
                                                                                :
 config_(config), time_(config_.getString("date"))
 {
     Log::trace() << "EnsembleCovsInterpolSDL created." << std::endl;
 }
~EnsembleCovsInterpolSDL()
template<typename MODEL > oops::EnsembleCovsInterpolSDL< MODEL >::~EnsembleCovsInterpolSDL
Definition at line 92 of file EnsembleCovsInterpolSDL.h.
{
     Log::trace() << "EnsembleCovsInterpolSDL destructed" << std::endl;
 }
Member Function Documentation
inverseMultiply()
template<typename MODEL > void oops::EnsembleCovsInterpolSDL< MODEL >::inverseMultiply (const Increment_ & , Increment_ &) const override virtual
\(dx_1 = B^{-1} dx_2 \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 294 of file EnsembleCovsInterpolSDL.h.
{
     dxo.zero();
 }
References oops::Increment< MODEL >::zero().
linearize()
template<typename MODEL > void oops::EnsembleCovsInterpolSDL< MODEL >::linearize (const State_ & , const Geometry_ & , const eckit::Configuration &) override virtual
Set up the inner loop resolution B matrix.
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 99 of file EnsembleCovsInterpolSDL.h.
{
     /*
      * Build Geometry of the Ensemble
      */
     const eckit::LocalConfiguration confNewGeo(config_, "ensemble_resol");
     resol_ens_.reset(new Geometry_(confNewGeo));
     /*
      * Build Interpolation operators
      */
     const eckit::LocalConfiguration confInterpol(config_, "interpol");
     intdir_.reset(new Interpolator_(xb, *resol_ens_, confInterpol, false));
     intadj_.reset(new Interpolator_(xb, *resol_ens_, confInterpol, true));
     /*
      * Compute the ensemble of perturbations at time of xb
      */
     ASSERT(xb.validTime() == time_);
     std::vector < eckit::LocalConfiguration > confEnsemble;
     config_.get("ensemble", confEnsemble);
     EnsemblePtr_ ens_k(new Ensemble_(xb.validTime(), confEnsemble[0]));
     ens_k->linearize(xb, *resol_ens_);
     EnsemblesCollection_::getInstance().put(xb.validTime(), ens_k);
     /*
      * Init Scale decomposition
      */
     const eckit::LocalConfiguration conf(config_, "localization");
     const eckit::LocalConfiguration confScaleDecomposition(conf, "scale_decomposition");
     // What type of SDL is demanded
     SDLtype_ = confScaleDecomposition.getInt("formulation");
     // How many horizontal bands do we have?
     nhorizBand_ = confScaleDecomposition.getInt("nb_wave_band_peaks");
     // How many localization lenghts do we have?
     std::vector < eckit::LocalConfiguration > confHorizBand;
     confScaleDecomposition.get("horiz_band", confHorizBand);
     int nband = confHorizBand.size();
     // Make sure that the above two numbers are equal
     ASSERT(nband == nhorizBand_);
     /*
      * Build Localization
      */
     for (unsigned horizBandIndex = 0; horizBandIndex < nhorizBand_; ++horizBandIndex) {
         loc_.emplace_back(new Localization_(*resol_ens_, confHorizBand[horizBandIndex]));
     }
     /*
      * Performed a horizontal scale decomposition of the perturbations
      */
     Log::info() << "Scale decomposition of the perturbation object" << std::endl;
     //Duplication de l'ensemble sur chacune des bandes
     EnsemblePtr_ e = EnsemblesCollection_::getInstance()[xb.validTime()];
     for (int horizBandIndex = 0; horizBandIndex < nhorizBand_; ++horizBandIndex) {
         EnsemblePtr_ ens(new Ensemble_(*e));
         EnsembleKey k(xb.validTime(),horizBandIndex);
         EnsemblesCollection_::getInstance().put(k, ens);
     }
     HorizScaleDecomposition_ fltbg(confScaleDecomposition);
     for (unsigned memberIndex = 0; memberIndex < e->size(); ++memberIndex) {
         Log::info() << " >> calling horiz_scale_decomposition for ensemble member # " << memberIndex + 1 << std::endl;
         for (int horizBandIndex = 0; horizBandIndex < nhorizBand_; ++horizBandIndex) {
             EnsembleKey k(xb.validTime(),horizBandIndex);
             EnsemblePtr_ horizBandEns = EnsemblesCollection_::getInstance()[k];
             fltbg.collect((*horizBandEns)[memberIndex], horizBandIndex);
         }
         fltbg.decompose((*e)[memberIndex], SDLtype_);
     }
     Log::trace() << "EnsembleCovsInterpolSDL linearized." << std::endl;
 }
References oops::HorizScaleDecomposition< MODEL >::collect(), oops::HorizScaleDecomposition< MODEL >::decompose(), and oops::State< MODEL >::validTime().
multiply()
template<typename MODEL > void oops::EnsembleCovsInterpolSDL< MODEL >::multiply (const Increment_ & , Increment_ &) const override virtual
\(dx_1 = B dx_2 \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 183 of file EnsembleCovsInterpolSDL.h.
 {
     EnsemblePtr_ e = EnsemblesCollection_::getInstance()[dxi.validTime()];
     // Adjoint interpolation to the resolution of the increment
     Log::trace() <<  "Adjoint Interpolation (HR -> LR) of the increment" << std::endl ;
     const eckit::LocalConfiguration confInterpol(config_, "interpol");
     const Variables_ var(confInterpol);
     Increment_ dxi_lr(*resol_ens_, var, dxi.validTime());
     dxi_lr.zero();
     intadj_->interpolate(dxi, var, dxi_lr);
     //
     // Note on the scale-dependent localization (SDL) formulation...
     // We use here a B^1/2 approach to save computational cost, since:
     // With B^1/2, the cost of the SDL approach is proportional to the number of scale-bands
     // With B    , the cost of the SDL approach is proportional to the SQUARE of the number of scale-bands
     //
     // Tringlerie : cration des IncrEnsCtlVec_ ncessaires
     // structures intermdiaires entre BT/2 et B1/2
     // Create one Ksi per ensemble member
     std::vector<std::unique_ptr< IncrEnsCtlVec_ > > aksi;
     unsigned ksiIndex;
     if (SDLtype_ == 1) {
         // Create one Ksi per ensemble member
         for (unsigned memberIndex = 0; memberIndex < e->size(); ++memberIndex) {
             IncrEnsCtlVec_* ksi = new IncrEnsCtlVec_(*resol_ens_, *loc_[0]);
             aksi.emplace_back(ksi);
         }
     } else {
         // Create one Ksi per ensemble member and per horizontal waveband
         for (unsigned horizBandIndex = 0; horizBandIndex < nhorizBand_; ++horizBandIndex) {
             for (unsigned l = 0; l < e->size(); ++l) {
                 IncrEnsCtlVec_* ksi = new IncrEnsCtlVec_(*resol_ens_, *loc_[0]);
                 aksi.emplace_back(ksi);
             }
         }
     }
     //
     // --- Apply B^T/2 ---
     //
     Log::info() << "Aplying B^T/2" << std::endl;
     // loop on horizontal scale band
     for (unsigned horizBandIndex = 0; horizBandIndex < nhorizBand_; ++horizBandIndex) {
         // loop on ensemble members
         for (unsigned memberIndex = 0; memberIndex < e->size(); ++memberIndex) {
             if (SDLtype_ == 1) {
                 ksiIndex = memberIndex;
             } else {
                 ksiIndex = horizBandIndex * e->size() + memberIndex;
             }
             aksi[ksiIndex]->zero();
             Increment_ dx_lr_loc(dxi_lr);
             EnsembleKey k(dxi_lr.validTime(),horizBandIndex);
             EnsemblePtr_ e_t = EnsemblesCollection_::getInstance()[k];
             dx_lr_loc.schur_product_with((*e_t)[memberIndex]);
             loc_[horizBandIndex]->multiplySqrtTrans(dx_lr_loc, *(aksi[ksiIndex]));
         }
     }
     //
     // --- Apply B^1/2 ---
     //
     Log::info() << "Aplying B^1/2" << std::endl;
     Increment_ dx_lr_loc(*resol_ens_, var, dxi.validTime());
     Increment_ dxo_lr(dx_lr_loc);
     dxo_lr.zero();
     // multiply
     // loop on horizontal scale band
     for (unsigned horizBandIndex = 0; horizBandIndex < nhorizBand_; ++horizBandIndex) {
         // loop on ensemble members
         for (unsigned memberIndex = 0; memberIndex < e->size(); ++memberIndex) {
             if (SDLtype_ == 1) {
                 ksiIndex = memberIndex;
             } else {
                 ksiIndex = horizBandIndex * e->size() + memberIndex;
             }
             loc_[horizBandIndex]->multiplySqrt(*(aksi[ksiIndex]), dx_lr_loc);
             EnsembleKey k(dx_lr_loc.validTime(),horizBandIndex);
             EnsemblePtr_ e_t = EnsemblesCollection_::getInstance()[k];
             dx_lr_loc.schur_product_with((*e_t)[memberIndex]);
             dxo_lr.axpy(1.0, dx_lr_loc, false);
         }
     }
     // Back to HR
     Log::trace() << "Direct interpolation (LR -> HR) of the increment " << std::endl ;
     intdir_->interpolate(dxo_lr, var , dxo);
 }
References oops::Increment< MODEL >::axpy(), oops::Increment< MODEL >::schur_product_with(), oops::Increment< MODEL >::validTime(), and oops::Increment< MODEL >::zero().
multiplySqrt()
template<typename MODEL > void oops::EnsembleCovsInterpolSDL< MODEL >::multiplySqrt (const IncrCtlVec_ & , Increment_ &) const override virtual
\(dx = B^{1/2} dv \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 303 of file EnsembleCovsInterpolSDL.h.
{
     // Interpolation to the resolution of the increment
     const eckit::LocalConfiguration confInterpol(config_, "interpol");
     const Variables_ var(confInterpol);
     Increment_ dx_lr_loc(*resol_ens_, var, dxo.validTime());
     Increment_ dxo_lr(dx_lr_loc);
     dxo_lr.zero();
     Log::info() << "Aplying B^1/2" << std::endl;
     int nMembers = EnsemblesCollection_::getInstance()[dxo.validTime()]->size();
     // loop on horizontal scale band
     for (unsigned horizBandIndex = 0; horizBandIndex < nhorizBand_; ++horizBandIndex) {
         // Get ensemble
         EnsembleKey k(dx_lr_loc.validTime(),horizBandIndex);
         EnsemblePtr_ ens_horizBandIndex = EnsemblesCollection_::getInstance()[k];
         // loop on ensemble members
         for (unsigned memberIndex = 0; memberIndex < nMembers; ++memberIndex) {
             loc_[horizBandIndex]->multiplySqrt(dvi.ensCtlVec(memberIndex), dx_lr_loc);
             dx_lr_loc.schur_product_with((*ens_horizBandIndex)[memberIndex]);
             dxo_lr.axpy(1.0, dx_lr_loc, false);
         }
     }
     // Back to HR
     Log::trace() << "Direct interpolation (LR -> HR) of the increment " << std::endl ;
     intdir_->interpolate(dxo_lr, var , dxo);
 }
References oops::Increment< MODEL >::axpy(), oops::IncrCtlVec< MODEL >::ensCtlVec(), oops::Increment< MODEL >::schur_product_with(), oops::Increment< MODEL >::validTime(), and oops::Increment< MODEL >::zero().
multiplySqrtTrans()
template<typename MODEL > void oops::EnsembleCovsInterpolSDL< MODEL >::multiplySqrtTrans (const Increment_ & , IncrCtlVec_ &) const override virtual
\(dv = [B^{1/2}]^T dx \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 337 of file EnsembleCovsInterpolSDL.h.
{
     // Adjoint interpolation to the resolution of the increment
     Log::trace() <<  "Adjoint Interpolation (HR -> LR) of the increment" << std::endl ;
     const eckit::LocalConfiguration confInterpol(config_, "interpol");
     const Variables_ var(confInterpol);
     Increment_ dxi_lr(*resol_ens_, var, dxi.validTime());
     dxi_lr.zero();
     intadj_->interpolate(dxi, var, dxi_lr);
     Log::info() << "Aplying B^T/2" << std::endl;
     int nMembers = EnsemblesCollection_::getInstance()[dxi.validTime()]->size();
     // loop on ensemble members
     for (unsigned memberIndex = 0; memberIndex < nMembers; ++memberIndex) {
       // Initialization
       dvo.ensCtlVec(memberIndex).zero();
       // loop on horizontal scale band
       for (unsigned horizBandIndex = 0; horizBandIndex < nhorizBand_; ++horizBandIndex) {
           EnsembleKey k(dxi_lr.validTime(),horizBandIndex);
           EnsemblePtr_ ens_horizBandIndex = EnsemblesCollection_::getInstance()[k];
           Increment_ dx_lr_loc(dxi_lr);
           dx_lr_loc.schur_product_with((*ens_horizBandIndex)[memberIndex]);
           loc_[horizBandIndex]->multiplySqrtTrans(dx_lr_loc, dvo.ensCtlVec(memberIndex));
         }
     }
 }
References oops::IncrCtlVec< MODEL >::ensCtlVec(), oops::Increment< MODEL >::schur_product_with(), oops::Increment< MODEL >::validTime(), oops::IncrEnsCtlVec< MODEL >::zero(), and oops::Increment< MODEL >::zero().
newIncrEnsCtlVec()
template<typename MODEL > IncrEnsCtlVec_* oops::EnsembleCovsInterpolSDL< MODEL >::newIncrEnsCtlVec () const inline override virtual
Return a new control vector corresponding to the localised sampled component of a B matrix
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 63 of file EnsembleCovsInterpolSDL.h.
 {return new IncrEnsCtlVec_(*resol_ens_, *loc_[0]);}
References oops::EnsembleCovsInterpolSDL< MODEL >::loc_, and oops::EnsembleCovsInterpolSDL< MODEL >::resol_ens_.
newIncrModCtlVec()
template<typename MODEL > IncrModCtlVec_* oops::EnsembleCovsInterpolSDL< MODEL >::newIncrModCtlVec () const inline override virtual
Return a new control vector corresponding to the modelled component of a B matrix
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 62 of file EnsembleCovsInterpolSDL.h.
 {return new IncrModCtlVec_();}
randomize()
template<typename MODEL > void oops::EnsembleCovsInterpolSDL< MODEL >::randomize (Increment_ &) const override virtual
\(dx = B^{1/2} dv_{random} \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 375 of file EnsembleCovsInterpolSDL.h.
{
     // Build control vector
     EnsemblePtr_ e_k = EnsemblesCollection_::getInstance()[dxo.validTime()];
     std::vector<std::unique_ptr< IncrEnsCtlVec_ > > aksi;
     if (SDLtype_ == 1) {
         // Create one Ksi per ensemble member
         for (unsigned memberIndex = 0; memberIndex < e_k->size(); ++memberIndex) {
             aksi.emplace_back(this->newIncrEnsCtlVec());
         }
     } else {
         // Create one Ksi per ensemble member and per horizontal waveband
         for (unsigned horizBandIndex = 0; horizBandIndex < nhorizBand_; ++horizBandIndex) {
             for (unsigned memberIndex = 0; memberIndex < e_k->size(); ++memberIndex) {
                 aksi.emplace_back(this->newIncrEnsCtlVec());
             }
         }
     }
     // Initialize control vector
     for (unsigned int ksi = 0; ksi < aksi.size(); ++ksi) {
         aksi[ksi]->random();
     }
     // dxo_lr = B^1/2 aksi
     //(a) prepare interpolation
     const eckit::LocalConfiguration confInterpol(config_, "interpol");
     const Variables_ var(confInterpol);
     Increment_ dx_lr_loc(*resol_ens_, var, dxo.validTime());
     Increment_ dxo_lr(dx_lr_loc);
     //(b) multiplication
     dxo_lr.zero();
     unsigned ksiIndex;
     for (unsigned horizBandIndex = 0; horizBandIndex < nhorizBand_; ++horizBandIndex) {
         // loop on ensemble members
         for (unsigned memberIndex = 0; memberIndex < e_k->size(); ++memberIndex) {
             if (SDLtype_ == 1) {
                 ksiIndex = memberIndex;
             } else {
                 ksiIndex = horizBandIndex * e_k->size() + memberIndex;
             }
             loc_[horizBandIndex]->multiplySqrt(*aksi[ksiIndex], dx_lr_loc);
             EnsembleKey k(dxo_lr.validTime(),horizBandIndex);
             EnsemblePtr_ e_t = EnsemblesCollection_::getInstance()[k];
             dx_lr_loc.schur_product_with((*e_t)[memberIndex]);
             dxo_lr.axpy(1.0, dx_lr_loc, false);
         }
     }
   // Pour test interpolation :
   //dxo_lr.zero();
   double product = dot_product(dxo_lr,dxo_lr);
   Log::info() <<  "EnsembleCovInterpol<MODEL>::randomize : product=" <<  product << std::endl ;
   //(c) interpolation to HR
   Log::trace() << "Direct interpolation (LR -> HR) of the increment " << std::endl;
   intdir_->interpolate(dxo_lr, var, dxo);
   double productHR = dot_product(dxo,dxo);
   Log::info() <<  "EnsembleCovInterpol<MODEL>::randomize : productHR=" <<  productHR << std::endl ;
 }
References oops::Increment< MODEL >::axpy(), dot_product(), oops::Increment< MODEL >::schur_product_with(), oops::Increment< MODEL >::validTime(), and oops::Increment< MODEL >::zero().
Member Data Documentation
config_
template<typename MODEL > const eckit::LocalConfiguration oops::EnsembleCovsInterpolSDL< MODEL >::config_ private
Definition at line 68 of file EnsembleCovsInterpolSDL.h.
intadj_
template<typename MODEL > std::unique_ptr<Interpolator_> oops::EnsembleCovsInterpolSDL< MODEL >::intadj_ private
Definition at line 72 of file EnsembleCovsInterpolSDL.h.
intdir_
template<typename MODEL > std::unique_ptr<Interpolator_> oops::EnsembleCovsInterpolSDL< MODEL >::intdir_ private
Definition at line 71 of file EnsembleCovsInterpolSDL.h.
loc_
template<typename MODEL > std::vector<std::unique_ptr<Localization_> > oops::EnsembleCovsInterpolSDL< MODEL >::loc_ private
Definition at line 70 of file EnsembleCovsInterpolSDL.h.
Referenced by oops::EnsembleCovsInterpolSDL< MODEL >::newIncrEnsCtlVec().
nhorizBand_
template<typename MODEL > int oops::EnsembleCovsInterpolSDL< MODEL >::nhorizBand_ private
Definition at line 74 of file EnsembleCovsInterpolSDL.h.
resol_ens_
template<typename MODEL > std::unique_ptr<Geometry_> oops::EnsembleCovsInterpolSDL< MODEL >::resol_ens_ private
Definition at line 73 of file EnsembleCovsInterpolSDL.h.
Referenced by oops::EnsembleCovsInterpolSDL< MODEL >::newIncrEnsCtlVec().
SDLtype_
template<typename MODEL > int oops::EnsembleCovsInterpolSDL< MODEL >::SDLtype_ private
Definition at line 75 of file EnsembleCovsInterpolSDL.h.
time_
template<typename MODEL > const util::DateTime oops::EnsembleCovsInterpolSDL< MODEL >::time_ private
Definition at line 69 of file EnsembleCovsInterpolSDL.h.
The documentation for this class was generated from the following file:
src/oops/base/EnsembleCovsInterpolSDL.h