OOPS Documentation: oops::EnsForecast< MODEL > Class Template Reference
oops::EnsForecast< MODEL > Class Template Reference
#include <EnsForecasts.h>
Public Member Functions
EnsForecast ()
virtual ~EnsForecast ()
int execute (const eckit::Configuration &fullConfig) const
Public Member Functions inherited from oops::Application
Application ()
virtual ~Application ()
Private Types
using Geometry_ = Geometry< MODEL >
using Model_ = Model< MODEL >
using ModelAux_ = ModelAuxControl< MODEL >
using State_ = State< MODEL >
Private Member Functions
std::string appname () const
Detailed Description
template<typename MODEL>
class oops::EnsForecast< MODEL >
Definition at line 34 of file EnsForecasts.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::EnsForecast< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 35 of file EnsForecasts.h.
Model_
template<typename MODEL > using oops::EnsForecast< MODEL >::Model_ = Model<MODEL> private
Definition at line 36 of file EnsForecasts.h.
ModelAux_
template<typename MODEL > using oops::EnsForecast< MODEL >::ModelAux_ = ModelAuxControl<MODEL> private
Definition at line 37 of file EnsForecasts.h.
State_
template<typename MODEL > using oops::EnsForecast< MODEL >::State_ = State<MODEL> private
Definition at line 38 of file EnsForecasts.h.
Constructor & Destructor Documentation
EnsForecast()
template<typename MODEL > oops::EnsForecast< MODEL >::EnsForecast () inline
Definition at line 42 of file EnsForecasts.h.
 {}
~EnsForecast()
template<typename MODEL > virtual oops::EnsForecast< MODEL >::~EnsForecast () inline virtual
Definition at line 44 of file EnsForecasts.h.
 {}
Member Function Documentation
appname()
template<typename MODEL > std::string oops::EnsForecast< MODEL >::appname () const inline private virtual
Implements oops::Application.
Definition at line 90 of file EnsForecasts.h.
{
     return "oops::EnsForecast<" + MODEL::name() + ">";
   }
execute()
template<typename MODEL > int oops::EnsForecast< MODEL >::execute (const eckit::Configuration & fullConfig) const inline virtual
Implements oops::Application.
Definition at line 46 of file EnsForecasts.h.
{
     //  Setup resolution
     const eckit::Configuration resolConfig(fullConfig, "resolution");
     const Geometry_ resol(resolConfig);
     //  Setup Model
     const eckit::Configuration modelConfig(fullConfig, "model");
     const Model_ model(resol, modelConfig);
     unsigned nm = config.getElementSize("member");
     for (unsigned jj = 0; jj < nm; ++jj) {
       //    Setup initial state
       const eckit::Configuration initialConfig(fullConfig, "member", jj);
       State_ xx(resol, initialConfig);
       Log::test() << "Initial state: " << xx.norm() << std::endl;
       //    Setup augmented state
       const ModelAux_ moderr(initialConfig);
       //    Setup times
       const util::Duration fclength(fullConfig.getString("forecast_length"));
       const util::DateTime bgndate(xx.validTime());
       const util::DateTime enddate(bgndate + fclength);
       Log::info() << "Running forecast " << jj << " from " << bgndate << " to "
                   << enddate << std::endl;
       //    Setup forecast outputs
       PostProcessor<State_> post;
       const eckit::Configuration prtConfig(fullConfig, "prints", true);
       post.enrollProcessor(new StateInfo<State_>("fc", prtConfig));
       const eckit::Configuration outConfig(fullConfig, "output");
       post.enrollProcessor(new StateWriter<State_>(bgndate, outConfig));
       //    Run forecast
       model.forecast(xx, moderr, fclength, post);
       Log::test() << "Final state " << jj << " : " << xx.norm() << std::endl;
     }
     return 0;
   }
References oops::PostProcessor< FLDS >::enrollProcessor(), oops::Model< MODEL >::forecast(), oops::State< MODEL >::norm(), and oops::State< MODEL >::validTime().
The documentation for this class was generated from the following file:
src/oops/runs/EnsForecasts.h