OOPS Documentation: oops::ObsAuxCovariance< MODEL > Class Template Reference
oops::ObsAuxCovariance< MODEL > Class Template Reference
Encapsulates the covariance matrix of auxiliary observation space components of ControlVariable.
#include <ObsAuxCovariance.h>
Public Member Functions
ObsAuxCovariance (const ObservationSpace_ &, const eckit::Configuration &)
Constructor.
~ObsAuxCovariance ()
Destructor.
void update (const ObsAuxControl_ &, const eckit::Configuration &)
Update.
void linearize (const ObsAuxControl_ &)
Set up the inner loop resolution B matrix.
void multiply (const ObsAuxIncrement_ &, ObsAuxIncrement_ &) const
\(dx_1 = B dx_2 \)
void inverseMultiply (const ObsAuxIncrement_ &, ObsAuxIncrement_ &) const
\(dx_1 = B^{-1} dx_2 \)
void multiplySqrt (const ObsAuxCtlVec_ &, ObsAuxIncrement_ &) const
\(dx = B^{1/2} dv \)
void multiplySqrtTrans (const ObsAuxIncrement_ &, ObsAuxCtlVec_ &) const
\(dv = [B^{1/2}]^T dx \)
void randomize (ObsAuxIncrement_ &) const
\(dx = B^{1/2} dv_{random} \)
const eckit::Configuration & config () const
Retrun a constant reference to configuration.
const ObsAuxCovarianceBase_ & errorCovariance (const std::string &id) const
Return a constant reference to the model specific object.
ObsAuxCovarianceBase_ & errorCovariance (const std::string &id)
Return a reference to the model specific object.
const size_t & size () const
Return the number of ObsAuxIncrementBase objects.
Static Public Member Functions
static const std::string classname ()
Private Types
using ObsAuxCovarianceBase_ = ObsAuxCovarianceBase< MODEL >
using ObsAuxControl_ = ObsAuxControl< MODEL >
using ObsAuxIncrement_ = ObsAuxIncrement< MODEL >
using ObsAuxCtlVec_ = ObsAuxCtlVec< MODEL >
using ObservationSpace_ = ObservationSpace< MODEL >
using ObsAuxCovariancePtrMap_ = std::map< std::string, std::unique_ptr< ObsAuxCovarianceBase_ > >
using iter_ = typename ObsAuxCovariancePtrMap_::iterator
using icst_ = typename ObsAuxCovariancePtrMap_::const_iterator
Private Member Functions
const ObsAuxCovarianceBase_ & get (const std::string &) const
Return a constant reference to the model specific object.
ObsAuxCovarianceBase_ & get (const std::string &)
Return a reference to the model specific object.
void print (std::ostream &) const
Private Attributes
size_t size_
Number of model specific objects.
ObsAuxCovariancePtrMap_ covs_
Map of pointers to model specific objects.
std::unique_ptr< eckit::LocalConfiguration > conf_
Configuration.
Detailed Description
template<typename MODEL>
class oops::ObsAuxCovariance< MODEL >
Encapsulates the covariance matrix of auxiliary observation space components of ControlVariable.
This class provides operations associated with the covariance matrix of auxiliary observation space components (e.g. VarBC, TOVSC) of ControlVariable. It contains a vector of ObsAuxCovarianceBase objects, where ObsAuxCovarianceBase is a base class for model specific (or potentially generic) classes.
ObsAuxCovariances class wraps around a vector of ObsAuxCovariance objects and is part of CostJbTotal. Refer to the documentation of ControlVariable and CostJo to understand the structure.
Definition at line 55 of file ObsAuxCovariance.h.
Member Typedef Documentation
icst_
template<typename MODEL > using oops::ObsAuxCovariance< MODEL >::icst_ = typename ObsAuxCovariancePtrMap_::const_iterator private
Definition at line 66 of file ObsAuxCovariance.h.
iter_
template<typename MODEL > using oops::ObsAuxCovariance< MODEL >::iter_ = typename ObsAuxCovariancePtrMap_::iterator private
Definition at line 65 of file ObsAuxCovariance.h.
ObsAuxControl_
template<typename MODEL > using oops::ObsAuxCovariance< MODEL >::ObsAuxControl_ = ObsAuxControl<MODEL> private
Definition at line 59 of file ObsAuxCovariance.h.
ObsAuxCovarianceBase_
template<typename MODEL > using oops::ObsAuxCovariance< MODEL >::ObsAuxCovarianceBase_ = ObsAuxCovarianceBase<MODEL> private
Definition at line 58 of file ObsAuxCovariance.h.
ObsAuxCovariancePtrMap_
template<typename MODEL > using oops::ObsAuxCovariance< MODEL >::ObsAuxCovariancePtrMap_ = std::map<std::string, std::unique_ptr<ObsAuxCovarianceBase_> > private
Definition at line 64 of file ObsAuxCovariance.h.
ObsAuxCtlVec_
template<typename MODEL > using oops::ObsAuxCovariance< MODEL >::ObsAuxCtlVec_ = ObsAuxCtlVec<MODEL> private
Definition at line 61 of file ObsAuxCovariance.h.
ObsAuxIncrement_
template<typename MODEL > using oops::ObsAuxCovariance< MODEL >::ObsAuxIncrement_ = ObsAuxIncrement<MODEL> private
Definition at line 60 of file ObsAuxCovariance.h.
ObservationSpace_
template<typename MODEL > using oops::ObsAuxCovariance< MODEL >::ObservationSpace_ = ObservationSpace<MODEL> private
Definition at line 62 of file ObsAuxCovariance.h.
Constructor & Destructor Documentation
ObsAuxCovariance()
template<typename MODEL > oops::ObsAuxCovariance< MODEL >::ObsAuxCovariance (const ObservationSpace_ & os, const eckit::Configuration & conf)
Constructor.
Definition at line 123 of file ObsAuxCovariance.h.
     : size_(0), covs_(), conf_(new eckit::LocalConfiguration(conf)) {
   Log::trace() << "ObsAuxCovariance<MODEL>::ObsAuxCovariance starting"
                << std::endl;
   util::Timer timer(classname(), "ObsAuxCovariance");
   std::vector<eckit::LocalConfiguration> covconfs;
   conf.get("covarianceObsAux", covconfs);
   size_ = covconfs.size();
   for (auto const &config : covconfs) {
     std::string key(config.getString("type"));
     std::unique_ptr<ObsAuxCovarianceBase_> auxcov(
         ObsAuxCovarianceFactory<MODEL>::create(os, config));
     covs_.emplace(key, std::move(auxcov));
   }
   Log::trace() << "ObsAuxCovariance<MODEL>::ObsAuxCovariance done" << std::endl;
 }
References oops::ObsAuxCovariance< MODEL >::classname(), oops::ObsAuxCovariance< MODEL >::config(), oops::ObsAuxCovariance< MODEL >::covs_, and oops::ObsAuxCovariance< MODEL >::size_.
~ObsAuxCovariance()
template<typename MODEL > oops::ObsAuxCovariance< MODEL >::~ObsAuxCovariance
Destructor.
Definition at line 146 of file ObsAuxCovariance.h.
{
   Log::trace() << "ObsAuxCovariance<MODEL>::~ObsAuxCovariance starting"
                << std::endl;
   util::Timer timer(classname(), "~ObsAuxCovariance");
   Log::trace() << "ObsAuxCovariance<MODEL>::~ObsAuxCovariance done"
                << std::endl;
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::ObsAuxCovariance< MODEL >::classname () inline static
Definition at line 69 of file ObsAuxCovariance.h.
 { return "oops::ObsAuxCovariance"; }
Referenced by oops::ObsAuxCovariance< MODEL >::ObsAuxCovariance().
config()
template<typename MODEL > const eckit::Configuration& oops::ObsAuxCovariance< MODEL >::config () const inline
Retrun a constant reference to configuration.
Definition at line 95 of file ObsAuxCovariance.h.
 { return *conf_; }
References oops::ObsAuxCovariance< MODEL >::conf_.
Referenced by oops::ObsAuxCovariance< MODEL >::ObsAuxCovariance(), and oops::ObsAuxCtlVec< MODEL >::ObsAuxCtlVec().
errorCovariance() [1/2]
template<typename MODEL > ObsAuxCovarianceBase_& oops::ObsAuxCovariance< MODEL >::errorCovariance (const std::string & id) inline
Return a reference to the model specific object.
Definition at line 102 of file ObsAuxCovariance.h.
{
     return this->get(id);
   }
References oops::ObsAuxCovariance< MODEL >::get().
errorCovariance() [2/2]
template<typename MODEL > const ObsAuxCovarianceBase_& oops::ObsAuxCovariance< MODEL >::errorCovariance (const std::string & id) const inline
Return a constant reference to the model specific object.
Definition at line 98 of file ObsAuxCovariance.h.
{
     return this->get(id);
   }
References oops::ObsAuxCovariance< MODEL >::get().
Referenced by oops::ObsAuxCtlVec< MODEL >::ObsAuxCtlVec().
get() [1/2]
template<typename MODEL > ObsAuxCovarianceBase< MODEL > & oops::ObsAuxCovariance< MODEL >::get (const std::string & id) private
Return a reference to the model specific object.
Definition at line 157 of file ObsAuxCovariance.h.
{
   iter_ it = covs_.find(id);
   ASSERT(it != covs_.end());
   return *it->second;
 }
get() [2/2]
template<typename MODEL > const ObsAuxCovarianceBase< MODEL > & oops::ObsAuxCovariance< MODEL >::get (const std::string & id) const private
Return a constant reference to the model specific object.
Definition at line 167 of file ObsAuxCovariance.h.
{
   icst_ it = covs_.find(id);
   ASSERT(it != covs_.end());
   return *it->second;
 }
Referenced by oops::ObsAuxCovariance< MODEL >::errorCovariance().
inverseMultiply()
template<typename MODEL > void oops::ObsAuxCovariance< MODEL >::inverseMultiply (const ObsAuxIncrement_ & dx1, ObsAuxIncrement_ & dx2) const
\(dx_1 = B^{-1} dx_2 \)
Definition at line 226 of file ObsAuxCovariance.h.
{
   Log::trace() << "ObsAuxCovariance<MODEL>::inverseMultiply starting"
                << std::endl;
   util::Timer timer(classname(), "inverseMultiply");
   for (icst_ it = covs_.begin(); it != covs_.end(); ++it) {
     it->second->inverseMultiply(dx1.obsauxincrement(it->first),
                                 dx2.obsauxincrement(it->first));
   }
   Log::trace() << "ObsAuxCovariance<MODEL>::inverseMultiply done" << std::endl;
 }
References oops::ObsAuxIncrement< MODEL >::obsauxincrement().
linearize()
template<typename MODEL > void oops::ObsAuxCovariance< MODEL >::linearize (const ObsAuxControl_ & xx)
Set up the inner loop resolution B matrix.
Definition at line 177 of file ObsAuxCovariance.h.
{
   Log::trace() << "ObsAuxCovariance<MODEL>::linearize starting" << std::endl;
   util::Timer timer(classname(), "linearize");
   for (iter_ it = covs_.begin(); it != covs_.end(); ++it) {
     it->second->linearize(xx.obsauxcontrol(it->first));
   }
   Log::trace() << "ObsAuxCovariance<MODEL>::linearize done" << std::endl;
 }
References oops::ObsAuxControl< MODEL >::obsauxcontrol().
multiply()
template<typename MODEL > void oops::ObsAuxCovariance< MODEL >::multiply (const ObsAuxIncrement_ & dx1, ObsAuxIncrement_ & dx2) const
\(dx_1 = B dx_2 \)
Definition at line 212 of file ObsAuxCovariance.h.
{
   Log::trace() << "ObsAuxCovariance<MODEL>::multiply starting" << std::endl;
   util::Timer timer(classname(), "multiply");
   for (icst_ it = covs_.begin(); it != covs_.end(); ++it) {
     it->second->multiply(dx1.obsauxincrement(it->first),
                          dx2.obsauxincrement(it->first));
   }
   Log::trace() << "ObsAuxCovariance<MODEL>::multiply done" << std::endl;
 }
References oops::ObsAuxIncrement< MODEL >::obsauxincrement().
multiplySqrt()
template<typename MODEL > void oops::ObsAuxCovariance< MODEL >::multiplySqrt (const ObsAuxCtlVec_ & dvin, ObsAuxIncrement_ & dxout) const
\(dx = B^{1/2} dv \)
Definition at line 241 of file ObsAuxCovariance.h.
{
   Log::trace() << "ObsAuxCovariance<MODEL>::multiplySqrt starting" << std::endl;
   util::Timer timer(classname(), "multiplySqrt");
   for (icst_ it = covs_.begin(); it != covs_.end(); ++it) {
     it->second->multiplySqrt(dvin.obsAuxCtlVec(it->first),
                              dxout.obsauxincrement(it->first));
   }
   Log::trace() << "ObsAuxCovariance<MODEL>::multiplySqrt done" << std::endl;
 }
References oops::ObsAuxCtlVec< MODEL >::obsAuxCtlVec(), and oops::ObsAuxIncrement< MODEL >::obsauxincrement().
multiplySqrtTrans()
template<typename MODEL > void oops::ObsAuxCovariance< MODEL >::multiplySqrtTrans (const ObsAuxIncrement_ & dxin, ObsAuxCtlVec_ & dvout) const
\(dv = [B^{1/2}]^T dx \)
Definition at line 255 of file ObsAuxCovariance.h.
{
   Log::trace() << "ObsAuxCovariance<MODEL>::multiplySqrtTrans starting"
                << std::endl;
   util::Timer timer(classname(), "multiplySqrtTrans");
   for (icst_ it = covs_.begin(); it != covs_.end(); ++it) {
     it->second->multiplySqrtTrans(dxin.obsauxincrement(it->first),
                                   dvout.obsAuxCtlVec(it->first));
   }
   Log::trace() << "ObsAuxCovariance<MODEL>::multiplySqrtTrans done"
                << std::endl;
 }
References oops::ObsAuxCtlVec< MODEL >::obsAuxCtlVec(), and oops::ObsAuxIncrement< MODEL >::obsauxincrement().
print()
template<typename MODEL > void oops::ObsAuxCovariance< MODEL >::print (std::ostream & os) const private
Definition at line 283 of file ObsAuxCovariance.h.
{
   Log::trace() << "ObsAuxCovariance<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   for (icst_ it = covs_.begin(); it != covs_.end(); ++it) {
     os << it->first << ": " << *it->second;
   }
   Log::trace() << "ObsAuxCovariance<MODEL>::print done" << std::endl;
 }
randomize()
template<typename MODEL > void oops::ObsAuxCovariance< MODEL >::randomize (ObsAuxIncrement_ & dx) const
\(dx = B^{1/2} dv_{random} \)
Definition at line 271 of file ObsAuxCovariance.h.
{
   Log::trace() << "ObsAuxCovariance<MODEL>::randomize starting" << std::endl;
   util::Timer timer(classname(), "randomize");
   for (icst_ it = covs_.begin(); it != covs_.end(); ++it) {
     it->second->randomize(dx.obsauxincrement(it->first));
   }
   Log::trace() << "ObsAuxCovariance<MODEL>::randomize done" << std::endl;
 }
References oops::ObsAuxIncrement< MODEL >::obsauxincrement().
size()
template<typename MODEL > const size_t& oops::ObsAuxCovariance< MODEL >::size () const inline
Return the number of ObsAuxIncrementBase objects.
Definition at line 106 of file ObsAuxCovariance.h.
 { return size_; }
References oops::ObsAuxCovariance< MODEL >::size_.
update()
template<typename MODEL > void oops::ObsAuxCovariance< MODEL >::update (const ObsAuxControl_ & xx, const eckit::Configuration & conf)
Update.
Definition at line 189 of file ObsAuxCovariance.h.
{
   Log::trace() << "ObsAuxCovariance<MODEL>::update starting" << std::endl;
   util::Timer timer(classname(), "update");
   conf_.reset(new eckit::LocalConfiguration(conf));
   std::vector<eckit::LocalConfiguration> confs;
   conf.get("covarianceObsAux", confs);
   for (iter_ it = covs_.begin(); it != covs_.end(); ++it) {
     for (auto const &config : confs) {
       if (config.getString("type") == it->first && config.getBool("update")) {
         it->second->update(xx.obsauxcontrol(it->first), config);
       }
     }
   }
   Log::trace() << "ObsAuxCovariance<MODEL>::update done" << std::endl;
 }
References oops::ObsAuxControl< MODEL >::obsauxcontrol().
Member Data Documentation
conf_
template<typename MODEL > std::unique_ptr<eckit::LocalConfiguration> oops::ObsAuxCovariance< MODEL >::conf_ private
Configuration.
Definition at line 117 of file ObsAuxCovariance.h.
Referenced by oops::ObsAuxCovariance< MODEL >::config().
covs_
template<typename MODEL > ObsAuxCovariancePtrMap_ oops::ObsAuxCovariance< MODEL >::covs_ private
Map of pointers to model specific objects.
Definition at line 116 of file ObsAuxCovariance.h.
Referenced by oops::ObsAuxCovariance< MODEL >::ObsAuxCovariance().
size_
template<typename MODEL > size_t oops::ObsAuxCovariance< MODEL >::size_ mutable private
Number of model specific objects.
Definition at line 115 of file ObsAuxCovariance.h.
Referenced by oops::ObsAuxCovariance< MODEL >::ObsAuxCovariance(), and oops::ObsAuxCovariance< MODEL >::size().
The documentation for this class was generated from the following file:
src/oops/interface/ObsAuxCovariance.h