OOPS Documentation: oops::DualConfigModel< MODEL > Class Template Reference
oops::DualConfigModel< MODEL > Class Template Reference
Encapsulates the nonlinear dual-config forecast model.
#include <DualConfigModel.h>
Public Member Functions
DualConfigModel (const DualConfigGeometry_ &, const eckit::Configuration &)
~DualConfigModel ()
void forecast (DualConfigState_ &, const DualConfigModelAuxControl_ &, const util::Duration &, DualConfigPostProcessor< State_ > &) const
const util::Duration & timeResolution1 () const
const util::Duration & timeResolution2 () const
const Model_ & model1 () const
const Model_ & model2 () const
Static Public Member Functions
static const std::string classname ()
Private Types
using DualConfigGeometry_ = DualConfigGeometry< MODEL >
using DualConfigModel_ = DualConfigModel< MODEL >
using DualConfigModelAuxControl_ = DualConfigModelAuxControl< MODEL >
using DualConfigPostProcessor_ = DualConfigPostProcessor< MODEL >
using DualConfigState_ = DualConfigState< MODEL >
using Geometry_ = Geometry< MODEL >
using ModelAux_ = ModelAuxControl< MODEL >
using Model_ = Model< MODEL >
using State_ = State< MODEL >
using Variables_ = Variables< MODEL >
Private Member Functions
void initialize (DualConfigState_ &, const DualConfigModelAuxControl_ &) const
void step (DualConfigState_ &, const DualConfigModelAuxControl_ &) const
void finalize (DualConfigState_ &) const
void print (std::ostream &) const
Private Attributes
std::unique_ptr< Model_ > model1_
std::unique_ptr< Model_ > model2_
const Variables_ varsForced1_
const Variables_ varsForced2_
Detailed Description
template<typename MODEL>
class oops::DualConfigModel< MODEL >
Encapsulates the nonlinear dual-config forecast model.
Definition at line 47 of file DualConfigModel.h.
Member Typedef Documentation
DualConfigGeometry_
template<typename MODEL > using oops::DualConfigModel< MODEL >::DualConfigGeometry_ = DualConfigGeometry<MODEL> private
Definition at line 50 of file DualConfigModel.h.
DualConfigModel_
template<typename MODEL > using oops::DualConfigModel< MODEL >::DualConfigModel_ = DualConfigModel<MODEL> private
Definition at line 51 of file DualConfigModel.h.
DualConfigModelAuxControl_
template<typename MODEL > using oops::DualConfigModel< MODEL >::DualConfigModelAuxControl_ = DualConfigModelAuxControl<MODEL> private
Definition at line 52 of file DualConfigModel.h.
DualConfigPostProcessor_
template<typename MODEL > using oops::DualConfigModel< MODEL >::DualConfigPostProcessor_ = DualConfigPostProcessor<MODEL> private
Definition at line 53 of file DualConfigModel.h.
DualConfigState_
template<typename MODEL > using oops::DualConfigModel< MODEL >::DualConfigState_ = DualConfigState<MODEL> private
Definition at line 54 of file DualConfigModel.h.
Geometry_
template<typename MODEL > using oops::DualConfigModel< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 55 of file DualConfigModel.h.
Model_
template<typename MODEL > using oops::DualConfigModel< MODEL >::Model_ = Model<MODEL> private
Definition at line 57 of file DualConfigModel.h.
ModelAux_
template<typename MODEL > using oops::DualConfigModel< MODEL >::ModelAux_ = ModelAuxControl<MODEL> private
Definition at line 56 of file DualConfigModel.h.
State_
template<typename MODEL > using oops::DualConfigModel< MODEL >::State_ = State<MODEL> private
Definition at line 58 of file DualConfigModel.h.
Variables_
template<typename MODEL > using oops::DualConfigModel< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 59 of file DualConfigModel.h.
Constructor & Destructor Documentation
DualConfigModel()
template<typename MODEL > oops::DualConfigModel< MODEL >::DualConfigModel (const DualConfigGeometry_ & resol, const eckit::Configuration & conf)
Definition at line 101 of file DualConfigModel.h.
     : model1_(),
       model2_(),
       varsForced1_(conf.getSubConfiguration("model1.forcing")),
       varsForced2_(conf.getSubConfiguration("model2.forcing")) {
   Log::trace() << classname() << "::DualConfigModel starting" << std::endl;
   util::Timer timer(classname(), "DualConfigModel");
   Log::debug() << "Full config is:" << conf << std::endl;
   eckit::LocalConfiguration conf1(conf, "model1");
   model1_.reset(new Model_(resol.geometry1(), conf1));
   eckit::LocalConfiguration conf2(conf, "model2");
   model2_.reset(new Model_(resol.geometry2(), conf2));
   Log::trace() << classname() << "::DualConfigModel done" << std::endl;
 }
References oops::DualConfigModel< MODEL >::classname(), oops::DualConfigGeometry< MODEL >::geometry1(), oops::DualConfigGeometry< MODEL >::geometry2(), oops::DualConfigModel< MODEL >::model1_, and oops::DualConfigModel< MODEL >::model2_.
~DualConfigModel()
template<typename MODEL > oops::DualConfigModel< MODEL >::~DualConfigModel
Definition at line 120 of file DualConfigModel.h.
{
   Log::trace() << classname() << "::~DualConfigModel starting" << std::endl;
   util::Timer timer(classname(), "~DualConfigModel");
   model1_.reset();
   model2_.reset();
   Log::trace() << classname() << "::~DualConfigModel done" << std::endl;
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::DualConfigModel< MODEL >::classname () inline static
Definition at line 62 of file DualConfigModel.h.
{
     return "oops::DualConfigModel<MODEL>";
   }
Referenced by oops::DualConfigModel< MODEL >::DualConfigModel().
finalize()
template<typename MODEL > void oops::DualConfigModel< MODEL >::finalize (DualConfigState_ & xx) const private
Definition at line 213 of file DualConfigModel.h.
{
   Log::trace() << classname() << "::finalize starting" << std::endl;
   util::Timer timer(classname(), "finalize");
   model1_->finalize(xx.state1());
   model2_->finalize(xx.state2());
   Log::trace() << classname() << "::finalize done" << std::endl;
 }
References oops::DualConfigState< MODEL >::state1(), and oops::DualConfigState< MODEL >::state2().
forecast()
template<typename MODEL > void oops::DualConfigModel< MODEL >::forecast (DualConfigState_ & xx, const DualConfigModelAuxControl_ & maux, const util::Duration & len, DualConfigPostProcessor< State_ > & post) const
Forecast initialization
Forecast time-stepping loop
Two-way forcing
Force State2 with State1 (varsForced2 fields)
Force State1 with State2 (varsForced1 fields)
Time step
Post-processing
Forecast finalization
Definition at line 131 of file DualConfigModel.h.
{
   Log::trace() << classname() << "::forecast starting" << std::endl;
   util::Timer timer(classname(), "forecast");
   util::LogbookWriter<std::string> log("Forecast", "Nonlinear HR trajectory");
   const util::DateTime end(xx.validTime1() + len);
   Log::info() << classname() << "::forecast: starting 1: " << xx.state1()
               << std::endl;
   Log::info() << classname() << "::forecast: starting 2: " << xx.state2()
               << std::endl;
   this->initialize(xx, maux);
   post.post1().initialize(xx.state1(), end, model1_->timeResolution());
   post.post2().initialize(xx.state2(), end, model2_->timeResolution());
   while (xx.validTime1() < end) {
     Log::info() << classname() << "::step starting" << std::endl
                 << "  t1 = " << xx.validTime1() << std::endl
                 << "  t2 = " << xx.validTime2() << std::endl;
     if (xx.validTime2() == xx.validTime1()) {
       xx.state2().forceWith(xx.state1(), varsForced2_);
       xx.state1().forceWith(xx.state2(), varsForced1_);
     }
     this->step(xx, maux);
     post.post1().process(xx.state1());
     if (xx.validTime2() == xx.validTime1()) post.post2().process(xx.state2());
     Log::info() << classname() << "::step done" << std::endl;
   }
   post.post1().finalize(xx.state1());
   post.post2().finalize(xx.state2());
   this->finalize(xx);
   Log::info() << classname() << "::forecast: forecast finished: " << xx
               << std::endl;
   ASSERT(xx.validTime1() == end);
   ASSERT(xx.validTime2() == end);
   Log::trace() << classname() << "::forecast done" << std::endl;
 }
References oops::State< MODEL >::forceWith(), oops::DualConfigPostProcessor< FLDS >::post1(), oops::DualConfigPostProcessor< FLDS >::post2(), oops::DualConfigState< MODEL >::state1(), oops::DualConfigState< MODEL >::state2(), oops::DualConfigState< MODEL >::validTime1(), and oops::DualConfigState< MODEL >::validTime2().
Referenced by oops::DualConfigForecast< MODEL >::execute().
initialize()
template<typename MODEL > void oops::DualConfigModel< MODEL >::initialize (DualConfigState_ & xx, const DualConfigModelAuxControl_ & maux) const private
Definition at line 188 of file DualConfigModel.h.
{
   Log::trace() << classname() << "initialize starting" << std::endl;
   util::Timer timer(classname(), "initialize");
   model1_->initialize(xx.state1(), maux.modelauxcontrol1());
   model2_->initialize(xx.state2(), maux.modelauxcontrol2());
   Log::trace() << classname() << "initialize done" << std::endl;
 }
References oops::DualConfigModelAuxControl< MODEL >::modelauxcontrol1(), oops::DualConfigModelAuxControl< MODEL >::modelauxcontrol2(), oops::DualConfigState< MODEL >::state1(), and oops::DualConfigState< MODEL >::state2().
model1()
template<typename MODEL > const Model_& oops::DualConfigModel< MODEL >::model1 () const inline
Definition at line 83 of file DualConfigModel.h.
 { return *model1_; }
References oops::DualConfigModel< MODEL >::model1_.
Referenced by oops::DualConfigModelAuxControl< MODEL >::DualConfigModelAuxControl(), and oops::DualConfigState< MODEL >::DualConfigState().
model2()
template<typename MODEL > const Model_& oops::DualConfigModel< MODEL >::model2 () const inline
Definition at line 84 of file DualConfigModel.h.
 { return *model2_; }
References oops::DualConfigModel< MODEL >::model2_.
Referenced by oops::DualConfigModelAuxControl< MODEL >::DualConfigModelAuxControl(), and oops::DualConfigState< MODEL >::DualConfigState().
print()
template<typename MODEL > void oops::DualConfigModel< MODEL >::print (std::ostream & os) const private
Definition at line 224 of file DualConfigModel.h.
{
   Log::trace() << classname() << "::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   os << *model1_;
   os << *model2_;
   Log::trace() << classname() << "::print done" << std::endl;
 }
step()
template<typename MODEL > void oops::DualConfigModel< MODEL >::step (DualConfigState_ & xx, const DualConfigModelAuxControl_ & maux) const private
Definition at line 200 of file DualConfigModel.h.
{
   Log::trace() << classname() << "::step starting" << std::endl;
   util::Timer timer(classname(), "step");
   model1_->step(xx.state1(), maux.modelauxcontrol1());
   if (xx.validTime2() < xx.validTime1())
     model2_->step(xx.state2(), maux.modelauxcontrol2());
   Log::trace() << classname() << "::step done" << std::endl;
 }
References oops::DualConfigModelAuxControl< MODEL >::modelauxcontrol1(), oops::DualConfigModelAuxControl< MODEL >::modelauxcontrol2(), oops::DualConfigState< MODEL >::state1(), oops::DualConfigState< MODEL >::state2(), oops::DualConfigState< MODEL >::validTime1(), and oops::DualConfigState< MODEL >::validTime2().
timeResolution1()
template<typename MODEL > const util::Duration& oops::DualConfigModel< MODEL >::timeResolution1 () const inline
Definition at line 75 of file DualConfigModel.h.
{
     return model1_->timeResolution();
   }
References oops::DualConfigModel< MODEL >::model1_.
timeResolution2()
template<typename MODEL > const util::Duration& oops::DualConfigModel< MODEL >::timeResolution2 () const inline
Definition at line 78 of file DualConfigModel.h.
{
     return model2_->timeResolution();
   }
References oops::DualConfigModel< MODEL >::model2_.
Member Data Documentation
model1_
template<typename MODEL > std::unique_ptr<Model_> oops::DualConfigModel< MODEL >::model1_ private
Definition at line 92 of file DualConfigModel.h.
Referenced by oops::DualConfigModel< MODEL >::DualConfigModel(), oops::DualConfigModel< MODEL >::model1(), and oops::DualConfigModel< MODEL >::timeResolution1().
model2_
template<typename MODEL > std::unique_ptr<Model_> oops::DualConfigModel< MODEL >::model2_ private
Definition at line 93 of file DualConfigModel.h.
Referenced by oops::DualConfigModel< MODEL >::DualConfigModel(), oops::DualConfigModel< MODEL >::model2(), and oops::DualConfigModel< MODEL >::timeResolution2().
varsForced1_
template<typename MODEL > const Variables_ oops::DualConfigModel< MODEL >::varsForced1_ private
Definition at line 94 of file DualConfigModel.h.
varsForced2_
template<typename MODEL > const Variables_ oops::DualConfigModel< MODEL >::varsForced2_ private
Definition at line 95 of file DualConfigModel.h.
The documentation for this class was generated from the following file:
src/oops/generic/DualConfigModel.h