OOPS Documentation: oops::DualConfigForecast< MODEL > Class Template Reference
oops::DualConfigForecast< MODEL > Class Template Reference
#include <DualConfigForecast.h>
Public Member Functions
DualConfigForecast ()
virtual ~DualConfigForecast ()
int execute (const eckit::Configuration &fullConfig) const
Public Member Functions inherited from oops::Application
Application ()
virtual ~Application ()
Private Types
using DualConfigGeometry_ = DualConfigGeometry< MODEL >
using DualConfigModel_ = DualConfigModel< MODEL >
using DualConfigModelAux_ = DualConfigModelAuxControl< MODEL >
using DualConfigState_ = DualConfigState< MODEL >
using Geometry_ = Geometry< MODEL >
using Model_ = Model< MODEL >
using ModelAux_ = ModelAuxControl< MODEL >
using State_ = State< MODEL >
Private Member Functions
std::string appname () const
Detailed Description
template<typename MODEL>
class oops::DualConfigForecast< MODEL >
Definition at line 39 of file DualConfigForecast.h.
Member Typedef Documentation
DualConfigGeometry_
template<typename MODEL > using oops::DualConfigForecast< MODEL >::DualConfigGeometry_ = DualConfigGeometry<MODEL> private
Definition at line 40 of file DualConfigForecast.h.
DualConfigModel_
template<typename MODEL > using oops::DualConfigForecast< MODEL >::DualConfigModel_ = DualConfigModel<MODEL> private
Definition at line 41 of file DualConfigForecast.h.
DualConfigModelAux_
template<typename MODEL > using oops::DualConfigForecast< MODEL >::DualConfigModelAux_ = DualConfigModelAuxControl<MODEL> private
Definition at line 42 of file DualConfigForecast.h.
DualConfigState_
template<typename MODEL > using oops::DualConfigForecast< MODEL >::DualConfigState_ = DualConfigState<MODEL> private
Definition at line 43 of file DualConfigForecast.h.
Geometry_
template<typename MODEL > using oops::DualConfigForecast< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 44 of file DualConfigForecast.h.
Model_
template<typename MODEL > using oops::DualConfigForecast< MODEL >::Model_ = Model<MODEL> private
Definition at line 45 of file DualConfigForecast.h.
ModelAux_
template<typename MODEL > using oops::DualConfigForecast< MODEL >::ModelAux_ = ModelAuxControl<MODEL> private
Definition at line 46 of file DualConfigForecast.h.
State_
template<typename MODEL > using oops::DualConfigForecast< MODEL >::State_ = State<MODEL> private
Definition at line 47 of file DualConfigForecast.h.
Constructor & Destructor Documentation
DualConfigForecast()
template<typename MODEL > oops::DualConfigForecast< MODEL >::DualConfigForecast () inline
Definition at line 51 of file DualConfigForecast.h.
 {}
~DualConfigForecast()
template<typename MODEL > virtual oops::DualConfigForecast< MODEL >::~DualConfigForecast () inline virtual
Definition at line 53 of file DualConfigForecast.h.
 {}
Member Function Documentation
appname()
template<typename MODEL > std::string oops::DualConfigForecast< MODEL >::appname () const inline private virtual
Implements oops::Application.
Definition at line 108 of file DualConfigForecast.h.
{
     return "oops::DualConfigForecast<" + MODEL::name() + ">";
   }
execute()
template<typename MODEL > int oops::DualConfigForecast< MODEL >::execute (const eckit::Configuration & fullConfig) const inline virtual
Implements oops::Application.
Definition at line 55 of file DualConfigForecast.h.
{
     //  Setup resolution
     const eckit::LocalConfiguration resolConfig(fullConfig, "resolution");
     const DualConfigGeometry_ resol(resolConfig);
     //  Setup Model
     const eckit::LocalConfiguration modelConfig(fullConfig, "model");
     const DualConfigModel_ model(resol, modelConfig);
     //  Setup initial state
     const eckit::LocalConfiguration initialConfig(fullConfig, "initial");
     DualConfigState_ xx(resol, model, initialConfig);
     Log::test() << "Initial state: " << xx.norm() << std::endl;
     //  Setup augmented state
     const DualConfigModelAux_ moderr(resol, model, initialConfig);
     //  Setup times
     const util::Duration fclength(fullConfig.getString("forecast_length"));
     const util::DateTime bgndate(xx.validTime1());
     const util::DateTime enddate(bgndate + fclength);
     Log::info() << "Running dual-config forecast from " << bgndate << " to "
                 << enddate << std::endl;
     //  Setup forecast outputs
     DualConfigPostProcessor<State_> post;
     eckit::LocalConfiguration prtConfig;
     eckit::LocalConfiguration prtConfig1;
     eckit::LocalConfiguration prtConfig2;
     if (fullConfig.has("prints")) {
       prtConfig = eckit::LocalConfiguration(fullConfig, "prints");
       prtConfig1 = eckit::LocalConfiguration(prtConfig, "prints1");
       prtConfig2 = eckit::LocalConfiguration(prtConfig, "prints2");
     }
     post.post1().enrollProcessor(new StateInfo<State_>("fc", prtConfig1));
     post.post2().enrollProcessor(new StateInfo<State_>("fc", prtConfig2));
     const eckit::LocalConfiguration outConfig(fullConfig, "output");
     const eckit::LocalConfiguration outConfig1(outConfig, "output1");
     const eckit::LocalConfiguration outConfig2(outConfig, "output2");
     post.post1().enrollProcessor(new StateWriter<State_>(bgndate, outConfig1));
     post.post2().enrollProcessor(new StateWriter<State_>(bgndate, outConfig2));
     //  Run forecast
     model.forecast(xx, moderr, fclength, post);
     Log::test() << "Final state: " << xx.norm() << std::endl;
     return 0;
   }
References oops::DualConfigModel< MODEL >::forecast(), oops::DualConfigState< MODEL >::norm(), oops::DualConfigPostProcessor< FLDS >::post1(), oops::DualConfigPostProcessor< FLDS >::post2(), and oops::DualConfigState< MODEL >::validTime1().
The documentation for this class was generated from the following file:
src/oops/runs/DualConfigForecast.h