OOPS Documentation: oops::PostBaseAD< INCR > Class Template Reference
oops::PostBaseAD< INCR > Class Template Reference abstract
Handles post-processing of model fields related to cost function.
#include <PostBaseAD.h>
Public Member Functions
PostBaseAD ()
PostBaseAD (const util::DateTime &start, const util::DateTime &finish, const util::Duration &freq=util::Duration(0))
virtual ~PostBaseAD ()
void initializeAD (INCR &dx, const util::DateTime &bgn, const util::Duration &step)
void processAD (INCR &dx)
void finalizeAD (INCR &dx)
Private Member Functions
virtual void doFirstAD (INCR &, const util::DateTime &, const util::Duration &)=0
virtual void doProcessingAD (INCR &)=0
virtual void doLastAD (INCR &)=0
Private Attributes
PostTimer timer_
Detailed Description
template<typename INCR>
class oops::PostBaseAD< INCR >
Handles post-processing of model fields related to cost function.
PostBaseAD is the base class for all cost function processors, it is mostly used so that PostProcessorAD can hold a vector of such processors. The difference with PostBase is that the adjoint can modify the increment.
Definition at line 35 of file PostBaseAD.h.
Constructor & Destructor Documentation
PostBaseAD() [1/2]
template<typename INCR > oops::PostBaseAD< INCR >::PostBaseAD () inline
Definition at line 37 of file PostBaseAD.h.
 : timer_() {}
PostBaseAD() [2/2]
template<typename INCR > oops::PostBaseAD< INCR >::PostBaseAD (const util::DateTime & start, const util::DateTime & finish, const util::Duration & freq = util::Duration(0)) inline
Definition at line 38 of file PostBaseAD.h.
       : timer_(start, finish, freq) {}
~PostBaseAD()
template<typename INCR > virtual oops::PostBaseAD< INCR >::~PostBaseAD () inline virtual
Definition at line 41 of file PostBaseAD.h.
 {}
Member Function Documentation
doFirstAD()
template<typename INCR > virtual void oops::PostBaseAD< INCR >::doFirstAD (INCR & , const util::DateTime & , const util::Duration &) private pure virtual
Implemented in oops::ObserverAD< MODEL, INCR >, oops::WeightedDiffAD< INCR >, and oops::ObserverEnVarAD< MODEL, INCR >.
Referenced by oops::PostBaseAD< INCR >::initializeAD().
doLastAD()
template<typename INCR > virtual void oops::PostBaseAD< INCR >::doLastAD (INCR &) private pure virtual
Implemented in oops::ObserverAD< MODEL, INCR >, oops::WeightedDiffAD< INCR >, and oops::ObserverEnVarAD< MODEL, INCR >.
Referenced by oops::PostBaseAD< INCR >::finalizeAD().
doProcessingAD()
template<typename INCR > virtual void oops::PostBaseAD< INCR >::doProcessingAD (INCR &) private pure virtual
Implemented in oops::ObserverAD< MODEL, INCR >, oops::WeightedDiffAD< INCR >, and oops::ObserverEnVarAD< MODEL, INCR >.
Referenced by oops::PostBaseAD< INCR >::finalizeAD(), and oops::PostBaseAD< INCR >::processAD().
finalizeAD()
template<typename INCR > void oops::PostBaseAD< INCR >::finalizeAD (INCR & dx) inline
Definition at line 53 of file PostBaseAD.h.
{
     if (timer_.itIsTime(dx.validTime())) this->doProcessingAD(dx);
     this->doLastAD(dx);
   }
References oops::PostBaseAD< INCR >::doLastAD(), oops::PostBaseAD< INCR >::doProcessingAD(), oops::PostTimer::itIsTime(), and oops::PostBaseAD< INCR >::timer_.
initializeAD()
template<typename INCR > void oops::PostBaseAD< INCR >::initializeAD (INCR & dx, const util::DateTime & bgn, const util::Duration & step) inline
Definition at line 43 of file PostBaseAD.h.
{
     timer_.initialize(bgn, dx.validTime(), step);
     this->doFirstAD(dx, bgn, step);
   }
References oops::PostBaseAD< INCR >::doFirstAD(), oops::PostTimer::initialize(), and oops::PostBaseAD< INCR >::timer_.
processAD()
template<typename INCR > void oops::PostBaseAD< INCR >::processAD (INCR & dx) inline
Definition at line 49 of file PostBaseAD.h.
{
     if (timer_.itIsTime(dx.validTime())) this->doProcessingAD(dx);
   }
References oops::PostBaseAD< INCR >::doProcessingAD(), oops::PostTimer::itIsTime(), and oops::PostBaseAD< INCR >::timer_.
Member Data Documentation
timer_
template<typename INCR > PostTimer oops::PostBaseAD< INCR >::timer_ private
Definition at line 59 of file PostBaseAD.h.
Referenced by oops::PostBaseAD< INCR >::finalizeAD(), oops::PostBaseAD< INCR >::initializeAD(), and oops::PostBaseAD< INCR >::processAD().
The documentation for this class was generated from the following file:
src/oops/base/PostBaseAD.h