OOPS Documentation: oops::Advector< MODEL > Class Template Reference
oops::Advector< MODEL > Class Template Reference
Advection operator.
#include <Advector.h>
Public Member Functions
Advector (const State_ &, const eckit::Configuration &, const bool is_adjoint)
Advector & operator= (const Advector &)
void set_vector (const eckit::Configuration &)
void set_wind (const State4D_ &, const util::DateTime &)
void set_wind_inv (const State4D_ &, const util::DateTime &)
void set_wind (const State4D_ &)
void set_wind_inv (const State4D_ &)
void advect (const Increment_ &, const eckit::Configuration &, Increment_ &)
void advect (const State_ &, const eckit::Configuration &, State_ &)
Public Member Functions inherited from oops::Interpolator< MODEL >
Interpolator (const State_ &, const eckit::Configuration &, const bool)
Interpolator (const State_ &, const Geometry_ &, const eckit::Configuration &, const bool)
Interpolator (const Interpolator &)
virtual ~Interpolator ()
Interpolator & operator= (const Interpolator &)
Interpolator & operator+= (const State_ &)
Interpolator & operator-= (const State_ &)
void set (const Geometry_ &, const Geometry_ &)
void interpolate (const Increment_ &, const Variables_ &, Increment_ &) const
void interpolate (const State_ &, const Variables_ &, State_ &) const
void smooth (Increment_ &) const
void save (Increment_ &) const
void read (const Increment_ &)
void write (const eckit::Configuration &) const
Private Types
using State4D_ = std::vector< std::unique_ptr< State< MODEL > > >
using Geometry_ = Geometry< MODEL >
using Variables_ = Variables< MODEL >
using Increment_ = Increment< MODEL >
using State_ = State< MODEL >
using Interpolator_ = Interpolator< MODEL >
Private Attributes
const eckit::LocalConfiguration config_
const eckit::LocalConfiguration vars_
const util::DateTime time_
unsigned niter_
double wind_coeff_
Additional Inherited Members
Static Public Member Functions inherited from oops::Interpolator< MODEL >
static const std::string classname ()
Detailed Description
template<typename MODEL>
class oops::Advector< MODEL >
Advection operator.
Definition at line 32 of file Advector.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::Advector< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 34 of file Advector.h.
Increment_
template<typename MODEL > using oops::Advector< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 36 of file Advector.h.
Interpolator_
template<typename MODEL > using oops::Advector< MODEL >::Interpolator_ = Interpolator<MODEL> private
Definition at line 38 of file Advector.h.
State4D_
template<typename MODEL > using oops::Advector< MODEL >::State4D_ = std::vector<std::unique_ptr<State<MODEL> > > private
Definition at line 33 of file Advector.h.
State_
template<typename MODEL > using oops::Advector< MODEL >::State_ = State<MODEL> private
Definition at line 37 of file Advector.h.
Variables_
template<typename MODEL > using oops::Advector< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 35 of file Advector.h.
Constructor & Destructor Documentation
Advector()
template<typename MODEL > oops::Advector< MODEL >::Advector (const State_ & xb, const eckit::Configuration & config, const bool is_adjoint)
Definition at line 64 of file Advector.h.
     : Interpolator_(xb, config, is_adjoint),
       config_(config),
       vars_(config, "wind"),
       time_(xb.validTime()) {
   niter_ = config.getInt("nb_iter_point_fixe");
   // Change default value for wind coefficient
   wind_coeff_ = 0.75;
   if (config.has("wind_coeff")) {
     wind_coeff_ = config.getDouble("wind_coeff");
   }
   Log::trace() << "Advector:Advector created";
 }
References oops::Advector< MODEL >::niter_, and oops::Advector< MODEL >::wind_coeff_.
Member Function Documentation
advect() [1/2]
template<typename MODEL > void oops::Advector< MODEL >::advect (const Increment_ & dxin, const eckit::Configuration & cfg, Increment_ & dxout)
Definition at line 96 of file Advector.h.
{
   const Variables_ var(cfg);
   this->interpolate(dxin, var, dxout);
 }
Referenced by oops::Advector< MODEL >::set_wind(), and oops::Advector< MODEL >::set_wind_inv().
advect() [2/2]
template<typename MODEL > void oops::Advector< MODEL >::advect (const State_ & xin, const eckit::Configuration & cfg, State_ & xout)
Definition at line 105 of file Advector.h.
{
   const Variables_ var(cfg);
   this->interpolate(xin, var, xout);
 }
operator=()
template<typename MODEL > Advector< MODEL > & oops::Advector< MODEL >::operator= (const Advector< MODEL > & other)
Definition at line 82 of file Advector.h.
{
   Interpolator_ *this_interp = this;
   (*this_interp) = other;
   return *this;
 }
set_vector()
template<typename MODEL > void oops::Advector< MODEL >::set_vector (const eckit::Configuration & cfg) virtual
Reimplemented from oops::Interpolator< MODEL >.
Definition at line 90 of file Advector.h.
{
   Interpolator_::set_vector(cfg);
 }
set_wind() [1/2]
template<typename MODEL > void oops::Advector< MODEL >::set_wind (const State4D_ & wind)
Definition at line 181 of file Advector.h.
{
   set_wind(wind, wind[0]->validTime());
 }
set_wind() [2/2]
template<typename MODEL > void oops::Advector< MODEL >::set_wind (const State4D_ & wind, const util::DateTime & date_start)
Definition at line 113 of file Advector.h.
{
   util::Duration step(wind[1]->validTime() - wind[0]->validTime());
   double deltat = (double)step.toSeconds();
   unsigned kstart = 0;
   unsigned kstop = 0;
   // Initialize with vector (0,0)
   set_vector(config_);
   for (unsigned k = 0; k < wind.size(); k++) {
     if (wind[k]->validTime() == time_) kstop = k;
     if (wind[k]->validTime() == date_start) kstart = k;
   }
   // Advect the grid step by step
   Advector<MODEL> s_star(*this);
   for (unsigned k = kstop; k > kstart; k -= 1) {
     for (unsigned iter = 0; iter < niter_; iter++) {
       Accumulator<MODEL, State_, State_> uv(*wind[k - 1]);
       uv.accumul(wind_coeff_, *wind[k - 1]);
       s_star.advect(uv, vars_, uv);
       Accumulator<MODEL, State_, State_> delta_xy(uv);
       delta_xy.accumul(deltat, uv);
       s_star = (*this);
       s_star -= delta_xy;
     }
     (*this) = s_star;
   }
 }
References oops::Accumulator< MODEL, ACC, FLDS >::accumul(), and oops::Advector< MODEL >::advect().
set_wind_inv() [1/2]
template<typename MODEL > void oops::Advector< MODEL >::set_wind_inv (const State4D_ & wind)
Definition at line 187 of file Advector.h.
{
   set_wind_inv(wind, wind[0]->validTime());
 }
set_wind_inv() [2/2]
template<typename MODEL > void oops::Advector< MODEL >::set_wind_inv (const State4D_ & wind, const util::DateTime & date_start)
Definition at line 148 of file Advector.h.
{
   util::Duration step(wind[1]->validTime() - wind[0]->validTime());
   double deltat = (double)step.toSeconds();
   unsigned kstart = 0;
   unsigned kstop = 0;
   set_vector(config_);
   for (unsigned k = 0; k < wind.size(); k++) {
     if (wind[k]->validTime() == time_) kstop = k;
     if (wind[k]->validTime() == date_start) kstart = k;
   }
   Advector<MODEL> s_star(*this);
   for (unsigned k = 1 + kstart; k <= kstop; ++k) {
     for (unsigned iter = 0; iter < niter_; iter++) {
       Accumulator<MODEL, State_, State_> uv(*wind[k]);
       uv.accumul(wind_coeff_, *wind[k]);
       s_star.advect(uv, vars_, uv);
       Accumulator<MODEL, State_, State_> delta_xy(uv);
       delta_xy.accumul(deltat, uv);
       s_star = (*this);
       s_star += delta_xy;
     }
     (*this) = s_star;
   }
 }
References oops::Accumulator< MODEL, ACC, FLDS >::accumul(), and oops::Advector< MODEL >::advect().
Member Data Documentation
config_
template<typename MODEL > const eckit::LocalConfiguration oops::Advector< MODEL >::config_ private
Definition at line 54 of file Advector.h.
niter_
template<typename MODEL > unsigned oops::Advector< MODEL >::niter_ private
Definition at line 57 of file Advector.h.
Referenced by oops::Advector< MODEL >::Advector().
time_
template<typename MODEL > const util::DateTime oops::Advector< MODEL >::time_ private
Definition at line 56 of file Advector.h.
vars_
template<typename MODEL > const eckit::LocalConfiguration oops::Advector< MODEL >::vars_ private
Definition at line 55 of file Advector.h.
wind_coeff_
template<typename MODEL > double oops::Advector< MODEL >::wind_coeff_ private
Definition at line 58 of file Advector.h.
Referenced by oops::Advector< MODEL >::Advector().
The documentation for this class was generated from the following file:
src/oops/base/Advector.h