OOPS Documentation: oops::Minimizer< MODEL > Class Template Reference
oops::Minimizer< MODEL > Class Template Reference abstract
Abstract base class for minimizers.
#include <Minimizer.h>
Public Member Functions
virtual const std::string classname () const =0
Minimizer (const CostFct_ &J)
Construct a minimizer.
virtual ~Minimizer ()
Destroy a minimizer.
ControlIncrement< MODEL > * minimize (const eckit::Configuration &)
Orchestrate the minimization of a quadratic cost function.
virtual void checkpoint (eckit::LocalConfiguration &) const =0
Checkpoint the minimizer (virtual method)
virtual void restart (const eckit::Configuration &)=0
Restart the minimizer (virtual method)
virtual void warmStart (const eckit::Configuration &)=0
Warm start the minimizer (virtual method)
Private Types
using CostFct_ = CostFunction< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using Dual_ = DualVector< MODEL >
using H_ = HMatrix< MODEL >
using Ht_ = HtMatrix< MODEL >
using M_ = MMatrix< MODEL >
using Mt_ = MtMatrix< MODEL >
using State_ = State< MODEL >
Private Member Functions
virtual ControlIncrement< MODEL > * doMinimize (const eckit::Configuration &)=0
Minimizer the quadratic cost function (virtual method)
void adjTests (const eckit::Configuration &) const
Perform adjoint tests.
void adjModelTest () const
Perform model adjoint tests.
void adjObsTest () const
Perform observation operator adjoint tests.
void tlmTests (const eckit::Configuration &) const
Perform tangent linear model tests.
void tlmApproxTest () const
Perform tangent linear model approximation test.
void tlmTaylorTest () const
Perform the Tayolor test.
void tlmPropagTest (const eckit::Configuration &config, const CtrlInc_ &) const
Peroform the tangent linear propagation test.
Private Attributes
const CostFct_ & J_
Handle to the cost function.
int outerIteration_
Current outer loop index.
Detailed Description
template<typename MODEL>
class oops::Minimizer< MODEL >
Abstract base class for minimizers.
Minimizer defines an interface for families of minimizers; it manages the minimization and adjoint/tangent linear model testing. The following families of minimizers are available: DRMinimizer (right B preconditioned minimizers), DualMinimizer (observation space minimizers), PrimalMinimizer (model space minimizers), SQRTMinimizer (square root minimizers), SaddlePointMinimizer (saddle point formulation minimizers), LBMinimizer (left B precondtioned minimizers)
Concrete minimizers are produced by the MinFactory
IFS: SQRTMinimizer is employed by default
Definition at line 60 of file Minimizer.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::Minimizer< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 61 of file Minimizer.h.
CtrlInc_
template<typename MODEL > using oops::Minimizer< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 62 of file Minimizer.h.
Dual_
template<typename MODEL > using oops::Minimizer< MODEL >::Dual_ = DualVector<MODEL> private
Definition at line 63 of file Minimizer.h.
H_
template<typename MODEL > using oops::Minimizer< MODEL >::H_ = HMatrix<MODEL> private
Definition at line 64 of file Minimizer.h.
Ht_
template<typename MODEL > using oops::Minimizer< MODEL >::Ht_ = HtMatrix<MODEL> private
Definition at line 65 of file Minimizer.h.
M_
template<typename MODEL > using oops::Minimizer< MODEL >::M_ = MMatrix<MODEL> private
Definition at line 66 of file Minimizer.h.
Mt_
template<typename MODEL > using oops::Minimizer< MODEL >::Mt_ = MtMatrix<MODEL> private
Definition at line 67 of file Minimizer.h.
State_
template<typename MODEL > using oops::Minimizer< MODEL >::State_ = State<MODEL> private
Definition at line 68 of file Minimizer.h.
Constructor & Destructor Documentation
Minimizer()
template<typename MODEL > oops::Minimizer< MODEL >::Minimizer (const CostFct_ & J) inline explicit
Construct a minimizer.
Definition at line 74 of file Minimizer.h.
 : J_(J), outerIteration_(0){};
~Minimizer()
template<typename MODEL > virtual oops::Minimizer< MODEL >::~Minimizer () inline virtual
Destroy a minimizer.
Definition at line 77 of file Minimizer.h.
 {}
Member Function Documentation
adjModelTest()
template<typename MODEL > void oops::Minimizer< MODEL >::adjModelTest private
Perform model adjoint tests.
Perform the adjoint test of the linear model:
<M dx1, dx2> - <dx1, Mt dx2>)/<M dx1, dx2>
where dx1 and dx2 are increments obtained through randomization
Construct the linear model matrix operator and its adjoint
Instantiate and initialize increments using randomization
Propagate dx1 with the tangent linear model
Propagate backwards dx2 with the adjoint of the linear model
Calculate < M dx1, dx2 >
Calculate < dx1, Mt dx2 >
Print results
Definition at line 355 of file Minimizer.h.
{
   const M_ M(J_);
   const Mt_ Mt(J_);
   CtrlInc_ dx1(J_.jb().getFirstGuessIncrement(), false);
   CtrlInc_ dx2(J_.jb().getFirstGuessIncrement(), false);
   J_.jb().randomize(dx1);
   J_.jb().randomize(dx2);
   CtrlInc_ mdx1(dx1);
   M.multiply(mdx1);
   CtrlInc_ mtdx2(dx2);
   mtdx2.state()[0].updateTime(mdx1.state()[0].validTime() -
                               dx1.state()[0].validTime());
   Mt.multiply(mtdx2);
   double adj_tst_fwd = dot_product(mdx1, dx2);
   double adj_tst_bwd = dot_product(dx1, mtdx2);
   Log::info() << "Model Adjoint Test: " << outerIteration_ << std::endl
               << util::PrintAdjTest(adj_tst_fwd, adj_tst_bwd, "M") << std::endl
               << std::endl;
 }
References dot_product(), oops::MMatrix< MODEL >::multiply(), oops::MtMatrix< MODEL >::multiply(), and oops::ControlIncrement< MODEL >::state().
adjObsTest()
template<typename MODEL > void oops::Minimizer< MODEL >::adjObsTest private
Perform observation operator adjoint tests.
Perform the adjoint test of the linear observation operator:
(<H dx, dy> - <dx, Ht dy>)/<H dx, dy>
where dx is an increment obtained through randomization and dy is a DualVector obtained by first creating an increment through randomization and then applying a linear observation operator
Note that the \(H = [\overline{H} P] [dx d\beta]\), where \(\overline{H}\) is the linear observation operator and \(P\) is the linear bias operator
A. Perform adjoint test of the composite observation and bias operator \([\overline{H} P] [dx d\beta]\)
Construct linear obs operator matrix and its adjoint
A.1 Instantiate and initialize increments and dual vectors
A.2 Create a new set of increments
A.3 Compute H dx1 and H dx2
A.4 Compute H^T (H dx2)
A.5 Calculate FWD < H dx1, H dx2 >
A.6 Calculate BWD < dx1, H^T (H dx2) >
A.7 Print results
B. Perform adjoint test of the observation operator only \(\overline{H}\). This is achieved by zeroing out the auxiliary observation space component of the control increment
B.1 Reset increments
B.2 Zero out auxiliary obs space component of ControlIncrements
B.3 Compute H dx1 and H dx2
B.4 Copmpute H^T (H dx2)
B.5 Calculate FWD < H dx1, H dx2 >
B.6 Calculate BWD < dx1, H^T (H dx2) >
B.7 Print results
C. Perform adjoint test of the bias operator only \(P\). This is achieved by zeroing out the state increment component of the control increment
C.1 Reset increments
C.2 Reset state increment component of ControlIncrements
C.3 Compute H dx1 and H dx2
C.4 Compute H^T (H dx2)
C.5 Calculate FWD < H dx1, H dx2 >
C.6 Calculate BWD < dx1, Ht (H dx2) >
C.7 Print results
Definition at line 399 of file Minimizer.h.
{
   const H_ H(J_);
   const Ht_ Ht(J_);
   CtrlInc_ dx1(J_.jb().getFirstGuessIncrement(), false);
   CtrlInc_ dx2(J_.jb().getFirstGuessIncrement(), false);
   CtrlInc_ hthdx2(J_.jb().getFirstGuessIncrement(), false);
   Dual_ hdx1;
   Dual_ hdx2;
   // randomize increments
   J_.jb().randomize(dx1);
   J_.jb().randomize(dx2);
   std::unique_ptr<CtrlInc_> dx1wrk(new CtrlInc_(dx1));
   std::unique_ptr<CtrlInc_> dx2wrk(new CtrlInc_(dx2));
   H.multiply(*dx1wrk, hdx1, true);
   H.multiply(*dx2wrk, hdx2, true);
   J_.zeroAD(hthdx2);
   Ht.multiply(hdx2, hthdx2, true);
   double adj_tst_fwd = dot_product(hdx1, hdx2);
   double adj_tst_bwd = dot_product(*dx1wrk, hthdx2);
   Log::info() << "Obs Adjoint Test: " << outerIteration_ << std::endl
               << util::PrintAdjTest(adj_tst_fwd, adj_tst_bwd, "HP") << std::endl
               << std::endl;
   //
   //
   hdx1.zero();
   hdx2.zero();
   dx1wrk.reset(new CtrlInc_(dx1));
   dx2wrk.reset(new CtrlInc_(dx2));
   dx1wrk->obsVar().zero();
   dx2wrk->obsVar().zero();
   H.multiply(*dx1wrk, hdx1, true);
   H.multiply(*dx2wrk, hdx2, true);
   J_.zeroAD(hthdx2);
   Ht.multiply(hdx2, hthdx2, true);
   adj_tst_fwd = dot_product(hdx1, hdx2);
   adj_tst_bwd = dot_product(*dx1wrk, hthdx2);
   Log::info() << "Obs Only Adjoint Test: " << outerIteration_ << std::endl
               << util::PrintAdjTest(adj_tst_fwd, adj_tst_bwd, "H") << std::endl
               << std::endl;
   //
   //
   hdx1.zero();
   hdx2.zero();
   dx1wrk.reset(new CtrlInc_(dx1));
   dx2wrk.reset(new CtrlInc_(dx2));
   dx1wrk->state().zero();
   dx2wrk->state().zero();
   H.multiply(*dx1wrk, hdx1, true);
   H.multiply(*dx2wrk, hdx2, true);
   J_.zeroAD(hthdx2);
   Ht.multiply(hdx2, hthdx2, true);
   adj_tst_fwd = dot_product(hdx1, hdx2);
   adj_tst_bwd = dot_product(*dx1wrk, hthdx2);
   Log::info() << "Obs Bias Only Adjoint Test: " << outerIteration_ << std::endl
               << util::PrintAdjTest(adj_tst_fwd, adj_tst_bwd, "P") << std::endl
               << std::endl;
 }
References dot_product(), oops::HtMatrix< MODEL >::multiply(), oops::HMatrix< MODEL >::multiply(), and oops::DualVector< MODEL >::zero().
adjTests()
template<typename MODEL > void oops::Minimizer< MODEL >::adjTests (const eckit::Configuration & config) const private
Perform adjoint tests.
Adjoint tests are performed if onlineDiagnostics configuration is found
Model adjoint test
Obs adjoint test
Definition at line 174 of file Minimizer.h.
{
   if (config.has("onlineDiagnostics")) {
     const eckit::LocalConfiguration onlineDiag(config, "onlineDiagnostics");
     bool runAdjTlmTest = onlineDiag.getBool("adjTlmTest");
     bool runAdjObsTest = onlineDiag.getBool("adjObsTest");
     // Online tests
     if (runAdjTlmTest) {
       util::LogbookWriter<std::string> log("AdjTests", "AdjModelTests");
       this->adjModelTest();
     }
     if (runAdjObsTest) {
       util::LogbookWriter<std::string> log("AdjTests", "AdjObsTests");
       this->adjObsTest();
     }
   }
 }
checkpoint()
template<typename MODEL > virtual void oops::Minimizer< MODEL >::checkpoint (eckit::LocalConfiguration &) const pure virtual
Checkpoint the minimizer (virtual method)
Implemented in oops::SQRTMinimizer< MODEL >, oops::SaddlePointMinimizer< MODEL >, oops::DRMinimizer< MODEL >, oops::DualMinimizer< MODEL >, oops::LBMinimizer< MODEL >, and oops::PrimalMinimizer< MODEL >.
classname()
template<typename MODEL > virtual const std::string oops::Minimizer< MODEL >::classname () const pure virtual
Implemented in oops::SQRTMinimizer< MODEL >, oops::DRMinimizer< MODEL >, oops::DualMinimizer< MODEL >, oops::LBMinimizer< MODEL >, oops::PrimalMinimizer< MODEL >, oops::DRPCGMinimizer< MODEL >, oops::DRIPCGMinimizer< MODEL >, oops::DRGMRESRMinimizer< MODEL >, oops::DRPLanczosMinimizer< MODEL >, oops::RPLanczosMinimizer< MODEL >, oops::RPCGMinimizer< MODEL >, oops::DRPFOMMinimizer< MODEL >, oops::LBGMRESRMinimizer< MODEL >, oops::SaddlePointMinimizer< MODEL >, oops::FGMRESMinimizer< MODEL >, oops::GMRESRMinimizer< MODEL >, oops::IPCGMinimizer< MODEL >, oops::MINRESMinimizer< MODEL >, oops::PCGMinimizer< MODEL >, oops::PLanczosMinimizer< MODEL >, oops::SQRTPLanczosMinimizer< MODEL >, oops::SQRTBPCGMinimizer< MODEL >, oops::SQRTPCGMinimizer< MODEL >, oops::SQRTBPFOMMinimizer< MODEL >, and oops::SQRTBPLanczosMinimizer< MODEL >.
doMinimize()
template<typename MODEL > virtual ControlIncrement<MODEL>* oops::Minimizer< MODEL >::doMinimize (const eckit::Configuration &) private pure virtual
Minimizer the quadratic cost function (virtual method)
Implemented in oops::SQRTMinimizer< MODEL >, oops::SaddlePointMinimizer< MODEL >, oops::DRMinimizer< MODEL >, oops::DualMinimizer< MODEL >, oops::LBMinimizer< MODEL >, and oops::PrimalMinimizer< MODEL >.
minimize()
template<typename MODEL > ControlIncrement< MODEL > * oops::Minimizer< MODEL >::minimize (const eckit::Configuration & config)
Orchestrate the minimization of a quadratic cost function.
Perform TLM tests
Perform ADJ tests
Minimize the cost function
Perform TLM propagation test
Update outer loop counter
Definition at line 124 of file Minimizer.h.
{
   this->tlmTests(config);
   this->adjTests(config);
   ControlIncrement<MODEL> *dx = this->doMinimize(config);
   this->tlmPropagTest(config, *dx);
   outerIteration_++;
   return dx;
 }
restart()
template<typename MODEL > virtual void oops::Minimizer< MODEL >::restart (const eckit::Configuration &) pure virtual
Restart the minimizer (virtual method)
Implemented in oops::SQRTMinimizer< MODEL >, oops::SaddlePointMinimizer< MODEL >, oops::DRMinimizer< MODEL >, oops::DualMinimizer< MODEL >, oops::LBMinimizer< MODEL >, and oops::PrimalMinimizer< MODEL >.
tlmApproxTest()
template<typename MODEL > void oops::Minimizer< MODEL >::tlmApproxTest private
Perform tangent linear model approximation test.
TL approx test:
calculate and store:
M(x + dx), M(x), M'(dx)
where dx is initialized using randomization
TO DO:
write to file depending on requirements
Construct the linear model matrix operator
Initialize the control incremet using randomization
Run the non-linear model starting from unperturbed initial conditions (x_b)
Run the non-linear model starting from perturbed initial conditions (x_b + dx)
Propagate the perurbation with the tangent linear model
Definition at line 200 of file Minimizer.h.
{
   Log::info() << std::endl
               << "TLM Linear Approximation Test - starting: " << outerIteration_
               << std::endl
               << std::endl;
   const M_ M(J_);
   CtrlInc_ dx(J_.jb().getFirstGuessIncrement(), false);
   J_.jb().randomize(dx);
   PostProcessor<State_> pp;
   ControlVariable<MODEL> mxx(J_.jb().getBackground());
   J_.runNL(mxx, pp);
   ControlVariable<MODEL> mpertxx(J_.jb().getBackground());
   J_.addIncrement(mpertxx, dx);
   J_.runNL(mpertxx, pp);
   CtrlInc_ mdx(dx);
   M.multiply(mdx);
   // print log
   Log::info() << std::endl
               << "TLM Linear Approximation Test: done." << std::endl;
 }
References oops::MMatrix< MODEL >::multiply().
tlmPropagTest()
template<typename MODEL > void oops::Minimizer< MODEL >::tlmPropagTest (const eckit::Configuration & config, const CtrlInc_ & dx) const private
Peroform the tangent linear propagation test.
TL propagation test:
calculate and store:
M'(dx)
where dx comes from minimization stopped at requested iteration
TO DO:
write to file depending on requirements
Construct linear model matrix operator
Propagete the control increment with the tangent linear model: M'(dx)
Definition at line 250 of file Minimizer.h.
{
   if (config.has("onlineDiagnostics")) {
     const eckit::LocalConfiguration onlineDiag(config, "onlineDiagnostics");
     bool runTlmPropagTest = onlineDiag.getBool("tlmPropagTest");
     if (runTlmPropagTest) {
       // print log
       Log::info() << "TLM Propagation Test - starting: " << outerIteration_
                   << std::endl
                   << std::endl;
       const M_ M(J_);
       CtrlInc_ mdx(dx);
       M.multiply(mdx);
       // print log
       Log::info() << std::endl << "TLM Propagation Test: done." << std::endl;
     }
   }
 }
References oops::MMatrix< MODEL >::multiply().
tlmTaylorTest()
template<typename MODEL > void oops::Minimizer< MODEL >::tlmTaylorTest private
Perform the Tayolor test.
TL Taylor test:
||M(x + p dx) - M(x)|| / ||M'(p dx)|| -> 1
where p is a scalar damping factor and dx is initialized using randomization
Construct linear model matrix
Instantiate and initialize the control increment using randomization
Run the non-linear model starting from unperturbed initial conditions (x_b)
Propagate the un-damped perturbation with the tangent linear model: M'(dx)
Loop over increments scaled with increasing damping factor
6.1 Compute ||p M'(dx)||
6.2 Propagate the perturbed state with the non-linear model NL: M(x+pdx)
6.3 Compute ||M(x+pdx) - M(x)||
6.4 Print results
Definition at line 292 of file Minimizer.h.
{
   Log::info() << std::endl
               << "TLM Taylor Test: " << outerIteration_ << std::endl;
   const M_ M(J_);
   CtrlInc_ dx(J_.jb().getFirstGuessIncrement(), false);
   J_.jb().randomize(dx);
   PostProcessor<State_> pp;
   ControlVariable<MODEL> mxx(J_.jb().getBackground());
   J_.runNL(mxx, pp);
   CtrlInc_ mdx(dx);
   M.multiply(mdx);
   for (unsigned int i = 0; i < 14; ++i) {
     CtrlInc_ pmdx(mdx);
     pmdx *= 1. / pow(10.0, i);
     double denom = sqrt(dot_product(pmdx, pmdx));
     ControlVariable<MODEL> mpertxx(J_.jb().getBackground());
     CtrlInc_ pdx(dx);
     pdx *= 1. / pow(10.0, i);
     J_.addIncrement(mpertxx, pdx);
     J_.runNL(mpertxx, pp);
     CtrlInc_ diff_nl(mdx, false);
     diff_nl.state()[0].diff(mpertxx.state()[0], mxx.state()[0]);
     double nom = sqrt(dot_product(diff_nl, diff_nl));
     Log::info() << std::endl
                 << "TLM Taylor test:  p = " << std::setw(8) << 1. / pow(10.0, i)
                 << ", ||M(x) - M(x+p dx)|| / ||p M'(dx)|| = "
                 << util::full_precision(1. + std::abs(1. - nom / denom))
                 << std::endl
                 << std::endl;
   }
   Log::info() << std::endl;
 }
References oops::Increment4D< MODEL >::diff(), dot_product(), util::full_precision(), oops::MMatrix< MODEL >::multiply(), oops::ControlVariable< MODEL >::state(), and oops::ControlIncrement< MODEL >::state().
tlmTests()
template<typename MODEL > void oops::Minimizer< MODEL >::tlmTests (const eckit::Configuration & config) const private
Perform tangent linear model tests.
Tangent Linear tests are performed if onlineDiagnostics configuration is found
TLM linear approximation test
TLM Taylor test
Definition at line 147 of file Minimizer.h.
{
   if (config.has("onlineDiagnostics")) {
     const eckit::LocalConfiguration onlineDiag(config, "onlineDiagnostics");
     bool runTlmTaylorTest = onlineDiag.getBool("tlmTaylorTest");
     bool runTlmApproxTest = onlineDiag.getBool("tlmApproxTest");
     // Online tests
     if (outerIteration_ == 0 && runTlmApproxTest) {
       util::LogbookWriter<std::string> log("TlmTests", "TlmApproxTest");
       this->tlmApproxTest();
     }
     if (outerIteration_ == 0 && runTlmTaylorTest) {
       util::LogbookWriter<std::string> log("TlmTests", "TlmTaylorTest");
       this->tlmTaylorTest();
     }
   }
 }
warmStart()
template<typename MODEL > virtual void oops::Minimizer< MODEL >::warmStart (const eckit::Configuration &) pure virtual
Warm start the minimizer (virtual method)
Implemented in oops::SQRTMinimizer< MODEL >, oops::SaddlePointMinimizer< MODEL >, oops::DRMinimizer< MODEL >, oops::DualMinimizer< MODEL >, oops::LBMinimizer< MODEL >, and oops::PrimalMinimizer< MODEL >.
Member Data Documentation
J_
template<typename MODEL > const CostFct_& oops::Minimizer< MODEL >::J_ private
Handle to the cost function.
Definition at line 117 of file Minimizer.h.
outerIteration_
template<typename MODEL > int oops::Minimizer< MODEL >::outerIteration_ private
Current outer loop index.
Definition at line 118 of file Minimizer.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/Minimizer.h