OOPS Documentation: oops::AdvectorHandler< MODEL > Class Template Reference
oops::AdvectorHandler< MODEL > Class Template Reference
Advector handler class.
#include <AdvectorHandler.h>
Public Member Functions
AdvectorHandler (const eckit::Configuration &config)
void mult (const Increment4D_ &dxi, Increment4D_ &dxo) const
void mult_ad (const Increment4D_ &dxi, Increment4D_ &dxo) const
Public Member Functions inherited from oops::PostBase< State< MODEL > >
PostBase ()
Constructors.
PostBase (const util::Duration &freq)
PostBase (const eckit::Configuration &conf)
PostBase (const util::DateTime &start, const eckit::Configuration &conf)
PostBase (const util::DateTime &start, const util::DateTime &finish, const util::Duration &freq=util::Duration(0))
virtual ~PostBase ()
Destructor.
void initialize (const State< MODEL > &xx, const util::DateTime &end, const util::Duration &tstep)
Wraps doInitialize method; doProcessing is called if requested.
void initialize (State< MODEL > &xx, const util::DateTime &end, const util::Duration &tstep)
void process (const State< MODEL > &xx)
Wraps doProcessing method; doProcessing is is called when requested.
void process (State< MODEL > &xx)
void finalize (const State< MODEL > &xx)
Wraps doFinalize method.
virtual void doProcessing (State< MODEL > &fld)
virtual void doInitialize (State< MODEL > &fld, const util::DateTime &t, const util::Duration &d)
Static Public Member Functions
static void setup (std::shared_ptr< AdvectorHandler > other)
static std::shared_ptr< AdvectorHandler > get ()
Private Types
using State_ = State< MODEL >
using State4D_ = std::vector< std::unique_ptr< State< MODEL > > >
using Increment4D_ = Increment4D< MODEL >
using Advector_ = Advector< MODEL >
using Ensemble_ = Ensemble< MODEL >
using EnsemblePtr_ = std::shared_ptr< Ensemble< MODEL > >
using EnsemblesCollection_ = EnsemblesCollection< MODEL >
Private Member Functions
void doInitialize (const State_ &, const util::DateTime &, const util::Duration &) override
Actual initialization.
void doProcessing (const State_ &) override
Actual processing.
void doFinalize (const State_ &) override
Actual finalization.
void inv_mult_ensemble () const
Private Attributes
const eckit::LocalConfiguration config_
std::vector< util::DateTime > time_
std::vector< std::unique_ptr< Advector_ > > advector_
std::vector< std::unique_ptr< Advector_ > > advector_ad_
std::vector< std::unique_ptr< Advector_ > > advector_inv_
std::unique_ptr< eckit::LocalConfiguration > param_adv_
State4D_ xx_
Static Private Attributes
static std::shared_ptr< AdvectorHandler< MODEL > > singleton_
Detailed Description
template<typename MODEL>
class oops::AdvectorHandler< MODEL >
Advector handler class.
Definition at line 45 of file AdvectorHandler.h.
Member Typedef Documentation
Advector_
template<typename MODEL > using oops::AdvectorHandler< MODEL >::Advector_ = Advector<MODEL> private
Definition at line 49 of file AdvectorHandler.h.
Ensemble_
template<typename MODEL > using oops::AdvectorHandler< MODEL >::Ensemble_ = Ensemble<MODEL> private
Definition at line 50 of file AdvectorHandler.h.
EnsemblePtr_
template<typename MODEL > using oops::AdvectorHandler< MODEL >::EnsemblePtr_ = std::shared_ptr<Ensemble<MODEL> > private
Definition at line 51 of file AdvectorHandler.h.
EnsemblesCollection_
template<typename MODEL > using oops::AdvectorHandler< MODEL >::EnsemblesCollection_ = EnsemblesCollection<MODEL> private
Definition at line 52 of file AdvectorHandler.h.
Increment4D_
template<typename MODEL > using oops::AdvectorHandler< MODEL >::Increment4D_ = Increment4D<MODEL> private
Definition at line 48 of file AdvectorHandler.h.
State4D_
template<typename MODEL > using oops::AdvectorHandler< MODEL >::State4D_ = std::vector<std::unique_ptr<State<MODEL> > > private
Definition at line 47 of file AdvectorHandler.h.
State_
template<typename MODEL > using oops::AdvectorHandler< MODEL >::State_ = State<MODEL> private
Definition at line 46 of file AdvectorHandler.h.
Constructor & Destructor Documentation
AdvectorHandler()
template<typename MODEL > oops::AdvectorHandler< MODEL >::AdvectorHandler (const eckit::Configuration & config)
Definition at line 93 of file AdvectorHandler.h.
                                                                          :
     PostBase<State_>(config), config_(config) {
   param_adv_.reset(new eckit::LocalConfiguration(config_, "fields_to_be_interpolated"));
 }
References oops::AdvectorHandler< MODEL >::config_, and oops::AdvectorHandler< MODEL >::param_adv_.
Member Function Documentation
doFinalize()
template<typename MODEL > void oops::AdvectorHandler< MODEL >::doFinalize (const State_ &) override private virtual
Actual finalization.
Reimplemented from oops::PostBase< State< MODEL > >.
Definition at line 148 of file AdvectorHandler.h.
{
   for (unsigned k = 1; k < xx_.size(); ++k) {
     time_.push_back(xx_[k]->validTime());
     advector_.emplace_back(
         new Advector_(*(xx_[k]), config_, false));
     advector_inv_.emplace_back(
         new Advector_(*(xx_[k]), config_, false));
     advector_ad_.emplace_back(
         new Advector_(*(xx_[k]), config_, true));
     advector_[k - 1]->set_wind(xx_);
     advector_inv_[k - 1]->set_wind_inv(xx_);
     *advector_ad_[k - 1] = *advector_[k - 1];
   }
   xx_.clear();
   inv_mult_ensemble();
 }
doInitialize()
template<typename MODEL > void oops::AdvectorHandler< MODEL >::doInitialize (const State_ & , const util::DateTime & , const util::Duration &) override private virtual
Actual initialization.
Reimplemented from oops::PostBase< State< MODEL > >.
Definition at line 132 of file AdvectorHandler.h.
{
   advector_.clear();
   advector_ad_.clear();
   advector_inv_.clear();
 }
doProcessing()
template<typename MODEL > void oops::AdvectorHandler< MODEL >::doProcessing (const State_ &) override private virtual
Actual processing.
Reimplemented from oops::PostBase< State< MODEL > >.
Definition at line 141 of file AdvectorHandler.h.
{
   Log::info() << "AdvectorHandler: State registered at " << xx.validTime() << std::endl;
   xx_.emplace_back(new State_(xx));
 }
References oops::State< MODEL >::validTime().
get()
template<typename MODEL > static std::shared_ptr<AdvectorHandler > oops::AdvectorHandler< MODEL >::get () inline static
Definition at line 61 of file AdvectorHandler.h.
{
     return singleton_;
   }
References oops::AdvectorHandler< MODEL >::singleton_.
inv_mult_ensemble()
template<typename MODEL > void oops::AdvectorHandler< MODEL >::inv_mult_ensemble private
Definition at line 116 of file AdvectorHandler.h.
{
   for (unsigned k = 0; k < advector_inv_.size(); ++k) {
     if (EnsemblesCollection_::getInstance().has(time_[k])) {
       Log::info()
           << "AdvectorHandler inv_mult_ensemble() called for time = "
           << time_[k] << std::endl;
       EnsemblePtr_ ens = EnsemblesCollection_::getInstance()[time_[k]];
       for (unsigned l = 0; l < ens->size(); ++l) {
         advector_inv_[k]->advect((*ens)[l], *param_adv_, (*ens)[l]);
       }
     }
   }
 }
mult()
template<typename MODEL > void oops::AdvectorHandler< MODEL >::mult (const Increment4D_ & dxi, Increment4D_ & dxo) const
Definition at line 100 of file AdvectorHandler.h.
{
   for (unsigned k = 0; k < advector_.size(); ++k) {
     advector_[k]->advect(dxi[k + 1], *param_adv_, dxo[k + 1]);
   }
 }
mult_ad()
template<typename MODEL > void oops::AdvectorHandler< MODEL >::mult_ad (const Increment4D_ & dxi, Increment4D_ & dxo) const
Definition at line 108 of file AdvectorHandler.h.
{
   for (unsigned k = 0; k < advector_ad_.size(); ++k) {
     advector_ad_[k]->advect(dxi[k + 1], *param_adv_, dxo[k + 1]);
   }
 }
setup()
template<typename MODEL > static void oops::AdvectorHandler< MODEL >::setup (std::shared_ptr< AdvectorHandler< MODEL > > other) inline static
Definition at line 58 of file AdvectorHandler.h.
{
     singleton_ = other;
   }
References oops::AdvectorHandler< MODEL >::singleton_.
Referenced by oops::ModelSpaceCovariance4DBase< MODEL >::ModelSpaceCovariance4DBase(), and oops::ModelSpaceCovariance4DBase< MODEL >::~ModelSpaceCovariance4DBase().
Member Data Documentation
advector_
template<typename MODEL > std::vector<std::unique_ptr<Advector_> > oops::AdvectorHandler< MODEL >::advector_ private
Definition at line 71 of file AdvectorHandler.h.
advector_ad_
template<typename MODEL > std::vector<std::unique_ptr<Advector_> > oops::AdvectorHandler< MODEL >::advector_ad_ private
Definition at line 72 of file AdvectorHandler.h.
advector_inv_
template<typename MODEL > std::vector<std::unique_ptr<Advector_> > oops::AdvectorHandler< MODEL >::advector_inv_ private
Definition at line 73 of file AdvectorHandler.h.
config_
template<typename MODEL > const eckit::LocalConfiguration oops::AdvectorHandler< MODEL >::config_ private
Definition at line 69 of file AdvectorHandler.h.
Referenced by oops::AdvectorHandler< MODEL >::AdvectorHandler().
param_adv_
template<typename MODEL > std::unique_ptr<eckit::LocalConfiguration> oops::AdvectorHandler< MODEL >::param_adv_ private
Definition at line 74 of file AdvectorHandler.h.
Referenced by oops::AdvectorHandler< MODEL >::AdvectorHandler().
singleton_
template<typename MODEL > std::shared_ptr< AdvectorHandler< MODEL > > oops::AdvectorHandler< MODEL >::singleton_ static private
Definition at line 77 of file AdvectorHandler.h.
Referenced by oops::AdvectorHandler< MODEL >::get(), and oops::AdvectorHandler< MODEL >::setup().
time_
template<typename MODEL > std::vector<util::DateTime> oops::AdvectorHandler< MODEL >::time_ private
Definition at line 70 of file AdvectorHandler.h.
xx_
template<typename MODEL > State4D_ oops::AdvectorHandler< MODEL >::xx_ private
Definition at line 75 of file AdvectorHandler.h.
The documentation for this class was generated from the following file:
src/oops/base/AdvectorHandler.h