OOPS Documentation: oops::RPLanczosMinimizer< MODEL > Class Template Reference
oops::RPLanczosMinimizer< MODEL > Class Template Reference
RLanczos Minimizer.
#include <RPLanczosMinimizer.h>
Public Member Functions
const std::string classname () const override
RPLanczosMinimizer (const eckit::Configuration &, const CostFct_ &J)
~RPLanczosMinimizer ()
Public Member Functions inherited from oops::DualMinimizer< MODEL >
DualMinimizer (const CostFct_ &J)
~DualMinimizer ()
void checkpoint (eckit::LocalConfiguration &) const
Checkpoint the minimizer (virtual method)
void restart (const eckit::Configuration &)
Restart the minimizer (virtual method)
void warmStart (const eckit::Configuration &)
Warm start the minimizer (virtual method)
Public Member Functions inherited from oops::Minimizer< MODEL >
Minimizer (const CostFct_ &J)
Construct a minimizer.
virtual ~Minimizer ()
Destroy a minimizer.
ControlIncrement< MODEL > * minimize (const eckit::Configuration &)
Orchestrate the minimization of a quadratic cost function.
Private Types
using CostFct_ = CostFunction< MODEL >
using Dual_ = DualVector< MODEL >
using HBHt_ = HBHtMatrix< MODEL >
using Rinv_ = RinvMatrix< MODEL >
Private Member Functions
double solve (Dual_ &, double &, Dual_ &, const HBHt_ &, const Rinv_ &, const int &, const double &, Dual_ &, const double &) override
Detailed Description
template<typename MODEL>
class oops::RPLanczosMinimizer< MODEL >
RLanczos Minimizer.
Augmented Restricted Lanczos method. It is the Lanczos version of RPCG.
This solver is based on the algorithm from Gurol, PhD Manuscript,
It performs minimization in the observation space.
It solves the linear system \((I + R^{-1}HBH^T) lambda = H^T R^{-1}d \) with \(HBH^T \) inner-product in the augmented observation space.
Note that the traditional \(B\)-preconditioning in model space corresponds to \(I\) for this algorithm.
A second-level preconditioner, \(G \), must be symmetric and positive definite with respect to \(HBH^T \) inner-product. Possible preconditioning is detailed in S. Gurol, PhD Manuscript, 2013.
On entry:
vv = starting point, \(v_0 \).
vvp = starting point augmented part, \(vp_0 \)
rr = right hand side.
aa = \(H (xb - xk) \)
sigma = \((xb - xk)^T B^{-1} (xb - xk)\).
HBHt = \(HBH^T \).
Rinv = \(R^{-1} \).
G = preconditioner \(G \).
On exit, vv and vvp will contain the solution \(lambda = [vv; vp] \)
The return value is the achieved reduction in preconditioned residual norm.
Iteration will stop if the maximum iteration limit "maxiter" is reached or if the preconditioned residual norm reduces by a factor of "tolerance".
Definition at line 70 of file RPLanczosMinimizer.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::RPLanczosMinimizer< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 71 of file RPLanczosMinimizer.h.
Dual_
template<typename MODEL > using oops::RPLanczosMinimizer< MODEL >::Dual_ = DualVector<MODEL> private
Definition at line 72 of file RPLanczosMinimizer.h.
HBHt_
template<typename MODEL > using oops::RPLanczosMinimizer< MODEL >::HBHt_ = HBHtMatrix<MODEL> private
Definition at line 73 of file RPLanczosMinimizer.h.
Rinv_
template<typename MODEL > using oops::RPLanczosMinimizer< MODEL >::Rinv_ = RinvMatrix<MODEL> private
Definition at line 74 of file RPLanczosMinimizer.h.
Constructor & Destructor Documentation
RPLanczosMinimizer()
template<typename MODEL > oops::RPLanczosMinimizer< MODEL >::RPLanczosMinimizer (const eckit::Configuration & , const CostFct_ & J) inline
Definition at line 78 of file RPLanczosMinimizer.h.
       : DualMinimizer<MODEL>(J) {}
~RPLanczosMinimizer()
template<typename MODEL > oops::RPLanczosMinimizer< MODEL >::~RPLanczosMinimizer () inline
Definition at line 80 of file RPLanczosMinimizer.h.
 {}
Member Function Documentation
classname()
template<typename MODEL > const std::string oops::RPLanczosMinimizer< MODEL >::classname () const inline override virtual
Implements oops::DualMinimizer< MODEL >.
Definition at line 77 of file RPLanczosMinimizer.h.
 { return "RPLanczosMinimizer"; }
solve()
template<typename MODEL > double oops::RPLanczosMinimizer< MODEL >::solve (Dual_ & vv, double & vvp, Dual_ & rr, const HBHt_ & HBHt, const Rinv_ & Rinv, const int & maxiter, const double & tolerance, Dual_ & dy, const double & sigma) override private virtual
Implements oops::DualMinimizer< MODEL >.
Definition at line 90 of file RPLanczosMinimizer.h.
{
   IdentityMatrix<Dual_> precond;
   Dual_ zz(vv);
   Dual_ ww(vv);
   Dual_ tt(vv);
   Dual_ vold(vv);
   Dual_ v(vv);
   // augmented part of the vectors
   double rrp = 1.0;
   double zzp;
   double wwp;
   double ttp = 0.0;
   double voldp = 0.0;
   double vp = 1.0;
   std::vector<Dual_> vVEC;  // required for re-orthogonalization
   std::vector<Dual_> tVEC;  // required for re-orthogonalization
   std::vector<Dual_> zVEC;  // required for solution
   std::vector<double> vpVEC;
   std::vector<double> tpVEC;
   std::vector<double> zpVEC;
   std::vector<double> alphas;
   std::vector<double> betas;
   std::vector<double> y;
   std::vector<double> d;
   // zzaug = Gaug  rraug
   precond.multiply(rr, zz);
   zzp = rrp;
   // ttaug = HBHtaug zzaug
   HBHt.multiply(zz, tt);
   tt.axpy(zzp, dy);
   ttp = dot_product(dy, zz) + sigma * zzp;
   double normReduction = 1.0;
   double beta0 = sqrt(dot_product(rr, tt) + rrp * ttp);
   double beta = 0.0;
   vold.zero();
   v = rr;
   vp = rrp;
   v *= 1 / beta0;
   vp *= 1 / beta0;
   tt *= 1 / beta0;
   zz *= 1 / beta0;
   ttp *= 1 / beta0;
   zzp *= 1 / beta0;
   vVEC.clear();
   zVEC.clear();
   tVEC.clear();
   vpVEC.clear();
   zpVEC.clear();
   tpVEC.clear();
   betas.clear();
   alphas.clear();
   vVEC.push_back(v);
   zVEC.push_back(zz);
   tVEC.push_back(tt);
   vpVEC.push_back(vp);
   zpVEC.push_back(zzp);
   tpVEC.push_back(ttp);
   int jiter;
   Log::info() << std::endl;
   for (jiter = 0; jiter < maxiter; ++jiter) {
     Log::info() << "RPLanczos Starting Iteration " << jiter + 1 << std::endl;
     // ww = (RinvHBHt + I) zz - beta * vold
     Rinv.multiply(tt, ww);
     ww += zz;
     wwp = zzp;
     ww.axpy(-beta, vold);
     wwp -= beta * voldp;
     double alpha = dot_product(tt, ww) + ttp * wwp;
     ww.axpy(-alpha, v);  // w = w - alpha * v
     wwp -= alpha * vp;
     // Re-orthogonalization
     for (int iiter = 0; iiter < jiter; ++iiter) {
       double proj = dot_product(ww, tVEC[iiter]) + wwp * tpVEC[iiter];
       ww.axpy(-proj, vVEC[iiter]);
       wwp -= proj * vpVEC[iiter];
     }
     // wwaug = Gaug  zzaug
     precond.multiply(ww, zz);
     zzp = wwp;
     // ttaug = HBHtaug zzaug
     HBHt.multiply(zz, tt);
     tt.axpy(zzp, dy);
     ttp = dot_product(dy, zz) + sigma * zzp;
     beta = sqrt(dot_product(tt, ww) + ttp * wwp);
     vold = v;
     voldp = vp;
     v = ww;
     vp = wwp;
     v *= 1 / beta;
     vp *= 1 / beta;
     tt *= 1 / beta;
     zz *= 1 / beta;
     ttp *= 1 / beta;
     zzp *= 1 / beta;
     vVEC.push_back(v);
     zVEC.push_back(zz);
     tVEC.push_back(tt);
     vpVEC.push_back(vp);
     zpVEC.push_back(zzp);
     tpVEC.push_back(ttp);
     alphas.push_back(alpha);
     y.clear();
     if (jiter == 0) {
       y.push_back(beta0 / alpha);
     } else {
       // Solve the tridiagonal system T_jiter y_jiter = beta0 * e_1
       d.clear();
       for (int iiter = 0; iiter <= jiter; ++iiter) {
         d.push_back(beta0 * (dot_product(tVEC[0], vVEC[iiter]) +
                              tpVEC[0] * vpVEC[iiter]));
       }
       TriDiagSolve(alphas, betas, d, y);
     }
     // Gradient norm in precond metric --> sqrt(r't) --> beta * y(jiter)
     double rznorm = beta * std::abs(y[jiter]);
     normReduction = rznorm / beta0;
     betas.push_back(beta);
     Log::info() << "RPLanczos end of iteration " << jiter + 1
                 << ". Norm reduction= " << util::full_precision(normReduction)
                 << std::endl
                 << std::endl;
     if (normReduction < tolerance) {
       Log::info() << "RPLanczos: Achieved required reduction in residual norm."
                   << std::endl;
       break;
     }
   }
   // Calculate the solution (xh = Binv x)
   for (int iiter = 0; iiter < jiter; ++iiter) {
     vv.axpy(y[iiter], zVEC[iiter]);
     vvp += y[iiter] * zpVEC[iiter];
   }
   Log::info() << "RPLanczos: end" << std::endl;
   return normReduction;
 }
References oops::DualVector< MODEL >::axpy(), dot_product(), util::full_precision(), oops::IdentityMatrix< VECTOR >::multiply(), oops::RinvMatrix< MODEL >::multiply(), oops::HBHtMatrix< MODEL >::multiply(), oops::TriDiagSolve(), and oops::DualVector< MODEL >::zero().
The documentation for this class was generated from the following file:
src/oops/assimilation/RPLanczosMinimizer.h