OOPS Documentation: oops::GeoVaLs< MODEL > Class Template Reference
oops::GeoVaLs< MODEL > Class Template Reference
Wrapper for geophysical values at observation locations.
#include <ObservationSpaces.h>
Public Member Functions
GeoVaLs (const ObsSpace_ &, const Variables_ &, const Increment_ &, const util::DateTime &, const util::DateTime &)
Constructor (takes an Increment)
GeoVaLs (const ObsSpace_ &, const Variables_ &, const State_ &, const util::DateTime &, const util::DateTime &)
Constructor (takes a State)
~GeoVaLs ()
Destructor.
const GeoVaLs_ & geovals () const
Return model-specific geovals.
GeoVaLs_ & geovals ()
Return constant model-specific geovals.
void zero ()
\(g = 0 \)
void random ()
\(g = rand(size(g)) \)
double dot_product_with (const GeoVaLs &) const
\(<g,g>=g^T g \)
void read (const eckit::Configuration &)
Read geovals.
void write (const eckit::Configuration &) const
Write geovals.
Static Public Member Functions
static const std::string classname ()
Private Types
using GeoVaLs_ = typename MODEL::GeoVaLs
using Increment_ = Increment< MODEL >
using ObsSpace_ = ObservationSpace< MODEL >
using State_ = State< MODEL >
using Variables_ = Variables< MODEL >
Private Member Functions
void print (std::ostream &) const
Private Attributes
std::unique_ptr< GeoVaLs_ > gvals_
Detailed Description
template<typename MODEL>
class oops::GeoVaLs< MODEL >
Wrapper for geophysical values at observation locations.
Consider the \(J_o \) term of the cost function:
\(J_o = \sum ({\cal G}_k (x_k) - y_k)^T R_k^{-1} ({\cal G}_k (x_k) - y_k) \)
-> \({\cal G}_k x_k = {\cal H}_k {\cal I}_k {\cal M}_{k:0} x_0 \); -> \({\cal I}_k \) is the interpolation operator, such that \(g_k = {\cal I}_k x_k \);
In practice the model fields are interpolated to the observation locations during the trajectory and subsequently the observation operator is called:
\begin{eqnarray*} \sum {\cal G}_k (x_k) &=& {\cal H} \sum {\cal I}_k {\cal M}_{k:0} x_0 \\ &=& {\cal H} \sum {\cal I}_k x_k \\ &=& {\cal H} \sum g_k \\ &=& {\cal H} g \end{eqnarray*}
GeoVaLs contains interpolated model values at observation locations \(g \).
Definition at line 36 of file ObservationSpaces.h.
Member Typedef Documentation
GeoVaLs_
template<typename MODEL > using oops::GeoVaLs< MODEL >::GeoVaLs_ = typename MODEL::GeoVaLs private
Definition at line 67 of file GeoVaLs.h.
Increment_
template<typename MODEL > using oops::GeoVaLs< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 68 of file GeoVaLs.h.
ObsSpace_
template<typename MODEL > using oops::GeoVaLs< MODEL >::ObsSpace_ = ObservationSpace<MODEL> private
Definition at line 69 of file GeoVaLs.h.
State_
template<typename MODEL > using oops::GeoVaLs< MODEL >::State_ = State<MODEL> private
Definition at line 70 of file GeoVaLs.h.
Variables_
template<typename MODEL > using oops::GeoVaLs< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 71 of file GeoVaLs.h.
Constructor & Destructor Documentation
GeoVaLs() [1/2]
template<typename MODEL > oops::GeoVaLs< MODEL >::GeoVaLs (const ObsSpace_ & os, const Variables_ & var, const Increment_ & dx, const util::DateTime & t1, const util::DateTime & t2)
Constructor (takes an Increment)
Definition at line 111 of file GeoVaLs.h.
     : gvals_() {
   Log::trace() << "GeoVaLs<MODEL>::GeoVaLs starting" << std::endl;
   util::Timer timer(classname(), "GeoVaLs");
   gvals_.reset(new GeoVaLs_(os.observationspace(), var.variables(),
                             dx.increment(), t1, t2));
   Log::trace() << "GeoVaLs<MODEL>::GeoVaLs done" << std::endl;
 }
References oops::GeoVaLs< MODEL >::classname(), oops::GeoVaLs< MODEL >::gvals_, oops::Increment< MODEL >::increment(), oops::ObservationSpace< MODEL >::observationspace(), and oops::Variables< MODEL >::variables().
GeoVaLs() [2/2]
template<typename MODEL > oops::GeoVaLs< MODEL >::GeoVaLs (const ObsSpace_ & os, const Variables_ & var, const State_ & xx, const util::DateTime & t1, const util::DateTime & t2)
Constructor (takes a State)
Definition at line 125 of file GeoVaLs.h.
     : gvals_() {
   Log::trace() << "GeoVaLs<MODEL>::GeoVaLs starting" << std::endl;
   util::Timer timer(classname(), "GeoVaLs");
   gvals_.reset(
       new GeoVaLs_(os.observationspace(), var.variables(), xx.state(), t1, t2));
   Log::trace() << "GeoVaLs<MODEL>::GeoVaLs done" << std::endl;
 }
References oops::GeoVaLs< MODEL >::classname(), oops::GeoVaLs< MODEL >::gvals_, oops::ObservationSpace< MODEL >::observationspace(), oops::State< MODEL >::state(), and oops::Variables< MODEL >::variables().
~GeoVaLs()
template<typename MODEL > oops::GeoVaLs< MODEL >::~GeoVaLs
Destructor.
Definition at line 139 of file GeoVaLs.h.
{
   Log::trace() << "GeoVaLs<MODEL>::~GeoVaLs starting" << std::endl;
   util::Timer timer(classname(), "~GeoVaLs");
   gvals_.reset();
   Log::trace() << "GeoVaLs<MODEL>::~GeoVaLs done" << std::endl;
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::GeoVaLs< MODEL >::classname () inline static
Definition at line 74 of file GeoVaLs.h.
 { return "oops::GeoVaLs"; }
Referenced by oops::GeoVaLs< MODEL >::GeoVaLs().
dot_product_with()
template<typename MODEL > double oops::GeoVaLs< MODEL >::dot_product_with (const GeoVaLs< MODEL > & other) const
\(<g,g>=g^T g \)
Definition at line 149 of file GeoVaLs.h.
{
   Log::trace() << "GeoVaLs<MODEL>::dot_product_with starting" << std::endl;
   util::Timer timer(classname(), "dot_product_with");
   double zz = gvals_->dot_product_with(other.gvals_);
   Log::trace() << "GeoVaLs<MODEL>::dot_product_with done" << std::endl;
   return zz;
 }
References oops::GeoVaLs< MODEL >::gvals_.
geovals() [1/2]
template<typename MODEL > GeoVaLs_& oops::GeoVaLs< MODEL >::geovals () inline
Return constant model-specific geovals.
Definition at line 89 of file GeoVaLs.h.
 { return *gvals_; }
References oops::GeoVaLs< MODEL >::gvals_.
geovals() [2/2]
template<typename MODEL > const GeoVaLs_& oops::GeoVaLs< MODEL >::geovals () const inline
Return model-specific geovals.
Definition at line 87 of file GeoVaLs.h.
 { return *gvals_; }
References oops::GeoVaLs< MODEL >::gvals_.
Referenced by oops::State< MODEL >::interpolate(), oops::Increment< MODEL >::interpolateAD(), oops::Increment< MODEL >::interpolateTL(), oops::ObsOperator< MODEL >::obsBiasEquiv(), oops::LinearObsOperator< MODEL >::obsBiasEquivAD(), oops::LinearObsOperator< MODEL >::obsBiasEquivTL(), oops::ObsOperator< MODEL >::obsEquiv(), oops::LinearObsOperator< MODEL >::obsEquivAD(), oops::LinearObsOperator< MODEL >::obsEquivTL(), oops::ObservationSpace< MODEL >::screenObservations(), and oops::LinearObsOperator< MODEL >::setTrajectory().
print()
template<typename MODEL > void oops::GeoVaLs< MODEL >::print (std::ostream & os) const private
Definition at line 200 of file GeoVaLs.h.
{
   Log::trace() << "GeoVaLs<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   os << *gvals_;
   Log::trace() << "GeoVaLs<MODEL>::print done" << std::endl;
 }
random()
template<typename MODEL > void oops::GeoVaLs< MODEL >::random
\(g = rand(size(g)) \)
Definition at line 170 of file GeoVaLs.h.
{
   Log::trace() << "GeoVaLs<MODEL>::random starting" << std::endl;
   util::Timer timer(classname(), "random");
   gvals_->random();
   Log::trace() << "GeoVaLs<MODEL>::random done" << std::endl;
 }
read()
template<typename MODEL > void oops::GeoVaLs< MODEL >::read (const eckit::Configuration & conf)
Read geovals.
Definition at line 180 of file GeoVaLs.h.
{
   Log::trace() << "GeoVaLs<MODEL>::read starting" << std::endl;
   util::Timer timer(classname(), "read");
   gvals_->read(conf);
   Log::trace() << "GeoVaLs<MODEL>::read done" << std::endl;
 }
write()
template<typename MODEL > void oops::GeoVaLs< MODEL >::write (const eckit::Configuration & conf) const
Write geovals.
Definition at line 190 of file GeoVaLs.h.
{
   Log::trace() << "GeoVaLs<MODEL>::write starting" << std::endl;
   util::Timer timer(classname(), "write");
   gvals_->write(conf);
   Log::trace() << "GeoVaLs<MODEL>::write done" << std::endl;
 }
zero()
template<typename MODEL > void oops::GeoVaLs< MODEL >::zero
\(g = 0 \)
Definition at line 160 of file GeoVaLs.h.
{
   Log::trace() << "GeoVaLs<MODEL>::zero starting" << std::endl;
   util::Timer timer(classname(), "zero");
   gvals_->zero();
   Log::trace() << "GeoVaLs<MODEL>::zero done" << std::endl;
 }
Member Data Documentation
gvals_
template<typename MODEL > std::unique_ptr<GeoVaLs_> oops::GeoVaLs< MODEL >::gvals_ private
Definition at line 105 of file GeoVaLs.h.
Referenced by oops::GeoVaLs< MODEL >::dot_product_with(), oops::GeoVaLs< MODEL >::GeoVaLs(), and oops::GeoVaLs< MODEL >::geovals().
The documentation for this class was generated from the following files:
src/oops/base/ObservationSpaces.h
src/oops/interface/GeoVaLs.h