OOPS Documentation: oops::PostProcessorFactory< FLDS > Class Template Reference
oops::PostProcessorFactory< FLDS > Class Template Reference abstract
The PostProcessorFactory defines and manages a factory to manage PostProcessor for objects.
#include <PostProcessorFactory.h>
Public Member Functions
virtual ~PostProcessorFactory ()
Static Public Member Functions
static PostBase< FLDS > * create (const eckit::Configuration &)
Protected Member Functions
PostProcessorFactory (const std::string &)
Private Member Functions
virtual PostBase< FLDS > * make (const eckit::Configuration &)=0
Static Private Member Functions
static std::map< std::string, PostProcessorFactory< FLDS > * > & getMakers ()
Detailed Description
template<typename FLDS>
class oops::PostProcessorFactory< FLDS >
The PostProcessorFactory defines and manages a factory to manage PostProcessor for objects.
Definition at line 38 of file PostProcessorFactory.h.
Constructor & Destructor Documentation
~PostProcessorFactory()
template<typename FLDS > virtual oops::PostProcessorFactory< FLDS >::~PostProcessorFactory () inline virtual
Definition at line 41 of file PostProcessorFactory.h.
 { getMakers().clear(); }
References oops::PostProcessorFactory< FLDS >::getMakers().
PostProcessorFactory()
template<typename FLDS > oops::PostProcessorFactory< FLDS >::PostProcessorFactory (const std::string & name) explicit protected
Definition at line 72 of file PostProcessorFactory.h.
{
   if (getMakers().find(name) != getMakers().end()) {
     Log::error() << name << " already registered in post processor factory."
                  << std::endl;
     ABORT("Element already registered in PostProcessorFactory.");
   }
   getMakers()[name] = this;
 }
References ABORT.
Member Function Documentation
create()
template<typename FLDS > PostBase< FLDS > * oops::PostProcessorFactory< FLDS >::create (const eckit::Configuration & config) static
Definition at line 84 of file PostProcessorFactory.h.
{
   std::string id = config.getString("post_processor_type");
   Log::trace() << "Post processor Type=" << id << std::endl;
   typename std::map<std::string, PostProcessorFactory<FLDS> *>::iterator j =
       getMakers().find(id);
   if (j == getMakers().end()) {
     Log::error() << id << " does not exist in post processor factory."
                  << std::endl;
     ABORT("Element does not exist in PostProcessorFactory.");
   }
   return (*j).second->make(config);
 }
References ABORT.
Referenced by oops::Forecast< MODEL >::execute().
getMakers()
template<typename FLDS > static std::map<std::string, PostProcessorFactory<FLDS> *>& oops::PostProcessorFactory< FLDS >::getMakers () inline static private
Definition at line 48 of file PostProcessorFactory.h.
{
     static std::map<std::string, PostProcessorFactory<FLDS> *> makers_;
     return makers_;
   }
Referenced by oops::PostProcessorFactory< FLDS >::~PostProcessorFactory().
make()
template<typename FLDS > virtual PostBase<FLDS>* oops::PostProcessorFactory< FLDS >::make (const eckit::Configuration &) private pure virtual
Implemented in oops::PostProcessorMaker< MODEL, FLDS, POST_PROC >.
The documentation for this class was generated from the following file:
src/oops/base/PostProcessorFactory.h