OOPS Documentation: oops::CostFunction< MODEL > Class Template Reference
oops::CostFunction< MODEL > Class Template Reference abstract
Abstract base class for a cost function.
#include <CostFunction.h>
Public Member Functions
CostFunction (const eckit::Configuration &, const Geometry_ &, const Model_ &)
Construct a cost function.
virtual ~CostFunction ()
Destroy a cost function.
virtual double evaluate (const CtrlVar_ &, const eckit::Configuration &config=eckit::LocalConfiguration(), PostProcessor< State_ > post=PostProcessor< State_ >()) const
Evaluate the non-linear cost function.
virtual double linearize (const CtrlVar_ &, const eckit::Configuration &, PostProcessor< State_ > post=PostProcessor< State_ >())
Linearise the cost function: set up the quadratic cost function.
virtual void runTL (CtrlInc_ &, PostProcessorTL< Increment_ > &, PostProcessor< Increment_ > post=PostProcessor< Increment_ >(), const bool idModel=false) const =0
Run the tangent linear model (virtual method)
virtual void runAD (CtrlInc_ &, PostProcessorAD< Increment_ > &, PostProcessor< Increment_ > post=PostProcessor< Increment_ >(), const bool idModel=false) const =0
Run the adjoint model (virtual method)
virtual void zeroAD (CtrlInc_ &) const =0
Nullify the increment prior to running the adjoint model (virtual method)
virtual void runNL (CtrlVar_ &, PostProcessor< State_ > &) const =0
Run the non-linear model (virtual method)
virtual void runNL (CtrlVar_ &xx, const Model_ &, PostProcessor< State_ > &pp)
Run the non-linear model (virtual method)
void addIncrement (CtrlVar_ &, const CtrlInc_ &, PostProcessor< Increment_ > post=PostProcessor< Increment_ >()) const
Add increment to the first guess.
void resetLinearization ()
Rest the quadratic cost function.
void computeGradientFG (CtrlInc_ &) const
Compute the cost function gradient at first guess (without Jb)
double computeGradientFG (const CtrlVec_ &, CtrlInc_ &) const
Compute the cost function gradient at first guess (without Jb)
void checkpoint (eckit::LocalConfiguration &) const
Checkpoint.
void restart (const eckit::Configuration &)
Restart.
const JbTotal_ & jb () const
Access \(J_b\).
const CostBase_ & jterm (const unsigned ii) const
Access terms of the cost function other than \(J_b\).
unsigned nterms () const
Return the numer of other cost function terms \(J_o, J_c, ..\).
virtual const double & getCostJb () const
Get the Jb cost function value.
virtual const double & getCostJoJc () const
Get the JoJc cost function value.
Static Public Member Functions
static const std::string classname ()
Protected Member Functions
void setupTerms (const eckit::Configuration &)
Set up terms of the cost function \(J_b, J_q, J_o, J_c, ..\).
const Model_ & getModel () const
Access the non-linear model.
const LinearModel_ & getTLM (const unsigned isub=0) const
Access the linear model.
void recentreBackground (const eckit::Configuration &)
Re-centre the background.
CostBase_ & getJterm (const unsigned ii) const
Non const access to JTerms for linearize() method in concrete cost-functions.
JbTotal_ & getJb () const
Non const access to Jb for linearize() method in concrete cost-functions
std::vector< std::unique_ptr< LinearModel_ > > & getTLMs ()
Non const access to TL Model for linearize() method in concrete cost-functions
Private Types
using CostBase_ = CostTermBase< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using CtrlVar_ = ControlVariable< MODEL >
using CtrlVec_ = ControlVector< MODEL >
using Geometry_ = Geometry< MODEL >
using Increment_ = Increment< MODEL >
using JbTotal_ = CostJbTotal< MODEL >
using JqTerm_ = JqTerm< MODEL >
using LinearModel_ = LinearModel< MODEL >
using Model_ = Model< MODEL >
using State_ = State< MODEL >
using Variables_ = Variables< MODEL >
Private Member Functions
virtual void addIncr (CtrlVar_ &, const CtrlInc_ &, PostProcessor< Increment_ > &) const =0
Virtual method to add the increment to the state.
virtual CostJbState< MODEL > * newJb (const eckit::Configuration &, const Geometry_ &, const CtrlVar_ &) const =0
Create the \(J_b, J_q\) term of the cost function (virtual method)
virtual CostJo< MODEL > * newJo (const eckit::Configuration &) const =0
Create the \(J_o\) term of the cost function (virtual method)
virtual CostTermBase< MODEL > * newJc (const eckit::Configuration &, const Geometry_ &) const =0
Create other terms of the cost function \(J_c, ..\) (virtual method)
const bool & reduceMemoryFootprint () const
Reduce memory footprit (for multi-executable mode only)
Private Attributes
const Geometry_ & resol_
Outer-loop geometry.
const Model_ & model_
Non-linear model.
std::unique_ptr< CtrlVar_ > xb_
Terms of the cost function.
std::unique_ptr< JbTotal_ > jb_
\(J_b, J_q\) term of the cost function
std::vector< std::unique_ptr< CostBase_ > > jterms_
\(J_o, J_c, ..\) terms of the cost function
std::vector< std::unique_ptr< LinearModel_ > > tlm_
Linear model (includes trajectory)
bool lreduceMemoryFootprint_
Reduce memory footprint (only in multi-executable mode)
double costJb_
double costJoJc_
Detailed Description
template<typename MODEL>
class oops::CostFunction< MODEL >
Abstract base class for a cost function.
CostFunction defines and manages the computation of all the terms of the variational data assimilation cost function. It is a base class for cost functions specific to 3D-Var, 4D-Var, 4DEns-Var and weak constraint 4D-Var implemented by oops::CostFct3DVar<MODEL>, oops::CostFct4DVar<MODEL>, oops::CostFct4DEnsVar<MODEL> and oops::CostFctWeak<MODEL>, respectively.
Concrete cost functions are produced by CostFactory.
IFS: 4D-Var (CostFct4DVar) is set up by default.
Definition at line 71 of file CostFunction.h.
Member Typedef Documentation
CostBase_
template<typename MODEL > using oops::CostFunction< MODEL >::CostBase_ = CostTermBase<MODEL> private
Definition at line 72 of file CostFunction.h.
CtrlInc_
template<typename MODEL > using oops::CostFunction< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 73 of file CostFunction.h.
CtrlVar_
template<typename MODEL > using oops::CostFunction< MODEL >::CtrlVar_ = ControlVariable<MODEL> private
Definition at line 74 of file CostFunction.h.
CtrlVec_
template<typename MODEL > using oops::CostFunction< MODEL >::CtrlVec_ = ControlVector<MODEL> private
Definition at line 75 of file CostFunction.h.
Geometry_
template<typename MODEL > using oops::CostFunction< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 76 of file CostFunction.h.
Increment_
template<typename MODEL > using oops::CostFunction< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 77 of file CostFunction.h.
JbTotal_
template<typename MODEL > using oops::CostFunction< MODEL >::JbTotal_ = CostJbTotal<MODEL> private
Definition at line 78 of file CostFunction.h.
JqTerm_
template<typename MODEL > using oops::CostFunction< MODEL >::JqTerm_ = JqTerm<MODEL> private
Definition at line 79 of file CostFunction.h.
LinearModel_
template<typename MODEL > using oops::CostFunction< MODEL >::LinearModel_ = LinearModel<MODEL> private
Definition at line 80 of file CostFunction.h.
Model_
template<typename MODEL > using oops::CostFunction< MODEL >::Model_ = Model<MODEL> private
Definition at line 81 of file CostFunction.h.
State_
template<typename MODEL > using oops::CostFunction< MODEL >::State_ = State<MODEL> private
Definition at line 82 of file CostFunction.h.
Variables_
template<typename MODEL > using oops::CostFunction< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 83 of file CostFunction.h.
Constructor & Destructor Documentation
CostFunction()
template<typename MODEL > oops::CostFunction< MODEL >::CostFunction (const eckit::Configuration & config, const Geometry_ & resol, const Model_ & model)
Construct a cost function.
The constructor sets the geomery and model objects
Definition at line 299 of file CostFunction.h.
     : resol_(resol),
       model_(model),
       xb_(),
       jb_(),
       jterms_(),
       tlm_(),
       lreduceMemoryFootprint_(false),
       costJb_(0.0),
       costJoJc_(0.0) {
   Log::trace() << "CostFunction:created" << std::endl;
 }
~CostFunction()
template<typename MODEL > virtual oops::CostFunction< MODEL >::~CostFunction () inline virtual
Destroy a cost function.
Definition at line 92 of file CostFunction.h.
 {}
Member Function Documentation
addIncr()
template<typename MODEL > virtual void oops::CostFunction< MODEL >::addIncr (CtrlVar_ & , const CtrlInc_ & , PostProcessor< Increment_ > &) const private pure virtual
Virtual method to add the increment to the state.
Implemented in oops::CostFct4DVarMFTemplate< MODEL >, oops::CostFct4DVarTrajHR< MODEL >, oops::CostFct4DEnVar< MODEL >, oops::CostFct4DEnsVar< MODEL >, oops::CostFctWeak< MODEL >, oops::CostFct4DVar< MODEL >, and oops::CostFct3DVar< MODEL >.
addIncrement()
template<typename MODEL > void oops::CostFunction< MODEL >::addIncrement (CtrlVar_ & xx, const CtrlInc_ & dx, PostProcessor< Increment_ > post = PostProcessor<Increment_>()) const
Add increment to the first guess.
This methods adds an increment to the first guess
Add the auxiliary observation space components (e.g. VarBC, TOVSCV, ..)
Add the auxiliary model space components (e.g. model bias)
Add the increment to the state
Definition at line 604 of file CostFunction.h.
{
   Log::trace() << "CostFunction::addIncrement start" << std::endl;
   Log::info() << "CostFunction::addIncrement: First guess:" << xx << std::endl;
   Log::info() << "CostFunction::addIncrement: Increment:" << dx << std::endl;
   xx.obsVar() += dx.obsVar();
   xx.modVar() += dx.modVar();
   this->addIncr(xx, dx, post);
   Log::test() << "CostFunction::addIncrement: Analysis norm: " << xx.norm()
               << std::endl;
   Log::trace() << "CostFunction::addIncrement done" << std::endl;
 }
References oops::ControlVariable< MODEL >::modVar(), oops::ControlIncrement< MODEL >::modVar(), oops::ControlVariable< MODEL >::norm(), oops::ControlVariable< MODEL >::obsVar(), and oops::ControlIncrement< MODEL >::obsVar().
checkpoint()
template<typename MODEL > void oops::CostFunction< MODEL >::checkpoint (eckit::LocalConfiguration & conf) const
Checkpoint.
This method is checkpointing the terms of the cost function required for restarting
Call the checkpoint method of \(J_o, J_c, ..\)
Definition at line 669 of file CostFunction.h.
{
   for (auto &jterm : jterms_) {
     jterm->checkpoint(conf);
   }
 }
classname()
template<typename MODEL > static const std::string oops::CostFunction< MODEL >::classname () inline static
Definition at line 86 of file CostFunction.h.
 { return "oops::CostFunction"; }
computeGradientFG() [1/2]
template<typename MODEL > double oops::CostFunction< MODEL >::computeGradientFG (const CtrlVec_ & dv0, CtrlInc_ & grad) const
Compute the cost function gradient at first guess (without Jb)
This method computes and returns the first guess gradient in control space: \(H^T R^{-1} [d + H (dx_{fg} - U dv_0) ]\)
Compute \(dx_{fg} - U dv_0\)
Compute \(H (dx_{fg} - U dv_0)\)
Compute \(R^{-1} [d + H (dx_{fg} - U dv_0) ]\)
Run ADJ: \(H^T R^{-1} [d + H (dx_{fg} - U dv_0) ] \)
Return: \(1/2 [d + H (dx_{fg} - U dv_0) ]^T R^{-1} [d + H (dx_{fg} - U dv_0) ] \)
Definition at line 547 of file CostFunction.h.
{
   CtrlInc_ dxfg(this->jb().getFirstGuessIncrement(), true);
   CtrlInc_ dx(this->jb().getFirstGuessIncrement(), false);
   this->jb().multiplyBsqrt(dv0, dx);
   dxfg -= dx;
   PostProcessorTL<Increment_> costtl;
   for (unsigned jj = 0; jj < this->nterms(); ++jj) {
     costtl.enrollProcessor(this->jterm(jj).setupTL(dxfg));
   }
   CtrlInc_ mdxfg(dxfg);
   this->runTL(mdxfg, costtl);
   PostProcessorAD<Increment_> costad;
   this->zeroAD(grad);
   DualVector<MODEL> yy;
   DualVector<MODEL> ww;
   DualVector<MODEL> zz;
   // \f$ d + H (dx_{fg} - U dv_0) \f$
   for (unsigned jj = 0; jj < this->nterms(); ++jj) {
     yy.append(this->jterm(jj).newDepartures());
     ww.append(costtl.releaseOutputFromTL(jj));
   }
   yy += ww;
   // \f$ R^{-1} [d + H (dx_{fg} - U dv_0) ] \f$
   for (unsigned jj = 0; jj < this->nterms(); ++jj) {
     zz.append(this->jterm(jj).multiplyCoInv(*yy.getv(jj)));
   }
   for (unsigned jj = 0; jj < this->nterms(); ++jj) {
     costad.enrollProcessor(this->jterm(jj).setupAD(zz.getv(jj), grad));
   }
   this->runAD(grad, costad);
   double costJ0JoJc = 0.5 * dot_product(yy, zz);
   return costJ0JoJc;
 }
References oops::DualVector< MODEL >::append(), dot_product(), oops::PostProcessorAD< INCR >::enrollProcessor(), oops::PostProcessorTL< INCR >::enrollProcessor(), oops::DualVector< MODEL >::getv(), and oops::PostProcessorTL< INCR >::releaseOutputFromTL().
computeGradientFG() [2/2]
template<typename MODEL > void oops::CostFunction< MODEL >::computeGradientFG (CtrlInc_ & grad) const
Compute the cost function gradient at first guess (without Jb)
This method computes and returns the first guess gradient in model space: \(H^T R^{-1} d\)
Set up post-processors for computation of the first guess gradient for \(J_o\) and \(J_c\)
Run the adjoint model with attached post-processors to compute the gradient
Definition at line 524 of file CostFunction.h.
{
   PostProcessor<Increment_> pp;
   PostProcessorAD<Increment_> costad;
   this->zeroAD(grad);
   for (auto &jterm : jterms_) {
     std::shared_ptr<const GeneralizedDepartures> tmp(jterm->newGradientFG());
     costad.enrollProcessor(jterm->setupAD(tmp, grad));
   }
   this->runAD(grad, costad, pp);
 }
References oops::PostProcessorAD< INCR >::enrollProcessor().
evaluate()
template<typename MODEL > double oops::CostFunction< MODEL >::evaluate (const CtrlVar_ & fguess, const eckit::Configuration & config = eckit::LocalConfiguration(), PostProcessor< State_ > post = PostProcessor<State_>()) const virtual
Evaluate the non-linear cost function.
This method evaluates the final non-linear cost function and returns the cost function value
Setup terms of cost function: \(J_b, J_q, J_o, J_c\)
Run the non-linear model
Compute the non-linear cost function value
Reimplemented in oops::CostFct4DVarMFTemplate< MODEL >, and oops::CostFct4DVarTrajHR< MODEL >.
Definition at line 353 of file CostFunction.h.
{
   util::LogbookWriter<bool> log("LastNonlinearIntegration", true);
   Log::trace() << "CostFunction::evaluate start" << std::endl;
   PostProcessor<State_> pp(post);
   JqTerm_ *jq = jb_->initialize(fguess);
   pp.enrollProcessor(jq);
   for (auto &jterm : jterms_) {
     pp.enrollProcessor(jterm->initialize(fguess, config));
   }
   CtrlVar_ mfguess(fguess);
   this->runNL(mfguess, pp);
   double zzz = 0.0;
   for (auto &jterm : jterms_) {
     zzz += jterm->finalize(config);
   }
   zzz += jb_->finalize(jq, config);
   Log::test() << "CostFunction: Nonlinear J = " << zzz << std::endl;
   Log::trace() << "CostFunction::evaluate done" << std::endl;
   return zzz;
 }
References oops::PostProcessor< FLDS >::enrollProcessor().
Referenced by oops::CostFct4DVarTrajHR< MODEL >::evaluate(), and oops::CostFct4DVarMFTemplate< MODEL >::evaluate().
getCostJb()
template<typename MODEL > virtual const double& oops::CostFunction< MODEL >::getCostJb () const inline virtual
Get the Jb cost function value.
Reimplemented in oops::CostFct4DVarMFTemplate< MODEL >, and oops::CostFct4DVarTrajHR< MODEL >.
Definition at line 156 of file CostFunction.h.
 { return costJb_; }
References oops::CostFunction< MODEL >::costJb_.
getCostJoJc()
template<typename MODEL > virtual const double& oops::CostFunction< MODEL >::getCostJoJc () const inline virtual
Get the JoJc cost function value.
Reimplemented in oops::CostFct4DVarMFTemplate< MODEL >, and oops::CostFct4DVarTrajHR< MODEL >.
Definition at line 159 of file CostFunction.h.
 { return costJoJc_; }
References oops::CostFunction< MODEL >::costJoJc_.
getJb()
template<typename MODEL > JbTotal_& oops::CostFunction< MODEL >::getJb () const inline protected
Non const access to Jb for linearize() method in concrete cost-functions
Definition at line 177 of file CostFunction.h.
 {return *jb_;}
References oops::CostFunction< MODEL >::jb_.
getJterm()
template<typename MODEL > CostBase_& oops::CostFunction< MODEL >::getJterm (const unsigned ii) const inline protected
Non const access to JTerms for linearize() method in concrete cost-functions.
Definition at line 174 of file CostFunction.h.
 {return *jterms_[ii];}
References oops::CostFunction< MODEL >::jterms_.
getModel()
template<typename MODEL > const Model_& oops::CostFunction< MODEL >::getModel () const inline protected
Access the non-linear model.
Definition at line 165 of file CostFunction.h.
 { return model_; }
References oops::CostFunction< MODEL >::model_.
getTLM()
template<typename MODEL > const LinearModel_& oops::CostFunction< MODEL >::getTLM (const unsigned isub = 0) const inline protected
Access the linear model.
Definition at line 167 of file CostFunction.h.
{
     return *tlm_[isub];
   }
References oops::CostFunction< MODEL >::tlm_.
getTLMs()
template<typename MODEL > std::vector<std::unique_ptr<LinearModel_> >& oops::CostFunction< MODEL >::getTLMs () inline protected
Non const access to TL Model for linearize() method in concrete cost-functions
Definition at line 180 of file CostFunction.h.
 {return tlm_;}
References oops::CostFunction< MODEL >::tlm_.
jb()
template<typename MODEL > const JbTotal_& oops::CostFunction< MODEL >::jb () const inline
Access \(J_b\).
Definition at line 147 of file CostFunction.h.
 { return *jb_; }
References oops::CostFunction< MODEL >::jb_.
Referenced by oops::BMatrix< MODEL >::multiply(), oops::LBHessianMatrix< MODEL >::multiply(), oops::JbMatrix< MODEL >::multiply(), oops::BMatrix< MODEL >::multiplyB(), oops::BMatrix< MODEL >::multiplyId(), oops::BMatrix< MODEL >::multiplySqrt(), and oops::BMatrix< MODEL >::multiplySqrtTrans().
jterm()
template<typename MODEL > const CostBase_& oops::CostFunction< MODEL >::jterm (const unsigned ii) const inline
Access terms of the cost function other than \(J_b\).
Definition at line 150 of file CostFunction.h.
 { return *jterms_[ii]; }
References oops::CostFunction< MODEL >::jterms_.
Referenced by oops::RinvMatrix< MODEL >::multiply(), oops::HtMatrix< MODEL >::multiply(), oops::HMatrix< MODEL >::multiply(), oops::LBHessianMatrix< MODEL >::multiply(), and oops::RMatrix< MODEL >::multiplyInv().
linearize()
template<typename MODEL > double oops::CostFunction< MODEL >::linearize (const CtrlVar_ & fguess, const eckit::Configuration & innerConf, PostProcessor< State_ > post = PostProcessor<State_>()) virtual
Linearise the cost function: set up the quadratic cost function.
This method sets up the quadratic cost function by linearizing the non-linear cost function.
Jo, Jc, .. (jterms_) terms of the cost function call their 'initialize' methods which return post-processors. These are subsequently attached to the non-linear trajectory and do their post-processing prior/during/after the trajectory evaluation; once the non-linear trajectory is completed, the terms of the cost function call their 'finalize' method which makes further use of the output acquired by the post-processors during the trajectory.
E.g. the 'initialize' method of the Jo term of the cost functions returns an Observer post-processor. Its task is to compute model equivalents at observation locations. Once the trajectory evaluation is completed, the 'finalize' method is called to compute departures, perform screening if requested, set up the observation error covariance and print diagnostics.
Along with with the post-processors set up by the terms of the cost function, the TrajectorySaver post-processor is set up. Its role is to record the interpolated high resolution states at the linear model time steps during the non-linear trajectory run. These interpolated high resolution states are subsequently used to force the linearisation trajectory.
Prior to the computation of the linearisation trajectory by the TrajecotrySaver, the Jb, Jo, Jc, .. terms of the cost function call their 'initializeTraj' methods which return post-processors. These are subsequently enrolled into the TrajecotrySaver and attached to the linearisation trajectory computation. Once the linearisation trajectory computation is completed, the terms of the cost function call the 'finalizeTraj' method which makes further use of the output acquired by the post-processors during the computation of the linearisation trajectory.
E.g. the 'initializeTraj' method of the Jo term of the cost function sets up the linear observation operator and returns an Observer post-processor. Its task is to compute the linearisation for the linear observation operator. Once the linearisation trajectory computation is completed, the 'finailzeTraj' method is called to compute the departures and print diagnostics.
Enable the option to reduce the memory footprint in case late 4d start is enabled to make more memory available prior to writing out 4V/AN states
Read the inner loop configuration
Set up the inner loop geomerty
Set up the TrajectorySaver post-processor
Set up \(J_o, J_c\) terms of cost function
Run the non-linear model with attached post-processors
Calculate the non-linear cost function value
Compute the linearisation trajectory
The TrajecotrySaver was attached to the non-linear model trajecotry in order to record the interpolated high resolution states at each linear model time step. Terms of the cost function (Jb, Jq, Jo, Jc) set up post processors which perform operations required to set up the quadratic cost function. These post-processors are enrolled into the TrajectorySaver. They do their post processing during the forced (with store interpolated high resolution fields) linearisation trajectory computation.
Such a design was required for IFS as the linearisation of the observation operator needs to be performed with the screened ODB (CCMA rather than ECMA).
Finalize setting up the terms of the quadratic cost function
Print the cost function value
Reset xb
Reimplemented in oops::CostFct4DVarMFTemplate< MODEL >, and oops::CostFct4DVarTrajHR< MODEL >.
Definition at line 388 of file CostFunction.h.
{
   if (innerConf.has("late4d")) {
     lreduceMemoryFootprint_ = true;
     Log::info() << "CostFunction::linearize reduced memory footprint enabled"
                 << std::endl;
   }
   const eckit::LocalConfiguration resConf(innerConf, "resolution");
   const eckit::LocalConfiguration tlmConf(innerConf, "linearmodel");
   eckit::LocalConfiguration diagnostic;
   if (innerConf.has("diagnostics")) {
     diagnostic = eckit::LocalConfiguration(innerConf, "diagnostics");
   }
   const Geometry_ lowres(resConf);
   PostProcessor<State_> pp(post);
   std::shared_ptr<TrajectorySaver<MODEL> > trajectorySaver(
       new TrajectorySaver<MODEL>(fguess.state()[0], fguess.modVar(), lowres,
                                  tlm_, tlmConf));
   pp.enrollProcessor(trajectorySaver);
   for (auto &jterm : jterms_) {
     pp.enrollProcessor(jterm->initialize(fguess, innerConf));
   }
   std::unique_ptr<CtrlVar_> mfguess(new CtrlVar_(fguess));
   this->runNL(*mfguess, pp);
   mfguess.reset();
   costJoJc_ = 0.0;
   for (auto &jterm : jterms_) {
     costJoJc_ += jterm->finalize(innerConf);
   }
   // JbJq trajectory
   std::shared_ptr<JqTerm_> jq(jb_->initializeTraj(fguess, lowres, innerConf));
   trajectorySaver->enrollProcessor(jq);
   // JoJc trajectory
   for (auto &jterm : jterms_) {
     trajectorySaver->enrollProcessor(
         jterm->initializeTraj(fguess, lowres, innerConf));
   }
   trajectorySaver->recordTrajectory();
   costJb_ = jb_->finalizeTraj(jq.get(), innerConf);
   double costJoJcTraj = 0.0;
   for (auto &jterm : jterms_) {
     costJoJcTraj += jterm->finalizeTraj(diagnostic);
   }
   double costJ = costJb_ + costJoJc_;
   double costJtraj = costJb_ + costJoJcTraj;
   Log::test() << "CostFunction: Nonlinear J = " << costJ << std::endl;
   Log::info() << "CostFunction: Nonlinear J (traj) = " << costJtraj
               << std::endl;
   if (reduceMemoryFootprint()) xb_.reset();
   return costJ;
 }
References oops::PostProcessor< FLDS >::enrollProcessor(), oops::ControlVariable< MODEL >::modVar(), and oops::ControlVariable< MODEL >::state().
newJb()
template<typename MODEL > virtual CostJbState<MODEL>* oops::CostFunction< MODEL >::newJb (const eckit::Configuration & , const Geometry_ & , const CtrlVar_ &) const private pure virtual
Create the \(J_b, J_q\) term of the cost function (virtual method)
Implemented in oops::CostFct4DVarMFTemplate< MODEL >, oops::CostFct4DEnVar< MODEL >, oops::CostFct4DEnsVar< MODEL >, oops::CostFctWeak< MODEL >, oops::CostFct4DVarHyb4D< MODEL >, oops::CostFct4DVar< MODEL >, and oops::CostFct3DVar< MODEL >.
newJc()
template<typename MODEL > virtual CostTermBase<MODEL>* oops::CostFunction< MODEL >::newJc (const eckit::Configuration & , const Geometry_ &) const private pure virtual
Create other terms of the cost function \(J_c, ..\) (virtual method)
Implemented in oops::CostFct4DVarMFTemplate< MODEL >, oops::CostFct4DEnVar< MODEL >, oops::CostFct4DEnsVar< MODEL >, oops::CostFctWeak< MODEL >, oops::CostFct4DVar< MODEL >, and oops::CostFct3DVar< MODEL >.
newJo()
template<typename MODEL > virtual CostJo<MODEL>* oops::CostFunction< MODEL >::newJo (const eckit::Configuration &) const private pure virtual
Create the \(J_o\) term of the cost function (virtual method)
Implemented in oops::CostFct4DVarMFTemplate< MODEL >, oops::CostFct4DEnVar< MODEL >, oops::CostFct4DEnsVar< MODEL >, oops::CostFctWeak< MODEL >, oops::CostFct4DVar< MODEL >, and oops::CostFct3DVar< MODEL >.
nterms()
template<typename MODEL > unsigned oops::CostFunction< MODEL >::nterms () const inline
Return the numer of other cost function terms \(J_o, J_c, ..\).
Definition at line 153 of file CostFunction.h.
 { return jterms_.size(); }
References oops::CostFunction< MODEL >::jterms_.
Referenced by oops::RinvMatrix< MODEL >::multiply(), oops::HtMatrix< MODEL >::multiply(), oops::HMatrix< MODEL >::multiply(), oops::LBHessianMatrix< MODEL >::multiply(), and oops::RMatrix< MODEL >::multiplyInv().
recentreBackground()
template<typename MODEL > void oops::CostFunction< MODEL >::recentreBackground (const eckit::Configuration & conf) protected
Re-centre the background.
This method is re-centres the background
Setup re-centring increment
Re-centre the background
Write out re-centred background (optional)
Definition at line 626 of file CostFunction.h.
{
   Log::trace() << "CostFunction::recentreBackground start" << std::endl;
   Log::info() << "CostFunction::recentreBackground enabled" << std::endl;
   Geometry_ bkgRecResol(conf.getSubConfiguration("resolution"));
   Variables_ bkgRecVars(conf);
   util::DateTime bkgRecValidTime(xb_->state()[0].validTime());
   Increment_ bkgRecIncr(bkgRecResol, bkgRecVars, bkgRecValidTime);
   bkgRecIncr.read(conf.getSubConfiguration("increment"));
   xb_->state()[0] += bkgRecIncr;
   if (conf.has("writeOutRecentredBackground")) {
     xb_->state().write(conf.getSubConfiguration("writeOutRecentredBackground"));
   }
   Log::trace() << "CostFunction::recentreBackground done" << std::endl;
 }
References oops::Increment< MODEL >::read(), and oops::Increment< MODEL >::write().
reduceMemoryFootprint()
template<typename MODEL > const bool& oops::CostFunction< MODEL >::reduceMemoryFootprint () const inline private
Reduce memory footprit (for multi-executable mode only)
Definition at line 198 of file CostFunction.h.
 { return lreduceMemoryFootprint_; }
References oops::CostFunction< MODEL >::lreduceMemoryFootprint_.
resetLinearization()
template<typename MODEL > void oops::CostFunction< MODEL >::resetLinearization
Rest the quadratic cost function.
This method resets the linearization of the non-linear cost function Reset Jb
Reset Jo, Jc
Reset linearization trajectory
Definition at line 653 of file CostFunction.h.
{
   if (reduceMemoryFootprint()) jb_.reset();
   for (auto &jterm : jterms_) {
     jterm->resetLinearization();
     if (reduceMemoryFootprint()) jterm.reset();
   }
   tlm_.clear();
 }
restart()
template<typename MODEL > void oops::CostFunction< MODEL >::restart (const eckit::Configuration & conf)
Restart.
This method is restarting the terms of the cost function
Call the restart method of \(J_o, J_c , .. \)
Definition at line 682 of file CostFunction.h.
{
   for (auto &jterm : jterms_) {
     jterm->restart(conf);
   }
 }
runAD()
template<typename MODEL > virtual void oops::CostFunction< MODEL >::runAD (CtrlInc_ & , PostProcessorAD< Increment_ > & , PostProcessor< Increment_ > post = PostProcessor< Increment_ >(), const bool idModel = false) const pure virtual
Run the adjoint model (virtual method)
Implemented in oops::CostFct4DVarMFTemplate< MODEL >, oops::CostFct4DEnVar< MODEL >, oops::CostFct4DEnsVar< MODEL >, oops::CostFct4DVarHyb4D< MODEL >, oops::CostFct4DVar< MODEL >, oops::CostFctWeak< MODEL >, and oops::CostFct3DVar< MODEL >.
Referenced by oops::HtMatrix< MODEL >::multiply(), oops::MtMatrix< MODEL >::multiply(), and oops::LBHessianMatrix< MODEL >::multiply().
runNL() [1/2]
template<typename MODEL > virtual void oops::CostFunction< MODEL >::runNL (CtrlVar_ & , PostProcessor< State_ > &) const pure virtual
Run the non-linear model (virtual method)
Implemented in oops::CostFct4DVarMFTemplate< MODEL >, oops::CostFct4DEnVar< MODEL >, oops::CostFct4DEnsVar< MODEL >, oops::CostFctWeak< MODEL >, oops::CostFct4DVar< MODEL >, and oops::CostFct3DVar< MODEL >.
runNL() [2/2]
template<typename MODEL > virtual void oops::CostFunction< MODEL >::runNL (CtrlVar_ & xx, const Model_ & , PostProcessor< State_ > & pp) inline virtual
Run the non-linear model (virtual method)
Reimplemented in oops::CostFct4DVarMFTemplate< MODEL >.
Definition at line 122 of file CostFunction.h.
{
     ASSERT(false);
   }
runTL()
template<typename MODEL > virtual void oops::CostFunction< MODEL >::runTL (CtrlInc_ & , PostProcessorTL< Increment_ > & , PostProcessor< Increment_ > post = PostProcessor< Increment_ >(), const bool idModel = false) const pure virtual
Run the tangent linear model (virtual method)
Implemented in oops::CostFct4DVarMFTemplate< MODEL >, oops::CostFct4DEnVar< MODEL >, oops::CostFct4DEnsVar< MODEL >, oops::CostFct4DVar< MODEL >, oops::CostFct4DVarHyb4D< MODEL >, oops::CostFctWeak< MODEL >, and oops::CostFct3DVar< MODEL >.
Referenced by oops::MMatrix< MODEL >::multiply(), oops::HMatrix< MODEL >::multiply(), and oops::LBHessianMatrix< MODEL >::multiply().
setupTerms()
template<typename MODEL > void oops::CostFunction< MODEL >::setupTerms (const eckit::Configuration & config) protected
Set up terms of the cost function \(J_b, J_q, J_o, J_c, ..\).
This method sets up the terms of the non-linear cost function
\(J_o\)
\(J_b\)
Set the background in the \(J_o\) term MC: \(J_b\) requires the \(J_o\) term to setup the observation space first in order to initialize observation space components
Other constraints: \(J_c, ..\)
Definition at line 317 of file CostFunction.h.
{
   Log::trace() << "CostFunction::setupTerms starting" << std::endl;
   eckit::LocalConfiguration joConf(config, "Jo");
   CostJo<MODEL> *jo = this->newJo(joConf);
   jterms_.emplace_back(jo);
   Log::trace() << "CostFunction: setupTerms Jo added" << std::endl;
   const eckit::LocalConfiguration jbConf(config, "Jb");
   xb_.reset(new CtrlVar_(config, resol_, model_, jo->obspaces()));
   if (jbConf.has("RecentreBackground"))
     this->recentreBackground(jbConf.getSubConfiguration("RecentreBackground"));
   jb_.reset(new JbTotal_(*xb_, this->newJb(jbConf, resol_, *xb_), config,
                          resol_, jo->obspaces()));
   Log::trace() << "CostFunction::setupTerms Jb added" << std::endl;
   jo->setBackground(*xb_);
   std::vector<eckit::LocalConfiguration> jcs;
   config.get("Jc", jcs);
   for (size_t jj = 0; jj < jcs.size(); ++jj) {
     CostTermBase<MODEL> *jc = this->newJc(jcs[jj], resol_);
     jterms_.emplace_back(jc);
   }
   Log::trace() << "CostFunction::setupTerms done" << std::endl;
 }
References oops::CostJo< MODEL >::obspaces(), and oops::CostJo< MODEL >::setBackground().
Referenced by oops::CostFct3DVar< MODEL >::CostFct3DVar(), oops::CostFct4DEnsVar< MODEL >::CostFct4DEnsVar(), oops::CostFct4DEnVar< MODEL >::CostFct4DEnVar(), oops::CostFct4DVar< MODEL >::CostFct4DVar(), oops::CostFct4DVarHyb4D< MODEL >::CostFct4DVarHyb4D(), oops::CostFct4DVarMF< MODEL >::CostFct4DVarMF(), oops::CostFct4DVarTrajHR< MODEL >::CostFct4DVarTrajHR(), and oops::CostFctWeak< MODEL >::CostFctWeak().
zeroAD()
template<typename MODEL > virtual void oops::CostFunction< MODEL >::zeroAD (CtrlInc_ &) const pure virtual
Nullify the increment prior to running the adjoint model (virtual method)
Implemented in oops::CostFct4DVarMFTemplate< MODEL >, oops::CostFct4DEnVar< MODEL >, oops::CostFct4DEnsVar< MODEL >, oops::CostFct4DVarHyb4D< MODEL >, oops::CostFct4DVar< MODEL >, oops::CostFctWeak< MODEL >, and oops::CostFct3DVar< MODEL >.
Referenced by oops::LBHessianMatrix< MODEL >::multiply().
Member Data Documentation
costJb_
template<typename MODEL > double oops::CostFunction< MODEL >::costJb_ private
Definition at line 216 of file CostFunction.h.
Referenced by oops::CostFunction< MODEL >::getCostJb().
costJoJc_
template<typename MODEL > double oops::CostFunction< MODEL >::costJoJc_ private
Definition at line 217 of file CostFunction.h.
Referenced by oops::CostFunction< MODEL >::getCostJoJc().
jb_
template<typename MODEL > std::unique_ptr<JbTotal_> oops::CostFunction< MODEL >::jb_ private
\(J_b, J_q\) term of the cost function
Definition at line 206 of file CostFunction.h.
Referenced by oops::CostFunction< MODEL >::getJb(), and oops::CostFunction< MODEL >::jb().
jterms_
template<typename MODEL > std::vector<std::unique_ptr<CostBase_> > oops::CostFunction< MODEL >::jterms_ private
\(J_o, J_c, ..\) terms of the cost function
Definition at line 208 of file CostFunction.h.
Referenced by oops::CostFunction< MODEL >::getJterm(), oops::CostFunction< MODEL >::jterm(), and oops::CostFunction< MODEL >::nterms().
lreduceMemoryFootprint_
template<typename MODEL > bool oops::CostFunction< MODEL >::lreduceMemoryFootprint_ private
Reduce memory footprint (only in multi-executable mode)
Definition at line 214 of file CostFunction.h.
Referenced by oops::CostFunction< MODEL >::reduceMemoryFootprint().
model_
template<typename MODEL > const Model_& oops::CostFunction< MODEL >::model_ private
Non-linear model.
Definition at line 202 of file CostFunction.h.
Referenced by oops::CostFunction< MODEL >::getModel().
resol_
template<typename MODEL > const Geometry_& oops::CostFunction< MODEL >::resol_ private
Outer-loop geometry.
Definition at line 201 of file CostFunction.h.
tlm_
template<typename MODEL > std::vector<std::unique_ptr<LinearModel_> > oops::CostFunction< MODEL >::tlm_ private
Linear model (includes trajectory)
Tangent-linear model
Definition at line 211 of file CostFunction.h.
Referenced by oops::CostFunction< MODEL >::getTLM(), and oops::CostFunction< MODEL >::getTLMs().
xb_
template<typename MODEL > std::unique_ptr<CtrlVar_> oops::CostFunction< MODEL >::xb_ private
Terms of the cost function.
Background control variable
Definition at line 205 of file CostFunction.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/CostFunction.h