OOPS Documentation: oops::HtMatrix< MODEL > Class Template Reference
oops::HtMatrix< MODEL > Class Template Reference
The \(H^T \) matrix.
#include <HtMatrix.h>
Public Member Functions
HtMatrix (const CostFct_ &j)
void multiply (const DualVector< MODEL > &dy, ControlIncrement< MODEL > &dx, const bool idModel=false) const
Private Types
using CostFct_ = CostFunction< MODEL >
using Increment_ = Increment< MODEL >
Private Attributes
CostFct_ const & j_
Detailed Description
template<typename MODEL>
class oops::HtMatrix< MODEL >
The \(H^T \) matrix.
The solvers represent matrices as objects that implement a "multiply" method. This class defines objects that apply a generalized \(H^T \) matrix which includes \(H^T \) itself and the equivalent operators for the other terms of the cost function.
Definition at line 34 of file HtMatrix.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::HtMatrix< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 35 of file HtMatrix.h.
Increment_
template<typename MODEL > using oops::HtMatrix< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 36 of file HtMatrix.h.
Constructor & Destructor Documentation
HtMatrix()
template<typename MODEL > oops::HtMatrix< MODEL >::HtMatrix (const CostFct_ & j) inline explicit
Definition at line 39 of file HtMatrix.h.
 : j_(j) {}
Member Function Documentation
multiply()
template<typename MODEL > void oops::HtMatrix< MODEL >::multiply (const DualVector< MODEL > & dy, ControlIncrement< MODEL > & dx, const bool idModel = false) const inline
Definition at line 41 of file HtMatrix.h.
{
     PostProcessor<Increment_> post;
     PostProcessorAD<Increment_> cost;
     // Don't zero out dx here
     for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
       cost.enrollProcessor(j_.jterm(jj).setupAD(dy.getv(jj), dx));
     }
     j_.runAD(dx, cost, post, idModel);
   }
References oops::PostProcessorAD< INCR >::enrollProcessor(), oops::DualVector< MODEL >::getv(), oops::HtMatrix< MODEL >::j_, oops::CostFunction< MODEL >::jterm(), oops::CostFunction< MODEL >::nterms(), oops::CostFunction< MODEL >::runAD(), and oops::CostTermBase< MODEL >::setupAD().
Referenced by oops::Minimizer< MODEL >::adjObsTest(), and oops::DualMinimizer< MODEL >::doMinimize().
Member Data Documentation
j_
template<typename MODEL > CostFct_ const& oops::HtMatrix< MODEL >::j_ private
Definition at line 53 of file HtMatrix.h.
Referenced by oops::HtMatrix< MODEL >::multiply().
The documentation for this class was generated from the following file:
src/oops/assimilation/HtMatrix.h