OOPS Documentation: oops::CostJbTotal< MODEL > Class Template Reference
oops::CostJbTotal< MODEL > Class Template Reference
Jb component of the cost function.
#include <ControlIncrement.h>
Public Member Functions
CostJbTotal (const CtrlVar_ &, JbState_ *, const eckit::Configuration &, const Geometry_ &, const ObsSpaces_ &odb)
Construct \(J_b\).
~CostJbTotal ()
Destructor.
JqTerm_ * initialize (const CtrlVar_ &) const
Various set ups prior to the integration of the model.
JqTerm_ * initializeTraj (const CtrlVar_ &, const Geometry_ &, const eckit::Configuration &)
Various set ups prior to the linearisation trajectory computation.
double finalize (JqTerm_ *, const eckit::Configuration &) const
Various computations after the integration of the model.
double finalizeTraj (JqTerm_ *, const eckit::Configuration &)
Various computations after the linearisation trajectory computation.
JqTermTL_ * initializeTL () const
Initialize JqTermTL (weak constraint only) before starting the TL run.
void finalizeTL (JqTermTL_ *, const CtrlInc_ &, CtrlInc_ &) const
Model error computation (weak constraint only) after the TL run.
JqTermAD_ * initializeAD (CtrlInc_ &, const CtrlInc_ &) const
Initialize JqTermAD (weak constraint only) before starting the AD run.
void finalizeAD (JqTermAD_ *) const
Perform clean ups after the AD run.
void multiplyB (const CtrlInc_ &, CtrlInc_ &) const
Multiply by the covariance matrix.
void multiplyBinv (const CtrlInc_ &, CtrlInc_ &) const
Multiply by the inverse covariance matrix.
void multiplyBsqrt (const CtrlVec_ &, CtrlInc_ &) const
Multiply by the square root of the covariance matrix.
void multiplyBsqrtTrans (const CtrlInc_ &, CtrlVec_ &) const
Multiply by the transpose of the square root of the covariance matrix.
void randomize (CtrlInc_ &) const
Randomize (using the square root of the covariance matrix)
void addGradientFG (CtrlInc_ &) const
Add Jb gradient at first guess.
void addGradientFG (CtrlInc_ &, CtrlInc_ &) const
void addGradientFG (CtrlVec_ &, CtrlVec_ &) const
const CtrlVar_ & getBackground () const
Return background.
const CtrlInc_ & getFirstGuessIncrement () const
Return first guess increment \(x_0-x_b\).
const Geometry_ & resolution () const
Access (inner loop) geometry.
const JbState_ & jbState () const
Access covariance matrix for the state component of ctrl vec.
const ModelAuxCovar_ & jbModBias () const
const ObsAuxCovars_ & jbObsBias () const
Static Public Member Functions
static const std::string classname ()
Private Types
using State4D_ = State4D< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using CtrlVar_ = ControlVariable< MODEL >
using CtrlVec_ = ControlVector< MODEL >
using JbState_ = CostJbState< MODEL >
using JqTerm_ = JqTerm< MODEL >
using JqTermAD_ = JqTermAD< MODEL >
using JqTermTL_ = JqTermTL< MODEL >
using Geometry_ = Geometry< MODEL >
using ModelAuxCovar_ = ModelAuxCovariance< MODEL >
using ObsAuxCovars_ = ObsAuxCovariances< MODEL >
using ObsSpaces_ = ObservationSpaces< MODEL >
Private Member Functions
double evaluate (const CtrlInc_ &) const
Compute Jb cost function value.
void writeIncrement (const CtrlInc_ &, const eckit::Configuration &) const
Write the increment.
Private Attributes
const CtrlVar_ & xb_
Reference to the background control variable.
std::unique_ptr< JbState_ > jb_
Cov matrix for state component of ctrl vec.
ModelAuxCovar_ jbModBias_
ObsAuxCovars_ jbObsBias_
Cov matrix for auxiliary obs space component of ctrl vec.
const CtrlVar_ * fg_
Pointer to the first guess.
std::unique_ptr< CtrlInc_ > dxFG_
std::unique_ptr< Geometry_ > geom_
Inner loop geometry.
Detailed Description
template<typename MODEL>
class oops::CostJbTotal< MODEL >
Jb component of the cost function.
CostJbTotal encapsulates B matrices corresponding to various components of the control increment/control vector:
Consider applying the matrix vector product:
\[ B dx = \begin{bmatrix} B_{state} & 0 & 0 \\ 0 & B_{modaux} & 0 \\ 0 & 0 & B_{obsaux} \end{bmatrix} \begin{bmatrix} dx_{state} \\ dx_{modaux} \\ dx_{obsaux} \\ \end{bmatrix} \]
CostJbState - \(B_{state} \): abstract base class encapsulating the background covariance matrix corresponding to the state component of the control increment. Concrete classes deriving from it are CostJb3D (3/4D-Var), CostJb4D (4D-Ens-Var), CostJbJq (weak constraint)
ModelAuxCovariance - \(B_{modaux} \): class encapsulating the background covariance matrix of an auxiliary model space component of the control increment (e.g.Q matrix - model bias covariance)
ObsAuxCovariances - \(B_{obsaux} \): class encapsulating background covariance matrices of auxiliary observation space components of the control increment (e.g. VarBC, TOVSCV)
Definition at line 33 of file ControlIncrement.h.
Member Typedef Documentation
CtrlInc_
template<typename MODEL > using oops::CostJbTotal< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 79 of file CostJbTotal.h.
CtrlVar_
template<typename MODEL > using oops::CostJbTotal< MODEL >::CtrlVar_ = ControlVariable<MODEL> private
Definition at line 80 of file CostJbTotal.h.
CtrlVec_
template<typename MODEL > using oops::CostJbTotal< MODEL >::CtrlVec_ = ControlVector<MODEL> private
Definition at line 81 of file CostJbTotal.h.
Geometry_
template<typename MODEL > using oops::CostJbTotal< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 86 of file CostJbTotal.h.
JbState_
template<typename MODEL > using oops::CostJbTotal< MODEL >::JbState_ = CostJbState<MODEL> private
Definition at line 82 of file CostJbTotal.h.
JqTerm_
template<typename MODEL > using oops::CostJbTotal< MODEL >::JqTerm_ = JqTerm<MODEL> private
Definition at line 83 of file CostJbTotal.h.
JqTermAD_
template<typename MODEL > using oops::CostJbTotal< MODEL >::JqTermAD_ = JqTermAD<MODEL> private
Definition at line 84 of file CostJbTotal.h.
JqTermTL_
template<typename MODEL > using oops::CostJbTotal< MODEL >::JqTermTL_ = JqTermTL<MODEL> private
Definition at line 85 of file CostJbTotal.h.
ModelAuxCovar_
template<typename MODEL > using oops::CostJbTotal< MODEL >::ModelAuxCovar_ = ModelAuxCovariance<MODEL> private
Definition at line 87 of file CostJbTotal.h.
ObsAuxCovars_
template<typename MODEL > using oops::CostJbTotal< MODEL >::ObsAuxCovars_ = ObsAuxCovariances<MODEL> private
Definition at line 88 of file CostJbTotal.h.
ObsSpaces_
template<typename MODEL > using oops::CostJbTotal< MODEL >::ObsSpaces_ = ObservationSpaces<MODEL> private
Definition at line 89 of file CostJbTotal.h.
State4D_
template<typename MODEL > using oops::CostJbTotal< MODEL >::State4D_ = State4D<MODEL> private
Definition at line 78 of file CostJbTotal.h.
Constructor & Destructor Documentation
CostJbTotal()
template<typename MODEL > oops::CostJbTotal< MODEL >::CostJbTotal (const CtrlVar_ & xb, JbState_ * jb, const eckit::Configuration & conf, const Geometry_ & resol, const ObsSpaces_ & odb)
Construct \(J_b\).
Set the pointer to the covariance matrix for the state component of the control vector. Construct the covariance matrices for the auxiliary observation and model space components of the control vector.
The covariance matrix for the state component of the control vector is constructed outside by calling the newJb method of one of the cost function classes derived from the abstract base class CostFunction: CostFct3DVar (returns CostJb3D), CostFct4DVar (returns CostJb3D), CostFct4DEnsVar (returns CostJb4D), CostFctWeak (returns CostJbJq).
Definition at line 199 of file CostJbTotal.h.
     : xb_(xb),
       jb_(jb),
       jbModBias_(conf.getSubConfiguration("Jb.ModelBiasCovariance"), resol),
       jbObsBias_(odb, eckit::LocalConfiguration(conf, "Jo")),
       fg_(),
       dxFG_(),
       geom_() {
   Log::trace() << "CostJbTotal contructed." << std::endl;
 }
~CostJbTotal()
template<typename MODEL > oops::CostJbTotal< MODEL >::~CostJbTotal () inline
Destructor.
Definition at line 99 of file CostJbTotal.h.
 {}
Member Function Documentation
addGradientFG() [1/3]
template<typename MODEL > void oops::CostJbTotal< MODEL >::addGradientFG (CtrlInc_ & grad) const
Add Jb gradient at first guess.
Add Jb component of the first gradient. Used for primal formulation.
Definition at line 409 of file CostJbTotal.h.
{
   CtrlInc_ gg(grad, false);
   this->multiplyBinv(*dxFG_, gg);
   grad -= gg;
 }
addGradientFG() [2/3]
template<typename MODEL > void oops::CostJbTotal< MODEL >::addGradientFG (CtrlInc_ & grad, CtrlInc_ & gradJb) const
Add Jb component of the first gradient. Used for B preconditioned formulation.
Definition at line 420 of file CostJbTotal.h.
{
   jb_->addGradient(dxFG_->state(), grad.state(), gradJb.state());
   grad.modVar() -= gradJb.modVar();
   grad.obsVar() -= gradJb.obsVar();
 }
References oops::ControlIncrement< MODEL >::modVar(), oops::ControlIncrement< MODEL >::obsVar(), and oops::ControlIncrement< MODEL >::state().
addGradientFG() [3/3]
template<typename MODEL > void oops::CostJbTotal< MODEL >::addGradientFG (CtrlVec_ & grad, CtrlVec_ & gradJb) const
Add Jb component of the first gradient. Used for square root B preconditioned formulation.
Definition at line 432 of file CostJbTotal.h.
{
   grad.state() -= gradJb.state();
   grad.modVar() -= gradJb.modVar();
   grad.obsVar() -= gradJb.obsVar();
 }
References oops::ControlVector< MODEL >::modVar(), oops::ControlVector< MODEL >::obsVar(), and oops::ControlVector< MODEL >::state().
classname()
template<typename MODEL > static const std::string oops::CostJbTotal< MODEL >::classname () inline static
Definition at line 92 of file CostJbTotal.h.
 { return "oops::CostJbTotal"; }
evaluate()
template<typename MODEL > double oops::CostJbTotal< MODEL >::evaluate (const CtrlInc_ & dx) const private
Compute Jb cost function value.
Definition at line 381 of file CostJbTotal.h.
{
   CtrlInc_ gg(dx, false);
   this->multiplyBinv(dx, gg);
   double zjb = 0.0;
   double zz = 0.5 * dot_product(dx.state(), gg.state());
   Log::info() << "CostJb   : Nonlinear Jb State = " << zz << std::endl;
   zjb += zz;
   zz = 0.5 * dot_product(dx.modVar(), gg.modVar());
   Log::info() << "CostJb   : Nonlinear Jb Model Aux = " << zz << std::endl;
   zjb += zz;
   zz = 0.5 * dot_product(dx.obsVar(), gg.obsVar());
   Log::info() << "CostJb   : Nonlinear Jb Obs Aux = " << zz << std::endl;
   zjb += zz;
   Log::info() << "CostJb   : Nonlinear Jb = " << zjb << std::endl;
   // Get rid of very small values for test
   double ztest = zjb;
   if (zjb >= 0.0 && zjb <= std::numeric_limits<double>::epsilon()) ztest = 0.0;
   Log::test() << "CostJb   : Nonlinear Jb = " << ztest << std::endl;
   return zjb;
 }
References dot_product(), oops::ControlIncrement< MODEL >::modVar(), oops::ControlIncrement< MODEL >::obsVar(), and oops::ControlIncrement< MODEL >::state().
finalize()
template<typename MODEL > double oops::CostJbTotal< MODEL >::finalize (JqTerm_ * jqnl, const eckit::Configuration & conf) const
Various computations after the integration of the model.
This method is called after the non-linear model integration. Its purpose is to compute the increment and evaluate the Jb cost function term value. For weak constraint the model error \(x_i - {\cal M}(x_{i-1}\) is computed. Returns the value of the Jb component of the cost function.
1.1 Compute x_0 - x_b for Jb
1.2 Compute model and obs space increments
Compute model error \(x_i - {\cal M}(x_{i-1}\) (weak constraint only)
Write increment (diagnostics)
Write the model space component of the first guess
Reset first guess pointer
Compute Jb value
Definition at line 240 of file CostJbTotal.h.
{
   CtrlInc_ dx(*this);
   jb_->computeIncrement(xb_.state(), fg_->state(), dx.state());
   dx.modVar().diff(fg_->modVar(), xb_.modVar());
   dx.obsVar().diff(fg_->obsVar(), xb_.obsVar());
   if (jqnl) jqnl->computeModelError(fg_->state(), dx.state());
   Log::info() << "CostJb: FG-BG" << dx << std::endl;
   this->writeIncrement(dx, conf);
   if (conf.has("stateModAux")) {
     fg_->modVar().write(conf);
   }
   fg_ = nullptr;
   double zjb = this->evaluate(dx);
   return zjb;
 }
References oops::JqTerm< MODEL >::computeModelError(), oops::ObsAuxIncrements< MODEL >::diff(), oops::ModelAuxIncrement< MODEL >::diff(), oops::ControlIncrement< MODEL >::modVar(), oops::ControlIncrement< MODEL >::obsVar(), and oops::ControlIncrement< MODEL >::state().
finalizeAD()
template<typename MODEL > void oops::CostJbTotal< MODEL >::finalizeAD (JqTermAD_ * jqad) const
Perform clean ups after the AD run.
Definition at line 471 of file CostJbTotal.h.
{
   if (jqad) jqad->clear();
 }
References oops::JqTermAD< MODEL >::clear().
Referenced by oops::LBHessianMatrix< MODEL >::multiply().
finalizeTL()
template<typename MODEL > void oops::CostJbTotal< MODEL >::finalizeTL (JqTermTL_ * jqtl, const CtrlInc_ & bgns, CtrlInc_ & dx) const
Model error computation (weak constraint only) after the TL run.
Definition at line 452 of file CostJbTotal.h.
{
   dx = bgns;
   if (jqtl) jqtl->computeModelErrorTL(dx.state());
 }
References oops::JqTermTL< MODEL >::computeModelErrorTL(), and oops::ControlIncrement< MODEL >::state().
Referenced by oops::LBHessianMatrix< MODEL >::multiply().
finalizeTraj()
template<typename MODEL > double oops::CostJbTotal< MODEL >::finalizeTraj (JqTerm_ * jqnl, const eckit::Configuration & conf)
Various computations after the linearisation trajectory computation.
This method is called once the model linearisation trajectory is computed. Its purpose is to compute the first guess increment, update background covariances corresponding to the auxiliary observation space components of the control vector (relevant for IFS). In case of weak constraint JqTerm computes the model error. Returns the value of the Jb component of the cost function.
Compute and save the first guess increment.
Compute the model error (relevant for weak constraint)
Update covariances corresponding to the auxiliary observation space components of the control vector
Compute and return the Jb value
Definition at line 334 of file CostJbTotal.h.
{
   dxFG_.reset(new CtrlInc_(*this));
   // Compute x_0 - x_b for Jb
   if (conf.has("explicitChangeResolution")) {
     State4D_ xblr(resolution(), xb_.state());
     jb_->computeIncrement(xblr, fg_->state(), dxFG_->state());
   } else {
     jb_->computeIncrement(xb_.state(), fg_->state(), dxFG_->state());
   }
   // Model and Obs biases
   dxFG_->modVar().diff(fg_->modVar(), xb_.modVar());
   dxFG_->obsVar().diff(fg_->obsVar(), xb_.obsVar());
   if (jqnl) jqnl->computeModelError(fg_->state(), dxFG_->state());
   Log::info() << "CostJb: FG-BG" << *dxFG_ << std::endl;
   if (conf.has("covariancesObsAux")) {
     // Update ObsAuxCovariance
     jbObsBias_.update(fg_->obsVar(), conf);
   }
   // Reset first guess pointer
   fg_ = nullptr;
   double zjb = this->evaluate(*dxFG_);
   return zjb;
 }
References oops::JqTerm< MODEL >::computeModelError().
getBackground()
template<typename MODEL > const CtrlVar_& oops::CostJbTotal< MODEL >::getBackground () const inline
Return background.
Definition at line 146 of file CostJbTotal.h.
 { return xb_; }
References oops::CostJbTotal< MODEL >::xb_.
getFirstGuessIncrement()
template<typename MODEL > const CtrlInc_& oops::CostJbTotal< MODEL >::getFirstGuessIncrement () const inline
Return first guess increment \(x_0-x_b\).
Definition at line 149 of file CostJbTotal.h.
 { return *dxFG_; }
References oops::CostJbTotal< MODEL >::dxFG_.
initialize()
template<typename MODEL > JqTerm< MODEL > * oops::CostJbTotal< MODEL >::initialize (const CtrlVar_ & fg) const
Various set ups prior to the integration of the model.
This method is called prior to the non-linear model integration. Relevant for weak constraint only. CostJbJq (inheriting from CostJbState) returns a post-processor that is subsequently attached to the model integration. Its purpose is to compute the model error \(x_i - {\cal M}(x_{i-1}\). Returns JqTerm post-processor.
Definition at line 225 of file CostJbTotal.h.
{
   fg_ = &fg;
   JqTerm_ *jqnl = jb_->initializeJq();
   return jqnl;
 }
initializeAD()
template<typename MODEL > JqTermAD< MODEL > * oops::CostJbTotal< MODEL >::initializeAD (CtrlInc_ & bgns, const CtrlInc_ & dx) const
Initialize JqTermAD (weak constraint only) before starting the AD run.
Definition at line 461 of file CostJbTotal.h.
{
   JqTermAD_ *jqad = jb_->initializeJqAD(dx.state());
   bgns += dx;
   return jqad;
 }
References oops::ControlIncrement< MODEL >::state().
Referenced by oops::LBHessianMatrix< MODEL >::multiply().
initializeTL()
template<typename MODEL > JqTermTL< MODEL > * oops::CostJbTotal< MODEL >::initializeTL
Initialize JqTermTL (weak constraint only) before starting the TL run.
Definition at line 444 of file CostJbTotal.h.
{
   JqTermTL_ *jqtl = jb_->initializeJqTL();
   return jqtl;
 }
Referenced by oops::LBHessianMatrix< MODEL >::multiply().
initializeTraj()
template<typename MODEL > JqTerm< MODEL > * oops::CostJbTotal< MODEL >::initializeTraj (const CtrlVar_ & fg, const Geometry_ & resol, const eckit::Configuration & config)
Various set ups prior to the linearisation trajectory computation.
This method is called prior to the forced model linearisation trajectory computation in the TrajecotrySaver. Its purpose is to reset the inner loop geometry, set up the background error covariances. Calls initialize method which returns JqTerm post-processor (relevant for weak constraint). Returns JqTerm post-processor.
Set the pointer to the first guess
Set up the inner loop geometry
Set up covariance matrices
Call the initialize method, linearize JqTerm post-processor and return it.
Definition at line 303 of file CostJbTotal.h.
{
   fg_ = &fg;
   geom_.reset(new Geometry_(resol));
   jb_->linearize(fg_->state(), *geom_, config);
   jbModBias_.linearize(fg_->modVar(), *geom_);
   jbObsBias_.linearize(fg_->obsVar(), fg_->obsVar().obspaces());
   JqTerm_ * jqnl = this->initialize(fg);
   if (jqnl) jqnl->linearize();
   return jqnl;
 }
References oops::JqTerm< MODEL >::linearize().
jbModBias()
template<typename MODEL > const ModelAuxCovar_& oops::CostJbTotal< MODEL >::jbModBias () const inline
Access covariance matrix for the auxiliary model space component of ctrl vec
Definition at line 161 of file CostJbTotal.h.
 { return jbModBias_; }
References oops::CostJbTotal< MODEL >::jbModBias_.
jbObsBias()
template<typename MODEL > const ObsAuxCovars_& oops::CostJbTotal< MODEL >::jbObsBias () const inline
Access covariance matrix for the auxiliary obs space component of ctrl vec
Definition at line 165 of file CostJbTotal.h.
 { return jbObsBias_; }
References oops::CostJbTotal< MODEL >::jbObsBias_.
Referenced by oops::JbMatrix< MODEL >::multiply(), oops::BMatrix< MODEL >::multiplyB(), and oops::BMatrix< MODEL >::multiplyId().
jbState()
template<typename MODEL > const JbState_& oops::CostJbTotal< MODEL >::jbState () const inline
Access covariance matrix for the state component of ctrl vec.
Definition at line 157 of file CostJbTotal.h.
 { return *jb_; }
References oops::CostJbTotal< MODEL >::jb_.
Referenced by oops::BMatrix< MODEL >::multiplyB().
multiplyB()
template<typename MODEL > void oops::CostJbTotal< MODEL >::multiplyB (const CtrlInc_ & dxin, CtrlInc_ & dxout) const
Multiply by the covariance matrix.
Definition at line 478 of file CostJbTotal.h.
{
   jb_->Bmult(dxin.state(), dxout.state());
   jbModBias_.multiply(dxin.modVar(), dxout.modVar());
   jbObsBias_.multiply(dxin.obsVar(), dxout.obsVar());
 }
References oops::ControlIncrement< MODEL >::modVar(), oops::ControlIncrement< MODEL >::obsVar(), and oops::ControlIncrement< MODEL >::state().
Referenced by oops::BMatrix< MODEL >::multiply(), and oops::LBHessianMatrix< MODEL >::multiply().
multiplyBinv()
template<typename MODEL > void oops::CostJbTotal< MODEL >::multiplyBinv (const CtrlInc_ & dxin, CtrlInc_ & dxout) const
Multiply by the inverse covariance matrix.
Definition at line 488 of file CostJbTotal.h.
{
   jb_->Bminv(dxin.state(), dxout.state());
   jbModBias_.inverseMultiply(dxin.modVar(), dxout.modVar());
   jbObsBias_.inverseMultiply(dxin.obsVar(), dxout.obsVar());
 }
References oops::ControlIncrement< MODEL >::modVar(), oops::ControlIncrement< MODEL >::obsVar(), and oops::ControlIncrement< MODEL >::state().
multiplyBsqrt()
template<typename MODEL > void oops::CostJbTotal< MODEL >::multiplyBsqrt (const CtrlVec_ & dvin, CtrlInc_ & dxout) const
Multiply by the square root of the covariance matrix.
Definition at line 498 of file CostJbTotal.h.
{
   jb_->BmultSqrt(dvin.state(), dxout.state());
   jbModBias_.multiplySqrt(dvin.modVar(), dxout.modVar());
   jbObsBias_.multiplySqrt(dvin.obsVar(), dxout.obsVar());
 }
References oops::ControlIncrement< MODEL >::modVar(), oops::ControlVector< MODEL >::modVar(), oops::ControlIncrement< MODEL >::obsVar(), oops::ControlVector< MODEL >::obsVar(), oops::ControlIncrement< MODEL >::state(), and oops::ControlVector< MODEL >::state().
Referenced by oops::BMatrix< MODEL >::multiplySqrt().
multiplyBsqrtTrans()
template<typename MODEL > void oops::CostJbTotal< MODEL >::multiplyBsqrtTrans (const CtrlInc_ & dxin, CtrlVec_ & dvout) const
Multiply by the transpose of the square root of the covariance matrix.
Definition at line 508 of file CostJbTotal.h.
{
   jb_->BmultSqrtTrans(dxin.state(), dvout.state());
   jbModBias_.multiplySqrtTrans(dxin.modVar(), dvout.modVar());
   jbObsBias_.multiplySqrtTrans(dxin.obsVar(), dvout.obsVar());
 }
References oops::ControlIncrement< MODEL >::modVar(), oops::ControlVector< MODEL >::modVar(), oops::ControlIncrement< MODEL >::obsVar(), oops::ControlVector< MODEL >::obsVar(), oops::ControlIncrement< MODEL >::state(), and oops::ControlVector< MODEL >::state().
Referenced by oops::BMatrix< MODEL >::multiplySqrtTrans().
randomize()
template<typename MODEL > void oops::CostJbTotal< MODEL >::randomize (CtrlInc_ & dx) const
Randomize (using the square root of the covariance matrix)
Definition at line 518 of file CostJbTotal.h.
{
   jb_->randomize(dx.state());
   jbModBias_.randomize(dx.modVar());
   jbObsBias_.randomize(dx.obsVar());
 }
References oops::ControlIncrement< MODEL >::modVar(), oops::ControlIncrement< MODEL >::obsVar(), and oops::ControlIncrement< MODEL >::state().
resolution()
template<typename MODEL > const Geometry_& oops::CostJbTotal< MODEL >::resolution () const inline
Access (inner loop) geometry.
Definition at line 154 of file CostJbTotal.h.
 { return *geom_; }
References oops::CostJbTotal< MODEL >::geom_.
writeIncrement()
template<typename MODEL > void oops::CostJbTotal< MODEL >::writeIncrement (const CtrlInc_ & dx, const eckit::Configuration & conf) const private
Write the increment.
Write the state component of the increment
Write the auxiliary model space component of the increment
Write the auxiliary observation space components of the increment
Definition at line 281 of file CostJbTotal.h.
{
   if (conf.has("increment")) {
     // Write increment
     dx.state().write(conf);
   }
   if (conf.has("incrementModAux")) {
     dx.modVar().write(conf);
   }
   if (conf.has("incrementsObsAux")) {
     dx.obsVar().write(conf);
   }
 }
References oops::ControlIncrement< MODEL >::modVar(), oops::ControlIncrement< MODEL >::obsVar(), oops::ControlIncrement< MODEL >::state(), oops::ObsAuxIncrements< MODEL >::write(), oops::ModelAuxIncrement< MODEL >::write(), and oops::Increment4D< MODEL >::write().
Member Data Documentation
dxFG_
template<typename MODEL > std::unique_ptr<CtrlInc_> oops::CostJbTotal< MODEL >::dxFG_ private
First guess increment \(x_0-x_b\) or more generally \(x_i-M(x_{i-1})\).
Definition at line 190 of file CostJbTotal.h.
Referenced by oops::CostJbTotal< MODEL >::getFirstGuessIncrement().
fg_
template<typename MODEL > const CtrlVar_* oops::CostJbTotal< MODEL >::fg_ mutable private
Pointer to the first guess.
Definition at line 186 of file CostJbTotal.h.
geom_
template<typename MODEL > std::unique_ptr<Geometry_> oops::CostJbTotal< MODEL >::geom_ private
Inner loop geometry.
Definition at line 193 of file CostJbTotal.h.
Referenced by oops::CostJbTotal< MODEL >::resolution().
jb_
template<typename MODEL > std::unique_ptr<JbState_> oops::CostJbTotal< MODEL >::jb_ private
Cov matrix for state component of ctrl vec.
Definition at line 179 of file CostJbTotal.h.
Referenced by oops::CostJbTotal< MODEL >::jbState().
jbModBias_
template<typename MODEL > ModelAuxCovar_ oops::CostJbTotal< MODEL >::jbModBias_ private
Cov matrix for auxiliary model space component of ctrl vec
Definition at line 180 of file CostJbTotal.h.
Referenced by oops::CostJbTotal< MODEL >::jbModBias().
jbObsBias_
template<typename MODEL > ObsAuxCovars_ oops::CostJbTotal< MODEL >::jbObsBias_ private
Cov matrix for auxiliary obs space component of ctrl vec.
Definition at line 183 of file CostJbTotal.h.
Referenced by oops::CostJbTotal< MODEL >::jbObsBias().
xb_
template<typename MODEL > const CtrlVar_& oops::CostJbTotal< MODEL >::xb_ private
Reference to the background control variable.
Definition at line 175 of file CostJbTotal.h.
Referenced by oops::CostJbTotal< MODEL >::getBackground().
The documentation for this class was generated from the following files:
src/oops/assimilation/ControlIncrement.h
src/oops/assimilation/CostJbTotal.h