OOPS Documentation: test Namespace Reference
test Namespace Reference
Classes
class ErrorCovariance
class ErrorCovarianceFixture
class Geometry
class GeometryFixture
class GomTestFixture
class Increment
class IncrementFixture
class IncrementTestFixture
class LinearModel
class LinearModelFixture
class Localization
class LocalizationFixture
class LocalizationMatrixFixture
class Locations
class LocationsFixture
class LocsTestFixture
class ModBiasCovTestFixture
class ModBiasTestFixture
class Model
class ModelAuxControl
class ModelAuxControlFixture
class ModelAuxCovariance
class ModelAuxCovarianceFixture
class ModelAuxIncrement
class ModelAuxIncrementFixture
class ModelFixture
class ModelTestFixture
class ObsAuxControl
class ObsAuxControlFixture
class ObsAuxCovariance
class ObsAuxCovarianceFixture
class ObsAuxIncrement
class ObsAuxIncrementFixture
class ObsBiasTestFixture
class ObsErrorCovariance
class ObsErrorCovarianceFixture
class ObservationSpace
class ObservationSpaceFixture
class ObsTableTestFixture
class ObsTestFixture
class ObsVecTestFixture
class ObsVector
class ObsVectorFixture
class ResolutionTestFixture
class State
class StateFixture
class StateTestFixture
class TestConfig
class TestEnvironment
TestEnvironment is a singleton that defines the unit testing enviroment.
struct TestFixture
class TlmTestFixture
class Variables
class VariablesFixture
Functions
template<typename MODEL >
void testErrorCovarianceZero ()
template<typename MODEL >
void testErrorCovarianceInverse ()
template<typename MODEL >
void testErrorCovarianceSym ()
template<typename MODEL >
void testConstructor ()
template<typename MODEL >
void testCopyConstructor ()
template<typename MODEL >
void testIncrementConstructor ()
template<typename MODEL >
void testIncrementCopyConstructor ()
template<typename MODEL >
void testIncrementTriangle ()
template<typename MODEL >
void testIncrementOpPlusEq ()
template<typename MODEL >
void testIncrementDotProduct ()
template<typename MODEL >
void testIncrementZero ()
template<typename MODEL >
void testIncrementAxpy ()
template<typename MODEL >
void testLinearModelConstructor ()
template<typename MODEL >
void testLinearModelZeroLength ()
template<typename MODEL >
void testLinearModelZeroPert ()
template<typename MODEL >
void testLinearModelLinearity ()
template<typename MODEL >
void testLinearApproximation ()
template<typename MODEL >
void testLinearModelAdjoint ()
template<typename MODEL >
void testLocalizationZero ()
template<typename MODEL >
void testLocalizationMultiply ()
template<typename MODEL >
void testConstructors ()
template<typename MODEL >
void testModelConstructor ()
template<typename MODEL >
void testModelNoForecast ()
template<typename MODEL >
void testModelForecast ()
template<typename MODEL >
void testChangeRes ()
template<typename MODEL >
void testModelAuxIncrementConstructor ()
template<typename MODEL >
void testModelAuxIncrementCopyConstructor ()
template<typename MODEL >
void testModelAuxIncrementChangeRes ()
template<typename MODEL >
void testModelAuxIncrementTriangle ()
template<typename MODEL >
void testModelAuxIncrementOpPlusEq ()
template<typename MODEL >
void testModelAuxIncrementDotProduct ()
template<typename MODEL >
void testModelAuxIncrementZero ()
template<typename MODEL >
void testModelAuxIncrementAxpy ()
template<typename MODEL >
void testObsAuxIncrementConstructor ()
template<typename MODEL >
void testObsAuxIncrementCopyConstructor ()
template<typename MODEL >
void testObsAuxIncrementChangeRes ()
template<typename MODEL >
void testObsAuxIncrementTriangle ()
template<typename MODEL >
void testObsAuxIncrementOpPlusEq ()
template<typename MODEL >
void testObsAuxIncrementDotProduct ()
template<typename MODEL >
void testObsAuxIncrementZero ()
template<typename MODEL >
void testObsAuxIncrementAxpy ()
template<typename MODEL >
void testStateConstructor ()
template<typename MODEL >
void testStateCopyConstructor ()
std::int32_t test_uniform_real_f (const eckit::Configuration *const *)
std::int32_t test_uniform_int_f (const eckit::Configuration *const *)
std::int32_t test_normal_real_f (const eckit::Configuration *const *)
CASE ("test_GomL95")
CASE ("test_IncrementL95")
CASE ("test_localizationMatrixL95")
CASE ("test_LocsL95")
CASE ("test_modelBias")
CASE ("test_modelBiasCorrection")
CASE ("test_modelBiasCovariance")
CASE ("test_modelL95")
CASE ("test_obsBias")
CASE ("test_obsBiasCorrection")
CASE ("test_obsBiasCovariance")
CASE ("test_ObsL95")
CASE ("test_ObsTable")
CASE ("test_ObsVec1D")
CASE ("test_resolution")
CASE ("test_StateL95")
CASE ("test_tlmL95")
Function Documentation
CASE() [1/17]
test::CASE ("test_GomL95")
Definition at line 58 of file GomL95.cc.
                     {
   GomTestFixture f;
 // -----------------------------------------------------------------------------
   SECTION("test_GomL95_constructor") {
     std::unique_ptr<lorenz95::GomL95> gom(new lorenz95::GomL95(*f.ot_, *f.novar_, *f.incr_, *f.t1_, *f.t2_));
     EXPECT(gom.get() != NULL);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_GomL95_nobs") {
     std::unique_ptr<lorenz95::GomL95> gom(new lorenz95::GomL95(*f.ot_, *f.novar_, *f.incr_, *f.t1_, *f.t2_));
     EXPECT(gom->nobs() == 160);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_gomL95_classname") {
     std::unique_ptr<lorenz95::GomL95> gom(new lorenz95::GomL95(*f.ot_, *f.novar_, *f.incr_, *f.t1_, *f.t2_));
     EXPECT(gom->classname() == "lorenz95::GomL95");
   }
 // -----------------------------------------------------------------------------
   SECTION("test_gomL95_zero") {
     std::unique_ptr<lorenz95::GomL95> gom(new lorenz95::GomL95(*f.ot_, *f.novar_, *f.incr_, *f.t1_, *f.t2_));
     gom->zero();
     for (int i = 0; i < gom->nobs(); ++i) {
       EXPECT((*gom)[i] == 0.0);
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_gomL95_dot_product_with") {
     std::unique_ptr<lorenz95::GomL95> gom1(new lorenz95::GomL95(*f.ot_, *f.novar_, *f.incr_, *f.t1_, *f.t2_));
     gom1->zero();
     std::unique_ptr<lorenz95::GomL95> gom2(new lorenz95::GomL95(*f.ot_, *f.novar_, *f.incr_, *f.t1_, *f.t2_));
     gom2->zero();
     double zz = gom1->dot_product_with(*gom2);
     EXPECT(zz == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_gomL95_operator") {
     std::unique_ptr<lorenz95::GomL95> gom1(new lorenz95::GomL95(*f.ot_, *f.novar_, *f.incr_, *f.t1_, *f.t2_));
     gom1->zero();
     std::unique_ptr<lorenz95::GomL95> gom2(new lorenz95::GomL95(*f.ot_, *f.novar_, *f.incr_, *f.t1_, *f.t2_));
     gom2->zero();
     (*gom1)[1] = 1.0;
     (*gom2)[3] = 1.0;
     double zz = gom1->dot_product_with(*gom2);
     EXPECT(zz == 0.0);
     (*gom1)[3] = 1.0;
     zz = gom1->dot_product_with(*gom2);
     EXPECT(zz == 1.0);
   }
 // -----------------------------------------------------------------------------
 }
CASE() [2/17]
test::CASE ("test_IncrementL95")
Definition at line 57 of file IncrementL95.cc.
{
   IncrementTestFixture fix;
 // -----------------------------------------------------------------------------
   SECTION("test_incrementL95_constructor") {
     std::unique_ptr<lorenz95::IncrementL95>
       dx(new lorenz95::IncrementL95(*fix.resol_, *fix.vars_, *fix.time_));
     EXPECT(dx.get() != NULL);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_incrementL95_interpolation_constructor") {
     std::unique_ptr<lorenz95::IncrementL95>
       dx1(new lorenz95::IncrementL95(*fix.resol_, *fix.vars_, *fix.time_));
     std::unique_ptr<lorenz95::IncrementL95>
       dx2(new lorenz95::IncrementL95(*fix.resol_, *dx1));
     EXPECT(dx2.get() != NULL);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_incrementL95_copy_constructor") {
     std::unique_ptr<lorenz95::IncrementL95>
       dx1(new lorenz95::IncrementL95(*fix.resol_, *fix.vars_, *fix.time_));
     std::unique_ptr<lorenz95::IncrementL95> dx2(new lorenz95::IncrementL95(*dx1));
     EXPECT(dx2.get() != NULL);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_incrementL95_diff") {
     lorenz95::IncrementL95 dx(*fix.resol_, *fix.vars_, *fix.time_);
     dx.read(*fix.file_);
     // construct the first stateL95 object
     lorenz95::StateL95 xx1(*fix.resol_, *fix.model_, *fix.file_);
     // read in the state config info
     xx1.read(*fix.file_);
     lorenz95::StateL95 xx2(xx1);
     // to vary the results a little, change the second StateL95 field values
     double fact = 0.75;
     dx *= fact;
     xx2 += dx;
     dx.diff(xx1, xx2);
     // to verify the diff method has worked correctly, we need
     // to open and read the file containing the FieldL95
     std::string filename(fix.file_->getString("filename"));
     std::ifstream inStream(filename.c_str());
     if (!inStream.is_open()) {
       oops::Log::error() << "diff functionality cannot be determined" << std::endl;
     }
     // we read in these two values but do not use them
     int resolInt;
     inStream >> resolInt;
     std::string time;
     inStream >> time;
     std::vector<double> doubleVec(resolInt);
     for (int i = 0; i < resolInt; ++i) {
       inStream >> doubleVec[i];
     }
     inStream.close();
     for (int i = 0; i < fix.resol_->npoints(); ++i) {
       EXPECT(oops::is_close((dx.getField())[i],
                          doubleVec[i] - (doubleVec[i] + (doubleVec[i] * fact)),
                          1.0e-6));
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_incrementL95_zero") {
     lorenz95::IncrementL95 dx(*fix.resol_, *fix.vars_, *fix.time_);
     dx.read(*fix.file_);
     // first check that we have good data, ie, at least one element is non-zero
     bool goodData = false;
     for (int i = 0; i < fix.resol_->npoints() && goodData == false; ++i) {
       if ((dx.getField())[i] != 0) {
         goodData = true;
       }
     }
     if (!goodData) {
       oops::Log::error() <<
         "unable to test zero method, since test data is already all zero" << std::endl;;
     } else {
       dx.zero();
       for (int i = 0; i < fix.resol_->npoints(); ++i) {
         EXPECT(dx.getField()[i] == 0);
       }
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_incrementL95_zero_set_datetime") {
     lorenz95::IncrementL95 dx(*fix.resol_, *fix.vars_, *fix.time_);
     dx.read(*fix.file_);
     // first check that we have good data, ie, at least one element is non-zero
     bool goodData = false;
     for (int i = 0; i < fix.resol_->npoints() && goodData == false; ++i) {
       if (dx.getField()[i] != 0) {
         goodData = true;
       }
     }
     if (!goodData) {
       oops::Log::error() <<
         "unable to test zero method, since test data is already all zero" << std::endl;
     } else {
       const std::string modified_date_string("2010-01-01T10:35:00Z");
       const util::DateTime dtModified(modified_date_string);
       dx.zero(dtModified);
       for (int i = 0; i < fix.resol_->npoints(); ++i) {
         EXPECT(dx.getField()[i] == 0);
       }
       EXPECT(dx.validTime().toString() != fix.date_str_);
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_incrementL95_assignment") {
     lorenz95::IncrementL95 dx1(*fix.resol_, *fix.vars_, *fix.time_);
     dx1.read(*fix.file_);
     // construct the second dx object
     lorenz95::IncrementL95 dx2(*fix.resol_, *fix.vars_, *fix.time_);
     double fact = 0.75;
     dx2.read(*fix.file_);
     dx2 *= fact;
     dx1 = dx2;
     for (int i = 0; i < dx1.getField().resol(); ++i) {
       EXPECT(dx1.getField()[i] == dx2.getField()[i]);
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_incrementL95_compound_assignment_add") {
     lorenz95::IncrementL95 dx1(*fix.resol_, *fix.vars_, *fix.time_);
     dx1.read(*fix.file_);
     // copy construct the second stateL95 object
     lorenz95::IncrementL95 dx2(dx1);
     dx1 += dx2;
     // since the two IncrementL95 objects started off with the same data,
     // once they've been added together incL591 will be double what incL952 is
     for (int i = 0; i < dx1.getField().resol(); ++i) {
       EXPECT(dx1.getField()[i] == 2.0 * dx2.getField()[i]);
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_incrementL95_compound_assignment_subtract") {
     lorenz95::IncrementL95 dx1(*fix.resol_, *fix.vars_, *fix.time_);
     dx1.read(*fix.file_);
     // copy construct the second stateL95 object
     lorenz95::IncrementL95 dx2(dx1);
     dx1 -= dx2;
     // since the two IncrementL95 objects started off with the same data,
     // once incL952 has been subtracted from incL951, the result is zero
     for (int i = 0; i < dx1.getField().resol(); ++i) {
       EXPECT(dx1.getField()[i] == 0.0);
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_incrementL95_compound_assignment_multiply") {
     lorenz95::IncrementL95 dx(*fix.resol_, *fix.vars_, *fix.time_);
     dx.read(*fix.file_);
     // create a copy of the original data for testing against
     std::vector<double> testData(dx.getField().resol());
     for (unsigned int ii = 0; ii < testData.size(); ++ii) {
       testData.at(ii) = dx.getField()[ii];
     }
     double fact = 0.75;
     dx *= fact;
     for (int ii = 0; ii < dx.getField().resol(); ++ii) {
       EXPECT(dx.getField()[ii] == testData.at(ii) * fact);
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_incrementL95_axpy") {
     lorenz95::IncrementL95 dx1(*fix.resol_, *fix.vars_, *fix.time_);
     dx1.read(*fix.file_);
     // copy construct the second stateL95 object
     lorenz95::IncrementL95 dx2(dx1);
     double fact = 0.75;
     dx1.axpy(fact, dx2);
     for (int i = 0; i < dx1.getField().resol(); ++i) {
       EXPECT(dx1.getField()[i] == dx2.getField()[i] + fact * dx2.getField()[i]);
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_incrementL95_dot_product_with") {
     lorenz95::IncrementL95 dx1(*fix.resol_, *fix.vars_, *fix.time_);
     dx1.read(*fix.file_);
     // copy construct the second stateL95 object
     lorenz95::IncrementL95 dx2(dx1);
     double dpwResult = dx1.dot_product_with(dx2);
     // prepare a value to test against
     double testResult = 0.0;
     for (int i = 0; i < dx1.getField().resol(); ++i) {
       testResult += (dx1.getField()[i] * dx2.getField()[i]);
     }
     EXPECT(dpwResult == testResult);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_incrementL95_schur_product_with") {
     lorenz95::IncrementL95 dx1(*fix.resol_, *fix.vars_, *fix.time_);
     dx1.read(*fix.file_);
     // copy construct the second stateL95 object
     lorenz95::IncrementL95 dx2(dx1);
     dx1.schur_product_with(dx2);
     // both incL951 and incL952 started off with the same data in x_,
     // so to test incL951 against incL952xincL952 is a valid test
     for (int i = 0; i < dx1.getField().resol(); ++i) {
       EXPECT(dx1.getField()[i] == dx2.getField()[i] * dx2.getField()[i]);
     }
   }
 // -----------------------------------------------------------------------------
   /*
   SECTION("test_incrementL95_interpolateTL") {
     lorenz95::IncrementL95 dx(*fix.resol_, *fix.vars_, *fix.time_);
     int maxVecSize = 5;
     // construct the LocsL95 object
     std::vector<double> doubleVec(maxVecSize);
     // populate the vector with values from 0.1 to 0.5
     for (int i = 0; i < maxVecSize; ++i) {
       doubleVec[i] = ((i + 1) * 0.1);
     }
     lorenz95::LocsL95 locsL95(doubleVec);
     // construct the GomL95 object
     std::vector<int> intVec(maxVecSize);
     lorenz95::GomL95 gomL95(intVec);
     // populate the locval_ vector with values from 1.1 to 0.5
     for (int i = 0; i < intVec.size(); ++i) {
       gomL95[i] = ((i + 1) * 0.1);
     }
     int origCurrent = gomL95.current();
     dx.interpolateTL(locsL95, gomL95);
     for (int i = 0; i < locsL95.nobs(); ++i) {
       EXPECT(gomL95[origCurrent + i] == dx.getField()[i]);
     }
     EXPECT(gomL95.current() == (origCurrent + locsL95.nobs()));
   }
 // -----------------------------------------------------------------------------
   SECTION("test_incrementL95_interpolateAD") {
     lorenz95::IncrementL95 dx(*fix.resol_, *fix.vars_, *fix.time_);
     int maxVecSize = 5;
     // construct the LocsL95 object
     std::vector<double> doubleVec(maxVecSize);
     // populate the vector with values from 0.1 to 0.5
     for (int i = 0; i < maxVecSize; ++i) {
       doubleVec[i] = ((i + 1) * 0.1);
     }
     lorenz95::LocsL95 locsL95(doubleVec);
     // construct the GomL95 object
     std::vector<int> intVec(maxVecSize);
     lorenz95::GomL95 gomL95(intVec);
     // populate the locval_ vector with values from 0.1 to 0.5
     for (int i = 0; i < intVec.size(); ++i) {
       gomL95[i] = ((i + 1) * 0.1);
     }
     int origCurrent = gomL95.current();
     dx.interpolateAD(locsL95, gomL95);
     const double dres = static_cast<double>(dx.getField().resol());
     if (gomL95.current() == 0) {
       gomL95.current() = gomL95.nobs();
     }
     gomL95.current() -= locsL95.nobs();
     for (int i = 0; i < locsL95->nobs(); ++i) {
       int idx = round(locsL95[i] * dres);
       EXPECT(dx.getField()[idx] == gomL95[gomL95.current() + i]);
     }
   }
   */
 // -----------------------------------------------------------------------------
   SECTION("test_incrementL95_read") {
     lorenz95::IncrementL95 dx(*fix.resol_, *fix.vars_, *fix.time_);
     dx.read(*fix.file_);
     // to verify the information has been read correctly, we need to open
     // and read the file using ifstream functionality
     const std::string filename(fix.file_->getString("filename"));
     std::ifstream inStream(filename.c_str());
     if (!inStream.is_open()) {
       oops::Log::error() << "read functionality cannot be determined" << std::endl;
     }
     int resolInt;
     inStream >> resolInt;
     std::string time;
     inStream >> time;
     std::vector<double> doubleVec(resolInt);
     for (int i = 0; i < resolInt; ++i) {
       inStream >> doubleVec[i];
     }
     inStream.close();
     for (int i = 0; i < fix.resol_->npoints(); ++i) {
       EXPECT(dx.getField()[i] == doubleVec[i]);
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_incrementL95_write") {
     lorenz95::IncrementL95 dx(*fix.resol_, *fix.vars_, *fix.time_);
     dx.read(*fix.file_);
     eckit::LocalConfiguration opFileCfg(TestConfig::config(), "outputFile");
     dx.write(opFileCfg);
     // Should read back in and compare values
   }
 // -----------------------------------------------------------------------------
   SECTION("test_incrementL95_validTime") {
     lorenz95::IncrementL95 dx(*fix.resol_, *fix.vars_, *fix.time_);
     EXPECT(dx.validTime().toString() == fix.date_str_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_incrementL95_timeUpdate") {
     util::Duration dur("PT1H30M10S");
     std::string updated_date_string("2010-01-01T10:30:10Z");
     lorenz95::IncrementL95 dx(*fix.resol_, *fix.vars_, *fix.time_);
     dx.validTime() += dur;
     EXPECT(dx.validTime().toString() == updated_date_string);
   }
 // -----------------------------------------------------------------------------
 /*
   SECTION("test_incrementL95_stream_output") {
     lorenz95::IncrementL95 dx(*fix.resol_, *fix.vars_, *fix.time_);
     // use the operator<< method to write the value to a file
     std::filebuf fb;
     std::string filename("IncrementL95Test.txt");
     fb.open(filename.c_str(), std::ios::out);
     std::ostream os(&fb);
     os << dx;
     fb.close();
     // then read the value that was written to the file
     std::string input;
     std::string inputTest(" Valid time: " + fix.date_str_);
     std::ifstream inputFile(filename.c_str());
     if (inputFile.is_open()) {
       getline(inputFile, input);  // ignore the first (blank) line
       getline(inputFile, input);
       EXPECT(input == inputTest);
     } else {
       // if we can't open the file then we can't
       // verify that the value was correctly written
       oops::Log::error() << "operator<< functionality cannot be determined" << std::endl;
     }
     inputFile.close();
   }
 */
 // -----------------------------------------------------------------------------
   SECTION("test_incrementL95_getField") {
     lorenz95::IncrementL95 dx(*fix.resol_, *fix.vars_, *fix.time_);
     // there are 2 values in FieldL95: the 1st is the *resol_ value,
     // the 2nd is a vector of doubles initialised to 0.0, the size of the
     // vector is the *resol_ value (we're just checking the final one)
     EXPECT(dx.getField().resol() == fix.resol_->npoints());
   }
 // -----------------------------------------------------------------------------
 }  //  CASE
References oops::is_close().
CASE() [3/17]
test::CASE ("test_localizationMatrixL95")
Definition at line 40 of file LocalizationMatrixL95.cc.
{
   LocalizationMatrixFixture fix;
 // -----------------------------------------------------------------------------
   SECTION("test_localizationMatrixL95_constructor") {
     std::unique_ptr<lorenz95::LocalizationMatrixL95> locmat(
         new lorenz95::LocalizationMatrixL95(*fix.resol_, *fix.cfg_));
     EXPECT(locmat.get() != NULL);
   }
 // -----------------------------------------------------------------------------
 }  //  CASE
CASE() [4/17]
test::CASE ("test_LocsL95")
Definition at line 51 of file LocsL95.cc.
                      {
   LocsTestFixture fix;
 // -----------------------------------------------------------------------------
   SECTION("test_LocsL95_constructor") {
     std::unique_ptr<lorenz95::LocsL95> locs(new lorenz95::LocsL95(*fix.ot_, *fix.t1_, *fix.t2_));
     EXPECT(locs.get() != NULL);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_LocsL95_nobs") {
     std::unique_ptr<lorenz95::LocsL95> locs(new lorenz95::LocsL95(*fix.ot_, *fix.t1_, *fix.t2_));
     size_t ref = 80;
     EXPECT(locs->nobs() ==ref);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_LocsL95_operator") {
     std::unique_ptr<lorenz95::LocsL95> locs(new lorenz95::LocsL95(*fix.ot_, *fix.t1_, *fix.t2_));
     double pos = 0.0;
     for (size_t jj = 0; jj < locs->nobs(); ++jj) {
       EXPECT(oops::is_close((*locs)[jj], pos, 0.00000001));
       pos += 0.05;
       if (pos >= 1.0) pos=0.0;
     }
   }
 // -----------------------------------------------------------------------------
 }  //  CASE
References oops::is_close().
CASE() [5/17]
test::CASE ("test_modelBias")
Definition at line 58 of file ModelBias.cc.
{
   ModBiasTestFixture fix;
 // -----------------------------------------------------------------------------
   SECTION("test_modelBias_constructor_bias") {
     lorenz95::ModelBias mbias(*fix.resol_, *fix.biasconf_);
     EXPECT(mbias.bias() == fix.bias1_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBias_constructor_nobias") {
     lorenz95::ModelBias mbias(*fix.resol_, *fix.nobias_);
     // because the biasconf_ is empty when used,
     // the active_ flag is false and the bias_ value is 0.0
     EXPECT(mbias.bias() == 0.0);
 }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBias_constructor_active") {
     lorenz95::ModelBias mbias1(*fix.resol_, *fix.biasconf_);
     lorenz95::ModelBias mbias2(*fix.resol_, mbias1);
     EXPECT(mbias2.bias() == fix.bias1_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBias_constructor_inactive") {
     lorenz95::ModelBias mbias1(*fix.resol_, *fix.nobias_);
     lorenz95::ModelBias mbias2(*fix.resol_, mbias1);
     // because the biasconf_ is empty when used,
     // the active_ flag is false and the bias_ value is 0.0
     EXPECT(mbias2.bias() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBias_constructor_active_copy") {
     lorenz95::ModelBias mbias1(*fix.resol_, *fix.biasconf_);
     lorenz95::ModelBias mbias2(mbias1, true);
     EXPECT(mbias2.bias() == fix.bias1_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBias_constructor_active_nocopy") {
     lorenz95::ModelBias mbias1(*fix.resol_, *fix.biasconf_);
     lorenz95::ModelBias mbias2(mbias1, false);
     // because copy flag is set to false, bias is 0.0
     EXPECT(mbias2.bias() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBias_constructor_inactive_copy") {
     lorenz95::ModelBias mbias1(*fix.resol_, *fix.nobias_);
     lorenz95::ModelBias mbias2(mbias1, true);
     // because the biasconf_ is empty when used,
     // the active_ flag is false and the bias_ value is 0.0
     EXPECT(mbias2.bias() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBias_constructor_inactive_nocopy") {
     lorenz95::ModelBias mbias1(*fix.resol_, *fix.nobias_);
     lorenz95::ModelBias mbias2(mbias1, false);
     EXPECT(mbias2.bias() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBias_destructor") {
     // not yet implemented
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBias_classname") {
     lorenz95::ModelBias mbias(*fix.resol_, *fix.biasconf_);
     EXPECT(mbias.classname() == "lorenz95::ModelBias");
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBias_compound_assignment_active") {
     lorenz95::ModelBias mbias(*fix.resol_, *fix.biasconf_);
     mbias += *fix.dbias_;
     EXPECT(mbias.bias() == fix.bias1_ + fix.bias2_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBias_compound_assignment_inactive") {
     lorenz95::ModelBias mbias(*fix.resol_, *fix.nobias_);
     mbias += *fix.dbias_;
     // because the biasconf_ is empty,
     // mbias bias value is not modified from 0.0
     EXPECT(mbias.bias() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBias_bias") {
     lorenz95::ModelBias mbias(*fix.resol_, *fix.biasconf_);
     EXPECT(mbias.bias() == fix.bias1_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBias_read") {
     // not yet implemented
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBias_write") {
     // not yet implemented
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBias_stream_output") {
     lorenz95::ModelBias mbias(*fix.resol_, *fix.biasconf_);
     // use the operator<< method to write the value to a file
     std::filebuf fb;
     std::string filename("ModelBiasTest.txt");
     fb.open(filename.c_str(), std::ios::out);
     std::ostream os(&fb);
     os << mbias;
     fb.close();
     // then read the value that was written to the file
     std::string inputString;
     std::string inputBias;
     double testBias = fix.bias1_;
     double bias = 0.0;
     int biasStartPos = 12;  // length of "ModelBias = " is 12
     std::ifstream inputFile(filename.c_str());
     if (inputFile.is_open()) {
       getline(inputFile, inputString);  // ignore first (blank) line
       getline(inputFile, inputString);
       inputBias = inputString.substr(biasStartPos);
       try {
         bias = eckit::Translator<std::string, double>()(inputBias);
       }
       catch(eckit::BadParameter const&) {
         oops::Log::error() << "operator<< incorrectly output a non-double" << std::endl;
       }
       EXPECT(oops::is_close(testBias, bias, 0.0001));
     } else {
       // if we can't open the file then we can't
       // verify that the value was correctly written
       oops::Log::error() << "operator<< functionality cannot be determined" << std::endl;
     }
     inputFile.close();
   }
 // -----------------------------------------------------------------------------
 }  //  CASE
References oops::is_close().
CASE() [6/17]
test::CASE ("test_modelBiasCorrection")
Definition at line 54 of file ModelBiasCorrection.cc.
{
   ModBiasTestFixture fix;
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_constructor_config") {
     std::unique_ptr<lorenz95::ModelBiasCorrection> dx(
       new lorenz95::ModelBiasCorrection(*fix.resol_, *fix.conf_));
     EXPECT(dx.get() != NULL);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_constructor_no_config") {
     std::unique_ptr<lorenz95::ModelBiasCorrection> dx(
       new lorenz95::ModelBiasCorrection(*fix.resol_, *fix.nobias_));
     EXPECT(dx.get() != NULL);
 }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_copy_ctor_active_copy") {
     lorenz95::ModelBiasCorrection dx1(*fix.resol_, *fix.conf_);
     dx1.bias() = fix.bias1_;
     lorenz95::ModelBiasCorrection dx2(dx1, true);
     EXPECT(dx2.bias() == fix.bias1_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_copy_ctor_active_no_copy") {
     lorenz95::ModelBiasCorrection dx1(*fix.resol_, *fix.conf_);
     dx1.bias() = fix.bias1_;
     // construct a copy of it with the copy flag set to false
     lorenz95::ModelBiasCorrection dx2(dx1, false);
     // because the copy is false,
     // the active_ flag is true and the bias_ value is 0.0
     EXPECT(dx2.bias() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_copy_ctor_inactive_copy") {
     lorenz95::ModelBiasCorrection dx1(*fix.resol_, *fix.nobias_);
     dx1.bias() = fix.bias1_;
     // construct a copy of it with the copy flag set to true
     lorenz95::ModelBiasCorrection dx2(dx1, true);
     // because the cfg is empty when used,
     // the active_ flag is false and the bias_ value is 0.0
     EXPECT(dx2.bias() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_copy_ctor_inactive_no_copy") {
     lorenz95::ModelBiasCorrection dx1(*fix.resol_, *fix.nobias_);
     dx1.bias() = fix.bias1_;
     // construct a copy of it with the copy flag set to false
     lorenz95::ModelBiasCorrection dx2(dx1, false);
     // because the cfg is empty when used and the copy flag is false,
     // the active_ flag is false and the bias_ value is 0.0
     EXPECT(dx2.bias() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_copy_ctor_config_active") {
     lorenz95::ModelBiasCorrection dx1(*fix.resol_, *fix.conf_);
     dx1.bias() = fix.bias1_;
     lorenz95::ModelBiasCorrection dx2(dx1, *fix.conf_);
     EXPECT(dx2.bias() == fix.bias1_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_copy_ctor_config_inactive") {
     lorenz95::ModelBiasCorrection dx1(*fix.resol_, *fix.nobias_);
     dx1.bias() = fix.bias1_;
     lorenz95::ModelBiasCorrection dx2(dx1, *fix.conf_);
      // because the covarCfg is empty when used (regardless of the cfg),
      // the active_ flag is false and the bias_ value is 0.0
      EXPECT(dx2.bias() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_diff_active") {
     lorenz95::ModelBias xx1(*fix.resol_, *fix.conf_);
     xx1.bias() = fix.bias1_;
     lorenz95::ModelBias xx2(*fix.resol_, *fix.conf_);
     xx2.bias() = fix.bias2_;
     lorenz95::ModelBiasCorrection dx(*fix.resol_, *fix.conf_);
     dx.diff(xx1, xx2);
     EXPECT(dx.bias() == fix.bias1_ - fix.bias2_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_diff_inactive") {
     lorenz95::ModelBias xx1(*fix.resol_, *fix.conf_);
     xx1.bias() = fix.bias1_;
     lorenz95::ModelBias xx2(*fix.resol_, *fix.conf_);
     xx2.bias() = fix.bias2_;
     lorenz95::ModelBiasCorrection dx(*fix.resol_, *fix.nobias_);
     dx.diff(xx1, xx2);
     // because the active_ flag is false, the bias cannot be updated
     EXPECT(dx.bias() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_zero") {
     lorenz95::ModelBiasCorrection dx(*fix.resol_, *fix.conf_);
     dx.bias() = fix.bias1_;
     dx.zero();
     EXPECT(dx.bias() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_assignment_active") {
     lorenz95::ModelBiasCorrection dx1(*fix.resol_, *fix.conf_);
     dx1.bias() = fix.bias1_;
     lorenz95::ModelBiasCorrection dx2(*fix.resol_, *fix.conf_);
     dx2.bias() = fix.bias2_;
     dx1 = dx2;
     // the original MBC should have the same bias value as the copy MBC
     EXPECT(dx1.bias() == fix.bias2_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_assignment_inactive") {
     lorenz95::ModelBiasCorrection dx1(*fix.resol_, *fix.nobias_);
     dx1.bias() = fix.bias1_;
     lorenz95::ModelBiasCorrection dx2(*fix.resol_, *fix.conf_);
     dx2.bias() = fix.bias2_;
     dx1 = dx2;
     // the active_ value is zero, so the bias will be zero
     EXPECT(dx1.bias() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_assignment_add_active") {
     lorenz95::ModelBiasCorrection dx1(*fix.resol_, *fix.conf_);
     dx1.bias() = fix.bias1_;
     lorenz95::ModelBiasCorrection dx2(*fix.resol_, *fix.conf_);
     dx2.bias() = fix.bias2_;
     dx1 += dx2;
     EXPECT(dx1.bias() == fix.bias1_ + fix.bias2_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_assignment_add_inactive") {
     lorenz95::ModelBiasCorrection dx1(*fix.resol_, *fix.nobias_);
     dx1.bias() = fix.bias1_;
     lorenz95::ModelBiasCorrection dx2(*fix.resol_, *fix.nobias_);
     dx2.bias() = fix.bias2_;
     dx1 += dx2;
     // the active_ value is zero, so the bias will be unchanged
     EXPECT(dx1.bias() == fix.bias1_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_assignment_subtract_active") {
     lorenz95::ModelBiasCorrection dx1(*fix.resol_, *fix.conf_);
     dx1.bias() = fix.bias1_;
     lorenz95::ModelBiasCorrection dx2(*fix.resol_, *fix.conf_);
     dx2.bias() = fix.bias2_;
     dx1 -= dx2;
     EXPECT(dx1.bias() == fix.bias1_ - fix.bias2_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_assignment_subtract_inactive") {
     lorenz95::ModelBiasCorrection dx1(*fix.resol_, *fix.nobias_);
     dx1.bias() = fix.bias1_;
     lorenz95::ModelBiasCorrection dx2(*fix.resol_, *fix.nobias_);
     dx2.bias() = fix.bias2_;
     dx1 -= dx2;
     // the active_ value is zero, so the bias will be unchanged
     EXPECT(dx1.bias() == fix.bias1_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_assignment_multiply_active") {
     lorenz95::ModelBiasCorrection dx(*fix.resol_, *fix.conf_);
     dx.bias() = fix.bias1_;
     dx *= fix.fact_;
     EXPECT(dx.bias() == fix.bias1_ * fix.fact_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_assignment_multiply_inactive") {
     lorenz95::ModelBiasCorrection dx(*fix.resol_, *fix.nobias_);
     dx.bias() = fix.bias1_;
     dx *= fix.fact_;
     // the active_ value is zero, so the bias will be unchanged
     EXPECT(dx.bias() == fix.bias1_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_axpy_active") {
     lorenz95::ModelBiasCorrection dx1(*fix.resol_, *fix.conf_);
     dx1.bias() = fix.bias1_;
     lorenz95::ModelBiasCorrection dx2(*fix.resol_, *fix.conf_);
     dx2.bias() = fix.bias2_;
     dx1.axpy(fix.fact_, dx2);
     EXPECT(dx1.bias() == (fix.bias1_ + fix.fact_ * fix.bias2_));
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_axpy_inactive") {
     lorenz95::ModelBiasCorrection dx1(*fix.resol_, *fix.nobias_);
     dx1.bias() = fix.bias1_;
     lorenz95::ModelBiasCorrection dx2(*fix.resol_, *fix.nobias_);
     dx2.bias() = fix.bias2_;
     dx1.axpy(fix.fact_, dx2);
     // the active_ value is zero, so the bias will be unchanged
     EXPECT(dx1.bias() == fix.bias1_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_dot_product_with_active") {
     lorenz95::ModelBiasCorrection dx1(*fix.resol_, *fix.conf_);
     dx1.bias() = fix.bias1_;
     lorenz95::ModelBiasCorrection dx2(*fix.resol_, *fix.conf_);
     dx2.bias() = fix.bias2_;
     double dpwResult = dx1.dot_product_with(dx2);
     EXPECT(dpwResult == fix.bias1_ * fix.bias2_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_dot_product_with_inactive") {
     lorenz95::ModelBiasCorrection dx1(*fix.resol_, *fix.nobias_);
     dx1.bias() = fix.bias1_;
     lorenz95::ModelBiasCorrection dx2(*fix.resol_, *fix.nobias_);
     dx2.bias() = fix.bias2_;
     double dpwResult = dx1.dot_product_with(dx2);
     // because of the empty config, the result is 0.0
     EXPECT(dpwResult == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_read") {
     // nothing to test
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_write") {
     // nothing to test
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_stream_output") {
     lorenz95::ModelBiasCorrection dx(*fix.resol_, *fix.conf_);
     dx.bias() = fix.bias1_;
     // use the operator<< method to write the value to a file
     std::filebuf fb;
     std::string filename("ModelBiasCorrectionTest.txt");
     fb.open(filename.c_str(), std::ios::out);
     std::ostream os(&fb);
     os << dx;
     fb.close();
     // then read the value that was written to the file
     std::string inputString;
     std::string inputBias;
     double testBias = fix.bias1_;
     double bias = 0.0;
     int biasStartPos = 22;  // length of "ModelBiasCorrection = " is 22
     std::ifstream inputFile(filename.c_str());
     if (inputFile.is_open()) {
       getline(inputFile, inputString);  // ignore first (blank) line
       getline(inputFile, inputString);
       inputBias = inputString.substr(biasStartPos);
       try {
         bias = eckit::Translator<std::string, double>()(inputBias);
       }
       catch(eckit::BadParameter const&) {
         oops::Log::error() << "operator<< incorrectly output a non-double" << std::endl;
       }
       EXPECT(oops::is_close(testBias, bias, 0.000001));
     } else {
       // if we can't open the file then we can't
       // verify that the value was correctly written
       oops::Log::error() << "operator<< functionality cannot be determined" << std::endl;
     }
     inputFile.close();
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCorrection_bias") {
     lorenz95::ModelBiasCorrection dx(*fix.resol_, *fix.conf_);
     dx.bias() = fix.bias1_;
     // this one test checks both the setting and getting of the bias value
     EXPECT(dx.bias() == fix.bias1_);
   }
 // -----------------------------------------------------------------------------
 }  //  CASE
References oops::is_close().
CASE() [7/17]
test::CASE ("test_modelBiasCovariance")
Definition at line 45 of file ModelBiasCovariance.cc.
{
   ModBiasCovTestFixture f;
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCovariance_constructor_conf") {
     lorenz95::ModelBiasCovariance bcovar(*f.covconf_, *f.resol_);
     EXPECT(bcovar.active() == true);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCovariance_constructor_no_conf") {
     lorenz95::ModelBiasCovariance bcovar(*f.nobias_, *f.resol_);
     EXPECT(bcovar.active() == false);
 }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCovariance_linearize") {
     // not yet implemented
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCovariance_multiply_activei") {
     // construct the ModelBiasCorrection object
     lorenz95::ModelBiasCovariance bcovar(*f.covconf_, *f.resol_);
     lorenz95::ModelBiasCorrection dbias1(*f.resol_, *f.covconf_);
     dbias1.bias() = 2.0;
     lorenz95::ModelBiasCorrection dbias2(dbias1, true);
     bcovar.multiply(dbias1, dbias2);
     double stdev = f.covconf_->getDouble("standard_deviation");
     EXPECT(dbias2.bias() == dbias1.bias() * stdev * stdev);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCovariance_multiply_inactive") {
     // construct the ModelBiasCorrection object
     lorenz95::ModelBiasCovariance bcovar(*f.nobias_, *f.resol_);
     lorenz95::ModelBiasCorrection dbias1(*f.resol_, *f.covconf_);
     dbias1.bias() = 2.0;
     lorenz95::ModelBiasCorrection dbias2(dbias1, true);
     bcovar.multiply(dbias1, dbias2);
     // because the covconf_ is empty, the bias is set to 0
     EXPECT(dbias2.bias() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCovariance_invMult_active") {
     // construct the ModelBiasCorrection object
     lorenz95::ModelBiasCovariance bcovar(*f.covconf_, *f.resol_);
     lorenz95::ModelBiasCorrection dbias1(*f.resol_, *f.covconf_);
     dbias1.bias() = 2.0;
     lorenz95::ModelBiasCorrection dbias2(dbias1, true);
     bcovar.inverseMultiply(dbias1, dbias2);
     double stdev = f.covconf_->getDouble("standard_deviation");
     EXPECT(dbias2.bias() == dbias1.bias() *1.0 / (stdev * stdev));
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCovariance_invMult_inactive") {
     // construct the ModelBiasCorrection object
     lorenz95::ModelBiasCovariance bcovar(*f.nobias_, *f.resol_);
     lorenz95::ModelBiasCorrection dbias1(*f.resol_, *f.covconf_);
     dbias1.bias() = 2.0;
     lorenz95::ModelBiasCorrection dbias2(dbias1, true);
     bcovar.inverseMultiply(dbias1, dbias2);
     // because the covconf_ is empty, the bias is set to 0
     EXPECT(dbias2.bias() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelBiasCovariance_active") {
     lorenz95::ModelBiasCovariance bcovar(*f.covconf_, *f.resol_);
     EXPECT(bcovar.active() == true);
   }
 // -----------------------------------------------------------------------------
 }  //  CASE
CASE() [8/17]
test::CASE ("test_modelL95")
Definition at line 49 of file ModelL95.cc.
                       {
 ModelTestFixture fix;
 // -----------------------------------------------------------------------------
   SECTION("test_modelL95_constructor") {
     std::unique_ptr<lorenz95::ModelL95> model(new lorenz95::ModelL95(*fix.resol_, *fix.nlconf_));
     EXPECT(model != NULL);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelL95_get_classname") {
     lorenz95::ModelL95 model(*fix.resol_, *fix.nlconf_);
     EXPECT(model.classname() == "lorenz95::ModelL95");
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelL95_get_timestep") {
     lorenz95::ModelL95 model(*fix.resol_, *fix.nlconf_);
     util::Duration dt(fix.nlconf_->getString("tstep"));
     EXPECT(model.timeResolution().toSeconds() == dt.toSeconds());
   }
 // -----------------------------------------------------------------------------
   SECTION("test_modelL95_stepRk") {
     lorenz95::ModelL95 model(*fix.resol_, *fix.nlconf_);
     // construct a FieldL95 object
     lorenz95::FieldL95 fieldL95(*fix.resol_);
     // construct a ModelBias object
     eckit::LocalConfiguration biasCfg(TestConfig::config(), "ModelBias");
     lorenz95::ModelBias modelBias(*fix.resol_, biasCfg);
     // construct a ModelTrajectory object
     lorenz95::ModelTrajectory modelTraj(true);
     modelTraj.set(fieldL95);
 //    for(int i = 0; i < fieldL95.resol(); ++i) {
 //      oops::Log::error() << "PMC: pre  stepRK " << fieldL95[i] << std::endl;
 //    }
     model.stepRK(fieldL95, modelBias, modelTraj);
 //    for(int i = 0; i < fieldL95.resol(); ++i) {
 //      oops::Log::error() << "PMC: post stepRK " << fieldL95[i] << std::endl;
 //    }
   }
 // -----------------------------------------------------------------------------
 }  //  CASE
CASE() [9/17]
test::CASE ("test_obsBias")
Definition at line 57 of file ObsBias.cc.
                      {
   ObsBiasTestFixture fix;
 // -----------------------------------------------------------------------------
   SECTION("test_obsBias_constructor_bias") {
     lorenz95::ObsBias ob(*fix.obstable_, *fix.biasconf_);
     EXPECT(ob.value() == fix.biasconf_->getDouble("bias"));
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBias_constructor_no_bias") {
     lorenz95::ObsBias ob(*fix.obstable_, *fix.nobias_);
     EXPECT(ob.value() == 0.0);
 }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBias_copy_constructor_config_copy") {
     lorenz95::ObsBias ob1(*fix.obstable_, *fix.biasconf_);
     lorenz95::ObsBias ob2(ob1, true);
     EXPECT(ob2.value() == fix.biasconf_->getDouble("bias"));
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBias_copy_constructor_config_no_copy") {
     lorenz95::ObsBias ob1(*fix.obstable_, *fix.biasconf_);
     lorenz95::ObsBias ob2(ob1, false);
     // bias value is 0 because copy flag was set to false
     EXPECT(ob2.value() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBias_copy_constructor_no_config_copy") {
     lorenz95::ObsBias ob1(*fix.obstable_, *fix.nobias_);
     lorenz95::ObsBias ob2(ob1, true);
     // bias value is 0 because an empty config was used
     EXPECT(ob2.value() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBias_copy_constructor_no_config_no_copy") {
     lorenz95::ObsBias ob1(*fix.obstable_, *fix.nobias_);
     lorenz95::ObsBias ob2(ob1, true);
     // bias value is 0 because an empty config was used
     EXPECT(ob2.value() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBias_destructor") {
     // not yet implemented
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBias_compound_assignment_add_active") {
     lorenz95::ObsBias ob(*fix.obstable_, *fix.biasconf_);
     // construct an obsBiasCorrection object
     lorenz95::ObsBiasCorrection obsBiasCorrection(*fix.obstable_, *fix.covconf_);
     obsBiasCorrection.value() = 3.14;
     ob += obsBiasCorrection;
     EXPECT(ob.value() == fix.biasconf_->getDouble("bias") + 3.14);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBias_compound_assignment_add_inactive") {
     lorenz95::ObsBias ob(*fix.obstable_, *fix.nobias_);
     // construct an obsBiasCorrection object
     lorenz95::ObsBiasCorrection obsBiasCorrection(*fix.obstable_, *fix.covconf_);
     obsBiasCorrection.value() = 3.14;
     ob += obsBiasCorrection;
     // the bias value will be 0 because the ob had an empty config
     EXPECT(ob.value() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBias_value") {
     lorenz95::ObsBias ob(*fix.obstable_, *fix.biasconf_);
     EXPECT(ob.value() == fix.biasconf_->getDouble("bias"));
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBias_read") {
     // not yet implemented
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBias_write") {
     // not yet implemented
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBias_stream_output") {
     lorenz95::ObsBias ob(*fix.obstable_, *fix.biasconf_);
     // use the operator<< method to write the value to a file
     std::filebuf fb;
     std::string filename("ObsBiasTest.txt");
     fb.open(filename.c_str(), std::ios::out);
     std::ostream os(&fb);
     os << ob;
     fb.close();
     // then read the value that was written to the file
     std::string inputString;
     std::string inputBias;
     double testBias = fix.biasconf_->getDouble("bias");
     double bias = 0.0;
     int biasStartPos = 10;  // length of "ObsBias = " is 10
     std::ifstream inputFile(filename.c_str());
     if (inputFile.is_open()) {
       getline(inputFile, inputString);
       getline(inputFile, inputString);
       inputBias = inputString.substr(biasStartPos);
       try {
         bias = eckit::Translator<std::string, double>()(inputBias);
       }
       catch(eckit::BadParameter const&) {
         oops::Log::error() << "operator<< incorrectly output a non-double" << std::endl;
       }
       EXPECT(oops::is_close(testBias, bias, 0.000001));
     } else {
       // if we can't open the file then we can't
       // verify that the value was correctly written
       oops::Log::error() << "operator<< functionality cannot be determined" << std::endl;
     }
     inputFile.close();
   }
 // -----------------------------------------------------------------------------
 }  //  CASE
References oops::is_close().
CASE() [10/17]
test::CASE ("test_obsBiasCorrection")
Definition at line 65 of file ObsBiasCorrection.cc.
{
   ObsBiasTestFixture fix;
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_constructor_active") {
     lorenz95::ObsBiasCorrection dob(*fix.obstable_, *fix.conf_);
     EXPECT(dob.value() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_constructor_inactive") {
     lorenz95::ObsBiasCorrection dob(*fix.obstable_, *fix.off_);
     EXPECT(dob.value() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_copy_ctor_active_copy") {
     lorenz95::ObsBiasCorrection dob1(*fix.obstable_, *fix.conf_);
     dob1.value() = fix.bias1_;
     lorenz95::ObsBiasCorrection dob2(dob1, true);
     EXPECT(dob2.value() == fix.bias1_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_copy_ctor_active_no_copy") {
     lorenz95::ObsBiasCorrection dob1(*fix.obstable_, *fix.conf_);
     dob1.value() = fix.bias1_;
     lorenz95::ObsBiasCorrection dob2(dob1, false);
     // because the copy is false,
     // the active_ flag is true and the bias1_ value is 0.0
     EXPECT(dob2.value() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_copy_ctor_inactive_copy") {
     lorenz95::ObsBiasCorrection dob1(*fix.obstable_, *fix.off_);
     dob1.value() = fix.bias1_;
     lorenz95::ObsBiasCorrection dob2(dob1, true);
     // because the cfg is empty when used,
     // the active_ flag is false and the bias1_ value is 0.0
     EXPECT(dob2.value() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_copy_ctor_inactive_no_copy") {
     lorenz95::ObsBiasCorrection dob1(*fix.obstable_, *fix.off_);
     dob1.value() = fix.bias1_;
     lorenz95::ObsBiasCorrection dob2(dob1, false);
     // because the cfg is empty when used and the copy flag is false,
     // the active_ flag is false and the bias1_ value is 0.0
     EXPECT(dob2.value() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_copy_constructor_config") {
     lorenz95::ObsBiasCorrection dob1(*fix.obstable_, *fix.conf_);
     dob1.value() = fix.bias1_;
     lorenz95::ObsBiasCorrection dob2(dob1, *fix.conf_);
     EXPECT(dob2.value() == fix.bias1_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_copy_constructor_no_config") {
     lorenz95::ObsBiasCorrection dob1(*fix.obstable_, *fix.off_);
     dob1.value() = fix.bias1_;
     lorenz95::ObsBiasCorrection dob2(dob1, eckit::LocalConfiguration());
     // because the covarCfg is empty when used (regardless of the cfg),
     // the active_ flag is false and the bias1_ value is 0.0
     EXPECT(dob2.value() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_diff_active") {
     lorenz95::ObsBias obias2(*fix.obstable_, *fix.conf_);
     obias2.value() = fix.bias2_;
     lorenz95::ObsBiasCorrection dob(*fix.obstable_, *fix.conf_);
     dob.diff(*fix.obias_, obias2);
     EXPECT(dob.value() == fix.bias1_ - fix.bias2_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_diff_inactive") {
     lorenz95::ObsBias obias2(*fix.obstable_, *fix.conf_);
     obias2.value() = fix.bias2_;
     // construct the dob object with empty config
     lorenz95::ObsBiasCorrection dob(*fix.obstable_, *fix.off_);
     dob.diff(*fix.obias_, obias2);
     // because the OBC has empty config the active_flag is false and
     // the diff will not be performed, leaving the OBC value unchanged
     EXPECT(dob.value() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_zero") {
     lorenz95::ObsBiasCorrection dob(*fix.obstable_, *fix.conf_);
     dob.value() = fix.bias1_;
     dob.zero();
     EXPECT(dob.value() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_assignment_active") {
     lorenz95::ObsBiasCorrection dob1(*fix.obstable_, *fix.conf_);
     dob1.value() = fix.bias1_;
     lorenz95::ObsBiasCorrection dob2(dob1);
     dob2.value() = fix.bias2_;
     dob1 = dob2;
     EXPECT(dob1.value() == fix.bias2_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_assignment_inactive") {
     lorenz95::ObsBiasCorrection dob1(*fix.obstable_, *fix.off_);
     dob1.value() = fix.bias1_;
     lorenz95::ObsBiasCorrection dob2(dob1);
     dob2.value() = fix.bias2_;
     dob1 = dob2;
     // because the OBC has empty config the active_ flag is false
     EXPECT(dob1.value() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_assignment_add_active") {
     lorenz95::ObsBiasCorrection dob1(*fix.obstable_, *fix.conf_);
     dob1.value() = fix.bias1_;
     lorenz95::ObsBiasCorrection dob2(dob1);
     dob2.value() = fix.bias2_;
     dob1 += dob2;
     EXPECT(dob1.value() == fix.bias1_ + fix.bias2_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_assign_add_inactive") {
     lorenz95::ObsBiasCorrection dob1(*fix.obstable_, *fix.off_);
     dob1.value() = fix.bias1_;
     lorenz95::ObsBiasCorrection dob2(dob1);
     dob2.value() = fix.bias2_;
     dob1 += dob2;
     // because the OBC has empty config, the bias value is unchanged
     EXPECT(dob1.value() == fix.bias1_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_assignment_subtract_active") {
     lorenz95::ObsBiasCorrection dob1(*fix.obstable_, *fix.conf_);
     dob1.value() = fix.bias1_;
     lorenz95::ObsBiasCorrection dob2(dob1);
     dob2.value() = fix.bias2_;
     dob1 -= dob2;
     EXPECT(dob1.value() == fix.bias1_ - fix.bias2_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_assignment_subtract_inactive") {
     lorenz95::ObsBiasCorrection dob1(*fix.obstable_, *fix.off_);
     dob1.value() = fix.bias1_;
     lorenz95::ObsBiasCorrection dob2(dob1);
     dob2.value() = fix.bias2_;
     dob1 -= dob2;
     // because the OBC has empty config, the bias value is unchanged
     EXPECT(dob1.value() == fix.bias1_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_assignment_multiply_active") {
     lorenz95::ObsBiasCorrection dob(*fix.obstable_, *fix.conf_);
     dob.value() = fix.bias1_;
     dob *= fix.fact_;
     EXPECT(dob.value() == fix.bias1_ * fix.fact_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_assignment_multiply_inactive") {
     lorenz95::ObsBiasCorrection dob(*fix.obstable_, *fix.off_);
     dob.value() = fix.bias1_;
     dob *= fix.fact_;
     // because the OBC has empty config, the bias value is unchanged
     EXPECT(dob.value() == fix.bias1_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_axpy_active") {
     lorenz95::ObsBiasCorrection dob1(*fix.obstable_, *fix.conf_);
     dob1.value() = fix.bias1_;
     lorenz95::ObsBiasCorrection dob2(dob1);
     dob2.value() = fix.bias2_;
     dob1.axpy(fix.fact_, dob2);
     EXPECT(dob1.value() == fix.bias1_ + (fix.fact_ * fix.bias2_));
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_axpy_inactive") {
     lorenz95::ObsBiasCorrection dob1(*fix.obstable_, *fix.off_);
     dob1.value() = fix.bias1_;
     lorenz95::ObsBiasCorrection dob2(dob1);
     dob2.value() = fix.bias2_;
     dob1.axpy(fix.fact_, dob2);
     // because the OBC has empty config, the bias value is unchanged
     EXPECT(dob1.value() == fix.bias1_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_dot_product_with_active") {
     lorenz95::ObsBiasCorrection dob1(*fix.obstable_, *fix.conf_);
     dob1.value() = fix.bias1_;
     lorenz95::ObsBiasCorrection dob2(dob1);
     dob2.value() = fix.bias2_;
     double dpwResult = dob1.dot_product_with(dob2);
     EXPECT(dpwResult == fix.bias1_ * fix.bias2_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_dot_product_with_inactive") {
     lorenz95::ObsBiasCorrection dob1(*fix.obstable_, *fix.off_);
     dob1.value() = fix.bias1_;
     lorenz95::ObsBiasCorrection dob2(dob1);
     dob2.value() = fix.bias2_;
     double dpwResult = dob1.dot_product_with(dob2);
     // because the OBC has empty config, the result is 0
     EXPECT(dpwResult == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_read") {
     // not yet implemented
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_write") {
     // not yet implemented
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCorrection_stream_output") {
     lorenz95::ObsBiasCorrection dob(*fix.obstable_, *fix.conf_);
     dob.value() = fix.bias1_;
     // use the operator<< method to write the value to a file
     std::filebuf fb;
     std::string filename("ObsBiasCorrectionTest.txt");
     fb.open(filename.c_str(), std::ios::out);
     std::ostream os(&fb);
     os << dob;
     fb.close();
     // then read the value that was written to the file
     std::string inputString;
     std::string inputBias;
     double bias = 0.0;
     int biasStartPos = 20;  // length of "ObsBiasCorrection = " is 20
     std::ifstream inputFile(filename.c_str());
     if (inputFile.is_open()) {
       getline(inputFile, inputString);  // ignore first (blank) line
       getline(inputFile, inputString);
       inputBias = inputString.substr(biasStartPos);
       try {
         bias = eckit::Translator<std::string, double>()(inputBias);
       }
       catch(eckit::BadParameter const&) {
         oops::Log::error() << "operator<< incorrectly output a non-double" << std::endl;
       }
       EXPECT(oops::is_close(fix.bias1_, bias, 0.0001));
     } else {
       // if we can't open the file then we can't
       // verify that the value was correctly written
       oops::Log::error() << "operator<< functionality cannot be determined" << std::endl;
     }
     inputFile.close();
   }
 // -----------------------------------------------------------------------------
 }  //  CASE
References oops::is_close().
CASE() [11/17]
test::CASE ("test_obsBiasCovariance")
Definition at line 53 of file ObsBiasCovariance.cc.
{
   ObsBiasTestFixture fix;
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCovariance_constructor_conf") {
     lorenz95::ObsBiasCovariance obcovar(*fix.obstable_, *fix.covconf_);
     EXPECT(obcovar.active() == true);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCovariance_constructor_no_conf") {
     lorenz95::ObsBiasCovariance obcovar(*fix.obstable_, *fix.nobias_);
     EXPECT(obcovar.active() == false);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCovariance_destructor") {
     // not yet implemented
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCovariance_linearize") {
     // not yet implemented
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCovariance_multiply_active") {
     lorenz95::ObsBiasCovariance obcovar(*fix.obstable_, *fix.covconf_);
     lorenz95::ObsBiasCorrection db1(*fix.obstable_, *fix.covconf_);
     db1.value() = 2.0;
     lorenz95::ObsBiasCorrection db2(db1, *fix.covconf_);
     obcovar.multiply(db1, db2);
     const double stdev = fix.covconf_->getDouble("standard_deviation");
     EXPECT(db2.value() == db1.value() * stdev * stdev);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCovariance_multiply_inactive") {
     lorenz95::ObsBiasCovariance obcovar(*fix.obstable_, *fix.nobias_);
     lorenz95::ObsBiasCorrection db1(*fix.obstable_, *fix.nobias_);
     db1.value() = 2.0;
     lorenz95::ObsBiasCorrection db2(db1, *fix.covconf_);
     obcovar.multiply(db1, db2);
     // because the OBC has empty config, the bias is set to 0.0
     EXPECT(db2.value() == 0.0);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCovariance_invMult_active") {
     lorenz95::ObsBiasCovariance obcovar(*fix.obstable_, *fix.covconf_);
     lorenz95::ObsBiasCorrection db1(*fix.obstable_, *fix.covconf_);
     db1.value() = 2.0;
     lorenz95::ObsBiasCorrection db2(db1, *fix.covconf_);
     obcovar.inverseMultiply(db1, db2);
     const double stdev = fix.covconf_->getDouble("standard_deviation");
     EXPECT(db2.value() == db1.value() * 1.0 / (stdev * stdev));
   }
 // -----------------------------------------------------------------------------
   SECTION("test_obsBiasCovariance_invMult_inactive") {
     lorenz95::ObsBiasCovariance obcovar(*fix.obstable_, *fix.nobias_);
     lorenz95::ObsBiasCorrection db1(*fix.obstable_, *fix.nobias_);
     db1.value() = 2.0;
     lorenz95::ObsBiasCorrection db2(db1, *fix.covconf_);
     obcovar.inverseMultiply(db1, db2);
     // because the OBC has empty config, the bias is set to 0.0
     EXPECT(db2.value() == 0.0);
   }
 // -----------------------------------------------------------------------------
 }  //  CASE
CASE() [12/17]
test::CASE ("test_ObsL95")
Definition at line 45 of file ObservationL95.cc.
                     {
   ObsTestFixture fix;
 // -----------------------------------------------------------------------------
   SECTION("test_ObsL95_constructor") {
     std::unique_ptr<lorenz95::ObservationL95>
       obs(new lorenz95::ObservationL95(*fix.ot_, TestConfig::config()));
     EXPECT(obs.get() != NULL);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_observationL95_classname") {
     std::unique_ptr<lorenz95::ObservationL95>
       obs(new lorenz95::ObservationL95(*fix.ot_, TestConfig::config()));
     EXPECT(obs->classname() == "lorenz95::ObservationL95");
   }
 // -----------------------------------------------------------------------------
 }  //  CASE
CASE() [13/17]
test::CASE ("test_ObsTable")
Definition at line 47 of file ObsTable.cc.
                       {
   ObsTableTestFixture fix;
 // -----------------------------------------------------------------------------
   SECTION("test_ObsTable_constructor") {
     std::unique_ptr<lorenz95::ObsTable>
       ot(new lorenz95::ObsTable(*fix.testconf_, *fix.resol_, *fix.bgn_, *fix.end_));
     EXPECT(ot.get() != NULL);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_ObsTable_nobs") {
     std::unique_ptr<lorenz95::ObsTable>
       ot(new lorenz95::ObsTable(*fix.testconf_, *fix.resol_, *fix.bgn_, *fix.end_));
     const unsigned int nobs = 160;
     EXPECT(ot->nobs() == nobs);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_observationL95_put_get") {
     std::unique_ptr<lorenz95::ObsTable>
       ot(new lorenz95::ObsTable(*fix.testconf_, *fix.resol_, *fix.bgn_, *fix.end_));
     unsigned int nn = ot->nobs();
     std::vector<double> v1(nn);
     for (unsigned int jj = 0; jj < nn; ++jj) {
       v1[jj] = 3.14*jj;
     }
     ot->putdb("ObsTest", v1);
     std::vector<double> v2;
     ot->getdb("ObsTest", v2);
     EXPECT(v2.size() == nn);
     for (unsigned int jj = 0; jj < nn; ++jj) {
       EXPECT(v2[jj] == v1[jj]);
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_observationL95_timeSelect") {
     std::unique_ptr<lorenz95::ObsTable>
       ot(new lorenz95::ObsTable(*fix.testconf_, *fix.resol_, *fix.bgn_, *fix.end_));
     util::DateTime t1("2010-01-01T09:00:00Z");
     util::DateTime t2("2010-01-01T21:00:00Z");
     std::vector<int> mask = ot->timeSelect(t1, t2);  // t1 not includede, t2 is
     const unsigned int size = 80;
     EXPECT(mask.size() == size);
     EXPECT(mask[0] == 40);
     EXPECT(mask[79] == 119);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_observationL95_locations") {
     std::unique_ptr<lorenz95::ObsTable>
       ot(new lorenz95::ObsTable(*fix.testconf_, *fix.resol_,  *fix.bgn_, *fix.end_));
     util::DateTime t1("2010-01-01T09:00:00Z");
     util::DateTime t2("2010-01-01T21:00:00Z");
     std::vector<double> locs = ot->locations(t1, t2);
     const unsigned int size = 80;
     EXPECT(locs.size() == size);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_observationL95_distribute") {
     eckit::LocalConfiguration otconf;
     util::DateTime t1("2010-01-01T00:00:00Z");
     util::DateTime t2("2010-01-02T23:59:59Z");
     std::unique_ptr<lorenz95::ObsTable>
       ot(new lorenz95::ObsTable(otconf, *fix.resol_, t1, t2));
     // More complete test in makeobs* tests.
     eckit::LocalConfiguration genconf(*fix.obsconf_, "Generate");
     ot->generateDistribution(genconf);
   }
 // -----------------------------------------------------------------------------
 }  //  CASE
CASE() [14/17]
test::CASE ("test_ObsVec1D")
Definition at line 47 of file ObsVec1D.cc.
                       {
   ObsVecTestFixture fix;
 // -----------------------------------------------------------------------------
   SECTION("test_ObsVec1D_constructor") {
     std::unique_ptr<lorenz95::ObsVec1D> ov(new lorenz95::ObsVec1D(*fix.obstable_));
     EXPECT(ov.get() != NULL);
     for (unsigned int ii = 0; ii < fix.obstable_->nobs(); ++ii) {
       EXPECT((*ov)(ii) == 0.0);
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_ObsVec1D_nobs") {
     std::unique_ptr<lorenz95::ObsVec1D> ov(new lorenz95::ObsVec1D(*fix.obstable_));
     EXPECT(ov->size() == fix.obstable_->nobs());
   }
 // -----------------------------------------------------------------------------
   SECTION("test_ObsVec1D_read") {
     std::unique_ptr<lorenz95::ObsVec1D> ov(new lorenz95::ObsVec1D(*fix.obstable_));
     ov->read("ObsVal");
     for (unsigned int ii = 0; ii < fix.obstable_->nobs(); ++ii) {
       EXPECT((*ov)(ii) != 0.0);
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_ObsVec1D_copy_constructor_copy") {
     std::unique_ptr<lorenz95::ObsVec1D> ov1(new lorenz95::ObsVec1D(*fix.obstable_));
     ov1->read("ObsVal");
     std::unique_ptr<lorenz95::ObsVec1D> ov2(new lorenz95::ObsVec1D(*ov1, true));
     for (unsigned int ii = 0; ii < fix.obstable_->nobs(); ++ii) {
       EXPECT((*ov2)(ii) == (*ov1)(ii));
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_ObsVec1D_copy_constructor_no_copy") {
     std::unique_ptr<lorenz95::ObsVec1D> ov1(new lorenz95::ObsVec1D(*fix.obstable_));
     ov1->read("ObsVal");
     std::unique_ptr<lorenz95::ObsVec1D> ov2(new lorenz95::ObsVec1D(*ov1, false));
     for (unsigned int ii = 0; ii < fix.obstable_->nobs(); ++ii) {
       EXPECT((*ov2)(ii) == 0.0);
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_ObsVec1D_classname") {
     std::unique_ptr<lorenz95::ObsVec1D> ov(new lorenz95::ObsVec1D(*fix.obstable_));
     EXPECT(ov->classname() == "lorenz95::ObsVec1D");
   }
 // -----------------------------------------------------------------------------
   SECTION("test_ObsVec1D_assignment") {
     std::unique_ptr<lorenz95::ObsVec1D> ov1(new lorenz95::ObsVec1D(*fix.obstable_));
     ov1->read("ObsVal");
     std::unique_ptr<lorenz95::ObsVec1D> ov2(new lorenz95::ObsVec1D(*fix.obstable_));
     // use the assignment operator to populate the second ObsVec1D object
     *ov2 = *ov1;
     for (unsigned int ii = 0; ii < fix.obstable_->nobs(); ++ii) {
       EXPECT((*ov2)(ii) == (*ov1)(ii));
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_ObsVec1D_compound_assignment_multiply_double") {
     std::unique_ptr<lorenz95::ObsVec1D> ov1(new lorenz95::ObsVec1D(*fix.obstable_));
     ov1->read("ObsVal");
     std::unique_ptr<lorenz95::ObsVec1D> ov2(new lorenz95::ObsVec1D(*ov1, true));
     // create a random double value
     double mult = 7.92;
     *ov2 *= mult;
     for (unsigned int ii = 0; ii < fix.obstable_->nobs(); ++ii) {
       EXPECT((*ov2)(ii) == (*ov1)(ii) * mult);
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_ObsVec1D_compound_assignment_add") {
     std::unique_ptr<lorenz95::ObsVec1D> ov1(new lorenz95::ObsVec1D(*fix.obstable_));
     ov1->read("ObsVal");
     std::unique_ptr<lorenz95::ObsVec1D> ov2(new lorenz95::ObsVec1D(*ov1, true));
     *ov1 += *ov2;
     for (unsigned int ii = 0; ii < fix.obstable_->nobs(); ++ii) {
       EXPECT((*ov1)(ii) == (*ov2)(ii) + (*ov2)(ii));
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_ObsVec1D_compound_assignment_subtract") {
     std::unique_ptr<lorenz95::ObsVec1D> ov1(new lorenz95::ObsVec1D(*fix.obstable_));
     ov1->read("ObsVal");
     std::unique_ptr<lorenz95::ObsVec1D> ov2(new lorenz95::ObsVec1D(*ov1, true));
     *ov1 -= *ov2;
     for (unsigned int ii = 0; ii < fix.obstable_->nobs(); ++ii) {
       EXPECT((*ov1)(ii) == 0.0);
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_ObsVec1D_compound_assignment_multiply") {
     std::unique_ptr<lorenz95::ObsVec1D> ov1(new lorenz95::ObsVec1D(*fix.obstable_));
     ov1->read("ObsVal");
     std::unique_ptr<lorenz95::ObsVec1D> ov2(new lorenz95::ObsVec1D(*ov1, true));
     *ov1 *= *ov2;
     for (unsigned int ii = 0; ii < fix.obstable_->nobs(); ++ii) {
       EXPECT((*ov1)(ii) == (*ov2)(ii) * (*ov2)(ii));
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_ObsVec1D_compound_assignment_divide") {
     std::unique_ptr<lorenz95::ObsVec1D> ov1(new lorenz95::ObsVec1D(*fix.obstable_));
     ov1->read("ObsVal");
     std::unique_ptr<lorenz95::ObsVec1D> ov2(new lorenz95::ObsVec1D(*ov1, true));
     *ov1 /= *ov2;
     for (unsigned int ii = 0; ii < fix.obstable_->nobs(); ++ii) {
       EXPECT((*ov1)(ii) == 1.0);
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_ObsVec1D_zero") {
     std::unique_ptr<lorenz95::ObsVec1D> ov(new lorenz95::ObsVec1D(*fix.obstable_));
     ov->read("ObsVal");
     ov->zero();
     for (unsigned int ii = 0; ii < fix.obstable_->nobs(); ++ii) {
       EXPECT((*ov)(ii) == 0.0);
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_ObsVec1D_axpy") {
     std::unique_ptr<lorenz95::ObsVec1D> ov1(new lorenz95::ObsVec1D(*fix.obstable_));
     ov1->read("ObsVal");
     std::unique_ptr<lorenz95::ObsVec1D> ov2(new lorenz95::ObsVec1D(*ov1, true));
     double mult = 2.00;
     ov1->axpy(mult, *ov2);
     for (unsigned int ii = 0; ii < fix.obstable_->nobs(); ++ii) {
       EXPECT((*ov1)(ii) == (*ov2)(ii) + mult * (*ov2)(ii));
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_ObsVec1D_invert") {
     std::unique_ptr<lorenz95::ObsVec1D> ov1(new lorenz95::ObsVec1D(*fix.obstable_));
     ov1->read("ObsVal");
     std::unique_ptr<lorenz95::ObsVec1D> ov2(new lorenz95::ObsVec1D(*ov1, true));
     ov1->invert();
     for (unsigned int ii = 0; ii < fix.obstable_->nobs(); ++ii) {
       EXPECT((*ov1)(ii) == 1.0 / (*ov2)(ii));
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_ObsVec1D_random") {
     std::unique_ptr<lorenz95::ObsVec1D> ov(new lorenz95::ObsVec1D(*fix.obstable_));
     ov->random();
     for (unsigned int ii = 0; ii < fix.obstable_->nobs(); ++ii) {
       EXPECT((*ov)(ii) != 0);
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_ObsVec1D_dot_product_with") {
     std::unique_ptr<lorenz95::ObsVec1D> ov1(new lorenz95::ObsVec1D(*fix.obstable_));
     ov1->read("ObsVal");
     std::unique_ptr<lorenz95::ObsVec1D> ov2(new lorenz95::ObsVec1D(*ov1, true));
     double result = ov1->dot_product_with(*ov2);
     double check = 0.0;
     for (unsigned int ii = 0; ii < fix.obstable_->nobs(); ++ii) {
       check += (*ov2)(ii) * (*ov2)(ii);
     }
     EXPECT(oops::is_close(result, check, 1.0e-8));
   }
 // -----------------------------------------------------------------------------
 }  //  CASE
References oops::is_close().
CASE() [15/17]
test::CASE ("test_resolution")
Definition at line 41 of file Resolution.cc.
{
   ResolutionTestFixture fix;
 // -----------------------------------------------------------------------------
   SECTION("test_resolution_constructor") {
     std::unique_ptr<lorenz95::Resolution> resol(new lorenz95::Resolution(*fix.testconf_));
     EXPECT(resol.get() != NULL);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_resolution_copy_constructor") {
     std::unique_ptr<lorenz95::Resolution> xx(new lorenz95::Resolution(*fix.testconf_));
     std::unique_ptr<lorenz95::Resolution> resol(new lorenz95::Resolution(*xx));
     EXPECT(resol.get() != NULL);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_resolution_get_npoints") {
     std::unique_ptr<lorenz95::Resolution> resol(new lorenz95::Resolution(*fix.testconf_));
     EXPECT(resol->npoints() == fix.testconf_->getInt("resol"));
   }
 // -----------------------------------------------------------------------------
   SECTION("test_resolution_stream_output") {
     std::unique_ptr<lorenz95::Resolution> resol(new lorenz95::Resolution(*fix.testconf_));
     // use the operator<< method to write the value to a file
     std::filebuf fb;
     std::string filename("ResolutionTest.txt");
     fb.open(filename.c_str(), std::ios::out);
     std::ostream os(&fb);
     os << *resol.get();
     fb.close();
     // then read the value that was written to the file
     int inputInt;
     std::string input;
     std::ifstream inputFile(filename.c_str());
     if (inputFile.is_open()) {
       getline(inputFile, input);
       try {
         inputInt = eckit::Translator<std::string, int>()(input);
       }
       catch(eckit::BadParameter const&) {
         // test fails because the value written to
         // the file can't be converted to an integer
         oops::Log::error() <<"operator<< incorrectly output a non-integer" << std::endl;
       }
       // it should equal the value that was used in the constructor
       EXPECT(inputInt == resol->npoints());
     } else {
       // if we can't open the file then we can't
       // verify that the value was correctly written
       oops::Log::error() << "operator<< functionality cannot be determined" << std::endl;
     }
     inputFile.close();
   }
 // -----------------------------------------------------------------------------
 }  //  CASE
CASE() [16/17]
test::CASE ("test_StateL95")
Definition at line 62 of file StateL95.cc.
                       {
   StateTestFixture fix;
 // -----------------------------------------------------------------------------
   SECTION("test_stateL95_readin_constructor") {
     std::unique_ptr<lorenz95::StateL95>
       xx(new lorenz95::StateL95(*fix.resol_, *fix.model_, *fix.file_));
     EXPECT(xx.get() != NULL);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_stateL95_interpolation_constructor") {
     lorenz95::StateL95 xx1(*fix.resol_, *fix.model_, *fix.file_);
     std::unique_ptr<lorenz95::StateL95> xx2(new lorenz95::StateL95(*fix.resol_, *fix.model_, xx1));
     EXPECT(xx2.get() != NULL);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_stateL95_copy_constructor") {
     lorenz95::StateL95 xx(*fix.resol_, *fix.model_, *fix.file_);
     std::unique_ptr<lorenz95::StateL95> xx2(new lorenz95::StateL95(xx));
     EXPECT(xx2.get() != NULL);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_stateL95_destructor") {
     // nothing to test
   }
 // -----------------------------------------------------------------------------
   SECTION("test_stateL95_getField") {
     lorenz95::StateL95 xx(*fix.resol_, *fix.model_, *fix.file_);
     // there are 2 values in FieldL95: the 1st is the *resol_ value,
     // the 2nd is a vector of doubles initialised to 0.0, the size of the
     // vector is the *resol_ value
     EXPECT(xx.getField().resol() == fix.resol_->npoints());
   }
 // -----------------------------------------------------------------------------
   SECTION("test_stateL95_validTime") {
     lorenz95::StateL95 xx(*fix.resol_, *fix.model_, *fix.file_);
     EXPECT(xx.validTime().toString() == fix.date_str_);
   }
 // -----------------------------------------------------------------------------
   SECTION("test_stateL95_assignment") {
     lorenz95::StateL95 xx1(*fix.resol_, *fix.model_, *fix.file_);
     // construct the second StateL95 object
     lorenz95::StateL95 xx2(*fix.resol_, *fix.model_, *fix.file_);
     xx2 = xx1;
     // initially, xx1 held data, xx2 was initialised to 0, now
     // ensure the two stateL95s are the same
     EXPECT(xx1.validTime() == xx2.validTime());
     EXPECT(xx1.getField().resol() == xx2.getField().resol());
     for (int i = 0; i < xx1.getField().resol(); ++i) {
       EXPECT(xx1.getField()[i] == xx2.getField()[i]);
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_stateL95_compound_assignment") {
     lorenz95::StateL95 xx(*fix.resol_, *fix.model_, *fix.file_);
     // construct the incrementL95 object
     lorenz95::IncrementL95 dx(*fix.resol_, *fix.vars_, *fix.time_);
     dx.read(*fix.file_);
     xx += dx;
     // both xx and dx were initialised with the same data,
     // so when the two are added together xx should be double incL95
     for (int i = 0; i < xx.getField().resol(); ++i) {
       EXPECT(xx.getField()[i] == 2.0 * dx.getField()[i]);
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_stateL95_read") {
     lorenz95::StateL95 xx(*fix.resol_, *fix.model_, *fix.file_);
     // to verify the information has been read correctly, we need to open
     // and read the file using ifstream functionality
     const std::string filename(fix.file_->getString("filename"));
     std::ifstream inStream(filename.c_str());
     if (!inStream.is_open()) {
       oops::Log::error() << "read functionality cannot be determined" << std::endl;
     }
     int resolInt;
     inStream >> resolInt;
     std::string time;
     inStream >> time;
     std::vector<double> doubleVec(resolInt);
     for (int i = 0; i < resolInt; ++i) {
       inStream >> doubleVec[i];
     }
     inStream.close();
     for (int i = 0; i < fix.resol_->npoints(); ++i) {
       EXPECT((xx.getField())[i] == doubleVec[i]);
     }
   }
 // -----------------------------------------------------------------------------
   SECTION("test_stateL95_timeUpdate") {
     lorenz95::StateL95 xx(*fix.resol_, *fix.model_, *fix.file_);
     util::Duration dur(10);
     util::DateTime updatedTime(*fix.time_);
     updatedTime += dur;
     std::string updated_date_string(updatedTime.toString());
     xx.validTime() += dur;
     EXPECT(xx.validTime().toString() == updated_date_string);
   }
 // -----------------------------------------------------------------------------
 /*
   SECTION("test_stateL95_stream_output") {
     lorenz95::StateL95 xx(*fix.resol_, *fix.vars_, *fix.time_);
     xx.read(*fix.file_);
     // use the operator<< method to write the value to a file
     std::filebuf fb;
     std::string filename("StateL95Test.txt");
     fb.open(filename.c_str(), std::ios::out);
     std::ostream os(&fb);
     os << xx;
     fb.close();
     std::vector<double> doubleVec(xx.getField().resol());
     for (int i = 0; i < xx.getField().resol(); ++i) {
       doubleVec[i] = xx.getField()[i];
     }
     std::vector<double>::iterator iter;
     iter = std::min_element(doubleVec.begin(), doubleVec.end());
     double min = *iter;
     iter = std::max_element(doubleVec.begin(), doubleVec.end());
     double max = *iter;
 //    double avg = 0.0;
     // then read the values that were written to the file
     int idxStart;
     int idxEnd;
     double inputDouble = 0.0;
     std::string input;
     std::string inputTest;
     std::string inputTimeTest(" Valid time: " + fix.file_->getString("date"));
     std::ifstream inputFile(filename.c_str());
     if (inputFile.is_open()) {
       getline(inputFile, input);  // ignore the first (blank) line
       getline(inputFile, input);
       EXPECT(input == inputTimeTest);
       getline(inputFile, input);
       // test min value
       idxStart = input.find("=");
       idxEnd = input.find(",");
       inputTest = input.substr(idxStart + 1, (idxEnd - 1) - idxStart);
       inputDouble = eckit::Translator<std::string, double>()(inputTest);
       EXPECT(oops::is_close(inputDouble, min, 0.0001));
       // test max value
       idxStart = input.find("=", idxEnd);
       idxEnd = input.find(",", idxEnd + 1);
       inputTest = input.substr(idxStart + 1, (idxEnd - 1) - idxStart);
       inputDouble = eckit::Translator<std::string, double>()(inputTest);
       EXPECT(oops::is_close(inputDouble, max, 0.0001));
       // test avg value
 //      idxStart = input.find("=", idxEnd + 1);
 //      idxEnd = input.find(",", idxEnd + 1);
 //      inputTest = input.substr(idxStart + 1);
 //      inputDouble = eckit::Translator<std::string, double>()(inputTest);
 //      EXPECT(oops::is_close(inputDouble, avg, 0.0001));
     } else {
       // if we can't open the file then we can't
       // verify that the value was correctly written
       oops::Log::error() << "operator<< functionality cannot be determined" << std::endl;
     }
     inputFile.close();
   }
 */
 // -----------------------------------------------------------------------------
 //  SECTION("test_stateL95_step_traj") {
 //    lorenz95::StateL95 xx(*fix.resol_, *fix.vars_, *fix.time_);
 //    xx.read(*fix.file_);
 //
 //    // construct a ModelL95 object
 //    eckit::LocalConfiguration modelCfg(TestConfig::config(), "model");
 //    lorenz95::ModelL95 modelL95(*fix.resol_, modelCfg);
 //
 //    // construct a ModelBias object
 //    eckit::LocalConfiguration biasCfg(TestConfig::config(), "ModelBias");
 //    lorenz95::ModelBias modelBias(*fix.resol_, biasCfg);
 //
 //    // construct a ModelTrajectory object
 //    lorenz95::ModelTrajectory modelTraj(true);
 //    // copy construct a FieldL95 object to set params
 //    // in the ModelTrajectory object
 //    lorenz95::FieldL95 fieldL95(xx.getField());
 //    modelTraj.set(fieldL95);
 //
 //    xx.stepTraj(modelL95, modelBias, modelTraj);
 //
 //    // create test data
 //    modelL95.stepRK(fieldL95, modelBias, modelTraj);
 //
 //    // test xx data against newly created fieldL95 test data
 //    for(int i = 0; i < xx.getField().resol(); ++i) {
 //      EXPECT(xx.getField()[i] == fieldL95[i]);
 //    }
 //  }
 // -----------------------------------------------------------------------------
 }  //  CASE
CASE() [17/17]
test::CASE ("test_tlmL95")
Definition at line 55 of file TLML95.cc.
                     {
   TlmTestFixture fix;
 // -----------------------------------------------------------------------------
   SECTION("test_tlmL95_constructor") {
     std::unique_ptr<lorenz95::TLML95> tlm(new lorenz95::TLML95(*fix.resol_, *fix.tlconf_));
     EXPECT(tlm.get() != NULL);
   }
 // -----------------------------------------------------------------------------
 /*
   SECTION("test_tlmL95_set_get_Trajectory") {
     lorenz95::TLML95 tlm(*fix.resol_, *fix.tlconf_, *fix.model_);
     // construct a StateL95 object
     std::string date_string("2014-09-12T09:35:00Z");
     util::DateTime dt(date_string);
     oops::Variables vars();
     std::unique_ptr<lorenz95::StateL95> stateL95(new lorenz95::StateL95(*fix.resol_, vars, dt));
     // construct a ModelBias object
     std::shared_ptr<const eckit::LocalConfiguration> biasCfg(new eckit::LocalConfiguration(TestConfig::config(), "ModelBias"));
     std::unique_ptr<lorenz95::ModelBias> modelBias(new lorenz95::ModelBias(*biasCfg, *fix.resol_));
     tlm.setTrajectory(*stateL95, *modelBias);
     std::unique_ptr<lorenz95::ModelTrajectory> modelTraj(new lorenz95::ModelTrajectory(true));
     oops::Log::error() << "PMC: getTraj result <" << tlm.getTrajectory(dt)->get(1) << ">" << std::endl;
     modelTraj->set(tlm.getTrajectory(dt)->get(1));
     //oops::Log::error() << "PMC: modelTraj 1st " << modelTraj->get(1)
     oops::Log::error() << "PMC: modelTraj resol  <" << modelTraj->get(1).resol() << ">" << std::endl;
     for(int i = 0; i < modelTraj->get(1).resol(); ++i) {
       oops::Log::error() << "PMC: modelTraj FieldL95 elements " << modelTraj->get(1)[i] << std::endl;
     }
   }
 */
 // -----------------------------------------------------------------------------
 /*
   SECTION("test_tlmL95_stepTL") {
     lorenz95::TLML95 tlm(*fix.resol_, *fix.tlconf_, *fix.model_);
     // construct a FieldL95 object
     std::unique_ptr<lorenz95::FieldL95> fieldL95(new lorenz95::FieldL95(*fix.resol_));
     // construct a datetime object
     std::string dateString("2014-10-08T11:25:45Z");
     util::DateTime dt(dateString);
     //construct a ModelBiasCorrection object
     std::unique_ptr<const eckit::LocalConfiguration> covarCfg(new eckit::LocalConfiguration(TestConfig::config(), "Covariance"));
     std::unique_ptr<lorenz95::ModelBiasCovariance> modelBiasCovariance(
         new lorenz95::ModelBiasCovariance(*covarCfg, *fix.resol_));
     std::unique_ptr<lorenz95::ModelBiasCorrection> modelBiasCorrection(
         new lorenz95::ModelBiasCorrection(*modelBiasCovariance));
     tlm.stepTL(*fieldL95, dt, *modelBiasCorrection);
     oops::Log::error() << "PMC: original dt was " << dateString << std::endl;
     oops::Log::error() << "PMC: modified dt is  " << dt.toString() << std::endl;
   }
 // -----------------------------------------------------------------------------
   SECTION("test_tlmL95_stepAD") {
   }
 */
 // -----------------------------------------------------------------------------
   SECTION("test_tlmL95_get_classname") {
     lorenz95::TLML95 tlm(*fix.resol_, *fix.tlconf_);
     EXPECT(tlm.classname() == "lorenz95::TLML95");
   }
 // -----------------------------------------------------------------------------
   SECTION("test_tlmL95_get_timestep") {
     lorenz95::TLML95 tlm(*fix.resol_, *fix.tlconf_);
     util::Duration dt(fix.tlconf_->getString("tstep"));
     EXPECT(tlm.timeResolution().toSeconds() == dt.toSeconds());
   }
 // -----------------------------------------------------------------------------
   SECTION("test_tlmL95_get_resolution") {
     eckit::LocalConfiguration rescf(TestConfig::config(), "resolution");
     lorenz95::Resolution resol(rescf);
     lorenz95::TLML95 tlm(*fix.resol_, *fix.tlconf_);
     EXPECT(tlm.resolution().npoints() == resol.npoints());
   }
 // -----------------------------------------------------------------------------
   SECTION("test_tlmL95_stream_output") {
     lorenz95::TLML95 tlm(*fix.resol_, *fix.tlconf_);
     // use the operator<< method to write the value to a file
     std::filebuf fb;
     std::string filename("TLML95Test.txt");
     fb.open(filename.c_str(), std::ios::out);
     std::ostream os(&fb);
     os << tlm;
     fb.close();
     // then read the value that was written to the file
     std::string inputString;
     std::string inputStartsWith;
     std::string testString("TLML95: resol = ");
     int endPos = testString.size();
     std::ifstream inputFile(filename.c_str());
     if (inputFile.is_open()) {
       getline(inputFile, inputString);
       inputStartsWith = inputString.substr(0, endPos);
       EXPECT(inputStartsWith == testString);
     } else {
       // if we can't open the file then we can't
       // verify that the value was correctly written
       oops::Log::error() <<"operator<< functionality cannot be determined" << std::endl;
     }
     inputFile.close();
   }
 // -----------------------------------------------------------------------------
 }  //  CASE
test_normal_real_f()
std::int32_t test::test_normal_real_f (const eckit::Configuration *const *)
test_uniform_int_f()
std::int32_t test::test_uniform_int_f (const eckit::Configuration *const *)
test_uniform_real_f()
std::int32_t test::test_uniform_real_f (const eckit::Configuration *const *)
This is intended as a general interface for testing objects in the util namespace from Fortran
testChangeRes()
template<typename MODEL > void test::testChangeRes ()
Definition at line 108 of file ModelAuxControl.h.
                      {
   using Test_ = ModelAuxControlFixture<MODEL>;
   using ModelAux_ = oops::ModelAuxControl<MODEL>;
   std::unique_ptr<ModelAux_> bias(
       new ModelAux_(Test_::resol(), Test_::model(), Test_::config()));
   std::unique_ptr<ModelAux_> other(new ModelAux_(Test_::resol(), *bias));
   EXPECT(other.get());
   other.reset();
   EXPECT(!other.get());
   EXPECT(bias.get());
 }
testConstructor()
template<typename MODEL > void test::testConstructor ()
Definition at line 57 of file Geometry.h.
{
   using Geometry_ = oops::Geometry<MODEL>;
   std::unique_ptr<Geometry_> geom(
       new Geometry_(GeometryFixture<MODEL>::getConfig()));
   EXPECT(geom.get());
   geom.reset();
   EXPECT(!geom.get());
 }
testConstructors()
template<typename MODEL > void test::testConstructors ()
Definition at line 80 of file Locations.h.
{
   using Locations_ = oops::Locations<MODEL>;
   std::unique_ptr<Locations_> locs(new Locations_(
       LocationsFixture<MODEL>::getObSpace(), LocationsFixture<MODEL>::gett1(),
       LocationsFixture<MODEL>::gett2()));
   EXPECT(locs.get());
   locs.reset();
   EXPECT(!locs.get());
 }
testCopyConstructor()
template<typename MODEL > void test::testCopyConstructor ()
Definition at line 71 of file Geometry.h.
{
   using Geometry_ = oops::Geometry<MODEL>;
   std::unique_ptr<Geometry_> geom(
       new Geometry_(GeometryFixture<MODEL>::getConfig()));
   std::unique_ptr<Geometry_> other(new Geometry_(*geom));
   EXPECT(other.get());
   other.reset();
   EXPECT(!other.get());
   EXPECT(geom.get());
 }
testErrorCovarianceInverse()
template<typename MODEL > void test::testErrorCovarianceInverse ()
Definition at line 143 of file ErrorCovariance.h.
{
   using Test_ = ErrorCovarianceFixture<MODEL>;
   using Increment_ = oops::Increment<MODEL>;
   const bool testinverse = Test_::test().getBool("testinverse", true);
   if (testinverse) {
     Increment_ dx1(Test_::resol(), Test_::ctlvars(), Test_::time());
     Increment_ dx2(Test_::resol(), Test_::ctlvars(), Test_::time());
     Increment_ dx3(Test_::resol(), Test_::ctlvars(), Test_::time());
     Test_::covariance().randomize(dx1);
     EXPECT(dx1.norm() > 0.0);
     Test_::covariance().multiply(dx1, dx2);
     Test_::covariance().inverseMultiply(dx2, dx3);
     EXPECT(dx2.norm() > 0.0);
     EXPECT(dx3.norm() > 0.0);
     dx3 -= dx1;
     const double tol = Test_::test().getDouble("tolerance");
     EXPECT(dx3.norm() / dx1.norm() < tol);
   } else {
     return;
   }
 }
testErrorCovarianceSym()
template<typename MODEL > void test::testErrorCovarianceSym ()
Definition at line 171 of file ErrorCovariance.h.
{
   using Test_ = ErrorCovarianceFixture<MODEL>;
   using Increment_ = oops::Increment<MODEL>;
   Increment_ dx(Test_::resol(), Test_::ctlvars(), Test_::time());
   Increment_ Bdx(Test_::resol(), Test_::ctlvars(), Test_::time());
   Increment_ dy(Test_::resol(), Test_::ctlvars(), Test_::time());
   Increment_ Bdy(Test_::resol(), Test_::ctlvars(), Test_::time());
   dx.random();
   dy.random();
   Test_::covariance().multiply(dx, Bdx);
   Test_::covariance().multiply(dy, Bdy);
   const double zz1 = dot_product(dx, Bdy);
   const double zz2 = dot_product(Bdx, dy);
   oops::Log::info() << "<dx,Bdy>-<Bdx,dy>/<dx,Bdy>=" << (zz1 - zz2) / zz1
                     << std::endl;
   oops::Log::info() << "<dx,Bdy>-<Bdx,dy>/<Bdx,dy>=" << (zz1 - zz2) / zz2
                     << std::endl;
   const double tol = Test_::test().getDouble("tolerance");
   EXPECT(oops::is_close(zz1, zz2, tol));
 }
References dot_product(), and oops::is_close().
testErrorCovarianceZero()
template<typename MODEL > void test::testErrorCovarianceZero ()
Definition at line 110 of file ErrorCovariance.h.
{
   using Test_ = ErrorCovarianceFixture<MODEL>;
   using Increment_ = oops::Increment<MODEL>;
   Increment_ dx1(Test_::resol(), Test_::ctlvars(), Test_::time());
   Increment_ dx2(Test_::resol(), Test_::ctlvars(), Test_::time());
   Test_::covariance().randomize(dx2);
   oops::Log::info() << "dx2.norm()=" << dx2.norm() << std::endl;
   EXPECT(dx1.norm() == 0.0);
   EXPECT(dx2.norm() > 0.0);
   Test_::covariance().multiply(dx1, dx2);
   EXPECT(dx2.norm() == 0.0);
   const bool testinverse = Test_::test().getBool("testinverse", true);
   if (testinverse) {
     oops::Log::info() << "Doing zero test for inverse" << std::endl;
     dx1.zero();
     Test_::covariance().randomize(dx2);
     EXPECT(dx1.norm() == 0.0);
     EXPECT(dx2.norm() > 0.0);
     Test_::covariance().inverseMultiply(dx1, dx2);
     EXPECT(dx2.norm() == 0.0);
   } else {
     oops::Log::info() << "Not doing zero test for inverse" << std::endl;
   }
 }
testIncrementAxpy()
template<typename MODEL > void test::testIncrementAxpy ()
Definition at line 204 of file Increment.h.
{
   using Test_ = IncrementFixture<MODEL>;
   using Increment_ = oops::Increment<MODEL>;
   Increment_ dx1(Test_::resol(), Test_::ctlvars(), Test_::time());
   dx1.random();
   // test axpy
   Increment_ dx2(dx1);
   dx2.axpy(2.0, dx1);
   dx2 -= dx1;
   dx2 -= dx1;
   dx2 -= dx1;
   EXPECT(dx2.norm() < 1e-8);
 }
testIncrementConstructor()
template<typename MODEL > void test::testIncrementConstructor ()
Definition at line 93 of file Increment.h.
{
   using Test_ = IncrementFixture<MODEL>;
   using Increment_ = oops::Increment<MODEL>;
   Increment_ dx(Test_::resol(), Test_::ctlvars(), Test_::time());
   EXPECT(dx.norm() == 0.0);
 }
testIncrementCopyConstructor()
template<typename MODEL > void test::testIncrementCopyConstructor ()
Definition at line 105 of file Increment.h.
{
   using Test_ = IncrementFixture<MODEL>;
   using Increment_ = oops::Increment<MODEL>;
   Increment_ dx1(Test_::resol(), Test_::ctlvars(), Test_::time());
   dx1.random();
   EXPECT(dx1.norm() > 0.0);
   Increment_ dx2(dx1);
   EXPECT(dx2.norm() > 0.0);
   // Check that the copy is equal to the original
   dx2 -= dx1;
   EXPECT(dx2.norm() == 0.0);
 }
testIncrementDotProduct()
template<typename MODEL > void test::testIncrementDotProduct ()
Definition at line 169 of file Increment.h.
{
   using Test_ = IncrementFixture<MODEL>;
   using Increment_ = oops::Increment<MODEL>;
   Increment_ dx1(Test_::resol(), Test_::ctlvars(), Test_::time());
   dx1.random();
   Increment_ dx2(Test_::resol(), Test_::ctlvars(), Test_::time());
   dx2.random();
   // test symmetry of dot product
   double zz1 = dot_product(dx1, dx2);
   double zz2 = dot_product(dx2, dx1);
   EXPECT(zz1 == zz2);
 }
References dot_product().
testIncrementOpPlusEq()
template<typename MODEL > void test::testIncrementOpPlusEq ()
Definition at line 150 of file Increment.h.
{
   using Test_ = IncrementFixture<MODEL>;
   using Increment_ = oops::Increment<MODEL>;
   Increment_ dx1(Test_::resol(), Test_::ctlvars(), Test_::time());
   dx1.random();
   Increment_ dx2(dx1);
   // test *= and +=
   dx2 += dx1;
   dx1 *= 2.0;
   dx2 -= dx1;
   EXPECT(dx2.norm() < 1e-8);
 }
testIncrementTriangle()
template<typename MODEL > void test::testIncrementTriangle ()
Definition at line 124 of file Increment.h.
{
   using Test_ = IncrementFixture<MODEL>;
   using Increment_ = oops::Increment<MODEL>;
   Increment_ dx1(Test_::resol(), Test_::ctlvars(), Test_::time());
   dx1.random();
   Increment_ dx2(Test_::resol(), Test_::ctlvars(), Test_::time());
   dx2.random();
   // test triangle inequality
   double dot1 = dx1.norm();
   EXPECT(dot1 > 0.0);
   double dot2 = dx2.norm();
   EXPECT(dot2 > 0.0);
   dx2 += dx1;
   double dot3 = dx2.norm();
   EXPECT(dot3 > 0.0);
   EXPECT(dot3 <= dot1 + dot2);
 }
testIncrementZero()
template<typename MODEL > void test::testIncrementZero ()
Definition at line 188 of file Increment.h.
{
   using Test_ = IncrementFixture<MODEL>;
   using Increment_ = oops::Increment<MODEL>;
   Increment_ dx(Test_::resol(), Test_::ctlvars(), Test_::time());
   dx.random();
   EXPECT(dx.norm() > 0.0);
   // test zero
   dx->zero();
   EXPECT(dx.norm() == 0.0);
 }
testLinearApproximation()
template<typename MODEL > void test::testLinearApproximation ()
Definition at line 268 of file LinearModel.h.
{
   using Test_ = LinearModelFixture<MODEL>;
   using Increment_ = oops::Increment<MODEL>;
   using State_ = oops::State<MODEL>;
   const util::Duration len(Test_::test().getString("fclength"));
   const util::DateTime t1(Test_::time());
   const util::DateTime t2(t1 + len);
   EXPECT(t2 > t1);
   Increment_ dx0(Test_::resol(), Test_::ctlvars(), t1);
   Test_::covariance().randomize(dx0);
   EXPECT(dx0.norm() > 0.0);
   Increment_ dx(dx0);
   Test_::tlm().forecastTL(dx, Test_::dbias(), len);
   const double dxnorm = dx.norm();
   oops::PostProcessor<State_> post;
   State_ xx0(Test_::xref());
   Test_::model().forecast(xx0, Test_::bias(), len, post);
   const unsigned int ntest = Test_::test().getInt("testiterTL");
   double zz = 1.0;
   std::vector<double> errors;
   for (unsigned int jtest = 0; jtest < ntest; ++jtest) {
     State_ xx(Test_::xref());
     Increment_ pert(dx0);
     pert *= zz;
     xx += pert;
     Test_::model().forecast(xx, Test_::bias(), len, post);
     Increment_ diff(Test_::resol(), Test_::ctlvars(), t2);
     diff.diff(xx, xx0);
     const double difnorm = diff.norm();
     const double err = zz * dxnorm / difnorm;
     Increment_ derr(dx);
     derr *= zz;
     derr -= diff;
     const double errnorm = derr.norm();
     errors.push_back(errnorm / difnorm);
     Log::test() << "TL error = " << std::setprecision(16) << err
                 << ", relative error = " << errnorm / difnorm << std::endl;
     zz /= 10.0;
   }
   // Analyze results
   const double approx = *std::min_element(errors.begin(), errors.end());
   Log::test() << "Test TL min error = " << approx << std::endl;
   const double tol = Test_::test().getDouble("toleranceTL");
   EXPECT(approx < tol);
 }
testLinearModelAdjoint()
template<typename MODEL > void test::testLinearModelAdjoint ()
Definition at line 324 of file LinearModel.h.
{
   using Test_ = LinearModelFixture<MODEL>;
   using Increment_ = oops::Increment<MODEL>;
   using ModelAuxIncr_ = oops::ModelAuxIncrement<MODEL>;
   const util::Duration len(Test_::test().getString("fclength"));
   const util::DateTime t1(Test_::time());
   const util::DateTime t2(t1 + len);
   EXPECT(t2 > t1);
   Increment_ dx11(Test_::resol(), Test_::ctlvars(), t1);
   Test_::covariance().randomize(dx11);
   ModelAuxIncr_ daux1(Test_::dbias());
   EXPECT(dx11.norm() > 0.0);
   Increment_ dx12(dx11);
   Test_::tlm().forecastTL(dx12, daux1, len);
   EXPECT(dx12.norm() > 0.0);
   Increment_ dx22(Test_::resol(), Test_::ctlvars(), t2);
   Test_::covariance().randomize(dx22);
   ModelAuxIncr_ daux2(Test_::dbias());
   EXPECT(dx22.norm() > 0.0);
   Increment_ dx21(dx22);
   Test_::tlm().forecastAD(dx21, daux2, len);
   EXPECT(dx21.norm() > 0.0);
   EXPECT(dx11.norm() != dx22.norm());
   EXPECT(dx11.validTime() == t1);
   EXPECT(dx21.validTime() == t1);
   EXPECT(dx12.validTime() == t2);
   EXPECT(dx22.validTime() == t2);
   const double dot1 = dot_product(dx11, dx21);
   const double dot2 = dot_product(dx12, dx22);
   const double tol = Test_::test().getDouble("toleranceAD");
   EXPECT(oops::is_close(dot1, dot2, tol));
 }
References dot_product(), and oops::is_close().
testLinearModelConstructor()
template<typename MODEL > void test::testLinearModelConstructor ()
Definition at line 158 of file LinearModel.h.
{
   using Test_ = LinearModelFixture<MODEL>;
   const util::Duration zero(0);
   EXPECT(Test_::tlm().timeResolution() > zero);
 }
testLinearModelLinearity()
template<typename MODEL > void test::testLinearModelLinearity ()
Definition at line 232 of file LinearModel.h.
{
   using Test_ = LinearModelFixture<MODEL>;
   using Increment_ = oops::Increment<MODEL>;
   using ModelAuxIncr_ = oops::ModelAuxIncrement<MODEL>;
   const util::Duration len(Test_::test().getString("fclength"));
   const util::DateTime t1(Test_::time());
   const util::DateTime t2(t1 + len);
   EXPECT(t2 > t1);
   const double zz = 3.1415;
   Increment_ dx1(Test_::resol(), Test_::ctlvars(), t1);
   Test_::covariance().randomize(dx1);
   ModelAuxIncr_ daux1(Test_::dbias());
   EXPECT(dx1.norm() > 0.0);
   Increment_ dx2(dx1);
   ModelAuxIncr_ daux2(daux1);
   Test_::tlm().forecastTL(dx1, daux1, len);
   EXPECT(dx1.validTime() == t2);
   dx1 *= zz;
   daux1 *= zz;
   dx2 *= zz;
   daux2 *= zz;
   Test_::tlm().forecastTL(dx2, daux2, len);
   EXPECT(dx2.validTime() == t2);
   const double tol = Test_::test().getDouble("toleranceAD");
   EXPECT(oops::is_close(dx1.norm(), dx2.norm(), tol));
 }
References oops::is_close().
testLinearModelZeroLength()
template<typename MODEL > void test::testLinearModelZeroLength ()
Definition at line 168 of file LinearModel.h.
{
   using Test_ = LinearModelFixture<MODEL>;
   using Increment_ = oops::Increment<MODEL>;
   using ModelAuxIncr_ = oops::ModelAuxIncrement<MODEL>;
   const util::DateTime vt(Test_::time());
   const util::Duration zero(0);
   Increment_ dxref(Test_::resol(), Test_::ctlvars(), vt);
   Test_::covariance().randomize(dxref);
   ModelAuxIncr_ daux(Test_::dbias());
   const double ininorm = dxref.norm();
   EXPECT(ininorm > 0.0);
   Increment_ dx(Test_::resol(), Test_::ctlvars(), vt);
   Increment_ dxm(Test_::resol(), Test_::ctlvars(), vt);
   dxm = dxref;
   Test_::tlm().forecastTL(dxm, daux, zero);
   dx = dxm;
   EXPECT(dx.validTime() == vt);
   EXPECT(dx.norm() == ininorm);
   dxm.zero();
   dxm = dxref;
   Test_::tlm().forecastAD(dxm, daux, zero);
   dx = dxm;
   EXPECT(dx.validTime() == vt);
   EXPECT(dx.norm() == ininorm);
 }
testLinearModelZeroPert()
template<typename MODEL > void test::testLinearModelZeroPert ()
Definition at line 201 of file LinearModel.h.
{
   using Test_ = LinearModelFixture<MODEL>;
   using Increment_ = oops::Increment<MODEL>;
   using ModelAuxIncr_ = oops::ModelAuxIncrement<MODEL>;
   const util::Duration len(Test_::test().getString("fclength"));
   const util::DateTime t1(Test_::time());
   const util::DateTime t2(t1 + len);
   EXPECT(t2 > t1);
   Increment_ dx(Test_::resol(), Test_::ctlvars(), t1);
   ModelAuxIncr_ daux(Test_::dbias());
   dx.zero();
   daux.zero();
   EXPECT(dx.norm() == 0.0);
   Test_::tlm().forecastTL(dx, daux, len);
   EXPECT(dx.validTime() == t2);
   EXPECT(dx.norm() == 0.0);
   dx.zero();
   daux.zero();
   EXPECT(dx.norm() == 0.0);
   Test_::tlm().forecastAD(dx, daux, len);
   EXPECT(dx.validTime() == t1);
   EXPECT(dx.norm() == 0.0);
 }
testLocalizationMultiply()
template<typename MODEL > void test::testLocalizationMultiply ()
Definition at line 102 of file Localization.h.
{
   using Test_ = LocalizationFixture<MODEL>;
   using Increment_ = oops::Increment<MODEL>;
   Increment_ dx(Test_::resol(), Test_::ctlvars(), Test_::time());
   dx.random();
   EXPECT(dx.norm() > 0.0);
   Test_::localization().multiply(dx);
   EXPECT(dx.norm() > 0.0);
 }
testLocalizationZero()
template<typename MODEL > void test::testLocalizationZero ()
Definition at line 88 of file Localization.h.
{
   using Test_ = LocalizationFixture<MODEL>;
   using Increment_ = oops::Increment<MODEL>;
   Increment_ dx(Test_::resol(), Test_::ctlvars(), Test_::time());
   EXPECT(dx.norm() == 0.0);
   Test_::localization().multiply(dx);
   EXPECT(dx.norm() == 0.0);
 }
testModelAuxIncrementAxpy()
template<typename MODEL > void test::testModelAuxIncrementAxpy ()
Definition at line 211 of file ModelAuxIncrement.h.
{
   using Test_ = ModelAuxIncrementFixture<MODEL>;
   using AuxIncr_ = oops::ModelAuxIncrement<MODEL>;
   AuxIncr_ dx1(Test_::resol(), Test_::config());
   ModelAuxIncrementFixture<MODEL>::covariance().randomize(dx1);
   // test axpy
   AuxIncr_ dx2(dx1);
   dx2.axpy(2.0, dx1);
   dx2 -= dx1;
   dx2 -= dx1;
   dx2 -= dx1;
   EXPECT(dx2.norm() < 1e-8);
 }
testModelAuxIncrementChangeRes()
template<typename MODEL > void test::testModelAuxIncrementChangeRes ()
Definition at line 112 of file ModelAuxIncrement.h.
{
   using Test_ = ModelAuxIncrementFixture<MODEL>;
   using AuxIncr_ = oops::ModelAuxIncrement<MODEL>;
   AuxIncr_ dx1(Test_::resol(), Test_::config());
   ModelAuxIncrementFixture<MODEL>::covariance().randomize(dx1);
   AuxIncr_ dx2(dx1, Test_::config());
   EXPECT(dx2.norm() > 0.0);
   EXPECT(dx2.norm() == dx1.norm());
   // Check that the copy is equal to the original
   dx2 -= dx1;
   EXPECT(dx2.norm() == 0.0);
 }
testModelAuxIncrementConstructor()
template<typename MODEL > void test::testModelAuxIncrementConstructor ()
Definition at line 81 of file ModelAuxIncrement.h.
{
   using Test_ = ModelAuxIncrementFixture<MODEL>;
   using AuxIncr_ = oops::ModelAuxIncrement<MODEL>;
   AuxIncr_ dx(Test_::resol(), Test_::config());
   EXPECT(dx.norm() == 0.0);
 }
testModelAuxIncrementCopyConstructor()
template<typename MODEL > void test::testModelAuxIncrementCopyConstructor ()
Definition at line 93 of file ModelAuxIncrement.h.
{
   using Test_ = ModelAuxIncrementFixture<MODEL>;
   using AuxIncr_ = oops::ModelAuxIncrement<MODEL>;
   AuxIncr_ dx1(Test_::resol(), Test_::config());
   ModelAuxIncrementFixture<MODEL>::covariance().randomize(dx1);
   AuxIncr_ dx2(dx1);
   EXPECT(dx2.norm() > 0.0);
   EXPECT(dx2.norm() == dx1.norm());
   // Check that the copy is equal to the original
   dx2 -= dx1;
   EXPECT(dx2.norm() == 0.0);
 }
testModelAuxIncrementDotProduct()
template<typename MODEL > void test::testModelAuxIncrementDotProduct ()
Definition at line 176 of file ModelAuxIncrement.h.
{
   using Test_ = ModelAuxIncrementFixture<MODEL>;
   using AuxIncr_ = oops::ModelAuxIncrement<MODEL>;
   AuxIncr_ dx1(Test_::resol(), Test_::config());
   ModelAuxIncrementFixture<MODEL>::covariance().randomize(dx1);
   AuxIncr_ dx2(Test_::resol(), Test_::config());
   ModelAuxIncrementFixture<MODEL>::covariance().randomize(dx2);
   // test symmetry of dot product
   double zz1 = dot_product(dx1, dx2);
   double zz2 = dot_product(dx2, dx1);
   EXPECT(zz1 == zz2);
 }
References dot_product().
testModelAuxIncrementOpPlusEq()
template<typename MODEL > void test::testModelAuxIncrementOpPlusEq ()
Definition at line 157 of file ModelAuxIncrement.h.
{
   using Test_ = ModelAuxIncrementFixture<MODEL>;
   using AuxIncr_ = oops::ModelAuxIncrement<MODEL>;
   AuxIncr_ dx1(Test_::resol(), Test_::config());
   ModelAuxIncrementFixture<MODEL>::covariance().randomize(dx1);
   AuxIncr_ dx2(dx1);
   // test *= and +=
   dx2 += dx1;
   dx1 *= 2.0;
   dx2 -= dx1;
   EXPECT(dx2.norm() < 1e-8);
 }
testModelAuxIncrementTriangle()
template<typename MODEL > void test::testModelAuxIncrementTriangle ()
Definition at line 131 of file ModelAuxIncrement.h.
{
   using Test_ = ModelAuxIncrementFixture<MODEL>;
   using AuxIncr_ = oops::ModelAuxIncrement<MODEL>;
   AuxIncr_ dx1(Test_::resol(), Test_::config());
   ModelAuxIncrementFixture<MODEL>::covariance().randomize(dx1);
   AuxIncr_ dx2(Test_::resol(), Test_::config());
   ModelAuxIncrementFixture<MODEL>::covariance().randomize(dx2);
   // test triangle inequality
   double dot1 = dx1.norm();
   EXPECT(dot1 > 0.0);
   double dot2 = dx2.norm();
   EXPECT(dot2 > 0.0);
   dx2 += dx1;
   double dot3 = dx2.norm();
   EXPECT(dot3 > 0.0);
   EXPECT(dot3 <= dot1 + dot2);
 }
testModelAuxIncrementZero()
template<typename MODEL > void test::testModelAuxIncrementZero ()
Definition at line 195 of file ModelAuxIncrement.h.
{
   using Test_ = ModelAuxIncrementFixture<MODEL>;
   using AuxIncr_ = oops::ModelAuxIncrement<MODEL>;
   AuxIncr_ dx(Test_::resol(), Test_::config());
   ModelAuxIncrementFixture<MODEL>::covariance().randomize(dx);
   EXPECT(dx.norm() > 0.0);
   // test zero
   dx->zero();
   EXPECT(dx.norm() == 0.0);
 }
testModelConstructor()
template<typename MODEL > void test::testModelConstructor ()
Definition at line 94 of file Model.h.
{
   using Test_ = ModelFixture<MODEL>;
   const util::Duration zero(0);
   EXPECT(Test_::model().timeResolution() > zero);
 }
testModelForecast()
template<typename MODEL > void test::testModelForecast ()
Definition at line 127 of file Model.h.
{
   using Test_ = ModelFixture<MODEL>;
   using State_ = oops::State<MODEL>;
   const double fnorm = Test_::test().getDouble("finalnorm");
   const double tol = Test_::test().getDouble("tolerance");
   const util::Duration len(Test_::test().getString("fclength"));
   const double ininorm = Test_::xref().norm();
   State_ xx(Test_::xref());
   const util::DateTime vt(xx.validTime() + len);
   oops::PostProcessor<State_> post;
   Test_::model().forecast(xx, Test_::bias(), len, post);
   EXPECT(xx.validTime() == vt);
   EXPECT(oops::is_close(xx.norm(), fnorm, tol));
   // Recomputing initial norm to make sure nothing bad happened
   EXPECT(Test_::xref().norm() == ininorm);
 }
References oops::is_close().
testModelNoForecast()
template<typename MODEL > void test::testModelNoForecast ()
Definition at line 104 of file Model.h.
{
   using Test_ = ModelFixture<MODEL>;
   using State_ = oops::State<MODEL>;
   const double ininorm = Test_::xref().norm();
   State_ xx(Test_::xref());
   const util::DateTime vt(xx.validTime());
   const util::Duration zero(0);
   oops::PostProcessor<State_> post;
   Test_::model().forecast(xx, Test_::bias(), zero, post);
   EXPECT(xx.validTime() == vt);
   EXPECT(xx.norm() == ininorm);
   // Recomputing initial norm to make sure nothing bad happened
   EXPECT(Test_::xref().norm() == ininorm);
 }
References oops::State< MODEL >::norm().
testObsAuxIncrementAxpy()
template<typename MODEL > void test::testObsAuxIncrementAxpy ()
Definition at line 220 of file ObsAuxIncrement.h.
{
   using Test_ = ObsAuxIncrementFixture<MODEL>;
   using AuxIncr_ = oops::ObsAuxIncrement<MODEL>;
   AuxIncr_ dx1(Test_::obspace(), Test_::config());
   ObsAuxIncrementFixture<MODEL>::covariance().randomize(dx1);
   // test axpy
   AuxIncr_ dx2(dx1);
   dx2.axpy(2.0, dx1);
   dx2 -= dx1;
   dx2 -= dx1;
   dx2 -= dx1;
   EXPECT(dx2.norm() < 1e-8);
 }
testObsAuxIncrementChangeRes()
template<typename MODEL > void test::testObsAuxIncrementChangeRes ()
Definition at line 121 of file ObsAuxIncrement.h.
{
   using Test_ = ObsAuxIncrementFixture<MODEL>;
   using AuxIncr_ = oops::ObsAuxIncrement<MODEL>;
   AuxIncr_ dx1(Test_::obspace(), Test_::config());
   ObsAuxIncrementFixture<MODEL>::covariance().randomize(dx1);
   AuxIncr_ dx2(dx1, Test_::config());
   EXPECT(dx2.norm() > 0.0);
   EXPECT(dx2.norm() == dx1.norm());
   // Check that the copy is equal to the original
   dx2 -= dx1;
   EXPECT(dx2.norm() == 0.0);
 }
testObsAuxIncrementConstructor()
template<typename MODEL > void test::testObsAuxIncrementConstructor ()
Definition at line 90 of file ObsAuxIncrement.h.
{
   using Test_ = ObsAuxIncrementFixture<MODEL>;
   using AuxIncr_ = oops::ObsAuxIncrement<MODEL>;
   AuxIncr_ dx(Test_::obspace(), Test_::config());
   EXPECT(dx.norm() == 0.0);
 }
testObsAuxIncrementCopyConstructor()
template<typename MODEL > void test::testObsAuxIncrementCopyConstructor ()
Definition at line 102 of file ObsAuxIncrement.h.
{
   using Test_ = ObsAuxIncrementFixture<MODEL>;
   using AuxIncr_ = oops::ObsAuxIncrement<MODEL>;
   AuxIncr_ dx1(Test_::obspace(), Test_::config());
   ObsAuxIncrementFixture<MODEL>::covariance().randomize(dx1);
   AuxIncr_ dx2(dx1);
   EXPECT(dx2.norm() > 0.0);
   EXPECT(dx2.norm() == dx1.norm());
   // Check that the copy is equal to the original
   dx2 -= dx1;
   EXPECT(dx2.norm() == 0.0);
 }
testObsAuxIncrementDotProduct()
template<typename MODEL > void test::testObsAuxIncrementDotProduct ()
Definition at line 185 of file ObsAuxIncrement.h.
{
   using Test_ = ObsAuxIncrementFixture<MODEL>;
   using AuxIncr_ = oops::ObsAuxIncrement<MODEL>;
   AuxIncr_ dx1(Test_::obspace(), Test_::config());
   ObsAuxIncrementFixture<MODEL>::covariance().randomize(dx1);
   AuxIncr_ dx2(Test_::obspace(), Test_::config());
   ObsAuxIncrementFixture<MODEL>::covariance().randomize(dx2);
   // test symmetry of dot product
   double zz1 = dot_product(dx1, dx2);
   double zz2 = dot_product(dx2, dx1);
   EXPECT(zz1 == zz2);
 }
References dot_product().
testObsAuxIncrementOpPlusEq()
template<typename MODEL > void test::testObsAuxIncrementOpPlusEq ()
Definition at line 166 of file ObsAuxIncrement.h.
{
   using Test_ = ObsAuxIncrementFixture<MODEL>;
   using AuxIncr_ = oops::ObsAuxIncrement<MODEL>;
   AuxIncr_ dx1(Test_::obspace(), Test_::config());
   ObsAuxIncrementFixture<MODEL>::covariance().randomize(dx1);
   AuxIncr_ dx2(dx1);
   // test *= and +=
   dx2 += dx1;
   dx1 *= 2.0;
   dx2 -= dx1;
   EXPECT(dx2.norm() < 1e-8);
 }
testObsAuxIncrementTriangle()
template<typename MODEL > void test::testObsAuxIncrementTriangle ()
Definition at line 140 of file ObsAuxIncrement.h.
{
   using Test_ = ObsAuxIncrementFixture<MODEL>;
   using AuxIncr_ = oops::ObsAuxIncrement<MODEL>;
   AuxIncr_ dx1(Test_::obspace(), Test_::config());
   ObsAuxIncrementFixture<MODEL>::covariance().randomize(dx1);
   AuxIncr_ dx2(Test_::obspace(), Test_::config());
   ObsAuxIncrementFixture<MODEL>::covariance().randomize(dx2);
   // test triangle inequality
   double dot1 = dx1.norm();
   EXPECT(dot1 > 0.0);
   double dot2 = dx2.norm();
   EXPECT(dot2 > 0.0);
   dx2 += dx1;
   double dot3 = dx2.norm();
   EXPECT(dot3 > 0.0);
   EXPECT(dot3 <= dot1 + dot2);
 }
testObsAuxIncrementZero()
template<typename MODEL > void test::testObsAuxIncrementZero ()
Definition at line 204 of file ObsAuxIncrement.h.
{
   using Test_ = ObsAuxIncrementFixture<MODEL>;
   using AuxIncr_ = oops::ObsAuxIncrement<MODEL>;
   AuxIncr_ dx(Test_::obspace(), Test_::config());
   ObsAuxIncrementFixture<MODEL>::covariance().randomize(dx);
   EXPECT(dx.norm() > 0.0);
   // test zero
   dx->zero();
   EXPECT(dx.norm() == 0.0);
 }
testStateConstructor()
template<typename MODEL > void test::testStateConstructor ()
Definition at line 96 of file State.h.
{
   using Test_ = StateFixture<MODEL>;
   EXPECT(Test_::xref().norm() == Test_::norm());
   double norm = Test_::test().getDouble("norm");
   double tol = Test_::test().getDouble("tolerance");
   EXPECT(std::abs(Test_::xref().norm() - norm) < tol);
   const util::DateTime vt(Test_::test().getString("date"));
   EXPECT(Test_::xref().validTime() == vt);
 }
testStateCopyConstructor()
template<typename MODEL > void test::testStateCopyConstructor ()
Definition at line 112 of file State.h.
{
   using Test_ = StateFixture<MODEL>;
   using State_ = oops::State<MODEL>;
   std::unique_ptr<State_> xx(new State_(Test_::xref()));
   EXPECT(xx.get());
   EXPECT(xx->norm() == Test_::norm());
   const util::DateTime vt(Test_::test().getString("date"));
   EXPECT(xx->validTime() == vt);
   xx.reset();
   EXPECT(!xx.get());
   // Recomputing initial norm to make sure nothing bad happened
   EXPECT(Test_::xref().norm() == Test_::norm());
 }