OOPS Documentation: oops::DRPCGMinimizer< MODEL > Class Template Reference
oops::DRPCGMinimizer< MODEL > Class Template Reference
DRPCG Minimizer.
#include <DRPCGMinimizer.h>
Public Member Functions
const std::string classname () const override
DRPCGMinimizer (const eckit::Configuration &, const CostFct_ &)
~DRPCGMinimizer ()
Public Member Functions inherited from oops::DRMinimizer< MODEL >
DRMinimizer (const CostFct_ &J)
~DRMinimizer ()
void checkpoint (eckit::LocalConfiguration &) const
Checkpointing, restart.
void restart (const eckit::Configuration &)
Restart the minimizer (virtual method)
void warmStart (const eckit::Configuration &)
Warm start the minimizer (virtual method)
Public Member Functions inherited from oops::Minimizer< MODEL >
Minimizer (const CostFct_ &J)
Construct a minimizer.
virtual ~Minimizer ()
Destroy a minimizer.
ControlIncrement< MODEL > * minimize (const eckit::Configuration &)
Orchestrate the minimization of a quadratic cost function.
Private Types
using Bmat_ = BMatrix< MODEL >
using CostFct_ = CostFunction< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using HtRinvH_ = HtRinvHMatrix< MODEL >
Private Member Functions
double solve (CtrlInc_ &, CtrlInc_ &, CtrlInc_ &, const Bmat_ &, const HtRinvH_ &, const double, const double, const int, const double) override
Private Attributes
QNewtonLMP< CtrlInc_, Bmat_ > lmp_
Detailed Description
template<typename MODEL>
class oops::DRPCGMinimizer< MODEL >
DRPCG Minimizer.
Derber-Rosati Preconditioned Conjugate Gradients solver.
This solver is based on the standard Preconditioned Conjugate Gradients solver for Ax=b (G. H. Golub and C. F. Van Loan, Matrix Computations), and on the Derber and Rosati double PCG algorithm (J. Derber and A. Rosati, 1989, J. Phys. Oceanog. 1333-1347). For details see S. Gurol, PhD Manuscript, 2013. It solves \(Ax=b\) for the particular case \(A=B^{-1}+C\), without requiring the application of \(B^{-1}\). This algorithm is similar to DRIPCG except it includes standard PCG instead IPCG and stopping criteria is based on the preconditioner norm.
A must be square, symmetric, positive definite.
A preconditioner must be supplied that, given a vector q, returns an approximation to \((AB)^{-1} q\). Possible preconditioning is detailed in S. Gurol, PhD Manuscript, 2013. Note that the traditional \(B\)-preconditioning corresponds to precond= \(I\).
On entry:
dx = starting point, \(dx_{0} \).
dxh = \(B^{-1} dx_{0} \). or
dxh = \(B^{-1} (dx_{0} + x_fg - x_b) \).
rr = \((sum B^{-1} dx^{b}_{i} +) H^T R^{-1} d - A dx_{0} \) or
rr = \(H^T R^{-1} [d + H (x_b - x_fg) ] - A dx_{0} \)
B = \(B \).
C = \(C \).
precond = preconditioner \(F_k \approx (AB)^{-1} \).
On exit, dx will contain the solution \(dx \) and dxh will contain \(B^{-1} dx\). The return value is the achieved reduction in preconditioned residual norm.
Iteration will stop if the maximum iteration limit "maxiter" is reached or if the residual norm reduces by a factor of "tolerance".
Each matrix must implement a method:
void multiply(const VECTOR&, VECTOR&) const
which applies the matrix to the first argument, and returns the matrix-vector product in the second. (Note: the const is optional, but recommended.)
Definition at line 85 of file DRPCGMinimizer.h.
Member Typedef Documentation
Bmat_
template<typename MODEL > using oops::DRPCGMinimizer< MODEL >::Bmat_ = BMatrix<MODEL> private
Definition at line 86 of file DRPCGMinimizer.h.
CostFct_
template<typename MODEL > using oops::DRPCGMinimizer< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 87 of file DRPCGMinimizer.h.
CtrlInc_
template<typename MODEL > using oops::DRPCGMinimizer< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 88 of file DRPCGMinimizer.h.
HtRinvH_
template<typename MODEL > using oops::DRPCGMinimizer< MODEL >::HtRinvH_ = HtRinvHMatrix<MODEL> private
Definition at line 89 of file DRPCGMinimizer.h.
Constructor & Destructor Documentation
DRPCGMinimizer()
template<typename MODEL > oops::DRPCGMinimizer< MODEL >::DRPCGMinimizer (const eckit::Configuration & conf, const CostFct_ & J)
Definition at line 107 of file DRPCGMinimizer.h.
     : DRMinimizer<MODEL>(J), lmp_(conf) {}
~DRPCGMinimizer()
template<typename MODEL > oops::DRPCGMinimizer< MODEL >::~DRPCGMinimizer () inline
Definition at line 94 of file DRPCGMinimizer.h.
 {}
Member Function Documentation
classname()
template<typename MODEL > const std::string oops::DRPCGMinimizer< MODEL >::classname () const inline override virtual
Implements oops::DRMinimizer< MODEL >.
Definition at line 92 of file DRPCGMinimizer.h.
 { return "DRPCGMinimizer"; }
solve()
template<typename MODEL > double oops::DRPCGMinimizer< MODEL >::solve (CtrlInc_ & dx, CtrlInc_ & dxh, CtrlInc_ & rr, const Bmat_ & B, const HtRinvH_ & HtRinvH, const double costJ0Jb, const double costJ0JoJc, const int maxiter, const double tolerance) override private virtual
Implements oops::DRMinimizer< MODEL >.
Definition at line 114 of file DRPCGMinimizer.h.
{
   // dx   increment
   CtrlInc_ qq(dxh, false);
   CtrlInc_ pp(dxh, false);
   CtrlInc_ hh(dxh, false);
   CtrlInc_ zz(dxh, false);
   CtrlInc_ pr(dxh, false);
   CtrlInc_ r0(dxh, false);
   CtrlInc_ ww(dxh, false);
   CtrlInc_ dx0(dx);
   CtrlInc_ dxh0(dxh);
   // vectors for re-orthogonalization
   std::vector<CtrlInc_> vvecs;
   std::vector<CtrlInc_> zvecs;
   std::vector<double> scals;
   // r_{0} = b - A x_{0}
   HtRinvH.multiply(dx, zz);
   zz += dxh;
   rr -= zz;
   // save the initial residual
   r0 = rr;
   // J0
   const double costJ0 = costJ0Jb + costJ0JoJc;
   // zero out initial guess
   dx.zero();
   dxh.zero();
   // r_{0}^T r_{0}
   Log::info() << "normr0 " << dot_product(rr, rr) << std::endl;
   // z_{0} = B LMP r_{0}
   lmp_.multiply(rr, pr);
   B.multiply(pr, zz);
   // p_{0} = z_{0}
   pp = zz;
   // h_{0} = LMP r_{0}
   hh = pr;
   // r_{0}^T z_{0}
   double dotRr0 = dot_product(rr, zz);
   double normReduction = 1.0;
   double rdots = dotRr0;
   double rdots_old = 0.0;
   vvecs.push_back(rr);
   zvecs.push_back(zz);
   scals.push_back(1.0 / dotRr0);
   Log::info() << std::endl;
   for (int jiter = 0; jiter < maxiter; ++jiter) {
     Log::info() << " DRPCG Starting Iteration " << jiter + 1 << std::endl;
     if (jiter > 0) {
       // beta_{i} = r_{i+1}^T z_{i+1} / r_{i}^T z_{i}
       double beta = rdots / rdots_old;
       Log::debug() << "DRPCG beta = " << beta << std::endl;
       // p_{i+1} = z_{i+1} + beta*p_{i}
       pp *= beta;
       pp += zz;
       // h_{i+1} = LMP r_{i+1} + beta*h_{i}
       hh *= beta;
       hh += pr;
     }
     // q_{i} = h_{i} + H^T R^{-1} H p_{i}
     HtRinvH.multiply(pp, qq);
     qq += hh;
     // alpha_{i} = r_{i}^T z_{i} / q_{i}^T p_{i}
     double rho = dot_product(pp, qq);
     double alpha = rdots / rho;
     // dx_{i+1} = dx_{i} + alpha * p_{i}
     dx.axpy(alpha, pp);
     // dxh_{i+1} = dxh_{i} + alpha * h_{i} ! for diagnosing Jb
     dxh.axpy(alpha, hh);
     // r_{i+1} = r_{i} - alpha * q_{i}
     rr.axpy(-alpha, qq);
     // Compute the quadratic cost function
     // J[dx_{i}] = J[0] - 0.5 dx_{i}^T r_{0}
     double costJ = costJ0 - 0.5 * dot_product(dx, r0);
     // Jb[dx_{i}] = 0.5 dx_{i}^T f_{i}
     double costJb = costJ0Jb + 0.5 * dot_product(dx, dxh);
     // Jo[dx_{i}] + Jc[dx_{i}] = J[dx_{i}] - Jb[dx_{i}]
     double costJoJc = costJ - costJb;
     // Re-orthogonalization
     for (int jj = 0; jj < jiter; ++jj) {
       double proj = scals[jj] * dot_product(rr, zvecs[jj]);
       rr.axpy(-proj, vvecs[jj]);
     }
     // z_{i+1} = B LMP r_{i+1}
     lmp_.multiply(rr, pr);
     B.multiply(pr, zz);
     // r_{i}^T z_{i}
     rdots_old = rdots;
     // r_{i+1}^T z_{i+1}
     rdots = dot_product(rr, zz);
     Log::info() << "rdots " << rdots << "      iteration    " << jiter
                 << std::endl;
     // r_{i+1}^T z_{i+1} / r_{0}^T z_{0}
     normReduction = sqrt(rdots / dotRr0);
     Log::info() << "DRPCG end of iteration " << jiter + 1 << std::endl
                 << "  Norm reduction (" << std::setw(2) << jiter + 1
                 << ") = " << util::full_precision(normReduction) << std::endl
                 << "  Quadratic cost function: J   (" << std::setw(2)
                 << jiter + 1 << ") = " << util::full_precision(costJ)
                 << std::endl
                 << "  Quadratic cost function: Jb  (" << std::setw(2)
                 << jiter + 1 << ") = " << util::full_precision(costJb)
                 << std::endl
                 << "  Quadratic cost function: JoJc(" << std::setw(2)
                 << jiter + 1 << ") = " << util::full_precision(costJoJc)
                 << std::endl
                 << std::endl;
     // Save the pairs for preconditioning
     lmp_.push(pp, hh, qq, rho);
     if (normReduction < tolerance) {
       Log::info() << "DRPCG: Achieved required reduction in residual norm."
                   << std::endl;
       break;
     }
     vvecs.push_back(rr);
     zvecs.push_back(zz);
     scals.push_back(1.0 / rdots);
   }
   // Generate the (second-level) Limited Memory Preconditioner
   lmp_.update(B);
   // Add increment to initial guess
   dx += dx0;
   dxh += dxh0;
   return normReduction;
 }
References oops::ControlIncrement< MODEL >::axpy(), dot_product(), util::full_precision(), oops::BMatrix< MODEL >::multiply(), oops::HtRinvHMatrix< MODEL >::multiply(), and oops::ControlIncrement< MODEL >::zero().
Member Data Documentation
lmp_
template<typename MODEL > QNewtonLMP<CtrlInc_, Bmat_> oops::DRPCGMinimizer< MODEL >::lmp_ private
Definition at line 101 of file DRPCGMinimizer.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/DRPCGMinimizer.h