OOPS Documentation: oops::DualResForecast< MODEL > Class Template Reference
oops::DualResForecast< MODEL > Class Template Reference
#include <DualResForecast.h>
Public Member Functions
DualResForecast ()
virtual ~DualResForecast ()
int execute (const eckit::Configuration &fullConfig) const
Public Member Functions inherited from oops::Application
Application ()
virtual ~Application ()
Private Types
using Geometry_ = Geometry< MODEL >
using Model_ = Model< MODEL >
using ModelAux_ = ModelAuxControl< MODEL >
using State_ = State< MODEL >
Private Member Functions
std::string appname () const
Detailed Description
template<typename MODEL>
class oops::DualResForecast< MODEL >
Definition at line 34 of file DualResForecast.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::DualResForecast< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 35 of file DualResForecast.h.
Model_
template<typename MODEL > using oops::DualResForecast< MODEL >::Model_ = Model<MODEL> private
Definition at line 36 of file DualResForecast.h.
ModelAux_
template<typename MODEL > using oops::DualResForecast< MODEL >::ModelAux_ = ModelAuxControl<MODEL> private
Definition at line 37 of file DualResForecast.h.
State_
template<typename MODEL > using oops::DualResForecast< MODEL >::State_ = State<MODEL> private
Definition at line 38 of file DualResForecast.h.
Constructor & Destructor Documentation
DualResForecast()
template<typename MODEL > oops::DualResForecast< MODEL >::DualResForecast () inline
Definition at line 42 of file DualResForecast.h.
 {}
~DualResForecast()
template<typename MODEL > virtual oops::DualResForecast< MODEL >::~DualResForecast () inline virtual
Definition at line 44 of file DualResForecast.h.
 {}
Member Function Documentation
appname()
template<typename MODEL > std::string oops::DualResForecast< MODEL >::appname () const inline private virtual
Implements oops::Application.
Definition at line 94 of file DualResForecast.h.
{
     return "oops::DualResForecast<" + MODEL::name() + ">";
   }
execute()
template<typename MODEL > int oops::DualResForecast< MODEL >::execute (const eckit::Configuration & fullConfig) const inline virtual
Implements oops::Application.
Definition at line 46 of file DualResForecast.h.
{
     const eckit::LocalConfiguration hiresModelConfig(fullConfig, "hiresModel");
     //  Setup resolution
     const eckit::LocalConfiguration resolConfig(hiresModelConfig, "resolution");
     const Geometry_ resol(resolConfig);
     //  Setup Model
     const eckit::LocalConfiguration modelConfig(hiresModelConfig, "model");
     const Model_ model(resol, modelConfig);
     //  Setup initial state
     const eckit::LocalConfiguration initialConfig(hiresModelConfig, "initial");
     State_ xx(resol, model, initialConfig);
     Log::test() << "Initial state: " << xx.norm() << std::endl;
     //  Setup augmented state
     const ModelAux_ moderr(resol, initialConfig);
     //  Setup times
     const util::Duration fclength(
         hiresModelConfig.getString("forecast_length"));
     const util::DateTime bgndate(xx.validTime());
     const util::DateTime enddate(bgndate + fclength);
     Log::info() << "Running forecast from " << bgndate << " to " << enddate
                 << std::endl;
     //  Setup forecast outputs
     PostProcessor<State_> post;
     eckit::LocalConfiguration prtConfig;
     if (hiresModelConfig.has("prints")) {
       prtConfig = eckit::LocalConfiguration(hiresModelConfig, "prints");
     }
     post.enrollProcessor(new StateInfo<State_>("fc", prtConfig));
     const eckit::LocalConfiguration outConfig(hiresModelConfig, "output");
     post.enrollProcessor(new StateWriter<State_>(bgndate, outConfig));
     //  Run forecast
     model.forecast(xx, moderr, fclength, post);
     Log::test() << "Final state: " << xx.norm() << std::endl;
     return 0;
   }
References oops::PostProcessor< FLDS >::enrollProcessor(), oops::Model< MODEL >::forecast(), oops::State< MODEL >::norm(), and oops::State< MODEL >::validTime().
The documentation for this class was generated from the following file:
src/oops/runs/DualResForecast.h