OOPS Documentation: oops::StaticCovariance4D< MODEL > Class Template Reference
oops::StaticCovariance4D< MODEL > Class Template Reference
Generic ensemble based model space error covariance.
#include <StaticCovariance4D.h>
Public Member Functions
StaticCovariance4D (const Geometry_ &, const Variables_ &, const eckit::Configuration &, const State4D_ &xb)
Constructor, destructor.
~StaticCovariance4D ()
void advectedLinearize (const State4D_ &, const Geometry_ &)
void advectedLinearize (const State4D_ &, const Geometry_ &, const eckit::Configuration &)
void advectedMultiply (const Increment4D_ &, Increment4D_ &) const
void advectedMultiplySqrt (const IncrCtlVec_ &, Increment4D_ &) const
void advectedMultiplySqrtTrans (const Increment4D_ &, IncrCtlVec_ &) const
void advectedInverseMultiply (const Increment4D_ &, Increment4D_ &) const
const ModelSpaceCovarianceBase< MODEL > & covar () const
IncrModCtlVec_ * newIncrModCtlVec () const
IncrEnsCtlVec_ * newIncrEnsCtlVec () const
Public Member Functions inherited from oops::ModelSpaceCovariance4DBase< MODEL >
ModelSpaceCovariance4DBase (const Geometry_ &, const eckit::Configuration &config)
virtual ~ModelSpaceCovariance4DBase ()
void linearize (const State4D_ &xb, const Geometry_ &resol)
void linearize (const State4D_ &xb, const Geometry_ &resol, const eckit::Configuration &config)
virtual void multiply (const Increment4D_ &dxi, Increment4D_ &dxo) const
virtual void multiplySqrt (const IncrCtlVec_ &dvi, Increment4D_ &dxo) const
virtual void multiplySqrtTrans (const Increment4D_ &dxi, IncrCtlVec_ &dvo) const
void inverseMultiply (const Increment4D_ &dxi, Increment4D_ &dxo) const
virtual void randomize (Increment4D_ &) const
Private Types
using Geometry_ = Geometry< MODEL >
using Increment_ = Increment< MODEL >
using State4D_ = State4D< MODEL >
using Increment4D_ = Increment4D< MODEL >
using IncrCtlVec_ = IncrCtlVec< MODEL >
using IncrEnsCtlVec_ = IncrEnsCtlVec< MODEL >
using IncrModCtlVec_ = IncrModCtlVec< MODEL >
using Variables_ = Variables< MODEL >
Private Attributes
unsigned nsubwin_
std::unique_ptr< ModelSpaceCovarianceBase< MODEL > > static_
Detailed Description
template<typename MODEL>
class oops::StaticCovariance4D< MODEL >
Generic ensemble based model space error covariance.
Definition at line 35 of file StaticCovariance4D.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::StaticCovariance4D< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 36 of file StaticCovariance4D.h.
IncrCtlVec_
template<typename MODEL > using oops::StaticCovariance4D< MODEL >::IncrCtlVec_ = IncrCtlVec<MODEL> private
Definition at line 40 of file StaticCovariance4D.h.
Increment4D_
template<typename MODEL > using oops::StaticCovariance4D< MODEL >::Increment4D_ = Increment4D<MODEL> private
Definition at line 39 of file StaticCovariance4D.h.
Increment_
template<typename MODEL > using oops::StaticCovariance4D< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 37 of file StaticCovariance4D.h.
IncrEnsCtlVec_
template<typename MODEL > using oops::StaticCovariance4D< MODEL >::IncrEnsCtlVec_ = IncrEnsCtlVec<MODEL> private
Definition at line 41 of file StaticCovariance4D.h.
IncrModCtlVec_
template<typename MODEL > using oops::StaticCovariance4D< MODEL >::IncrModCtlVec_ = IncrModCtlVec<MODEL> private
Definition at line 42 of file StaticCovariance4D.h.
State4D_
template<typename MODEL > using oops::StaticCovariance4D< MODEL >::State4D_ = State4D<MODEL> private
Definition at line 38 of file StaticCovariance4D.h.
Variables_
template<typename MODEL > using oops::StaticCovariance4D< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 43 of file StaticCovariance4D.h.
Constructor & Destructor Documentation
StaticCovariance4D()
template<typename MODEL > oops::StaticCovariance4D< MODEL >::StaticCovariance4D (const Geometry_ & resol, const Variables_ & vars, const eckit::Configuration & config, const State4D_ & xb)
Constructor, destructor.
Definition at line 74 of file StaticCovariance4D.h.
     : ModelSpaceCovariance4DBase<MODEL>::ModelSpaceCovariance4DBase(resol,
                                                                     config),
       nsubwin_(0),
       static_(CovarianceFactory<MODEL>::create(
           eckit::LocalConfiguration(config, "covariance_3d"), resol, vars,
           xb[0])) {
   Log::trace() << "StaticCovariance4D created.";
 }
~StaticCovariance4D()
template<typename MODEL > oops::StaticCovariance4D< MODEL >::~StaticCovariance4D
Definition at line 87 of file StaticCovariance4D.h.
{
   Log::trace() << "StaticCovariance4D destructed.";
 }
Member Function Documentation
advectedInverseMultiply()
template<typename MODEL > void oops::StaticCovariance4D< MODEL >::advectedInverseMultiply (const Increment4D_ & dxi, Increment4D_ & dxo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 145 of file StaticCovariance4D.h.
{
   dxo.zero();
 }
References oops::Increment4D< MODEL >::zero().
advectedLinearize() [1/2]
template<typename MODEL > void oops::StaticCovariance4D< MODEL >::advectedLinearize (const State4D_ & xb, const Geometry_ & resol) virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 92 of file StaticCovariance4D.h.
{
   static_->linearize(xb[0], resol);
   Log::trace() << "StaticCovariance4D linearized.";
 }
advectedLinearize() [2/2]
template<typename MODEL > void oops::StaticCovariance4D< MODEL >::advectedLinearize (const State4D_ & xb, const Geometry_ & resol, const eckit::Configuration &) virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 99 of file StaticCovariance4D.h.
{
   static_->linearize(xb[0], resol);
   Log::trace() << "StaticCovariance4D linearized.";
 }
advectedMultiply()
template<typename MODEL > void oops::StaticCovariance4D< MODEL >::advectedMultiply (const Increment4D_ & dxi, Increment4D_ & dxo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 106 of file StaticCovariance4D.h.
{
   Increment_ temp(dxi[0]);
   temp.zero();
   for (int k2 = dxi.first(); k2 <= dxi.last(); ++k2) {
     temp.axpy(1.0, dxi[k2], false);
   }
   static_->multiply(temp, dxo[dxi.first()]);
   for (int k1 = dxi.first() + 1; k1 <= dxi.last(); ++k1) {
     dxo[k1].zero();
     dxo[k1].axpy(1.0, dxo[0], false);
   }
 }
References oops::Increment4D< MODEL >::axpy(), oops::Increment< MODEL >::axpy(), oops::Increment4D< MODEL >::first(), oops::Increment4D< MODEL >::last(), oops::Increment4D< MODEL >::zero(), and oops::Increment< MODEL >::zero().
advectedMultiplySqrt()
template<typename MODEL > void oops::StaticCovariance4D< MODEL >::advectedMultiplySqrt (const IncrCtlVec_ & dvi, Increment4D_ & dxo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 122 of file StaticCovariance4D.h.
{
   static_->multiplySqrt(dvi, dxo[dxo.first()]);
   for (int k1 = dxo.first() + 1; k1 <= dxo.last(); ++k1) {
     dxo[k1].zero();
     dxo[k1].axpy(1.0, dxo[0], false);
   }
 }
References oops::Increment4D< MODEL >::axpy(), oops::Increment4D< MODEL >::first(), oops::Increment4D< MODEL >::last(), and oops::Increment4D< MODEL >::zero().
advectedMultiplySqrtTrans()
template<typename MODEL > void oops::StaticCovariance4D< MODEL >::advectedMultiplySqrtTrans (const Increment4D_ & dxi, IncrCtlVec_ & dvo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 133 of file StaticCovariance4D.h.
{
   Increment_ temp(dxi[0]);
   temp.zero();
   for (int k2 = dxi.first(); k2 <= dxi.last(); ++k2) {
     temp.axpy(1.0, dxi[k2], false);
   }
   static_->multiplySqrtTrans(temp, dvo);
 }
References oops::Increment< MODEL >::axpy(), oops::Increment4D< MODEL >::first(), oops::Increment4D< MODEL >::last(), and oops::Increment< MODEL >::zero().
covar()
template<typename MODEL > const ModelSpaceCovarianceBase<MODEL>& oops::StaticCovariance4D< MODEL >::covar () const inline virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 56 of file StaticCovariance4D.h.
 { return *static_; }
References oops::StaticCovariance4D< MODEL >::static_.
newIncrEnsCtlVec()
template<typename MODEL > IncrEnsCtlVec_* oops::StaticCovariance4D< MODEL >::newIncrEnsCtlVec () const inline virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 62 of file StaticCovariance4D.h.
 { return new IncrEnsCtlVec_(); }
newIncrModCtlVec()
template<typename MODEL > IncrModCtlVec_* oops::StaticCovariance4D< MODEL >::newIncrModCtlVec () const inline virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 59 of file StaticCovariance4D.h.
{
     return static_->newIncrModCtlVec();
   }
References oops::StaticCovariance4D< MODEL >::static_.
Member Data Documentation
nsubwin_
template<typename MODEL > unsigned oops::StaticCovariance4D< MODEL >::nsubwin_ private
Definition at line 65 of file StaticCovariance4D.h.
static_
template<typename MODEL > std::unique_ptr<ModelSpaceCovarianceBase<MODEL> > oops::StaticCovariance4D< MODEL >::static_ private
Definition at line 66 of file StaticCovariance4D.h.
Referenced by oops::StaticCovariance4D< MODEL >::covar(), and oops::StaticCovariance4D< MODEL >::newIncrModCtlVec().
The documentation for this class was generated from the following file:
src/oops/base/StaticCovariance4D.h