OOPS Documentation: oops::CostJbJq< MODEL > Class Template Reference
oops::CostJbJq< MODEL > Class Template Reference
Jb + Jq Cost Function.
#include <CostJbJq.h>
Public Member Functions
CostJbJq (const eckit::Configuration &, const Geometry_ &, const Variables_ &, const util::Duration &, const State4D_ &, const bool)
Construct \(J_b\).
virtual ~CostJbJq ()
Destructor.
JqTerm< MODEL > * initializeJq () const override
Finalize \(J_q\) after the model run.
void computeIncrement (const State4D_ &, const State4D_ &, Increment4D_ &) const override
Get increment from state (usually first guess).
void linearize (const State4D_ &, const Geometry_ &, const eckit::Configuration &) override
Linearize before the linear computations.
void addGradient (const Increment4D_ &, Increment4D_ &, Increment4D_ &) const override
Add Jb gradient.
JqTermTL< MODEL > * initializeJqTL () const override
Finalize \(J_q\) after the TL run.
JqTermAD< MODEL > * initializeJqAD (const Increment4D_ &) const override
Initialize \(J_q\) forcing before the AD run.
void Bmult (const Increment4D_ &, Increment4D_ &) const override
Multiply by \(B\) and \(B^{-1}\).
void Bminv (const Increment4D_ &, Increment4D_ &) const override
Multiply by \(B^{-1}\).
void BmultSqrt (const IncrCtlVec4D_ &, Increment4D_ &) const override
Multiply by \(B^{1/2}\) and \([B^{1/2}]^T\).
void BmultSqrtTrans (const Increment4D_ &, IncrCtlVec4D_ &) const override
Multiply by \([B^{1/2}]^T\).
void randomize (Increment4D_ &) const override
Randomize.
const ModelSpaceCovarianceBase< MODEL > & covar () const
Access to B.
unsigned int nstates () const override
Create new increment (set to 0).
Increment_ * newStateIncrement (const unsigned int) const override
Create new increment (set to 0).
unsigned int nchistates () const override
Create new control vector.
IncrCtlVec_ * newIncrCtlVec (const unsigned int) const override
Create new control vector.
IncrModCtlVec_ * newIncrModCtlVec () const override
Create new control vector (mod)
IncrEnsCtlVec_ * newIncrEnsCtlVec () const override
Create new control vector (ens)
Public Member Functions inherited from oops::CostJbState< MODEL >
CostJbState ()
Constructor.
virtual ~CostJbState ()
Destructor.
Private Types
using CtrlInc_ = ControlIncrement< MODEL >
using Geometry_ = Geometry< MODEL >
using Increment_ = Increment< MODEL >
using Increment4D_ = Increment4D< MODEL >
using IncrCtlVec_ = IncrCtlVec< MODEL >
using IncrCtlVec4D_ = IncrCtlVec4D< MODEL >
using State4D_ = State4D< MODEL >
using Variables_ = Variables< MODEL >
using IncrModCtlVec_ = IncrModCtlVec< MODEL >
using IncrEnsCtlVec_ = IncrEnsCtlVec< MODEL >
Private Attributes
std::vector< std::unique_ptr< ModelSpaceCovarianceBase< MODEL > > > B_
const util::Duration subwin_
const bool forcing_
const Variables_ controlvars_
std::unique_ptr< const Geometry_ > resol_
std::vector< util::DateTime > times_
Detailed Description
template<typename MODEL>
class oops::CostJbJq< MODEL >
Jb + Jq Cost Function.
CostJbJq encapsulates the generalized Jb term of the cost weak constraint 4D-Var function (ie Jb+Jq).
Definition at line 52 of file CostJbJq.h.
Member Typedef Documentation
CtrlInc_
template<typename MODEL > using oops::CostJbJq< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 53 of file CostJbJq.h.
Geometry_
template<typename MODEL > using oops::CostJbJq< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 54 of file CostJbJq.h.
IncrCtlVec4D_
template<typename MODEL > using oops::CostJbJq< MODEL >::IncrCtlVec4D_ = IncrCtlVec4D<MODEL> private
Definition at line 58 of file CostJbJq.h.
IncrCtlVec_
template<typename MODEL > using oops::CostJbJq< MODEL >::IncrCtlVec_ = IncrCtlVec<MODEL> private
Definition at line 57 of file CostJbJq.h.
Increment4D_
template<typename MODEL > using oops::CostJbJq< MODEL >::Increment4D_ = Increment4D<MODEL> private
Definition at line 56 of file CostJbJq.h.
Increment_
template<typename MODEL > using oops::CostJbJq< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 55 of file CostJbJq.h.
IncrEnsCtlVec_
template<typename MODEL > using oops::CostJbJq< MODEL >::IncrEnsCtlVec_ = IncrEnsCtlVec<MODEL> private
Definition at line 62 of file CostJbJq.h.
IncrModCtlVec_
template<typename MODEL > using oops::CostJbJq< MODEL >::IncrModCtlVec_ = IncrModCtlVec<MODEL> private
Definition at line 61 of file CostJbJq.h.
State4D_
template<typename MODEL > using oops::CostJbJq< MODEL >::State4D_ = State4D<MODEL> private
Definition at line 59 of file CostJbJq.h.
Variables_
template<typename MODEL > using oops::CostJbJq< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 60 of file CostJbJq.h.
Constructor & Destructor Documentation
CostJbJq()
template<typename MODEL > oops::CostJbJq< MODEL >::CostJbJq (const eckit::Configuration & config, const Geometry_ & resolouter, const Variables_ & ctlvars, const util::Duration & len, const State4D_ & xb, const bool forcing)
Construct \(J_b\).
Definition at line 140 of file CostJbJq.h.
     : B_(0),
       subwin_(len),
       forcing_(forcing),
       controlvars_(ctlvars),
       resol_(),
       times_() {
   std::vector<eckit::LocalConfiguration> confs;
   config.get("Covariance", confs);
   for (size_t jsub = 0; jsub < confs.size(); ++jsub) {
     B_.emplace_back(CovarianceFactory<MODEL>::create(confs[jsub], resolouter,
                                                      ctlvars, xb[jsub]));
   }
   Log::trace() << "CostJbJq contructed." << std::endl;
 }
References oops::CostJbJq< MODEL >::B_.
~CostJbJq()
template<typename MODEL > virtual oops::CostJbJq< MODEL >::~CostJbJq () inline virtual
Destructor.
Definition at line 70 of file CostJbJq.h.
 {}
Member Function Documentation
addGradient()
template<typename MODEL > void oops::CostJbJq< MODEL >::addGradient (const Increment4D_ & dxFG, Increment4D_ & grad, Increment4D_ & gradJb) const override virtual
Add Jb gradient.
Implements oops::CostJbState< MODEL >.
Definition at line 187 of file CostJbJq.h.
{
   // Jb from pre-computed gradient
   grad[0] -= gradJb[0];
   // MC - the first formulation below would be valid if the state was updated
   //      just at the begining of the window and the forecast was ran from
   //      there throughout the entire window; this is not the case in the
   //      forcing formulation
   // Compute and add Jq gradient Qi^{-1} ( x_i - M(x_{i-1}) )
   if (!forcing_) {
     Increment4D_ gg(grad, false);
     for (unsigned jsub = 1; jsub < B_.size(); ++jsub) {
       B_[jsub]->inverseMultiply(dxFG[jsub], gg[jsub]);
       grad[jsub] -= gg[jsub];
     }
   } else {
     for (unsigned jsub = 1; jsub < B_.size(); ++jsub) {
       grad[jsub] -= gradJb[jsub];
     }
   }
 }
Bminv()
template<typename MODEL > void oops::CostJbJq< MODEL >::Bminv (const Increment4D_ & , Increment4D_ &) const override virtual
Multiply by \(B^{-1}\).
Implements oops::CostJbState< MODEL >.
Definition at line 266 of file CostJbJq.h.
{
   Log::warning() << "*** B inverse might not always exist ***" << std::endl;
   for (unsigned jsub = 0; jsub < B_.size(); ++jsub) {
     B_[jsub]->inverseMultiply(dxin[jsub], dxout[jsub]);
     if (jsub == 0) {
       Log::debug() << "CostJbJq:inverseMultiply Jb is "
                    << 0.5 * dot_product(dxin[0], dxout[0]) << std::endl;
     } else {
       Log::debug() << "CostJbJq:inverseMultiply Jq(" << jsub << ") is "
                    << 0.5 * dot_product(dxin[jsub], dxout[jsub]);
     }
   }
   Log::warning() << "*** B inverse might not always exist ***" << std::endl;
 }
References dot_product().
Bmult()
template<typename MODEL > void oops::CostJbJq< MODEL >::Bmult (const Increment4D_ & dxin, Increment4D_ & dxout) const override virtual
Multiply by \(B\) and \(B^{-1}\).
Implements oops::CostJbState< MODEL >.
Definition at line 239 of file CostJbJq.h.
{
   for (unsigned jsub = 0; jsub < B_.size(); ++jsub) {
     B_[jsub]->multiply(dxin[jsub], dxout[jsub]);
     if (jsub == 0) {
       Log::debug() << "CostJbJq:multiply Jb is "
                    << 0.5 * dot_product(dxin[0], dxout[0]) << std::endl;
     } else {
       Log::debug() << "CostJbJq:multiply Jq(" << jsub << ") is "
                    << 0.5 * dot_product(dxin[jsub], dxout[jsub]);
     }
   }
 }
References dot_product().
BmultSqrt()
template<typename MODEL > void oops::CostJbJq< MODEL >::BmultSqrt (const IncrCtlVec4D_ & dv, Increment4D_ & dxout) const override virtual
Multiply by \(B^{1/2}\) and \([B^{1/2}]^T\).
Implements oops::CostJbState< MODEL >.
Definition at line 286 of file CostJbJq.h.
{
   for (unsigned jsub = 0; jsub < B_.size(); ++jsub) {
     B_[jsub]->multiplySqrt(dv[jsub], dxout[jsub]);
   }
 }
BmultSqrtTrans()
template<typename MODEL > void oops::CostJbJq< MODEL >::BmultSqrtTrans (const Increment4D_ & , IncrCtlVec4D_ &) const override virtual
Multiply by \([B^{1/2}]^T\).
Implements oops::CostJbState< MODEL >.
Definition at line 296 of file CostJbJq.h.
{
   for (unsigned jsub = 0; jsub < B_.size(); ++jsub) {
     B_[jsub]->multiplySqrtTrans(dxin[jsub], dv[jsub]);
   }
 }
computeIncrement()
template<typename MODEL > void oops::CostJbJq< MODEL >::computeIncrement (const State4D_ & xb, const State4D_ & fg, Increment4D_ & dx) const override virtual
Get increment from state (usually first guess).
Implements oops::CostJbState< MODEL >.
Definition at line 177 of file CostJbJq.h.
{
   // Compute x_0 - x_b for Jb
   dx[0].diff(fg[0], xb[0]);
   Log::info() << "CostJbJq: x_0 - x_b" << dx[0] << std::endl;
 }
References oops::Increment4D< MODEL >::diff().
covar()
template<typename MODEL > const ModelSpaceCovarianceBase<MODEL>& oops::CostJbJq< MODEL >::covar () const inline virtual
Access to B.
Implements oops::CostJbState< MODEL >.
Definition at line 104 of file CostJbJq.h.
 { return *B_[0]; }
References oops::CostJbJq< MODEL >::B_.
Referenced by oops::CostJbJq< MODEL >::newIncrEnsCtlVec(), and oops::CostJbJq< MODEL >::newIncrModCtlVec().
initializeJq()
template<typename MODEL > JqTerm< MODEL > * oops::CostJbJq< MODEL >::initializeJq override virtual
Finalize \(J_q\) after the model run.
Implements oops::CostJbState< MODEL >.
Definition at line 214 of file CostJbJq.h.
{
   return new JqTerm<MODEL>(B_.size());
 }
initializeJqAD()
template<typename MODEL > JqTermAD< MODEL > * oops::CostJbJq< MODEL >::initializeJqAD (const Increment4D_ & dx) const override virtual
Initialize \(J_q\) forcing before the AD run.
Implements oops::CostJbState< MODEL >.
Definition at line 230 of file CostJbJq.h.
{
   JqTermAD<MODEL> *jqad = 0;
   if (!forcing_) jqad = new JqTermAD<MODEL>(B_.size(), dx);
   return jqad;
 }
initializeJqTL()
template<typename MODEL > JqTermTL< MODEL > * oops::CostJbJq< MODEL >::initializeJqTL override virtual
Finalize \(J_q\) after the TL run.
Implements oops::CostJbState< MODEL >.
Definition at line 221 of file CostJbJq.h.
{
   JqTermTL<MODEL> *jqtl = 0;
   if (!forcing_) jqtl = new JqTermTL<MODEL>(B_.size());
   return jqtl;
 }
linearize()
template<typename MODEL > void oops::CostJbJq< MODEL >::linearize (const State4D_ & fg, const Geometry_ & resolinner, const eckit::Configuration & innerConf) override virtual
Linearize before the linear computations.
Implements oops::CostJbState< MODEL >.
Definition at line 162 of file CostJbJq.h.
{
   ASSERT(fg.checkStatesNumber(B_.size()));
   resol_.reset(new Geometry_(resolinner));
   times_.clear();
   for (unsigned jsub = 0; jsub < B_.size(); ++jsub) {
     times_.push_back(fg[jsub].validTime());
     B_[jsub]->linearize(fg[jsub], *resol_, innerConf);
   }
 }
References oops::State4D< MODEL >::checkStatesNumber().
nchistates()
template<typename MODEL > unsigned int oops::CostJbJq< MODEL >::nchistates () const inline override virtual
Create new control vector.
Implements oops::CostJbState< MODEL >.
Definition at line 111 of file CostJbJq.h.
 { return B_.size(); }
References oops::CostJbJq< MODEL >::B_.
newIncrCtlVec()
template<typename MODEL > IncrCtlVec< MODEL > * oops::CostJbJq< MODEL >::newIncrCtlVec (const unsigned int) const override virtual
Create new control vector.
Implements oops::CostJbState< MODEL >.
Definition at line 315 of file CostJbJq.h.
{
   return new IncrCtlVec_(*this, times_[isub]);
 }
newIncrEnsCtlVec()
template<typename MODEL > IncrEnsCtlVec_* oops::CostJbJq< MODEL >::newIncrEnsCtlVec () const inline override virtual
Create new control vector (ens)
Implements oops::CostJbState< MODEL >.
Definition at line 120 of file CostJbJq.h.
{
     return covar().newIncrEnsCtlVec();
   }
References oops::CostJbJq< MODEL >::covar().
newIncrModCtlVec()
template<typename MODEL > IncrModCtlVec_* oops::CostJbJq< MODEL >::newIncrModCtlVec () const inline override virtual
Create new control vector (mod)
Implements oops::CostJbState< MODEL >.
Definition at line 115 of file CostJbJq.h.
{
     return covar().newIncrModCtlVec();
   }
References oops::CostJbJq< MODEL >::covar().
newStateIncrement()
template<typename MODEL > Increment< MODEL > * oops::CostJbJq< MODEL >::newStateIncrement (const unsigned int) const override virtual
Create new increment (set to 0).
Implements oops::CostJbState< MODEL >.
Definition at line 306 of file CostJbJq.h.
{
   Increment_ *incr = new Increment_(*resol_, controlvars_, times_[isub]);
   return incr;
 }
nstates()
template<typename MODEL > unsigned int oops::CostJbJq< MODEL >::nstates () const inline override virtual
Create new increment (set to 0).
Implements oops::CostJbState< MODEL >.
Definition at line 107 of file CostJbJq.h.
 { return B_.size(); }
References oops::CostJbJq< MODEL >::B_.
randomize()
template<typename MODEL > void oops::CostJbJq< MODEL >::randomize (Increment4D_ & dx) const override virtual
Randomize.
Implements oops::CostJbState< MODEL >.
Definition at line 257 of file CostJbJq.h.
{
   for (unsigned jsub = 0; jsub < B_.size(); ++jsub) {
     B_[jsub]->randomize(dx[jsub]);
   }
 }
Member Data Documentation
B_
template<typename MODEL > std::vector<std::unique_ptr<ModelSpaceCovarianceBase<MODEL> > > oops::CostJbJq< MODEL >::B_ private
Definition at line 125 of file CostJbJq.h.
Referenced by oops::CostJbJq< MODEL >::CostJbJq(), oops::CostJbJq< MODEL >::covar(), oops::CostJbJq< MODEL >::nchistates(), and oops::CostJbJq< MODEL >::nstates().
controlvars_
template<typename MODEL > const Variables_ oops::CostJbJq< MODEL >::controlvars_ private
Definition at line 129 of file CostJbJq.h.
forcing_
template<typename MODEL > const bool oops::CostJbJq< MODEL >::forcing_ private
Definition at line 128 of file CostJbJq.h.
resol_
template<typename MODEL > std::unique_ptr<const Geometry_> oops::CostJbJq< MODEL >::resol_ private
Definition at line 130 of file CostJbJq.h.
subwin_
template<typename MODEL > const util::Duration oops::CostJbJq< MODEL >::subwin_ private
Definition at line 127 of file CostJbJq.h.
times_
template<typename MODEL > std::vector<util::DateTime> oops::CostJbJq< MODEL >::times_ private
Definition at line 131 of file CostJbJq.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/CostJbJq.h