OOPS Documentation: oops::SaddlePointMinimizer< MODEL > Class Template Reference
oops::SaddlePointMinimizer< MODEL > Class Template Reference
SaddlePoint Minimizer.
#include <SaddlePointMinimizer.h>
Public Member Functions
const std::string classname () const override
SaddlePointMinimizer (const eckit::Configuration &config, const CostFct_ &J)
~SaddlePointMinimizer ()
void checkpoint (eckit::LocalConfiguration &) const
Checkpoint the minimizer (virtual method)
void restart (const eckit::Configuration &)
Restart the minimizer (virtual method)
void warmStart (const eckit::Configuration &)
Warm start the minimizer (virtual method)
Public Member Functions inherited from oops::Minimizer< MODEL >
Minimizer (const CostFct_ &J)
Construct a minimizer.
virtual ~Minimizer ()
Destroy a minimizer.
ControlIncrement< MODEL > * minimize (const eckit::Configuration &)
Orchestrate the minimization of a quadratic cost function.
Private Types
using CtrlInc_ = ControlIncrement< MODEL >
using CostFct_ = CostFunction< MODEL >
using Minimizer_ = Minimizer< MODEL >
using Multipliers_ = DualVector< MODEL >
Private Member Functions
CtrlInc_ * doMinimize (const eckit::Configuration &) override
Minimizer the quadratic cost function (virtual method)
Private Attributes
const CostFct_ & J_
bool idmodel_
std::string solver_
std::string precond_type_
int precond_order_
std::unique_ptr< CtrlInc_ > gradJb_
std::vector< SaddlePointVector< MODEL > > xyVEC_
std::vector< SaddlePointVector< MODEL > > pqVEC_
Detailed Description
template<typename MODEL>
class oops::SaddlePointMinimizer< MODEL >
SaddlePoint Minimizer.
Implements the SaddlePoint algorithm.
Definition at line 46 of file SaddlePointMinimizer.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::SaddlePointMinimizer< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 48 of file SaddlePointMinimizer.h.
CtrlInc_
template<typename MODEL > using oops::SaddlePointMinimizer< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 47 of file SaddlePointMinimizer.h.
Minimizer_
template<typename MODEL > using oops::SaddlePointMinimizer< MODEL >::Minimizer_ = Minimizer<MODEL> private
Definition at line 49 of file SaddlePointMinimizer.h.
Multipliers_
template<typename MODEL > using oops::SaddlePointMinimizer< MODEL >::Multipliers_ = DualVector<MODEL> private
Definition at line 50 of file SaddlePointMinimizer.h.
Constructor & Destructor Documentation
SaddlePointMinimizer()
template<typename MODEL > oops::SaddlePointMinimizer< MODEL >::SaddlePointMinimizer (const eckit::Configuration & config, const CostFct_ & J) inline
Definition at line 57 of file SaddlePointMinimizer.h.
       : Minimizer_(J),
         J_(J),
         solver_("GMRESR"),
         precond_type_("NeumannApprox"),
         precond_order_(1),
         gradJb_() {
     if (config.has("solver")) solver_ = config.getString("solver");
     if (config.has("precond_type"))
       precond_type_ = config.getString("precond_type");
     if (config.has("precond_order"))
       precond_order_ = config.getInt("precond_order");
     ASSERT(solver_ == "GMRESR" || solver_ == "FullGMRES");
   }
References oops::SaddlePointMinimizer< MODEL >::precond_order_, oops::SaddlePointMinimizer< MODEL >::precond_type_, and oops::SaddlePointMinimizer< MODEL >::solver_.
~SaddlePointMinimizer()
template<typename MODEL > oops::SaddlePointMinimizer< MODEL >::~SaddlePointMinimizer () inline
Definition at line 71 of file SaddlePointMinimizer.h.
 {}
Member Function Documentation
checkpoint()
template<typename MODEL > void oops::SaddlePointMinimizer< MODEL >::checkpoint (eckit::LocalConfiguration &) const inline virtual
Checkpoint the minimizer (virtual method)
Implements oops::Minimizer< MODEL >.
Definition at line 73 of file SaddlePointMinimizer.h.
 {}
classname()
template<typename MODEL > const std::string oops::SaddlePointMinimizer< MODEL >::classname () const inline override virtual
Implements oops::Minimizer< MODEL >.
Definition at line 53 of file SaddlePointMinimizer.h.
{
     return "SaddlePointMinimizer";
   }
doMinimize()
template<typename MODEL > ControlIncrement< MODEL > * oops::SaddlePointMinimizer< MODEL >::doMinimize (const eckit::Configuration &) override private virtual
Minimizer the quadratic cost function (virtual method)
Implements oops::Minimizer< MODEL >.
Definition at line 94 of file SaddlePointMinimizer.h.
{
   int ninner = config.getInt("ninner");
   int gnreduc = config.getDouble("gradient_norm_reduction");
   //  if (gradJb_ == 0) gradJb_.reset(new CtrlInc_(J_.jb()));
   Log::info() << "SaddlePointMinimizer: max iter = " << ninner
               << ", requested norm reduction = " << gnreduc << std::endl;
   // Define saddle-point control vectors
   Multipliers_ *pdxx = new Multipliers_();
   pdxx->dx(new CtrlInc_(J_.jb()));
   for (unsigned jj = 0; jj < J_.nterms(); ++jj) {
     pdxx->append(J_.jterm(jj).newDualVector());
   }
   CtrlInc_ *tmp1 = new CtrlInc_(J_.jb());
   SaddlePointVector<MODEL> spdx(tmp1, pdxx);
   // Compute RHS
   Multipliers_ *pdfg = new Multipliers_();
   CtrlInc_ *tmp3 = new CtrlInc_(J_.jb().getFirstGuessIncrement());
   *tmp3 *= -1.0;
   pdfg->dx(tmp3);
   for (unsigned jj = 0; jj < J_.nterms(); ++jj) {
     std::unique_ptr<GeneralizedDepartures> ww(J_.jterm(jj).newGradientFG());
     pdfg->append(J_.jterm(jj).multiplyCovar(*ww));
   }
   CtrlInc_ *tmp2 = new CtrlInc_(J_.jb());
   SaddlePointVector<MODEL> rhs(tmp2, pdfg);
   // Define the matrices
   SaddlePointMatrix<MODEL> A(J_);
   // Inexact constraint preconditioner
   if (precond_type_ == "identity") {
     precond_order_ = 0;
   } else if (precond_type_ == "Midentity") {
     precond_order_ = 1;  // should be nsub
     idmodel_ = true;
   } else if (precond_type_ == "NeumannApprox") {
     idmodel_ = false;
   } else {
     Log::error() << "SaddlePointMinimizer: wrong choice of preconditioner: "
                  << precond_type_ << std::endl;
   }
   SaddlePointPrecondMatrix<MODEL> Pinv(J_, precond_order_, idmodel_);
   // Initialize the limited memory preconditioner
   // Eigen  if (!Pinv_.get()) {
   // Eigen    Pinv_.reset(new LMP_(J_));
   // Eigen  }
   // Update the preconditioner
   // Eigen  Pinv_->setup(xyVEC_, pqVEC_);
   // Solve the linear system
   double reduc = 1.0;
   if (solver_ == "GMRESR") {
     reduc = GMRESR(spdx, rhs, A, Pinv, ninner, gnreduc);
   } else if (solver_ == "FullGMRES") {
     reduc = FullGMRES(spdx, rhs, A, Pinv, ninner, gnreduc, pqVEC_, xyVEC_);
   } else {
     Log::error() << "SaddlePointMinimizer: wrong choice of solver: " << solver_
                  << std::endl;
   }
   CtrlInc_ *dx = new CtrlInc_(spdx.dx());
   Log::test() << "SaddlePointMinimizer: reduction in residual norm = " << reduc
               << std::endl;
   Log::info() << "SaddlePointMinimizer output" << *dx << std::endl;
   //  *gradJb_ = dx.lambda().dx();
   //  *gradJb_ *= -1.0;
   return dx;
 }
References oops::DualVector< MODEL >::append(), oops::DualVector< MODEL >::dx(), oops::SaddlePointVector< MODEL >::dx(), oops::FullGMRES(), and oops::GMRESR().
restart()
template<typename MODEL > void oops::SaddlePointMinimizer< MODEL >::restart (const eckit::Configuration &) inline virtual
Restart the minimizer (virtual method)
Implements oops::Minimizer< MODEL >.
Definition at line 74 of file SaddlePointMinimizer.h.
 {}
warmStart()
template<typename MODEL > void oops::SaddlePointMinimizer< MODEL >::warmStart (const eckit::Configuration &) inline virtual
Warm start the minimizer (virtual method)
Implements oops::Minimizer< MODEL >.
Definition at line 75 of file SaddlePointMinimizer.h.
 {}
Member Data Documentation
gradJb_
template<typename MODEL > std::unique_ptr<CtrlInc_> oops::SaddlePointMinimizer< MODEL >::gradJb_ private
Definition at line 85 of file SaddlePointMinimizer.h.
idmodel_
template<typename MODEL > bool oops::SaddlePointMinimizer< MODEL >::idmodel_ private
Definition at line 81 of file SaddlePointMinimizer.h.
J_
template<typename MODEL > const CostFct_& oops::SaddlePointMinimizer< MODEL >::J_ private
Definition at line 80 of file SaddlePointMinimizer.h.
pqVEC_
template<typename MODEL > std::vector<SaddlePointVector<MODEL> > oops::SaddlePointMinimizer< MODEL >::pqVEC_ private
Definition at line 88 of file SaddlePointMinimizer.h.
precond_order_
template<typename MODEL > int oops::SaddlePointMinimizer< MODEL >::precond_order_ private
Definition at line 84 of file SaddlePointMinimizer.h.
Referenced by oops::SaddlePointMinimizer< MODEL >::SaddlePointMinimizer().
precond_type_
template<typename MODEL > std::string oops::SaddlePointMinimizer< MODEL >::precond_type_ private
Definition at line 83 of file SaddlePointMinimizer.h.
Referenced by oops::SaddlePointMinimizer< MODEL >::SaddlePointMinimizer().
solver_
template<typename MODEL > std::string oops::SaddlePointMinimizer< MODEL >::solver_ private
Definition at line 82 of file SaddlePointMinimizer.h.
Referenced by oops::SaddlePointMinimizer< MODEL >::SaddlePointMinimizer().
xyVEC_
template<typename MODEL > std::vector<SaddlePointVector<MODEL> > oops::SaddlePointMinimizer< MODEL >::xyVEC_ private
Definition at line 87 of file SaddlePointMinimizer.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/SaddlePointMinimizer.h