OOPS Documentation: oops::DRPLanczosMinimizer< MODEL > Class Template Reference
oops::DRPLanczosMinimizer< MODEL > Class Template Reference
DRPLanczos Minimizer.
#include <DRPLanczosMinimizer.h>
Public Member Functions
const std::string classname () const override
DRPLanczosMinimizer (const eckit::Configuration &, const CostFct_ &)
~DRPLanczosMinimizer ()
Public Member Functions inherited from oops::DRMinimizer< MODEL >
DRMinimizer (const CostFct_ &J)
~DRMinimizer ()
void checkpoint (eckit::LocalConfiguration &) const
Checkpointing, restart.
void restart (const eckit::Configuration &)
Restart the minimizer (virtual method)
void warmStart (const eckit::Configuration &)
Warm start the minimizer (virtual method)
Public Member Functions inherited from oops::Minimizer< MODEL >
Minimizer (const CostFct_ &J)
Construct a minimizer.
virtual ~Minimizer ()
Destroy a minimizer.
ControlIncrement< MODEL > * minimize (const eckit::Configuration &)
Orchestrate the minimization of a quadratic cost function.
Private Types
using Bmat_ = BMatrix< MODEL >
using CostFct_ = CostFunction< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using HtRinvH_ = HtRinvHMatrix< MODEL >
Private Member Functions
double solve (CtrlInc_ &, CtrlInc_ &, CtrlInc_ &, const Bmat_ &, const HtRinvH_ &, const double, const double, const int, const double) override
Private Attributes
const eckit::LocalConfiguration config_
SpectralLMP< CtrlInc_ > lmp_
std::vector< std::unique_ptr< CtrlInc_ > > hvecs_
std::vector< std::unique_ptr< CtrlInc_ > > vvecs_
std::vector< std::unique_ptr< CtrlInc_ > > zvecs_
std::vector< double > alphas_
std::vector< double > betas_
Detailed Description
template<typename MODEL>
class oops::DRPLanczosMinimizer< MODEL >
DRPLanczos Minimizer.
Derber-Rosati Preconditioned Lanczos solver.
This solver is the Lanczos version of the DRPCG algorithm It solves \(Ax=b\) for the particular case \(A=B^{-1}+C\), without requiring the application of \(B^{-1}\).
A must be square, symmetric, positive definite.
A preconditioner must be supplied that, given a vector q, returns an approximation to \((AB)^{-1} q\). Possible preconditioning is detailed in S. Gurol, PhD Manuscript, 2013. Note that the traditional \(B\)-preconditioning corresponds to precond= \(I\).
On entry:
dx = starting point.
dxh = starting point, \(B^{-1} dx_{0}\).
rr = residual at starting point.
B = \(B \).
C = \(C \).
precond = preconditioner \(F_k \approx (AB)^{-1} \).
On exit, dxh will contain \(B^{-1} x\) where x is the solution. The return value is the achieved reduction in residual norm.
Iteration will stop if the maximum iteration limit "maxiter" is reached or if the residual norm reduces by a factor of "tolerance".
Each matrix must implement a method:
void multiply(const VECTOR&, VECTOR&) const
which applies the matrix to the first argument, and returns the matrix-vector product in the second. (Note: the const is optional, but recommended.)
Definition at line 74 of file DRPLanczosMinimizer.h.
Member Typedef Documentation
Bmat_
template<typename MODEL > using oops::DRPLanczosMinimizer< MODEL >::Bmat_ = BMatrix<MODEL> private
Definition at line 75 of file DRPLanczosMinimizer.h.
CostFct_
template<typename MODEL > using oops::DRPLanczosMinimizer< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 76 of file DRPLanczosMinimizer.h.
CtrlInc_
template<typename MODEL > using oops::DRPLanczosMinimizer< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 77 of file DRPLanczosMinimizer.h.
HtRinvH_
template<typename MODEL > using oops::DRPLanczosMinimizer< MODEL >::HtRinvH_ = HtRinvHMatrix<MODEL> private
Definition at line 78 of file DRPLanczosMinimizer.h.
Constructor & Destructor Documentation
DRPLanczosMinimizer()
template<typename MODEL > oops::DRPLanczosMinimizer< MODEL >::DRPLanczosMinimizer (const eckit::Configuration & conf, const CostFct_ & J)
Definition at line 103 of file DRPLanczosMinimizer.h.
     : DRMinimizer<MODEL>(J),
       config_(conf),
       lmp_(conf),
       hvecs_(),
       vvecs_(),
       zvecs_(),
       alphas_(),
       betas_() {}
~DRPLanczosMinimizer()
template<typename MODEL > oops::DRPLanczosMinimizer< MODEL >::~DRPLanczosMinimizer () inline
Definition at line 83 of file DRPLanczosMinimizer.h.
 {}
Member Function Documentation
classname()
template<typename MODEL > const std::string oops::DRPLanczosMinimizer< MODEL >::classname () const inline override virtual
Implements oops::DRMinimizer< MODEL >.
Definition at line 81 of file DRPLanczosMinimizer.h.
 { return "DRPLanczosMinimizer"; }
solve()
template<typename MODEL > double oops::DRPLanczosMinimizer< MODEL >::solve (CtrlInc_ & dx, CtrlInc_ & dxh, CtrlInc_ & rr, const Bmat_ & B, const HtRinvH_ & HtRinvH, const double costJ0Jb, const double costJ0JoJc, const int maxiter, const double tolerance) override private virtual
Implements oops::DRMinimizer< MODEL >.
Definition at line 117 of file DRPLanczosMinimizer.h.
{
   // dx   increment
   // dxh  B^{-1} dx
   // rr   (sum B^{-1} dx_i^{b} +) G^T H^{-1} d
   CtrlInc_ zz(dxh);
   CtrlInc_ pr(dxh);
   CtrlInc_ vv(rr);
   CtrlInc_ mm(rr);
   std::vector<double> ss;
   std::vector<double> dd;
   // J0
   const double costJ0 = costJ0Jb + costJ0JoJc;
   lmp_.update(vvecs_, hvecs_, zvecs_, alphas_, betas_);
   // z_{0} = B LMP r_{0}
   lmp_.multiply(vv, pr);
   B.multiplyB(pr, zz);
   // beta_{0} = sqrt( z_{0}^T r_{0} )
   double beta = sqrt(dot_product(zz, vv));
   const double beta0 = beta;
   // v_{1} = r_{0} / beta_{0}
   vv *= 1 / beta;
   // pr_{1} = LMP r_{0} / beta_{0}
   pr *= 1 / beta;
   // z_{1} = z_{0} / beta_{0}
   zz *= 1 / beta;
   // hvecs[0] = pr_{1} --> required for solution
   hvecs_.emplace_back(new CtrlInc_(pr, config_));
   // zvecs[0] = z_{1} ---> for re-orthogonalization
   zvecs_.emplace_back(new CtrlInc_(zz, config_));
   // vvecs[0] = v_{1} ---> for re-orthogonalization
   vvecs_.emplace_back(new CtrlInc_(vv, config_));
   double normReduction = 1.0;
   Log::info() << std::endl;
   for (int jiter = 0; jiter < maxiter; ++jiter) {
     Log::info() << "DRPLanczos Starting Iteration " << jiter + 1 << std::endl;
     // v_{i+1} = ( pr_{i} + H^T R^{-1} H z_{i} ) - beta * v_{i-1}
     HtRinvH.multiply(zz, vv);
     B.multiplyId(pr, mm);
     vv += mm;
     if (jiter > 0) vv.axpy(-beta, *vvecs_[jiter - 1]);
     // alpha_{i} = v_{i+1}^T z_{i}
     double alpha = dot_product(zz, vv);
     // v_{i+1} = v_{i+1} - alpha_{i} v_{i}
     vv.axpy(-alpha, *vvecs_[jiter]);  // vv = vv - alpha * v_j
     // Re-orthogonalization
     for (int jj = 0; jj < jiter; ++jj) {
       double proj = dot_product(vv, *zvecs_[jj]);
       vv.axpy(-proj, *vvecs_[jj]);
     }
     // z_{i+1} = B LMP v_{i+1}
     lmp_.multiply(vv, pr);
     B.multiplyB(pr, zz);
     // beta_{i+1} = sqrt( zz_{i+1}^t, vv_{i+1} )
     beta = sqrt(dot_product(zz, vv));
     // v_{i+1} = v_{i+1} / beta_{i+1}
     vv *= 1 / beta;
     // pr_{i+1} = pr_{i+1} / beta_{i+1}
     pr *= 1 / beta;
     // z_{i+1} = z_{i+1} / beta_{i+1}
     zz *= 1 / beta;
     // hvecs[i+1] =pr_{i+1}
     hvecs_.emplace_back(new CtrlInc_(pr, config_));
     // zvecs[i+1] = z_{i+1}
     zvecs_.emplace_back(new CtrlInc_(zz, config_));
     // vvecs[i+1] = v_{i+1}
     vvecs_.emplace_back(new CtrlInc_(vv, config_));
     alphas_.push_back(alpha);
     if (jiter == 0) {
       ss.push_back(beta0 / alpha);
       dd.push_back(beta0);
     } else {
       // Solve the tridiagonal system T_{i} s_{i} = beta0 * e_1
       dd.push_back(beta0 * dot_product(*zvecs_[0], vv));
       TriDiagSolve(alphas_, betas_, dd, ss);
     }
     betas_.push_back(beta);
     // Compute the quadratic cost function
     // J[du_{i}] = J[0] - 0.5 s_{i}^T Z_{i}^T r_{0}
     // Jb[du_{i}] = 0.5 s_{i}^T V_{i}^T Z_{i} s_{i}
     double costJ = costJ0;
     double costJb = costJ0Jb;
     dx.zero();
     for (int jj = 0; jj < jiter + 1; ++jj) {
       dx.axpy(ss[jj], *zvecs_[jj]);
       // costJ -= 0.5 * ss[jj] * dot_product(*zvecs_[jj], rr);
       costJb += 0.5 * ss[jj] * dot_product(*vvecs_[jj], *zvecs_[jj]) * ss[jj];
     }
     costJ -= 0.5 * dot_product(dx, rr);
     double costJoJc = costJ - costJb;
     // Gradient norm in precond metric --> sqrt(r'z) --> beta * s_{i}
     double rznorm = beta * std::abs(ss[jiter]);
     normReduction = rznorm / beta0;
     Log::info() << "DRPLanczos end of iteration " << jiter + 1 << std::endl
                 << "  Norm reduction (" << std::setw(2) << jiter + 1
                 << ") = " << util::full_precision(normReduction) << std::endl
                 << "  Quadratic cost function: J   (" << std::setw(2)
                 << jiter + 1 << ") = " << util::full_precision(costJ)
                 << std::endl
                 << "  Quadratic cost function: Jb  (" << std::setw(2)
                 << jiter + 1 << ") = " << util::full_precision(costJb)
                 << std::endl
                 << "  Quadratic cost function: JoJc(" << std::setw(2)
                 << jiter + 1 << ") = " << util::full_precision(costJoJc)
                 << std::endl
                 << std::endl;
     if (normReduction < tolerance) {
       Log::info() << "DRPLanczos: Achieved required reduction in residual norm."
                   << std::endl;
       break;
     }
   }
   // Calculate the solution (dxh = Binv dx)
   dx.zero();
   for (unsigned int jj = 0; jj < ss.size(); ++jj) {
     dx.axpy(ss[jj], *zvecs_[jj]);
     dxh.axpy(ss[jj], *hvecs_[jj]);
   }
   return normReduction;
 }
References oops::ControlIncrement< MODEL >::axpy(), dot_product(), util::full_precision(), oops::HtRinvHMatrix< MODEL >::multiply(), oops::BMatrix< MODEL >::multiplyB(), oops::BMatrix< MODEL >::multiplyId(), oops::TriDiagSolve(), and oops::ControlIncrement< MODEL >::zero().
Member Data Documentation
alphas_
template<typename MODEL > std::vector<double> oops::DRPLanczosMinimizer< MODEL >::alphas_ private
Definition at line 96 of file DRPLanczosMinimizer.h.
betas_
template<typename MODEL > std::vector<double> oops::DRPLanczosMinimizer< MODEL >::betas_ private
Definition at line 97 of file DRPLanczosMinimizer.h.
config_
template<typename MODEL > const eckit::LocalConfiguration oops::DRPLanczosMinimizer< MODEL >::config_ private
Definition at line 90 of file DRPLanczosMinimizer.h.
hvecs_
template<typename MODEL > std::vector<std::unique_ptr<CtrlInc_> > oops::DRPLanczosMinimizer< MODEL >::hvecs_ private
Definition at line 93 of file DRPLanczosMinimizer.h.
lmp_
template<typename MODEL > SpectralLMP<CtrlInc_> oops::DRPLanczosMinimizer< MODEL >::lmp_ private
Definition at line 91 of file DRPLanczosMinimizer.h.
vvecs_
template<typename MODEL > std::vector<std::unique_ptr<CtrlInc_> > oops::DRPLanczosMinimizer< MODEL >::vvecs_ private
Definition at line 94 of file DRPLanczosMinimizer.h.
zvecs_
template<typename MODEL > std::vector<std::unique_ptr<CtrlInc_> > oops::DRPLanczosMinimizer< MODEL >::zvecs_ private
Definition at line 95 of file DRPLanczosMinimizer.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/DRPLanczosMinimizer.h