OOPS Documentation: oops::Increment4D< MODEL > Class Template Reference
oops::Increment4D< MODEL > Class Template Reference
Increment4D class.
#include <CostJbState.h>
Public Member Functions
Increment4D (const JbState_ &)
Constructor.
Increment4D (const Increment4D &, const bool copy=true)
Copy constructor.
Increment4D (const Increment4D &, const eckit::Configuration &)
Copy constructor with additional configuration.
Increment4D (const Geometry_ &, const Increment4D &)
Copy constructor with interpolation if required.
~Increment4D ()
Destructor.
void diff (const State4D_ &, const State4D_ &)
Compute 4D increment as a difference between two 4D states.
void zero ()
\(dx_1 = 0 \)
Increment4D & operator= (const Increment4D &)
\(dx_1 = dx_2 \)
Increment4D & operator+= (const Increment4D &)
\(dx_1 = dx_1 + dx_2 \)
Increment4D & operator-= (const Increment4D &)
\(dx_1 = dx_1 - dx_2 \)
Increment4D & operator*= (const double)
\(dx_1 = dx_1 * c \)
void axpy (const double, const Increment4D &)
\(dx_1 = dx_1 * c dx_2 \)
double dot_product_with (const Increment4D &) const
\(<dx_1,dx_1> = dx_1^T dx_1 \)
void read (const eckit::Configuration &)
Read increment.
void write (const eckit::Configuration &) const
Write increment.
Geometry_ geometry () const
Get geometry.
Increment_ & operator[] (const int ii)
Get a reference to i-th Increment.
const Increment_ & operator[] (const int ii) const
Get a constant reference to i-th Increment.
int first () const
Return the index of the first Increment.
int last () const
Return the index of the last Increment.
void shift_forward ()
To be removed.
void shift_backward ()
Static Public Member Functions
static const std::string classname ()
Private Types
using Geometry_ = Geometry< MODEL >
using Increment_ = Increment< MODEL >
using JbState_ = CostJbState< MODEL >
using State4D_ = State4D< MODEL >
using iter_ = typename std::map< int, std::unique_ptr< Increment_ > >::iterator
Iterator over a map of Increment objects.
using icst_ = typename std::map< int, std::unique_ptr< Increment_ > >::const_iterator
Constant iterator over a map of Increment objects.
Private Member Functions
Increment_ & get (const int)
Get a reference to i-th Increment.
const Increment_ & get (const int) const
Get a constant reference to i-th Increment.
void print (std::ostream &) const
Private Attributes
std::map< int, std::unique_ptr< Increment_ > > incr4d_
Map of Increment objects (key: integer; value: Increment pointer)
int first_
Index of the first Increment.
int last_
Index of the last Increment.
Detailed Description
template<typename MODEL>
class oops::Increment4D< MODEL >
Increment4D class.
The state increment contains the increment to the 3D or 4D state part of the control increment.
\(dx_{state4D} \) as implemented by Increment4D implements the state component of a ControlIncrement and contains a vector of Increment objects.
\[ dx_{state4D} = \begin{bmatrix} dx^0 \\ .. \\ dx^K \\ .. \\ dx^M \\ \end{bmatrix} \]
where \(dx^K \) corresponds to the Increment valid for K-th sub-window.
Definition at line 32 of file CostJbState.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::Increment4D< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 61 of file Increment4D.h.
icst_
template<typename MODEL > using oops::Increment4D< MODEL >::icst_ = typename std::map<int, std::unique_ptr<Increment_> >::const_iterator private
Constant iterator over a map of Increment objects.
Definition at line 131 of file Increment4D.h.
Increment_
template<typename MODEL > using oops::Increment4D< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 62 of file Increment4D.h.
iter_
template<typename MODEL > using oops::Increment4D< MODEL >::iter_ = typename std::map<int, std::unique_ptr<Increment_> >::iterator private
Iterator over a map of Increment objects.
Definition at line 128 of file Increment4D.h.
JbState_
template<typename MODEL > using oops::Increment4D< MODEL >::JbState_ = CostJbState<MODEL> private
Definition at line 63 of file Increment4D.h.
State4D_
template<typename MODEL > using oops::Increment4D< MODEL >::State4D_ = State4D<MODEL> private
Definition at line 64 of file Increment4D.h.
Constructor & Destructor Documentation
Increment4D() [1/4]
template<typename MODEL > oops::Increment4D< MODEL >::Increment4D (const JbState_ & jb) explicit
Constructor.
Definition at line 143 of file Increment4D.h.
     : incr4d_(), first_(0), last_(jb.nstates() - 1) {
   for (int jsub = 0; jsub <= last_; ++jsub) {
     std::unique_ptr<Increment_> incr(jb.newStateIncrement(jsub));
     incr4d_.emplace(jsub, std::move(incr));
   }
   Log::trace() << "Increment4D:Increment4D created." << std::endl;
 }
References oops::Increment4D< MODEL >::incr4d_, oops::Increment4D< MODEL >::last_, and oops::CostJbState< MODEL >::newStateIncrement().
Increment4D() [2/4]
template<typename MODEL > oops::Increment4D< MODEL >::Increment4D (const Increment4D< MODEL > & other, const bool copy = true)
Copy constructor.
Definition at line 153 of file Increment4D.h.
     : incr4d_(), first_(other.first_), last_(other.last_) {
   for (icst_ jsub = other.incr4d_.begin(); jsub != other.incr4d_.end();
        ++jsub) {
     int isub = jsub->first;
     std::unique_ptr<Increment_> incr(new Increment_(*jsub->second, copy));
     incr4d_.emplace(isub, std::move(incr));
   }
   Log::trace() << "Increment4D:Increment4D copied." << std::endl;
 }
References oops::Increment4D< MODEL >::incr4d_.
Increment4D() [3/4]
template<typename MODEL > oops::Increment4D< MODEL >::Increment4D (const Increment4D< MODEL > & other, const eckit::Configuration & tlConf)
Copy constructor with additional configuration.
Definition at line 165 of file Increment4D.h.
     : incr4d_(), first_(other.first_), last_(other.last_) {
   for (icst_ jsub = other.incr4d_.begin(); jsub != other.incr4d_.end();
        ++jsub) {
     int isub = jsub->first;
     std::unique_ptr<Increment_> incr(new Increment_(*jsub->second));
     incr4d_.emplace(isub, std::move(incr));
   }
   Log::trace() << "Increment4D:Increment4D copied." << std::endl;
 }
References oops::Increment4D< MODEL >::incr4d_.
Increment4D() [4/4]
template<typename MODEL > oops::Increment4D< MODEL >::Increment4D (const Geometry_ & geom, const Increment4D< MODEL > & other)
Copy constructor with interpolation if required.
Definition at line 178 of file Increment4D.h.
     : incr4d_(), first_(other.first_), last_(other.last_) {
   for (icst_ jsub = other.incr4d_.begin(); jsub != other.incr4d_.end();
        ++jsub) {
     int isub = jsub->first;
     std::unique_ptr<Increment_> incr(new Increment_(geom, *jsub->second));
     incr4d_.emplace(isub, std::move(incr));
   }
   Log::trace() << "Increment4D:Increment4D copied." << std::endl;
 }
References oops::Increment4D< MODEL >::incr4d_.
~Increment4D()
template<typename MODEL > oops::Increment4D< MODEL >::~Increment4D
Destructor.
Definition at line 204 of file Increment4D.h.
 {}
Member Function Documentation
axpy()
template<typename MODEL > void oops::Increment4D< MODEL >::axpy (const double zz, const Increment4D< MODEL > & rhs)
\(dx_1 = dx_1 * c dx_2 \)
Definition at line 256 of file Increment4D.h.
{
   for (iter_ jsub = incr4d_.begin(); jsub != incr4d_.end(); ++jsub) {
     jsub->second->axpy(zz, rhs[jsub->first]);
   }
 }
Referenced by oops::StaticCovariance4D< MODEL >::advectedMultiply(), oops::StaticCovariance4D< MODEL >::advectedMultiplySqrt(), oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::toControlVariableTimes(), and oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::toControlVariableTimes_ad().
classname()
template<typename MODEL > static const std::string oops::Increment4D< MODEL >::classname () inline static
Definition at line 67 of file Increment4D.h.
 { return "Increment4D"; }
diff()
template<typename MODEL > void oops::Increment4D< MODEL >::diff (const State4D_ & cv1, const State4D_ & cv2)
Compute 4D increment as a difference between two 4D states.
Definition at line 214 of file Increment4D.h.
{
   for (iter_ jsub = incr4d_.begin(); jsub != incr4d_.end(); ++jsub) {
     jsub->second->diff(cv1[jsub->first], cv2[jsub->first]);
   }
 }
Referenced by oops::CostJbJq< MODEL >::computeIncrement(), oops::CostJb4D< MODEL >::computeIncrement(), oops::CostJb3D< MODEL >::computeIncrement(), oops::JqTerm< MODEL >::computeModelError(), and oops::Minimizer< MODEL >::tlmTaylorTest().
dot_product_with()
template<typename MODEL > double oops::Increment4D< MODEL >::dot_product_with (const Increment4D< MODEL > & x2) const
\(<dx_1,dx_1> = dx_1^T dx_1 \)
Definition at line 292 of file Increment4D.h.
{
   double zz = 0.0;
   for (icst_ jsub = incr4d_.begin(); jsub != incr4d_.end(); ++jsub) {
     zz += dot_product(*jsub->second, x2[jsub->first]);
   }
   return zz;
 }
References dot_product().
first()
template<typename MODEL > int oops::Increment4D< MODEL >::first () const inline
Return the index of the first Increment.
Definition at line 112 of file Increment4D.h.
 { return first_; }
References oops::Increment4D< MODEL >::first_.
Referenced by oops::StaticCovariance4D< MODEL >::advectedMultiply(), oops::StaticWithTLModelCovariance4D< MODEL >::advectedMultiply(), oops::StaticCovariance4D< MODEL >::advectedMultiplySqrt(), oops::StaticWithTLModelCovariance4D< MODEL >::advectedMultiplySqrt(), oops::StaticCovariance4D< MODEL >::advectedMultiplySqrtTrans(), oops::StaticWithTLModelCovariance4D< MODEL >::advectedMultiplySqrtTrans(), oops::GenericMatrix< MODEL >::multiply(), oops::ObserverEnVarAD< MODEL, INCR >::ObserverEnVarAD(), oops::ObserverEnVarTL< MODEL, INCR >::ObserverEnVarTL(), oops::Increment4D< MODEL >::operator=(), oops::CostFctWeak< MODEL >::runAD(), oops::CostFctWeak< MODEL >::runTL(), oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::toControlVariableTimes(), oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::toControlVariableTimes_ad(), and oops::CostFctWeak< MODEL >::zeroAD().
geometry()
template<typename MODEL > Geometry_ oops::Increment4D< MODEL >::geometry () const inline
Get geometry.
Definition at line 105 of file Increment4D.h.
 { return this->get(first_).geometry(); }
References oops::Increment4D< MODEL >::first_, oops::Increment< MODEL >::geometry(), and oops::Increment4D< MODEL >::get().
Referenced by oops::ControlIncrement< MODEL >::geometry().
get() [1/2]
template<typename MODEL > Increment< MODEL > & oops::Increment4D< MODEL >::get (const int ii) private
Get a reference to i-th Increment.
Definition at line 190 of file Increment4D.h.
{
   iter_ it = incr4d_.find(ii);
   ASSERT(it != incr4d_.end());
   return *it->second;
 }
Referenced by oops::Increment4D< MODEL >::geometry(), and oops::Increment4D< MODEL >::operator[]().
get() [2/2]
template<typename MODEL > const Increment< MODEL > & oops::Increment4D< MODEL >::get (const int ii) const private
Get a constant reference to i-th Increment.
Definition at line 197 of file Increment4D.h.
{
   icst_ it = incr4d_.find(ii);
   ASSERT(it != incr4d_.end());
   return *it->second;
 }
last()
template<typename MODEL > int oops::Increment4D< MODEL >::last () const inline
Return the index of the last Increment.
Definition at line 114 of file Increment4D.h.
 { return last_; }
References oops::Increment4D< MODEL >::last_.
Referenced by oops::StaticCovariance4D< MODEL >::advectedMultiply(), oops::StaticWithTLModelCovariance4D< MODEL >::advectedMultiply(), oops::StaticCovariance4D< MODEL >::advectedMultiplySqrt(), oops::StaticWithTLModelCovariance4D< MODEL >::advectedMultiplySqrt(), oops::StaticCovariance4D< MODEL >::advectedMultiplySqrtTrans(), oops::StaticWithTLModelCovariance4D< MODEL >::advectedMultiplySqrtTrans(), oops::GenericMatrix< MODEL >::multiply(), oops::ObserverEnVarAD< MODEL, INCR >::ObserverEnVarAD(), oops::ObserverEnVarTL< MODEL, INCR >::ObserverEnVarTL(), oops::CostFctWeak< MODEL >::runAD(), oops::CostFctWeak< MODEL >::runTL(), oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::toControlVariableTimes(), oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::toControlVariableTimes_ad(), and oops::CostFctWeak< MODEL >::zeroAD().
operator*=()
template<typename MODEL > Increment4D< MODEL > & oops::Increment4D< MODEL >::operator*= (const double zz)
\(dx_1 = dx_1 * c \)
Definition at line 248 of file Increment4D.h.
{
   for (iter_ jsub = incr4d_.begin(); jsub != incr4d_.end(); ++jsub) {
     *jsub->second *= zz;
   }
   return *this;
 }
operator+=()
template<typename MODEL > Increment4D< MODEL > & oops::Increment4D< MODEL >::operator+= (const Increment4D< MODEL > & rhs)
\(dx_1 = dx_1 + dx_2 \)
Definition at line 232 of file Increment4D.h.
{
   for (int jsub = rhs.first(); jsub <= rhs.last(); ++jsub) {
     this->get(jsub) += rhs[jsub];
   }
   return *this;
 }
operator-=()
template<typename MODEL > Increment4D< MODEL > & oops::Increment4D< MODEL >::operator-= (const Increment4D< MODEL > & rhs)
\(dx_1 = dx_1 - dx_2 \)
Definition at line 240 of file Increment4D.h.
{
   for (int jsub = rhs.first(); jsub <= rhs.last(); ++jsub) {
     this->get(jsub) -= rhs[jsub];
   }
   return *this;
 }
operator=()
template<typename MODEL > Increment4D< MODEL > & oops::Increment4D< MODEL >::operator= (const Increment4D< MODEL > & rhs)
\(dx_1 = dx_2 \)
Definition at line 221 of file Increment4D.h.
{
   incr4d_.clear();
   for (icst_ jsub = rhs.incr4d_.begin(); jsub != rhs.incr4d_.end(); ++jsub) {
     int isub = jsub->first;
     std::unique_ptr<Increment_> incr(new Increment_(*jsub->second));
     incr4d_.emplace(isub, std::move(incr));
   }
   return *this;
 }
References oops::Increment4D< MODEL >::first().
operator[]() [1/2]
template<typename MODEL > Increment_& oops::Increment4D< MODEL >::operator[] (const int ii) inline
Get a reference to i-th Increment.
Definition at line 108 of file Increment4D.h.
 { return this->get(ii); }
References oops::Increment4D< MODEL >::get().
operator[]() [2/2]
template<typename MODEL > const Increment_& oops::Increment4D< MODEL >::operator[] (const int ii) const inline
Get a constant reference to i-th Increment.
Definition at line 110 of file Increment4D.h.
 { return this->get(ii); }
References oops::Increment4D< MODEL >::get().
print()
template<typename MODEL > void oops::Increment4D< MODEL >::print (std::ostream & outs) const private
Definition at line 285 of file Increment4D.h.
{
   for (icst_ jsub = incr4d_.begin(); jsub != incr4d_.end(); ++jsub) {
     outs << *jsub->second << std::endl;
   }
 }
read()
template<typename MODEL > void oops::Increment4D< MODEL >::read (const eckit::Configuration & config)
Read increment.
Definition at line 263 of file Increment4D.h.
{
   std::vector<eckit::LocalConfiguration> confs;
   config.get("increment", confs);
   ASSERT(incr4d_.size() == confs.size());
   for (iter_ jsub = incr4d_.begin(); jsub != incr4d_.end(); ++jsub) {
     Log::debug() << "Increment4D:read" << confs[jsub->first] << std::endl;
     jsub->second->read(confs[jsub->first]);
   }
 }
shift_backward()
template<typename MODEL > void oops::Increment4D< MODEL >::shift_backward
Definition at line 314 of file Increment4D.h.
{
   for (iter_ jsub = incr4d_.begin(); jsub != incr4d_.end(); ++jsub) {
     const int isub = jsub->first;
     if (isub < last_) this->get(isub) = this->get(isub + 1);
   }
   incr4d_.erase(last_);
   Log::info() << "Increment4D::shift_backward erased " << last_ << std::endl;
   last_ -= 1;
 }
Referenced by oops::CostFctWeak< MODEL >::runAD().
shift_forward()
template<typename MODEL > void oops::Increment4D< MODEL >::shift_forward
To be removed.
Definition at line 301 of file Increment4D.h.
{
   using rit =
       typename std::map<int, std::unique_ptr<Increment_>>::reverse_iterator;
   for (rit jsub = incr4d_.rbegin(); jsub != incr4d_.rend(); ++jsub) {
     const int isub = jsub->first;
     if (isub > first_) this->get(isub) = this->get(isub - 1);
   }
   incr4d_.erase(first_);
   Log::info() << "Increment4D::shift_forward erased " << first_ << std::endl;
   first_ += 1;
 }
Referenced by oops::CostFctWeak< MODEL >::runTL().
write()
template<typename MODEL > void oops::Increment4D< MODEL >::write (const eckit::Configuration & config) const
Write increment.
Definition at line 274 of file Increment4D.h.
{
   std::vector<eckit::LocalConfiguration> confs;
   config.get("increment", confs);
   ASSERT(incr4d_.size() == confs.size());
   for (icst_ jsub = incr4d_.begin(); jsub != incr4d_.end(); ++jsub) {
     Log::debug() << "Increment4D:write" << confs[jsub->first] << std::endl;
     jsub->second->write(confs[jsub->first]);
   }
 }
Referenced by oops::CostJbTotal< MODEL >::writeIncrement().
zero()
template<typename MODEL > void oops::Increment4D< MODEL >::zero
\(dx_1 = 0 \)
Definition at line 207 of file Increment4D.h.
{
   for (iter_ jsub = incr4d_.begin(); jsub != incr4d_.end(); ++jsub) {
     jsub->second->zero();
   }
 }
Referenced by oops::StaticCovariance4D< MODEL >::advectedInverseMultiply(), oops::HybridCovariance4D< MODEL >::advectedInverseMultiply(), oops::EnsembleCovariance4D< MODEL >::advectedInverseMultiply(), oops::EnsembleCovariance4DScaleDependent< MODEL >::advectedInverseMultiply(), oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::advectedInverseMultiply(), oops::EnsembleCovariance4DDistributed< MODEL >::advectedInverseMultiply(), oops::EnsembleCovsInterpol4D< MODEL >::advectedInverseMultiply(), oops::StaticWithTLModelCovariance4D< MODEL >::advectedInverseMultiply(), oops::StaticCovariance4D< MODEL >::advectedMultiply(), oops::EnsembleCovariance4D< MODEL >::advectedMultiply(), oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::advectedMultiply(), oops::EnsembleCovariance4DScaleDependent< MODEL >::advectedMultiply(), oops::EnsembleCovsInterpol4D< MODEL >::advectedMultiply(), oops::EnsembleCovariance4DDistributed< MODEL >::advectedMultiply(), oops::StaticWithTLModelCovariance4D< MODEL >::advectedMultiply(), oops::StaticCovariance4D< MODEL >::advectedMultiplySqrt(), oops::EnsembleCovariance4D< MODEL >::advectedMultiplySqrt(), oops::EnsembleCovariance4DScaleDependent< MODEL >::advectedMultiplySqrt(), oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::advectedMultiplySqrt(), oops::EnsembleCovsInterpol4D< MODEL >::advectedMultiplySqrt(), oops::EnsembleCovariance4DDistributed< MODEL >::advectedMultiplySqrt(), oops::StaticWithTLModelCovariance4D< MODEL >::advectedMultiplySqrt(), oops::EnsembleCovsInterpol4D< MODEL >::advectedMultiplySqrtTrans(), oops::CostJb4D< MODEL >::computeIncrement(), oops::CostFct3DVar< MODEL >::zeroAD(), oops::CostFctWeak< MODEL >::zeroAD(), oops::CostFct4DVar< MODEL >::zeroAD(), oops::CostFct4DVarHyb4D< MODEL >::zeroAD(), oops::CostFct4DEnsVar< MODEL >::zeroAD(), oops::CostFct4DEnVar< MODEL >::zeroAD(), and oops::CostFct4DVarMFTemplate< MODEL >::zeroAD().
Member Data Documentation
first_
template<typename MODEL > int oops::Increment4D< MODEL >::first_ private
Index of the first Increment.
Definition at line 135 of file Increment4D.h.
Referenced by oops::Increment4D< MODEL >::first(), and oops::Increment4D< MODEL >::geometry().
incr4d_
template<typename MODEL > std::map<int, std::unique_ptr<Increment_> > oops::Increment4D< MODEL >::incr4d_ private
Map of Increment objects (key: integer; value: Increment pointer)
Definition at line 133 of file Increment4D.h.
Referenced by oops::Increment4D< MODEL >::Increment4D().
last_
template<typename MODEL > int oops::Increment4D< MODEL >::last_ private
Index of the last Increment.
Definition at line 137 of file Increment4D.h.
Referenced by oops::Increment4D< MODEL >::Increment4D(), and oops::Increment4D< MODEL >::last().
The documentation for this class was generated from the following files:
src/oops/assimilation/CostJbState.h
src/oops/assimilation/Increment4D.h