OOPS Documentation: oops::UtHtRinvHUMatrix< MODEL > Class Template Reference
oops::UtHtRinvHUMatrix< MODEL > Class Template Reference
The \(U^T H^T R^{-1} H U\) matrix.
#include <UtHtRinvHUMatrix.h>
Public Member Functions
UtHtRinvHUMatrix (const CostFct_ &j, const eckit::Configuration &config)
void multiply (const CtrlVec_ &dv, CtrlVec_ &dz) const
void computeDiagnostics (std::vector< double > &ss, const bool &convergenceReached) const
Private Types
using Increment_ = Increment< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using CtrlVec_ = ControlVector< MODEL >
using CostFct_ = CostFunction< MODEL >
using CostJo_ = CostJo< MODEL >
using Departures_ = Departures< MODEL >
Private Attributes
const eckit::LocalConfiguration config_
const CostFct_ & j_
CtrlInc_ dx_
CtrlInc_ mdx_
CtrlInc_ dz_
std::unique_ptr< DualVector< MODEL > > ww_
std::unique_ptr< DualVector< MODEL > > zz_
std::vector< DualVector< MODEL > > wwhudvvec_
bool diags_
unsigned iter_
Detailed Description
template<typename MODEL>
class oops::UtHtRinvHUMatrix< MODEL >
The \(U^T H^T R^{-1} H U\) matrix.
The solvers represent matrices as objects that implement a "multiply" method. This class defines objects that apply a generalized \(U^T H^T R^{-1} H U\) matrix that also includes the equivalent operators for the other terms of the cost function.
Definition at line 44 of file UtHtRinvHUMatrix.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::UtHtRinvHUMatrix< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 48 of file UtHtRinvHUMatrix.h.
CostJo_
template<typename MODEL > using oops::UtHtRinvHUMatrix< MODEL >::CostJo_ = CostJo<MODEL> private
Definition at line 49 of file UtHtRinvHUMatrix.h.
CtrlInc_
template<typename MODEL > using oops::UtHtRinvHUMatrix< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 46 of file UtHtRinvHUMatrix.h.
CtrlVec_
template<typename MODEL > using oops::UtHtRinvHUMatrix< MODEL >::CtrlVec_ = ControlVector<MODEL> private
Definition at line 47 of file UtHtRinvHUMatrix.h.
Departures_
template<typename MODEL > using oops::UtHtRinvHUMatrix< MODEL >::Departures_ = Departures<MODEL> private
Definition at line 50 of file UtHtRinvHUMatrix.h.
Increment_
template<typename MODEL > using oops::UtHtRinvHUMatrix< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 45 of file UtHtRinvHUMatrix.h.
Constructor & Destructor Documentation
UtHtRinvHUMatrix()
template<typename MODEL > oops::UtHtRinvHUMatrix< MODEL >::UtHtRinvHUMatrix (const CostFct_ & j, const eckit::Configuration & config) explicit
Definition at line 75 of file UtHtRinvHUMatrix.h.
     : j_(j),
       dx_(j.jb().getFirstGuessIncrement(), false),
       mdx_(j.jb().getFirstGuessIncrement(), false),
       dz_(j.jb().getFirstGuessIncrement(), false),
       ww_(),
       zz_(),
       wwhudvvec_(),
       diags_(config.has("onlineDiagnostics")),
       config_(config),
       iter_(0) {}
Member Function Documentation
computeDiagnostics()
template<typename MODEL > void oops::UtHtRinvHUMatrix< MODEL >::computeDiagnostics (std::vector< double > & ss, const bool & convergenceReached) const
Definition at line 140 of file UtHtRinvHUMatrix.h.
{
   if (diags_ && (iter_ <= 2 || convergenceReached)) {
     Log::info() << "Online diagnostics:" << std::endl
                 << "------------------" << std::endl;
     // Quadratic JO-table
     for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
       if (j_.jterm(jj).classname() == "Jo") {
         const CostJo_ &jo = dynamic_cast<const CostJo_ &>(j_.jterm(jj));
         // We would like to compute H dx = H U dv
         // Note that dv = sum_i=1^N dv[ii] ss[ii]
         DualVector<MODEL> wwhudv(wwhudvvec_[0]);
         DualVector<MODEL> wwhudvii(wwhudvvec_[0]);
         DualVector<MODEL> dd;
         DualVector<MODEL> zz;
         wwhudv.zero();
         wwhudvii.zero();
         for (unsigned ii = 0; ii < iter_; ++ii) {
           // compute H U dv[i] ss[i]
           wwhudvii = wwhudvvec_[ii];
           wwhudvii *= ss[ii];
           // compute H dx = H U dv = sum_i=1^N H U dv[ii] ss[ii]
           wwhudv += wwhudvii;
         }
         // Release d = y - H_NL(x)
         dd.append(j_.jterm(jj).newDepartures());
         // Compute dp = y - H_NL(x) - H(dx) = d - H(dx)
         dd -= wwhudv;
         // Compute R^-1 (dp)
         zz.append(j_.jterm(jj).multiplyCoInv(*dd.getv(jj)));
         // print JO table
         jo.printJo(dynamic_cast<const Departures_ &>(*dd.getv(jj)),
                    dynamic_cast<const Departures_ &>(*zz.getv(jj)),
                    CostJo_::OS::Quadratic);
         if (config_.has("onlineDiagnostics.residue")) {
           dynamic_cast<const Departures_ &>(*dd.getv(jj)).save(
             eckit::LocalConfiguration(config_, "onlineDiagnostics.residue"));
         }
         Log::info() << "----------" << std::endl;
       }
     }
     // Online adjoint test
     // <G dx, dy>, where dy = Rinv H dx
     double adj_tst_fwd = dot_product(*ww_, *zz_);
     // <dx, Gt dy> , where dy = Rinv H dx
     double adj_tst_bwd = dot_product(dx_, dz_);
     Log::info() << "Online adjoint test, iteration: " << iter_ << std::endl
                 << util::PrintAdjTest(adj_tst_fwd, adj_tst_bwd, "G")
                 << "----------" << std::endl;
   }
 }
References oops::DualVector< MODEL >::append(), dot_product(), oops::DualVector< MODEL >::getv(), oops::CostJo< MODEL >::printJo(), and oops::DualVector< MODEL >::zero().
Referenced by oops::SQRTPLanczosMinimizer< MODEL >::solve().
multiply()
template<typename MODEL > void oops::UtHtRinvHUMatrix< MODEL >::multiply (const CtrlVec_ & dv, CtrlVec_ & dz) const
Definition at line 90 of file UtHtRinvHUMatrix.h.
{
   // Increment counter
   iter_++;
   // Multiply by the square root of the covariance
   j_.jb().multiplyBsqrt(dvin, dx_);
   // Setup TL terms of cost function
   PostProcessorTL<Increment_> costtl;
   for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
     costtl.enrollProcessor(j_.jterm(jj).setupTL(dx_));
   }
   // Run TLM
   mdx_ = dx_;
   j_.runTL(mdx_, costtl);
   // Get TLM outputs, multiply by covariance inverses, and setup ADJ forcing
   // terms
   j_.zeroAD(dz_);
   PostProcessorAD<Increment_> costad;
   ww_.reset(new DualVector<MODEL>());
   zz_.reset(new DualVector<MODEL>());
   for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
     ww_->append(costtl.releaseOutputFromTL(jj));
     if (diags_ && j_.jterm(jj).classname() == "Jo") {
       // Required for diagnostic quadratic JO-table
       //  save H dx[i]= H U dv[i], where
       //       dx = sum_i=1^N dx[i] = U sum_i=1^N dv[i] ss[i]
       DualVector<MODEL> wwhudvii;
       wwhudvii.append(costtl.releaseOutputFromTL(jj));
       wwhudvvec_.push_back(wwhudvii);
     }
     zz_->append(j_.jterm(jj).multiplyCoInv(*ww_->getv(jj)));
     costad.enrollProcessor(j_.jterm(jj).setupAD(zz_->getv(jj), dz_));
   }
   // Run ADJ
   j_.runAD(dz_, costad);
   // Multiply by the transpose of the square root of the covariance
   j_.jb().multiplyBsqrtTrans(dz_, dvout);
 }
References oops::DualVector< MODEL >::append(), oops::PostProcessorAD< INCR >::enrollProcessor(), oops::PostProcessorTL< INCR >::enrollProcessor(), and oops::PostProcessorTL< INCR >::releaseOutputFromTL().
Referenced by oops::SQRTBPFOMMinimizer< MODEL >::solve(), oops::SQRTBPLanczosMinimizer< MODEL >::solve(), oops::SQRTPCGMinimizer< MODEL >::solve(), oops::SQRTBPCGMinimizer< MODEL >::solve(), and oops::SQRTPLanczosMinimizer< MODEL >::solve().
Member Data Documentation
config_
template<typename MODEL > const eckit::LocalConfiguration oops::UtHtRinvHUMatrix< MODEL >::config_ private
Definition at line 60 of file UtHtRinvHUMatrix.h.
diags_
template<typename MODEL > bool oops::UtHtRinvHUMatrix< MODEL >::diags_ private
Definition at line 68 of file UtHtRinvHUMatrix.h.
dx_
template<typename MODEL > CtrlInc_ oops::UtHtRinvHUMatrix< MODEL >::dx_ mutable private
Definition at line 62 of file UtHtRinvHUMatrix.h.
dz_
template<typename MODEL > CtrlInc_ oops::UtHtRinvHUMatrix< MODEL >::dz_ mutable private
Definition at line 64 of file UtHtRinvHUMatrix.h.
iter_
template<typename MODEL > unsigned oops::UtHtRinvHUMatrix< MODEL >::iter_ mutable private
Definition at line 69 of file UtHtRinvHUMatrix.h.
j_
template<typename MODEL > const CostFct_& oops::UtHtRinvHUMatrix< MODEL >::j_ private
Definition at line 61 of file UtHtRinvHUMatrix.h.
mdx_
template<typename MODEL > CtrlInc_ oops::UtHtRinvHUMatrix< MODEL >::mdx_ mutable private
Definition at line 63 of file UtHtRinvHUMatrix.h.
ww_
template<typename MODEL > std::unique_ptr<DualVector<MODEL> > oops::UtHtRinvHUMatrix< MODEL >::ww_ mutable private
Definition at line 65 of file UtHtRinvHUMatrix.h.
wwhudvvec_
template<typename MODEL > std::vector<DualVector<MODEL> > oops::UtHtRinvHUMatrix< MODEL >::wwhudvvec_ mutable private
Definition at line 67 of file UtHtRinvHUMatrix.h.
zz_
template<typename MODEL > std::unique_ptr<DualVector<MODEL> > oops::UtHtRinvHUMatrix< MODEL >::zz_ mutable private
Definition at line 66 of file UtHtRinvHUMatrix.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/UtHtRinvHUMatrix.h