OOPS Documentation: oops::State4D< MODEL > Class Template Reference
oops::State4D< MODEL > Class Template Reference
Four dimensional state.
#include <CostJbState.h>
Public Member Functions
State4D (const eckit::Configuration &, const Geometry_ &, const Model_ &)
The arguments define the number of sub-windows and the resolution.
State4D (const State4D &)
State4D (const Geometry_ &, const State4D &)
~State4D ()
void read (const eckit::Configuration &)
I/O and diagnostics.
void write (const eckit::Configuration &) const
double norm () const
bool checkStatesNumber (const unsigned int nn) const
Get model space control variable.
unsigned int statesNumber () const
State_ & operator[] (const int ii)
const State_ & operator[] (const int ii) const
Static Public Member Functions
static const std::string classname ()
Private Types
using Geometry_ = Geometry< MODEL >
using State_ = State< MODEL >
using Model_ = Model< MODEL >
Private Member Functions
State4D & operator= (const State4D &)
void print (std::ostream &) const
Private Attributes
std::vector< std::unique_ptr< State_ > > state4d_
Detailed Description
template<typename MODEL>
class oops::State4D< MODEL >
Four dimensional state.
The 4D state is mostly used as part of the VDA control variable.
Definition at line 48 of file CostJbState.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::State4D< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 39 of file State4D.h.
Model_
template<typename MODEL > using oops::State4D< MODEL >::Model_ = Model<MODEL> private
Definition at line 41 of file State4D.h.
State_
template<typename MODEL > using oops::State4D< MODEL >::State_ = State<MODEL> private
Definition at line 40 of file State4D.h.
Constructor & Destructor Documentation
State4D() [1/3]
template<typename MODEL > oops::State4D< MODEL >::State4D (const eckit::Configuration & config, const Geometry_ & resol, const Model_ & model)
The arguments define the number of sub-windows and the resolution.
Definition at line 75 of file State4D.h.
{
   std::vector<eckit::LocalConfiguration> files;
   config.get("state", files);
   for (size_t jsub = 0; jsub < files.size(); ++jsub) {
     State_ *js = new State_(resol, model, files[jsub]);
     state4d_.emplace_back(js);
   }
   Log::trace() << "State4D constructed." << std::endl;
 }
State4D() [2/3]
template<typename MODEL > oops::State4D< MODEL >::State4D (const State4D< MODEL > & other) explicit
Definition at line 90 of file State4D.h.
{
   for (const auto &js : other.state4d_) {
     state4d_.emplace_back(new State_(*js));
   }
   Log::trace() << "State4D copied." << std::endl;
 }
State4D() [3/3]
template<typename MODEL > oops::State4D< MODEL >::State4D (const Geometry_ & resol, const State4D< MODEL > & other)
Definition at line 100 of file State4D.h.
{
   for (const auto &js : other.state4d_) {
     state4d_.emplace_back(new State_(resol, *js));
   }
   Log::trace() << "State4D copied." << std::endl;
 }
~State4D()
template<typename MODEL > oops::State4D< MODEL >::~State4D
Definition at line 110 of file State4D.h.
{
   Log::trace() << "State4D destructed." << std::endl;
 }
Member Function Documentation
checkStatesNumber()
template<typename MODEL > bool oops::State4D< MODEL >::checkStatesNumber (const unsigned int nn) const inline
Get model space control variable.
Definition at line 58 of file State4D.h.
{
     return state4d_.size() == nn;
   }
References oops::State4D< MODEL >::state4d_.
Referenced by oops::CostFct3DVar< MODEL >::addIncr(), oops::CostFct4DVar< MODEL >::addIncr(), oops::CostFct4DVarTrajHR< MODEL >::addIncr(), oops::CostFct4DVarMF< MODEL >::addIncr(), oops::CostJbJq< MODEL >::linearize(), oops::CostJb3D< MODEL >::linearize(), oops::CostFct3DVar< MODEL >::newJb(), oops::CostFct4DVar< MODEL >::newJb(), oops::CostFct4DVarMF< MODEL >::newJb(), oops::CostFct3DVar< MODEL >::runNL(), oops::CostFct4DVar< MODEL >::runNL(), and oops::CostFct4DVarMF< MODEL >::runNL().
classname()
template<typename MODEL > static const std::string oops::State4D< MODEL >::classname () inline static
Definition at line 44 of file State4D.h.
 { return "State4D"; }
norm()
template<typename MODEL > double oops::State4D< MODEL >::norm
Definition at line 160 of file State4D.h.
{
   double zn = 0.0;
   for (const std::unique_ptr<State_> &js : state4d_) {
     double zz = js->norm();
     zn += zz * zz;
   }
   return sqrt(zn);
 }
operator=()
template<typename MODEL > State4D& oops::State4D< MODEL >::operator= (const State4D< MODEL > &) private
operator[]() [1/2]
template<typename MODEL > State_& oops::State4D< MODEL >::operator[] (const int ii) inline
Definition at line 62 of file State4D.h.
 { return *state4d_[ii]; }
References oops::State4D< MODEL >::state4d_.
operator[]() [2/2]
template<typename MODEL > const State_& oops::State4D< MODEL >::operator[] (const int ii) const inline
Definition at line 63 of file State4D.h.
 { return *state4d_[ii]; }
References oops::State4D< MODEL >::state4d_.
print()
template<typename MODEL > void oops::State4D< MODEL >::print (std::ostream & outs) const private
Definition at line 151 of file State4D.h.
{
   for (const std::unique_ptr<State_> &js : state4d_) {
     outs << *js << std::endl;
   }
 }
read()
template<typename MODEL > void oops::State4D< MODEL >::read (const eckit::Configuration & config)
I/O and diagnostics.
Definition at line 117 of file State4D.h.
{
   std::vector<eckit::LocalConfiguration> confs;
   if (config.has("state")) {
     config.get("state", confs);
     ASSERT(state4d_.size() == confs.size());
     unsigned jsub = 0;
     for (std::unique_ptr<State_> &js : state4d_) {
       Log::debug() << "State4D::read" << confs[jsub] << std::endl;
       js->read(confs[jsub]);
       ++jsub;
     }
   }
 }
statesNumber()
template<typename MODEL > unsigned int oops::State4D< MODEL >::statesNumber () const inline
Definition at line 61 of file State4D.h.
 { return state4d_.size(); }
References oops::State4D< MODEL >::state4d_.
Referenced by oops::CostJb4D< MODEL >::computeIncrement(), and oops::CostJb4D< MODEL >::CostJb4D().
write()
template<typename MODEL > void oops::State4D< MODEL >::write (const eckit::Configuration & config) const
Definition at line 134 of file State4D.h.
{
   std::vector<eckit::LocalConfiguration> confs;
   if (config.has("state")) {
     config.get("state", confs);
     ASSERT(state4d_.size() == confs.size());
     unsigned int jsub = 0;
     for (const std::unique_ptr<State_> &js : state4d_) {
       Log::debug() << "State4D::write" << confs[jsub] << std::endl;
       js->write(confs[jsub]);
       ++jsub;
     }
   }
 }
Member Data Documentation
state4d_
template<typename MODEL > std::vector<std::unique_ptr<State_> > oops::State4D< MODEL >::state4d_ private
Definition at line 69 of file State4D.h.
Referenced by oops::State4D< MODEL >::checkStatesNumber(), oops::State4D< MODEL >::operator[](), and oops::State4D< MODEL >::statesNumber().
The documentation for this class was generated from the following files:
src/oops/assimilation/CostJbState.h
src/oops/assimilation/State4D.h