OOPS Documentation: oops::SaddlePointLMPMatrix< MODEL > Class Template Reference
oops::SaddlePointLMPMatrix< MODEL > Class Template Reference
The preconditioner for the saddle-point minimizer.
#include <SaddlePointLMPMatrix.h>
Public Member Functions
SaddlePointLMPMatrix (const CostFct_ &j)
void setup (const std::vector< SPVector_ > &, const std::vector< SPVector_ > &)
const int & getk () const
void multiply (const SPVector_ &, SPVector_ &) const
Private Types
using Increment_ = Increment< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using CostFctWeak_ = CostFctWeak< MODEL >
using CostFct_ = CostFunction< MODEL >
using SPVector_ = SaddlePointVector< MODEL >
using LagVector_ = DualVector< MODEL >
Private Member Functions
void Pinitmultiply (const SPVector_ &, SPVector_ &) const
void Gmultiply (const SPVector_ &, Eigen::VectorXd &) const
void Rmultiply (Eigen::VectorXd &, SPVector_ &) const
void Fmultiply (Eigen::VectorXd &, Eigen::VectorXd &) const
Private Attributes
const CostFctWeak_ & j_
const bool idmodel_
std::vector< SPVector_ > xyVEC_
std::vector< SPVector_ > pqVEC_
std::vector< LagVector_ > RpVEC_
std::vector< CtrlInc_ > RqVEC_
std::unique_ptr< SPVector_ > spvecinit_
int nvec_
Eigen::MatrixXd ZMat_
Eigen::MatrixXd FMat_
Detailed Description
template<typename MODEL>
class oops::SaddlePointLMPMatrix< MODEL >
The preconditioner for the saddle-point minimizer.
The preconditioner is obtained by using low-rank updates. Let us define the matrices:
\(R = [ 0 Rp ], G = [ Zinv*Rp' 0 ] \) \([ Rq 0 ] [ 0 Zinv'*Rq' ] \)
\(F = I + G*P0inv*R \)
where \(P0 \) is the initial preconditioner and \(I \) is the identity matrix of order 2.
Then the preconditioner is updated from
\(Pk = P0inv - P0inv*R*Finv*G*P0inv \)
The solvers represent matrices as objects that implement a "multiply" method. This class defines objects that apply the saddle-point matrix.
Definition at line 57 of file SaddlePointLMPMatrix.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::SaddlePointLMPMatrix< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 61 of file SaddlePointLMPMatrix.h.
CostFctWeak_
template<typename MODEL > using oops::SaddlePointLMPMatrix< MODEL >::CostFctWeak_ = CostFctWeak<MODEL> private
Definition at line 60 of file SaddlePointLMPMatrix.h.
CtrlInc_
template<typename MODEL > using oops::SaddlePointLMPMatrix< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 59 of file SaddlePointLMPMatrix.h.
Increment_
template<typename MODEL > using oops::SaddlePointLMPMatrix< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 58 of file SaddlePointLMPMatrix.h.
LagVector_
template<typename MODEL > using oops::SaddlePointLMPMatrix< MODEL >::LagVector_ = DualVector<MODEL> private
Definition at line 63 of file SaddlePointLMPMatrix.h.
SPVector_
template<typename MODEL > using oops::SaddlePointLMPMatrix< MODEL >::SPVector_ = SaddlePointVector<MODEL> private
Definition at line 62 of file SaddlePointLMPMatrix.h.
Constructor & Destructor Documentation
SaddlePointLMPMatrix()
template<typename MODEL > oops::SaddlePointLMPMatrix< MODEL >::SaddlePointLMPMatrix (const CostFct_ & j) explicit
Definition at line 98 of file SaddlePointLMPMatrix.h.
     : j_(dynamic_cast<const CostFctWeak_ &>(j)), idmodel_(false) {}
Member Function Documentation
Fmultiply()
template<typename MODEL > void oops::SaddlePointLMPMatrix< MODEL >::Fmultiply (Eigen::VectorXd & x, Eigen::VectorXd & fx) const private
Definition at line 274 of file SaddlePointLMPMatrix.h.
{
   SaddlePointPrecondMatrix<MODEL> P0inv(j_);
   SPVector_ tmp(*spvecinit_);
   SPVector_ tmp2(*spvecinit_);
   Eigen::VectorXd ww(2 * nvec_);
   fx = x;
   this->Rmultiply(x, tmp);
   P0inv.multiply(tmp, tmp2);
   this->Gmultiply(tmp2, ww);
   fx += ww;
 }
References oops::SaddlePointPrecondMatrix< MODEL >::multiply().
getk()
template<typename MODEL > const int& oops::SaddlePointLMPMatrix< MODEL >::getk () const inline
Definition at line 70 of file SaddlePointLMPMatrix.h.
 { return nvec_; }
References oops::SaddlePointLMPMatrix< MODEL >::nvec_.
Gmultiply()
template<typename MODEL > void oops::SaddlePointLMPMatrix< MODEL >::Gmultiply (const SPVector_ & x, Eigen::VectorXd & z) const private
Definition at line 235 of file SaddlePointLMPMatrix.h.
{
   Eigen::VectorXd v1(nvec_);
   Eigen::VectorXd v2(nvec_);
   Eigen::VectorXd ax(nvec_);
   Eigen::VectorXd axt(nvec_);
   Eigen::MatrixXd ZMatt(nvec_, nvec_);
   ZMatt = ZMat_.transpose();
   // Rp'*x and Rq'*y
   for (unsigned jj = 0; jj < nvec_; ++jj) {
     v1(jj) = dot_product(RpVEC_[jj], x.lambda());
     v2(jj) = dot_product(RqVEC_[jj], x.dx());
   }
   ax = ZMat_.colPivHouseholderQr().solve(v1);   // Zinv*Rp'*x
   axt = ZMatt.colPivHouseholderQr().solve(v2);  // Ztinv*Rq'*y
   z << ax, axt;                                 // z = [ax ; axt]
 }
References dot_product(), oops::SaddlePointVector< MODEL >::dx(), and oops::SaddlePointVector< MODEL >::lambda().
multiply()
template<typename MODEL > void oops::SaddlePointLMPMatrix< MODEL >::multiply (const SPVector_ & x, SPVector_ & z) const
Definition at line 213 of file SaddlePointLMPMatrix.h.
{
   // z = P0inv*x - P0inv*R*Finv*G*P0inv*x
   SaddlePointPrecondMatrix<MODEL> P0inv(j_);
   SPVector_ svw(x);
   SPVector_ svt(x);
   P0inv.multiply(x, z);
   if (nvec_ != 0) {
     Eigen::VectorXd rhs(2 * nvec_);
     Eigen::VectorXd finvx(2 * nvec_);
     this->Gmultiply(z, rhs);                         // rhs = G*z
     finvx = FMat_.colPivHouseholderQr().solve(rhs);  // finvx = Finv*rhs
     this->Rmultiply(finvx, svw);                     // svw = R * finvx
     P0inv.multiply(svw, svt);                        // svt = P0inv * svw
     z -= svt;                                        // z = z - svt
   }
 }
References oops::SaddlePointPrecondMatrix< MODEL >::multiply().
Pinitmultiply()
template<typename MODEL > void oops::SaddlePointLMPMatrix< MODEL >::Pinitmultiply (const SPVector_ & x, SPVector_ & z) const private
Definition at line 161 of file SaddlePointLMPMatrix.h.
{
   //  P0 = [D   0   L]
   //       [0   R   0]
   //       [Lt  0   0]
   //
   //  where M = I.
   CtrlInc_ ww(x.lambda().dx());
   // ADJ block
   j_.runAD(ww, true);
   z.dx() = x.lambda().dx();
   z.dx() -= ww;
   // TLM block
   ww = x.dx();
   j_.runTL(ww, true);
   z.lambda().zero();
   z.lambda().dx() = x.dx();
   z.lambda().dx() -= ww;
   // Diagonal block
   DualVector<MODEL> diag;
   diag.dx(new CtrlInc_(j_.jb()));
   j_.jb().multiplyB(x.lambda().dx(), diag.dx());
   for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
     diag.append(j_.jterm(jj).multiplyCovar(*x.lambda().getv(jj)));
   }
   z.lambda() += diag;
   /*
   //  *********************************
   //  P0 = [D  0  I]
   //       [0  R  0]
   //       [I  0  0]
     z.dx() = x.lambda().dx();
     DualVector<MODEL> diag;
     diag.dx(new CtrlInc_(j_.jb()));
     j_.jb().multiplyB(x.lambda().dx(), diag.dx());
     for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
       diag.append(j_.jterm(jj).multiplyCovar(*x.lambda().getv(jj)));
     }
     z.lambda().zero();
     z.lambda().dx() = x.dx();
     z.lambda() += diag;
   //  *********************************
   */
 }
References oops::DualVector< MODEL >::append(), oops::DualVector< MODEL >::dx(), oops::SaddlePointVector< MODEL >::dx(), oops::DualVector< MODEL >::getv(), oops::SaddlePointVector< MODEL >::lambda(), and oops::DualVector< MODEL >::zero().
Rmultiply()
template<typename MODEL > void oops::SaddlePointLMPMatrix< MODEL >::Rmultiply (Eigen::VectorXd & x, SPVector_ & rx) const private
Definition at line 257 of file SaddlePointLMPMatrix.h.
{
   LagVector_ ww(rx.lambda());
   ww.zero();
   CtrlInc_ zz(rx.dx());
   zz.zero();
   for (unsigned ii = 0; ii < nvec_; ++ii) {
     ww.axpy(x(ii + nvec_), RpVEC_[ii]);
     zz.axpy(x(ii), RqVEC_[ii]);
   }
   rx.lambda() = ww;
   rx.dx() = zz;
 }
References oops::DualVector< MODEL >::axpy(), oops::ControlIncrement< MODEL >::axpy(), oops::SaddlePointVector< MODEL >::dx(), oops::SaddlePointVector< MODEL >::lambda(), oops::DualVector< MODEL >::zero(), and oops::ControlIncrement< MODEL >::zero().
setup()
template<typename MODEL > void oops::SaddlePointLMPMatrix< MODEL >::setup (const std::vector< SPVector_ > & xyVEC, const std::vector< SPVector_ > & pqVEC)
Definition at line 104 of file SaddlePointLMPMatrix.h.
{
   xyVEC_.clear();
   pqVEC_.clear();
   RpVEC_.clear();
   RqVEC_.clear();
   for (unsigned ii = 0; ii < xyVEC.size(); ++ii) {
     xyVEC_.push_back(xyVEC[ii]);
     pqVEC_.push_back(pqVEC[ii]);
   }
   nvec_ = xyVEC_.size();
   if (nvec_ != 0) {
     spvecinit_.reset(new SPVector_(xyVEC_[0]));
     (*spvecinit_).zero();
     SPVector_ ww(xyVEC_[0]);
     SPVector_ yy(xyVEC_[0]);
     // RpRqVEC = pqVEC - P0 * xyVEC
     for (unsigned jv = 0; jv < nvec_; ++jv) {
       this->Pinitmultiply(xyVEC_[jv], ww);
       yy = pqVEC_[jv];
       yy -= ww;
       RpVEC_.push_back(yy.lambda());
       RqVEC_.push_back(yy.dx());
     }
     // Z = RpVEC'*xVEC
     ZMat_.resize(nvec_, nvec_);
     double calpha = 10;
     for (unsigned jj = 0; jj < nvec_; ++jj) {
       for (unsigned ii = 0; ii < nvec_; ++ii) {
         ZMat_(ii, jj) = calpha * dot_product(RpVEC_[ii], xyVEC_[jj].lambda());
       }
     }
     // Get F Matrix explicitly
     // Set Identity matrix
     Eigen::MatrixXd Ik;
     Ik = Eigen::MatrixXd::Identity(2 * nvec_, 2 * nvec_);
     // Apply Fmultiply to identity matrix
     FMat_.resize(2 * nvec_, 2 * nvec_);
     Eigen::VectorXd output(2 * nvec_);
     Eigen::VectorXd input(2 * nvec_);
     for (int ii = 0; ii < 2 * nvec_; ii++) {
       input = Ik.col(ii);
       Fmultiply(input, output);
       FMat_.col(ii) = output;
     }
   }
 }
References dot_product(), oops::SaddlePointVector< MODEL >::dx(), and oops::SaddlePointVector< MODEL >::lambda().
Member Data Documentation
FMat_
template<typename MODEL > Eigen::MatrixXd oops::SaddlePointLMPMatrix< MODEL >::FMat_ private
Definition at line 92 of file SaddlePointLMPMatrix.h.
idmodel_
template<typename MODEL > const bool oops::SaddlePointLMPMatrix< MODEL >::idmodel_ private
Definition at line 84 of file SaddlePointLMPMatrix.h.
j_
template<typename MODEL > const CostFctWeak_& oops::SaddlePointLMPMatrix< MODEL >::j_ private
Definition at line 83 of file SaddlePointLMPMatrix.h.
nvec_
template<typename MODEL > int oops::SaddlePointLMPMatrix< MODEL >::nvec_ private
Definition at line 90 of file SaddlePointLMPMatrix.h.
Referenced by oops::SaddlePointLMPMatrix< MODEL >::getk().
pqVEC_
template<typename MODEL > std::vector<SPVector_> oops::SaddlePointLMPMatrix< MODEL >::pqVEC_ private
Definition at line 86 of file SaddlePointLMPMatrix.h.
RpVEC_
template<typename MODEL > std::vector<LagVector_> oops::SaddlePointLMPMatrix< MODEL >::RpVEC_ private
Definition at line 87 of file SaddlePointLMPMatrix.h.
RqVEC_
template<typename MODEL > std::vector<CtrlInc_> oops::SaddlePointLMPMatrix< MODEL >::RqVEC_ private
Definition at line 88 of file SaddlePointLMPMatrix.h.
spvecinit_
template<typename MODEL > std::unique_ptr<SPVector_> oops::SaddlePointLMPMatrix< MODEL >::spvecinit_ private
Definition at line 89 of file SaddlePointLMPMatrix.h.
xyVEC_
template<typename MODEL > std::vector<SPVector_> oops::SaddlePointLMPMatrix< MODEL >::xyVEC_ private
Definition at line 85 of file SaddlePointLMPMatrix.h.
ZMat_
template<typename MODEL > Eigen::MatrixXd oops::SaddlePointLMPMatrix< MODEL >::ZMat_ private
Definition at line 91 of file SaddlePointLMPMatrix.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/SaddlePointLMPMatrix.h