OOPS Documentation: oops::SQRTBPCGMinimizer< MODEL > Class Template Reference
oops::SQRTBPCGMinimizer< MODEL > Class Template Reference
SQRTBPCG Minimizer.
#include <SQRTBPCGMinimizer.h>
Public Member Functions
const std::string classname () const final
SQRTBPCGMinimizer (const eckit::Configuration &, const CostFct_ &)
Constructor, destructor.
~SQRTBPCGMinimizer ()
Public Member Functions inherited from oops::SQRTMinimizer< MODEL >
SQRTMinimizer (const eckit::Configuration &conf, const CostFct_ &J)
Construct the minimizer.
~SQRTMinimizer ()
Destroy the minimizer.
void checkpoint (eckit::LocalConfiguration &) const
Checkpoint the minimizer.
void restart (const eckit::Configuration &)
Restart the minimizer.
void warmStart (const eckit::Configuration &)
Warm start the minimizer.
Public Member Functions inherited from oops::Minimizer< MODEL >
Minimizer (const CostFct_ &J)
Construct a minimizer.
virtual ~Minimizer ()
Destroy a minimizer.
ControlIncrement< MODEL > * minimize (const eckit::Configuration &)
Orchestrate the minimization of a quadratic cost function.
Private Types
using Bmat_ = BMatrix< MODEL >
using CostFct_ = CostFunction< MODEL >
using CtrlVec_ = ControlVector< MODEL >
using Jbmat_ = JbMatrix< MODEL >
using UtHtRinvHU_ = UtHtRinvHUMatrix< MODEL >
Private Member Functions
double solve (CtrlVec_ &, CtrlVec_ &, const Jbmat_ &, const UtHtRinvHU_ &, const bool &, const size_t &, const size_t &, const double &, const double &, const double &) final
void checkpointLMP (eckit::LocalConfiguration &) const final
Checkpointing, restart of the limited memory preconditioner.
void restartLMP (const eckit::Configuration &) final
Restart the limited memory preconditioner (virtual method)
void setupQuadCost (const double &costJ0Jb, const double &costJ0JoJc)
Quadratic cost function calculations.
void calcQuadCost (const CtrlVec_ &, const CtrlVec_ &, const CtrlVec_ &)
void printQuadCost (const CtrlVec_ &, const size_t &) const
Private Attributes
double costJ0_
Data members.
double costJ0Jb_
double costJ0JoJc_
double costJ_
double costJb_
double costJoJc_
QNewtonSqrtLMP< MODEL > lmp_
Additional Inherited Members
Protected Attributes inherited from oops::SQRTMinimizer< MODEL >
size_t iter_
Outer loop index.
size_t maxiter_
Number of outer loops.
Detailed Description
template<typename MODEL>
class oops::SQRTBPCGMinimizer< MODEL >
SQRTBPCG Minimizer.
Preconditioned Conjugate Gradients solver for the square root preconditioned formulation of the Hessian
This solver is based on the standard Preconditioned Conjugate Gradients solver for Ax=b (G. H. Golub and C. F. Van Loan, Matrix Computations).
A must be square, symmetric, positive definite.
On entry:
dv = starting point, \(dv_{0} \).
rr = \((sum dv^{b}_{i} +) U^T H^T R^{-1} d \)
On exit, dv will contain the solution \(U^{-1} dx \) The solution \(dx = U dv \) is recovered in the SQRTMinimizer class The return value is the achieved reduction in preconditioned residual norm.
Iteration will stop if the maximum iteration limit "maxiter" is reached or if the residual norm reduces by a factor of "tolerance".
Definition at line 62 of file SQRTBPCGMinimizer.h.
Member Typedef Documentation
Bmat_
template<typename MODEL > using oops::SQRTBPCGMinimizer< MODEL >::Bmat_ = BMatrix<MODEL> private
Definition at line 63 of file SQRTBPCGMinimizer.h.
CostFct_
template<typename MODEL > using oops::SQRTBPCGMinimizer< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 64 of file SQRTBPCGMinimizer.h.
CtrlVec_
template<typename MODEL > using oops::SQRTBPCGMinimizer< MODEL >::CtrlVec_ = ControlVector<MODEL> private
Definition at line 65 of file SQRTBPCGMinimizer.h.
Jbmat_
template<typename MODEL > using oops::SQRTBPCGMinimizer< MODEL >::Jbmat_ = JbMatrix<MODEL> private
Definition at line 66 of file SQRTBPCGMinimizer.h.
UtHtRinvHU_
template<typename MODEL > using oops::SQRTBPCGMinimizer< MODEL >::UtHtRinvHU_ = UtHtRinvHUMatrix<MODEL> private
Definition at line 67 of file SQRTBPCGMinimizer.h.
Constructor & Destructor Documentation
SQRTBPCGMinimizer()
template<typename MODEL > oops::SQRTBPCGMinimizer< MODEL >::SQRTBPCGMinimizer (const eckit::Configuration & conf, const CostFct_ & J)
Constructor, destructor.
Definition at line 105 of file SQRTBPCGMinimizer.h.
     : SQRTMinimizer<MODEL>(conf, J),
       costJ0_(0),
       costJ0Jb_(0),
       costJ0JoJc_(0),
       costJ_(0),
       costJb_(0),
       costJoJc_(0),
       lmp_(conf, J) {}
~SQRTBPCGMinimizer()
template<typename MODEL > oops::SQRTBPCGMinimizer< MODEL >::~SQRTBPCGMinimizer () inline
Definition at line 74 of file SQRTBPCGMinimizer.h.
 {}
Member Function Documentation
calcQuadCost()
template<typename MODEL > void oops::SQRTBPCGMinimizer< MODEL >::calcQuadCost (const CtrlVec_ & dv, const CtrlVec_ & jbdv, const CtrlVec_ & r0) private
Definition at line 269 of file SQRTBPCGMinimizer.h.
{
   // Compute the quadratic cost function
   // J[dv_{i}] = J[0] - 0.5 dv_{i}^T r_{0}
   costJ_ = costJ0_ - 0.5 * dot_product(dv, r0);
   Log::info() << "dvtro " << util::full_precision(dot_product(dv, r0))
               << std::endl;
   // Jb[dv_{i}] = 0.5 dv_{i}^T Jb.dv_{i}
   costJb_ = costJ0Jb_ + 0.5 * dot_product(dv, jbdv);
   // Jo[dv_{i}] + Jc[dv_{i}] = J[dv_{i}] - Jb[dv_{i}]
   costJoJc_ = costJ_ - costJb_;
 }
References dot_product(), and util::full_precision().
checkpointLMP()
template<typename MODEL > void oops::SQRTBPCGMinimizer< MODEL >::checkpointLMP (eckit::LocalConfiguration &) const final private virtual
Checkpointing, restart of the limited memory preconditioner.
Implements oops::SQRTMinimizer< MODEL >.
Definition at line 301 of file SQRTBPCGMinimizer.h.
                                      {}
classname()
template<typename MODEL > const std::string oops::SQRTBPCGMinimizer< MODEL >::classname () const inline final virtual
Implements oops::SQRTMinimizer< MODEL >.
Definition at line 70 of file SQRTBPCGMinimizer.h.
 { return "SQRTBPCGMinimizer"; }
printQuadCost()
template<typename MODEL > void oops::SQRTBPCGMinimizer< MODEL >::printQuadCost (const CtrlVec_ & dv, const size_t & jiter) const private
Definition at line 286 of file SQRTBPCGMinimizer.h.
{
   // Print the quadratic cost function
   Log::info() << "  Quadratic cost function: J   (" << std::setw(2) << jiter + 1
               << ") = " << util::full_precision(costJ_) << std::endl
               << "  Quadratic cost function: Jb  (" << std::setw(2) << jiter + 1
               << ") = " << util::full_precision(costJb_) << std::endl;
   Log::info() << "  Quadratic cost function: JoJc(" << std::setw(2) << jiter + 1
               << ") = " << util::full_precision(costJoJc_) << std::endl
               << std::endl;
 }
References util::full_precision().
restartLMP()
template<typename MODEL > void oops::SQRTBPCGMinimizer< MODEL >::restartLMP (const eckit::Configuration &) final private virtual
Restart the limited memory preconditioner (virtual method)
Implements oops::SQRTMinimizer< MODEL >.
Definition at line 307 of file SQRTBPCGMinimizer.h.
 {}
setupQuadCost()
template<typename MODEL > void oops::SQRTBPCGMinimizer< MODEL >::setupQuadCost (const double & costJ0Jb, const double & costJ0JoJc) private
Quadratic cost function calculations.
Definition at line 251 of file SQRTBPCGMinimizer.h.
{
   // J0
   costJ0Jb_ = costJ0Jb;
   costJ0JoJc_ = costJ0JoJc;
   // J0
   costJ0_ = costJ0Jb_ + costJ0JoJc_;
   // reset
   costJ_ = 0;
   costJb_ = 0;
   costJoJc_ = 0;
 }
solve()
template<typename MODEL > double oops::SQRTBPCGMinimizer< MODEL >::solve (CtrlVec_ & dv, CtrlVec_ & rr, const Jbmat_ & Jb, const UtHtRinvHU_ & UtHtRinvHU, const bool & linfoconv, const size_t & maxiter, const size_t & miniter, const double & tolerance, const double & costJ0Jb, const double & costJ0JoJc) final private virtual
Implements oops::SQRTMinimizer< MODEL >.
Definition at line 119 of file SQRTBPCGMinimizer.h.
{
   // dv   control vector
   // rr   (sum dv_i^{b} +) U^T G^T R^{-1} d
   CtrlVec_ qq(dv);
   CtrlVec_ pp(dv);
   CtrlVec_ pr(dv);
   CtrlVec_ jbpp(dv);
   CtrlVec_ jbdv(dv);
   CtrlVec_ zz(dv);
   CtrlVec_ r0(dv);
   CtrlVec_ ww(dv);
   // vectors for re-orthogonalization
   std::vector<CtrlVec_> vvecs;
   std::vector<CtrlVec_> zvecs;
   std::vector<double> scals;
   // setup calculation of the quadratic cost function
   this->setupQuadCost(costJ0Jb, costJ0JoJc);
   // change resolution of LMP vectors
   lmp_.changeResolution();
   // r_{0}
   r0 = rr;
   // r_{0}^T r_{0}
   Log::info() << "normr0 " << dot_product(rr, rr) << std::endl;
   // z_{0} = LMP r_{0}
   lmp_.inverseMultiply(rr, zz);
   // p_{0} = z_{0}
   pp = zz;
   // r_{0}^T z_{0}
   double dotZZ0 = dot_product(rr, zz);
   Log::info() << "normr0z0 " << dotZZ0 << std::endl;
   double normReduction = 1.0;
   double zdots = dotZZ0;
   double zdots_old = 0.0;
   vvecs.push_back(rr);
   zvecs.push_back(zz);
   scals.push_back(1.0 / dotZZ0);
   Log::info() << std::endl;
   for (size_t jiter = 0; jiter < maxiter; ++jiter) {
     Log::info() << " SQRTPCG Starting Iteration " << jiter + 1 << std::endl;
     util::LogbookWriter<int> log("InnerLoop", jiter);
     if (jiter > 0) {
       // beta_{i} = z_{i+1}^T z_{i+1} / z_{i}^T z_{i}
       double beta = zdots / zdots_old;
       // p_{i+1} = z_{i+1} + beta*p_{i}
       pp *= beta;
       pp += zz;
     }
     // q_{i} = ( P^-1/2  Jb P^-T/2 + U^T H^T R^{-1} H U ) p_{i}
     UtHtRinvHU.multiply(pp, qq);
     Jb.multiply(pp, jbpp);  // U^T B^-1 U != I for VarBC
     qq += jbpp;
     // alpha_{i} = z_{i}^T z_{i} / q_{i}^T p_{i}
     double rho = dot_product(pp, qq);
     double alpha = zdots / rho;
     // dv_{i+1} = dv_{i} + alpha * p_{i}
     dv.axpy(alpha, pp);
     // jbdv_{i+1} = jbdv_{i} + alpha * jbh_{i}
     jbdv.axpy(alpha, jbpp);
     // r_{i+1} = r_{i} - alpha * q_{i}
     rr.axpy(-alpha, qq);
     // Compute the quadratic cost function
     this->calcQuadCost(dv, jbdv, r0);
     // Re-orthogonalization
     for (size_t jj = 0; jj < jiter; ++jj) {
       double proj = scals[jj] * dot_product(rr, zvecs[jj]);
       rr.axpy(-proj, vvecs[jj]);
     }
     lmp_.inverseMultiply(rr, zz);
     // z_{i}^T z_{i}
     zdots_old = zdots;
     // z_{i+1}^T z_{i+1}
     zdots = dot_product(rr, zz);
     Log::info() << "zdots " << zdots << "      iteration    " << jiter
                 << std::endl;
     // z_{i+1}^T z_{i+1} / z_{0}^T z_{0}
     normReduction = sqrt(zdots / dotZZ0);
     util::LogbookWriter<double> log_norm("NormReduction", normReduction);
     Log::info() << "SQRTPCG end of iteration " << jiter + 1 << std::endl
                 << "  Norm reduction (" << std::setw(2) << jiter + 1
                 << ") = " << util::full_precision(normReduction) << std::endl;
     this->printQuadCost(dv, jiter);
     if (normReduction < tolerance && jiter >= miniter) {
       Log::info() << "SQRTPCG: Achieved required reduction in residual norm."
                   << std::endl;
       break;
     }
     vvecs.push_back(rr);
     zvecs.push_back(zz);
     scals.push_back(1.0 / zdots);
     lmp_.push(pp, zz, qq, rho);
   }
   lmp_.update();
   return normReduction;
 }
References oops::ControlVector< MODEL >::axpy(), dot_product(), util::full_precision(), oops::JbMatrix< MODEL >::multiply(), and oops::UtHtRinvHUMatrix< MODEL >::multiply().
Member Data Documentation
costJ0_
template<typename MODEL > double oops::SQRTBPCGMinimizer< MODEL >::costJ0_ private
Data members.
Definition at line 91 of file SQRTBPCGMinimizer.h.
costJ0Jb_
template<typename MODEL > double oops::SQRTBPCGMinimizer< MODEL >::costJ0Jb_ private
Definition at line 92 of file SQRTBPCGMinimizer.h.
costJ0JoJc_
template<typename MODEL > double oops::SQRTBPCGMinimizer< MODEL >::costJ0JoJc_ private
Definition at line 93 of file SQRTBPCGMinimizer.h.
costJ_
template<typename MODEL > double oops::SQRTBPCGMinimizer< MODEL >::costJ_ private
Definition at line 95 of file SQRTBPCGMinimizer.h.
costJb_
template<typename MODEL > double oops::SQRTBPCGMinimizer< MODEL >::costJb_ private
Definition at line 96 of file SQRTBPCGMinimizer.h.
costJoJc_
template<typename MODEL > double oops::SQRTBPCGMinimizer< MODEL >::costJoJc_ private
Definition at line 97 of file SQRTBPCGMinimizer.h.
lmp_
template<typename MODEL > QNewtonSqrtLMP<MODEL> oops::SQRTBPCGMinimizer< MODEL >::lmp_ private
Definition at line 99 of file SQRTBPCGMinimizer.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/SQRTBPCGMinimizer.h