OOPS Documentation: oops::LBHessianMatrix< MODEL > Class Template Reference
oops::LBHessianMatrix< MODEL > Class Template Reference
The Hessian matrix: \(I + B H^T R^{-1} H \).
#include <LBHessianMatrix.h>
Public Member Functions
LBHessianMatrix (const CostFct_ &j)
void multiply (const CtrlInc_ &dx, CtrlInc_ &dz) const
Private Types
using Increment_ = Increment< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using CostFct_ = CostFunction< MODEL >
using JqTermAD_ = JqTermAD< MODEL >
using JqTermTL_ = JqTermTL< MODEL >
Private Attributes
CostFct_ const & j_
Detailed Description
template<typename MODEL>
class oops::LBHessianMatrix< MODEL >
The Hessian matrix: \(I + B H^T R^{-1} H \).
The solvers represent matrices as objects that implement a "multiply" method. This class defines objects that apply a generalized Hessian matrix which includes all the terms of the cost function.
Definition at line 39 of file LBHessianMatrix.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::LBHessianMatrix< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 42 of file LBHessianMatrix.h.
CtrlInc_
template<typename MODEL > using oops::LBHessianMatrix< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 41 of file LBHessianMatrix.h.
Increment_
template<typename MODEL > using oops::LBHessianMatrix< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 40 of file LBHessianMatrix.h.
JqTermAD_
template<typename MODEL > using oops::LBHessianMatrix< MODEL >::JqTermAD_ = JqTermAD<MODEL> private
Definition at line 43 of file LBHessianMatrix.h.
JqTermTL_
template<typename MODEL > using oops::LBHessianMatrix< MODEL >::JqTermTL_ = JqTermTL<MODEL> private
Definition at line 44 of file LBHessianMatrix.h.
Constructor & Destructor Documentation
LBHessianMatrix()
template<typename MODEL > oops::LBHessianMatrix< MODEL >::LBHessianMatrix (const CostFct_ & j) inline explicit
Definition at line 47 of file LBHessianMatrix.h.
 : j_(j) {}
Member Function Documentation
multiply()
template<typename MODEL > void oops::LBHessianMatrix< MODEL >::multiply (const CtrlInc_ & dx, CtrlInc_ & dz) const inline
Definition at line 49 of file LBHessianMatrix.h.
{
     //  Setup TL terms of cost function
     PostProcessorTL<Increment_> costtl;
     JqTermTL_* jqtl = j_.jb().initializeTL();
     costtl.enrollProcessor(jqtl);
     unsigned iq = 0;
     if (jqtl) iq = 1;
     for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
       costtl.enrollProcessor(j_.jterm(jj).setupTL(dx));
     }
     //  Run TLM
     CtrlInc_ mdx(dx);
     j_.runTL(mdx, costtl);
     //  Finalize Jb+Jq
     //  Get TLM outputs, multiply by covariance inverses and setup ADJ forcing
     //  terms
     PostProcessorAD<Increment_> costad;
     dz.zero();
     CtrlInc_ dw(j_.jb());
     //  Jb
     CtrlInc_ tmp(j_.jb());
     j_.jb().finalizeTL(jqtl, dx, dw);
     tmp = dw;
     JqTermAD_* jqad = j_.jb().initializeAD(dz, tmp);
     costad.enrollProcessor(jqad);
     j_.zeroAD(dw);
     //  Jo + Jc
     for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
       std::unique_ptr<GeneralizedDepartures> ww(
           costtl.releaseOutputFromTL(iq + jj));
       std::shared_ptr<GeneralizedDepartures> zz(
           j_.jterm(jj).multiplyCoInv(*ww));
       costad.enrollProcessor(j_.jterm(jj).setupAD(zz, dw));
     }
     //  Run ADJ
     j_.runAD(dw, costad);
     //  Multiply by B
     CtrlInc_ zz(j_.jb());
     j_.jb().multiplyB(dw, zz);
     dz += zz;
     j_.jb().finalizeAD(jqad);
   }
References oops::PostProcessorAD< INCR >::enrollProcessor(), oops::PostProcessorTL< INCR >::enrollProcessor(), oops::CostJbTotal< MODEL >::finalizeAD(), oops::CostJbTotal< MODEL >::finalizeTL(), oops::CostJbTotal< MODEL >::initializeAD(), oops::CostJbTotal< MODEL >::initializeTL(), oops::LBHessianMatrix< MODEL >::j_, oops::CostFunction< MODEL >::jb(), oops::CostFunction< MODEL >::jterm(), oops::CostJbTotal< MODEL >::multiplyB(), oops::CostTermBase< MODEL >::multiplyCoInv(), oops::CostFunction< MODEL >::nterms(), oops::PostProcessorTL< INCR >::releaseOutputFromTL(), oops::CostFunction< MODEL >::runAD(), oops::CostFunction< MODEL >::runTL(), oops::CostTermBase< MODEL >::setupAD(), oops::CostTermBase< MODEL >::setupTL(), oops::ControlIncrement< MODEL >::zero(), and oops::CostFunction< MODEL >::zeroAD().
Member Data Documentation
j_
template<typename MODEL > CostFct_ const& oops::LBHessianMatrix< MODEL >::j_ private
Definition at line 101 of file LBHessianMatrix.h.
Referenced by oops::LBHessianMatrix< MODEL >::multiply().
The documentation for this class was generated from the following file:
src/oops/assimilation/LBHessianMatrix.h