OOPS Documentation: oops::Increment< MODEL > Class Template Reference
oops::Increment< MODEL > Class Template Reference
Encapsulates model increment.
#include <GeoVaLs.h>
Public Member Functions
Increment (const Geometry_ &, const Variables_ &, const util::DateTime &)
Constructor [1].
Increment (const Geometry_ &, const Variables_ &, const util::DateTime &, const util::DateTime &)
Constructor [2].
Increment (const Geometry_ &, const Increment &)
Constructor with copy initialization.
Increment (const Increment &, const bool copy=true)
Copy constructor.
virtual ~Increment ()
Destructor.
Increment_ & increment ()
Return a reference to the model specific increment.
const Increment_ & increment () const
Return a constant reference to the model specific increment.
Geometry_ geometry () const
Get geometry.
void interpolateTL (const Locations_ &, GeoVaLs_ &) const
Interpolate to observation locations TL.
void interpolateAD (const Locations_ &, const GeoVaLs_ &)
Interpolate to observation locations AD.
void diff (const State_ &, const State_ &)
Compute increment as a difference between two States.
const util::DateTime & validTime () const
Return the valid time.
void updateTime (const util::Duration &dt)
Update the valid time.
void zero ()
\(dx_1 = 0 \)
void zero (const util::DateTime &)
\(dx_1 = 0, set valid time \)
Increment & operator= (const Increment &)
\(dx_1 = dx_2 \)
Increment & operator+= (const Increment &)
\(dx_1 = dx_1 + dx_2 \)
Increment & operator-= (const Increment &)
\(dx_1 = dx_1 - dx_2 \)
Increment & operator*= (const double &)
\(dx_1 = dx_1 * c \)
void axpy (const double &, const Increment &, const bool check=true)
\(dx_1 = dx_1 * c dx_2 \)
double dot_product_with (const Increment &) const
\(<dx_1,dx_1> = dx_1^T dx_1 \)
void schur_product_with (const Increment &)
Hadamard product (element-wise)
void random ()
Random increment.
void accumul (const double &, const State_ &)
Accumulate.
void read (const eckit::Configuration &)
Read increment.
void write (const eckit::Configuration &) const
Write increment.
double norm () const
L-2 norm.
double max (const Variables_ &) const
Return maximum value.
double min (const Variables_ &) const
Return minimum value.
Static Public Member Functions
static const std::string classname ()
Private Types
using Increment_ = typename MODEL::Increment
using Geometry_ = Geometry< MODEL >
using GeoVaLs_ = GeoVaLs< MODEL >
using Locations_ = Locations< MODEL >
using State_ = State< MODEL >
using Variables_ = Variables< MODEL >
Private Member Functions
void print (std::ostream &) const
Private Attributes
std::unique_ptr< Increment_ > increment_
Pointer to the model specific increment object.
Friends
eckit::Stream & operator<< (eckit::Stream &s, const Increment &dx)
Serialization.
eckit::Stream & operator>> (eckit::Stream &s, Increment &dx)
Detailed Description
template<typename MODEL>
class oops::Increment< MODEL >
Encapsulates model increment.
Wrapper around a model specific increment class. Increment is defined as a difference between two states. Some fields that are present in a State may not be present in an Increment.
\(dx_{state4D} \) implemented by Increment4D implements the state component of a ControlIncrement and contains a vector of Increment objects.
Definition at line 32 of file GeoVaLs.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::Increment< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 51 of file Increment.h.
GeoVaLs_
template<typename MODEL > using oops::Increment< MODEL >::GeoVaLs_ = GeoVaLs<MODEL> private
Definition at line 52 of file Increment.h.
Increment_
template<typename MODEL > using oops::Increment< MODEL >::Increment_ = typename MODEL::Increment private
Definition at line 50 of file Increment.h.
Locations_
template<typename MODEL > using oops::Increment< MODEL >::Locations_ = Locations<MODEL> private
Definition at line 53 of file Increment.h.
State_
template<typename MODEL > using oops::Increment< MODEL >::State_ = State<MODEL> private
Definition at line 54 of file Increment.h.
Variables_
template<typename MODEL > using oops::Increment< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 55 of file Increment.h.
Constructor & Destructor Documentation
Increment() [1/4]
template<typename MODEL > oops::Increment< MODEL >::Increment (const Geometry_ & resol, const Variables_ & vars, const util::DateTime & time)
Constructor [1].
Constructor, destructor.
Definition at line 164 of file Increment.h.
     : increment_() {
   Log::trace() << "Increment<MODEL>::Increment starting" << std::endl;
   util::Timer timer(classname(), "Increment");
   increment_.reset(new Increment_(resol.geometry(), vars.variables(), time));
   Log::trace() << "Increment<MODEL>::Increment done" << std::endl;
 }
References oops::Increment< MODEL >::classname(), oops::Geometry< MODEL >::geometry(), oops::Increment< MODEL >::increment_, and oops::Variables< MODEL >::variables().
Increment() [2/4]
template<typename MODEL > oops::Increment< MODEL >::Increment (const Geometry_ & resol, const Variables_ & vars, const util::DateTime & reftime, const util::DateTime & validtime)
Constructor [2].
Definition at line 174 of file Increment.h.
     : increment_() {
   Log::trace() << "Increment<MODEL>::Increment starting" << std::endl;
   util::Timer timer(classname(), "Increment");
   increment_.reset(
       new Increment_(resol.geometry(), vars.variables(), reftime, validtime));
   Log::trace() << "Increment<MODEL>::Increment done" << std::endl;
 }
References oops::Increment< MODEL >::classname(), oops::Geometry< MODEL >::geometry(), oops::Increment< MODEL >::increment_, and oops::Variables< MODEL >::variables().
Increment() [3/4]
template<typename MODEL > oops::Increment< MODEL >::Increment (const Geometry_ & resol, const Increment< MODEL > & other)
Constructor with copy initialization.
Definition at line 188 of file Increment.h.
     : increment_() {
   Log::trace() << "Increment<MODEL>::Increment starting" << std::endl;
   util::Timer timer(classname(), "Increment");
   increment_.reset(new Increment_(resol.geometry(), *other.increment_));
   Log::trace() << "Increment<MODEL>::Increment done" << std::endl;
 }
References oops::Increment< MODEL >::classname(), oops::Geometry< MODEL >::geometry(), and oops::Increment< MODEL >::increment_.
Increment() [4/4]
template<typename MODEL > oops::Increment< MODEL >::Increment (const Increment< MODEL > & other, const bool copy = true)
Copy constructor.
Definition at line 199 of file Increment.h.
     : increment_() {
   Log::trace() << "Increment<MODEL>::Increment copy starting" << std::endl;
   util::Timer timer(classname(), "Increment");
   increment_.reset(new Increment_(*other.increment_, copy));
   Log::trace() << "Increment<MODEL>::Increment copy done" << std::endl;
 }
References oops::Increment< MODEL >::classname(), and oops::Increment< MODEL >::increment_.
~Increment()
template<typename MODEL > oops::Increment< MODEL >::~Increment virtual
Destructor.
Definition at line 210 of file Increment.h.
{
   Log::trace() << "Increment<MODEL>::~Increment starting" << std::endl;
   util::Timer timer(classname(), "~Increment");
   increment_.reset();
   Log::trace() << "Increment<MODEL>::~Increment done" << std::endl;
 }
Member Function Documentation
accumul()
template<typename MODEL > void oops::Increment< MODEL >::accumul (const double & zz, const State_ & xx)
Accumulate.
Definition at line 364 of file Increment.h.
{
   Log::trace() << "Increment<MODEL>::accumul starting" << std::endl;
   util::Timer timer(classname(), "accumul");
   increment_->accumul(zz, xx.state());
   Log::trace() << "Increment<MODEL>::accumul done" << std::endl;
 }
References oops::State< MODEL >::state().
Referenced by oops::Ensemble< MODEL >::build().
axpy()
template<typename MODEL > void oops::Increment< MODEL >::axpy (const double & zz, const Increment< MODEL > & dx, const bool check = true)
\(dx_1 = dx_1 * c dx_2 \)
Definition at line 322 of file Increment.h.
{
   Log::trace() << "Increment<MODEL>::axpy starting" << std::endl;
   util::Timer timer(classname(), "axpy");
   increment_->axpy(zz, *dx.increment_, check);
   Log::trace() << "Increment<MODEL>::axpy done" << std::endl;
 }
Referenced by oops::StaticCovariance4D< MODEL >::advectedMultiply(), oops::StaticCovariance4D< MODEL >::advectedMultiplySqrtTrans(), oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::assign_no_date_ctrl(), oops::EnsembleCovsInterpolSDL< MODEL >::multiply(), oops::HybridCovariance< MODEL >::multiply(), oops::EnsembleCovariance< MODEL >::multiply(), oops::EnsembleCovarianceSDL< MODEL >::multiply(), oops::EnsembleCovsInterpolSDL< MODEL >::multiplySqrt(), oops::HybridCovariance< MODEL >::multiplySqrt(), oops::EnsembleCovarianceSDL< MODEL >::multiplySqrt(), oops::EnsembleCovariance< MODEL >::multiplySqrt(), oops::EnsembleCovsInterpolSDL< MODEL >::randomize(), oops::EnsembleCovariance< MODEL >::randomize(), oops::EnsembleCovarianceSDL< MODEL >::randomize(), oops::EnsembleCovariance4D< MODEL >::schur_add(), oops::EnsembleCovsInterpol< MODEL >::schur_add(), oops::EnsembleCovariance4DScaleDependent< MODEL >::schur_add(), oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::schur_add(), oops::EnsembleCovsInterpol4D< MODEL >::schur_add(), oops::EnsembleCovariance4DDistributed< MODEL >::schur_add(), and oops::Ensemble< MODEL >::to_perturbations().
classname()
template<typename MODEL > static const std::string oops::Increment< MODEL >::classname () inline static
Definition at line 58 of file Increment.h.
 { return "oops::Increment"; }
Referenced by oops::Increment< MODEL >::Increment().
diff()
template<typename MODEL > void oops::Increment< MODEL >::diff (const State_ & x1, const State_ & x2)
Compute increment as a difference between two States.
Definition at line 248 of file Increment.h.
{
   Log::trace() << "Increment<MODEL>::diff starting" << std::endl;
   util::Timer timer(classname(), "diff");
   increment_->diff(x1.state(), x2.state());
   Log::trace() << "Increment<MODEL>::diff done" << std::endl;
 }
References oops::State< MODEL >::state().
Referenced by oops::CostFct4DVarTrajHR< MODEL >::addIncr(), and oops::CostFct4DVarMFTemplate< MODEL >::addIncr().
dot_product_with()
template<typename MODEL > double oops::Increment< MODEL >::dot_product_with (const Increment< MODEL > & dx) const
\(<dx_1,dx_1> = dx_1^T dx_1 \)
Definition at line 333 of file Increment.h.
{
   Log::trace() << "Increment<MODEL>::dot_product_with starting" << std::endl;
   util::Timer timer(classname(), "dot_product_with");
   double zz = increment_->dot_product_with(*dx.increment_);
   Log::trace() << "Increment<MODEL>::dot_product_with done" << std::endl;
   return zz;
 }
geometry()
template<typename MODEL > Geometry< MODEL > oops::Increment< MODEL >::geometry
Get geometry.
Definition at line 428 of file Increment.h.
{
   Log::trace() << "Increment<MODEL>::geometry starting" << std::endl;
   util::Timer timer(classname(), "geometry");
   Geometry<MODEL> geom(increment_->geometry());
   Log::trace() << "Increment<MODEL>::geometry done" << std::endl;
   return geom;
 }
Referenced by oops::Increment4D< MODEL >::geometry().
increment() [1/2]
template<typename MODEL > Increment_& oops::Increment< MODEL >::increment () inline
Return a reference to the model specific increment.
Definition at line 74 of file Increment.h.
 { return *increment_; }
References oops::Increment< MODEL >::increment_.
Referenced by oops::HorizScaleDecomposition< MODEL >::collect(), oops::HorizScaleDecomposition< MODEL >::decompose(), oops::LinearModelBase< L95Traits >::finalizeAD(), oops::LinearModelBase< L95Traits >::finalizeTL(), oops::GeoVaLs< MODEL >::GeoVaLs(), oops::LinearModelBase< L95Traits >::initializeAD(), oops::LinearModelBase< L95Traits >::initializeTL(), oops::Interpolator< MODEL >::interpolate(), oops::GenericMatrix< MODEL >::inverseMultiply(), oops::JcCovarBase< MODEL >::inverseMultiply(), oops::ErrorCovariance< MODEL >::inverseMultiply(), oops::GenericMatrix< MODEL >::multiply(), oops::Localization< MODEL >::multiply(), oops::JcCovarBase< MODEL >::multiply(), oops::ErrorCovariance< MODEL >::multiply(), oops::Localization< MODEL >::multiplySqrt(), oops::ErrorCovariance< MODEL >::multiplySqrt(), oops::Localization< MODEL >::multiplySqrtTrans(), oops::ErrorCovariance< MODEL >::multiplySqrtTrans(), oops::ErrorCovariance< MODEL >::randomize(), oops::Interpolator< MODEL >::read(), oops::Interpolator< MODEL >::save(), oops::Interpolator< MODEL >::smooth(), oops::LinearModelBase< L95Traits >::stepAD(), oops::LinearModelBase< L95Traits >::stepTL(), and oops::GenericMatrix< MODEL >::transposeInverseMultiply().
increment() [2/2]
template<typename MODEL > const Increment_& oops::Increment< MODEL >::increment () const inline
Return a constant reference to the model specific increment.
Definition at line 76 of file Increment.h.
 { return *increment_; }
References oops::Increment< MODEL >::increment_.
interpolateAD()
template<typename MODEL > void oops::Increment< MODEL >::interpolateAD (const Locations_ & loc, const GeoVaLs_ & gvals)
Interpolate to observation locations AD.
See GeoVaLs documentation; implements adjoint of the interpolation to observation locations operator
Definition at line 234 of file Increment.h.
{
   Log::trace() << "Increment<MODEL>::interpolateAD starting" << std::endl;
   util::Timer timer(classname(), "interpolateAD");
   increment_->interpolateAD(loc.locations(), gvals.geovals());
   Log::trace() << "Increment<MODEL>::interpolateAD done" << std::endl;
 }
References oops::GeoVaLs< MODEL >::geovals(), and oops::Locations< MODEL >::locations().
interpolateTL()
template<typename MODEL > void oops::Increment< MODEL >::interpolateTL (const Locations_ & loc, GeoVaLs_ & gvals) const
Interpolate to observation locations TL.
See GeoVaLs documentation; implements tangent linear of the interpolation to observation locations operator
Definition at line 220 of file Increment.h.
{
   Log::trace() << "Increment<MODEL>::interpolateTL starting" << std::endl;
   util::Timer timer(classname(), "interpolateTL");
   increment_->interpolateTL(loc.locations(), gvals.geovals());
   Log::trace() << "Increment<MODEL>::interpolateTL done" << std::endl;
 }
References oops::GeoVaLs< MODEL >::geovals(), and oops::Locations< MODEL >::locations().
max()
template<typename MODEL > double oops::Increment< MODEL >::max (const Variables_ & var) const
Return maximum value.
Definition at line 406 of file Increment.h.
{
   Log::trace() << "Increment<MODEL>::max starting" << std::endl;
   util::Timer timer(classname(), "max");
   double zz = increment_->max(var.variables());
   Log::trace() << "Increment<MODEL>::max done" << std::endl;
   return zz;
 }
References oops::Variables< MODEL >::variables().
min()
template<typename MODEL > double oops::Increment< MODEL >::min (const Variables_ & var) const
Return minimum value.
Definition at line 417 of file Increment.h.
{
   Log::trace() << "Increment<MODEL>::min starting" << std::endl;
   util::Timer timer(classname(), "min");
   double zz = increment_->min(var.variables());
   Log::trace() << "Increment<MODEL>::min done" << std::endl;
   return zz;
 }
References oops::Variables< MODEL >::variables().
norm()
template<typename MODEL > double oops::Increment< MODEL >::norm
L-2 norm.
Definition at line 395 of file Increment.h.
{
   Log::trace() << "Increment<MODEL>::norm starting" << std::endl;
   util::Timer timer(classname(), "norm");
   double zz = increment_->norm();
   Log::trace() << "Increment<MODEL>::norm done" << std::endl;
   return zz;
 }
operator*=()
template<typename MODEL > Increment< MODEL > & oops::Increment< MODEL >::operator*= (const double & zz)
\(dx_1 = dx_1 * c \)
Definition at line 311 of file Increment.h.
{
   Log::trace() << "Increment<MODEL>::operator*= starting" << std::endl;
   util::Timer timer(classname(), "operator*=");
   *increment_ *= zz;
   Log::trace() << "Increment<MODEL>::operator*= done" << std::endl;
   return *this;
 }
operator+=()
template<typename MODEL > Increment< MODEL > & oops::Increment< MODEL >::operator+= (const Increment< MODEL > & rhs)
\(dx_1 = dx_1 + dx_2 \)
Definition at line 289 of file Increment.h.
{
   Log::trace() << "Increment<MODEL>::operator+= starting" << std::endl;
   util::Timer timer(classname(), "operator+=");
   *increment_ += *rhs.increment_;
   Log::trace() << "Increment<MODEL>::operator+= done" << std::endl;
   return *this;
 }
operator-=()
template<typename MODEL > Increment< MODEL > & oops::Increment< MODEL >::operator-= (const Increment< MODEL > & rhs)
\(dx_1 = dx_1 - dx_2 \)
Definition at line 300 of file Increment.h.
{
   Log::trace() << "Increment<MODEL>::operator-= starting" << std::endl;
   util::Timer timer(classname(), "operator-=");
   *increment_ -= *rhs.increment_;
   Log::trace() << "Increment<MODEL>::operator-= done" << std::endl;
   return *this;
 }
operator=()
template<typename MODEL > Increment< MODEL > & oops::Increment< MODEL >::operator= (const Increment< MODEL > & rhs)
\(dx_1 = dx_2 \)
Definition at line 278 of file Increment.h.
{
   Log::trace() << "Increment<MODEL>::operator= starting" << std::endl;
   util::Timer timer(classname(), "operator=");
   *increment_ = *rhs.increment_;
   Log::trace() << "Increment<MODEL>::operator= done" << std::endl;
   return *this;
 }
print()
template<typename MODEL > void oops::Increment< MODEL >::print (std::ostream & os) const private
Definition at line 439 of file Increment.h.
{
   Log::trace() << "Increment<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   os << *increment_;
   Log::trace() << "Increment<MODEL>::print done" << std::endl;
 }
random()
template<typename MODEL > void oops::Increment< MODEL >::random
Random increment.
Definition at line 354 of file Increment.h.
{
   Log::trace() << "Increment<MODEL>::random starting" << std::endl;
   util::Timer timer(classname(), "random");
   increment_->random();
   Log::trace() << "Increment<MODEL>::random done" << std::endl;
 }
read()
template<typename MODEL > void oops::Increment< MODEL >::read (const eckit::Configuration & conf)
Read increment.
Definition at line 374 of file Increment.h.
{
   Log::trace() << "Increment<MODEL>::read starting" << std::endl;
   util::Timer timer(classname(), "read");
   increment_->read(conf);
   Log::trace() << "Increment<MODEL>::read done" << std::endl;
 }
Referenced by oops::ObserverIAU< MODEL, STATE >::doInitialize(), oops::CostFunction< MODEL >::recentreBackground(), and oops::IncrementalAssimilation< MODEL >::recentreFirstGuess().
schur_product_with()
template<typename MODEL > void oops::Increment< MODEL >::schur_product_with (const Increment< MODEL > & dx)
Hadamard product (element-wise)
Definition at line 344 of file Increment.h.
{
   Log::trace() << "Increment<MODEL>::schur_product_with starting" << std::endl;
   util::Timer timer(classname(), "schur_product_with");
   increment_->schur_product_with(*dx.increment_);
   Log::trace() << "Increment<MODEL>::schur_product_with done" << std::endl;
 }
Referenced by oops::EnsembleCovsInterpolSDL< MODEL >::multiply(), oops::EnsembleCovarianceSDL< MODEL >::multiply(), oops::EnsembleCovariance< MODEL >::multiply(), oops::EnsembleCovsInterpolSDL< MODEL >::multiplySqrt(), oops::EnsembleCovariance< MODEL >::multiplySqrt(), oops::EnsembleCovarianceSDL< MODEL >::multiplySqrt(), oops::EnsembleCovsInterpolSDL< MODEL >::multiplySqrtTrans(), oops::EnsembleCovarianceSDL< MODEL >::multiplySqrtTrans(), oops::EnsembleCovariance< MODEL >::multiplySqrtTrans(), oops::EnsembleCovsInterpolSDL< MODEL >::randomize(), oops::EnsembleCovarianceSDL< MODEL >::randomize(), oops::EnsembleCovariance< MODEL >::randomize(), oops::EnsembleCovariance4D< MODEL >::schur_add(), oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::schur_add(), oops::EnsembleCovsInterpol< MODEL >::schur_add(), oops::EnsembleCovariance4DScaleDependent< MODEL >::schur_add(), oops::EnsembleCovsInterpol4D< MODEL >::schur_add(), and oops::EnsembleCovariance4DDistributed< MODEL >::schur_add().
updateTime()
template<typename MODEL > void oops::Increment< MODEL >::updateTime (const util::Duration & dt) inline
Update the valid time.
Definition at line 93 of file Increment.h.
 { increment_->updateTime(dt); }
References oops::Increment< MODEL >::increment_.
Referenced by oops::LinearModel< MODEL >::forecastAD(), and oops::LinearModel< MODEL >::forecastTL().
validTime()
template<typename MODEL > const util::DateTime& oops::Increment< MODEL >::validTime () const inline
Return the valid time.
Definition at line 91 of file Increment.h.
 { return increment_->validTime(); }
References oops::Increment< MODEL >::increment_.
Referenced by oops::LinearModel< MODEL >::forecastAD(), oops::LinearModel< MODEL >::forecastTL(), oops::EnsembleCovsInterpolSDL< MODEL >::multiply(), oops::EnsembleCovsInterpol< MODEL >::multiply(), oops::EnsembleCovarianceSDL< MODEL >::multiply(), oops::EnsembleCovariance< MODEL >::multiply(), oops::EnsembleCovsInterpolSDL< MODEL >::multiplySqrt(), oops::EnsembleCovsInterpol< MODEL >::multiplySqrt(), oops::EnsembleCovariance< MODEL >::multiplySqrt(), oops::EnsembleCovarianceSDL< MODEL >::multiplySqrt(), oops::EnsembleCovsInterpolSDL< MODEL >::multiplySqrtTrans(), oops::EnsembleCovsInterpol< MODEL >::multiplySqrtTrans(), oops::EnsembleCovarianceSDL< MODEL >::multiplySqrtTrans(), oops::EnsembleCovariance< MODEL >::multiplySqrtTrans(), oops::EnsembleCovsInterpolSDL< MODEL >::randomize(), oops::EnsembleCovarianceSDL< MODEL >::randomize(), and oops::EnsembleCovariance< MODEL >::randomize().
write()
template<typename MODEL > void oops::Increment< MODEL >::write (const eckit::Configuration & conf) const
Write increment.
Definition at line 384 of file Increment.h.
{
   Log::trace() << "Increment<MODEL>::write starting" << std::endl;
   util::Timer timer(classname(), "write");
   util::LogbookWriter<bool> log("IncrementWriting", true);
   increment_->write(conf);
   Log::trace() << "Increment<MODEL>::write done" << std::endl;
 }
Referenced by oops::CostFct4DVarMFTemplate< MODEL >::addIncr(), and oops::CostFunction< MODEL >::recentreBackground().
zero() [1/2]
template<typename MODEL > void oops::Increment< MODEL >::zero
\(dx_1 = 0 \)
Definition at line 258 of file Increment.h.
{
   Log::trace() << "Increment<MODEL>::zero starting" << std::endl;
   util::Timer timer(classname(), "zero");
   increment_->zero();
   Log::trace() << "Increment<MODEL>::zero done" << std::endl;
 }
Referenced by oops::StaticCovariance4D< MODEL >::advectedMultiply(), oops::EnsembleCovariance4D< MODEL >::advectedMultiply(), oops::EnsembleCovariance4DScaleDependent< MODEL >::advectedMultiply(), oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::advectedMultiply(), oops::EnsembleCovariance4DDistributed< MODEL >::advectedMultiply(), oops::EnsembleCovsInterpol4D< MODEL >::advectedMultiply(), oops::StaticWithTLModelCovariance4D< MODEL >::advectedMultiply(), oops::EnsembleCovariance4DScaleDependent< MODEL >::advectedMultiplySqrt(), oops::StaticWithTLModelCovariance4D< MODEL >::advectedMultiplySqrt(), oops::StaticCovariance4D< MODEL >::advectedMultiplySqrtTrans(), oops::EnsembleCovariance4D< MODEL >::advectedMultiplySqrtTrans(), oops::EnsembleCovariance4DScaleDependent< MODEL >::advectedMultiplySqrtTrans(), oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::advectedMultiplySqrtTrans(), oops::EnsembleCovariance4DDistributed< MODEL >::advectedMultiplySqrtTrans(), oops::EnsembleCovsInterpol4D< MODEL >::advectedMultiplySqrtTrans(), oops::StaticWithTLModelCovariance4D< MODEL >::advectedMultiplySqrtTrans(), oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::assign_no_date_ctrl(), oops::Ensemble< MODEL >::build(), oops::EnsembleCovsInterpolSDL< MODEL >::inverseMultiply(), oops::HybridCovariance< MODEL >::inverseMultiply(), oops::HybridCovarianceGeneralCoeff< MODEL >::inverseMultiply(), oops::EnsembleCovsInterpol< MODEL >::inverseMultiply(), oops::EnsembleCovariance< MODEL >::inverseMultiply(), oops::EnsembleCovarianceSDL< MODEL >::inverseMultiply(), oops::EnsembleCovsInterpolSDL< MODEL >::multiply(), oops::EnsembleCovsInterpol< MODEL >::multiply(), oops::EnsembleCovarianceSDL< MODEL >::multiply(), oops::EnsembleCovariance< MODEL >::multiply(), oops::EnsembleCovsInterpolSDL< MODEL >::multiplySqrt(), oops::HybridCovariance< MODEL >::multiplySqrt(), oops::EnsembleCovsInterpol< MODEL >::multiplySqrt(), oops::EnsembleCovarianceSDL< MODEL >::multiplySqrt(), oops::EnsembleCovariance< MODEL >::multiplySqrt(), oops::EnsembleCovsInterpolSDL< MODEL >::multiplySqrtTrans(), oops::EnsembleCovsInterpol< MODEL >::multiplySqrtTrans(), oops::EnsembleCovsInterpolSDL< MODEL >::randomize(), oops::EnsembleCovsInterpol< MODEL >::randomize(), oops::EnsembleCovarianceSDL< MODEL >::randomize(), oops::EnsembleCovariance< MODEL >::randomize(), and oops::Ensemble< MODEL >::to_perturbations().
zero() [2/2]
template<typename MODEL > void oops::Increment< MODEL >::zero (const util::DateTime & tt)
\(dx_1 = 0, set valid time \)
Definition at line 268 of file Increment.h.
{
   Log::trace() << "Increment<MODEL>::zero starting" << std::endl;
   util::Timer timer(classname(), "zero");
   increment_->zero(tt);
   Log::trace() << "Increment<MODEL>::zero done" << std::endl;
 }
Friends And Related Function Documentation
operator<<
template<typename MODEL > eckit::Stream& operator<< (eckit::Stream & s, const Increment< MODEL > & dx) friend
Serialization.
Definition at line 132 of file Increment.h.
{
     s << dx.increment();
     return s;
   }
operator>>
template<typename MODEL > eckit::Stream& operator>> (eckit::Stream & s, Increment< MODEL > & dx) friend
Definition at line 136 of file Increment.h.
{
     s >> dx.increment();
     return s;
   }
Member Data Documentation
increment_
template<typename MODEL > std::unique_ptr<Increment_> oops::Increment< MODEL >::increment_ private
Pointer to the model specific increment object.
Definition at line 145 of file Increment.h.
Referenced by oops::Increment< MODEL >::Increment(), oops::Increment< MODEL >::increment(), oops::Increment< MODEL >::updateTime(), and oops::Increment< MODEL >::validTime().
The documentation for this class was generated from the following files:
src/oops/interface/GeoVaLs.h
src/oops/interface/Increment.h