OOPS Documentation: oops::ControlVector< MODEL > Class Template Reference
oops::ControlVector< MODEL > Class Template Reference
Control Vector.
#include <ControlVector.h>
Public Member Functions
ControlVector (const JbTotal_ &)
Constructor.
ControlVector (const JbTotal_ &, const ControlVector &)
Constructor with copy initialization.
ControlVector (const ControlVector &, const bool copy=true)
Copy constructor.
ControlVector (const ControlVector &, const eckit::Configuration &)
Copy constructor with additional configuration.
~ControlVector ()
Destructor.
void zero ()
\(dv_1 = 0 \)
ControlVector & operator= (const ControlVector &)
\(dv_1 = dv_2 \)
ControlVector & operator+= (const ControlVector &)
\(dv_1 = dv_1 + dv_2 \)
ControlVector & operator-= (const ControlVector &)
\(dv_1 = dv_1 - dv_2 \)
ControlVector & operator*= (const double)
\(dv_1 = dv_1 * c \)
void axpy (const double, const ControlVector &)
\(dv_1 = dv_1 * c dv_2 \)
double dot_product_with (const ControlVector &) const
\(<dv_1,dv_1> = dv_1^T dv_1 \)
void read (const eckit::Configuration &)
Read control vector.
void write (const eckit::Configuration &) const
Write control vector.
IncrCtlVec4D_ & state ()
Get state control vector.
const IncrCtlVec4D_ & state () const
Get constant state control vector.
ModelAuxCtlVec_ & modVar ()
Get augmented model control vector.
const ModelAuxCtlVec_ & modVar () const
Get constant augmented model control vector.
ObsAuxCtlVecs_ & obsVar ()
Get augmented observation control vector.
const ObsAuxCtlVecs_ & obsVar () const
Get constant augmented observation control vector.
Static Public Member Functions
static const std::string classname ()
Private Types
using JbTotal_ = CostJbTotal< MODEL >
using IncrCtlVec4D_ = IncrCtlVec4D< MODEL >
using ModelAuxCtlVec_ = ModelAuxCtlVec< MODEL >
using ObsAuxCtlVecs_ = ObsAuxCtlVecs< MODEL >
Private Member Functions
void print (std::ostream &) const
Private Attributes
IncrCtlVec4D_ incrCtlVec4D_
4D state component
ModelAuxCtlVec_ modAuxCtlVec_
Auxiliary model space component.
ObsAuxCtlVecs_ obsAuxCtlVecs_
Auxiliary observation space component.
Detailed Description
template<typename MODEL>
class oops::ControlVector< MODEL >
Control Vector.
The control vector acts as a container for the inputs of the variational data assimilation cost functions in the control variable space. That includes the control vectors at the start the assimilation window or of each sub-window but also additional variables such as model bias, VarBC coefficients, or other control variables for algorithms that use them. The control vector structure is determined by the B matrix.
The control vector \(dv \) has the following structure
\[ dv = \begin{bmatrix} dv_{state4D} \\ dv_{modaux} \\ dv_{obsaux} \end{bmatrix} \]
where
\f[  dv_{state4D} =  \begin{bmatrix} dv^0 \\
                                     dv^1 \\
                                     ..   \\
                                     dv^N
                      \end{bmatrix}
\f]
and N is the number of sub-windows. For each sub-window:
-> \(dv_{state4D} \) is implemented by IncrCtlVec4D containing a vector of IncrCtlVec objects:
\[ dv^K = \begin{bmatrix} dv^K_{mod} \\ dv^K_{ens} \end{bmatrix} = \begin{bmatrix} dv^K_{mod} \\ \begin{bmatrix} dv^K_{ens_{1}} \\ .. \\ dv^K_{ens_{L}} \end{bmatrix} \end{bmatrix} \]
-> \(dv^K_{mod} \) is implemented by IncrModCtlVec
-> \(dv^K_{ens_m} \) is implemented by IncrEnsCtlVec, L is the number of ensemble perturbations used to construct the localized sampled covariance matrix
\[ dv_{modaux} = \begin{bmatrix} dv_{modaux}^0 \end{bmatrix} \]
-> \(dv_{modaux} \) is implemented by ModelAuxCtlVec
\[ dv_{obsaux} = \begin{bmatrix} dv_{obsaux}^0 \\ dv_{obsaux}^1 \\ .. \\ dv_{obsaux}^K \end{bmatrix} \]
-> \(dv_{obsaux} \) is implemented by ObsAuxCtlVecs which contains a vector of ObsAuxCtlVec objects (\(dv_{obsaux}^i \)), which in turn contain a map of ObsAuxCtlVecBase objects (e.g \(dv_{VarBC}, dv_{TOVSCV} \)):
\[ dv_{obsaux}^i = \begin{bmatrix} dv_{obsaux,i}^0 \\ .. \\ dv_{obsaux,i}^L \end{bmatrix} \]
-> IFS: K=0, L=1:
\[ dv_{obsaux}= \begin{bmatrix} \begin{bmatrix} dv_{VarBC} \\ dv_{TOVSCV} \end{bmatrix} \end{bmatrix} \]
Definition at line 121 of file ControlVector.h.
Member Typedef Documentation
IncrCtlVec4D_
template<typename MODEL > using oops::ControlVector< MODEL >::IncrCtlVec4D_ = IncrCtlVec4D<MODEL> private
Definition at line 124 of file ControlVector.h.
JbTotal_
template<typename MODEL > using oops::ControlVector< MODEL >::JbTotal_ = CostJbTotal<MODEL> private
Definition at line 123 of file ControlVector.h.
ModelAuxCtlVec_
template<typename MODEL > using oops::ControlVector< MODEL >::ModelAuxCtlVec_ = ModelAuxCtlVec<MODEL> private
Definition at line 125 of file ControlVector.h.
ObsAuxCtlVecs_
template<typename MODEL > using oops::ControlVector< MODEL >::ObsAuxCtlVecs_ = ObsAuxCtlVecs<MODEL> private
Definition at line 126 of file ControlVector.h.
Constructor & Destructor Documentation
ControlVector() [1/4]
template<typename MODEL > oops::ControlVector< MODEL >::ControlVector (const JbTotal_ & jb) explicit
Constructor.
Definition at line 190 of file ControlVector.h.
     : incrCtlVec4D_(jb.jbState()),
       modAuxCtlVec_(jb.jbModBias().errorCovariance()),
       obsAuxCtlVecs_(jb.jbObsBias()) {
   Log::trace() << "ControlVector:ControlVector created." << std::endl;
 }
ControlVector() [2/4]
template<typename MODEL > oops::ControlVector< MODEL >::ControlVector (const JbTotal_ & jb, const ControlVector< MODEL > & other)
Constructor with copy initialization.
Definition at line 198 of file ControlVector.h.
     : incrCtlVec4D_(jb.jbState()),
       modAuxCtlVec_(jb.jbModBias().errorCovariance()),
       obsAuxCtlVecs_(jb.jbObsBias()) {
   incrCtlVec4D_ = other.incrCtlVec4D_;
   modAuxCtlVec_ = other.modAuxCtlVec_;
   obsAuxCtlVecs_ = other.obsAuxCtlVecs_;
   Log::trace() << "ControlVector:ControlVector created." << std::endl;
 }
References oops::ControlVector< MODEL >::incrCtlVec4D_, oops::ControlVector< MODEL >::modAuxCtlVec_, and oops::ControlVector< MODEL >::obsAuxCtlVecs_.
ControlVector() [3/4]
template<typename MODEL > oops::ControlVector< MODEL >::ControlVector (const ControlVector< MODEL > & other, const bool copy = true)
Copy constructor.
Definition at line 210 of file ControlVector.h.
     : incrCtlVec4D_(other.incrCtlVec4D_, copy),
       modAuxCtlVec_(other.modAuxCtlVec_, copy),
       obsAuxCtlVecs_(other.obsAuxCtlVecs_, copy) {
   Log::trace() << "ControlVector:ControlVector copied." << std::endl;
 }
ControlVector() [4/4]
template<typename MODEL > oops::ControlVector< MODEL >::ControlVector (const ControlVector< MODEL > & other, const eckit::Configuration & tlConf)
Copy constructor with additional configuration.
Definition at line 218 of file ControlVector.h.
     : incrCtlVec4D_(other.incrCtlVec4D_, tlConf),
       modAuxCtlVec_(other.modAuxCtlVec_, tlConf),
       obsAuxCtlVecs_(other.obsAuxCtlVecs_) {
   Log::trace() << "ControlVector:ControlVector copied." << std::endl;
 }
~ControlVector()
template<typename MODEL > oops::ControlVector< MODEL >::~ControlVector
Destructor.
Definition at line 227 of file ControlVector.h.
 {}
Member Function Documentation
axpy()
template<typename MODEL > void oops::ControlVector< MODEL >::axpy (const double zz, const ControlVector< MODEL > & rhs)
\(dv_1 = dv_1 * c dv_2 \)
Definition at line 272 of file ControlVector.h.
{
   incrCtlVec4D_.axpy(zz, rhs.incrCtlVec4D_);
   modAuxCtlVec_.axpy(zz, rhs.modAuxCtlVec_);
   obsAuxCtlVecs_.axpy(zz, rhs.obsAuxCtlVecs_);
 }
References oops::ControlVector< MODEL >::incrCtlVec4D_, oops::ControlVector< MODEL >::modAuxCtlVec_, and oops::ControlVector< MODEL >::obsAuxCtlVecs_.
Referenced by oops::QNewtonSqrtLMP< MODEL >::inverseMultiply(), oops::SpectralSqrtLMP< MODEL >::inverseMultiply(), oops::QNewtonSqrtLMP< MODEL >::inverseMultiplySqrt(), oops::SpectralSqrtLMP< MODEL >::inverseMultiplySqrt(), oops::SpectralSqrtLMP< MODEL >::multiplySqrt(), oops::SQRTBPLanczosMinimizer< MODEL >::solve(), oops::SQRTBPFOMMinimizer< MODEL >::solve(), oops::SQRTPCGMinimizer< MODEL >::solve(), and oops::SQRTBPCGMinimizer< MODEL >::solve().
classname()
template<typename MODEL > static const std::string oops::ControlVector< MODEL >::classname () inline static
Definition at line 129 of file ControlVector.h.
 { return "oops::ControlVector"; }
dot_product_with()
template<typename MODEL > double oops::ControlVector< MODEL >::dot_product_with (const ControlVector< MODEL > & x2) const
\(<dv_1,dv_1> = dv_1^T dv_1 \)
Definition at line 300 of file ControlVector.h.
{
   double zz = 0.0;
   zz += dot_product(incrCtlVec4D_, x2.incrCtlVec4D_);
   zz += dot_product(modAuxCtlVec_, x2.modAuxCtlVec_);
   zz += dot_product(obsAuxCtlVecs_, x2.obsAuxCtlVecs_);
   return zz;
 }
References dot_product(), oops::ControlVector< MODEL >::incrCtlVec4D_, oops::ControlVector< MODEL >::modAuxCtlVec_, and oops::ControlVector< MODEL >::obsAuxCtlVecs_.
modVar() [1/2]
template<typename MODEL > ModelAuxCtlVec_& oops::ControlVector< MODEL >::modVar () inline
Get augmented model control vector.
Definition at line 170 of file ControlVector.h.
 { return modAuxCtlVec_; }
References oops::ControlVector< MODEL >::modAuxCtlVec_.
Referenced by oops::CostJbTotal< MODEL >::addGradientFG(), oops::JbMatrix< MODEL >::multiply(), oops::CostJbTotal< MODEL >::multiplyBsqrt(), oops::CostJbTotal< MODEL >::multiplyBsqrtTrans(), and oops::SQRTMinimizer< MODEL >::updateJbCostFunction().
modVar() [2/2]
template<typename MODEL > const ModelAuxCtlVec_& oops::ControlVector< MODEL >::modVar () const inline
Get constant augmented model control vector.
Definition at line 172 of file ControlVector.h.
 { return modAuxCtlVec_; }
References oops::ControlVector< MODEL >::modAuxCtlVec_.
obsVar() [1/2]
template<typename MODEL > ObsAuxCtlVecs_& oops::ControlVector< MODEL >::obsVar () inline
Get augmented observation control vector.
Definition at line 175 of file ControlVector.h.
 { return obsAuxCtlVecs_; }
References oops::ControlVector< MODEL >::obsAuxCtlVecs_.
Referenced by oops::CostJbTotal< MODEL >::addGradientFG(), oops::SQRTMinimizer< MODEL >::enforceObsAuxFormulation(), oops::JbMatrix< MODEL >::multiply(), oops::CostJbTotal< MODEL >::multiplyBsqrt(), and oops::CostJbTotal< MODEL >::multiplyBsqrtTrans().
obsVar() [2/2]
template<typename MODEL > const ObsAuxCtlVecs_& oops::ControlVector< MODEL >::obsVar () const inline
Get constant augmented observation control vector.
Definition at line 177 of file ControlVector.h.
 { return obsAuxCtlVecs_; }
References oops::ControlVector< MODEL >::obsAuxCtlVecs_.
operator*=()
template<typename MODEL > ControlVector< MODEL > & oops::ControlVector< MODEL >::operator*= (const double zz)
\(dv_1 = dv_1 * c \)
Definition at line 257 of file ControlVector.h.
{
   incrCtlVec4D_ *= zz;
   modAuxCtlVec_ *= zz;
   obsAuxCtlVecs_ *= zz;
   return *this;
 }
operator+=()
template<typename MODEL > ControlVector< MODEL > & oops::ControlVector< MODEL >::operator+= (const ControlVector< MODEL > & rhs)
\(dv_1 = dv_1 + dv_2 \)
Definition at line 239 of file ControlVector.h.
{
   incrCtlVec4D_ += rhs.incrCtlVec4D_;
   modAuxCtlVec_ += rhs.modAuxCtlVec_;
   obsAuxCtlVecs_ += rhs.obsAuxCtlVecs_;
   return *this;
 }
References oops::ControlVector< MODEL >::incrCtlVec4D_, oops::ControlVector< MODEL >::modAuxCtlVec_, and oops::ControlVector< MODEL >::obsAuxCtlVecs_.
operator-=()
template<typename MODEL > ControlVector< MODEL > & oops::ControlVector< MODEL >::operator-= (const ControlVector< MODEL > & rhs)
\(dv_1 = dv_1 - dv_2 \)
Definition at line 248 of file ControlVector.h.
{
   incrCtlVec4D_ -= rhs.incrCtlVec4D_;
   modAuxCtlVec_ -= rhs.modAuxCtlVec_;
   obsAuxCtlVecs_ -= rhs.obsAuxCtlVecs_;
   return *this;
 }
References oops::ControlVector< MODEL >::incrCtlVec4D_, oops::ControlVector< MODEL >::modAuxCtlVec_, and oops::ControlVector< MODEL >::obsAuxCtlVecs_.
operator=()
template<typename MODEL > ControlVector< MODEL > & oops::ControlVector< MODEL >::operator= (const ControlVector< MODEL > & rhs)
\(dv_1 = dv_2 \)
Definition at line 230 of file ControlVector.h.
{
   incrCtlVec4D_ = rhs.incrCtlVec4D_;
   modAuxCtlVec_ = rhs.modAuxCtlVec_;
   obsAuxCtlVecs_ = rhs.obsAuxCtlVecs_;
   return *this;
 }
References oops::ControlVector< MODEL >::incrCtlVec4D_, oops::ControlVector< MODEL >::modAuxCtlVec_, and oops::ControlVector< MODEL >::obsAuxCtlVecs_.
print()
template<typename MODEL > void oops::ControlVector< MODEL >::print (std::ostream & outs) const private
Definition at line 293 of file ControlVector.h.
{
   outs << incrCtlVec4D_;
   outs << modAuxCtlVec_;
   outs << obsAuxCtlVecs_;
 }
read()
template<typename MODEL > void oops::ControlVector< MODEL >::read (const eckit::Configuration & config)
Read control vector.
Definition at line 279 of file ControlVector.h.
{
   incrCtlVec4D_.read(config);
   if (config.has("ctlvecModAux")) modAuxCtlVec_.read(config);
   if (config.has("ctlvecsObsAux")) obsAuxCtlVecs_.read(config);
 }
Referenced by oops::SQRTMinimizer< MODEL >::restartDvh().
state() [1/2]
template<typename MODEL > IncrCtlVec4D_& oops::ControlVector< MODEL >::state () inline
Get state control vector.
Definition at line 165 of file ControlVector.h.
 { return incrCtlVec4D_; }
References oops::ControlVector< MODEL >::incrCtlVec4D_.
Referenced by oops::CostJbTotal< MODEL >::addGradientFG(), oops::JbMatrix< MODEL >::multiply(), oops::CostJbTotal< MODEL >::multiplyBsqrt(), and oops::CostJbTotal< MODEL >::multiplyBsqrtTrans().
state() [2/2]
template<typename MODEL > const IncrCtlVec4D_& oops::ControlVector< MODEL >::state () const inline
Get constant state control vector.
Definition at line 167 of file ControlVector.h.
 { return incrCtlVec4D_; }
References oops::ControlVector< MODEL >::incrCtlVec4D_.
write()
template<typename MODEL > void oops::ControlVector< MODEL >::write (const eckit::Configuration & config) const
Write control vector.
Definition at line 286 of file ControlVector.h.
{
   incrCtlVec4D_.write(config);
   if (config.has("ctlvecModAux")) modAuxCtlVec_.write(config);
   if (config.has("ctlvecsObsAux")) obsAuxCtlVecs_.write(config);
 }
zero()
template<typename MODEL > void oops::ControlVector< MODEL >::zero
\(dv_1 = 0 \)
Definition at line 265 of file ControlVector.h.
{
   incrCtlVec4D_.zero();
   modAuxCtlVec_.zero();
   obsAuxCtlVecs_.zero();
 }
Referenced by oops::SQRTBPFOMMinimizer< MODEL >::solve(), and oops::SQRTBPLanczosMinimizer< MODEL >::solve().
Member Data Documentation
incrCtlVec4D_
template<typename MODEL > IncrCtlVec4D_ oops::ControlVector< MODEL >::incrCtlVec4D_ private
4D state component
Definition at line 182 of file ControlVector.h.
Referenced by oops::ControlVector< MODEL >::axpy(), oops::ControlVector< MODEL >::ControlVector(), oops::ControlVector< MODEL >::dot_product_with(), oops::ControlVector< MODEL >::operator+=(), oops::ControlVector< MODEL >::operator-=(), oops::ControlVector< MODEL >::operator=(), and oops::ControlVector< MODEL >::state().
modAuxCtlVec_
template<typename MODEL > ModelAuxCtlVec_ oops::ControlVector< MODEL >::modAuxCtlVec_ private
Auxiliary model space component.
Definition at line 183 of file ControlVector.h.
Referenced by oops::ControlVector< MODEL >::axpy(), oops::ControlVector< MODEL >::ControlVector(), oops::ControlVector< MODEL >::dot_product_with(), oops::ControlVector< MODEL >::modVar(), oops::ControlVector< MODEL >::operator+=(), oops::ControlVector< MODEL >::operator-=(), and oops::ControlVector< MODEL >::operator=().
obsAuxCtlVecs_
template<typename MODEL > ObsAuxCtlVecs_ oops::ControlVector< MODEL >::obsAuxCtlVecs_ private
Auxiliary observation space component.
Definition at line 184 of file ControlVector.h.
Referenced by oops::ControlVector< MODEL >::axpy(), oops::ControlVector< MODEL >::ControlVector(), oops::ControlVector< MODEL >::dot_product_with(), oops::ControlVector< MODEL >::obsVar(), oops::ControlVector< MODEL >::operator+=(), oops::ControlVector< MODEL >::operator-=(), and oops::ControlVector< MODEL >::operator=().
The documentation for this class was generated from the following file:
src/oops/assimilation/ControlVector.h