OOPS Documentation: oops::SQRTPLanczosMinimizer< MODEL > Class Template Reference
oops::SQRTPLanczosMinimizer< MODEL > Class Template Reference
SQRTPLanczosMinimizer.
#include <SQRTPLanczosMinimizer.h>
Public Member Functions
const std::string classname () const final
SQRTPLanczosMinimizer (const eckit::Configuration &, const CostFct_ &)
Constructor, destructor.
~SQRTPLanczosMinimizer ()
Public Member Functions inherited from oops::SQRTMinimizer< MODEL >
SQRTMinimizer (const eckit::Configuration &conf, const CostFct_ &J)
Construct the minimizer.
~SQRTMinimizer ()
Destroy the minimizer.
void checkpoint (eckit::LocalConfiguration &) const
Checkpoint the minimizer.
void restart (const eckit::Configuration &)
Restart the minimizer.
void warmStart (const eckit::Configuration &)
Warm start the minimizer.
Public Member Functions inherited from oops::Minimizer< MODEL >
Minimizer (const CostFct_ &J)
Construct a minimizer.
virtual ~Minimizer ()
Destroy a minimizer.
ControlIncrement< MODEL > * minimize (const eckit::Configuration &)
Orchestrate the minimization of a quadratic cost function.
Private Types
using CostFct_ = CostFunction< MODEL >
using CtrlVec_ = ControlVector< MODEL >
using Jbmat_ = JbMatrix< MODEL >
using UtHtRinvHU_ = UtHtRinvHUMatrix< MODEL >
Private Member Functions
double solve (CtrlVec_ &, CtrlVec_ &, const Jbmat_ &, const UtHtRinvHU_ &, const bool &, const size_t &, const size_t &, const double &, const double &, const double &) final
void releaseResources ()
void checkpointLMP (eckit::LocalConfiguration &) const final
Checkpointing, restart of the limited memory preconditioner.
void restartLMP (const eckit::Configuration &) final
Restart the limited memory preconditioner (virtual method)
void setupQuadCost (const double &costJ0Jb, const double &costJ0JoJc)
Quadratic cost function calculations.
void calcQuadCost (const CtrlVec_ &, const CtrlVec_ &, const std::vector< double > &)
void printQuadCost (const size_t &) const
bool calcRitzInformation ()
Other diagnostics.
void printRitzInformation (const size_t &) const
Private Attributes
const CostFct_ & J_
Data memebers.
SpectralSqrtLMP< MODEL > lmp_
LMP.
std::vector< std::shared_ptr< CtrlVec_ > > vvecs_
Local.
std::vector< double > alphas_
std::vector< double > betas_
std::vector< double > evals_
std::vector< double > eigvals_
std::vector< double > erritz_
std::vector< double > erritzlm_
std::vector< std::vector< double > > evecs_
std::vector< std::string > error_messages_
double costJ0_
Quadratic cost function calculations data members.
double costJ0Jb_
double costJ0JoJc_
double costJ_
double costJb_
double costJbLocal_
double costJoJc_
Additional Inherited Members
Protected Attributes inherited from oops::SQRTMinimizer< MODEL >
size_t iter_
Outer loop index.
size_t maxiter_
Number of outer loops.
Detailed Description
template<typename MODEL>
class oops::SQRTPLanczosMinimizer< MODEL >
SQRTPLanczosMinimizer.
Preconditioned Lanczos solver for the square root preconditioned formulation of the Hessian
The Hessian must be square, symmetric and positive definite.
On entry:
A = \((U^T B^{-1} U + U^T H^T R^{-1} U) \)
dv = starting point, \(dv_0 \).
rr = \((-\sum dv^{b}_{i} +) U^T H^T R^{-1} d - A dv_0 \)
or
rr = \(U^T H^T R^{-1} [d + H (x_b - x_{fg})] - A dv_0 \)
On exit, dv will contain the solution such that \(dx = U dv \) or \(dx = U dv + x_{b} - x_{fg} \) The solution is recovered in the SQRTMinimizer class The return value is the achieved reduction in preconditioned residual norm/information content gain.
Iteration will stop if the maximum iteration limit "maxiter" is reached or if the residual norm reduces by a factor of "tolerance"/information content based convergence criterion is reached.
Definition at line 64 of file SQRTPLanczosMinimizer.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::SQRTPLanczosMinimizer< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 65 of file SQRTPLanczosMinimizer.h.
CtrlVec_
template<typename MODEL > using oops::SQRTPLanczosMinimizer< MODEL >::CtrlVec_ = ControlVector<MODEL> private
Definition at line 66 of file SQRTPLanczosMinimizer.h.
Jbmat_
template<typename MODEL > using oops::SQRTPLanczosMinimizer< MODEL >::Jbmat_ = JbMatrix<MODEL> private
Definition at line 67 of file SQRTPLanczosMinimizer.h.
UtHtRinvHU_
template<typename MODEL > using oops::SQRTPLanczosMinimizer< MODEL >::UtHtRinvHU_ = UtHtRinvHUMatrix<MODEL> private
Definition at line 68 of file SQRTPLanczosMinimizer.h.
Constructor & Destructor Documentation
SQRTPLanczosMinimizer()
template<typename MODEL > oops::SQRTPLanczosMinimizer< MODEL >::SQRTPLanczosMinimizer (const eckit::Configuration & conf, const CostFct_ & J)
Constructor, destructor.
Definition at line 131 of file SQRTPLanczosMinimizer.h.
     : SQRTMinimizer<MODEL>(conf, J),
       J_(J),
       lmp_(conf, J),
       vvecs_(),
       alphas_(),
       betas_(),
       costJ0_(0),
       costJ0Jb_(0),
       costJ0JoJc_(0),
       costJ_(0),
       costJb_(0),
       costJbLocal_(0),
       costJoJc_(0) {}
~SQRTPLanczosMinimizer()
template<typename MODEL > oops::SQRTPLanczosMinimizer< MODEL >::~SQRTPLanczosMinimizer () inline
Definition at line 75 of file SQRTPLanczosMinimizer.h.
 {}
Member Function Documentation
calcQuadCost()
template<typename MODEL > void oops::SQRTPLanczosMinimizer< MODEL >::calcQuadCost (const CtrlVec_ & dv0, const CtrlVec_ & rr, const std::vector< double > & ss) private
Definition at line 405 of file SQRTPLanczosMinimizer.h.
{
   // Compute the quadratic cost function
   // J[du_{i}] = J[0] - 0.5 s_{i}^T Z_{i}^T r_{0}
   // Jb[du_{i}] = 0.5 s_{i}^T V_{i}^T Z_{i} s_{i}
   // Note: here we calculate the quadratic cost function in the preconditioned
   //       space;
   costJ_ = costJ0_;
   costJb_ = costJ0Jb_;
   costJbLocal_ = 0.0;
   for (size_t jj = 0; jj < ss.size(); ++jj) {
     costJ_ -= 0.5 * ss[jj] * dot_product(*vvecs_[jj], rr);
     costJbLocal_ +=
         0.5 * ss[jj] * dot_product(*vvecs_[jj], *vvecs_[jj]) * ss[jj];
     /* EA TODO:
      * if (not lclassicincrform) {
      *  costJbLocal_ += ss[jj] * dot_product(*vvecs_[jj], dv0);
     }*/
   }
   costJb_ += costJbLocal_;
   costJoJc_ = costJ_ - costJb_;
 }
References dot_product().
calcRitzInformation()
template<typename MODEL > bool oops::SQRTPLanczosMinimizer< MODEL >::calcRitzInformation private
Other diagnostics.
Definition at line 445 of file SQRTPLanczosMinimizer.h.
{
   ASSERT(alphas_.size() == betas_.size());
   const unsigned nvec = alphas_.size();
   bool ritzFailureCheckFlag = false;
   // Save the leading converged eigenvalue
   std::vector<double> eigvals_old;
   if (eigvals_.size() > 0) eigvals_old.push_back(eigvals_[0]);
   if (nvec > 0) {
     evals_.clear();
     eigvals_.clear();
     evecs_.clear();
     erritz_.clear();
     erritzlm_.clear();
     //  Compute spectrum of tri-diagonal matrix
     TriDiagSpectrum(alphas_, betas_, evals_, evecs_);
     //  Determine the converged eigenvalues
     for (unsigned jiter = 0; jiter < nvec; ++jiter) {
       double erritz = std::abs(evecs_[jiter][nvec - 1] * betas_[nvec - 1]);
       double lambda = evals_[jiter];
       if (lambda < 0) {
         // NEGATIVE RITZ VALUE DETECTED"
         ritzFailureCheckFlag = true;
         error_messages_.push_back("Negative Ritz value detected");
         break;
       }
       //    Add new converged eigenvalues
       double erritzlm = 0.0001 * lambda;
       if (erritz <= erritzlm) {
         eigvals_.push_back(lambda);
         erritz_.push_back(erritz);
         erritzlm_.push_back(erritzlm);
       }
     }
     // Check if Ritz values are not exploding
     if (eigvals_.size() != 0 && eigvals_old.size() != 0) {
       if (eigvals_[0] > 1.01 * eigvals_old[0]) {
         // RITZ VALUES EXPLODE!
         ritzFailureCheckFlag = true;
         Log::info() << "SQRTPLanczos: Ritz values explode" << std::endl
                     << "Leading Ritz value: " << eigvals_[0] << std::endl
                     << "Leading converged eigenvalue: " << eigvals_old[0]
                     << std::endl;
         error_messages_.push_back("Ritz values explode");
       }
     }
   }
   return ritzFailureCheckFlag;
 }
References oops::TriDiagSpectrum().
checkpointLMP()
template<typename MODEL > void oops::SQRTPLanczosMinimizer< MODEL >::checkpointLMP (eckit::LocalConfiguration & conf) const final private virtual
Checkpointing, restart of the limited memory preconditioner.
Implements oops::SQRTMinimizer< MODEL >.
Definition at line 528 of file SQRTPLanczosMinimizer.h.
{
   ASSERT(conf.has("preconditioner"));
   // Checkpoint lmp
   lmp_.checkpoint(conf);
 }
classname()
template<typename MODEL > const std::string oops::SQRTPLanczosMinimizer< MODEL >::classname () const inline final virtual
Implements oops::SQRTMinimizer< MODEL >.
Definition at line 71 of file SQRTPLanczosMinimizer.h.
 { return "SQRTPLanczosMinimizer"; }
printQuadCost()
template<typename MODEL > void oops::SQRTPLanczosMinimizer< MODEL >::printQuadCost (const size_t & jiter) const private
Definition at line 432 of file SQRTPLanczosMinimizer.h.
{
   // Print the quadratic cost function
   Log::info() << "  Quadratic cost function: J   (" << std::setw(2) << jiter + 1
               << ") = " << util::full_precision(costJ_) << std::endl
               << "  Quadratic cost function: Jb  (" << std::setw(2) << jiter + 1
               << ") = " << util::full_precision(costJb_) << std::endl
               << "  Quadratic cost function: JoJc(" << std::setw(2) << jiter + 1
               << ") = " << util::full_precision(costJoJc_) << std::endl;
 }
References util::full_precision().
printRitzInformation()
template<typename MODEL > void oops::SQRTPLanczosMinimizer< MODEL >::printRitzInformation (const size_t & jiter) const private
Definition at line 500 of file SQRTPLanczosMinimizer.h.
{
   ASSERT(alphas_.size() == betas_.size());
   const unsigned nvec = alphas_.size();
   if (nvec > 0) {
     Log::info() << "  Converged Ritz values (" << jiter + 1
                 << "):" << std::endl;
     for (auto const &eigval : eigvals_) {
       Log::info() << "    Ritz value: " << util::full_precision(eigval)
                   << std::endl;
     }
     for (auto const &err : erritz_) {
       Log::info() << "    Error bounds: " << util::full_precision(err)
                   << std::endl;
     }
     for (auto const &errlm : erritzlm_) {
       Log::info() << "    Error bound limits: " << util::full_precision(errlm)
                   << std::endl;
     }
     Log::info() << std::endl;
   }
   return;
 }
References util::full_precision().
releaseResources()
template<typename MODEL > void oops::SQRTPLanczosMinimizer< MODEL >::releaseResources private
Definition at line 372 of file SQRTPLanczosMinimizer.h.
{
   vvecs_.clear();
   alphas_.clear();
   betas_.clear();
   evals_.clear();
   eigvals_.clear();
   evecs_.clear();
   erritz_.clear();
   erritzlm_.clear();
 }
restartLMP()
template<typename MODEL > void oops::SQRTPLanczosMinimizer< MODEL >::restartLMP (const eckit::Configuration &) final private virtual
Restart the limited memory preconditioner (virtual method)
Implements oops::SQRTMinimizer< MODEL >.
Definition at line 539 of file SQRTPLanczosMinimizer.h.
{
   ASSERT(conf.has("preconditioner"));
   // Restart lmp
   lmp_.restart(conf);
 }
setupQuadCost()
template<typename MODEL > void oops::SQRTPLanczosMinimizer< MODEL >::setupQuadCost (const double & costJ0Jb, const double & costJ0JoJc) private
Quadratic cost function calculations.
Definition at line 386 of file SQRTPLanczosMinimizer.h.
{
   // J0
   costJ0Jb_ = costJ0Jb;
   costJ0JoJc_ = costJ0JoJc;
   // J0
   costJ0_ = costJ0Jb_ + costJ0JoJc_;
   // reset
   costJ_ = 0;
   costJb_ = 0;
   costJbLocal_ = 0;
   costJoJc_ = 0;
 }
solve()
template<typename MODEL > double oops::SQRTPLanczosMinimizer< MODEL >::solve (CtrlVec_ & dv, CtrlVec_ & rr, const Jbmat_ & Jb, const UtHtRinvHU_ & UtHtRinvHU, const bool & linfoconv, const size_t & maxiter, const size_t & miniter, const double & tolerance, const double & costJ0Jb, const double & costJ0JoJc) final private virtual
Implements oops::SQRTMinimizer< MODEL >.
Definition at line 150 of file SQRTPLanczosMinimizer.h.
{
   // dv   control vector
   std::vector<double> ss;
   std::vector<double> dd;
   // J0
   this->setupQuadCost(costJ0Jb, costJ0JoJc);
   // Change resolution of LMP vectors
   lmp_.changeResolution();
   // Postprocess preconditioning vectors
   lmp_.postprocess();
   // v_{0} = P^-1/2 r_{0}
   std::unique_ptr<CtrlVec_> mrr(new CtrlVec_(rr, false));
   lmp_.inverseMultiplySqrt(rr, *mrr);
   std::unique_ptr<CtrlVec_> vv(new CtrlVec_(*mrr));
   // beta_{0} = sqrt( v_{0}^T v_{0} )
   double beta = sqrt(dot_product(*vv, *vv));
   const double beta0 = beta;
   // v_{1} = r_{0} / beta_{0}
   *vv *= 1.0 / beta;
   // vvecs[0] = v_{1} ---> for re-orthogonalization
   vvecs_.push_back(std::shared_ptr<CtrlVec_>(new CtrlVec_(*vv)));
   double normReduction = 1.0;
   double zdfi = 0.0;
   bool convergenceReached = false;
   size_t jiter = 0;
   std::unique_ptr<CtrlVec_> mvv(new CtrlVec_(dv, false));
   std::unique_ptr<CtrlVec_> jbzz(new CtrlVec_(dv, false));
   std::unique_ptr<CtrlVec_> zz(new CtrlVec_(rr, false));
   while (jiter < maxiter) {
     Log::info() << "SQRTPLanczos Starting Iteration " << jiter + 1 << std::endl;
     util::LogbookWriter<size_t> log("InnerLoop", jiter + 1);
     // v_{i+1} = P^-1/2 ( I + U^T H^T R^{-1} H U ) P^-1/2 v_{i}
     lmp_.inverseMultiplySqrt(*vv, *mvv);
     UtHtRinvHU.multiply(*mvv, *zz);
     Jb.multiply(*mvv, *jbzz);
     *zz += *jbzz;
     lmp_.inverseMultiplySqrt(*zz, *vv);
     // v_{i+1} = v_{i+1} - beta * v_{i-1}
     if (jiter > 0) vv->axpy(-beta, *vvecs_[jiter - 1]);
     // alpha_{i} = v_{i+1}^T v_{i}
     double alpha = dot_product(*vvecs_[jiter], *vv);
     if (alpha <= 0.0) {
       error_messages_.push_back(
           "SQRTPLanczos: stopping J'' not positive definite");
       break;
     }
     // v_{i+1} = v_{i+1} - alpha_{i} v_{i}
     vv->axpy(-alpha, *vvecs_[jiter]);
     // Re-orthogonalization
     for (size_t jj = 0; jj < jiter; ++jj) {
       double proj = dot_product(*vv, *vvecs_[jj]);
       vv->axpy(-proj, *vvecs_[jj]);
     }
     // beta_{i+1} = sqrt( vv_{i+1}^t, vv_{i+1} )
     beta = sqrt(dot_product(*vv, *vv));
     // v_{i+1} = v_{i+1} / beta_{i+1}
     *vv *= 1.0 / beta;
     // vvecs[i+1] = v_{i+1}
     vvecs_.push_back(std::shared_ptr<CtrlVec_>(new CtrlVec_(*vv)));
     alphas_.push_back(alpha);
     if (jiter == 0) {
       ss.push_back(beta0 / alpha);
       dd.push_back(beta0);
     } else {
       // Solve the tridiagonal system T_{i} s_{i} = beta0 * e_1
       dd.push_back(beta0 * dot_product(*vvecs_[0], *vv));
       TriDiagSolve(alphas_, betas_, dd, ss);
     }
     betas_.push_back(beta);
     // Compute the quadratic cost function
     this->calcQuadCost(dv, *mrr, ss);
     // Compute the Ritz information
     bool ritzFailureCheckFlag = this->calcRitzInformation();
     // Convergence criterion
     if (linfoconv) {
       // Information content based convergence criterion
       //  - Information content defined as 0.5 dv^T dv
       //  - We should measure the change in the solution vector length
       //    in the un-preconditioned metric
       //  - This would require additional call to the preconditioner
       double zdfi_old = zdfi;
       zdfi = costJbLocal_;
       ASSERT(zdfi != 0.0);
       normReduction = (zdfi - zdfi_old) / zdfi;
       Log::info() << "SQRTPLanczos end of iteration " << jiter + 1 << std::endl
                   << "  Relative information content gain (" << std::setw(2)
                   << jiter + 1 << ") = " << util::full_precision(normReduction)
                   << std::endl;
     } else {
       // Gradient reduction based convergence criterion
       // Gradient norm in precond metric --> sqrt(r'z) --> beta * s_{i}
       double rznorm = beta * std::abs(ss[jiter]);
       normReduction = rznorm / beta0;
       Log::info() << "SQRTPLanczos end of iteration " << jiter + 1 << std::endl
                                                                         << "  Norm gradient  (" << std::setw(2) << jiter+1 << ") = "
                   << util::full_precision(rznorm) << std::endl
                   << "  Norm reduction (" << std::setw(2) << jiter + 1
                   << ") = " << util::full_precision(normReduction) << std::endl;
     }
     if (normReduction < tolerance && jiter >= miniter)
       convergenceReached = true;
     util::LogbookWriter<double> log_norm("NormReduction", normReduction);
     // Print iteration summary
     this->printQuadCost(jiter);
     this->printRitzInformation(jiter);
     // Compute online diagnostics
     UtHtRinvHU.computeDiagnostics(ss, convergenceReached);
     // Check if convergence criteria are met
     if (ritzFailureCheckFlag) break;
     if (normReduction < tolerance && (jiter+1) >= miniter) {
       convergenceReached = true;
       ++jiter;
       break;
     }
     // Increment iteration counter
     ++jiter;
   }
   // Free memory
   mrr.reset();
   vv.reset();
   mvv.reset();
   jbzz.reset();
   zz.reset();
   // Print summary
   Log::info() << "Summary of SQRTPLanczos solver: " << std::endl
               << " Information based convergence criterion: " << linfoconv
               << std::endl
               << " Number of iterations performed: " << jiter << std::endl
               << " Maximum allowed number of iterations: " << maxiter
               << std::endl
               << " Minimum allowed number of iterations: " << miniter
               << std::endl;
   if (linfoconv) {
     Log::info() << " Required relative gain in information content: "
                 << tolerance << std::endl
                 << " Last relative gain in information content: "
                 << normReduction << std::endl;
   } else {
     Log::info() << " Required reduction in norm of gradient: " << tolerance
                 << std::endl
                 << " Achieved reduction in norm of gradient: " << normReduction
                 << std::endl;
   }
   if (convergenceReached) {
     Log::info() << " Requested convergence criteria met. Well done. "
                 << std::endl;
   } else {
     Log::info() << " Failed to meet convergence criteria. " << std::endl;
     for (auto const &err : error_messages_) {
       Log::info() << "  " << err << std::endl;
     }
   }
   Log::info() << std::endl;
   // Calculate the solution
   std::unique_ptr<CtrlVec_> dv0(new CtrlVec_(dv));
   std::unique_ptr<CtrlVec_> mdv(new CtrlVec_(dv, false));
   mdv->zero();
   for (size_t jj = 0; jj < ss.size(); ++jj) {
     mdv->axpy(ss[jj], *vvecs_[jj]);
   }
   // Transform control variable back to space with scalar product
   lmp_.inverseMultiplySqrt(*mdv, dv);
   dv += *dv0;
   // Free memory
   dv0.reset();
   mdv.reset();
   // Update LMP
   if (SQRTMinimizer<MODEL>::iter_ < SQRTMinimizer<MODEL>::maxiter_)
     lmp_.update(vvecs_, alphas_, betas_);
   // Clean up
   releaseResources();
   return normReduction;
 }
References oops::UtHtRinvHUMatrix< MODEL >::computeDiagnostics(), dot_product(), util::full_precision(), oops::JbMatrix< MODEL >::multiply(), oops::UtHtRinvHUMatrix< MODEL >::multiply(), and oops::TriDiagSolve().
Member Data Documentation
alphas_
template<typename MODEL > std::vector<double> oops::SQRTPLanczosMinimizer< MODEL >::alphas_ private
Definition at line 106 of file SQRTPLanczosMinimizer.h.
betas_
template<typename MODEL > std::vector<double> oops::SQRTPLanczosMinimizer< MODEL >::betas_ private
Definition at line 107 of file SQRTPLanczosMinimizer.h.
costJ0_
template<typename MODEL > double oops::SQRTPLanczosMinimizer< MODEL >::costJ0_ private
Quadratic cost function calculations data members.
Definition at line 118 of file SQRTPLanczosMinimizer.h.
costJ0Jb_
template<typename MODEL > double oops::SQRTPLanczosMinimizer< MODEL >::costJ0Jb_ private
Definition at line 119 of file SQRTPLanczosMinimizer.h.
costJ0JoJc_
template<typename MODEL > double oops::SQRTPLanczosMinimizer< MODEL >::costJ0JoJc_ private
Definition at line 120 of file SQRTPLanczosMinimizer.h.
costJ_
template<typename MODEL > double oops::SQRTPLanczosMinimizer< MODEL >::costJ_ private
Definition at line 122 of file SQRTPLanczosMinimizer.h.
costJb_
template<typename MODEL > double oops::SQRTPLanczosMinimizer< MODEL >::costJb_ private
Definition at line 123 of file SQRTPLanczosMinimizer.h.
costJbLocal_
template<typename MODEL > double oops::SQRTPLanczosMinimizer< MODEL >::costJbLocal_ private
Definition at line 124 of file SQRTPLanczosMinimizer.h.
costJoJc_
template<typename MODEL > double oops::SQRTPLanczosMinimizer< MODEL >::costJoJc_ private
Definition at line 125 of file SQRTPLanczosMinimizer.h.
eigvals_
template<typename MODEL > std::vector<double> oops::SQRTPLanczosMinimizer< MODEL >::eigvals_ private
Definition at line 110 of file SQRTPLanczosMinimizer.h.
erritz_
template<typename MODEL > std::vector<double> oops::SQRTPLanczosMinimizer< MODEL >::erritz_ private
Definition at line 111 of file SQRTPLanczosMinimizer.h.
erritzlm_
template<typename MODEL > std::vector<double> oops::SQRTPLanczosMinimizer< MODEL >::erritzlm_ private
Definition at line 112 of file SQRTPLanczosMinimizer.h.
error_messages_
template<typename MODEL > std::vector<std::string> oops::SQRTPLanczosMinimizer< MODEL >::error_messages_ private
Definition at line 115 of file SQRTPLanczosMinimizer.h.
evals_
template<typename MODEL > std::vector<double> oops::SQRTPLanczosMinimizer< MODEL >::evals_ private
Definition at line 109 of file SQRTPLanczosMinimizer.h.
evecs_
template<typename MODEL > std::vector<std::vector<double> > oops::SQRTPLanczosMinimizer< MODEL >::evecs_ private
Definition at line 113 of file SQRTPLanczosMinimizer.h.
J_
template<typename MODEL > const CostFct_& oops::SQRTPLanczosMinimizer< MODEL >::J_ private
Data memebers.
Definition at line 99 of file SQRTPLanczosMinimizer.h.
lmp_
template<typename MODEL > SpectralSqrtLMP<MODEL> oops::SQRTPLanczosMinimizer< MODEL >::lmp_ private
LMP.
Definition at line 102 of file SQRTPLanczosMinimizer.h.
vvecs_
template<typename MODEL > std::vector<std::shared_ptr<CtrlVec_> > oops::SQRTPLanczosMinimizer< MODEL >::vvecs_ private
Local.
Definition at line 105 of file SQRTPLanczosMinimizer.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/SQRTPLanczosMinimizer.h