OOPS Documentation: oops::QNewtonSqrtLMP< MODEL > Class Template Reference
oops::QNewtonSqrtLMP< MODEL > Class Template Reference
#include <QNewtonSqrtLMP.h>
Public Member Functions
QNewtonSqrtLMP (const eckit::Configuration &, const CostFct_ &)
~QNewtonSqrtLMP ()
void push (const CtrlVec_ &, const CtrlVec_ &, const CtrlVec_ &, const double &)
void update ()
void changeResolution ()
void inverseMultiplySqrt (const CtrlVec_ &, CtrlVec_ &) const
void inverseMultiply (const CtrlVec_ &, CtrlVec_ &) const
Private Types
using CostFct_ = CostFunction< MODEL >
using CtrlVec_ = ControlVector< MODEL >
Private Attributes
const CostFct_ & J_
const bool active_
unsigned maxpairs_
unsigned maxnewpairs_
bool useoldpairs_
int maxouter_
int update_
std::vector< std::shared_ptr< CtrlVec_ > > P_
std::vector< std::shared_ptr< CtrlVec_ > > R_
std::vector< std::shared_ptr< CtrlVec_ > > AP_
std::vector< double > rhos_
std::vector< unsigned > usedpairIndx_
std::vector< CtrlVec_ > savedP_
std::vector< CtrlVec_ > savedR_
std::vector< CtrlVec_ > savedAP_
std::vector< double > savedrhos_
Detailed Description
template<typename MODEL>
class oops::QNewtonSqrtLMP< MODEL >
Definition at line 44 of file QNewtonSqrtLMP.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::QNewtonSqrtLMP< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 45 of file QNewtonSqrtLMP.h.
CtrlVec_
template<typename MODEL > using oops::QNewtonSqrtLMP< MODEL >::CtrlVec_ = ControlVector<MODEL> private
Definition at line 46 of file QNewtonSqrtLMP.h.
Constructor & Destructor Documentation
QNewtonSqrtLMP()
template<typename MODEL > oops::QNewtonSqrtLMP< MODEL >::QNewtonSqrtLMP (const eckit::Configuration & conf, const CostFct_ & J) explicit
Definition at line 84 of file QNewtonSqrtLMP.h.
     : J_(J),
       active_(conf.has("preconditioner")),
       maxpairs_(0),
       maxnewpairs_(0),
       useoldpairs_(false),
       maxouter_(0),
       update_(1) {
   if (active_) {
     maxouter_ = conf.getInt("minimizations");
     Log::info() << "QNewtonSqrtLMP: maxouter : " << maxouter_ << std::endl;
     const eckit::LocalConfiguration precond(conf, "preconditioner");
     if (precond.has("maxpairs")) maxpairs_ = precond.getInt("maxpairs");
     if (maxpairs_ > 0) {
       std::string old;
       if (precond.has("useoldpairs")) old = precond.getString("useoldpairs");
       useoldpairs_ = (old == "on" || old == "true");
       if (useoldpairs_ && precond.has("maxnewpairs")) {
         maxnewpairs_ = precond.getInt("maxnewpairs");
         maxnewpairs_ = std::min(maxpairs_, maxnewpairs_);
       } else {
         maxnewpairs_ = maxpairs_;
       }
     }
   }
 }
References oops::QNewtonSqrtLMP< MODEL >::active_, oops::QNewtonSqrtLMP< MODEL >::maxnewpairs_, oops::QNewtonSqrtLMP< MODEL >::maxouter_, oops::QNewtonSqrtLMP< MODEL >::maxpairs_, and oops::QNewtonSqrtLMP< MODEL >::useoldpairs_.
~QNewtonSqrtLMP()
template<typename MODEL > oops::QNewtonSqrtLMP< MODEL >::~QNewtonSqrtLMP () inline
Definition at line 50 of file QNewtonSqrtLMP.h.
 {}
Member Function Documentation
changeResolution()
template<typename MODEL > void oops::QNewtonSqrtLMP< MODEL >::changeResolution
Definition at line 228 of file QNewtonSqrtLMP.h.
{
   if (active_) {
     Log::info() << "QNewtonSqrtLMP:::changeResolution starting" << std::endl;
     for (auto &pp : P_) pp.reset(new CtrlVec_(J_.jb(), *pp));
     for (auto &rr : R_) rr.reset(new CtrlVec_(J_.jb(), *rr));
     for (auto &ap : AP_) ap.reset(new CtrlVec_(J_.jb(), *ap));
     Log::info() << "QNewtonSqrtLMP:::changeResolution done" << std::endl;
   }
 }
inverseMultiply()
template<typename MODEL > void oops::QNewtonSqrtLMP< MODEL >::inverseMultiply (const CtrlVec_ & a, CtrlVec_ & b) const
Definition at line 258 of file QNewtonSqrtLMP.h.
{
   b = a;
   const unsigned nvec = P_.size();
   if (nvec != 0) {
     std::vector<double> etas(nvec, 0);
     // etas.clear();
     for (int iiter = nvec - 1; iiter >= 0; iiter--) {
       double eta = dot_product(b, *P_[iiter]);
       eta *= rhos_[iiter];
       etas[iiter] = eta;
       b.axpy(-eta, *AP_[iiter]);
     }
     b *= dot_product(*AP_[nvec - 1], *P_[nvec - 1]) /
          dot_product(*AP_[nvec - 1], *AP_[nvec - 1]);
     for (unsigned iiter = 0; iiter < nvec; ++iiter) {
       double sigma = dot_product(b, *AP_[iiter]);
       sigma *= rhos_[iiter];
       sigma -= etas[iiter];
       b.axpy(-sigma, *P_[iiter]);
     }
   }
 }
References oops::ControlVector< MODEL >::axpy(), and dot_product().
inverseMultiplySqrt()
template<typename MODEL > void oops::QNewtonSqrtLMP< MODEL >::inverseMultiplySqrt (const CtrlVec_ & a, CtrlVec_ & b) const
Definition at line 241 of file QNewtonSqrtLMP.h.
{
   b = a;
   const unsigned nvec = P_.size();
   if (nvec != 0) {
     for (unsigned iiter = 0; iiter < nvec; ++iiter) {
       double factor = sqrt(rhos_[iiter]) * dot_product(*R_[iiter], b) /
                       sqrt(dot_product(*R_[iiter], *R_[iiter]));
       factor += rhos_[iiter] * dot_product(*AP_[iiter], b);
       b.axpy(-factor, *P_[iiter]);
     }
   }
 }
References oops::ControlVector< MODEL >::axpy(), and dot_product().
push()
template<typename MODEL > void oops::QNewtonSqrtLMP< MODEL >::push (const CtrlVec_ & p, const CtrlVec_ & ph, const CtrlVec_ & ap, const double & rho)
Definition at line 116 of file QNewtonSqrtLMP.h.
{
   if (active_) {
     ASSERT(savedP_.size() <= maxnewpairs_);
     if (maxnewpairs_ > 0 && update_ < maxouter_) {
       if (savedP_.size() == maxnewpairs_) {
         savedP_.erase(savedP_.begin());
         savedR_.erase(savedR_.begin());
         savedAP_.erase(savedAP_.begin());
         savedrhos_.erase(savedrhos_.begin());
       }
       savedP_.push_back(p);
       savedR_.push_back(ph);
       savedAP_.push_back(ap);
       savedrhos_.push_back(1.0 / rho);
     }
   }
 }
update()
template<typename MODEL > void oops::QNewtonSqrtLMP< MODEL >::update
Definition at line 138 of file QNewtonSqrtLMP.h.
{
   if (active_) {
     Log::debug() << "QNewtonLMP size saved Ph    = " << savedR_.size()
                  << std::endl;
     Log::debug() << "QNewtonLMP size saved P     = " << savedP_.size()
                  << std::endl;
     Log::debug() << "QNewtonLMP size saved AP    = " << savedAP_.size()
                  << std::endl;
     Log::debug() << "QNewtonLMP size saved rhos  = " << savedrhos_.size()
                  << std::endl;
     const unsigned nvec = savedR_.size();
     ASSERT(savedP_.size() == nvec);
     ASSERT(savedAP_.size() == nvec);
     ASSERT(savedrhos_.size() == nvec);
     if (!useoldpairs_ || nvec >= maxpairs_) {
       R_.clear();
       P_.clear();
       AP_.clear();
       rhos_.clear();
       for (unsigned kiter = 0; kiter < usedpairIndx_.size(); ++kiter) {
         usedpairIndx_[kiter] = 0;
       }
     }
     if (nvec > 0 && update_ < maxouter_) {
       Log::info() << "QNewtonLMP: update " << update_
                   << ", max = " << maxouter_ - 1 << std::endl;
       unsigned newpairs = std::min(nvec, maxpairs_);
       unsigned oldpairs = P_.size();
       unsigned rmpairs = 0;
       //    First remove pairs we no longer need.
       if (oldpairs + newpairs > maxpairs_) {
         rmpairs = oldpairs + newpairs - maxpairs_;
         for (unsigned jv = 0; jv < rmpairs; ++jv) {
           R_.erase(R_.begin());
           P_.erase(P_.begin());
           AP_.erase(AP_.begin());
           rhos_.erase(rhos_.begin());
         }
         oldpairs -= rmpairs;
         //      Keep information on how many pairs are used at each minimization
         //      loop
         unsigned removed = rmpairs;
         for (unsigned kiter = 0; kiter < usedpairIndx_.size(); ++kiter) {
           unsigned rmiter = std::min(usedpairIndx_[kiter], removed);
           usedpairIndx_[kiter] -= rmiter;
           removed -= rmiter;
         }
         ASSERT(removed == 0);
       }
       ASSERT(P_.size() == oldpairs);
       ASSERT(oldpairs + newpairs <= maxpairs_);
       //    Add the new pairs.
       for (unsigned jv = nvec - newpairs; jv < nvec; ++jv) {
         P_.push_back(std::shared_ptr<CtrlVec_>(new CtrlVec_(savedP_[jv])));
         R_.push_back(std::shared_ptr<CtrlVec_>(new CtrlVec_(savedR_[jv])));
         AP_.push_back(std::shared_ptr<CtrlVec_>(new CtrlVec_(savedAP_[jv])));
         rhos_.push_back(savedrhos_[jv]);
       }
       ASSERT(P_.size() == oldpairs + newpairs);
       Log::info() << "Number of inner iterations       : " << nvec << std::endl;
       Log::info() << "Number of maximum pairs          : " << maxpairs_
                   << std::endl;
       Log::info() << "Number of used total pairs       : "
                   << oldpairs + newpairs << std::endl;
       Log::info() << "Number of new pairs              : " << newpairs
                   << std::endl;
       Log::info() << "Number of removed old pairs      : " << rmpairs
                   << std::endl;
       for (unsigned kiter = 0; kiter < usedpairIndx_.size(); ++kiter) {
         Log::info() << "Number of used pairs from outer loop " << kiter + 1
                     << " : " << usedpairIndx_[kiter];
       }
     }
     ++update_;
     savedP_.clear();
     savedR_.clear();
     savedAP_.clear();
     savedrhos_.clear();
   }
 }
Member Data Documentation
active_
template<typename MODEL > const bool oops::QNewtonSqrtLMP< MODEL >::active_ private
Definition at line 62 of file QNewtonSqrtLMP.h.
Referenced by oops::QNewtonSqrtLMP< MODEL >::QNewtonSqrtLMP().
AP_
template<typename MODEL > std::vector<std::shared_ptr<CtrlVec_> > oops::QNewtonSqrtLMP< MODEL >::AP_ private
Definition at line 71 of file QNewtonSqrtLMP.h.
J_
template<typename MODEL > const CostFct_& oops::QNewtonSqrtLMP< MODEL >::J_ private
Definition at line 61 of file QNewtonSqrtLMP.h.
maxnewpairs_
template<typename MODEL > unsigned oops::QNewtonSqrtLMP< MODEL >::maxnewpairs_ private
Definition at line 64 of file QNewtonSqrtLMP.h.
Referenced by oops::QNewtonSqrtLMP< MODEL >::QNewtonSqrtLMP().
maxouter_
template<typename MODEL > int oops::QNewtonSqrtLMP< MODEL >::maxouter_ private
Definition at line 66 of file QNewtonSqrtLMP.h.
Referenced by oops::QNewtonSqrtLMP< MODEL >::QNewtonSqrtLMP().
maxpairs_
template<typename MODEL > unsigned oops::QNewtonSqrtLMP< MODEL >::maxpairs_ private
Definition at line 63 of file QNewtonSqrtLMP.h.
Referenced by oops::QNewtonSqrtLMP< MODEL >::QNewtonSqrtLMP().
P_
template<typename MODEL > std::vector<std::shared_ptr<CtrlVec_> > oops::QNewtonSqrtLMP< MODEL >::P_ private
Definition at line 69 of file QNewtonSqrtLMP.h.
R_
template<typename MODEL > std::vector<std::shared_ptr<CtrlVec_> > oops::QNewtonSqrtLMP< MODEL >::R_ private
Definition at line 70 of file QNewtonSqrtLMP.h.
rhos_
template<typename MODEL > std::vector<double> oops::QNewtonSqrtLMP< MODEL >::rhos_ private
Definition at line 72 of file QNewtonSqrtLMP.h.
savedAP_
template<typename MODEL > std::vector<CtrlVec_> oops::QNewtonSqrtLMP< MODEL >::savedAP_ private
Definition at line 77 of file QNewtonSqrtLMP.h.
savedP_
template<typename MODEL > std::vector<CtrlVec_> oops::QNewtonSqrtLMP< MODEL >::savedP_ private
Definition at line 75 of file QNewtonSqrtLMP.h.
savedR_
template<typename MODEL > std::vector<CtrlVec_> oops::QNewtonSqrtLMP< MODEL >::savedR_ private
Definition at line 76 of file QNewtonSqrtLMP.h.
savedrhos_
template<typename MODEL > std::vector<double> oops::QNewtonSqrtLMP< MODEL >::savedrhos_ private
Definition at line 78 of file QNewtonSqrtLMP.h.
update_
template<typename MODEL > int oops::QNewtonSqrtLMP< MODEL >::update_ private
Definition at line 67 of file QNewtonSqrtLMP.h.
usedpairIndx_
template<typename MODEL > std::vector<unsigned> oops::QNewtonSqrtLMP< MODEL >::usedpairIndx_ private
Definition at line 73 of file QNewtonSqrtLMP.h.
useoldpairs_
template<typename MODEL > bool oops::QNewtonSqrtLMP< MODEL >::useoldpairs_ private
Definition at line 65 of file QNewtonSqrtLMP.h.
Referenced by oops::QNewtonSqrtLMP< MODEL >::QNewtonSqrtLMP().
The documentation for this class was generated from the following file:
src/oops/assimilation/QNewtonSqrtLMP.h