OOPS Documentation: oops::ObsErrorCovariance< MODEL > Class Template Reference
oops::ObsErrorCovariance< MODEL > Class Template Reference
Encapsulates observation and observation bias error covariance matrices.
#include <ObsErrorCovariance.h>
Public Member Functions
ObsErrorCovariance (const ObsSpace_ &, const eckit::Configuration &)
Constructor.
~ObsErrorCovariance ()
Destructor.
void linearize (const ControlObsVector_ &)
Setup the covariance matrix.
void setupWeights (const ControlObsVector_ &)
Setup the VarQC weights.
ControlObsVector_ * multiply (const ControlObsVector_ &) const
Multiply a Departure by \(\bar{R}\).
ControlObsVector_ * inverseMultiply (const ControlObsVector_ &) const
Multiply a Departure by \(\bar{R}^{-1}\).
void randomize (ControlObsVector_ &) const
Generate random perturbation.
double getRMSE () const
Get mean error for Jo table.
Static Public Member Functions
static const std::string classname ()
Private Types
using ObsErrorBase_ = ObsErrorBase< MODEL >
using ObsSpace_ = ObservationSpace< MODEL >
using ObsVector_ = ObsVector< MODEL >
using ControlObsVector_ = ControlObsVector< MODEL >
Private Member Functions
ControlObsVector_ * multiplyWghtSqrt_ (const ControlObsVector_ &) const
\(\bar{y}_1 = \bar{W}^{1/2} \bar{y}_2 \)
ControlObsVector_ * inverseMultiply_ (const ControlObsVector_ &) const
\(\bar{y}_1 = \bar{R}^{-1} \bar{y}_2 \)
void print (std::ostream &) const
Private Attributes
bool lvarqc_
Controls VarQC.
std::unique_ptr< ObsErrorBase_ > covar_
Pointer to observation error covariance.
std::unique_ptr< ObsErrorBase_ > biascovar_
Pointer to bias error covariance.
Detailed Description
template<typename MODEL>
class oops::ObsErrorCovariance< MODEL >
Encapsulates observation and observation bias error covariance matrices.
This class provides the operations associated with the observation and observation bias error covariance matrices. It wraps the actual observation and observation bias error covariance matrices which can be model specific or generic.
The interface for the observation error comprises two levels (ObsErrorCovariance and ObsErrorBase) because we want run time polymorphism.
The observation and observation bias error covariance matrix has block diagonal structure and is defined as:
\[ \bar{R} \bar{y} = \begin{bmatrix} \tilde{R} && 0 \\ 0 && \tilde{R}_{\beta} \end{bmatrix} \begin{bmatrix} \tilde{y} \\ \tilde{b} \end{bmatrix} \]
where \(\tilde{R} \) is the observation error covariance matrix and \(\tilde{R}_{\beta} \) is the observation bias error covariance matrix. \(\bar{y} \) is implemented by ControlObsVector, which holds two ObsVector components corresponding to observations \(\tilde{y} \) and biases \(\tilde{b} \).
If VarQC is active, it is applied in a square root symmetric form:
\[ \bar{W}^{1/2} \bar{R} \bar{W}^{1/2} \bar{y} = \begin{bmatrix} \tilde{W}^{1/2} && 0 \\ 0 && I \end{bmatrix} \begin{bmatrix} \tilde{R} && 0 \\ 0 && \tilde{R}_{\beta} \end{bmatrix} \begin{bmatrix} \tilde{W}^{1/2} && 0 \\ 0 && I \end{bmatrix} \begin{bmatrix} \tilde{y} \\ \tilde{b} \end{bmatrix} \]
where \(\tilde{W}^{1/2} \) is a diagonal matrix of VarQC weights.
ObsErrors class holds a vector of ObsErrorCovariance objects. Refere to the documentation of CostJo to understand the structure.
Definition at line 96 of file ObsErrorCovariance.h.
Member Typedef Documentation
ControlObsVector_
template<typename MODEL > using oops::ObsErrorCovariance< MODEL >::ControlObsVector_ = ControlObsVector<MODEL> private
Definition at line 103 of file ObsErrorCovariance.h.
ObsErrorBase_
template<typename MODEL > using oops::ObsErrorCovariance< MODEL >::ObsErrorBase_ = ObsErrorBase<MODEL> private
Definition at line 100 of file ObsErrorCovariance.h.
ObsSpace_
template<typename MODEL > using oops::ObsErrorCovariance< MODEL >::ObsSpace_ = ObservationSpace<MODEL> private
Definition at line 101 of file ObsErrorCovariance.h.
ObsVector_
template<typename MODEL > using oops::ObsErrorCovariance< MODEL >::ObsVector_ = ObsVector<MODEL> private
Definition at line 102 of file ObsErrorCovariance.h.
Constructor & Destructor Documentation
ObsErrorCovariance()
template<typename MODEL > oops::ObsErrorCovariance< MODEL >::ObsErrorCovariance (const ObsSpace_ & obsdb, const eckit::Configuration & conf)
Constructor.
Definition at line 146 of file ObsErrorCovariance.h.
     : lvarqc_(false), covar_(), biascovar_() {
   Log::trace() << "ObsErrorCovariance<MODEL>::ObsErrorCovariance starting"
                << std::endl;
   util::Timer timer(classname(), "ObsErrorCovariance");
   eckit::LocalConfiguration obscovarconf(conf, "ObsErrorCovariance");
   covar_.reset(ObsErrorFactory<MODEL>::create(obsdb, obscovarconf));
   if (conf.has("BiasErrorCovariance")) {
     eckit::LocalConfiguration biascovarconf(conf, "BiasErrorCovariance");
     biascovar_.reset(ObsErrorFactory<MODEL>::create(obsdb, biascovarconf));
   }
   Log::trace() << "ObsErrorCovariance<MODEL>::ObsErrorCovariance done"
                << std::endl;
 }
References oops::ObsErrorCovariance< MODEL >::biascovar_, oops::ObsErrorCovariance< MODEL >::classname(), and oops::ObsErrorCovariance< MODEL >::covar_.
~ObsErrorCovariance()
template<typename MODEL > oops::ObsErrorCovariance< MODEL >::~ObsErrorCovariance
Destructor.
Definition at line 165 of file ObsErrorCovariance.h.
{
   Log::trace() << "ObsErrorCovariance<MODEL>::~ObsErrorCovariance starting"
                << std::endl;
   util::Timer timer(classname(), "~ObsErrorCovariance");
   covar_.reset();
   biascovar_.reset();
   Log::trace() << "ObsErrorCovariance<MODEL>::~ObsErrorCovariance done"
                << std::endl;
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::ObsErrorCovariance< MODEL >::classname () inline static
Definition at line 106 of file ObsErrorCovariance.h.
 { return "oops::ObsErrorCovariance"; }
Referenced by oops::ObsErrorCovariance< MODEL >::ObsErrorCovariance().
getRMSE()
template<typename MODEL > double oops::ObsErrorCovariance< MODEL >::getRMSE
Get mean error for Jo table.
Definition at line 290 of file ObsErrorCovariance.h.
{
   Log::trace() << "ObsErrorCovariance<MODEL>::getRMSE starting" << std::endl;
   util::Timer timer(classname(), "getRMSE");
   double zz = covar_->getRMSE();
   Log::trace() << "ObsErrorCovariance<MODEL>::getRMSE done" << std::endl;
   return zz;
 }
inverseMultiply()
template<typename MODEL > ControlObsVector< MODEL > * oops::ObsErrorCovariance< MODEL >::inverseMultiply (const ControlObsVector_ & dy) const
Multiply a Departure by \(\bar{R}^{-1}\).
Definition at line 259 of file ObsErrorCovariance.h.
{
   Log::trace() << "ObsErrorCovariance<MODEL>::inverseMultiply starting"
                << std::endl;
   util::Timer timer(classname(), "inverseMultiply");
   ControlObsVector<MODEL> *wrinvwdy = nullptr;
   if (lvarqc_) {
     std::unique_ptr<ControlObsVector<MODEL> > wdy(this->multiplyWghtSqrt_(dy));
     std::unique_ptr<ControlObsVector<MODEL> > rinvwdy(this->inverseMultiply_(*wdy));
     wrinvwdy = this->multiplyWghtSqrt_(*rinvwdy);
   } else {
     wrinvwdy = this->inverseMultiply_(dy);
   }
   Log::trace() << "ObsErrorCovariance<MODEL>::inverseMultiply done"
                << std::endl;
   return wrinvwdy;
 }
inverseMultiply_()
template<typename MODEL > ControlObsVector< MODEL > * oops::ObsErrorCovariance< MODEL >::inverseMultiply_ (const ControlObsVector_ & dy) const private
\(\bar{y}_1 = \bar{R}^{-1} \bar{y}_2 \)
Definition at line 239 of file ObsErrorCovariance.h.
{
   Log::trace() << "ObsErrorCovariance<MODEL>::inverseMultiply_ starting"
                << std::endl;
   util::Timer timer(classname(), "inverseMultiply_");
   ObsVector_ *dyobs =
       new ObsVector_(covar_->inverseMultiply(dy.obsvector().obsvector()));
   ObsVector_ *dybias = nullptr;
   if (biascovar_)
     dybias = new ObsVector_(
         biascovar_->inverseMultiply(dy.biasvector().obsvector()));
   ControlObsVector_ *dyctl = new ControlObsVector_(dyobs, dybias);
   Log::trace() << "ObsErrorCovariance<MODEL>::inverseMultiply_ done"
                << std::endl;
   return dyctl;
 }
References oops::ControlObsVector< MODEL >::biasvector(), oops::ControlObsVector< MODEL >::obsvector(), and oops::ObsVector< MODEL >::obsvector().
linearize()
template<typename MODEL > void oops::ObsErrorCovariance< MODEL >::linearize (const ControlObsVector_ & yy)
Setup the covariance matrix.
Definition at line 178 of file ObsErrorCovariance.h.
{
   Log::trace() << "ObsErrorCovariance<MODEL>::linearize starting" << std::endl;
   util::Timer timer(classname(), "linearize");
   lvarqc_ = false;
   covar_->linearize(yy.obsvector().obsvector());
   if (biascovar_) biascovar_->linearize(yy.biasvector().obsvector());
   Log::trace() << "ObsErrorCovariance<MODEL>::linearize done" << std::endl;
 }
References oops::ControlObsVector< MODEL >::biasvector(), oops::ControlObsVector< MODEL >::obsvector(), and oops::ObsVector< MODEL >::obsvector().
multiply()
template<typename MODEL > ControlObsVector< MODEL > * oops::ObsErrorCovariance< MODEL >::multiply (const ControlObsVector_ & dy) const
Multiply a Departure by \(\bar{R}\).
Definition at line 202 of file ObsErrorCovariance.h.
{
   Log::trace() << "ObsErrorCovariance<MODEL>::multiply starting" << std::endl;
   util::Timer timer(classname(), "multiply");
   ObsVector_ *dyobs =
       new ObsVector_(covar_->multiply(dy.obsvector().obsvector()));
   ObsVector_ *dybias = nullptr;
   if (biascovar_)
     dybias = new ObsVector_(biascovar_->multiply(dy.biasvector().obsvector()));
   ControlObsVector_ *dyctl = new ControlObsVector_(dyobs, dybias);
   Log::trace() << "ObsErrorCovariance<MODEL>::multiply done" << std::endl;
   return dyctl;
 }
References oops::ControlObsVector< MODEL >::biasvector(), oops::ControlObsVector< MODEL >::obsvector(), and oops::ObsVector< MODEL >::obsvector().
multiplyWghtSqrt_()
template<typename MODEL > ControlObsVector< MODEL > * oops::ObsErrorCovariance< MODEL >::multiplyWghtSqrt_ (const ControlObsVector_ & dy) const private
\(\bar{y}_1 = \bar{W}^{1/2} \bar{y}_2 \)
Definition at line 219 of file ObsErrorCovariance.h.
{
   Log::trace() << "ObsErrorCovariance<MODEL>::multiplyWghtSqrt_ starting"
                << std::endl;
   util::Timer timer(classname(), "multiplyWghtSqrt_");
   ObsVector_ *dyobs =
       new ObsVector_(covar_->multiplyWghtSqrt(dy.obsvector().obsvector()));
   ObsVector_ *dybias = nullptr;
   if (biascovar_)
     dybias =
         new ObsVector_(covar_->multiplyWghtSqrt(dy.biasvector().obsvector()));
   ControlObsVector_ *dyctl = new ControlObsVector_(dyobs, dybias);
   Log::trace() << "ObsErrorCovariance<MODEL>::multiplyWghtSqrt_ done"
                << std::endl;
   return dyctl;
 }
References oops::ControlObsVector< MODEL >::biasvector(), oops::ControlObsVector< MODEL >::obsvector(), and oops::ObsVector< MODEL >::obsvector().
print()
template<typename MODEL > void oops::ObsErrorCovariance< MODEL >::print (std::ostream & os) const private
Definition at line 301 of file ObsErrorCovariance.h.
{
   Log::trace() << "ObsErrorCovariance<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   os << *covar_;
   if (biascovar_) os << *biascovar_;
   Log::trace() << "ObsErrorCovariance<MODEL>::print done" << std::endl;
 }
randomize()
template<typename MODEL > void oops::ObsErrorCovariance< MODEL >::randomize (ControlObsVector_ & dy) const
Generate random perturbation.
Definition at line 280 of file ObsErrorCovariance.h.
{
   Log::trace() << "ObsErrorCovariance<MODEL>::randomize starting" << std::endl;
   util::Timer timer(classname(), "randomize");
   covar_->randomize(dy.obsvector().obsvector());
   Log::trace() << "ObsErrorCovariance<MODEL>::randomize done" << std::endl;
 }
References oops::ControlObsVector< MODEL >::obsvector(), and oops::ObsVector< MODEL >::obsvector().
setupWeights()
template<typename MODEL > void oops::ObsErrorCovariance< MODEL >::setupWeights (const ControlObsVector_ & yy)
Setup the VarQC weights.
Definition at line 190 of file ObsErrorCovariance.h.
{
   Log::trace() << "ObsErrorCovariance<MODEL>::setupWeights starting"
                << std::endl;
   util::Timer timer(classname(), "setupWeights");
   covar_->setupWeights(yy.obsvector().obsvector());
   lvarqc_ = true;
   Log::trace() << "ObsErrorCovariance<MODEL>::setupWeights done" << std::endl;
 }
References oops::ControlObsVector< MODEL >::obsvector(), and oops::ObsVector< MODEL >::obsvector().
Member Data Documentation
biascovar_
template<typename MODEL > std::unique_ptr<ObsErrorBase_> oops::ObsErrorCovariance< MODEL >::biascovar_ private
Pointer to bias error covariance.
Definition at line 140 of file ObsErrorCovariance.h.
Referenced by oops::ObsErrorCovariance< MODEL >::ObsErrorCovariance().
covar_
template<typename MODEL > std::unique_ptr<ObsErrorBase_> oops::ObsErrorCovariance< MODEL >::covar_ private
Pointer to observation error covariance.
Definition at line 138 of file ObsErrorCovariance.h.
Referenced by oops::ObsErrorCovariance< MODEL >::ObsErrorCovariance().
lvarqc_
template<typename MODEL > bool oops::ObsErrorCovariance< MODEL >::lvarqc_ private
Controls VarQC.
Definition at line 136 of file ObsErrorCovariance.h.
The documentation for this class was generated from the following file:
src/oops/interface/ObsErrorCovariance.h