OOPS Documentation: oops::RPCGMinimizer< MODEL > Class Template Reference
oops::RPCGMinimizer< MODEL > Class Template Reference
RPCG Minimizer.
#include <RPCGMinimizer.h>
Public Member Functions
const std::string classname () const override
RPCGMinimizer (const eckit::Configuration &, const CostFct_ &J)
~RPCGMinimizer ()
Public Member Functions inherited from oops::DualMinimizer< MODEL >
DualMinimizer (const CostFct_ &J)
~DualMinimizer ()
void checkpoint (eckit::LocalConfiguration &) const
Checkpoint the minimizer (virtual method)
void restart (const eckit::Configuration &)
Restart the minimizer (virtual method)
void warmStart (const eckit::Configuration &)
Warm start the minimizer (virtual method)
Public Member Functions inherited from oops::Minimizer< MODEL >
Minimizer (const CostFct_ &J)
Construct a minimizer.
virtual ~Minimizer ()
Destroy a minimizer.
ControlIncrement< MODEL > * minimize (const eckit::Configuration &)
Orchestrate the minimization of a quadratic cost function.
Private Types
using CostFct_ = CostFunction< MODEL >
using Dual_ = DualVector< MODEL >
using HBHt_ = HBHtMatrix< MODEL >
using Rinv_ = RinvMatrix< MODEL >
Private Member Functions
double solve (Dual_ &, double &, Dual_ &, const HBHt_ &, const Rinv_ &, const int &, const double &, Dual_ &, const double &) override
Detailed Description
template<typename MODEL>
class oops::RPCGMinimizer< MODEL >
RPCG Minimizer.
Augmented Restricted Preconditioned Conjugate Gradients.
This solver is based on the algorithm proposed in Gratton and Tshimanga, QJRMS, 135: 1573-1585 (2009). It performs minimization in observation space.
It solves the linear system \((I + R^{-1}HBH^T) lambda = H^T R^{-1}d \) with \(HBH^T \) inner-product in the augmented observation space.
Note that the traditional \(B\)-preconditioning in model space corresponds to \(I\) for this algorithm.
A second-level preconditioner, \(G \), must be symmetric and positive definite with respect to \(HBH^T \) inner-product. Possible preconditioning is detailed in S. Gurol, PhD Manuscript, 2013.
On entry:
vv = starting point, \(v_0 \).
vvp = starting point augmented part, \(vp_0 \)
rr = right hand side.
dy = \(H (xb - xk) \)
sigma = \((xb - xk)^T B^{-1} (xb - xk)\).
HBHt = \(HBH^T \).
Rinv = \(R^{-1} \).
G = preconditioner \(G \).
Gt = preconditioner transpose \(G^T \).
On exit, vv and vvp will contain the solution \(lambda = [vv; vp] \)
The return value is the achieved reduction in preconditioned residual norm.
Iteration will stop if the maximum iteration limit "maxiter" is reached or if the preconditioned residual norm reduces by a factor of "tolerance".
Definition at line 69 of file RPCGMinimizer.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::RPCGMinimizer< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 70 of file RPCGMinimizer.h.
Dual_
template<typename MODEL > using oops::RPCGMinimizer< MODEL >::Dual_ = DualVector<MODEL> private
Definition at line 71 of file RPCGMinimizer.h.
HBHt_
template<typename MODEL > using oops::RPCGMinimizer< MODEL >::HBHt_ = HBHtMatrix<MODEL> private
Definition at line 72 of file RPCGMinimizer.h.
Rinv_
template<typename MODEL > using oops::RPCGMinimizer< MODEL >::Rinv_ = RinvMatrix<MODEL> private
Definition at line 73 of file RPCGMinimizer.h.
Constructor & Destructor Documentation
RPCGMinimizer()
template<typename MODEL > oops::RPCGMinimizer< MODEL >::RPCGMinimizer (const eckit::Configuration & , const CostFct_ & J) inline
Definition at line 77 of file RPCGMinimizer.h.
       : DualMinimizer<MODEL>(J) {}
~RPCGMinimizer()
template<typename MODEL > oops::RPCGMinimizer< MODEL >::~RPCGMinimizer () inline
Definition at line 79 of file RPCGMinimizer.h.
 {}
Member Function Documentation
classname()
template<typename MODEL > const std::string oops::RPCGMinimizer< MODEL >::classname () const inline override virtual
Implements oops::DualMinimizer< MODEL >.
Definition at line 76 of file RPCGMinimizer.h.
 { return "RPCGMinimizer"; }
solve()
template<typename MODEL > double oops::RPCGMinimizer< MODEL >::solve (Dual_ & vv, double & vvp, Dual_ & rr, const HBHt_ & HBHt, const Rinv_ & Rinv, const int & maxiter, const double & tolerance, Dual_ & dy, const double & sigma) override private virtual
Implements oops::DualMinimizer< MODEL >.
Definition at line 89 of file RPCGMinimizer.h.
{
   IdentityMatrix<Dual_> precond;
   IdentityMatrix<Dual_> precondt;
   Dual_ zz(vv);
   Dual_ ww(vv);
   Dual_ pp(vv);
   Dual_ tt(vv);
   Dual_ ll(vv);
   Dual_ qq(vv);
   Dual_ w(vv);
   Dual_ v(vv);
   // augmented part of the vectors
   double rrp = 1.0;
   double llp;
   double wwp;
   double zzp;
   double ppp = 0.0;
   double ttp = 0.0;
   double qqp;
   double vp = 1.0;
   double wp;
   std::vector<Dual_> vVEC;  // required for re-orthogonalization
   std::vector<Dual_> wVEC;  // required for re-orthogonalization
   std::vector<double> vpVEC;
   std::vector<double> wpVEC;
   // llaug = HBHtaug rraug
   HBHt.multiply(rr, ll);
   ll.axpy(rrp, dy);
   llp = dot_product(dy, rr) + sigma * rrp;
   // wwaug = Gtaug llaug
   precondt.multiply(ll, ww);  // UPDATE WHEN G IS NOT IDENTITY
   wwp = llp;
   // zzaug = Gaug  rraug
   precond.multiply(rr, zz);  // UPDATE WHEN G IS NOT IDENTITY
   zzp = rrp;
   double dotwr = dot_product(rr, ww) + rrp * wwp;
   double normReduction = 1.0;
   double dotw0r0 = dotwr;
   double dotwr_old = 0.0;
   v = rr;
   v *= 1 / sqrt(dotwr);
   vp = rrp;
   vp *= 1 / sqrt(dotwr);
   w = ww;
   w *= 1 / sqrt(dotwr);
   wp = wwp;
   wp *= 1 / sqrt(dotwr);
   vVEC.clear();
   vpVEC.clear();
   wVEC.clear();
   wpVEC.clear();
   vVEC.push_back(v);
   vpVEC.push_back(vp);
   wVEC.push_back(w);
   wpVEC.push_back(wp);
   Log::info() << std::endl;
   for (int jiter = 0; jiter < maxiter; ++jiter) {
     Log::info() << "RPCG Starting Iteration " << jiter + 1 << std::endl;
     if (jiter > 0) {
       double beta = dotwr / dotwr_old;
       Log::debug() << "RPCG beta = " << beta << std::endl;
       pp *= beta;
       ppp *= beta;
       tt *= beta;
       ttp *= beta;
     }
     pp += zz;
     ppp += zzp;  // ppaug = zzaug + beta*ppaug
     tt += ww;
     ttp += wwp;  // ttaug = wwaug + beta*ttaug
     // (RinvHBHt + I) pp
     Rinv.multiply(tt, qq);
     qq += pp;
     qqp = ppp;  // qqaug = ppaug + Rinv_aug ttaug
     double alpha = dotwr / (dot_product(qq, tt) + qqp * ttp);
     Log::debug() << "RPCG alpha = " << alpha << std::endl;
     vv.axpy(alpha, pp);
     vvp = vvp + alpha * ppp;  // vvaug = vvaug + alpha*ppaug
     rr.axpy(-alpha, qq);
     rrp = rrp - alpha * qqp;  // rraug = rraug - alpha*qqaug
     // Re-orthogonalization
     for (int iiter = 0; iiter < jiter; ++iiter) {
       double proj = dot_product(rr, wVEC[iiter]) + rrp * wpVEC[iiter];
       rr.axpy(-proj, vVEC[iiter]);
       rrp -= proj * vpVEC[iiter];
     }
     // llaug = HBHt_aug rraug
     HBHt.multiply(rr, ll);
     ll.axpy(rrp, dy);
     llp = dot_product(dy, rr) + sigma * rrp;
     // wwaug = Gt_aug llaug
     precondt.multiply(ll, ww);  // UPDATE WHEN G IS NOT IDENTITY
     wwp = llp;
     // zzaug = Gaug  rraug
     precond.multiply(rr, zz);  // UPDATE WHEN G IS NOT IDENTITY
     zzp = rrp;
     dotwr_old = dotwr;
     dotwr = dot_product(ww, rr) + rrp * wwp;
     v = rr;
     v *= 1 / sqrt(dotwr);
     vp = rrp;
     vp *= 1 / sqrt(dotwr);
     w = ww;
     w *= 1 / sqrt(dotwr);
     wp = wwp;
     wp *= 1 / sqrt(dotwr);
     vVEC.push_back(v);
     vpVEC.push_back(vp);
     wVEC.push_back(w);
     wpVEC.push_back(wp);
     normReduction = sqrt(dotwr / dotw0r0);
     Log::info() << "RPCG end of iteration " << jiter + 1
                 << ". Norm reduction= " << util::full_precision(normReduction)
                 << std::endl
                 << std::endl;
     if (normReduction < tolerance) {
       Log::info() << "RPCG: Achieved required reduction in residual norm."
                   << std::endl;
       break;
     }
   }
   return normReduction;
 }
References oops::DualVector< MODEL >::axpy(), dot_product(), util::full_precision(), oops::IdentityMatrix< VECTOR >::multiply(), oops::RinvMatrix< MODEL >::multiply(), and oops::HBHtMatrix< MODEL >::multiply().
The documentation for this class was generated from the following file:
src/oops/assimilation/RPCGMinimizer.h