OOPS Documentation: oops::PostBaseTL< INCR > Class Template Reference
oops::PostBaseTL< INCR > Class Template Reference abstract
Handles post-processing of model fields related to cost function.
#include <PostBaseTL.h>
Public Member Functions
PostBaseTL ()
Constructors.
PostBaseTL (const util::DateTime &start, const util::DateTime &finish, const util::Duration &freq=util::Duration(0))
virtual ~PostBaseTL ()
Destructor.
void initializeTL (const INCR &dx, const util::DateTime &end, const util::Duration &step)
Wraps doInitializerTL method; doProcessingTL is is called if requested.
void processTL (const INCR &dx)
Wraps doProcessing method; doProcessing is is called when requested.
void finalizeTL (const INCR &dx)
Wraps doFinalizeTL method.
virtual GeneralizedDepartures * releaseOutputFromTL ()=0
Return TL dual space output.
Private Member Functions
virtual void doInitializeTL (const INCR &, const util::DateTime &, const util::Duration &)=0
Actual processing.
virtual void doProcessingTL (const INCR &)=0
Actual initialization.
virtual void doFinalizeTL (const INCR &)=0
Actual finalization.
Private Attributes
PostTimer timer_
Detailed Description
template<typename INCR>
class oops::PostBaseTL< INCR >
Handles post-processing of model fields related to cost function.
PostBaseTL is the base class for all cost function processors, it is mostly used so that PostProcessorTL can hold a vector of such processors.
PostProcessorTL is typically attached to LinearModel::forecastTL method.
By default processing is performed on every call.
PostBaseTL is templated on INCR; INCR would typically be Increment.
Post-processing is organized in three stages/methods: initializeTL (called prior to time-stepping), processTL (called during forecastTL at each time step) and finalizeTL (called once the time-stepping is finished).
Methods initializeTL, processTL and finalizeTL wrap around virtual methods (implemented by PostBaseTL children classes) doInitializeTL, doProcessingTL and doFinalizeTL.
PostBaseTL class contains a PostTimer object. PostTimer class controls the frequency of post-processing.
PostBaseTL is the base class of the following classes (refer to their documentation for more information):
ObserverTL
WeightedDiffTL
JqTermTL
Definition at line 63 of file PostBaseTL.h.
Constructor & Destructor Documentation
PostBaseTL() [1/2]
template<typename INCR > oops::PostBaseTL< INCR >::PostBaseTL () inline
Constructors.
Definition at line 66 of file PostBaseTL.h.
 : timer_() {}
PostBaseTL() [2/2]
template<typename INCR > oops::PostBaseTL< INCR >::PostBaseTL (const util::DateTime & start, const util::DateTime & finish, const util::Duration & freq = util::Duration(0)) inline
Definition at line 67 of file PostBaseTL.h.
       : timer_(start, finish, freq) {}
~PostBaseTL()
template<typename INCR > virtual oops::PostBaseTL< INCR >::~PostBaseTL () inline virtual
Destructor.
Definition at line 71 of file PostBaseTL.h.
 {}
Member Function Documentation
doFinalizeTL()
template<typename INCR > virtual void oops::PostBaseTL< INCR >::doFinalizeTL (const INCR &) private pure virtual
Actual finalization.
Implemented in oops::ObserverTL< MODEL, INCR >, oops::WeightedDiffTL< MODEL, INCR >, and oops::ObserverEnVarTL< MODEL, INCR >.
Referenced by oops::PostBaseTL< INCR >::finalizeTL().
doInitializeTL()
template<typename INCR > virtual void oops::PostBaseTL< INCR >::doInitializeTL (const INCR & , const util::DateTime & , const util::Duration &) private pure virtual
Actual processing.
Implemented in oops::ObserverTL< MODEL, INCR >, oops::WeightedDiffTL< MODEL, INCR >, and oops::ObserverEnVarTL< MODEL, INCR >.
Referenced by oops::PostBaseTL< INCR >::initializeTL().
doProcessingTL()
template<typename INCR > virtual void oops::PostBaseTL< INCR >::doProcessingTL (const INCR &) private pure virtual
Actual initialization.
Implemented in oops::ObserverTL< MODEL, INCR >, oops::WeightedDiffTL< MODEL, INCR >, and oops::ObserverEnVarTL< MODEL, INCR >.
Referenced by oops::PostBaseTL< INCR >::initializeTL(), and oops::PostBaseTL< INCR >::processTL().
finalizeTL()
template<typename INCR > void oops::PostBaseTL< INCR >::finalizeTL (const INCR & dx) inline
Wraps doFinalizeTL method.
Definition at line 87 of file PostBaseTL.h.
 { this->doFinalizeTL(dx); }
References oops::PostBaseTL< INCR >::doFinalizeTL().
initializeTL()
template<typename INCR > void oops::PostBaseTL< INCR >::initializeTL (const INCR & dx, const util::DateTime & end, const util::Duration & step) inline
Wraps doInitializerTL method; doProcessingTL is is called if requested.
Definition at line 74 of file PostBaseTL.h.
{
     timer_.initialize(dx.validTime(), end, step);
     this->doInitializeTL(dx, end, step);
     if (timer_.itIsTime(dx.validTime())) this->doProcessingTL(dx);
   }
References oops::PostBaseTL< INCR >::doInitializeTL(), oops::PostBaseTL< INCR >::doProcessingTL(), oops::PostTimer::initialize(), oops::PostTimer::itIsTime(), and oops::PostBaseTL< INCR >::timer_.
processTL()
template<typename INCR > void oops::PostBaseTL< INCR >::processTL (const INCR & dx) inline
Wraps doProcessing method; doProcessing is is called when requested.
Definition at line 82 of file PostBaseTL.h.
{
     if (timer_.itIsTime(dx.validTime())) this->doProcessingTL(dx);
   }
References oops::PostBaseTL< INCR >::doProcessingTL(), oops::PostTimer::itIsTime(), and oops::PostBaseTL< INCR >::timer_.
releaseOutputFromTL()
template<typename INCR > virtual GeneralizedDepartures* oops::PostBaseTL< INCR >::releaseOutputFromTL () pure virtual
Return TL dual space output.
Implemented in oops::ObserverTL< MODEL, INCR >, oops::WeightedDiffTL< MODEL, INCR >, and oops::ObserverEnVarTL< MODEL, INCR >.
Member Data Documentation
timer_
template<typename INCR > PostTimer oops::PostBaseTL< INCR >::timer_ private
Definition at line 101 of file PostBaseTL.h.
Referenced by oops::PostBaseTL< INCR >::initializeTL(), and oops::PostBaseTL< INCR >::processTL().
The documentation for this class was generated from the following file:
src/oops/base/PostBaseTL.h