OOPS Documentation: oops::DualVector< MODEL > Class Template Reference
oops::DualVector< MODEL > Class Template Reference
Container of dual space vectors for all terms of the cost function.
#include <DualVector.h>
Public Member Functions
DualVector ()
DualVector (const DualVector &)
~DualVector ()
void dx (CtrlInc_ *dx)
const CtrlInc_ & dx () const
CtrlInc_ & dx ()
void append (GeneralizedDepartures *)
std::shared_ptr< const GeneralizedDepartures > getv (const unsigned) const
DualVector & operator= (const DualVector &)
DualVector & operator+= (const DualVector &)
DualVector & operator-= (const DualVector &)
DualVector & operator*= (const double)
void zero ()
void axpy (const double, const DualVector &)
double dot_product_with (const DualVector &) const
void clear ()
Private Types
using Increment_ = Increment< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using Departures_ = Departures< MODEL >
Private Member Functions
bool compatible (const DualVector &other) const
Private Attributes
std::unique_ptr< CtrlInc_ > dxjb_
std::vector< std::shared_ptr< Departures_ > > dxjo_
std::vector< std::shared_ptr< Increment_ > > dxjc_
std::vector< unsigned > ijo_
std::vector< unsigned > ijc_
unsigned size_
Detailed Description
template<typename MODEL>
class oops::DualVector< MODEL >
Container of dual space vectors for all terms of the cost function.
Contains dual space vectors for all terms of the cost function, that is Departures for Jo, an Increment_ for Jc, a ControlIncrement for Jb and Jq.
Definition at line 34 of file DualVector.h.
Member Typedef Documentation
CtrlInc_
template<typename MODEL > using oops::DualVector< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 36 of file DualVector.h.
Departures_
template<typename MODEL > using oops::DualVector< MODEL >::Departures_ = Departures<MODEL> private
Definition at line 37 of file DualVector.h.
Increment_
template<typename MODEL > using oops::DualVector< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 35 of file DualVector.h.
Constructor & Destructor Documentation
DualVector() [1/2]
template<typename MODEL > oops::DualVector< MODEL >::DualVector () inline
Definition at line 40 of file DualVector.h.
 : dxjb_(), dxjo_(), dxjc_(), ijo_(), ijc_(), size_(0) {}
DualVector() [2/2]
template<typename MODEL > oops::DualVector< MODEL >::DualVector (const DualVector< MODEL > & other)
Definition at line 79 of file DualVector.h.
     : dxjb_(),
       dxjo_(),
       dxjc_(),
       ijo_(other.ijo_),
       ijc_(other.ijc_),
       size_(other.size_) {
   if (other.dxjb_ != 0) {
     dxjb_.reset(new CtrlInc_(*other.dxjb_));
   }
   for (unsigned jj = 0; jj < other.dxjo_.size(); ++jj) {
     std::shared_ptr<Departures_> pd(new Departures_(*other.dxjo_[jj]));
     dxjo_.push_back(pd);
   }
   for (unsigned jj = 0; jj < other.dxjc_.size(); ++jj) {
     std::shared_ptr<Increment_> pi(new Increment_(*other.dxjc_[jj]));
     dxjc_.push_back(pi);
   }
 }
References oops::DualVector< MODEL >::dxjb_, oops::DualVector< MODEL >::dxjc_, and oops::DualVector< MODEL >::dxjo_.
~DualVector()
template<typename MODEL > oops::DualVector< MODEL >::~DualVector () inline
Definition at line 42 of file DualVector.h.
 {}
Member Function Documentation
append()
template<typename MODEL > void oops::DualVector< MODEL >::append (GeneralizedDepartures * pv)
Definition at line 110 of file DualVector.h.
{
   // Since there is no duck-typing in C++, we do it manually.
   Increment_ *pi = dynamic_cast<Increment_ *>(pv);
   if (pi != 0) {
     std::shared_ptr<Increment_> si(pi);
     dxjc_.push_back(si);
     ijc_.push_back(size_);
   }
   Departures_ *pd = dynamic_cast<Departures_ *>(pv);
   if (pd != 0) {
     std::shared_ptr<Departures_> sd(pd);
     dxjo_.push_back(sd);
     ijo_.push_back(size_);
   }
   ASSERT(pi != 0 || pd != 0);
   ++size_;
 }
Referenced by oops::HtRinvHdxFG< MODEL >::compute(), oops::UtHtRinvHUMatrix< MODEL >::computeDiagnostics(), oops::CostFunction< MODEL >::computeGradientFG(), oops::DualMinimizer< MODEL >::doMinimize(), oops::SaddlePointMinimizer< MODEL >::doMinimize(), oops::RinvMatrix< MODEL >::multiply(), oops::HMatrix< MODEL >::multiply(), oops::SaddlePointPrecondMatrix< MODEL >::multiply(), oops::HBHtMatrix< MODEL >::multiply(), oops::SaddlePointMatrix< MODEL >::multiply(), oops::HessianMatrix< MODEL >::multiply(), oops::HtRinvHMatrix< MODEL >::multiply(), oops::UtHtRinvHUMatrix< MODEL >::multiply(), and oops::SaddlePointLMPMatrix< MODEL >::Pinitmultiply().
axpy()
template<typename MODEL > void oops::DualVector< MODEL >::axpy (const double zz, const DualVector< MODEL > & rhs)
Definition at line 216 of file DualVector.h.
{
   ASSERT(this->compatible(rhs));
   if (dxjb_ != 0) {
     dxjb_->axpy(zz, *rhs.dxjb_);
   }
   for (unsigned jj = 0; jj < dxjo_.size(); ++jj) {
     dxjo_[jj]->axpy(zz, *rhs.dxjo_[jj]);
   }
   for (unsigned jj = 0; jj < dxjc_.size(); ++jj) {
     dxjc_[jj]->axpy(zz, *rhs.dxjc_[jj]);
   }
 }
References oops::DualVector< MODEL >::dxjb_, oops::DualVector< MODEL >::dxjc_, and oops::DualVector< MODEL >::dxjo_.
Referenced by oops::SaddlePointLMPMatrix< MODEL >::Rmultiply(), oops::RPCGMinimizer< MODEL >::solve(), and oops::RPLanczosMinimizer< MODEL >::solve().
clear()
template<typename MODEL > void oops::DualVector< MODEL >::clear
Definition at line 100 of file DualVector.h.
{
   dxjb_.reset();
   dxjo_.clear();
   dxjc_.clear();
   ijo_.clear();
   ijc_.clear();
   size_ = 0;
 }
Referenced by oops::RinvMatrix< MODEL >::multiply(), oops::HMatrix< MODEL >::multiply(), oops::SaddlePointPrecondMatrix< MODEL >::multiply(), oops::HBHtMatrix< MODEL >::multiply(), and oops::SaddlePointMatrix< MODEL >::multiply().
compatible()
template<typename MODEL > bool oops::DualVector< MODEL >::compatible (const DualVector< MODEL > & other) const private
Definition at line 246 of file DualVector.h.
{
   bool lcheck = (dxjb_ == 0) == (other.dxjb_ == 0) &&
                 (dxjo_.size() == other.dxjo_.size()) &&
                 (dxjc_.size() == other.dxjc_.size());
   return lcheck;
 }
References oops::DualVector< MODEL >::dxjb_, oops::DualVector< MODEL >::dxjc_, and oops::DualVector< MODEL >::dxjo_.
dot_product_with()
template<typename MODEL > double oops::DualVector< MODEL >::dot_product_with (const DualVector< MODEL > & x2) const
Definition at line 230 of file DualVector.h.
{
   ASSERT(this->compatible(x2));
   double zz = 0.0;
   if (dxjb_ != 0) {
     zz += dot_product(*dxjb_, *x2.dxjb_);
   }
   for (unsigned jj = 0; jj < dxjo_.size(); ++jj) {
     zz += dot_product(*dxjo_[jj], *x2.dxjo_[jj]);
   }
   for (unsigned jj = 0; jj < dxjc_.size(); ++jj) {
     zz += dot_product(*dxjc_[jj], *x2.dxjc_[jj]);
   }
   return zz;
 }
References dot_product(), oops::DualVector< MODEL >::dxjb_, oops::DualVector< MODEL >::dxjc_, and oops::DualVector< MODEL >::dxjo_.
dx() [1/3]
template<typename MODEL > CtrlInc_& oops::DualVector< MODEL >::dx () inline
Definition at line 47 of file DualVector.h.
 { return *dxjb_; }
References oops::DualVector< MODEL >::dxjb_.
dx() [2/3]
template<typename MODEL > const CtrlInc_& oops::DualVector< MODEL >::dx () const inline
Definition at line 46 of file DualVector.h.
 { return *dxjb_; }
References oops::DualVector< MODEL >::dxjb_.
Referenced by oops::DualVector< MODEL >::dx().
dx() [3/3]
template<typename MODEL > void oops::DualVector< MODEL >::dx (CtrlInc_ * dx) inline
Definition at line 45 of file DualVector.h.
 { dxjb_.reset(dx); }
References oops::DualVector< MODEL >::dx(), and oops::DualVector< MODEL >::dxjb_.
Referenced by oops::SaddlePointMinimizer< MODEL >::doMinimize(), oops::SaddlePointPrecondMatrix< MODEL >::multiply(), oops::SaddlePointMatrix< MODEL >::multiply(), and oops::SaddlePointLMPMatrix< MODEL >::Pinitmultiply().
getv()
template<typename MODEL > std::shared_ptr< const GeneralizedDepartures > oops::DualVector< MODEL >::getv (const unsigned ii) const
Definition at line 129 of file DualVector.h.
{
   ASSERT(ii < size_);
   std::shared_ptr<const GeneralizedDepartures> pv;
   for (unsigned jj = 0; jj < ijo_.size(); ++jj) {
     if (ijo_[jj] == ii) pv = dxjo_[jj];
   }
   for (unsigned jj = 0; jj < ijc_.size(); ++jj) {
     if (ijc_[jj] == ii) pv = dxjc_[jj];
   }
   ASSERT(pv != 0);
   return pv;
 }
Referenced by oops::HtRinvHdxFG< MODEL >::compute(), oops::UtHtRinvHUMatrix< MODEL >::computeDiagnostics(), oops::CostFunction< MODEL >::computeGradientFG(), oops::RinvMatrix< MODEL >::multiply(), oops::HtMatrix< MODEL >::multiply(), oops::SaddlePointPrecondMatrix< MODEL >::multiply(), oops::HBHtMatrix< MODEL >::multiply(), oops::SaddlePointMatrix< MODEL >::multiply(), oops::HessianMatrix< MODEL >::multiply(), oops::HtRinvHMatrix< MODEL >::multiply(), oops::RMatrix< MODEL >::multiplyInv(), and oops::SaddlePointLMPMatrix< MODEL >::Pinitmultiply().
operator*=()
template<typename MODEL > DualVector< MODEL > & oops::DualVector< MODEL >::operator*= (const double zz)
Definition at line 189 of file DualVector.h.
{
   if (dxjb_ != 0) {
     *dxjb_ *= zz;
   }
   for (unsigned jj = 0; jj < dxjo_.size(); ++jj) {
     *dxjo_[jj] *= zz;
   }
   for (unsigned jj = 0; jj < dxjc_.size(); ++jj) {
     *dxjc_[jj] *= zz;
   }
   return *this;
 }
operator+=()
template<typename MODEL > DualVector< MODEL > & oops::DualVector< MODEL >::operator+= (const DualVector< MODEL > & rhs)
Definition at line 159 of file DualVector.h.
{
   ASSERT(this->compatible(rhs));
   if (dxjb_ != 0) {
     *dxjb_ += *rhs.dxjb_;
   }
   for (unsigned jj = 0; jj < dxjo_.size(); ++jj) {
     *dxjo_[jj] += *rhs.dxjo_[jj];
   }
   for (unsigned jj = 0; jj < dxjc_.size(); ++jj) {
     *dxjc_[jj] += *rhs.dxjc_[jj];
   }
   return *this;
 }
References oops::DualVector< MODEL >::dxjb_, oops::DualVector< MODEL >::dxjc_, and oops::DualVector< MODEL >::dxjo_.
operator-=()
template<typename MODEL > DualVector< MODEL > & oops::DualVector< MODEL >::operator-= (const DualVector< MODEL > & rhs)
Definition at line 174 of file DualVector.h.
{
   ASSERT(this->compatible(rhs));
   if (dxjb_ != 0) {
     *dxjb_ -= *rhs.dxjb_;
   }
   for (unsigned jj = 0; jj < dxjo_.size(); ++jj) {
     *dxjo_[jj] -= *rhs.dxjo_[jj];
   }
   for (unsigned jj = 0; jj < dxjc_.size(); ++jj) {
     *dxjc_[jj] -= *rhs.dxjc_[jj];
   }
   return *this;
 }
References oops::DualVector< MODEL >::dxjb_, oops::DualVector< MODEL >::dxjc_, and oops::DualVector< MODEL >::dxjo_.
operator=()
template<typename MODEL > DualVector< MODEL > & oops::DualVector< MODEL >::operator= (const DualVector< MODEL > & rhs)
Definition at line 144 of file DualVector.h.
{
   ASSERT(this->compatible(rhs));
   if (dxjb_ != 0) {
     *dxjb_ = *rhs.dxjb_;
   }
   for (unsigned jj = 0; jj < dxjo_.size(); ++jj) {
     *dxjo_[jj] = *rhs.dxjo_[jj];
   }
   for (unsigned jj = 0; jj < dxjc_.size(); ++jj) {
     *dxjc_[jj] = *rhs.dxjc_[jj];
   }
   return *this;
 }
References oops::DualVector< MODEL >::dxjb_, oops::DualVector< MODEL >::dxjc_, and oops::DualVector< MODEL >::dxjo_.
zero()
template<typename MODEL > void oops::DualVector< MODEL >::zero
Definition at line 203 of file DualVector.h.
{
   if (dxjb_ != 0) {
     dxjb_->zero();
   }
   for (unsigned jj = 0; jj < dxjo_.size(); ++jj) {
     dxjo_[jj]->zero();
   }
   for (unsigned jj = 0; jj < dxjc_.size(); ++jj) {
     dxjc_[jj]->zero();
   }
 }
Referenced by oops::Minimizer< MODEL >::adjObsTest(), oops::UtHtRinvHUMatrix< MODEL >::computeDiagnostics(), oops::SaddlePointLMPMatrix< MODEL >::Pinitmultiply(), oops::SaddlePointLMPMatrix< MODEL >::Rmultiply(), and oops::RPLanczosMinimizer< MODEL >::solve().
Member Data Documentation
dxjb_
template<typename MODEL > std::unique_ptr<CtrlInc_> oops::DualVector< MODEL >::dxjb_ private
Definition at line 68 of file DualVector.h.
Referenced by oops::DualVector< MODEL >::axpy(), oops::DualVector< MODEL >::compatible(), oops::DualVector< MODEL >::dot_product_with(), oops::DualVector< MODEL >::DualVector(), oops::DualVector< MODEL >::dx(), oops::DualVector< MODEL >::operator+=(), oops::DualVector< MODEL >::operator-=(), and oops::DualVector< MODEL >::operator=().
dxjc_
template<typename MODEL > std::vector<std::shared_ptr<Increment_> > oops::DualVector< MODEL >::dxjc_ private
Definition at line 70 of file DualVector.h.
Referenced by oops::DualVector< MODEL >::axpy(), oops::DualVector< MODEL >::compatible(), oops::DualVector< MODEL >::dot_product_with(), oops::DualVector< MODEL >::DualVector(), oops::DualVector< MODEL >::operator+=(), oops::DualVector< MODEL >::operator-=(), and oops::DualVector< MODEL >::operator=().
dxjo_
template<typename MODEL > std::vector<std::shared_ptr<Departures_> > oops::DualVector< MODEL >::dxjo_ private
Definition at line 69 of file DualVector.h.
Referenced by oops::DualVector< MODEL >::axpy(), oops::DualVector< MODEL >::compatible(), oops::DualVector< MODEL >::dot_product_with(), oops::DualVector< MODEL >::DualVector(), oops::DualVector< MODEL >::operator+=(), oops::DualVector< MODEL >::operator-=(), and oops::DualVector< MODEL >::operator=().
ijc_
template<typename MODEL > std::vector<unsigned> oops::DualVector< MODEL >::ijc_ private
Definition at line 72 of file DualVector.h.
ijo_
template<typename MODEL > std::vector<unsigned> oops::DualVector< MODEL >::ijo_ private
Definition at line 71 of file DualVector.h.
size_
template<typename MODEL > unsigned oops::DualVector< MODEL >::size_ private
Definition at line 73 of file DualVector.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/DualVector.h