OOPS Documentation: oops::StaticWithTLModelCovariance4D< MODEL > Class Template Reference
oops::StaticWithTLModelCovariance4D< MODEL > Class Template Reference
Generic ensemble based model space error covariance.
#include <StaticWithTLModelCovariance4D.h>
Public Member Functions
StaticWithTLModelCovariance4D (const Geometry_ &, const Variables_ &, const eckit::Configuration &, const State4D_ &xb)
Constructor, destructor.
~StaticWithTLModelCovariance4D ()
void advectedLinearize (const State4D_ &, const Geometry_ &, const eckit::Configuration &)
void advectedMultiply (const Increment4D_ &, Increment4D_ &) const
void advectedMultiplySqrt (const IncrCtlVec_ &, Increment4D_ &) const
void advectedMultiplySqrtTrans (const Increment4D_ &, IncrCtlVec_ &) const
void advectedInverseMultiply (const Increment4D_ &, Increment4D_ &) const
const ModelSpaceCovarianceBase< MODEL > & covar () const
IncrModCtlVec_ * newIncrModCtlVec () const
IncrEnsCtlVec_ * newIncrEnsCtlVec () const
Public Member Functions inherited from oops::ModelSpaceCovariance4DBase< MODEL >
ModelSpaceCovariance4DBase (const Geometry_ &, const eckit::Configuration &config)
virtual ~ModelSpaceCovariance4DBase ()
void linearize (const State4D_ &xb, const Geometry_ &resol, const eckit::Configuration &config)
virtual void multiply (const Increment4D_ &dxi, Increment4D_ &dxo) const
virtual void multiplySqrt (const IncrCtlVec_ &dvi, Increment4D_ &dxo) const
virtual void multiplySqrtTrans (const Increment4D_ &dxi, IncrCtlVec_ &dvo) const
void inverseMultiply (const Increment4D_ &dxi, Increment4D_ &dxo) const
virtual void randomize (Increment4D_ &) const
Private Types
using Geometry_ = Geometry< MODEL >
using Increment_ = Increment< MODEL >
using State_ = State< MODEL >
using State4D_ = State4D< MODEL >
using Increment4D_ = Increment4D< MODEL >
using IncrCtlVec_ = IncrCtlVec< MODEL >
using IncrEnsCtlVec_ = IncrEnsCtlVec< MODEL >
using IncrModCtlVec_ = IncrModCtlVec< MODEL >
using Variables_ = Variables< MODEL >
using ModelAuxCtrl_ = ModelAuxControl< MODEL >
using ModelAuxIncrement_ = ModelAuxIncrement< MODEL >
using LinearModel_ = LinearModel< MODEL >
using Model_ = Model< MODEL >
using ObserverTL_ = ObserverEnVarTL< MODEL, Increment_ >
using ObserverAD_ = ObserverEnVarAD< MODEL, Increment_ >
using PostProcessorTL_ = PostProcessorTL< Increment_ >
using PostProcessorAD_ = PostProcessorAD< Increment_ >
using TrajectorySaver_ = TrajectorySaverMF< MODEL >
using GenericMatrix_ = GenericMatrix< MODEL >
using MatrixFactory_ = GenericMatrixFactory< MODEL >
Private Attributes
unsigned nsubwin_
const eckit::LocalConfiguration config_
const Variables_ variables_
std::unique_ptr< ModelSpaceCovarianceBase< MODEL > > static_
std::unique_ptr< ModelAuxIncrement_ > modaux_
std::unique_ptr< Model_ > model_
std::vector< std::unique_ptr< LinearModel_ > > tlm_
std::unique_ptr< Geometry_ > low_resol_
std::shared_ptr< GenericMatrix_ > to_low_resol_
Detailed Description
template<typename MODEL>
class oops::StaticWithTLModelCovariance4D< MODEL >
Generic ensemble based model space error covariance.
Definition at line 45 of file StaticWithTLModelCovariance4D.h.
Member Typedef Documentation
GenericMatrix_
template<typename MODEL > using oops::StaticWithTLModelCovariance4D< MODEL >::GenericMatrix_ = GenericMatrix<MODEL> private
Definition at line 64 of file StaticWithTLModelCovariance4D.h.
Geometry_
template<typename MODEL > using oops::StaticWithTLModelCovariance4D< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 46 of file StaticWithTLModelCovariance4D.h.
IncrCtlVec_
template<typename MODEL > using oops::StaticWithTLModelCovariance4D< MODEL >::IncrCtlVec_ = IncrCtlVec<MODEL> private
Definition at line 51 of file StaticWithTLModelCovariance4D.h.
Increment4D_
template<typename MODEL > using oops::StaticWithTLModelCovariance4D< MODEL >::Increment4D_ = Increment4D<MODEL> private
Definition at line 50 of file StaticWithTLModelCovariance4D.h.
Increment_
template<typename MODEL > using oops::StaticWithTLModelCovariance4D< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 47 of file StaticWithTLModelCovariance4D.h.
IncrEnsCtlVec_
template<typename MODEL > using oops::StaticWithTLModelCovariance4D< MODEL >::IncrEnsCtlVec_ = IncrEnsCtlVec<MODEL> private
Definition at line 52 of file StaticWithTLModelCovariance4D.h.
IncrModCtlVec_
template<typename MODEL > using oops::StaticWithTLModelCovariance4D< MODEL >::IncrModCtlVec_ = IncrModCtlVec<MODEL> private
Definition at line 53 of file StaticWithTLModelCovariance4D.h.
LinearModel_
template<typename MODEL > using oops::StaticWithTLModelCovariance4D< MODEL >::LinearModel_ = LinearModel<MODEL> private
Definition at line 57 of file StaticWithTLModelCovariance4D.h.
MatrixFactory_
template<typename MODEL > using oops::StaticWithTLModelCovariance4D< MODEL >::MatrixFactory_ = GenericMatrixFactory<MODEL> private
Definition at line 65 of file StaticWithTLModelCovariance4D.h.
Model_
template<typename MODEL > using oops::StaticWithTLModelCovariance4D< MODEL >::Model_ = Model<MODEL> private
Definition at line 58 of file StaticWithTLModelCovariance4D.h.
ModelAuxCtrl_
template<typename MODEL > using oops::StaticWithTLModelCovariance4D< MODEL >::ModelAuxCtrl_ = ModelAuxControl<MODEL> private
Definition at line 55 of file StaticWithTLModelCovariance4D.h.
ModelAuxIncrement_
template<typename MODEL > using oops::StaticWithTLModelCovariance4D< MODEL >::ModelAuxIncrement_ = ModelAuxIncrement<MODEL> private
Definition at line 56 of file StaticWithTLModelCovariance4D.h.
ObserverAD_
template<typename MODEL > using oops::StaticWithTLModelCovariance4D< MODEL >::ObserverAD_ = ObserverEnVarAD<MODEL, Increment_> private
Definition at line 60 of file StaticWithTLModelCovariance4D.h.
ObserverTL_
template<typename MODEL > using oops::StaticWithTLModelCovariance4D< MODEL >::ObserverTL_ = ObserverEnVarTL<MODEL, Increment_> private
Definition at line 59 of file StaticWithTLModelCovariance4D.h.
PostProcessorAD_
template<typename MODEL > using oops::StaticWithTLModelCovariance4D< MODEL >::PostProcessorAD_ = PostProcessorAD<Increment_> private
Definition at line 62 of file StaticWithTLModelCovariance4D.h.
PostProcessorTL_
template<typename MODEL > using oops::StaticWithTLModelCovariance4D< MODEL >::PostProcessorTL_ = PostProcessorTL<Increment_> private
Definition at line 61 of file StaticWithTLModelCovariance4D.h.
State4D_
template<typename MODEL > using oops::StaticWithTLModelCovariance4D< MODEL >::State4D_ = State4D<MODEL> private
Definition at line 49 of file StaticWithTLModelCovariance4D.h.
State_
template<typename MODEL > using oops::StaticWithTLModelCovariance4D< MODEL >::State_ = State<MODEL> private
Definition at line 48 of file StaticWithTLModelCovariance4D.h.
TrajectorySaver_
template<typename MODEL > using oops::StaticWithTLModelCovariance4D< MODEL >::TrajectorySaver_ = TrajectorySaverMF<MODEL> private
Definition at line 63 of file StaticWithTLModelCovariance4D.h.
Variables_
template<typename MODEL > using oops::StaticWithTLModelCovariance4D< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 54 of file StaticWithTLModelCovariance4D.h.
Constructor & Destructor Documentation
StaticWithTLModelCovariance4D()
template<typename MODEL > oops::StaticWithTLModelCovariance4D< MODEL >::StaticWithTLModelCovariance4D (const Geometry_ & resol, const Variables_ & vars, const eckit::Configuration & config, const State4D_ & xb)
Constructor, destructor.
Definition at line 103 of file StaticWithTLModelCovariance4D.h.
                 : ModelSpaceCovariance4DBase<MODEL>::ModelSpaceCovariance4DBase(resol,
                                                                                 config),
                   nsubwin_(0),
                   config_(config),
                   variables_(vars) {
   static_.reset(CovarianceFactory<MODEL>::create(
      eckit::LocalConfiguration(config, "covariance_3d"),
      resol, variables_, xb[0]));
         Log::trace() << "StaticWithTLModelCovariance4D created.";
 }
References oops::StaticWithTLModelCovariance4D< MODEL >::static_, and oops::StaticWithTLModelCovariance4D< MODEL >::variables_.
~StaticWithTLModelCovariance4D()
template<typename MODEL > oops::StaticWithTLModelCovariance4D< MODEL >::~StaticWithTLModelCovariance4D
Definition at line 119 of file StaticWithTLModelCovariance4D.h.
{
   Log::trace() << "StaticWithTLModelCovariance4D destructed.";
 }
Member Function Documentation
advectedInverseMultiply()
template<typename MODEL > void oops::StaticWithTLModelCovariance4D< MODEL >::advectedInverseMultiply (const Increment4D_ & dxi, Increment4D_ & dxo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 216 of file StaticWithTLModelCovariance4D.h.
{
   dxo.zero();
 }
References oops::Increment4D< MODEL >::zero().
advectedLinearize()
template<typename MODEL > void oops::StaticWithTLModelCovariance4D< MODEL >::advectedLinearize (const State4D_ & xb, const Geometry_ & resol, const eckit::Configuration & config) virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 124 of file StaticWithTLModelCovariance4D.h.
{
   const util::Duration length(config.getString("window_length"));
         PostProcessor<State_> post;
   const eckit::LocalConfiguration low_resol_config(config, "low_resolution");
   low_resol_.reset(new Geometry_(low_resol_config));
         const eckit::LocalConfiguration modelConf(config, "model");
         model_.reset(new Model_(*low_resol_, modelConf));
         const eckit::LocalConfiguration tlmConf(config, "linearmodel");
         ModelAuxCtrl_ moderr(*low_resol_, *model_, config);
         modaux_.reset(new ModelAuxIncrement_(*low_resol_, config));
         State_ x0(xb[0]);
   if (config.has("matrix")) {
     to_low_resol_.reset( MatrixFactory_::create(config));
           to_low_resol_->multiply(x0);
   }
         static_->linearize(x0, *low_resol_, config);
         tlm_.clear();
         post.enrollProcessor(
                         new TrajectorySaver_(x0, moderr, *low_resol_, tlm_, tlmConf));
         model_->forecast(x0, moderr, length, post);
   Log::trace() << "StaticWithTLModelCovariance4D linearized.";
 }
References oops::PostProcessor< FLDS >::enrollProcessor().
advectedMultiply()
template<typename MODEL > void oops::StaticWithTLModelCovariance4D< MODEL >::advectedMultiply (const Increment4D_ & dxi, Increment4D_ & dxo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 152 of file StaticWithTLModelCovariance4D.h.
{
   util::Duration length = dxi[dxi.last()].validTime() - dxi[0].validTime();
   PostProcessor<Increment_> no_post;
   dxo.zero();
   std::shared_ptr<ObserverTL_> obstl(new ObserverTL_(dxo, to_low_resol_));
   PostProcessorTL_ costtl;
   costtl.enrollProcessor(obstl);
   std::shared_ptr<ObserverAD_> obsad(new ObserverAD_(dxi, to_low_resol_));
   PostProcessorAD_ costad;
   costad.enrollProcessor(obsad);
   Increment_ dx(*low_resol_, variables_, dxi[dxi.first()].validTime(),
                 dxi[dxi.last()].validTime());
   dx.zero();
   tlm_[0]->forecastAD(dx, *modaux_, length, no_post, costad);
   static_->multiply(dx, dx);
   tlm_[0]->forecastTL(dx, *modaux_, length, no_post, costtl);
 }
References oops::PostProcessorAD< INCR >::enrollProcessor(), oops::PostProcessorTL< INCR >::enrollProcessor(), oops::Increment4D< MODEL >::first(), oops::Increment4D< MODEL >::last(), oops::Increment4D< MODEL >::zero(), and oops::Increment< MODEL >::zero().
advectedMultiplySqrt()
template<typename MODEL > void oops::StaticWithTLModelCovariance4D< MODEL >::advectedMultiplySqrt (const IncrCtlVec_ & dvi, Increment4D_ & dxo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 177 of file StaticWithTLModelCovariance4D.h.
{
   util::Duration length = dxo[dxo.last()].validTime() - dxo[0].validTime();
   PostProcessor<Increment_> no_post;
   dxo.zero();
   std::shared_ptr<ObserverTL_> obstl(new ObserverTL_(dxo, to_low_resol_));
   PostProcessorTL_ costtl;
   costtl.enrollProcessor(obstl);
   Increment_ dx(*low_resol_, variables_, dxo[dxo.first()].validTime(),
                 dxo[dxo.first()].validTime());
   dx.zero();
   static_->multiplySqrt(dvi, dx);
   tlm_[0]->forecastTL(dx, *modaux_, length, no_post, costtl);
 }
References oops::PostProcessorTL< INCR >::enrollProcessor(), oops::Increment4D< MODEL >::first(), oops::Increment4D< MODEL >::last(), oops::Increment4D< MODEL >::zero(), and oops::Increment< MODEL >::zero().
advectedMultiplySqrtTrans()
template<typename MODEL > void oops::StaticWithTLModelCovariance4D< MODEL >::advectedMultiplySqrtTrans (const Increment4D_ & dxi, IncrCtlVec_ & dvo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 197 of file StaticWithTLModelCovariance4D.h.
{
   util::Duration length = dxi[dxi.last()].validTime() - dxi[0].validTime();
   PostProcessor<Increment_> no_post;
   std::shared_ptr<ObserverAD_> obsad(new ObserverAD_(dxi, to_low_resol_));
   PostProcessorAD_ costad;
   costad.enrollProcessor(obsad);
   Increment_ dx(*low_resol_, variables_, dxi[dxi.first()].validTime(),
                 dxi[dxi.last()].validTime());
   dx.zero();
   tlm_[0]->forecastAD(dx, *modaux_, length, no_post, costad);
   static_->multiplySqrtTrans(dx, dvo);
 }
References oops::PostProcessorAD< INCR >::enrollProcessor(), oops::Increment4D< MODEL >::first(), oops::Increment4D< MODEL >::last(), and oops::Increment< MODEL >::zero().
covar()
template<typename MODEL > const ModelSpaceCovarianceBase<MODEL>& oops::StaticWithTLModelCovariance4D< MODEL >::covar () const inline virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 78 of file StaticWithTLModelCovariance4D.h.
 { return *static_; }
References oops::StaticWithTLModelCovariance4D< MODEL >::static_.
newIncrEnsCtlVec()
template<typename MODEL > IncrEnsCtlVec_* oops::StaticWithTLModelCovariance4D< MODEL >::newIncrEnsCtlVec () const inline virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 84 of file StaticWithTLModelCovariance4D.h.
 { return new IncrEnsCtlVec_(); }
newIncrModCtlVec()
template<typename MODEL > IncrModCtlVec_* oops::StaticWithTLModelCovariance4D< MODEL >::newIncrModCtlVec () const inline virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 81 of file StaticWithTLModelCovariance4D.h.
{
     return static_->newIncrModCtlVec();
   }
References oops::StaticWithTLModelCovariance4D< MODEL >::static_.
Member Data Documentation
config_
template<typename MODEL > const eckit::LocalConfiguration oops::StaticWithTLModelCovariance4D< MODEL >::config_ private
Definition at line 88 of file StaticWithTLModelCovariance4D.h.
low_resol_
template<typename MODEL > std::unique_ptr<Geometry_> oops::StaticWithTLModelCovariance4D< MODEL >::low_resol_ private
Definition at line 94 of file StaticWithTLModelCovariance4D.h.
modaux_
template<typename MODEL > std::unique_ptr<ModelAuxIncrement_> oops::StaticWithTLModelCovariance4D< MODEL >::modaux_ private
Definition at line 91 of file StaticWithTLModelCovariance4D.h.
model_
template<typename MODEL > std::unique_ptr<Model_> oops::StaticWithTLModelCovariance4D< MODEL >::model_ private
Definition at line 92 of file StaticWithTLModelCovariance4D.h.
nsubwin_
template<typename MODEL > unsigned oops::StaticWithTLModelCovariance4D< MODEL >::nsubwin_ private
Definition at line 87 of file StaticWithTLModelCovariance4D.h.
static_
template<typename MODEL > std::unique_ptr<ModelSpaceCovarianceBase<MODEL> > oops::StaticWithTLModelCovariance4D< MODEL >::static_ private
Definition at line 90 of file StaticWithTLModelCovariance4D.h.
Referenced by oops::StaticWithTLModelCovariance4D< MODEL >::covar(), oops::StaticWithTLModelCovariance4D< MODEL >::newIncrModCtlVec(), and oops::StaticWithTLModelCovariance4D< MODEL >::StaticWithTLModelCovariance4D().
tlm_
template<typename MODEL > std::vector<std::unique_ptr<LinearModel_> > oops::StaticWithTLModelCovariance4D< MODEL >::tlm_ private
Definition at line 93 of file StaticWithTLModelCovariance4D.h.
to_low_resol_
template<typename MODEL > std::shared_ptr<GenericMatrix_> oops::StaticWithTLModelCovariance4D< MODEL >::to_low_resol_ private
Definition at line 95 of file StaticWithTLModelCovariance4D.h.
variables_
template<typename MODEL > const Variables_ oops::StaticWithTLModelCovariance4D< MODEL >::variables_ private
Definition at line 89 of file StaticWithTLModelCovariance4D.h.
Referenced by oops::StaticWithTLModelCovariance4D< MODEL >::StaticWithTLModelCovariance4D().
The documentation for this class was generated from the following file:
src/oops/base/StaticWithTLModelCovariance4D.h