OOPS Documentation: oops::DRGMRESRMinimizer< MODEL > Class Template Reference
oops::DRGMRESRMinimizer< MODEL > Class Template Reference
Derber-Rosati GMRESR Minimizer.
#include <DRGMRESRMinimizer.h>
Public Member Functions
const std::string classname () const override
DRGMRESRMinimizer (const eckit::Configuration &, const CostFct_ &J)
~DRGMRESRMinimizer ()
Public Member Functions inherited from oops::DRMinimizer< MODEL >
DRMinimizer (const CostFct_ &J)
~DRMinimizer ()
void checkpoint (eckit::LocalConfiguration &) const
Checkpointing, restart.
void restart (const eckit::Configuration &)
Restart the minimizer (virtual method)
void warmStart (const eckit::Configuration &)
Warm start the minimizer (virtual method)
Public Member Functions inherited from oops::Minimizer< MODEL >
Minimizer (const CostFct_ &J)
Construct a minimizer.
virtual ~Minimizer ()
Destroy a minimizer.
ControlIncrement< MODEL > * minimize (const eckit::Configuration &)
Orchestrate the minimization of a quadratic cost function.
Private Types
using Bmat_ = BMatrix< MODEL >
using CostFct_ = CostFunction< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using HtRinvH_ = HtRinvHMatrix< MODEL >
Private Member Functions
double solve (CtrlInc_ &, CtrlInc_ &, CtrlInc_ &, const Bmat_ &, const HtRinvH_ &, const double, const double, const int, const double) override
Detailed Description
template<typename MODEL>
class oops::DRGMRESRMinimizer< MODEL >
Derber-Rosati GMRESR Minimizer.
Derber-Rosati GMRESR solver for Ax=b.
DRGMRESR solver for Ax=b. This is a "double" version of GMRESR (H.A. Van der Vorst and C. Vuik, 1994, Numerical Linear Algebra with Applications, 1(4), 369-386) following Derber and Rosati (J. Derber and A. Rosati, 1989, J. Phys. Oceanog. 1333-1347). It solves Ax=b for the particular case \(A=B^{-1}+C\), without requiring the application of \(B^{-1}\). A must be square, but need not be symmetric. (For a symmetric matrix, and constant preconditioner, DRGMRESR is simply Derber-Rosati PCG with full orthogonalisation.) A preconditioner must be supplied that, given a vector q, returns an approximate solution of \((AB)^{-1} q\). The preconditioner can be variable. Note that the traditional \(B\)-preconditioning corresponds to precond= \(I\).
On entry:
x = starting point, \(X_0 \).
xh = \(B^{-1} x_0\).
B = \(B \).
C = \(C \).
precond = preconditioner matrix \(F_k \approx (AB)^{-1} \).
On exit, x will contain the solution \(x \) and xh will contain \(B^{-1} x\).
Matrices must implement a method:
void multiply(const VECTOR&, VECTOR&) const
which applies the matrix to the first argument, and returns the matrix-vector product in the second. (Note: the const is optional, but recommended.)
Iteration will stop if the maximum iteration limit "maxiter" is reached or if the residual norm reduces by a factor of "tolerance".
The return value is the achieved reduction in residual norm.
Definition at line 74 of file DRGMRESRMinimizer.h.
Member Typedef Documentation
Bmat_
template<typename MODEL > using oops::DRGMRESRMinimizer< MODEL >::Bmat_ = BMatrix<MODEL> private
Definition at line 75 of file DRGMRESRMinimizer.h.
CostFct_
template<typename MODEL > using oops::DRGMRESRMinimizer< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 76 of file DRGMRESRMinimizer.h.
CtrlInc_
template<typename MODEL > using oops::DRGMRESRMinimizer< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 77 of file DRGMRESRMinimizer.h.
HtRinvH_
template<typename MODEL > using oops::DRGMRESRMinimizer< MODEL >::HtRinvH_ = HtRinvHMatrix<MODEL> private
Definition at line 78 of file DRGMRESRMinimizer.h.
Constructor & Destructor Documentation
DRGMRESRMinimizer()
template<typename MODEL > oops::DRGMRESRMinimizer< MODEL >::DRGMRESRMinimizer (const eckit::Configuration & , const CostFct_ & J) inline
Definition at line 82 of file DRGMRESRMinimizer.h.
       : DRMinimizer<MODEL>(J) {}
~DRGMRESRMinimizer()
template<typename MODEL > oops::DRGMRESRMinimizer< MODEL >::~DRGMRESRMinimizer () inline
Definition at line 84 of file DRGMRESRMinimizer.h.
 {}
Member Function Documentation
classname()
template<typename MODEL > const std::string oops::DRGMRESRMinimizer< MODEL >::classname () const inline override virtual
Implements oops::DRMinimizer< MODEL >.
Definition at line 81 of file DRGMRESRMinimizer.h.
 { return "DRGMRESRMinimizer"; }
solve()
template<typename MODEL > double oops::DRGMRESRMinimizer< MODEL >::solve (CtrlInc_ & xx, CtrlInc_ & xh, CtrlInc_ & rr, const Bmat_ & B, const HtRinvH_ & HtRinvH, const double costJ0Jb, const double costJ0JoJc, const int maxiter, const double tolerance) override private virtual
Implements oops::DRMinimizer< MODEL >.
Definition at line 95 of file DRGMRESRMinimizer.h.
{
   IdentityMatrix<CtrlInc_> precond;
   std::vector<CtrlInc_> c;
   std::vector<CtrlInc_> u;
   std::vector<CtrlInc_> uh;
   CtrlInc_ cc(xh);
   CtrlInc_ zz(xh);
   CtrlInc_ zh(xh);
   double dotRr0 = dot_product(rr, rr);
   double normReduction = 1.0;
   Log::info() << std::endl;
   for (int jiter = 0; jiter < maxiter; ++jiter) {
     Log::info() << " DRGMRESR Starting Iteration " << jiter + 1 << std::endl;
     precond.multiply(rr, zh);  // returns zh as approxmate solve of (BA)zh = r
     B.multiply(zh, zz);        // x=B zh
     HtRinvH.multiply(zz, cc);
     cc += zh;  // cc = zh+Cz = Az
     for (int jj = 0; jj < jiter; ++jj) {
       double alpha = -dot_product(c[jj], cc);
       cc.axpy(alpha, c[jj]);   // cc = cc - <c[jj],cc>*c[jj];
       zz.axpy(alpha, u[jj]);   // zz = zz - <c[jj],cc>*u[jj];
       zh.axpy(alpha, uh[jj]);  // zh = zh - <c[jj],cc>*uh[jj];
     }
     double ccnorm = sqrt(dot_product(cc, cc));
     c.push_back(cc);  // c[jiter]=cc
     c[jiter] *= 1.0 / ccnorm;
     u.push_back(zz);  // u[jiter]=z
     u[jiter] *= 1.0 / ccnorm;
     uh.push_back(zh);  // uh[jiter]=zh
     uh[jiter] *= 1.0 / ccnorm;
     double cdotr = dot_product(c[jiter], rr);
     xx.axpy(cdotr, u[jiter]);
     xh.axpy(cdotr, uh[jiter]);
     rr.axpy(-cdotr, c[jiter]);
     normReduction = sqrt(dot_product(rr, rr) / dotRr0);
     Log::info() << "DRGMRESR end of iteration " << jiter + 1
                 << ". Norm reduction= " << util::full_precision(normReduction)
                 << std::endl
                 << std::endl;
     if (normReduction < tolerance) {
       Log::info() << "DRGMRESR: Achieved required reduction in residual norm."
                   << std::endl;
       break;
     }
   }
   return normReduction;
 }
References oops::ControlIncrement< MODEL >::axpy(), dot_product(), util::full_precision(), oops::IdentityMatrix< VECTOR >::multiply(), oops::BMatrix< MODEL >::multiply(), and oops::HtRinvHMatrix< MODEL >::multiply().
The documentation for this class was generated from the following file:
src/oops/assimilation/DRGMRESRMinimizer.h