OOPS Documentation: oops::GenericMatrixFactory< MODEL > Class Template Reference
oops::GenericMatrixFactory< MODEL > Class Template Reference abstract
GenericMatrixFactory Factory.
#include <GenericMatrix.h>
Public Member Functions
virtual ~GenericMatrixFactory ()
Static Public Member Functions
static GenericMatrix< MODEL > * create (const eckit::Configuration &)
Protected Member Functions
GenericMatrixFactory (const std::string &)
Private Member Functions
virtual GenericMatrix< MODEL > * make (const eckit::Configuration &)=0
Static Private Member Functions
static std::map< std::string, GenericMatrixFactory< MODEL > * > & getMakers ()
Detailed Description
template<typename MODEL>
class oops::GenericMatrixFactory< MODEL >
GenericMatrixFactory Factory.
Definition at line 69 of file GenericMatrix.h.
Constructor & Destructor Documentation
~GenericMatrixFactory()
template<typename MODEL > virtual oops::GenericMatrixFactory< MODEL >::~GenericMatrixFactory () inline virtual
Definition at line 72 of file GenericMatrix.h.
 { getMakers().clear(); }
References oops::GenericMatrixFactory< MODEL >::getMakers().
GenericMatrixFactory()
template<typename MODEL > oops::GenericMatrixFactory< MODEL >::GenericMatrixFactory (const std::string & name) explicit protected
Definition at line 101 of file GenericMatrix.h.
{
   if (getMakers().find(name) != getMakers().end()) {
     Log::error() << name << " already registered in observation error factory."
                  << std::endl;
     ABORT("Element already registered in GenericMatrixFactory.");
   }
   getMakers()[name] = this;
 }
References ABORT.
Member Function Documentation
create()
template<typename MODEL > GenericMatrix< MODEL > * oops::GenericMatrixFactory< MODEL >::create (const eckit::Configuration & conf) static
Definition at line 113 of file GenericMatrix.h.
{
   Log::trace() << "GenericMatrix<MODEL>::create starting" << std::endl;
   const std::string id = conf.getString("matrix");
   typename std::map<std::string, GenericMatrixFactory<MODEL> *>::iterator jerr =
       getMakers().find(id);
   if (jerr == getMakers().end()) {
     Log::error() << id << " does not exist in matrix factory." << std::endl;
     ABORT("Element does not exist in GenericMatrixFactory.");
   }
   GenericMatrix<MODEL> *ptr = jerr->second->make(conf);
   Log::trace() << "GenericMatrix<MODEL>::create done" << std::endl;
   return ptr;
 }
References ABORT.
Referenced by oops::ObserverIAU< MODEL, STATE >::ObserverIAU().
getMakers()
template<typename MODEL > static std::map<std::string, GenericMatrixFactory<MODEL> *>& oops::GenericMatrixFactory< MODEL >::getMakers () inline static private
Definition at line 79 of file GenericMatrix.h.
{
     static std::map<std::string, GenericMatrixFactory<MODEL> *> makers_;
     return makers_;
   }
Referenced by oops::GenericMatrixFactory< MODEL >::~GenericMatrixFactory().
make()
template<typename MODEL > virtual GenericMatrix<MODEL>* oops::GenericMatrixFactory< MODEL >::make (const eckit::Configuration &) private pure virtual
Implemented in oops::GenericMatrixMaker< MODEL, T >.
The documentation for this class was generated from the following file:
src/oops/interface/GenericMatrix.h