OOPS Documentation: oops::Forecast< MODEL > Class Template Reference
oops::Forecast< MODEL > Class Template Reference
#include <Forecast.h>
Public Member Functions
Forecast ()
virtual ~Forecast ()
int execute (const eckit::Configuration &fullConfig) const
Public Member Functions inherited from oops::Application
Application ()
virtual ~Application ()
Private Types
using Geometry_ = Geometry< MODEL >
using Model_ = Model< MODEL >
using ModelAux_ = ModelAuxControl< MODEL >
using State_ = State< MODEL >
Private Member Functions
std::string appname () const
Detailed Description
template<typename MODEL>
class oops::Forecast< MODEL >
Definition at line 36 of file Forecast.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::Forecast< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 37 of file Forecast.h.
Model_
template<typename MODEL > using oops::Forecast< MODEL >::Model_ = Model<MODEL> private
Definition at line 38 of file Forecast.h.
ModelAux_
template<typename MODEL > using oops::Forecast< MODEL >::ModelAux_ = ModelAuxControl<MODEL> private
Definition at line 39 of file Forecast.h.
State_
template<typename MODEL > using oops::Forecast< MODEL >::State_ = State<MODEL> private
Definition at line 40 of file Forecast.h.
Constructor & Destructor Documentation
Forecast()
template<typename MODEL > oops::Forecast< MODEL >::Forecast () inline
Definition at line 44 of file Forecast.h.
 { instantiatePostProcessorStateFactory<MODEL>(); }
~Forecast()
template<typename MODEL > virtual oops::Forecast< MODEL >::~Forecast () inline virtual
Definition at line 46 of file Forecast.h.
 {}
Member Function Documentation
appname()
template<typename MODEL > std::string oops::Forecast< MODEL >::appname () const inline private virtual
Implements oops::Application.
Definition at line 103 of file Forecast.h.
{
     return "oops::Forecast<" + MODEL::name() + ">";
   }
execute()
template<typename MODEL > int oops::Forecast< MODEL >::execute (const eckit::Configuration & fullConfig) const inline virtual
Setup resolution
Setup Model
Setup initial state
Setup augmented state
Setup times
Setup forecast outputs
Run forecast
Implements oops::Application.
Definition at line 48 of file Forecast.h.
{
     const eckit::LocalConfiguration resolConfig(fullConfig, "resolution");
     const Geometry_ resol(resolConfig);
     const eckit::LocalConfiguration modelConfig(fullConfig, "model");
     const Model_ model(resol, modelConfig);
     const eckit::LocalConfiguration initialConfig(fullConfig, "initial");
     State_ xx(resol, model, initialConfig);
     Log::test() << "Initial state: " << xx.norm() << std::endl;
     const ModelAux_ moderr(resol, model, initialConfig);
     const util::Duration fclength(fullConfig.getString("forecast_length"));
     const util::DateTime bgndate(xx.validTime());
     const util::DateTime enddate(bgndate + fclength);
     Log::info() << "Running forecast from " << bgndate << " to " << enddate
                 << std::endl;
     PostProcessor<State_> post;
     eckit::LocalConfiguration prtConfig;
     if (fullConfig.has("prints")) {
       prtConfig = eckit::LocalConfiguration(fullConfig, "prints");
     }
     post.enrollProcessor(new StateInfo<State_>("fc", prtConfig));
     const eckit::LocalConfiguration outConfig(fullConfig, "output");
     post.enrollProcessor(new StateWriter<State_>(bgndate, outConfig));
     if (fullConfig.has("post_processors")) {
       std::vector<eckit::LocalConfiguration> postConfigs;
       fullConfig.get("post_processors", postConfigs);
       for (size_t jj = 0; jj < postConfigs.size(); ++jj) {
         PostBase<State_>* pp =
             PostProcessorFactory<State_>::create(postConfigs[jj]);
         post.enrollProcessor(pp);
       }
     }
     model.forecast(xx, moderr, fclength, post);
     Log::test() << "Final state: " << xx.norm() << std::endl;
     return 0;
   }
References oops::PostProcessorFactory< FLDS >::create(), oops::PostProcessor< FLDS >::enrollProcessor(), oops::Model< MODEL >::forecast(), oops::State< MODEL >::norm(), and oops::State< MODEL >::validTime().
The documentation for this class was generated from the following file:
src/oops/runs/Forecast.h