OOPS Documentation: oops::JqTerm< MODEL > Class Template Reference
oops::JqTerm< MODEL > Class Template Reference
#include <CostFunction.h>
Public Member Functions
JqTerm (unsigned nsub)
~JqTerm ()
void linearize ()
void computeModelError (const State4D_ &, Increment4D_ &)
Private Types
using State_ = State< MODEL >
using Increment4D_ = Increment4D< MODEL >
using State4D_ = State4D< MODEL >
Private Member Functions
void doInitialize (const State_ &, const util::DateTime &, const util::Duration &) override
void doProcessing (const State_ &) override
void doFinalize (const State_ &) override
Private Attributes
std::vector< State_ > mxi_
const unsigned nsubwin_
Detailed Description
template<typename MODEL>
class oops::JqTerm< MODEL >
Definition at line 53 of file CostFunction.h.
Member Typedef Documentation
Increment4D_
template<typename MODEL > using oops::JqTerm< MODEL >::Increment4D_ = Increment4D<MODEL> private
Definition at line 31 of file JqTerm.h.
State4D_
template<typename MODEL > using oops::JqTerm< MODEL >::State4D_ = State4D<MODEL> private
Definition at line 32 of file JqTerm.h.
State_
template<typename MODEL > using oops::JqTerm< MODEL >::State_ = State<MODEL> private
Definition at line 30 of file JqTerm.h.
Constructor & Destructor Documentation
JqTerm()
template<typename MODEL > oops::JqTerm< MODEL >::JqTerm (unsigned nsub) inline explicit
Definition at line 35 of file JqTerm.h.
 : mxi_(), nsubwin_(nsub) {}
~JqTerm()
template<typename MODEL > oops::JqTerm< MODEL >::~JqTerm () inline
Definition at line 36 of file JqTerm.h.
 {}
Member Function Documentation
computeModelError()
template<typename MODEL > void oops::JqTerm< MODEL >::computeModelError (const State4D_ & fg, Increment4D_ & dx)
Definition at line 61 of file JqTerm.h.
{
   // Compute x_i - M(x_{i-1})
   for (unsigned jsub = 1; jsub < nsubwin_; ++jsub) {
     dx[jsub].diff(fg[jsub], mxi_[jsub - 1]);
     Log::info() << "CostJbJq: x_" << jsub << " - M(x_" << jsub - 1 << ")"
                 << dx[jsub] << std::endl;
   }
   mxi_.clear();
 }
References oops::Increment4D< MODEL >::diff().
Referenced by oops::CostJbTotal< MODEL >::finalize(), and oops::CostJbTotal< MODEL >::finalizeTraj().
doFinalize()
template<typename MODEL > void oops::JqTerm< MODEL >::doFinalize (const State_ & xx) override private
Definition at line 54 of file JqTerm.h.
{
   if (mxi_.size() < nsubwin_ - 1) mxi_.push_back(xx);
 }
doInitialize()
template<typename MODEL > void oops::JqTerm< MODEL >::doInitialize (const State_ & , const util::DateTime & , const util::Duration &) inline override private
Definition at line 42 of file JqTerm.h.
                                                    {}
doProcessing()
template<typename MODEL > void oops::JqTerm< MODEL >::doProcessing (const State_ &) inline override private
Definition at line 44 of file JqTerm.h.
 {}
linearize()
template<typename MODEL > void oops::JqTerm< MODEL >::linearize () inline
Definition at line 38 of file JqTerm.h.
 {}
Referenced by oops::CostJbTotal< MODEL >::initializeTraj().
Member Data Documentation
mxi_
template<typename MODEL > std::vector<State_> oops::JqTerm< MODEL >::mxi_ private
Definition at line 47 of file JqTerm.h.
nsubwin_
template<typename MODEL > const unsigned oops::JqTerm< MODEL >::nsubwin_ private
Definition at line 48 of file JqTerm.h.
The documentation for this class was generated from the following files:
src/oops/assimilation/CostFunction.h
src/oops/assimilation/JqTerm.h