OOPS Documentation: oops::CostJbState< MODEL > Class Template Reference
oops::CostJbState< MODEL > Class Template Reference abstract
Pure abstract base class for the Jb term state component.
#include <CostJbState.h>
Public Member Functions
CostJbState ()
Constructor.
virtual ~CostJbState ()
Destructor.
virtual JqTerm< MODEL > * initializeJq () const =0
Initialize Jq computations (relevant for weak constraint).
virtual void computeIncrement (const State4D_ &, const State4D_ &, Increment4D_ &) const =0
Get increment from state (usually first guess).
virtual void linearize (const State4D_ &, const Geometry_ &)=0
Linearize before the linear computations.
virtual void linearize (const State4D_ &xx, const Geometry_ &geom, const eckit::Configuration &)
virtual void addGradient (const Increment4D_ &, Increment4D_ &, Increment4D_ &) const =0
Add Jb gradient.
virtual JqTermTL< MODEL > * initializeJqTL () const =0
Finalize \(J_b\) after the TL run (relevant for weak constraint).
virtual JqTermAD< MODEL > * initializeJqAD (const Increment4D_ &) const =0
Initialize \(J_b\) before the AD run (relevant for weak constraint).
virtual void Bmult (const Increment4D_ &, Increment4D_ &) const =0
Multiply by \(B\).
virtual void Bminv (const Increment4D_ &, Increment4D_ &) const =0
Multiply by \(B^{-1}\).
virtual void BmultSqrt (const IncrCtlVec4D_ &, Increment4D_ &) const =0
Multiply by \(B^{1/2}\).
virtual void BmultSqrtTrans (const Increment4D_ &, IncrCtlVec4D_ &) const =0
Multiply by \([B^{1/2}]^T\).
virtual void randomize (Increment4D_ &) const =0
Randomize.
virtual const ModelSpaceCovarianceBase< MODEL > & covar () const =0
Access to B.
virtual unsigned int nstates () const =0
Return size of the state component of the control variable.
virtual Increment_ * newStateIncrement (const unsigned int) const =0
Create new increment (set to 0).
virtual unsigned int nchistates () const =0
Return size of the state component of the control vector.
virtual IncrCtlVec_ * newIncrCtlVec (const unsigned int) const =0
Create new control vector.
virtual IncrModCtlVec_ * newIncrModCtlVec () const =0
Create new control vector (mod)
virtual IncrEnsCtlVec_ * newIncrEnsCtlVec () const =0
Create new control vector (ens)
Private Types
using CtrlInc_ = ControlIncrement< MODEL >
using Geometry_ = Geometry< MODEL >
using Increment_ = Increment< MODEL >
using Increment4D_ = Increment4D< MODEL >
using IncrCtlVec_ = IncrCtlVec< MODEL >
using IncrCtlVec4D_ = IncrCtlVec4D< MODEL >
using IncrModCtlVec_ = IncrModCtlVec< MODEL >
using IncrEnsCtlVec_ = IncrEnsCtlVec< MODEL >
using State4D_ = State4D< MODEL >
Detailed Description
template<typename MODEL>
class oops::CostJbState< MODEL >
Pure abstract base class for the Jb term state component.
The CostJbState is the base class for the Jb term corresponding to the state part (3D or 4D) of the control variable.
Consider applying the matrix vector product:
\[ B_{state} dx_{state} = \begin{bmatrix} B_0 & 0 & .. & 0 \\ 0 & B_1 & .. & 0 \\ .. & .. & .. & .. \\ 0 & 0 & .. & B_N \end{bmatrix} \begin{bmatrix} dx_0 \\ dx_1 \\ .. \\ dx_N \\ \end{bmatrix} \]
Both \(B_{state} \), as implemented by the JbState class, and \(dx_{state} \), as implemented by Increment4D class, have in the most general case a 4D structure. In case of 3/4D-Var, CostJb3D class contains only a single component \(B_0 \) and likewise Increment4D, implemented as a vector of increments, contains only single component \(dx_0 \).
Definition at line 81 of file CostJbState.h.
Member Typedef Documentation
CtrlInc_
template<typename MODEL > using oops::CostJbState< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 82 of file CostJbState.h.
Geometry_
template<typename MODEL > using oops::CostJbState< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 83 of file CostJbState.h.
IncrCtlVec4D_
template<typename MODEL > using oops::CostJbState< MODEL >::IncrCtlVec4D_ = IncrCtlVec4D<MODEL> private
Definition at line 87 of file CostJbState.h.
IncrCtlVec_
template<typename MODEL > using oops::CostJbState< MODEL >::IncrCtlVec_ = IncrCtlVec<MODEL> private
Definition at line 86 of file CostJbState.h.
Increment4D_
template<typename MODEL > using oops::CostJbState< MODEL >::Increment4D_ = Increment4D<MODEL> private
Definition at line 85 of file CostJbState.h.
Increment_
template<typename MODEL > using oops::CostJbState< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 84 of file CostJbState.h.
IncrEnsCtlVec_
template<typename MODEL > using oops::CostJbState< MODEL >::IncrEnsCtlVec_ = IncrEnsCtlVec<MODEL> private
Definition at line 89 of file CostJbState.h.
IncrModCtlVec_
template<typename MODEL > using oops::CostJbState< MODEL >::IncrModCtlVec_ = IncrModCtlVec<MODEL> private
Definition at line 88 of file CostJbState.h.
State4D_
template<typename MODEL > using oops::CostJbState< MODEL >::State4D_ = State4D<MODEL> private
Definition at line 90 of file CostJbState.h.
Constructor & Destructor Documentation
CostJbState()
template<typename MODEL > oops::CostJbState< MODEL >::CostJbState () inline
Constructor.
Definition at line 94 of file CostJbState.h.
 {}
~CostJbState()
template<typename MODEL > virtual oops::CostJbState< MODEL >::~CostJbState () inline virtual
Destructor.
Definition at line 97 of file CostJbState.h.
 {}
Member Function Documentation
addGradient()
template<typename MODEL > virtual void oops::CostJbState< MODEL >::addGradient (const Increment4D_ & , Increment4D_ & , Increment4D_ &) const pure virtual
Add Jb gradient.
Implemented in oops::CostJb3D< MODEL >, oops::CostJb4D< MODEL >, and oops::CostJbJq< MODEL >.
Bminv()
template<typename MODEL > virtual void oops::CostJbState< MODEL >::Bminv (const Increment4D_ & , Increment4D_ &) const pure virtual
Multiply by \(B^{-1}\).
Implemented in oops::CostJb3D< MODEL >, oops::CostJb4D< MODEL >, and oops::CostJbJq< MODEL >.
Bmult()
template<typename MODEL > virtual void oops::CostJbState< MODEL >::Bmult (const Increment4D_ & , Increment4D_ &) const pure virtual
Multiply by \(B\).
Implemented in oops::CostJb3D< MODEL >, oops::CostJb4D< MODEL >, and oops::CostJbJq< MODEL >.
Referenced by oops::BMatrix< MODEL >::multiplyB().
BmultSqrt()
template<typename MODEL > virtual void oops::CostJbState< MODEL >::BmultSqrt (const IncrCtlVec4D_ & , Increment4D_ &) const pure virtual
Multiply by \(B^{1/2}\).
Implemented in oops::CostJb3D< MODEL >, oops::CostJb4D< MODEL >, and oops::CostJbJq< MODEL >.
BmultSqrtTrans()
template<typename MODEL > virtual void oops::CostJbState< MODEL >::BmultSqrtTrans (const Increment4D_ & , IncrCtlVec4D_ &) const pure virtual
Multiply by \([B^{1/2}]^T\).
Implemented in oops::CostJb3D< MODEL >, oops::CostJb4D< MODEL >, and oops::CostJbJq< MODEL >.
computeIncrement()
template<typename MODEL > virtual void oops::CostJbState< MODEL >::computeIncrement (const State4D_ & , const State4D_ & , Increment4D_ &) const pure virtual
Get increment from state (usually first guess).
Implemented in oops::CostJb3D< MODEL >, oops::CostJb4D< MODEL >, and oops::CostJbJq< MODEL >.
covar()
template<typename MODEL > virtual const ModelSpaceCovarianceBase<MODEL>& oops::CostJbState< MODEL >::covar () const pure virtual
Access to B.
Implemented in oops::CostJb3D< MODEL >, oops::CostJb4D< MODEL >, and oops::CostJbJq< MODEL >.
initializeJq()
template<typename MODEL > virtual JqTerm<MODEL>* oops::CostJbState< MODEL >::initializeJq () const pure virtual
Initialize Jq computations (relevant for weak constraint).
Implemented in oops::CostJb3D< MODEL >, oops::CostJb4D< MODEL >, and oops::CostJbJq< MODEL >.
initializeJqAD()
template<typename MODEL > virtual JqTermAD<MODEL>* oops::CostJbState< MODEL >::initializeJqAD (const Increment4D_ &) const pure virtual
Initialize \(J_b\) before the AD run (relevant for weak constraint).
Implemented in oops::CostJb3D< MODEL >, oops::CostJb4D< MODEL >, and oops::CostJbJq< MODEL >.
initializeJqTL()
template<typename MODEL > virtual JqTermTL<MODEL>* oops::CostJbState< MODEL >::initializeJqTL () const pure virtual
Finalize \(J_b\) after the TL run (relevant for weak constraint).
Implemented in oops::CostJb3D< MODEL >, oops::CostJb4D< MODEL >, and oops::CostJbJq< MODEL >.
linearize() [1/2]
template<typename MODEL > virtual void oops::CostJbState< MODEL >::linearize (const State4D_ & , const Geometry_ &) pure virtual
Linearize before the linear computations.
Implemented in oops::CostJb3D< MODEL >, oops::CostJb4D< MODEL >, and oops::CostJbJq< MODEL >.
Referenced by oops::CostJbState< MODEL >::linearize().
linearize() [2/2]
template<typename MODEL > virtual void oops::CostJbState< MODEL >::linearize (const State4D_ & xx, const Geometry_ & geom, const eckit::Configuration &) inline virtual
Reimplemented in oops::CostJb3D< MODEL >, and oops::CostJb4D< MODEL >.
Definition at line 108 of file CostJbState.h.
{
     linearize(xx,geom);
   }
References oops::CostJbState< MODEL >::linearize().
nchistates()
template<typename MODEL > virtual unsigned int oops::CostJbState< MODEL >::nchistates () const pure virtual
Return size of the state component of the control vector.
Implemented in oops::CostJb3D< MODEL >, oops::CostJb4D< MODEL >, and oops::CostJbJq< MODEL >.
newIncrCtlVec()
template<typename MODEL > virtual IncrCtlVec_* oops::CostJbState< MODEL >::newIncrCtlVec (const unsigned int) const pure virtual
Create new control vector.
Implemented in oops::CostJb3D< MODEL >, oops::CostJb4D< MODEL >, and oops::CostJbJq< MODEL >.
Referenced by oops::IncrCtlVec4D< MODEL >::IncrCtlVec4D().
newIncrEnsCtlVec()
template<typename MODEL > virtual IncrEnsCtlVec_* oops::CostJbState< MODEL >::newIncrEnsCtlVec () const pure virtual
Create new control vector (ens)
Implemented in oops::CostJb3D< MODEL >, oops::CostJb4D< MODEL >, and oops::CostJbJq< MODEL >.
Referenced by oops::IncrCtlVec< MODEL >::newIncrEnsCtlVecCollection().
newIncrModCtlVec()
template<typename MODEL > virtual IncrModCtlVec_* oops::CostJbState< MODEL >::newIncrModCtlVec () const pure virtual
Create new control vector (mod)
Implemented in oops::CostJb3D< MODEL >, oops::CostJb4D< MODEL >, and oops::CostJbJq< MODEL >.
Referenced by oops::IncrCtlVec< MODEL >::newIncrModCtlVec().
newStateIncrement()
template<typename MODEL > virtual Increment_* oops::CostJbState< MODEL >::newStateIncrement (const unsigned int) const pure virtual
Create new increment (set to 0).
Implemented in oops::CostJb3D< MODEL >, oops::CostJb4D< MODEL >, and oops::CostJbJq< MODEL >.
Referenced by oops::Increment4D< MODEL >::Increment4D().
nstates()
template<typename MODEL > virtual unsigned int oops::CostJbState< MODEL >::nstates () const pure virtual
Return size of the state component of the control variable.
Implemented in oops::CostJb3D< MODEL >, oops::CostJb4D< MODEL >, and oops::CostJbJq< MODEL >.
randomize()
template<typename MODEL > virtual void oops::CostJbState< MODEL >::randomize (Increment4D_ &) const pure virtual
Randomize.
Implemented in oops::CostJb3D< MODEL >, oops::CostJb4D< MODEL >, and oops::CostJbJq< MODEL >.
The documentation for this class was generated from the following file:
src/oops/assimilation/CostJbState.h