OOPS Documentation: oops::JcCovarBase< MODEL > Class Template Reference
oops::JcCovarBase< MODEL > Class Template Reference abstract
Base class for encapsulation of the Jc covariances.
#include <JcCovarBase.h>
Public Member Functions
JcCovarBase ()
Constructor.
virtual ~JcCovarBase ()
Destructor.
void linearize (const State_ &, const Geometry_ &)
Set up the inner loop resolution covariance matrix.
void multiply (const Increment_ &, Increment_ &) const
\(dx_1 = C dx_2 \)
void inverseMultiply (const Increment_ &, Increment_ &) const
\(dx_1 = C^{-1} dx_2 \)
Static Public Member Functions
static const std::string classname ()
Protected Member Functions
virtual void linearize (const typename MODEL::State &, const typename MODEL::Geometry &)=0
virtual void multiply (const typename MODEL::Increment &, typename MODEL::Increment &) const =0
virtual void inverseMultiply (const typename MODEL::Increment &, typename MODEL::Increment &) const =0
virtual void print (std::ostream &) const =0
Information and diagnostics.
Private Types
using Increment_ = Increment< MODEL >
using Geometry_ = Geometry< MODEL >
using State_ = State< MODEL >
Detailed Description
template<typename MODEL>
class oops::JcCovarBase< MODEL >
Base class for encapsulation of the Jc covariances.
Defines the interfaces for Jc covariances. JcCovarFactory is used to produce concrete Jc covariances (model specific or generic).
The public methods (linearize, multiply and inverseMultiply) wrap around the corresponding protected virtual methods (linearize, multiply and inverseMultiply) which are implemented by child model specific or generic classes.
Definition at line 52 of file JcCovarBase.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::JcCovarBase< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 54 of file JcCovarBase.h.
Increment_
template<typename MODEL > using oops::JcCovarBase< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 53 of file JcCovarBase.h.
State_
template<typename MODEL > using oops::JcCovarBase< MODEL >::State_ = State<MODEL> private
Definition at line 55 of file JcCovarBase.h.
Constructor & Destructor Documentation
JcCovarBase()
template<typename MODEL > oops::JcCovarBase< MODEL >::JcCovarBase () inline
Constructor.
Definition at line 61 of file JcCovarBase.h.
 {}
~JcCovarBase()
template<typename MODEL > virtual oops::JcCovarBase< MODEL >::~JcCovarBase () inline virtual
Destructor.
Definition at line 63 of file JcCovarBase.h.
 {}
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::JcCovarBase< MODEL >::classname () inline static
Definition at line 58 of file JcCovarBase.h.
 { return "oops::JcCovarBase"; }
inverseMultiply() [1/2]
template<typename MODEL > void oops::JcCovarBase< MODEL >::inverseMultiply (const Increment_ & dx_in, Increment_ & dx_out) const
\(dx_1 = C^{-1} dx_2 \)
Wrapper around the inverseMultiply method of a model-specific/generic JcCovarBase child class.
Definition at line 188 of file JcCovarBase.h.
{
   Log::trace() << "JcCovarBase<MODEL>::inverseMultiply starting" << std::endl;
   util::Timer timer(classname(), "inverseMultiply");
   this->inverseMultiply(dx_in.increment(), dx_out.increment());
   Log::trace() << "JcCovarBase<MODEL>::inverseMultiply done" << std::endl;
 }
References oops::Increment< MODEL >::increment().
inverseMultiply() [2/2]
template<typename MODEL > virtual void oops::JcCovarBase< MODEL >::inverseMultiply (const typename MODEL::Increment & , typename MODEL::Increment &) const protected pure virtual
linearize() [1/2]
template<typename MODEL > void oops::JcCovarBase< MODEL >::linearize (const State_ & x, const Geometry_ & geom)
Set up the inner loop resolution covariance matrix.
Wrapper around the linearize method of a model-specific/generic JcCovarBase child class.
Definition at line 161 of file JcCovarBase.h.
{
   Log::trace() << "JcCovarBase<MODEL>::linearize starting" << std::endl;
   util::Timer timer(classname(), "linearize");
   this->linearize(x.state(), geom.geometry());
   Log::trace() << "JcCovarBase<MODEL>::linearize done" << std::endl;
 }
References oops::Geometry< MODEL >::geometry(), and oops::State< MODEL >::state().
linearize() [2/2]
template<typename MODEL > virtual void oops::JcCovarBase< MODEL >::linearize (const typename MODEL::State & , const typename MODEL::Geometry &) protected pure virtual
multiply() [1/2]
template<typename MODEL > void oops::JcCovarBase< MODEL >::multiply (const Increment_ & dx_in, Increment_ & dx_out) const
\(dx_1 = C dx_2 \)
Wrapper around the multiply method of a model-specific/generic JcCovarBase child class.
Definition at line 174 of file JcCovarBase.h.
{
   Log::trace() << "JcCovarBase<MODEL>::multiply starting" << std::endl;
   util::Timer timer(classname(), "multiply");
   this->multiply(dx_in.increment(), dx_out.increment());
   Log::trace() << "JcCovarBase<MODEL>::multiply done" << std::endl;
 }
References oops::Increment< MODEL >::increment().
multiply() [2/2]
template<typename MODEL > virtual void oops::JcCovarBase< MODEL >::multiply (const typename MODEL::Increment & , typename MODEL::Increment &) const protected pure virtual
print()
template<typename MODEL > virtual void oops::JcCovarBase< MODEL >::print (std::ostream &) const protected pure virtual
Information and diagnostics.
The documentation for this class was generated from the following file:
src/oops/interface/JcCovarBase.h