OOPS Documentation: oops::CostTermBase< MODEL > Class Template Reference
oops::CostTermBase< MODEL > Class Template Reference abstract
Abstract base class for the terms of the cost function (e.g. Jo, Jc).
#include <CostTermBase.h>
Public Member Functions
virtual const std::string classname () const =0
virtual ~CostTermBase ()
Destructor.
virtual PostPtr_ initialize (const ControlVariable< MODEL > &, const eckit::Configuration &) const =0
Return a post-processor to be attached to the non-linear model integration.
virtual PostPtr_ initializeTraj (const ControlVariable< MODEL > &, const Geometry_ &, const eckit::Configuration &)=0
virtual double finalize (const eckit::Configuration &) const =0
Perform computations after nonlinear model integration.
virtual double finalizeTraj (const eckit::Configuration &)=0
Perform computation after the linearisation trajectory computation.
virtual PostTLPtr_ setupTL (const ControlIncrement< MODEL > &) const =0
Return a post-processor-tl to be attached to the TL run.
virtual PostADPtr_ setupAD (std::shared_ptr< const GeneralizedDepartures >, ControlIncrement< MODEL > &) const =0
Return a post-processor-ad to be attached to the AD run.
virtual GeneralizedDepartures * multiplyCovar (const GeneralizedDepartures &) const =0
Multiply by covariance (or weight) matrix and its inverse.
virtual GeneralizedDepartures * multiplyCoInv (const GeneralizedDepartures &) const =0
Multiply by inverse covariance (or weight) matrix.
virtual GeneralizedDepartures * newDualVector () const =0
Provide new dual space vector (for example a Departure for Jo).
virtual GeneralizedDepartures * newDepartures () const =0
Provide departures (for example a Departure for Jo).
virtual GeneralizedDepartures * newGradientFG () const =0
Return gradient at first guess.
virtual void resetLinearization ()=0
Reset trajectory.
virtual void checkpoint (eckit::LocalConfiguration &) const =0
Checkpoint.
virtual void restart (const eckit::Configuration &)=0
Restart.
Private Types
using Geometry_ = Geometry< MODEL >
using State_ = State< MODEL >
using Increment_ = Increment< MODEL >
using PostPtr_ = std::shared_ptr< PostBase< State_ > >
using PostTLPtr_ = std::shared_ptr< PostBaseTL< Increment_ > >
using PostADPtr_ = std::shared_ptr< PostBaseAD< Increment_ > >
Detailed Description
template<typename MODEL>
class oops::CostTermBase< MODEL >
Abstract base class for the terms of the cost function (e.g. Jo, Jc).
A vector of CostTermBase objects is stored by the CostFunction allowing for flexibility of the choice of the terms of the cost function.
Methods initialize (returns a post-processor)/finalize are called prior/post the non-linear model trajectory integration.
Methods initializeTraj (returns a post-processor)/finalizeTraj are called prior/post the linearisation trajectory computation by the TrajecotrySaver.
SetupTL/SetupAD set up post-processors-tl/ad attached to the linear/adjoint model integration.
Definition at line 49 of file CostTermBase.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::CostTermBase< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 50 of file CostTermBase.h.
Increment_
template<typename MODEL > using oops::CostTermBase< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 52 of file CostTermBase.h.
PostADPtr_
template<typename MODEL > using oops::CostTermBase< MODEL >::PostADPtr_ = std::shared_ptr<PostBaseAD<Increment_> > private
Definition at line 55 of file CostTermBase.h.
PostPtr_
template<typename MODEL > using oops::CostTermBase< MODEL >::PostPtr_ = std::shared_ptr<PostBase<State_> > private
Definition at line 53 of file CostTermBase.h.
PostTLPtr_
template<typename MODEL > using oops::CostTermBase< MODEL >::PostTLPtr_ = std::shared_ptr<PostBaseTL<Increment_> > private
Definition at line 54 of file CostTermBase.h.
State_
template<typename MODEL > using oops::CostTermBase< MODEL >::State_ = State<MODEL> private
Definition at line 51 of file CostTermBase.h.
Constructor & Destructor Documentation
~CostTermBase()
template<typename MODEL > virtual oops::CostTermBase< MODEL >::~CostTermBase () inline virtual
Destructor.
Definition at line 61 of file CostTermBase.h.
 {}
Member Function Documentation
checkpoint()
template<typename MODEL > virtual void oops::CostTermBase< MODEL >::checkpoint (eckit::LocalConfiguration &) const pure virtual
Checkpoint.
Implemented in oops::CostJo< MODEL >, and oops::CostJcDFI< MODEL >.
classname()
template<typename MODEL > virtual const std::string oops::CostTermBase< MODEL >::classname () const pure virtual
Implemented in oops::CostJo< MODEL >, and oops::CostJcDFI< MODEL >.
finalize()
template<typename MODEL > virtual double oops::CostTermBase< MODEL >::finalize (const eckit::Configuration &) const pure virtual
Perform computations after nonlinear model integration.
Implemented in oops::CostJo< MODEL >, and oops::CostJcDFI< MODEL >.
finalizeTraj()
template<typename MODEL > virtual double oops::CostTermBase< MODEL >::finalizeTraj (const eckit::Configuration &) pure virtual
Perform computation after the linearisation trajectory computation.
Implemented in oops::CostJo< MODEL >, and oops::CostJcDFI< MODEL >.
initialize()
template<typename MODEL > virtual PostPtr_ oops::CostTermBase< MODEL >::initialize (const ControlVariable< MODEL > & , const eckit::Configuration &) const pure virtual
Return a post-processor to be attached to the non-linear model integration.
Implemented in oops::CostJo< MODEL >, and oops::CostJcDFI< MODEL >.
initializeTraj()
template<typename MODEL > virtual PostPtr_ oops::CostTermBase< MODEL >::initializeTraj (const ControlVariable< MODEL > & , const Geometry_ & , const eckit::Configuration &) pure virtual
Return a post-processor to be attached to the linearisation trajectory computation
Implemented in oops::CostJo< MODEL >, and oops::CostJcDFI< MODEL >.
multiplyCoInv()
template<typename MODEL > virtual GeneralizedDepartures* oops::CostTermBase< MODEL >::multiplyCoInv (const GeneralizedDepartures &) const pure virtual
Multiply by inverse covariance (or weight) matrix.
Implemented in oops::CostJo< MODEL >, and oops::CostJcDFI< MODEL >.
Referenced by oops::RinvMatrix< MODEL >::multiply(), oops::LBHessianMatrix< MODEL >::multiply(), and oops::RMatrix< MODEL >::multiplyInv().
multiplyCovar()
template<typename MODEL > virtual GeneralizedDepartures* oops::CostTermBase< MODEL >::multiplyCovar (const GeneralizedDepartures &) const pure virtual
Multiply by covariance (or weight) matrix and its inverse.
Implemented in oops::CostJo< MODEL >, and oops::CostJcDFI< MODEL >.
newDepartures()
template<typename MODEL > virtual GeneralizedDepartures* oops::CostTermBase< MODEL >::newDepartures () const pure virtual
Provide departures (for example a Departure for Jo).
Implemented in oops::CostJo< MODEL >, and oops::CostJcDFI< MODEL >.
newDualVector()
template<typename MODEL > virtual GeneralizedDepartures* oops::CostTermBase< MODEL >::newDualVector () const pure virtual
Provide new dual space vector (for example a Departure for Jo).
Implemented in oops::CostJo< MODEL >, and oops::CostJcDFI< MODEL >.
newGradientFG()
template<typename MODEL > virtual GeneralizedDepartures* oops::CostTermBase< MODEL >::newGradientFG () const pure virtual
Return gradient at first guess.
Implemented in oops::CostJo< MODEL >, and oops::CostJcDFI< MODEL >.
resetLinearization()
template<typename MODEL > virtual void oops::CostTermBase< MODEL >::resetLinearization () pure virtual
Reset trajectory.
Implemented in oops::CostJo< MODEL >, and oops::CostJcDFI< MODEL >.
restart()
template<typename MODEL > virtual void oops::CostTermBase< MODEL >::restart (const eckit::Configuration &) pure virtual
Restart.
Implemented in oops::CostJo< MODEL >, and oops::CostJcDFI< MODEL >.
setupAD()
template<typename MODEL > virtual PostADPtr_ oops::CostTermBase< MODEL >::setupAD (std::shared_ptr< const GeneralizedDepartures > , ControlIncrement< MODEL > &) const pure virtual
Return a post-processor-ad to be attached to the AD run.
Implemented in oops::CostJo< MODEL >, and oops::CostJcDFI< MODEL >.
Referenced by oops::HtMatrix< MODEL >::multiply(), and oops::LBHessianMatrix< MODEL >::multiply().
setupTL()
template<typename MODEL > virtual PostTLPtr_ oops::CostTermBase< MODEL >::setupTL (const ControlIncrement< MODEL > &) const pure virtual
Return a post-processor-tl to be attached to the TL run.
Implemented in oops::CostJo< MODEL >, and oops::CostJcDFI< MODEL >.
Referenced by oops::HMatrix< MODEL >::multiply(), and oops::LBHessianMatrix< MODEL >::multiply().
The documentation for this class was generated from the following file:
src/oops/assimilation/CostTermBase.h