OOPS Documentation: oops::ControlObsVector< MODEL > Class Template Reference
oops::ControlObsVector< MODEL > Class Template Reference
#include <ControlObsVector.h>
Public Member Functions
ControlObsVector (const ObsSpace_ &)
ControlObsVector (const ControlObsVector &, const bool copy=true)
ControlObsVector (ObsVector_ *, ObsVector_ *)
~ControlObsVector ()
ObsVector_ & obsvector ()
Interfacing.
const ObsVector_ & obsvector () const
ObsVector_ & biasvector ()
const ObsVector_ & biasvector () const
bool hasBias () const
ControlObsVector & operator= (const ControlObsVector &)
ControlObsVector & operator*= (const double &)
ControlObsVector & operator+= (const ControlObsVector &)
ControlObsVector & operator-= (const ControlObsVector &)
ControlObsVector & operator*= (const ControlObsVector &)
ControlObsVector & operator/= (const ControlObsVector &)
void zero ()
void axpy (const double &, const ControlObsVector &)
void invert ()
void random ()
double dot_product_with (const ControlObsVector &) const
double rms () const
unsigned int size () const
void read (const eckit::Configuration &)
void save (const eckit::Configuration &) const
Static Public Member Functions
static const std::string classname ()
Private Types
using ObsVector_ = ObsVector< MODEL >
using ObsSpace_ = ObservationSpace< MODEL >
Private Member Functions
void print (std::ostream &) const
Private Attributes
std::unique_ptr< ObsVector_ > obsvec_
std::unique_ptr< ObsVector_ > biasvec_
Detailed Description
template<typename MODEL>
class oops::ControlObsVector< MODEL >
Definition at line 44 of file ControlObsVector.h.
Member Typedef Documentation
ObsSpace_
template<typename MODEL > using oops::ControlObsVector< MODEL >::ObsSpace_ = ObservationSpace<MODEL> private
Definition at line 47 of file ControlObsVector.h.
ObsVector_
template<typename MODEL > using oops::ControlObsVector< MODEL >::ObsVector_ = ObsVector<MODEL> private
Definition at line 46 of file ControlObsVector.h.
Constructor & Destructor Documentation
ControlObsVector() [1/3]
template<typename MODEL > oops::ControlObsVector< MODEL >::ControlObsVector (const ObsSpace_ & os) explicit
Definition at line 98 of file ControlObsVector.h.
     : obsvec_(), biasvec_() {
   Log::trace() << "ControlObsVector<MODEL>::ControlObsVector starting"
                << std::endl;
   util::Timer timer(classname(), "ControlObsVector");
   obsvec_.reset(new ObsVector_(os));
   if (os.config().has("ObsBias") ? os.config().getBool("ObsBias") : false)
     biasvec_.reset(new ObsVector_(os));
   Log::trace() << "ControlObsVector<MODEL>::ControlObsVector done" << std::endl;
 }
References oops::ControlObsVector< MODEL >::biasvec_, oops::ControlObsVector< MODEL >::classname(), oops::ObservationSpace< MODEL >::config(), and oops::ControlObsVector< MODEL >::obsvec_.
ControlObsVector() [2/3]
template<typename MODEL > oops::ControlObsVector< MODEL >::ControlObsVector (const ControlObsVector< MODEL > & other, const bool copy = true) explicit
Definition at line 112 of file ControlObsVector.h.
     : obsvec_(), biasvec_() {
   Log::trace() << "ControlObsVector<MODEL>::ControlObsVector starting"
                << std::endl;
   util::Timer timer(classname(), "ControlObsVector");
   obsvec_.reset(new ObsVector_(*other.obsvec_, copy));
   if (other.hasBias()) biasvec_.reset(new ObsVector_(*other.biasvec_, copy));
   Log::trace() << "ControlObsVector<MODEL>::ControlObsVector done" << std::endl;
 }
References oops::ControlObsVector< MODEL >::biasvec_, oops::ControlObsVector< MODEL >::classname(), oops::ControlObsVector< MODEL >::hasBias(), and oops::ControlObsVector< MODEL >::obsvec_.
ControlObsVector() [3/3]
template<typename MODEL > oops::ControlObsVector< MODEL >::ControlObsVector (ObsVector_ * obsvec, ObsVector_ * biasvec) explicit
Definition at line 126 of file ControlObsVector.h.
     : obsvec_(obsvec), biasvec_(biasvec) {
   Log::trace() << "ControlObsVector<MODEL>::ControlObsVector done" << std::endl;
 }
~ControlObsVector()
template<typename MODEL > oops::ControlObsVector< MODEL >::~ControlObsVector
Definition at line 133 of file ControlObsVector.h.
{
   Log::trace() << "ControlObsVector<MODEL>::~ControlObsVector starting"
                << std::endl;
   util::Timer timer(classname(), "~ControlObsVector");
   obsvec_.reset();
   biasvec_.reset();
   Log::trace() << "ControlObsVector<MODEL>::~ControlObsVector done"
                << std::endl;
 }
Member Function Documentation
axpy()
template<typename MODEL > void oops::ControlObsVector< MODEL >::axpy (const double & zz, const ControlObsVector< MODEL > & rhs)
Definition at line 234 of file ControlObsVector.h.
{
   Log::trace() << "ControlObsVector<MODEL>::axpy starting" << std::endl;
   util::Timer timer(classname(), "axpy");
   obsvec_->axpy(zz, *rhs.obsvec_);
   if (this->hasBias()) biasvec_->axpy(zz, *rhs.biasvec_);
   Log::trace() << "ControlObsVector<MODEL>::axpy done" << std::endl;
 }
References oops::ControlObsVector< MODEL >::biasvec_, and oops::ControlObsVector< MODEL >::obsvec_.
biasvector() [1/2]
template<typename MODEL > ObsVector_& oops::ControlObsVector< MODEL >::biasvector () inline
Definition at line 60 of file ControlObsVector.h.
{
     ASSERT(biasvec_);
     return *biasvec_;
   }
References oops::ControlObsVector< MODEL >::biasvec_.
Referenced by oops::ObsErrorCovariance< MODEL >::inverseMultiply_(), oops::ObsErrorCovariance< MODEL >::linearize(), oops::ObsErrorCovariance< MODEL >::multiply(), and oops::ObsErrorCovariance< MODEL >::multiplyWghtSqrt_().
biasvector() [2/2]
template<typename MODEL > const ObsVector_& oops::ControlObsVector< MODEL >::biasvector () const inline
Definition at line 64 of file ControlObsVector.h.
{
     ASSERT(biasvec_);
     return *biasvec_;
   }
References oops::ControlObsVector< MODEL >::biasvec_.
classname()
template<typename MODEL > static const std::string oops::ControlObsVector< MODEL >::classname () inline static
Definition at line 50 of file ControlObsVector.h.
 { return "oops::ControlObsVector"; }
Referenced by oops::ControlObsVector< MODEL >::ControlObsVector().
dot_product_with()
template<typename MODEL > double oops::ControlObsVector< MODEL >::dot_product_with (const ControlObsVector< MODEL > & other) const
Definition at line 268 of file ControlObsVector.h.
{
   Log::trace() << "ControlObsVector<MODEL>::dot_product starting" << std::endl;
   util::Timer timer(classname(), "dot_product");
   double zz = 0.0;
   zz += obsvec_->dot_product_with(*other.obsvec_);
   if (this->hasBias()) zz += biasvec_->dot_product_with(*other.biasvec_);
   Log::trace() << "ControlObsVector<MODEL>::dot_product done" << std::endl;
   return zz;
 }
References oops::ControlObsVector< MODEL >::biasvec_, and oops::ControlObsVector< MODEL >::obsvec_.
hasBias()
template<typename MODEL > bool oops::ControlObsVector< MODEL >::hasBias () const inline
Definition at line 68 of file ControlObsVector.h.
 { return biasvec_ ? true : false; }
References oops::ControlObsVector< MODEL >::biasvec_.
Referenced by oops::ControlObsVector< MODEL >::ControlObsVector().
invert()
template<typename MODEL > void oops::ControlObsVector< MODEL >::invert
Definition at line 246 of file ControlObsVector.h.
{
   Log::trace() << "ControlObsVector<MODEL>::invert starting" << std::endl;
   util::Timer timer(classname(), "invert");
   obsvec_->invert();
   if (this->hasBias()) biasvec_->invert();
   Log::trace() << "ControlObsVector<MODEL>::invert done" << std::endl;
 }
obsvector() [1/2]
template<typename MODEL > ObsVector_& oops::ControlObsVector< MODEL >::obsvector () inline
Interfacing.
Definition at line 58 of file ControlObsVector.h.
 { return *obsvec_; }
References oops::ControlObsVector< MODEL >::obsvec_.
Referenced by oops::ObsErrorCovariance< MODEL >::inverseMultiply_(), oops::ObsErrorCovariance< MODEL >::linearize(), oops::ObsErrorCovariance< MODEL >::multiply(), oops::ObsErrorCovariance< MODEL >::multiplyWghtSqrt_(), oops::ObsErrorCovariance< MODEL >::randomize(), and oops::ObsErrorCovariance< MODEL >::setupWeights().
obsvector() [2/2]
template<typename MODEL > const ObsVector_& oops::ControlObsVector< MODEL >::obsvector () const inline
Definition at line 59 of file ControlObsVector.h.
 { return *obsvec_; }
References oops::ControlObsVector< MODEL >::obsvec_.
operator*=() [1/2]
template<typename MODEL > ControlObsVector< MODEL > & oops::ControlObsVector< MODEL >::operator*= (const ControlObsVector< MODEL > & rhs)
Definition at line 197 of file ControlObsVector.h.
{
   Log::trace() << "ControlObsVector<MODEL>::operator*= starting" << std::endl;
   util::Timer timer(classname(), "operator*=");
   *obsvec_ *= *rhs.obsvec_;
   if (this->hasBias()) *biasvec_ *= *rhs.biasvec_;
   Log::trace() << "ControlObsVector<MODEL>::operator*= done" << std::endl;
   return *this;
 }
References oops::ControlObsVector< MODEL >::biasvec_, and oops::ControlObsVector< MODEL >::obsvec_.
operator*=() [2/2]
template<typename MODEL > ControlObsVector< MODEL > & oops::ControlObsVector< MODEL >::operator*= (const double & zz)
Definition at line 159 of file ControlObsVector.h.
{
   Log::trace() << "ControlObsVector<MODEL>::operator*= starting" << std::endl;
   util::Timer timer(classname(), "operator*=");
   *obsvec_ *= zz;
   if (this->hasBias()) *biasvec_ *= zz;
   Log::trace() << "ControlObsVector<MODEL>::operator*= done" << std::endl;
   return *this;
 }
operator+=()
template<typename MODEL > ControlObsVector< MODEL > & oops::ControlObsVector< MODEL >::operator+= (const ControlObsVector< MODEL > & rhs)
Definition at line 171 of file ControlObsVector.h.
{
   Log::trace() << "ControlObsVector<MODEL>::operator+= starting" << std::endl;
   util::Timer timer(classname(), "operator+=");
   *obsvec_ += *rhs.obsvec_;
   if (this->hasBias()) *biasvec_ += *rhs.biasvec_;
   Log::trace() << "ControlObsVector<MODEL>::operator+= done" << std::endl;
   return *this;
 }
References oops::ControlObsVector< MODEL >::biasvec_, and oops::ControlObsVector< MODEL >::obsvec_.
operator-=()
template<typename MODEL > ControlObsVector< MODEL > & oops::ControlObsVector< MODEL >::operator-= (const ControlObsVector< MODEL > & rhs)
Definition at line 184 of file ControlObsVector.h.
{
   Log::trace() << "ControlObsVector<MODEL>::operator-= starting" << std::endl;
   util::Timer timer(classname(), "operator-=");
   *obsvec_ -= *rhs.obsvec_;
   if (this->hasBias()) *biasvec_ -= *rhs.biasvec_;
   Log::trace() << "ControlObsVector<MODEL>::operator-= done" << std::endl;
   return *this;
 }
References oops::ControlObsVector< MODEL >::biasvec_, and oops::ControlObsVector< MODEL >::obsvec_.
operator/=()
template<typename MODEL > ControlObsVector< MODEL > & oops::ControlObsVector< MODEL >::operator/= (const ControlObsVector< MODEL > & rhs)
Definition at line 210 of file ControlObsVector.h.
{
   Log::trace() << "ControlObsVector<MODEL>::operator/= starting" << std::endl;
   util::Timer timer(classname(), "operator/=");
   *obsvec_ /= *rhs.obsvec_;
   if (this->hasBias()) *biasvec_ /= *rhs.biasvec_;
   Log::trace() << "ControlObsVector<MODEL>::operator/= done" << std::endl;
   return *this;
 }
References oops::ControlObsVector< MODEL >::biasvec_, and oops::ControlObsVector< MODEL >::obsvec_.
operator=()
template<typename MODEL > ControlObsVector< MODEL > & oops::ControlObsVector< MODEL >::operator= (const ControlObsVector< MODEL > & rhs)
Definition at line 146 of file ControlObsVector.h.
{
   Log::trace() << "ControlObsVector<MODEL>::operator= starting" << std::endl;
   util::Timer timer(classname(), "operator=");
   *obsvec_ = *rhs.obsvec_;
   if (this->hasBias()) *biasvec_ = *rhs.biasvec_;
   Log::trace() << "ControlObsVector<MODEL>::operator= done" << std::endl;
   return *this;
 }
References oops::ControlObsVector< MODEL >::biasvec_, and oops::ControlObsVector< MODEL >::obsvec_.
print()
template<typename MODEL > void oops::ControlObsVector< MODEL >::print (std::ostream & os) const private
Definition at line 294 of file ControlObsVector.h.
{
   Log::trace() << "ControlObsVector<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   os << *obsvec_;
   if (this->hasBias()) os << std::endl << *biasvec_;
   Log::trace() << "ControlObsVector<MODEL>::print done" << std::endl;
 }
random()
template<typename MODEL > void oops::ControlObsVector< MODEL >::random
Definition at line 257 of file ControlObsVector.h.
{
   Log::trace() << "ControlObsVector<MODEL>::random starting" << std::endl;
   util::Timer timer(classname(), "random");
   obsvec_->random();
   if (this->hasBias()) biasvec_->random();
   Log::trace() << "ControlObsVector<MODEL>::random done" << std::endl;
 }
read()
template<typename MODEL > void oops::ControlObsVector< MODEL >::read (const eckit::Configuration & conf)
Definition at line 305 of file ControlObsVector.h.
{
   Log::trace() << "ControlObsVector<MODEL>::read starting" << std::endl;
   util::Timer timer(classname(), "read");
   std::string obsname = conf.getString("obsvalue");
   obsvec_->read(obsname);
   if (this->hasBias()) {
     if (conf.has("biasvalue")) {
       std::string biasname = conf.getString("biasvalue");
       biasvec_->read(biasname);
     } else {
       biasvec_->zero();
     }
   }
   Log::trace() << "ControlObsVector<MODEL>::read done" << std::endl;
 }
rms()
template<typename MODEL > double oops::ControlObsVector< MODEL >::rms
Definition at line 282 of file ControlObsVector.h.
{
   Log::trace() << "ControlObsVector<MODEL>::rms starting" << std::endl;
   util::Timer timer(classname(), "rms");
   const double zz = 0.0;
   zz += obsvec_->rms();
   Log::trace() << "ControlObsVector<MODEL>::rms done" << std::endl;
   return zz;
 }
save()
template<typename MODEL > void oops::ControlObsVector< MODEL >::save (const eckit::Configuration & conf) const
Definition at line 325 of file ControlObsVector.h.
{
   Log::trace() << "ControlObsVector<MODEL>::save starting";
   util::Timer timer(classname(), "save");
   std::string obsname = conf.getString("obsvalue");
   obsvec_->save(obsname);
   if (this->hasBias()) {
     if (conf.has("biasvalue")) {
       std::string biasname = conf.getString("biasvalue");
       biasvec_->save(biasname);
     }
   }
   Log::trace() << "ControlObsVector<MODEL>::save done" << std::endl;
 }
size()
template<typename MODEL > unsigned int oops::ControlObsVector< MODEL >::size () const inline
Definition at line 84 of file ControlObsVector.h.
 { return obsvec_->size(); }
References oops::ControlObsVector< MODEL >::obsvec_.
zero()
template<typename MODEL > void oops::ControlObsVector< MODEL >::zero
Definition at line 223 of file ControlObsVector.h.
{
   Log::trace() << "ControlObsVector<MODEL>::zero starting" << std::endl;
   util::Timer timer(classname(), "zero");
   obsvec_->zero();
   if (this->hasBias()) biasvec_->zero();
   Log::trace() << "ControlObsVector<MODEL>::zero done" << std::endl;
 }
Member Data Documentation
biasvec_
template<typename MODEL > std::unique_ptr<ObsVector_> oops::ControlObsVector< MODEL >::biasvec_ private
Definition at line 93 of file ControlObsVector.h.
Referenced by oops::ControlObsVector< MODEL >::axpy(), oops::ControlObsVector< MODEL >::biasvector(), oops::ControlObsVector< MODEL >::ControlObsVector(), oops::ControlObsVector< MODEL >::dot_product_with(), oops::ControlObsVector< MODEL >::hasBias(), oops::ControlObsVector< MODEL >::operator*=(), oops::ControlObsVector< MODEL >::operator+=(), oops::ControlObsVector< MODEL >::operator-=(), oops::ControlObsVector< MODEL >::operator/=(), and oops::ControlObsVector< MODEL >::operator=().
obsvec_
template<typename MODEL > std::unique_ptr<ObsVector_> oops::ControlObsVector< MODEL >::obsvec_ private
Definition at line 92 of file ControlObsVector.h.
Referenced by oops::ControlObsVector< MODEL >::axpy(), oops::ControlObsVector< MODEL >::ControlObsVector(), oops::ControlObsVector< MODEL >::dot_product_with(), oops::ControlObsVector< MODEL >::obsvector(), oops::ControlObsVector< MODEL >::operator*=(), oops::ControlObsVector< MODEL >::operator+=(), oops::ControlObsVector< MODEL >::operator-=(), oops::ControlObsVector< MODEL >::operator/=(), oops::ControlObsVector< MODEL >::operator=(), and oops::ControlObsVector< MODEL >::size().
The documentation for this class was generated from the following file:
src/oops/assimilation/ControlObsVector.h