OOPS Documentation: oops::Application Class Reference
oops::Application Class Reference abstract
#include <Application.h>
Public Member Functions
Application ()
virtual ~Application ()
virtual int execute (const eckit::Configuration &) const =0
Private Member Functions
virtual std::string appname () const =0
virtual void print (std::ostream &os) const
Detailed Description
Definition at line 27 of file Application.h.
Constructor & Destructor Documentation
Application()
oops::Application::Application () inline
Definition at line 29 of file Application.h.
 {}
~Application()
virtual oops::Application::~Application () inline virtual
Definition at line 30 of file Application.h.
 {}
Member Function Documentation
appname()
virtual std::string oops::Application::appname () const private pure virtual
Implemented in oops::MakeObs< MODEL >, oops::Variational< MODEL >, oops::HofX< MODEL >, oops::GenEnsPertB< MODEL >, oops::ExternalDFI< MODEL >, oops::DualConfigForecast< MODEL >, oops::Forecast< MODEL >, oops::DualResForecast< MODEL >, oops::EnsForecast< MODEL >, oops::ModelAuxNN< MODEL >, oops::AssimEnsemble< MODEL >, and oops::Test.
Referenced by print().
execute()
virtual int oops::Application::execute (const eckit::Configuration &) const pure virtual
Implemented in oops::Variational< MODEL >, oops::MakeObs< MODEL >, oops::HofX< MODEL >, oops::DualConfigForecast< MODEL >, oops::GenEnsPertB< MODEL >, oops::ExternalDFI< MODEL >, oops::Forecast< MODEL >, oops::ModelAuxNN< MODEL >, oops::DualResForecast< MODEL >, oops::EnsForecast< MODEL >, oops::AssimEnsemble< MODEL >, and oops::Test.
Referenced by oops::Run::execute().
print()
virtual void oops::Application::print (std::ostream & os) const inline private virtual
Definition at line 35 of file Application.h.
 { os << appname(); }
References appname().
The documentation for this class was generated from the following file:
src/oops/runs/Application.h