OOPS Documentation: oops::PostBase< FLDS > Class Template Reference
oops::PostBase< FLDS > Class Template Reference
Handles post-processing of model fields.
#include <PostBase.h>
Public Member Functions
PostBase ()
Constructors.
PostBase (const util::Duration &freq)
PostBase (const eckit::Configuration &conf)
PostBase (const util::DateTime &start, const eckit::Configuration &conf)
PostBase (const util::DateTime &start, const util::DateTime &finish, const util::Duration &freq=util::Duration(0))
virtual ~PostBase ()
Destructor.
void initialize (const FLDS &xx, const util::DateTime &end, const util::Duration &tstep)
Wraps doInitialize method; doProcessing is called if requested.
void initialize (FLDS &xx, const util::DateTime &end, const util::Duration &tstep)
void process (const FLDS &xx)
Wraps doProcessing method; doProcessing is is called when requested.
void process (FLDS &xx)
void finalize (const FLDS &xx)
Wraps doFinalize method.
virtual void doProcessing (const FLDS &)
Actual processing.
virtual void doProcessing (FLDS &fld)
virtual void doInitialize (const FLDS &, const util::DateTime &, const util::Duration &)
Actual initialization.
virtual void doInitialize (FLDS &fld, const util::DateTime &t, const util::Duration &d)
virtual void doFinalize (const FLDS &)
Actual finalization.
Private Attributes
PostTimer timer_
Detailed Description
template<typename FLDS>
class oops::PostBase< FLDS >
Handles post-processing of model fields.
PostBase is the base class for all state post processors, it is mostly used so that PostProcessor can hold a vector of such processors.
By default processing is performed on every call.
PostBase is templated on FLDS; FLDS would typically be either State or Increment.
Post-processing is organized in three stages/methods: initialize (called prior to time-stepping), process (called during the forecast at each time step) and finalize (called once the time-stepping is finished).
Methods initialize, process and finalize wrap around virtual methods (implemented by PostBase children classes) doInitialize, doProcessing and doFinalize.
PostBase class contains a PostTimer object. PostTimer class controls the frequency of post-processing.
PostBase is the base class of the following classes (refer to their documentation for more information):
Observer
StateInfo
StateSaver
StateWriter
TrajectorySaver
WeightedDiff
WeightedMean
JqTerm
Definition at line 71 of file PostBase.h.
Constructor & Destructor Documentation
PostBase() [1/5]
template<typename FLDS > oops::PostBase< FLDS >::PostBase () inline
Constructors.
Definition at line 74 of file PostBase.h.
 : timer_() {}
PostBase() [2/5]
template<typename FLDS > oops::PostBase< FLDS >::PostBase (const util::Duration & freq) inline explicit
Definition at line 75 of file PostBase.h.
 : timer_(freq) {}
PostBase() [3/5]
template<typename FLDS > oops::PostBase< FLDS >::PostBase (const eckit::Configuration & conf) inline explicit
Definition at line 76 of file PostBase.h.
 : timer_(conf) {}
PostBase() [4/5]
template<typename FLDS > oops::PostBase< FLDS >::PostBase (const util::DateTime & start, const eckit::Configuration & conf) inline
Definition at line 77 of file PostBase.h.
       : timer_(start, conf) {}
PostBase() [5/5]
template<typename FLDS > oops::PostBase< FLDS >::PostBase (const util::DateTime & start, const util::DateTime & finish, const util::Duration & freq = util::Duration(0)) inline
Definition at line 79 of file PostBase.h.
       : timer_(start, finish, freq) {}
~PostBase()
template<typename FLDS > virtual oops::PostBase< FLDS >::~PostBase () inline virtual
Destructor.
Definition at line 83 of file PostBase.h.
 {}
Member Function Documentation
doFinalize()
template<typename FLDS > virtual void oops::PostBase< FLDS >::doFinalize (const FLDS &) inline virtual
Actual finalization.
Reimplemented in oops::TrajectorySaverFP< MODEL >, oops::TrajectorySaver< MODEL >, oops::AdvectorHandler< MODEL >, oops::TrajectorySaverMF< MODEL >, and oops::Observer< MODEL, STATE >.
Definition at line 123 of file PostBase.h.
 {}
Referenced by oops::PostBase< State< MODEL > >::finalize().
doInitialize() [1/2]
template<typename FLDS > virtual void oops::PostBase< FLDS >::doInitialize (const FLDS & , const util::DateTime & , const util::Duration &) inline virtual
Actual initialization.
Reimplemented in oops::TrajectorySaverFP< MODEL >, oops::TrajectorySaver< MODEL >, oops::AdvectorHandler< MODEL >, oops::DFIProcessor< MODEL >, oops::TrajectorySaverMF< MODEL >, oops::Observer< MODEL, STATE >, oops::PostProcessorModel< MODEL, STATE >, oops::WeightedMean< MODEL, FLDS >, and oops::WeightedDiff< MODEL, INCR, FLDS >.
Definition at line 116 of file PostBase.h.
                                                   {}
Referenced by oops::PostBase< State< MODEL > >::doInitialize(), and oops::PostBase< State< MODEL > >::initialize().
doInitialize() [2/2]
template<typename FLDS > virtual void oops::PostBase< FLDS >::doInitialize (FLDS & fld, const util::DateTime & t, const util::Duration & d) inline virtual
Reimplemented in oops::ObserverIAU< MODEL, STATE >.
Definition at line 118 of file PostBase.h.
{
     doInitialize((const FLDS &)fld, t, d);
   }
doProcessing() [1/2]
template<typename FLDS > virtual void oops::PostBase< FLDS >::doProcessing (const FLDS &) inline virtual
Actual processing.
Reimplemented in oops::TrajectorySaverFP< MODEL >, oops::TrajectorySaver< MODEL >, oops::AdvectorHandler< MODEL >, oops::DFIProcessor< MODEL >, oops::TrajectorySaverMF< MODEL >, oops::Observer< MODEL, STATE >, oops::PostProcessorModel< MODEL, STATE >, oops::StateInfo< FLDS >, oops::StateSaver< FLDS >, oops::StateWriter< FLDS >, oops::WeightedMean< MODEL, FLDS >, and oops::WeightedDiff< MODEL, INCR, FLDS >.
Definition at line 113 of file PostBase.h.
 {}
Referenced by oops::PostBase< State< MODEL > >::initialize(), and oops::PostBase< State< MODEL > >::process().
doProcessing() [2/2]
template<typename FLDS > virtual void oops::PostBase< FLDS >::doProcessing (FLDS & fld) inline virtual
Reimplemented in oops::ObserverIAU< MODEL, STATE >.
Definition at line 114 of file PostBase.h.
 { doProcessing((const FLDS &)fld); }
Referenced by oops::PostBase< State< MODEL > >::doProcessing().
finalize()
template<typename FLDS > void oops::PostBase< FLDS >::finalize (const FLDS & xx) inline
Wraps doFinalize method.
Definition at line 110 of file PostBase.h.
 { this->doFinalize(xx); }
initialize() [1/2]
template<typename FLDS > void oops::PostBase< FLDS >::initialize (const FLDS & xx, const util::DateTime & end, const util::Duration & tstep) inline
Wraps doInitialize method; doProcessing is called if requested.
Definition at line 86 of file PostBase.h.
{
     timer_.initialize(xx.validTime(), end, tstep);
     this->doInitialize(xx, end, tstep);
     if (timer_.itIsTime(xx.validTime())) this->doProcessing(xx);
   }
initialize() [2/2]
template<typename FLDS > void oops::PostBase< FLDS >::initialize (FLDS & xx, const util::DateTime & end, const util::Duration & tstep) inline
Definition at line 93 of file PostBase.h.
{
     timer_.initialize(xx.validTime(), end, tstep);
     this->doInitialize(xx, end, tstep);
     if (timer_.itIsTime(xx.validTime())) this->doProcessing(xx);
   }
process() [1/2]
template<typename FLDS > void oops::PostBase< FLDS >::process (const FLDS & xx) inline
Wraps doProcessing method; doProcessing is is called when requested.
Definition at line 101 of file PostBase.h.
{
     if (timer_.itIsTime(xx.validTime())) this->doProcessing(xx);
   }
process() [2/2]
template<typename FLDS > void oops::PostBase< FLDS >::process (FLDS & xx) inline
Definition at line 105 of file PostBase.h.
{
     if (timer_.itIsTime(xx.validTime())) this->doProcessing(xx);
   }
Member Data Documentation
timer_
template<typename FLDS > PostTimer oops::PostBase< FLDS >::timer_ private
Definition at line 126 of file PostBase.h.
Referenced by oops::PostBase< State< MODEL > >::initialize(), and oops::PostBase< State< MODEL > >::process().
The documentation for this class was generated from the following file:
src/oops/base/PostBase.h