OOPS Documentation: oops::ObsVector< MODEL > Class Template Reference
oops::ObsVector< MODEL > Class Template Reference
Encapsulates the observation vector.
#include <ObservationSpace.h>
Public Member Functions
ObsVector (const ObservationSpace< MODEL > &)
Constructor.
ObsVector (const ObsVector &, const bool copy=true)
Copy constructor.
ObsVector (ObsVector_ *)
Copy constructor.
~ObsVector ()
Destructor.
const ObsVector_ & obsvector () const
Return a constant reference to the model-specific observation vector.
ObsVector_ & obsvector ()
Return a reference to the model-specific observation vector.
ObsVector & operator= (const ObsVector &)
\(\tilde{y}_1 = \tilde{y}_2 \)
ObsVector & operator*= (const double &)
\(\tilde{y}_1 = c * \tilde{y}_1 \)
ObsVector & operator+= (const ObsVector &)
\(\tilde{y}_1 = \tilde{y}_1 + \tilde{y}_2 \)
ObsVector & operator-= (const ObsVector &)
\(\tilde{y}_1 = \tilde{y}_1 - \tilde{y}_2 \)
ObsVector & operator*= (const ObsVector &)
\(\tilde{y}_1 = \tilde{y}_1 *. \tilde{y}_2 \)
ObsVector & operator/= (const ObsVector &)
\(\tilde{y}_1 = \tilde{y}_1 /. \tilde{y}_2 \)
void zero ()
\(\tilde{y} = 0 \)
void axpy (const double &, const ObsVector &)
\(\tilde{y}_1 = \tilde{y}_1 + c * \tilde{y}_2 \)
void invert ()
\(\tilde{y} = 1 ./ \tilde{y} \)
void random ()
Initialize random observation vector.
double dot_product_with (const ObsVector &) const
\(<\tilde{y},\tilde{y}> = \tilde{y}^T \tilde{y} \)
double rms () const
Compute RMS.
unsigned int size () const
Return the size of the observation vector.
void read (const std::string &)
Read observation vector.
void save (const std::string &) const
Write observation vector.
Static Public Member Functions
static const std::string classname ()
Private Types
using ObsVector_ = typename MODEL::ObsVector
Private Member Functions
void print (std::ostream &) const
Private Attributes
std::unique_ptr< ObsVector_ > data_
Pointer to the model specific object.
Detailed Description
template<typename MODEL>
class oops::ObsVector< MODEL >
Encapsulates the observation vector.
ControlObsVector contains two ObsVector objects to store both observations and biases. Refer to the documentation of ControlObsVector, Observations, Departures and CostJo.
Definition at line 35 of file ObservationSpace.h.
Member Typedef Documentation
ObsVector_
template<typename MODEL > using oops::ObsVector< MODEL >::ObsVector_ = typename MODEL::ObsVector private
Definition at line 48 of file ObsVector.h.
Constructor & Destructor Documentation
ObsVector() [1/3]
template<typename MODEL > oops::ObsVector< MODEL >::ObsVector (const ObservationSpace< MODEL > & os) explicit
Constructor.
Definition at line 111 of file ObsVector.h.
                                                              : data_() {
   Log::trace() << "ObsVector<MODEL>::ObsVector starting" << std::endl;
   util::Timer timer(classname(), "ObsVector");
   data_.reset(new ObsVector_(os.observationspace()));
   Log::trace() << "ObsVector<MODEL>::ObsVector done" << std::endl;
 }
References oops::ObsVector< MODEL >::classname(), oops::ObsVector< MODEL >::data_, and oops::ObservationSpace< MODEL >::observationspace().
ObsVector() [2/3]
template<typename MODEL > oops::ObsVector< MODEL >::ObsVector (const ObsVector< MODEL > & other, const bool copy = true) explicit
Copy constructor.
Definition at line 119 of file ObsVector.h.
                                                                    : data_() {
   Log::trace() << "ObsVector<MODEL>::ObsVector starting" << std::endl;
   util::Timer timer(classname(), "ObsVector");
   data_.reset(new ObsVector_(*other.data_, copy));
   Log::trace() << "ObsVector<MODEL>::ObsVector done" << std::endl;
 }
References oops::ObsVector< MODEL >::classname(), and oops::ObsVector< MODEL >::data_.
ObsVector() [3/3]
template<typename MODEL > oops::ObsVector< MODEL >::ObsVector (ObsVector_ * data) explicit
Copy constructor.
Definition at line 127 of file ObsVector.h.
                                             : data_(data) {
   Log::trace() << "ObsVector<MODEL>::ObsVector done" << std::endl;
 }
~ObsVector()
template<typename MODEL > oops::ObsVector< MODEL >::~ObsVector
Destructor.
Definition at line 132 of file ObsVector.h.
{
   Log::trace() << "ObsVector<MODEL>::~ObsVector starting" << std::endl;
   util::Timer timer(classname(), "~ObsVector");
   data_.reset();
   Log::trace() << "ObsVector<MODEL>::~ObsVector done" << std::endl;
 }
Member Function Documentation
axpy()
template<typename MODEL > void oops::ObsVector< MODEL >::axpy (const double & zz, const ObsVector< MODEL > & rhs)
\(\tilde{y}_1 = \tilde{y}_1 + c * \tilde{y}_2 \)
Definition at line 202 of file ObsVector.h.
{
   Log::trace() << "ObsVector<MODEL>::axpy starting" << std::endl;
   util::Timer timer(classname(), "axpy");
   data_->axpy(zz, *rhs.data_);
   Log::trace() << "ObsVector<MODEL>::axpy done" << std::endl;
 }
classname()
template<typename MODEL > static const std::string oops::ObsVector< MODEL >::classname () inline static
Definition at line 51 of file ObsVector.h.
 { return "oops::ObsVector"; }
Referenced by oops::ObsVector< MODEL >::ObsVector().
dot_product_with()
template<typename MODEL > double oops::ObsVector< MODEL >::dot_product_with (const ObsVector< MODEL > & other) const
\(<\tilde{y},\tilde{y}> = \tilde{y}^T \tilde{y} \)
Definition at line 226 of file ObsVector.h.
{
   Log::trace() << "ObsVector<MODEL>::dot_product starting" << std::endl;
   util::Timer timer(classname(), "dot_product");
   const double zz = data_->dot_product_with(*other.data_);
   Log::trace() << "ObsVector<MODEL>::dot_product done" << std::endl;
   return zz;
 }
invert()
template<typename MODEL > void oops::ObsVector< MODEL >::invert
\(\tilde{y} = 1 ./ \tilde{y} \)
Definition at line 210 of file ObsVector.h.
{
   Log::trace() << "ObsVector<MODEL>::invert starting" << std::endl;
   util::Timer timer(classname(), "invert");
   data_->invert();
   Log::trace() << "ObsVector<MODEL>::invert done" << std::endl;
 }
obsvector() [1/2]
template<typename MODEL > ObsVector_& oops::ObsVector< MODEL >::obsvector () inline
Return a reference to the model-specific observation vector.
Definition at line 66 of file ObsVector.h.
 { return *data_; }
References oops::ObsVector< MODEL >::data_.
obsvector() [2/2]
template<typename MODEL > const ObsVector_& oops::ObsVector< MODEL >::obsvector () const inline
Return a constant reference to the model-specific observation vector.
Definition at line 64 of file ObsVector.h.
 { return *data_; }
References oops::ObsVector< MODEL >::data_.
Referenced by oops::ObsErrorCovariance< MODEL >::inverseMultiply_(), oops::ObsErrorCovariance< MODEL >::linearize(), oops::ObsErrorCovariance< MODEL >::multiply(), oops::ObsErrorCovariance< MODEL >::multiplyWghtSqrt_(), oops::ObsOperator< MODEL >::obsBiasEquiv(), oops::LinearObsOperator< MODEL >::obsBiasEquivAD(), oops::LinearObsOperator< MODEL >::obsBiasEquivTL(), oops::ObsOperator< MODEL >::obsEquiv(), oops::LinearObsOperator< MODEL >::obsEquivAD(), oops::LinearObsOperator< MODEL >::obsEquivTL(), oops::ObservationSpace< MODEL >::printJo(), oops::ObsErrorCovariance< MODEL >::randomize(), oops::ObservationSpace< MODEL >::screenObservations(), and oops::ObsErrorCovariance< MODEL >::setupWeights().
operator*=() [1/2]
template<typename MODEL > ObsVector< MODEL > & oops::ObsVector< MODEL >::operator*= (const double & zz)
\(\tilde{y}_1 = c * \tilde{y}_1 \)
Definition at line 149 of file ObsVector.h.
{
   Log::trace() << "ObsVector<MODEL>::operator*= starting" << std::endl;
   util::Timer timer(classname(), "operator*=");
   *data_ *= zz;
   Log::trace() << "ObsVector<MODEL>::operator*= done" << std::endl;
   return *this;
 }
operator*=() [2/2]
template<typename MODEL > ObsVector< MODEL > & oops::ObsVector< MODEL >::operator*= (const ObsVector< MODEL > & rhs)
\(\tilde{y}_1 = \tilde{y}_1 *. \tilde{y}_2 \)
Definition at line 176 of file ObsVector.h.
{
   Log::trace() << "ObsVector<MODEL>::operator*= starting" << std::endl;
   util::Timer timer(classname(), "operator*=");
   *data_ *= *rhs.data_;
   Log::trace() << "ObsVector<MODEL>::operator*= done" << std::endl;
   return *this;
 }
operator+=()
template<typename MODEL > ObsVector< MODEL > & oops::ObsVector< MODEL >::operator+= (const ObsVector< MODEL > & rhs)
\(\tilde{y}_1 = \tilde{y}_1 + \tilde{y}_2 \)
Definition at line 158 of file ObsVector.h.
{
   Log::trace() << "ObsVector<MODEL>::operator+= starting" << std::endl;
   util::Timer timer(classname(), "operator+=");
   *data_ += *rhs.data_;
   Log::trace() << "ObsVector<MODEL>::operator+= done" << std::endl;
   return *this;
 }
operator-=()
template<typename MODEL > ObsVector< MODEL > & oops::ObsVector< MODEL >::operator-= (const ObsVector< MODEL > & rhs)
\(\tilde{y}_1 = \tilde{y}_1 - \tilde{y}_2 \)
Definition at line 167 of file ObsVector.h.
{
   Log::trace() << "ObsVector<MODEL>::operator-= starting" << std::endl;
   util::Timer timer(classname(), "operator-=");
   *data_ -= *rhs.data_;
   Log::trace() << "ObsVector<MODEL>::operator-= done" << std::endl;
   return *this;
 }
operator/=()
template<typename MODEL > ObsVector< MODEL > & oops::ObsVector< MODEL >::operator/= (const ObsVector< MODEL > & rhs)
\(\tilde{y}_1 = \tilde{y}_1 /. \tilde{y}_2 \)
Definition at line 185 of file ObsVector.h.
{
   Log::trace() << "ObsVector<MODEL>::operator/= starting" << std::endl;
   util::Timer timer(classname(), "operator/=");
   *data_ /= *rhs.data_;
   Log::trace() << "ObsVector<MODEL>::operator/= done" << std::endl;
   return *this;
 }
operator=()
template<typename MODEL > ObsVector< MODEL > & oops::ObsVector< MODEL >::operator= (const ObsVector< MODEL > & rhs)
\(\tilde{y}_1 = \tilde{y}_2 \)
Definition at line 140 of file ObsVector.h.
{
   Log::trace() << "ObsVector<MODEL>::operator= starting" << std::endl;
   util::Timer timer(classname(), "operator=");
   *data_ = *rhs.data_;
   Log::trace() << "ObsVector<MODEL>::operator= done" << std::endl;
   return *this;
 }
print()
template<typename MODEL > void oops::ObsVector< MODEL >::print (std::ostream & os) const private
Definition at line 244 of file ObsVector.h.
{
   Log::trace() << "ObsVector<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   os << *data_;
   Log::trace() << "ObsVector<MODEL>::print done" << std::endl;
 }
random()
template<typename MODEL > void oops::ObsVector< MODEL >::random
Initialize random observation vector.
Definition at line 218 of file ObsVector.h.
{
   Log::trace() << "ObsVector<MODEL>::random starting" << std::endl;
   util::Timer timer(classname(), "random");
   data_->random();
   Log::trace() << "ObsVector<MODEL>::random done" << std::endl;
 }
read()
template<typename MODEL > void oops::ObsVector< MODEL >::read (const std::string & name)
Read observation vector.
Definition at line 252 of file ObsVector.h.
{
   Log::trace() << "ObsVector<MODEL>::read starting" << std::endl;
   util::Timer timer(classname(), "read");
   data_->read(name);
   Log::trace() << "ObsVector<MODEL>::read done" << std::endl;
 }
rms()
template<typename MODEL > double oops::ObsVector< MODEL >::rms
Compute RMS.
Definition at line 235 of file ObsVector.h.
{
   Log::trace() << "ObsVector<MODEL>::rms starting" << std::endl;
   util::Timer timer(classname(), "rms");
   const double zz = data_->rms();
   Log::trace() << "ObsVector<MODEL>::rms done" << std::endl;
   return zz;
 }
save()
template<typename MODEL > void oops::ObsVector< MODEL >::save (const std::string & name) const
Write observation vector.
Definition at line 260 of file ObsVector.h.
{
   Log::trace() << "ObsVector<MODEL>::save starting";
   util::Timer timer(classname(), "save");
   data_->save(name);
   Log::trace() << "ObsVector<MODEL>::save done" << std::endl;
 }
size()
template<typename MODEL > unsigned int oops::ObsVector< MODEL >::size () const inline
Return the size of the observation vector.
Definition at line 95 of file ObsVector.h.
 { return data_->size(); }
References oops::ObsVector< MODEL >::data_.
zero()
template<typename MODEL > void oops::ObsVector< MODEL >::zero
\(\tilde{y} = 0 \)
Definition at line 194 of file ObsVector.h.
{
   Log::trace() << "ObsVector<MODEL>::zero starting" << std::endl;
   util::Timer timer(classname(), "zero");
   data_->zero();
   Log::trace() << "ObsVector<MODEL>::zero done" << std::endl;
 }
Member Data Documentation
data_
template<typename MODEL > std::unique_ptr<ObsVector_> oops::ObsVector< MODEL >::data_ private
Pointer to the model specific object.
Definition at line 106 of file ObsVector.h.
Referenced by oops::ObsVector< MODEL >::ObsVector(), oops::ObsVector< MODEL >::obsvector(), and oops::ObsVector< MODEL >::size().
The documentation for this class was generated from the following files:
src/oops/interface/ObservationSpace.h
src/oops/interface/ObsVector.h