OOPS Documentation: oops::JbMatrix< MODEL > Class Template Reference
oops::JbMatrix< MODEL > Class Template Reference
The \(Jb \) matrix.
#include <JbMatrix.h>
Public Member Functions
JbMatrix (const CostFct_ &j, bool adjointTest=false)
~JbMatrix ()
void multiply (const CtrlVec_ &v, CtrlVec_ &jbv) const
Private Types
using CtrlInc_ = ControlIncrement< MODEL >
using CtrlVec_ = ControlVector< MODEL >
using CostFct_ = CostFunction< MODEL >
using ObsAuxIncrements_ = ObsAuxIncrements< MODEL >
Private Attributes
CostFct_ const & j_
const bool adjointTest_
ObsAuxIncrements_ dxObsAux_
ObsAuxIncrements_ invBdxObsAux_
Detailed Description
template<typename MODEL>
class oops::JbMatrix< MODEL >
The \(Jb \) matrix.
The solvers represent matrices as objects that implement a "multiply" method. This class defines objects that apply the \(Jb \) matrix for a general case where U' is not equal to U, where B = UU^t
Definition at line 36 of file JbMatrix.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::JbMatrix< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 39 of file JbMatrix.h.
CtrlInc_
template<typename MODEL > using oops::JbMatrix< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 37 of file JbMatrix.h.
CtrlVec_
template<typename MODEL > using oops::JbMatrix< MODEL >::CtrlVec_ = ControlVector<MODEL> private
Definition at line 38 of file JbMatrix.h.
ObsAuxIncrements_
template<typename MODEL > using oops::JbMatrix< MODEL >::ObsAuxIncrements_ = ObsAuxIncrements<MODEL> private
Definition at line 40 of file JbMatrix.h.
Constructor & Destructor Documentation
JbMatrix()
template<typename MODEL > oops::JbMatrix< MODEL >::JbMatrix (const CostFct_ & j, bool adjointTest = false) inline explicit
Definition at line 43 of file JbMatrix.h.
       : j_(j),
         adjointTest_(adjointTest),
         dxObsAux_(j.jb().getFirstGuessIncrement().obsVar(), false),
         invBdxObsAux_(j.jb().getFirstGuessIncrement().obsVar(), false) {}
~JbMatrix()
template<typename MODEL > oops::JbMatrix< MODEL >::~JbMatrix () inline
Definition at line 48 of file JbMatrix.h.
 {}
Member Function Documentation
multiply()
template<typename MODEL > void oops::JbMatrix< MODEL >::multiply (const CtrlVec_ & v, CtrlVec_ & jbv) const inline
JbMatrix = | I | | U'^T B^-1 U' | where B = UU^T and U' does not have to be equal to U
Definition at line 50 of file JbMatrix.h.
{
     // State part
     jbv.state() = v.state();
     // Mod Aux part
     jbv.modVar() = v.modVar();
     // Obs Aux part
     dxObsAux_.zero();
     invBdxObsAux_.zero();
     // U'v
     j_.jb().jbObsBias().multiplySqrt(v.obsVar(), dxObsAux_);
     // B^-1 U' v
     j_.jb().jbObsBias().inverseMultiply(dxObsAux_, invBdxObsAux_);
     // U'^T B^-1 U' v
     j_.jb().jbObsBias().multiplySqrtTrans(invBdxObsAux_, jbv.obsVar());
     if (adjointTest_) {
       // Adjoint Test
       // U'^t U'v
       double fwd = dot_product(dxObsAux_, invBdxObsAux_);
       double bwd = dot_product(v.obsVar(), jbv.obsVar());
       Log::info() << "ObsBiasCovariance Adjoint Test: " << std::endl
                   << util::PrintAdjTest(fwd, bwd, "B_bias") << std::endl;
     }
   }
References oops::JbMatrix< MODEL >::adjointTest_, dot_product(), oops::JbMatrix< MODEL >::dxObsAux_, oops::JbMatrix< MODEL >::invBdxObsAux_, oops::ObsAuxCovariances< MODEL >::inverseMultiply(), oops::JbMatrix< MODEL >::j_, oops::CostFunction< MODEL >::jb(), oops::CostJbTotal< MODEL >::jbObsBias(), oops::ControlVector< MODEL >::modVar(), oops::ObsAuxCovariances< MODEL >::multiplySqrt(), oops::ObsAuxCovariances< MODEL >::multiplySqrtTrans(), oops::ControlVector< MODEL >::obsVar(), oops::ControlVector< MODEL >::state(), and oops::ObsAuxIncrements< MODEL >::zero().
Referenced by oops::SQRTMinimizer< MODEL >::doMinimize(), oops::SQRTBPFOMMinimizer< MODEL >::solve(), oops::SQRTBPLanczosMinimizer< MODEL >::solve(), oops::SQRTPCGMinimizer< MODEL >::solve(), oops::SQRTBPCGMinimizer< MODEL >::solve(), and oops::SQRTPLanczosMinimizer< MODEL >::solve().
Member Data Documentation
adjointTest_
template<typename MODEL > const bool oops::JbMatrix< MODEL >::adjointTest_ private
Definition at line 87 of file JbMatrix.h.
Referenced by oops::JbMatrix< MODEL >::multiply().
dxObsAux_
template<typename MODEL > ObsAuxIncrements_ oops::JbMatrix< MODEL >::dxObsAux_ mutable private
Definition at line 89 of file JbMatrix.h.
Referenced by oops::JbMatrix< MODEL >::multiply().
invBdxObsAux_
template<typename MODEL > ObsAuxIncrements_ oops::JbMatrix< MODEL >::invBdxObsAux_ mutable private
Definition at line 90 of file JbMatrix.h.
Referenced by oops::JbMatrix< MODEL >::multiply().
j_
template<typename MODEL > CostFct_ const& oops::JbMatrix< MODEL >::j_ private
Definition at line 86 of file JbMatrix.h.
Referenced by oops::JbMatrix< MODEL >::multiply().
The documentation for this class was generated from the following file:
src/oops/assimilation/JbMatrix.h