OOPS Documentation: oops::PostTimer Class Reference
oops::PostTimer Class Reference
Handles timing of post-processing and similar actions.
#include <PostTimer.h>
Public Member Functions
PostTimer ()
PostTimer (const util::Duration &)
PostTimer (const eckit::Configuration &)
PostTimer (const util::DateTime &, const eckit::Configuration &)
PostTimer (const util::DateTime &, const util::DateTime &, const util::Duration &)
~PostTimer ()
void initialize (const util::DateTime &, const util::DateTime &, const util::Duration &)
bool itIsTime (const util::DateTime &)
Private Attributes
const eckit::LocalConfiguration conf_
util::Duration freq_
util::DateTime bgn_
util::DateTime end_
std::unique_ptr< util::DateTime > start_
std::unique_ptr< util::DateTime > finish_
std::vector< util::DateTime > pptimes_
Detailed Description
Handles timing of post-processing and similar actions.
By default processing is performed on every call.
Definition at line 32 of file PostTimer.h.
Constructor & Destructor Documentation
PostTimer() [1/5]
oops::PostTimer::PostTimer ()
Definition at line 26 of file PostTimer.cc.
     : conf_(),
       freq_(0),
       bgn_(),
       end_(),
       start_(nullptr),
       finish_(nullptr),
       pptimes_() {}
PostTimer() [2/5]
oops::PostTimer::PostTimer (const util::Duration & freq) explicit
Definition at line 35 of file PostTimer.cc.
     : conf_(),
       freq_(freq),
       bgn_(),
       end_(),
       start_(nullptr),
       finish_(nullptr),
       pptimes_() {}
PostTimer() [3/5]
oops::PostTimer::PostTimer (const eckit::Configuration & conf) explicit
Definition at line 44 of file PostTimer.cc.
     : conf_(conf),
       freq_(0),
       bgn_(),
       end_(),
       start_(nullptr),
       finish_(nullptr),
       pptimes_() {}
PostTimer() [4/5]
oops::PostTimer::PostTimer (const util::DateTime & start, const eckit::Configuration & conf)
Definition at line 53 of file PostTimer.cc.
     : conf_(conf),
       freq_(0),
       bgn_(),
       end_(),
       start_(new util::DateTime(start)),
       finish_(nullptr),
       pptimes_() {}
PostTimer() [5/5]
oops::PostTimer::PostTimer (const util::DateTime & start, const util::DateTime & finish, const util::Duration & freq)
Definition at line 63 of file PostTimer.cc.
     : conf_(),
       freq_(freq),
       bgn_(),
       end_(),
       start_(new util::DateTime(start)),
       finish_(new util::DateTime(finish)),
       pptimes_() {}
~PostTimer()
oops::PostTimer::~PostTimer () inline
Definition at line 40 of file PostTimer.h.
 {}
Member Function Documentation
initialize()
void oops::PostTimer::initialize (const util::DateTime & bgn, const util::DateTime & end, const util::Duration &)
Definition at line 73 of file PostTimer.cc.
{
   util::DateTime start(bgn);
   if (start_ != 0) {
     start = *start_;
   }
   bgn_ = start;
   util::DateTime finish(end);
   if (finish_ != 0) {
     finish = *finish_;
   }
   end_ = finish;
   // User specified configuration
   Log::debug() << "PProc configuration is:" << conf_ << std::endl;
   // User specified frequency and start
   if (conf_.has("frequency"))
     freq_ = util::Duration(conf_.getString("frequency"));
   if (conf_.has("first")) {
     const util::Duration first(conf_.getString("first"));
     bgn_ += first;
   }
   // User specified steps
   if (conf_.has("steps")) {
     const std::string steps = conf_.getString("steps");
     // this separator list is to maintain compatibility with previous
     // boost::tokenizer default values
     eckit::Tokenizer tok("\t\n\v\f\r !\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~");
     std::vector<std::string> tokens;
     tok(steps, tokens);
     for (const std::string &token : tokens) {
       const util::Duration step(token);
       const util::DateTime tt = start + step;
       if (bgn <= tt && tt <= end) pptimes_.push_back(tt);
     }
   }
 }
References bgn_, conf_, end_, finish_, freq_, pptimes_, and start_.
Referenced by oops::PostBase< State< MODEL > >::initialize(), oops::PostBaseAD< INCR >::initializeAD(), and oops::PostBaseTL< INCR >::initializeTL().
itIsTime()
bool oops::PostTimer::itIsTime (const util::DateTime & now)
Definition at line 111 of file PostTimer.cc.
{
   bool doit = false;
   if (now >= bgn_ && now <= end_) {
     doit = (freq_.toSeconds() == 0 && pptimes_.empty());
     if (!doit && freq_.toSeconds() > 0) {
       const util::Duration dt = now - bgn_;
       doit = (dt >= util::Duration(0) && dt % freq_ == 0);
     }
     if (!doit && !pptimes_.empty()) {
       std::vector<util::DateTime>::iterator it;
       it = find(pptimes_.begin(), pptimes_.end(), now);
       doit = (it != pptimes_.end());
     }
   }
   Log::trace() << "In PostTimer:itIsTime, time = " << now << ", doit = " << doit
                << std::endl;
   return doit;
 }
References bgn_, end_, freq_, and pptimes_.
Referenced by oops::PostBaseAD< INCR >::finalizeAD(), oops::PostBase< State< MODEL > >::initialize(), oops::PostBaseTL< INCR >::initializeTL(), oops::PostBase< State< MODEL > >::process(), oops::PostBaseAD< INCR >::processAD(), and oops::PostBaseTL< INCR >::processTL().
Member Data Documentation
bgn_
util::DateTime oops::PostTimer::bgn_ private
Definition at line 49 of file PostTimer.h.
Referenced by initialize(), and itIsTime().
conf_
const eckit::LocalConfiguration oops::PostTimer::conf_ private
Definition at line 47 of file PostTimer.h.
Referenced by initialize().
end_
util::DateTime oops::PostTimer::end_ private
Definition at line 50 of file PostTimer.h.
Referenced by initialize(), and itIsTime().
finish_
std::unique_ptr<util::DateTime> oops::PostTimer::finish_ private
Definition at line 52 of file PostTimer.h.
Referenced by initialize().
freq_
util::Duration oops::PostTimer::freq_ private
Definition at line 48 of file PostTimer.h.
Referenced by initialize(), and itIsTime().
pptimes_
std::vector<util::DateTime> oops::PostTimer::pptimes_ private
Definition at line 53 of file PostTimer.h.
Referenced by initialize(), and itIsTime().
start_
std::unique_ptr<util::DateTime> oops::PostTimer::start_ private
Definition at line 51 of file PostTimer.h.
Referenced by initialize().
The documentation for this class was generated from the following files:
src/oops/base/PostTimer.h
src/oops/base/PostTimer.cc