OOPS Documentation: oops::SQRTPCGMinimizer< MODEL > Class Template Reference
oops::SQRTPCGMinimizer< MODEL > Class Template Reference
SQRTPCG Minimizer.
#include <SQRTPCGMinimizer.h>
Public Member Functions
const std::string classname () const final
SQRTPCGMinimizer (const eckit::Configuration &, const CostFct_ &)
Constructor, destructor.
~SQRTPCGMinimizer ()
Public Member Functions inherited from oops::SQRTMinimizer< MODEL >
SQRTMinimizer (const eckit::Configuration &conf, const CostFct_ &J)
Construct the minimizer.
~SQRTMinimizer ()
Destroy the minimizer.
void checkpoint (eckit::LocalConfiguration &) const
Checkpoint the minimizer.
void restart (const eckit::Configuration &)
Restart the minimizer.
void warmStart (const eckit::Configuration &)
Warm start the minimizer.
Public Member Functions inherited from oops::Minimizer< MODEL >
Minimizer (const CostFct_ &J)
Construct a minimizer.
virtual ~Minimizer ()
Destroy a minimizer.
ControlIncrement< MODEL > * minimize (const eckit::Configuration &)
Orchestrate the minimization of a quadratic cost function.
Private Types
using Bmat_ = BMatrix< MODEL >
using CostFct_ = CostFunction< MODEL >
using CtrlVec_ = ControlVector< MODEL >
using Jbmat_ = JbMatrix< MODEL >
using UtHtRinvHU_ = UtHtRinvHUMatrix< MODEL >
Private Member Functions
double solve (CtrlVec_ &, CtrlVec_ &, const Jbmat_ &, const UtHtRinvHU_ &, const bool &, const size_t &, const size_t &, const double &, const double &, const double &) final
void checkpointLMP (eckit::LocalConfiguration &) const final
Checkpointing, restart of the limited memory preconditioner.
void restartLMP (const eckit::Configuration &) final
Restart the limited memory preconditioner (virtual method)
void setupQuadCost (const double &costJ0Jb, const double &costJ0JoJc)
Quadratic cost function calculations.
void calcQuadCost (const CtrlVec_ &, const CtrlVec_ &, const CtrlVec_ &)
void printQuadCost (const CtrlVec_ &, const size_t &) const
Private Attributes
double costJ0_
Data members.
double costJ0Jb_
double costJ0JoJc_
double costJ_
double costJb_
double costJoJc_
QNewtonSqrtLMP< MODEL > lmp_
Additional Inherited Members
Protected Attributes inherited from oops::SQRTMinimizer< MODEL >
size_t iter_
Outer loop index.
size_t maxiter_
Number of outer loops.
Detailed Description
template<typename MODEL>
class oops::SQRTPCGMinimizer< MODEL >
SQRTPCG Minimizer.
Preconditioned Conjugate Gradients solver for the square root preconditioned formulation of the Hessian
This solver is based on the standard Preconditioned Conjugate Gradients solver for Ax=b (G. H. Golub and C. F. Van Loan, Matrix Computations).
A must be square, symmetric, positive definite.
On entry:
dv = starting point, \(dv_{0} \).
rr = \((sum dv^{b}_{i} +) U^T H^T R^{-1} d \)
On exit, dv will contain the solution \(U^{-1} dx \) The solution \(dx = U dv \) is recovered in the SQRTMinimizer class The return value is the achieved reduction in preconditioned residual norm.
Iteration will stop if the maximum iteration limit "maxiter" is reached or if the residual norm reduces by a factor of "tolerance".
Definition at line 61 of file SQRTPCGMinimizer.h.
Member Typedef Documentation
Bmat_
template<typename MODEL > using oops::SQRTPCGMinimizer< MODEL >::Bmat_ = BMatrix<MODEL> private
Definition at line 62 of file SQRTPCGMinimizer.h.
CostFct_
template<typename MODEL > using oops::SQRTPCGMinimizer< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 63 of file SQRTPCGMinimizer.h.
CtrlVec_
template<typename MODEL > using oops::SQRTPCGMinimizer< MODEL >::CtrlVec_ = ControlVector<MODEL> private
Definition at line 64 of file SQRTPCGMinimizer.h.
Jbmat_
template<typename MODEL > using oops::SQRTPCGMinimizer< MODEL >::Jbmat_ = JbMatrix<MODEL> private
Definition at line 65 of file SQRTPCGMinimizer.h.
UtHtRinvHU_
template<typename MODEL > using oops::SQRTPCGMinimizer< MODEL >::UtHtRinvHU_ = UtHtRinvHUMatrix<MODEL> private
Definition at line 66 of file SQRTPCGMinimizer.h.
Constructor & Destructor Documentation
SQRTPCGMinimizer()
template<typename MODEL > oops::SQRTPCGMinimizer< MODEL >::SQRTPCGMinimizer (const eckit::Configuration & conf, const CostFct_ & J)
Constructor, destructor.
Definition at line 104 of file SQRTPCGMinimizer.h.
     : SQRTMinimizer<MODEL>(conf, J),
       costJ0_(0),
       costJ0Jb_(0),
       costJ0JoJc_(0),
       costJ_(0),
       costJb_(0),
       costJoJc_(0),
       lmp_(conf, J) {}
~SQRTPCGMinimizer()
template<typename MODEL > oops::SQRTPCGMinimizer< MODEL >::~SQRTPCGMinimizer () inline
Definition at line 73 of file SQRTPCGMinimizer.h.
 {}
Member Function Documentation
calcQuadCost()
template<typename MODEL > void oops::SQRTPCGMinimizer< MODEL >::calcQuadCost (const CtrlVec_ & dv, const CtrlVec_ & jbdv, const CtrlVec_ & r0) private
Definition at line 267 of file SQRTPCGMinimizer.h.
{
   // Compute the quadratic cost function
   // J[dv_{i}] = J[0] - 0.5 dv_{i}^T r_{0}
   costJ_ = costJ0_ - 0.5 * dot_product(dv, r0);
   // Jb[dv_{i}] = 0.5 dv_{i}^T Jb.dv_{i}
   costJb_ = costJ0Jb_ + 0.5 * dot_product(dv, jbdv);
   // Jo[dv_{i}] + Jc[dv_{i}] = J[dv_{i}] - Jb[dv_{i}]
   costJoJc_ = costJ_ - costJb_;
 }
References dot_product().
checkpointLMP()
template<typename MODEL > void oops::SQRTPCGMinimizer< MODEL >::checkpointLMP (eckit::LocalConfiguration &) const final private virtual
Checkpointing, restart of the limited memory preconditioner.
Implements oops::SQRTMinimizer< MODEL >.
Definition at line 297 of file SQRTPCGMinimizer.h.
{
 }
classname()
template<typename MODEL > const std::string oops::SQRTPCGMinimizer< MODEL >::classname () const inline final virtual
Implements oops::SQRTMinimizer< MODEL >.
Definition at line 69 of file SQRTPCGMinimizer.h.
 { return "SQRTPCGMinimizer"; }
printQuadCost()
template<typename MODEL > void oops::SQRTPCGMinimizer< MODEL >::printQuadCost (const CtrlVec_ & dv, const size_t & jiter) const private
Definition at line 282 of file SQRTPCGMinimizer.h.
{
   // Print the quadratic cost function
   Log::info() << "  Quadratic cost function: J   (" << std::setw(2) << jiter + 1
               << ") = " << util::full_precision(costJ_) << std::endl
               << "  Quadratic cost function: Jb  (" << std::setw(2) << jiter + 1
               << ") = " << util::full_precision(costJb_) << std::endl;
   Log::info() << "  Quadratic cost function: JoJc(" << std::setw(2) << jiter + 1
               << ") = " << util::full_precision(costJoJc_) << std::endl
               << std::endl;
 }
References util::full_precision().
restartLMP()
template<typename MODEL > void oops::SQRTPCGMinimizer< MODEL >::restartLMP (const eckit::Configuration &) final private virtual
Restart the limited memory preconditioner (virtual method)
Implements oops::SQRTMinimizer< MODEL >.
Definition at line 303 of file SQRTPCGMinimizer.h.
 {}
setupQuadCost()
template<typename MODEL > void oops::SQRTPCGMinimizer< MODEL >::setupQuadCost (const double & costJ0Jb, const double & costJ0JoJc) private
Quadratic cost function calculations.
Definition at line 249 of file SQRTPCGMinimizer.h.
{
   // J0
   costJ0Jb_ = costJ0Jb;
   costJ0JoJc_ = costJ0JoJc;
   // J0
   costJ0_ = costJ0Jb_ + costJ0JoJc_;
   // reset
   costJ_ = 0;
   costJb_ = 0;
   costJoJc_ = 0;
 }
solve()
template<typename MODEL > double oops::SQRTPCGMinimizer< MODEL >::solve (CtrlVec_ & dv, CtrlVec_ & rr, const Jbmat_ & Jb, const UtHtRinvHU_ & UtHtRinvHU, const bool & linfoconv, const size_t & maxiter, const size_t & miniter, const double & tolerance, const double & costJ0Jb, const double & costJ0JoJc) final private virtual
Implements oops::SQRTMinimizer< MODEL >.
Definition at line 118 of file SQRTPCGMinimizer.h.
{
   // dv   control vector
   // rr   (sum dv_i^{b} +) U^T G^T R^{-1} d
   CtrlVec_ qq(dv);
   CtrlVec_ pp(dv);
   CtrlVec_ pr(dv);
   CtrlVec_ jbpp(dv);
   CtrlVec_ jbdv(dv);
   CtrlVec_ zz(dv);
   CtrlVec_ r0(dv);
   CtrlVec_ ww(dv);
   // vectors for re-orthogonalization
   std::vector<CtrlVec_> zvecs;
   std::vector<double> scals;
   // setup calculation of the quadratic cost function
   this->setupQuadCost(costJ0Jb, costJ0JoJc);
   // change resolution of LMP vectors
   lmp_.changeResolution();
   // r_{0}
   r0 = rr;
   // r_{0}^T r_{0}
   Log::info() << "normr0 " << dot_product(rr, rr) << std::endl;
   // z_{0} = LMP r_{0}
   lmp_.inverseMultiplySqrt(rr, zz);
   // z_{0} = LMP r_{0}
   pp = zz;
   // z_{0}^T z_{0}
   double dotZZ0 = dot_product(zz, zz);
   double normReduction = 1.0;
   double zdots = dotZZ0;
   double zdots_old = 0.0;
   zvecs.push_back(zz);
   scals.push_back(1.0 / dotZZ0);
   Log::info() << std::endl;
   for (size_t jiter = 0; jiter < maxiter; ++jiter) {
     Log::info() << " SQRTPCG Starting Iteration " << jiter + 1 << std::endl;
     util::LogbookWriter<int> log("InnerLoop", jiter);
     if (jiter > 0) {
       // beta_{i} = z_{i+1}^T z_{i+1} / z_{i}^T z_{i}
       double beta = zdots / zdots_old;
       // p_{i+1} = z_{i+1} + beta*p_{i}
       pp *= beta;
       pp += zz;
     }
     // q_{i} = P^-1/2 ( Jb + U^T H^T R^{-1} H U ) P^-1/2 p_{i}
     lmp_.inverseMultiplySqrt(pp, pr);
     UtHtRinvHU.multiply(pr, ww);
     Jb.multiply(pr, jbpp);  // U^T B^-1 U != I for VarBC
     ww += jbpp;
     lmp_.inverseMultiplySqrt(ww, qq);
     // alpha_{i} = z_{i}^T z_{i} / q_{i}^T p_{i}
     double rho = dot_product(pp, qq);
     double alpha = zdots / rho;
     // dv_{i+1} = dv_{i} + alpha * p_{i}
     dv.axpy(alpha, pp);
     // jbdv_{i+1} = jbdv_{i} + alpha * jbh_{i}
     jbdv.axpy(alpha, jbpp);
     // z_{i+1} = z_{i} - alpha * q_{i}
     zz.axpy(-alpha, qq);
     // Compute the quadratic cost function
     this->calcQuadCost(dv, jbdv, r0);
     // Re-orthogonalization
     for (size_t jj = 0; jj < jiter; ++jj) {
       double proj = scals[jj] * dot_product(zz, zvecs[jj]);
       zz.axpy(-proj, zvecs[jj]);
     }
     // z_{i}^T z_{i}
     zdots_old = zdots;
     // z_{i+1}^T z_{i+1}
     zdots = dot_product(zz, zz);
     Log::info() << "zdots " << zdots << "      iteration    " << jiter
                 << std::endl;
     // z_{i+1}^T z_{i+1} / z_{0}^T z_{0}
     normReduction = sqrt(zdots / dotZZ0);
     util::LogbookWriter<double> log_norm("NormReduction", normReduction);
     Log::info() << "SQRTPCG end of iteration " << jiter + 1 << std::endl
                 << "  Norm reduction (" << std::setw(2) << jiter + 1
                 << ") = " << util::full_precision(normReduction) << std::endl;
     this->printQuadCost(dv, jiter);
     if (normReduction < tolerance && jiter >= miniter) {
       Log::info() << "SQRTPCG: Achieved required reduction in residual norm."
                   << std::endl;
       break;
     }
     zvecs.push_back(zz);
     scals.push_back(1.0 / zdots);
     lmp_.push(pp, zz, qq, rho);
   }
   lmp_.update();
   return normReduction;
 }
References oops::ControlVector< MODEL >::axpy(), dot_product(), util::full_precision(), oops::JbMatrix< MODEL >::multiply(), and oops::UtHtRinvHUMatrix< MODEL >::multiply().
Member Data Documentation
costJ0_
template<typename MODEL > double oops::SQRTPCGMinimizer< MODEL >::costJ0_ private
Data members.
Definition at line 90 of file SQRTPCGMinimizer.h.
costJ0Jb_
template<typename MODEL > double oops::SQRTPCGMinimizer< MODEL >::costJ0Jb_ private
Definition at line 91 of file SQRTPCGMinimizer.h.
costJ0JoJc_
template<typename MODEL > double oops::SQRTPCGMinimizer< MODEL >::costJ0JoJc_ private
Definition at line 92 of file SQRTPCGMinimizer.h.
costJ_
template<typename MODEL > double oops::SQRTPCGMinimizer< MODEL >::costJ_ private
Definition at line 94 of file SQRTPCGMinimizer.h.
costJb_
template<typename MODEL > double oops::SQRTPCGMinimizer< MODEL >::costJb_ private
Definition at line 95 of file SQRTPCGMinimizer.h.
costJoJc_
template<typename MODEL > double oops::SQRTPCGMinimizer< MODEL >::costJoJc_ private
Definition at line 96 of file SQRTPCGMinimizer.h.
lmp_
template<typename MODEL > QNewtonSqrtLMP<MODEL> oops::SQRTPCGMinimizer< MODEL >::lmp_ private
Definition at line 98 of file SQRTPCGMinimizer.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/SQRTPCGMinimizer.h