OOPS Documentation: oops::LinearObsOperator< MODEL > Class Template Reference
oops::LinearObsOperator< MODEL > Class Template Reference
Encapsulates the linear observation operator.
#include <LinearObsOperator.h>
Public Member Functions
LinearObsOperator (const ObsSpace_ &)
Constructor.
~LinearObsOperator ()
Destructor.
const LinearObsOperBase_ & linearobsoperator () const
Interfacing - return a constant reference to the concrete operator object.
void setTrajectory (const GeoVaLs_ &, const ObsAuxControl_ &)
Set the linearisation trajectory.
void obsEquivTL (const GeoVaLs_ &, ObsVector_ &, const ObsAuxIncrement_ &) const
Evaluate the linear observation operator \(\bar{H} \).
void obsEquivAD (GeoVaLs_ &, const ObsVector_ &, ObsAuxIncrement_ &) const
Evaluate the adjoint of the linear observation operator \(\bar{H} \).
void obsBiasEquivTL (const GeoVaLs_ &, ObsVector_ &, const ObsAuxIncrement_ &) const
Evaluate the linear bias operator.
void obsBiasEquivAD (const GeoVaLs_ &, const ObsVector_ &, ObsAuxIncrement_ &) const
Evaluate the adjoint of the bias observation operator.
Variables_ variables () const
Retrun variables (required input variables from LinearModel)
Static Public Member Functions
static const std::string classname ()
Private Types
using LinearObsOperBase_ = LinearObsOperBase< MODEL >
using GeoVaLs_ = GeoVaLs< MODEL >
using ObsAuxControl_ = ObsAuxControl< MODEL >
using ObsAuxIncrement_ = ObsAuxIncrement< MODEL >
using ObsSpace_ = ObservationSpace< MODEL >
using ObsVector_ = ObsVector< MODEL >
using Variables_ = Variables< MODEL >
Private Member Functions
void print (std::ostream &) const
Private Attributes
std::unique_ptr< LinearObsOperBase_ > oper_
Pointer to a LinearObsOperBase object.
Detailed Description
template<typename MODEL>
class oops::LinearObsOperator< MODEL >
Encapsulates the linear observation operator.
This class provides the operations associated with the linear observation operator. It wraps the actual linear observation operator which is derived from the linear observation operator base class LinearObsOperBase. The interface for the linear observation operator comprises two levels because we want run time polymorphism. Note that it may be desirable to define a linear observation operator for each individual observation type rather than a single composite operator (which is the case the IFS). LinearObsOperFactory produces concrete objects of LinearObsOperBase children classes.
LinearObsOperators class contains a vector of LinearObsOperator objects. Refer to the documentation of CostJo class to understand the structure of the \(J_o \) term.
Definition at line 60 of file LinearObsOperator.h.
Member Typedef Documentation
GeoVaLs_
template<typename MODEL > using oops::LinearObsOperator< MODEL >::GeoVaLs_ = GeoVaLs<MODEL> private
Definition at line 65 of file LinearObsOperator.h.
LinearObsOperBase_
template<typename MODEL > using oops::LinearObsOperator< MODEL >::LinearObsOperBase_ = LinearObsOperBase<MODEL> private
Definition at line 64 of file LinearObsOperator.h.
ObsAuxControl_
template<typename MODEL > using oops::LinearObsOperator< MODEL >::ObsAuxControl_ = ObsAuxControl<MODEL> private
Definition at line 66 of file LinearObsOperator.h.
ObsAuxIncrement_
template<typename MODEL > using oops::LinearObsOperator< MODEL >::ObsAuxIncrement_ = ObsAuxIncrement<MODEL> private
Definition at line 67 of file LinearObsOperator.h.
ObsSpace_
template<typename MODEL > using oops::LinearObsOperator< MODEL >::ObsSpace_ = ObservationSpace<MODEL> private
Definition at line 68 of file LinearObsOperator.h.
ObsVector_
template<typename MODEL > using oops::LinearObsOperator< MODEL >::ObsVector_ = ObsVector<MODEL> private
Definition at line 69 of file LinearObsOperator.h.
Variables_
template<typename MODEL > using oops::LinearObsOperator< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 70 of file LinearObsOperator.h.
Constructor & Destructor Documentation
LinearObsOperator()
template<typename MODEL > oops::LinearObsOperator< MODEL >::LinearObsOperator (const ObsSpace_ & os) explicit
Constructor.
Definition at line 112 of file LinearObsOperator.h.
                                                                : oper_() {
   Log::trace() << "LinearObsOperator<MODEL>::LinearObsOperator starting"
                << std::endl;
   util::Timer timer(classname(), "LinearObsOperator");
   oper_.reset(
       LinearObsOperFactory<MODEL>::create(os.observationspace(), os.config()));
   Log::trace() << "LinearObsOperator<MODEL>::LinearObsOperator done"
                << std::endl;
 }
References oops::LinearObsOperator< MODEL >::classname(), oops::ObservationSpace< MODEL >::config(), oops::ObservationSpace< MODEL >::observationspace(), and oops::LinearObsOperator< MODEL >::oper_.
~LinearObsOperator()
template<typename MODEL > oops::LinearObsOperator< MODEL >::~LinearObsOperator
Destructor.
Definition at line 125 of file LinearObsOperator.h.
{
   Log::trace() << "LinearObsOperator<MODEL>::~LinearObsOperator starting"
                << std::endl;
   util::Timer timer(classname(), "~LinearObsOperator");
   oper_.reset();
   Log::trace() << "LinearObsOperator<MODEL>::~LinearObsOperator done"
                << std::endl;
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::LinearObsOperator< MODEL >::classname () inline static
Definition at line 73 of file LinearObsOperator.h.
 { return "oops::LinearObsOperator"; }
Referenced by oops::LinearObsOperator< MODEL >::LinearObsOperator().
linearobsoperator()
template<typename MODEL > const LinearObsOperBase_& oops::LinearObsOperator< MODEL >::linearobsoperator () const inline
Interfacing - return a constant reference to the concrete operator object.
Definition at line 81 of file LinearObsOperator.h.
 { return *oper_; }
References oops::LinearObsOperator< MODEL >::oper_.
obsBiasEquivAD()
template<typename MODEL > void oops::LinearObsOperator< MODEL >::obsBiasEquivAD (const GeoVaLs_ & gvals, const ObsVector_ & obias, ObsAuxIncrement_ & aux) const
Evaluate the adjoint of the bias observation operator.
\(\tilde{P}^T dy \)
Definition at line 194 of file LinearObsOperator.h.
{
   Log::trace() << "LinearObsOperator<MODEL>::obsBiasEquivAD starting"
                << std::endl;
   util::Timer timer(classname(), "ObsBiasEquivAD");
   ObsAuxIncrement_ auxbias(aux, false);
   auxbias.zero();
   oper_->obsBiasEquivAD(gvals.geovals(), obias.obsvector(),
                         auxbias.obsauxincrement());
   aux += auxbias;
   Log::trace() << "LinearObsOperator<MODEL>::obsBiasEquivAD done" << std::endl;
 }
References oops::GeoVaLs< MODEL >::geovals(), oops::ObsAuxIncrement< MODEL >::obsauxincrement(), oops::ObsVector< MODEL >::obsvector(), and oops::ObsAuxIncrement< MODEL >::zero().
obsBiasEquivTL()
template<typename MODEL > void oops::LinearObsOperator< MODEL >::obsBiasEquivTL (const GeoVaLs_ & gvals, ObsVector_ & obias, const ObsAuxIncrement_ & aux) const
Evaluate the linear bias operator.
\(\tilde{P} dx_{obsaux} \)
Definition at line 179 of file LinearObsOperator.h.
{
   Log::trace() << "LinearObsOperator<MODEL>::obsBiasEquivTL starting"
                << std::endl;
   util::Timer timer(classname(), "ObsBiasEquivTL");
   oper_->obsBiasEquivTL(gvals.geovals(), obias.obsvector(),
                         aux.obsauxincrement());
   Log::trace() << "LinearObsOperator<MODEL>::obsBiasEquivTL done" << std::endl;
 }
References oops::GeoVaLs< MODEL >::geovals(), oops::ObsAuxIncrement< MODEL >::obsauxincrement(), and oops::ObsVector< MODEL >::obsvector().
obsEquivAD()
template<typename MODEL > void oops::LinearObsOperator< MODEL >::obsEquivAD (GeoVaLs_ & gvals, const ObsVector_ & yy, ObsAuxIncrement_ & aux) const
Evaluate the adjoint of the linear observation operator \(\bar{H} \).
\[ \begin{bmatrix} \tilde{H}^T \\ \tilde{P}^T \end{bmatrix} dy \]
Definition at line 165 of file LinearObsOperator.h.
{
   Log::trace() << "LinearObsOperator<MODEL>::obsEquivAD starting" << std::endl;
   util::Timer timer(classname(), "ObsEquivAD");
   oper_->obsEquivAD(gvals.geovals(), yy.obsvector(), aux.obsauxincrement());
   Log::trace() << "LinearObsOperator<MODEL>::obsEquivAD done" << std::endl;
 }
References oops::GeoVaLs< MODEL >::geovals(), oops::ObsAuxIncrement< MODEL >::obsauxincrement(), and oops::ObsVector< MODEL >::obsvector().
obsEquivTL()
template<typename MODEL > void oops::LinearObsOperator< MODEL >::obsEquivTL (const GeoVaLs_ & gvals, ObsVector_ & yy, const ObsAuxIncrement_ & aux) const
Evaluate the linear observation operator \(\bar{H} \).
\[ \begin{bmatrix} \tilde{H} && \tilde{P} \end{bmatrix} \begin{bmatrix} I (dx) \\ dx_{obsaux} \end{bmatrix} \]
Note: -> \(I (dx) \) is stored by GeoVaLs.
Definition at line 148 of file LinearObsOperator.h.
{
   Log::trace() << "LinearObsOperator<MODEL>::obsEquivTL starting" << std::endl;
   util::Timer timer(classname(), "ObsEquivTL");
   oper_->obsEquivTL(gvals.geovals(), yy.obsvector(), aux.obsauxincrement());
   Log::trace() << "LinearObsOperator<MODEL>::obsEquivTL done" << std::endl;
 }
References oops::GeoVaLs< MODEL >::geovals(), oops::ObsAuxIncrement< MODEL >::obsauxincrement(), and oops::ObsVector< MODEL >::obsvector().
print()
template<typename MODEL > void oops::LinearObsOperator< MODEL >::print (std::ostream & os) const private
Definition at line 222 of file LinearObsOperator.h.
{
   Log::trace() << "LinearObsOperator<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   os << *oper_;
   Log::trace() << "LinearObsOperator<MODEL>::print done" << std::endl;
 }
setTrajectory()
template<typename MODEL > void oops::LinearObsOperator< MODEL >::setTrajectory (const GeoVaLs_ & gvals, const ObsAuxControl_ & aux)
Set the linearisation trajectory.
Definition at line 137 of file LinearObsOperator.h.
{
   Log::trace() << "LinearObsOperator<MODEL>::obsEquiv starting" << std::endl;
   util::Timer timer(classname(), "ObsEquiv");
   oper_->setTrajectory(gvals.geovals(), aux.obsauxcontrol());
   Log::trace() << "LinearObsOperator<MODEL>::obsEquiv done" << std::endl;
 }
References oops::GeoVaLs< MODEL >::geovals(), and oops::ObsAuxControl< MODEL >::obsauxcontrol().
variables()
template<typename MODEL > Variables< MODEL > oops::LinearObsOperator< MODEL >::variables
Retrun variables (required input variables from LinearModel)
Definition at line 211 of file LinearObsOperator.h.
{
   Log::trace() << "LinearObsOperator<MODEL>::variables starting" << std::endl;
   util::Timer timer(classname(), "variables");
   Variables_ inputs(oper_->variables());
   Log::trace() << "LinearObsOperator<MODEL>::variables done" << std::endl;
   return inputs;
 }
Member Data Documentation
oper_
template<typename MODEL > std::unique_ptr<LinearObsOperBase_> oops::LinearObsOperator< MODEL >::oper_ private
Pointer to a LinearObsOperBase object.
Definition at line 106 of file LinearObsOperator.h.
Referenced by oops::LinearObsOperator< MODEL >::LinearObsOperator(), and oops::LinearObsOperator< MODEL >::linearobsoperator().
The documentation for this class was generated from the following file:
src/oops/interface/LinearObsOperator.h