OOPS Documentation: oops::ModelAuxControl< MODEL > Class Template Reference
oops::ModelAuxControl< MODEL > Class Template Reference
Encapsulates the auxiliary model space component of ControlVariable.
#include <ModelAuxControl.h>
Public Member Functions
ModelAuxControl (const Geometry_ &, const Model_ &, const eckit::Configuration &)
Constructor.
ModelAuxControl (const Geometry_ &, const ModelAuxControl &)
Copy constructor with interpolation.
ModelAuxControl (const ModelAuxControl &, const bool copy=true)
Copy constructor.
~ModelAuxControl ()
Destructor.
const ModelAuxControl_ & modelauxcontrol () const
Return a constant reference to the encapsulated model specific object.
ModelAuxControl_ & modelauxcontrol ()
Return a reference to the encapsulated model specific object.
void read (const eckit::Configuration &)
Read.
void write (const eckit::Configuration &) const
Write.
double norm () const
Compute L-2 norm.
Static Public Member Functions
static const std::string classname ()
Private Types
using ModelAuxControl_ = typename MODEL::ModelAuxControl
using Geometry_ = Geometry< MODEL >
using Model_ = Model< MODEL >
using State_ = State< MODEL >
Private Member Functions
ModelAuxControl & operator= (const ModelAuxControl &)
void print (std::ostream &) const
Private Attributes
std::unique_ptr< ModelAuxControl_ > aux_
Pointer to the model specific object.
Detailed Description
template<typename MODEL>
class oops::ModelAuxControl< MODEL >
Encapsulates the auxiliary model space component of ControlVariable.
The auxiliary model space component of ControlVariable is designed as a constant (time step independent) model error forcing term that can be jointly estimated by the assimilation algorithm.
\(x_{k+1} = {\cal M}_{k+1:k} x_k + \eta \), where \(\eta \) is the model error forcing term implemented by ModelAuxControl.
Definition at line 48 of file ModelAuxControl.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::ModelAuxControl< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 51 of file ModelAuxControl.h.
Model_
template<typename MODEL > using oops::ModelAuxControl< MODEL >::Model_ = Model<MODEL> private
Definition at line 52 of file ModelAuxControl.h.
ModelAuxControl_
template<typename MODEL > using oops::ModelAuxControl< MODEL >::ModelAuxControl_ = typename MODEL::ModelAuxControl private
Definition at line 50 of file ModelAuxControl.h.
State_
template<typename MODEL > using oops::ModelAuxControl< MODEL >::State_ = State<MODEL> private
Definition at line 53 of file ModelAuxControl.h.
Constructor & Destructor Documentation
ModelAuxControl() [1/3]
template<typename MODEL > oops::ModelAuxControl< MODEL >::ModelAuxControl (const Geometry_ & resol, const Model_ & model, const eckit::Configuration & conf)
Constructor.
Definition at line 93 of file ModelAuxControl.h.
     : aux_() {
   Log::trace() << "ModelAuxControl<MODEL>::ModelAuxControl starting"
                << std::endl;
   util::Timer timer(classname(), "ModelAuxControl");
   aux_.reset(new ModelAuxControl_(resol.geometry(), model.model(),
                                   conf.getSubConfiguration("stateModAux")));
   Log::trace() << "ModelAuxControl<MODEL>::ModelAuxControl done" << std::endl;
 }
References oops::ModelAuxControl< MODEL >::aux_, oops::ModelAuxControl< MODEL >::classname(), oops::Geometry< MODEL >::geometry(), and oops::Model< MODEL >::model().
ModelAuxControl() [2/3]
template<typename MODEL > oops::ModelAuxControl< MODEL >::ModelAuxControl (const Geometry_ & resol, const ModelAuxControl< MODEL > & other)
Copy constructor with interpolation.
Definition at line 108 of file ModelAuxControl.h.
     : aux_() {
   Log::trace()
       << "ModelAuxControl<MODEL>::ModelAuxControl interpolated starting"
       << std::endl;
   util::Timer timer(classname(), "ModelAuxControl");
   aux_.reset(new ModelAuxControl_(resol.geometry(), *other.aux_));
   Log::trace() << "ModelAuxControl<MODEL>::ModelAuxControl interpolated done"
                << std::endl;
 }
References oops::ModelAuxControl< MODEL >::aux_, oops::ModelAuxControl< MODEL >::classname(), and oops::Geometry< MODEL >::geometry().
ModelAuxControl() [3/3]
template<typename MODEL > oops::ModelAuxControl< MODEL >::ModelAuxControl (const ModelAuxControl< MODEL > & other, const bool copy = true) explicit
Copy constructor.
Definition at line 123 of file ModelAuxControl.h.
     : aux_() {
   Log::trace() << "ModelAuxControl<MODEL>::ModelAuxControl copy starting"
                << std::endl;
   util::Timer timer(classname(), "ModelAuxControl");
   aux_.reset(new ModelAuxControl_(*other.aux_, copy));
   Log::trace() << "ModelAuxControl<MODEL>::ModelAuxControl copy done"
                << std::endl;
 }
References oops::ModelAuxControl< MODEL >::aux_, and oops::ModelAuxControl< MODEL >::classname().
~ModelAuxControl()
template<typename MODEL > oops::ModelAuxControl< MODEL >::~ModelAuxControl
Destructor.
Definition at line 137 of file ModelAuxControl.h.
{
   Log::trace() << "ModelAuxControl<MODEL>::~ModelAuxControl starting"
                << std::endl;
   util::Timer timer(classname(), "~ModelAuxControl");
   aux_.reset();
   Log::trace() << "ModelAuxControl<MODEL>::~ModelAuxControl done" << std::endl;
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::ModelAuxControl< MODEL >::classname () inline static
Definition at line 56 of file ModelAuxControl.h.
 { return "oops::ModelAuxControl"; }
Referenced by oops::ModelAuxControl< MODEL >::ModelAuxControl().
modelauxcontrol() [1/2]
template<typename MODEL > ModelAuxControl_& oops::ModelAuxControl< MODEL >::modelauxcontrol () inline
Return a reference to the encapsulated model specific object.
Definition at line 72 of file ModelAuxControl.h.
 { return *aux_; }
References oops::ModelAuxControl< MODEL >::aux_.
modelauxcontrol() [2/2]
template<typename MODEL > const ModelAuxControl_& oops::ModelAuxControl< MODEL >::modelauxcontrol () const inline
Return a constant reference to the encapsulated model specific object.
Definition at line 70 of file ModelAuxControl.h.
 { return *aux_; }
References oops::ModelAuxControl< MODEL >::aux_.
Referenced by oops::ModelAuxIncrement< MODEL >::diff(), oops::ModelAuxControlEstimator< MODEL >::estimate(), oops::Model< MODEL >::initialize(), oops::ModelAuxCovariance< MODEL >::linearize(), oops::operator+=(), oops::LinearModelBase< L95Traits >::setTrajectory(), and oops::Model< MODEL >::step().
norm()
template<typename MODEL > double oops::ModelAuxControl< MODEL >::norm
Compute L-2 norm.
Definition at line 168 of file ModelAuxControl.h.
{
   Log::trace() << "ModelAuxControl<MODEL>::norm starting" << std::endl;
   util::Timer timer(classname(), "norm");
   double zz = aux_->norm();
   Log::trace() << "ModelAuxControl<MODEL>::norm done" << std::endl;
   return zz;
 }
Referenced by oops::ModelAuxNN< MODEL >::execute().
operator=()
template<typename MODEL > ModelAuxControl& oops::ModelAuxControl< MODEL >::operator= (const ModelAuxControl< MODEL > &) private
print()
template<typename MODEL > void oops::ModelAuxControl< MODEL >::print (std::ostream & os) const private
Definition at line 179 of file ModelAuxControl.h.
{
   Log::trace() << "ModelAuxControl<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   os << *aux_;
   Log::trace() << "ModelAuxControl<MODEL>::print done" << std::endl;
 }
read()
template<typename MODEL > void oops::ModelAuxControl< MODEL >::read (const eckit::Configuration & conf)
Read.
Definition at line 148 of file ModelAuxControl.h.
{
   Log::trace() << "ModelAuxControl<MODEL>::read starting" << std::endl;
   util::Timer timer(classname(), "read");
   aux_->read(conf.getSubConfiguration("stateModAux"));
   Log::trace() << "ModelAuxControl<MODEL>::read done" << std::endl;
 }
write()
template<typename MODEL > void oops::ModelAuxControl< MODEL >::write (const eckit::Configuration & conf) const
Write.
Definition at line 158 of file ModelAuxControl.h.
{
   Log::trace() << "ModelAuxControl<MODEL>::write starting" << std::endl;
   util::Timer timer(classname(), "write");
   aux_->write(conf.getSubConfiguration("stateModAux"));
   Log::trace() << "ModelAuxControl<MODEL>::write done" << std::endl;
 }
Member Data Documentation
aux_
template<typename MODEL > std::unique_ptr<ModelAuxControl_> oops::ModelAuxControl< MODEL >::aux_ private
Pointer to the model specific object.
Definition at line 87 of file ModelAuxControl.h.
Referenced by oops::ModelAuxControl< MODEL >::ModelAuxControl(), and oops::ModelAuxControl< MODEL >::modelauxcontrol().
The documentation for this class was generated from the following file:
src/oops/interface/ModelAuxControl.h