OOPS Documentation: oops::EnsembleCovariance4DDistributed< MODEL > Class Template Reference
oops::EnsembleCovariance4DDistributed< MODEL > Class Template Reference
Generic ensemble based model space error covariance.
#include <EnsembleCovariance4DDistributed.h>
Public Member Functions
EnsembleCovariance4DDistributed (const Geometry_ &, const Variables_ &, const eckit::Configuration &, const State4D_ &)
Constructor, destructor.
~EnsembleCovariance4DDistributed ()
void advectedLinearize (const State4D_ &, const Geometry_ &, const eckit::Configuration &)
void advectedMultiply (const Increment4D_ &, Increment4D_ &) const
void advectedMultiplySqrt (const IncrCtlVec_ &, Increment4D_ &) const
void advectedMultiplySqrtTrans (const Increment4D_ &, IncrCtlVec_ &) const
void advectedInverseMultiply (const Increment4D_ &, Increment4D_ &) const
const ModelSpaceCovarianceBase< MODEL > & covar () const
IncrModCtlVec_ * newIncrModCtlVec () const override
IncrEnsCtlVec_ * newIncrEnsCtlVec () const override
Public Member Functions inherited from oops::ModelSpaceCovariance4DBase< MODEL >
ModelSpaceCovariance4DBase (const Geometry_ &, const eckit::Configuration &config)
virtual ~ModelSpaceCovariance4DBase ()
void linearize (const State4D_ &xb, const Geometry_ &resol, const eckit::Configuration &config)
virtual void multiply (const Increment4D_ &dxi, Increment4D_ &dxo) const
virtual void multiplySqrt (const IncrCtlVec_ &dvi, Increment4D_ &dxo) const
virtual void multiplySqrtTrans (const Increment4D_ &dxi, IncrCtlVec_ &dvo) const
void inverseMultiply (const Increment4D_ &dxi, Increment4D_ &dxo) const
virtual void randomize (Increment4D_ &) const
Private Types
using Ensemble_ = Ensemble< MODEL >
using EnsemblePtr_ = std::shared_ptr< Ensemble< MODEL > >
using EnsemblesCollection_ = EnsemblesCollection< MODEL >
using Geometry_ = Geometry< MODEL >
using Increment_ = Increment< MODEL >
using Localization_ = Localization< MODEL >
using State4D_ = State4D< MODEL >
using Increment4D_ = Increment4D< MODEL >
using IncrCtlVec_ = IncrCtlVec< MODEL >
using IncrEnsCtlVec_ = IncrEnsCtlVec< MODEL >
using IncrModCtlVec_ = IncrModCtlVec< MODEL >
using Variables_ = Variables< MODEL >
Private Member Functions
unsigned get_xb_prim (unsigned l) const
void schur_add (const Increment_ &, const Increment_ &dxi, Increment_ &dxo, Increment_ &tmp) const
Private Attributes
const eckit::LocalConfiguration config_
unsigned nsubwin_
std::vector< util::DateTime > time_
std::unique_ptr< Localization_ > loc_
std::unique_ptr< Geometry_ > geom_
std::unique_ptr< ModelSpaceCovarianceBase< MODEL > > static_
Detailed Description
template<typename MODEL>
class oops::EnsembleCovariance4DDistributed< MODEL >
Generic ensemble based model space error covariance.
Definition at line 39 of file EnsembleCovariance4DDistributed.h.
Member Typedef Documentation
Ensemble_
template<typename MODEL > using oops::EnsembleCovariance4DDistributed< MODEL >::Ensemble_ = Ensemble<MODEL> private
Definition at line 41 of file EnsembleCovariance4DDistributed.h.
EnsemblePtr_
template<typename MODEL > using oops::EnsembleCovariance4DDistributed< MODEL >::EnsemblePtr_ = std::shared_ptr<Ensemble<MODEL> > private
Definition at line 42 of file EnsembleCovariance4DDistributed.h.
EnsemblesCollection_
template<typename MODEL > using oops::EnsembleCovariance4DDistributed< MODEL >::EnsemblesCollection_ = EnsemblesCollection<MODEL> private
Definition at line 43 of file EnsembleCovariance4DDistributed.h.
Geometry_
template<typename MODEL > using oops::EnsembleCovariance4DDistributed< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 44 of file EnsembleCovariance4DDistributed.h.
IncrCtlVec_
template<typename MODEL > using oops::EnsembleCovariance4DDistributed< MODEL >::IncrCtlVec_ = IncrCtlVec<MODEL> private
Definition at line 49 of file EnsembleCovariance4DDistributed.h.
Increment4D_
template<typename MODEL > using oops::EnsembleCovariance4DDistributed< MODEL >::Increment4D_ = Increment4D<MODEL> private
Definition at line 48 of file EnsembleCovariance4DDistributed.h.
Increment_
template<typename MODEL > using oops::EnsembleCovariance4DDistributed< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 45 of file EnsembleCovariance4DDistributed.h.
IncrEnsCtlVec_
template<typename MODEL > using oops::EnsembleCovariance4DDistributed< MODEL >::IncrEnsCtlVec_ = IncrEnsCtlVec<MODEL> private
Definition at line 50 of file EnsembleCovariance4DDistributed.h.
IncrModCtlVec_
template<typename MODEL > using oops::EnsembleCovariance4DDistributed< MODEL >::IncrModCtlVec_ = IncrModCtlVec<MODEL> private
Definition at line 51 of file EnsembleCovariance4DDistributed.h.
Localization_
template<typename MODEL > using oops::EnsembleCovariance4DDistributed< MODEL >::Localization_ = Localization<MODEL> private
Definition at line 46 of file EnsembleCovariance4DDistributed.h.
State4D_
template<typename MODEL > using oops::EnsembleCovariance4DDistributed< MODEL >::State4D_ = State4D<MODEL> private
Definition at line 47 of file EnsembleCovariance4DDistributed.h.
Variables_
template<typename MODEL > using oops::EnsembleCovariance4DDistributed< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 52 of file EnsembleCovariance4DDistributed.h.
Constructor & Destructor Documentation
EnsembleCovariance4DDistributed()
template<typename MODEL > oops::EnsembleCovariance4DDistributed< MODEL >::EnsembleCovariance4DDistributed (const Geometry_ & resol, const Variables_ & , const eckit::Configuration & config, const State4D_ &)
Constructor, destructor.
Definition at line 93 of file EnsembleCovariance4DDistributed.h.
     : ModelSpaceCovariance4DBase<MODEL>::ModelSpaceCovariance4DBase(resol,
                                                                     config),
       config_(config),
       nsubwin_((unsigned int)0) {
   Log::trace() << "EnsembleCovariance4DDistributed created.";
 }
~EnsembleCovariance4DDistributed()
template<typename MODEL > oops::EnsembleCovariance4DDistributed< MODEL >::~EnsembleCovariance4DDistributed
Definition at line 104 of file EnsembleCovariance4DDistributed.h.
{
   Log::trace() << "EnsembleCovariance4DDistributed destructed.";
 }
Member Function Documentation
advectedInverseMultiply()
template<typename MODEL > void oops::EnsembleCovariance4DDistributed< MODEL >::advectedInverseMultiply (const Increment4D_ & dxi, Increment4D_ & dxo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 218 of file EnsembleCovariance4DDistributed.h.
{
   dxo.zero();
 }
References oops::Increment4D< MODEL >::zero().
advectedLinearize()
template<typename MODEL > void oops::EnsembleCovariance4DDistributed< MODEL >::advectedLinearize (const State4D_ & xb, const Geometry_ & resol, const eckit::Configuration &) virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 110 of file EnsembleCovariance4DDistributed.h.
{
   /*
    * Build localization
    */
   geom_.reset(new Geometry_(resol));
   const eckit::LocalConfiguration confLoc(config_, "localization");
   loc_.reset(new Localization_(*geom_, confLoc));
   /*
    * Build ensemble
    */
   std::vector<eckit::LocalConfiguration> confEnsemble;
   config_.get("ensemble", confEnsemble);
   time_.clear();
   nsubwin_ = confEnsemble.size();
   for (unsigned jsub = 0; jsub < nsubwin_; ++jsub) {
     EnsemblePtr_ ens_k(
         new Ensemble_(xb[jsub].validTime(), confEnsemble[jsub], true));
     ens_k->build(xb[jsub], resol);
     EnsemblesCollection_::getInstance().put(xb[jsub].validTime(), ens_k);
     time_.push_back(xb[jsub].validTime());
   }
   /*
    * Calculate perturbations
    */
   for (unsigned jsub = 0; jsub < nsubwin_; ++jsub) {
     EnsemblePtr_ ens =
         EnsemblesCollection_::getInstance()[xb[jsub].validTime()];
     ens->to_perturbations((bool)true);
   }
   Log::trace() << "EnsembleCovariance4DDistributed linearized.";
 }
advectedMultiply()
template<typename MODEL > void oops::EnsembleCovariance4DDistributed< MODEL >::advectedMultiply (const Increment4D_ & dxi, Increment4D_ & dxo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 149 of file EnsembleCovariance4DDistributed.h.
{
   Increment_ dx_loc(dxo[0]);
   Increment_ tmp(dxo[0]);
   EnsemblePtr_ e = EnsemblesCollection_::getInstance()[dxi[0].validTime()];
   dxo.zero();
   for (unsigned l = 0; l < e->size(); ++l) {
     unsigned ix = get_xb_prim(l);
     dx_loc.zero();
     for (unsigned k2 = 0; k2 < nsubwin_; ++k2) {
       EnsemblePtr_ e_k2 =
           EnsemblesCollection_::getInstance()[dxi[k2].validTime()];
       schur_add((*e_k2)[ix], dxi[k2], dx_loc, tmp);
     }
     loc_->multiply(dx_loc);
     for (unsigned k1 = 0; k1 < nsubwin_; ++k1) {
       EnsemblePtr_ e_k1 =
           EnsemblesCollection_::getInstance()[dxi[k1].validTime()];
       schur_add((*e_k1)[ix], dx_loc, dxo[k1], tmp);
     }
   }
 }
References oops::Increment4D< MODEL >::zero(), and oops::Increment< MODEL >::zero().
advectedMultiplySqrt()
template<typename MODEL > void oops::EnsembleCovariance4DDistributed< MODEL >::advectedMultiplySqrt (const IncrCtlVec_ & dvi, Increment4D_ & dxo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 177 of file EnsembleCovariance4DDistributed.h.
{
   Increment_ dx(dxo[0]);
   Increment_ tmp(dxo[0]);
   EnsemblePtr_ e = EnsemblesCollection_::getInstance()[dxo[0].validTime()];
   dxo.zero();
   for (unsigned l = 0; l < e->size(); ++l) {
     loc_->multiplySqrt(dvi.ensCtlVec(l), dx);
     unsigned ix = get_xb_prim(l);
     for (unsigned k1 = 0; k1 < nsubwin_; ++k1) {
       EnsemblePtr_ e_k1 =
           EnsemblesCollection_::getInstance()[dxo[k1].validTime()];
       schur_add((*e_k1)[ix], dx, dxo[k1], tmp);
     }
   }
 }
References oops::IncrCtlVec< MODEL >::ensCtlVec(), and oops::Increment4D< MODEL >::zero().
advectedMultiplySqrtTrans()
template<typename MODEL > void oops::EnsembleCovariance4DDistributed< MODEL >::advectedMultiplySqrtTrans (const Increment4D_ & dxi, IncrCtlVec_ & dvo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 197 of file EnsembleCovariance4DDistributed.h.
{
   Increment_ dx(dxi[0]);
   Increment_ tmp(dxi[0]);
   EnsemblePtr_ e = EnsemblesCollection_::getInstance()[dxi[0].validTime()];
   for (unsigned l = 0; l < e->size(); ++l) {
     unsigned ix = get_xb_prim(l);
     dx.zero();
     dvo.ensCtlVec(l).zero();
     for (unsigned k2 = 0; k2 < nsubwin_; ++k2) {
       EnsemblePtr_ e_k2 =
           EnsemblesCollection_::getInstance()[dxi[k2].validTime()];
       schur_add((*e_k2)[ix], dxi[k2], dx, tmp);
     }
     loc_->multiplySqrtTrans(dx, dvo.ensCtlVec(l));
   }
 }
References oops::IncrCtlVec< MODEL >::ensCtlVec(), oops::IncrEnsCtlVec< MODEL >::zero(), and oops::Increment< MODEL >::zero().
covar()
template<typename MODEL > const ModelSpaceCovarianceBase<MODEL>& oops::EnsembleCovariance4DDistributed< MODEL >::covar () const inline virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 65 of file EnsembleCovariance4DDistributed.h.
 { return *static_; }
References oops::EnsembleCovariance4DDistributed< MODEL >::static_.
get_xb_prim()
template<typename MODEL > unsigned oops::EnsembleCovariance4DDistributed< MODEL >::get_xb_prim (unsigned l) const private
Definition at line 225 of file EnsembleCovariance4DDistributed.h.
{
   util::MPIWrapper &mpiw = util::MPIWrapper::Instance();
   // Circular permutation that depends on my rank
   unsigned i_xb_prim =
       (mpiw.nb_worlds() - mpiw.my_rank() + l) % mpiw.nb_worlds();
   if (mpiw.my_rank() == i_xb_prim)
     // Nothing to do, since xb_prim is my perturbation
     return 0;
   Log::info() << "EnsembleCovariance4DDistributed.get_xb_prim(): my_rank="
               << mpiw.my_rank() << " get xb_prim=" << i_xb_prim;
   util::MPIThreadPool<Increment_> pool;
   for (unsigned k = 0; k < nsubwin_; k++) {
     EnsemblePtr_ e_k = EnsemblesCollection_::getInstance()[time_[k]];
     pool.add(&(e_k->pack()), &(*e_k)[1]);
   }
   int tag = l;
   pool.send_recv_nb(i_xb_prim, tag);
   // xb_prim is the perturbation I have received and stored in (*e_k)[1])
   return 1;
 }
newIncrEnsCtlVec()
template<typename MODEL > IncrEnsCtlVec_* oops::EnsembleCovariance4DDistributed< MODEL >::newIncrEnsCtlVec () const inline override virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 71 of file EnsembleCovariance4DDistributed.h.
{
     return new IncrEnsCtlVec_(*geom_, *loc_);
   }
References oops::EnsembleCovariance4DDistributed< MODEL >::geom_, and oops::EnsembleCovariance4DDistributed< MODEL >::loc_.
newIncrModCtlVec()
template<typename MODEL > IncrModCtlVec_* oops::EnsembleCovariance4DDistributed< MODEL >::newIncrModCtlVec () const inline override virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 68 of file EnsembleCovariance4DDistributed.h.
{
     return new IncrModCtlVec_();
   }
schur_add()
template<typename MODEL > void oops::EnsembleCovariance4DDistributed< MODEL >::schur_add (const Increment_ & pert, const Increment_ & dxi, Increment_ & dxo, Increment_ & tmp) const private
Definition at line 253 of file EnsembleCovariance4DDistributed.h.
{
   tmp_schur = pert;
   tmp_schur.schur_product_with(dxi);
   dxo.axpy(1.0, tmp_schur, false);
 }
References oops::Increment< MODEL >::axpy(), and oops::Increment< MODEL >::schur_product_with().
Member Data Documentation
config_
template<typename MODEL > const eckit::LocalConfiguration oops::EnsembleCovariance4DDistributed< MODEL >::config_ private
Definition at line 80 of file EnsembleCovariance4DDistributed.h.
geom_
template<typename MODEL > std::unique_ptr<Geometry_> oops::EnsembleCovariance4DDistributed< MODEL >::geom_ private
Definition at line 84 of file EnsembleCovariance4DDistributed.h.
Referenced by oops::EnsembleCovariance4DDistributed< MODEL >::newIncrEnsCtlVec().
loc_
template<typename MODEL > std::unique_ptr<Localization_> oops::EnsembleCovariance4DDistributed< MODEL >::loc_ private
Definition at line 83 of file EnsembleCovariance4DDistributed.h.
Referenced by oops::EnsembleCovariance4DDistributed< MODEL >::newIncrEnsCtlVec().
nsubwin_
template<typename MODEL > unsigned oops::EnsembleCovariance4DDistributed< MODEL >::nsubwin_ private
Definition at line 81 of file EnsembleCovariance4DDistributed.h.
static_
template<typename MODEL > std::unique_ptr<ModelSpaceCovarianceBase<MODEL> > oops::EnsembleCovariance4DDistributed< MODEL >::static_ private
Definition at line 85 of file EnsembleCovariance4DDistributed.h.
Referenced by oops::EnsembleCovariance4DDistributed< MODEL >::covar().
time_
template<typename MODEL > std::vector<util::DateTime> oops::EnsembleCovariance4DDistributed< MODEL >::time_ private
Definition at line 82 of file EnsembleCovariance4DDistributed.h.
The documentation for this class was generated from the following file:
src/oops/base/EnsembleCovariance4DDistributed.h