OOPS Documentation: oops::RinvMatrix< MODEL > Class Template Reference
oops::RinvMatrix< MODEL > Class Template Reference
The \(R^{-1} \) matrix.
#include <RinvMatrix.h>
Public Member Functions
RinvMatrix (const CostFct_ &j)
void multiply (const Dual_ &dx, Dual_ &dy) const
Private Types
using CostFct_ = CostFunction< MODEL >
using Dual_ = DualVector< MODEL >
Private Attributes
CostFct_ const & j_
Detailed Description
template<typename MODEL>
class oops::RinvMatrix< MODEL >
The \(R^{-1} \) matrix.
The solvers represent matrices as objects that implement a "multiply" method. This class defines objects that apply a generalized \(R^{-1} \) matrix which includes \(R^{-1} \) itself and the equivalent operators for the other terms of the cost function.
Definition at line 30 of file RinvMatrix.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::RinvMatrix< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 31 of file RinvMatrix.h.
Dual_
template<typename MODEL > using oops::RinvMatrix< MODEL >::Dual_ = DualVector<MODEL> private
Definition at line 32 of file RinvMatrix.h.
Constructor & Destructor Documentation
RinvMatrix()
template<typename MODEL > oops::RinvMatrix< MODEL >::RinvMatrix (const CostFct_ & j) inline explicit
Definition at line 35 of file RinvMatrix.h.
 : j_(j) {}
Member Function Documentation
multiply()
template<typename MODEL > void oops::RinvMatrix< MODEL >::multiply (const Dual_ & dx, Dual_ & dy) const inline
Definition at line 37 of file RinvMatrix.h.
{
     dy.clear();
     for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
       dy.append(j_.jterm(jj).multiplyCoInv(*dx.getv(jj)));
     }
   }
References oops::DualVector< MODEL >::append(), oops::DualVector< MODEL >::clear(), oops::DualVector< MODEL >::getv(), oops::RinvMatrix< MODEL >::j_, oops::CostFunction< MODEL >::jterm(), oops::CostTermBase< MODEL >::multiplyCoInv(), and oops::CostFunction< MODEL >::nterms().
Referenced by oops::RPCGMinimizer< MODEL >::solve(), and oops::RPLanczosMinimizer< MODEL >::solve().
Member Data Documentation
j_
template<typename MODEL > CostFct_ const& oops::RinvMatrix< MODEL >::j_ private
Definition at line 45 of file RinvMatrix.h.
Referenced by oops::RinvMatrix< MODEL >::multiply().
The documentation for this class was generated from the following file:
src/oops/assimilation/RinvMatrix.h