OOPS Documentation: oops::ObsAuxCovariances< MODEL > Class Template Reference
oops::ObsAuxCovariances< MODEL > Class Template Reference
Encapsulates a vector of ObsAuxCovariance objects.
#include <ObsAuxCovariances.h>
Public Member Functions
ObsAuxCovariances (const ObsSpaces_ &, const eckit::Configuration &)
Constructor.
~ObsAuxCovariances ()
Destructor.
std::size_t size () const
Return the size.
const ObsAuxCovariance_ & operator[] (const std::size_t ii) const
Return a constant reference to the i-th ObsAuxCovariance object.
ObsAuxCovariance_ & operator[] (const std::size_t ii)
Return a reference to the i-th ObsAuxCovariance object.
void update (const ObsAuxControls_ &, const eckit::Configuration &)
Update.
void linearize (const ObsAuxControls_ &, const ObsSpaces_ &)
Set up the inner loop resolution B matrix.
void multiply (const ObsAuxIncrements_ &, ObsAuxIncrements_ &) const
\(dx_1 = B dx_2 \)
void inverseMultiply (const ObsAuxIncrements_ &, ObsAuxIncrements_ &) const
\(dx_1 = B^{-1} dx_2 \)
void multiplySqrt (const ObsAuxCtlVecs_ &, ObsAuxIncrements_ &) const
\(dx = B^{1/2} dv \)
void multiplySqrtTrans (const ObsAuxIncrements_ &, ObsAuxCtlVecs_ &) const
\(dv = [B^{1/2}]^T dx \)
void randomize (ObsAuxIncrements_ &) const
\(dx = B^{1/2} dv_{random} \)
const eckit::LocalConfiguration & config () const
Retrun a constant reference to configuration.
const ObsSpaces_ & obspaces () const
Retrun a constant reference to ObsSpaces.
Static Public Member Functions
static const std::string classname ()
Private Types
using ObsAuxCovariance_ = ObsAuxCovariance< MODEL >
using ObsAuxControls_ = ObsAuxControls< MODEL >
using ObsAuxCtlVecs_ = ObsAuxCtlVecs< MODEL >
using ObsAuxIncrements_ = ObsAuxIncrements< MODEL >
using ObsSpaces_ = ObservationSpaces< MODEL >
Private Member Functions
void print (std::ostream &) const
Private Attributes
std::vector< std::shared_ptr< ObsAuxCovariance_ > > covs_
Vector of shared pointers to ObsAuxCovariance objects.
const ObsSpaces_ * odb_
const eckit::LocalConfiguration conf_
Detailed Description
template<typename MODEL>
class oops::ObsAuxCovariances< MODEL >
Encapsulates a vector of ObsAuxCovariance objects.
An object of ObsAuxCovariances class is part of CostJbTotal. The class contains a vector of ObsAuxCovariance objects. Refer to the documentation of ControlVariable, CostJbTotal and CostJo to understand the structure.
Definition at line 41 of file ObsAuxCovariances.h.
Member Typedef Documentation
ObsAuxControls_
template<typename MODEL > using oops::ObsAuxCovariances< MODEL >::ObsAuxControls_ = ObsAuxControls<MODEL> private
Definition at line 43 of file ObsAuxCovariances.h.
ObsAuxCovariance_
template<typename MODEL > using oops::ObsAuxCovariances< MODEL >::ObsAuxCovariance_ = ObsAuxCovariance<MODEL> private
Definition at line 42 of file ObsAuxCovariances.h.
ObsAuxCtlVecs_
template<typename MODEL > using oops::ObsAuxCovariances< MODEL >::ObsAuxCtlVecs_ = ObsAuxCtlVecs<MODEL> private
Definition at line 44 of file ObsAuxCovariances.h.
ObsAuxIncrements_
template<typename MODEL > using oops::ObsAuxCovariances< MODEL >::ObsAuxIncrements_ = ObsAuxIncrements<MODEL> private
Definition at line 45 of file ObsAuxCovariances.h.
ObsSpaces_
template<typename MODEL > using oops::ObsAuxCovariances< MODEL >::ObsSpaces_ = ObservationSpaces<MODEL> private
Definition at line 46 of file ObsAuxCovariances.h.
Constructor & Destructor Documentation
ObsAuxCovariances()
template<typename MODEL > oops::ObsAuxCovariances< MODEL >::ObsAuxCovariances (const ObsSpaces_ & odb, const eckit::Configuration & conf)
Constructor.
Definition at line 100 of file ObsAuxCovariances.h.
     : covs_(0), odb_(), conf_(conf) {
   Log::trace() << "ObsAuxCovariances<MODEL>::ObsAuxCovariances starting"
                << std::endl;
   odb_ = &odb;
   std::vector<eckit::LocalConfiguration> obsconf;
   conf.get("ObsTypes", obsconf);
   for (std::size_t jobs = 0; jobs < obsconf.size(); ++jobs) {
     std::shared_ptr<ObsAuxCovariance_> tmp(
         new ObsAuxCovariance_(odb[jobs], obsconf[jobs]));
     covs_.push_back(tmp);
   }
   Log::trace() << "ObsAuxCovariances<MODEL>::ObsAuxCovariances done"
                << std::endl;
 }
References oops::ObsAuxCovariances< MODEL >::covs_, and oops::ObsAuxCovariances< MODEL >::odb_.
~ObsAuxCovariances()
template<typename MODEL > oops::ObsAuxCovariances< MODEL >::~ObsAuxCovariances
Destructor.
Definition at line 120 of file ObsAuxCovariances.h.
{
   Log::trace() << "ObsAuxCovariances<MODEL>::~ObsAuxCovariances starting"
                << std::endl;
   odb_ = nullptr;
   for (std::size_t jobs = 0; jobs < covs_.size(); ++jobs) {
     covs_[jobs].reset();
   }
   Log::trace() << "ObsAuxCovariances<MODEL>::~ObsAuxCovariances done"
                << std::endl;
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::ObsAuxCovariances< MODEL >::classname () inline static
Definition at line 49 of file ObsAuxCovariances.h.
 { return "oops::ObsAuxCovariances"; }
config()
template<typename MODEL > const eckit::LocalConfiguration& oops::ObsAuxCovariances< MODEL >::config () const inline
Retrun a constant reference to configuration.
Definition at line 84 of file ObsAuxCovariances.h.
 { return conf_; }
References oops::ObsAuxCovariances< MODEL >::conf_.
inverseMultiply()
template<typename MODEL > void oops::ObsAuxCovariances< MODEL >::inverseMultiply (const ObsAuxIncrements_ & dx1, ObsAuxIncrements_ & dx2) const
\(dx_1 = B^{-1} dx_2 \)
Definition at line 176 of file ObsAuxCovariances.h.
{
   Log::trace() << "ObsAuxCovariances<MODEL>::inverseMultiply starting"
                << std::endl;
   ASSERT(dx1.size() == dx2.size() && covs_.size() == dx1.size());
   for (std::size_t jobs = 0; jobs < dx1.size(); ++jobs) {
     covs_[jobs]->inverseMultiply(dx1[jobs], dx2[jobs]);
   }
   Log::trace() << "ObsAuxCovariances<MODEL>::inverseMultiply done" << std::endl;
 }
References oops::ObsAuxIncrements< MODEL >::size().
Referenced by oops::JbMatrix< MODEL >::multiply(), and oops::BMatrix< MODEL >::multiplyId().
linearize()
template<typename MODEL > void oops::ObsAuxCovariances< MODEL >::linearize (const ObsAuxControls_ & xx, const ObsSpaces_ & odb)
Set up the inner loop resolution B matrix.
Definition at line 149 of file ObsAuxCovariances.h.
{
   Log::trace() << "ObsAuxCovariances<MODEL>::linearize starting" << std::endl;
   odb_ = &odb;
   ASSERT(covs_.size() == xx.size());
   for (std::size_t jobs = 0; jobs < xx.size(); ++jobs) {
     covs_[jobs]->linearize(xx[jobs]);
   }
   Log::trace() << "ObsAuxCovariances<MODEL>::linearize done" << std::endl;
 }
References oops::ObsAuxControls< MODEL >::size().
multiply()
template<typename MODEL > void oops::ObsAuxCovariances< MODEL >::multiply (const ObsAuxIncrements_ & dx1, ObsAuxIncrements_ & dx2) const
\(dx_1 = B dx_2 \)
Definition at line 163 of file ObsAuxCovariances.h.
{
   Log::trace() << "ObsAuxCovariances<MODEL>::multiply starting" << std::endl;
   ASSERT(dx1.size() == dx2.size() && covs_.size() == dx1.size());
   for (std::size_t jobs = 0; jobs < dx1.size(); ++jobs) {
     covs_[jobs]->multiply(dx1[jobs], dx2[jobs]);
   }
   Log::trace() << "ObsAuxCovariances<MODEL>::multiply done" << std::endl;
 }
References oops::ObsAuxIncrements< MODEL >::size().
multiplySqrt()
template<typename MODEL > void oops::ObsAuxCovariances< MODEL >::multiplySqrt (const ObsAuxCtlVecs_ & dv, ObsAuxIncrements_ & dx) const
\(dx = B^{1/2} dv \)
Definition at line 190 of file ObsAuxCovariances.h.
{
   Log::trace() << "ObsAuxCovariances<MODEL>::multiplySqrt starting"
                << std::endl;
   ASSERT(dv.size() == dx.size() && covs_.size() == dx.size());
   for (std::size_t jobs = 0; jobs < dx.size(); ++jobs) {
     covs_[jobs]->multiplySqrt(dv[jobs], dx[jobs]);
   }
   Log::trace() << "ObsAuxCovariances<MODEL>::multiplySqrt done" << std::endl;
 }
References oops::ObsAuxIncrements< MODEL >::size(), and oops::ObsAuxCtlVecs< MODEL >::size().
Referenced by oops::JbMatrix< MODEL >::multiply(), oops::BMatrix< MODEL >::multiplyB(), and oops::BMatrix< MODEL >::multiplyId().
multiplySqrtTrans()
template<typename MODEL > void oops::ObsAuxCovariances< MODEL >::multiplySqrtTrans (const ObsAuxIncrements_ & dx, ObsAuxCtlVecs_ & dv) const
\(dv = [B^{1/2}]^T dx \)
Definition at line 204 of file ObsAuxCovariances.h.
{
   Log::trace() << "ObsAuxCovariances<MODEL>::multiplySqrtTrans starting"
                << std::endl;
   ASSERT(dv.size() == dx.size() && covs_.size() == dx.size());
   for (std::size_t jobs = 0; jobs < dx.size(); ++jobs) {
     covs_[jobs]->multiplySqrtTrans(dx[jobs], dv[jobs]);
   }
   Log::trace() << "ObsAuxCovariances<MODEL>::multiplySqrtTrans done"
                << std::endl;
 }
References oops::ObsAuxIncrements< MODEL >::size(), and oops::ObsAuxCtlVecs< MODEL >::size().
Referenced by oops::JbMatrix< MODEL >::multiply(), oops::BMatrix< MODEL >::multiplyB(), and oops::BMatrix< MODEL >::multiplyId().
obspaces()
template<typename MODEL > const ObsSpaces_& oops::ObsAuxCovariances< MODEL >::obspaces () const inline
Retrun a constant reference to ObsSpaces.
Definition at line 86 of file ObsAuxCovariances.h.
 { return *odb_; }
References oops::ObsAuxCovariances< MODEL >::odb_.
operator[]() [1/2]
template<typename MODEL > ObsAuxCovariance_& oops::ObsAuxCovariances< MODEL >::operator[] (const std::size_t ii) inline
Return a reference to the i-th ObsAuxCovariance object.
Definition at line 64 of file ObsAuxCovariances.h.
 { return *covs_.at(ii); }
References oops::ObsAuxCovariances< MODEL >::covs_.
operator[]() [2/2]
template<typename MODEL > const ObsAuxCovariance_& oops::ObsAuxCovariances< MODEL >::operator[] (const std::size_t ii) const inline
Return a constant reference to the i-th ObsAuxCovariance object.
Definition at line 60 of file ObsAuxCovariances.h.
{
     return *covs_.at(ii);
   }
References oops::ObsAuxCovariances< MODEL >::covs_.
print()
template<typename MODEL > void oops::ObsAuxCovariances< MODEL >::print (std::ostream & os) const private
Definition at line 231 of file ObsAuxCovariances.h.
{
   Log::trace() << "ObsAuxCovariances<MODEL>::print starting" << std::endl;
   for (std::size_t jobs = 0; jobs < covs_.size(); ++jobs)
     os << *covs_.at(jobs) << " ";
   Log::trace() << "ObsAuxCovariances<MODEL>::print done" << std::endl;
 }
randomize()
template<typename MODEL > void oops::ObsAuxCovariances< MODEL >::randomize (ObsAuxIncrements_ & dx) const
\(dx = B^{1/2} dv_{random} \)
Definition at line 219 of file ObsAuxCovariances.h.
{
   Log::trace() << "ObsAuxCovariances<MODEL>::randomize starting" << std::endl;
   ASSERT(covs_.size() == dx.size());
   for (std::size_t jobs = 0; jobs < dx.size(); ++jobs) {
     covs_[jobs]->randomize(dx[jobs]);
   }
   Log::trace() << "ObsAuxCovariances<MODEL>::randomize done" << std::endl;
 }
References oops::ObsAuxIncrements< MODEL >::size().
size()
template<typename MODEL > std::size_t oops::ObsAuxCovariances< MODEL >::size () const inline
Return the size.
Definition at line 58 of file ObsAuxCovariances.h.
 { return covs_.size(); }
References oops::ObsAuxCovariances< MODEL >::covs_.
Referenced by oops::ObsAuxCtlVecs< MODEL >::ObsAuxCtlVecs().
update()
template<typename MODEL > void oops::ObsAuxCovariances< MODEL >::update (const ObsAuxControls_ & xx, const eckit::Configuration & conf)
Update.
Definition at line 134 of file ObsAuxCovariances.h.
{
   Log::trace() << "ObsAuxCovariances<MODEL>::update starting" << std::endl;
   std::vector<eckit::LocalConfiguration> obsconf;
   conf.get("covariancesObsAux", obsconf);
   ASSERT(covs_.size() == xx.size());
   for (std::size_t jobs = 0; jobs < xx.size(); ++jobs) {
     covs_[jobs]->update(xx[jobs], obsconf[jobs]);
   }
   Log::trace() << "ObsAuxCovariances<MODEL>::update done" << std::endl;
 }
References oops::ObsAuxControls< MODEL >::size().
Member Data Documentation
conf_
template<typename MODEL > const eckit::LocalConfiguration oops::ObsAuxCovariances< MODEL >::conf_ private
Definition at line 94 of file ObsAuxCovariances.h.
Referenced by oops::ObsAuxCovariances< MODEL >::config().
covs_
template<typename MODEL > std::vector<std::shared_ptr<ObsAuxCovariance_> > oops::ObsAuxCovariances< MODEL >::covs_ private
Vector of shared pointers to ObsAuxCovariance objects.
Definition at line 92 of file ObsAuxCovariances.h.
Referenced by oops::ObsAuxCovariances< MODEL >::ObsAuxCovariances(), oops::ObsAuxCovariances< MODEL >::operator[](), and oops::ObsAuxCovariances< MODEL >::size().
odb_
template<typename MODEL > const ObsSpaces_* oops::ObsAuxCovariances< MODEL >::odb_ mutable private
Definition at line 93 of file ObsAuxCovariances.h.
Referenced by oops::ObsAuxCovariances< MODEL >::ObsAuxCovariances(), and oops::ObsAuxCovariances< MODEL >::obspaces().
The documentation for this class was generated from the following file:
src/oops/base/ObsAuxCovariances.h