OOPS Documentation: oops::Locations< MODEL > Class Template Reference
oops::Locations< MODEL > Class Template Reference
Encapsulates the observation locations.
#include <Locations.h>
Public Member Functions
Locations (const ObservationSpace< MODEL > &, const util::DateTime &, const util::DateTime &)
Constructor.
~Locations ()
Destructor.
const Locations_ & locations () const
Return a constant reference to model specific locations.
Static Public Member Functions
static const std::string classname ()
Private Types
using Locations_ = typename MODEL::Locations
Private Member Functions
void print (std::ostream &) const
Private Attributes
std::unique_ptr< Locations_ > locs_
Pointer to model specific locations.
Detailed Description
template<typename MODEL>
class oops::Locations< MODEL >
Encapsulates the observation locations.
Locations of observations are extracted from ObservationSpace. Locations are passed to the interpolate and interpolateTL/AD methods of the State and Increment, respectively, in order to interpolate the model fields to observation locations (GeoVaLs).
Definition at line 37 of file Locations.h.
Member Typedef Documentation
Locations_
template<typename MODEL > using oops::Locations< MODEL >::Locations_ = typename MODEL::Locations private
Definition at line 39 of file Locations.h.
Constructor & Destructor Documentation
Locations()
template<typename MODEL > oops::Locations< MODEL >::Locations (const ObservationSpace< MODEL > & os, const util::DateTime & t1, const util::DateTime & t2)
Constructor.
Construct Locations by extracting the locations of observations from ObservationSpace for a time slot defined by (t1,t2] or [t1,t2).
Definition at line 63 of file Locations.h.
     : locs_() {
   Log::trace() << "Locations<MODEL>::Locations starting" << std::endl;
   util::Timer timer(classname(), "Locations");
   locs_.reset(new Locations_(os.observationspace(), t1, t2));
   Log::trace() << "Locations<MODEL>::Locations done" << std::endl;
 }
References oops::Locations< MODEL >::classname(), oops::Locations< MODEL >::locs_, and oops::ObservationSpace< MODEL >::observationspace().
~Locations()
template<typename MODEL > oops::Locations< MODEL >::~Locations
Destructor.
Definition at line 78 of file Locations.h.
{
   Log::trace() << "Locations<MODEL>::~Locations starting" << std::endl;
   util::Timer timer(classname(), "~Locations");
   locs_.reset();
   Log::trace() << "Locations<MODEL>::~Locations done" << std::endl;
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::Locations< MODEL >::classname () inline static
Definition at line 42 of file Locations.h.
 { return "oops::Locations"; }
Referenced by oops::Locations< MODEL >::Locations().
locations()
template<typename MODEL > const Locations_& oops::Locations< MODEL >::locations () const inline
Return a constant reference to model specific locations.
Definition at line 52 of file Locations.h.
 { return *locs_; }
References oops::Locations< MODEL >::locs_.
Referenced by oops::State< MODEL >::interpolate(), oops::Increment< MODEL >::interpolateAD(), and oops::Increment< MODEL >::interpolateTL().
print()
template<typename MODEL > void oops::Locations< MODEL >::print (std::ostream & os) const private
Definition at line 88 of file Locations.h.
{
   Log::trace() << "Locations<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   Log::trace() << "Locations<MODEL>::print done" << std::endl;
 }
Member Data Documentation
locs_
template<typename MODEL > std::unique_ptr<Locations_> oops::Locations< MODEL >::locs_ private
Pointer to model specific locations.
Definition at line 57 of file Locations.h.
Referenced by oops::Locations< MODEL >::Locations(), and oops::Locations< MODEL >::locations().
The documentation for this class was generated from the following file:
src/oops/interface/Locations.h