OOPS Documentation: oops::CostJb3D< MODEL > Class Template Reference
oops::CostJb3D< MODEL > Class Template Reference
CostJb3D encapsulates the state component of the Jb term of the cost function for a 3 dimensional background (3/4D-Var).
#include <CostJb3D.h>
Public Member Functions
CostJb3D (const eckit::Configuration &, const Geometry_ &, const Variables_ &, const util::Duration &, const State_ &)
Construct \(J_b\).
virtual ~CostJb3D ()
Destructor.
JqTerm< MODEL > * initializeJq () const override
Empty Jq observer.
void computeIncrement (const State4D_ &, const State4D_ &, Increment4D_ &) const override
Get increment from state (usually first guess).
void linearize (const State4D_ &, const Geometry_ &) override
Linearize before the linear computations.
void linearize (const State4D_ &, const Geometry_ &, const eckit::Configuration &) override
void addGradient (const Increment4D_ &, Increment4D_ &, Increment4D_ &) const override
Add Jb gradient.
JqTermTL< MODEL > * initializeJqTL () const override
Empty TL Jq observer.
JqTermAD< MODEL > * initializeJqAD (const Increment4D_ &) const override
Empty AD Jq observer.
void Bmult (const Increment4D_ &, Increment4D_ &) const override
Multiply by \(B\).
void Bminv (const Increment4D_ &, Increment4D_ &) const override
Multiply by \(B^{-1}\).
void BmultSqrt (const IncrCtlVec4D_ &, Increment4D_ &) const override
Multiply by \(B^{1/2}\).
void BmultSqrtTrans (const Increment4D_ &, IncrCtlVec4D_ &) const override
Multiply by \([B^{1/2}]^T\).
void randomize (Increment4D_ &) const override
Randomize.
const ModelSpaceCovarianceBase< MODEL > & covar () const
Access to B.
unsigned int nstates () const override
Return size of the state component of the control variable.
Increment_ * newStateIncrement (const unsigned int) const override
Create new increment (set to 0).
unsigned int nchistates () const override
Return size of the state component of the control vector.
IncrCtlVec_ * newIncrCtlVec (const unsigned int) const override
Create new control vector.
IncrModCtlVec_ * newIncrModCtlVec () const override
Create new control vector (mod)
IncrEnsCtlVec_ * newIncrEnsCtlVec () const override
Create new control vector (ens)
Public Member Functions inherited from oops::CostJbState< MODEL >
CostJbState ()
Constructor.
virtual ~CostJbState ()
Destructor.
Private Types
using CtrlInc_ = ControlIncrement< MODEL >
using Increment_ = Increment< MODEL >
using Increment4D_ = Increment4D< MODEL >
using IncrCtlVec_ = IncrCtlVec< MODEL >
using IncrCtlVec4D_ = IncrCtlVec4D< MODEL >
using IncrModCtlVec_ = IncrModCtlVec< MODEL >
using IncrEnsCtlVec_ = IncrEnsCtlVec< MODEL >
using Geometry_ = Geometry< MODEL >
using State_ = State< MODEL >
using State4D_ = State4D< MODEL >
using Variables_ = Variables< MODEL >
Private Attributes
std::unique_ptr< ModelSpaceCovarianceBase< MODEL > > B_
B matrix pointer.
const util::Duration winLength_
Window length.
const Variables_ controlvars_
Control variables.
std::unique_ptr< const Geometry_ > resol_
Pointer to the geometry.
std::unique_ptr< const util::DateTime > time_
Valid time pointer.
Detailed Description
template<typename MODEL>
class oops::CostJb3D< MODEL >
CostJb3D encapsulates the state component of the Jb term of the cost function for a 3 dimensional background (3/4D-Var).
CostJb3D class is not really necessary since it is only a special case of the more general CostJbJq weak constraint term with one sub-window. It is provided for readability.
Consider applying the matrix vector product:
\[ B_{state} dx_{state} = \begin{bmatrix} B_0 \end{bmatrix} \begin{bmatrix} dx_0 \end{bmatrix} \]
\(-> dx_0 \) is implemented by Increment4D containing a single Increment,
 \f$ -> B_{state} \f$, is implemented through the ModelSpaceCovarianceBase
class; ModelSpaceCovarianceBase is a pure abstract base class for a model
space background error covariance matrix. The following classes inherit
from it:
  - ErrorCovariance - implements a modelled covariance matrix;
  - EnsembleCovariance - implements a localized ensemble covariance matrix;
  - HybridCovariance - implements a hybrid covariance matrix;
Definition at line 78 of file CostJb3D.h.
Member Typedef Documentation
CtrlInc_
template<typename MODEL > using oops::CostJb3D< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 79 of file CostJb3D.h.
Geometry_
template<typename MODEL > using oops::CostJb3D< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 86 of file CostJb3D.h.
IncrCtlVec4D_
template<typename MODEL > using oops::CostJb3D< MODEL >::IncrCtlVec4D_ = IncrCtlVec4D<MODEL> private
Definition at line 83 of file CostJb3D.h.
IncrCtlVec_
template<typename MODEL > using oops::CostJb3D< MODEL >::IncrCtlVec_ = IncrCtlVec<MODEL> private
Definition at line 82 of file CostJb3D.h.
Increment4D_
template<typename MODEL > using oops::CostJb3D< MODEL >::Increment4D_ = Increment4D<MODEL> private
Definition at line 81 of file CostJb3D.h.
Increment_
template<typename MODEL > using oops::CostJb3D< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 80 of file CostJb3D.h.
IncrEnsCtlVec_
template<typename MODEL > using oops::CostJb3D< MODEL >::IncrEnsCtlVec_ = IncrEnsCtlVec<MODEL> private
Definition at line 85 of file CostJb3D.h.
IncrModCtlVec_
template<typename MODEL > using oops::CostJb3D< MODEL >::IncrModCtlVec_ = IncrModCtlVec<MODEL> private
Definition at line 84 of file CostJb3D.h.
State4D_
template<typename MODEL > using oops::CostJb3D< MODEL >::State4D_ = State4D<MODEL> private
Definition at line 88 of file CostJb3D.h.
State_
template<typename MODEL > using oops::CostJb3D< MODEL >::State_ = State<MODEL> private
Definition at line 87 of file CostJb3D.h.
Variables_
template<typename MODEL > using oops::CostJb3D< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 89 of file CostJb3D.h.
Constructor & Destructor Documentation
CostJb3D()
template<typename MODEL > oops::CostJb3D< MODEL >::CostJb3D (const eckit::Configuration & config, const Geometry_ & resolouter, const Variables_ & ctlvars, const util::Duration & len, const State_ & xb)
Construct \(J_b\).
The B matrix (either ErrorCovariance [modelled B matrix], EnsembleCovariance or HybridCovariance is produced by the CovarianceFactory class.
Definition at line 176 of file CostJb3D.h.
     : B_(CovarianceFactory<MODEL>::create(
           eckit::LocalConfiguration(config, "Covariance"), resolouter, ctlvars,
           xb)),
       winLength_(len),
       controlvars_(ctlvars),
       resol_(),
       time_() {
   Log::trace() << "CostJb3D constructed." << std::endl;
 }
~CostJb3D()
template<typename MODEL > virtual oops::CostJb3D< MODEL >::~CostJb3D () inline virtual
Destructor.
Definition at line 97 of file CostJb3D.h.
 {}
Member Function Documentation
addGradient()
template<typename MODEL > void oops::CostJb3D< MODEL >::addGradient (const Increment4D_ & dxFG, Increment4D_ & grad, Increment4D_ & gradJb) const override virtual
Add Jb gradient.
Add the Jb component of the first guess gradient
Implements oops::CostJbState< MODEL >.
Definition at line 228 of file CostJb3D.h.
{
   grad -= gradJb;
 }
Bminv()
template<typename MODEL > void oops::CostJb3D< MODEL >::Bminv (const Increment4D_ & dxin, Increment4D_ & dxout) const override virtual
Multiply by \(B^{-1}\).
Implements oops::CostJbState< MODEL >.
Definition at line 245 of file CostJb3D.h.
{
   Log::warning() << "*** B inverse might not always exist ***" << std::endl;
   B_->inverseMultiply(dxin[0], dxout[0]);
   Log::warning() << "*** B inverse might not always exist ***" << std::endl;
 }
Bmult()
template<typename MODEL > void oops::CostJb3D< MODEL >::Bmult (const Increment4D_ & dxin, Increment4D_ & dxout) const override virtual
Multiply by \(B\).
Implements oops::CostJbState< MODEL >.
Definition at line 237 of file CostJb3D.h.
{
   B_->multiply(dxin[0], dxout[0]);
 }
BmultSqrt()
template<typename MODEL > void oops::CostJb3D< MODEL >::BmultSqrt (const IncrCtlVec4D_ & dv, Increment4D_ & dxout) const override virtual
Multiply by \(B^{1/2}\).
Implements oops::CostJbState< MODEL >.
Definition at line 255 of file CostJb3D.h.
{
   B_->multiplySqrt(dv[0], dxout[0]);
 }
BmultSqrtTrans()
template<typename MODEL > void oops::CostJb3D< MODEL >::BmultSqrtTrans (const Increment4D_ & dxin, IncrCtlVec4D_ & dv) const override virtual
Multiply by \([B^{1/2}]^T\).
Implements oops::CostJbState< MODEL >.
Definition at line 263 of file CostJb3D.h.
{
   B_->multiplySqrtTrans(dxin[0], dv[0]);
 }
computeIncrement()
template<typename MODEL > void oops::CostJb3D< MODEL >::computeIncrement (const State4D_ & xb, const State4D_ & fg, Increment4D_ & dx) const override virtual
Get increment from state (usually first guess).
Compute \(dx = x_{fg} - x_{b} \)
Implements oops::CostJbState< MODEL >.
Definition at line 219 of file CostJb3D.h.
{
   dx.diff(fg, xb);
 }
References oops::Increment4D< MODEL >::diff().
covar()
template<typename MODEL > const ModelSpaceCovarianceBase<MODEL>& oops::CostJb3D< MODEL >::covar () const inline virtual
Access to B.
Implements oops::CostJbState< MODEL >.
Definition at line 138 of file CostJb3D.h.
 { return *B_; }
References oops::CostJb3D< MODEL >::B_.
initializeJq()
template<typename MODEL > JqTerm<MODEL>* oops::CostJb3D< MODEL >::initializeJq () const inline override virtual
Empty Jq observer.
Implements oops::CostJbState< MODEL >.
Definition at line 100 of file CostJb3D.h.
 { return 0; }
initializeJqAD()
template<typename MODEL > JqTermAD<MODEL>* oops::CostJb3D< MODEL >::initializeJqAD (const Increment4D_ &) const inline override virtual
Empty AD Jq observer.
Implements oops::CostJbState< MODEL >.
Definition at line 118 of file CostJb3D.h.
{
     return 0;
   }
initializeJqTL()
template<typename MODEL > JqTermTL<MODEL>* oops::CostJb3D< MODEL >::initializeJqTL () const inline override virtual
Empty TL Jq observer.
Implements oops::CostJbState< MODEL >.
Definition at line 115 of file CostJb3D.h.
 { return 0; }
linearize() [1/2]
template<typename MODEL > void oops::CostJb3D< MODEL >::linearize (const State4D_ & fg, const Geometry_ & resolinner) override virtual
Linearize before the linear computations.
Set up the inner loop geometry and construct the B matrix
Implements oops::CostJbState< MODEL >.
Definition at line 197 of file CostJb3D.h.
{
   ASSERT(fg.checkStatesNumber(1));
   resol_.reset(new Geometry_(resolinner));
   time_.reset(new util::DateTime(fg[0].validTime()));
   B_->linearize(fg[0], *resol_);
 }
References oops::State4D< MODEL >::checkStatesNumber().
linearize() [2/2]
template<typename MODEL > void oops::CostJb3D< MODEL >::linearize (const State4D_ & fg, const Geometry_ & resolinner, const eckit::Configuration & innerconf) override virtual
Reimplemented from oops::CostJbState< MODEL >.
Definition at line 210 of file CostJb3D.h.
{
   ASSERT(fg.checkStatesNumber(1));
   resol_.reset(new Geometry_(resolinner));
   time_.reset(new util::DateTime(fg[0].validTime()));
   B_->linearize(fg[0], *resol_, innerconf);
 }
References oops::State4D< MODEL >::checkStatesNumber().
nchistates()
template<typename MODEL > unsigned int oops::CostJb3D< MODEL >::nchistates () const inline override virtual
Return size of the state component of the control vector.
Implements oops::CostJbState< MODEL >.
Definition at line 147 of file CostJb3D.h.
 { return 1; }
newIncrCtlVec()
template<typename MODEL > IncrCtlVec< MODEL > * oops::CostJb3D< MODEL >::newIncrCtlVec (const unsigned int isub) const override virtual
Create new control vector.
Return a new state component of the control vector
Implements oops::CostJbState< MODEL >.
Definition at line 287 of file CostJb3D.h.
{
   return new IncrCtlVec_(*this, *time_);
 }
newIncrEnsCtlVec()
template<typename MODEL > IncrEnsCtlVec_* oops::CostJb3D< MODEL >::newIncrEnsCtlVec () const inline override virtual
Create new control vector (ens)
Implements oops::CostJbState< MODEL >.
Definition at line 158 of file CostJb3D.h.
{
     return B_->newIncrEnsCtlVec();
   }
References oops::CostJb3D< MODEL >::B_.
newIncrModCtlVec()
template<typename MODEL > IncrModCtlVec_* oops::CostJb3D< MODEL >::newIncrModCtlVec () const inline override virtual
Create new control vector (mod)
Implements oops::CostJbState< MODEL >.
Definition at line 153 of file CostJb3D.h.
{
     return B_->newIncrModCtlVec();
   }
References oops::CostJb3D< MODEL >::B_.
newStateIncrement()
template<typename MODEL > Increment< MODEL > * oops::CostJb3D< MODEL >::newStateIncrement (const unsigned int) const override virtual
Create new increment (set to 0).
Return a new increment with control variables at the inner loop resolution
Implements oops::CostJbState< MODEL >.
Definition at line 278 of file CostJb3D.h.
{
   Increment_ *incr = new Increment_(*resol_, controlvars_, *time_);
   return incr;
 }
nstates()
template<typename MODEL > unsigned int oops::CostJb3D< MODEL >::nstates () const inline override virtual
Return size of the state component of the control variable.
Implements oops::CostJbState< MODEL >.
Definition at line 141 of file CostJb3D.h.
 { return 1; }
randomize()
template<typename MODEL > void oops::CostJb3D< MODEL >::randomize (Increment4D_ & dx) const override virtual
Randomize.
Implements oops::CostJbState< MODEL >.
Definition at line 271 of file CostJb3D.h.
{
   B_->randomize(dx[0]);
 }
Member Data Documentation
B_
template<typename MODEL > std::unique_ptr<ModelSpaceCovarianceBase<MODEL> > oops::CostJb3D< MODEL >::B_ private
B matrix pointer.
Definition at line 163 of file CostJb3D.h.
Referenced by oops::CostJb3D< MODEL >::covar(), oops::CostJb3D< MODEL >::newIncrEnsCtlVec(), and oops::CostJb3D< MODEL >::newIncrModCtlVec().
controlvars_
template<typename MODEL > const Variables_ oops::CostJb3D< MODEL >::controlvars_ private
Control variables.
Definition at line 165 of file CostJb3D.h.
resol_
template<typename MODEL > std::unique_ptr<const Geometry_> oops::CostJb3D< MODEL >::resol_ private
Pointer to the geometry.
Definition at line 166 of file CostJb3D.h.
time_
template<typename MODEL > std::unique_ptr<const util::DateTime> oops::CostJb3D< MODEL >::time_ private
Valid time pointer.
Definition at line 167 of file CostJb3D.h.
winLength_
template<typename MODEL > const util::Duration oops::CostJb3D< MODEL >::winLength_ private
Window length.
Definition at line 164 of file CostJb3D.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/CostJb3D.h