OOPS Documentation: oops::IncrCtlVec4D< MODEL > Class Template Reference
oops::IncrCtlVec4D< MODEL > Class Template Reference
IncrCtlVec4D class.
#include <CostJbState.h>
Public Member Functions
IncrCtlVec4D (const JbState_ &)
Constructor.
IncrCtlVec4D (const JbState_ &, const IncrCtlVec4D &)
Constructor with copy initialization.
IncrCtlVec4D (const IncrCtlVec4D &, const bool copy=true)
Copy constructor.
virtual ~IncrCtlVec4D ()
Destructor.
IncrCtlVec_ & operator[] (const int ii)
Return reference to the component corresponding to i-th sub-window.
const IncrCtlVec_ & operator[] (const int ii) const
int first () const
Return the index of the first component.
int last () const
Return the index of the last component.
void zero ()
\(dv_1 = 0 \)
IncrCtlVec4D & operator= (const IncrCtlVec4D &)
\(dv_1 = dv_2 \)
IncrCtlVec4D & operator+= (const IncrCtlVec4D &)
\(dv_1 = dv_1 + dv_2 \)
IncrCtlVec4D & operator-= (const IncrCtlVec4D &)
\(dv_1 = dv_1 - dv_2 \)
IncrCtlVec4D & operator*= (const double &)
\(dv_1 = dv_1 * c \)
void axpy (const double &, const IncrCtlVec4D &, const bool check=true)
\(dv_1 = dv_1 * c dv_2 \)
double dot_product_with (const IncrCtlVec4D &) const
\(<dv_1,dv_1> = dv_1^T dv_1 \)
void schur_product_with (const IncrCtlVec4D &)
Hadamard product (element-wise)
void random ()
Random control vector.
void read (const eckit::Configuration &)
Read control vector.
void write (const eckit::Configuration &) const
Write control vector.
double norm () const
L-2 norm.
Static Public Member Functions
static const std::string classname ()
Private Types
using Geometry_ = Geometry< MODEL >
using IncrCtlVec_ = IncrCtlVec< MODEL >
using JbState_ = CostJbState< MODEL >
using iter_ = typename std::map< int, std::unique_ptr< IncrCtlVec_ > >::iterator
Iterator over a map of IncrCtlVec.
using icst_ = typename std::map< int, std::unique_ptr< IncrCtlVec_ > >::const_iterator
Constant iterator over a map of IncrCtlVec.
Private Member Functions
IncrCtlVec_ & get (const int)
Return reference to the component corresponding to i-th sub-window.
const IncrCtlVec_ & get (const int) const
void print (std::ostream &) const
Private Attributes
std::map< int, std::unique_ptr< IncrCtlVec_ > > incrCtlVec4d_
Map of IncrCtlVec (key: integer; value: IncrCtlVec pointer)
int first_
Index of the first control vector.
int last_
Index of the last control vector.
Detailed Description
template<typename MODEL>
class oops::IncrCtlVec4D< MODEL >
IncrCtlVec4D class.
State part of the control vector. It has a 4D structure:
\[ dv = \begin{bmatrix} dv^0 \\ .. \\ dv^K \\ .. \\ dv^M \\ \end{bmatrix} \]
where \(dv^K \) corresponds to the K-th sub-window and is defined as:
\[ dv^K = \begin{bmatrix} dv^K_{mod} \\ dv^K_{ens} \end{bmatrix} \]
-> \(dv^K \) is implemented by IncrCtlVec
Definition at line 36 of file CostJbState.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::IncrCtlVec4D< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 60 of file IncrCtlVec4D.h.
icst_
template<typename MODEL > using oops::IncrCtlVec4D< MODEL >::icst_ = typename std::map<int, std::unique_ptr<IncrCtlVec_> >::const_iterator private
Constant iterator over a map of IncrCtlVec.
Definition at line 127 of file IncrCtlVec4D.h.
IncrCtlVec_
template<typename MODEL > using oops::IncrCtlVec4D< MODEL >::IncrCtlVec_ = IncrCtlVec<MODEL> private
Definition at line 61 of file IncrCtlVec4D.h.
iter_
template<typename MODEL > using oops::IncrCtlVec4D< MODEL >::iter_ = typename std::map<int, std::unique_ptr<IncrCtlVec_> >::iterator private
Iterator over a map of IncrCtlVec.
Definition at line 124 of file IncrCtlVec4D.h.
JbState_
template<typename MODEL > using oops::IncrCtlVec4D< MODEL >::JbState_ = CostJbState<MODEL> private
Definition at line 62 of file IncrCtlVec4D.h.
Constructor & Destructor Documentation
IncrCtlVec4D() [1/3]
template<typename MODEL > oops::IncrCtlVec4D< MODEL >::IncrCtlVec4D (const JbState_ & jb) explicit
Constructor.
Constructor, destructor.
Definition at line 141 of file IncrCtlVec4D.h.
     : incrCtlVec4d_(), first_(0), last_(jb.nchistates() - 1) {
   for (int jsub = 0; jsub <= last_; ++jsub) {
     std::unique_ptr<IncrCtlVec_> incrCtlVec(jb.newIncrCtlVec(jsub));
     incrCtlVec4d_.emplace(jsub, std::move(incrCtlVec));
   }
   Log::trace() << "IncrCtlVec4D<MODEL>::IncrCtlVec4D created" << std::endl;
 }
References oops::IncrCtlVec4D< MODEL >::incrCtlVec4d_, oops::IncrCtlVec4D< MODEL >::last_, and oops::CostJbState< MODEL >::newIncrCtlVec().
IncrCtlVec4D() [2/3]
template<typename MODEL > oops::IncrCtlVec4D< MODEL >::IncrCtlVec4D (const JbState_ & jb, const IncrCtlVec4D< MODEL > & other)
Constructor with copy initialization.
Definition at line 153 of file IncrCtlVec4D.h.
     : incrCtlVec4d_(), first_(0), last_(jb.nchistates() - 1) {
   for (int jsub = 0; jsub <= last_; ++jsub) {
     IncrCtlVec_ *incrCtlVec = jb.newIncrCtlVec(jsub);
     incrCtlVec4d_.insert(jsub, incrCtlVec);
     incrCtlVec4d_[jsub] = other.incrCtlVec4d_[jsub];
   }
   Log::trace() << "IncrCtlVec4D<MODEL>::IncrCtlVec4D done" << std::endl;
 }
References oops::IncrCtlVec4D< MODEL >::incrCtlVec4d_, oops::IncrCtlVec4D< MODEL >::last_, and oops::CostJbState< MODEL >::newIncrCtlVec().
IncrCtlVec4D() [3/3]
template<typename MODEL > oops::IncrCtlVec4D< MODEL >::IncrCtlVec4D (const IncrCtlVec4D< MODEL > & other, const bool copy = true)
Copy constructor.
Definition at line 167 of file IncrCtlVec4D.h.
     : incrCtlVec4d_(), first_(0), last_(other.last_) {
   for (int jsub = 0; jsub <= last_; ++jsub) {
     std::unique_ptr<IncrCtlVec_> incrCtlVec(new IncrCtlVec_(other[jsub]));
     incrCtlVec4d_.emplace(jsub, std::move(incrCtlVec));
   }
   Log::trace() << "IncrCtlVec4D<MODEL>::IncrCtlVec4D copy done" << std::endl;
 }
References oops::IncrCtlVec4D< MODEL >::incrCtlVec4d_, and oops::IncrCtlVec4D< MODEL >::last_.
~IncrCtlVec4D()
template<typename MODEL > oops::IncrCtlVec4D< MODEL >::~IncrCtlVec4D virtual
Destructor.
Definition at line 180 of file IncrCtlVec4D.h.
{
   Log::trace() << "IncrCtlVec4D<MODEL>::~IncrCtlVec4D starting" << std::endl;
   Log::trace() << "IncrCtlVec4D<MODEL>::~IncrCtlVec4D done" << std::endl;
 }
Member Function Documentation
axpy()
template<typename MODEL > void oops::IncrCtlVec4D< MODEL >::axpy (const double & zz, const IncrCtlVec4D< MODEL > & rhs, const bool check = true)
\(dv_1 = dv_1 * c dv_2 \)
Definition at line 282 of file IncrCtlVec4D.h.
{
   Log::trace() << "IncrCtlVec4D<MODEL>::axpy starting" << std::endl;
   util::Timer timer(classname(), "axpy");
   for (iter_ jsub = incrCtlVec4d_.begin(); jsub != incrCtlVec4d_.end();
        ++jsub) {
     jsub->second->axpy(zz, rhs[jsub->first]);
   }
   Log::trace() << "IncrCtlVec4D<MODEL>::axpy done" << std::endl;
 }
classname()
template<typename MODEL > static const std::string oops::IncrCtlVec4D< MODEL >::classname () inline static
Definition at line 65 of file IncrCtlVec4D.h.
 { return "oops::IncrCtlVec4D"; }
dot_product_with()
template<typename MODEL > double oops::IncrCtlVec4D< MODEL >::dot_product_with (const IncrCtlVec4D< MODEL > & dv) const
\(<dv_1,dv_1> = dv_1^T dv_1 \)
Definition at line 298 of file IncrCtlVec4D.h.
{
   Log::trace() << "IncrCtlVec4D<MODEL>::dot_product_with starting" << std::endl;
   util::Timer timer(classname(), "dot_product_with");
   double zz = 0.0;
   for (icst_ jsub = incrCtlVec4d_.begin(); jsub != incrCtlVec4d_.end();
        ++jsub) {
     zz += dot_product(*jsub->second, dv[jsub->first]);
   }
   Log::trace() << "IncrCtlVec4D<MODEL>::dot_product_with done" << std::endl;
   return zz;
 }
References dot_product().
first()
template<typename MODEL > int oops::IncrCtlVec4D< MODEL >::first () const inline
Return the index of the first component.
Definition at line 83 of file IncrCtlVec4D.h.
 { return first_; }
References oops::IncrCtlVec4D< MODEL >::first_.
get() [1/2]
template<typename MODEL > IncrCtlVec< MODEL > & oops::IncrCtlVec4D< MODEL >::get (const int ii) private
Return reference to the component corresponding to i-th sub-window.
Definition at line 188 of file IncrCtlVec4D.h.
{
   iter_ it = incrCtlVec4d_.find(ii);
   ASSERT(it != incrCtlVec4d_.end());
   return *it->second;
 }
Referenced by oops::IncrCtlVec4D< MODEL >::operator[]().
get() [2/2]
template<typename MODEL > const IncrCtlVec< MODEL > & oops::IncrCtlVec4D< MODEL >::get (const int ii) const private
Return constant reference to the component corresponding to i-th sub-window
Definition at line 197 of file IncrCtlVec4D.h.
{
   icst_ it = incrCtlVec4d_.find(ii);
   ASSERT(it != incrCtlVec4d_.end());
   return *it->second;
 }
last()
template<typename MODEL > int oops::IncrCtlVec4D< MODEL >::last () const inline
Return the index of the last component.
Definition at line 85 of file IncrCtlVec4D.h.
 { return last_; }
References oops::IncrCtlVec4D< MODEL >::last_.
norm()
template<typename MODEL > double oops::IncrCtlVec4D< MODEL >::norm
L-2 norm.
Definition at line 381 of file IncrCtlVec4D.h.
{
   Log::trace() << "IncrCtlVec4D<MODEL>::norm starting" << std::endl;
   util::Timer timer(classname(), "norm");
   double zz = 0.0;
   for (iter_ jsub = incrCtlVec4d_.begin(); jsub != incrCtlVec4d_.end();
        ++jsub) {
     zz += jsub->second->norm();
   }
   Log::trace() << "IncrCtlVec4D<MODEL>::norm done" << std::endl;
   return zz;
 }
operator*=()
template<typename MODEL > IncrCtlVec4D< MODEL > & oops::IncrCtlVec4D< MODEL >::operator*= (const double & zz)
\(dv_1 = dv_1 * c \)
Definition at line 266 of file IncrCtlVec4D.h.
{
   Log::trace() << "IncrCtlVec4D<MODEL>::operator*= starting" << std::endl;
   util::Timer timer(classname(), "operator*=");
   for (iter_ jsub = incrCtlVec4d_.begin(); jsub != incrCtlVec4d_.end();
        ++jsub) {
     *jsub->second *= zz;
   }
   Log::trace() << "IncrCtlVec4D<MODEL>::operator*= done" << std::endl;
   return *this;
 }
operator+=()
template<typename MODEL > IncrCtlVec4D< MODEL > & oops::IncrCtlVec4D< MODEL >::operator+= (const IncrCtlVec4D< MODEL > & rhs)
\(dv_1 = dv_1 + dv_2 \)
Definition at line 236 of file IncrCtlVec4D.h.
{
   Log::trace() << "IncrCtlVec4D<MODEL>::operator+= starting" << std::endl;
   util::Timer timer(classname(), "operator+=");
   for (int jsub = rhs.first(); jsub <= rhs.last(); ++jsub) {
     this->get(jsub) += rhs[jsub];
   }
   Log::trace() << "IncrCtlVec4D<MODEL>::operator+= done" << std::endl;
   return *this;
 }
operator-=()
template<typename MODEL > IncrCtlVec4D< MODEL > & oops::IncrCtlVec4D< MODEL >::operator-= (const IncrCtlVec4D< MODEL > & rhs)
\(dv_1 = dv_1 - dv_2 \)
Definition at line 251 of file IncrCtlVec4D.h.
{
   Log::trace() << "IncrCtlVec4D<MODEL>::operator-= starting" << std::endl;
   util::Timer timer(classname(), "operator-=");
   for (int jsub = rhs.first(); jsub <= rhs.last(); ++jsub) {
     this->get(jsub) -= rhs[jsub];
   }
   Log::trace() << "IncrCtlVec4D<MODEL>::operator-= done" << std::endl;
   return *this;
 }
operator=()
template<typename MODEL > IncrCtlVec4D< MODEL > & oops::IncrCtlVec4D< MODEL >::operator= (const IncrCtlVec4D< MODEL > & rhs)
\(dv_1 = dv_2 \)
Definition at line 221 of file IncrCtlVec4D.h.
{
   Log::trace() << "IncrCtlVec4D<MODEL>::operator= starting" << std::endl;
   util::Timer timer(classname(), "operator=");
   for (int jsub = rhs.first(); jsub <= rhs.last(); ++jsub) {
     this->get(jsub) = rhs[jsub];
   }
   Log::trace() << "IncrCtlVec4D<MODEL>::operator= done" << std::endl;
   return *this;
 }
operator[]() [1/2]
template<typename MODEL > IncrCtlVec_& oops::IncrCtlVec4D< MODEL >::operator[] (const int ii) inline
Return reference to the component corresponding to i-th sub-window.
Definition at line 78 of file IncrCtlVec4D.h.
 { return this->get(ii); }
References oops::IncrCtlVec4D< MODEL >::get().
operator[]() [2/2]
template<typename MODEL > const IncrCtlVec_& oops::IncrCtlVec4D< MODEL >::operator[] (const int ii) const inline
Return constant reference to the component corresponding to i-th sub-window
Definition at line 81 of file IncrCtlVec4D.h.
 { return this->get(ii); }
References oops::IncrCtlVec4D< MODEL >::get().
print()
template<typename MODEL > void oops::IncrCtlVec4D< MODEL >::print (std::ostream & os) const private
Definition at line 399 of file IncrCtlVec4D.h.
{
   Log::trace() << "IncrCtlVec4D<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   for (icst_ jsub = incrCtlVec4d_.begin(); jsub != incrCtlVec4d_.end();
        ++jsub) {
     os << *jsub->second << std::endl;
   }
   Log::trace() << "IncrCtlVec4D<MODEL>::print done" << std::endl;
 }
random()
template<typename MODEL > void oops::IncrCtlVec4D< MODEL >::random
Random control vector.
Definition at line 331 of file IncrCtlVec4D.h.
{
   Log::trace() << "IncrCtlVec4D<MODEL>::random starting" << std::endl;
   util::Timer timer(classname(), "random");
   for (iter_ jsub = incrCtlVec4d_.begin(); jsub != incrCtlVec4d_.end();
        ++jsub) {
     jsub->second->random();
   }
   Log::trace() << "IncrCtlVec4D<MODEL>::random done" << std::endl;
 }
read()
template<typename MODEL > void oops::IncrCtlVec4D< MODEL >::read (const eckit::Configuration & conf)
Read control vector.
Definition at line 346 of file IncrCtlVec4D.h.
{
   Log::trace() << "IncrCtlVec4D<MODEL>::read starting" << std::endl;
   util::Timer timer(classname(), "read");
   std::vector<eckit::LocalConfiguration> confs;
   conf.get("ctlvec", confs);
   ASSERT(incrCtlVec4d_.size() == confs.size());
   for (iter_ jsub = incrCtlVec4d_.begin(); jsub != incrCtlVec4d_.end();
        ++jsub) {
     jsub->second->read(confs[jsub->first]);
   }
   Log::trace() << "IncrCtlVec4D<MODEL>::read done" << std::endl;
 }
schur_product_with()
template<typename MODEL > void oops::IncrCtlVec4D< MODEL >::schur_product_with (const IncrCtlVec4D< MODEL > & dv)
Hadamard product (element-wise)
Definition at line 315 of file IncrCtlVec4D.h.
{
   Log::trace() << "IncrCtlVec4D<MODEL>::schur_product_with starting"
                << std::endl;
   util::Timer timer(classname(), "schur_product_with");
   for (iter_ jsub = incrCtlVec4d_.begin(); jsub != incrCtlVec4d_.end();
        ++jsub) {
     jsub->second->shur_product_with(dv[jsub->first]);
   }
   Log::trace() << "IncrCtlVec4D<MODEL>::schur_product_with done" << std::endl;
 }
write()
template<typename MODEL > void oops::IncrCtlVec4D< MODEL >::write (const eckit::Configuration & conf) const
Write control vector.
Definition at line 363 of file IncrCtlVec4D.h.
{
   Log::trace() << "IncrCtlVec4D<MODEL>::write starting" << std::endl;
   util::Timer timer(classname(), "write");
   Log::info() << "IncrCtlVec4D<MODEL>::write conf" << conf << std::endl;
   std::vector<eckit::LocalConfiguration> confs;
   conf.get("ctlvec", confs);
   ASSERT(incrCtlVec4d_.size() == confs.size());
   for (icst_ jsub = incrCtlVec4d_.begin(); jsub != incrCtlVec4d_.end();
        ++jsub) {
     jsub->second->write(confs[jsub->first]);
   }
   Log::trace() << "IncrCtlVec4D<MODEL>::write done" << std::endl;
 }
zero()
template<typename MODEL > void oops::IncrCtlVec4D< MODEL >::zero
\(dv_1 = 0 \)
Definition at line 206 of file IncrCtlVec4D.h.
{
   Log::trace() << "IncrCtlVec4D<MODEL>::zero starting" << std::endl;
   util::Timer timer(classname(), "zero");
   for (iter_ jsub = incrCtlVec4d_.begin(); jsub != incrCtlVec4d_.end();
        ++jsub) {
     jsub->second->zero();
   }
   Log::trace() << "IncrCtlVec4D<MODEL>::zero done" << std::endl;
 }
Member Data Documentation
first_
template<typename MODEL > int oops::IncrCtlVec4D< MODEL >::first_ private
Index of the first control vector.
Definition at line 131 of file IncrCtlVec4D.h.
Referenced by oops::IncrCtlVec4D< MODEL >::first().
incrCtlVec4d_
template<typename MODEL > std::map<int, std::unique_ptr<IncrCtlVec_> > oops::IncrCtlVec4D< MODEL >::incrCtlVec4d_ private
Map of IncrCtlVec (key: integer; value: IncrCtlVec pointer)
Definition at line 129 of file IncrCtlVec4D.h.
Referenced by oops::IncrCtlVec4D< MODEL >::IncrCtlVec4D().
last_
template<typename MODEL > int oops::IncrCtlVec4D< MODEL >::last_ private
Index of the last control vector.
Definition at line 133 of file IncrCtlVec4D.h.
Referenced by oops::IncrCtlVec4D< MODEL >::IncrCtlVec4D(), and oops::IncrCtlVec4D< MODEL >::last().
The documentation for this class was generated from the following files:
src/oops/assimilation/CostJbState.h
src/oops/assimilation/IncrCtlVec4D.h