OOPS Documentation: oops::HofX< MODEL > Class Template Reference
oops::HofX< MODEL > Class Template Reference
#include <HofX.h>
Public Member Functions
HofX ()
virtual ~HofX ()
int execute (const eckit::Configuration &fullConfig) const
Public Member Functions inherited from oops::Application
Application ()
virtual ~Application ()
Private Types
using Geometry_ = Geometry< MODEL >
using Model_ = Model< MODEL >
using ModelAux_ = ModelAuxControl< MODEL >
using ObsAuxCtrls_ = ObsAuxControls< MODEL >
using Observations_ = Observations< MODEL >
using ObsOperators_ = ObsOperators< MODEL >
using ObsSpaces_ = ObservationSpaces< MODEL >
using State_ = State< MODEL >
Private Member Functions
std::string appname () const
Detailed Description
template<typename MODEL>
class oops::HofX< MODEL >
Definition at line 41 of file HofX.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::HofX< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 42 of file HofX.h.
Model_
template<typename MODEL > using oops::HofX< MODEL >::Model_ = Model<MODEL> private
Definition at line 43 of file HofX.h.
ModelAux_
template<typename MODEL > using oops::HofX< MODEL >::ModelAux_ = ModelAuxControl<MODEL> private
Definition at line 44 of file HofX.h.
ObsAuxCtrls_
template<typename MODEL > using oops::HofX< MODEL >::ObsAuxCtrls_ = ObsAuxControls<MODEL> private
Definition at line 45 of file HofX.h.
Observations_
template<typename MODEL > using oops::HofX< MODEL >::Observations_ = Observations<MODEL> private
Definition at line 46 of file HofX.h.
ObsOperators_
template<typename MODEL > using oops::HofX< MODEL >::ObsOperators_ = ObsOperators<MODEL> private
Definition at line 47 of file HofX.h.
ObsSpaces_
template<typename MODEL > using oops::HofX< MODEL >::ObsSpaces_ = ObservationSpaces<MODEL> private
Definition at line 48 of file HofX.h.
State_
template<typename MODEL > using oops::HofX< MODEL >::State_ = State<MODEL> private
Definition at line 49 of file HofX.h.
Constructor & Destructor Documentation
HofX()
template<typename MODEL > oops::HofX< MODEL >::HofX () inline
Definition at line 53 of file HofX.h.
 {}
~HofX()
template<typename MODEL > virtual oops::HofX< MODEL >::~HofX () inline virtual
Definition at line 55 of file HofX.h.
 {}
Member Function Documentation
appname()
template<typename MODEL > std::string oops::HofX< MODEL >::appname () const inline private virtual
Implements oops::Application.
Definition at line 118 of file HofX.h.
 { return "oops::HofX<" + MODEL::name() + ">"; }
execute()
template<typename MODEL > int oops::HofX< MODEL >::execute (const eckit::Configuration & fullConfig) const inline virtual
Implements oops::Application.
Definition at line 57 of file HofX.h.
{
     //  Setup observation window
     const eckit::LocalConfiguration windowConf(fullConfig,
                                                "Assimilation Window");
     const util::Duration winlen(windowConf.getString("Length"));
     const util::DateTime winbgn(windowConf.getString("Begin"));
     const util::DateTime winend(winbgn + winlen);
     Log::info() << "Observation window is:" << windowConf << std::endl;
     //  Setup resolution
     const eckit::LocalConfiguration geomConfig(fullConfig, "Geometry");
     const Geometry_ geom(geomConfig);
     //  Setup Model
     const eckit::LocalConfiguration modelConfig(fullConfig, "Model");
     const Model_ model(geom, modelConfig);
     //  Setup initial state
     const eckit::LocalConfiguration initialConfig(fullConfig,
                                                   "Initial Condition");
     Log::info() << "Initial configuration is:" << initialConfig << std::endl;
     State_ xx(geom, model, initialConfig);
     Log::test() << "Initial state: " << xx.norm() << std::endl;
     //  Setup augmented state
     ModelAux_ moderr(geom, model, initialConfig);
     //  Setup forecast outputs
     PostProcessor<State_> post;
     eckit::LocalConfiguration prtConf;
     fullConfig.get("Prints", prtConf);
     post.enrollProcessor(new StateInfo<State_>("fc", prtConf));
     //  Setup observations
     eckit::LocalConfiguration obsconf(fullConfig, "Observations");
     Log::debug() << "Observations configuration is:" << obsconf << std::endl;
     ObsSpaces_ obsdb(obsconf, geom, winbgn, winend);
     ObsOperators_ hop(obsdb);
     //  Setup observations bias
     ObsAuxCtrls_ ybias(obsdb, obsconf);
     std::shared_ptr<Observer<MODEL, State_> > pobs(
         new Observer<MODEL, State_>(obsdb, hop, ybias));
     post.enrollProcessor(pobs);
     //  Compute H(x)
     model.forecast(xx, moderr, winlen, post);
     Log::info() << "HofX: Finished observation computation." << std::endl;
     Log::test() << "Final state: " << xx.norm() << std::endl;
     //  Save H(x)
     std::unique_ptr<Observations_> yobs(pobs->release());
     Log::test() << "H(x): " << *yobs << std::endl;
     yobs->save(obsconf);
     return 0;
   }
References oops::PostProcessor< FLDS >::enrollProcessor(), oops::Model< MODEL >::forecast(), and oops::State< MODEL >::norm().
The documentation for this class was generated from the following file:
src/oops/runs/HofX.h