OOPS Documentation: oops::Interpolator< MODEL > Class Template Reference
oops::Interpolator< MODEL > Class Template Reference
#include <Interpolator.h>
Public Member Functions
Interpolator (const State_ &, const eckit::Configuration &, const bool)
Interpolator (const State_ &, const Geometry_ &, const eckit::Configuration &, const bool)
Interpolator (const Interpolator &)
virtual ~Interpolator ()
Interpolator & operator= (const Interpolator &)
Interpolator & operator+= (const State_ &)
Interpolator & operator-= (const State_ &)
void set (const Geometry_ &, const Geometry_ &)
virtual void set_vector (const eckit::Configuration &)
void interpolate (const Increment_ &, const Variables_ &, Increment_ &) const
void interpolate (const State_ &, const Variables_ &, State_ &) const
void smooth (Increment_ &) const
void save (Increment_ &) const
void read (const Increment_ &)
void write (const eckit::Configuration &) const
Static Public Member Functions
static const std::string classname ()
Private Types
using Interpolator_ = typename MODEL::Interpolator
using Geometry_ = Geometry< MODEL >
using Variables_ = Variables< MODEL >
using Increment_ = Increment< MODEL >
using State_ = State< MODEL >
Private Member Functions
void print (std::ostream &) const
Private Attributes
std::unique_ptr< Interpolator_ > interp_
Friends
std::ostream & operator<< (std::ostream &os, const Interpolator &loc)
Diagnostics.
Detailed Description
template<typename MODEL>
class oops::Interpolator< MODEL >
Definition at line 38 of file Interpolator.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::Interpolator< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 41 of file Interpolator.h.
Increment_
template<typename MODEL > using oops::Interpolator< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 43 of file Interpolator.h.
Interpolator_
template<typename MODEL > using oops::Interpolator< MODEL >::Interpolator_ = typename MODEL::Interpolator private
Definition at line 40 of file Interpolator.h.
State_
template<typename MODEL > using oops::Interpolator< MODEL >::State_ = State<MODEL> private
Definition at line 44 of file Interpolator.h.
Variables_
template<typename MODEL > using oops::Interpolator< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 42 of file Interpolator.h.
Constructor & Destructor Documentation
Interpolator() [1/3]
template<typename MODEL > oops::Interpolator< MODEL >::Interpolator (const State_ & xb, const eckit::Configuration & conf, const bool is_adjoint)
Definition at line 83 of file Interpolator.h.
     : interp_() {
   Log::trace() << "Interpolator<MODEL>::Interpolator starting";
   util::Timer timer(classname(), "Interpolator");
   interp_.reset(new Interpolator_(xb.state(), conf, is_adjoint));
   Log::trace() << "Interpolator<MODEL>::Interpolator done";
 }
References oops::Interpolator< MODEL >::classname(), oops::Interpolator< MODEL >::interp_, and oops::State< MODEL >::state().
Interpolator() [2/3]
template<typename MODEL > oops::Interpolator< MODEL >::Interpolator (const State_ & xb, const Geometry_ & geo, const eckit::Configuration & conf, const bool is_adjoint)
Definition at line 94 of file Interpolator.h.
     : interp_() {
   Log::trace()
       << "Interpolator<MODEL>::Interpolator with 2 geometries starting";
   util::Timer timer(classname(), "Interpolator");
   interp_.reset(
       new Interpolator_(xb.state(), geo.geometry(), conf, is_adjoint));
   Log::trace() << "Interpolator<MODEL>::Interpolator with 2 geometries done";
 }
References oops::Interpolator< MODEL >::classname(), oops::Geometry< MODEL >::geometry(), oops::Interpolator< MODEL >::interp_, and oops::State< MODEL >::state().
Interpolator() [3/3]
template<typename MODEL > oops::Interpolator< MODEL >::Interpolator (const Interpolator< MODEL > & other) explicit
Definition at line 107 of file Interpolator.h.
                                                            : interp_() {
   Log::trace() << "Interpolator<MODEL>::Interpolator starting";
   util::Timer timer(classname(), "Interpolator");
   interp_.reset(new Interpolator_(*other.interp_));
   Log::trace() << "Interpolator<MODEL>::Interpolator done";
 }
References oops::Interpolator< MODEL >::classname(), and oops::Interpolator< MODEL >::interp_.
~Interpolator()
template<typename MODEL > oops::Interpolator< MODEL >::~Interpolator virtual
Definition at line 117 of file Interpolator.h.
{
   Log::trace() << "Interpolator<MODEL>::~Interpolator starting";
   util::Timer timer(classname(), "~Interpolator");
   interp_.reset();
   Log::trace() << "Interpolator<MODEL>::~Interpolator done";
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::Interpolator< MODEL >::classname () inline static
Definition at line 47 of file Interpolator.h.
 { return "oops::Interpolator"; }
Referenced by oops::Interpolator< MODEL >::Interpolator().
interpolate() [1/2]
template<typename MODEL > void oops::Interpolator< MODEL >::interpolate (const Increment_ & dxi, const Variables_ & var, Increment_ & dxo) const
Definition at line 181 of file Interpolator.h.
{
   Log::trace() << "Interpolator<MODEL>::interpolate starting";
   util::Timer timer(classname(), "interpolate");
   interp_->interpolate(dxi.increment(), var.variables(), dxo.increment());
   Log::trace() << "Interpolator<MODEL>::interpolate done";
 }
References oops::Increment< MODEL >::increment(), and oops::Variables< MODEL >::variables().
interpolate() [2/2]
template<typename MODEL > void oops::Interpolator< MODEL >::interpolate (const State_ & xxi, const Variables_ & var, State_ & xxo) const
Definition at line 193 of file Interpolator.h.
{
   Log::trace() << "Interpolator<MODEL>::interpolate starting";
   util::Timer timer(classname(), "interpolate");
   interp_->interpolate(xxi.state(), var.variables(), xxo.state());
   Log::trace() << "Interpolator<MODEL>::interpolate done";
 }
References oops::State< MODEL >::state(), and oops::Variables< MODEL >::variables().
operator+=()
template<typename MODEL > Interpolator< MODEL > & oops::Interpolator< MODEL >::operator+= (const State_ & rhs)
Definition at line 138 of file Interpolator.h.
{
   Log::trace() << "Interpolator<MODEL>::operator+= starting";
   util::Timer timer(classname(), "operator+=");
   *interp_ += rhs.state();
   Log::trace() << "Interpolator<MODEL>::operator+= done";
   return *this;
 }
References oops::State< MODEL >::state().
operator-=()
template<typename MODEL > Interpolator< MODEL > & oops::Interpolator< MODEL >::operator-= (const State_ & rhs)
Definition at line 149 of file Interpolator.h.
{
   Log::trace() << "Interpolator<MODEL>::operator+= starting";
   util::Timer timer(classname(), "operator+=");
   *interp_ -= rhs.state();
   Log::trace() << "Interpolator<MODEL>::operator+= done";
   return *this;
 }
References oops::State< MODEL >::state().
operator=()
template<typename MODEL > Interpolator< MODEL > & oops::Interpolator< MODEL >::operator= (const Interpolator< MODEL > & rhs)
Definition at line 127 of file Interpolator.h.
{
   Log::trace() << "Interpolator<MODEL>::operator= starting";
   util::Timer timer(classname(), "operator=");
   *interp_ = *rhs.interp_;
   Log::trace() << "Interpolator<MODEL>::operator= done";
   return *this;
 }
References oops::Interpolator< MODEL >::interp_.
print()
template<typename MODEL > void oops::Interpolator< MODEL >::print (std::ostream & os) const private
Definition at line 244 of file Interpolator.h.
{
   Log::trace() << "Interpolator<MODEL>::print starting";
   util::Timer timer(classname(), "print");
   os << *interp_;
   Log::trace() << "Interpolator<MODEL>::print done";
 }
read()
template<typename MODEL > void oops::Interpolator< MODEL >::read (const Increment_ & dx)
Definition at line 224 of file Interpolator.h.
{
   Log::trace() << "Interpolator<MODEL>::read starting";
   util::Timer timer(classname(), "read");
   interp_->read(dx.increment());
   Log::trace() << "Interpolator<MODEL>::read done";
 }
References oops::Increment< MODEL >::increment().
save()
template<typename MODEL > void oops::Interpolator< MODEL >::save (Increment_ & dx) const
Definition at line 214 of file Interpolator.h.
{
   Log::trace() << "Interpolator<MODEL>::save starting";
   util::Timer timer(classname(), "save");
   interp_->save(dx.increment());
   Log::trace() << "Interpolator<MODEL>::save done";
 }
References oops::Increment< MODEL >::increment().
set()
template<typename MODEL > void oops::Interpolator< MODEL >::set (const Geometry_ & geo_in, const Geometry_ & geo_out)
Definition at line 160 of file Interpolator.h.
{
   Log::trace() << "Interpolator<MODEL>::set starting";
   util::Timer timer(classname(), "set");
   interp_->set(geo_in.geometry(), geo_out.geometry());
   Log::trace() << "Interpolator<MODEL>::set done";
 }
References oops::Geometry< MODEL >::geometry().
set_vector()
template<typename MODEL > void oops::Interpolator< MODEL >::set_vector (const eckit::Configuration & conf) virtual
Reimplemented in oops::Advector< MODEL >.
Definition at line 171 of file Interpolator.h.
{
   Log::trace() << "Interpolator<MODEL>::set_vector starting";
   util::Timer timer(classname(), "set_vector");
   interp_->set_vector(conf);
   Log::trace() << "Interpolator<MODEL>::set_vector done";
 }
smooth()
template<typename MODEL > void oops::Interpolator< MODEL >::smooth (Increment_ & dx) const
Definition at line 204 of file Interpolator.h.
{
   Log::trace() << "Interpolator<MODEL>::smooth starting";
   util::Timer timer(classname(), "smooth");
   interp_->smooth(dx.increment());
   Log::trace() << "Interpolator<MODEL>::smooth done";
 }
References oops::Increment< MODEL >::increment().
write()
template<typename MODEL > void oops::Interpolator< MODEL >::write (const eckit::Configuration & conf) const
Definition at line 234 of file Interpolator.h.
{
   Log::trace() << "Interpolator<MODEL>::write starting";
   util::Timer timer(classname(), "write");
   interp_->write(conf);
   Log::trace() << "Interpolator<MODEL>::write done";
 }
Friends And Related Function Documentation
operator<<
template<typename MODEL > std::ostream& operator<< (std::ostream & os, const Interpolator< MODEL > & loc) friend
Diagnostics.
Definition at line 70 of file Interpolator.h.
{
     loc.print(os);
     return os;
   }
Member Data Documentation
interp_
template<typename MODEL > std::unique_ptr<Interpolator_> oops::Interpolator< MODEL >::interp_ private
Definition at line 77 of file Interpolator.h.
Referenced by oops::Interpolator< MODEL >::Interpolator(), and oops::Interpolator< MODEL >::operator=().
The documentation for this class was generated from the following file:
src/oops/interface/Interpolator.h