OOPS Documentation: oops::ObservationSpaces< MODEL > Class Template Reference
oops::ObservationSpaces< MODEL > Class Template Reference
Wrapper around a vector of observation spaces.
#include <ObservationSpaces.h>
Public Member Functions
ObservationSpaces (const eckit::Configuration &, const Geometry_ &, const util::DateTime &, const util::DateTime &, const bool lscreened=false)
~ObservationSpaces ()
std::size_t size () const
Access.
const ObsSpace_ & operator[] (const std::size_t ii) const
ObsSpace_ & operator[] (const std::size_t ii)
const util::DateTime & windowStart () const
Assimilation window.
const util::DateTime & windowEnd () const
void screenObservations (const Departures_ &, const GeoVaLsVec_ &) const
Screen observations.
void saveObservations () const
Save observations.
void printJo (const Departures_ &, const Departures_ &) const
Other.
Static Public Member Functions
static const std::string classname ()
Private Types
using Departures_ = Departures< MODEL >
using GeoVaLs_ = GeoVaLs< MODEL >
using ObsSpace_ = ObservationSpace< MODEL >
using Geometry_ = Geometry< MODEL >
using GeoVaLsVec_ = std::vector< std::shared_ptr< GeoVaLs_ > >
Private Member Functions
void print (std::ostream &) const
Private Attributes
const util::DateTime wbgn_
const util::DateTime wend_
const bool lscreened_
std::vector< std::shared_ptr< ObsSpace_ > > spaces_
Detailed Description
template<typename MODEL>
class oops::ObservationSpaces< MODEL >
Wrapper around a vector of observation spaces.
Definition at line 44 of file ObservationSpaces.h.
Member Typedef Documentation
Departures_
template<typename MODEL > using oops::ObservationSpaces< MODEL >::Departures_ = Departures<MODEL> private
Definition at line 48 of file ObservationSpaces.h.
Geometry_
template<typename MODEL > using oops::ObservationSpaces< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 51 of file ObservationSpaces.h.
GeoVaLs_
template<typename MODEL > using oops::ObservationSpaces< MODEL >::GeoVaLs_ = GeoVaLs<MODEL> private
Definition at line 49 of file ObservationSpaces.h.
GeoVaLsVec_
template<typename MODEL > using oops::ObservationSpaces< MODEL >::GeoVaLsVec_ = std::vector<std::shared_ptr<GeoVaLs_> > private
Definition at line 52 of file ObservationSpaces.h.
ObsSpace_
template<typename MODEL > using oops::ObservationSpaces< MODEL >::ObsSpace_ = ObservationSpace<MODEL> private
Definition at line 50 of file ObservationSpaces.h.
Constructor & Destructor Documentation
ObservationSpaces()
template<typename MODEL > oops::ObservationSpaces< MODEL >::ObservationSpaces (const eckit::Configuration & conf, const Geometry_ & geom, const util::DateTime & bgn, const util::DateTime & end, const bool lscreened = false)
Definition at line 94 of file ObservationSpaces.h.
     : wbgn_(bgn), wend_(end), lscreened_(lscreened), spaces_(0) {
   std::vector<eckit::LocalConfiguration> obsconf;
   conf.get("ObsTypes", obsconf);
   for (std::size_t jj = 0; jj < obsconf.size(); ++jj) {
     Log::debug() << "ObservationSpaces::ObservationSpaces : conf "
                  << obsconf[jj] << std::endl;
     std::shared_ptr<ObsSpace_> tmp(
         new ObsSpace_(obsconf[jj], geom, bgn, end, lscreened));
     spaces_.push_back(tmp);
     //  Generate locations etc... if required
     if (obsconf[jj].has("Generate")) {
       const eckit::LocalConfiguration gconf(obsconf[jj], "Generate");
       spaces_[jj]->generateDistribution(gconf);
     }
   }
 }
References oops::ObservationSpaces< MODEL >::spaces_.
~ObservationSpaces()
template<typename MODEL > oops::ObservationSpaces< MODEL >::~ObservationSpaces
Definition at line 119 of file ObservationSpaces.h.
 {}
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::ObservationSpaces< MODEL >::classname () inline static
Definition at line 55 of file ObservationSpaces.h.
 { return "oops::ObservationSpaces"; }
operator[]() [1/2]
template<typename MODEL > ObsSpace_& oops::ObservationSpaces< MODEL >::operator[] (const std::size_t ii) inline
Definition at line 67 of file ObservationSpaces.h.
 { return *spaces_.at(ii); }
References oops::ObservationSpaces< MODEL >::spaces_.
operator[]() [2/2]
template<typename MODEL > const ObsSpace_& oops::ObservationSpaces< MODEL >::operator[] (const std::size_t ii) const inline
Definition at line 64 of file ObservationSpaces.h.
{
     return *spaces_.at(ii);
   }
References oops::ObservationSpaces< MODEL >::spaces_.
print()
template<typename MODEL > void oops::ObservationSpaces< MODEL >::print (std::ostream & os) const private
Definition at line 153 of file ObservationSpaces.h.
{
   for (std::size_t jj = 0; jj < spaces_.size(); ++jj) {
     os << *spaces_[jj];
   }
 }
printJo()
template<typename MODEL > void oops::ObservationSpaces< MODEL >::printJo (const Departures_ & dy, const Departures_ & grad) const
Other.
Definition at line 143 of file ObservationSpaces.h.
{
   for (std::size_t jj = 0; jj < spaces_.size(); ++jj) {
     spaces_[jj]->printJo(dy[jj].obsvector(), grad[jj].obsvector());
   }
 }
saveObservations()
template<typename MODEL > void oops::ObservationSpaces< MODEL >::saveObservations
Save observations.
Definition at line 134 of file ObservationSpaces.h.
{
   for (std::size_t jj = 0; jj < spaces_.size(); ++jj) {
     spaces_[jj]->saveObservations();
   }
 }
screenObservations()
template<typename MODEL > void oops::ObservationSpaces< MODEL >::screenObservations (const Departures_ & dep, const GeoVaLsVec_ & geovals) const
Screen observations.
Definition at line 124 of file ObservationSpaces.h.
{
   for (std::size_t jj = 0; jj < spaces_.size(); ++jj) {
     spaces_[jj]->screenObservations(dep[jj].obsvector(), *geovals[jj]);
   }
 }
size()
template<typename MODEL > std::size_t oops::ObservationSpaces< MODEL >::size () const inline
Access.
Definition at line 63 of file ObservationSpaces.h.
 { return spaces_.size(); }
References oops::ObservationSpaces< MODEL >::spaces_.
Referenced by oops::Departures< MODEL >::Departures(), oops::LinearObsOperators< MODEL >::LinearObsOperators(), oops::ObsErrors< MODEL >::ObsErrors(), oops::Observations< MODEL >::Observations(), and oops::ObsOperators< MODEL >::ObsOperators().
windowEnd()
template<typename MODEL > const util::DateTime& oops::ObservationSpaces< MODEL >::windowEnd () const inline
Definition at line 71 of file ObservationSpaces.h.
 { return wend_; }
References oops::ObservationSpaces< MODEL >::wend_.
windowStart()
template<typename MODEL > const util::DateTime& oops::ObservationSpaces< MODEL >::windowStart () const inline
Assimilation window.
Definition at line 70 of file ObservationSpaces.h.
 { return wbgn_; }
References oops::ObservationSpaces< MODEL >::wbgn_.
Member Data Documentation
lscreened_
template<typename MODEL > const bool oops::ObservationSpaces< MODEL >::lscreened_ private
Definition at line 87 of file ObservationSpaces.h.
spaces_
template<typename MODEL > std::vector<std::shared_ptr<ObsSpace_> > oops::ObservationSpaces< MODEL >::spaces_ private
Definition at line 88 of file ObservationSpaces.h.
Referenced by oops::ObservationSpaces< MODEL >::ObservationSpaces(), oops::ObservationSpaces< MODEL >::operator[](), and oops::ObservationSpaces< MODEL >::size().
wbgn_
template<typename MODEL > const util::DateTime oops::ObservationSpaces< MODEL >::wbgn_ private
Definition at line 85 of file ObservationSpaces.h.
Referenced by oops::ObservationSpaces< MODEL >::windowStart().
wend_
template<typename MODEL > const util::DateTime oops::ObservationSpaces< MODEL >::wend_ private
Definition at line 86 of file ObservationSpaces.h.
Referenced by oops::ObservationSpaces< MODEL >::windowEnd().
The documentation for this class was generated from the following file:
src/oops/base/ObservationSpaces.h