OOPS Documentation: oops::PostProcessorTL< INCR > Class Template Reference
oops::PostProcessorTL< INCR > Class Template Reference
Control linear model post processing.
#include <PostProcessorTL.h>
Public Member Functions
PostProcessorTL ()
Constructor.
PostProcessorTL (const PostProcessorTL &pp)
Copy constructor.
~PostProcessorTL ()
Destructor.
void enrollProcessor (PostBaseTL_ *pp)
Adds a post processor to the vector of post-processors.
void enrollProcessor (std::shared_ptr< PostBaseTL_ > pp)
Adds a post processor to the vector of post-processors.
GeneralizedDepartures * releaseOutputFromTL (unsigned int ii)
Release the dual space output of the post-processor.
void initializeTL (const INCR &dx, const util::DateTime &end, const util::Duration &step)
Calls initializeTL method of individual processors.
void processTL (const INCR &dx)
Calls processTL method of individual processors.
void finalizeTL (const INCR &dx)
Calls finalizeTL method of individual processors.
Private Types
using PostBaseTL_ = PostBaseTL< INCR >
Private Member Functions
PostProcessorTL operator= (const PostProcessorTL &)
Private Attributes
std::vector< std::shared_ptr< PostBaseTL_ > > processors_
Vector of shared pointers to individual processors.
Detailed Description
template<typename INCR>
class oops::PostProcessorTL< INCR >
Control linear model post processing.
This class controls linear model post processing in the most general sense, ie all diagnostics computations that do not affect the linear model integration. It just calls all the individual processors one by one.
Post-processing is organized in three stages/methods: initializeTL (called prior to time-stepping), processTL (called during LinearModel::forecastTL), nd finalize (called once the time-stepping is finished).
Methods initializeTL, processTL and finalizeTL simply call the initializeTL, processTL and finalizeTL methods, respectively, of the enrolled individual processors.
See the documentation of PostBaseTL for the details of implementation of processors and the list of available processors.
Definition at line 43 of file PostProcessorTL.h.
Member Typedef Documentation
PostBaseTL_
template<typename INCR > using oops::PostProcessorTL< INCR >::PostBaseTL_ = PostBaseTL<INCR> private
Definition at line 44 of file PostProcessorTL.h.
Constructor & Destructor Documentation
PostProcessorTL() [1/2]
template<typename INCR > oops::PostProcessorTL< INCR >::PostProcessorTL () inline
Constructor.
Definition at line 48 of file PostProcessorTL.h.
 : processors_() {}
PostProcessorTL() [2/2]
template<typename INCR > oops::PostProcessorTL< INCR >::PostProcessorTL (const PostProcessorTL< INCR > & pp) inline
Copy constructor.
Definition at line 50 of file PostProcessorTL.h.
 : processors_(pp.processors_) {}
~PostProcessorTL()
template<typename INCR > oops::PostProcessorTL< INCR >::~PostProcessorTL () inline
Destructor.
Definition at line 52 of file PostProcessorTL.h.
 {}
Member Function Documentation
enrollProcessor() [1/2]
template<typename INCR > void oops::PostProcessorTL< INCR >::enrollProcessor (PostBaseTL_ * pp) inline
Adds a post processor to the vector of post-processors.
Definition at line 55 of file PostProcessorTL.h.
{
     if (pp != 0) {
       std::shared_ptr<PostBaseTL_> sp(pp);
       processors_.push_back(sp);
     }
   }
References oops::PostProcessorTL< INCR >::processors_.
Referenced by oops::StaticWithTLModelCovariance4D< MODEL >::advectedMultiply(), oops::StaticWithTLModelCovariance4D< MODEL >::advectedMultiplySqrt(), oops::HtRinvHdxFG< MODEL >::compute(), oops::CostFunction< MODEL >::computeGradientFG(), oops::HMatrix< MODEL >::multiply(), oops::HBHtMatrix< MODEL >::multiply(), oops::SaddlePointMatrix< MODEL >::multiply(), oops::HtRinvHMatrix< MODEL >::multiply(), oops::LBHessianMatrix< MODEL >::multiply(), oops::HessianMatrix< MODEL >::multiply(), and oops::UtHtRinvHUMatrix< MODEL >::multiply().
enrollProcessor() [2/2]
template<typename INCR > void oops::PostProcessorTL< INCR >::enrollProcessor (std::shared_ptr< PostBaseTL_ > pp) inline
Adds a post processor to the vector of post-processors.
Definition at line 63 of file PostProcessorTL.h.
{
     if (pp != 0) processors_.push_back(pp);
   }
References oops::PostProcessorTL< INCR >::processors_.
finalizeTL()
template<typename INCR > void oops::PostProcessorTL< INCR >::finalizeTL (const INCR & dx) inline
Calls finalizeTL method of individual processors.
Definition at line 87 of file PostProcessorTL.h.
{
     for (std::shared_ptr<PostBaseTL_> jp : processors_) jp->finalizeTL(dx);
   }
References oops::PostProcessorTL< INCR >::processors_.
Referenced by oops::LinearModel< MODEL >::forecastTL(), oops::CostFct4DVarHyb4D< MODEL >::runTL(), and oops::CostFct4DEnVar< MODEL >::runTL().
initializeTL()
template<typename INCR > void oops::PostProcessorTL< INCR >::initializeTL (const INCR & dx, const util::DateTime & end, const util::Duration & step) inline
Calls initializeTL method of individual processors.
Definition at line 74 of file PostProcessorTL.h.
{
     for (std::shared_ptr<PostBaseTL_> jp : processors_) {
       jp->initializeTL(dx, end, step);
     }
   }
References oops::PostProcessorTL< INCR >::processors_.
Referenced by oops::LinearModel< MODEL >::forecastTL(), oops::CostFct4DVarHyb4D< MODEL >::runTL(), and oops::CostFct4DEnVar< MODEL >::runTL().
operator=()
template<typename INCR > PostProcessorTL oops::PostProcessorTL< INCR >::operator= (const PostProcessorTL< INCR > &) private
processTL()
template<typename INCR > void oops::PostProcessorTL< INCR >::processTL (const INCR & dx) inline
Calls processTL method of individual processors.
Definition at line 82 of file PostProcessorTL.h.
{
     for (std::shared_ptr<PostBaseTL_> jp : processors_) jp->processTL(dx);
   }
References oops::PostProcessorTL< INCR >::processors_.
Referenced by oops::LinearModel< MODEL >::forecastTL(), oops::CostFct4DVarHyb4D< MODEL >::runTL(), and oops::CostFct4DEnVar< MODEL >::runTL().
releaseOutputFromTL()
template<typename INCR > GeneralizedDepartures* oops::PostProcessorTL< INCR >::releaseOutputFromTL (unsigned int ii) inline
Release the dual space output of the post-processor.
Definition at line 68 of file PostProcessorTL.h.
{
     GeneralizedDepartures *lambda = processors_[ii]->releaseOutputFromTL();
     return lambda;
   }
References oops::PostProcessorTL< INCR >::processors_.
Referenced by oops::HtRinvHdxFG< MODEL >::compute(), oops::CostFunction< MODEL >::computeGradientFG(), oops::HMatrix< MODEL >::multiply(), oops::HBHtMatrix< MODEL >::multiply(), oops::SaddlePointMatrix< MODEL >::multiply(), oops::HtRinvHMatrix< MODEL >::multiply(), oops::LBHessianMatrix< MODEL >::multiply(), oops::HessianMatrix< MODEL >::multiply(), and oops::UtHtRinvHUMatrix< MODEL >::multiply().
Member Data Documentation
processors_
template<typename INCR > std::vector<std::shared_ptr<PostBaseTL_> > oops::PostProcessorTL< INCR >::processors_ private
Vector of shared pointers to individual processors.
Definition at line 95 of file PostProcessorTL.h.
Referenced by oops::PostProcessorTL< INCR >::enrollProcessor(), oops::PostProcessorTL< INCR >::finalizeTL(), oops::PostProcessorTL< INCR >::initializeTL(), oops::PostProcessorTL< INCR >::processTL(), and oops::PostProcessorTL< INCR >::releaseOutputFromTL().
The documentation for this class was generated from the following file:
src/oops/base/PostProcessorTL.h