OOPS Documentation: oops::ModelAuxIncrement< MODEL > Class Template Reference
oops::ModelAuxIncrement< MODEL > Class Template Reference
Encapsulates the auxiliary model space component of ControlIncrement.
#include <ModelAuxIncrement.h>
Public Member Functions
ModelAuxIncrement (const Geometry_ &, const eckit::Configuration &)
Constructor.
ModelAuxIncrement (const ModelAuxIncrement &, const bool copy=true)
Copy constructor.
ModelAuxIncrement (const ModelAuxIncrement &, const eckit::Configuration &)
Copy constructor with configuration.
~ModelAuxIncrement ()
Destructor.
const ModelAuxIncrement_ & modelauxincrement () const
Return a constant reference to the model specific object.
ModelAuxIncrement_ & modelauxincrement ()
Return a reference to the model specific object.
void diff (const ModelAuxControl_ &, const ModelAuxControl_ &)
\(dx = x_1 - x_2 \)
void zero ()
\(dx_1 = 0 \)
ModelAuxIncrement & operator= (const ModelAuxIncrement &)
\(dx_1 = dx_2 \)
ModelAuxIncrement & operator+= (const ModelAuxIncrement &)
\(dx_1 = dx_1 + dx_2 \)
ModelAuxIncrement & operator-= (const ModelAuxIncrement &)
\(dx_1 = dx_1 - dx_2 \)
ModelAuxIncrement & operator*= (const double &)
\(dx_1 = dx_1 * c \)
void axpy (const double &, const ModelAuxIncrement &)
\(dx_1 = dx_1 * c dx_2 \)
double dot_product_with (const ModelAuxIncrement &) const
\(<dx_1,dx_1> = dx_1^T dx_1 \)
void read (const eckit::Configuration &)
Read increment.
void write (const eckit::Configuration &) const
Write increment.
double norm () const
L-2 norm.
Static Public Member Functions
static const std::string classname ()
Private Types
using ModelAuxIncrement_ = typename MODEL::ModelAuxIncrement
using Geometry_ = Geometry< MODEL >
using ModelAuxControl_ = ModelAuxControl< MODEL >
Private Member Functions
void print (std::ostream &) const
Private Attributes
std::unique_ptr< ModelAuxIncrement_ > aux_
Pointer to the model specific object.
Detailed Description
template<typename MODEL>
class oops::ModelAuxIncrement< MODEL >
Encapsulates the auxiliary model space component of ControlIncrement.
The auxiliary model space component of ControlIncrement is designed as a constant (time step independent) linear model error forcing term that can be jointly estimated by the assimilation algorithm.
\(dx_{k+1} = M_{k+1:k} dx_k + d\eta \), where \(d\eta \) is the model error forcing term increment implemented by ModelAuxIncrement.
Definition at line 45 of file ModelAuxIncrement.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::ModelAuxIncrement< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 49 of file ModelAuxIncrement.h.
ModelAuxControl_
template<typename MODEL > using oops::ModelAuxIncrement< MODEL >::ModelAuxControl_ = ModelAuxControl<MODEL> private
Definition at line 50 of file ModelAuxIncrement.h.
ModelAuxIncrement_
template<typename MODEL > using oops::ModelAuxIncrement< MODEL >::ModelAuxIncrement_ = typename MODEL::ModelAuxIncrement private
Definition at line 48 of file ModelAuxIncrement.h.
Constructor & Destructor Documentation
ModelAuxIncrement() [1/3]
template<typename MODEL > oops::ModelAuxIncrement< MODEL >::ModelAuxIncrement (const Geometry_ & resol, const eckit::Configuration & conf)
Constructor.
Definition at line 120 of file ModelAuxIncrement.h.
     : aux_() {
   Log::trace() << "ModelAuxIncrement<MODEL>::ModelAuxIncrement starting"
                << std::endl;
   util::Timer timer(classname(), "ModelAuxIncrement");
   aux_.reset(new ModelAuxIncrement_(resol.geometry(), conf));
   Log::trace() << "ModelAuxIncrement<MODEL>::ModelAuxIncrement done"
                << std::endl;
 }
References oops::ModelAuxIncrement< MODEL >::aux_, oops::ModelAuxIncrement< MODEL >::classname(), and oops::Geometry< MODEL >::geometry().
ModelAuxIncrement() [2/3]
template<typename MODEL > oops::ModelAuxIncrement< MODEL >::ModelAuxIncrement (const ModelAuxIncrement< MODEL > & other, const bool copy = true) explicit
Copy constructor.
Definition at line 132 of file ModelAuxIncrement.h.
     : aux_() {
   Log::trace() << "ModelAuxIncrement<MODEL>::ModelAuxIncrement copy starting"
                << std::endl;
   util::Timer timer(classname(), "ModelAuxIncrement");
   aux_.reset(new ModelAuxIncrement_(*other.aux_, copy));
   Log::trace() << "ModelAuxIncrement<MODEL>::ModelAuxIncrement copy done"
                << std::endl;
 }
References oops::ModelAuxIncrement< MODEL >::aux_, and oops::ModelAuxIncrement< MODEL >::classname().
ModelAuxIncrement() [3/3]
template<typename MODEL > oops::ModelAuxIncrement< MODEL >::ModelAuxIncrement (const ModelAuxIncrement< MODEL > & other, const eckit::Configuration & conf)
Copy constructor with configuration.
Definition at line 144 of file ModelAuxIncrement.h.
     : aux_() {
   Log::trace()
       << "ModelAuxIncrement<MODEL>::ModelAuxIncrement interpolated starting"
       << std::endl;
   util::Timer timer(classname(), "ModelAuxIncrement");
   aux_.reset(new ModelAuxIncrement_(*other.aux_, conf));
   Log::trace()
       << "ModelAuxIncrement<MODEL>::ModelAuxIncrement interpolated done"
       << std::endl;
 }
References oops::ModelAuxIncrement< MODEL >::aux_, and oops::ModelAuxIncrement< MODEL >::classname().
~ModelAuxIncrement()
template<typename MODEL > oops::ModelAuxIncrement< MODEL >::~ModelAuxIncrement
Destructor.
Definition at line 158 of file ModelAuxIncrement.h.
{
   Log::trace() << "ModelAuxIncrement<MODEL>::~ModelAuxIncrement starting"
                << std::endl;
   util::Timer timer(classname(), "~ModelAuxIncrement");
   aux_.reset();
   Log::trace() << "ModelAuxIncrement<MODEL>::~ModelAuxIncrement done"
                << std::endl;
 }
Member Function Documentation
axpy()
template<typename MODEL > void oops::ModelAuxIncrement< MODEL >::axpy (const double & zz, const ModelAuxIncrement< MODEL > & dx)
\(dx_1 = dx_1 * c dx_2 \)
Definition at line 225 of file ModelAuxIncrement.h.
{
   Log::trace() << "ModelAuxIncrement<MODEL>::axpy starting" << std::endl;
   util::Timer timer(classname(), "axpy");
   aux_->axpy(zz, *dx.aux_);
   Log::trace() << "ModelAuxIncrement<MODEL>::axpy done" << std::endl;
 }
References oops::ModelAuxIncrement< MODEL >::aux_.
classname()
template<typename MODEL > static const std::string oops::ModelAuxIncrement< MODEL >::classname () inline static
Definition at line 53 of file ModelAuxIncrement.h.
 { return "oops::ModelAuxIncrement"; }
Referenced by oops::ModelAuxIncrement< MODEL >::ModelAuxIncrement().
diff()
template<typename MODEL > void oops::ModelAuxIncrement< MODEL >::diff (const ModelAuxControl_ & x1, const ModelAuxControl_ & x2)
\(dx = x_1 - x_2 \)
Definition at line 168 of file ModelAuxIncrement.h.
{
   Log::trace() << "ModelAuxIncrement<MODEL>::diff starting" << std::endl;
   util::Timer timer(classname(), "diff");
   aux_->diff(x1.modelauxcontrol(), x2.modelauxcontrol());
   Log::trace() << "ModelAuxIncrement<MODEL>::diff done" << std::endl;
 }
References oops::ModelAuxControl< MODEL >::modelauxcontrol().
Referenced by oops::CostJbTotal< MODEL >::finalize().
dot_product_with()
template<typename MODEL > double oops::ModelAuxIncrement< MODEL >::dot_product_with (const ModelAuxIncrement< MODEL > & dx) const
\(<dx_1,dx_1> = dx_1^T dx_1 \)
Definition at line 234 of file ModelAuxIncrement.h.
{
   Log::trace() << "ModelAuxIncrement<MODEL>::dot_product_with starting"
                << std::endl;
   util::Timer timer(classname(), "dot_product_with");
   double zz = aux_->dot_product_with(*dx.aux_);
   Log::trace() << "ModelAuxIncrement<MODEL>::dot_product_with done"
                << std::endl;
   return zz;
 }
References oops::ModelAuxIncrement< MODEL >::aux_.
modelauxincrement() [1/2]
template<typename MODEL > ModelAuxIncrement_& oops::ModelAuxIncrement< MODEL >::modelauxincrement () inline
Return a reference to the model specific object.
Definition at line 68 of file ModelAuxIncrement.h.
 { return *aux_; }
References oops::ModelAuxIncrement< MODEL >::aux_.
modelauxincrement() [2/2]
template<typename MODEL > const ModelAuxIncrement_& oops::ModelAuxIncrement< MODEL >::modelauxincrement () const inline
Return a constant reference to the model specific object.
Definition at line 66 of file ModelAuxIncrement.h.
 { return *aux_; }
References oops::ModelAuxIncrement< MODEL >::aux_.
Referenced by oops::LinearModelBase< L95Traits >::initializeAD(), oops::LinearModelBase< L95Traits >::initializeTL(), oops::ModelAuxCovariance< MODEL >::inverseMultiply(), oops::ModelAuxCovariance< MODEL >::multiply(), oops::ModelAuxCovariance< MODEL >::multiplySqrt(), oops::ModelAuxCovariance< MODEL >::multiplySqrtTrans(), oops::operator+=(), oops::ModelAuxCovariance< MODEL >::randomize(), oops::LinearModelBase< L95Traits >::stepAD(), and oops::LinearModelBase< L95Traits >::stepTL().
norm()
template<typename MODEL > double oops::ModelAuxIncrement< MODEL >::norm
L-2 norm.
Definition at line 262 of file ModelAuxIncrement.h.
{
   Log::trace() << "ModelAuxIncrement<MODEL>::norm starting" << std::endl;
   util::Timer timer(classname(), "norm");
   double zz = aux_->norm();
   Log::trace() << "ModelAuxIncrement<MODEL>::norm done" << std::endl;
   return zz;
 }
operator*=()
template<typename MODEL > ModelAuxIncrement< MODEL > & oops::ModelAuxIncrement< MODEL >::operator*= (const double & zz)
\(dx_1 = dx_1 * c \)
Definition at line 215 of file ModelAuxIncrement.h.
                       {
   Log::trace() << "ModelAuxIncrement<MODEL>::operator*= starting" << std::endl;
   util::Timer timer(classname(), "operator*=");
   *aux_ *= zz;
   Log::trace() << "ModelAuxIncrement<MODEL>::operator*= done" << std::endl;
   return *this;
 }
operator+=()
template<typename MODEL > ModelAuxIncrement< MODEL > & oops::ModelAuxIncrement< MODEL >::operator+= (const ModelAuxIncrement< MODEL > & rhs)
\(dx_1 = dx_1 + dx_2 \)
Definition at line 195 of file ModelAuxIncrement.h.
{
   Log::trace() << "ModelAuxIncrement<MODEL>::operator+= starting" << std::endl;
   util::Timer timer(classname(), "operator+=");
   *aux_ += *rhs.aux_;
   Log::trace() << "ModelAuxIncrement<MODEL>::operator+= done" << std::endl;
   return *this;
 }
References oops::ModelAuxIncrement< MODEL >::aux_.
operator-=()
template<typename MODEL > ModelAuxIncrement< MODEL > & oops::ModelAuxIncrement< MODEL >::operator-= (const ModelAuxIncrement< MODEL > & rhs)
\(dx_1 = dx_1 - dx_2 \)
Definition at line 205 of file ModelAuxIncrement.h.
{
   Log::trace() << "ModelAuxIncrement<MODEL>::operator-= starting" << std::endl;
   util::Timer timer(classname(), "operator-=");
   *aux_ -= *rhs.aux_;
   Log::trace() << "ModelAuxIncrement<MODEL>::operator-= done" << std::endl;
   return *this;
 }
References oops::ModelAuxIncrement< MODEL >::aux_.
operator=()
template<typename MODEL > ModelAuxIncrement< MODEL > & oops::ModelAuxIncrement< MODEL >::operator= (const ModelAuxIncrement< MODEL > & rhs)
\(dx_1 = dx_2 \)
Definition at line 185 of file ModelAuxIncrement.h.
{
   Log::trace() << "ModelAuxIncrement<MODEL>::operator= starting" << std::endl;
   util::Timer timer(classname(), "operator=");
   *aux_ = *rhs.aux_;
   Log::trace() << "ModelAuxIncrement<MODEL>::operator= done" << std::endl;
   return *this;
 }
References oops::ModelAuxIncrement< MODEL >::aux_.
print()
template<typename MODEL > void oops::ModelAuxIncrement< MODEL >::print (std::ostream & os) const private
Definition at line 271 of file ModelAuxIncrement.h.
{
   Log::trace() << "ModelAuxIncrement<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   os << *aux_;
   Log::trace() << "ModelAuxIncrement<MODEL>::print done" << std::endl;
 }
read()
template<typename MODEL > void oops::ModelAuxIncrement< MODEL >::read (const eckit::Configuration & conf)
Read increment.
Definition at line 246 of file ModelAuxIncrement.h.
{
   Log::trace() << "ModelAuxIncrement<MODEL>::read starting" << std::endl;
   util::Timer timer(classname(), "read");
   aux_->read(conf.getSubConfiguration("incrementModAux"));
   Log::trace() << "ModelAuxIncrement<MODEL>::read done" << std::endl;
 }
write()
template<typename MODEL > void oops::ModelAuxIncrement< MODEL >::write (const eckit::Configuration & conf) const
Write increment.
Definition at line 254 of file ModelAuxIncrement.h.
{
   Log::trace() << "ModelAuxIncrement<MODEL>::write starting" << std::endl;
   util::Timer timer(classname(), "write");
   aux_->write(conf.getSubConfiguration("incrementModAux"));
   Log::trace() << "ModelAuxIncrement<MODEL>::write done" << std::endl;
 }
Referenced by oops::CostJbTotal< MODEL >::writeIncrement().
zero()
template<typename MODEL > void oops::ModelAuxIncrement< MODEL >::zero
\(dx_1 = 0 \)
Definition at line 177 of file ModelAuxIncrement.h.
{
   Log::trace() << "ModelAuxIncrement<MODEL>::zero starting" << std::endl;
   util::Timer timer(classname(), "zero");
   aux_->zero();
   Log::trace() << "ModelAuxIncrement<MODEL>::zero done" << std::endl;
 }
Referenced by oops::CostFct3DVar< MODEL >::zeroAD(), oops::CostFct4DVar< MODEL >::zeroAD(), oops::CostFctWeak< MODEL >::zeroAD(), oops::CostFct4DVarHyb4D< MODEL >::zeroAD(), oops::CostFct4DEnsVar< MODEL >::zeroAD(), oops::CostFct4DEnVar< MODEL >::zeroAD(), and oops::CostFct4DVarMF< MODEL >::zeroAD().
Member Data Documentation
aux_
template<typename MODEL > std::unique_ptr<ModelAuxIncrement_> oops::ModelAuxIncrement< MODEL >::aux_ private
Pointer to the model specific object.
Definition at line 100 of file ModelAuxIncrement.h.
Referenced by oops::ModelAuxIncrement< MODEL >::axpy(), oops::ModelAuxIncrement< MODEL >::dot_product_with(), oops::ModelAuxIncrement< MODEL >::ModelAuxIncrement(), oops::ModelAuxIncrement< MODEL >::modelauxincrement(), oops::ModelAuxIncrement< MODEL >::operator+=(), oops::ModelAuxIncrement< MODEL >::operator-=(), and oops::ModelAuxIncrement< MODEL >::operator=().
The documentation for this class was generated from the following file:
src/oops/interface/ModelAuxIncrement.h