OOPS Documentation: oops::ExternalDFI< MODEL > Class Template Reference
oops::ExternalDFI< MODEL > Class Template Reference
#include <ExternalDFI.h>
Public Member Functions
ExternalDFI ()
virtual ~ExternalDFI ()
int execute (const eckit::Configuration &fullConfig) const
Public Member Functions inherited from oops::Application
Application ()
virtual ~Application ()
Private Types
using Geometry_ = Geometry< MODEL >
using Model_ = Model< MODEL >
using ModelAux_ = ModelAuxControl< MODEL >
using State_ = State< MODEL >
Private Member Functions
std::string appname () const
Detailed Description
template<typename MODEL>
class oops::ExternalDFI< MODEL >
Definition at line 37 of file ExternalDFI.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::ExternalDFI< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 38 of file ExternalDFI.h.
Model_
template<typename MODEL > using oops::ExternalDFI< MODEL >::Model_ = Model<MODEL> private
Definition at line 39 of file ExternalDFI.h.
ModelAux_
template<typename MODEL > using oops::ExternalDFI< MODEL >::ModelAux_ = ModelAuxControl<MODEL> private
Definition at line 40 of file ExternalDFI.h.
State_
template<typename MODEL > using oops::ExternalDFI< MODEL >::State_ = State<MODEL> private
Definition at line 41 of file ExternalDFI.h.
Constructor & Destructor Documentation
ExternalDFI()
template<typename MODEL > oops::ExternalDFI< MODEL >::ExternalDFI () inline
Definition at line 45 of file ExternalDFI.h.
 {}
~ExternalDFI()
template<typename MODEL > virtual oops::ExternalDFI< MODEL >::~ExternalDFI () inline virtual
Definition at line 47 of file ExternalDFI.h.
 {}
Member Function Documentation
appname()
template<typename MODEL > std::string oops::ExternalDFI< MODEL >::appname () const inline private virtual
Implements oops::Application.
Definition at line 113 of file ExternalDFI.h.
{
     return "oops::ExternalDFI<" + MODEL::name() + ">";
   }
execute()
template<typename MODEL > int oops::ExternalDFI< MODEL >::execute (const eckit::Configuration & fullConfig) const inline virtual
Implements oops::Application.
Definition at line 49 of file ExternalDFI.h.
{
     //  Setup resolution
     const eckit::LocalConfiguration resolConfig(fullConfig, "resolution");
     const Geometry_ resol(resolConfig);
     //  Setup Model
     const eckit::LocalConfiguration modelConfig(fullConfig, "model");
     const Model_ model(resol, modelConfig);
     //  Setup initial state
     const eckit::LocalConfiguration initialConfig(fullConfig, "initial");
     State_ xx(resol, model, initialConfig);
     Log::test() << "Initial state: " << xx.norm() << std::endl;
     //  Setup augmented state
     const ModelAux_ moderr(resol, model, initialConfig);
     //  Setup times
     const util::Duration fclength(fullConfig.getString("forecast_length"));
     const util::DateTime bgndate(xx.validTime());
     const util::DateTime enddate(bgndate + fclength);
     Log::info() << "Running forecast from " << bgndate << " to " << enddate
                 << std::endl;
     //  Setup post-processing
     PostProcessor<State_> post;
     eckit::LocalConfiguration prtConf;
     fullConfig.get("prints", prtConf);
     post.enrollProcessor(new StateInfo<State_>("fc", prtConf));
     //  Setup DFI
     PostProcessor<State_> pp(post);
     const eckit::LocalConfiguration dfiConf(fullConfig, "dfi");
     const util::Duration dfispan(dfiConf.getString("filter_span"));
     const util::DateTime dfitime(bgndate + dfispan / 2);
     std::shared_ptr<WeightedMean<MODEL, State_> > pdfi(
         new WeightedMean<MODEL, State_>(dfitime, dfispan, resol, dfiConf));
     pp.enrollProcessor(pdfi);
     //  Run DFI forecast
     model.forecast(xx, moderr, dfispan, pp);
     //  Retrieve initialized state
     std::unique_ptr<State_> xdfi(pdfi->releaseMean());
     Log::test() << "Filtered state: " << xdfi->norm() << std::endl;
     //  Setup forecast outputs
     const eckit::LocalConfiguration outConfig(fullConfig, "output");
     post.enrollProcessor(new StateWriter<State_>(bgndate, outConfig));
     //  Run forecast from initialized state
     const util::Duration fclen = fclength - dfispan / 2;
     if (fclength < util::Duration(0))
       ABORT("DFI: fliter span longer than forecast");
     State_ zz(*xdfi);
     model.forecast(zz, moderr, fclen, post);
     Log::test() << "Final state: " << zz.norm() << std::endl;
     return 0;
   }
References ABORT, oops::PostProcessor< FLDS >::enrollProcessor(), oops::Model< MODEL >::forecast(), oops::State< MODEL >::norm(), and oops::State< MODEL >::validTime().
The documentation for this class was generated from the following file:
src/oops/runs/ExternalDFI.h