OOPS Documentation: oops::ControlVariable< MODEL > Class Template Reference
oops::ControlVariable< MODEL > Class Template Reference
Control Variable.
#include <ControlVariable.h>
Public Member Functions
ControlVariable (const eckit::Configuration &, const Geometry_ &, const Model_ &, const ObsSpaces_ &)
The arguments define the number of sub-windows and the resolution.
ControlVariable (const Geometry_ &, const ControlVariable &)
ControlVariable (const ControlVariable &)
~ControlVariable ()
Destructor.
void read (const eckit::Configuration &)
Read a control variable.
void write (const eckit::Configuration &) const
Write a control variable.
double norm () const
Compute the L-2 norm of the control variable.
State4D_ & state ()
Returns a 4D state component of the control variable.
const State4D_ & state () const
Returns a constant 4D state component of the control variable.
ModelAuxCtrl_ & modVar ()
Returns the auxiliary model space component of the control variable.
const ModelAuxCtrl_ & modVar () const
ObsAuxCtrls_ & obsVar ()
Returns the auxiliary observation space component of the control variable.
const ObsAuxCtrls_ & obsVar () const
Static Public Member Functions
static const std::string classname ()
Private Types
using Geometry_ = Geometry< MODEL >
using Model_ = Model< MODEL >
using ModelAuxCtrl_ = ModelAuxControl< MODEL >
using ModelAuxCtrlEstimator_ = ModelAuxControlEstimator< MODEL >
using ObsAuxCtrls_ = ObsAuxControls< MODEL >
using ObsSpaces_ = ObservationSpaces< MODEL >
using State_ = State< MODEL >
using State4D_ = State4D< MODEL >
Private Member Functions
ControlVariable & operator= (const ControlVariable &)
void print (std::ostream &) const
Private Attributes
State4D_ state4d_
4D state component
std::unique_ptr< ModelAuxCtrl_ > modbias_
Auxiliary model space component.
ObsAuxCtrls_ obsbias_
Auxiliary observation space component.
Detailed Description
template<typename MODEL>
class oops::ControlVariable< MODEL >
Control Variable.
The control variable acts as a container for the inputs of the variational data assimilation cost functions in physical space. That includes the states at the start the assimilation window or of each sub-window but also additional variables such as model bias, VarBC coefficients, or other control variables for algorithms that use them. This is mostly a convenience class that is used to keep things together and reduce the number of arguments to be passed around.
The control variable \(x \) has the following structure
\[ x = \begin{bmatrix} x_{state4D} \\ x_{modaux} \\ x_{obsaux} \end{bmatrix} \]
where
\[ x_{state4D} = \begin{bmatrix} x^0 \\ x^1 \\ .. \\ x^N \end{bmatrix} \]
and \(N \) is the number of sub-windows.
-> \(x_{state4D} \) is implemented by State4D containing a vector of State objects
\[ x_{modaux} = \begin{bmatrix} x_{modaux}^0 \end{bmatrix} \]
-> \(x_{modaux} \) is implemented by ModelAuxControl
\[ x_{obsaux} = \begin{bmatrix} x_{obsaux}^0 \\ x_{obsaux}^1 \\ .. \\ x_{obsaux}^K \end{bmatrix} \]
-> \(x_{obsaux} \) is implemented by ObsAuxControls which contains a vector of ObsAuxControl objects (\(x_{obsaux}^i \)), which in turns contain a map of ObsAuxControlBase objects (e.g \(x_{VarBC}, x_{TOVSCV} \)):
\[ x_{obsaux}^i = \begin{bmatrix} x_{obsaux,i}^0 \\ .. \\ x_{obsaux,i}^L \end{bmatrix} \]
-> IFS: K=0, L=1:
\[ x_{obsaux}= \begin{bmatrix} \begin{bmatrix} x_{VarBC} \\ x_{TOVSCV} \end{bmatrix} \end{bmatrix} \]
Definition at line 95 of file ControlVariable.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::ControlVariable< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 101 of file ControlVariable.h.
Model_
template<typename MODEL > using oops::ControlVariable< MODEL >::Model_ = Model<MODEL> private
Definition at line 102 of file ControlVariable.h.
ModelAuxCtrl_
template<typename MODEL > using oops::ControlVariable< MODEL >::ModelAuxCtrl_ = ModelAuxControl<MODEL> private
Definition at line 103 of file ControlVariable.h.
ModelAuxCtrlEstimator_
template<typename MODEL > using oops::ControlVariable< MODEL >::ModelAuxCtrlEstimator_ = ModelAuxControlEstimator<MODEL> private
Definition at line 104 of file ControlVariable.h.
ObsAuxCtrls_
template<typename MODEL > using oops::ControlVariable< MODEL >::ObsAuxCtrls_ = ObsAuxControls<MODEL> private
Definition at line 105 of file ControlVariable.h.
ObsSpaces_
template<typename MODEL > using oops::ControlVariable< MODEL >::ObsSpaces_ = ObservationSpaces<MODEL> private
Definition at line 106 of file ControlVariable.h.
State4D_
template<typename MODEL > using oops::ControlVariable< MODEL >::State4D_ = State4D<MODEL> private
Definition at line 108 of file ControlVariable.h.
State_
template<typename MODEL > using oops::ControlVariable< MODEL >::State_ = State<MODEL> private
Definition at line 107 of file ControlVariable.h.
Constructor & Destructor Documentation
ControlVariable() [1/3]
template<typename MODEL > oops::ControlVariable< MODEL >::ControlVariable (const eckit::Configuration & conf, const Geometry_ & resol, const Model_ & model, const ObsSpaces_ & odb)
The arguments define the number of sub-windows and the resolution.
Definition at line 161 of file ControlVariable.h.
     : state4d_(eckit::LocalConfiguration(conf, "Jb.Background"), resol, model),
       modbias_(),
       obsbias_(odb, eckit::LocalConfiguration(conf, "Jo")) {
   modbias_.reset(new ModelAuxCtrl_(resol, model,
                                    conf.getSubConfiguration("Jb.Background")));
   if (conf.has("Jb.Background.stateModAuxEstimator")) {
     Log::info() << "ControlVariable<MODEL>::ControlVariable Estimate Model Bias"
                 << std::endl;
     //  Setup NN geometry
     const eckit::LocalConfiguration resolConfig(
         conf, "Jb.Background.stateModAuxEstimator.resolution");
     const Geometry_ resolNN(resolConfig);
     //  Setup model error estimator
     const ModelAuxCtrlEstimator_ modauxEstimator(
         resolNN, model, conf.getSubConfiguration("Jb.Background"));
     //  Setup MODERR at lowres
     ModelAuxCtrl_ me(resolNN, *modbias_);
     //  Setup BG predictor at lowres
     State_ bg(resolNN, state4d_[0]);
     if (conf.has("Jb.Background.stateModAuxEstimator.an")) {
       //  Setup AN state predictor
       const eckit::LocalConfiguration anConfig(
           conf, "Jb.Background.stateModAuxEstimator.an");
       State_ anhres(resol, model, anConfig);
       State_ an(resolNN, anhres);
       //  Estimate model error
       modauxEstimator.estimate(bg, an, me);
     } else {
       //  Estimate model error
       modauxEstimator.estimate(bg, me);
     }
     //  Interpolate model error
     modbias_.reset(new ModelAuxCtrl_(resol, me));
   }
   Log::trace() << "ControlVariable contructed" << std::endl;
 }
References oops::ModelAuxControlEstimator< MODEL >::estimate(), oops::ControlVariable< MODEL >::modbias_, and oops::ControlVariable< MODEL >::state4d_.
ControlVariable() [2/3]
template<typename MODEL > oops::ControlVariable< MODEL >::ControlVariable (const Geometry_ & resol, const ControlVariable< MODEL > & other)
Definition at line 220 of file ControlVariable.h.
     : state4d_(resol, other.state4d_),
       modbias_(new ModelAuxCtrl_(*other.modbias_)),
       obsbias_(other.obsbias_) {
   Log::trace() << "ControlVariable copied with change of resolution"
                << std::endl;
 }
ControlVariable() [3/3]
template<typename MODEL > oops::ControlVariable< MODEL >::ControlVariable (const ControlVariable< MODEL > & other) explicit
Definition at line 210 of file ControlVariable.h.
     : state4d_(other.state4d_),
       modbias_(new ModelAuxCtrl_(*other.modbias_)),
       obsbias_(other.obsbias_) {
   Log::trace() << "ControlVariable copied" << std::endl;
 }
~ControlVariable()
template<typename MODEL > oops::ControlVariable< MODEL >::~ControlVariable
Destructor.
Definition at line 232 of file ControlVariable.h.
{
   Log::trace() << "ControlVariable destructed" << std::endl;
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::ControlVariable< MODEL >::classname () inline static
Definition at line 111 of file ControlVariable.h.
 { return "oops::ControlVariable"; }
modVar() [1/2]
template<typename MODEL > ModelAuxCtrl_& oops::ControlVariable< MODEL >::modVar () inline
Returns the auxiliary model space component of the control variable.
Definition at line 137 of file ControlVariable.h.
 { return *modbias_; }
References oops::ControlVariable< MODEL >::modbias_.
Referenced by oops::CostFunction< MODEL >::addIncrement(), oops::CostFct4DVarTrajHR< MODEL >::linearize(), oops::CostFunction< MODEL >::linearize(), oops::CostFct3DVar< MODEL >::runNL(), oops::CostFct4DVar< MODEL >::runNL(), oops::CostFctWeak< MODEL >::runNL(), oops::CostFct4DEnsVar< MODEL >::runNL(), oops::CostFct4DEnVar< MODEL >::runNL(), and oops::CostFct4DVarMF< MODEL >::runNL().
modVar() [2/2]
template<typename MODEL > const ModelAuxCtrl_& oops::ControlVariable< MODEL >::modVar () const inline
Returns the constant auxiliary model space component of the control variable
Definition at line 140 of file ControlVariable.h.
 { return *modbias_; }
References oops::ControlVariable< MODEL >::modbias_.
norm()
template<typename MODEL > double oops::ControlVariable< MODEL >::norm
Compute the L-2 norm of the control variable.
Definition at line 266 of file ControlVariable.h.
{
   double zz = state4d_.norm();
   double zn = zz * zz;
   zz = modbias_->norm();
   zn += zz * zz;
   zz = obsbias_.norm();
   zn += zz * zz;
   return sqrt(zn);
 }
Referenced by oops::CostFunction< MODEL >::addIncrement().
obsVar() [1/2]
template<typename MODEL > ObsAuxCtrls_& oops::ControlVariable< MODEL >::obsVar () inline
Returns the auxiliary observation space component of the control variable.
Definition at line 144 of file ControlVariable.h.
 { return obsbias_; }
References oops::ControlVariable< MODEL >::obsbias_.
Referenced by oops::CostFunction< MODEL >::addIncrement(), and oops::CostJo< MODEL >::initializeTraj().
obsVar() [2/2]
template<typename MODEL > const ObsAuxCtrls_& oops::ControlVariable< MODEL >::obsVar () const inline
Returns the constant auxiliary observation space component of the control variable
Definition at line 147 of file ControlVariable.h.
 { return obsbias_; }
References oops::ControlVariable< MODEL >::obsbias_.
operator=()
template<typename MODEL > ControlVariable& oops::ControlVariable< MODEL >::operator= (const ControlVariable< MODEL > &) private
print()
template<typename MODEL > void oops::ControlVariable< MODEL >::print (std::ostream & outs) const private
Definition at line 257 of file ControlVariable.h.
{
   outs << state4d_;
   outs << *modbias_;
   outs << obsbias_;
 }
read()
template<typename MODEL > void oops::ControlVariable< MODEL >::read (const eckit::Configuration & config)
Read a control variable.
Definition at line 239 of file ControlVariable.h.
{
   state4d_.read(config);
   if (config.has("stateModAux")) modbias_->read(config);
   if (config.has("statesObsAux")) obsbias_.read(config);
 }
Referenced by oops::CostJo< MODEL >::initialize().
state() [1/2]
template<typename MODEL > State4D_& oops::ControlVariable< MODEL >::state () inline
Returns a 4D state component of the control variable.
Definition at line 131 of file ControlVariable.h.
 { return state4d_; }
References oops::ControlVariable< MODEL >::state4d_.
Referenced by oops::CostFct3DVar< MODEL >::addIncr(), oops::CostFct4DVar< MODEL >::addIncr(), oops::CostFctWeak< MODEL >::addIncr(), oops::CostFct4DEnsVar< MODEL >::addIncr(), oops::CostFct4DEnVar< MODEL >::addIncr(), oops::CostFct4DVarTrajHR< MODEL >::addIncr(), oops::CostFct4DVarMF< MODEL >::addIncr(), oops::CostFct4DVarTrajHR< MODEL >::evaluate(), oops::CostFct4DVarMF< MODEL >::evaluate(), oops::CostJcDFI< MODEL >::initialize(), oops::CostJcDFI< MODEL >::initializeTraj(), oops::CostFct4DVarTrajHR< MODEL >::linearize(), oops::CostFct4DVarMF< MODEL >::linearize(), oops::CostFunction< MODEL >::linearize(), oops::CostFct3DVar< MODEL >::newJb(), oops::CostFct4DVar< MODEL >::newJb(), oops::CostFct4DVarHyb4D< MODEL >::newJb(), oops::CostFctWeak< MODEL >::newJb(), oops::CostFct4DEnsVar< MODEL >::newJb(), oops::CostFct4DEnVar< MODEL >::newJb(), oops::CostFct4DVarMF< MODEL >::newJb(), oops::CostFct3DVar< MODEL >::runNL(), oops::CostFct4DVar< MODEL >::runNL(), oops::CostFctWeak< MODEL >::runNL(), oops::CostFct4DEnsVar< MODEL >::runNL(), oops::CostFct4DEnVar< MODEL >::runNL(), oops::CostFct4DVarMF< MODEL >::runNL(), and oops::Minimizer< MODEL >::tlmTaylorTest().
state() [2/2]
template<typename MODEL > const State4D_& oops::ControlVariable< MODEL >::state () const inline
Returns a constant 4D state component of the control variable.
Definition at line 133 of file ControlVariable.h.
 { return state4d_; }
References oops::ControlVariable< MODEL >::state4d_.
write()
template<typename MODEL > void oops::ControlVariable< MODEL >::write (const eckit::Configuration & config) const
Write a control variable.
Definition at line 248 of file ControlVariable.h.
{
   state4d_.write(config);
   if (config.has("stateModAux")) modbias_->write(config);
   if (config.has("statesObsAux")) obsbias_.write(config);
 }
Member Data Documentation
modbias_
template<typename MODEL > std::unique_ptr<ModelAuxCtrl_> oops::ControlVariable< MODEL >::modbias_ private
Auxiliary model space component.
Definition at line 154 of file ControlVariable.h.
Referenced by oops::ControlVariable< MODEL >::ControlVariable(), and oops::ControlVariable< MODEL >::modVar().
obsbias_
template<typename MODEL > ObsAuxCtrls_ oops::ControlVariable< MODEL >::obsbias_ private
Auxiliary observation space component.
Definition at line 155 of file ControlVariable.h.
Referenced by oops::ControlVariable< MODEL >::obsVar().
state4d_
template<typename MODEL > State4D_ oops::ControlVariable< MODEL >::state4d_ private
4D state component
Definition at line 153 of file ControlVariable.h.
Referenced by oops::ControlVariable< MODEL >::ControlVariable(), and oops::ControlVariable< MODEL >::state().
The documentation for this class was generated from the following file:
src/oops/assimilation/ControlVariable.h