OOPS Documentation: oops::DualConfigPostProcessor< FLDS > Class Template Reference
oops::DualConfigPostProcessor< FLDS > Class Template Reference
Control model post processing.
#include <DualConfigPostProcessor.h>
Public Member Functions
DualConfigPostProcessor ()
DualConfigPostProcessor (const DualConfigPostProcessor &pp)
~DualConfigPostProcessor ()
const PostProcessor_ & post1 () const
const PostProcessor_ & post2 () const
PostProcessor_ & post1 ()
PostProcessor_ & post2 ()
Private Types
using PostProcessor_ = PostProcessor< FLDS >
Private Member Functions
DualConfigPostProcessor operator= (const DualConfigPostProcessor &)
Private Attributes
PostProcessor_ post1_
PostProcessor_ post2_
Detailed Description
template<typename FLDS>
class oops::DualConfigPostProcessor< FLDS >
Control model post processing.
This class controls model post processing in the most general sense, ie all diagnostics computations that do not affect the dual config model integration. It just calls all the individual processors one by one.
Definition at line 26 of file DualConfigPostProcessor.h.
Member Typedef Documentation
PostProcessor_
template<typename FLDS > using oops::DualConfigPostProcessor< FLDS >::PostProcessor_ = PostProcessor<FLDS> private
Definition at line 27 of file DualConfigPostProcessor.h.
Constructor & Destructor Documentation
DualConfigPostProcessor() [1/2]
template<typename FLDS > oops::DualConfigPostProcessor< FLDS >::DualConfigPostProcessor () inline
Definition at line 30 of file DualConfigPostProcessor.h.
 {}
DualConfigPostProcessor() [2/2]
template<typename FLDS > oops::DualConfigPostProcessor< FLDS >::DualConfigPostProcessor (const DualConfigPostProcessor< FLDS > & pp) inline
Definition at line 31 of file DualConfigPostProcessor.h.
       : post1_(pp.post1_), post2_(pp.post2_) {}
~DualConfigPostProcessor()
template<typename FLDS > oops::DualConfigPostProcessor< FLDS >::~DualConfigPostProcessor () inline
Definition at line 33 of file DualConfigPostProcessor.h.
 {}
Member Function Documentation
operator=()
template<typename FLDS > DualConfigPostProcessor oops::DualConfigPostProcessor< FLDS >::operator= (const DualConfigPostProcessor< FLDS > &) private
post1() [1/2]
template<typename FLDS > PostProcessor_& oops::DualConfigPostProcessor< FLDS >::post1 () inline
Definition at line 38 of file DualConfigPostProcessor.h.
 { return post1_; }
References oops::DualConfigPostProcessor< FLDS >::post1_.
post1() [2/2]
template<typename FLDS > const PostProcessor_& oops::DualConfigPostProcessor< FLDS >::post1 () const inline
Definition at line 35 of file DualConfigPostProcessor.h.
 { return post1_; }
References oops::DualConfigPostProcessor< FLDS >::post1_.
Referenced by oops::DualConfigForecast< MODEL >::execute(), and oops::DualConfigModel< MODEL >::forecast().
post2() [1/2]
template<typename FLDS > PostProcessor_& oops::DualConfigPostProcessor< FLDS >::post2 () inline
Definition at line 39 of file DualConfigPostProcessor.h.
 { return post2_; }
References oops::DualConfigPostProcessor< FLDS >::post2_.
post2() [2/2]
template<typename FLDS > const PostProcessor_& oops::DualConfigPostProcessor< FLDS >::post2 () const inline
Definition at line 36 of file DualConfigPostProcessor.h.
 { return post2_; }
References oops::DualConfigPostProcessor< FLDS >::post2_.
Referenced by oops::DualConfigForecast< MODEL >::execute(), and oops::DualConfigModel< MODEL >::forecast().
Member Data Documentation
post1_
template<typename FLDS > PostProcessor_ oops::DualConfigPostProcessor< FLDS >::post1_ private
Definition at line 42 of file DualConfigPostProcessor.h.
Referenced by oops::DualConfigPostProcessor< FLDS >::post1().
post2_
template<typename FLDS > PostProcessor_ oops::DualConfigPostProcessor< FLDS >::post2_ private
Definition at line 43 of file DualConfigPostProcessor.h.
Referenced by oops::DualConfigPostProcessor< FLDS >::post2().
The documentation for this class was generated from the following file:
src/oops/generic/DualConfigPostProcessor.h