OOPS Documentation: oops::EnsembleCovsInterpol4D< MODEL > Class Template Reference
oops::EnsembleCovsInterpol4D< MODEL > Class Template Reference
Generic ensemble based model space error covariance.
#include <EnsembleCovsInterpol4D.h>
Public Member Functions
EnsembleCovsInterpol4D (const Geometry_ &, const Variables_ &, const eckit::Configuration &, const State4D_ &)
Constructor, destructor.
~EnsembleCovsInterpol4D ()
void advectedLinearize (const State4D_ &, const Geometry_ &, const eckit::Configuration &)
void advectedMultiply (const Increment4D_ &, Increment4D_ &) const
void advectedMultiplySqrt (const IncrCtlVec_ &, Increment4D_ &) const
void advectedMultiplySqrtTrans (const Increment4D_ &, IncrCtlVec_ &) const
void advectedInverseMultiply (const Increment4D_ &, Increment4D_ &) const
const ModelSpaceCovarianceBase< MODEL > & covar () const
IncrModCtlVec_ * newIncrModCtlVec () const override
IncrEnsCtlVec_ * newIncrEnsCtlVec () const override
Public Member Functions inherited from oops::ModelSpaceCovariance4DBase< MODEL >
ModelSpaceCovariance4DBase (const Geometry_ &, const eckit::Configuration &config)
virtual ~ModelSpaceCovariance4DBase ()
void linearize (const State4D_ &xb, const Geometry_ &resol, const eckit::Configuration &config)
virtual void multiply (const Increment4D_ &dxi, Increment4D_ &dxo) const
virtual void multiplySqrt (const IncrCtlVec_ &dvi, Increment4D_ &dxo) const
virtual void multiplySqrtTrans (const Increment4D_ &dxi, IncrCtlVec_ &dvo) const
void inverseMultiply (const Increment4D_ &dxi, Increment4D_ &dxo) const
virtual void randomize (Increment4D_ &) const
Private Types
using Ensemble_ = Ensemble< MODEL >
using EnsemblePtr_ = std::shared_ptr< Ensemble< MODEL > >
using EnsemblesCollection_ = EnsemblesCollection< MODEL >
using Geometry_ = Geometry< MODEL >
using Increment_ = Increment< MODEL >
using Localization_ = Localization< MODEL >
using State4D_ = State4D< MODEL >
using Increment4D_ = Increment4D< MODEL >
using IncrCtlVec_ = IncrCtlVec< MODEL >
using IncrEnsCtlVec_ = IncrEnsCtlVec< MODEL >
using IncrModCtlVec_ = IncrModCtlVec< MODEL >
using Variables_ = Variables< MODEL >
using Interpolator_ = Interpolator< MODEL >
Private Member Functions
void schur_add (const Increment_ &, const Increment_ &dxi, Increment_ &dxo, Increment_ &tmp) const
Private Attributes
const eckit::LocalConfiguration config_
unsigned nsubwin_
std::unique_ptr< Localization_ > loc_
std::unique_ptr< Interpolator_ > intdir_
std::unique_ptr< Interpolator_ > intadj_
std::unique_ptr< ModelSpaceCovarianceBase< MODEL > > static_
std::unique_ptr< Geometry_ > resol_ens_
Detailed Description
template<typename MODEL>
class oops::EnsembleCovsInterpol4D< MODEL >
Generic ensemble based model space error covariance.
Definition at line 40 of file EnsembleCovsInterpol4D.h.
Member Typedef Documentation
Ensemble_
template<typename MODEL > using oops::EnsembleCovsInterpol4D< MODEL >::Ensemble_ = Ensemble<MODEL> private
Definition at line 41 of file EnsembleCovsInterpol4D.h.
EnsemblePtr_
template<typename MODEL > using oops::EnsembleCovsInterpol4D< MODEL >::EnsemblePtr_ = std::shared_ptr<Ensemble<MODEL> > private
Definition at line 42 of file EnsembleCovsInterpol4D.h.
EnsemblesCollection_
template<typename MODEL > using oops::EnsembleCovsInterpol4D< MODEL >::EnsemblesCollection_ = EnsemblesCollection<MODEL> private
Definition at line 43 of file EnsembleCovsInterpol4D.h.
Geometry_
template<typename MODEL > using oops::EnsembleCovsInterpol4D< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 44 of file EnsembleCovsInterpol4D.h.
IncrCtlVec_
template<typename MODEL > using oops::EnsembleCovsInterpol4D< MODEL >::IncrCtlVec_ = IncrCtlVec<MODEL> private
Definition at line 49 of file EnsembleCovsInterpol4D.h.
Increment4D_
template<typename MODEL > using oops::EnsembleCovsInterpol4D< MODEL >::Increment4D_ = Increment4D<MODEL> private
Definition at line 48 of file EnsembleCovsInterpol4D.h.
Increment_
template<typename MODEL > using oops::EnsembleCovsInterpol4D< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 45 of file EnsembleCovsInterpol4D.h.
IncrEnsCtlVec_
template<typename MODEL > using oops::EnsembleCovsInterpol4D< MODEL >::IncrEnsCtlVec_ = IncrEnsCtlVec<MODEL> private
Definition at line 50 of file EnsembleCovsInterpol4D.h.
IncrModCtlVec_
template<typename MODEL > using oops::EnsembleCovsInterpol4D< MODEL >::IncrModCtlVec_ = IncrModCtlVec<MODEL> private
Definition at line 51 of file EnsembleCovsInterpol4D.h.
Interpolator_
template<typename MODEL > using oops::EnsembleCovsInterpol4D< MODEL >::Interpolator_ = Interpolator<MODEL> private
Definition at line 53 of file EnsembleCovsInterpol4D.h.
Localization_
template<typename MODEL > using oops::EnsembleCovsInterpol4D< MODEL >::Localization_ = Localization<MODEL> private
Definition at line 46 of file EnsembleCovsInterpol4D.h.
State4D_
template<typename MODEL > using oops::EnsembleCovsInterpol4D< MODEL >::State4D_ = State4D<MODEL> private
Definition at line 47 of file EnsembleCovsInterpol4D.h.
Variables_
template<typename MODEL > using oops::EnsembleCovsInterpol4D< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 52 of file EnsembleCovsInterpol4D.h.
Constructor & Destructor Documentation
EnsembleCovsInterpol4D()
template<typename MODEL > oops::EnsembleCovsInterpol4D< MODEL >::EnsembleCovsInterpol4D (const Geometry_ & resol, const Variables_ & , const eckit::Configuration & config, const State4D_ &)
Constructor, destructor.
Definition at line 93 of file EnsembleCovsInterpol4D.h.
     : ModelSpaceCovariance4DBase<MODEL>::ModelSpaceCovariance4DBase(resol,
                                                                     config),
       config_(config),
       nsubwin_(0),
       loc_(),
       static_() {
   Log::trace() << "EnsembleCovsInterpol4D created.";
 }
~EnsembleCovsInterpol4D()
template<typename MODEL > oops::EnsembleCovsInterpol4D< MODEL >::~EnsembleCovsInterpol4D
Definition at line 106 of file EnsembleCovsInterpol4D.h.
{
   Log::trace() << "EnsembleCovsInterpol4D destructed.";
 }
Member Function Documentation
advectedInverseMultiply()
template<typename MODEL > void oops::EnsembleCovsInterpol4D< MODEL >::advectedInverseMultiply (const Increment4D_ & dxi, Increment4D_ & dxo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 302 of file EnsembleCovsInterpol4D.h.
{
   dxo.zero();
 }
References oops::Increment4D< MODEL >::zero().
advectedLinearize()
template<typename MODEL > void oops::EnsembleCovsInterpol4D< MODEL >::advectedLinearize (const State4D_ & xb, const Geometry_ & resol, const eckit::Configuration &) virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 111 of file EnsembleCovsInterpol4D.h.
{
   /*
    * Build Geometry of the Ensemble
    */
   const eckit::LocalConfiguration confNewGeo(config_, "ensemble_resol");
   resol_ens_.reset(new Geometry_(confNewGeo));
   /*
    * Build localization
    */
   const eckit::LocalConfiguration conf(config_, "localization");
   loc_.reset(new Localization_(*resol_ens_, conf));
   /*
    * Build Interpolation operators
    */
   const eckit::LocalConfiguration confInterpol(config_, "interpol");
   intdir_.reset(new Interpolator_(xb[0], *resol_ens_, confInterpol, false));
   intadj_.reset(new Interpolator_(xb[0], *resol_ens_, confInterpol, true));
   /*
    * Build ensemble
    */
   std::vector<eckit::LocalConfiguration> confEnsemble;
   config_.get("ensemble", confEnsemble);
   nsubwin_ = confEnsemble.size();
   for (unsigned jsub = 0; jsub < nsubwin_; ++jsub) {
     EnsemblePtr_ ens_k(new Ensemble_(xb[jsub].validTime(), confEnsemble[jsub]));
     ens_k->build(xb[jsub], *resol_ens_);
     EnsemblesCollection_::getInstance().put(xb[jsub].validTime(), ens_k);
   }
   /*
    * Read files
    */
   for (unsigned jsub = 0; jsub < nsubwin_; ++jsub) {
     EnsemblePtr_ ens =
         EnsemblesCollection_::getInstance()[xb[jsub].validTime()];
     ens->read();
   }
   /*
    * Calculate mean
    */
   for (unsigned jsub = 0; jsub < nsubwin_; ++jsub) {
     EnsemblePtr_ ens =
         EnsemblesCollection_::getInstance()[xb[jsub].validTime()];
     ens->to_perturbations();
   }
   Log::trace() << "EnsembleCovsInterpol4D linearized.";
 }
advectedMultiply()
template<typename MODEL > void oops::EnsembleCovsInterpol4D< MODEL >::advectedMultiply (const Increment4D_ & dxi, Increment4D_ & dxo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 168 of file EnsembleCovsInterpol4D.h.
{
   EnsemblePtr_ e = EnsemblesCollection_::getInstance()[dxi[0].validTime()];
   dxo.zero();
   // Adjoint interpolation to the resolution of the perturbations
   const eckit::LocalConfiguration confInterpol(config_, "interpol");
   const Variables_ var(confInterpol);
   Increment4D_ dx_lr(*resol_ens_, dxi);
   dx_lr.zero();
   for (unsigned k = 0; k < nsubwin_; ++k) {
     Log::trace()
         << "Adjoint Interpolation (HR -> LR) of the increment for timeslot #"
         << k;
     intadj_->interpolate(dxi[k], var, dx_lr[k]);
   }
   Increment_ dx_lr_loc(dx_lr[0]);
   Increment_ tmp(dx_lr[0]);
   Increment4D_ dxo_lr(dx_lr);
   dxo_lr.zero();
   for (unsigned l = 0; l < e->size(); ++l) {
     dx_lr_loc.zero();
     for (unsigned k2 = 0; k2 < nsubwin_; ++k2) {
       EnsemblePtr_ e_k2 =
           EnsemblesCollection_::getInstance()[dx_lr[k2].validTime()];
       schur_add((*e_k2)[l], dx_lr[k2], dx_lr_loc, tmp);
     }
     loc_->multiply(dx_lr_loc);
     for (unsigned k1 = 0; k1 < nsubwin_; ++k1) {
       EnsemblePtr_ e_k1 =
           EnsemblesCollection_::getInstance()[dx_lr[k1].validTime()];
       schur_add((*e_k1)[l], dx_lr_loc, dxo_lr[k1], tmp);
     }
   }
   // Back to HR
   for (unsigned k = 0; k < nsubwin_; ++k) {
     Log::trace()
         << "Direct interpolation (LR -> HR) of the increment for timeslot #"
         << k;
     intdir_->interpolate(dxo_lr[k], var, dxo[k]);
   }
 }
References oops::Increment4D< MODEL >::zero(), and oops::Increment< MODEL >::zero().
advectedMultiplySqrt()
template<typename MODEL > void oops::EnsembleCovsInterpol4D< MODEL >::advectedMultiplySqrt (const IncrCtlVec_ & dvi, Increment4D_ & dxo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 221 of file EnsembleCovsInterpol4D.h.
{
   EnsemblePtr_ e = EnsemblesCollection_::getInstance()[dxo[0].validTime()];
   // Interpolation to the resolution of the increment
   const eckit::LocalConfiguration confInterpol(config_, "interpol");
   const Variables_ var(confInterpol);
   Increment4D_ dx_lr(*resol_ens_, dxo);
   Increment_ dx_lr_loc(dx_lr[0]);
   Increment_ tmp(dx_lr_loc);
   Increment4D_ dxo_lr(dx_lr);
   dxo_lr.zero();
   dxo.zero();
   for (unsigned l = 0; l < e->size(); ++l) {
     loc_->multiplySqrt(dvi.ensCtlVec(l), dx_lr_loc);
     for (unsigned k1 = 0; k1 < nsubwin_; ++k1) {
       EnsemblePtr_ e_k1 =
           EnsemblesCollection_::getInstance()[dxo[k1].validTime()];
       schur_add((*e_k1)[l], dx_lr_loc, dxo_lr[k1], tmp);
     }
   }
   // Back to HR
   for (unsigned k = 0; k < nsubwin_; ++k) {
     Log::trace()
         << "Direct interpolation (LR -> HR) of the increment for timeslot #"
         << k;
     intdir_->interpolate(dxo_lr[k], var, dxo[k]);
   }
 }
References oops::IncrCtlVec< MODEL >::ensCtlVec(), and oops::Increment4D< MODEL >::zero().
advectedMultiplySqrtTrans()
template<typename MODEL > void oops::EnsembleCovsInterpol4D< MODEL >::advectedMultiplySqrtTrans (const Increment4D_ & dxi, IncrCtlVec_ & dvo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 257 of file EnsembleCovsInterpol4D.h.
{
   EnsemblePtr_ e = EnsemblesCollection_::getInstance()[dxi[0].validTime()];
   // Adjoint interpolation to the resolution of the increment
   const eckit::LocalConfiguration confInterpol(config_, "interpol");
   const Variables_ var(confInterpol);
   Increment4D_ dx_lr(*resol_ens_, dxi);
   dx_lr.zero();
   for (unsigned k = 0; k < nsubwin_; ++k) {
     Log::trace()
         << "Adjoint Interpolation (HR -> LR) of the increment for timeslot #"
         << k;
     intadj_->interpolate(dxi[k], var, dx_lr[k]);
   }
   Increment_ dx_lr_loc(dx_lr[0]);
   Increment_ tmp(dx_lr[0]);
   for (unsigned l = 0; l < e->size(); ++l) {
     dx_lr_loc.zero();
     for (unsigned k2 = 0; k2 < nsubwin_; ++k2) {
       EnsemblePtr_ e_k2 =
           EnsemblesCollection_::getInstance()[dx_lr[k2].validTime()];
       schur_add((*e_k2)[l], dx_lr[k2], dx_lr_loc, tmp);
     }
     loc_->multiplySqrtTrans(dx_lr_loc, dvo.ensCtlVec(l));
   }
 }
References oops::IncrCtlVec< MODEL >::ensCtlVec(), oops::Increment4D< MODEL >::zero(), and oops::Increment< MODEL >::zero().
covar()
template<typename MODEL > const ModelSpaceCovarianceBase<MODEL>& oops::EnsembleCovsInterpol4D< MODEL >::covar () const inline virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 65 of file EnsembleCovsInterpol4D.h.
 { return *static_; }
References oops::EnsembleCovsInterpol4D< MODEL >::static_.
newIncrEnsCtlVec()
template<typename MODEL > IncrEnsCtlVec_* oops::EnsembleCovsInterpol4D< MODEL >::newIncrEnsCtlVec () const inline override virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 71 of file EnsembleCovsInterpol4D.h.
{
     return new IncrEnsCtlVec_(*resol_ens_, *loc_);
   }
References oops::EnsembleCovsInterpol4D< MODEL >::loc_, and oops::EnsembleCovsInterpol4D< MODEL >::resol_ens_.
newIncrModCtlVec()
template<typename MODEL > IncrModCtlVec_* oops::EnsembleCovsInterpol4D< MODEL >::newIncrModCtlVec () const inline override virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 68 of file EnsembleCovsInterpol4D.h.
{
     return new IncrModCtlVec_();
   }
schur_add()
template<typename MODEL > void oops::EnsembleCovsInterpol4D< MODEL >::schur_add (const Increment_ & pert, const Increment_ & dxi, Increment_ & dxo, Increment_ & tmp) const private
Definition at line 291 of file EnsembleCovsInterpol4D.h.
{
   tmp_schur = pert;
   tmp_schur.schur_product_with(dxi);
   dxo.axpy(1.0, tmp_schur, false);
 }
References oops::Increment< MODEL >::axpy(), and oops::Increment< MODEL >::schur_product_with().
Member Data Documentation
config_
template<typename MODEL > const eckit::LocalConfiguration oops::EnsembleCovsInterpol4D< MODEL >::config_ private
Definition at line 79 of file EnsembleCovsInterpol4D.h.
intadj_
template<typename MODEL > std::unique_ptr<Interpolator_> oops::EnsembleCovsInterpol4D< MODEL >::intadj_ private
Definition at line 83 of file EnsembleCovsInterpol4D.h.
intdir_
template<typename MODEL > std::unique_ptr<Interpolator_> oops::EnsembleCovsInterpol4D< MODEL >::intdir_ private
Definition at line 82 of file EnsembleCovsInterpol4D.h.
loc_
template<typename MODEL > std::unique_ptr<Localization_> oops::EnsembleCovsInterpol4D< MODEL >::loc_ private
Definition at line 81 of file EnsembleCovsInterpol4D.h.
Referenced by oops::EnsembleCovsInterpol4D< MODEL >::newIncrEnsCtlVec().
nsubwin_
template<typename MODEL > unsigned oops::EnsembleCovsInterpol4D< MODEL >::nsubwin_ private
Definition at line 80 of file EnsembleCovsInterpol4D.h.
resol_ens_
template<typename MODEL > std::unique_ptr<Geometry_> oops::EnsembleCovsInterpol4D< MODEL >::resol_ens_ private
Definition at line 85 of file EnsembleCovsInterpol4D.h.
Referenced by oops::EnsembleCovsInterpol4D< MODEL >::newIncrEnsCtlVec().
static_
template<typename MODEL > std::unique_ptr<ModelSpaceCovarianceBase<MODEL> > oops::EnsembleCovsInterpol4D< MODEL >::static_ private
Definition at line 84 of file EnsembleCovsInterpol4D.h.
Referenced by oops::EnsembleCovsInterpol4D< MODEL >::covar().
The documentation for this class was generated from the following file:
src/oops/base/EnsembleCovsInterpol4D.h