OOPS Documentation: oops::ObsAuxIncrements< MODEL > Class Template Reference
oops::ObsAuxIncrements< MODEL > Class Template Reference
Encapsulates a vector of ObsAuxIncrement objects.
#include <ObsAuxIncrements.h>
Public Member Functions
ObsAuxIncrements (const ObsSpaces_ &, const eckit::Configuration &)
Constructor.
ObsAuxIncrements (const ObsAuxIncrements &, const bool copy=true)
Copy constructor.
ObsAuxIncrements (const ObsAuxIncrements &, const eckit::Configuration &)
Copy constructor.
~ObsAuxIncrements ()
Destructor.
std::size_t size () const
Return the size.
const ObsAuxIncrement_ & operator[] (const std::size_t ii) const
Return a constant reference to the i-th ObsAuxIncrement object.
ObsAuxIncrement_ & operator[] (const std::size_t ii)
Return a reference to the i-th ObsAuxIncrement object.
void diff (const ObsAuxControls_ &, const ObsAuxControls_ &)
\(dx = x_1 - x_2 \)
void zero ()
\(dx_1 = 0 \)
ObsAuxIncrements & operator= (const ObsAuxIncrements &)
\(dx_1 = dx_2 \)
ObsAuxIncrements & operator+= (const ObsAuxIncrements &)
\(dx_1 = dx_1 + dx_2 \)
ObsAuxIncrements & operator-= (const ObsAuxIncrements &)
\(dx_1 = dx_1 - dx_2 \)
ObsAuxIncrements & operator*= (const double &)
\(dx_1 = dx_1 * c \)
void axpy (const double &, const ObsAuxIncrements &)
\(dx_1 = dx_1 * c dx_2 \)
double dot_product_with (const ObsAuxIncrements &) const
\(<dx_1,dx_1> = dx_1^T dx_1 \)
void read (const eckit::Configuration &)
Read control increment.
void write (const eckit::Configuration &) const
Write control increment.
double norm () const
L-2 norm.
Static Public Member Functions
static const std::string classname ()
Private Types
using ObsAuxIncrement_ = ObsAuxIncrement< MODEL >
using ObsAuxControls_ = ObsAuxControls< MODEL >
using ObsSpaces_ = ObservationSpaces< MODEL >
Private Member Functions
void print (std::ostream &) const
Private Attributes
std::vector< std::shared_ptr< ObsAuxIncrement_ > > auxs_
Vector of shared pointers to ObsAuxIncrement objects.
Detailed Description
template<typename MODEL>
class oops::ObsAuxIncrements< MODEL >
Encapsulates a vector of ObsAuxIncrement objects.
An object of ObsAuxIncrements class is part of ControlIncrement. The class contains a vector of ObsAuxIncrement bjects. Refer to the documentation of ControlIncrement and CostJo to understand the structure.
Definition at line 36 of file ObsAuxIncrements.h.
Member Typedef Documentation
ObsAuxControls_
template<typename MODEL > using oops::ObsAuxIncrements< MODEL >::ObsAuxControls_ = ObsAuxControls<MODEL> private
Definition at line 38 of file ObsAuxIncrements.h.
ObsAuxIncrement_
template<typename MODEL > using oops::ObsAuxIncrements< MODEL >::ObsAuxIncrement_ = ObsAuxIncrement<MODEL> private
Definition at line 37 of file ObsAuxIncrements.h.
ObsSpaces_
template<typename MODEL > using oops::ObsAuxIncrements< MODEL >::ObsSpaces_ = ObservationSpaces<MODEL> private
Definition at line 39 of file ObsAuxIncrements.h.
Constructor & Destructor Documentation
ObsAuxIncrements() [1/3]
template<typename MODEL > oops::ObsAuxIncrements< MODEL >::ObsAuxIncrements (const ObsSpaces_ & odb, const eckit::Configuration & conf)
Constructor.
Definition at line 115 of file ObsAuxIncrements.h.
     : auxs_(0) {
   std::vector<eckit::LocalConfiguration> obsconf;
   conf.get("ObsTypes", obsconf);
   for (std::size_t jobs = 0; jobs < obsconf.size(); ++jobs) {
     std::shared_ptr<ObsAuxIncrement_> tmp(
         new ObsAuxIncrement_(odb[jobs], obsconf[jobs]));
     auxs_.push_back(tmp);
   }
 }
References oops::ObsAuxIncrements< MODEL >::auxs_.
ObsAuxIncrements() [2/3]
template<typename MODEL > oops::ObsAuxIncrements< MODEL >::ObsAuxIncrements (const ObsAuxIncrements< MODEL > & other, const bool copy = true)
Copy constructor.
Definition at line 128 of file ObsAuxIncrements.h.
     : auxs_(other.size()) {
   Log::trace() << "ObsAuxIncrements<MODEL>::ObsAuxIncrements starting"
                << std::endl;
   ASSERT(size() == other.size());
   for (std::size_t jobs = 0; jobs < other.size(); ++jobs) {
     auxs_[jobs].reset(new ObsAuxIncrement_(other[jobs], copy));
   }
   Log::trace() << "ObsAuxIncrements<MODEL>::ObsAuxIncrements done" << std::endl;
 }
References oops::ObsAuxIncrements< MODEL >::auxs_, and oops::ObsAuxIncrements< MODEL >::size().
ObsAuxIncrements() [3/3]
template<typename MODEL > oops::ObsAuxIncrements< MODEL >::ObsAuxIncrements (const ObsAuxIncrements< MODEL > & other, const eckit::Configuration & conf)
Copy constructor.
Definition at line 141 of file ObsAuxIncrements.h.
     : auxs_(other.size()) {
   Log::trace() << "ObsAuxIncrements<MODEL>::ObsAuxIncrements starting"
                << std::endl;
   std::vector<eckit::LocalConfiguration> obsconf;
   ASSERT(size() == other.size());
   for (std::size_t jobs = 0; jobs < other.size(); ++jobs) {
     auxs_[jobs].reset(new ObsAuxIncrement_(other[jobs]));
   }
   Log::trace() << "ObsAuxIncrements<MODEL>::ObsAuxIncrements done" << std::endl;
 }
References oops::ObsAuxIncrements< MODEL >::auxs_, and oops::ObsAuxIncrements< MODEL >::size().
~ObsAuxIncrements()
template<typename MODEL > oops::ObsAuxIncrements< MODEL >::~ObsAuxIncrements
Destructor.
Definition at line 155 of file ObsAuxIncrements.h.
{
   Log::trace() << "ObsAuxIncrements<MODEL>::~ObsAuxIncrements starting"
                << std::endl;
   for (std::size_t jobs = 0; jobs < auxs_.size(); ++jobs) auxs_[jobs].reset();
   Log::trace() << "ObsAuxIncrements<MODEL>::~ObsAuxIncrements done"
                << std::endl;
 }
Member Function Documentation
axpy()
template<typename MODEL > void oops::ObsAuxIncrements< MODEL >::axpy (const double & zz, const ObsAuxIncrements< MODEL > & dx)
\(dx_1 = dx_1 * c dx_2 \)
Definition at line 230 of file ObsAuxIncrements.h.
{
   Log::trace() << "ObsAuxIncrements<MODEL>::axpy starting" << std::endl;
   ASSERT(size() == dx.size());
   for (std::size_t jobs = 0; jobs < size(); ++jobs) {
     auxs_[jobs]->axpy(zz, dx[jobs]);
   }
   Log::trace() << "ObsAuxIncrements<MODEL>::axpy done" << std::endl;
 }
References oops::ObsAuxIncrements< MODEL >::size().
classname()
template<typename MODEL > static const std::string oops::ObsAuxIncrements< MODEL >::classname () inline static
Definition at line 42 of file ObsAuxIncrements.h.
 { return "oops::ObsAuxIncrements"; }
diff()
template<typename MODEL > void oops::ObsAuxIncrements< MODEL >::diff (const ObsAuxControls_ & x1, const ObsAuxControls_ & x2)
\(dx = x_1 - x_2 \)
Definition at line 164 of file ObsAuxIncrements.h.
{
   Log::trace() << "ObsAuxIncrements<MODEL>::diff starting" << std::endl;
   ASSERT(x1.size() == x2.size() && size() == x2.size());
   for (std::size_t jobs = 0; jobs < size(); ++jobs) {
     auxs_[jobs]->diff(x1[jobs], x2[jobs]);
   }
   Log::trace() << "ObsAuxIncrements<MODEL>::diff done" << std::endl;
 }
References oops::ObsAuxControls< MODEL >::size().
Referenced by oops::CostJbTotal< MODEL >::finalize().
dot_product_with()
template<typename MODEL > double oops::ObsAuxIncrements< MODEL >::dot_product_with (const ObsAuxIncrements< MODEL > & dx) const
\(<dx_1,dx_1> = dx_1^T dx_1 \)
Definition at line 241 of file ObsAuxIncrements.h.
{
   Log::trace() << "ObsAuxIncrements<MODEL>::dot_product_with starting"
                << std::endl;
   ASSERT(size() == dx.size());
   double zz = static_cast<double>(0.0);
   for (std::size_t jobs = 0; jobs < size(); ++jobs) {
     zz += auxs_[jobs]->dot_product_with(dx[jobs]);
   }
   Log::trace() << "ObsAuxIncrements<MODEL>::dot_product_with done" << std::endl;
   return zz;
 }
References oops::ObsAuxIncrements< MODEL >::size().
norm()
template<typename MODEL > double oops::ObsAuxIncrements< MODEL >::norm
L-2 norm.
Definition at line 277 of file ObsAuxIncrements.h.
{
   Log::trace() << "ObsAuxIncrements<MODEL>::norm starting" << std::endl;
   double zz = static_cast<double>(0.0);
   for (std::size_t jobs = 0; jobs < size(); ++jobs) {
     double norm = auxs_[jobs]->norm();
     zz += norm * norm;
   }
   Log::trace() << "ObsAuxIncrements<MODEL>::norm done" << std::endl;
   return std::sqrt(zz);
 }
operator*=()
template<typename MODEL > ObsAuxIncrements< MODEL > & oops::ObsAuxIncrements< MODEL >::operator*= (const double & zz)
\(dx_1 = dx_1 * c \)
Definition at line 220 of file ObsAuxIncrements.h.
{
   Log::trace() << "ObsAuxIncrements<MODEL>::operator*= starting" << std::endl;
   for (std::size_t jobs = 0; jobs < size(); ++jobs) {
     *auxs_[jobs] *= zz;
   }
   Log::trace() << "ObsAuxIncrements<MODEL>::operator*= done" << std::endl;
   return *this;
 }
operator+=()
template<typename MODEL > ObsAuxIncrements< MODEL > & oops::ObsAuxIncrements< MODEL >::operator+= (const ObsAuxIncrements< MODEL > & rhs)
\(dx_1 = dx_1 + dx_2 \)
Definition at line 196 of file ObsAuxIncrements.h.
{
   Log::trace() << "ObsAuxIncrements<MODEL>::operator+= starting" << std::endl;
   ASSERT(size() == rhs.size());
   for (std::size_t jobs = 0; jobs < size(); ++jobs) {
     *auxs_[jobs] += rhs[jobs];
   }
   Log::trace() << "ObsAuxIncrements<MODEL>::operator+= done" << std::endl;
   return *this;
 }
References oops::ObsAuxIncrements< MODEL >::size().
operator-=()
template<typename MODEL > ObsAuxIncrements< MODEL > & oops::ObsAuxIncrements< MODEL >::operator-= (const ObsAuxIncrements< MODEL > & rhs)
\(dx_1 = dx_1 - dx_2 \)
Definition at line 208 of file ObsAuxIncrements.h.
{
   Log::trace() << "ObsAuxIncrements<MODEL>::operator-= starting" << std::endl;
   ASSERT(size() == rhs.size());
   for (std::size_t jobs = 0; jobs < size(); ++jobs) {
     *auxs_[jobs] -= rhs[jobs];
   }
   Log::trace() << "ObsAuxIncrements<MODEL>::operator-= done" << std::endl;
   return *this;
 }
References oops::ObsAuxIncrements< MODEL >::size().
operator=()
template<typename MODEL > ObsAuxIncrements< MODEL > & oops::ObsAuxIncrements< MODEL >::operator= (const ObsAuxIncrements< MODEL > & rhs)
\(dx_1 = dx_2 \)
Definition at line 184 of file ObsAuxIncrements.h.
{
   Log::trace() << "ObsAuxIncrements<MODEL>::operator= starting" << std::endl;
   ASSERT(size() == rhs.size());
   for (std::size_t jobs = 0; jobs < size(); ++jobs) {
     *auxs_[jobs] = rhs[jobs];
   }
   Log::trace() << "ObsAuxIncrements<MODEL>::operator= done" << std::endl;
   return *this;
 }
References oops::ObsAuxIncrements< MODEL >::size().
operator[]() [1/2]
template<typename MODEL > ObsAuxIncrement_& oops::ObsAuxIncrements< MODEL >::operator[] (const std::size_t ii) inline
Return a reference to the i-th ObsAuxIncrement object.
Definition at line 61 of file ObsAuxIncrements.h.
 { return *auxs_.at(ii); }
References oops::ObsAuxIncrements< MODEL >::auxs_.
operator[]() [2/2]
template<typename MODEL > const ObsAuxIncrement_& oops::ObsAuxIncrements< MODEL >::operator[] (const std::size_t ii) const inline
Return a constant reference to the i-th ObsAuxIncrement object.
Definition at line 57 of file ObsAuxIncrements.h.
{
     return *auxs_.at(ii);
   }
References oops::ObsAuxIncrements< MODEL >::auxs_.
print()
template<typename MODEL > void oops::ObsAuxIncrements< MODEL >::print (std::ostream & os) const private
Definition at line 289 of file ObsAuxIncrements.h.
{
   for (std::size_t jobs = 0; jobs < auxs_.size(); ++jobs) os << *auxs_[jobs];
 }
read()
template<typename MODEL > void oops::ObsAuxIncrements< MODEL >::read (const eckit::Configuration & conf)
Read control increment.
Definition at line 255 of file ObsAuxIncrements.h.
{
   Log::trace() << "ObsAuxIncrements<MODEL>::read starting" << std::endl;
   std::vector<eckit::LocalConfiguration> obsconfs;
   conf.get("incrementsObsAux", obsconfs);
   ASSERT(auxs_.size() >= obsconfs.size());
   for (std::size_t jobs = 0; jobs < obsconfs.size(); ++jobs)
     auxs_[jobs]->read(obsconfs[jobs]);
   Log::trace() << "ObsAuxIncrements<MODEL>::read done" << std::endl;
 }
size()
template<typename MODEL > std::size_t oops::ObsAuxIncrements< MODEL >::size () const inline
Return the size.
Definition at line 55 of file ObsAuxIncrements.h.
 { return auxs_.size(); }
References oops::ObsAuxIncrements< MODEL >::auxs_.
Referenced by oops::ObsAuxIncrements< MODEL >::axpy(), oops::ObsAuxIncrements< MODEL >::dot_product_with(), oops::ObsAuxCovariances< MODEL >::inverseMultiply(), oops::ObsAuxCovariances< MODEL >::multiply(), oops::ObsAuxCovariances< MODEL >::multiplySqrt(), oops::ObsAuxCovariances< MODEL >::multiplySqrtTrans(), oops::ObsAuxIncrements< MODEL >::ObsAuxIncrements(), oops::ObsAuxIncrements< MODEL >::operator+=(), oops::operator+=(), oops::ObsAuxIncrements< MODEL >::operator-=(), oops::ObsAuxIncrements< MODEL >::operator=(), and oops::ObsAuxCovariances< MODEL >::randomize().
write()
template<typename MODEL > void oops::ObsAuxIncrements< MODEL >::write (const eckit::Configuration & conf) const
Write control increment.
Definition at line 266 of file ObsAuxIncrements.h.
{
   Log::trace() << "ObsAuxIncrements<MODEL>::write starting" << std::endl;
   std::vector<eckit::LocalConfiguration> obsconfs;
   conf.get("incrementsObsAux", obsconfs);
   ASSERT(auxs_.size() >= obsconfs.size());
   for (std::size_t jobs = 0; jobs < obsconfs.size(); ++jobs)
     auxs_[jobs]->write(obsconfs[jobs]);
   Log::trace() << "ObsAuxIncrements<MODEL>::write done" << std::endl;
 }
Referenced by oops::CostJbTotal< MODEL >::writeIncrement().
zero()
template<typename MODEL > void oops::ObsAuxIncrements< MODEL >::zero
\(dx_1 = 0 \)
Definition at line 175 of file ObsAuxIncrements.h.
{
   Log::trace() << "ObsAuxIncrements<MODEL>::zero starting" << std::endl;
   for (std::size_t jobs = 0; jobs < size(); ++jobs) {
     auxs_[jobs]->zero();
   }
   Log::trace() << "ObsAuxIncrements<MODEL>::zero done" << std::endl;
 }
Referenced by oops::JbMatrix< MODEL >::multiply(), oops::BMatrix< MODEL >::multiplyId(), oops::CostFct3DVar< MODEL >::zeroAD(), oops::CostFctWeak< MODEL >::zeroAD(), oops::CostFct4DVar< MODEL >::zeroAD(), oops::CostFct4DVarHyb4D< MODEL >::zeroAD(), oops::CostFct4DEnsVar< MODEL >::zeroAD(), oops::CostFct4DEnVar< MODEL >::zeroAD(), and oops::CostFct4DVarMF< MODEL >::zeroAD().
Member Data Documentation
auxs_
template<typename MODEL > std::vector<std::shared_ptr<ObsAuxIncrement_> > oops::ObsAuxIncrements< MODEL >::auxs_ private
Vector of shared pointers to ObsAuxIncrement objects.
Definition at line 93 of file ObsAuxIncrements.h.
Referenced by oops::ObsAuxIncrements< MODEL >::ObsAuxIncrements(), oops::ObsAuxIncrements< MODEL >::operator[](), and oops::ObsAuxIncrements< MODEL >::size().
The documentation for this class was generated from the following file:
src/oops/base/ObsAuxIncrements.h