OOPS Documentation: oops::EnsembleCovarianceSDL< MODEL > Class Template Reference
oops::EnsembleCovarianceSDL< MODEL > Class Template Reference
Generic ensemble based model space error covariance.
#include <EnsembleCovarianceSDL.h>
Public Member Functions
EnsembleCovarianceSDL (const Geometry_ &, const Variables_ &, const eckit::Configuration &, const State_ &)
Constructor, destructor.
~EnsembleCovarianceSDL ()
void linearize (const State_ &, const Geometry_ &, const eckit::Configuration &) override
Set up the inner loop resolution B matrix.
void multiply (const Increment_ &, Increment_ &) const override
\(dx_1 = B dx_2 \)
void inverseMultiply (const Increment_ &, Increment_ &) const override
\(dx_1 = B^{-1} dx_2 \)
void multiplySqrt (const IncrCtlVec_ &, Increment_ &) const override
\(dx = B^{1/2} dv \)
void multiplySqrtTrans (const Increment_ &, IncrCtlVec_ &) const override
\(dv = [B^{1/2}]^T dx \)
void randomize (Increment_ &) const override
\(dx = B^{1/2} dv_{random} \)
IncrModCtlVec_ * newIncrModCtlVec () const override
IncrEnsCtlVec_ * newIncrEnsCtlVec () const override
Public Member Functions inherited from oops::ModelSpaceCovarianceBase< MODEL >
virtual ~ModelSpaceCovarianceBase ()
Destructor.
Private Types
using Ensemble_ = Ensemble< MODEL >
using EnsemblePtr_ = std::shared_ptr< Ensemble< MODEL > >
using EnsemblesCollection_ = EnsemblesCollection< MODEL >
using Geometry_ = Geometry< MODEL >
using Increment_ = Increment< MODEL >
using IncrCtlVec_ = IncrCtlVec< MODEL >
using IncrEnsCtlVec_ = IncrEnsCtlVec< MODEL >
using IncrModCtlVec_ = IncrModCtlVec< MODEL >
using Localization_ = Localization< MODEL >
using State_ = State< MODEL >
using Variables_ = Variables< MODEL >
using GenericMatrix_ = GenericMatrix< MODEL >
using MatrixFactory_ = GenericMatrixFactory< MODEL >
using HorizScaleDecomposition_ = HorizScaleDecomposition< MODEL >
Private Attributes
const eckit::LocalConfiguration config_
Configuration.
const util::DateTime time_
Valid time.
bool has_change_of_variable_
Change of variable.
std::vector< std::unique_ptr< Localization_ > > loc_
Localization matrix.
std::unique_ptr< Geometry_ > geom_
Pointer to a geometry object.
std::unique_ptr< GenericMatrix_ > change_of_variable_
int nhorizBand_
unsigned members_
Detailed Description
template<typename MODEL>
class oops::EnsembleCovarianceSDL< MODEL >
Generic ensemble based model space error covariance.
This class implements a generic localized sampled model space error covariance matrix.
Definition at line 46 of file EnsembleCovarianceSDL.h.
Member Typedef Documentation
Ensemble_
template<typename MODEL > using oops::EnsembleCovarianceSDL< MODEL >::Ensemble_ = Ensemble<MODEL> private
Definition at line 47 of file EnsembleCovarianceSDL.h.
EnsemblePtr_
template<typename MODEL > using oops::EnsembleCovarianceSDL< MODEL >::EnsemblePtr_ = std::shared_ptr<Ensemble<MODEL> > private
Definition at line 48 of file EnsembleCovarianceSDL.h.
EnsemblesCollection_
template<typename MODEL > using oops::EnsembleCovarianceSDL< MODEL >::EnsemblesCollection_ = EnsemblesCollection<MODEL> private
Definition at line 49 of file EnsembleCovarianceSDL.h.
GenericMatrix_
template<typename MODEL > using oops::EnsembleCovarianceSDL< MODEL >::GenericMatrix_ = GenericMatrix<MODEL> private
Definition at line 58 of file EnsembleCovarianceSDL.h.
Geometry_
template<typename MODEL > using oops::EnsembleCovarianceSDL< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 50 of file EnsembleCovarianceSDL.h.
HorizScaleDecomposition_
template<typename MODEL > using oops::EnsembleCovarianceSDL< MODEL >::HorizScaleDecomposition_ = HorizScaleDecomposition<MODEL> private
Definition at line 60 of file EnsembleCovarianceSDL.h.
IncrCtlVec_
template<typename MODEL > using oops::EnsembleCovarianceSDL< MODEL >::IncrCtlVec_ = IncrCtlVec<MODEL> private
Definition at line 52 of file EnsembleCovarianceSDL.h.
Increment_
template<typename MODEL > using oops::EnsembleCovarianceSDL< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 51 of file EnsembleCovarianceSDL.h.
IncrEnsCtlVec_
template<typename MODEL > using oops::EnsembleCovarianceSDL< MODEL >::IncrEnsCtlVec_ = IncrEnsCtlVec<MODEL> private
Definition at line 53 of file EnsembleCovarianceSDL.h.
IncrModCtlVec_
template<typename MODEL > using oops::EnsembleCovarianceSDL< MODEL >::IncrModCtlVec_ = IncrModCtlVec<MODEL> private
Definition at line 54 of file EnsembleCovarianceSDL.h.
Localization_
template<typename MODEL > using oops::EnsembleCovarianceSDL< MODEL >::Localization_ = Localization<MODEL> private
Definition at line 55 of file EnsembleCovarianceSDL.h.
MatrixFactory_
template<typename MODEL > using oops::EnsembleCovarianceSDL< MODEL >::MatrixFactory_ = GenericMatrixFactory<MODEL> private
Definition at line 59 of file EnsembleCovarianceSDL.h.
State_
template<typename MODEL > using oops::EnsembleCovarianceSDL< MODEL >::State_ = State<MODEL> private
Definition at line 56 of file EnsembleCovarianceSDL.h.
Variables_
template<typename MODEL > using oops::EnsembleCovarianceSDL< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 57 of file EnsembleCovarianceSDL.h.
Constructor & Destructor Documentation
EnsembleCovarianceSDL()
template<typename MODEL > oops::EnsembleCovarianceSDL< MODEL >::EnsembleCovarianceSDL (const Geometry_ & resol, const Variables_ & , const eckit::Configuration & config, const State_ &)
Constructor, destructor.
Definition at line 101 of file EnsembleCovarianceSDL.h.
     : config_(config),
       time_(config_.getString("date")),
       has_change_of_variable_(false),
       loc_(),
       geom_(),
       change_of_variable_(),
       nhorizBand_(0),
       members_(0) {
   geom_.reset(new Geometry_(resol));
   has_change_of_variable_ = config.has("change_of_variable");
   Log::trace() << "EnsembleCovarianceSDL created." << std::endl;
 }
References oops::EnsembleCovarianceSDL< MODEL >::geom_, and oops::EnsembleCovarianceSDL< MODEL >::has_change_of_variable_.
~EnsembleCovarianceSDL()
template<typename MODEL > oops::EnsembleCovarianceSDL< MODEL >::~EnsembleCovarianceSDL
Definition at line 118 of file EnsembleCovarianceSDL.h.
{
   loc_.clear();
   geom_.reset();
   Log::trace() << "EnsembleCovarianceSDL destructed." << std::endl;
 }
Member Function Documentation
inverseMultiply()
template<typename MODEL > void oops::EnsembleCovarianceSDL< MODEL >::inverseMultiply (const Increment_ & , Increment_ &) const override virtual
\(dx_1 = B^{-1} dx_2 \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 256 of file EnsembleCovarianceSDL.h.
{
   dxo.zero();
 }
References oops::Increment< MODEL >::zero().
linearize()
template<typename MODEL > void oops::EnsembleCovarianceSDL< MODEL >::linearize (const State_ & , const Geometry_ & , const eckit::Configuration &) override virtual
Set up the inner loop resolution B matrix.
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 126 of file EnsembleCovarianceSDL.h.
{
   geom_.reset(new Geometry_(resol));
   // Compute the ensemble of perturbations at time of xb.
   ASSERT(xb.validTime() == time_);
   EnsemblePtr_ ens(new Ensemble_(xb.validTime(), config));
   ens->build(xb, resol);
   EnsemblesCollection_::getInstance().put(xb.validTime(), ens);
   ens->read();
   members_ = ens->size();
   if (has_change_of_variable_) {
     change_of_variable_.reset(
         MatrixFactory_::create(eckit::LocalConfiguration(config, "change_of_variable")));
     for (unsigned l = 0; l < members_; ++l) {
       change_of_variable_->multiply((*ens)[l]);
     }
   }
   ens->to_perturbations(1);
   /*
    * Init Scale decomposition
    */
   const eckit::LocalConfiguration conf(config, "localization");
   const eckit::LocalConfiguration confScaleDecomposition(conf, "scale_decomposition");
   // How many horizontal bands do we have?
   nhorizBand_ = confScaleDecomposition.getInt("nb_wave_band_peaks");
   // How many localization lengths do we have?
   std::vector < eckit::LocalConfiguration > confHorizBand;
   confScaleDecomposition.get("horiz_band", confHorizBand);
   int nband = confHorizBand.size();
   // Make sure that the above two numbers are equal
   ASSERT(nband == nhorizBand_);
   /*
    * Build Localization
    */
   loc_.clear();
   for (unsigned horizBandIndex = 0; horizBandIndex < nhorizBand_; ++horizBandIndex) {
     loc_.emplace_back(new Localization_(*geom_, confHorizBand[horizBandIndex]));
   }
   /*
    * Performed a horizontal scale decomposition of the perturbations
    */
   Log::info() << "Scale decomposition of the perturbation object" << std::endl;
   HorizScaleDecomposition_ fltbg(confScaleDecomposition);
   EnsemblePtr_ e = EnsemblesCollection_::getInstance()[xb.validTime()];
   for (int horizBandIndex = 0; horizBandIndex < nhorizBand_; ++horizBandIndex) {
     EnsemblePtr_ ens(new Ensemble_(*e));
     EnsembleKey k(xb.validTime(),horizBandIndex);
     EnsemblesCollection_::getInstance().put(k, ens);
   }
   for (unsigned m = 0; m < members_; ++m) {
     Log::info() << " >> calling horiz_scale_decomposition for ensemble member # " << m + 1 << std::endl;
     for (int horizBandIndex = 0; horizBandIndex < nhorizBand_; ++horizBandIndex) {
       EnsembleKey k(xb.validTime(),horizBandIndex);
       EnsemblePtr_ horizBandEns = EnsemblesCollection_::getInstance()[k];
       fltbg.collect((*horizBandEns)[m], horizBandIndex);
     }
     int SDLtype = 1;
     fltbg.decompose((*e)[m], SDLtype);
   }
   Log::trace() << "EnsembleCovarianceSDL linearized." << std::endl;
 }
References oops::HorizScaleDecomposition< MODEL >::collect(), oops::HorizScaleDecomposition< MODEL >::decompose(), and oops::State< MODEL >::validTime().
multiply()
template<typename MODEL > void oops::EnsembleCovarianceSDL< MODEL >::multiply (const Increment_ & , Increment_ &) const override virtual
\(dx_1 = B dx_2 \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 202 of file EnsembleCovarianceSDL.h.
{
   Increment_ dxi_tmp(dxi);
   dxo.zero();
   if (has_change_of_variable_) change_of_variable_->transposeInverseMultiply(dxi_tmp);
   //
   // --- B formulation ---
   //
   // loop on horizontal scale band
   for (unsigned horizBandIndex1 = 0; horizBandIndex1 < nhorizBand_; ++horizBandIndex1) {
     EnsembleKey j1(dxi.validTime(),horizBandIndex1);
     EnsemblePtr_ e_j1 = EnsemblesCollection_::getInstance()[j1];
     // loop on horizontal scale band
     for (unsigned horizBandIndex2 = 0; horizBandIndex2 < nhorizBand_; ++horizBandIndex2) {
       EnsembleKey j2(dxi.validTime(),horizBandIndex2);
       EnsemblePtr_ e_j2 = EnsemblesCollection_::getInstance()[j2];
       for (unsigned k = 0; k < members_; ++k) {
         std::unique_ptr<IncrEnsCtlVec<MODEL> > dv(this->newIncrEnsCtlVec());
         Increment_ dx(dxi_tmp);
         dx.schur_product_with((*e_j1)[k]);
         loc_[horizBandIndex1]->multiplySqrtTrans(dx, *dv);
         loc_[horizBandIndex2]->multiplySqrt(*dv, dx);
         dx.schur_product_with((*e_j2)[k]);
         dxo.axpy(1.0, dx, false);
       }
     }
   }
   /* No localization
   for (unsigned horizBandIndex1 = 0; horizBandIndex1 < nhorizBand_; ++horizBandIndex1) {
     EnsembleKey j1(dxi.validTime(),horizBandIndex1);
     EnsemblePtr_ e_j1 = EnsemblesCollection_::getInstance()[j1];
     // loop on horizontal scale band
     for (unsigned horizBandIndex2 = 0; horizBandIndex2 < nhorizBand_; ++horizBandIndex2) {
       EnsembleKey j2(dxi.validTime(),horizBandIndex2);
       EnsemblePtr_ e_j2 = EnsemblesCollection_::getInstance()[j2];
       for (unsigned int m = 0; m < members_; ++m) {
         double zz = (*e_j2)[m].dot_product_with(dxi_tmp);
         dxo.axpy(zz, (*e_j1)[m], false);
       }
     }
   }*/
   if (has_change_of_variable_) change_of_variable_->inverseMultiply(dxo);
 }
References oops::Increment< MODEL >::axpy(), oops::Increment< MODEL >::schur_product_with(), oops::Increment< MODEL >::validTime(), and oops::Increment< MODEL >::zero().
multiplySqrt()
template<typename MODEL > void oops::EnsembleCovarianceSDL< MODEL >::multiplySqrt (const IncrCtlVec_ & , Increment_ &) const override virtual
\(dx = B^{1/2} dv \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 262 of file EnsembleCovarianceSDL.h.
{
   dxo.zero();
   Increment_ dx(dxo);
   for (unsigned horizBandIndex = 0; horizBandIndex < nhorizBand_; ++horizBandIndex) {
     EnsembleKey j(dx.validTime(),horizBandIndex);
     EnsemblePtr_ e_j = EnsemblesCollection_::getInstance()[j];
     for (unsigned int k = 0; k < members_; ++k) {
       loc_[horizBandIndex]->multiplySqrt(dv.ensCtlVec(k), dx);
       dx.schur_product_with((*e_j)[k]);
       dxo.axpy(1.0, dx, false);
     }
   }
   if (has_change_of_variable_) change_of_variable_->inverseMultiply(dxo);
 }
References oops::Increment< MODEL >::axpy(), oops::IncrCtlVec< MODEL >::ensCtlVec(), oops::Increment< MODEL >::schur_product_with(), oops::Increment< MODEL >::validTime(), and oops::Increment< MODEL >::zero().
multiplySqrtTrans()
template<typename MODEL > void oops::EnsembleCovarianceSDL< MODEL >::multiplySqrtTrans (const Increment_ & , IncrCtlVec_ &) const override virtual
\(dv = [B^{1/2}]^T dx \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 279 of file EnsembleCovarianceSDL.h.
{
   Increment_ dxi_tmp(dxi);
   for (unsigned k = 0; k < members_; ++k) {
     dv.ensCtlVec(k).zero();
   }
   if (has_change_of_variable_) change_of_variable_->transposeInverseMultiply(dxi_tmp);
   for (unsigned horizBandIndex = 0; horizBandIndex < nhorizBand_; ++horizBandIndex) {
     EnsembleKey j(dxi_tmp.validTime(),horizBandIndex);
     EnsemblePtr_ e_j = EnsemblesCollection_::getInstance()[j];
     for (unsigned int k = 0; k < members_; ++k) {
       Increment_ dx(dxi_tmp);
       dx.schur_product_with((*e_j)[k]);
       loc_[horizBandIndex]->multiplySqrtTrans(dx, dv.ensCtlVec(k));
     }
   }
 }
References oops::IncrCtlVec< MODEL >::ensCtlVec(), oops::Increment< MODEL >::schur_product_with(), oops::Increment< MODEL >::validTime(), and oops::IncrEnsCtlVec< MODEL >::zero().
newIncrEnsCtlVec()
template<typename MODEL > IncrEnsCtlVec_* oops::EnsembleCovarianceSDL< MODEL >::newIncrEnsCtlVec () const inline override virtual
Return a new control vector corresponding to the localised sampled component of a B matrix
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 80 of file EnsembleCovarianceSDL.h.
{
     return new IncrEnsCtlVec_(*geom_, *loc_[0]);
   }
References oops::EnsembleCovarianceSDL< MODEL >::geom_, and oops::EnsembleCovarianceSDL< MODEL >::loc_.
newIncrModCtlVec()
template<typename MODEL > IncrModCtlVec_* oops::EnsembleCovarianceSDL< MODEL >::newIncrModCtlVec () const inline override virtual
Return a new control vector corresponding to the modelled component of a B matrix
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 77 of file EnsembleCovarianceSDL.h.
{
     return new IncrModCtlVec_();
   }
randomize()
template<typename MODEL > void oops::EnsembleCovarianceSDL< MODEL >::randomize (Increment_ &) const override virtual
\(dx = B^{1/2} dv_{random} \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 299 of file EnsembleCovarianceSDL.h.
{
   // Build dv
   std::vector<std::unique_ptr<IncrEnsCtlVec<MODEL> > > dv;
   for (unsigned int jj = 0; jj < members_; ++jj) {
     dv.emplace_back(this->newIncrEnsCtlVec());
   }
   // Initialize dv
   for (unsigned int m = 0; m < members_; ++m) {
     dv[m]->random();
   }
   // dxo = B^1/2 dv
   dxo.zero();
   Increment_ dx(dxo);
   for (unsigned horizBandIndex = 0; horizBandIndex < nhorizBand_; ++horizBandIndex) {
     EnsembleKey k(dx.validTime(),horizBandIndex);
     EnsemblePtr_ e_t = EnsemblesCollection_::getInstance()[k];
     for (unsigned int m = 0; m < members_; ++m) {
       loc_[horizBandIndex]->multiplySqrt(*dv[m], dx);
       dx.schur_product_with((*e_t)[m]);
       dxo.axpy(1.0, dx, false);
     }
   }
   if (has_change_of_variable_) change_of_variable_->inverseMultiply(dxo);
 }
References oops::Increment< MODEL >::axpy(), oops::Increment< MODEL >::schur_product_with(), oops::Increment< MODEL >::validTime(), and oops::Increment< MODEL >::zero().
Member Data Documentation
change_of_variable_
template<typename MODEL > std::unique_ptr<GenericMatrix_> oops::EnsembleCovarianceSDL< MODEL >::change_of_variable_ private
Definition at line 91 of file EnsembleCovarianceSDL.h.
config_
template<typename MODEL > const eckit::LocalConfiguration oops::EnsembleCovarianceSDL< MODEL >::config_ private
Configuration.
Definition at line 86 of file EnsembleCovarianceSDL.h.
geom_
template<typename MODEL > std::unique_ptr<Geometry_> oops::EnsembleCovarianceSDL< MODEL >::geom_ private
Pointer to a geometry object.
Definition at line 90 of file EnsembleCovarianceSDL.h.
Referenced by oops::EnsembleCovarianceSDL< MODEL >::EnsembleCovarianceSDL(), and oops::EnsembleCovarianceSDL< MODEL >::newIncrEnsCtlVec().
has_change_of_variable_
template<typename MODEL > bool oops::EnsembleCovarianceSDL< MODEL >::has_change_of_variable_ private
Change of variable.
Definition at line 88 of file EnsembleCovarianceSDL.h.
Referenced by oops::EnsembleCovarianceSDL< MODEL >::EnsembleCovarianceSDL().
loc_
template<typename MODEL > std::vector<std::unique_ptr<Localization_> > oops::EnsembleCovarianceSDL< MODEL >::loc_ private
Localization matrix.
Definition at line 89 of file EnsembleCovarianceSDL.h.
Referenced by oops::EnsembleCovarianceSDL< MODEL >::newIncrEnsCtlVec().
members_
template<typename MODEL > unsigned oops::EnsembleCovarianceSDL< MODEL >::members_ private
Definition at line 93 of file EnsembleCovarianceSDL.h.
nhorizBand_
template<typename MODEL > int oops::EnsembleCovarianceSDL< MODEL >::nhorizBand_ private
Definition at line 92 of file EnsembleCovarianceSDL.h.
time_
template<typename MODEL > const util::DateTime oops::EnsembleCovarianceSDL< MODEL >::time_ private
Valid time.
Definition at line 87 of file EnsembleCovarianceSDL.h.
The documentation for this class was generated from the following file:
src/oops/base/EnsembleCovarianceSDL.h