OOPS Documentation: oops::State< MODEL > Class Template Reference
oops::State< MODEL > Class Template Reference
Encapsulates model state.
#include <GeoVaLs.h>
Public Member Functions
State (const Geometry_ &, const Model_ &, const eckit::Configuration &)
Constructor (with Model)
State (const Geometry_ &, const LinearModel_ &, const eckit::Configuration &)
Constructor (with LinearModel)
State (const Geometry_ &, const Model_ &, const State &, const eckit::Configuration &)
Copy constructor (with Model and Configuration)
State (const Geometry_ &, const Model_ &, const State &)
Copy constructor (with Model)
State (const Geometry_ &, const State &)
Copy constructor.
State (const State &)
Copy constructor (no interpolation)
~State ()
Destructor.
State & operator= (const State &)
Assignment.
State_ & state ()
Return a reference to the model specific state.
const State_ & state () const
Return a constant reference to the model specific state.
Geometry_ geometry () const
Get geometry.
void interpolate (const Locations_ &, GeoVaLs_ &) const
Interpolate to observation locations.
void forceWith (const State &, const Variables_ &)
Interpolate full fields (for forcing linearisation trajectory)
const util::DateTime & validTime () const
Time.
util::DateTime & validTime ()
void read (const eckit::Configuration &)
Read state.
void write (const eckit::Configuration &) const
Write state.
double norm () const
L-2 norm.
Static Public Member Functions
static const std::string classname ()
Protected Member Functions
void zero ()
Protected methods are for Accumulator. Could we find a better design?
void accumul (const double &, const State &)
Private Types
using State_ = typename MODEL::State
using Geometry_ = Geometry< MODEL >
using GeoVaLs_ = GeoVaLs< MODEL >
using Locations_ = Locations< MODEL >
using Model_ = Model< MODEL >
using LinearModel_ = LinearModel< MODEL >
using Variables_ = Variables< MODEL >
Private Member Functions
void print (std::ostream &) const
Private Attributes
std::unique_ptr< State_ > state_
Pointer to the model specific object.
const Model_ & model_
Constant reference to the model.
Detailed Description
template<typename MODEL>
class oops::State< MODEL >
Encapsulates model state.
Wrapper around a model specific state class.
\(x_{state4D} \) implemented by State4D implements the state component of ControlVariable and contains a vector of State objects.
Definition at line 34 of file GeoVaLs.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::State< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 52 of file State.h.
GeoVaLs_
template<typename MODEL > using oops::State< MODEL >::GeoVaLs_ = GeoVaLs<MODEL> private
Definition at line 53 of file State.h.
LinearModel_
template<typename MODEL > using oops::State< MODEL >::LinearModel_ = LinearModel<MODEL> private
Definition at line 56 of file State.h.
Locations_
template<typename MODEL > using oops::State< MODEL >::Locations_ = Locations<MODEL> private
Definition at line 54 of file State.h.
Model_
template<typename MODEL > using oops::State< MODEL >::Model_ = Model<MODEL> private
Definition at line 55 of file State.h.
State_
template<typename MODEL > using oops::State< MODEL >::State_ = typename MODEL::State private
Definition at line 51 of file State.h.
Variables_
template<typename MODEL > using oops::State< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 57 of file State.h.
Constructor & Destructor Documentation
State() [1/6]
template<typename MODEL > oops::State< MODEL >::State (const Geometry_ & resol, const Model_ & model, const eckit::Configuration & conf)
Constructor (with Model)
Definition at line 121 of file State.h.
     : state_(), model_(model) {
   Log::trace() << "State<MODEL>::State read starting" << std::endl;
   util::Timer timer(classname(), "State");
   state_.reset(new State_(resol.geometry(), model.model(), conf));
   Log::trace() << "State<MODEL>::State read done" << std::endl;
 }
References oops::State< MODEL >::classname(), oops::Geometry< MODEL >::geometry(), oops::Model< MODEL >::model(), and oops::State< MODEL >::state_.
State() [2/6]
template<typename MODEL > oops::State< MODEL >::State (const Geometry_ & resol, const LinearModel_ & model, const eckit::Configuration & conf)
Constructor (with LinearModel)
Definition at line 133 of file State.h.
     : state_(), model_(model) {
   Log::trace() << "State<MODEL>::State read starting" << std::endl;
   util::Timer timer(classname(), "State");
   state_.reset(new State_(resol.geometry(), model.model(), conf));
   Log::trace() << "State<MODEL>::State read done" << std::endl;
 }
References oops::State< MODEL >::classname(), oops::Geometry< MODEL >::geometry(), oops::LinearModel< MODEL >::model(), and oops::State< MODEL >::state_.
State() [3/6]
template<typename MODEL > oops::State< MODEL >::State (const Geometry_ & resol, const Model_ & model, const State< MODEL > & other, const eckit::Configuration & conf)
Copy constructor (with Model and Configuration)
Definition at line 145 of file State.h.
     : state_(), model_(model) {
   Log::trace() << "State<MODEL>::State interpolated starting" << std::endl;
   util::Timer timer(classname(), "State");
   state_.reset(
       new State_(resol.geometry(), model.model(), *other.state_, conf));
   Log::trace() << "State<MODEL>::State interpolated done" << std::endl;
 }
References oops::State< MODEL >::classname(), oops::Geometry< MODEL >::geometry(), oops::Model< MODEL >::model(), and oops::State< MODEL >::state_.
State() [4/6]
template<typename MODEL > oops::State< MODEL >::State (const Geometry_ & resol, const Model_ & model, const State< MODEL > & other)
Copy constructor (with Model)
Definition at line 158 of file State.h.
     : state_(), model_(model) {
   Log::trace() << "State<MODEL>::State interpolated starting" << std::endl;
   util::Timer timer(classname(), "State");
   state_.reset(new State_(resol.geometry(), model.model(), *other.state_));
   Log::trace() << "State<MODEL>::State interpolated done" << std::endl;
 }
References oops::State< MODEL >::classname(), oops::Geometry< MODEL >::geometry(), oops::Model< MODEL >::model(), and oops::State< MODEL >::state_.
State() [5/6]
template<typename MODEL > oops::State< MODEL >::State (const Geometry_ & resol, const State< MODEL > & other)
Copy constructor.
Definition at line 170 of file State.h.
     : state_(), model_(other.model_) {
   Log::trace() << "State<MODEL>::State starting copy" << std::endl;
   util::Timer timer(classname(), "State");
   state_.reset(new State_(resol.geometry(), model_.model(), *other.state_));
   Log::trace() << "State<MODEL>::State copy done" << std::endl;
 }
References oops::State< MODEL >::classname(), oops::Geometry< MODEL >::geometry(), oops::Model< MODEL >::model(), oops::State< MODEL >::model_, and oops::State< MODEL >::state_.
State() [6/6]
template<typename MODEL > oops::State< MODEL >::State (const State< MODEL > & other)
Copy constructor (no interpolation)
Definition at line 181 of file State.h.
                                       : state_(), model_(other.model_) {
   Log::trace() << "State<MODEL>::State starting copy" << std::endl;
   util::Timer timer(classname(), "State");
   state_.reset(new State_(*other.state_));
   Log::trace() << "State<MODEL>::State copy done" << std::endl;
 }
References oops::State< MODEL >::classname(), and oops::State< MODEL >::state_.
~State()
template<typename MODEL > oops::State< MODEL >::~State
Destructor.
Definition at line 191 of file State.h.
                      {
   Log::trace() << "State<MODEL>::~State starting" << std::endl;
   util::Timer timer(classname(), "~State");
   state_.reset();
   Log::trace() << "State<MODEL>::~State done" << std::endl;
 }
Member Function Documentation
accumul()
template<typename MODEL > void oops::State< MODEL >::accumul (const double & zz, const State< MODEL > & xx) protected
Definition at line 295 of file State.h.
{
   Log::trace() << "State<MODEL>::accumul starting" << std::endl;
   util::Timer timer(classname(), "accumul");
   state_->accumul(zz, *xx.state_);
   Log::trace() << "State<MODEL>::accumul done" << std::endl;
 }
classname()
template<typename MODEL > static const std::string oops::State< MODEL >::classname () inline static
Definition at line 60 of file State.h.
 { return "oops::State"; }
Referenced by oops::State< MODEL >::State().
forceWith()
template<typename MODEL > void oops::State< MODEL >::forceWith (const State< MODEL > & xx, const Variables_ & vars)
Interpolate full fields (for forcing linearisation trajectory)
Definition at line 222 of file State.h.
{
   Log::trace() << "State<MODEL>::forceWith starting" << std::endl;
   util::Timer timer(classname(), "forceWith");
   state_->forceWith(*xx.state_, vars.variables());
   Log::trace() << "State<MODEL>::forceWith done" << std::endl;
 }
References oops::Variables< MODEL >::variables().
Referenced by oops::DualConfigModel< MODEL >::forecast().
geometry()
template<typename MODEL > Geometry< MODEL > oops::State< MODEL >::geometry
Get geometry.
Definition at line 264 of file State.h.
{
   Log::trace() << "State<MODEL>::geometry starting" << std::endl;
   util::Timer timer(classname(), "geometry");
   Geometry<MODEL> geom(state_->geometry());
   Log::trace() << "State<MODEL>::geometry done" << std::endl;
   return geom;
 }
interpolate()
template<typename MODEL > void oops::State< MODEL >::interpolate (const Locations_ & locs, GeoVaLs_ & gvals) const
Interpolate to observation locations.
Definition at line 212 of file State.h.
{
   Log::trace() << "State<MODEL>::interpolate starting" << std::endl;
   util::Timer timer(classname(), "interpolate");
   state_->interpolate(locs.locations(), gvals.geovals());
   Log::trace() << "State<MODEL>::interpolate done" << std::endl;
 }
References oops::GeoVaLs< MODEL >::geovals(), and oops::Locations< MODEL >::locations().
norm()
template<typename MODEL > double oops::State< MODEL >::norm
L-2 norm.
Definition at line 253 of file State.h.
{
   Log::trace() << "State<MODEL>::norm starting" << std::endl;
   util::Timer timer(classname(), "norm");
   double zz = state_->norm();
   Log::trace() << "State<MODEL>::norm done" << std::endl;
   return zz;
 }
Referenced by oops::DualResForecast< MODEL >::execute(), oops::EnsForecast< MODEL >::execute(), oops::Forecast< MODEL >::execute(), oops::ModelAuxNN< MODEL >::execute(), oops::ExternalDFI< MODEL >::execute(), oops::GenEnsPertB< MODEL >::execute(), oops::HofX< MODEL >::execute(), oops::MakeObs< MODEL >::execute(), and test::testModelNoForecast().
operator=()
template<typename MODEL > State< MODEL > & oops::State< MODEL >::operator= (const State< MODEL > & rhs)
Assignment.
Definition at line 201 of file State.h.
{
   Log::trace() << "State<MODEL>::operator= starting" << std::endl;
   util::Timer timer(classname(), "operator=");
   *state_ = *rhs.state_;
   Log::trace() << "State<MODEL>::operator= done" << std::endl;
   return *this;
 }
print()
template<typename MODEL > void oops::State< MODEL >::print (std::ostream & os) const private
Definition at line 275 of file State.h.
{
   Log::trace() << "State<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   os << *state_;
   Log::trace() << "State<MODEL>::print done" << std::endl;
 }
read()
template<typename MODEL > void oops::State< MODEL >::read (const eckit::Configuration & conf)
Read state.
Definition at line 232 of file State.h.
{
   Log::trace() << "State<MODEL>::read starting" << std::endl;
   util::Timer timer(classname(), "read");
   state_->read(conf);
   Log::trace() << "State<MODEL>::read done" << std::endl;
 }
state() [1/2]
template<typename MODEL > State_& oops::State< MODEL >::state () inline
Return a reference to the model specific state.
Definition at line 82 of file State.h.
 { return *state_; }
References oops::State< MODEL >::state_.
Referenced by oops::GenericMatrix< MODEL >::accumul(), oops::Increment< MODEL >::accumul(), oops::Increment< MODEL >::diff(), oops::ErrorCovariance< MODEL >::ErrorCovariance(), oops::ModelAuxControlEstimator< MODEL >::estimate(), oops::Model< MODEL >::finalize(), oops::GeoVaLs< MODEL >::GeoVaLs(), oops::Model< MODEL >::initialize(), oops::Interpolator< MODEL >::interpolate(), oops::Interpolator< MODEL >::Interpolator(), oops::JcCovarBase< MODEL >::linearize(), oops::ErrorCovariance< MODEL >::linearize(), oops::JcCovarMaker< MODEL, T >::make(), oops::GenericMatrix< MODEL >::multiply(), oops::Interpolator< MODEL >::operator+=(), oops::operator+=(), oops::Interpolator< MODEL >::operator-=(), oops::LinearModelBase< L95Traits >::setTrajectory(), and oops::Model< MODEL >::step().
state() [2/2]
template<typename MODEL > const State_& oops::State< MODEL >::state () const inline
Return a constant reference to the model specific state.
Definition at line 84 of file State.h.
 { return *state_; }
References oops::State< MODEL >::state_.
validTime() [1/2]
template<typename MODEL > util::DateTime& oops::State< MODEL >::validTime () inline
Definition at line 96 of file State.h.
 { return state_->validTime(); }
References oops::State< MODEL >::state_.
validTime() [2/2]
template<typename MODEL > const util::DateTime& oops::State< MODEL >::validTime () const inline
Time.
Definition at line 95 of file State.h.
 { return state_->validTime(); }
References oops::State< MODEL >::state_.
Referenced by oops::DFIProcessor< MODEL >::doInitialize(), oops::DFIProcessor< MODEL >::doProcessing(), oops::AdvectorHandler< MODEL >::doProcessing(), oops::DualResForecast< MODEL >::execute(), oops::EnsForecast< MODEL >::execute(), oops::Forecast< MODEL >::execute(), oops::ExternalDFI< MODEL >::execute(), oops::GenEnsPertB< MODEL >::execute(), oops::Model< MODEL >::forecast(), oops::EnsembleCovsInterpolSDL< MODEL >::linearize(), oops::EnsembleCovsInterpol< MODEL >::linearize(), oops::Ensemble< MODEL >::linearize(), oops::EnsembleCovarianceSDL< MODEL >::linearize(), oops::EnsembleCovariance< MODEL >::linearize(), oops::CostFct4DEnVar< MODEL >::runNL(), and oops::CostFct4DVarMFTemplate< MODEL >::runNL().
write()
template<typename MODEL > void oops::State< MODEL >::write (const eckit::Configuration & conf) const
Write state.
Definition at line 242 of file State.h.
{
   Log::trace() << "State<MODEL>::write starting" << std::endl;
   util::Timer timer(classname(), "write");
   util::LogbookWriter<bool> log("StateWriting", true);
   state_->write(conf);
   Log::trace() << "State<MODEL>::write done" << std::endl;
 }
zero()
template<typename MODEL > void oops::State< MODEL >::zero protected
Protected methods are for Accumulator. Could we find a better design?
Definition at line 285 of file State.h.
{
   Log::trace() << "State<MODEL>::zero starting" << std::endl;
   util::Timer timer(classname(), "zero");
   state_->zero();
   Log::trace() << "State<MODEL>::zero done" << std::endl;
 }
Member Data Documentation
model_
template<typename MODEL > const Model_& oops::State< MODEL >::model_ private
Constant reference to the model.
Definition at line 115 of file State.h.
Referenced by oops::State< MODEL >::State().
state_
template<typename MODEL > std::unique_ptr<State_> oops::State< MODEL >::state_ private
Pointer to the model specific object.
Definition at line 114 of file State.h.
Referenced by oops::State< MODEL >::State(), oops::State< MODEL >::state(), and oops::State< MODEL >::validTime().
The documentation for this class was generated from the following files:
src/oops/interface/GeoVaLs.h
src/oops/interface/State.h