OOPS Documentation: oops::Variables< MODEL > Class Template Reference
oops::Variables< MODEL > Class Template Reference
#include <Variables.h>
Public Member Functions
Variables (const eckit::Configuration &)
Variables (std::shared_ptr< const Variables_ >)
Variables (const Variables &)
~Variables ()
const Variables_ & variables () const
Interfacing.
Static Public Member Functions
static const std::string classname ()
Private Types
using Variables_ = typename MODEL::Variables
Private Member Functions
Variables & operator= (const Variables &)
void print (std::ostream &) const
Private Attributes
std::shared_ptr< const Variables_ > variables_
Detailed Description
template<typename MODEL>
class oops::Variables< MODEL >
Definition at line 32 of file Variables.h.
Member Typedef Documentation
Variables_
template<typename MODEL > using oops::Variables< MODEL >::Variables_ = typename MODEL::Variables private
Definition at line 34 of file Variables.h.
Constructor & Destructor Documentation
Variables() [1/3]
template<typename MODEL > oops::Variables< MODEL >::Variables (const eckit::Configuration & conf) explicit
Definition at line 56 of file Variables.h.
                                                           : variables_() {
   Log::trace() << "Variables<MODEL>::Variables starting" << std::endl;
   util::Timer timer(classname(), "Variables");
   variables_.reset(new Variables_(conf));
   Log::trace() << "Variables<MODEL>::Variables done" << std::endl;
 }
References oops::Variables< MODEL >::classname(), and oops::Variables< MODEL >::variables_.
Variables() [2/3]
template<typename MODEL > oops::Variables< MODEL >::Variables (std::shared_ptr< const Variables_ > ptr) explicit
Definition at line 66 of file Variables.h.
     : variables_(ptr) {
   Log::trace() << "Variables<MODEL>::Variables shared_ptr done" << std::endl;
 }
Variables() [3/3]
template<typename MODEL > oops::Variables< MODEL >::Variables (const Variables< MODEL > & other)
Definition at line 74 of file Variables.h.
     : variables_(other.variables_) {
   Log::trace() << "Variables<MODEL>::Variables copy done" << std::endl;
 }
~Variables()
template<typename MODEL > oops::Variables< MODEL >::~Variables
Definition at line 82 of file Variables.h.
{
   Log::trace() << "Variables<MODEL>::~Variables starting" << std::endl;
   util::Timer timer(classname(), "~Variables");
   variables_.reset();
   Log::trace() << "Variables<MODEL>::~Variables done" << std::endl;
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::Variables< MODEL >::classname () inline static
Definition at line 37 of file Variables.h.
 { return "oops::Variables"; }
Referenced by oops::Variables< MODEL >::Variables().
operator=()
template<typename MODEL > Variables& oops::Variables< MODEL >::operator= (const Variables< MODEL > &) private
print()
template<typename MODEL > void oops::Variables< MODEL >::print (std::ostream & os) const private
Definition at line 92 of file Variables.h.
{
   Log::trace() << "Variables<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   os << *variables_;
   Log::trace() << "Variables<MODEL>::print done" << std::endl;
 }
variables()
template<typename MODEL > const Variables_& oops::Variables< MODEL >::variables () const inline
Interfacing.
Definition at line 45 of file Variables.h.
 { return *variables_; }
References oops::Variables< MODEL >::variables_.
Referenced by oops::ErrorCovariance< MODEL >::ErrorCovariance(), oops::State< MODEL >::forceWith(), oops::GeoVaLs< MODEL >::GeoVaLs(), oops::Increment< MODEL >::Increment(), oops::Interpolator< MODEL >::interpolate(), oops::Increment< MODEL >::max(), and oops::Increment< MODEL >::min().
Member Data Documentation
variables_
template<typename MODEL > std::shared_ptr<const Variables_> oops::Variables< MODEL >::variables_ private
Definition at line 50 of file Variables.h.
Referenced by oops::Variables< MODEL >::Variables(), and oops::Variables< MODEL >::variables().
The documentation for this class was generated from the following file:
src/oops/interface/Variables.h