OOPS Documentation: oops::ObsAuxControls< MODEL > Class Template Reference
oops::ObsAuxControls< MODEL > Class Template Reference
Encapsulates a vector of ObsAuxControl objects.
#include <ObsAuxControls.h>
Public Member Functions
ObsAuxControls (const ObsSpaces_ &, const eckit::Configuration &)
Constructor.
ObsAuxControls (const ObsAuxControls &, const bool copy=true)
Copy constructor.
~ObsAuxControls ()
Destructor.
std::size_t size () const
Return the size.
const ObsAuxControl_ & operator[] (const std::size_t ii) const
Return a constant reference to the i-th ObsAuxControl object.
ObsAuxControl_ & operator[] (const std::size_t ii)
Return a reference to the i-th ObsAuxControl object.
const ObsSpaces_ & obspaces () const
Return a constant reference to ObsSpaces.
void reset (const ObsSpaces_ &, const std::string &, const eckit::Configuration &)
Reset.
void read (const eckit::Configuration &)
Read control variable.
void write (const eckit::Configuration &) const
Write control variable.
double norm () const
L-2 norm.
Static Public Member Functions
static const std::string classname ()
Private Types
using ObsAuxControl_ = ObsAuxControl< MODEL >
using ObsSpaces_ = ObservationSpaces< MODEL >
Private Member Functions
ObsAuxControls & operator= (const ObsAuxControls &)
void print (std::ostream &) const
Private Attributes
const ObsSpaces_ * odb_
std::vector< std::shared_ptr< ObsAuxControl_ > > auxs_
Vector of shared pointers to ObsAuxControl objects.
Detailed Description
template<typename MODEL>
class oops::ObsAuxControls< MODEL >
Encapsulates a vector of ObsAuxControl objects.
An object of ObsAuxControls class is part of ControlVariable. The class contains a vector of ObsAuxControl objects. Refer to the documentation of ControlVariable and CostJo to understand the structure.
Definition at line 37 of file ObsAuxControls.h.
Member Typedef Documentation
ObsAuxControl_
template<typename MODEL > using oops::ObsAuxControls< MODEL >::ObsAuxControl_ = ObsAuxControl<MODEL> private
Definition at line 38 of file ObsAuxControls.h.
ObsSpaces_
template<typename MODEL > using oops::ObsAuxControls< MODEL >::ObsSpaces_ = ObservationSpaces<MODEL> private
Definition at line 39 of file ObsAuxControls.h.
Constructor & Destructor Documentation
ObsAuxControls() [1/2]
template<typename MODEL > oops::ObsAuxControls< MODEL >::ObsAuxControls (const ObsSpaces_ & odb, const eckit::Configuration & conf)
Constructor.
Definition at line 87 of file ObsAuxControls.h.
     : odb_(), auxs_(0) {
   std::vector<eckit::LocalConfiguration> obsconf;
   odb_ = &odb;
   conf.get("ObsTypes", obsconf);
   for (std::size_t jobs = 0; jobs < obsconf.size(); ++jobs) {
     std::shared_ptr<ObsAuxControl_> tmp(
         new ObsAuxControl_(odb[jobs], obsconf[jobs]));
     auxs_.push_back(tmp);
   }
 }
References oops::ObsAuxControls< MODEL >::auxs_, and oops::ObsAuxControls< MODEL >::odb_.
ObsAuxControls() [2/2]
template<typename MODEL > oops::ObsAuxControls< MODEL >::ObsAuxControls (const ObsAuxControls< MODEL > & other, const bool copy = true)
Copy constructor.
Definition at line 103 of file ObsAuxControls.h.
     : odb_(other.odb_), auxs_(other.size()) {
   Log::trace() << "ObsAuxControls<MODEL>::ObsAuxControls copy starting"
                << std::endl;
   for (std::size_t jobs = 0; jobs < other.size(); ++jobs) {
     auxs_[jobs].reset(new ObsAuxControl_(other[jobs], copy));
   }
   Log::trace() << "ObsAuxControls<MODEL>::ObsAuxControls copy done"
                << std::endl;
 }
References oops::ObsAuxControls< MODEL >::auxs_, and oops::ObsAuxControls< MODEL >::size().
~ObsAuxControls()
template<typename MODEL > oops::ObsAuxControls< MODEL >::~ObsAuxControls
Destructor.
Definition at line 118 of file ObsAuxControls.h.
{
   Log::trace() << "ObsAuxControls<MODEL>::~ObsAuxControls starting"
                << std::endl;
   for (std::size_t jobs = 0; jobs < auxs_.size(); ++jobs) auxs_[jobs].reset();
   odb_ = nullptr;
   Log::trace() << "ObsAuxControls<MODEL>::~ObsAuxControls done" << std::endl;
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::ObsAuxControls< MODEL >::classname () inline static
Definition at line 42 of file ObsAuxControls.h.
 { return "oops::ObsAuxControls"; }
norm()
template<typename MODEL > double oops::ObsAuxControls< MODEL >::norm
L-2 norm.
Definition at line 176 of file ObsAuxControls.h.
{
   Log::trace() << "ObsAuxControls<MODEL>::norm starting" << std::endl;
   double zz = static_cast<double>(0.0);
   for (std::size_t jobs = 0; jobs < auxs_.size(); ++jobs) {
     double norm = auxs_[jobs]->norm();
     zz += norm * norm;
   }
   Log::trace() << "ObsAuxControls<MODEL>::norm done" << std::endl;
   return std::sqrt(zz);
 }
obspaces()
template<typename MODEL > const ObsSpaces_& oops::ObsAuxControls< MODEL >::obspaces () const inline
Return a constant reference to ObsSpaces.
Definition at line 61 of file ObsAuxControls.h.
 { return *odb_; }
References oops::ObsAuxControls< MODEL >::odb_.
operator=()
template<typename MODEL > ObsAuxControls& oops::ObsAuxControls< MODEL >::operator= (const ObsAuxControls< MODEL > &) private
operator[]() [1/2]
template<typename MODEL > ObsAuxControl_& oops::ObsAuxControls< MODEL >::operator[] (const std::size_t ii) inline
Return a reference to the i-th ObsAuxControl object.
Definition at line 59 of file ObsAuxControls.h.
 { return *auxs_.at(ii); }
References oops::ObsAuxControls< MODEL >::auxs_.
operator[]() [2/2]
template<typename MODEL > const ObsAuxControl_& oops::ObsAuxControls< MODEL >::operator[] (const std::size_t ii) const inline
Return a constant reference to the i-th ObsAuxControl object.
Definition at line 55 of file ObsAuxControls.h.
{
     return *auxs_.at(ii);
   }
References oops::ObsAuxControls< MODEL >::auxs_.
print()
template<typename MODEL > void oops::ObsAuxControls< MODEL >::print (std::ostream & os) const private
Definition at line 190 of file ObsAuxControls.h.
{
   for (std::size_t jobs = 0; jobs < auxs_.size(); ++jobs) os << *auxs_[jobs];
 }
read()
template<typename MODEL > void oops::ObsAuxControls< MODEL >::read (const eckit::Configuration & conf)
Read control variable.
Definition at line 150 of file ObsAuxControls.h.
{
   Log::trace() << "ObsAuxControls<MODEL>::read starting" << std::endl;
   std::vector<eckit::LocalConfiguration> obsconfs;
   conf.get("statesObsAux", obsconfs);
   ASSERT(auxs_.size() >= obsconfs.size());
   for (std::size_t jobs = 0; jobs < obsconfs.size(); ++jobs)
     auxs_[jobs]->read(obsconfs[jobs]);
   Log::trace() << "ObsAuxControls<MODEL>::read done" << std::endl;
 }
reset()
template<typename MODEL > void oops::ObsAuxControls< MODEL >::reset (const ObsSpaces_ & os, const std::string & stateid, const eckit::Configuration & conf)
Reset.
Definition at line 129 of file ObsAuxControls.h.
{
   Log::trace() << "ObsAuxControls<MODEL>::reset starting" << std::endl;
   odb_ = &os;
   std::vector<eckit::LocalConfiguration> obsconfs;
   if (conf.has("screening") && conf.has("statesObsAuxReset")) {
     if (conf.getBool("screening.active")) {
       conf.get("statesObsAuxReset", obsconfs);
     }
   }
   ASSERT(auxs_.size() >= obsconfs.size());
   for (std::size_t jobs = 0; jobs < obsconfs.size(); ++jobs) {
     auxs_[jobs]->reset(os[jobs], stateid, obsconfs[jobs]);
   }
   Log::trace() << "ObsAuxControls<MODEL>::reset done" << std::endl;
 }
Referenced by oops::CostJo< MODEL >::screenObservations().
size()
template<typename MODEL > std::size_t oops::ObsAuxControls< MODEL >::size () const inline
Return the size.
Definition at line 53 of file ObsAuxControls.h.
 { return auxs_.size(); }
References oops::ObsAuxControls< MODEL >::auxs_.
Referenced by oops::ObsAuxIncrements< MODEL >::diff(), oops::ObsAuxCovariances< MODEL >::linearize(), oops::ObsAuxControls< MODEL >::ObsAuxControls(), oops::operator+=(), and oops::ObsAuxCovariances< MODEL >::update().
write()
template<typename MODEL > void oops::ObsAuxControls< MODEL >::write (const eckit::Configuration & conf) const
Write control variable.
Definition at line 163 of file ObsAuxControls.h.
{
   Log::trace() << "ObsAuxControls<MODEL>::write starting" << std::endl;
   std::vector<eckit::LocalConfiguration> obsconfs;
   conf.get("statesObsAux", obsconfs);
   ASSERT(auxs_.size() >= obsconfs.size());
   for (std::size_t jobs = 0; jobs < obsconfs.size(); ++jobs)
     auxs_[jobs]->write(obsconfs[jobs]);
   Log::trace() << "ObsAuxControls<MODEL>::write done" << std::endl;
 }
Member Data Documentation
auxs_
template<typename MODEL > std::vector<std::shared_ptr<ObsAuxControl_> > oops::ObsAuxControls< MODEL >::auxs_ private
Vector of shared pointers to ObsAuxControl objects.
Definition at line 81 of file ObsAuxControls.h.
Referenced by oops::ObsAuxControls< MODEL >::ObsAuxControls(), oops::ObsAuxControls< MODEL >::operator[](), and oops::ObsAuxControls< MODEL >::size().
odb_
template<typename MODEL > const ObsSpaces_* oops::ObsAuxControls< MODEL >::odb_ mutable private
Definition at line 79 of file ObsAuxControls.h.
Referenced by oops::ObsAuxControls< MODEL >::ObsAuxControls(), and oops::ObsAuxControls< MODEL >::obspaces().
The documentation for this class was generated from the following file:
src/oops/base/ObsAuxControls.h