OOPS Documentation: oops::ObsAuxCtlVec< MODEL > Class Template Reference
oops::ObsAuxCtlVec< MODEL > Class Template Reference
Encapsulates auxiliary observation space components of ControlVector.
#include <ObsAuxCtlVec.h>
Public Member Functions
ObsAuxCtlVec (const ObsAuxCovariance_ &)
Constructor.
ObsAuxCtlVec (const ObsAuxCovariance_ &, const ObsAuxCtlVec &)
Constructor with copy initialization.
ObsAuxCtlVec (const ObsAuxCtlVec &, const bool copy=true)
Copy constructor.
~ObsAuxCtlVec ()
Destructor.
void zero ()
\(dv_1 = 0 \)
ObsAuxCtlVec & operator= (const ObsAuxCtlVec &)
\(dv_1 = dv_2 \)
ObsAuxCtlVec & operator+= (const ObsAuxCtlVec &)
\(dv_1 = dv_1 + dv_2 \)
ObsAuxCtlVec & operator-= (const ObsAuxCtlVec &)
\(dv_1 = dv_1 - dv_2 \)
ObsAuxCtlVec & operator*= (const double &)
\(dv_1 = dv_1 * c \)
void axpy (const double &, const ObsAuxCtlVec &)
\(dv_1 = dv_1 * c dv_2 \)
double dot_product_with (const ObsAuxCtlVec &) const
\(<dv_1,dv_1> = dv_1^T dv_1 \)
void read (const eckit::Configuration &)
Read control vector.
void write (const eckit::Configuration &) const
Write control vector.
double norm () const
L-2 norm.
const ObsAuxCtlVecBase_ & obsAuxCtlVec (const std::string &id) const
Return a constant reference to the model specific object.
ObsAuxCtlVecBase_ & obsAuxCtlVec (const std::string &id)
Return a reference to the model specific object.
const std::vector< std::string > & getKeys () const
Return a constant reference to the vector of keys.
const size_t & size () const
Return the number of ObsAuxCtlVecBase objects.
Static Public Member Functions
static const std::string classname ()
Private Types
using ObsAuxCtlVecBase_ = ObsAuxCtlVecBase< MODEL >
using ObsAuxCovariance_ = ObsAuxCovariance< MODEL >
using ObsAuxCtlVecPtrMap_ = std::map< std::string, std::unique_ptr< ObsAuxCtlVecBase_ > >
using iter_ = typename ObsAuxCtlVecPtrMap_::iterator
using icst_ = typename ObsAuxCtlVecPtrMap_::const_iterator
Private Member Functions
const ObsAuxCtlVecBase_ & get (const std::string &) const
Return a constant reference to the model specific object.
ObsAuxCtlVecBase_ & get (const std::string &)
Return a reference to the model specific object.
void print (std::ostream &) const
Private Attributes
size_t size_
Number of model specific objects.
std::vector< std::string > keys_
Vector of keys to model specific objects.
ObsAuxCtlVecPtrMap_ ctlvecs_
Map of pointers to model specific objects.
Detailed Description
template<typename MODEL>
class oops::ObsAuxCtlVec< MODEL >
Encapsulates auxiliary observation space components of ControlVector.
This class provides operations associated with the auxiliary observation space components (e.g. VarBC, TOVSC) of ControlVector. It contains a vector of ObsAuxCtlVecBase objects, where ObsAuxCtlVecBase is a base class for model specific (or potentially generic) classes.
ObsAuxCtlVecs class wraps around a vector of ObsAuxCtlVec objects and is part of ControlVector. Refer to the documentation of ControlVector and CostJo to understand the structure.
Definition at line 50 of file ObsAuxCtlVec.h.
Member Typedef Documentation
icst_
template<typename MODEL > using oops::ObsAuxCtlVec< MODEL >::icst_ = typename ObsAuxCtlVecPtrMap_::const_iterator private
Definition at line 57 of file ObsAuxCtlVec.h.
iter_
template<typename MODEL > using oops::ObsAuxCtlVec< MODEL >::iter_ = typename ObsAuxCtlVecPtrMap_::iterator private
Definition at line 56 of file ObsAuxCtlVec.h.
ObsAuxCovariance_
template<typename MODEL > using oops::ObsAuxCtlVec< MODEL >::ObsAuxCovariance_ = ObsAuxCovariance<MODEL> private
Definition at line 53 of file ObsAuxCtlVec.h.
ObsAuxCtlVecBase_
template<typename MODEL > using oops::ObsAuxCtlVec< MODEL >::ObsAuxCtlVecBase_ = ObsAuxCtlVecBase<MODEL> private
Definition at line 52 of file ObsAuxCtlVec.h.
ObsAuxCtlVecPtrMap_
template<typename MODEL > using oops::ObsAuxCtlVec< MODEL >::ObsAuxCtlVecPtrMap_ = std::map<std::string, std::unique_ptr<ObsAuxCtlVecBase_> > private
Definition at line 55 of file ObsAuxCtlVec.h.
Constructor & Destructor Documentation
ObsAuxCtlVec() [1/3]
template<typename MODEL > oops::ObsAuxCtlVec< MODEL >::ObsAuxCtlVec (const ObsAuxCovariance_ & cov)
Constructor.
Definition at line 125 of file ObsAuxCtlVec.h.
     : size_(0), keys_(), ctlvecs_() {
   Log::trace() << "ObsAuxCtlVec<MODEL>::ObsAuxCtlVec starting" << std::endl;
   util::Timer timer(classname(), "ObsAuxCtlVec");
   std::vector<eckit::LocalConfiguration> covconfs;
   cov.config().get("covarianceObsAux", covconfs);
   size_ = covconfs.size();
   for (auto const &config : covconfs) {
     std::string key(config.getString("type"));
     std::unique_ptr<ObsAuxCtlVecBase<MODEL>> auxctl(
         ObsAuxCtlVecFactory<MODEL>::create(cov.errorCovariance(key)));
     ctlvecs_.emplace(key, std::move(auxctl));
     keys_.push_back(key);
   }
   Log::trace() << "ObsAuxCtlVec<MODEL>::ObsAuxCtlVec done" << std::endl;
 }
References oops::ObsAuxCtlVec< MODEL >::classname(), oops::ObsAuxCovariance< MODEL >::config(), oops::ObsAuxCtlVec< MODEL >::ctlvecs_, oops::ObsAuxCovariance< MODEL >::errorCovariance(), oops::ObsAuxCtlVec< MODEL >::keys_, and oops::ObsAuxCtlVec< MODEL >::size_.
ObsAuxCtlVec() [2/3]
template<typename MODEL > oops::ObsAuxCtlVec< MODEL >::ObsAuxCtlVec (const ObsAuxCovariance_ & cov, const ObsAuxCtlVec< MODEL > & other)
Constructor with copy initialization.
Definition at line 145 of file ObsAuxCtlVec.h.
     : size_(other.size_), keys_(), ctlvecs_() {
   Log::trace() << "ObsAuxCtlVec<MODEL>::ObsAuxCtlVec starting" << std::endl;
   util::Timer timer(classname(), "ObsAuxCtlVec");
   for (icst_ it = other.ctlvecs_.begin(); it != other.ctlvecs_.end(); ++it) {
     std::string incname = it->first;
     std::unique_ptr<ObsAuxCtlVecBase<MODEL>> auxctl(it->second->clone(cov));
     ctlvecs_.emplace(incname, std::move(auxctl));
     keys_.push_back(incname);
   }
   Log::trace() << "ObsAuxCtlVec<MODEL>::ObsAuxCtlVec done" << std::endl;
 }
References oops::ObsAuxCtlVec< MODEL >::classname(), oops::ObsAuxCtlVec< MODEL >::ctlvecs_, and oops::ObsAuxCtlVec< MODEL >::keys_.
ObsAuxCtlVec() [3/3]
template<typename MODEL > oops::ObsAuxCtlVec< MODEL >::ObsAuxCtlVec (const ObsAuxCtlVec< MODEL > & other, const bool copy = true)
Copy constructor.
Definition at line 160 of file ObsAuxCtlVec.h.
     : size_(other.size_), keys_(), ctlvecs_() {
   Log::trace() << "ObsAuxCtlVec<MODEL>::ObsAuxCtlVec starting" << std::endl;
   util::Timer timer(classname(), "ObsAuxCtlVec");
   for (icst_ it = other.ctlvecs_.begin(); it != other.ctlvecs_.end(); ++it) {
     std::string incname = it->first;
     std::unique_ptr<ObsAuxCtlVecBase<MODEL>> auxctl(it->second->clone(copy));
     ctlvecs_.emplace(incname, std::move(auxctl));
     keys_.push_back(incname);
   }
   Log::trace() << "ObsAuxCtlVec<MODEL>::ObsAuxCtlVec done" << std::endl;
 }
References oops::ObsAuxCtlVec< MODEL >::classname(), oops::ObsAuxCtlVec< MODEL >::ctlvecs_, and oops::ObsAuxCtlVec< MODEL >::keys_.
~ObsAuxCtlVec()
template<typename MODEL > oops::ObsAuxCtlVec< MODEL >::~ObsAuxCtlVec
Destructor.
Definition at line 174 of file ObsAuxCtlVec.h.
{
   Log::trace() << "ObsAuxCtlVec<MODEL>::~ObsAuxCtlVec starting" << std::endl;
   util::Timer timer(classname(), "~ObsAuxCtlVec");
   Log::trace() << "ObsAuxCtlVec<MODEL>::~ObsAuxCtlVec done" << std::endl;
 }
Member Function Documentation
axpy()
template<typename MODEL > void oops::ObsAuxCtlVec< MODEL >::axpy (const double & zz, const ObsAuxCtlVec< MODEL > & dx)
\(dv_1 = dv_1 * c dv_2 \)
Definition at line 250 of file ObsAuxCtlVec.h.
{
   Log::trace() << "ObsAuxCtlVec<MODEL>::axpy starting" << std::endl;
   util::Timer timer(classname(), "axpy");
   for (iter_ it = ctlvecs_.begin(); it != ctlvecs_.end(); ++it) {
     it->second->axpy(zz, dx.obsAuxCtlVec(it->first));
   }
   Log::trace() << "ObsAuxCtlVec<MODEL>::axpy done" << std::endl;
 }
References oops::ObsAuxCtlVec< MODEL >::obsAuxCtlVec().
classname()
template<typename MODEL > static const std::string oops::ObsAuxCtlVec< MODEL >::classname () inline static
Definition at line 60 of file ObsAuxCtlVec.h.
 { return "oops::ObsAuxCtlVec"; }
Referenced by oops::ObsAuxCtlVec< MODEL >::ObsAuxCtlVec().
dot_product_with()
template<typename MODEL > double oops::ObsAuxCtlVec< MODEL >::dot_product_with (const ObsAuxCtlVec< MODEL > & dx) const
\(<dv_1,dv_1> = dv_1^T dv_1 \)
Definition at line 260 of file ObsAuxCtlVec.h.
{
   Log::trace() << "ObsAuxCtlVec<MODEL>::dot_product_with starting" << std::endl;
   util::Timer timer(classname(), "dot_product_with");
   double zz = 0.0;
   for (icst_ it = ctlvecs_.begin(); it != ctlvecs_.end(); ++it) {
     zz += it->second->dot_product_with(dx.obsAuxCtlVec(it->first));
   }
   Log::trace() << "ObsAuxCtlVec<MODEL>::dot_product_with done" << std::endl;
   return zz;
 }
References oops::ObsAuxCtlVec< MODEL >::obsAuxCtlVec().
get() [1/2]
template<typename MODEL > ObsAuxCtlVecBase< MODEL > & oops::ObsAuxCtlVec< MODEL >::get (const std::string & id) private
Return a reference to the model specific object.
Definition at line 181 of file ObsAuxCtlVec.h.
{
   iter_ it = ctlvecs_.find(id);
   ASSERT(it != ctlvecs_.end());
   return *it->second;
 }
get() [2/2]
template<typename MODEL > const ObsAuxCtlVecBase< MODEL > & oops::ObsAuxCtlVec< MODEL >::get (const std::string & id) const private
Return a constant reference to the model specific object.
Definition at line 188 of file ObsAuxCtlVec.h.
{
   icst_ it = ctlvecs_.find(id);
   ASSERT(it != ctlvecs_.end());
   return *it->second;
 }
Referenced by oops::ObsAuxCtlVec< MODEL >::obsAuxCtlVec().
getKeys()
template<typename MODEL > const std::vector<std::string>& oops::ObsAuxCtlVec< MODEL >::getKeys () const inline
Return a constant reference to the vector of keys.
Definition at line 106 of file ObsAuxCtlVec.h.
 { return keys_; }
References oops::ObsAuxCtlVec< MODEL >::keys_.
norm()
template<typename MODEL > double oops::ObsAuxCtlVec< MODEL >::norm
L-2 norm.
Definition at line 304 of file ObsAuxCtlVec.h.
{
   Log::trace() << "ObsAuxCtlVec<MODEL>::norm starting" << std::endl;
   util::Timer timer(classname(), "norm");
   double zz = 0.0;
   for (icst_ it = ctlvecs_.begin(); it != ctlvecs_.end(); ++it) {
     double norm = it->second->norm();
     zz += norm * norm;
   }
   Log::trace() << "ObsAuxCtlVec<MODEL>::norm done" << std::endl;
   return sqrt(zz);
 }
obsAuxCtlVec() [1/2]
template<typename MODEL > ObsAuxCtlVecBase_& oops::ObsAuxCtlVec< MODEL >::obsAuxCtlVec (const std::string & id) inline
Return a reference to the model specific object.
Definition at line 101 of file ObsAuxCtlVec.h.
{
     return this->get(id);
   }
References oops::ObsAuxCtlVec< MODEL >::get().
obsAuxCtlVec() [2/2]
template<typename MODEL > const ObsAuxCtlVecBase_& oops::ObsAuxCtlVec< MODEL >::obsAuxCtlVec (const std::string & id) const inline
Return a constant reference to the model specific object.
Definition at line 97 of file ObsAuxCtlVec.h.
{
     return this->get(id);
   }
References oops::ObsAuxCtlVec< MODEL >::get().
Referenced by oops::ObsAuxCtlVec< MODEL >::axpy(), oops::ObsAuxCtlVec< MODEL >::dot_product_with(), oops::ObsAuxCovariance< MODEL >::multiplySqrt(), oops::ObsAuxCovariance< MODEL >::multiplySqrtTrans(), oops::ObsAuxCtlVec< MODEL >::operator+=(), oops::ObsAuxCtlVec< MODEL >::operator-=(), and oops::ObsAuxCtlVec< MODEL >::operator=().
operator*=()
template<typename MODEL > ObsAuxCtlVec< MODEL > & oops::ObsAuxCtlVec< MODEL >::operator*= (const double & zz)
\(dv_1 = dv_1 * c \)
Definition at line 239 of file ObsAuxCtlVec.h.
{
   Log::trace() << "ObsAuxCtlVec<MODEL>::operator*= starting" << std::endl;
   util::Timer timer(classname(), "operator*=");
   for (iter_ it = ctlvecs_.begin(); it != ctlvecs_.end(); ++it) {
     *(it->second) *= zz;
   }
   Log::trace() << "ObsAuxCtlVec<MODEL>::operator*= done" << std::endl;
   return *this;
 }
operator+=()
template<typename MODEL > ObsAuxCtlVec< MODEL > & oops::ObsAuxCtlVec< MODEL >::operator+= (const ObsAuxCtlVec< MODEL > & rhs)
\(dv_1 = dv_1 + dv_2 \)
Definition at line 217 of file ObsAuxCtlVec.h.
{
   Log::trace() << "ObsAuxCtlVec<MODEL>::operator+= starting" << std::endl;
   util::Timer timer(classname(), "operator+=");
   for (iter_ it = ctlvecs_.begin(); it != ctlvecs_.end(); ++it) {
     *(it->second) += rhs.obsAuxCtlVec(it->first);
   }
   Log::trace() << "ObsAuxCtlVec<MODEL>::operator+= done" << std::endl;
   return *this;
 }
References oops::ObsAuxCtlVec< MODEL >::obsAuxCtlVec().
operator-=()
template<typename MODEL > ObsAuxCtlVec< MODEL > & oops::ObsAuxCtlVec< MODEL >::operator-= (const ObsAuxCtlVec< MODEL > & rhs)
\(dv_1 = dv_1 - dv_2 \)
Definition at line 228 of file ObsAuxCtlVec.h.
{
   Log::trace() << "ObsAuxCtlVec<MODEL>::operator-= starting" << std::endl;
   util::Timer timer(classname(), "operator-=");
   for (iter_ it = ctlvecs_.begin(); it != ctlvecs_.end(); ++it) {
     *(it->second) -= rhs.obsAuxCtlVec(it->first);
   }
   Log::trace() << "ObsAuxCtlVec<MODEL>::operator-= done" << std::endl;
   return *this;
 }
References oops::ObsAuxCtlVec< MODEL >::obsAuxCtlVec().
operator=()
template<typename MODEL > ObsAuxCtlVec< MODEL > & oops::ObsAuxCtlVec< MODEL >::operator= (const ObsAuxCtlVec< MODEL > & rhs)
\(dv_1 = dv_2 \)
Definition at line 206 of file ObsAuxCtlVec.h.
{
   Log::trace() << "ObsAuxCtlVec<MODEL>::operator= starting" << std::endl;
   util::Timer timer(classname(), "operator=");
   for (iter_ it = ctlvecs_.begin(); it != ctlvecs_.end(); ++it) {
     *(it->second) = rhs.obsAuxCtlVec(it->first);
   }
   Log::trace() << "ObsAuxCtlVec<MODEL>::operator= done" << std::endl;
   return *this;
 }
References oops::ObsAuxCtlVec< MODEL >::obsAuxCtlVec().
print()
template<typename MODEL > void oops::ObsAuxCtlVec< MODEL >::print (std::ostream & os) const private
Definition at line 317 of file ObsAuxCtlVec.h.
{
   Log::trace() << "ObsAuxCtlVec<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   for (icst_ it = ctlvecs_.begin(); it != ctlvecs_.end(); ++it) {
     os << it->first << ": " << *it->second;
   }
   Log::trace() << "ObsAuxCtlVec<MODEL>::print done" << std::endl;
 }
read()
template<typename MODEL > void oops::ObsAuxCtlVec< MODEL >::read (const eckit::Configuration & conf)
Read control vector.
Definition at line 272 of file ObsAuxCtlVec.h.
{
   Log::trace() << "ObsAuxCtlVec<MODEL>::read starting" << std::endl;
   util::Timer timer(classname(), "read");
   std::vector<eckit::LocalConfiguration> confs;
   if (conf.has("ctlvecObsAux")) conf.get("ctlvecObsAux", confs);
   for (iter_ it = ctlvecs_.begin(); it != ctlvecs_.end(); ++it) {
     for (auto const &config : confs) {
       if (config.getString("type") == it->first) it->second->read(config);
     }
   }
   Log::trace() << "ObsAuxCtlVec<MODEL>::read done" << std::endl;
 }
size()
template<typename MODEL > const size_t& oops::ObsAuxCtlVec< MODEL >::size () const inline
Return the number of ObsAuxCtlVecBase objects.
Definition at line 109 of file ObsAuxCtlVec.h.
 { return size_; }
References oops::ObsAuxCtlVec< MODEL >::size_.
write()
template<typename MODEL > void oops::ObsAuxCtlVec< MODEL >::write (const eckit::Configuration & conf) const
Write control vector.
Definition at line 288 of file ObsAuxCtlVec.h.
{
   Log::trace() << "ObsAuxCtlVec<MODEL>::write starting" << std::endl;
   util::Timer timer(classname(), "write");
   std::vector<eckit::LocalConfiguration> confs;
   if (conf.has("ctlvecObsAux")) conf.get("ctlvecObsAux", confs);
   for (icst_ it = ctlvecs_.begin(); it != ctlvecs_.end(); ++it) {
     for (auto const &config : confs) {
       if (config.getString("type") == it->first) it->second->write(config);
     }
   }
   Log::trace() << "ObsAuxCtlVec<MODEL>::write done" << std::endl;
 }
zero()
template<typename MODEL > void oops::ObsAuxCtlVec< MODEL >::zero
\(dv_1 = 0 \)
Definition at line 196 of file ObsAuxCtlVec.h.
{
   Log::trace() << "ObsAuxCtlVec<MODEL>::zero starting" << std::endl;
   util::Timer timer(classname(), "zero");
   for (iter_ it = ctlvecs_.begin(); it != ctlvecs_.end(); ++it) {
     it->second->zero();
   }
   Log::trace() << "ObsAuxCtlVec<MODEL>::zero done" << std::endl;
 }
Member Data Documentation
ctlvecs_
template<typename MODEL > ObsAuxCtlVecPtrMap_ oops::ObsAuxCtlVec< MODEL >::ctlvecs_ private
Map of pointers to model specific objects.
Definition at line 120 of file ObsAuxCtlVec.h.
Referenced by oops::ObsAuxCtlVec< MODEL >::ObsAuxCtlVec().
keys_
template<typename MODEL > std::vector<std::string> oops::ObsAuxCtlVec< MODEL >::keys_ private
Vector of keys to model specific objects.
Definition at line 119 of file ObsAuxCtlVec.h.
Referenced by oops::ObsAuxCtlVec< MODEL >::getKeys(), and oops::ObsAuxCtlVec< MODEL >::ObsAuxCtlVec().
size_
template<typename MODEL > size_t oops::ObsAuxCtlVec< MODEL >::size_ mutable private
Number of model specific objects.
Definition at line 118 of file ObsAuxCtlVec.h.
Referenced by oops::ObsAuxCtlVec< MODEL >::ObsAuxCtlVec(), and oops::ObsAuxCtlVec< MODEL >::size().
The documentation for this class was generated from the following file:
src/oops/interface/ObsAuxCtlVec.h