OOPS Documentation: oops::CostFct4DVarHyb4D< MODEL > Class Template Reference
oops::CostFct4DVarHyb4D< MODEL > Class Template Reference
4DVarHyb4D Cost Function in the ARPEGE
#include <CostFct4DVarHyb4D.h>
Public Member Functions
CostFct4DVarHyb4D (const eckit::Configuration &, const Geometry_ &, const Model_ &)
~CostFct4DVarHyb4D ()
void runTL (CtrlInc_ &, PostProcessorTL< Increment_ > &, PostProcessor< Increment_ >, const bool idModel=false) const override
Run the tangent linear model with 4D Increment.
void runAD (CtrlInc_ &, PostProcessorAD< Increment_ > &, PostProcessor< Increment_ >, const bool idModel=false) const override
Run the adjoint model with 4D Increment.
void zeroAD (CtrlInc_ &) const override
Nullify the 4D increment prior to running the adjoint model.
Public Member Functions inherited from oops::CostFct4DVarMFTemplate< MODEL >
CostFct4DVarMFTemplate (const eckit::Configuration &, const Geometry_ &, const Model_ &)
~CostFct4DVarMFTemplate ()
double evaluate (const CtrlVar_ &, const eckit::Configuration &config=eckit::LocalConfiguration(), PostProcessor< State_ > post=PostProcessor< State_ >()) const override
Evaluate the non-linear cost function.
double linearize (const CtrlVar_ &, const eckit::Configuration &, PostProcessor< State_ > post=PostProcessor< State_ >()) override
Set up the quadratic cost function. Specific linearization for ARPEGE 4D-Var.
void runTL (CtrlInc_ &, PostProcessorTL< Increment_ > &, PostProcessor< Increment_ >, const bool idModel=false) const override
Run the tangent linear model.
void runAD (CtrlInc_ &, PostProcessorAD< Increment_ > &, PostProcessor< Increment_ >, const bool idModel=false) const override
Run the adjoint model.
void zeroAD (CtrlInc_ &) const override
Nullify the increment prior to running the adjoint model.
void runNL (CtrlVar_ &xx, PostProcessor< State_ > &pp) const override
Run the non-linear model (HR)
void runNL (CtrlVar_ &, const Model_ &model, PostProcessor< State_ > &) override
Run the non-linear model (Trajectory)
const double & getCostJoJc () const override
Get the JoJc cost function value.
const double & getCostJb () const override
Get the Jb cost function value.
Public Member Functions inherited from oops::CostFunction< MODEL >
CostFunction (const eckit::Configuration &, const Geometry_ &, const Model_ &)
Construct a cost function.
virtual ~CostFunction ()
Destroy a cost function.
void addIncrement (CtrlVar_ &, const CtrlInc_ &, PostProcessor< Increment_ > post=PostProcessor< Increment_ >()) const
Add increment to the first guess.
void resetLinearization ()
Rest the quadratic cost function.
void computeGradientFG (CtrlInc_ &) const
Compute the cost function gradient at first guess (without Jb)
double computeGradientFG (const CtrlVec_ &, CtrlInc_ &) const
Compute the cost function gradient at first guess (without Jb)
void checkpoint (eckit::LocalConfiguration &) const
Checkpoint.
void restart (const eckit::Configuration &)
Restart.
const JbTotal_ & jb () const
Access \(J_b\).
const CostBase_ & jterm (const unsigned ii) const
Access terms of the cost function other than \(J_b\).
unsigned nterms () const
Return the numer of other cost function terms \(J_o, J_c, ..\).
Private Types
using Increment_ = Increment< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using CtrlVar_ = ControlVariable< MODEL >
using CostFct_ = CostFunction< MODEL >
using Geometry_ = Geometry< MODEL >
using State_ = State< MODEL >
using Model_ = Model< MODEL >
using Variables_ = Variables< MODEL >
Private Member Functions
CostJbState< MODEL > * newJb (const eckit::Configuration &, const Geometry_ &, const CtrlVar_ &) const override
Create the \(J_b\) 4D term of the cost function.
Private Attributes
util::Duration windowLength_
util::DateTime windowBegin_
util::DateTime windowEnd_
util::Duration windowSub_
unsigned int ncontrol_
const Variables_ ctlvars_
Additional Inherited Members
Static Public Member Functions inherited from oops::CostFunction< MODEL >
static const std::string classname ()
Protected Member Functions inherited from oops::CostFunction< MODEL >
void setupTerms (const eckit::Configuration &)
Set up terms of the cost function \(J_b, J_q, J_o, J_c, ..\).
const Model_ & getModel () const
Access the non-linear model.
const LinearModel_ & getTLM (const unsigned isub=0) const
Access the linear model.
void recentreBackground (const eckit::Configuration &)
Re-centre the background.
CostBase_ & getJterm (const unsigned ii) const
Non const access to JTerms for linearize() method in concrete cost-functions.
JbTotal_ & getJb () const
Non const access to Jb for linearize() method in concrete cost-functions
std::vector< std::unique_ptr< LinearModel_ > > & getTLMs ()
Non const access to TL Model for linearize() method in concrete cost-functions
Detailed Description
template<typename MODEL>
class oops::CostFct4DVarHyb4D< MODEL >
4DVarHyb4D Cost Function in the ARPEGE
This class implements a 4D-Var cost function for ARPEGE with specific TL/AD methods.
Definition at line 45 of file CostFct4DVarHyb4D.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::CostFct4DVarHyb4D< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 49 of file CostFct4DVarHyb4D.h.
CtrlInc_
template<typename MODEL > using oops::CostFct4DVarHyb4D< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 47 of file CostFct4DVarHyb4D.h.
CtrlVar_
template<typename MODEL > using oops::CostFct4DVarHyb4D< MODEL >::CtrlVar_ = ControlVariable<MODEL> private
Definition at line 48 of file CostFct4DVarHyb4D.h.
Geometry_
template<typename MODEL > using oops::CostFct4DVarHyb4D< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 50 of file CostFct4DVarHyb4D.h.
Increment_
template<typename MODEL > using oops::CostFct4DVarHyb4D< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 46 of file CostFct4DVarHyb4D.h.
Model_
template<typename MODEL > using oops::CostFct4DVarHyb4D< MODEL >::Model_ = Model<MODEL> private
Definition at line 52 of file CostFct4DVarHyb4D.h.
State_
template<typename MODEL > using oops::CostFct4DVarHyb4D< MODEL >::State_ = State<MODEL> private
Definition at line 51 of file CostFct4DVarHyb4D.h.
Variables_
template<typename MODEL > using oops::CostFct4DVarHyb4D< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 53 of file CostFct4DVarHyb4D.h.
Constructor & Destructor Documentation
CostFct4DVarHyb4D()
template<typename MODEL > oops::CostFct4DVarHyb4D< MODEL >::CostFct4DVarHyb4D (const eckit::Configuration & config, const Geometry_ & resol, const Model_ & model)
Create J components \(J_b\) , \(J_o\), \(J_c\) ...
Definition at line 91 of file CostFct4DVarHyb4D.h.
 : CostFct4DVarMFTemplate<MODEL>::CostFct4DVarMFTemplate(config, resol, model), ctlvars_(config)
 {
   windowLength_ = util::Duration(config.getString("window_length"));
   windowBegin_ = util::DateTime(config.getString("window_begin"));
   windowEnd_ = windowBegin_ + windowLength_;
   windowSub_ = util::Duration(config.getString("window_sub"));
   ncontrol_ = windowLength_.toSeconds() / windowSub_.toSeconds();
   ASSERT(windowLength_.toSeconds() == windowSub_.toSeconds()*ncontrol_);
   this->setupTerms(config);
   Log::trace() << "CostFct4DVarHyb4D constructed" << std::endl;
 }
References oops::CostFct4DVarHyb4D< MODEL >::ncontrol_, oops::CostFunction< MODEL >::setupTerms(), oops::CostFct4DVarHyb4D< MODEL >::windowBegin_, oops::CostFct4DVarHyb4D< MODEL >::windowEnd_, oops::CostFct4DVarHyb4D< MODEL >::windowLength_, and oops::CostFct4DVarHyb4D< MODEL >::windowSub_.
~CostFct4DVarHyb4D()
template<typename MODEL > oops::CostFct4DVarHyb4D< MODEL >::~CostFct4DVarHyb4D () inline
Definition at line 57 of file CostFct4DVarHyb4D.h.
 {}
Member Function Documentation
newJb()
template<typename MODEL > CostJbState< MODEL > * oops::CostFct4DVarHyb4D< MODEL >::newJb (const eckit::Configuration & jbConf, const Geometry_ & resol, const CtrlVar_ & xb) const override private virtual
Create the \(J_b\) 4D term of the cost function.
Implements oops::CostFunction< MODEL >.
Definition at line 110 of file CostFct4DVarHyb4D.h.
{
   util::Duration zero(0);
   return new CostJb4D<MODEL>(jbConf, resol, ctlvars_, zero, xb.state());
 }
References oops::ControlVariable< MODEL >::state().
runAD()
template<typename MODEL > void oops::CostFct4DVarHyb4D< MODEL >::runAD (CtrlInc_ & dx, PostProcessorAD< Increment_ > & cost, PostProcessor< Increment_ > post, const bool idModel = false) const override virtual
Run the adjoint model with 4D Increment.
In the IFS, cost.finalizeTL has to be called once after all horizontal interpolations (cost.processTL). But a forecast is called at each timeslot in order to connect dx with the model object.
Implements oops::CostFunction< MODEL >.
Definition at line 162 of file CostFct4DVarHyb4D.h.
{
   PostProcessorAD<Increment_> no_cost;
   PostProcessor<Increment_> no_post;
   CostFct_::getTLM().forecastAD(dx.state()[ncontrol_], dx.modVar(), util::Duration(0),
       no_post, no_cost);
   cost.initializeAD(dx.state()[ncontrol_], dx.state()[0].validTime(), util::Duration(0));
   for (int jsub = ncontrol_; jsub >= 1; --jsub) {
     util::DateTime now(windowBegin_ + jsub*windowSub_);
     ASSERT(dx.state()[jsub].validTime() == now);
     CostFct_::getTLM().forecastAD(dx.state()[jsub], dx.modVar(), util::Duration(0),
           no_post, no_cost);
     cost.processAD(dx.state()[jsub]);
   }
   CostFct_::getTLM().forecastAD(dx.state()[0], dx.modVar(), util::Duration(0),
       no_post, no_cost);
   cost.finalizeAD(dx.state()[0]);
 }
References oops::PostProcessorAD< INCR >::finalizeAD(), oops::PostProcessorAD< INCR >::initializeAD(), oops::ControlIncrement< MODEL >::modVar(), oops::PostProcessorAD< INCR >::processAD(), and oops::ControlIncrement< MODEL >::state().
runTL()
template<typename MODEL > void oops::CostFct4DVarHyb4D< MODEL >::runTL (CtrlInc_ & dx, PostProcessorTL< Increment_ > & cost, PostProcessor< Increment_ > post, const bool idModel = false) const override virtual
Run the tangent linear model with 4D Increment.
In the IFS, cost.finalizeTL has to be called once after all horizontal interpolations (cost.processTL). But a forecast is called at each timeslot in order to connect dx with the model object.
Implements oops::CostFunction< MODEL >.
Definition at line 120 of file CostFct4DVarHyb4D.h.
{
   PostProcessorTL<Increment_> no_cost;
   PostProcessor<Increment_> no_post;
   CostFct_::getTLM().forecastTL(dx.state()[0], dx.modVar(), util::Duration(0),
       no_post, no_cost);
   cost.initializeTL(dx.state()[0], dx.state()[ncontrol_].validTime(), util::Duration(0));
   for (int jsub = 1; jsub <= ncontrol_; ++jsub) {
     util::DateTime now(windowBegin_ + jsub*windowSub_);
     ASSERT(dx.state()[jsub].validTime() == now);
     CostFct_::getTLM().forecastTL(dx.state()[jsub], dx.modVar(), util::Duration(0),
           no_post, no_cost);
     cost.processTL(dx.state()[jsub]);
   }
   cost.finalizeTL(dx.state()[0]);
 }
References oops::PostProcessorTL< INCR >::finalizeTL(), oops::PostProcessorTL< INCR >::initializeTL(), oops::ControlIncrement< MODEL >::modVar(), oops::PostProcessorTL< INCR >::processTL(), and oops::ControlIncrement< MODEL >::state().
zeroAD()
template<typename MODEL > void oops::CostFct4DVarHyb4D< MODEL >::zeroAD (CtrlInc_ & dx) const override virtual
Nullify the 4D increment prior to running the adjoint model.
Implements oops::CostFunction< MODEL >.
Definition at line 149 of file CostFct4DVarHyb4D.h.
{
   util::DateTime now(windowBegin_);
   for (unsigned int jsub = 0; jsub <= ncontrol_; ++jsub) {
     dx.state()[jsub].zero(now);
     now += windowSub_;
   }
   dx.modVar().zero();
   dx.obsVar().zero();
 }
References oops::ControlIncrement< MODEL >::modVar(), oops::ControlIncrement< MODEL >::obsVar(), oops::ControlIncrement< MODEL >::state(), oops::ObsAuxIncrements< MODEL >::zero(), oops::ModelAuxIncrement< MODEL >::zero(), and oops::Increment4D< MODEL >::zero().
Member Data Documentation
ctlvars_
template<typename MODEL > const Variables_ oops::CostFct4DVarHyb4D< MODEL >::ctlvars_ private
Definition at line 84 of file CostFct4DVarHyb4D.h.
ncontrol_
template<typename MODEL > unsigned int oops::CostFct4DVarHyb4D< MODEL >::ncontrol_ private
Definition at line 83 of file CostFct4DVarHyb4D.h.
Referenced by oops::CostFct4DVarHyb4D< MODEL >::CostFct4DVarHyb4D().
windowBegin_
template<typename MODEL > util::DateTime oops::CostFct4DVarHyb4D< MODEL >::windowBegin_ private
Definition at line 80 of file CostFct4DVarHyb4D.h.
Referenced by oops::CostFct4DVarHyb4D< MODEL >::CostFct4DVarHyb4D().
windowEnd_
template<typename MODEL > util::DateTime oops::CostFct4DVarHyb4D< MODEL >::windowEnd_ private
Definition at line 81 of file CostFct4DVarHyb4D.h.
Referenced by oops::CostFct4DVarHyb4D< MODEL >::CostFct4DVarHyb4D().
windowLength_
template<typename MODEL > util::Duration oops::CostFct4DVarHyb4D< MODEL >::windowLength_ private
Definition at line 79 of file CostFct4DVarHyb4D.h.
Referenced by oops::CostFct4DVarHyb4D< MODEL >::CostFct4DVarHyb4D().
windowSub_
template<typename MODEL > util::Duration oops::CostFct4DVarHyb4D< MODEL >::windowSub_ private
Definition at line 82 of file CostFct4DVarHyb4D.h.
Referenced by oops::CostFct4DVarHyb4D< MODEL >::CostFct4DVarHyb4D().
The documentation for this class was generated from the following file:
src/oops/assimilation/CostFct4DVarHyb4D.h