OOPS Documentation: oops::IdentityMatrix< VECTOR > Class Template Reference
oops::IdentityMatrix< VECTOR > Class Template Reference
Identity matrix.
#include <IdentityMatrix.h>
Public Member Functions
void multiply (const VECTOR &a, VECTOR &b) const
Detailed Description
template<typename VECTOR>
class oops::IdentityMatrix< VECTOR >
Identity matrix.
Definition at line 18 of file IdentityMatrix.h.
Member Function Documentation
multiply()
template<typename VECTOR > void oops::IdentityMatrix< VECTOR >::multiply (const VECTOR & a, VECTOR & b) const inline
Definition at line 20 of file IdentityMatrix.h.
 { b = a; }
Referenced by oops::RPCGMinimizer< MODEL >::solve(), oops::RPLanczosMinimizer< MODEL >::solve(), and oops::DRGMRESRMinimizer< MODEL >::solve().
The documentation for this class was generated from the following file:
src/oops/base/IdentityMatrix.h