OOPS Documentation: oops::Ensemble< MODEL > Class Template Reference
oops::Ensemble< MODEL > Class Template Reference
Ensemble.
#include <Ensemble.h>
Public Member Functions
Ensemble (const util::DateTime &, const eckit::Configuration &, bool distributed=false)
Constructor.
Ensemble (const Ensemble &)
virtual ~Ensemble ()
Destructor.
unsigned int size () const
Accessors.
Increment_ & operator[] (const int ii)
const Increment_ & operator[] (const int ii) const
void linearize (const State_ &, const Geometry_ &)
void build (const State_ &, const Geometry_ &)
void read ()
void to_perturbations ()
void to_perturbations (bool distributed, unsigned id=0)
void to_perturbations (int nb_sub_ens)
const Variables_ & controlVariables () const
eckit::Buffer & pack ()
Private Types
using Geometry_ = Geometry< MODEL >
using State_ = State< MODEL >
using Increment_ = Increment< MODEL >
using Variables_ = Variables< MODEL >
Private Attributes
const eckit::LocalConfiguration config_
const util::DateTime validTime_
const Variables_ vars_
unsigned int rank_
double infl_
std::vector< std::unique_ptr< Increment_ > > ensemblePerturbs_
bool is_distributed_
std::unique_ptr< eckit::Buffer > arch_
Detailed Description
template<typename MODEL>
class oops::Ensemble< MODEL >
Ensemble.
Definition at line 43 of file Ensemble.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::Ensemble< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 44 of file Ensemble.h.
Increment_
template<typename MODEL > using oops::Ensemble< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 46 of file Ensemble.h.
State_
template<typename MODEL > using oops::Ensemble< MODEL >::State_ = State<MODEL> private
Definition at line 45 of file Ensemble.h.
Variables_
template<typename MODEL > using oops::Ensemble< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 47 of file Ensemble.h.
Constructor & Destructor Documentation
Ensemble() [1/2]
template<typename MODEL > oops::Ensemble< MODEL >::Ensemble (const util::DateTime & validTime, const eckit::Configuration & conf, bool distributed = false)
Constructor.
Definition at line 95 of file Ensemble.h.
     : config_(conf),
       validTime_(validTime),
       vars_(conf),
       rank_(conf.getInt("members")),
       infl_(conf.getDouble("inflation", 1.0)),
       ensemblePerturbs_(),
       is_distributed_(distributed) {
   Log::trace() << "Ensemble:contructor done" << std::endl;
 }
Ensemble() [2/2]
template<typename MODEL > oops::Ensemble< MODEL >::Ensemble (const Ensemble< MODEL > & e)
Definition at line 110 of file Ensemble.h.
     : config_(e.config_),
       validTime_(e.validTime_),
       vars_(e.vars_),
       rank_(e.rank_),
       infl_(e.infl_),
       ensemblePerturbs_(),
       is_distributed_(e.is_distributed_) {
   for (unsigned int m = 0; m < rank_; ++m) {
     Increment_ *dx = new Increment_(*(e.ensemblePerturbs_[m]));
     ensemblePerturbs_.emplace_back(dx);
   }
   Log::trace() << "Ensemble:copy contructor done" << std::endl;
 }
References oops::Ensemble< MODEL >::ensemblePerturbs_, and oops::Ensemble< MODEL >::rank_.
~Ensemble()
template<typename MODEL > virtual oops::Ensemble< MODEL >::~Ensemble () inline virtual
Destructor.
Definition at line 57 of file Ensemble.h.
 {}
Member Function Documentation
build()
template<typename MODEL > void oops::Ensemble< MODEL >::build (const State_ & xb, const Geometry_ & resol)
Definition at line 137 of file Ensemble.h.
{
   /* Build objects for storing Ensemble datas */
   unsigned int size = rank_;
   if (is_distributed_) size = 2;
   for (unsigned int m = 0; m < size; ++m) {
     Increment_ *dx = new Increment_(resol, vars_, validTime_);
     dx->zero();
     if (is_distributed_ && (m == 0)) {
       dx->accumul(1.0, xb);
     }
     ensemblePerturbs_.emplace_back(dx);
   }
 }
References oops::Increment< MODEL >::accumul(), and oops::Increment< MODEL >::zero().
controlVariables()
template<typename MODEL > const Variables_& oops::Ensemble< MODEL >::controlVariables () const inline
Definition at line 73 of file Ensemble.h.
 { return vars_; }
References oops::Ensemble< MODEL >::vars_.
linearize()
template<typename MODEL > void oops::Ensemble< MODEL >::linearize (const State_ & xb, const Geometry_ & resol)
Definition at line 128 of file Ensemble.h.
{
   ASSERT(xb.validTime() == validTime_);
   build(xb, resol);
   read();
   to_perturbations();
 }
References oops::State< MODEL >::validTime().
operator[]() [1/2]
template<typename MODEL > Increment_& oops::Ensemble< MODEL >::operator[] (const int ii) inline
Definition at line 61 of file Ensemble.h.
 { return *ensemblePerturbs_[ii]; }
References oops::Ensemble< MODEL >::ensemblePerturbs_.
operator[]() [2/2]
template<typename MODEL > const Increment_& oops::Ensemble< MODEL >::operator[] (const int ii) const inline
Definition at line 62 of file Ensemble.h.
{
     return *ensemblePerturbs_[ii];
   }
References oops::Ensemble< MODEL >::ensemblePerturbs_.
pack()
template<typename MODEL > eckit::Buffer& oops::Ensemble< MODEL >::pack () inline
Definition at line 75 of file Ensemble.h.
                       {
     ASSERT(is_distributed_);
     return *arch_;
   }
References oops::Ensemble< MODEL >::arch_, and oops::Ensemble< MODEL >::is_distributed_.
read()
template<typename MODEL > void oops::Ensemble< MODEL >::read
Definition at line 154 of file Ensemble.h.
{
   if (is_distributed_) return;
   std::vector<eckit::LocalConfiguration> confs;
   config_.get("state", confs);
   ASSERT(confs.size() == rank_);
   for (unsigned int jm = 0; jm < rank_; ++jm) {
     ensemblePerturbs_[jm]->read(confs[jm]);
   }
 }
size()
template<typename MODEL > unsigned int oops::Ensemble< MODEL >::size () const inline
Accessors.
Definition at line 60 of file Ensemble.h.
 { return rank_; }
References oops::Ensemble< MODEL >::rank_.
to_perturbations() [1/3]
template<typename MODEL > void oops::Ensemble< MODEL >::to_perturbations
Definition at line 168 of file Ensemble.h.
{
   double r = 1.0 / sqrt(((double)rank_ - 1.0));
   double invrank = 1.0 / ((double)rank_);
   /* Update datas */
   Increment_ sum(*ensemblePerturbs_[0]);
   sum *= invrank;
   for (unsigned m = 1; m < rank_; ++m) {
     sum.axpy(invrank, *ensemblePerturbs_[m]);
   }
   Log::info() << "Ensemble.to_perturbations with inflation :" << infl_;
   r *= infl_;
   for (unsigned m = 0; m < rank_; ++m) {
     *ensemblePerturbs_[m] -= sum;
     *ensemblePerturbs_[m] *= r;
   }
 }
References oops::Increment< MODEL >::axpy().
to_perturbations() [2/3]
template<typename MODEL > void oops::Ensemble< MODEL >::to_perturbations (bool distributed, unsigned id = 0)
Definition at line 190 of file Ensemble.h.
{
   double r = 1.0 / sqrt(((double)rank_ - 1.0));
   double invrank = 1.0 / ((double)rank_);
   /* Update datas */
   Increment_ sum(*ensemblePerturbs_[0]);
   sum *= invrank;
   ASSERT(distributed == is_distributed_);
   util::MPIWrapper &mpiw = util::MPIWrapper::Instance();
   Increment_ tmp(*ensemblePerturbs_[0]);
   tmp.zero();
   if (mpiw.my_rank() == 0) {
     int tag = 666 + 1;
     eckit::mpi::Status st = mpiw.comm().probe(int(1), tag);
     size_t size = eckit::round(mpiw.comm().getCount<char>(st),
                                8);  //< round to nearest 8 bytes
     eckit::Buffer b(size);
     // Get members
     for (unsigned m = 1; m < rank_; ++m) {
       tag = 666 + m;
       b.zero();
       mpiw.comm().receive(static_cast<char *>(b.data()), b.size(), m, tag);
       eckit::ResizableMemoryStream sr(b);
       sr >> tmp;
       sum.axpy(invrank, tmp);
     }
     // Send the sum
     b.zero();
     eckit::ResizableMemoryStream ss(b);
     ss << sum;
     mpiw.comm().broadcast(static_cast<char *>(b.data()), ss.position(),
                           (size_t)0);
   } else {
     // Send my member
     int tag = 666 + mpiw.my_rank();
     eckit::Buffer b(32);
     eckit::ResizableMemoryStream ss(b);
     ss << (*ensemblePerturbs_[0]);
     eckit::mpi::Request req = mpiw.comm().iSend(
         static_cast<const char *>(b.data()), ss.position(), 0, tag);
     // Get the sum
     b.zero();
     mpiw.comm().broadcast(static_cast<char *>(b.data()), b.size(), (size_t)0);
     eckit::ResizableMemoryStream sr(b);
     sr >> sum;
     mpiw.comm().wait(req);
   }
   Log::info() << "Ensemble.to_perturbations with inflation :" << infl_;
   r *= infl_;
   int size = 1;
   for (int m = 0; m < size; ++m) {
     (*ensemblePerturbs_[m]) -= sum;
     (*ensemblePerturbs_[m]) *= r;
   }
   // Prepare package for MPI transfers
   arch_.reset(new eckit::Buffer(32));
   eckit::ResizableMemoryStream s(*arch_);
   s << (*ensemblePerturbs_[0]);
 }
References oops::Increment< MODEL >::axpy(), and oops::Increment< MODEL >::zero().
to_perturbations() [3/3]
template<typename MODEL > void oops::Ensemble< MODEL >::to_perturbations (int nb_sub_ens)
Definition at line 257 of file Ensemble.h.
{
   int sub_rank = rank_ / nb_sub_ensemble;
   double inv_sub_rank = 1.0 / ((double)sub_rank);
   double r = 1.0 / sqrt(((double)rank_ - 1.0));
   Log::info() << "Ensemble.to_perturbations with inflation :" << infl_;
   r *= infl_;
   /* Update datas */
   for (int p = 0; p < nb_sub_ensemble; ++p) {
     Log::info() << "Ensemble.to_perturbations, remove ensemble mean for "
                    "sub_ensemble # :"
                 << p + 1;
     Increment_ sum(*ensemblePerturbs_[p * sub_rank]);
     sum *= inv_sub_rank;
     for (int m = 1; m < sub_rank; ++m) {
       sum.axpy(inv_sub_rank, *ensemblePerturbs_[p * sub_rank + m]);
     }
     for (int m = 0; m < sub_rank; ++m) {
       *ensemblePerturbs_[p * sub_rank + m] -= sum;
       *ensemblePerturbs_[p * sub_rank + m] *= r;
     }
   }
 }
References oops::Increment< MODEL >::axpy().
Member Data Documentation
arch_
template<typename MODEL > std::unique_ptr<eckit::Buffer> oops::Ensemble< MODEL >::arch_ private
Definition at line 89 of file Ensemble.h.
Referenced by oops::Ensemble< MODEL >::pack().
config_
template<typename MODEL > const eckit::LocalConfiguration oops::Ensemble< MODEL >::config_ private
Definition at line 81 of file Ensemble.h.
ensemblePerturbs_
template<typename MODEL > std::vector<std::unique_ptr<Increment_> > oops::Ensemble< MODEL >::ensemblePerturbs_ private
Definition at line 86 of file Ensemble.h.
Referenced by oops::Ensemble< MODEL >::Ensemble(), and oops::Ensemble< MODEL >::operator[]().
infl_
template<typename MODEL > double oops::Ensemble< MODEL >::infl_ private
Definition at line 85 of file Ensemble.h.
is_distributed_
template<typename MODEL > bool oops::Ensemble< MODEL >::is_distributed_ private
Definition at line 88 of file Ensemble.h.
Referenced by oops::Ensemble< MODEL >::pack().
rank_
template<typename MODEL > unsigned int oops::Ensemble< MODEL >::rank_ private
Definition at line 84 of file Ensemble.h.
Referenced by oops::Ensemble< MODEL >::Ensemble(), and oops::Ensemble< MODEL >::size().
validTime_
template<typename MODEL > const util::DateTime oops::Ensemble< MODEL >::validTime_ private
Definition at line 82 of file Ensemble.h.
vars_
template<typename MODEL > const Variables_ oops::Ensemble< MODEL >::vars_ private
Definition at line 83 of file Ensemble.h.
Referenced by oops::Ensemble< MODEL >::controlVariables().
The documentation for this class was generated from the following file:
src/oops/base/Ensemble.h