OOPS Documentation: oops::CostFctWeak< MODEL > Class Template Reference
oops::CostFctWeak< MODEL > Class Template Reference
Weak Constraint 4D-Var Cost Function.
#include <CostFctWeak.h>
Public Member Functions
CostFctWeak (const eckit::Configuration &, const Geometry_ &, const Model_ &)
~CostFctWeak ()
void runTL (CtrlInc_ &, PostProcessorTL< Increment_ > &, PostProcessor< Increment_ >, const bool idModel=false) const override
Run the tangent linear model (virtual method)
void runAD (CtrlInc_ &, PostProcessorAD< Increment_ > &, PostProcessor< Increment_ >, const bool idModel=false) const override
Run the adjoint model (virtual method)
void zeroAD (CtrlInc_ &) const override
Nullify the increment prior to running the adjoint model (virtual method)
void runTL (CtrlInc_ &, const bool idModel=false) const
void runAD (CtrlInc_ &, const bool idModel=false) const
void runNL (CtrlVar_ &, PostProcessor< State_ > &) const override
Run the non-linear model (virtual method)
Public Member Functions inherited from oops::CostFunction< MODEL >
CostFunction (const eckit::Configuration &, const Geometry_ &, const Model_ &)
Construct a cost function.
virtual ~CostFunction ()
Destroy a cost function.
virtual double evaluate (const CtrlVar_ &, const eckit::Configuration &config=eckit::LocalConfiguration(), PostProcessor< State_ > post=PostProcessor< State_ >()) const
Evaluate the non-linear cost function.
virtual double linearize (const CtrlVar_ &, const eckit::Configuration &, PostProcessor< State_ > post=PostProcessor< State_ >())
Linearise the cost function: set up the quadratic cost function.
virtual void runNL (CtrlVar_ &xx, const Model_ &, PostProcessor< State_ > &pp)
Run the non-linear model (virtual method)
void addIncrement (CtrlVar_ &, const CtrlInc_ &, PostProcessor< Increment_ > post=PostProcessor< Increment_ >()) const
Add increment to the first guess.
void resetLinearization ()
Rest the quadratic cost function.
void computeGradientFG (CtrlInc_ &) const
Compute the cost function gradient at first guess (without Jb)
double computeGradientFG (const CtrlVec_ &, CtrlInc_ &) const
Compute the cost function gradient at first guess (without Jb)
void checkpoint (eckit::LocalConfiguration &) const
Checkpoint.
void restart (const eckit::Configuration &)
Restart.
const JbTotal_ & jb () const
Access \(J_b\).
const CostBase_ & jterm (const unsigned ii) const
Access terms of the cost function other than \(J_b\).
unsigned nterms () const
Return the numer of other cost function terms \(J_o, J_c, ..\).
virtual const double & getCostJb () const
Get the Jb cost function value.
virtual const double & getCostJoJc () const
Get the JoJc cost function value.
Private Types
using Increment_ = Increment< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using CtrlVar_ = ControlVariable< MODEL >
using CostFct_ = CostFunction< MODEL >
using Geometry_ = Geometry< MODEL >
using State_ = State< MODEL >
using Model_ = Model< MODEL >
using Variables_ = Variables< MODEL >
Private Member Functions
void addIncr (CtrlVar_ &, const CtrlInc_ &, PostProcessor< Increment_ > &) const override
Virtual method to add the increment to the state.
CostJbJq< MODEL > * newJb (const eckit::Configuration &, const Geometry_ &, const CtrlVar_ &) const override
Create the \(J_b, J_q\) term of the cost function (virtual method)
CostJo< MODEL > * newJo (const eckit::Configuration &) const override
Create the \(J_o\) term of the cost function (virtual method)
CostTermBase< MODEL > * newJc (const eckit::Configuration &, const Geometry_ &) const override
Create other terms of the cost function \(J_c, ..\) (virtual method)
Private Attributes
util::Duration windowLength_
util::DateTime windowBegin_
util::DateTime windowEnd_
util::Duration windowSub_
unsigned int nsubwin_
bool tlforcing_
const Geometry_ & geom_
const Variables_ ctlvars_
Additional Inherited Members
Static Public Member Functions inherited from oops::CostFunction< MODEL >
static const std::string classname ()
Protected Member Functions inherited from oops::CostFunction< MODEL >
void setupTerms (const eckit::Configuration &)
Set up terms of the cost function \(J_b, J_q, J_o, J_c, ..\).
const Model_ & getModel () const
Access the non-linear model.
const LinearModel_ & getTLM (const unsigned isub=0) const
Access the linear model.
void recentreBackground (const eckit::Configuration &)
Re-centre the background.
CostBase_ & getJterm (const unsigned ii) const
Non const access to JTerms for linearize() method in concrete cost-functions.
JbTotal_ & getJb () const
Non const access to Jb for linearize() method in concrete cost-functions
std::vector< std::unique_ptr< LinearModel_ > > & getTLMs ()
Non const access to TL Model for linearize() method in concrete cost-functions
Detailed Description
template<typename MODEL>
class oops::CostFctWeak< MODEL >
Weak Constraint 4D-Var Cost Function.
General weak constraint constraint 4D-Var cost function.
Definition at line 47 of file CostFctWeak.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::CostFctWeak< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 51 of file CostFctWeak.h.
CtrlInc_
template<typename MODEL > using oops::CostFctWeak< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 49 of file CostFctWeak.h.
CtrlVar_
template<typename MODEL > using oops::CostFctWeak< MODEL >::CtrlVar_ = ControlVariable<MODEL> private
Definition at line 50 of file CostFctWeak.h.
Geometry_
template<typename MODEL > using oops::CostFctWeak< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 52 of file CostFctWeak.h.
Increment_
template<typename MODEL > using oops::CostFctWeak< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 48 of file CostFctWeak.h.
Model_
template<typename MODEL > using oops::CostFctWeak< MODEL >::Model_ = Model<MODEL> private
Definition at line 54 of file CostFctWeak.h.
State_
template<typename MODEL > using oops::CostFctWeak< MODEL >::State_ = State<MODEL> private
Definition at line 53 of file CostFctWeak.h.
Variables_
template<typename MODEL > using oops::CostFctWeak< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 55 of file CostFctWeak.h.
Constructor & Destructor Documentation
CostFctWeak()
template<typename MODEL > oops::CostFctWeak< MODEL >::CostFctWeak (const eckit::Configuration & config, const Geometry_ & geom, const Model_ & model)
Definition at line 96 of file CostFctWeak.h.
     : CostFunction<MODEL>::CostFunction(config, geom, model),
       tlforcing_(false),
       geom_(geom),
       ctlvars_(config) {
   windowLength_ = util::Duration(config.getString("window_length"));
   windowBegin_ = util::DateTime(config.getString("window_begin"));
   windowEnd_ = windowBegin_ + windowLength_;
   windowSub_ = util::Duration(config.getString("window_sub"));
   nsubwin_ = windowLength_.toSeconds() / windowSub_.toSeconds();
   ASSERT(windowLength_.toSeconds() == windowSub_.toSeconds() * nsubwin_);
   if (config.has("tlforcing")) {
     if (config.getString("tlforcing") == "on") tlforcing_ = true;
   }
   this->setupTerms(config);
   Log::trace() << "CostFctWeak constructed" << std::endl;
 }
References oops::CostFctWeak< MODEL >::nsubwin_, oops::CostFunction< MODEL >::setupTerms(), oops::CostFctWeak< MODEL >::tlforcing_, oops::CostFctWeak< MODEL >::windowBegin_, oops::CostFctWeak< MODEL >::windowEnd_, oops::CostFctWeak< MODEL >::windowLength_, and oops::CostFctWeak< MODEL >::windowSub_.
~CostFctWeak()
template<typename MODEL > oops::CostFctWeak< MODEL >::~CostFctWeak () inline
Definition at line 59 of file CostFctWeak.h.
 {}
Member Function Documentation
addIncr()
template<typename MODEL > void oops::CostFctWeak< MODEL >::addIncr (CtrlVar_ & , const CtrlInc_ & , PostProcessor< Increment_ > &) const override private virtual
Virtual method to add the increment to the state.
Implements oops::CostFunction< MODEL >.
Definition at line 266 of file CostFctWeak.h.
{
   if (tlforcing_) {
     Increment_ xi(dx.state()[0]);
     for (unsigned int jsub = 0; jsub < nsubwin_; ++jsub) {
       if (jsub > 0) xi += dx.state()[jsub];
       xx.state()[jsub] += xi;
       if (jsub < nsubwin_ - 1) {
         CostFct_::getTLM(jsub).forecastTL(xi, dx.modVar(), windowSub_, post);
       }
     }
   } else {
     for (unsigned int jsub = 0; jsub < nsubwin_; ++jsub) {
       xx.state()[jsub] += dx.state()[jsub];
     }
   }
 }
References oops::ControlIncrement< MODEL >::modVar(), oops::ControlVariable< MODEL >::state(), and oops::ControlIncrement< MODEL >::state().
newJb()
template<typename MODEL > CostJbJq< MODEL > * oops::CostFctWeak< MODEL >::newJb (const eckit::Configuration & , const Geometry_ & , const CtrlVar_ &) const override private virtual
Create the \(J_b, J_q\) term of the cost function (virtual method)
Implements oops::CostFunction< MODEL >.
Definition at line 121 of file CostFctWeak.h.
{
   return new CostJbJq<MODEL>(jbConf, geom, ctlvars_, windowSub_, xb.state(),
                              tlforcing_);
 }
References oops::ControlVariable< MODEL >::state().
newJc()
template<typename MODEL > CostTermBase< MODEL > * oops::CostFctWeak< MODEL >::newJc (const eckit::Configuration & , const Geometry_ &) const override private virtual
Create other terms of the cost function \(J_c, ..\) (virtual method)
Implements oops::CostFunction< MODEL >.
Definition at line 140 of file CostFctWeak.h.
{
   const eckit::LocalConfiguration jcdfi(jcConf, "jcdfi");
   const util::DateTime vt(windowBegin_ + windowLength_ / 2);
   return new CostJcDFI<MODEL>(jcdfi, geom, vt, windowLength_);
 }
newJo()
template<typename MODEL > CostJo< MODEL > * oops::CostFctWeak< MODEL >::newJo (const eckit::Configuration &) const override private virtual
Create the \(J_o\) term of the cost function (virtual method)
Implements oops::CostFunction< MODEL >.
Definition at line 131 of file CostFctWeak.h.
{
   return new CostJo<MODEL>(joConf, geom_, windowBegin_, windowEnd_,
                            util::Duration(0), true);
 }
runAD() [1/2]
template<typename MODEL > void oops::CostFctWeak< MODEL >::runAD (CtrlInc_ & dx, const bool idModel = false) const
Definition at line 240 of file CostFctWeak.h.
{
   PostProcessor<Increment_> post;
   PostProcessorAD<Increment_> cost;
   ASSERT(!tlforcing_);
   dx.state().shift_backward();
   for (int jsub = dx.state().last(); jsub >= dx.state().first(); --jsub) {
     util::DateTime bgn(windowBegin_ + jsub * windowSub_);
     util::DateTime end(bgn + windowSub_);
     ASSERT(dx.state()[jsub].validTime() == end);
     if (idModel) {
       dx.state()[jsub].updateTime(-windowSub_);
     } else {
       CostFct_::getTLM(jsub).forecastAD(dx.state()[jsub], dx.modVar(),
                                         windowSub_, post, cost);
     }
     ASSERT(dx.state()[jsub].validTime() == bgn);
   }
 }
References oops::Increment4D< MODEL >::first(), oops::Increment4D< MODEL >::last(), oops::ControlIncrement< MODEL >::modVar(), oops::Increment4D< MODEL >::shift_backward(), and oops::ControlIncrement< MODEL >::state().
runAD() [2/2]
template<typename MODEL > void oops::CostFctWeak< MODEL >::runAD (CtrlInc_ & , PostProcessorAD< Increment_ > & , PostProcessor< Increment_ > post, const bool idModel = false) const override virtual
Run the adjoint model (virtual method)
Implements oops::CostFunction< MODEL >.
Definition at line 222 of file CostFctWeak.h.
{
   for (int jsub = dx.state().last(); jsub >= dx.state().first(); --jsub) {
     util::DateTime bgn(windowBegin_ + jsub * windowSub_);
     util::DateTime end(bgn + windowSub_);
     ASSERT(dx.state()[jsub].validTime() == end);
     CostFct_::getTLM(jsub).forecastAD(dx.state()[jsub], dx.modVar(), windowSub_,
                                       post, cost, idModel);
     if (tlforcing_ && jsub > 0) dx.state()[jsub - 1] += dx.state()[jsub];
     ASSERT(dx.state()[jsub].validTime() == bgn);
   }
 }
References oops::Increment4D< MODEL >::first(), oops::Increment4D< MODEL >::last(), oops::ControlIncrement< MODEL >::modVar(), and oops::ControlIncrement< MODEL >::state().
runNL()
template<typename MODEL > void oops::CostFctWeak< MODEL >::runNL (CtrlVar_ & , PostProcessor< State_ > &) const override virtual
Run the non-linear model (virtual method)
Implements oops::CostFunction< MODEL >.
Definition at line 150 of file CostFctWeak.h.
{
   for (unsigned int jsub = 0; jsub < nsubwin_; ++jsub) {
     util::DateTime bgn(windowBegin_ + jsub * windowSub_);
     util::DateTime end(bgn + windowSub_);
     ASSERT(xx.state()[jsub].validTime() == bgn);
     CostFct_::getModel().forecast(xx.state()[jsub], xx.modVar(), windowSub_,
                                   post);
     ASSERT(xx.state()[jsub].validTime() == end);
   }
 }
References oops::ControlVariable< MODEL >::modVar(), and oops::ControlVariable< MODEL >::state().
runTL() [1/2]
template<typename MODEL > void oops::CostFctWeak< MODEL >::runTL (CtrlInc_ & dx, const bool idModel = false) const
Definition at line 184 of file CostFctWeak.h.
{
   PostProcessor<Increment_> post;
   PostProcessorTL<Increment_> cost;
   ASSERT(!tlforcing_);
   for (int jsub = dx.state().first(); jsub <= dx.state().last(); ++jsub) {
     util::DateTime bgn(windowBegin_ + jsub * windowSub_);
     util::DateTime end(bgn + windowSub_);
     ASSERT(dx.state()[jsub].validTime() == bgn);
     if (idModel) {
       dx.state()[jsub].updateTime(windowSub_);
     } else {
       CostFct_::getTLM(jsub).forecastTL(dx.state()[jsub], dx.modVar(),
                                         windowSub_, post, cost);
     }
     ASSERT(dx.state()[jsub].validTime() == end);
   }
   dx.state().shift_forward();
 }
References oops::Increment4D< MODEL >::first(), oops::Increment4D< MODEL >::last(), oops::ControlIncrement< MODEL >::modVar(), oops::Increment4D< MODEL >::shift_forward(), and oops::ControlIncrement< MODEL >::state().
runTL() [2/2]
template<typename MODEL > void oops::CostFctWeak< MODEL >::runTL (CtrlInc_ & , PostProcessorTL< Increment_ > & , PostProcessor< Increment_ > post, const bool idModel = false) const override virtual
Run the tangent linear model (virtual method)
Implements oops::CostFunction< MODEL >.
Definition at line 166 of file CostFctWeak.h.
{
   for (int jsub = dx.state().first(); jsub <= dx.state().last(); ++jsub) {
     util::DateTime bgn(windowBegin_ + jsub * windowSub_);
     util::DateTime end(bgn + windowSub_);
     ASSERT(dx.state()[jsub].validTime() == bgn);
     if (tlforcing_ && jsub > 0) dx.state()[jsub] += dx.state()[jsub - 1];
     CostFct_::getTLM(jsub).forecastTL(dx.state()[jsub], dx.modVar(), windowSub_,
                                       post, cost, idModel);
     ASSERT(dx.state()[jsub].validTime() == end);
   }
 }
References oops::Increment4D< MODEL >::first(), oops::Increment4D< MODEL >::last(), oops::ControlIncrement< MODEL >::modVar(), and oops::ControlIncrement< MODEL >::state().
zeroAD()
template<typename MODEL > void oops::CostFctWeak< MODEL >::zeroAD (CtrlInc_ &) const override virtual
Nullify the increment prior to running the adjoint model (virtual method)
Implements oops::CostFunction< MODEL >.
Definition at line 210 of file CostFctWeak.h.
{
   for (int jsub = dx.state().first(); jsub <= dx.state().last(); ++jsub) {
     util::DateTime end(windowBegin_ + (jsub + 1) * windowSub_);
     dx.state()[jsub].zero(end);
   }
   dx.modVar().zero();
   dx.obsVar().zero();
 }
References oops::Increment4D< MODEL >::first(), oops::Increment4D< MODEL >::last(), oops::ControlIncrement< MODEL >::modVar(), oops::ControlIncrement< MODEL >::obsVar(), oops::ControlIncrement< MODEL >::state(), oops::ObsAuxIncrements< MODEL >::zero(), oops::ModelAuxIncrement< MODEL >::zero(), and oops::Increment4D< MODEL >::zero().
Member Data Documentation
ctlvars_
template<typename MODEL > const Variables_ oops::CostFctWeak< MODEL >::ctlvars_ private
Definition at line 90 of file CostFctWeak.h.
geom_
template<typename MODEL > const Geometry_& oops::CostFctWeak< MODEL >::geom_ private
Definition at line 89 of file CostFctWeak.h.
nsubwin_
template<typename MODEL > unsigned int oops::CostFctWeak< MODEL >::nsubwin_ private
Definition at line 87 of file CostFctWeak.h.
Referenced by oops::CostFctWeak< MODEL >::CostFctWeak().
tlforcing_
template<typename MODEL > bool oops::CostFctWeak< MODEL >::tlforcing_ private
Definition at line 88 of file CostFctWeak.h.
Referenced by oops::CostFctWeak< MODEL >::CostFctWeak().
windowBegin_
template<typename MODEL > util::DateTime oops::CostFctWeak< MODEL >::windowBegin_ private
Definition at line 84 of file CostFctWeak.h.
Referenced by oops::CostFctWeak< MODEL >::CostFctWeak().
windowEnd_
template<typename MODEL > util::DateTime oops::CostFctWeak< MODEL >::windowEnd_ private
Definition at line 85 of file CostFctWeak.h.
Referenced by oops::CostFctWeak< MODEL >::CostFctWeak().
windowLength_
template<typename MODEL > util::Duration oops::CostFctWeak< MODEL >::windowLength_ private
Definition at line 83 of file CostFctWeak.h.
Referenced by oops::CostFctWeak< MODEL >::CostFctWeak().
windowSub_
template<typename MODEL > util::Duration oops::CostFctWeak< MODEL >::windowSub_ private
Definition at line 86 of file CostFctWeak.h.
Referenced by oops::CostFctWeak< MODEL >::CostFctWeak().
The documentation for this class was generated from the following file:
src/oops/assimilation/CostFctWeak.h