OOPS Documentation: oops::ObsAuxCtlVecFactory< MODEL > Class Template Reference
oops::ObsAuxCtlVecFactory< MODEL > Class Template Reference abstract
ObsAuxCtlVec Factory.
#include <ObsAuxCtlVecBase.h>
Public Member Functions
virtual ~ObsAuxCtlVecFactory ()
Static Public Member Functions
static ObsAuxCtlVecBase< MODEL > * create (const ObsAuxCovarianceBase_ &)
Protected Member Functions
ObsAuxCtlVecFactory (const std::string &)
Private Types
using ObsAuxCovarianceBase_ = ObsAuxCovarianceBase< MODEL >
Private Member Functions
virtual ObsAuxCtlVecBase< MODEL > * make (const ObsAuxCovarianceBase_ &)=0
Static Private Member Functions
static std::map< std::string, ObsAuxCtlVecFactory< MODEL > * > & getMakers ()
Detailed Description
template<typename MODEL>
class oops::ObsAuxCtlVecFactory< MODEL >
ObsAuxCtlVec Factory.
Definition at line 92 of file ObsAuxCtlVecBase.h.
Member Typedef Documentation
ObsAuxCovarianceBase_
template<typename MODEL > using oops::ObsAuxCtlVecFactory< MODEL >::ObsAuxCovarianceBase_ = ObsAuxCovarianceBase<MODEL> private
Definition at line 93 of file ObsAuxCtlVecBase.h.
Constructor & Destructor Documentation
~ObsAuxCtlVecFactory()
template<typename MODEL > virtual oops::ObsAuxCtlVecFactory< MODEL >::~ObsAuxCtlVecFactory () inline virtual
Definition at line 97 of file ObsAuxCtlVecBase.h.
 { getMakers().clear(); }
References oops::ObsAuxCtlVecFactory< MODEL >::getMakers().
ObsAuxCtlVecFactory()
template<typename MODEL > oops::ObsAuxCtlVecFactory< MODEL >::ObsAuxCtlVecFactory (const std::string & name) explicit protected
Definition at line 127 of file ObsAuxCtlVecBase.h.
{
   if (getMakers().find(name) != getMakers().end()) {
     Log::error() << name << " already registered in ObsAuxCtlVecFactory."
                  << std::endl;
     ABORT("Element already registered in ObsAuxCtlVecFactory.");
   }
   getMakers()[name] = this;
 }
References ABORT.
Member Function Documentation
create()
template<typename MODEL > ObsAuxCtlVecBase< MODEL > * oops::ObsAuxCtlVecFactory< MODEL >::create (const ObsAuxCovarianceBase_ & cov) static
Definition at line 139 of file ObsAuxCtlVecBase.h.
{
   const std::string id = cov.config().getString("type");
   typename std::map<std::string, ObsAuxCtlVecFactory<MODEL> *>::iterator jloc =
       getMakers().find(id);
   if (jloc == getMakers().end()) {
     Log::error() << id << " does not exist in ObsAuxCtlVecFactory."
                  << std::endl;
     ABORT("Element does not exist in ObsAuxCtlVecFactory.");
   }
   ObsAuxCtlVecBase<MODEL> *ptr = jloc->second->make(cov);
   return ptr;
 }
References ABORT, and oops::ObsAuxCovarianceBase< MODEL >::config().
getMakers()
template<typename MODEL > static std::map<std::string, ObsAuxCtlVecFactory<MODEL> *>& oops::ObsAuxCtlVecFactory< MODEL >::getMakers () inline static private
Definition at line 104 of file ObsAuxCtlVecBase.h.
{
     static std::map<std::string, ObsAuxCtlVecFactory<MODEL> *> makers_;
     return makers_;
   }
Referenced by oops::ObsAuxCtlVecFactory< MODEL >::~ObsAuxCtlVecFactory().
make()
template<typename MODEL > virtual ObsAuxCtlVecBase<MODEL>* oops::ObsAuxCtlVecFactory< MODEL >::make (const ObsAuxCovarianceBase_ &) private pure virtual
Implemented in oops::ObsAuxCtlVecMaker< MODEL, T >.
The documentation for this class was generated from the following file:
src/oops/interface/ObsAuxCtlVecBase.h