OOPS Documentation: oops::ModelAuxCtlVec< MODEL > Class Template Reference
oops::ModelAuxCtlVec< MODEL > Class Template Reference
#include <ModelAuxCtlVec.h>
Public Member Functions
ModelAuxCtlVec (const ModelAuxCovariance_ &)
Constructor (using Covariance)
ModelAuxCtlVec (const ModelAuxCovariance_ &, const ModelAuxCtlVec &)
Constructor (using Covariance with copy initialization)
ModelAuxCtlVec (const ModelAuxCtlVec &, const bool copy=true)
Copy constructor.
~ModelAuxCtlVec ()
Destructor.
const ModelAuxCtlVec_ & modelAuxCtlVec () const
Return a constant reference to the encapsulated model specific object.
ModelAuxCtlVec_ & modelAuxCtlVec ()
Return a reference to the encapsulated model specific object.
void zero ()
\(dv_1 = 0 \)
ModelAuxCtlVec & operator= (const ModelAuxCtlVec &)
\(dv_1 = dv_2 \)
ModelAuxCtlVec & operator+= (const ModelAuxCtlVec &)
\(dv_1 = dv_1 + dv_2 \)
ModelAuxCtlVec & operator-= (const ModelAuxCtlVec &)
\(dv_1 = dv_1 - dv_2 \)
ModelAuxCtlVec & operator*= (const double &)
\(dv_1 = dv_1 * c \)
void axpy (const double &, const ModelAuxCtlVec &)
\(dv_1 = dv_1 * c dv_2 \)
double dot_product_with (const ModelAuxCtlVec &) const
\(<dv_1,dv_1> = dv_1^T dv_1 \)
void read (const eckit::Configuration &)
Read control vector.
void write (const eckit::Configuration &) const
Write control vector.
double norm () const
L-2 norm.
Static Public Member Functions
static const std::string classname ()
Private Types
using ModelAuxCtlVec_ = typename MODEL::ModelAuxCtlVec
using ModelAuxCovariance_ = typename MODEL::ModelAuxCovariance
using ModelAuxControl_ = ModelAuxControl< MODEL >
Private Member Functions
void print (std::ostream &) const
Private Attributes
std::unique_ptr< ModelAuxCtlVec_ > aux_
Pointer to the model specific object.
Detailed Description
template<typename MODEL>
class oops::ModelAuxCtlVec< MODEL >
Encapsulates the auxiliary model space component of ControlVector
Part of the control vector corresponding to the ModelAuxIncrement part of ControlIncrement. The structure of ModelAuxCovariances determines the size of ModelAuxCtlVec.
Definition at line 42 of file ModelAuxCtlVec.h.
Member Typedef Documentation
ModelAuxControl_
template<typename MODEL > using oops::ModelAuxCtlVec< MODEL >::ModelAuxControl_ = ModelAuxControl<MODEL> private
Definition at line 46 of file ModelAuxCtlVec.h.
ModelAuxCovariance_
template<typename MODEL > using oops::ModelAuxCtlVec< MODEL >::ModelAuxCovariance_ = typename MODEL::ModelAuxCovariance private
Definition at line 45 of file ModelAuxCtlVec.h.
ModelAuxCtlVec_
template<typename MODEL > using oops::ModelAuxCtlVec< MODEL >::ModelAuxCtlVec_ = typename MODEL::ModelAuxCtlVec private
Definition at line 44 of file ModelAuxCtlVec.h.
Constructor & Destructor Documentation
ModelAuxCtlVec() [1/3]
template<typename MODEL > oops::ModelAuxCtlVec< MODEL >::ModelAuxCtlVec (const ModelAuxCovariance_ & cov)
Constructor (using Covariance)
Definition at line 99 of file ModelAuxCtlVec.h.
                                                                     : aux_() {
   Log::trace() << "ModelAuxCtlVec<MODEL>::ModelAuxCtlVec starting" << std::endl;
   util::Timer timer(classname(), "ModelAuxCtlVec");
   aux_.reset(new ModelAuxCtlVec_(cov));
   Log::trace() << "ModelAuxCtlVec<MODEL>::ModelAuxCtlVec done" << std::endl;
 }
References oops::ModelAuxCtlVec< MODEL >::aux_, and oops::ModelAuxCtlVec< MODEL >::classname().
ModelAuxCtlVec() [2/3]
template<typename MODEL > oops::ModelAuxCtlVec< MODEL >::ModelAuxCtlVec (const ModelAuxCovariance_ & cov, const ModelAuxCtlVec< MODEL > & other)
Constructor (using Covariance with copy initialization)
Definition at line 107 of file ModelAuxCtlVec.h.
     : aux_() {
   Log::trace() << "ModelAuxCtlVec<MODEL>::ModelAuxCtlVec interpolated starting"
                << std::endl;
   util::Timer timer(classname(), "ModelAuxCtlVec");
   aux_.reset(new ModelAuxCtlVec_(cov, *other.aux_));
   Log::trace() << "ModelAuxCtlVec<MODEL>::ModelAuxCtlVec interpolated done"
                << std::endl;
 }
References oops::ModelAuxCtlVec< MODEL >::aux_, and oops::ModelAuxCtlVec< MODEL >::classname().
ModelAuxCtlVec() [3/3]
template<typename MODEL > oops::ModelAuxCtlVec< MODEL >::ModelAuxCtlVec (const ModelAuxCtlVec< MODEL > & other, const bool copy = true)
Copy constructor.
Definition at line 119 of file ModelAuxCtlVec.h.
     : aux_() {
   Log::trace() << "ModelAuxCtlVec<MODEL>::ModelAuxCtlVec copy starting"
                << std::endl;
   util::Timer timer(classname(), "ModelAuxCtlVec");
   aux_.reset(new ModelAuxCtlVec_(*other.aux_, copy));
   Log::trace() << "ModelAuxCtlVec<MODEL>::ModelAuxCtlVec copy done"
                << std::endl;
 }
References oops::ModelAuxCtlVec< MODEL >::aux_, and oops::ModelAuxCtlVec< MODEL >::classname().
~ModelAuxCtlVec()
template<typename MODEL > oops::ModelAuxCtlVec< MODEL >::~ModelAuxCtlVec
Destructor.
Definition at line 131 of file ModelAuxCtlVec.h.
{
   Log::trace() << "ModelAuxCtlVec<MODEL>::~ModelAuxCtlVec starting"
                << std::endl;
   util::Timer timer(classname(), "~ModelAuxCtlVec");
   aux_.reset();
   Log::trace() << "ModelAuxCtlVec<MODEL>::~ModelAuxCtlVec done" << std::endl;
 }
Member Function Documentation
axpy()
template<typename MODEL > void oops::ModelAuxCtlVec< MODEL >::axpy (const double & zz, const ModelAuxCtlVec< MODEL > & dx)
\(dv_1 = dv_1 * c dv_2 \)
Definition at line 187 of file ModelAuxCtlVec.h.
{
   Log::trace() << "ModelAuxCtlVec<MODEL>::axpy starting" << std::endl;
   util::Timer timer(classname(), "axpy");
   aux_->axpy(zz, *dx.aux_);
   Log::trace() << "ModelAuxCtlVec<MODEL>::axpy done" << std::endl;
 }
References oops::ModelAuxCtlVec< MODEL >::aux_.
classname()
template<typename MODEL > static const std::string oops::ModelAuxCtlVec< MODEL >::classname () inline static
Definition at line 49 of file ModelAuxCtlVec.h.
 { return "oops::ModelAuxCtlVec"; }
Referenced by oops::ModelAuxCtlVec< MODEL >::ModelAuxCtlVec().
dot_product_with()
template<typename MODEL > double oops::ModelAuxCtlVec< MODEL >::dot_product_with (const ModelAuxCtlVec< MODEL > & dx) const
\(<dv_1,dv_1> = dv_1^T dv_1 \)
Definition at line 195 of file ModelAuxCtlVec.h.
{
   Log::trace() << "ModelAuxCtlVec<MODEL>::dot_product_with starting"
                << std::endl;
   util::Timer timer(classname(), "dot_product_with");
   double zz = aux_->dot_product_with(*dx.aux_);
   Log::trace() << "ModelAuxCtlVec<MODEL>::dot_product_with done" << std::endl;
   return zz;
 }
References oops::ModelAuxCtlVec< MODEL >::aux_.
modelAuxCtlVec() [1/2]
template<typename MODEL > ModelAuxCtlVec_& oops::ModelAuxCtlVec< MODEL >::modelAuxCtlVec () inline
Return a reference to the encapsulated model specific object.
Definition at line 64 of file ModelAuxCtlVec.h.
 { return *aux_; }
References oops::ModelAuxCtlVec< MODEL >::aux_.
modelAuxCtlVec() [2/2]
template<typename MODEL > const ModelAuxCtlVec_& oops::ModelAuxCtlVec< MODEL >::modelAuxCtlVec () const inline
Return a constant reference to the encapsulated model specific object.
Definition at line 62 of file ModelAuxCtlVec.h.
 { return *aux_; }
References oops::ModelAuxCtlVec< MODEL >::aux_.
Referenced by oops::ModelAuxCovariance< MODEL >::multiplySqrt(), and oops::ModelAuxCovariance< MODEL >::multiplySqrtTrans().
norm()
template<typename MODEL > double oops::ModelAuxCtlVec< MODEL >::norm
L-2 norm.
Definition at line 221 of file ModelAuxCtlVec.h.
{
   Log::trace() << "ModelAuxCtlVec<MODEL>::norm starting" << std::endl;
   util::Timer timer(classname(), "norm");
   double zz = aux_->norm();
   Log::trace() << "ModelAuxCtlVec<MODEL>::norm done" << std::endl;
   return zz;
 }
operator*=()
template<typename MODEL > ModelAuxCtlVec< MODEL > & oops::ModelAuxCtlVec< MODEL >::operator*= (const double & zz)
\(dv_1 = dv_1 * c \)
Definition at line 178 of file ModelAuxCtlVec.h.
{
   Log::trace() << "ModelAuxCtlVec<MODEL>::operator*= starting" << std::endl;
   util::Timer timer(classname(), "operator*=");
   *aux_ *= zz;
   Log::trace() << "ModelAuxCtlVec<MODEL>::operator*= done" << std::endl;
   return *this;
 }
operator+=()
template<typename MODEL > ModelAuxCtlVec< MODEL > & oops::ModelAuxCtlVec< MODEL >::operator+= (const ModelAuxCtlVec< MODEL > & rhs)
\(dv_1 = dv_1 + dv_2 \)
Definition at line 158 of file ModelAuxCtlVec.h.
{
   Log::trace() << "ModelAuxCtlVec<MODEL>::operator+= starting" << std::endl;
   util::Timer timer(classname(), "operator+=");
   *aux_ += *rhs.aux_;
   Log::trace() << "ModelAuxCtlVec<MODEL>::operator+= done" << std::endl;
   return *this;
 }
References oops::ModelAuxCtlVec< MODEL >::aux_.
operator-=()
template<typename MODEL > ModelAuxCtlVec< MODEL > & oops::ModelAuxCtlVec< MODEL >::operator-= (const ModelAuxCtlVec< MODEL > & rhs)
\(dv_1 = dv_1 - dv_2 \)
Definition at line 168 of file ModelAuxCtlVec.h.
{
   Log::trace() << "ModelAuxCtlVec<MODEL>::operator-= starting" << std::endl;
   util::Timer timer(classname(), "operator-=");
   *aux_ -= *rhs.aux_;
   Log::trace() << "ModelAuxCtlVec<MODEL>::operator-= done" << std::endl;
   return *this;
 }
References oops::ModelAuxCtlVec< MODEL >::aux_.
operator=()
template<typename MODEL > ModelAuxCtlVec< MODEL > & oops::ModelAuxCtlVec< MODEL >::operator= (const ModelAuxCtlVec< MODEL > & rhs)
\(dv_1 = dv_2 \)
Definition at line 148 of file ModelAuxCtlVec.h.
{
   Log::trace() << "ModelAuxCtlVec<MODEL>::operator= starting" << std::endl;
   util::Timer timer(classname(), "operator=");
   *aux_ = *rhs.aux_;
   Log::trace() << "ModelAuxCtlVec<MODEL>::operator= done" << std::endl;
   return *this;
 }
References oops::ModelAuxCtlVec< MODEL >::aux_.
print()
template<typename MODEL > void oops::ModelAuxCtlVec< MODEL >::print (std::ostream & os) const private
Definition at line 230 of file ModelAuxCtlVec.h.
{
   Log::trace() << "ModelAuxCtlVec<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   os << *aux_;
   Log::trace() << "ModelAuxCtlVec<MODEL>::print done" << std::endl;
 }
read()
template<typename MODEL > void oops::ModelAuxCtlVec< MODEL >::read (const eckit::Configuration & conf)
Read control vector.
Definition at line 205 of file ModelAuxCtlVec.h.
{
   Log::trace() << "ModelAuxCtlVec<MODEL>::read starting" << std::endl;
   util::Timer timer(classname(), "read");
   aux_->read(conf.getSubConfiguration("ctlvecModAux"));
   Log::trace() << "ModelAuxCtlVec<MODEL>::read done" << std::endl;
 }
write()
template<typename MODEL > void oops::ModelAuxCtlVec< MODEL >::write (const eckit::Configuration & conf) const
Write control vector.
Definition at line 213 of file ModelAuxCtlVec.h.
{
   Log::trace() << "ModelAuxCtlVec<MODEL>::write starting" << std::endl;
   util::Timer timer(classname(), "write");
   aux_->write(conf.getSubConfiguration("ctlvecModAux"));
   Log::trace() << "ModelAuxCtlVec<MODEL>::write done" << std::endl;
 }
zero()
template<typename MODEL > void oops::ModelAuxCtlVec< MODEL >::zero
\(dv_1 = 0 \)
Definition at line 140 of file ModelAuxCtlVec.h.
{
   Log::trace() << "ModelAuxCtlVec<MODEL>::zero starting" << std::endl;
   util::Timer timer(classname(), "zero");
   aux_->zero();
   Log::trace() << "ModelAuxCtlVec<MODEL>::zero done" << std::endl;
 }
Member Data Documentation
aux_
template<typename MODEL > std::unique_ptr<ModelAuxCtlVec_> oops::ModelAuxCtlVec< MODEL >::aux_ private
Pointer to the model specific object.
Definition at line 94 of file ModelAuxCtlVec.h.
Referenced by oops::ModelAuxCtlVec< MODEL >::axpy(), oops::ModelAuxCtlVec< MODEL >::dot_product_with(), oops::ModelAuxCtlVec< MODEL >::ModelAuxCtlVec(), oops::ModelAuxCtlVec< MODEL >::modelAuxCtlVec(), oops::ModelAuxCtlVec< MODEL >::operator+=(), oops::ModelAuxCtlVec< MODEL >::operator-=(), and oops::ModelAuxCtlVec< MODEL >::operator=().
The documentation for this class was generated from the following file:
src/oops/interface/ModelAuxCtlVec.h