OOPS Documentation: oops::DualConfigModelAuxControl< MODEL > Class Template Reference
oops::DualConfigModelAuxControl< MODEL > Class Template Reference
#include <DualConfigModelAuxControl.h>
Public Member Functions
DualConfigModelAuxControl (const DualConfigGeometry_ &, const DualConfigModel_ &, const eckit::Configuration &)
DualConfigModelAuxControl (const DualConfigGeometry_ &, const DualConfigModelAuxControl &)
DualConfigModelAuxControl (const DualConfigModelAuxControl &, const bool copy=true)
~DualConfigModelAuxControl ()
const ModelAuxControl_ & modelauxcontrol1 () const
Interfacing.
ModelAuxControl_ & modelauxcontrol1 ()
const ModelAuxControl_ & modelauxcontrol2 () const
ModelAuxControl_ & modelauxcontrol2 ()
void read (const eckit::Configuration &)
I/O and diagnostics.
void write (const eckit::Configuration &) const
double norm () const
Static Public Member Functions
static const std::string classname ()
Private Types
using DualConfigModelAuxControl_ = DualConfigModelAuxControl< MODEL >
using DualConfigGeometry_ = DualConfigGeometry< MODEL >
using DualConfigModel_ = DualConfigModel< MODEL >
using ModelAuxControl_ = ModelAuxControl< MODEL >
using Geometry_ = Geometry< MODEL >
Private Member Functions
DualConfigModelAuxControl & operator= (const DualConfigModelAuxControl &)
void print (std::ostream &) const
Private Attributes
std::unique_ptr< ModelAuxControl_ > aux1_
std::unique_ptr< ModelAuxControl_ > aux2_
Detailed Description
template<typename MODEL>
class oops::DualConfigModelAuxControl< MODEL >
Definition at line 40 of file DualConfigModelAuxControl.h.
Member Typedef Documentation
DualConfigGeometry_
template<typename MODEL > using oops::DualConfigModelAuxControl< MODEL >::DualConfigGeometry_ = DualConfigGeometry<MODEL> private
Definition at line 44 of file DualConfigModelAuxControl.h.
DualConfigModel_
template<typename MODEL > using oops::DualConfigModelAuxControl< MODEL >::DualConfigModel_ = DualConfigModel<MODEL> private
Definition at line 45 of file DualConfigModelAuxControl.h.
DualConfigModelAuxControl_
template<typename MODEL > using oops::DualConfigModelAuxControl< MODEL >::DualConfigModelAuxControl_ = DualConfigModelAuxControl<MODEL> private
Definition at line 43 of file DualConfigModelAuxControl.h.
Geometry_
template<typename MODEL > using oops::DualConfigModelAuxControl< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 47 of file DualConfigModelAuxControl.h.
ModelAuxControl_
template<typename MODEL > using oops::DualConfigModelAuxControl< MODEL >::ModelAuxControl_ = ModelAuxControl<MODEL> private
Definition at line 46 of file DualConfigModelAuxControl.h.
Constructor & Destructor Documentation
DualConfigModelAuxControl() [1/3]
template<typename MODEL > oops::DualConfigModelAuxControl< MODEL >::DualConfigModelAuxControl (const DualConfigGeometry_ & resol, const DualConfigModel_ & model, const eckit::Configuration & conf)
Definition at line 85 of file DualConfigModelAuxControl.h.
     : aux1_(), aux2_() {
   Log::trace() << classname() << "::DualConfigModelAuxControl starting"
                << std::endl;
   util::Timer timer(classname(), "DualConfigModelAuxControl");
   Log::debug() << "Full config is:" << conf << std::endl;
   eckit::LocalConfiguration conf1(conf, "state1");
   aux1_.reset(new ModelAuxControl_(resol.geometry1(), model.model1(), conf1));
   eckit::LocalConfiguration conf2(conf, "state2");
   aux2_.reset(new ModelAuxControl_(resol.geometry2(), model.model2(), conf2));
   Log::trace() << classname() << "::DualConfigModelAuxControl done"
                << std::endl;
 }
References oops::DualConfigModelAuxControl< MODEL >::aux1_, oops::DualConfigModelAuxControl< MODEL >::aux2_, oops::DualConfigModelAuxControl< MODEL >::classname(), oops::DualConfigGeometry< MODEL >::geometry1(), oops::DualConfigGeometry< MODEL >::geometry2(), oops::DualConfigModel< MODEL >::model1(), and oops::DualConfigModel< MODEL >::model2().
DualConfigModelAuxControl() [2/3]
template<typename MODEL > oops::DualConfigModelAuxControl< MODEL >::DualConfigModelAuxControl (const DualConfigGeometry_ & resol, const DualConfigModelAuxControl< MODEL > & other)
Definition at line 104 of file DualConfigModelAuxControl.h.
     : aux1_(), aux2_() {
   Log::trace() << classname()
                << "::DualConfigModelAuxControl interpolated starting"
                << std::endl;
   util::Timer timer(classname(), "DualConfigModelAuxControl");
   aux1_.reset(new ModelAuxControl_(resol.geometry1(), *other.aux1_));
   aux2_.reset(new ModelAuxControl_(resol.geometry2(), *other.aux2_));
   Log::trace() << classname() << "::DualConfigModelAuxControl interpolated done"
                << std::endl;
 }
References oops::DualConfigModelAuxControl< MODEL >::aux1_, oops::DualConfigModelAuxControl< MODEL >::aux2_, oops::DualConfigModelAuxControl< MODEL >::classname(), oops::DualConfigGeometry< MODEL >::geometry1(), and oops::DualConfigGeometry< MODEL >::geometry2().
DualConfigModelAuxControl() [3/3]
template<typename MODEL > oops::DualConfigModelAuxControl< MODEL >::DualConfigModelAuxControl (const DualConfigModelAuxControl< MODEL > & other, const bool copy = true) explicit
Definition at line 120 of file DualConfigModelAuxControl.h.
     : aux1_(), aux2_() {
   Log::trace() << classname() << "::DualConfigModelAuxControl copy starting"
                << std::endl;
   util::Timer timer(classname(), "DualConfigModelAuxControl");
   aux1_.reset(new ModelAuxControl_(*other.aux1_, copy));
   aux2_.reset(new ModelAuxControl_(*other.aux2_, copy));
   Log::trace() << classname() << "::DualConfigModelAuxControl copy done"
                << std::endl;
 }
References oops::DualConfigModelAuxControl< MODEL >::aux1_, oops::DualConfigModelAuxControl< MODEL >::aux2_, and oops::DualConfigModelAuxControl< MODEL >::classname().
~DualConfigModelAuxControl()
template<typename MODEL > oops::DualConfigModelAuxControl< MODEL >::~DualConfigModelAuxControl
Definition at line 135 of file DualConfigModelAuxControl.h.
{
   Log::trace() << classname() << "::~DualConfigModelAuxControl starting"
                << std::endl;
   util::Timer timer(classname(), "~DualConfigModelAuxControl");
   aux1_.reset();
   aux2_.reset();
   Log::trace() << classname() << "::~DualConfigModelAuxControl done"
                << std::endl;
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::DualConfigModelAuxControl< MODEL >::classname () inline static
Definition at line 50 of file DualConfigModelAuxControl.h.
{
     return "oops::DualConfigModelAuxControl";
   }
Referenced by oops::DualConfigModelAuxControl< MODEL >::DualConfigModelAuxControl().
modelauxcontrol1() [1/2]
template<typename MODEL > ModelAuxControl_& oops::DualConfigModelAuxControl< MODEL >::modelauxcontrol1 () inline
Definition at line 65 of file DualConfigModelAuxControl.h.
 { return *aux1_; }
References oops::DualConfigModelAuxControl< MODEL >::aux1_.
modelauxcontrol1() [2/2]
template<typename MODEL > const ModelAuxControl_& oops::DualConfigModelAuxControl< MODEL >::modelauxcontrol1 () const inline
Interfacing.
Definition at line 64 of file DualConfigModelAuxControl.h.
 { return *aux1_; }
References oops::DualConfigModelAuxControl< MODEL >::aux1_.
Referenced by oops::DualConfigModel< MODEL >::initialize(), and oops::DualConfigModel< MODEL >::step().
modelauxcontrol2() [1/2]
template<typename MODEL > ModelAuxControl_& oops::DualConfigModelAuxControl< MODEL >::modelauxcontrol2 () inline
Definition at line 67 of file DualConfigModelAuxControl.h.
 { return *aux2_; }
References oops::DualConfigModelAuxControl< MODEL >::aux2_.
modelauxcontrol2() [2/2]
template<typename MODEL > const ModelAuxControl_& oops::DualConfigModelAuxControl< MODEL >::modelauxcontrol2 () const inline
Definition at line 66 of file DualConfigModelAuxControl.h.
 { return *aux2_; }
References oops::DualConfigModelAuxControl< MODEL >::aux2_.
Referenced by oops::DualConfigModel< MODEL >::initialize(), and oops::DualConfigModel< MODEL >::step().
norm()
template<typename MODEL > double oops::DualConfigModelAuxControl< MODEL >::norm
Definition at line 177 of file DualConfigModelAuxControl.h.
{
   Log::trace() << classname() << "::norm starting" << std::endl;
   util::Timer timer(classname(), "norm");
   double zz = aux1_->norm();
   zz += aux2_->norm();
   Log::trace() << classname() << "::norm done" << std::endl;
   return zz;
 }
operator=()
template<typename MODEL > DualConfigModelAuxControl& oops::DualConfigModelAuxControl< MODEL >::operator= (const DualConfigModelAuxControl< MODEL > &) private
print()
template<typename MODEL > void oops::DualConfigModelAuxControl< MODEL >::print (std::ostream & os) const private
Definition at line 189 of file DualConfigModelAuxControl.h.
{
   Log::trace() << classname() << "::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   os << *aux1_;
   os << *aux2_;
   Log::trace() << classname() << "::print done" << std::endl;
 }
read()
template<typename MODEL > void oops::DualConfigModelAuxControl< MODEL >::read (const eckit::Configuration & conf)
I/O and diagnostics.
Definition at line 148 of file DualConfigModelAuxControl.h.
{
   Log::trace() << classname() << "::read starting" << std::endl;
   util::Timer timer(classname(), "read");
   Log::debug() << "Full config is:" << conf << std::endl;
   eckit::LocalConfiguration conf1(conf, "model1");
   aux1_->read(conf1);
   eckit::LocalConfiguration conf2(conf, "model2");
   aux1_->read(conf2);
   Log::trace() << classname() << "::read done" << std::endl;
 }
write()
template<typename MODEL > void oops::DualConfigModelAuxControl< MODEL >::write (const eckit::Configuration & conf) const
Definition at line 162 of file DualConfigModelAuxControl.h.
{
   Log::trace() << classname() << "::write starting" << std::endl;
   util::Timer timer(classname(), "write");
   Log::debug() << "Full config is:" << conf << std::endl;
   eckit::LocalConfiguration conf1(conf, "model1");
   aux1_->write(conf1);
   eckit::LocalConfiguration conf2(conf, "model2");
   aux2_->write(conf2);
   Log::trace() << classname() << "::write done" << std::endl;
 }
Member Data Documentation
aux1_
template<typename MODEL > std::unique_ptr<ModelAuxControl_> oops::DualConfigModelAuxControl< MODEL >::aux1_ private
Definition at line 78 of file DualConfigModelAuxControl.h.
Referenced by oops::DualConfigModelAuxControl< MODEL >::DualConfigModelAuxControl(), and oops::DualConfigModelAuxControl< MODEL >::modelauxcontrol1().
aux2_
template<typename MODEL > std::unique_ptr<ModelAuxControl_> oops::DualConfigModelAuxControl< MODEL >::aux2_ private
Definition at line 79 of file DualConfigModelAuxControl.h.
Referenced by oops::DualConfigModelAuxControl< MODEL >::DualConfigModelAuxControl(), and oops::DualConfigModelAuxControl< MODEL >::modelauxcontrol2().
The documentation for this class was generated from the following file:
src/oops/generic/DualConfigModelAuxControl.h