OOPS Documentation: oops::MMatrix< MODEL > Class Template Reference
oops::MMatrix< MODEL > Class Template Reference
The \(M \) matrix.
#include <MMatrix.h>
Public Member Functions
MMatrix (const CostFct_ &j)
void multiply (CtrlInc_ &dx, PostProcessor< Increment_ > post=PostProcessor< Increment_ >()) const
Private Types
using CtrlInc_ = ControlIncrement< MODEL >
using CostFct_ = CostFunction< MODEL >
using Increment_ = Increment< MODEL >
Private Attributes
CostFct_ const & j_
Detailed Description
template<typename MODEL>
class oops::MMatrix< MODEL >
The \(M \) matrix.
The solvers represent matrices as objects that implement a "multiply" method. This class defines objects that apply a linear model \(M \) matrix
Definition at line 33 of file MMatrix.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::MMatrix< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 35 of file MMatrix.h.
CtrlInc_
template<typename MODEL > using oops::MMatrix< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 34 of file MMatrix.h.
Increment_
template<typename MODEL > using oops::MMatrix< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 36 of file MMatrix.h.
Constructor & Destructor Documentation
MMatrix()
template<typename MODEL > oops::MMatrix< MODEL >::MMatrix (const CostFct_ & j) inline explicit
Definition at line 39 of file MMatrix.h.
 : j_(j) {}
Member Function Documentation
multiply()
template<typename MODEL > void oops::MMatrix< MODEL >::multiply (CtrlInc_ & dx, PostProcessor< Increment_ > post = PostProcessor<Increment_>()) const inline
Definition at line 41 of file MMatrix.h.
{
     PostProcessorTL<Increment_> cost;
     j_.runTL(dx, cost, post, false);
   }
References oops::MMatrix< MODEL >::j_, and oops::CostFunction< MODEL >::runTL().
Referenced by oops::Minimizer< MODEL >::adjModelTest(), oops::Minimizer< MODEL >::tlmApproxTest(), oops::Minimizer< MODEL >::tlmPropagTest(), and oops::Minimizer< MODEL >::tlmTaylorTest().
Member Data Documentation
j_
template<typename MODEL > CostFct_ const& oops::MMatrix< MODEL >::j_ private
Definition at line 48 of file MMatrix.h.
Referenced by oops::MMatrix< MODEL >::multiply().
The documentation for this class was generated from the following file:
src/oops/assimilation/MMatrix.h