OOPS Documentation: oops::DualConfigGeometry< MODEL > Class Template Reference
oops::DualConfigGeometry< MODEL > Class Template Reference
#include <DualConfigGeometry.h>
Public Member Functions
DualConfigGeometry (const eckit::Configuration &)
DualConfigGeometry (const DualConfigGeometry &)
~DualConfigGeometry ()
const Geometry_ & geometry1 () const
Interfacing.
const Geometry_ & geometry2 () const
Static Public Member Functions
static const std::string classname ()
Private Types
using Geometry_ = Geometry< MODEL >
Private Member Functions
void print (std::ostream &) const
Private Attributes
std::shared_ptr< const Geometry_ > geom1_
std::shared_ptr< const Geometry_ > geom2_
Detailed Description
template<typename MODEL>
class oops::DualConfigGeometry< MODEL >
Definition at line 34 of file DualConfigGeometry.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::DualConfigGeometry< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 37 of file DualConfigGeometry.h.
Constructor & Destructor Documentation
DualConfigGeometry() [1/2]
template<typename MODEL > oops::DualConfigGeometry< MODEL >::DualConfigGeometry (const eckit::Configuration & conf) explicit
Definition at line 60 of file DualConfigGeometry.h.
     : geom1_(), geom2_() {
   Log::trace() << "DualConfigGeometry<MODELS>::DualConfigGeometry starting"
                << std::endl;
   util::Timer timer(classname(), "DualConfigGeometry");
   Log::debug() << "Full config is:" << conf << std::endl;
   eckit::LocalConfiguration conf1(conf, "resolution1");
   geom1_.reset(new Geometry_(conf1));
   eckit::LocalConfiguration conf2(conf, "resolution2");
   geom2_.reset(new Geometry_(conf2));
   Log::trace() << "DualConfigGeometry<MODELS>::DualConfigGeometry done"
                << std::endl;
 }
References oops::DualConfigGeometry< MODEL >::classname(), oops::DualConfigGeometry< MODEL >::geom1_, and oops::DualConfigGeometry< MODEL >::geom2_.
DualConfigGeometry() [2/2]
template<typename MODEL > oops::DualConfigGeometry< MODEL >::DualConfigGeometry (const DualConfigGeometry< MODEL > & other)
Definition at line 77 of file DualConfigGeometry.h.
{
   Log::trace() << "DualConfigGeometry<MODELS>::DualConfigGeometry copy starting"
                << std::endl;
   util::Timer timer(classname(), "DualConfigGeometry");
   geom1_(other.geom1_);
   geom2_(other.geom2_);
   Log::trace() << "DualConfigGeometry<MODELS>::DualConfigGeometry copy done"
                << std::endl;
 }
References oops::DualConfigGeometry< MODEL >::geom1_, and oops::DualConfigGeometry< MODEL >::geom2_.
~DualConfigGeometry()
template<typename MODEL > oops::DualConfigGeometry< MODEL >::~DualConfigGeometry
Definition at line 90 of file DualConfigGeometry.h.
{
   Log::trace() << "DualConfigGeometry<MODELS>::~DualConfigGeometry starting"
                << std::endl;
   util::Timer timer(classname(), "~DualConfigGeometry");
   geom1_.reset();
   geom2_.reset();
   Log::trace() << "DualConfigGeometry<MODELS>::~DualConfigGeometry done"
                << std::endl;
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::DualConfigGeometry< MODEL >::classname () inline static
Definition at line 40 of file DualConfigGeometry.h.
 { return "oops::DualConfigGeometry"; }
Referenced by oops::DualConfigGeometry< MODEL >::DualConfigGeometry().
geometry1()
template<typename MODEL > const Geometry_& oops::DualConfigGeometry< MODEL >::geometry1 () const inline
Interfacing.
Definition at line 47 of file DualConfigGeometry.h.
 { return *geom1_; }
References oops::DualConfigGeometry< MODEL >::geom1_.
Referenced by oops::DualConfigModel< MODEL >::DualConfigModel(), oops::DualConfigModelAuxControl< MODEL >::DualConfigModelAuxControl(), and oops::DualConfigState< MODEL >::DualConfigState().
geometry2()
template<typename MODEL > const Geometry_& oops::DualConfigGeometry< MODEL >::geometry2 () const inline
Definition at line 48 of file DualConfigGeometry.h.
 { return *geom2_; }
References oops::DualConfigGeometry< MODEL >::geom2_.
Referenced by oops::DualConfigModel< MODEL >::DualConfigModel(), oops::DualConfigModelAuxControl< MODEL >::DualConfigModelAuxControl(), and oops::DualConfigState< MODEL >::DualConfigState().
print()
template<typename MODEL > void oops::DualConfigGeometry< MODEL >::print (std::ostream & os) const private
Definition at line 103 of file DualConfigGeometry.h.
{
   Log::trace() << "DualConfigGeometry<MODELS>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   os << *geom1_;
   os << *geom2_;
   Log::trace() << "DualConfigGeometry<MODELS>::print done" << std::endl;
 }
Member Data Documentation
geom1_
template<typename MODEL > std::shared_ptr<const Geometry_> oops::DualConfigGeometry< MODEL >::geom1_ private
Definition at line 53 of file DualConfigGeometry.h.
Referenced by oops::DualConfigGeometry< MODEL >::DualConfigGeometry(), and oops::DualConfigGeometry< MODEL >::geometry1().
geom2_
template<typename MODEL > std::shared_ptr<const Geometry_> oops::DualConfigGeometry< MODEL >::geom2_ private
Definition at line 54 of file DualConfigGeometry.h.
Referenced by oops::DualConfigGeometry< MODEL >::DualConfigGeometry(), and oops::DualConfigGeometry< MODEL >::geometry2().
The documentation for this class was generated from the following file:
src/oops/generic/DualConfigGeometry.h