OOPS Documentation: oops::ObservationSpace< MODEL > Class Template Reference
oops::ObservationSpace< MODEL > Class Template Reference
Encapsulates the observation space.
#include <ObservationSpace.h>
Public Member Functions
ObservationSpace (const eckit::Configuration &, const Geometry_ &, const util::DateTime &, const util::DateTime &, const bool lscreened=false)
Constructor.
~ObservationSpace ()
Destructor.
ObsSpace_ & observationspace () const
Return a reference to the model specific object.
const eckit::Configuration & config () const
Return a constant reference to the configuration.
const util::DateTime & windowStart () const
Assimilation window start.
const util::DateTime & windowEnd () const
Assimilation window end.
const util::Duration & windowLength () const
Assimilation window length.
void screenObservations (const ObsVector_ &, const GeoVaLs_ &) const
Perform screening.
void saveObservations () const
Save observations.
void generateDistribution (const eckit::Configuration &)
Generate observations.
void printJo (const ObsVector_ &, const ObsVector_ &) const
Print the Jo table.
Static Public Member Functions
static const std::string classname ()
Private Types
using ObsSpace_ = typename MODEL::ObsSpace
using Geometry_ = Geometry< MODEL >
using GeoVaLs_ = GeoVaLs< MODEL >
using ObsVector_ = ObsVector< MODEL >
Private Member Functions
void print (std::ostream &) const
Private Attributes
const util::DateTime winbgn_
Window start.
const util::DateTime winend_
Window end.
const util::Duration winlen_
Window length.
eckit::LocalConfiguration conf_
Configuration.
std::unique_ptr< ObsSpace_ > obsdb_
Pointer to the model specific object.
Detailed Description
template<typename MODEL>
class oops::ObservationSpace< MODEL >
Encapsulates the observation space.
ObservationSpace is a bucket for observations; ObservationSpace object can contain observations of specific observation type/types, or it can include observations of all the observation types. This information is agnostic to the OOPS control layer.
ObservationSpace is responsible for performing screening of observations.
ObservationSpaces class contains a vector of ObservationSpace objects. Refer to the documentation of CostJo class to understand the structure of the \(J_o \) term.
Definition at line 56 of file ObservationSpace.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::ObservationSpace< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 59 of file ObservationSpace.h.
GeoVaLs_
template<typename MODEL > using oops::ObservationSpace< MODEL >::GeoVaLs_ = GeoVaLs<MODEL> private
Definition at line 60 of file ObservationSpace.h.
ObsSpace_
template<typename MODEL > using oops::ObservationSpace< MODEL >::ObsSpace_ = typename MODEL::ObsSpace private
Definition at line 58 of file ObservationSpace.h.
ObsVector_
template<typename MODEL > using oops::ObservationSpace< MODEL >::ObsVector_ = ObsVector<MODEL> private
Definition at line 61 of file ObservationSpace.h.
Constructor & Destructor Documentation
ObservationSpace()
template<typename MODEL > oops::ObservationSpace< MODEL >::ObservationSpace (const eckit::Configuration & conf, const Geometry_ & geom, const util::DateTime & bgn, const util::DateTime & end, const bool lscreened = false)
Constructor.
Definition at line 111 of file ObservationSpace.h.
     : winbgn_(bgn), winend_(end), winlen_(end - bgn), conf_(conf), obsdb_() {
   Log::trace() << "ObservationSpace<MODEL>::ObservationSpace starting"
                << std::endl;
   util::Timer timer(classname(), "ObservationSpace");
   obsdb_.reset(new ObsSpace_(conf, geom.geometry(), bgn, end, lscreened));
   Log::trace() << "ObservationSpace<MODEL>::ObservationSpace done" << std::endl;
 }
References oops::ObservationSpace< MODEL >::classname(), oops::Geometry< MODEL >::geometry(), and oops::ObservationSpace< MODEL >::obsdb_.
~ObservationSpace()
template<typename MODEL > oops::ObservationSpace< MODEL >::~ObservationSpace
Destructor.
Definition at line 127 of file ObservationSpace.h.
{
   Log::trace() << "ObservationSpace<MODEL>::~ObservationSpace" << std::endl;
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::ObservationSpace< MODEL >::classname () inline static
Definition at line 64 of file ObservationSpace.h.
 { return "oops::ObservationSpace"; }
Referenced by oops::ObservationSpace< MODEL >::ObservationSpace().
config()
template<typename MODEL > const eckit::Configuration& oops::ObservationSpace< MODEL >::config () const inline
Return a constant reference to the configuration.
Definition at line 77 of file ObservationSpace.h.
 { return conf_; }
References oops::ObservationSpace< MODEL >::conf_.
Referenced by oops::ControlObsVector< MODEL >::ControlObsVector(), oops::LinearObsOperator< MODEL >::LinearObsOperator(), and oops::ObsOperator< MODEL >::ObsOperator().
generateDistribution()
template<typename MODEL > void oops::ObservationSpace< MODEL >::generateDistribution (const eckit::Configuration & conf)
Generate observations.
Definition at line 158 of file ObservationSpace.h.
{
   Log::trace() << "ObservationSpace<MODEL>::generateDistribution starting"
                << std::endl;
   util::Timer timer(classname(), "generateDistribution");
   obsdb_->generateDistribution(conf);
   Log::trace() << "ObservationSpace<MODEL>::generateDistribution done"
                << std::endl;
 }
observationspace()
template<typename MODEL > ObsSpace_& oops::ObservationSpace< MODEL >::observationspace () const inline
Return a reference to the model specific object.
Definition at line 75 of file ObservationSpace.h.
 { return *obsdb_; }
References oops::ObservationSpace< MODEL >::obsdb_.
Referenced by oops::GeoVaLs< MODEL >::GeoVaLs(), oops::LinearObsOperator< MODEL >::LinearObsOperator(), oops::Locations< MODEL >::Locations(), oops::ObsErrorMaker< MODEL, T >::make(), oops::ObsAuxControlMaker< MODEL, T >::make(), oops::ObsAuxIncrementMaker< MODEL, T >::make(), oops::ObsAuxCovarianceMaker< MODEL, T >::make(), oops::ObsOperator< MODEL >::ObsOperator(), oops::ObsVector< MODEL >::ObsVector(), and oops::ObsAuxControlBase< L95Traits >::reset().
print()
template<typename MODEL > void oops::ObservationSpace< MODEL >::print (std::ostream & os) const private
Definition at line 182 of file ObservationSpace.h.
{
   Log::trace() << "ObservationSpace<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   os << *obsdb_;
   Log::trace() << "ObservationSpace<MODEL>::print done" << std::endl;
 }
printJo()
template<typename MODEL > void oops::ObservationSpace< MODEL >::printJo (const ObsVector_ & dy, const ObsVector_ & grad) const
Print the Jo table.
Definition at line 171 of file ObservationSpace.h.
{
   Log::trace() << "ObservationSpace<MODEL>::printJo starting" << std::endl;
   util::Timer timer(classname(), "printJo");
   obsdb_->printJo(dy.obsvector(), grad.obsvector());
   Log::trace() << "ObservationSpace<MODEL>::printJo done" << std::endl;
 }
References oops::ObsVector< MODEL >::obsvector().
saveObservations()
template<typename MODEL > void oops::ObservationSpace< MODEL >::saveObservations
Save observations.
Definition at line 147 of file ObservationSpace.h.
{
   Log::trace() << "ObservationSpace<MODEL>::saveObservations starting"
                << std::endl;
   util::Timer timer(classname(), "saveObservations");
   obsdb_->saveObservations();
   Log::trace() << "ObservationSpace<MODEL>::saveObservations done" << std::endl;
 }
screenObservations()
template<typename MODEL > void oops::ObservationSpace< MODEL >::screenObservations (const ObsVector_ & dy, const GeoVaLs_ & gvals) const
Perform screening.
Definition at line 134 of file ObservationSpace.h.
{
   Log::trace() << "ObservationSpace<MODEL>::screenObservations starting"
                << std::endl;
   util::Timer timer(classname(), "screenObservations");
   obsdb_->screenObservations(dy.obsvector(), gvals.geovals());
   Log::trace() << "ObservationSpace<MODEL>::screenObservations done"
                << std::endl;
 }
References oops::GeoVaLs< MODEL >::geovals(), and oops::ObsVector< MODEL >::obsvector().
windowEnd()
template<typename MODEL > const util::DateTime& oops::ObservationSpace< MODEL >::windowEnd () const inline
Assimilation window end.
Definition at line 82 of file ObservationSpace.h.
 { return winend_; }
References oops::ObservationSpace< MODEL >::winend_.
windowLength()
template<typename MODEL > const util::Duration& oops::ObservationSpace< MODEL >::windowLength () const inline
Assimilation window length.
Definition at line 84 of file ObservationSpace.h.
 { return winlen_; }
References oops::ObservationSpace< MODEL >::winlen_.
windowStart()
template<typename MODEL > const util::DateTime& oops::ObservationSpace< MODEL >::windowStart () const inline
Assimilation window start.
Definition at line 80 of file ObservationSpace.h.
 { return winbgn_; }
References oops::ObservationSpace< MODEL >::winbgn_.
Member Data Documentation
conf_
template<typename MODEL > eckit::LocalConfiguration oops::ObservationSpace< MODEL >::conf_ private
Configuration.
Definition at line 104 of file ObservationSpace.h.
Referenced by oops::ObservationSpace< MODEL >::config().
obsdb_
template<typename MODEL > std::unique_ptr<ObsSpace_> oops::ObservationSpace< MODEL >::obsdb_ private
Pointer to the model specific object.
Definition at line 105 of file ObservationSpace.h.
Referenced by oops::ObservationSpace< MODEL >::ObservationSpace(), and oops::ObservationSpace< MODEL >::observationspace().
winbgn_
template<typename MODEL > const util::DateTime oops::ObservationSpace< MODEL >::winbgn_ private
Window start.
Definition at line 101 of file ObservationSpace.h.
Referenced by oops::ObservationSpace< MODEL >::windowStart().
winend_
template<typename MODEL > const util::DateTime oops::ObservationSpace< MODEL >::winend_ private
Window end.
Definition at line 102 of file ObservationSpace.h.
Referenced by oops::ObservationSpace< MODEL >::windowEnd().
winlen_
template<typename MODEL > const util::Duration oops::ObservationSpace< MODEL >::winlen_ private
Window length.
Definition at line 103 of file ObservationSpace.h.
Referenced by oops::ObservationSpace< MODEL >::windowLength().
The documentation for this class was generated from the following file:
src/oops/interface/ObservationSpace.h