OOPS Documentation: oops::Geometry< MODEL > Class Template Reference
oops::Geometry< MODEL > Class Template Reference
Wrapper for geometry.
#include <Geometry.h>
Public Member Functions
Geometry (const eckit::Configuration &)
Constructor.
Geometry (const Geometry &)
Copy constructor.
Geometry (std::shared_ptr< const Geometry_ >)
Copy constructor.
~Geometry ()
Destructor.
const Geometry_ & geometry () const
Interfacing - returns a constant reference to model specific geometry.
Static Public Member Functions
static const std::string classname ()
Private Types
using Geometry_ = typename MODEL::Geometry
Private Member Functions
Geometry & operator= (const Geometry &)
void print (std::ostream &) const
Private Attributes
std::shared_ptr< const Geometry_ > geom_
Detailed Description
template<typename MODEL>
class oops::Geometry< MODEL >
Wrapper for geometry.
This class holds a shared pointer to the model specific geometry object.
Definition at line 37 of file Geometry.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::Geometry< MODEL >::Geometry_ = typename MODEL::Geometry private
Definition at line 39 of file Geometry.h.
Constructor & Destructor Documentation
Geometry() [1/3]
template<typename MODEL > oops::Geometry< MODEL >::Geometry (const eckit::Configuration & conf) explicit
Constructor.
Definition at line 67 of file Geometry.h.
                                                         : geom_() {
   Log::trace() << "Geometry<MODEL>::Geometry starting" << std::endl;
   util::Timer timer(classname(), "Geometry");
   geom_.reset(new Geometry_(conf));
   Log::trace() << "Geometry<MODEL>::Geometry done" << std::endl;
 }
References oops::Geometry< MODEL >::classname(), and oops::Geometry< MODEL >::geom_.
Geometry() [2/3]
template<typename MODEL > oops::Geometry< MODEL >::Geometry (const Geometry< MODEL > & other)
Copy constructor.
Definition at line 77 of file Geometry.h.
                                                : geom_(other.geom_) {
   Log::trace() << "Geometry<MODEL>::Geometry copy done" << std::endl;
 }
Geometry() [3/3]
template<typename MODEL > oops::Geometry< MODEL >::Geometry (std::shared_ptr< const Geometry_ > ptr) explicit
Copy constructor.
Definition at line 84 of file Geometry.h.
                                                             : geom_(ptr) {
   Log::trace() << "Geometry<MODEL>::Geometry shared_ptr done" << std::endl;
 }
~Geometry()
template<typename MODEL > oops::Geometry< MODEL >::~Geometry
Destructor.
Definition at line 91 of file Geometry.h.
{
   Log::trace() << "Geometry<MODEL>::~Geometry starting" << std::endl;
   util::Timer timer(classname(), "~Geometry");
   geom_.reset();
   Log::trace() << "Geometry<MODEL>::~Geometry done" << std::endl;
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::Geometry< MODEL >::classname () inline static
Definition at line 42 of file Geometry.h.
 { return "oops::Geometry"; }
Referenced by oops::Geometry< MODEL >::Geometry().
geometry()
template<typename MODEL > const Geometry_& oops::Geometry< MODEL >::geometry () const inline
Interfacing - returns a constant reference to model specific geometry.
Definition at line 54 of file Geometry.h.
 { return *geom_; }
References oops::Geometry< MODEL >::geom_.
Referenced by oops::ErrorCovariance< MODEL >::ErrorCovariance(), oops::Increment< MODEL >::Increment(), oops::IncrEnsCtlVec< MODEL >::IncrEnsCtlVec(), oops::Interpolator< MODEL >::Interpolator(), oops::ModelAuxCovariance< MODEL >::linearize(), oops::JcCovarBase< MODEL >::linearize(), oops::ErrorCovariance< MODEL >::linearize(), oops::Localization< MODEL >::Localization(), oops::JcCovarMaker< MODEL, T >::make(), oops::LinearModelMaker< MODEL, T >::make(), oops::Model< MODEL >::Model(), oops::ModelAuxControl< MODEL >::ModelAuxControl(), oops::ModelAuxControlEstimator< MODEL >::ModelAuxControlEstimator(), oops::ModelAuxCovariance< MODEL >::ModelAuxCovariance(), oops::ModelAuxIncrement< MODEL >::ModelAuxIncrement(), oops::ObservationSpace< MODEL >::ObservationSpace(), oops::Interpolator< MODEL >::set(), and oops::State< MODEL >::State().
operator=()
template<typename MODEL > Geometry& oops::Geometry< MODEL >::operator= (const Geometry< MODEL > &) private
print()
template<typename MODEL > void oops::Geometry< MODEL >::print (std::ostream & os) const private
Definition at line 101 of file Geometry.h.
{
   Log::trace() << "Geometry<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   os << *geom_;
   Log::trace() << "Geometry<MODEL>::print done" << std::endl;
 }
Member Data Documentation
geom_
template<typename MODEL > std::shared_ptr<const Geometry_> oops::Geometry< MODEL >::geom_ private
Shared pointer to the model specific geometry
Definition at line 60 of file Geometry.h.
Referenced by oops::Geometry< MODEL >::Geometry(), and oops::Geometry< MODEL >::geometry().
The documentation for this class was generated from the following file:
src/oops/interface/Geometry.h