OOPS Documentation: oops::CostFct4DVarTrajHR< MODEL > Class Template Reference
oops::CostFct4DVarTrajHR< MODEL > Class Template Reference
4D-Var Cost Function in the ARPEGE
#include <CostFct4DVarTrajHR.h>
Public Member Functions
CostFct4DVarTrajHR (const eckit::Configuration &, const Geometry_ &, const Model_ &)
~CostFct4DVarTrajHR ()
double evaluate (const CtrlVar_ &, const eckit::Configuration &config=eckit::LocalConfiguration(), PostProcessor< State_ > post=PostProcessor< State_ >()) const override
Evaluate the non-linear cost function.
double linearize (const CtrlVar_ &, const eckit::Configuration &, PostProcessor< State_ > post=PostProcessor< State_ >()) override
Specific linearization for ARPEGE 4D-Var with trajectory from high resolution.
const double & getCostJoJc () const override
Get the JoJc cost function value.
const double & getCostJb () const override
Get the Jb cost function value.
Public Member Functions inherited from oops::CostFct4DVarMFTemplate< MODEL >
CostFct4DVarMFTemplate (const eckit::Configuration &, const Geometry_ &, const Model_ &)
~CostFct4DVarMFTemplate ()
void runTL (CtrlInc_ &, PostProcessorTL< Increment_ > &, PostProcessor< Increment_ >, const bool idModel=false) const override
Run the tangent linear model.
void runAD (CtrlInc_ &, PostProcessorAD< Increment_ > &, PostProcessor< Increment_ >, const bool idModel=false) const override
Run the adjoint model.
void zeroAD (CtrlInc_ &) const override
Nullify the increment prior to running the adjoint model.
void runNL (CtrlVar_ &xx, PostProcessor< State_ > &pp) const override
Run the non-linear model (HR)
void runNL (CtrlVar_ &, const Model_ &model, PostProcessor< State_ > &) override
Run the non-linear model (Trajectory)
Public Member Functions inherited from oops::CostFunction< MODEL >
CostFunction (const eckit::Configuration &, const Geometry_ &, const Model_ &)
Construct a cost function.
virtual ~CostFunction ()
Destroy a cost function.
void addIncrement (CtrlVar_ &, const CtrlInc_ &, PostProcessor< Increment_ > post=PostProcessor< Increment_ >()) const
Add increment to the first guess.
void resetLinearization ()
Rest the quadratic cost function.
void computeGradientFG (CtrlInc_ &) const
Compute the cost function gradient at first guess (without Jb)
double computeGradientFG (const CtrlVec_ &, CtrlInc_ &) const
Compute the cost function gradient at first guess (without Jb)
void checkpoint (eckit::LocalConfiguration &) const
Checkpoint.
void restart (const eckit::Configuration &)
Restart.
const JbTotal_ & jb () const
Access \(J_b\).
const CostBase_ & jterm (const unsigned ii) const
Access terms of the cost function other than \(J_b\).
unsigned nterms () const
Return the numer of other cost function terms \(J_o, J_c, ..\).
Private Types
using Increment_ = Increment< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using CtrlVar_ = ControlVariable< MODEL >
using CostFct_ = CostFunction< MODEL >
using Geometry_ = Geometry< MODEL >
using State_ = State< MODEL >
using Model_ = Model< MODEL >
using Variables_ = Variables< MODEL >
using Advector_ = AdvectorHandler< MODEL >
using JqTerm_ = JqTerm< MODEL >
using ObsAuxControls_ = ObsAuxControls< MODEL >
using TrajectorySaver_ = TrajectorySaverFP< MODEL >
using WeightedDiff_ = WeightedDiff< MODEL, Increment_, State_ >
using WeightedMean_ = DFIProcessor< MODEL >
Private Member Functions
void addIncr (CtrlVar_ &, const CtrlInc_ &, PostProcessor< Increment_ > &) const override
Add increment to the first guess (with FullPos change of resolution)
Private Attributes
double costJoJc_
double costJb_
const Geometry_ geom_
std::unique_ptr< Model_ > trajectoryModel_
Model that calculates the trajectory at low resolution.
std::unique_ptr< State_ > fglr_
Guess at low resolution.
std::unique_ptr< Increment_ > biasDFI_
biasDFI calculated in the first trajectory and used at the end.
Additional Inherited Members
Static Public Member Functions inherited from oops::CostFunction< MODEL >
static const std::string classname ()
Protected Member Functions inherited from oops::CostFunction< MODEL >
void setupTerms (const eckit::Configuration &)
Set up terms of the cost function \(J_b, J_q, J_o, J_c, ..\).
const Model_ & getModel () const
Access the non-linear model.
const LinearModel_ & getTLM (const unsigned isub=0) const
Access the linear model.
void recentreBackground (const eckit::Configuration &)
Re-centre the background.
CostBase_ & getJterm (const unsigned ii) const
Non const access to JTerms for linearize() method in concrete cost-functions.
JbTotal_ & getJb () const
Non const access to Jb for linearize() method in concrete cost-functions
std::vector< std::unique_ptr< LinearModel_ > > & getTLMs ()
Non const access to TL Model for linearize() method in concrete cost-functions
Detailed Description
template<typename MODEL>
class oops::CostFct4DVarTrajHR< MODEL >
4D-Var Cost Function in the ARPEGE
This class implements a specific linearize method for ARPEGE. The model trajectory is calculated at high resolution and the changes of resolution are made with FullPOS
Definition at line 48 of file CostFct4DVarTrajHR.h.
Member Typedef Documentation
Advector_
template<typename MODEL > using oops::CostFct4DVarTrajHR< MODEL >::Advector_ = AdvectorHandler<MODEL> private
Definition at line 57 of file CostFct4DVarTrajHR.h.
CostFct_
template<typename MODEL > using oops::CostFct4DVarTrajHR< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 52 of file CostFct4DVarTrajHR.h.
CtrlInc_
template<typename MODEL > using oops::CostFct4DVarTrajHR< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 50 of file CostFct4DVarTrajHR.h.
CtrlVar_
template<typename MODEL > using oops::CostFct4DVarTrajHR< MODEL >::CtrlVar_ = ControlVariable<MODEL> private
Definition at line 51 of file CostFct4DVarTrajHR.h.
Geometry_
template<typename MODEL > using oops::CostFct4DVarTrajHR< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 53 of file CostFct4DVarTrajHR.h.
Increment_
template<typename MODEL > using oops::CostFct4DVarTrajHR< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 49 of file CostFct4DVarTrajHR.h.
JqTerm_
template<typename MODEL > using oops::CostFct4DVarTrajHR< MODEL >::JqTerm_ = JqTerm<MODEL> private
Definition at line 58 of file CostFct4DVarTrajHR.h.
Model_
template<typename MODEL > using oops::CostFct4DVarTrajHR< MODEL >::Model_ = Model<MODEL> private
Definition at line 55 of file CostFct4DVarTrajHR.h.
ObsAuxControls_
template<typename MODEL > using oops::CostFct4DVarTrajHR< MODEL >::ObsAuxControls_ = ObsAuxControls<MODEL> private
Definition at line 59 of file CostFct4DVarTrajHR.h.
State_
template<typename MODEL > using oops::CostFct4DVarTrajHR< MODEL >::State_ = State<MODEL> private
Definition at line 54 of file CostFct4DVarTrajHR.h.
TrajectorySaver_
template<typename MODEL > using oops::CostFct4DVarTrajHR< MODEL >::TrajectorySaver_ = TrajectorySaverFP<MODEL> private
Definition at line 60 of file CostFct4DVarTrajHR.h.
Variables_
template<typename MODEL > using oops::CostFct4DVarTrajHR< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 56 of file CostFct4DVarTrajHR.h.
WeightedDiff_
template<typename MODEL > using oops::CostFct4DVarTrajHR< MODEL >::WeightedDiff_ = WeightedDiff<MODEL, Increment_, State_> private
Definition at line 61 of file CostFct4DVarTrajHR.h.
WeightedMean_
template<typename MODEL > using oops::CostFct4DVarTrajHR< MODEL >::WeightedMean_ = DFIProcessor<MODEL> private
Definition at line 62 of file CostFct4DVarTrajHR.h.
Constructor & Destructor Documentation
CostFct4DVarTrajHR()
template<typename MODEL > oops::CostFct4DVarTrajHR< MODEL >::CostFct4DVarTrajHR (const eckit::Configuration & config, const Geometry_ & resol, const Model_ & model)
Create J components \(J_b\) , \(J_o\), \(J_c\) ...
Definition at line 105 of file CostFct4DVarTrajHR.h.
   : CostFct4DVarMFTemplate<MODEL>::CostFct4DVarMFTemplate(config, resol, model), geom_(resol)
 {
   this->setupTerms(config);
 }
References oops::CostFunction< MODEL >::setupTerms().
~CostFct4DVarTrajHR()
template<typename MODEL > oops::CostFct4DVarTrajHR< MODEL >::~CostFct4DVarTrajHR () inline
Definition at line 66 of file CostFct4DVarTrajHR.h.
 {}
Member Function Documentation
addIncr()
template<typename MODEL > void oops::CostFct4DVarTrajHR< MODEL >::addIncr (CtrlVar_ & xfghr, const CtrlInc_ & dxlr, PostProcessor< Increment_ > &) const override private virtual
Add increment to the first guess (with FullPos change of resolution)
\(x_{hr}^{g} = {fullpos}_{l2h}(x_{lr}^{g})\)
\(x_{hr}^{a} = {fullpos}_{l2h}(x_{lr}^{g} + {\delta x}_{lr})\)
\({\delta x}_{hr} = x_{hr}^{a} - x_{hr}^{g}\)
\(x_{hr}^{g} += {\delta x}_{hr}\)
Reimplemented from oops::CostFct4DVarMFTemplate< MODEL >.
Definition at line 304 of file CostFct4DVarTrajHR.h.
{
   ASSERT(xfghr.state().checkStatesNumber(1));
   State_ fghr(geom_, *trajectoryModel_, *fglr_);
   (*fglr_) += dxlr.state()[0];
   State_ xahr(geom_, *trajectoryModel_, *fglr_);
   Increment_ dxhr(geom_, dxlr.state()[0]);
   dxhr.diff(xahr, fghr);
   xfghr.state()[0] += dxhr;
 }
References oops::State4D< MODEL >::checkStatesNumber(), oops::Increment< MODEL >::diff(), oops::ControlVariable< MODEL >::state(), and oops::ControlIncrement< MODEL >::state().
evaluate()
template<typename MODEL > double oops::CostFct4DVarTrajHR< MODEL >::evaluate (const CtrlVar_ & fguess, const eckit::Configuration & config = eckit::LocalConfiguration(), PostProcessor< State_ > post = PostProcessor<State_>()) const override virtual
Evaluate the non-linear cost function.
Setup DFI
Call standard J.evaluate()
Write analysis state in the middle of the window, filtered with incremental DFI
\(\widetilde{x}^{a}=DFI(x^{a})\)
\(x_{+3h}^{a}=x_{+3h}^{b}+(\widetilde{x}^{a}-\widetilde{x}^{b}) =x_{+3h}^{b}+\widetilde{\delta x}\)
\(x_{+3h}^{a}=\widetilde{x}^{a}+(x_{+3h}^{b}-\widetilde{x}^{b}) =x^{b}+biasDFI\)
Reimplemented from oops::CostFct4DVarMFTemplate< MODEL >.
Definition at line 116 of file CostFct4DVarTrajHR.h.
{
   Log::trace() << "CostFct4DVarTrajHR::evaluate start" << std::endl;
   PostProcessor<State_> pp(post);
   std::shared_ptr<WeightedMean_> pdfi;
   if (config.has("dfi")) {
     const eckit::LocalConfiguration dfiConf(config, "dfi");
     const util::Duration dfispan(dfiConf.getString("filter_span"));
     const util::DateTime dfitime(fguess.state()[0].validTime() + dfispan / 2);
     pdfi.reset(new WeightedMean_(dfitime, dfispan, geom_, dfiConf));
     pp.enrollProcessor(pdfi);
   }
   double zzz = this->CostFunction<MODEL>::evaluate(fguess, config, pp);
   if (config.has("dfi")) {
     const eckit::LocalConfiguration dfiConf(config, "dfi");
     std::unique_ptr<State_> xdfi(pdfi->releaseMean());
     (*xdfi) += (*biasDFI_);
     Log::info() << "CostFunction: Write filtered analysis in the middle of the window.";
     xdfi->write(eckit::LocalConfiguration(dfiConf, "output"));
   }
   Log::trace() << "CostFct4DVarTrajHR::evaluate done" << std::endl;
   return zzz;
 }
References oops::PostProcessor< FLDS >::enrollProcessor(), oops::CostFunction< MODEL >::evaluate(), and oops::ControlVariable< MODEL >::state().
getCostJb()
template<typename MODEL > const double& oops::CostFct4DVarTrajHR< MODEL >::getCostJb () const inline override virtual
Get the Jb cost function value.
Reimplemented from oops::CostFct4DVarMFTemplate< MODEL >.
Definition at line 81 of file CostFct4DVarTrajHR.h.
 {return costJb_;}
References oops::CostFct4DVarTrajHR< MODEL >::costJb_.
getCostJoJc()
template<typename MODEL > const double& oops::CostFct4DVarTrajHR< MODEL >::getCostJoJc () const inline override virtual
Get the JoJc cost function value.
Reimplemented from oops::CostFct4DVarMFTemplate< MODEL >.
Definition at line 78 of file CostFct4DVarTrajHR.h.
 {return costJoJc_;}
References oops::CostFct4DVarTrajHR< MODEL >::costJoJc_.
linearize()
template<typename MODEL > double oops::CostFct4DVarTrajHR< MODEL >::linearize (const CtrlVar_ & fguess, const eckit::Configuration & innerConf, PostProcessor< State_ > post = PostProcessor<State_>()) override virtual
Specific linearization for ARPEGE 4D-Var with trajectory from high resolution.
This method sets up the quadratic cost function by linearizing the non-linear cost function in the specific case of ARPEGE
Jo, Jc, .. (jterms_) terms of the cost function call their 'initialize' methods which return post-processors. These are subsequently attached to the non-linear trajectory and do their post-processing prior/during/after the trajectory evaluation; once the non-linear trajectory is completed, the terms of the cost function call their 'finalize' method which makes further use of the output acquired by the post-processors during the trajectory.
E.g. the 'initialize' method of the Jo term of the cost functions returns an Observer post-processor. Its task is to compute model equivalents at observation locations. Once the trajectory evaluation is completed, the 'finalize' method is called to compute departures, perform screening if requested, set up the observation error covariance and print diagnostics.
Along with with the post-processors set up by the terms of the cost function, the TrajectorySaver post-processor is set up. Its role is to record the interpolated high resolution states at the linear model time steps during the non-linear trajectory run. These interpolated high resolution states are subsequently used to force the linearisation trajectory.
If required, a DFI bias is calculated.
Prior to the computation of the linearisation trajectory by the TrajectorySaver, the Jb, Jo, Jc, .. terms of the cost function call their 'initializeTraj' methods which return post-processors. These are subsequently enrolled into the TrajectorySaver and attached to the linearisation trajectory computation. Once the linearisation trajectory computation is completed, the terms of the cost function call the 'finalizeTraj' method which makes further use of the output acquired by the post-processors during the computation of the linearisation trajectory.
E.g. the 'initializeTraj' method of the Jo term of the cost function sets up the linear observation operator and returns an Observer post-processor. Its task is to compute the linearisation for the linear observation operator. Once the linearisation trajectory computation is completed, the 'finailzeTraj' method is called to compute the departures and print diagnostics.
Read inner loop configuration
Calculate Guess at low resolution for future change of resolution in addIncr()
Initialize Observation operator and TrajectorySaver, possibly DFI.
Run non linear model at high resolution with screening, if required
Calculate non linear Jo (without Jc)
Put filter aside for usage after the final trajectory (biasDFI)
\(\widetilde{x}^{b}=DFI(x^{b})\)
\(biasDFI=x_{+3h}^{b}-\widetilde{x}^{b}\)
Record trajectory with:
JbJq trajectory JoJc trajectory Advector winds fields along the assimilation window
Calculate trajectory cost function value
Print cost function value
Reimplemented from oops::CostFct4DVarMFTemplate< MODEL >.
Definition at line 160 of file CostFct4DVarTrajHR.h.
{
   PostProcessor<State_> no_post;
   const eckit::LocalConfiguration resConf(innerConf, "resolution");
   const eckit::LocalConfiguration tlmConf(innerConf, "linearmodel");
   std::unique_ptr<eckit::LocalConfiguration> dfiConf;
   const Geometry_ lowres(resConf);
   std::shared_ptr<WeightedDiff_> pdfi;
   std::unique_ptr<WeightingFct> wfct;
   const eckit::LocalConfiguration lowresModelConfig(innerConf, "low_resolution_model");
   trajectoryModel_.reset(new Model_(lowres, lowresModelConfig));
   CtrlVar_ fglr(lowres, *trajectoryModel_, fguess);
   fglr_.reset(new State_(fglr.state()[0]));
   malloc_trim(0);
   PostProcessor<State_> pp(post);
   pp.enrollProcessor(this->getJterm(0).initialize(fguess, innerConf));
   std::shared_ptr< TrajectorySaver_ >
     trajectorySaver(new TrajectorySaver_(fglr.state()[0], fglr.modVar(),
         lowres, this->getTLMs(), tlmConf));
   pp.enrollProcessor(trajectorySaver);
   if (innerConf.has("screening.dfi")) {
     dfiConf.reset(new eckit::LocalConfiguration(innerConf, "screening.dfi"));
     const util::Duration dfispan(dfiConf->getString("filter_span"));
     const util::DateTime dfitime(fguess.state()[0].validTime() + dfispan / 2);
     wfct.reset(new DolphChebyshev(*dfiConf));
     pdfi.reset(new WeightedDiff_(dfitime, dfispan, geom_, *dfiConf, util::Duration(0), *wfct));
     pp.enrollProcessor(pdfi);
     if (dfiConf->has("output")) {
       const eckit::LocalConfiguration outConfig(*dfiConf, "output");
       pp.enrollProcessor(new StateWriter<State_>(fguess.state()[0].validTime(), outConfig));
     }
   }
   CtrlVar_ fghr(fguess);
   this->runNL(fghr, pp);
   costJoJc_ = this->getJterm(0).finalize(innerConf);
   if (innerConf.has("screening.dfi")) {
     biasDFI_.reset(pdfi->releaseDiff());
     (*biasDFI_) *= -1.0;
   }
   //TODO:
   // 5. Reset the observation space component of the first guess
   //ObsAuxControls_ &obsvarfg = const_cast<ObsAuxControls_ &>(fglr.obsVar());
   //obsvarfg.reset(*obsSpaces_, "fg", innerConf);
   std::shared_ptr<JqTerm_> jq(this->getJb().initializeTraj(fglr, lowres, innerConf));
   trajectorySaver->enrollProcessor(jq);
   for (unsigned iterm=0; iterm < this->nterms(); ++iterm) {
     trajectorySaver->enrollProcessor(this->getJterm(iterm).initializeTraj(fglr, lowres, innerConf));
   }
   std::shared_ptr<Advector_ > advector = Advector_::get();
   if (advector) trajectorySaver->enrollProcessor(advector);
   trajectorySaver->recordTrajectory();
   costJb_ = this->getJb().finalizeTraj(jq.get(), innerConf);
   double costJoJcTraj = 0.0;
   for (unsigned iterm=0; iterm < this->nterms(); ++iterm) {
     costJoJcTraj += this->getJterm(iterm).finalizeTraj(innerConf);
   }
   double costJ = costJb_ + costJoJc_;
   Log::test() << "CostFunction: Nonlinear J = " << costJ << std::endl;
   return costJ;
 }
References oops::PostProcessor< FLDS >::enrollProcessor(), oops::ControlVariable< MODEL >::modVar(), and oops::ControlVariable< MODEL >::state().
Member Data Documentation
biasDFI_
template<typename MODEL > std::unique_ptr<Increment_> oops::CostFct4DVarTrajHR< MODEL >::biasDFI_ private
biasDFI calculated in the first trajectory and used at the end.
Definition at line 99 of file CostFct4DVarTrajHR.h.
costJb_
template<typename MODEL > double oops::CostFct4DVarTrajHR< MODEL >::costJb_ private
Definition at line 90 of file CostFct4DVarTrajHR.h.
Referenced by oops::CostFct4DVarTrajHR< MODEL >::getCostJb().
costJoJc_
template<typename MODEL > double oops::CostFct4DVarTrajHR< MODEL >::costJoJc_ private
Definition at line 89 of file CostFct4DVarTrajHR.h.
Referenced by oops::CostFct4DVarTrajHR< MODEL >::getCostJoJc().
fglr_
template<typename MODEL > std::unique_ptr<State_> oops::CostFct4DVarTrajHR< MODEL >::fglr_ private
Guess at low resolution.
Definition at line 96 of file CostFct4DVarTrajHR.h.
geom_
template<typename MODEL > const Geometry_ oops::CostFct4DVarTrajHR< MODEL >::geom_ private
Definition at line 91 of file CostFct4DVarTrajHR.h.
trajectoryModel_
template<typename MODEL > std::unique_ptr<Model_> oops::CostFct4DVarTrajHR< MODEL >::trajectoryModel_ private
Model that calculates the trajectory at low resolution.
Definition at line 94 of file CostFct4DVarTrajHR.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/CostFct4DVarTrajHR.h