OOPS Documentation: oops::ObsAuxIncrement< MODEL > Class Template Reference
oops::ObsAuxIncrement< MODEL > Class Template Reference
Encapsulates auxiliary observation space components of ControlIncrement.
#include <ObsAuxIncrement.h>
Public Member Functions
ObsAuxIncrement (const ObservationSpace_ &, const eckit::Configuration &)
Constructor.
ObsAuxIncrement (const ObsAuxIncrement &, const bool copy=true)
Copy constructor.
ObsAuxIncrement (const ObsAuxIncrement &, const eckit::Configuration &)
Copy constructor.
~ObsAuxIncrement ()
Destructor.
void diff (const ObsAuxControl_ &, const ObsAuxControl_ &)
\(dx = x_1 - x_2 \)
void zero ()
\(dx_1 = 0 \)
ObsAuxIncrement & operator= (const ObsAuxIncrement &)
\(dx_1 = dx_2 \)
ObsAuxIncrement & operator+= (const ObsAuxIncrement &)
\(dx_1 = dx_1 + dx_2 \)
ObsAuxIncrement & operator-= (const ObsAuxIncrement &)
\(dx_1 = dx_1 - dx_2 \)
ObsAuxIncrement & operator*= (const double &)
\(dx_1 = dx_1 * c \)
void axpy (const double &, const ObsAuxIncrement &)
\(dx_1 = dx_1 * c dx_2 \)
double dot_product_with (const ObsAuxIncrement &) const
\(<dx_1,dx_1> = dx_1^T dx_1 \)
void read (const eckit::Configuration &)
Read control increment.
void write (const eckit::Configuration &) const
Write control increment.
double norm () const
L-2 norm.
const ObsAuxIncrementBase_ & obsauxincrement (const std::string &id) const
Return a constant reference to the model specific object.
ObsAuxIncrementBase_ & obsauxincrement (const std::string &id)
Return a reference to the model specific object.
const ObsAuxIncrementPtrMap_ & obsauxincrement () const
Return a constant reference to the map of model specific objects.
ObsAuxIncrementPtrMap_ & obsauxincrement ()
Return a reference to the map of model specific objects.
const std::vector< std::string > & getKeys () const
Return a constant reference to the vector of keys.
const size_t & size () const
Return the number of ObsAuxIncrementBase objects.
Static Public Member Functions
static const std::string classname ()
Private Types
using ObsAuxIncrementBase_ = ObsAuxIncrementBase< MODEL >
using ObsAuxControl_ = ObsAuxControl< MODEL >
using ObservationSpace_ = ObservationSpace< MODEL >
using ObsAuxIncrementPtrMap_ = std::map< std::string, std::unique_ptr< ObsAuxIncrementBase_ > >
using iter_ = typename ObsAuxIncrementPtrMap_::iterator
using icst_ = typename ObsAuxIncrementPtrMap_::const_iterator
Private Member Functions
const ObsAuxIncrementBase_ & get (const std::string &) const
Return a constant reference to the model specific object.
ObsAuxIncrementBase_ & get (const std::string &)
Return a reference to the model specific object.
void print (std::ostream &) const
Private Attributes
size_t size_
Number of model specific objects.
std::vector< std::string > keys_
Vector of keys to model specific objects.
ObsAuxIncrementPtrMap_ incs_
Map of pointers to model specific objects.
Detailed Description
template<typename MODEL>
class oops::ObsAuxIncrement< MODEL >
Encapsulates auxiliary observation space components of ControlIncrement.
This class provides operations associated with the auxiliary observation space components (e.g. VarBC, TOVSC) of ControlIncrement. It contains a vector of ObsAuxIncrementBase objects, where ObsAuxIncrementBase is a base class for model specific (or potentially generic) classes.
ObsAuxIncrements class wraps around a vector of ObsAuxIncrement objects and is part of ControlIncrement. Refer to the documentation of ControlIncrement and CostJo to understand the structure.
Definition at line 52 of file ObsAuxIncrement.h.
Member Typedef Documentation
icst_
template<typename MODEL > using oops::ObsAuxIncrement< MODEL >::icst_ = typename ObsAuxIncrementPtrMap_::const_iterator private
Definition at line 60 of file ObsAuxIncrement.h.
iter_
template<typename MODEL > using oops::ObsAuxIncrement< MODEL >::iter_ = typename ObsAuxIncrementPtrMap_::iterator private
Definition at line 59 of file ObsAuxIncrement.h.
ObsAuxControl_
template<typename MODEL > using oops::ObsAuxIncrement< MODEL >::ObsAuxControl_ = ObsAuxControl<MODEL> private
Definition at line 55 of file ObsAuxIncrement.h.
ObsAuxIncrementBase_
template<typename MODEL > using oops::ObsAuxIncrement< MODEL >::ObsAuxIncrementBase_ = ObsAuxIncrementBase<MODEL> private
Definition at line 54 of file ObsAuxIncrement.h.
ObsAuxIncrementPtrMap_
template<typename MODEL > using oops::ObsAuxIncrement< MODEL >::ObsAuxIncrementPtrMap_ = std::map<std::string, std::unique_ptr<ObsAuxIncrementBase_> > private
Definition at line 58 of file ObsAuxIncrement.h.
ObservationSpace_
template<typename MODEL > using oops::ObsAuxIncrement< MODEL >::ObservationSpace_ = ObservationSpace<MODEL> private
Definition at line 56 of file ObsAuxIncrement.h.
Constructor & Destructor Documentation
ObsAuxIncrement() [1/3]
template<typename MODEL > oops::ObsAuxIncrement< MODEL >::ObsAuxIncrement (const ObservationSpace_ & os, const eckit::Configuration & conf)
Constructor.
Definition at line 155 of file ObsAuxIncrement.h.
     : size_(0), keys_(), incs_() {
   Log::trace() << "ObsAuxIncrement<MODEL>::ObsAuxIncrement starting"
                << std::endl;
   util::Timer timer(classname(), "ObsAuxIncrement");
   std::vector<eckit::LocalConfiguration> confs;
   conf.get("covarianceObsAux", confs);
   size_ = confs.size();
   for (auto const &config : confs) {
     std::string key(config.getString("type"));
     std::unique_ptr<ObsAuxIncrementBase<MODEL>> auxinc(
         ObsAuxIncrementFactory<MODEL>::create(os, config));
     incs_.emplace(key, std::move(auxinc));
     keys_.push_back(key);
   }
   Log::trace() << "ObsAuxIncrement<MODEL>::ObsAuxIncrement done" << std::endl;
 }
References oops::ObsAuxIncrement< MODEL >::classname(), oops::ObsAuxIncrement< MODEL >::incs_, oops::ObsAuxIncrement< MODEL >::keys_, and oops::ObsAuxIncrement< MODEL >::size_.
ObsAuxIncrement() [2/3]
template<typename MODEL > oops::ObsAuxIncrement< MODEL >::ObsAuxIncrement (const ObsAuxIncrement< MODEL > & other, const bool copy = true)
Copy constructor.
Definition at line 177 of file ObsAuxIncrement.h.
     : size_(other.size_), keys_(), incs_() {
   Log::trace() << "ObsAuxIncrement<MODEL>::ObsAuxIncrement starting"
                << std::endl;
   util::Timer timer(classname(), "ObsAuxIncrement");
   for (icst_ it = other.incs_.begin(); it != other.incs_.end(); ++it) {
     std::string incname = it->first;
     std::unique_ptr<ObsAuxIncrementBase<MODEL>> auxinc(it->second->clone(copy));
     incs_.emplace(incname, std::move(auxinc));
     keys_.push_back(incname);
   }
   Log::trace() << "ObsAuxIncrement<MODEL>::ObsAuxIncrement done" << std::endl;
 }
References oops::ObsAuxIncrement< MODEL >::classname(), oops::ObsAuxIncrement< MODEL >::incs_, and oops::ObsAuxIncrement< MODEL >::keys_.
ObsAuxIncrement() [3/3]
template<typename MODEL > oops::ObsAuxIncrement< MODEL >::ObsAuxIncrement (const ObsAuxIncrement< MODEL > & other, const eckit::Configuration & conf)
Copy constructor.
Definition at line 193 of file ObsAuxIncrement.h.
     : size_(other.size_), keys_(), incs_() {
   Log::trace() << "ObsAuxIncrement<MODEL>::ObsAuxIncrement starting"
                << std::endl;
   util::Timer timer(classname(), "ObsAuxIncrement");
   for (icst_ it = other.incs_.begin(); it != other.incs_.end(); ++it) {
     std::string incname = it->first;
     std::unique_ptr<ObsAuxIncrementBase<MODEL>> auxinc(it->second->clone(conf));
     incs_.emplace(incname, std::move(auxinc));
     keys_.push_back(incname);
   }
   Log::trace() << "ObsAuxIncrement<MODEL>::ObsAuxIncrement done" << std::endl;
 }
References oops::ObsAuxIncrement< MODEL >::classname(), oops::ObsAuxIncrement< MODEL >::incs_, and oops::ObsAuxIncrement< MODEL >::keys_.
~ObsAuxIncrement()
template<typename MODEL > oops::ObsAuxIncrement< MODEL >::~ObsAuxIncrement
Destructor.
Definition at line 209 of file ObsAuxIncrement.h.
{
   Log::trace() << "ObsAuxIncrement<MODEL>::~ObsAuxIncrement starting"
                << std::endl;
   util::Timer timer(classname(), "~ObsAuxIncrement");
   Log::trace() << "ObsAuxIncrement<MODEL>::~ObsAuxIncrement done" << std::endl;
 }
Member Function Documentation
axpy()
template<typename MODEL > void oops::ObsAuxIncrement< MODEL >::axpy (const double & zz, const ObsAuxIncrement< MODEL > & dx)
\(dx_1 = dx_1 * c dx_2 \)
Definition at line 300 of file ObsAuxIncrement.h.
{
   Log::trace() << "ObsAuxIncrement<MODEL>::axpy starting" << std::endl;
   util::Timer timer(classname(), "axpy");
   for (iter_ it = incs_.begin(); it != incs_.end(); ++it) {
     it->second->axpy(zz, dx.obsauxincrement(it->first));
   }
   Log::trace() << "ObsAuxIncrement<MODEL>::axpy done" << std::endl;
 }
References oops::ObsAuxIncrement< MODEL >::obsauxincrement().
classname()
template<typename MODEL > static const std::string oops::ObsAuxIncrement< MODEL >::classname () inline static
Definition at line 63 of file ObsAuxIncrement.h.
 { return "oops::ObsAuxIncrement"; }
Referenced by oops::ObsAuxIncrement< MODEL >::ObsAuxIncrement().
diff()
template<typename MODEL > void oops::ObsAuxIncrement< MODEL >::diff (const ObsAuxControl_ & x1, const ObsAuxControl_ & x2)
\(dx = x_1 - x_2 \)
Definition at line 232 of file ObsAuxIncrement.h.
{
   Log::trace() << "ObsAuxIncrement<MODEL>::diff starting" << std::endl;
   util::Timer timer(classname(), "diff");
   for (iter_ it = incs_.begin(); it != incs_.end(); ++it) {
     it->second->diff(x1.obsauxcontrol(it->first), x2.obsauxcontrol(it->first));
   }
   Log::trace() << "ObsAuxIncrement<MODEL>::diff done" << std::endl;
 }
References oops::ObsAuxControl< MODEL >::obsauxcontrol().
dot_product_with()
template<typename MODEL > double oops::ObsAuxIncrement< MODEL >::dot_product_with (const ObsAuxIncrement< MODEL > & dx) const
\(<dx_1,dx_1> = dx_1^T dx_1 \)
Definition at line 310 of file ObsAuxIncrement.h.
{
   Log::trace() << "ObsAuxIncrement<MODEL>::dot_product_with starting"
                << std::endl;
   util::Timer timer(classname(), "dot_product_with");
   double zz = 0.0;
   for (icst_ it = incs_.begin(); it != incs_.end(); ++it) {
     zz += it->second->dot_product_with(dx.obsauxincrement(it->first));
   }
   Log::trace() << "ObsAuxIncrement<MODEL>::dot_product_with done" << std::endl;
   return zz;
 }
References oops::ObsAuxIncrement< MODEL >::obsauxincrement().
get() [1/2]
template<typename MODEL > ObsAuxIncrementBase< MODEL > & oops::ObsAuxIncrement< MODEL >::get (const std::string & id) private
Return a reference to the model specific object.
Definition at line 217 of file ObsAuxIncrement.h.
{
   iter_ it = incs_.find(id);
   ASSERT(it != incs_.end());
   return *it->second;
 }
get() [2/2]
template<typename MODEL > const ObsAuxIncrementBase< MODEL > & oops::ObsAuxIncrement< MODEL >::get (const std::string & id) const private
Return a constant reference to the model specific object.
Definition at line 224 of file ObsAuxIncrement.h.
{
   icst_ it = incs_.find(id);
   ASSERT(it != incs_.end());
   return *it->second;
 }
Referenced by oops::ObsAuxIncrement< MODEL >::obsauxincrement().
getKeys()
template<typename MODEL > const std::vector<std::string>& oops::ObsAuxIncrement< MODEL >::getKeys () const inline
Return a constant reference to the vector of keys.
Definition at line 116 of file ObsAuxIncrement.h.
 { return keys_; }
References oops::ObsAuxIncrement< MODEL >::keys_.
norm()
template<typename MODEL > double oops::ObsAuxIncrement< MODEL >::norm
L-2 norm.
Definition at line 356 of file ObsAuxIncrement.h.
{
   Log::trace() << "ObsAuxIncrement<MODEL>::norm starting" << std::endl;
   util::Timer timer(classname(), "norm");
   double zz = 0.0;
   for (icst_ it = incs_.begin(); it != incs_.end(); ++it) {
     double norm = it->second->norm();
     zz += norm * norm;
   }
   Log::trace() << "ObsAuxIncrement<MODEL>::norm done" << std::endl;
   return sqrt(zz);
 }
obsauxincrement() [1/4]
template<typename MODEL > ObsAuxIncrementPtrMap_& oops::ObsAuxIncrement< MODEL >::obsauxincrement () inline
Return a reference to the map of model specific objects.
Definition at line 113 of file ObsAuxIncrement.h.
 { return incs_; }
References oops::ObsAuxIncrement< MODEL >::incs_.
obsauxincrement() [2/4]
template<typename MODEL > const ObsAuxIncrementPtrMap_& oops::ObsAuxIncrement< MODEL >::obsauxincrement () const inline
Return a constant reference to the map of model specific objects.
Definition at line 111 of file ObsAuxIncrement.h.
 { return incs_; }
References oops::ObsAuxIncrement< MODEL >::incs_.
obsauxincrement() [3/4]
template<typename MODEL > ObsAuxIncrementBase_& oops::ObsAuxIncrement< MODEL >::obsauxincrement (const std::string & id) inline
Return a reference to the model specific object.
Definition at line 106 of file ObsAuxIncrement.h.
{
     return this->get(id);
   }
References oops::ObsAuxIncrement< MODEL >::get().
obsauxincrement() [4/4]
template<typename MODEL > const ObsAuxIncrementBase_& oops::ObsAuxIncrement< MODEL >::obsauxincrement (const std::string & id) const inline
Return a constant reference to the model specific object.
Definition at line 102 of file ObsAuxIncrement.h.
{
     return this->get(id);
   }
References oops::ObsAuxIncrement< MODEL >::get().
Referenced by oops::ObsAuxIncrement< MODEL >::axpy(), oops::ObsAuxIncrement< MODEL >::dot_product_with(), oops::ObsAuxCovariance< MODEL >::inverseMultiply(), oops::ObsAuxCovariance< MODEL >::multiply(), oops::ObsAuxCovariance< MODEL >::multiplySqrt(), oops::ObsAuxCovariance< MODEL >::multiplySqrtTrans(), oops::LinearObsOperator< MODEL >::obsBiasEquivAD(), oops::LinearObsOperator< MODEL >::obsBiasEquivTL(), oops::LinearObsOperator< MODEL >::obsEquivAD(), oops::LinearObsOperator< MODEL >::obsEquivTL(), oops::ObsAuxIncrement< MODEL >::operator+=(), oops::operator+=(), oops::ObsAuxIncrement< MODEL >::operator-=(), oops::ObsAuxIncrement< MODEL >::operator=(), and oops::ObsAuxCovariance< MODEL >::randomize().
operator*=()
template<typename MODEL > ObsAuxIncrement< MODEL > & oops::ObsAuxIncrement< MODEL >::operator*= (const double & zz)
\(dx_1 = dx_1 * c \)
Definition at line 289 of file ObsAuxIncrement.h.
{
   Log::trace() << "ObsAuxIncrement<MODEL>::operator*= starting" << std::endl;
   util::Timer timer(classname(), "operator*=");
   for (iter_ it = incs_.begin(); it != incs_.end(); ++it) {
     *(it->second) *= zz;
   }
   Log::trace() << "ObsAuxIncrement<MODEL>::operator*= done" << std::endl;
   return *this;
 }
operator+=()
template<typename MODEL > ObsAuxIncrement< MODEL > & oops::ObsAuxIncrement< MODEL >::operator+= (const ObsAuxIncrement< MODEL > & rhs)
\(dx_1 = dx_1 + dx_2 \)
Definition at line 265 of file ObsAuxIncrement.h.
{
   Log::trace() << "ObsAuxIncrement<MODEL>::operator+= starting" << std::endl;
   util::Timer timer(classname(), "operator+=");
   for (iter_ it = incs_.begin(); it != incs_.end(); ++it) {
     *(it->second) += rhs.obsauxincrement(it->first);
   }
   Log::trace() << "ObsAuxIncrement<MODEL>::operator+= done" << std::endl;
   return *this;
 }
References oops::ObsAuxIncrement< MODEL >::obsauxincrement().
operator-=()
template<typename MODEL > ObsAuxIncrement< MODEL > & oops::ObsAuxIncrement< MODEL >::operator-= (const ObsAuxIncrement< MODEL > & rhs)
\(dx_1 = dx_1 - dx_2 \)
Definition at line 277 of file ObsAuxIncrement.h.
{
   Log::trace() << "ObsAuxIncrement<MODEL>::operator-= starting" << std::endl;
   util::Timer timer(classname(), "operator-=");
   for (iter_ it = incs_.begin(); it != incs_.end(); ++it) {
     *(it->second) -= rhs.obsauxincrement(it->first);
   }
   Log::trace() << "ObsAuxIncrement<MODEL>::operator-= done" << std::endl;
   return *this;
 }
References oops::ObsAuxIncrement< MODEL >::obsauxincrement().
operator=()
template<typename MODEL > ObsAuxIncrement< MODEL > & oops::ObsAuxIncrement< MODEL >::operator= (const ObsAuxIncrement< MODEL > & rhs)
\(dx_1 = dx_2 \)
Definition at line 253 of file ObsAuxIncrement.h.
{
   Log::trace() << "ObsAuxIncrement<MODEL>::operator= starting" << std::endl;
   util::Timer timer(classname(), "operator=");
   for (iter_ it = incs_.begin(); it != incs_.end(); ++it) {
     *(it->second) = rhs.obsauxincrement(it->first);
   }
   Log::trace() << "ObsAuxIncrement<MODEL>::operator= done" << std::endl;
   return *this;
 }
References oops::ObsAuxIncrement< MODEL >::obsauxincrement().
print()
template<typename MODEL > void oops::ObsAuxIncrement< MODEL >::print (std::ostream & os) const private
Definition at line 369 of file ObsAuxIncrement.h.
{
   Log::trace() << "ObsAuxIncrement<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   for (icst_ it = incs_.begin(); it != incs_.end(); ++it) {
     os << it->first << ": " << *it->second;
   }
   Log::trace() << "ObsAuxIncrement<MODEL>::print done" << std::endl;
 }
read()
template<typename MODEL > void oops::ObsAuxIncrement< MODEL >::read (const eckit::Configuration & conf)
Read control increment.
Definition at line 324 of file ObsAuxIncrement.h.
{
   Log::trace() << "ObsAuxIncrement<MODEL>::read starting" << std::endl;
   util::Timer timer(classname(), "read");
   std::vector<eckit::LocalConfiguration> confs;
   conf.get("incrementObsAux", confs);
   for (iter_ it = incs_.begin(); it != incs_.end(); ++it) {
     for (auto const &config : confs) {
       if (config.getString("type") == it->first) it->second->read(config);
     }
   }
   Log::trace() << "ObsAuxIncrement<MODEL>::read done" << std::endl;
 }
size()
template<typename MODEL > const size_t& oops::ObsAuxIncrement< MODEL >::size () const inline
Return the number of ObsAuxIncrementBase objects.
Definition at line 119 of file ObsAuxIncrement.h.
 { return size_; }
References oops::ObsAuxIncrement< MODEL >::size_.
write()
template<typename MODEL > void oops::ObsAuxIncrement< MODEL >::write (const eckit::Configuration & conf) const
Write control increment.
Definition at line 340 of file ObsAuxIncrement.h.
{
   Log::trace() << "ObsAuxIncrement<MODEL>::write starting" << std::endl;
   util::Timer timer(classname(), "write");
   std::vector<eckit::LocalConfiguration> confs;
   if (conf.has("incrementObsAux")) conf.get("incrementObsAux", confs);
   for (icst_ it = incs_.begin(); it != incs_.end(); ++it) {
     for (auto const &config : confs) {
       if (config.getString("type") == it->first) it->second->write(config);
     }
   }
   Log::trace() << "ObsAuxIncrement<MODEL>::write done" << std::endl;
 }
zero()
template<typename MODEL > void oops::ObsAuxIncrement< MODEL >::zero
\(dx_1 = 0 \)
Definition at line 243 of file ObsAuxIncrement.h.
{
   Log::trace() << "ObsAuxIncrement<MODEL>::zero starting" << std::endl;
   util::Timer timer(classname(), "zero");
   for (iter_ it = incs_.begin(); it != incs_.end(); ++it) {
     it->second->zero();
   }
   Log::trace() << "ObsAuxIncrement<MODEL>::zero done" << std::endl;
 }
Referenced by oops::LinearObsOperator< MODEL >::obsBiasEquivAD().
Member Data Documentation
incs_
template<typename MODEL > ObsAuxIncrementPtrMap_ oops::ObsAuxIncrement< MODEL >::incs_ private
Map of pointers to model specific objects.
Definition at line 130 of file ObsAuxIncrement.h.
Referenced by oops::ObsAuxIncrement< MODEL >::ObsAuxIncrement(), and oops::ObsAuxIncrement< MODEL >::obsauxincrement().
keys_
template<typename MODEL > std::vector<std::string> oops::ObsAuxIncrement< MODEL >::keys_ private
Vector of keys to model specific objects.
Definition at line 129 of file ObsAuxIncrement.h.
Referenced by oops::ObsAuxIncrement< MODEL >::getKeys(), and oops::ObsAuxIncrement< MODEL >::ObsAuxIncrement().
size_
template<typename MODEL > size_t oops::ObsAuxIncrement< MODEL >::size_ mutable private
Number of model specific objects.
Definition at line 128 of file ObsAuxIncrement.h.
Referenced by oops::ObsAuxIncrement< MODEL >::ObsAuxIncrement(), and oops::ObsAuxIncrement< MODEL >::size().
The documentation for this class was generated from the following file:
src/oops/interface/ObsAuxIncrement.h