OOPS Documentation: oops::IncrModCtlVec< MODEL > Class Template Reference
oops::IncrModCtlVec< MODEL > Class Template Reference
IncrModCtlVec class.
#include <CostJbState.h>
Public Member Functions
IncrModCtlVec ()
Constructor.
IncrModCtlVec (const ErrorCovariance_ &)
Constructor.
IncrModCtlVec (const ErrorCovariance_ &, const IncrModCtlVec &)
Constructor with copy initialization.
IncrModCtlVec (const IncrModCtlVec &, const bool copy=true)
Copy constructor.
virtual ~IncrModCtlVec ()
Destructor.
void zero ()
\(dv_1 = 0 \)
IncrModCtlVec & operator= (const IncrModCtlVec &)
\(dv_1 = dv_2 \)
IncrModCtlVec & operator+= (const IncrModCtlVec &)
\(dv_1 = dv_1 + dv_2 \)
IncrModCtlVec & operator-= (const IncrModCtlVec &)
\(dv_1 = dv_1 - dv_2 \)
IncrModCtlVec & operator*= (const double &)
\(dv_1 = dv_1 * c \)
void axpy (const double &, const IncrModCtlVec &, const bool check=true)
\(dv_1 = dv_1 * c dv_2 \)
double dot_product_with (const IncrModCtlVec &) const
\(<dv_1,dv_1> = dv_1^T dv_1 \)
void schur_product_with (const IncrModCtlVec &)
Hadamard product (element-wise)
void random ()
Random control vector.
void getSection (std::vector< double > &, const int &, const int &) const
Get section of the control vector.
void setSection (const std::vector< double > &, const int &, const int &)
Set section of the control vector.
void read (const eckit::Configuration &)
Read control vector.
void write (const eckit::Configuration &) const
Write control vector.
double norm () const
L-2 norm.
IncrModCtlVec_ & ctlVec ()
Get control vector.
const IncrModCtlVec_ & ctlVec () const
Get constant control vector.
Static Public Member Functions
static const std::string classname ()
Private Types
using IncrModCtlVec_ = typename MODEL::IncrModCtlVec
using ErrorCovariance_ = ErrorCovariance< MODEL >
Private Member Functions
void print (std::ostream &) const
Private Attributes
std::unique_ptr< IncrModCtlVec_ > incrModCtlVec_
Model specific implementation.
Detailed Description
template<typename MODEL>
class oops::IncrModCtlVec< MODEL >
IncrModCtlVec class.
Part of the control vector (acted upon by the modelled background error covariance matrix). Consider a general formulation of the state component of the control vector for a particular sub-window \(K \), having two components corresponding to the modelled and ensemble based covariance matrices:
\[ dv^K = \begin{bmatrix} dv^K_{mod} \\ dv^K_{ens} \end{bmatrix} \]
-> \(dv^K \) is implemented by IncrCtlVec
-> \(dv^K_{mod} \) is implemented by IncrModCtlVec
Definition at line 38 of file CostJbState.h.
Member Typedef Documentation
ErrorCovariance_
template<typename MODEL > using oops::IncrModCtlVec< MODEL >::ErrorCovariance_ = ErrorCovariance<MODEL> private
Definition at line 53 of file IncrModCtlVec.h.
IncrModCtlVec_
template<typename MODEL > using oops::IncrModCtlVec< MODEL >::IncrModCtlVec_ = typename MODEL::IncrModCtlVec private
Definition at line 52 of file IncrModCtlVec.h.
Constructor & Destructor Documentation
IncrModCtlVec() [1/4]
template<typename MODEL > oops::IncrModCtlVec< MODEL >::IncrModCtlVec
Constructor.
Constructor, destructor.
Definition at line 121 of file IncrModCtlVec.h.
 : incrModCtlVec_() {}
IncrModCtlVec() [2/4]
template<typename MODEL > oops::IncrModCtlVec< MODEL >::IncrModCtlVec (const ErrorCovariance_ & cov)
Constructor.
Definition at line 126 of file IncrModCtlVec.h.
     : incrModCtlVec_() {
   Log::trace() << "IncrModCtlVec<MODEL>::IncrModCtlVec starting" << std::endl;
   util::Timer timer(classname(), "Incr");
   incrModCtlVec_.reset(new IncrModCtlVec_(cov.errorCovariance()));
   Log::trace() << "IncrModCtlVec<MODEL>::IncrModCtlVec done" << std::endl;
 }
References oops::IncrModCtlVec< MODEL >::classname(), oops::ErrorCovariance< MODEL >::errorCovariance(), and oops::IncrModCtlVec< MODEL >::incrModCtlVec_.
IncrModCtlVec() [3/4]
template<typename MODEL > oops::IncrModCtlVec< MODEL >::IncrModCtlVec (const ErrorCovariance_ & cov, const IncrModCtlVec< MODEL > & other)
Constructor with copy initialization.
Definition at line 137 of file IncrModCtlVec.h.
     : incrModCtlVec_() {
   Log::trace() << "IncrModCtlVec<MODEL>::IncrModCtlVec starting" << std::endl;
   util::Timer timer(classname(), "Incr");
   if (other.incrModCtlVec_ != 0) {
     incrModCtlVec_.reset(
         new IncrModCtlVec_(cov.errorCovariance(), *other.incrModCtlVec_));
   }
   Log::trace() << "IncrModCtlVec<MODEL>::IncrModCtlVec done" << std::endl;
 }
References oops::IncrModCtlVec< MODEL >::classname(), oops::ErrorCovariance< MODEL >::errorCovariance(), and oops::IncrModCtlVec< MODEL >::incrModCtlVec_.
IncrModCtlVec() [4/4]
template<typename MODEL > oops::IncrModCtlVec< MODEL >::IncrModCtlVec (const IncrModCtlVec< MODEL > & other, const bool copy = true)
Copy constructor.
Definition at line 152 of file IncrModCtlVec.h.
     : incrModCtlVec_() {
   Log::trace() << "IncrModCtlVec<MODEL>::IncrModCtlVec copy starting"
                << std::endl;
   util::Timer timer(classname(), "Incr");
   if (other.incrModCtlVec_ != 0) {
     incrModCtlVec_.reset(new IncrModCtlVec_(*other.incrModCtlVec_, copy));
   }
   Log::trace() << "IncrModCtlVec<MODEL>::IncrModCtlVec copy done" << std::endl;
 }
References oops::IncrModCtlVec< MODEL >::classname(), and oops::IncrModCtlVec< MODEL >::incrModCtlVec_.
~IncrModCtlVec()
template<typename MODEL > oops::IncrModCtlVec< MODEL >::~IncrModCtlVec virtual
Destructor.
Definition at line 166 of file IncrModCtlVec.h.
{
   Log::trace() << "IncrModCtlVec<MODEL>::~IncrModCtlVec starting" << std::endl;
   util::Timer timer(classname(), "~Incr");
   incrModCtlVec_.reset();
   Log::trace() << "IncrModCtlVec<MODEL>::~IncrModCtlVec done" << std::endl;
 }
Member Function Documentation
axpy()
template<typename MODEL > void oops::IncrModCtlVec< MODEL >::axpy (const double & zz, const IncrModCtlVec< MODEL > & dx, const bool check = true)
\(dv_1 = dv_1 * c dv_2 \)
Definition at line 243 of file IncrModCtlVec.h.
{
   Log::trace() << "IncrModCtlVec<MODEL>::axpy starting" << std::endl;
   util::Timer timer(classname(), "axpy");
   if (incrModCtlVec_ != 0) incrModCtlVec_->axpy(zz, *dx.incrModCtlVec_, check);
   Log::trace() << "IncrModCtlVec<MODEL>::axpy done" << std::endl;
 }
classname()
template<typename MODEL > static const std::string oops::IncrModCtlVec< MODEL >::classname () inline static
Definition at line 56 of file IncrModCtlVec.h.
 { return "oops::IncrModCtlVec"; }
Referenced by oops::IncrModCtlVec< MODEL >::IncrModCtlVec().
ctlVec() [1/2]
template<typename MODEL > IncrModCtlVec_& oops::IncrModCtlVec< MODEL >::ctlVec () inline
Get control vector.
Definition at line 105 of file IncrModCtlVec.h.
 { return *incrModCtlVec_; }
References oops::IncrModCtlVec< MODEL >::incrModCtlVec_.
Referenced by oops::ErrorCovariance< MODEL >::multiplySqrt(), and oops::ErrorCovariance< MODEL >::multiplySqrtTrans().
ctlVec() [2/2]
template<typename MODEL > const IncrModCtlVec_& oops::IncrModCtlVec< MODEL >::ctlVec () const inline
Get constant control vector.
Definition at line 107 of file IncrModCtlVec.h.
 { return *incrModCtlVec_; }
References oops::IncrModCtlVec< MODEL >::incrModCtlVec_.
dot_product_with()
template<typename MODEL > double oops::IncrModCtlVec< MODEL >::dot_product_with (const IncrModCtlVec< MODEL > & dx) const
\(<dv_1,dv_1> = dv_1^T dv_1 \)
Definition at line 254 of file IncrModCtlVec.h.
{
   Log::trace() << "IncrModCtlVec<MODEL>::dot_product_with starting"
                << std::endl;
   util::Timer timer(classname(), "dot_product_with");
   double zz = 0.0;
   if (incrModCtlVec_ != 0)
     zz += incrModCtlVec_->dot_product_with(*dx.incrModCtlVec_);
   Log::trace() << "IncrModCtlVec<MODEL>::dot_product_with done" << std::endl;
   return zz;
 }
getSection()
template<typename MODEL > void oops::IncrModCtlVec< MODEL >::getSection (std::vector< double > & section, const int & iistart, const int & iiend) const
Get section of the control vector.
Definition at line 290 of file IncrModCtlVec.h.
{
   Log::trace() << "IncrModCtlVec<MODEL>::getSection starting" << std::endl;
   util::Timer timer(classname(), "getSection");
   if (incrModCtlVec_ != 0) incrModCtlVec_->getSection(section, iistart, iiend);
   Log::trace() << "IncrModCtlVec<MODEL>::getSection done" << std::endl;
 }
norm()
template<typename MODEL > double oops::IncrModCtlVec< MODEL >::norm
L-2 norm.
Definition at line 333 of file IncrModCtlVec.h.
{
   Log::trace() << "IncrModCtlVec<MODEL>::norm starting" << std::endl;
   util::Timer timer(classname(), "norm");
   double zz = 0.0;
   if (incrModCtlVec_ != 0) zz += incrModCtlVec_->norm();
   Log::trace() << "IncrModCtlVec<MODEL>::norm done" << std::endl;
   return zz;
 }
operator*=()
template<typename MODEL > IncrModCtlVec< MODEL > & oops::IncrModCtlVec< MODEL >::operator*= (const double & zz)
\(dv_1 = dv_1 * c \)
Definition at line 232 of file IncrModCtlVec.h.
{
   Log::trace() << "IncrModCtlVec<MODEL>::operator*= starting" << std::endl;
   util::Timer timer(classname(), "operator*=");
   if (incrModCtlVec_ != 0) *incrModCtlVec_ *= zz;
   Log::trace() << "IncrModCtlVec<MODEL>::operator*= done" << std::endl;
   return *this;
 }
operator+=()
template<typename MODEL > IncrModCtlVec< MODEL > & oops::IncrModCtlVec< MODEL >::operator+= (const IncrModCtlVec< MODEL > & rhs)
\(dv_1 = dv_1 + dv_2 \)
Definition at line 208 of file IncrModCtlVec.h.
{
   Log::trace() << "IncrModCtlVec<MODEL>::operator+= starting" << std::endl;
   util::Timer timer(classname(), "operator+=");
   if (incrModCtlVec_ != 0) *incrModCtlVec_ += *rhs.incrModCtlVec_;
   Log::trace() << "IncrModCtlVec<MODEL>::operator+= done" << std::endl;
   return *this;
 }
operator-=()
template<typename MODEL > IncrModCtlVec< MODEL > & oops::IncrModCtlVec< MODEL >::operator-= (const IncrModCtlVec< MODEL > & rhs)
\(dv_1 = dv_1 - dv_2 \)
Definition at line 220 of file IncrModCtlVec.h.
{
   Log::trace() << "IncrModCtlVec<MODEL>::operator-= starting" << std::endl;
   util::Timer timer(classname(), "operator-=");
   if (incrModCtlVec_ != 0) *incrModCtlVec_ -= *rhs.incrModCtlVec_;
   Log::trace() << "IncrModCtlVec<MODEL>::operator-= done" << std::endl;
   return *this;
 }
operator=()
template<typename MODEL > IncrModCtlVec< MODEL > & oops::IncrModCtlVec< MODEL >::operator= (const IncrModCtlVec< MODEL > & rhs)
\(dv_1 = dv_2 \)
Definition at line 196 of file IncrModCtlVec.h.
{
   Log::trace() << "IncrModCtlVec<MODEL>::operator= starting" << std::endl;
   util::Timer timer(classname(), "operator=");
   if (incrModCtlVec_ != 0) *incrModCtlVec_ = *rhs.incrModCtlVec_;
   Log::trace() << "IncrModCtlVec<MODEL>::operator= done" << std::endl;
   return *this;
 }
print()
template<typename MODEL > void oops::IncrModCtlVec< MODEL >::print (std::ostream & os) const private
Definition at line 345 of file IncrModCtlVec.h.
{
   Log::trace() << "IncrModCtlVec<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   if (incrModCtlVec_ != 0) os << *incrModCtlVec_;
   Log::trace() << "IncrModCtlVec<MODEL>::print done" << std::endl;
 }
random()
template<typename MODEL > void oops::IncrModCtlVec< MODEL >::random
Random control vector.
Definition at line 280 of file IncrModCtlVec.h.
{
   Log::trace() << "IncrModCtlVec<MODEL>::random starting" << std::endl;
   util::Timer timer(classname(), "random");
   if (incrModCtlVec_ != 0) incrModCtlVec_->random();
   Log::trace() << "IncrModCtlVec<MODEL>::random done" << std::endl;
 }
read()
template<typename MODEL > void oops::IncrModCtlVec< MODEL >::read (const eckit::Configuration & conf)
Read control vector.
Definition at line 313 of file IncrModCtlVec.h.
{
   Log::trace() << "IncrModCtlVec<MODEL>::read starting" << std::endl;
   util::Timer timer(classname(), "read");
   if (incrModCtlVec_ != 0) incrModCtlVec_->read(conf);
   Log::trace() << "IncrModCtlVec<MODEL>::read done" << std::endl;
 }
schur_product_with()
template<typename MODEL > void oops::IncrModCtlVec< MODEL >::schur_product_with (const IncrModCtlVec< MODEL > & dx)
Hadamard product (element-wise)
Definition at line 268 of file IncrModCtlVec.h.
{
   Log::trace() << "IncrModCtlVec<MODEL>::schur_product_with starting"
                << std::endl;
   util::Timer timer(classname(), "schur_product_with");
   if (incrModCtlVec_ != 0)
     incrModCtlVec_->schur_product_with(*dx.incrModCtlVec_);
   Log::trace() << "IncrModCtlVec<MODEL>::schur_product_with done" << std::endl;
 }
setSection()
template<typename MODEL > void oops::IncrModCtlVec< MODEL >::setSection (const std::vector< double > & section, const int & iistart, const int & iiend)
Set section of the control vector.
Definition at line 302 of file IncrModCtlVec.h.
{
   Log::trace() << "IncrModCtlVec<MODEL>::setSection starting" << std::endl;
   util::Timer timer(classname(), "setSection");
   if (incrModCtlVec_ != 0) incrModCtlVec_->setSection(section, iistart, iiend);
   Log::trace() << "IncrModCtlVec<MODEL>::setSection done" << std::endl;
 }
write()
template<typename MODEL > void oops::IncrModCtlVec< MODEL >::write (const eckit::Configuration & conf) const
Write control vector.
Definition at line 323 of file IncrModCtlVec.h.
{
   Log::trace() << "IncrModCtlVec<MODEL>::write starting" << std::endl;
   util::Timer timer(classname(), "write");
   if (incrModCtlVec_ != 0) incrModCtlVec_->write(conf);
   Log::trace() << "IncrModCtlVec<MODEL>::write done" << std::endl;
 }
zero()
template<typename MODEL > void oops::IncrModCtlVec< MODEL >::zero
\(dv_1 = 0 \)
Definition at line 176 of file IncrModCtlVec.h.
{
   Log::trace() << "IncrModCtlVec<MODEL>::zero starting" << std::endl;
   util::Timer timer(classname(), "zero");
   if (incrModCtlVec_ != 0) incrModCtlVec_->zero();
   Log::trace() << "IncrModCtlVec<MODEL>::zero done" << std::endl;
 }
Member Data Documentation
incrModCtlVec_
template<typename MODEL > std::unique_ptr<IncrModCtlVec_> oops::IncrModCtlVec< MODEL >::incrModCtlVec_ private
Model specific implementation.
Definition at line 113 of file IncrModCtlVec.h.
Referenced by oops::IncrModCtlVec< MODEL >::ctlVec(), and oops::IncrModCtlVec< MODEL >::IncrModCtlVec().
The documentation for this class was generated from the following files:
src/oops/assimilation/CostJbState.h
src/oops/interface/IncrModCtlVec.h