OOPS Documentation: oops::Departures< MODEL > Class Template Reference
oops::Departures< MODEL > Class Template Reference
Difference between two observation vectors.
#include <Departures.h>
Public Member Functions
Departures (const ObsSpaces_ &)
Constructor.
Departures (std::vector< std::shared_ptr< ControlObsVector_ > >)
Constructor.
Departures (const Departures &)
Copy constructor.
~Departures ()
Destructor.
std::size_t size () const
Return the number of components.
const ControlObsVector_ & operator[] (const std::size_t ii) const
Return a constant reference to i-th component.
ControlObsVector_ & operator[] (const std::size_t ii)
Return a reference to i-th component.
Departures & operator= (const Departures &)
\(d1 = d2 \)
Departures & operator+= (const Departures &)
\(d1 = d1 + d2 \)
Departures & operator-= (const Departures &)
\(d1 = d1 - d2 \)
Departures & operator*= (const double &)
\(d1 = c*d1 \)
Departures & operator*= (const Departures &)
\(d1 = d1*d2 \)
Departures & operator/= (const Departures &)
\(d1 = d1/d2 \)
void zero ()
\(d1 = 0 \)
void invert ()
\(d1 = 1/d1 \)
void axpy (const double &, const Departures &)
\(d1 = d1 + c*d2 \)
double dot_product_with (const Departures &) const
\(<d1, d1> = d1^T d1\)
const ControlObsVector_ & depvalues () const
Get departue values.
void save (const eckit::Configuration &) const
Write departures.
void read (const eckit::Configuration &)
Read departures.
Public Member Functions inherited from oops::GeneralizedDepartures
GeneralizedDepartures ()
virtual ~GeneralizedDepartures ()
Private Types
using ControlObsVector_ = ControlObsVector< MODEL >
using ObsErrorBase_ = ObsErrorBase< MODEL >
using ObsSpaces_ = ObservationSpaces< MODEL >
Private Member Functions
void print (std::ostream &) const
Private Attributes
std::vector< std::shared_ptr< ControlObsVector_ > > dep_
Vector of shared pointers to ControlObsVector objects.
Detailed Description
template<typename MODEL>
class oops::Departures< MODEL >
Difference between two observation vectors.
A departure is the difference between two observations. The archetypal example is
\[ d = y - {\cal G}(x) = \begin{bmatrix} \bar{y}_1 \\ .. \\ \bar{y}_L \end{bmatrix} - \begin{bmatrix} \bar{\cal G}_1 && .. && .. \\ .. && .. && .. \\ .. && .. && \bar{\cal G}_L \end{bmatrix} \begin{bmatrix} \bar{x}_1 \\ .. \\ \bar{x}_L \end{bmatrix} \]
where
\[ \bar{y}_j = \begin{bmatrix} \tilde{y}_j \\ \tilde{b}_j \\ \end{bmatrix} \]
and
\[ \bar{\cal G}_j = \begin{bmatrix} \tilde{\cal G}_j && \tilde{\cal P}_j \\ 0 && \tilde{\cal P}_j \end{bmatrix} \]
\[ \bar{x}_j = \begin{bmatrix} x \\ \beta_j \end{bmatrix} \]
and \(L \) is the number of ObservationSpace objects held by ObservationSpaces, \(\bar{y}_j \) is implemented by ControlObsVector and has two components: observation \(\tilde{y}_j \) and bias \(\tilde{b}_j \) vectors (each implemented by ObsVector).
Departures hold a vector of ControlObsVector objects.
Keeping an observation space vector here is necessary for the implementation of generic observation error covariance matrices.
Refer to the documentation of CostJo to better understand the structure.
Definition at line 95 of file Departures.h.
Member Typedef Documentation
ControlObsVector_
template<typename MODEL > using oops::Departures< MODEL >::ControlObsVector_ = ControlObsVector<MODEL> private
Definition at line 96 of file Departures.h.
ObsErrorBase_
template<typename MODEL > using oops::Departures< MODEL >::ObsErrorBase_ = ObsErrorBase<MODEL> private
Definition at line 97 of file Departures.h.
ObsSpaces_
template<typename MODEL > using oops::Departures< MODEL >::ObsSpaces_ = ObservationSpaces<MODEL> private
Definition at line 98 of file Departures.h.
Constructor & Destructor Documentation
Departures() [1/3]
template<typename MODEL > oops::Departures< MODEL >::Departures (const ObsSpaces_ & obsgeom) explicit
Constructor.
Definition at line 160 of file Departures.h.
                                                        : dep_(0) {
   for (std::size_t jj = 0; jj < obsgeom.size(); ++jj) {
     std::shared_ptr<ControlObsVector_> tmp(new ControlObsVector_(obsgeom[jj]));
     dep_.push_back(tmp);
   }
   Log::trace() << "Departures created" << std::endl;
 }
References oops::Departures< MODEL >::dep_, and oops::ObservationSpaces< MODEL >::size().
Departures() [2/3]
template<typename MODEL > oops::Departures< MODEL >::Departures (std::vector< std::shared_ptr< ControlObsVector_ > > val) explicit
Constructor.
Definition at line 169 of file Departures.h.
     : dep_(val) {
   Log::trace() << "Departures created" << std::endl;
 }
Departures() [3/3]
template<typename MODEL > oops::Departures< MODEL >::Departures (const Departures< MODEL > & other) explicit
Copy constructor.
Definition at line 176 of file Departures.h.
                                                      : dep_(0) {
   // We want deep copy here
   for (std::size_t jj = 0; jj < other.dep_.size(); ++jj) {
     std::shared_ptr<ControlObsVector_> tmp(
         new ControlObsVector_(*other.dep_[jj]));
     dep_.push_back(tmp);
   }
   Log::trace() << "Departures copy-created" << std::endl;
 }
References oops::Departures< MODEL >::dep_.
~Departures()
template<typename MODEL > oops::Departures< MODEL >::~Departures
Destructor.
Definition at line 187 of file Departures.h.
{
   Log::trace() << "Departures destructed" << std::endl;
 }
Member Function Documentation
axpy()
template<typename MODEL > void oops::Departures< MODEL >::axpy (const double & zz, const Departures< MODEL > & rhs)
\(d1 = d1 + c*d2 \)
Definition at line 254 of file Departures.h.
{
   for (std::size_t jj = 0; jj < dep_.size(); ++jj) {
     dep_[jj]->axpy(zz, *rhs.dep_[jj]);
   }
 }
References oops::Departures< MODEL >::dep_.
depvalues()
template<typename MODEL > const ControlObsVector_& oops::Departures< MODEL >::depvalues () const inline
Get departue values.
Definition at line 142 of file Departures.h.
 { return *dep_; }
References oops::Departures< MODEL >::dep_.
dot_product_with()
template<typename MODEL > double oops::Departures< MODEL >::dot_product_with (const Departures< MODEL > & other) const
\(<d1, d1> = d1^T d1\)
Definition at line 261 of file Departures.h.
{
   double zz = 0.0;
   for (std::size_t jj = 0; jj < dep_.size(); ++jj) {
     zz += dot_product(*dep_[jj], *other.dep_[jj]);
   }
   return zz;
 }
References oops::Departures< MODEL >::dep_, and dot_product().
invert()
template<typename MODEL > void oops::Departures< MODEL >::invert
\(d1 = 1/d1 \)
Definition at line 247 of file Departures.h.
{
   for (std::size_t jj = 0; jj < dep_.size(); ++jj) {
     dep_[jj]->invert();
   }
 }
operator*=() [1/2]
template<typename MODEL > Departures< MODEL > & oops::Departures< MODEL >::operator*= (const Departures< MODEL > & rhs)
\(d1 = d1*d2 \)
Definition at line 224 of file Departures.h.
{
   for (std::size_t jj = 0; jj < dep_.size(); ++jj) {
     *dep_[jj] *= *rhs.dep_[jj];
   }
   return *this;
 }
References oops::Departures< MODEL >::dep_.
operator*=() [2/2]
template<typename MODEL > Departures< MODEL > & oops::Departures< MODEL >::operator*= (const double & zz)
\(d1 = c*d1 \)
Definition at line 216 of file Departures.h.
{
   for (std::size_t jj = 0; jj < dep_.size(); ++jj) {
     *dep_[jj] *= zz;
   }
   return *this;
 }
operator+=()
template<typename MODEL > Departures< MODEL > & oops::Departures< MODEL >::operator+= (const Departures< MODEL > & rhs)
\(d1 = d1 + d2 \)
Definition at line 200 of file Departures.h.
{
   for (std::size_t jj = 0; jj < dep_.size(); ++jj) {
     *dep_[jj] += *rhs.dep_[jj];
   }
   return *this;
 }
References oops::Departures< MODEL >::dep_.
operator-=()
template<typename MODEL > Departures< MODEL > & oops::Departures< MODEL >::operator-= (const Departures< MODEL > & rhs)
\(d1 = d1 - d2 \)
Definition at line 208 of file Departures.h.
{
   for (std::size_t jj = 0; jj < dep_.size(); ++jj) {
     *dep_[jj] -= *rhs.dep_[jj];
   }
   return *this;
 }
References oops::Departures< MODEL >::dep_.
operator/=()
template<typename MODEL > Departures< MODEL > & oops::Departures< MODEL >::operator/= (const Departures< MODEL > & rhs)
\(d1 = d1/d2 \)
Definition at line 232 of file Departures.h.
{
   for (std::size_t jj = 0; jj < dep_.size(); ++jj) {
     *dep_[jj] /= *rhs.dep_[jj];
   }
   return *this;
 }
References oops::Departures< MODEL >::dep_.
operator=()
template<typename MODEL > Departures< MODEL > & oops::Departures< MODEL >::operator= (const Departures< MODEL > & rhs)
\(d1 = d2 \)
Definition at line 192 of file Departures.h.
{
   for (std::size_t jj = 0; jj < dep_.size(); ++jj) {
     *dep_[jj] = *rhs.dep_[jj];
   }
   return *this;
 }
References oops::Departures< MODEL >::dep_.
operator[]() [1/2]
template<typename MODEL > ControlObsVector_& oops::Departures< MODEL >::operator[] (const std::size_t ii) inline
Return a reference to i-th component.
Definition at line 117 of file Departures.h.
 { return *dep_.at(ii); }
References oops::Departures< MODEL >::dep_.
operator[]() [2/2]
template<typename MODEL > const ControlObsVector_& oops::Departures< MODEL >::operator[] (const std::size_t ii) const inline
Return a constant reference to i-th component.
Definition at line 113 of file Departures.h.
{
     return *dep_.at(ii);
   }
References oops::Departures< MODEL >::dep_.
print()
template<typename MODEL > void oops::Departures< MODEL >::print (std::ostream & os) const private
Definition at line 288 of file Departures.h.
{
   for (std::size_t jj = 0; jj < dep_.size(); ++jj) {
     os << *dep_[jj];
   }
 }
read()
template<typename MODEL > void oops::Departures< MODEL >::read (const eckit::Configuration & conf)
Read departures.
Definition at line 279 of file Departures.h.
{
   for (std::size_t jj = 0; jj < dep_.size(); ++jj) {
     dep_[jj]->read(conf);
   }
   Log::trace() << "Departures:Departures have been read: " << conf << std::endl;
 }
Referenced by oops::CostJo< MODEL >::initialize().
save()
template<typename MODEL > void oops::Departures< MODEL >::save (const eckit::Configuration & conf) const
Write departures.
Definition at line 270 of file Departures.h.
{
   for (std::size_t jj = 0; jj < dep_.size(); ++jj) {
     dep_[jj]->save(conf);
   }
   Log::trace() << "Departures:Departures have been saved: " << conf
                << std::endl;
 }
Referenced by oops::CostJo< MODEL >::finalizeTraj().
size()
template<typename MODEL > std::size_t oops::Departures< MODEL >::size () const inline
Return the number of components.
Definition at line 111 of file Departures.h.
 { return dep_.size(); }
References oops::Departures< MODEL >::dep_.
Referenced by oops::CostJo< MODEL >::finalizeTraj(), and oops::CostJo< MODEL >::printJo().
zero()
template<typename MODEL > void oops::Departures< MODEL >::zero
\(d1 = 0 \)
Definition at line 240 of file Departures.h.
{
   for (std::size_t jj = 0; jj < dep_.size(); ++jj) {
     dep_[jj]->zero();
   }
 }
Referenced by oops::CostJo< MODEL >::newDualVector().
Member Data Documentation
dep_
template<typename MODEL > std::vector<std::shared_ptr<ControlObsVector_> > oops::Departures< MODEL >::dep_ private
Vector of shared pointers to ControlObsVector objects.
Definition at line 154 of file Departures.h.
Referenced by oops::Departures< MODEL >::axpy(), oops::Departures< MODEL >::Departures(), oops::Departures< MODEL >::depvalues(), oops::Departures< MODEL >::dot_product_with(), oops::Departures< MODEL >::operator*=(), oops::Departures< MODEL >::operator+=(), oops::Departures< MODEL >::operator-=(), oops::Departures< MODEL >::operator/=(), oops::Departures< MODEL >::operator=(), oops::Departures< MODEL >::operator[](), and oops::Departures< MODEL >::size().
The documentation for this class was generated from the following file:
src/oops/base/Departures.h