OOPS Documentation: oops::HorizScaleDecomposition< MODEL > Class Template Reference
oops::HorizScaleDecomposition< MODEL > Class Template Reference
#include <HorizScaleDecomposition.h>
Public Member Functions
HorizScaleDecomposition (const eckit::Configuration &)
HorizScaleDecomposition (const HorizScaleDecomposition &)
virtual ~HorizScaleDecomposition ()
void collect (const Increment_ &, const int &) const
void decompose (const Increment_ &, const int &) const
Static Public Member Functions
static const std::string classname ()
Private Types
using HorizScaleDecomposition_ = typename MODEL::HorizScaleDecomposition
using Geometry_ = Geometry< MODEL >
using Increment_ = Increment< MODEL >
Private Attributes
std::unique_ptr< HorizScaleDecomposition_ > horiz_sd_
Friends
std::ostream & operator<< (std::ostream &os, const HorizScaleDecomposition &loc)
Diagnostics.
Detailed Description
template<typename MODEL>
class oops::HorizScaleDecomposition< MODEL >
Definition at line 36 of file HorizScaleDecomposition.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::HorizScaleDecomposition< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 40 of file HorizScaleDecomposition.h.
HorizScaleDecomposition_
template<typename MODEL > using oops::HorizScaleDecomposition< MODEL >::HorizScaleDecomposition_ = typename MODEL::HorizScaleDecomposition private
Definition at line 39 of file HorizScaleDecomposition.h.
Increment_
template<typename MODEL > using oops::HorizScaleDecomposition< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 41 of file HorizScaleDecomposition.h.
Constructor & Destructor Documentation
HorizScaleDecomposition() [1/2]
template<typename MODEL > oops::HorizScaleDecomposition< MODEL >::HorizScaleDecomposition (const eckit::Configuration & conf)
Definition at line 69 of file HorizScaleDecomposition.h.
     : horiz_sd_() {
   Log::trace()
       << "HorizScaleDecomposition<MODEL>::HorizScaleDecomposition starting";
   util::Timer timer(classname(), "HorizScaleDecomposition");
   horiz_sd_.reset(new HorizScaleDecomposition_(conf));
   Log::trace()
       << "HorizScaleDecomposition<MODEL>::HorizScaleDecomposition done";
 }
References oops::HorizScaleDecomposition< MODEL >::classname(), and oops::HorizScaleDecomposition< MODEL >::horiz_sd_.
HorizScaleDecomposition() [2/2]
template<typename MODEL > oops::HorizScaleDecomposition< MODEL >::HorizScaleDecomposition (const HorizScaleDecomposition< MODEL > & other) explicit
Definition at line 81 of file HorizScaleDecomposition.h.
     : horiz_sd_() {
   Log::trace()
       << "HorizScaleDecomposition<MODEL>::HorizScaleDecomposition starting";
   util::Timer timer(classname(), "HorizScaleDecomposition");
   Log::trace()
       << "HorizScaleDecomposition<MODEL>::HorizScaleDecomposition done";
 }
References oops::HorizScaleDecomposition< MODEL >::classname().
~HorizScaleDecomposition()
template<typename MODEL > oops::HorizScaleDecomposition< MODEL >::~HorizScaleDecomposition virtual
Definition at line 94 of file HorizScaleDecomposition.h.
{
   Log::trace()
       << "HorizScaleDecomposition<MODEL>::~HorizScaleDecomposition starting";
   util::Timer timer(classname(), "~HorizScaleDecomposition");
   horiz_sd_.reset();
   Log::trace()
       << "HorizScaleDecomposition<MODEL>::~HorizScaleDecomposition done";
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::HorizScaleDecomposition< MODEL >::classname () inline static
Definition at line 44 of file HorizScaleDecomposition.h.
{
     return "oops::HorizScaleDecomposition";
   }
Referenced by oops::HorizScaleDecomposition< MODEL >::HorizScaleDecomposition().
collect()
template<typename MODEL > void oops::HorizScaleDecomposition< MODEL >::collect (const Increment_ & dx, const int & band_index) const
Definition at line 106 of file HorizScaleDecomposition.h.
{
   Log::trace() << "HorizScaleDecomposition<MODEL>::horizScaleCollect starting";
   util::Timer timer(classname(), "horizScaleCollect");
   horiz_sd_->collect(dx.increment(), band_index);
   Log::trace() << "HorizScaleDecomposition<MODEL>::horizScaleCollect done";
 }
References oops::Increment< MODEL >::increment().
Referenced by oops::EnsembleCovariance4DScaleDependent< MODEL >::advectedLinearize(), oops::EnsembleCovsInterpolSDL< MODEL >::linearize(), and oops::EnsembleCovarianceSDL< MODEL >::linearize().
decompose()
template<typename MODEL > void oops::HorizScaleDecomposition< MODEL >::decompose (const Increment_ & dx, const int & SDLtype) const
Definition at line 117 of file HorizScaleDecomposition.h.
{
   Log::trace() << "HorizScaleDecomposition<MODEL>::decompose starting";
   util::Timer timer(classname(), "decompose");
   horiz_sd_->decompose(dx.increment(), SDLtype);
   Log::trace() << "HorizScaleDecomposition<MODEL>::decompose done";
 }
References oops::Increment< MODEL >::increment().
Referenced by oops::EnsembleCovariance4DScaleDependent< MODEL >::advectedLinearize(), oops::EnsembleCovsInterpolSDL< MODEL >::linearize(), and oops::EnsembleCovarianceSDL< MODEL >::linearize().
Friends And Related Function Documentation
operator<<
template<typename MODEL > std::ostream& operator<< (std::ostream & os, const HorizScaleDecomposition< MODEL > & loc) friend
Diagnostics.
Definition at line 56 of file HorizScaleDecomposition.h.
{
     // loc.print(os);
     return os;
   }
Member Data Documentation
horiz_sd_
template<typename MODEL > std::unique_ptr<HorizScaleDecomposition_> oops::HorizScaleDecomposition< MODEL >::horiz_sd_ private
Definition at line 63 of file HorizScaleDecomposition.h.
Referenced by oops::HorizScaleDecomposition< MODEL >::HorizScaleDecomposition().
The documentation for this class was generated from the following file:
src/oops/interface/HorizScaleDecomposition.h