OOPS Documentation: oops::BMatrix< MODEL > Class Template Reference
oops::BMatrix< MODEL > Class Template Reference
The \(B \) matrix.
#include <BMatrix.h>
Public Member Functions
BMatrix (const CostFct_ &j)
void multiply (const CtrlInc_ &x, CtrlInc_ &bx) const
void multiplySqrt (const CtrlVec_ &dv, CtrlInc_ &dx) const
void multiplySqrtTrans (const CtrlInc_ &dx, CtrlVec_ &dv) const
void multiplyId (const CtrlInc_ &dx, CtrlInc_ &jbdx) const
void multiplyB (const CtrlInc_ &dx, CtrlInc_ &jbdx) const
Private Types
using CtrlInc_ = ControlIncrement< MODEL >
using CtrlVec_ = ControlVector< MODEL >
using CostFct_ = CostFunction< MODEL >
using ObsAuxIncrements_ = ObsAuxIncrements< MODEL >
using ObsAuxCtlVecs_ = ObsAuxCtlVecs< MODEL >
Private Attributes
CostFct_ const & j_
ObsAuxIncrements_ dxObsAux_
ObsAuxCtlVecs_ dvObsAux_
Detailed Description
template<typename MODEL>
class oops::BMatrix< MODEL >
The \(B \) matrix.
The solvers represent matrices as objects that implement a "multiply" method. This class defines objects that apply the \(B \) matrix.
Definition at line 29 of file BMatrix.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::BMatrix< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 32 of file BMatrix.h.
CtrlInc_
template<typename MODEL > using oops::BMatrix< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 30 of file BMatrix.h.
CtrlVec_
template<typename MODEL > using oops::BMatrix< MODEL >::CtrlVec_ = ControlVector<MODEL> private
Definition at line 31 of file BMatrix.h.
ObsAuxCtlVecs_
template<typename MODEL > using oops::BMatrix< MODEL >::ObsAuxCtlVecs_ = ObsAuxCtlVecs<MODEL> private
Definition at line 34 of file BMatrix.h.
ObsAuxIncrements_
template<typename MODEL > using oops::BMatrix< MODEL >::ObsAuxIncrements_ = ObsAuxIncrements<MODEL> private
Definition at line 33 of file BMatrix.h.
Constructor & Destructor Documentation
BMatrix()
template<typename MODEL > oops::BMatrix< MODEL >::BMatrix (const CostFct_ & j) inline explicit
Definition at line 37 of file BMatrix.h.
       : j_(j),
         dxObsAux_(j.jb().getFirstGuessIncrement().obsVar(), false),
         dvObsAux_(j.jb().jbObsBias()) {}
Member Function Documentation
multiply()
template<typename MODEL > void oops::BMatrix< MODEL >::multiply (const CtrlInc_ & x, CtrlInc_ & bx) const inline
Definition at line 41 of file BMatrix.h.
{
     j_.jb().multiplyB(x, bx);
   }
References oops::BMatrix< MODEL >::j_, oops::CostFunction< MODEL >::jb(), and oops::CostJbTotal< MODEL >::multiplyB().
Referenced by oops::DualMinimizer< MODEL >::doMinimize(), oops::DRMinimizer< MODEL >::doMinimize(), oops::DRPFOMMinimizer< MODEL >::solve(), oops::DRIPCGMinimizer< MODEL >::solve(), oops::DRGMRESRMinimizer< MODEL >::solve(), and oops::DRPCGMinimizer< MODEL >::solve().
multiplyB()
template<typename MODEL > void oops::BMatrix< MODEL >::multiplyB (const CtrlInc_ & dx, CtrlInc_ & jbdx) const inline
= | B | | U'U'^T | where B = UU^T and U' does not have to be equal to U
Definition at line 74 of file BMatrix.h.
{
     // State part
     j_.jb().jbState().Bmult(dx.state(), jbdx.state());
     // Mod Aux part
     jbdx.modVar() = dx.modVar();
     // Obs Aux part
     dvObsAux_.zero();
     // U'^T
     j_.jb().jbObsBias().multiplySqrtTrans(dx.obsVar(), dvObsAux_);
     // U' U'^T
     j_.jb().jbObsBias().multiplySqrt(dvObsAux_, jbdx.obsVar());
   }
References oops::CostJbState< MODEL >::Bmult(), oops::BMatrix< MODEL >::dvObsAux_, oops::BMatrix< MODEL >::j_, oops::CostFunction< MODEL >::jb(), oops::CostJbTotal< MODEL >::jbObsBias(), oops::CostJbTotal< MODEL >::jbState(), oops::ControlIncrement< MODEL >::modVar(), oops::ObsAuxCovariances< MODEL >::multiplySqrt(), oops::ObsAuxCovariances< MODEL >::multiplySqrtTrans(), oops::ControlIncrement< MODEL >::obsVar(), oops::ControlIncrement< MODEL >::state(), and oops::ObsAuxCtlVecs< MODEL >::zero().
Referenced by oops::DRPLanczosMinimizer< MODEL >::solve().
multiplyId()
template<typename MODEL > void oops::BMatrix< MODEL >::multiplyId (const CtrlInc_ & dx, CtrlInc_ & jbdx) const inline
= | I | | B^-1 U'U'^T | where B = UU^T and U' does not have to be equal to U
Definition at line 50 of file BMatrix.h.
{
     // State part
     jbdx.state() = dx.state();
     // Mod Aux part
     jbdx.modVar() = dx.modVar();
     // Obs Aux part
     dvObsAux_.zero();
     dxObsAux_.zero();
     // U'^T
     j_.jb().jbObsBias().multiplySqrtTrans(dx.obsVar(), dvObsAux_);
     // U' U'^T
     j_.jb().jbObsBias().multiplySqrt(dvObsAux_, dxObsAux_);
     // B^-1 U' U'^T
     j_.jb().jbObsBias().inverseMultiply(dxObsAux_, jbdx.obsVar());
   }
References oops::BMatrix< MODEL >::dvObsAux_, oops::BMatrix< MODEL >::dxObsAux_, oops::ObsAuxCovariances< MODEL >::inverseMultiply(), oops::BMatrix< MODEL >::j_, oops::CostFunction< MODEL >::jb(), oops::CostJbTotal< MODEL >::jbObsBias(), oops::ControlIncrement< MODEL >::modVar(), oops::ObsAuxCovariances< MODEL >::multiplySqrt(), oops::ObsAuxCovariances< MODEL >::multiplySqrtTrans(), oops::ControlIncrement< MODEL >::obsVar(), oops::ControlIncrement< MODEL >::state(), oops::ObsAuxCtlVecs< MODEL >::zero(), and oops::ObsAuxIncrements< MODEL >::zero().
Referenced by oops::DRPLanczosMinimizer< MODEL >::solve().
multiplySqrt()
template<typename MODEL > void oops::BMatrix< MODEL >::multiplySqrt (const CtrlVec_ & dv, CtrlInc_ & dx) const inline
Definition at line 44 of file BMatrix.h.
{
     j_.jb().multiplyBsqrt(dv, dx);
   }
References oops::BMatrix< MODEL >::j_, oops::CostFunction< MODEL >::jb(), and oops::CostJbTotal< MODEL >::multiplyBsqrt().
Referenced by oops::SQRTMinimizer< MODEL >::doMinimize().
multiplySqrtTrans()
template<typename MODEL > void oops::BMatrix< MODEL >::multiplySqrtTrans (const CtrlInc_ & dx, CtrlVec_ & dv) const inline
Definition at line 47 of file BMatrix.h.
{
     j_.jb().multiplyBsqrtTrans(dx, dv);
   }
References oops::BMatrix< MODEL >::j_, oops::CostFunction< MODEL >::jb(), and oops::CostJbTotal< MODEL >::multiplyBsqrtTrans().
Referenced by oops::SQRTMinimizer< MODEL >::doMinimize().
Member Data Documentation
dvObsAux_
template<typename MODEL > ObsAuxCtlVecs_ oops::BMatrix< MODEL >::dvObsAux_ mutable private
Definition at line 99 of file BMatrix.h.
Referenced by oops::BMatrix< MODEL >::multiplyB(), and oops::BMatrix< MODEL >::multiplyId().
dxObsAux_
template<typename MODEL > ObsAuxIncrements_ oops::BMatrix< MODEL >::dxObsAux_ mutable private
Definition at line 98 of file BMatrix.h.
Referenced by oops::BMatrix< MODEL >::multiplyId().
j_
template<typename MODEL > CostFct_ const& oops::BMatrix< MODEL >::j_ private
Definition at line 96 of file BMatrix.h.
Referenced by oops::BMatrix< MODEL >::multiply(), oops::BMatrix< MODEL >::multiplyB(), oops::BMatrix< MODEL >::multiplyId(), oops::BMatrix< MODEL >::multiplySqrt(), and oops::BMatrix< MODEL >::multiplySqrtTrans().
The documentation for this class was generated from the following file:
src/oops/assimilation/BMatrix.h