OOPS Documentation: oops::EnsembleCovariance< MODEL > Class Template Reference
oops::EnsembleCovariance< MODEL > Class Template Reference
Generic ensemble based model space error covariance.
#include <EnsembleCovariance.h>
Public Member Functions
EnsembleCovariance (const Geometry_ &, const Variables_ &, const eckit::Configuration &, const State_ &)
Constructor, destructor.
~EnsembleCovariance ()
void linearize (const State_ &, const Geometry_ &) override
Set up the inner loop resolution B matrix.
void linearize (const State_ &, const Geometry_ &, const eckit::Configuration &) override
void multiply (const Increment_ &, Increment_ &) const override
\(dx_1 = B dx_2 \)
void inverseMultiply (const Increment_ &, Increment_ &) const override
\(dx_1 = B^{-1} dx_2 \)
void multiplySqrt (const IncrCtlVec_ &, Increment_ &) const override
\(dx = B^{1/2} dv \)
void multiplySqrtTrans (const Increment_ &, IncrCtlVec_ &) const override
\(dv = [B^{1/2}]^T dx \)
void randomize (Increment_ &) const override
\(dx = B^{1/2} dv_{random} \)
IncrModCtlVec_ * newIncrModCtlVec () const override
IncrEnsCtlVec_ * newIncrEnsCtlVec () const override
Public Member Functions inherited from oops::ModelSpaceCovarianceBase< MODEL >
virtual ~ModelSpaceCovarianceBase ()
Destructor.
Private Types
using Ensemble_ = Ensemble< MODEL >
using EnsemblePtr_ = std::shared_ptr< Ensemble< MODEL > >
using EnsemblesCollection_ = EnsemblesCollection< MODEL >
using Geometry_ = Geometry< MODEL >
using Increment_ = Increment< MODEL >
using IncrCtlVec_ = IncrCtlVec< MODEL >
using IncrEnsCtlVec_ = IncrEnsCtlVec< MODEL >
using IncrModCtlVec_ = IncrModCtlVec< MODEL >
using Localization_ = Localization< MODEL >
using State_ = State< MODEL >
using Variables_ = Variables< MODEL >
using GenericMatrix_ = GenericMatrix< MODEL >
using MatrixFactory_ = GenericMatrixFactory< MODEL >
Private Attributes
const eckit::LocalConfiguration config_
Configuration.
const util::DateTime time_
Valid time.
bool has_change_of_variable_
Change of variable.
std::unique_ptr< Localization_ > loc_
Localization matrix.
std::unique_ptr< Geometry_ > geom_
Pointer to a geometry object.
std::unique_ptr< GenericMatrix_ > change_of_variable_
Detailed Description
template<typename MODEL>
class oops::EnsembleCovariance< MODEL >
Generic ensemble based model space error covariance.
This class implements a generic localized sampled model space error covariance matrix.
Definition at line 47 of file EnsembleCovariance.h.
Member Typedef Documentation
Ensemble_
template<typename MODEL > using oops::EnsembleCovariance< MODEL >::Ensemble_ = Ensemble<MODEL> private
Definition at line 48 of file EnsembleCovariance.h.
EnsemblePtr_
template<typename MODEL > using oops::EnsembleCovariance< MODEL >::EnsemblePtr_ = std::shared_ptr<Ensemble<MODEL> > private
Definition at line 49 of file EnsembleCovariance.h.
EnsemblesCollection_
template<typename MODEL > using oops::EnsembleCovariance< MODEL >::EnsemblesCollection_ = EnsemblesCollection<MODEL> private
Definition at line 50 of file EnsembleCovariance.h.
GenericMatrix_
template<typename MODEL > using oops::EnsembleCovariance< MODEL >::GenericMatrix_ = GenericMatrix<MODEL> private
Definition at line 59 of file EnsembleCovariance.h.
Geometry_
template<typename MODEL > using oops::EnsembleCovariance< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 51 of file EnsembleCovariance.h.
IncrCtlVec_
template<typename MODEL > using oops::EnsembleCovariance< MODEL >::IncrCtlVec_ = IncrCtlVec<MODEL> private
Definition at line 53 of file EnsembleCovariance.h.
Increment_
template<typename MODEL > using oops::EnsembleCovariance< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 52 of file EnsembleCovariance.h.
IncrEnsCtlVec_
template<typename MODEL > using oops::EnsembleCovariance< MODEL >::IncrEnsCtlVec_ = IncrEnsCtlVec<MODEL> private
Definition at line 54 of file EnsembleCovariance.h.
IncrModCtlVec_
template<typename MODEL > using oops::EnsembleCovariance< MODEL >::IncrModCtlVec_ = IncrModCtlVec<MODEL> private
Definition at line 55 of file EnsembleCovariance.h.
Localization_
template<typename MODEL > using oops::EnsembleCovariance< MODEL >::Localization_ = Localization<MODEL> private
Definition at line 56 of file EnsembleCovariance.h.
MatrixFactory_
template<typename MODEL > using oops::EnsembleCovariance< MODEL >::MatrixFactory_ = GenericMatrixFactory<MODEL> private
Definition at line 60 of file EnsembleCovariance.h.
State_
template<typename MODEL > using oops::EnsembleCovariance< MODEL >::State_ = State<MODEL> private
Definition at line 57 of file EnsembleCovariance.h.
Variables_
template<typename MODEL > using oops::EnsembleCovariance< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 58 of file EnsembleCovariance.h.
Constructor & Destructor Documentation
EnsembleCovariance()
template<typename MODEL > oops::EnsembleCovariance< MODEL >::EnsembleCovariance (const Geometry_ & resol, const Variables_ & , const eckit::Configuration & config, const State_ &)
Constructor, destructor.
Definition at line 99 of file EnsembleCovariance.h.
     : config_(config),
       time_(config_.getString("date")),
       has_change_of_variable_(false),
       loc_(),
       geom_(),
       change_of_variable_() {
   geom_.reset(new Geometry_(resol));
   has_change_of_variable_ = config.has("change_of_variable");
   Log::trace() << "EnsembleCovariance created." << std::endl;
 }
References oops::EnsembleCovariance< MODEL >::geom_, and oops::EnsembleCovariance< MODEL >::has_change_of_variable_.
~EnsembleCovariance()
template<typename MODEL > oops::EnsembleCovariance< MODEL >::~EnsembleCovariance
Definition at line 114 of file EnsembleCovariance.h.
{
   loc_.reset();
   geom_.reset();
   Log::trace() << "EnsembleCovariance destructed." << std::endl;
 }
Member Function Documentation
inverseMultiply()
template<typename MODEL > void oops::EnsembleCovariance< MODEL >::inverseMultiply (const Increment_ & , Increment_ &) const override virtual
\(dx_1 = B^{-1} dx_2 \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 179 of file EnsembleCovariance.h.
{
   dxo.zero();
 }
References oops::Increment< MODEL >::zero().
linearize() [1/2]
template<typename MODEL > void oops::EnsembleCovariance< MODEL >::linearize (const State_ & , const Geometry_ &) override virtual
Set up the inner loop resolution B matrix.
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 121 of file EnsembleCovariance.h.
{
   linearize(xb, resol, config_);
 }
linearize() [2/2]
template<typename MODEL > void oops::EnsembleCovariance< MODEL >::linearize (const State_ & xb, const Geometry_ & resol, const eckit::Configuration & config) override virtual
Reimplemented from oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 128 of file EnsembleCovariance.h.
{
   geom_.reset(new Geometry_(resol));
   // Compute the ensemble of perturbations at time of xb.
   ASSERT(xb.validTime() == time_);
   EnsemblePtr_ ens(new Ensemble_(xb.validTime(), config));
   ens->build(xb, resol);
   EnsemblesCollection_::getInstance().put(xb.validTime(), ens);
   ens->read();
   if (has_change_of_variable_) {
     change_of_variable_.reset(
         MatrixFactory_::create(eckit::LocalConfiguration(config, "change_of_variable")));
     for (unsigned l = 0; l < ens->size(); ++l) {
       change_of_variable_->multiply((*ens)[l]);
     }
   }
   ens->to_perturbations(1);
   // Build Localization
   const eckit::LocalConfiguration conf(config, "localization");
   loc_.reset(new Localization_(resol, conf));
   Log::trace() << "EnsembleCovariance linearized." << std::endl;
 }
References oops::State< MODEL >::validTime().
multiply()
template<typename MODEL > void oops::EnsembleCovariance< MODEL >::multiply (const Increment_ & , Increment_ &) const override virtual
\(dx_1 = B dx_2 \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 155 of file EnsembleCovariance.h.
{
   EnsemblePtr_ e_k2 = EnsemblesCollection_::getInstance()[dxi.validTime()];
   EnsemblePtr_ e_k1 = EnsemblesCollection_::getInstance()[dxo.validTime()];
   Increment_ dxi_tmp(dxi);
   // Apply to dxi the block B_k1k2 of the B matrix which contains the
   // covariance of perturbations at time k1 with covariance at time k2
   if (has_change_of_variable_)
     change_of_variable_->transposeInverseMultiply(dxi_tmp);
   dxo.zero();
   for (unsigned int m = 0; m < e_k1->size(); ++m) {
     Increment_ dx(dxi_tmp);
     dx.schur_product_with((*e_k2)[m]);
     loc_->multiply(dx);
     dx.schur_product_with((*e_k1)[m]);
     // We can't use '+=' , dxo and dx aren't at the same time (QG)
     dxo.axpy(1.0, dx, false);
   }
   if (has_change_of_variable_) change_of_variable_->inverseMultiply(dxo);
 }
References oops::Increment< MODEL >::axpy(), oops::Increment< MODEL >::schur_product_with(), oops::Increment< MODEL >::validTime(), and oops::Increment< MODEL >::zero().
multiplySqrt()
template<typename MODEL > void oops::EnsembleCovariance< MODEL >::multiplySqrt (const IncrCtlVec_ & , Increment_ &) const override virtual
\(dx = B^{1/2} dv \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 185 of file EnsembleCovariance.h.
{
   EnsemblePtr_ e_k = EnsemblesCollection_::getInstance()[dxo.validTime()];
   dxo.zero();
   Increment_ dxi(dxo);
   for (unsigned int m = 0; m < e_k->size(); ++m) {
     loc_->multiplySqrt(dv.ensCtlVec(m), dxi);
     dxi.schur_product_with((*e_k)[m]);
     dxo.axpy(1.0, dxi, false);
   }
   if (has_change_of_variable_) change_of_variable_->inverseMultiply(dxo);
 }
References oops::Increment< MODEL >::axpy(), oops::IncrCtlVec< MODEL >::ensCtlVec(), oops::Increment< MODEL >::schur_product_with(), oops::Increment< MODEL >::validTime(), and oops::Increment< MODEL >::zero().
multiplySqrtTrans()
template<typename MODEL > void oops::EnsembleCovariance< MODEL >::multiplySqrtTrans (const Increment_ & , IncrCtlVec_ &) const override virtual
\(dv = [B^{1/2}]^T dx \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 200 of file EnsembleCovariance.h.
{
   EnsemblePtr_ e_k = EnsemblesCollection_::getInstance()[dxi.validTime()];
   Increment_ dxi_tmp(dxi);
   if (has_change_of_variable_)
     change_of_variable_->transposeInverseMultiply(dxi_tmp);
   for (unsigned int m = 0; m < e_k->size(); ++m) {
     dv.ensCtlVec(m).zero();
     Increment_ dx(dxi_tmp);
     dx.schur_product_with((*e_k)[m]);
     loc_->multiplySqrtTrans(dx, dv.ensCtlVec(m));
   }
 }
References oops::IncrCtlVec< MODEL >::ensCtlVec(), oops::Increment< MODEL >::schur_product_with(), oops::Increment< MODEL >::validTime(), and oops::IncrEnsCtlVec< MODEL >::zero().
newIncrEnsCtlVec()
template<typename MODEL > IncrEnsCtlVec_* oops::EnsembleCovariance< MODEL >::newIncrEnsCtlVec () const inline override virtual
Return a new control vector corresponding to the localised sampled component of a B matrix
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 81 of file EnsembleCovariance.h.
{
     return new IncrEnsCtlVec_(*geom_, *loc_);
   }
References oops::EnsembleCovariance< MODEL >::geom_, and oops::EnsembleCovariance< MODEL >::loc_.
newIncrModCtlVec()
template<typename MODEL > IncrModCtlVec_* oops::EnsembleCovariance< MODEL >::newIncrModCtlVec () const inline override virtual
Return a new control vector corresponding to the modelled component of a B matrix
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 78 of file EnsembleCovariance.h.
{
     return new IncrModCtlVec_();
   }
randomize()
template<typename MODEL > void oops::EnsembleCovariance< MODEL >::randomize (Increment_ &) const override virtual
\(dx = B^{1/2} dv_{random} \)
Implements oops::ModelSpaceCovarianceBase< MODEL >.
Definition at line 216 of file EnsembleCovariance.h.
{
   // Build dv
   EnsemblePtr_ e_k = EnsemblesCollection_::getInstance()[dxo.validTime()];
   std::vector<std::unique_ptr<IncrEnsCtlVec<MODEL> > > dv;
   for (unsigned int jj = 0; jj < e_k->size(); ++jj) {
     dv.emplace_back(this->newIncrEnsCtlVec());
   }
   // Initialize dv
   for (unsigned int m = 0; m < e_k->size(); ++m) {
     dv[m]->random();
   }
   // dxo = B^1/2 dv
   dxo.zero();
   Increment_ dx(dxo);
   for (unsigned int m = 0; m < e_k->size(); ++m) {
     loc_->multiplySqrt(*dv[m], dx);
     dx.schur_product_with((*e_k)[m]);
     dxo.axpy(1.0, dx, false);
   }
   if (has_change_of_variable_) change_of_variable_->inverseMultiply(dxo);
 }
References oops::Increment< MODEL >::axpy(), oops::Increment< MODEL >::schur_product_with(), oops::Increment< MODEL >::validTime(), and oops::Increment< MODEL >::zero().
Member Data Documentation
change_of_variable_
template<typename MODEL > std::unique_ptr<GenericMatrix_> oops::EnsembleCovariance< MODEL >::change_of_variable_ private
Definition at line 91 of file EnsembleCovariance.h.
config_
template<typename MODEL > const eckit::LocalConfiguration oops::EnsembleCovariance< MODEL >::config_ private
Configuration.
Definition at line 86 of file EnsembleCovariance.h.
geom_
template<typename MODEL > std::unique_ptr<Geometry_> oops::EnsembleCovariance< MODEL >::geom_ private
Pointer to a geometry object.
Definition at line 90 of file EnsembleCovariance.h.
Referenced by oops::EnsembleCovariance< MODEL >::EnsembleCovariance(), and oops::EnsembleCovariance< MODEL >::newIncrEnsCtlVec().
has_change_of_variable_
template<typename MODEL > bool oops::EnsembleCovariance< MODEL >::has_change_of_variable_ private
Change of variable.
Definition at line 88 of file EnsembleCovariance.h.
Referenced by oops::EnsembleCovariance< MODEL >::EnsembleCovariance().
loc_
template<typename MODEL > std::unique_ptr<Localization_> oops::EnsembleCovariance< MODEL >::loc_ private
Localization matrix.
Definition at line 89 of file EnsembleCovariance.h.
Referenced by oops::EnsembleCovariance< MODEL >::newIncrEnsCtlVec().
time_
template<typename MODEL > const util::DateTime oops::EnsembleCovariance< MODEL >::time_ private
Valid time.
Definition at line 87 of file EnsembleCovariance.h.
The documentation for this class was generated from the following file:
src/oops/base/EnsembleCovariance.h