OOPS Documentation: oops::HtRinvHMatrix< MODEL > Class Template Reference
oops::HtRinvHMatrix< MODEL > Class Template Reference
The \(H^T R^{-1} H \) matrix.
#include <HtRinvHMatrix.h>
Public Member Functions
HtRinvHMatrix (const CostFct_ &j, const bool test=false)
void multiply (const CtrlInc_ &dx, CtrlInc_ &dz) const
Private Types
using Increment_ = Increment< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using CostFct_ = CostFunction< MODEL >
Private Attributes
CostFct_ const & j_
bool test_
int iter_
Detailed Description
template<typename MODEL>
class oops::HtRinvHMatrix< MODEL >
The \(H^T R^{-1} H \) matrix.
The solvers represent matrices as objects that implement a "multiply" method. This class defines objects that apply a generalized \(H^T R^{-1} H \) matrix that also includes the equivalent operators for the other terms of the cost function.
Definition at line 41 of file HtRinvHMatrix.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::HtRinvHMatrix< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 44 of file HtRinvHMatrix.h.
CtrlInc_
template<typename MODEL > using oops::HtRinvHMatrix< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 43 of file HtRinvHMatrix.h.
Increment_
template<typename MODEL > using oops::HtRinvHMatrix< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 42 of file HtRinvHMatrix.h.
Constructor & Destructor Documentation
HtRinvHMatrix()
template<typename MODEL > oops::HtRinvHMatrix< MODEL >::HtRinvHMatrix (const CostFct_ & j, const bool test = false) explicit
Definition at line 60 of file HtRinvHMatrix.h.
     : j_(j), test_(test), iter_(0) {}
Member Function Documentation
multiply()
template<typename MODEL > void oops::HtRinvHMatrix< MODEL >::multiply (const CtrlInc_ & dx, CtrlInc_ & dz) const
Definition at line 66 of file HtRinvHMatrix.h.
{
   // Increment counter
   iter_++;
   // Setup TL terms of cost function
   PostProcessorTL<Increment_> costtl;
   for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
     costtl.enrollProcessor(j_.jterm(jj).setupTL(dx));
   }
   // Run TLM
   CtrlInc_ mdx(dx);
   j_.runTL(mdx, costtl);
   // Get TLM outputs, multiply by covariance inverses, and setup ADJ forcing
   // terms
   j_.zeroAD(dz);
   PostProcessorAD<Increment_> costad;
   DualVector<MODEL> ww;
   DualVector<MODEL> zz;
   for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
     ww.append(costtl.releaseOutputFromTL(jj));
     zz.append(j_.jterm(jj).multiplyCoInv(*ww.getv(jj)));
     costad.enrollProcessor(j_.jterm(jj).setupAD(zz.getv(jj), dz));
   }
   // Run ADJ
   j_.runAD(dz, costad);
   if (test_) {
     // <G dx, dy>, where dy = Rinv H dx
     double adj_tst_fwd = dot_product(ww, zz);
     // <dx, Gt dy> , where dy = Rinv H dx
     double adj_tst_bwd = dot_product(dx, dz);
     Log::info() << "Online adjoint test, iteration: " << iter_ << std::endl
                 << util::PrintAdjTest(adj_tst_fwd, adj_tst_bwd, "G")
                 << std::endl;
   }
 }
References oops::DualVector< MODEL >::append(), dot_product(), oops::PostProcessorAD< INCR >::enrollProcessor(), oops::PostProcessorTL< INCR >::enrollProcessor(), oops::DualVector< MODEL >::getv(), and oops::PostProcessorTL< INCR >::releaseOutputFromTL().
Referenced by oops::DRPFOMMinimizer< MODEL >::solve(), oops::DRPLanczosMinimizer< MODEL >::solve(), oops::DRGMRESRMinimizer< MODEL >::solve(), oops::DRIPCGMinimizer< MODEL >::solve(), and oops::DRPCGMinimizer< MODEL >::solve().
Member Data Documentation
iter_
template<typename MODEL > int oops::HtRinvHMatrix< MODEL >::iter_ mutable private
Definition at line 54 of file HtRinvHMatrix.h.
j_
template<typename MODEL > CostFct_ const& oops::HtRinvHMatrix< MODEL >::j_ private
Definition at line 52 of file HtRinvHMatrix.h.
test_
template<typename MODEL > bool oops::HtRinvHMatrix< MODEL >::test_ private
Definition at line 53 of file HtRinvHMatrix.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/HtRinvHMatrix.h