OOPS Documentation: oops::DualConfigState< MODEL > Class Template Reference
oops::DualConfigState< MODEL > Class Template Reference
Encapsulates the model state.
#include <DualConfigState.h>
Public Member Functions
DualConfigState (const DualConfigGeometry_ &, const DualConfigModel_ &, const eckit::Configuration &)
Constructor, destructor.
DualConfigState (const DualConfigGeometry_ &, const DualConfigState &)
DualConfigState (const DualConfigState &)
~DualConfigState ()
DualConfigState & operator= (const DualConfigState &)
State_ & state1 ()
Interfacing.
State_ & state2 ()
const State_ & state1 () const
const State_ & state2 () const
const util::DateTime validTime1 () const
Time.
const util::DateTime validTime2 () const
void read (const eckit::Configuration &)
I/O and diagnostics.
void write (const eckit::Configuration &) const
double norm () const
Geometry_ geometry1 () const
Geometry_ geometry2 () const
Static Public Member Functions
static const std::string classname ()
Protected Member Functions
void zero ()
Private Types
using DualConfigGeometry_ = DualConfigGeometry< MODEL >
using DualConfigModel_ = DualConfigModel< MODEL >
using DualConfigState_ = DualConfigState< MODEL >
using Geometry_ = Geometry< MODEL >
using Model_ = Model< MODEL >
using State_ = State< MODEL >
Private Member Functions
void print (std::ostream &) const
Private Attributes
std::unique_ptr< State_ > state1_
std::unique_ptr< State_ > state2_
Detailed Description
template<typename MODEL>
class oops::DualConfigState< MODEL >
Encapsulates the model state.
Definition at line 44 of file DualConfigState.h.
Member Typedef Documentation
DualConfigGeometry_
template<typename MODEL > using oops::DualConfigState< MODEL >::DualConfigGeometry_ = DualConfigGeometry<MODEL> private
Definition at line 46 of file DualConfigState.h.
DualConfigModel_
template<typename MODEL > using oops::DualConfigState< MODEL >::DualConfigModel_ = DualConfigModel<MODEL> private
Definition at line 47 of file DualConfigState.h.
DualConfigState_
template<typename MODEL > using oops::DualConfigState< MODEL >::DualConfigState_ = DualConfigState<MODEL> private
Definition at line 48 of file DualConfigState.h.
Geometry_
template<typename MODEL > using oops::DualConfigState< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 49 of file DualConfigState.h.
Model_
template<typename MODEL > using oops::DualConfigState< MODEL >::Model_ = Model<MODEL> private
Definition at line 50 of file DualConfigState.h.
State_
template<typename MODEL > using oops::DualConfigState< MODEL >::State_ = State<MODEL> private
Definition at line 51 of file DualConfigState.h.
Constructor & Destructor Documentation
DualConfigState() [1/3]
template<typename MODEL > oops::DualConfigState< MODEL >::DualConfigState (const DualConfigGeometry_ & resol, const DualConfigModel_ & model, const eckit::Configuration & conf)
Constructor, destructor.
Definition at line 95 of file DualConfigState.h.
     : state1_(), state2_() {
   Log::trace() << "DualConfigState<MODEL>::DualConfigState read starting"
                << std::endl;
   util::Timer timer(classname(), "DualConfigState");
   Log::debug() << "Full config is:" << conf << std::endl;
   eckit::LocalConfiguration conf1(conf, "state1");
   state1_.reset(new State_(resol.geometry1(), model.model1(), conf1));
   eckit::LocalConfiguration conf2(conf, "state2");
   state2_.reset(new State_(resol.geometry2(), model.model2(), conf2));
   Log::trace() << "DualConfigState<MODEL>::DualConfigState read done"
                << std::endl;
 }
References oops::DualConfigState< MODEL >::classname(), oops::DualConfigGeometry< MODEL >::geometry1(), oops::DualConfigGeometry< MODEL >::geometry2(), oops::DualConfigModel< MODEL >::model1(), oops::DualConfigModel< MODEL >::model2(), oops::DualConfigState< MODEL >::state1_, and oops::DualConfigState< MODEL >::state2_.
DualConfigState() [2/3]
template<typename MODEL > oops::DualConfigState< MODEL >::DualConfigState (const DualConfigGeometry_ & resol, const DualConfigState< MODEL > & other)
Definition at line 114 of file DualConfigState.h.
     : state1_(), state2_() {
   Log::trace()
       << "DualConfigState<MODEL>::DualConfigState interpolated starting"
       << std::endl;
   util::Timer timer(classname(), "DualConfigState");
   state1_.reset(new State_(resol.geometry1(), *other.state1_));
   state2_.reset(new State_(resol.geometry2(), *other.state2_));
   Log::trace() << "DualConfigState<MODEL>::DualConfigState interpolated done"
                << std::endl;
 }
References oops::DualConfigState< MODEL >::classname(), oops::DualConfigGeometry< MODEL >::geometry1(), oops::DualConfigGeometry< MODEL >::geometry2(), oops::DualConfigState< MODEL >::state1_, and oops::DualConfigState< MODEL >::state2_.
DualConfigState() [3/3]
template<typename MODEL > oops::DualConfigState< MODEL >::DualConfigState (const DualConfigState< MODEL > & other)
Definition at line 130 of file DualConfigState.h.
     : state1_(), state2_() {
   Log::trace() << "DualConfigState<MODEL>::DualConfigState starting copy"
                << std::endl;
   util::Timer timer(classname(), "DualConfigState");
   state1_.reset(new State_(*other.state1_));
   state2_.reset(new State_(*other.state2_));
   Log::trace() << "DualConfigState<MODEL>::DualConfigState copy done"
                << std::endl;
 }
References oops::DualConfigState< MODEL >::classname(), oops::DualConfigState< MODEL >::state1_, and oops::DualConfigState< MODEL >::state2_.
~DualConfigState()
template<typename MODEL > oops::DualConfigState< MODEL >::~DualConfigState
Definition at line 144 of file DualConfigState.h.
{
   Log::trace() << "DualConfigState<MODEL>::~DualConfigState starting"
                << std::endl;
   util::Timer timer(classname(), "~DualConfigState");
   state1_.reset();
   state2_.reset();
   Log::trace() << "DualConfigState<MODEL>::~DualConfigState done" << std::endl;
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::DualConfigState< MODEL >::classname () inline static
Definition at line 54 of file DualConfigState.h.
 { return "oops::DualConfigState"; }
Referenced by oops::DualConfigState< MODEL >::DualConfigState().
geometry1()
template<typename MODEL > Geometry< MODEL > oops::DualConfigState< MODEL >::geometry1
Definition at line 210 of file DualConfigState.h.
{
   Log::trace() << "DualConfigState<MODEL>::geometry1 starting" << std::endl;
   util::Timer timer(classname(), "geometry1");
   Geometry<MODEL> geom(state1_->geometry());
   Log::trace() << "DualConfigState<MODEL>::geometry1 done" << std::endl;
   return geom;
 }
geometry2()
template<typename MODEL > Geometry< MODEL > oops::DualConfigState< MODEL >::geometry2
Definition at line 221 of file DualConfigState.h.
{
   Log::trace() << "DualConfigState<MODEL>::geometry2 starting" << std::endl;
   util::Timer timer(classname(), "geometry2");
   Geometry<MODEL> geom(state2_->geometry());
   Log::trace() << "DualConfigState<MODEL>::geometry2 done" << std::endl;
   return geom;
 }
norm()
template<typename MODEL > double oops::DualConfigState< MODEL >::norm
Definition at line 198 of file DualConfigState.h.
{
   Log::trace() << "DualConfigState<MODEL>::norm starting" << std::endl;
   util::Timer timer(classname(), "norm");
   double zz = state1_->norm();
   zz += state2_->norm();
   Log::trace() << "DualConfigState<MODEL>::norm done" << std::endl;
   return zz;
 }
Referenced by oops::DualConfigForecast< MODEL >::execute().
operator=()
template<typename MODEL > DualConfigState< MODEL > & oops::DualConfigState< MODEL >::operator= (const DualConfigState< MODEL > & rhs)
Definition at line 156 of file DualConfigState.h.
{
   Log::trace() << "DualConfigState<MODEL>::operator= starting" << std::endl;
   util::Timer timer(classname(), "operator=");
   *state1_ = *rhs.state1_;
   *state2_ = *rhs.state2_;
   Log::trace() << "DualConfigState<MODEL>::operator= done" << std::endl;
   return *this;
 }
References oops::DualConfigState< MODEL >::state1_, and oops::DualConfigState< MODEL >::state2_.
print()
template<typename MODEL > void oops::DualConfigState< MODEL >::print (std::ostream & os) const private
Definition at line 232 of file DualConfigState.h.
{
   Log::trace() << "DualConfigState<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   os << *state1_;
   os << *state2_;
   Log::trace() << "DualConfigState<MODEL>::print done" << std::endl;
 }
read()
template<typename MODEL > void oops::DualConfigState< MODEL >::read (const eckit::Configuration & conf)
I/O and diagnostics.
Definition at line 169 of file DualConfigState.h.
{
   Log::trace() << "DualConfigState<MODEL>::read starting" << std::endl;
   util::Timer timer(classname(), "read");
   Log::debug() << "Full config is:" << conf << std::endl;
   eckit::LocalConfiguration conf1(conf, "model1");
   state1_->read(conf1);
   eckit::LocalConfiguration conf2(conf, "model2");
   state2_->read(conf2);
   Log::trace() << "DualConfigState<MODEL>::read done" << std::endl;
 }
state1() [1/2]
template<typename MODEL > State_& oops::DualConfigState< MODEL >::state1 () inline
Interfacing.
Definition at line 65 of file DualConfigState.h.
 { return *state1_; }
References oops::DualConfigState< MODEL >::state1_.
Referenced by oops::DualConfigModel< MODEL >::finalize(), oops::DualConfigModel< MODEL >::forecast(), oops::DualConfigModel< MODEL >::initialize(), and oops::DualConfigModel< MODEL >::step().
state1() [2/2]
template<typename MODEL > const State_& oops::DualConfigState< MODEL >::state1 () const inline
Definition at line 67 of file DualConfigState.h.
 { return *state1_; }
References oops::DualConfigState< MODEL >::state1_.
state2() [1/2]
template<typename MODEL > State_& oops::DualConfigState< MODEL >::state2 () inline
Definition at line 66 of file DualConfigState.h.
 { return *state2_; }
References oops::DualConfigState< MODEL >::state2_.
Referenced by oops::DualConfigModel< MODEL >::finalize(), oops::DualConfigModel< MODEL >::forecast(), oops::DualConfigModel< MODEL >::initialize(), and oops::DualConfigModel< MODEL >::step().
state2() [2/2]
template<typename MODEL > const State_& oops::DualConfigState< MODEL >::state2 () const inline
Definition at line 68 of file DualConfigState.h.
 { return *state2_; }
References oops::DualConfigState< MODEL >::state2_.
validTime1()
template<typename MODEL > const util::DateTime oops::DualConfigState< MODEL >::validTime1 () const inline
Time.
Definition at line 71 of file DualConfigState.h.
 { return state1_->validTime(); }
References oops::DualConfigState< MODEL >::state1_.
Referenced by oops::DualConfigForecast< MODEL >::execute(), oops::DualConfigModel< MODEL >::forecast(), and oops::DualConfigModel< MODEL >::step().
validTime2()
template<typename MODEL > const util::DateTime oops::DualConfigState< MODEL >::validTime2 () const inline
Definition at line 72 of file DualConfigState.h.
 { return state2_->validTime(); }
References oops::DualConfigState< MODEL >::state2_.
Referenced by oops::DualConfigModel< MODEL >::forecast(), and oops::DualConfigModel< MODEL >::step().
write()
template<typename MODEL > void oops::DualConfigState< MODEL >::write (const eckit::Configuration & conf) const
Definition at line 183 of file DualConfigState.h.
{
   Log::trace() << "DualConfigState<MODEL>::write starting" << std::endl;
   util::Timer timer(classname(), "write");
   util::LogbookWriter<bool> log("DualConfigStateWriting", true);
   Log::debug() << "Full config is:" << conf << std::endl;
   eckit::LocalConfiguration conf1(conf, "model1");
   state1_->write(conf1);
   eckit::LocalConfiguration conf2(conf, "model2");
   state2_->write(conf2);
   Log::trace() << "DualConfigState<MODEL>::write done" << std::endl;
 }
zero()
template<typename MODEL > void oops::DualConfigState< MODEL >::zero protected
Definition at line 243 of file DualConfigState.h.
{
   Log::trace() << "DualConfigState<MODEL>::zero starting" << std::endl;
   util::Timer timer(classname(), "zero");
   state1_->zero();
   state2_->zero();
   Log::trace() << "DualConfigState<MODEL>::zero done" << std::endl;
 }
Member Data Documentation
state1_
template<typename MODEL > std::unique_ptr<State_> oops::DualConfigState< MODEL >::state1_ private
Definition at line 88 of file DualConfigState.h.
Referenced by oops::DualConfigState< MODEL >::DualConfigState(), oops::DualConfigState< MODEL >::operator=(), oops::DualConfigState< MODEL >::state1(), and oops::DualConfigState< MODEL >::validTime1().
state2_
template<typename MODEL > std::unique_ptr<State_> oops::DualConfigState< MODEL >::state2_ private
Definition at line 89 of file DualConfigState.h.
Referenced by oops::DualConfigState< MODEL >::DualConfigState(), oops::DualConfigState< MODEL >::operator=(), oops::DualConfigState< MODEL >::state2(), and oops::DualConfigState< MODEL >::validTime2().
The documentation for this class was generated from the following file:
src/oops/generic/DualConfigState.h