OOPS Documentation: oops::SQRTMinimizer< MODEL > Class Template Reference
oops::SQRTMinimizer< MODEL > Class Template Reference abstract
Abstract base class for square root minimizers.
#include <SQRTMinimizer.h>
Public Member Functions
virtual const std::string classname () const override=0
SQRTMinimizer (const eckit::Configuration &conf, const CostFct_ &J)
Construct the minimizer.
~SQRTMinimizer ()
Destroy the minimizer.
void checkpoint (eckit::LocalConfiguration &) const
Checkpoint the minimizer.
void restart (const eckit::Configuration &)
Restart the minimizer.
void warmStart (const eckit::Configuration &)
Warm start the minimizer.
Public Member Functions inherited from oops::Minimizer< MODEL >
Minimizer (const CostFct_ &J)
Construct a minimizer.
virtual ~Minimizer ()
Destroy a minimizer.
ControlIncrement< MODEL > * minimize (const eckit::Configuration &)
Orchestrate the minimization of a quadratic cost function.
Protected Attributes
size_t iter_
Outer loop index.
size_t maxiter_
Number of outer loops.
Private Types
using Bmat_ = BMatrix< MODEL >
using CostFct_ = CostFunction< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using CtrlVec_ = ControlVector< MODEL >
using Jbmat_ = JbMatrix< MODEL >
using Minimizer_ = Minimizer< MODEL >
using UtHtRinvHU_ = UtHtRinvHUMatrix< MODEL >
Private Member Functions
CtrlInc_ * doMinimize (const eckit::Configuration &) override
Solver (virtual method) - implemented by concrete minimizers.
virtual double solve (CtrlVec_ &, CtrlVec_ &, const Jbmat_ &, const UtHtRinvHU_ &, const bool &, const size_t &, const size_t &, const double &, const double &, const double &)=0
virtual void checkpointLMP (eckit::LocalConfiguration &) const =0
Checkpoint the limited memory preconditioner (virtual method)
virtual void restartLMP (const eckit::Configuration &)=0
Restart the limited memory preconditioner (virtual method)
void checkpointGradJb (eckit::LocalConfiguration &) const
void checkpointDv0 (eckit::LocalConfiguration &) const
void checkpointDvh (eckit::LocalConfiguration &) const
void checkpointAux (eckit::LocalConfiguration &) const
void restartGradJb (const eckit::Configuration &)
void restartDv0 (const eckit::Configuration &)
void restartDvh (const eckit::Configuration &)
void restartAux (const eckit::Configuration &)
void warmStartAux ()
void updateJbCostFunction (const CtrlVec_ &dv, const CtrlVec_ &jbdv)
Quadratic cost function calculation (Jb component)
void setupSolver (const eckit::Configuration &)
Setup solver controls (general settings)
void setupMinimization (const eckit::Configuration &)
Setup the minimization (settings specific to the current minimization)
void enforceObsAuxFormulation (CtrlVec_ &dv) const
Private Attributes
const CostFct_ & J_
Handle to the cost function.
bool lclassicChaVar_
bool linfoConv_
criterion is enabled
bool lauxMinDiags_
size_t ninner_
Maximum number of iterations of the solver.
size_t ninnerMin_
Minimum number of iterations of the solver.
double gnreduc_
Gradient norm reduction.
std::unique_ptr< CtrlVec_ > gradJb_
Jb component of the first guess gradient.
std::unique_ptr< CtrlVec_ > dv0_
Initial control vector.
std::vector< CtrlVec_ > dvh_
double costJ0Jb_
value of the Jb component of the cost function
double costJ0JbJq_
value of the JbJq component of the cost function
bool setObsAuxFormulation_
observation space components of the control increment
std::map< std::string, bool > obsAuxFormulation_
Detailed Description
template<typename MODEL>
class oops::SQRTMinimizer< MODEL >
Abstract base class for square root minimizers.
SQRTMinimizer is the base class for all minimizers that use the square root \(U\) of the \(B = UU^T\) matrix to precondition the variational minimisation problem through the introduction of an auxiliary variable \(dx = U \hat{v} \) or \(dx = U \hat{v} + x_b - x_fg \).
IFS: SQRTPLanczosMinimizer is employed by default, the change of variable \(dx = U \hat{v} + x_b - x_fg \) is default.
Definition at line 51 of file SQRTMinimizer.h.
Member Typedef Documentation
Bmat_
template<typename MODEL > using oops::SQRTMinimizer< MODEL >::Bmat_ = BMatrix<MODEL> private
Definition at line 52 of file SQRTMinimizer.h.
CostFct_
template<typename MODEL > using oops::SQRTMinimizer< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 53 of file SQRTMinimizer.h.
CtrlInc_
template<typename MODEL > using oops::SQRTMinimizer< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 54 of file SQRTMinimizer.h.
CtrlVec_
template<typename MODEL > using oops::SQRTMinimizer< MODEL >::CtrlVec_ = ControlVector<MODEL> private
Definition at line 55 of file SQRTMinimizer.h.
Jbmat_
template<typename MODEL > using oops::SQRTMinimizer< MODEL >::Jbmat_ = JbMatrix<MODEL> private
Definition at line 56 of file SQRTMinimizer.h.
Minimizer_
template<typename MODEL > using oops::SQRTMinimizer< MODEL >::Minimizer_ = Minimizer<MODEL> private
Definition at line 57 of file SQRTMinimizer.h.
UtHtRinvHU_
template<typename MODEL > using oops::SQRTMinimizer< MODEL >::UtHtRinvHU_ = UtHtRinvHUMatrix<MODEL> private
Definition at line 58 of file SQRTMinimizer.h.
Constructor & Destructor Documentation
SQRTMinimizer()
template<typename MODEL > oops::SQRTMinimizer< MODEL >::SQRTMinimizer (const eckit::Configuration & conf, const CostFct_ & J) inline
Construct the minimizer.
Over-write default configuration following user input
Definition at line 64 of file SQRTMinimizer.h.
       : Minimizer_(J),
         J_(J),
         lclassicChaVar_(true),
         linfoConv_(false),
         lauxMinDiags_(false),
         ninner_(30),
         ninnerMin_(0),
         gnreduc_(1.e-14),
         gradJb_(),
         dv0_(),
         dvh_(),
         costJ0Jb_(0),
         costJ0JbJq_(0),
         setObsAuxFormulation_(false),
         obsAuxFormulation_(),
         iter_(0),
         maxiter_(999) {
     this->setupSolver(conf);
   }
References oops::SQRTMinimizer< MODEL >::setupSolver().
~SQRTMinimizer()
template<typename MODEL > oops::SQRTMinimizer< MODEL >::~SQRTMinimizer () inline
Destroy the minimizer.
Definition at line 86 of file SQRTMinimizer.h.
 {}
Member Function Documentation
checkpoint()
template<typename MODEL > void oops::SQRTMinimizer< MODEL >::checkpoint (eckit::LocalConfiguration & conf) const virtual
Checkpoint the minimizer.
Checkpoint the minimizer based on the configuration
\(dx = U dv \) :
A.1 Checkpoint GradJb (
A.2 Checkpoint dvh
\(dx = U dv + x_b - x_{fg} \) :
B.1 Checkpoint dv0
Both formulations:
C.1 Checkpoint costJ0Jb
C.2 Checkpoint LMP
C.3 Checkpoint the current outer loop iteration
Implements oops::Minimizer< MODEL >.
Definition at line 463 of file SQRTMinimizer.h.
{
   Log::info() << " " << classname() << "::checkpoint starting" << std::endl;
   checkpointGradJb(conf);
   // checkpointDvh(conf);
   checkpointDv0(conf);
   checkpointAux(conf);
   if (conf.has("preconditioner")) this->checkpointLMP(conf);
   conf.set("outerIteration", iter_);
   Log::info() << " " << classname() << "::checkpoint done" << std::endl;
 }
checkpointAux()
template<typename MODEL > void oops::SQRTMinimizer< MODEL >::checkpointAux (eckit::LocalConfiguration & conf) const private
Checkpoint costJ0Jb (required for computation of the quadratic cost function only)
Definition at line 621 of file SQRTMinimizer.h.
{
   conf.set("costJ0Jb", util::full_precision(costJ0Jb_));
   Log::info() << " " << classname()
               << "::checkpoint costJ0Jb: " << util::full_precision(costJ0Jb_)
               << std::endl;
 }
References util::full_precision().
checkpointDv0()
template<typename MODEL > void oops::SQRTMinimizer< MODEL >::checkpointDv0 (eckit::LocalConfiguration & conf) const private
Checkpoint dv0 (initial guess)
Definition at line 578 of file SQRTMinimizer.h.
{
   if (not lclassicChaVar_) {
     ASSERT(conf.has("dv0"));
     {
       eckit::LocalConfiguration dv0conf(conf, "dv0");
       ASSERT(dv0_);
       dv0_->write(dv0conf);
       Log::info() << " " << classname() << "::checkpoint dv0: "
                   << util::full_precision(dot_product(*dv0_, *dv0_))
                   << std::endl;
     }
   }
 }
References dot_product(), and util::full_precision().
checkpointDvh()
template<typename MODEL > void oops::SQRTMinimizer< MODEL >::checkpointDvh (eckit::LocalConfiguration & conf) const private
Checkpoint dvh (Jb.dv) for all minimizations; required for computation of the quadratic cost function value only)
Definition at line 597 of file SQRTMinimizer.h.
{
   if (lclassicChaVar_) {
     ASSERT(conf.has("dvh"));
     {
       std::vector<eckit::LocalConfiguration> dvhconfs;
       conf.get("dvh", dvhconfs);
       ASSERT(dvh_.size() == dvhconfs.size());
       for (size_t ii = 0; ii < dvh_.size(); ++ii) {
         dvh_[ii].write(dvhconfs[ii]);
         Log::info() << " " << classname() << "::checkpoint dvh[" << ii << "]: "
                     << util::full_precision(dot_product(dvh_[ii], dvh_[ii]))
                     << std::endl;
       }
     }
   }
 }
References dot_product(), and util::full_precision().
checkpointGradJb()
template<typename MODEL > void oops::SQRTMinimizer< MODEL >::checkpointGradJb (eckit::LocalConfiguration & conf) const private
Checkpoint GradJb (\(-\sum dv_i \))
Definition at line 560 of file SQRTMinimizer.h.
{
   if (lclassicChaVar_) {
     ASSERT(conf.has("gradJb"));
     {
       eckit::LocalConfiguration gradjbconf(conf, "gradJb");
       gradJb_->write(gradjbconf);
       Log::info() << " " << classname() << "::checkpoint gradJb: "
                   << util::full_precision(dot_product(*gradJb_, *gradJb_))
                   << std::endl;
     }
   }
 }
References dot_product(), and util::full_precision().
checkpointLMP()
template<typename MODEL > virtual void oops::SQRTMinimizer< MODEL >::checkpointLMP (eckit::LocalConfiguration &) const private pure virtual
Checkpoint the limited memory preconditioner (virtual method)
Implemented in oops::SQRTPLanczosMinimizer< MODEL >, oops::SQRTBPCGMinimizer< MODEL >, oops::SQRTBPFOMMinimizer< MODEL >, oops::SQRTBPLanczosMinimizer< MODEL >, and oops::SQRTPCGMinimizer< MODEL >.
classname()
template<typename MODEL > virtual const std::string oops::SQRTMinimizer< MODEL >::classname () const override pure virtual
Implements oops::Minimizer< MODEL >.
Implemented in oops::SQRTPLanczosMinimizer< MODEL >, oops::SQRTBPCGMinimizer< MODEL >, oops::SQRTPCGMinimizer< MODEL >, oops::SQRTBPFOMMinimizer< MODEL >, and oops::SQRTBPLanczosMinimizer< MODEL >.
doMinimize()
template<typename MODEL > ControlIncrement< MODEL > * oops::SQRTMinimizer< MODEL >::doMinimize (const eckit::Configuration & config) override private virtual
Solver (virtual method) - implemented by concrete minimizers.
A.1 Setup minimization specific controls
A.2 Setup the operators B, Jb, UtHtRinvHU
A.3 Instantiate a control increment meant to hold \(H^T R^{-1} d \) or \(H^T R^{-1} [d + H (x_{fg} - x_b) - dv_0] \)
A.4 Instantiate a control vector meant to hold \(U^T H^T R^{-1} d \) or \(H^T R^{-1} [d + H (x_{fg} - x_b) - dv_0] \)
A.5 Instantiate a control vector meant to hold the solution
B.1 Setup the first guess gradient for the classic change of variables \(dx = U dv \)
B.2 Interpolate Jb component of the first guess gradient \(-\sum dv_i \) to the new inner loop resolution
B.3 Compute \(H^T R^{-1} d \)
B.4 Compute \(U^T H^T R^{-1} d \)
B.5 Compute the tolal fist guess gradinet \(-\sum dv_i + U^T H^T R^{-1} d \)
B.6 Set \(J[0] = 0.5 d^T R^{-1} d \)
C.1 Setup the first guess gradient for the change of variables \(dx = U dv + x_b - x_{fg} \)
C.2 Interpolate initial guess control vector to the new inner loop resolution
C.3.a Calculate first guess gradient \(H^T R^{-1} d \)
C.3.b Set \(J[0] = 0.5 d^T R^{-1} d \)
C.3.b Calculate first guess gradient \(H^T R^{-1} [d + H (dx_{fg} - U dv_0) ] \) and set \(J[0] = 0.5 (d + H (dx_fg - U dv0))^T R^{-1} (d + H (dx_fg - U dv0)) \)
C.4 Calculate first guess gradient in control space \(U^T H^T R^{-1} [d + H (dx_{fg} - U dv_0) ] \)
Note that:
\(U^T H^T R^{-1} [d + H (dx_{fg} - U dv_0) ] - J_b dv_0 \)
is equivalent to
\(U^T H^T R^{-1} d + U^T H^T R^{-1} H dx_{fg} - [J_b + U^T H^T R^{-1} H U] dv_0 \)
C.5 Compute \(J_b dv_0 \)
C.6 Initialise \(dv \) to \(dv_0 \)
D.1 Solve the linear system
D.2 Enforce the formulation of the auxiliary observation space component of the control increment
D.3 Calculate the increment \(dx_k = U dv \)
D.4 Calculate quadratic cost function
D.5 Book-keeping for next minimization/(transformation of the increment)
\(dx = U dv \):
Update the Jb component of the first guess gradient
\(dx = U dv + x_b - x_{fg} \) :
Save inital guess
Tranform \(dx_k \) to be defined w.r.t. the first guess
Implements oops::Minimizer< MODEL >.
Definition at line 175 of file SQRTMinimizer.h.
{
   iter_++;
   ASSERT(iter_ <= maxiter_);
   Log::info() << std::endl;
   Log::info() << classname() << ": starting" << std::endl;
   this->setupMinimization(config);
   const Jbmat_ Jb(J_);
   const Bmat_ B(J_);
   const UtHtRinvHU_ UtHtRinvHU(J_, lauxMinDiags_);
   CtrlInc_ fgrhs(J_.jb().getFirstGuessIncrement(), false);
   CtrlVec_ rhs(J_.jb());
   CtrlVec_ dv(J_.jb());
   double costJ0JoJc(0.0);
   if (lclassicChaVar_) {
     if (gradJb_ == 0) {
       gradJb_.reset(new CtrlVec_(J_.jb()));
     } else {
       gradJb_.reset(new CtrlVec_(J_.jb(), *gradJb_));
     }
     // Calculate first guess gradient
     J_.computeGradientFG(fgrhs);
     B.multiplySqrtTrans(fgrhs, rhs);
     J_.jb().addGradientFG(rhs, *gradJb_);
     costJ0JoJc = J_.getCostJoJc();
   } else {
     if (dv0_ == 0) {
       dv0_.reset(new CtrlVec_(J_.jb()));
       J_.computeGradientFG(fgrhs);
       costJ0JoJc = J_.getCostJoJc();
     } else {
       dv0_.reset(new CtrlVec_(J_.jb(), *dv0_));
       costJ0JoJc = J_.computeGradientFG(*dv0_, fgrhs);
     }
     B.multiplySqrtTrans(fgrhs, rhs);
     CtrlVec_ jbdv0(J_.jb());
     Jb.multiply(*dv0_, jbdv0);
     rhs -= jbdv0;
     dv = *dv0_;
   }
   double reduc = this->solve(dv, rhs, Jb, UtHtRinvHU, linfoConv_, ninner_,
                              ninnerMin_, gnreduc_, costJ0Jb_, costJ0JoJc);
   this->enforceObsAuxFormulation(dv);
   CtrlInc_ *dx = new CtrlInc_(J_.jb().getFirstGuessIncrement(), false);
   B.multiplySqrt(dv, *dx);
   // Print
   if (linfoConv_) {
     Log::test() << classname()
                 << ": final relative gain in information content = " << reduc
                 << std::endl;
   } else {
     Log::test() << classname() << ": reduction in residual norm = " << reduc
                 << std::endl;
   }
   Log::info() << classname() << " output increment:" << *dx << std::endl;
   CtrlVec_ jbdv(dv, false);
   Jb.multiply(dv, jbdv);
   // Update Jb component of J[0]: 0.5 (x_i - x_b)^T B^-1 (x_i - x_b)
   this->updateJbCostFunction(dv, jbdv);
   if (lclassicChaVar_) {
     *gradJb_ += dv;
   } else {
     *dv0_ = dv;
     const CtrlInc_ &dxfg = J_.jb().getFirstGuessIncrement();
     *dx -= dxfg;
   }
   Log::info() << classname() << ": done" << std::endl;
   return dx;
 }
References oops::JbMatrix< MODEL >::multiply(), oops::BMatrix< MODEL >::multiplySqrt(), and oops::BMatrix< MODEL >::multiplySqrtTrans().
enforceObsAuxFormulation()
template<typename MODEL > void oops::SQRTMinimizer< MODEL >::enforceObsAuxFormulation (CtrlVec_ & dv) const private
Enforce incremental/non-incremental formulation of observation space components of the control increment
The formulation (incremental/non-incremental) is enforced for the observations space components of the control vector except in the last outer loop.
IFS: VarBC has non-incremental formulation; TOVSCV has incremental formulation in a standard AN experiment and non-incremental formulation in continuous DA.
Definition at line 398 of file SQRTMinimizer.h.
{
   if (setObsAuxFormulation_ && iter_ < maxiter_) {
     Log::info() << "SQRTMinimizer<MODEL>::enforceObsAuxFormulation(dv)"
                 << std::endl;
     std::map<std::string, bool>::const_iterator icst =
         obsAuxFormulation_.begin();
     while (icst != obsAuxFormulation_.end()) {
       if (!icst->second) {
         for (std::size_t jobs = 0; jobs < dv.obsVar().size(); ++jobs) {
           if (dv.obsVar()[jobs].size() > 0) {
             dv.obsVar()[jobs].obsAuxCtlVec(icst->first).zero();
             Log::info() << "  set component of the control vector: "
                         << icst->first << " to zero" << std::endl;
           }
         }
       }
       ++icst;
     }
   }
 }
References oops::ControlVector< MODEL >::obsVar(), oops::ObsAuxCtlVecs< MODEL >::size(), and oops::ObsAuxCtlVecs< MODEL >::zero().
restart()
template<typename MODEL > void oops::SQRTMinimizer< MODEL >::restart (const eckit::Configuration & conf) virtual
Restart the minimizer.
Restart the minimizer following the configuration
\(dx = U dv \) :
A.1 Restart GradJb
A.2 Restart dvh
\(dx = U dv + x_b - x_{fg} \) :
B.1 Restart dv0
Both formulations:
C.1 Restart costJ0Jb
C.2 Restart LMP
C.3 Set the current outer loop iteration
Implements oops::Minimizer< MODEL >.
Definition at line 527 of file SQRTMinimizer.h.
{
   Log::info() << " " << classname() << "::restart starting" << std::endl;
   restartGradJb(conf);
   // restartDvh(conf);
   restartDv0(conf);
   restartAux(conf);
   if (conf.has("preconditioner")) {
     this->restartLMP(conf);
   }
   iter_ = conf.getUnsigned("outerIteration");
   Log::info() << " " << classname() << "::restart done" << std::endl;
 }
restartAux()
template<typename MODEL > void oops::SQRTMinimizer< MODEL >::restartAux (const eckit::Configuration & conf) private
Restart costJ0Jb (required for computation of the quadratic cost function only)
Definition at line 690 of file SQRTMinimizer.h.
{
   ASSERT(conf.has("costJ0Jb"));
   costJ0Jb_ = conf.getDouble("costJ0Jb");
   Log::info() << " " << classname()
               << "::restart costJ0Jb: " << util::full_precision(costJ0Jb_)
               << std::endl;
 }
References util::full_precision().
restartDv0()
template<typename MODEL > void oops::SQRTMinimizer< MODEL >::restartDv0 (const eckit::Configuration & conf) private
Restart dv0 (initial guess)
Definition at line 652 of file SQRTMinimizer.h.
{
   if (not lclassicChaVar_) {
     ASSERT(conf.has("dv0"));
     eckit::LocalConfiguration dv0conf(conf, "dv0");
     if (dv0_ == 0) {
       dv0_.reset(new CtrlVec_(J_.jb()));
     }
     dv0_->read(dv0conf);
     Log::info() << " " << classname() << "::restart dv0: "
                 << util::full_precision(dot_product(*dv0_, *dv0_)) << std::endl;
   }
 }
References dot_product(), and util::full_precision().
restartDvh()
template<typename MODEL > void oops::SQRTMinimizer< MODEL >::restartDvh (const eckit::Configuration & conf) private
Restart dvh (Jb.dv for all minimizations; required for computation of the quadratic cost function value only)
Definition at line 669 of file SQRTMinimizer.h.
{
   if (lclassicChaVar_) {
     ASSERT(conf.has("dvh"));
     std::vector<eckit::LocalConfiguration> dvhconfs;
     conf.get("dvh", dvhconfs);
     for (size_t ii = 0; ii < dvhconfs.size(); ++ii) {
       CtrlVec_ dvh(J_.jb());
       dvh.read(dvhconfs[ii]);
       dvh_.push_back(dvh);
       Log::info() << " " << classname() << "::restart dvh[" << ii << "]: "
                   << util::full_precision(dot_product(dvh_[ii], dvh_[ii]))
                   << std::endl;
     }
   }
 }
References dot_product(), util::full_precision(), and oops::ControlVector< MODEL >::read().
restartGradJb()
template<typename MODEL > void oops::SQRTMinimizer< MODEL >::restartGradJb (const eckit::Configuration & conf) private
Restart GradJb (\(-\sum dv_i \))
Definition at line 634 of file SQRTMinimizer.h.
{
   if (lclassicChaVar_) {
     ASSERT(conf.has("gradJb"));
     eckit::LocalConfiguration gradjbconf(conf, "gradJb");
     if (gradJb_ == 0) {
       gradJb_.reset(new CtrlVec_(J_.jb()));
     }
     gradJb_->read(gradjbconf);
     Log::info() << " " << classname() << "::restart gradJb: "
                 << util::full_precision(dot_product(*gradJb_, *gradJb_))
                 << std::endl;
   }
 }
References dot_product(), and util::full_precision().
restartLMP()
template<typename MODEL > virtual void oops::SQRTMinimizer< MODEL >::restartLMP (const eckit::Configuration &) private pure virtual
Restart the limited memory preconditioner (virtual method)
Implemented in oops::SQRTPLanczosMinimizer< MODEL >, oops::SQRTBPCGMinimizer< MODEL >, oops::SQRTBPFOMMinimizer< MODEL >, oops::SQRTBPLanczosMinimizer< MODEL >, and oops::SQRTPCGMinimizer< MODEL >.
setupMinimization()
template<typename MODEL > void oops::SQRTMinimizer< MODEL >::setupMinimization (const eckit::Configuration & conf) private
Setup the minimization (settings specific to the current minimization)
Setup settings of the solver specific for the current minimization (can be different across different minimizations (IFS: consistent settings are used for all minimizations)
Set the minimum number of iterations
Set the maximum number of iterations
Set the solver tolerance
Control of online adjoint tests
Definition at line 368 of file SQRTMinimizer.h.
{
   if (conf.has("ninnermin")) ninnerMin_ = conf.getUnsigned("ninnermin");
   if (conf.has("ninner")) ninner_ = conf.getUnsigned("ninner");
   ASSERT(ninner_ >= ninnerMin_);
   util::LogbookWriter<size_t> log_nin("maxiters", ninner_);
   if (conf.has("gradient_norm_reduction"))
     gnreduc_ = conf.getDouble("gradient_norm_reduction");
   util::LogbookWriter<double> log_tol("tolerance", gnreduc_);
   if (conf.has("onlineDiagnostics")) {
     const eckit::LocalConfiguration onlineDiag(conf, "onlineDiagnostics");
     lauxMinDiags_ = onlineDiag.getBool("auxMinDiags");
   } else {
     lauxMinDiags_ = false;
   }
 }
setupSolver()
template<typename MODEL > void oops::SQRTMinimizer< MODEL >::setupSolver (const eckit::Configuration & conf) private
Setup solver controls (general settings)
Setup general solver settings (consistent for all minimizations) from configuration
Setup the choice of the change of variable
Check if the information content based convergence criteria enabled
Check if LMP preconditioner is enabled
Set formulation (incremental/non-incremental) of the observation space components of the control vector
Definition at line 323 of file SQRTMinimizer.h.
{
   if (conf.has("classic_change_of_variables")) {
     // true  : dx = U dv
     // false : dx = U dv + x_b - x_fg
     lclassicChaVar_ = conf.getBool("classic_change_of_variables");
   }
   if (conf.has("linfoconv")) linfoConv_ = conf.getBool("linfoconv");
   if (conf.has("preconditioner") || conf.has("obsAuxFormulations")) {
     // Provide number of outer loops in order to skip the update of the
     // preconditioner in the final minimization or/and to properly apply
     // obs aux incremental formulation
     ASSERT(conf.has("minimizations"));
     maxiter_ = conf.getUnsigned("minimizations");
   }
   if (conf.has("obsAuxFormulations")) {
     Log::info()
         << "SQRTMinimizer<MODEL>::setupSolver() set ObsAux* formulations"
         << std::endl;
     setObsAuxFormulation_ = true;
     std::vector<eckit::LocalConfiguration> configs;
     conf.get("obsAuxFormulations", configs);
     for (size_t ii = 0; ii < configs.size(); ++ii) {
       std::string key(configs[ii].getString("component"));
       bool value(configs[ii].getBool("incremental"));
       obsAuxFormulation_.insert(std::make_pair(key, value));
       Log::info() << "   ObsAuxComponent: " << key
                   << ", incremental formulation: " << value << std::endl;
     }
   }
 }
Referenced by oops::SQRTMinimizer< MODEL >::SQRTMinimizer().
solve()
template<typename MODEL > virtual double oops::SQRTMinimizer< MODEL >::solve (CtrlVec_ & , CtrlVec_ & , const Jbmat_ & , const UtHtRinvHU_ & , const bool & , const size_t & , const size_t & , const double & , const double & , const double &) private pure virtual
Implemented in oops::SQRTPLanczosMinimizer< MODEL >, oops::SQRTBPCGMinimizer< MODEL >, oops::SQRTPCGMinimizer< MODEL >, oops::SQRTBPFOMMinimizer< MODEL >, and oops::SQRTBPLanczosMinimizer< MODEL >.
updateJbCostFunction()
template<typename MODEL > void oops::SQRTMinimizer< MODEL >::updateJbCostFunction (const CtrlVec_ & dv, const CtrlVec_ & jbdv) private
Quadratic cost function calculation (Jb component)
Compute the cost of the Jb component of the cost function. In case of the classic change of variables formulation store Jb.dv
Definition at line 430 of file SQRTMinimizer.h.
{
   if (lclassicChaVar_) {
     dvh_.push_back(jbdv);
     // Update Jb component of J[0]: 0.5 (x_i - x_b)^T B^-1 (x_i - x_b)
     costJ0Jb_ += 0.5 * dot_product(dv, jbdv);
     costJ0JbJq_ += 0.5 * dot_product(dv.modVar(), jbdv.modVar());
     for (size_t jouter = 1; jouter < dvh_.size(); ++jouter) {
       CtrlVec_ dvhtmp(J_.jb(), dvh_[jouter - 1]);
       // MC temp
       // costJ0Jb_ += dot_product(dv.state(), dvhtmp.state());
       costJ0JbJq_ += dot_product(dv.modVar(), dvhtmp.modVar());
     }
   } else {
     // Update Jb component of J[0]: 0.5 (x_i - x_b)^T B^-1 (x_i - x_b)
     costJ0Jb_ = 0.5 * dot_product(dv, jbdv);
     costJ0JbJq_ = 0.5 * dot_product(dv.modVar(), jbdv.modVar());
   }
   // Print out costJ0Jb and its ObsAux components
   Log::info() << "SQRTMinimizer: costJ0Jb      : "
               << util::full_precision(costJ0Jb_) << std::endl;
   Log::info() << "SQRTMinimizer: costJ0JbJq    : "
               << util::full_precision(costJ0JbJq_) << std::endl;
 }
References dot_product(), util::full_precision(), and oops::ControlVector< MODEL >::modVar().
warmStart()
template<typename MODEL > void oops::SQRTMinimizer< MODEL >::warmStart (const eckit::Configuration & conf) virtual
Warm start the minimizer.
Warm start the minimizer based on the configuration
\(dx = U dv \) :
A.1 Warm start GradJb
A.2 Warm start dvh
\(dx = U dv + x_b - x_{fg} \) :
B.1 Warm start dv0
Both formulations:
C.1 Warm start costJ0Jb
C.2 Warm start LMP
Implements oops::Minimizer< MODEL >.
Definition at line 494 of file SQRTMinimizer.h.
{
   Log::info() << " " << classname() << "::warmStart starting" << std::endl;
   if (conf.has("gradJb")) restartGradJb(conf);
   // if (conf.has("dvh"))
   //  restartDvh(conf);
   if (conf.has("dv0")) restartDv0(conf);
   if (conf.has("quadraticCost")) {
     restartAux(conf.getSubConfiguration("quadraticCost"));
   } else {
     warmStartAux();
   }
   if (conf.has("preconditioner")) this->restartLMP(conf);
   Log::info() << " " << classname() << "::warmStart done" << std::endl;
 }
warmStartAux()
template<typename MODEL > void oops::SQRTMinimizer< MODEL >::warmStartAux private
Warm start costJ0Jb (required for computation of the quadratic cost function only)
Definition at line 703 of file SQRTMinimizer.h.
{
   costJ0Jb_ = 0.0;
   if (lclassicChaVar_) {
     // not implemented
   } else {
     if (dv0_ != 0) costJ0Jb_ = 0.5 * dot_product(*dv0_, *dv0_);
   }
   Log::info() << " " << classname()
               << "::warmStart costJ0Jb: " << util::full_precision(costJ0Jb_)
               << std::endl;
 }
References dot_product(), and util::full_precision().
Member Data Documentation
costJ0Jb_
template<typename MODEL > double oops::SQRTMinimizer< MODEL >::costJ0Jb_ private
value of the Jb component of the cost function
Definition at line 157 of file SQRTMinimizer.h.
costJ0JbJq_
template<typename MODEL > double oops::SQRTMinimizer< MODEL >::costJ0JbJq_ private
value of the JbJq component of the cost function
Definition at line 158 of file SQRTMinimizer.h.
dv0_
template<typename MODEL > std::unique_ptr<CtrlVec_> oops::SQRTMinimizer< MODEL >::dv0_ private
Initial control vector.
Definition at line 153 of file SQRTMinimizer.h.
dvh_
template<typename MODEL > std::vector<CtrlVec_> oops::SQRTMinimizer< MODEL >::dvh_ private
Definition at line 154 of file SQRTMinimizer.h.
gnreduc_
template<typename MODEL > double oops::SQRTMinimizer< MODEL >::gnreduc_ private
Gradient norm reduction.
Definition at line 148 of file SQRTMinimizer.h.
gradJb_
template<typename MODEL > std::unique_ptr<CtrlVec_> oops::SQRTMinimizer< MODEL >::gradJb_ private
Jb component of the first guess gradient.
Definition at line 152 of file SQRTMinimizer.h.
iter_
template<typename MODEL > size_t oops::SQRTMinimizer< MODEL >::iter_ protected
Outer loop index.
Definition at line 168 of file SQRTMinimizer.h.
J_
template<typename MODEL > const CostFct_& oops::SQRTMinimizer< MODEL >::J_ private
Handle to the cost function.
Definition at line 136 of file SQRTMinimizer.h.
lauxMinDiags_
template<typename MODEL > bool oops::SQRTMinimizer< MODEL >::lauxMinDiags_ private
Logical controlling auxiliary minimization diagnostics
Definition at line 144 of file SQRTMinimizer.h.
lclassicChaVar_
template<typename MODEL > bool oops::SQRTMinimizer< MODEL >::lclassicChaVar_ private
Logical controlling the choice of the change of variables
Definition at line 139 of file SQRTMinimizer.h.
linfoConv_
template<typename MODEL > bool oops::SQRTMinimizer< MODEL >::linfoConv_ private
criterion is enabled
Logical controlling if the information content convergence
Definition at line 141 of file SQRTMinimizer.h.
maxiter_
template<typename MODEL > size_t oops::SQRTMinimizer< MODEL >::maxiter_ mutable protected
Number of outer loops.
Definition at line 169 of file SQRTMinimizer.h.
ninner_
template<typename MODEL > size_t oops::SQRTMinimizer< MODEL >::ninner_ private
Maximum number of iterations of the solver.
Definition at line 146 of file SQRTMinimizer.h.
ninnerMin_
template<typename MODEL > size_t oops::SQRTMinimizer< MODEL >::ninnerMin_ private
Minimum number of iterations of the solver.
Definition at line 147 of file SQRTMinimizer.h.
obsAuxFormulation_
template<typename MODEL > std::map<std::string, bool> oops::SQRTMinimizer< MODEL >::obsAuxFormulation_ mutable private
Definition at line 165 of file SQRTMinimizer.h.
setObsAuxFormulation_
template<typename MODEL > bool oops::SQRTMinimizer< MODEL >::setObsAuxFormulation_ mutable private
observation space components of the control increment
Logical controlling the enforcement of incremental/non-incremental formulation of
Definition at line 162 of file SQRTMinimizer.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/SQRTMinimizer.h