OOPS Documentation: oops::ModelAuxControlEstimator< MODEL > Class Template Reference
oops::ModelAuxControlEstimator< MODEL > Class Template Reference
#include <ModelAuxControlEstimator.h>
Public Member Functions
ModelAuxControlEstimator (const Geometry_ &, const Model_ &, const eckit::Configuration &)
virtual ~ModelAuxControlEstimator ()
void estimate (const State_ &, ModelAuxControl_ &) const
Methods.
void estimate (const State_ &, const State_ &, ModelAuxControl_ &) const
const ModelAuxControlEstimator_ & modelAuxControlEstimator () const
Interfacing.
ModelAuxControlEstimator_ & modelAuxControlEstimator ()
Static Public Member Functions
static const std::string classname ()
Private Types
using ModelAuxControlEstimator_ = typename MODEL::ModelAuxControlEstimator
using Geometry_ = Geometry< MODEL >
using Model_ = Model< MODEL >
using ModelAuxControl_ = ModelAuxControl< MODEL >
using State_ = State< MODEL >
Private Member Functions
ModelAuxControlEstimator & operator= (const ModelAuxControlEstimator &)
void print (std::ostream &) const
Private Attributes
std::unique_ptr< ModelAuxControlEstimator_ > aux_
Detailed Description
template<typename MODEL>
class oops::ModelAuxControlEstimator< MODEL >
Definition at line 39 of file ModelAuxControlEstimator.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::ModelAuxControlEstimator< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 44 of file ModelAuxControlEstimator.h.
Model_
template<typename MODEL > using oops::ModelAuxControlEstimator< MODEL >::Model_ = Model<MODEL> private
Definition at line 45 of file ModelAuxControlEstimator.h.
ModelAuxControl_
template<typename MODEL > using oops::ModelAuxControlEstimator< MODEL >::ModelAuxControl_ = ModelAuxControl<MODEL> private
Definition at line 46 of file ModelAuxControlEstimator.h.
ModelAuxControlEstimator_
template<typename MODEL > using oops::ModelAuxControlEstimator< MODEL >::ModelAuxControlEstimator_ = typename MODEL::ModelAuxControlEstimator private
Definition at line 43 of file ModelAuxControlEstimator.h.
State_
template<typename MODEL > using oops::ModelAuxControlEstimator< MODEL >::State_ = State<MODEL> private
Definition at line 47 of file ModelAuxControlEstimator.h.
Constructor & Destructor Documentation
ModelAuxControlEstimator()
template<typename MODEL > oops::ModelAuxControlEstimator< MODEL >::ModelAuxControlEstimator (const Geometry_ & resol, const Model_ & model, const eckit::Configuration & conf) explicit
Definition at line 77 of file ModelAuxControlEstimator.h.
     : aux_() {
   Log::trace()
       << "ModelAuxControlEstimator<MODEL>::ModelAuxControlEstimator starting"
       << std::endl;
   util::Timer timer(classname(), "ModelAuxControlEstimator");
   aux_.reset(new ModelAuxControlEstimator_(
       resol.geometry(), model.model(),
       conf.getSubConfiguration("stateModAuxEstimator")));
   Log::trace()
       << "ModelAuxControlEstimator<MODEL>::ModelAuxControlEstimator done"
       << std::endl;
 }
References oops::ModelAuxControlEstimator< MODEL >::aux_, oops::ModelAuxControlEstimator< MODEL >::classname(), oops::Geometry< MODEL >::geometry(), and oops::Model< MODEL >::model().
~ModelAuxControlEstimator()
template<typename MODEL > oops::ModelAuxControlEstimator< MODEL >::~ModelAuxControlEstimator virtual
Definition at line 96 of file ModelAuxControlEstimator.h.
{
   Log::trace()
       << "ModelAuxControlEstimator<MODEL>::~ModelAuxControlEstimator starting"
       << std::endl;
   util::Timer timer(classname(), "~ModelAuxControlEstimator");
   aux_.reset();
   Log::trace()
       << "ModelAuxControlEstimator<MODEL>::~ModelAuxControlEstimator done"
       << std::endl;
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::ModelAuxControlEstimator< MODEL >::classname () inline static
Definition at line 50 of file ModelAuxControlEstimator.h.
{
     return "oops::ModelAuxControlEstimator";
   }
Referenced by oops::ModelAuxControlEstimator< MODEL >::ModelAuxControlEstimator().
estimate() [1/2]
template<typename MODEL > void oops::ModelAuxControlEstimator< MODEL >::estimate (const State_ & xb, const State_ & an, ModelAuxControl_ & xerr) const
Definition at line 122 of file ModelAuxControlEstimator.h.
{
   Log::trace() << "ModelAuxControlEstimator<MODEL>::estimate starting"
                << std::endl;
   util::Timer timer(classname(), "estimate");
   aux_->estimate(xb.state(), an.state(), xerr.modelauxcontrol());
   Log::trace() << "ModelAuxControlEstimator<MODEL>::estimate done" << std::endl;
 }
References oops::ModelAuxControl< MODEL >::modelauxcontrol(), and oops::State< MODEL >::state().
estimate() [2/2]
template<typename MODEL > void oops::ModelAuxControlEstimator< MODEL >::estimate (const State_ & xb, ModelAuxControl_ & xerr) const
Methods.
Definition at line 110 of file ModelAuxControlEstimator.h.
{
   Log::trace() << "ModelAuxControlEstimator<MODEL>::estimate starting"
                << std::endl;
   util::Timer timer(classname(), "estimate");
   aux_->estimate(xb.state(), xerr.modelauxcontrol());
   Log::trace() << "ModelAuxControlEstimator<MODEL>::estimate done" << std::endl;
 }
References oops::ModelAuxControl< MODEL >::modelauxcontrol(), and oops::State< MODEL >::state().
Referenced by oops::ControlVariable< MODEL >::ControlVariable(), and oops::ModelAuxNN< MODEL >::execute().
modelAuxControlEstimator() [1/2]
template<typename MODEL > ModelAuxControlEstimator_& oops::ModelAuxControlEstimator< MODEL >::modelAuxControlEstimator () inline
Definition at line 66 of file ModelAuxControlEstimator.h.
 { return *aux_; }
References oops::ModelAuxControlEstimator< MODEL >::aux_.
modelAuxControlEstimator() [2/2]
template<typename MODEL > const ModelAuxControlEstimator_& oops::ModelAuxControlEstimator< MODEL >::modelAuxControlEstimator () const inline
Interfacing.
Definition at line 63 of file ModelAuxControlEstimator.h.
{
     return *aux_;
   }
References oops::ModelAuxControlEstimator< MODEL >::aux_.
operator=()
template<typename MODEL > ModelAuxControlEstimator& oops::ModelAuxControlEstimator< MODEL >::operator= (const ModelAuxControlEstimator< MODEL > &) private
print()
template<typename MODEL > void oops::ModelAuxControlEstimator< MODEL >::print (std::ostream & os) const private
Definition at line 135 of file ModelAuxControlEstimator.h.
{
   Log::trace() << "ModelAuxControlEstimator<MODEL>::print starting"
                << std::endl;
   util::Timer timer(classname(), "print");
   os << *aux_;
   Log::trace() << "ModelAuxControlEstimator<MODEL>::print done" << std::endl;
 }
Member Data Documentation
aux_
template<typename MODEL > std::unique_ptr<ModelAuxControlEstimator_> oops::ModelAuxControlEstimator< MODEL >::aux_ private
Definition at line 71 of file ModelAuxControlEstimator.h.
Referenced by oops::ModelAuxControlEstimator< MODEL >::ModelAuxControlEstimator(), and oops::ModelAuxControlEstimator< MODEL >::modelAuxControlEstimator().
The documentation for this class was generated from the following file:
src/oops/interface/ModelAuxControlEstimator.h