OOPS Documentation: oops::DRMinimizer< MODEL > Class Template Reference
oops::DRMinimizer< MODEL > Class Template Reference abstract
DR (Derber and Rosati) Minimizers.
#include <DRMinimizer.h>
Public Member Functions
virtual const std::string classname () const override=0
DRMinimizer (const CostFct_ &J)
~DRMinimizer ()
void checkpoint (eckit::LocalConfiguration &) const
Checkpointing, restart.
void restart (const eckit::Configuration &)
Restart the minimizer (virtual method)
void warmStart (const eckit::Configuration &)
Warm start the minimizer (virtual method)
Public Member Functions inherited from oops::Minimizer< MODEL >
Minimizer (const CostFct_ &J)
Construct a minimizer.
virtual ~Minimizer ()
Destroy a minimizer.
ControlIncrement< MODEL > * minimize (const eckit::Configuration &)
Orchestrate the minimization of a quadratic cost function.
Private Types
using Bmat_ = BMatrix< MODEL >
using CostFct_ = CostFunction< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using HtRinvHdxFG_ = HtRinvHdxFG< MODEL >
using HtRinvH_ = HtRinvHMatrix< MODEL >
using Minimizer_ = Minimizer< MODEL >
Private Member Functions
CtrlInc_ * doMinimize (const eckit::Configuration &) override
Minimizer the quadratic cost function (virtual method)
virtual double solve (CtrlInc_ &, CtrlInc_ &, CtrlInc_ &, const Bmat_ &, const HtRinvH_ &, const double, const double, const int, const double)=0
Private Attributes
const CostFct_ & J_
Data members.
bool lclassicChaVar_
Controls.
std::unique_ptr< CtrlInc_ > gradJb_
Control increments.
std::unique_ptr< CtrlInc_ > dxh0_
std::vector< CtrlInc_ > dxh_
double costJ0Jb_
Cost function J0Jb.
Detailed Description
template<typename MODEL>
class oops::DRMinimizer< MODEL >
DR (Derber and Rosati) Minimizers.
DRMinimizer is the base class for all minimizers that use \(B\) to precondition the variational minimisation problem and use the auxiliary variable \(x = B \hat{x}\) or \(x = B \hat{x} + x_b -x_fg\) and to update it in parallel to \(x\) based on Derber and Rosati, 1989, J. Phys. Oceanog. 1333-1347. \(J_b\) is then computed as \(x^T\hat{x}\) eliminating the need for \(B^{-1}\) or \(B^{1/2}\).
Definition at line 48 of file DRMinimizer.h.
Member Typedef Documentation
Bmat_
template<typename MODEL > using oops::DRMinimizer< MODEL >::Bmat_ = BMatrix<MODEL> private
Definition at line 49 of file DRMinimizer.h.
CostFct_
template<typename MODEL > using oops::DRMinimizer< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 50 of file DRMinimizer.h.
CtrlInc_
template<typename MODEL > using oops::DRMinimizer< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 51 of file DRMinimizer.h.
HtRinvH_
template<typename MODEL > using oops::DRMinimizer< MODEL >::HtRinvH_ = HtRinvHMatrix<MODEL> private
Definition at line 53 of file DRMinimizer.h.
HtRinvHdxFG_
template<typename MODEL > using oops::DRMinimizer< MODEL >::HtRinvHdxFG_ = HtRinvHdxFG<MODEL> private
Definition at line 52 of file DRMinimizer.h.
Minimizer_
template<typename MODEL > using oops::DRMinimizer< MODEL >::Minimizer_ = Minimizer<MODEL> private
Definition at line 54 of file DRMinimizer.h.
Constructor & Destructor Documentation
DRMinimizer()
template<typename MODEL > oops::DRMinimizer< MODEL >::DRMinimizer (const CostFct_ & J) inline explicit
Definition at line 59 of file DRMinimizer.h.
       : Minimizer_(J),
         J_(J),
         lclassicChaVar_(true),
         gradJb_(),
         dxh0_(),
         dxh_(),
         costJ0Jb_(0) {}
~DRMinimizer()
template<typename MODEL > oops::DRMinimizer< MODEL >::~DRMinimizer () inline
Definition at line 67 of file DRMinimizer.h.
 {}
Member Function Documentation
checkpoint()
template<typename MODEL > void oops::DRMinimizer< MODEL >::checkpoint (eckit::LocalConfiguration & conf) const virtual
Checkpointing, restart.
Implements oops::Minimizer< MODEL >.
Definition at line 214 of file DRMinimizer.h.
{
   Log::info() << classname() << "::checkpoint starting" << std::endl;
   // GradJb
   ASSERT(conf.has("gradJb"));
   eckit::LocalConfiguration gradjbconf(conf, "gradJb");
   gradJb_->write(gradjbconf);
   Log::info() << classname() << "::checkpoint gradJb: "
               << util::full_precision(dot_product(*gradJb_, *gradJb_))
               << std::endl;
   // dxh
   ASSERT(conf.has("dxh"));
   std::vector<eckit::LocalConfiguration> dxhconfs;
   conf.get("dxh", dxhconfs);
   ASSERT(dxhconfs.size() == dxh_.size());
   for (unsigned int jj = 0; jj < dxhconfs.size(); ++jj) {
     dxh_[jj].write(dxhconfs[jj]);
     Log::info() << classname() << "::checkpoint dxh[" << jj << "]: "
                 << util::full_precision(dot_product(dxh_[jj], dxh_[jj]))
                 << std::endl;
   }
   // costJ0Jb
   conf.set("costJ0Jb", util::full_precision(costJ0Jb_));
   Log::info() << classname()
               << "::checkpoint costJ0Jb: " << util::full_precision(costJ0Jb_)
               << std::endl;
   Log::info() << classname() << "::checkpoint done" << std::endl;
 }
References dot_product(), and util::full_precision().
classname()
template<typename MODEL > virtual const std::string oops::DRMinimizer< MODEL >::classname () const override pure virtual
Implements oops::Minimizer< MODEL >.
Implemented in oops::DRPCGMinimizer< MODEL >, oops::DRIPCGMinimizer< MODEL >, oops::DRGMRESRMinimizer< MODEL >, oops::DRPLanczosMinimizer< MODEL >, and oops::DRPFOMMinimizer< MODEL >.
doMinimize()
template<typename MODEL > ControlIncrement< MODEL > * oops::DRMinimizer< MODEL >::doMinimize (const eckit::Configuration &) override private virtual
Minimizer the quadratic cost function (virtual method)
Implements oops::Minimizer< MODEL >.
Definition at line 98 of file DRMinimizer.h.
{
   // Config
   int ninner = config.getInt("ninner");
   double gnreduc = config.getDouble("gradient_norm_reduction");
   // Online Diagnostics
   bool lauxMinDiags = false;
   if (config.has("onlineDiagnostics")) {
     const eckit::LocalConfiguration onlineDiag(config, "onlineDiagnostics");
     lauxMinDiags = onlineDiag.getBool("auxMinDiags");
   }
   // Change of variable
   if (config.has("classic_change_of_variables")) {
     // true  : dx = B dx'
     // false : dx = B dx' + x_b - x_fg
     lclassicChaVar_ = config.getBool("classic_change_of_variables");
   }
   Log::info() << std::endl;
   Log::info() << classname() << ": max iter = " << ninner
               << ", requested norm reduction = " << gnreduc << std::endl;
   // Define matrices
   const Bmat_ B(J_);
   const HtRinvH_ HtRinvH(J_, lauxMinDiags);
   // Allocate dx and dxh
   // dx
   CtrlInc_ *dx = new CtrlInc_(J_.jb());
   // dxh = B^{-1} dx
   CtrlInc_ dxh(J_.jb());
   // Compute H^T R^{-1} d
   // dx_i = x_i - x_{i-1}; dx_1 = x_1 - x_b
   CtrlInc_ rhs(J_.jb());
   J_.computeGradientFG(rhs);
   if (lclassicChaVar_) {
     // dx = Bdx'
     // Interpolate gradJb to the new inner loop resolution
     if (gradJb_ == 0) {
       gradJb_.reset(new CtrlInc_(J_.jb()));
     } else {
       gradJb_.reset(new CtrlInc_(J_.jb().resolution(), *gradJb_));
     }
     // Calculate first guess gradient
     // -SUM dx' + H^T R^{-1} d
     J_.jb().addGradientFG(rhs, *gradJb_);
   } else {
     // dx = Bdx' + x_b - x_fg
     // Interpolate the initial guess to the new inner loop resolution
     if (dxh0_ == 0) {
       dxh0_.reset(new CtrlInc_(J_.jb()));
     } else {
       dxh0_.reset(new CtrlInc_(J_.jb().resolution(), *dxh0_));
     }
     // Calculate first guess gradient
     // H^T R^{-1} [d + H (x_b - x_fg)]
     const HtRinvHdxFG_ HtRinvHdxFG(J_);
     CtrlInc_ ht_rinv_h_dxfg(J_.jb());
     HtRinvHdxFG.compute(ht_rinv_h_dxfg);
     rhs += ht_rinv_h_dxfg;
     // Set initial guess
     dxh = *dxh0_;
     B.multiply(dxh, *dx);
   }
   Log::info() << classname() << " rhs" << rhs << std::endl;
   // Set J[0] = 0.5 (x_i - x_b)^T B^{-1} (x_i - x_b) + 0.5 d^T R^{-1} d
   const double costJ0Jb = costJ0Jb_;
   const double costJ0JoJc = J_.getCostJoJc();
   // Solve the linear system
   double reduc = this->solve(*dx, dxh, rhs, B, HtRinvH, costJ0Jb, costJ0JoJc,
                              ninner, gnreduc);
   Log::test() << classname() << ": reduction in residual norm = " << reduc
               << std::endl;
   Log::info() << classname() << " output increment:" << *dx << std::endl;
   if (lclassicChaVar_) {
     // dx = Bdx'
     // Update gradJb_
     *gradJb_ += dxh;
     dxh_.push_back(dxh);
     // Update Jb component of J[0]: 0.5 (x_i - x_b)^T B^-1 (x_i - x_b)
     costJ0Jb_ += 0.5 * dot_product(*dx, dxh);
     for (unsigned int jouter = 1; jouter < dxh_.size(); ++jouter) {
       CtrlInc_ dxhtmp(dx->geometry(), dxh_[jouter - 1]);
       costJ0Jb_ += dot_product(*dx, dxhtmp);
     }
   } else {
     // dx = Bdx' + x_b - x_fg
     // Save inital guess for next minimization
     *dxh0_ = dxh;
     // Update Jb component of J[0]: 0.5 (x_i - x_b)^T B^-1 (x_i - x_b)
     costJ0Jb_ = 0.5 * dot_product(*dx, dxh);
     // Tranform dx_k to be defined w.r.t. the first guess
     const CtrlInc_ &dxfg = J_.jb().getFirstGuessIncrement();
     *dx -= dxfg;
   }
   return dx;
 }
References oops::HtRinvHdxFG< MODEL >::compute(), dot_product(), oops::ControlIncrement< MODEL >::geometry(), and oops::BMatrix< MODEL >::multiply().
restart()
template<typename MODEL > void oops::DRMinimizer< MODEL >::restart (const eckit::Configuration &) virtual
Restart the minimizer (virtual method)
Implements oops::Minimizer< MODEL >.
Definition at line 247 of file DRMinimizer.h.
{
   Log::info() << classname() << "::restart starting" << std::endl;
   // GradJb
   ASSERT(conf.has("gradJb"));
   eckit::LocalConfiguration gradjbconf(conf, "gradJb");
   if (gradJb_ == 0) {
     gradJb_.reset(new CtrlInc_(J_.jb()));
   }
   gradJb_->read(gradjbconf);
   Log::info() << classname() << "::restart gradJb: "
               << util::full_precision(dot_product(*gradJb_, *gradJb_))
               << std::endl;
   // dxh
   ASSERT(conf.has("dxh"));
   std::vector<eckit::LocalConfiguration> dxhconfs;
   conf.get("dxh", dxhconfs);
   for (unsigned int jj = 0; jj < dxhconfs.size(); ++jj) {
     CtrlInc_ dxh(J_.jb());
     dxh.read(dxhconfs[jj]);
     dxh_.push_back(dxh);
     Log::info() << classname() << "::restart dxh[" << jj << "]: "
                 << util::full_precision(dot_product(dxh_[jj], dxh_[jj]))
                 << std::endl;
   }
   // costJ0Jb
   ASSERT(conf.has("costJ0Jb"));
   costJ0Jb_ = conf.getDouble("costJ0Jb");
   Log::info() << classname()
               << "::restart costJ0Jb: " << util::full_precision(costJ0Jb_)
               << std::endl;
   Log::info() << classname() << "::restart done" << std::endl;
 }
References dot_product(), util::full_precision(), and oops::ControlIncrement< MODEL >::read().
solve()
template<typename MODEL > virtual double oops::DRMinimizer< MODEL >::solve (CtrlInc_ & , CtrlInc_ & , CtrlInc_ & , const Bmat_ & , const HtRinvH_ & , const double , const double , const int , const double) private pure virtual
Implemented in oops::DRPCGMinimizer< MODEL >, oops::DRGMRESRMinimizer< MODEL >, oops::DRIPCGMinimizer< MODEL >, oops::DRPLanczosMinimizer< MODEL >, and oops::DRPFOMMinimizer< MODEL >.
warmStart()
template<typename MODEL > void oops::DRMinimizer< MODEL >::warmStart (const eckit::Configuration &) inline virtual
Warm start the minimizer (virtual method)
Implements oops::Minimizer< MODEL >.
Definition at line 72 of file DRMinimizer.h.
 {}
Member Data Documentation
costJ0Jb_
template<typename MODEL > double oops::DRMinimizer< MODEL >::costJ0Jb_ private
Cost function J0Jb.
Definition at line 92 of file DRMinimizer.h.
dxh0_
template<typename MODEL > std::unique_ptr<CtrlInc_> oops::DRMinimizer< MODEL >::dxh0_ private
Definition at line 88 of file DRMinimizer.h.
dxh_
template<typename MODEL > std::vector<CtrlInc_> oops::DRMinimizer< MODEL >::dxh_ private
Definition at line 89 of file DRMinimizer.h.
gradJb_
template<typename MODEL > std::unique_ptr<CtrlInc_> oops::DRMinimizer< MODEL >::gradJb_ private
Control increments.
Definition at line 87 of file DRMinimizer.h.
J_
template<typename MODEL > const CostFct_& oops::DRMinimizer< MODEL >::J_ private
Data members.
Definition at line 81 of file DRMinimizer.h.
lclassicChaVar_
template<typename MODEL > bool oops::DRMinimizer< MODEL >::lclassicChaVar_ private
Controls.
Definition at line 84 of file DRMinimizer.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/DRMinimizer.h