OOPS Documentation: oops::Test Class Reference
oops::Test Class Reference abstract
#include <Test.h>
Public Member Functions
Test ()
virtual ~Test ()
int execute (const eckit::Configuration &config) const
Public Member Functions inherited from oops::Application
Application ()
virtual ~Application ()
Private Member Functions
virtual void register_tests () const =0
virtual std::string testid () const =0
std::string appname () const
Static Private Member Functions
static bool init_unit_test ()
Detailed Description
Definition at line 33 of file Test.h.
Constructor & Destructor Documentation
Test()
oops::Test::Test () inline
Definition at line 35 of file Test.h.
 {}
~Test()
virtual oops::Test::~Test () inline virtual
Definition at line 36 of file Test.h.
 {}
Member Function Documentation
appname()
std::string oops::Test::appname () const inline private virtual
Implements oops::Application.
Definition at line 43 of file Test.h.
 { return "oops::Test running " + testid(); }
References testid().
execute()
int oops::Test::execute (const eckit::Configuration & config) const virtual
Implements oops::Application.
Definition at line 48 of file Test.h.
{
   // Setup configuration for tests
   test::TestEnvironment::getInstance().setup(config);
   // Extract the runtime config for the tests from the config file.
   std::string args = config.getString("test_framework_runtime_config");
   // Create a string version of argv
   std::vector<std::string> argvec;
   argvec.push_back(std::string("abcd"));
   eckit::Tokenizer tok(" \n\t");
   tok(args, argvec);
   // Generate the argc and argv arguments for unit_test_main(...)
   int argc = argvec.size();
   char* argv[argc];
   for (int i = 0; i < argc; ++i) {
     argv[i] = new char[argvec[i].size() + 1];
     strcpy(argv[i], argvec[i].c_str());
   }
   // Run the tests
   Log::trace() << "Registering the unit tests" << std::endl;
   register_tests();
   Log::trace() << "Running the unit tests" << std::endl;
   int result = eckit::testing::run_tests(argc, argv, false);
   Log::trace() << "Finished running the unit tests" << std::endl;
   Log::error() << "Finished running the unit tests, result = " << result
                << std::endl;
   // Tidy up
   for (int i = 0; i < argc; ++i) {
     delete[] argv[i];
   }
   // Return test status
   return result;
 }
References register_tests().
init_unit_test()
static bool oops::Test::init_unit_test () inline static private
Definition at line 42 of file Test.h.
 { return true; }
register_tests()
virtual void oops::Test::register_tests () const private pure virtual
Referenced by execute().
testid()
virtual std::string oops::Test::testid () const private pure virtual
Referenced by appname().
The documentation for this class was generated from the following file:
src/oops/runs/Test.h