OOPS Documentation: oops::IncrementalAssimilation< MODEL > Class Template Reference
oops::IncrementalAssimilation< MODEL > Class Template Reference
IncrementalAssimilation implements variational algorithms.
#include <IncrementalAssimilation.h>
Public Member Functions
IncrementalAssimilation (CostFunction< MODEL > &)
Constructor.
~IncrementalAssimilation ()
Destructor.
void assimilate (const eckit::Configuration &)
Perform incremental assimilation.
std::shared_ptr< CtrlVariable_ > getAnalysis () const
Return the analysis.
const bool & skipFinalNonlinearTrajectory () const
Skip the final non-linear trajectory.
Static Public Member Functions
static const std::string classname ()
Private Types
using CtrlInc_ = ControlIncrement< MODEL >
using CtrlVariable_ = ControlVariable< MODEL >
using Geometry_ = Geometry< MODEL >
using Increment_ = Increment< MODEL >
using Minimizer_ = Minimizer< MODEL >
using State_ = State< MODEL >
using Variables_ = Variables< MODEL >
Private Member Functions
void checkpoint (eckit::LocalConfiguration &conf) const
Restart mechanism: checkpoint variational assimilation.
void restart (const eckit::Configuration &conf) const
Restart mechanism: restart variational assimilation.
void connectToRestart (util::Restart &restarter) const
Restart mechanism: connect with the restart mechanism.
void recentreFirstGuess (const eckit::Configuration &conf)
Re-centre First Guess.
void late4Dstart (const eckit::LocalConfiguration &, const std::shared_ptr< StateSaver< State_ > >, const CtrlInc_ &)
Late 4D start mechanism.
const bool & isLate4D () const
Check if the late 4D start mechanism is active.
void setLate4D (const bool &active)
Activate the late 4D start mechanism.
void setSkipFinalNonlinearTrajectory (const bool &skip)
Skip the final non-linear trajectory.
void setOuterLoopBounds (const size_t &)
Set the outer loop bounds.
void setOuterLoopIndex (const size_t &, const eckit::LocalConfiguration &)
Set the outer loop index.
Private Attributes
CostFunction< MODEL > & J_
Data members.
std::shared_ptr< ControlVariable< MODEL > > xx_
First guess.
std::unique_ptr< Minimizer< MODEL > > minim_
Minimizer.
size_t jouter_
Outer loop index.
size_t jstart_
Index of the first outer loop.
size_t jend_
Index of the last outer loop.
bool late4D_
Logical controlling the late 4D start.
bool skipFinalTraj_
Logical controlling skipping the final traj.
Detailed Description
template<typename MODEL>
class oops::IncrementalAssimilation< MODEL >
IncrementalAssimilation implements variational algorithms.
The variational algorithms are implemented using the incremental formulation. IncrementalAssimilation orchestrates the execution of outer loops. Each outer loop consists of three key stages:
Set up the quadratic cost function: compute departures, linearization trajectory, set up linear operators
Minimize the quadratic cost function
Update the first guess
IncrementalAssimilation implements the late 4D start mechanism, orchestrates checkpointing/restart mechanism and warm starts the first guess/minimizer if requested.
IncrementalAssimilation is adapted for single- and multi-executable modes.
IFS: multi-executable mode is default, late 4D start is active by default
Definition at line 64 of file IncrementalAssimilation.h.
Member Typedef Documentation
CtrlInc_
template<typename MODEL > using oops::IncrementalAssimilation< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 65 of file IncrementalAssimilation.h.
CtrlVariable_
template<typename MODEL > using oops::IncrementalAssimilation< MODEL >::CtrlVariable_ = ControlVariable<MODEL> private
Definition at line 66 of file IncrementalAssimilation.h.
Geometry_
template<typename MODEL > using oops::IncrementalAssimilation< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 67 of file IncrementalAssimilation.h.
Increment_
template<typename MODEL > using oops::IncrementalAssimilation< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 68 of file IncrementalAssimilation.h.
Minimizer_
template<typename MODEL > using oops::IncrementalAssimilation< MODEL >::Minimizer_ = Minimizer<MODEL> private
Definition at line 69 of file IncrementalAssimilation.h.
State_
template<typename MODEL > using oops::IncrementalAssimilation< MODEL >::State_ = State<MODEL> private
Definition at line 70 of file IncrementalAssimilation.h.
Variables_
template<typename MODEL > using oops::IncrementalAssimilation< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 71 of file IncrementalAssimilation.h.
Constructor & Destructor Documentation
IncrementalAssimilation()
template<typename MODEL > oops::IncrementalAssimilation< MODEL >::IncrementalAssimilation (CostFunction< MODEL > & J)
Constructor.
Definition at line 147 of file IncrementalAssimilation.h.
     : J_(J),
       xx_(),
       minim_(),
       jouter_(0),
       jstart_(0),
       jend_(0),
       late4D_(false),
       skipFinalTraj_(false) {
   Log::trace() << "IncrementalAssimilation:constructed" << std::endl;
 }
~IncrementalAssimilation()
template<typename MODEL > oops::IncrementalAssimilation< MODEL >::~IncrementalAssimilation () inline
Destructor.
Definition at line 82 of file IncrementalAssimilation.h.
 {}
Member Function Documentation
assimilate()
template<typename MODEL > void oops::IncrementalAssimilation< MODEL >::assimilate (const eckit::Configuration & config)
Perform incremental assimilation.
Initialize first guess from background
Setup configurations of outer loops
Setup the minimizer
Setup the restart mechanism and restart the first guess and incremental assimilation if required
Warm start the first guess (if requested through config)
5.A Re-centre the first guess (if requested through config)
Instantiate the late 4D start utilities
Instantiate the control increment
Set bounds of the loop over outer loops
Perform the outer loop (trajectory + minimization)
9.1 Set current outer loop index
9.2 Register the outer loop in the logbook
9.3 Allow skipping the final nonlinear trajectory; default off
9.4 Set up the late 4D start mechanism (if requested)
9.5 Setup post-processors for the non-linear trajectory run
9.5.1 Setup diagnostic prints
9.5.2 Setup state writer/saver for late 4D start
9.6 Setup the quadratic cost function
9.6.1 Output CCMA
9.7 Warm start the minimizer (if requested)
9.8 Restart the minimizer (if requested)
9.9 Perform the minimization
9.10 Add the control increment to the first guess
9.11 Write the control increment (if requested)
9.12 Clean-up the quadratic cost function (unless late 4D is active)
9.13 Checkpoint the variational assimilation
Compute and save 4D analysis/increment (if late 4D start is active)
10.1 Calculate and write an fields, write increment
10.2 Clean-up
Definition at line 162 of file IncrementalAssimilation.h.
{
   xx_.reset(new CtrlVariable_(J_.jb().getBackground()));
   Log::trace() << "IncrementalAssimilation: first guess has been set up"
                << std::endl;
   std::vector<eckit::LocalConfiguration> iterconfs;
   config.get("variational.iteration", iterconfs);
   const size_t nouterconfSize = iterconfs.size();
   eckit::LocalConfiguration minConf(config, "minimizer");
   minim_.reset(MinFactory<MODEL>::create(minConf, J_));
   util::Restart restarter(
       {"FirstGuess", "Minimizer", "IncrementalAssimilation"});
   this->connectToRestart(restarter);
   restarter.restart({"FirstGuess", "IncrementalAssimilation"});
   if (not restarter.isRestarted() &&
       config.has("variational.WarmStart.FirstGuess")) {
     xx_->read(config.getSubConfiguration("variational.WarmStart.FirstGuess"));
   }
   if (not restarter.isRestarted() &&
       config.has("variational.WarmStart.RecentreFirstGuess")) {
     eckit::LocalConfiguration recentreFirstGuessConf(
         config, "variational.WarmStart.RecentreFirstGuess");
     this->recentreFirstGuess(recentreFirstGuessConf);
   }
   std::shared_ptr<StateSaver<State_> > stateSaver;
   std::shared_ptr<StateWriter<State_> > stateWriter;
   std::unique_ptr<eckit::LocalConfiguration> late4Dconf;
   std::unique_ptr<CtrlInc_> dx;
   this->setOuterLoopBounds(nouterconfSize);
   Log::info() << "Running incremental assimilation with " << nouterconfSize
               << " outer iterations." << std::endl;
   for (size_t jj = jstart_; jj < jend_; ++jj) {
     this->setOuterLoopIndex(jj, iterconfs[jj]);
     //  Get configuration for current outer iteration
     Log::info() << "IncrementalAssimilation: Configuration for outer iteration "
                 << jouter_ << ":\n"
                 << iterconfs[jj];
     util::LogbookWriter<size_t> log("OuterLoop", jouter_);
     this->setSkipFinalNonlinearTrajectory(false);
     if (iterconfs[jj].has("skipFinalTraj")) {
       const bool skipTraj = iterconfs[jj].getBool("skipFinalTraj");
       this->setSkipFinalNonlinearTrajectory(skipTraj);
     }
     if (iterconfs[jj].has("late4d")) {
       this->setLate4D(true);
       late4Dconf.reset(new eckit::LocalConfiguration(iterconfs[jj], "late4d"));
     }
     PostProcessor<State_> post;
     if (iterconfs[jj].has("prints")) {
       const eckit::LocalConfiguration prtConfig(iterconfs[jj], "prints");
       post.enrollProcessor(new StateInfo<State_>("traj", prtConfig));
     }
     if (this->isLate4D()) {
       const eckit::LocalConfiguration late4DstateConf(*late4Dconf, "state");
       if (late4DstateConf.has("writeToDisk")) {
         const eckit::LocalConfiguration late4DstateWriteConf(late4DstateConf,
                                                              "writeToDisk");
         stateWriter.reset(new StateWriter<State_>(late4DstateWriteConf));
         post.enrollProcessor(stateWriter);
       } else {
         stateSaver.reset(new StateSaver<State_>(late4DstateConf));
         post.enrollProcessor(stateSaver);
       }
     }
     J_.linearize(*xx_, iterconfs[jj], post);
     {
        restarter.checkpoint(iterconfs[jj], {"CostFunction"});
        util::LogbookWriter<size_t> log("CostFunctionCheckpoint", jouter_);
     }
     if (jouter_ == 0 && config.has("variational.WarmStart.Minimizer")) {
       minim_->warmStart(
           config.getSubConfiguration("variational.WarmStart.Minimizer"));
     }
     if (jj == jstart_) restarter.restart({"Minimizer"});
     dx.reset(minim_->minimize(iterconfs[jj]));
     if (jj == jend_) minim_.reset();
     J_.addIncrement(*xx_, *dx);
     if (iterconfs[jj].has("increment"))
       dx->write(iterconfs[jj].getSubConfiguration("increment"));
     if (!isLate4D()) J_.resetLinearization();
     restarter.checkpoint(
         iterconfs[jj],
         {"FirstGuess", "Minimizer", "IncrementalAssimilation"});
   }
   if (this->isLate4D()) {
     this->late4Dstart(*late4Dconf, stateSaver, *dx);
     stateSaver.reset();
   }
 }
References oops::PostProcessor< FLDS >::enrollProcessor().
Referenced by oops::Variational< MODEL >::execute().
checkpoint()
template<typename MODEL > void oops::IncrementalAssimilation< MODEL >::checkpoint (eckit::LocalConfiguration & conf) const private
Restart mechanism: checkpoint variational assimilation.
The checkpoint mechanism stores the current outer loop index to know where to restart in case of failure
Definition at line 336 of file IncrementalAssimilation.h.
{
   conf.set("Iteration", jouter_);
 }
classname()
template<typename MODEL > static const std::string oops::IncrementalAssimilation< MODEL >::classname () inline static
Definition at line 74 of file IncrementalAssimilation.h.
{
     return "oops::IncrementalAssimilation";
   }
connectToRestart()
template<typename MODEL > void oops::IncrementalAssimilation< MODEL >::connectToRestart (util::Restart & restarter) const private
Restart mechanism: connect with the restart mechanism.
The restart/checkpoint mechanism works by calling callback functions of various components of the system: CostFunction, Minimizer, FirstGuess and IncrementalAssimilation; Each callback function takes a configuration as input
Register checkpoint callback functions
Register restart callback functions
Definition at line 357 of file IncrementalAssimilation.h.
{
   restarter.connectChkptCallback(
       "CostFunction",
       [this](eckit::LocalConfiguration &conf) { return J_.checkpoint(conf); });
   restarter.connectChkptCallback("Minimizer",
                                  [this](eckit::LocalConfiguration &conf) {
                                    return minim_->checkpoint(conf);
                                  });
   restarter.connectChkptCallback(
       "FirstGuess",
       [this](eckit::LocalConfiguration &conf) { return xx_->write(conf); });
   restarter.connectChkptCallback("IncrementalAssimilation",
                                  [this](eckit::LocalConfiguration &conf) {
                                    return this->checkpoint(conf);
                                  });
   restarter.connectRstrtCallback(
       "CostFunction",
       [this](const eckit::Configuration &conf) { return J_.restart(conf); });
   restarter.connectRstrtCallback("Minimizer",
                                  [this](const eckit::Configuration &conf) {
                                    return minim_->restart(conf);
                                  });
   restarter.connectRstrtCallback(
       "FirstGuess",
       [this](const eckit::Configuration &conf) { return xx_->read(conf); });
   restarter.connectRstrtCallback(
       "IncrementalAssimilation",
       [this](const eckit::Configuration &conf) { return this->restart(conf); });
 }
getAnalysis()
template<typename MODEL > std::shared_ptr<CtrlVariable_> oops::IncrementalAssimilation< MODEL >::getAnalysis () const inline
Return the analysis.
Definition at line 88 of file IncrementalAssimilation.h.
{
     ASSERT(xx_);
     return xx_;
   }
References oops::IncrementalAssimilation< MODEL >::xx_.
Referenced by oops::Variational< MODEL >::execute().
isLate4D()
template<typename MODEL > const bool& oops::IncrementalAssimilation< MODEL >::isLate4D () const inline private
Check if the late 4D start mechanism is active.
Definition at line 115 of file IncrementalAssimilation.h.
 { return late4D_; }
References oops::IncrementalAssimilation< MODEL >::late4D_.
late4Dstart()
template<typename MODEL > void oops::IncrementalAssimilation< MODEL >::late4Dstart (const eckit::LocalConfiguration & conf, const std::shared_ptr< StateSaver< State_ > > stateSaver, const CtrlInc_ & dx) private
Late 4D start mechanism.
Late 4D start mechanism is applied in the last outer loop.
The mechanims consists of the following steps: A.) Record/Save \(x_{fg}^{steps}\) during the first guess trajectory; B.) Propagate the tangent linear model and record \(dx_{fg}^{steps}\); C.) Perform sanity checks on \(dx_{fg}^{steps}\); D.) Obtain 'an' fields: \(x_{an}^{steps} = x_{fg}^{steps} + dx_{fg}^{steps}\); E.) Write out 'an' fields and \(dx_{fg}^{steps}\);
Propagate the increment to the requested times This is achieved by setting up a StateSaver templated on Increment and adding it to the post processor that is attached to the tangent linear model propagation
Retrieve the recorded increments
Perform sanity checks on the retrieved increments based on configuration
Control skipping the final nonlinear trajectory
Write ObsAux, ModAux
Reset linearization, close ODB
Write 4V fields (+0H)
Register the sanity check outcome in the logbook
Retrieve saved FG states if kept in memory
Check if all the sanity tests passed. Skip the final trajecotry if this is the case
Read in written out FG states if they are not available in memory
Release first guess
Compute and write AN fields
13.1 Add increment to the first guess state
13.2 Write AN fields
13.3 Write AN increments
13.4 Release AN fields
Definition at line 436 of file IncrementalAssimilation.h.
{
   Log::info() << "IncrementalAssimilation::late4Dstart starting" << std::endl;
   const eckit::LocalConfiguration late4DstateConf(conf, "state");
   PostProcessorTL<Increment_> cost;
   PostProcessor<Increment_> post;
   std::shared_ptr<StateSaver<Increment_> > incrementSaver;
   incrementSaver.reset(new StateSaver<Increment_>(late4DstateConf));
   post.enrollProcessor(incrementSaver);
   CtrlInc_ dxtmp(dx);
   J_.runTL(dxtmp, cost, post);
   const std::vector<std::shared_ptr<Increment_> > &increments(
       incrementSaver->releaseFields());
   bool lSanityCheckPassed = true;
   std::vector<eckit::LocalConfiguration> confs;
   if (late4DstateConf.has("incrementSanityChecks"))
     late4DstateConf.get("incrementSanityChecks", confs);
   for (auto const &config : confs) {
     const std::vector<std::string> varname = config.getStringVector("variables");
     const double zmin = config.getDouble("min");
     const double zmax = config.getDouble("max");
     Variables_ var(config);
     for (auto const &incr : increments) {
       const double zincmin = incr->min(var);
       const double zincmax = incr->max(var);
       Log::info() << "IncrementalAssimilation::late4Dstart " << std::endl
                   << "  Sanity Test: date: " << incr->validTime()
                   << ", variable: " << varname[0]
                   << ", bounds: (" << zmin << ", " << zmax << ")"
                   << ", min = " << zincmin
                   << ", max = " << zincmax << std::endl;
       if (zincmin >= zmin && zincmax <= zmax) {
         Log::info() << "  Sanity Test: passed" << std::endl;
       } else {
         Log::info() << "  Sanity Test: NOT passed" << std::endl;
         lSanityCheckPassed = false;
         // Don't skip final trajectory
         this->setSkipFinalNonlinearTrajectory(false);
       }
     }
   }
   if (lSanityCheckPassed) {
     this->setSkipFinalNonlinearTrajectory(true);
   } else {
     this->setSkipFinalNonlinearTrajectory(false);
   }
   if (conf.has("skipFinalTraj")) {
     this->setSkipFinalNonlinearTrajectory(conf.getBool("skipFinalTraj"));
   }
   xx_->obsVar().write(conf);
   xx_->modVar().write(conf);
   J_.resetLinearization();
   if (conf.getBool("write4Vfields") || not lSanityCheckPassed) {
     xx_->state()[0].write(late4DstateConf);
     util::LogbookWriter<bool> log("4VfieldsWrittenOut", true);
   }
   util::LogbookWriter<bool> log("Late4D_check", lSanityCheckPassed);
   std::vector<std::shared_ptr<State_> > states;
   if (stateSaver) states = stateSaver->releaseFields();
   if (lSanityCheckPassed) {
     Log::info() << "IncrementalAssimilation::late4Dstart " << std::endl
                 << "  All increment sanity tests PASSED   " << std::endl
                 << "  Skipping final non-linear trajectory" << std::endl
                 << conf << std::endl;
     if (late4DstateConf.has("writeToDisk")) {
       eckit::LocalConfiguration writeToDiskConf(
           late4DstateConf.getSubConfiguration("writeToDisk"));
       ASSERT(states.size() == 0);
       ASSERT(writeToDiskConf.has("restart_file"));
       ASSERT(writeToDiskConf.has("steps"));
       util::DateTime refTime(xx_->state()[0].validTime());
       const std::string restartFileBase =
           writeToDiskConf.getString("restart_file");
       const std::string steps = writeToDiskConf.getString("steps");
       eckit::Tokenizer tok("\t\n\v\f\r !\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~");
       std::vector<std::string> tokens;
       tok(steps, tokens);
       for (const std::string &token : tokens) {
         util::DateTime validTime(refTime);
         const util::Duration step(token);
         validTime += step;
         std::string restartFile = restartFileBase + validTime.toString();
         Log::info() << "IncrementalAssimilation::late4Dstart " << std::endl
                     << "  -> read in FG state: " << restartFile << std::endl;
         eckit::LocalConfiguration config(writeToDiskConf);
         config.set("restart_file", restartFile);
         config.set("step", step.toString());
         std::shared_ptr<State_> state(new State_(xx_->state()[0]));
         state->read(config);
         states.push_back(state);
       }
     }
     size_t nAnStates = states.size();
     ASSERT(increments.size() == nAnStates);
     if (skipFinalNonlinearTrajectory()) xx_.reset();
     for (size_t jj = 0; jj < nAnStates; ++jj) {
       *states[jj] += *increments[jj];
       states[jj]->write(late4DstateConf);
       increments[jj]->write(late4DstateConf);
       Log::info() << "IncrementalAssimilation::late4Dstart " << std::endl
                   << "  State An valid at: " << states[jj]->validTime()
                   << " written out." << std::endl;
       states[jj].reset();
     }
   }
   Log::info() << "IncrementalAssimilation::late4Dstart finished" << std::endl;
 }
References oops::PostProcessor< FLDS >::enrollProcessor().
recentreFirstGuess()
template<typename MODEL > void oops::IncrementalAssimilation< MODEL >::recentreFirstGuess (const eckit::Configuration & conf) private
Re-centre First Guess.
Re-centre first-guess
Setup re-centring increment
Re-centre first guess
Definition at line 399 of file IncrementalAssimilation.h.
{
   Log::trace() << "IncrementalAssimilation<MODEL>::recentreFirstGuess start"
                << std::endl;
   Log::info() << "IncrementalAssimilation<MODEL>::recentreFirstGuess enabled"
               << std::endl;
   Geometry_ fgRecResol(conf.getSubConfiguration("resolution"));
   Variables_ fgRecVars(conf);
   util::DateTime fgRecValidTime(xx_->state()[0].validTime());
   Increment_ fgRecIncr(fgRecResol, fgRecVars, fgRecValidTime);
   fgRecIncr.read(conf.getSubConfiguration("increment"));
   xx_->state()[0] += fgRecIncr;
   Log::trace() << "IncrementalAssimilation<MODEL>::recentreFirstGuess done"
                << std::endl;
 }
References oops::Increment< MODEL >::read().
restart()
template<typename MODEL > void oops::IncrementalAssimilation< MODEL >::restart (const eckit::Configuration & conf) const private
Restart mechanism: restart variational assimilation.
Set the loop over the outer loops to start from the last completed outer loop recorded in the restart configuration file
Definition at line 346 of file IncrementalAssimilation.h.
{
   jstart_ = conf.getUnsigned("Iteration");
   ++jstart_;
 }
setLate4D()
template<typename MODEL > void oops::IncrementalAssimilation< MODEL >::setLate4D (const bool & active) inline private
Activate the late 4D start mechanism.
Definition at line 118 of file IncrementalAssimilation.h.
 { late4D_ = active; }
References oops::IncrementalAssimilation< MODEL >::late4D_.
setOuterLoopBounds()
template<typename MODEL > void oops::IncrementalAssimilation< MODEL >::setOuterLoopBounds (const size_t & nouterconfSize) private
Set the outer loop bounds.
In single executable mode nouterconfSize is set to the total number of outer loops while in multi-executable mode it is set to one.
Definition at line 310 of file IncrementalAssimilation.h.
{
   jend_ = nouterconfSize;
   if (jstart_ >= jend_) {
     jstart_ = 0;
   }
 }
setOuterLoopIndex()
template<typename MODEL > void oops::IncrementalAssimilation< MODEL >::setOuterLoopIndex (const size_t & jouter, const eckit::LocalConfiguration & conf) private
Set the outer loop index.
Set the current outer loop index; it is set based on the outer loop index (jouter) or based on the configuration entry (relied upon in multi executable mode
Definition at line 324 of file IncrementalAssimilation.h.
{
   jouter_ = jouter;
   if (conf.has("iteration")) jouter_ = conf.getInt("iteration");
 }
setSkipFinalNonlinearTrajectory()
template<typename MODEL > void oops::IncrementalAssimilation< MODEL >::setSkipFinalNonlinearTrajectory (const bool & skip) inline private
Skip the final non-linear trajectory.
Definition at line 122 of file IncrementalAssimilation.h.
{
     skipFinalTraj_ = skip;
   }
References oops::IncrementalAssimilation< MODEL >::skipFinalTraj_.
skipFinalNonlinearTrajectory()
template<typename MODEL > const bool& oops::IncrementalAssimilation< MODEL >::skipFinalNonlinearTrajectory () const inline
Skip the final non-linear trajectory.
Definition at line 94 of file IncrementalAssimilation.h.
 { return skipFinalTraj_; }
References oops::IncrementalAssimilation< MODEL >::skipFinalTraj_.
Referenced by oops::Variational< MODEL >::execute().
Member Data Documentation
J_
template<typename MODEL > CostFunction<MODEL>& oops::IncrementalAssimilation< MODEL >::J_ private
Data members.
Cost function
Definition at line 133 of file IncrementalAssimilation.h.
jend_
template<typename MODEL > size_t oops::IncrementalAssimilation< MODEL >::jend_ mutable private
Index of the last outer loop.
Definition at line 139 of file IncrementalAssimilation.h.
jouter_
template<typename MODEL > size_t oops::IncrementalAssimilation< MODEL >::jouter_ private
Outer loop index.
Definition at line 137 of file IncrementalAssimilation.h.
jstart_
template<typename MODEL > size_t oops::IncrementalAssimilation< MODEL >::jstart_ mutable private
Index of the first outer loop.
Definition at line 138 of file IncrementalAssimilation.h.
late4D_
template<typename MODEL > bool oops::IncrementalAssimilation< MODEL >::late4D_ private
Logical controlling the late 4D start.
Definition at line 140 of file IncrementalAssimilation.h.
Referenced by oops::IncrementalAssimilation< MODEL >::isLate4D(), and oops::IncrementalAssimilation< MODEL >::setLate4D().
minim_
template<typename MODEL > std::unique_ptr<Minimizer<MODEL> > oops::IncrementalAssimilation< MODEL >::minim_ private
Minimizer.
Definition at line 135 of file IncrementalAssimilation.h.
skipFinalTraj_
template<typename MODEL > bool oops::IncrementalAssimilation< MODEL >::skipFinalTraj_ private
Logical controlling skipping the final traj.
Definition at line 141 of file IncrementalAssimilation.h.
Referenced by oops::IncrementalAssimilation< MODEL >::setSkipFinalNonlinearTrajectory(), and oops::IncrementalAssimilation< MODEL >::skipFinalNonlinearTrajectory().
xx_
template<typename MODEL > std::shared_ptr<ControlVariable<MODEL> > oops::IncrementalAssimilation< MODEL >::xx_ private
First guess.
Definition at line 134 of file IncrementalAssimilation.h.
Referenced by oops::IncrementalAssimilation< MODEL >::getAnalysis().
The documentation for this class was generated from the following file:
src/oops/assimilation/IncrementalAssimilation.h