OOPS Documentation: oops::CostJb4D< MODEL > Class Template Reference
oops::CostJb4D< MODEL > Class Template Reference
4D Jb Cost Function
#include <CostJb4D.h>
Public Member Functions
CostJb4D (const eckit::Configuration &, const Geometry_ &, const Variables_ &, const util::Duration &, const State4D_ &)
Construct \(J_b\).
virtual ~CostJb4D ()
Destructor.
JqTerm< MODEL > * initializeJq () const override
Empty Jq observer.
void computeIncrement (const State4D_ &, const State4D_ &, Increment4D_ &) const override
Get increment from state (usually first guess).
void linearize (const State4D_ &, const Geometry_ &, const eckit::Configuration &) override
Linearize before the linear computations.
void addGradient (const Increment4D_ &, Increment4D_ &, Increment4D_ &) const override
Add Jb gradient.
JqTermTL< MODEL > * initializeJqTL () const override
Empty TL Jq observer.
JqTermAD< MODEL > * initializeJqAD (const Increment4D_ &) const override
Empty AD Jq observer.
void Bmult (const Increment4D_ &, Increment4D_ &) const override
Multiply by \(B\) and \(B^{-1}\).
void Bminv (const Increment4D_ &, Increment4D_ &) const override
Multiply by \(B^{-1}\).
void BmultSqrt (const IncrCtlVec4D_ &, Increment4D_ &) const override
Multiply by \(B^{1/2}\) and \([B^{1/2}]^T\).
void BmultSqrtTrans (const Increment4D_ &, IncrCtlVec4D_ &) const override
Multiply by \([B^{1/2}]^T\).
const ModelSpaceCovarianceBase< MODEL > & covar () const
Access to B.
void randomize (Increment4D_ &) const override
Randomize.
unsigned int nstates () const override
Create new increment (set to 0).
Increment_ * newStateIncrement (const unsigned int) const override
Create new increment (set to 0).
unsigned int nchistates () const override
Create new control vector.
IncrCtlVec_ * newIncrCtlVec (const unsigned int) const override
Create new control vector.
IncrModCtlVec_ * newIncrModCtlVec () const override
Create new control vector (mod)
IncrEnsCtlVec_ * newIncrEnsCtlVec () const override
Create new control vector (ens)
Public Member Functions inherited from oops::CostJbState< MODEL >
CostJbState ()
Constructor.
virtual ~CostJbState ()
Destructor.
Private Types
using CtrlInc_ = ControlIncrement< MODEL >
using Geometry_ = Geometry< MODEL >
using Increment_ = Increment< MODEL >
using Increment4D_ = Increment4D< MODEL >
using IncrCtlVec_ = IncrCtlVec< MODEL >
using IncrCtlVec4D_ = IncrCtlVec4D< MODEL >
using IncrModCtlVec_ = IncrModCtlVec< MODEL >
using IncrEnsCtlVec_ = IncrEnsCtlVec< MODEL >
using State4D_ = State4D< MODEL >
using Variables_ = Variables< MODEL >
Private Attributes
std::shared_ptr< ModelSpaceCovariance4DBase< MODEL > > B4D_
const Variables_ controlvars_
std::unique_ptr< const Geometry_ > resol_
std::vector< util::DateTime > times_
Detailed Description
template<typename MODEL>
class oops::CostJb4D< MODEL >
4D Jb Cost Function
CostJb4D encapsulates the generalized four dimensional Jb term of the 4D-Ens-Var cost function. NOTE: for the square root formulation it is assumed that the localization matrix is constant L_bar = [I I .. I]^T L [I I .. I]
Definition at line 58 of file CostJb4D.h.
Member Typedef Documentation
CtrlInc_
template<typename MODEL > using oops::CostJb4D< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 59 of file CostJb4D.h.
Geometry_
template<typename MODEL > using oops::CostJb4D< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 60 of file CostJb4D.h.
IncrCtlVec4D_
template<typename MODEL > using oops::CostJb4D< MODEL >::IncrCtlVec4D_ = IncrCtlVec4D<MODEL> private
Definition at line 64 of file CostJb4D.h.
IncrCtlVec_
template<typename MODEL > using oops::CostJb4D< MODEL >::IncrCtlVec_ = IncrCtlVec<MODEL> private
Definition at line 63 of file CostJb4D.h.
Increment4D_
template<typename MODEL > using oops::CostJb4D< MODEL >::Increment4D_ = Increment4D<MODEL> private
Definition at line 62 of file CostJb4D.h.
Increment_
template<typename MODEL > using oops::CostJb4D< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 61 of file CostJb4D.h.
IncrEnsCtlVec_
template<typename MODEL > using oops::CostJb4D< MODEL >::IncrEnsCtlVec_ = IncrEnsCtlVec<MODEL> private
Definition at line 66 of file CostJb4D.h.
IncrModCtlVec_
template<typename MODEL > using oops::CostJb4D< MODEL >::IncrModCtlVec_ = IncrModCtlVec<MODEL> private
Definition at line 65 of file CostJb4D.h.
State4D_
template<typename MODEL > using oops::CostJb4D< MODEL >::State4D_ = State4D<MODEL> private
Definition at line 67 of file CostJb4D.h.
Variables_
template<typename MODEL > using oops::CostJb4D< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 68 of file CostJb4D.h.
Constructor & Destructor Documentation
CostJb4D()
template<typename MODEL > oops::CostJb4D< MODEL >::CostJb4D (const eckit::Configuration & config, const Geometry_ & resolouter, const Variables_ & ctlvars, const util::Duration & , const State4D_ & xb)
Construct \(J_b\).
Definition at line 145 of file CostJb4D.h.
     : B4D_(), controlvars_(ctlvars), resol_(), times_() {
   // Create one row of blocks of the whole BMatrix, one object for each
   // subwindow. Each object stands for all blocks in the same column of the B
   // Matrix.
   // It can be from any concrete class of ModelSpaceCovarianceBase,
   // according to the configuration file.
   const eckit::LocalConfiguration covar(config, "Covariance");
   B4D_.reset(
       Covariance4DFactory<MODEL>::create(covar, resolouter, controlvars_, xb));
   times_.clear();
   if (covar.has("envar_times")) {
     std::vector<eckit::LocalConfiguration> envar_times;
     covar.get("envar_times", envar_times);
     for (size_t jsub = 0; jsub < envar_times.size(); ++jsub) {
       times_.push_back(util::DateTime(envar_times[jsub].getString("reference_time") ));
     }
   }
   else {
     for (unsigned jsub = 0; jsub < xb.statesNumber(); ++jsub) {
       times_.push_back(xb[jsub].validTime());
     }
   }
   Log::trace() << "CostJb4D contructed." << std::endl;
 }
References oops::CostJb4D< MODEL >::B4D_, oops::CostJb4D< MODEL >::controlvars_, oops::CostJb4D< MODEL >::covar(), oops::State4D< MODEL >::statesNumber(), and oops::CostJb4D< MODEL >::times_.
~CostJb4D()
template<typename MODEL > virtual oops::CostJb4D< MODEL >::~CostJb4D () inline virtual
Destructor.
Definition at line 76 of file CostJb4D.h.
 {}
Member Function Documentation
addGradient()
template<typename MODEL > void oops::CostJb4D< MODEL >::addGradient (const Increment4D_ & dxFG, Increment4D_ & grad, Increment4D_ & gradJb) const override virtual
Add Jb gradient.
Implements oops::CostJbState< MODEL >.
Definition at line 199 of file CostJb4D.h.
{
   grad -= gradJb;
 }
Bminv()
template<typename MODEL > void oops::CostJb4D< MODEL >::Bminv (const Increment4D_ & , Increment4D_ &) const override virtual
Multiply by \(B^{-1}\).
Implements oops::CostJbState< MODEL >.
Definition at line 215 of file CostJb4D.h.
{
   B4D_->inverseMultiply(dxin, dxout);
 }
Bmult()
template<typename MODEL > void oops::CostJb4D< MODEL >::Bmult (const Increment4D_ & dxin, Increment4D_ & dxout) const override virtual
Multiply by \(B\) and \(B^{-1}\).
Implements oops::CostJbState< MODEL >.
Definition at line 207 of file CostJb4D.h.
{
   B4D_->multiply(dxin, dxout);
 }
BmultSqrt()
template<typename MODEL > void oops::CostJb4D< MODEL >::BmultSqrt (const IncrCtlVec4D_ & dvin, Increment4D_ & dxout) const override virtual
Multiply by \(B^{1/2}\) and \([B^{1/2}]^T\).
Implements oops::CostJbState< MODEL >.
Definition at line 223 of file CostJb4D.h.
{
   B4D_->multiplySqrt(dvin[0], dxout);
 }
BmultSqrtTrans()
template<typename MODEL > void oops::CostJb4D< MODEL >::BmultSqrtTrans (const Increment4D_ & , IncrCtlVec4D_ &) const override virtual
Multiply by \([B^{1/2}]^T\).
Implements oops::CostJbState< MODEL >.
Definition at line 231 of file CostJb4D.h.
{
   B4D_->multiplySqrtTrans(dxin, dvout[0]);
 }
computeIncrement()
template<typename MODEL > void oops::CostJb4D< MODEL >::computeIncrement (const State4D_ & xb, const State4D_ & fg, Increment4D_ & dx) const override virtual
Get increment from state (usually first guess).
Implements oops::CostJbState< MODEL >.
Definition at line 186 of file CostJb4D.h.
{
   if (xb.statesNumber() == 1) {
     dx.zero();
     dx[0].diff(fg[0], xb[0]);
   } else {
     dx.diff(fg, xb);
   }
 }
References oops::Increment4D< MODEL >::diff(), oops::State4D< MODEL >::statesNumber(), and oops::Increment4D< MODEL >::zero().
covar()
template<typename MODEL > const ModelSpaceCovarianceBase<MODEL>& oops::CostJb4D< MODEL >::covar () const inline virtual
Access to B.
Implements oops::CostJbState< MODEL >.
Definition at line 109 of file CostJb4D.h.
 { return B4D_->covar(); }
References oops::CostJb4D< MODEL >::B4D_.
Referenced by oops::CostJb4D< MODEL >::CostJb4D().
initializeJq()
template<typename MODEL > JqTerm<MODEL>* oops::CostJb4D< MODEL >::initializeJq () const inline override virtual
Empty Jq observer.
Implements oops::CostJbState< MODEL >.
Definition at line 79 of file CostJb4D.h.
 { return 0; }
initializeJqAD()
template<typename MODEL > JqTermAD<MODEL>* oops::CostJb4D< MODEL >::initializeJqAD (const Increment4D_ &) const inline override virtual
Empty AD Jq observer.
Implements oops::CostJbState< MODEL >.
Definition at line 96 of file CostJb4D.h.
{
     return 0;
   }
initializeJqTL()
template<typename MODEL > JqTermTL<MODEL>* oops::CostJb4D< MODEL >::initializeJqTL () const inline override virtual
Empty TL Jq observer.
Implements oops::CostJbState< MODEL >.
Definition at line 93 of file CostJb4D.h.
 { return 0; }
linearize()
template<typename MODEL > void oops::CostJb4D< MODEL >::linearize (const State4D_ & fg, const Geometry_ & resolinner, const eckit::Configuration & innerConf) override virtual
Linearize before the linear computations.
Implements oops::CostJbState< MODEL >.
Definition at line 177 of file CostJb4D.h.
{
   resol_.reset(new Geometry_(resolinner));
   B4D_->linearize(fg, *resol_, innerConf);
 }
nchistates()
template<typename MODEL > unsigned int oops::CostJb4D< MODEL >::nchistates () const inline override virtual
Create new control vector.
Implements oops::CostJbState< MODEL >.
Definition at line 119 of file CostJb4D.h.
 { return 1; }
newIncrCtlVec()
template<typename MODEL > IncrCtlVec< MODEL > * oops::CostJb4D< MODEL >::newIncrCtlVec (const unsigned int) const override virtual
Create new control vector.
Implements oops::CostJbState< MODEL >.
Definition at line 258 of file CostJb4D.h.
{
   return new IncrCtlVec_(*this, times_[isub]);
 }
newIncrEnsCtlVec()
template<typename MODEL > IncrEnsCtlVec_* oops::CostJb4D< MODEL >::newIncrEnsCtlVec () const inline override virtual
Create new control vector (ens)
Implements oops::CostJbState< MODEL >.
Definition at line 128 of file CostJb4D.h.
{
     return B4D_->newIncrEnsCtlVec();
   }
References oops::CostJb4D< MODEL >::B4D_.
newIncrModCtlVec()
template<typename MODEL > IncrModCtlVec_* oops::CostJb4D< MODEL >::newIncrModCtlVec () const inline override virtual
Create new control vector (mod)
Implements oops::CostJbState< MODEL >.
Definition at line 123 of file CostJb4D.h.
{
     return B4D_->newIncrModCtlVec();
   }
References oops::CostJb4D< MODEL >::B4D_.
newStateIncrement()
template<typename MODEL > Increment< MODEL > * oops::CostJb4D< MODEL >::newStateIncrement (const unsigned int) const override virtual
Create new increment (set to 0).
Implements oops::CostJbState< MODEL >.
Definition at line 248 of file CostJb4D.h.
{
   Increment_ *incr =
       new Increment_(*resol_, controlvars_, times_[0], times_[isub]);
   return incr;
 }
nstates()
template<typename MODEL > unsigned int oops::CostJb4D< MODEL >::nstates () const inline override virtual
Create new increment (set to 0).
Implements oops::CostJbState< MODEL >.
Definition at line 115 of file CostJb4D.h.
 { return times_.size(); }
References oops::CostJb4D< MODEL >::times_.
randomize()
template<typename MODEL > void oops::CostJb4D< MODEL >::randomize (Increment4D_ & dx) const override virtual
Randomize.
Implements oops::CostJbState< MODEL >.
Definition at line 239 of file CostJb4D.h.
{
   /* TODO:
     B4D_[jsub].randomize(dx[jsub]);
   */
 }
Member Data Documentation
B4D_
template<typename MODEL > std::shared_ptr<ModelSpaceCovariance4DBase<MODEL> > oops::CostJb4D< MODEL >::B4D_ private
Definition at line 133 of file CostJb4D.h.
Referenced by oops::CostJb4D< MODEL >::CostJb4D(), oops::CostJb4D< MODEL >::covar(), oops::CostJb4D< MODEL >::newIncrEnsCtlVec(), and oops::CostJb4D< MODEL >::newIncrModCtlVec().
controlvars_
template<typename MODEL > const Variables_ oops::CostJb4D< MODEL >::controlvars_ private
Definition at line 134 of file CostJb4D.h.
Referenced by oops::CostJb4D< MODEL >::CostJb4D().
resol_
template<typename MODEL > std::unique_ptr<const Geometry_> oops::CostJb4D< MODEL >::resol_ private
Definition at line 135 of file CostJb4D.h.
times_
template<typename MODEL > std::vector<util::DateTime> oops::CostJb4D< MODEL >::times_ private
Definition at line 136 of file CostJb4D.h.
Referenced by oops::CostJb4D< MODEL >::CostJb4D(), and oops::CostJb4D< MODEL >::nstates().
The documentation for this class was generated from the following file:
src/oops/assimilation/CostJb4D.h