OOPS Documentation: oops::IncrCtlVec< MODEL > Class Template Reference
oops::IncrCtlVec< MODEL > Class Template Reference
IncrCtlVec Class.
#include <CostJb3D.h>
Public Member Functions
IncrCtlVec (const JbState_ &, const util::DateTime &)
Constructor.
IncrCtlVec (const JbState_ &, const IncrCtlVec &)
Constructor with copy initialization.
IncrCtlVec (const IncrCtlVec &, const bool copy=true)
Copy constructor.
virtual ~IncrCtlVec ()
Destructor.
IncrModCtlVec_ & modCtlVec ()
Return component acted upon the modelled covariance matrix.
const IncrModCtlVec_ & modCtlVec () const
Return constant component acted upon the modelled covariance matrix.
IncrEnsCtlVec_ & ensCtlVec (const int ii)
Return component acted upon the ensemble covariance matrix.
const IncrEnsCtlVec_ & ensCtlVec (const int ii) const
Return constant component acted upon the ensemble covariance matrix.
const util::DateTime validTime () const
Time.
void zero ()
\(dv_1 = 0 \)
IncrCtlVec & operator= (const IncrCtlVec &)
\(dv_1 = dv_2 \)
IncrCtlVec & operator+= (const IncrCtlVec &)
\(dv_1 = dv_1 + dv_2 \)
IncrCtlVec & operator-= (const IncrCtlVec &)
\(dv_1 = dv_1 - dv_2 \)
IncrCtlVec & operator*= (const double &)
\(dv_1 = dv_1 * c \)
void axpy (const double &, const IncrCtlVec &, const bool check=true)
\(dv_1 = dv_1 * c dv_2 \)
double dot_product_with (const IncrCtlVec &) const
\(<dv_1,dv_1> = dv_1^T dv_1 \)
void schur_product_with (const IncrCtlVec &)
Hadamard product (element-wise)
void random ()
Random control vector.
void read (const eckit::Configuration &)
Read control vector.
void write (const eckit::Configuration &) const
Write control vector.
double norm () const
L-2 norm.
Static Public Member Functions
static const std::string classname ()
Private Types
using EnsemblesCollection_ = EnsemblesCollection< MODEL >
using IncrEnsCtlVec_ = IncrEnsCtlVec< MODEL >
using IncrModCtlVec_ = IncrModCtlVec< MODEL >
using JbState_ = CostJbState< MODEL >
Private Member Functions
IncrModCtlVec_ * newIncrModCtlVec (const JbState_ &) const
std::vector< std::unique_ptr< IncrEnsCtlVec_ > > newIncrEnsCtlVecCollection (const JbState_ &) const
void print (std::ostream &) const
Private Attributes
util::DateTime time_
Valid time.
unsigned int ensSize_
Size of the ensemble component.
std::unique_ptr< IncrModCtlVec_ > incrModCtlVec_
std::vector< std::unique_ptr< IncrEnsCtlVec_ > > incrEnsCtlVecCollection_
Detailed Description
template<typename MODEL>
class oops::IncrCtlVec< MODEL >
IncrCtlVec Class.
Part of the control vector corresponding to the increment part of the control increment defined for a given time-step/sub-window. It has two components, IncrModCtlVec and IncrEnsCtlVec acted upon by the modelled and localized ensemble background error covariance, respectively.
\[ dv^K = \begin{bmatrix} dv^K_{mod} \\ dv^K_{ens} \end{bmatrix} \]
-> \(dv^K \) is implemented by IncrCtlVec
-> \(dv^K_{mod} \) is implemented by IncrModCtlVec
The component corresponding to the localized ensemble B matrix is defined as:
\[ dv^K_{ens} = \begin{bmatrix} dv^K_{ens_{1}} \\ .. \\ dv^K_{ens_{L}} \end{bmatrix} \]
-> \(dv^K_{ens_m} \) is implemented by IncrEnsCtlVec, L is the number of ensemble perturbations used to construct the localized sampled covariance matrix;
Definition at line 40 of file CostJb3D.h.
Member Typedef Documentation
EnsemblesCollection_
template<typename MODEL > using oops::IncrCtlVec< MODEL >::EnsemblesCollection_ = EnsemblesCollection<MODEL> private
Definition at line 72 of file IncrCtlVec.h.
IncrEnsCtlVec_
template<typename MODEL > using oops::IncrCtlVec< MODEL >::IncrEnsCtlVec_ = IncrEnsCtlVec<MODEL> private
Definition at line 73 of file IncrCtlVec.h.
IncrModCtlVec_
template<typename MODEL > using oops::IncrCtlVec< MODEL >::IncrModCtlVec_ = IncrModCtlVec<MODEL> private
Definition at line 74 of file IncrCtlVec.h.
JbState_
template<typename MODEL > using oops::IncrCtlVec< MODEL >::JbState_ = CostJbState<MODEL> private
Definition at line 75 of file IncrCtlVec.h.
Constructor & Destructor Documentation
IncrCtlVec() [1/3]
template<typename MODEL > oops::IncrCtlVec< MODEL >::IncrCtlVec (const JbState_ & jb, const util::DateTime & time) explicit
Constructor.
Constructor, destructor.
Definition at line 158 of file IncrCtlVec.h.
     : time_(time),
       ensSize_(EnsemblesCollection_::getInstance().size()),
       incrModCtlVec_(),
       incrEnsCtlVecCollection_() {
   Log::trace() << "IncrCtlVec<MODEL>::IncrCtlVec starting" << std::endl;
   util::Timer timer(classname(), "Incr");
   incrModCtlVec_.reset(this->newIncrModCtlVec(jb));
   incrEnsCtlVecCollection_ = this->newIncrEnsCtlVecCollection(jb);
   Log::trace() << "IncrCtlVec<MODEL>::IncrCtlVec done" << std::endl;
 }
References oops::IncrCtlVec< MODEL >::classname(), oops::IncrCtlVec< MODEL >::incrEnsCtlVecCollection_, oops::IncrCtlVec< MODEL >::incrModCtlVec_, oops::IncrCtlVec< MODEL >::newIncrEnsCtlVecCollection(), and oops::IncrCtlVec< MODEL >::newIncrModCtlVec().
IncrCtlVec() [2/3]
template<typename MODEL > oops::IncrCtlVec< MODEL >::IncrCtlVec (const JbState_ & jb, const IncrCtlVec< MODEL > & other)
Constructor with copy initialization.
Definition at line 176 of file IncrCtlVec.h.
     : time_(other.time_),
       ensSize_(other.ensSize_),
       incrModCtlVec_(0),
       incrEnsCtlVecCollection_(0) {
   Log::trace() << "IncrCtlVec<MODEL>::IncrCtlVec starting" << std::endl;
   util::Timer timer(classname(), "Incr");
   // Create new control vectors at the resolution defined by jb
   incrModCtlVec_.reset(this->newIncrModCtlVec(jb));
   *incrModCtlVec_ = *other.incrModCtlVec_;
   incrEnsCtlVecCollection_ = this->newIncrEnsCtlVecCollection(jb);
   for (unsigned int jj = 0; jj < ensSize_; ++jj) {
     incrEnsCtlVecCollection_[jj] = other.incrEnsCtlVecCollection_[jj];
   }
   Log::trace() << "IncrCtlVec<MODEL>::IncrCtlVec done" << std::endl;
 }
References oops::IncrCtlVec< MODEL >::classname(), oops::IncrCtlVec< MODEL >::ensSize_, oops::IncrCtlVec< MODEL >::incrEnsCtlVecCollection_, oops::IncrCtlVec< MODEL >::incrModCtlVec_, oops::IncrCtlVec< MODEL >::newIncrEnsCtlVecCollection(), and oops::IncrCtlVec< MODEL >::newIncrModCtlVec().
IncrCtlVec() [3/3]
template<typename MODEL > oops::IncrCtlVec< MODEL >::IncrCtlVec (const IncrCtlVec< MODEL > & other, const bool copy = true)
Copy constructor.
Definition at line 199 of file IncrCtlVec.h.
     : time_(other.time_),
       ensSize_(other.ensSize_),
       incrModCtlVec_(),
       incrEnsCtlVecCollection_(0) {
   Log::trace() << "IncrCtlVec<MODEL>::IncrCtlVec copy starting" << std::endl;
   util::Timer timer(classname(), "Incr");
   incrModCtlVec_.reset(new IncrModCtlVec_(*other.incrModCtlVec_, copy));
   for (unsigned int jj = 0; jj < ensSize_; ++jj) {
     incrEnsCtlVecCollection_.emplace_back(
         new IncrEnsCtlVec_(*other.incrEnsCtlVecCollection_[jj], copy));
   }
   Log::trace() << "IncrCtlVec<MODEL>::IncrCtlVec copy done" << std::endl;
 }
References oops::IncrCtlVec< MODEL >::classname(), oops::IncrCtlVec< MODEL >::ensSize_, oops::IncrCtlVec< MODEL >::incrEnsCtlVecCollection_, and oops::IncrCtlVec< MODEL >::incrModCtlVec_.
~IncrCtlVec()
template<typename MODEL > oops::IncrCtlVec< MODEL >::~IncrCtlVec virtual
Destructor.
Definition at line 220 of file IncrCtlVec.h.
{
   Log::trace() << "IncrCtlVec<MODEL>::~IncrCtlVec starting" << std::endl;
   util::Timer timer(classname(), "~Incr");
   incrModCtlVec_.reset();
   Log::trace() << "IncrCtlVec<MODEL>::~IncrCtlVec done" << std::endl;
 }
Member Function Documentation
axpy()
template<typename MODEL > void oops::IncrCtlVec< MODEL >::axpy (const double & zz, const IncrCtlVec< MODEL > & dv, const bool check = true)
\(dv_1 = dv_1 * c dv_2 \)
Definition at line 326 of file IncrCtlVec.h.
{
   Log::trace() << "IncrCtlVec<MODEL>::axpy starting" << std::endl;
   util::Timer timer(classname(), "axpy");
   incrModCtlVec_->axpy(zz, *dv.incrModCtlVec_, check);
   if (ensSize_ != 0) {
     for (unsigned int jj = 0; jj < ensSize_; ++jj) {
       incrEnsCtlVecCollection_[jj]->axpy(zz, *dv.incrEnsCtlVecCollection_[jj],
                                          check);
     }
   }
   Log::trace() << "IncrCtlVec<MODEL>::axpy done" << std::endl;
 }
classname()
template<typename MODEL > static const std::string oops::IncrCtlVec< MODEL >::classname () inline static
Definition at line 78 of file IncrCtlVec.h.
 { return "oops::IncrCtlVec"; }
Referenced by oops::IncrCtlVec< MODEL >::IncrCtlVec().
dot_product_with()
template<typename MODEL > double oops::IncrCtlVec< MODEL >::dot_product_with (const IncrCtlVec< MODEL > & dv) const
\(<dv_1,dv_1> = dv_1^T dv_1 \)
Definition at line 346 of file IncrCtlVec.h.
{
   Log::trace() << "IncrCtlVec<MODEL>::dot_product_with starting" << std::endl;
   util::Timer timer(classname(), "dot_product_with");
   double zz = incrModCtlVec_->dot_product_with(*dv.incrModCtlVec_);
   if (ensSize_ != 0) {
     std::vector<double> zzloc;
     for (unsigned int jj = 0; jj < ensSize_; ++jj) {
       zzloc.push_back(incrEnsCtlVecCollection_[jj]->local_dot_product_with(
         *dv.incrEnsCtlVecCollection_[jj]));
     }
     eckit::mpi::comm().allReduceInPlace(zzloc.begin(), zzloc.end(), eckit::mpi::sum());
     zz += std::accumulate(zzloc.begin(), zzloc.end(), double(0.0));
   }
   Log::trace() << "IncrCtlVec<MODEL>::dot_product_with done" << std::endl;
   return zz;
 }
ensCtlVec() [1/2]
template<typename MODEL > IncrEnsCtlVec_& oops::IncrCtlVec< MODEL >::ensCtlVec (const int ii) inline
Return component acted upon the ensemble covariance matrix.
Definition at line 95 of file IncrCtlVec.h.
{
     return *incrEnsCtlVecCollection_[ii];
   }
References oops::IncrCtlVec< MODEL >::incrEnsCtlVecCollection_.
Referenced by oops::EnsembleCovariance4D< MODEL >::advectedMultiplySqrt(), oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::advectedMultiplySqrt(), oops::EnsembleCovariance4DScaleDependent< MODEL >::advectedMultiplySqrt(), oops::EnsembleCovariance4DDistributed< MODEL >::advectedMultiplySqrt(), oops::EnsembleCovsInterpol4D< MODEL >::advectedMultiplySqrt(), oops::EnsembleCovariance4D< MODEL >::advectedMultiplySqrtTrans(), oops::EnsembleCovariance4DScaleDependent< MODEL >::advectedMultiplySqrtTrans(), oops::EnsembleCovariance4DWithChangeOfVariable< MODEL >::advectedMultiplySqrtTrans(), oops::EnsembleCovsInterpol4D< MODEL >::advectedMultiplySqrtTrans(), oops::EnsembleCovariance4DDistributed< MODEL >::advectedMultiplySqrtTrans(), oops::EnsembleCovsInterpolSDL< MODEL >::multiplySqrt(), oops::EnsembleCovsInterpol< MODEL >::multiplySqrt(), oops::EnsembleCovarianceSDL< MODEL >::multiplySqrt(), oops::EnsembleCovariance< MODEL >::multiplySqrt(), oops::EnsembleCovsInterpolSDL< MODEL >::multiplySqrtTrans(), oops::EnsembleCovsInterpol< MODEL >::multiplySqrtTrans(), oops::EnsembleCovarianceSDL< MODEL >::multiplySqrtTrans(), and oops::EnsembleCovariance< MODEL >::multiplySqrtTrans().
ensCtlVec() [2/2]
template<typename MODEL > const IncrEnsCtlVec_& oops::IncrCtlVec< MODEL >::ensCtlVec (const int ii) const inline
Return constant component acted upon the ensemble covariance matrix.
Definition at line 99 of file IncrCtlVec.h.
{
     return *incrEnsCtlVecCollection_[ii];
   }
References oops::IncrCtlVec< MODEL >::incrEnsCtlVecCollection_.
modCtlVec() [1/2]
template<typename MODEL > IncrModCtlVec_& oops::IncrCtlVec< MODEL >::modCtlVec () inline
Return component acted upon the modelled covariance matrix.
Definition at line 91 of file IncrCtlVec.h.
 { return *incrModCtlVec_; }
References oops::IncrCtlVec< MODEL >::incrModCtlVec_.
Referenced by oops::ErrorCovariance< MODEL >::multiplySqrt(), and oops::ErrorCovariance< MODEL >::multiplySqrtTrans().
modCtlVec() [2/2]
template<typename MODEL > const IncrModCtlVec_& oops::IncrCtlVec< MODEL >::modCtlVec () const inline
Return constant component acted upon the modelled covariance matrix.
Definition at line 93 of file IncrCtlVec.h.
 { return *incrModCtlVec_; }
References oops::IncrCtlVec< MODEL >::incrModCtlVec_.
newIncrEnsCtlVecCollection()
template<typename MODEL > std::vector< std::unique_ptr< IncrEnsCtlVec< MODEL > > > oops::IncrCtlVec< MODEL >::newIncrEnsCtlVecCollection (const JbState_ & jb) const private
Return a vector of pointers to the control vectors components acted upon by the ensemble covariance matrix
Definition at line 479 of file IncrCtlVec.h.
{
   unsigned int ensSize = EnsemblesCollection_::getInstance().size();
   std::vector<std::unique_ptr<IncrEnsCtlVec<MODEL> > > incrEnsCtlVecCollection;
   for (unsigned int jj = 0; jj < ensSize; ++jj) {
     incrEnsCtlVecCollection.emplace_back(jb.newIncrEnsCtlVec());
   }
   return incrEnsCtlVecCollection;
 }
References oops::CostJbState< MODEL >::newIncrEnsCtlVec().
Referenced by oops::IncrCtlVec< MODEL >::IncrCtlVec().
newIncrModCtlVec()
template<typename MODEL > IncrModCtlVec< MODEL > * oops::IncrCtlVec< MODEL >::newIncrModCtlVec (const JbState_ & jb) const private
Return a pointer to the control vector component acted upon by the modelled covariance matrix
Definition at line 468 of file IncrCtlVec.h.
{
   return jb.newIncrModCtlVec();
 }
References oops::CostJbState< MODEL >::newIncrModCtlVec().
Referenced by oops::IncrCtlVec< MODEL >::IncrCtlVec().
norm()
template<typename MODEL > double oops::IncrCtlVec< MODEL >::norm
L-2 norm.
Definition at line 432 of file IncrCtlVec.h.
{
   Log::trace() << "IncrCtlVec<MODEL>::norm starting" << std::endl;
   util::Timer timer(classname(), "norm");
   double zz = incrModCtlVec_->norm();
   if (ensSize_ != 0) {
     for (unsigned int jj = 0; jj < ensSize_; ++jj) {
       zz += incrEnsCtlVecCollection_[jj]->norm();
     }
   }
   Log::trace() << "IncrCtlVec<MODEL>::norm done" << std::endl;
   return zz;
 }
operator*=()
template<typename MODEL > IncrCtlVec< MODEL > & oops::IncrCtlVec< MODEL >::operator*= (const double & zz)
\(dv_1 = dv_1 * c \)
Definition at line 307 of file IncrCtlVec.h.
{
   Log::trace() << "IncrCtlVec<MODEL>::operator*= starting" << std::endl;
   util::Timer timer(classname(), "operator*=");
   *incrModCtlVec_ *= zz;
   if (ensSize_ != 0) {
     for (unsigned int jj = 0; jj < ensSize_; ++jj) {
       *incrEnsCtlVecCollection_[jj] *= zz;
     }
   }
   Log::trace() << "IncrCtlVec<MODEL>::operator*= done" << std::endl;
   return *this;
 }
operator+=()
template<typename MODEL > IncrCtlVec< MODEL > & oops::IncrCtlVec< MODEL >::operator+= (const IncrCtlVec< MODEL > & rhs)
\(dv_1 = dv_1 + dv_2 \)
Definition at line 269 of file IncrCtlVec.h.
{
   Log::trace() << "IncrCtlVec<MODEL>::operator+= starting" << std::endl;
   util::Timer timer(classname(), "operator+=");
   *incrModCtlVec_ += *rhs.incrModCtlVec_;
   if (ensSize_ != 0) {
     for (unsigned int jj = 0; jj < ensSize_; ++jj) {
       *incrEnsCtlVecCollection_[jj] += *rhs.incrEnsCtlVecCollection_[jj];
     }
   }
   Log::trace() << "IncrCtlVec<MODEL>::operator+= done" << std::endl;
   return *this;
 }
operator-=()
template<typename MODEL > IncrCtlVec< MODEL > & oops::IncrCtlVec< MODEL >::operator-= (const IncrCtlVec< MODEL > & rhs)
\(dv_1 = dv_1 - dv_2 \)
Definition at line 288 of file IncrCtlVec.h.
{
   Log::trace() << "IncrCtlVec<MODEL>::operator-= starting" << std::endl;
   util::Timer timer(classname(), "operator-=");
   *incrModCtlVec_ -= *rhs.incrModCtlVec_;
   if (ensSize_ != 0) {
     for (unsigned int jj = 0; jj < ensSize_; ++jj) {
       *incrEnsCtlVecCollection_[jj] -= *rhs.incrEnsCtlVecCollection_[jj];
     }
   }
   Log::trace() << "IncrCtlVec<MODEL>::operator-= done" << std::endl;
   return *this;
 }
operator=()
template<typename MODEL > IncrCtlVec< MODEL > & oops::IncrCtlVec< MODEL >::operator= (const IncrCtlVec< MODEL > & rhs)
\(dv_1 = dv_2 \)
Definition at line 250 of file IncrCtlVec.h.
{
   Log::trace() << "IncrCtlVec<MODEL>::operator= starting" << std::endl;
   util::Timer timer(classname(), "operator=");
   *incrModCtlVec_ = *rhs.incrModCtlVec_;
   if (ensSize_ != 0) {
     for (unsigned int jj = 0; jj < ensSize_; ++jj) {
       *incrEnsCtlVecCollection_[jj] = *rhs.incrEnsCtlVecCollection_[jj];
     }
   }
   Log::trace() << "IncrCtlVec<MODEL>::operator= done" << std::endl;
   return *this;
 }
print()
template<typename MODEL > void oops::IncrCtlVec< MODEL >::print (std::ostream & os) const private
Definition at line 451 of file IncrCtlVec.h.
{
   Log::trace() << "IncrCtlVec<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   os << *incrModCtlVec_;
   if (ensSize_ != 0) {
     for (unsigned int jj = 0; jj < ensSize_; ++jj) {
       os << *incrEnsCtlVecCollection_[jj] << std::endl;
     }
   }
   Log::trace() << "IncrCtlVec<MODEL>::print done" << std::endl;
 }
random()
template<typename MODEL > void oops::IncrCtlVec< MODEL >::random
Random control vector.
Definition at line 388 of file IncrCtlVec.h.
{
   Log::trace() << "IncrCtlVec<MODEL>::random starting" << std::endl;
   util::Timer timer(classname(), "random");
   incrModCtlVec_->random();
   if (ensSize_ != 0) {
     for (unsigned int jj = 0; jj < ensSize_; ++jj) {
       incrEnsCtlVecCollection_[jj]->random();
     }
   }
   Log::trace() << "IncrCtlVec<MODEL>::random done" << std::endl;
 }
read()
template<typename MODEL > void oops::IncrCtlVec< MODEL >::read (const eckit::Configuration & conf)
Read control vector.
Definition at line 406 of file IncrCtlVec.h.
{
   Log::trace() << "IncrCtlVec<MODEL>::read starting" << std::endl;
   util::Timer timer(classname(), "read");
   incrModCtlVec_->read(conf);
   // incrEnsCtlVec_->read(conf);
   Log::trace() << "IncrCtlVec<MODEL>::read done" << std::endl;
 }
schur_product_with()
template<typename MODEL > void oops::IncrCtlVec< MODEL >::schur_product_with (const IncrCtlVec< MODEL > & dv)
Hadamard product (element-wise)
Definition at line 369 of file IncrCtlVec.h.
{
   Log::trace() << "IncrCtlVec<MODEL>::schur_product_with starting" << std::endl;
   util::Timer timer(classname(), "schur_product_with");
   incrModCtlVec_->schur_product_with(*dv.incrModCtlVec_);
   if (ensSize_ != 0) {
     for (unsigned int jj = 0; jj < ensSize_; ++jj) {
       incrEnsCtlVecCollection_[jj].schur_product_with(
           dv.incrEnsCtlVecCollection_[jj]);
     }
   }
   Log::trace() << "IncrCtlVec<MODEL>::schur_product_with done" << std::endl;
 }
validTime()
template<typename MODEL > const util::DateTime oops::IncrCtlVec< MODEL >::validTime () const inline
Time.
Definition at line 104 of file IncrCtlVec.h.
 { return time_; }
References oops::IncrCtlVec< MODEL >::time_.
write()
template<typename MODEL > void oops::IncrCtlVec< MODEL >::write (const eckit::Configuration & conf) const
Write control vector.
Definition at line 419 of file IncrCtlVec.h.
{
   Log::trace() << "IncrCtlVec<MODEL>::write starting" << std::endl;
   util::Timer timer(classname(), "write");
   incrModCtlVec_->write(conf);
   // incrEnsCtlVec_->write(conf);
   Log::trace() << "IncrCtlVec<MODEL>::write done" << std::endl;
 }
zero()
template<typename MODEL > void oops::IncrCtlVec< MODEL >::zero
\(dv_1 = 0 \)
Definition at line 232 of file IncrCtlVec.h.
{
   Log::trace() << "IncrCtlVec<MODEL>::zero starting" << std::endl;
   util::Timer timer(classname(), "zero");
   incrModCtlVec_->zero();
   if (ensSize_ != 0) {
     for (unsigned int jj = 0; jj < ensSize_; ++jj) {
       incrEnsCtlVecCollection_[jj]->zero();
     }
   }
   Log::trace() << "IncrCtlVec<MODEL>::zero done" << std::endl;
 }
Member Data Documentation
ensSize_
template<typename MODEL > unsigned int oops::IncrCtlVec< MODEL >::ensSize_ private
Size of the ensemble component.
Definition at line 144 of file IncrCtlVec.h.
Referenced by oops::IncrCtlVec< MODEL >::IncrCtlVec().
incrEnsCtlVecCollection_
template<typename MODEL > std::vector<std::unique_ptr<IncrEnsCtlVec_> > oops::IncrCtlVec< MODEL >::incrEnsCtlVecCollection_ private
A vector of pointer to model specific implementation of the control vector components acted upon by the ensemble B matrix
Definition at line 150 of file IncrCtlVec.h.
Referenced by oops::IncrCtlVec< MODEL >::ensCtlVec(), and oops::IncrCtlVec< MODEL >::IncrCtlVec().
incrModCtlVec_
template<typename MODEL > std::unique_ptr<IncrModCtlVec_> oops::IncrCtlVec< MODEL >::incrModCtlVec_ private
Pointer to model specific implementation of the control vector component acted upon by the modelled B matrix
Definition at line 147 of file IncrCtlVec.h.
Referenced by oops::IncrCtlVec< MODEL >::IncrCtlVec(), and oops::IncrCtlVec< MODEL >::modCtlVec().
time_
template<typename MODEL > util::DateTime oops::IncrCtlVec< MODEL >::time_ private
Valid time.
Definition at line 142 of file IncrCtlVec.h.
Referenced by oops::IncrCtlVec< MODEL >::validTime().
The documentation for this class was generated from the following files:
src/oops/assimilation/CostJb3D.h
src/oops/assimilation/IncrCtlVec.h