OOPS Documentation: oops::CostFct4DVarMF< MODEL > Class Template Reference
oops::CostFct4DVarMF< MODEL > Class Template Reference
4D-Var Cost Function in the ARPEGE
#include <CostFct4DVarMF.h>
Public Member Functions
CostFct4DVarMF (const eckit::Configuration &, const Geometry_ &, const Model_ &)
~CostFct4DVarMF ()
double evaluate (const CtrlVar_ &, const eckit::Configuration &config=eckit::LocalConfiguration(), PostProcessor< State_ > post=PostProcessor< State_ >()) const override
Evaluate the non-linear cost function.
double linearize (const CtrlVar_ &, const eckit::Configuration &, PostProcessor< State_ > post=PostProcessor< State_ >()) override
Set up the quadratic cost function. Specific linearization for ARPEGE 4D-Var.
void runTL (CtrlInc_ &, PostProcessorTL< Increment_ > &, PostProcessor< Increment_ >, const bool idModel=false) const override
Run the tangent linear model.
void runAD (CtrlInc_ &, PostProcessorAD< Increment_ > &, PostProcessor< Increment_ >, const bool idModel=false) const override
Run the adjoint model.
void zeroAD (CtrlInc_ &) const override
Nullify the increment prior to running the adjoint model.
void runNL (CtrlVar_ &xx, PostProcessor< State_ > &pp) const override
Run the non-linear model (HR)
void runNL (CtrlVar_ &, const Model_ &model, PostProcessor< State_ > &) override
Run the non-linear model (Trajectory)
const double & getCostJoJc () const override
Get the JoJc cost function value.
const double & getCostJb () const override
Get the Jb cost function value.
Public Member Functions inherited from oops::CostFunction< MODEL >
CostFunction (const eckit::Configuration &, const Geometry_ &, const Model_ &)
Construct a cost function.
virtual ~CostFunction ()
Destroy a cost function.
void addIncrement (CtrlVar_ &, const CtrlInc_ &, PostProcessor< Increment_ > post=PostProcessor< Increment_ >()) const
Add increment to the first guess.
void resetLinearization ()
Rest the quadratic cost function.
void computeGradientFG (CtrlInc_ &) const
Compute the cost function gradient at first guess (without Jb)
double computeGradientFG (const CtrlVec_ &, CtrlInc_ &) const
Compute the cost function gradient at first guess (without Jb)
void checkpoint (eckit::LocalConfiguration &) const
Checkpoint.
void restart (const eckit::Configuration &)
Restart.
const JbTotal_ & jb () const
Access \(J_b\).
const CostBase_ & jterm (const unsigned ii) const
Access terms of the cost function other than \(J_b\).
unsigned nterms () const
Return the numer of other cost function terms \(J_o, J_c, ..\).
Private Types
using Increment_ = Increment< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using CtrlVar_ = ControlVariable< MODEL >
using CostFct_ = CostFunction< MODEL >
using Geometry_ = Geometry< MODEL >
using State_ = State< MODEL >
using Model_ = Model< MODEL >
using Variables_ = Variables< MODEL >
using Advector_ = AdvectorHandler< MODEL >
using JqTerm_ = JqTerm< MODEL >
using TrajectorySaver_ = TrajectorySaverMF< MODEL >
using WeightedDiff_ = WeightedDiff< MODEL, Increment_, State_ >
using WeightedMean_ = DFIProcessor< MODEL >
Private Member Functions
void addIncr (CtrlVar_ &, const CtrlInc_ &, PostProcessor< Increment_ > &) const override
Add increment to the first guess (with FullPos change of resolution)
CostJbState< MODEL > * newJb (const eckit::Configuration &, const Geometry_ &, const CtrlVar_ &) const override
Create the \(J_b, J_q\) term of the cost function.
CostJo< MODEL > * newJo (const eckit::Configuration &) const override
Create the \(J_o\) term of the cost function.
CostTermBase< MODEL > * newJc (const eckit::Configuration &, const Geometry_ &) const override
Create other terms of the cost function \(J_c, ..\).
Private Attributes
double costJoJc_
double costJb_
util::Duration windowLength_
util::DateTime windowBegin_
util::DateTime windowEnd_
const Geometry_ & geom_
const Variables_ ctlvars_
std::unique_ptr< State_ > fglr_
std::unique_ptr< Increment_ > biasDFI_
biasDFI calculated in the first trajectory and used at the end
Additional Inherited Members
Static Public Member Functions inherited from oops::CostFunction< MODEL >
static const std::string classname ()
Protected Member Functions inherited from oops::CostFunction< MODEL >
void setupTerms (const eckit::Configuration &)
Set up terms of the cost function \(J_b, J_q, J_o, J_c, ..\).
const Model_ & getModel () const
Access the non-linear model.
const LinearModel_ & getTLM (const unsigned isub=0) const
Access the linear model.
void recentreBackground (const eckit::Configuration &)
Re-centre the background.
CostBase_ & getJterm (const unsigned ii) const
Non const access to JTerms for linearize() method in concrete cost-functions.
JbTotal_ & getJb () const
Non const access to Jb for linearize() method in concrete cost-functions
std::vector< std::unique_ptr< LinearModel_ > > & getTLMs ()
Non const access to TL Model for linearize() method in concrete cost-functions
Detailed Description
template<typename MODEL>
class oops::CostFct4DVarMF< MODEL >
4D-Var Cost Function in the ARPEGE
This class implements a specific linearize method for ARPEGE. The model trajectory is calculated at low resolution and the changes of resolution are made with FullPos
Definition at line 54 of file CostFct4DVarMF.h.
Member Typedef Documentation
Advector_
template<typename MODEL > using oops::CostFct4DVarMF< MODEL >::Advector_ = AdvectorHandler<MODEL> private
Definition at line 63 of file CostFct4DVarMF.h.
CostFct_
template<typename MODEL > using oops::CostFct4DVarMF< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 58 of file CostFct4DVarMF.h.
CtrlInc_
template<typename MODEL > using oops::CostFct4DVarMF< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 56 of file CostFct4DVarMF.h.
CtrlVar_
template<typename MODEL > using oops::CostFct4DVarMF< MODEL >::CtrlVar_ = ControlVariable<MODEL> private
Definition at line 57 of file CostFct4DVarMF.h.
Geometry_
template<typename MODEL > using oops::CostFct4DVarMF< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 59 of file CostFct4DVarMF.h.
Increment_
template<typename MODEL > using oops::CostFct4DVarMF< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 55 of file CostFct4DVarMF.h.
JqTerm_
template<typename MODEL > using oops::CostFct4DVarMF< MODEL >::JqTerm_ = JqTerm<MODEL> private
Definition at line 64 of file CostFct4DVarMF.h.
Model_
template<typename MODEL > using oops::CostFct4DVarMF< MODEL >::Model_ = Model<MODEL> private
Definition at line 61 of file CostFct4DVarMF.h.
State_
template<typename MODEL > using oops::CostFct4DVarMF< MODEL >::State_ = State<MODEL> private
Definition at line 60 of file CostFct4DVarMF.h.
TrajectorySaver_
template<typename MODEL > using oops::CostFct4DVarMF< MODEL >::TrajectorySaver_ = TrajectorySaverMF<MODEL> private
Definition at line 65 of file CostFct4DVarMF.h.
Variables_
template<typename MODEL > using oops::CostFct4DVarMF< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 62 of file CostFct4DVarMF.h.
WeightedDiff_
template<typename MODEL > using oops::CostFct4DVarMF< MODEL >::WeightedDiff_ = WeightedDiff<MODEL, Increment_, State_> private
Definition at line 66 of file CostFct4DVarMF.h.
WeightedMean_
template<typename MODEL > using oops::CostFct4DVarMF< MODEL >::WeightedMean_ = DFIProcessor<MODEL> private
Definition at line 67 of file CostFct4DVarMF.h.
Constructor & Destructor Documentation
CostFct4DVarMF()
template<typename MODEL > oops::CostFct4DVarMF< MODEL >::CostFct4DVarMF (const eckit::Configuration & config, const Geometry_ & geom, const Model_ & model)
Create J components \(J_b\) , \(J_o\), \(J_c\) ...
Definition at line 143 of file CostFct4DVarMF.h.
     : CostFunction<MODEL>::CostFunction(config, geom, model),
       geom_(geom),
       ctlvars_(config) {
   Log::trace() << "CostFct4DVarMF:CostFct4DVarMF" << std::endl;
   windowLength_ = util::Duration(config.getString("window_length"));
   windowBegin_ = util::DateTime(config.getString("window_begin"));
   windowEnd_ = windowBegin_ + windowLength_;
   this->setupTerms(config);
   Log::trace() << "CostFct4DVarMF constructed" << std::endl;
 }
References oops::CostFunction< MODEL >::setupTerms(), oops::CostFct4DVarMF< MODEL >::windowBegin_, oops::CostFct4DVarMF< MODEL >::windowEnd_, and oops::CostFct4DVarMF< MODEL >::windowLength_.
~CostFct4DVarMF()
template<typename MODEL > oops::CostFct4DVarMF< MODEL >::~CostFct4DVarMF () inline
Definition at line 72 of file CostFct4DVarMF.h.
 {}
Member Function Documentation
addIncr()
template<typename MODEL > void oops::CostFct4DVarMF< MODEL >::addIncr (CtrlVar_ & xfghr, const CtrlInc_ & dxlr, PostProcessor< Increment_ > &) const override private virtual
Add increment to the first guess (with FullPos change of resolution)
\(x_{hr}^{g} = {fullpos}_{l2h}(x_{lr}^{g})\)
\(x_{hr}^{a} = {fullpos}_{l2h}(x_{lr}^{g} + {\delta x}_{lr})\)
\({\delta x}_{hr} = x_{hr}^{a} - x_{hr}^{g}\)
\(x_{hr}^{g} += {\delta x}_{hr}\)
Implements oops::CostFunction< MODEL >.
Reimplemented in oops::CostFct4DVarTrajHR< MODEL >.
Definition at line 454 of file CostFct4DVarMF.h.
{
   ASSERT(xfghr.state().checkStatesNumber(1));
   State_ fghr(geom_, *fglr_);
   (*fglr_) += dxlr.state()[0];
   State_ xahr(geom_, *fglr_);
   Increment_ dxhr(geom_, dxlr.state()[0]);
   dxhr.diff(xahr, fghr);
   xfghr.state()[0] += dxhr;
 }
References oops::State4D< MODEL >::checkStatesNumber(), oops::Increment< MODEL >::diff(), oops::ControlVariable< MODEL >::state(), and oops::ControlIncrement< MODEL >::state().
evaluate()
template<typename MODEL > double oops::CostFct4DVarMF< MODEL >::evaluate (const CtrlVar_ & fguess, const eckit::Configuration & config = eckit::LocalConfiguration(), PostProcessor< State_ > post = PostProcessor<State_>()) const override virtual
Evaluate the non-linear cost function.
Setup DFI
Call standard J.evaluate()
Write analysis state in the middle of the window, filtered with incremental DFI
\(\widetilde{x}^{a}=DFI(x^{a})\)
\(x_{+3h}^{a}=x_{+3h}^{b}+(\widetilde{x}^{a}-\widetilde{x}^{b}) =x_{+3h}^{b}+\widetilde{\delta x}\)
\(x_{+3h}^{a}=\widetilde{x}^{a}+(x_{+3h}^{b}-\widetilde{x}^{b}) =x^{b}+biasDFI\)
Reimplemented from oops::CostFunction< MODEL >.
Reimplemented in oops::CostFct4DVarTrajHR< MODEL >.
Definition at line 161 of file CostFct4DVarMF.h.
{
   Log::trace() << "CostFct4DVarMF::evaluate start" << std::endl;
   PostProcessor<State_> pp(post);
   std::shared_ptr<WeightedMean_> pdfi;
   if (config.has("dfi")) {
     const eckit::LocalConfiguration dfiConf(config, "dfi");
     const util::Duration dfispan(dfiConf.getString("filter_span"));
     const util::DateTime dfitime(fguess.state()[0].validTime() + dfispan / 2);
     pdfi.reset(new WeightedMean_(dfitime, dfispan, geom_, dfiConf));
     pp.enrollProcessor(pdfi);
   }
   double zzz = this->CostFunction<MODEL>::evaluate(fguess, config, pp);
   if (config.has("dfi")) {
     const eckit::LocalConfiguration dfiConf(config, "dfi");
     std::unique_ptr<State_> xdfi(pdfi->releaseMean());
     (*xdfi) += (*biasDFI_);
     Log::info() << "CostFunction: Write filtered analysis in the middle of the window.";
     xdfi->write(eckit::LocalConfiguration(dfiConf, "output"));
   }
   Log::trace() << "CostFct4DVarMF::evaluate done" << std::endl;
   return zzz;
 }
References oops::PostProcessor< FLDS >::enrollProcessor(), oops::CostFunction< MODEL >::evaluate(), and oops::ControlVariable< MODEL >::state().
getCostJb()
template<typename MODEL > const double& oops::CostFct4DVarMF< MODEL >::getCostJb () const inline override virtual
Get the Jb cost function value.
Reimplemented from oops::CostFunction< MODEL >.
Reimplemented in oops::CostFct4DVarTrajHR< MODEL >.
Definition at line 106 of file CostFct4DVarMF.h.
 {return costJb_;}
References oops::CostFct4DVarMF< MODEL >::costJb_.
getCostJoJc()
template<typename MODEL > const double& oops::CostFct4DVarMF< MODEL >::getCostJoJc () const inline override virtual
Get the JoJc cost function value.
Reimplemented from oops::CostFunction< MODEL >.
Reimplemented in oops::CostFct4DVarTrajHR< MODEL >.
Definition at line 103 of file CostFct4DVarMF.h.
 {return costJoJc_;}
References oops::CostFct4DVarMF< MODEL >::costJoJc_.
linearize()
template<typename MODEL > double oops::CostFct4DVarMF< MODEL >::linearize (const CtrlVar_ & fguess, const eckit::Configuration & innerConf, PostProcessor< State_ > post = PostProcessor<State_>()) override virtual
Set up the quadratic cost function. Specific linearization for ARPEGE 4D-Var.
This method sets up the quadratic cost function by linearizing the non-linear cost function in the specific case of ARPEGE
Jo, Jc, .. (jterms_) terms of the cost function call their 'initialize' methods which return post-processors. These are subsequently attached to the non-linear trajectory and do their post-processing prior/during/after the trajectory evaluation; once the non-linear trajectory is completed, the terms of the cost function call their 'finalize' method which makes further use of the output acquired by the post-processors during the trajectory.
E.g. the 'initialize' method of the Jo term of the cost functions returns an Observer post-processor. Its task is to compute model equivalents at observation locations. Once the trajectory evaluation is completed, the 'finalize' method is called to compute departures, perform screening if requested, set up the observation error covariance and print diagnostics.
If required, a DFI bias is calculated.
Prior to the computation of the linearisation trajectory by the TrajectorySaver, the Jb, Jo, Jc, .. terms of the cost function call their 'initializeTraj' methods which return post-processors. These are subsequently enrolled into the TrajectorySaver and attached to the linearisation trajectory computation. Once the linearisation trajectory computation is completed, the terms of the cost function call the 'finalizeTraj' method which makes further use of the output acquired by the post-processors during the computation of the linearisation trajectory.
E.g. the 'initializeTraj' method of the Jo term of the cost function sets up the linear observation operator and returns an Observer post-processor. Its task is to compute the linearisation for the linear observation operator. Once the linearisation trajectory computation is completed, the 'finailzeTraj' method is called to compute the departures and print diagnostics.
Read inner loop configuration
Prepare DFI if required If needed, the background +3H is written
Run non linear model at high resolution with screening, if required Calculate non linear Jo (without Jc)
Put filter aside for usage after the final trajectory (biasDFI)
\(\widetilde{x}^{b}=DFI(x^{b})\)
\(biasDFI=x_{+3h}^{b}-\widetilde{x}^{b}\)
Calculate first guess at low resolution with FullPos
Run NL model at low resolution. The PostProcessor object contains:
Only horizontal interpolation of observation operators Model trajectory saver Advector builder in the case of Hybrid4D, the wind fields at each timeslot of the 4D ControlVariable is given to the Advector object.
Calculate Jb value
Print cost function value
Reimplemented from oops::CostFunction< MODEL >.
Reimplemented in oops::CostFct4DVarTrajHR< MODEL >.
Definition at line 205 of file CostFct4DVarMF.h.
{
   const eckit::LocalConfiguration resConf(innerConf, "resolution");
   const eckit::LocalConfiguration tlmConf(innerConf, "linearmodel");
   std::unique_ptr<eckit::LocalConfiguration> dfiConf;
   const Geometry_ lowres(resConf);
   std::shared_ptr<WeightedDiff_> pdfi;
   std::unique_ptr<WeightingFct> wfct;
   PostProcessor<State_> pp(post);
   pp.enrollProcessor(this->getJterm(0).initialize(fguess, innerConf));
   if (innerConf.has("screening.dfi")) {
     dfiConf.reset(new eckit::LocalConfiguration(innerConf, "screening.dfi"));
     const util::Duration dfispan(dfiConf->getString("filter_span"));
     const util::DateTime dfitime(fguess.state()[0].validTime() + dfispan / 2);
     wfct.reset(new DolphChebyshev(*dfiConf));
     pdfi.reset(new WeightedDiff_(dfitime, dfispan, geom_, *dfiConf, util::Duration(0), *wfct));
     pp.enrollProcessor(pdfi);
     if (dfiConf->has("output")) {
       const eckit::LocalConfiguration outConfig(*dfiConf, "output");
       pp.enrollProcessor(new StateWriter<State_>(fguess.state()[0].validTime(), outConfig));
     }
   }
   if (innerConf.has("low_resolution_model")) {
     CtrlVar_ fghr(fguess);
     this->runNL(fghr, pp);
     costJoJc_ = this->getJterm(0).finalize(innerConf);
   }
   if (innerConf.has("screening.dfi")) {
     biasDFI_.reset(pdfi->releaseDiff());
     (*biasDFI_) *= -1.0;
   }
   std::unique_ptr<CtrlVar_> fglr;
   std::unique_ptr<Model_> lowResolModel;
   if (innerConf.has("low_resolution_model")) {
     PostProcessor<State_> no_post;
     const eckit::LocalConfiguration modelConfig(innerConf,
                                                 "low_resolution_model");
     lowResolModel.reset(new Model_(lowres, modelConfig));
     malloc_trim(0);
     fglr.reset(new CtrlVar_(lowres, fguess));
     lowResolModel->forecast(fglr->state()[0], fglr->modVar(), util::Duration(0),
                             no_post);
   } else {
     fglr.reset(new CtrlVar_(fguess));
   }
   // 6. Setup trajectory calculation at low resolution
   PostProcessor<State_> pplr(post);
   std::shared_ptr<JqTerm_> jq(this->getJb().initializeTraj(*fglr, lowres, innerConf));
   pplr.enrollProcessor(jq);
   for (unsigned iterm=0; iterm < this->nterms(); ++iterm) {
     pplr.enrollProcessor(this->getJterm(iterm).initializeTraj(*fglr, lowres, innerConf));
   }
   std::shared_ptr<TrajectorySaver_ > trajectorySaver(
       new TrajectorySaver_(fglr->state()[0], fglr->modVar(), lowres,
           this->getTLMs(), tlmConf));
   pplr.enrollProcessor(trajectorySaver);
   std::shared_ptr<Advector_ > advector = Advector_::get();
   if (advector) pplr.enrollProcessor(advector);
   if (innerConf.has("low_resolution_model")) {
     util::LogbookWriter<std::string> log("MF4DVarTrajectory",
                                          "onlyHorizInterpol");
     this->runNL(*fglr, *lowResolModel, pplr);
   } else {
     CtrlVar_ x0(*fglr);
     this->runNL(x0, pplr);
   }
   costJb_ = this->getJb().finalizeTraj(jq.get(), innerConf);
   if (innerConf.has("low_resolution_model")) {
     double costJoJc = 0.0;
     /* Do not change Jo.gradFG */
     for (unsigned iterm=1; iterm < this->nterms(); ++iterm) {
       costJoJc += this->getJterm(iterm).finalizeTraj(innerConf);
     }
   } else {
     costJoJc_ = 0.0;
     for (unsigned iterm=0; iterm < this->nterms(); ++iterm) {
       costJoJc_ += this->getJterm(iterm).finalizeTraj(innerConf);
     }
   }
   double costJ = costJb_ + costJoJc_;
   Log::test() << "CostFunction: Nonlinear J = " << costJ << std::endl;
   return costJ;
 }
References oops::PostProcessor< FLDS >::enrollProcessor(), and oops::ControlVariable< MODEL >::state().
newJb()
template<typename MODEL > CostJbState< MODEL > * oops::CostFct4DVarMF< MODEL >::newJb (const eckit::Configuration & jbConf, const Geometry_ & geom, const CtrlVar_ & xb) const override private virtual
Create the \(J_b, J_q\) term of the cost function.
Implements oops::CostFunction< MODEL >.
Definition at line 364 of file CostFct4DVarMF.h.
{
   ASSERT(xb.state().checkStatesNumber(1));
   return new CostJb3D<MODEL>(jbConf, geom, ctlvars_, windowLength_,
                              xb.state()[0]);
 }
References oops::State4D< MODEL >::checkStatesNumber(), and oops::ControlVariable< MODEL >::state().
newJc()
template<typename MODEL > CostTermBase< MODEL > * oops::CostFct4DVarMF< MODEL >::newJc (const eckit::Configuration & jcConf, const Geometry_ & geom) const override private virtual
Create other terms of the cost function \(J_c, ..\).
Implements oops::CostFunction< MODEL >.
Definition at line 384 of file CostFct4DVarMF.h.
{
   const eckit::LocalConfiguration jcdfi(jcConf, "jcdfi");
   const util::DateTime vt(windowBegin_ + windowLength_ / 2);
   return new CostJcDFI<MODEL>(jcdfi, geom, vt, windowLength_);
 }
newJo()
template<typename MODEL > CostJo< MODEL > * oops::CostFct4DVarMF< MODEL >::newJo (const eckit::Configuration & joConf) const override private virtual
Create the \(J_o\) term of the cost function.
Implements oops::CostFunction< MODEL >.
Definition at line 375 of file CostFct4DVarMF.h.
{
   const util::Duration tslot(joConf.getString("timeslot"));
   return new CostJo<MODEL>(joConf, geom_, windowBegin_, windowEnd_, tslot);
 }
runAD()
template<typename MODEL > void oops::CostFct4DVarMF< MODEL >::runAD (CtrlInc_ & dx, PostProcessorAD< Increment_ > & cost, PostProcessor< Increment_ > post, const bool idModel = false) const override virtual
Run the adjoint model.
Implements oops::CostFunction< MODEL >.
Definition at line 441 of file CostFct4DVarMF.h.
{
   ASSERT(dx.state()[0].validTime() == windowEnd_);
   CostFct_::getTLM().forecastAD(dx.state()[0], dx.modVar(), windowLength_, post,
                                 cost, idModel);
   ASSERT(dx.state()[0].validTime() == windowBegin_);
 }
References oops::ControlIncrement< MODEL >::modVar(), and oops::ControlIncrement< MODEL >::state().
runNL() [1/2]
template<typename MODEL > void oops::CostFct4DVarMF< MODEL >::runNL (CtrlVar_ & xx, const Model_ & model, PostProcessor< State_ > & post) override virtual
Run the non-linear model (Trajectory)
Reimplemented from oops::CostFunction< MODEL >.
Definition at line 406 of file CostFct4DVarMF.h.
{
   ASSERT(xx.state().checkStatesNumber(1));
   ASSERT(xx.state()[0].validTime() == windowBegin_);
   fglr_.reset(new State_(xx.state()[0]));
   State_ x0(xx.state()[0]);
   model.forecast(x0, xx.modVar(), windowLength_, post);
   ASSERT(x0.validTime() == windowEnd_);
 }
References oops::State4D< MODEL >::checkStatesNumber(), oops::Model< MODEL >::forecast(), oops::ControlVariable< MODEL >::modVar(), oops::ControlVariable< MODEL >::state(), and oops::State< MODEL >::validTime().
runNL() [2/2]
template<typename MODEL > void oops::CostFct4DVarMF< MODEL >::runNL (CtrlVar_ & xx, PostProcessor< State_ > & pp) const override virtual
Run the non-linear model (HR)
Implements oops::CostFunction< MODEL >.
Definition at line 394 of file CostFct4DVarMF.h.
{
   ASSERT(xx.state().checkStatesNumber(1));
   ASSERT(xx.state()[0].validTime() == windowBegin_);
   CostFct_::getModel().forecast(xx.state()[0], xx.modVar(), windowLength_,
                                 post);
   ASSERT(xx.state()[0].validTime() == windowEnd_);
 }
References oops::State4D< MODEL >::checkStatesNumber(), oops::ControlVariable< MODEL >::modVar(), and oops::ControlVariable< MODEL >::state().
runTL()
template<typename MODEL > void oops::CostFct4DVarMF< MODEL >::runTL (CtrlInc_ & dx, PostProcessorTL< Increment_ > & cost, PostProcessor< Increment_ > post, const bool idModel = false) const override virtual
Run the tangent linear model.
Implements oops::CostFunction< MODEL >.
Definition at line 419 of file CostFct4DVarMF.h.
{
   ASSERT(dx.state()[0].validTime() == windowBegin_);
   CostFct_::getTLM().forecastTL(dx.state()[0], dx.modVar(), windowLength_, post,
                                 cost, idModel);
   ASSERT(dx.state()[0].validTime() == windowEnd_);
 }
References oops::ControlIncrement< MODEL >::modVar(), and oops::ControlIncrement< MODEL >::state().
zeroAD()
template<typename MODEL > void oops::CostFct4DVarMF< MODEL >::zeroAD (CtrlInc_ & dx) const override virtual
Nullify the increment prior to running the adjoint model.
Implements oops::CostFunction< MODEL >.
Definition at line 432 of file CostFct4DVarMF.h.
{
   dx.state()[0].zero(windowEnd_);
   dx.modVar().zero();
   dx.obsVar().zero();
 }
References oops::ControlIncrement< MODEL >::modVar(), oops::ControlIncrement< MODEL >::obsVar(), oops::ControlIncrement< MODEL >::state(), oops::ObsAuxIncrements< MODEL >::zero(), oops::ModelAuxIncrement< MODEL >::zero(), and oops::Increment4D< MODEL >::zero().
Member Data Documentation
biasDFI_
template<typename MODEL > std::unique_ptr<Increment_> oops::CostFct4DVarMF< MODEL >::biasDFI_ private
biasDFI calculated in the first trajectory and used at the end
Definition at line 137 of file CostFct4DVarMF.h.
costJb_
template<typename MODEL > double oops::CostFct4DVarMF< MODEL >::costJb_ private
Definition at line 126 of file CostFct4DVarMF.h.
Referenced by oops::CostFct4DVarMF< MODEL >::getCostJb().
costJoJc_
template<typename MODEL > double oops::CostFct4DVarMF< MODEL >::costJoJc_ private
Definition at line 125 of file CostFct4DVarMF.h.
Referenced by oops::CostFct4DVarMF< MODEL >::getCostJoJc().
ctlvars_
template<typename MODEL > const Variables_ oops::CostFct4DVarMF< MODEL >::ctlvars_ private
Definition at line 132 of file CostFct4DVarMF.h.
fglr_
template<typename MODEL > std::unique_ptr<State_> oops::CostFct4DVarMF< MODEL >::fglr_ private
Definition at line 134 of file CostFct4DVarMF.h.
geom_
template<typename MODEL > const Geometry_& oops::CostFct4DVarMF< MODEL >::geom_ private
Definition at line 131 of file CostFct4DVarMF.h.
windowBegin_
template<typename MODEL > util::DateTime oops::CostFct4DVarMF< MODEL >::windowBegin_ private
Definition at line 129 of file CostFct4DVarMF.h.
Referenced by oops::CostFct4DVarMF< MODEL >::CostFct4DVarMF().
windowEnd_
template<typename MODEL > util::DateTime oops::CostFct4DVarMF< MODEL >::windowEnd_ private
Definition at line 130 of file CostFct4DVarMF.h.
Referenced by oops::CostFct4DVarMF< MODEL >::CostFct4DVarMF().
windowLength_
template<typename MODEL > util::Duration oops::CostFct4DVarMF< MODEL >::windowLength_ private
Definition at line 128 of file CostFct4DVarMF.h.
Referenced by oops::CostFct4DVarMF< MODEL >::CostFct4DVarMF().
The documentation for this class was generated from the following file:
src/oops/assimilation/CostFct4DVarMF.h