OOPS Documentation: oops::LinearModel< MODEL > Class Template Reference
oops::LinearModel< MODEL > Class Template Reference
Encapsulates the linear forecast model.
#include <LinearModel.h>
Public Member Functions
LinearModel (const Geometry_ &, const eckit::Configuration &)
Constructor.
~LinearModel ()
Destructor.
void forecastTL (Increment_ &, const ModelAuxIncr_ &, const util::Duration &, PostProcessor< Increment_ > post=PostProcessor< Increment_ >(), PostProcessorTL< Increment_ > cost=PostProcessorTL< Increment_ >(), const bool idmodel=false) const
Run the tangent linear forecast.
void forecastAD (Increment_ &, ModelAuxIncr_ &, const util::Duration &, PostProcessor< Increment_ > post=PostProcessor< Increment_ >(), PostProcessorAD< Increment_ > cost=PostProcessorAD< Increment_ >(), const bool idmodel=false) const
Run the adjoint forecast.
void setTrajectory (State_ &, const ModelAux_ &)
Set the linearization trajectory.
const Model_ & getTrajectoryModel () const
Access the linearisation trajectory model.
const util::Duration & timeResolution () const
Return time step.
const Geometry_ & geom () const
Return a constant reference to the Geometry object.
const LinearModelBase_ & model () const
Return a constant reference to the LinearModelBase object.
Static Public Member Functions
static const std::string classname ()
Protected Member Functions
void initializeTL (Increment_ &, const ModelAuxIncr_ &) const
Initialize the TL model.
void stepTL (Increment_ &, const ModelAuxIncr_ &) const
Make a time step TL.
void finalizeTL (Increment_ &) const
Finalize the TL model.
void initializeAD (Increment_ &, const ModelAuxIncr_ &) const
Initialize the adjoint model.
void stepAD (Increment_ &, ModelAuxIncr_ &) const
Make a time step AD.
void finalizeAD (Increment_ &) const
Finalize the adjoint model.
Private Types
using LinearModelBase_ = LinearModelBase< MODEL >
using Increment_ = Increment< MODEL >
using Geometry_ = Geometry< MODEL >
using Model_ = Model< MODEL >
using ModelAux_ = ModelAuxControl< MODEL >
using ModelAuxIncr_ = ModelAuxIncrement< MODEL >
using State_ = State< MODEL >
Private Member Functions
void print (std::ostream &) const
Private Attributes
std::unique_ptr< LinearModelBase_ > tlm_
Pointer to a LinearModelBase object.
std::unique_ptr< Geometry_ > geom_
Pointer to a Geometry object.
std::unique_ptr< Model_ > lrmodel_
Pointer to the linearisation model.
Detailed Description
template<typename MODEL>
class oops::LinearModel< MODEL >
Encapsulates the linear forecast model.
This class provides the operations associated with the LinearModel. It wraps the actual linear model which can be a model specific one or a generic one (identity). The interface for the linear model comprises two levels (LinearModel and LinearModelBase) because we want run time polymorphism. LinearModelFactory produces concrete objects of LinearModelBase children classes.
Definition at line 51 of file LinearModel.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::LinearModel< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 56 of file LinearModel.h.
Increment_
template<typename MODEL > using oops::LinearModel< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 55 of file LinearModel.h.
LinearModelBase_
template<typename MODEL > using oops::LinearModel< MODEL >::LinearModelBase_ = LinearModelBase<MODEL> private
Definition at line 54 of file LinearModel.h.
Model_
template<typename MODEL > using oops::LinearModel< MODEL >::Model_ = Model<MODEL> private
Definition at line 57 of file LinearModel.h.
ModelAux_
template<typename MODEL > using oops::LinearModel< MODEL >::ModelAux_ = ModelAuxControl<MODEL> private
Definition at line 58 of file LinearModel.h.
ModelAuxIncr_
template<typename MODEL > using oops::LinearModel< MODEL >::ModelAuxIncr_ = ModelAuxIncrement<MODEL> private
Definition at line 59 of file LinearModel.h.
State_
template<typename MODEL > using oops::LinearModel< MODEL >::State_ = State<MODEL> private
Definition at line 60 of file LinearModel.h.
Constructor & Destructor Documentation
LinearModel()
template<typename MODEL > oops::LinearModel< MODEL >::LinearModel (const Geometry_ & resol, const eckit::Configuration & conf)
Constructor.
Definition at line 132 of file LinearModel.h.
     : tlm_(), geom_(), lrmodel_() {
   Log::trace() << "LinearModel<MODEL>::LinearModel starting" << std::endl;
   util::Timer timer(classname(), "LinearModel");
   Log::debug() << "LinearModel config is:" << conf << std::endl;
   tlm_.reset(LinearModelFactory<MODEL>::create(resol, conf));
   geom_.reset(new Geometry_(resol));
   lrmodel_.reset(new Model_(resol, conf.getSubConfiguration("trajectory")));
   Log::trace() << "LinearModel<MODEL>::LinearModel done" << std::endl;
 }
References oops::LinearModel< MODEL >::classname(), oops::LinearModel< MODEL >::geom_, oops::LinearModel< MODEL >::lrmodel_, and oops::LinearModel< MODEL >::tlm_.
~LinearModel()
template<typename MODEL > oops::LinearModel< MODEL >::~LinearModel
Destructor.
Definition at line 147 of file LinearModel.h.
{
   Log::trace() << "LinearModel<MODEL>::~LinearModel starting" << std::endl;
   util::Timer timer(classname(), "~LinearModel");
   lrmodel_.reset();
   geom_.reset();
   tlm_.reset();
   Log::trace() << "LinearModel<MODEL>::~LinearModel done" << std::endl;
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::LinearModel< MODEL >::classname () inline static
Definition at line 63 of file LinearModel.h.
 { return "oops::LinearModel"; }
Referenced by oops::LinearModel< MODEL >::LinearModel().
finalizeAD()
template<typename MODEL > void oops::LinearModel< MODEL >::finalizeAD (Increment_ & dx) const protected
Finalize the adjoint model.
Definition at line 321 of file LinearModel.h.
{
   Log::trace() << "LinearModel<MODEL>::finalizeAD starting" << std::endl;
   util::Timer timer(classname(), "finalizeAD");
   tlm_->finalizeAD(dx);
   Log::trace() << "LinearModel<MODEL>::finalizeAD done" << std::endl;
 }
finalizeTL()
template<typename MODEL > void oops::LinearModel< MODEL >::finalizeTL (Increment_ & dx) const protected
Finalize the TL model.
Definition at line 290 of file LinearModel.h.
{
   Log::trace() << "LinearModel<MODEL>::finalizeTL starting" << std::endl;
   util::Timer timer(classname(), "finalizeTL");
   tlm_->finalizeTL(dx);
   Log::trace() << "LinearModel<MODEL>::finalizeTL done" << std::endl;
 }
forecastAD()
template<typename MODEL > void oops::LinearModel< MODEL >::forecastAD (Increment_ & dx, ModelAuxIncr_ & mctl, const util::Duration & len, PostProcessor< Increment_ > post = PostProcessor<Increment_>(), PostProcessorAD< Increment_ > cost = PostProcessorAD<Increment_>(), const bool idmodel = false) const
Run the adjoint forecast.
The adjoint model forecast receives PostProcessor and PostProcessorAD; PostProcessor can be used for post-processing (storing/writing of an Increment at requested lead times) and PostProcessorAD can be used to evaluate the adjoint of linear operators (e.g. \(H^T \) matrix).
The model error term is handled internally by the model.
Definition at line 209 of file LinearModel.h.
{
   Log::trace() << "LinearModel<MODEL>::forecastAD starting" << std::endl;
   util::Timer timer(classname(), "forecastAD");
   const util::DateTime bgn(dx.validTime() - len);
   const util::Duration tstep(tlm_->timeResolution());
   Log::info() << "LinearModel<MODEL>::forecastAD: Starting " << dx << std::endl;
   this->initializeAD(dx, mctl);
   post.initialize(dx, bgn, tstep);
   cost.initializeAD(dx, bgn, tstep);
   if (idmodel) {
     while (dx.validTime() > bgn) {
       cost.processAD(dx);
       dx.updateTime(-tstep);
       post.process(dx);
     }
   } else {
     while (dx.validTime() > bgn) {
       cost.processAD(dx);
       this->stepAD(dx, mctl);
       post.process(dx);
     }
   }
   cost.finalizeAD(dx);
   post.finalize(dx);
   this->finalizeAD(dx);
   Log::info() << "LinearModel<MODEL>::forecastAD: Finished " << dx << std::endl;
   ASSERT(dx.validTime() == bgn);
   Log::trace() << "LinearModel<MODEL>::forecastAD done" << std::endl;
 }
References oops::PostProcessor< FLDS >::finalize(), oops::PostProcessorAD< INCR >::finalizeAD(), oops::PostProcessor< FLDS >::initialize(), oops::PostProcessorAD< INCR >::initializeAD(), oops::PostProcessor< FLDS >::process(), oops::PostProcessorAD< INCR >::processAD(), oops::Increment< MODEL >::updateTime(), and oops::Increment< MODEL >::validTime().
forecastTL()
template<typename MODEL > void oops::LinearModel< MODEL >::forecastTL (Increment_ & dx, const ModelAuxIncr_ & mctl, const util::Duration & len, PostProcessor< Increment_ > post = PostProcessor<Increment_>(), PostProcessorTL< Increment_ > cost = PostProcessorTL<Increment_>(), const bool idmodel = false) const
Run the tangent linear forecast.
Run forecast TL and AD.
The linear model forecast receives PostProcessor and PostProcessorTL; PostProcessor can be used for post-processing (storing/writing of an Increment at requested lead times) and PostProcessorTL can be used to linear operators (e.g. \(H \) matrix).
The model error term is handled internally by the model.
Definition at line 163 of file LinearModel.h.
{
   Log::trace() << "LinearModel<MODEL>::forecastTL starting" << std::endl;
   util::Timer timer(classname(), "forecastTL");
   const util::DateTime end(dx.validTime() + len);
   const util::Duration tstep(tlm_->timeResolution());
   Log::info() << "LinearModel<MODEL>::forecastTL: Starting " << dx << std::endl;
   this->initializeTL(dx, mctl);
   cost.initializeTL(dx, end, tstep);
   post.initialize(dx, end, tstep);
   if (idmodel) {
     while (dx.validTime() < end) {
       dx.updateTime(tstep);
       cost.processTL(dx);
       post.process(dx);
     }
   } else {
     while (dx.validTime() < end) {
       this->stepTL(dx, mctl);
       cost.processTL(dx);
       post.process(dx);
     }
   }
   cost.finalizeTL(dx);
   post.finalize(dx);
   this->finalizeTL(dx);
   Log::info() << "LinearModel<MODEL>::forecastTL: Finished " << dx << std::endl;
   ASSERT(dx.validTime() == end);
   Log::trace() << "LinearModel<MODEL>::forecastTL done" << std::endl;
 }
References oops::PostProcessor< FLDS >::finalize(), oops::PostProcessorTL< INCR >::finalizeTL(), oops::PostProcessor< FLDS >::initialize(), oops::PostProcessorTL< INCR >::initializeTL(), oops::PostProcessor< FLDS >::process(), oops::PostProcessorTL< INCR >::processTL(), oops::Increment< MODEL >::updateTime(), and oops::Increment< MODEL >::validTime().
geom()
template<typename MODEL > const Geometry_& oops::LinearModel< MODEL >::geom () const inline
Return a constant reference to the Geometry object.
Definition at line 98 of file LinearModel.h.
 { return *geom_; }
References oops::LinearModel< MODEL >::geom_.
getTrajectoryModel()
template<typename MODEL > const Model_& oops::LinearModel< MODEL >::getTrajectoryModel () const inline
Access the linearisation trajectory model.
Definition at line 88 of file LinearModel.h.
 { return *lrmodel_; }
References oops::LinearModel< MODEL >::lrmodel_.
initializeAD()
template<typename MODEL > void oops::LinearModel< MODEL >::initializeAD (Increment_ & dx, const ModelAuxIncr_ & merr) const protected
Initialize the adjoint model.
Definition at line 300 of file LinearModel.h.
{
   Log::trace() << "LinearModel<MODEL>::initializeAD starting" << std::endl;
   util::Timer timer(classname(), "initializeAD");
   tlm_->initializeAD(dx, merr);
   Log::trace() << "LinearModel<MODEL>::initializeAD done" << std::endl;
 }
initializeTL()
template<typename MODEL > void oops::LinearModel< MODEL >::initializeTL (Increment_ & dx, const ModelAuxIncr_ & merr) const protected
Initialize the TL model.
Definition at line 268 of file LinearModel.h.
{
   Log::trace() << "LinearModel<MODEL>::initializeTL starting" << std::endl;
   util::Timer timer(classname(), "initializeTL");
   tlm_->initializeTL(dx, merr);
   Log::trace() << "LinearModel<MODEL>::initializeTL done" << std::endl;
 }
model()
template<typename MODEL > const LinearModelBase_& oops::LinearModel< MODEL >::model () const inline
Return a constant reference to the LinearModelBase object.
Definition at line 100 of file LinearModel.h.
 { return *tlm_; }
References oops::LinearModel< MODEL >::tlm_.
Referenced by oops::State< MODEL >::State().
print()
template<typename MODEL > void oops::LinearModel< MODEL >::print (std::ostream & os) const private
Definition at line 331 of file LinearModel.h.
{
   Log::trace() << "LinearModel<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   os << *tlm_;
   Log::trace() << "LinearModel<MODEL>::print done" << std::endl;
 }
setTrajectory()
template<typename MODEL > void oops::LinearModel< MODEL >::setTrajectory (State_ & xlr, const ModelAux_ & maux)
Set the linearization trajectory.
The low resolution linearisation trajectory model is used to construct the linearisation trajectory.
Definition at line 255 of file LinearModel.h.
{
   Log::trace() << "LinearModel<MODEL>::setTrajectory starting" << std::endl;
   util::Timer timer(classname(), "setTrajectory");
   tlm_->setTrajectory(xlr, *lrmodel_, maux);
   Log::trace() << "LinearModel<MODEL>::setTrajectory done" << std::endl;
 }
stepAD()
template<typename MODEL > void oops::LinearModel< MODEL >::stepAD (Increment_ & dx, ModelAuxIncr_ & merr) const protected
Make a time step AD.
Definition at line 311 of file LinearModel.h.
{
   Log::trace() << "LinearModel<MODEL>::stepAD starting" << std::endl;
   util::Timer timer(classname(), "stepAD");
   tlm_->stepAD(dx, merr);
   Log::trace() << "LinearModel<MODEL>::stepAD done" << std::endl;
 }
stepTL()
template<typename MODEL > void oops::LinearModel< MODEL >::stepTL (Increment_ & dx, const ModelAuxIncr_ & merr) const protected
Make a time step TL.
Definition at line 279 of file LinearModel.h.
{
   Log::trace() << "LinearModel<MODEL>::stepTL starting" << std::endl;
   util::Timer timer(classname(), "stepTL");
   tlm_->stepTL(dx, merr);
   Log::trace() << "LinearModel<MODEL>::stepTL done" << std::endl;
 }
timeResolution()
template<typename MODEL > const util::Duration& oops::LinearModel< MODEL >::timeResolution () const inline
Return time step.
Definition at line 92 of file LinearModel.h.
{
     return tlm_->timeResolution();
   }
References oops::LinearModel< MODEL >::tlm_.
Member Data Documentation
geom_
template<typename MODEL > std::unique_ptr<Geometry_> oops::LinearModel< MODEL >::geom_ private
Pointer to a Geometry object.
Definition at line 125 of file LinearModel.h.
Referenced by oops::LinearModel< MODEL >::geom(), and oops::LinearModel< MODEL >::LinearModel().
lrmodel_
template<typename MODEL > std::unique_ptr<Model_> oops::LinearModel< MODEL >::lrmodel_ private
Pointer to the linearisation model.
Definition at line 126 of file LinearModel.h.
Referenced by oops::LinearModel< MODEL >::getTrajectoryModel(), and oops::LinearModel< MODEL >::LinearModel().
tlm_
template<typename MODEL > std::unique_ptr<LinearModelBase_> oops::LinearModel< MODEL >::tlm_ private
Pointer to a LinearModelBase object.
Definition at line 124 of file LinearModel.h.
Referenced by oops::LinearModel< MODEL >::LinearModel(), oops::LinearModel< MODEL >::model(), and oops::LinearModel< MODEL >::timeResolution().
The documentation for this class was generated from the following file:
src/oops/interface/LinearModel.h