OOPS Documentation: oops::HMatrix< MODEL > Class Template Reference
oops::HMatrix< MODEL > Class Template Reference
The \(H \) matrix.
#include <HMatrix.h>
Public Member Functions
HMatrix (const CostFct_ &j)
void multiply (CtrlInc_ &dx, DualVector< MODEL > &dy, const bool idModel=false) const
Private Types
using Increment_ = Increment< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using CostFct_ = CostFunction< MODEL >
Private Attributes
CostFct_ const & j_
Detailed Description
template<typename MODEL>
class oops::HMatrix< MODEL >
The \(H \) matrix.
The solvers represent matrices as objects that implement a "multiply" method. This class defines objects that apply a generalized \(H \) matrix which includes \(H \) itself and the equivalent operators for the other terms of the cost function.
Definition at line 34 of file HMatrix.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::HMatrix< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 37 of file HMatrix.h.
CtrlInc_
template<typename MODEL > using oops::HMatrix< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 36 of file HMatrix.h.
Increment_
template<typename MODEL > using oops::HMatrix< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 35 of file HMatrix.h.
Constructor & Destructor Documentation
HMatrix()
template<typename MODEL > oops::HMatrix< MODEL >::HMatrix (const CostFct_ & j) inline explicit
Definition at line 40 of file HMatrix.h.
 : j_(j) {}
Member Function Documentation
multiply()
template<typename MODEL > void oops::HMatrix< MODEL >::multiply (CtrlInc_ & dx, DualVector< MODEL > & dy, const bool idModel = false) const inline
Definition at line 42 of file HMatrix.h.
{
     PostProcessor<Increment_> post;
     PostProcessorTL<Increment_> cost;
     for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
       cost.enrollProcessor(j_.jterm(jj).setupTL(dx));
     }
     j_.runTL(dx, cost, post, idModel);
     dy.clear();
     for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
       dy.append(cost.releaseOutputFromTL(jj));
     }
   }
References oops::DualVector< MODEL >::append(), oops::DualVector< MODEL >::clear(), oops::PostProcessorTL< INCR >::enrollProcessor(), oops::HMatrix< MODEL >::j_, oops::CostFunction< MODEL >::jterm(), oops::CostFunction< MODEL >::nterms(), oops::PostProcessorTL< INCR >::releaseOutputFromTL(), oops::CostFunction< MODEL >::runTL(), and oops::CostTermBase< MODEL >::setupTL().
Referenced by oops::Minimizer< MODEL >::adjObsTest(), and oops::DualMinimizer< MODEL >::doMinimize().
Member Data Documentation
j_
template<typename MODEL > CostFct_ const& oops::HMatrix< MODEL >::j_ private
Definition at line 60 of file HMatrix.h.
Referenced by oops::HMatrix< MODEL >::multiply().
The documentation for this class was generated from the following file:
src/oops/assimilation/HMatrix.h