OOPS Documentation: oops::HtRinvHdxFG< MODEL > Class Template Reference
oops::HtRinvHdxFG< MODEL > Class Template Reference
Calculate \(H^T R^{-1} H dx_FG \).
#include <HtRinvHdxFG.h>
Public Member Functions
HtRinvHdxFG (const CostFct_ &j)
void compute (CtrlInc_ &dz) const
Private Types
using Increment_ = Increment< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using CostFct_ = CostFunction< MODEL >
Private Attributes
CostFct_ const & j_
CtrlInc_ dx_
Detailed Description
template<typename MODEL>
class oops::HtRinvHdxFG< MODEL >
Calculate \(H^T R^{-1} H dx_FG \).
Definition at line 35 of file HtRinvHdxFG.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::HtRinvHdxFG< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 38 of file HtRinvHdxFG.h.
CtrlInc_
template<typename MODEL > using oops::HtRinvHdxFG< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 37 of file HtRinvHdxFG.h.
Increment_
template<typename MODEL > using oops::HtRinvHdxFG< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 36 of file HtRinvHdxFG.h.
Constructor & Destructor Documentation
HtRinvHdxFG()
template<typename MODEL > oops::HtRinvHdxFG< MODEL >::HtRinvHdxFG (const CostFct_ & j) explicit
Definition at line 53 of file HtRinvHdxFG.h.
     : j_(j), dx_(j.jb().getFirstGuessIncrement(), true) {}
Member Function Documentation
compute()
template<typename MODEL > void oops::HtRinvHdxFG< MODEL >::compute (CtrlInc_ & dz) const
Definition at line 59 of file HtRinvHdxFG.h.
{
   // Setup TL terms of cost function
   PostProcessorTL<Increment_> costtl;
   for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
     costtl.enrollProcessor(j_.jterm(jj).setupTL(dx_));
   }
   // Run TLM
   CtrlInc_ mdx(dx_);
   j_.runTL(mdx, costtl);
   // Get TLM outputs, multiply by covariance inverses, and setup ADJ forcing
   // terms
   j_.zeroAD(dz);
   PostProcessorAD<Increment_> costad;
   DualVector<MODEL> ww;
   DualVector<MODEL> zz;
   for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
     ww.append(costtl.releaseOutputFromTL(jj));
     zz.append(j_.jterm(jj).multiplyCoInv(*ww.getv(jj)));
     costad.enrollProcessor(j_.jterm(jj).setupAD(zz.getv(jj), dz));
   }
   // Run ADJ
   j_.runAD(dz, costad);
 }
References oops::DualVector< MODEL >::append(), oops::PostProcessorAD< INCR >::enrollProcessor(), oops::PostProcessorTL< INCR >::enrollProcessor(), oops::DualVector< MODEL >::getv(), and oops::PostProcessorTL< INCR >::releaseOutputFromTL().
Referenced by oops::DRMinimizer< MODEL >::doMinimize().
Member Data Documentation
dx_
template<typename MODEL > CtrlInc_ oops::HtRinvHdxFG< MODEL >::dx_ mutable private
Definition at line 47 of file HtRinvHdxFG.h.
j_
template<typename MODEL > CostFct_ const& oops::HtRinvHdxFG< MODEL >::j_ private
Definition at line 46 of file HtRinvHdxFG.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/HtRinvHdxFG.h