OOPS Documentation: oops::RMatrix< MODEL > Class Template Reference
oops::RMatrix< MODEL > Class Template Reference
The \(R \) matrix.
#include <RMatrix.h>
Public Member Functions
RMatrix (const CostFct_ &j)
void multiplyInv (DualVector< MODEL > &dy) const
Private Types
using CostFct_ = CostFunction< MODEL >
Private Attributes
CostFct_ const & j_
Detailed Description
template<typename MODEL>
class oops::RMatrix< MODEL >
The \(R \) matrix.
The solvers represent matrices as objects that implement a "multiply" method. This class defines objects that apply a generalized \(H \) matrix which includes \(H \) itself and the equivalent operators for the other terms of the cost function.
Definition at line 30 of file RMatrix.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::RMatrix< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 31 of file RMatrix.h.
Constructor & Destructor Documentation
RMatrix()
template<typename MODEL > oops::RMatrix< MODEL >::RMatrix (const CostFct_ & j) inline explicit
Definition at line 34 of file RMatrix.h.
 : j_(j) {}
Member Function Documentation
multiplyInv()
template<typename MODEL > void oops::RMatrix< MODEL >::multiplyInv (DualVector< MODEL > & dy) const inline
Definition at line 36 of file RMatrix.h.
{
     for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
       j_.jterm(jj).multiplyCoInv(dy.getv(jj));
     }
   }
References oops::DualVector< MODEL >::getv(), oops::RMatrix< MODEL >::j_, oops::CostFunction< MODEL >::jterm(), oops::CostTermBase< MODEL >::multiplyCoInv(), and oops::CostFunction< MODEL >::nterms().
Member Data Documentation
j_
template<typename MODEL > CostFct_ const& oops::RMatrix< MODEL >::j_ private
Definition at line 43 of file RMatrix.h.
Referenced by oops::RMatrix< MODEL >::multiplyInv().
The documentation for this class was generated from the following file:
src/oops/assimilation/RMatrix.h