OOPS Documentation: oops::SaddlePointPrecondMatrix< MODEL > Class Template Reference
oops::SaddlePointPrecondMatrix< MODEL > Class Template Reference
The preconditioner for the saddle-point minimizer.
#include <SaddlePointPrecondMatrix.h>
Public Member Functions
SaddlePointPrecondMatrix (const CostFct_ &j, const int norder=1, const bool idmodel=false)
void multiply (const SPVector_ &, SPVector_ &) const
Private Types
using Increment_ = Increment< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using CostFctWeak_ = CostFctWeak< MODEL >
using CostFct_ = CostFunction< MODEL >
using SPVector_ = SaddlePointVector< MODEL >
Private Member Functions
void Lhatinv (const CtrlInc_ &, CtrlInc_ &, const int, const bool) const
void Lhatinvt (const CtrlInc_ &, CtrlInc_ &, const int, const bool) const
Private Attributes
const CostFctWeak_ & j_
const int norder_
const bool idmodel_
Detailed Description
template<typename MODEL>
class oops::SaddlePointPrecondMatrix< MODEL >
The preconditioner for the saddle-point minimizer.
The solvers represent matrices as objects that implement a "multiply" method. This class defines objects that apply the saddle-point matrix.
Definition at line 34 of file SaddlePointPrecondMatrix.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::SaddlePointPrecondMatrix< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 38 of file SaddlePointPrecondMatrix.h.
CostFctWeak_
template<typename MODEL > using oops::SaddlePointPrecondMatrix< MODEL >::CostFctWeak_ = CostFctWeak<MODEL> private
Definition at line 37 of file SaddlePointPrecondMatrix.h.
CtrlInc_
template<typename MODEL > using oops::SaddlePointPrecondMatrix< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 36 of file SaddlePointPrecondMatrix.h.
Increment_
template<typename MODEL > using oops::SaddlePointPrecondMatrix< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 35 of file SaddlePointPrecondMatrix.h.
SPVector_
template<typename MODEL > using oops::SaddlePointPrecondMatrix< MODEL >::SPVector_ = SaddlePointVector<MODEL> private
Definition at line 39 of file SaddlePointPrecondMatrix.h.
Constructor & Destructor Documentation
SaddlePointPrecondMatrix()
template<typename MODEL > oops::SaddlePointPrecondMatrix< MODEL >::SaddlePointPrecondMatrix (const CostFct_ & j, const int norder = 1, const bool idmodel = false) explicit
Definition at line 58 of file SaddlePointPrecondMatrix.h.
     : j_(dynamic_cast<const CostFctWeak_ &>(j)),
       norder_(norder),
       idmodel_(idmodel) {}
Member Function Documentation
Lhatinv()
template<typename MODEL > void oops::SaddlePointPrecondMatrix< MODEL >::Lhatinv (const CtrlInc_ & xx, CtrlInc_ & zz, const int norder, const bool idmodel) const private
Definition at line 91 of file SaddlePointPrecondMatrix.h.
{
   // Approximate L=I + (I-L) + (I-L)^2 + ... + (I-L)^norder
   CtrlInc_ ww(xx);
   zz = xx;
   for (int i = 0; i < norder; ++i) {
     j_.runTL(ww, idmodel);
     zz += ww;
   }
 }
Lhatinvt()
template<typename MODEL > void oops::SaddlePointPrecondMatrix< MODEL >::Lhatinvt (const CtrlInc_ & xx, CtrlInc_ & zz, const int norder, const bool idmodel) const private
Definition at line 107 of file SaddlePointPrecondMatrix.h.
{
   // Approximate L'=I + (I-L') + (I-L')^2 + ... + (I-L')^norder
   CtrlInc_ ww(xx);
   zz = xx;
   for (int i = 0; i < norder; ++i) {
     j_.runAD(ww, idmodel);
     zz += ww;
   }
 }
multiply()
template<typename MODEL > void oops::SaddlePointPrecondMatrix< MODEL >::multiply (const SPVector_ & x, SPVector_ & z) const
Definition at line 68 of file SaddlePointPrecondMatrix.h.
{
   z.lambda().clear();
   z.lambda().dx(new CtrlInc_(j_.jb()));
   z.dx(new CtrlInc_(j_.jb()));
   Lhatinvt(x.dx(), z.lambda().dx(), norder_, idmodel_);
   CtrlInc_ l(z.lambda().dx());
   j_.jb().multiplyB(z.lambda().dx(), l);
   l *= -1.0;
   l += x.lambda().dx();
   Lhatinv(l, z.dx(), norder_, idmodel_);
   for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
     z.lambda().append(j_.jterm(jj).multiplyCoInv(*x.lambda().getv(jj)));
   }
 }
References oops::DualVector< MODEL >::append(), oops::DualVector< MODEL >::clear(), oops::DualVector< MODEL >::dx(), oops::SaddlePointVector< MODEL >::dx(), oops::DualVector< MODEL >::getv(), and oops::SaddlePointVector< MODEL >::lambda().
Referenced by oops::SaddlePointLMPMatrix< MODEL >::Fmultiply(), and oops::SaddlePointLMPMatrix< MODEL >::multiply().
Member Data Documentation
idmodel_
template<typename MODEL > const bool oops::SaddlePointPrecondMatrix< MODEL >::idmodel_ private
Definition at line 52 of file SaddlePointPrecondMatrix.h.
j_
template<typename MODEL > const CostFctWeak_& oops::SaddlePointPrecondMatrix< MODEL >::j_ private
Definition at line 50 of file SaddlePointPrecondMatrix.h.
norder_
template<typename MODEL > const int oops::SaddlePointPrecondMatrix< MODEL >::norder_ private
Definition at line 51 of file SaddlePointPrecondMatrix.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/SaddlePointPrecondMatrix.h