OOPS Documentation: oops::GenericMatrix< MODEL > Class Template Reference
oops::GenericMatrix< MODEL > Class Template Reference abstract
Base class generic matrices.
#include <GenericMatrix.h>
Public Member Functions
GenericMatrix ()
virtual ~GenericMatrix ()
State_ & multiply (State_ &) const
Increment_ & multiply (Increment_ &) const
Increment4D_ & multiply (Increment4D_ &) const
Increment_ & inverseMultiply (Increment_ &) const
Increment_ & transposeInverseMultiply (Increment_ &) const
void accumul (State_ &xx, const State_ &rhs) const
Private Types
using State_ = State< MODEL >
using Increment_ = Increment< MODEL >
using Increment4D_ = Increment4D< MODEL >
Private Member Functions
virtual void multiply (typename MODEL::State &) const =0
virtual void multiply (typename MODEL::Increment &) const =0
virtual void inverseMultiply (typename MODEL::Increment &) const =0
virtual void transposeInverseMultiply (typename MODEL::Increment &) const =0
virtual void print (std::ostream &) const =0
virtual void accumul (typename MODEL::State &xx, const typename MODEL::State &rhs) const
Detailed Description
template<typename MODEL>
class oops::GenericMatrix< MODEL >
Base class generic matrices.
Definition at line 37 of file GenericMatrix.h.
Member Typedef Documentation
Increment4D_
template<typename MODEL > using oops::GenericMatrix< MODEL >::Increment4D_ = Increment4D<MODEL> private
Definition at line 40 of file GenericMatrix.h.
Increment_
template<typename MODEL > using oops::GenericMatrix< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 39 of file GenericMatrix.h.
State_
template<typename MODEL > using oops::GenericMatrix< MODEL >::State_ = State<MODEL> private
Definition at line 38 of file GenericMatrix.h.
Constructor & Destructor Documentation
GenericMatrix()
template<typename MODEL > oops::GenericMatrix< MODEL >::GenericMatrix () inline
Definition at line 43 of file GenericMatrix.h.
 {}
~GenericMatrix()
template<typename MODEL > virtual oops::GenericMatrix< MODEL >::~GenericMatrix () inline virtual
Definition at line 44 of file GenericMatrix.h.
 {}
Member Function Documentation
accumul() [1/2]
template<typename MODEL > void oops::GenericMatrix< MODEL >::accumul (State_ & xx, const State_ & rhs) const
Definition at line 181 of file GenericMatrix.h.
{
   Log::trace() << "GenericMatrix<MODEL>::accumul starting" << std::endl;
   this->accumul(xx.state(), rhs.state());
   Log::trace() << "GenericMatrix<MODEL>::accumul done" << std::endl;
 }
References oops::State< MODEL >::state().
accumul() [2/2]
template<typename MODEL > virtual void oops::GenericMatrix< MODEL >::accumul (typename MODEL::State & xx, const typename MODEL::State & rhs) const inline private virtual
Definition at line 62 of file GenericMatrix.h.
 {}
inverseMultiply() [1/2]
template<typename MODEL > Increment< MODEL > & oops::GenericMatrix< MODEL >::inverseMultiply (Increment_ & dx) const
Definition at line 160 of file GenericMatrix.h.
{
   Log::trace() << "GenericMatrix<MODEL>::multiply starting" << std::endl;
   this->inverseMultiply(dx.increment());
   Log::trace() << "GenericMatrix<MODEL>::multiply done" << std::endl;
   return dx;
 }
References oops::Increment< MODEL >::increment().
inverseMultiply() [2/2]
template<typename MODEL > virtual void oops::GenericMatrix< MODEL >::inverseMultiply (typename MODEL::Increment &) const private pure virtual
multiply() [1/5]
template<typename MODEL > Increment4D< MODEL > & oops::GenericMatrix< MODEL >::multiply (Increment4D_ & dx) const
Definition at line 149 of file GenericMatrix.h.
{
   Log::trace() << "GenericMatrix<MODEL>::multiply starting" << std::endl;
   for (int jsub = dx.first(); jsub <= dx.last(); ++jsub) {
     this->multiply(dx[jsub].increment());
   }
   Log::trace() << "GenericMatrix<MODEL>::multiply done" << std::endl;
   return dx;
 }
References oops::Increment4D< MODEL >::first(), and oops::Increment4D< MODEL >::last().
multiply() [2/5]
template<typename MODEL > Increment< MODEL > & oops::GenericMatrix< MODEL >::multiply (Increment_ & dx) const
Definition at line 140 of file GenericMatrix.h.
{
   Log::trace() << "GenericMatrix<MODEL>::multiply starting" << std::endl;
   this->multiply(dx.increment());
   Log::trace() << "GenericMatrix<MODEL>::multiply done" << std::endl;
   return dx;
 }
References oops::Increment< MODEL >::increment().
multiply() [3/5]
template<typename MODEL > State< MODEL > & oops::GenericMatrix< MODEL >::multiply (State_ & xx) const
Definition at line 131 of file GenericMatrix.h.
{
   Log::trace() << "GenericMatrix<MODEL>::multiply starting" << std::endl;
   this->multiply(xx.state());
   Log::trace() << "GenericMatrix<MODEL>::multiply done" << std::endl;
   return xx;
 }
References oops::State< MODEL >::state().
multiply() [4/5]
template<typename MODEL > virtual void oops::GenericMatrix< MODEL >::multiply (typename MODEL::Increment &) const private pure virtual
multiply() [5/5]
template<typename MODEL > virtual void oops::GenericMatrix< MODEL >::multiply (typename MODEL::State &) const private pure virtual
print()
template<typename MODEL > virtual void oops::GenericMatrix< MODEL >::print (std::ostream &) const private pure virtual
transposeInverseMultiply() [1/2]
template<typename MODEL > Increment< MODEL > & oops::GenericMatrix< MODEL >::transposeInverseMultiply (Increment_ & dx) const
Definition at line 170 of file GenericMatrix.h.
{
   Log::trace() << "GenericMatrix<MODEL>::transposeMultiply starting"
                << std::endl;
   this->transposeInverseMultiply(dx.increment());
   Log::trace() << "GenericMatrix<MODEL>::transposeMultiply done" << std::endl;
   return dx;
 }
References oops::Increment< MODEL >::increment().
transposeInverseMultiply() [2/2]
template<typename MODEL > virtual void oops::GenericMatrix< MODEL >::transposeInverseMultiply (typename MODEL::Increment &) const private pure virtual
The documentation for this class was generated from the following file:
src/oops/interface/GenericMatrix.h