OOPS Documentation: oops::HessianMatrix< MODEL > Class Template Reference
oops::HessianMatrix< MODEL > Class Template Reference
The Hessian matrix: \(B^{-1} + H^T R^{-1} H \).
#include <HessianMatrix.h>
Public Member Functions
HessianMatrix (const CostFct_ &j, const bool test=false)
void multiply (const CtrlInc_ &dx, CtrlInc_ &dz) const
Private Types
using Increment_ = Increment< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using CostFct_ = CostFunction< MODEL >
using JqTermAD_ = JqTermAD< MODEL >
using JqTermTL_ = JqTermTL< MODEL >
Private Attributes
CostFct_ const & j_
bool test_
int iter_
Detailed Description
template<typename MODEL>
class oops::HessianMatrix< MODEL >
The Hessian matrix: \(B^{-1} + H^T R^{-1} H \).
The solvers represent matrices as objects that implement a "multiply" method. This class defines objects that apply a generalized Hessian matrix which includes all the terms of the cost function.
Definition at line 39 of file HessianMatrix.h.
Member Typedef Documentation
CostFct_
template<typename MODEL > using oops::HessianMatrix< MODEL >::CostFct_ = CostFunction<MODEL> private
Definition at line 42 of file HessianMatrix.h.
CtrlInc_
template<typename MODEL > using oops::HessianMatrix< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 41 of file HessianMatrix.h.
Increment_
template<typename MODEL > using oops::HessianMatrix< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 40 of file HessianMatrix.h.
JqTermAD_
template<typename MODEL > using oops::HessianMatrix< MODEL >::JqTermAD_ = JqTermAD<MODEL> private
Definition at line 43 of file HessianMatrix.h.
JqTermTL_
template<typename MODEL > using oops::HessianMatrix< MODEL >::JqTermTL_ = JqTermTL<MODEL> private
Definition at line 44 of file HessianMatrix.h.
Constructor & Destructor Documentation
HessianMatrix()
template<typename MODEL > oops::HessianMatrix< MODEL >::HessianMatrix (const CostFct_ & j, const bool test = false) explicit
Definition at line 60 of file HessianMatrix.h.
     : j_(j), test_(test), iter_(0) {}
Member Function Documentation
multiply()
template<typename MODEL > void oops::HessianMatrix< MODEL >::multiply (const CtrlInc_ & dx, CtrlInc_ & dz) const
Definition at line 66 of file HessianMatrix.h.
{
   // Increment counter
   iter_++;
   // Setup TL terms of cost function
   PostProcessorTL<Increment_> costtl;
   JqTermTL_* jqtl = j_.jb().initializeTL();
   costtl.enrollProcessor(jqtl);
   unsigned iq = 0;
   if (jqtl) iq = 1;
   for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
     costtl.enrollProcessor(j_.jterm(jj).setupTL(dx));
   }
   // Run TLM
   CtrlInc_ mdx(dx);
   j_.runTL(mdx, costtl);
   // Finalize Jb+Jq
   // Get TLM outputs, multiply by covariance inverses and setup ADJ forcing
   // terms
   PostProcessorAD<Increment_> costad;
   dz.zero();
   CtrlInc_ dw(j_.jb());
   // Jb
   CtrlInc_ tmp(j_.jb());
   j_.jb().finalizeTL(jqtl, dx, dw);
   j_.jb().multiplyBinv(dw, tmp);
   JqTermAD_* jqad = j_.jb().initializeAD(dz, tmp);
   costad.enrollProcessor(jqad);
   j_.zeroAD(dw);
   DualVector<MODEL> ww;
   DualVector<MODEL> zz;
   // Jo + Jc
   for (unsigned jj = 0; jj < j_.nterms(); ++jj) {
     ww.append(costtl.releaseOutputFromTL(iq + jj));
     zz.append(j_.jterm(jj).multiplyCoInv(*ww.getv(jj)));
     costad.enrollProcessor(j_.jterm(jj).setupAD(zz.getv(jj), dw));
   }
   // Run ADJ
   j_.runAD(dw, costad);
   dz += dw;
   j_.jb().finalizeAD(jqad);
   if (test_) {
     // <G dx, dy>, where dy = Rinv H dx
     double adj_tst_fwd = dot_product(ww, zz);
     // <dx, Gt dy> , where dy = Rinv H dx
     double adj_tst_bwd = dot_product(dx, dw);
     Log::info() << "Online adjoint test, iteration: " << iter_ << std::endl
                 << util::PrintAdjTest(adj_tst_fwd, adj_tst_bwd, "G")
                 << std::endl;
   }
 }
References oops::DualVector< MODEL >::append(), dot_product(), oops::PostProcessorAD< INCR >::enrollProcessor(), oops::PostProcessorTL< INCR >::enrollProcessor(), oops::DualVector< MODEL >::getv(), oops::PostProcessorTL< INCR >::releaseOutputFromTL(), and oops::ControlIncrement< MODEL >::zero().
Member Data Documentation
iter_
template<typename MODEL > int oops::HessianMatrix< MODEL >::iter_ mutable private
Definition at line 54 of file HessianMatrix.h.
j_
template<typename MODEL > CostFct_ const& oops::HessianMatrix< MODEL >::j_ private
Definition at line 52 of file HessianMatrix.h.
test_
template<typename MODEL > bool oops::HessianMatrix< MODEL >::test_ private
Definition at line 53 of file HessianMatrix.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/HessianMatrix.h