OOPS Documentation: oops::ModelAuxCovariance< MODEL > Class Template Reference
oops::ModelAuxCovariance< MODEL > Class Template Reference
Encapsulates covariance for auxiliary model space component of ControlVariable.
#include <ModelAuxCovariance.h>
Public Member Functions
ModelAuxCovariance (const eckit::Configuration &, const Geometry_ &)
Constructor.
~ModelAuxCovariance ()
Destructor.
void linearize (const ModelAuxControl_ &, const Geometry_ &)
Set up the inner loop resolution covariance matrix.
void multiply (const ModelAuxIncrement_ &, ModelAuxIncrement_ &) const
\(dx_1 = Q dx_2 \)
void inverseMultiply (const ModelAuxIncrement_ &, ModelAuxIncrement_ &) const
\(dx_1 = Q^{-1} dx_2 \)
void multiplySqrt (const ModelAuxCtlVec_ &, ModelAuxIncrement_ &) const
\(dx = Q^{1/2} dv \)
void multiplySqrtTrans (const ModelAuxIncrement_ &, ModelAuxCtlVec_ &) const
\(dv = [Q^{1/2}]^T dx \)
void randomize (ModelAuxIncrement_ &) const
\(dx = Q^{1/2} dv_{random} \)
const eckit::Configuration & config () const
Return a constant reference to configuration.
ModelAuxCovariance_ & errorCovariance ()
Return a reference to the model specific object.
const ModelAuxCovariance_ & errorCovariance () const
Return a constant reference to the model specific object.
Static Public Member Functions
static const std::string classname ()
Private Types
using ModelAuxCovariance_ = typename MODEL::ModelAuxCovariance
using Geometry_ = Geometry< MODEL >
using ModelAuxControl_ = ModelAuxControl< MODEL >
using ModelAuxCtlVec_ = ModelAuxCtlVec< MODEL >
using ModelAuxIncrement_ = ModelAuxIncrement< MODEL >
Private Member Functions
void print (std::ostream &) const
Private Attributes
std::unique_ptr< ModelAuxCovariance_ > cov_
Pointer to the model specific object.
Detailed Description
template<typename MODEL>
class oops::ModelAuxCovariance< MODEL >
Encapsulates covariance for auxiliary model space component of ControlVariable.
This class provides the operations associated with the covariance matrix of the auxiliary model space component of ControlVariable. It wraps the actual model specific covariance matrix.
Definition at line 43 of file ModelAuxCovariance.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::ModelAuxCovariance< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 48 of file ModelAuxCovariance.h.
ModelAuxControl_
template<typename MODEL > using oops::ModelAuxCovariance< MODEL >::ModelAuxControl_ = ModelAuxControl<MODEL> private
Definition at line 49 of file ModelAuxCovariance.h.
ModelAuxCovariance_
template<typename MODEL > using oops::ModelAuxCovariance< MODEL >::ModelAuxCovariance_ = typename MODEL::ModelAuxCovariance private
Definition at line 47 of file ModelAuxCovariance.h.
ModelAuxCtlVec_
template<typename MODEL > using oops::ModelAuxCovariance< MODEL >::ModelAuxCtlVec_ = ModelAuxCtlVec<MODEL> private
Definition at line 50 of file ModelAuxCovariance.h.
ModelAuxIncrement_
template<typename MODEL > using oops::ModelAuxCovariance< MODEL >::ModelAuxIncrement_ = ModelAuxIncrement<MODEL> private
Definition at line 51 of file ModelAuxCovariance.h.
Constructor & Destructor Documentation
ModelAuxCovariance()
template<typename MODEL > oops::ModelAuxCovariance< MODEL >::ModelAuxCovariance (const eckit::Configuration & conf, const Geometry_ & resol)
Constructor.
Definition at line 93 of file ModelAuxCovariance.h.
     : cov_() {
   Log::trace() << "ModelAuxCovariance<MODEL>::ModelAuxCovariance starting"
                << std::endl;
   util::Timer timer(classname(), "ModelAuxCovariance");
   cov_.reset(new ModelAuxCovariance_(conf, resol.geometry()));
   Log::trace() << "ModelAuxCovariance<MODEL>::ModelAuxCovariance done"
                << std::endl;
 }
References oops::ModelAuxCovariance< MODEL >::classname(), oops::ModelAuxCovariance< MODEL >::cov_, and oops::Geometry< MODEL >::geometry().
~ModelAuxCovariance()
template<typename MODEL > oops::ModelAuxCovariance< MODEL >::~ModelAuxCovariance
Destructor.
Definition at line 107 of file ModelAuxCovariance.h.
{
   Log::trace() << "ModelAuxCovariance<MODEL>::~ModelAuxCovariance starting"
                << std::endl;
   util::Timer timer(classname(), "~ModelAuxCovariance");
   cov_.reset();
   Log::trace() << "ModelAuxCovariance<MODEL>::~ModelAuxCovariance done"
                << std::endl;
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::ModelAuxCovariance< MODEL >::classname () inline static
Definition at line 54 of file ModelAuxCovariance.h.
 { return "oops::ModelAuxCovariance"; }
Referenced by oops::ModelAuxCovariance< MODEL >::ModelAuxCovariance().
config()
template<typename MODEL > const eckit::Configuration& oops::ModelAuxCovariance< MODEL >::config () const inline
Return a constant reference to configuration.
Definition at line 77 of file ModelAuxCovariance.h.
 { return cov_->config(); }
References oops::ModelAuxCovariance< MODEL >::cov_.
errorCovariance() [1/2]
template<typename MODEL > ModelAuxCovariance_& oops::ModelAuxCovariance< MODEL >::errorCovariance () inline
Return a reference to the model specific object.
Definition at line 79 of file ModelAuxCovariance.h.
 { return *cov_; }
References oops::ModelAuxCovariance< MODEL >::cov_.
errorCovariance() [2/2]
template<typename MODEL > const ModelAuxCovariance_& oops::ModelAuxCovariance< MODEL >::errorCovariance () const inline
Return a constant reference to the model specific object.
Definition at line 81 of file ModelAuxCovariance.h.
 { return *cov_; }
References oops::ModelAuxCovariance< MODEL >::cov_.
inverseMultiply()
template<typename MODEL > void oops::ModelAuxCovariance< MODEL >::inverseMultiply (const ModelAuxIncrement_ & dx1, ModelAuxIncrement_ & dx2) const
\(dx_1 = Q^{-1} dx_2 \)
Definition at line 141 of file ModelAuxCovariance.h.
{
   Log::trace() << "ModelAuxCovariance<MODEL>::inverseMultiply starting"
                << std::endl;
   util::Timer timer(classname(), "inverseMultiply");
   cov_->inverseMultiply(dx1.modelauxincrement(), dx2.modelauxincrement());
   Log::trace() << "ModelAuxCovariance<MODEL>::inverseMultiply done"
                << std::endl;
 }
References oops::ModelAuxIncrement< MODEL >::modelauxincrement().
linearize()
template<typename MODEL > void oops::ModelAuxCovariance< MODEL >::linearize (const ModelAuxControl_ & xx, const Geometry_ & resol)
Set up the inner loop resolution covariance matrix.
Definition at line 119 of file ModelAuxCovariance.h.
{
   Log::trace() << "ModelAuxCovariance<MODEL>::linearize starting" << std::endl;
   util::Timer timer(classname(), "linearize");
   cov_->linearize(xx.modelauxcontrol(), resol.geometry());
   Log::trace() << "ModelAuxCovariance<MODEL>::linearize done" << std::endl;
 }
References oops::Geometry< MODEL >::geometry(), and oops::ModelAuxControl< MODEL >::modelauxcontrol().
multiply()
template<typename MODEL > void oops::ModelAuxCovariance< MODEL >::multiply (const ModelAuxIncrement_ & dx1, ModelAuxIncrement_ & dx2) const
\(dx_1 = Q dx_2 \)
Definition at line 130 of file ModelAuxCovariance.h.
{
   Log::trace() << "ModelAuxCovariance<MODEL>::multiply starting" << std::endl;
   util::Timer timer(classname(), "multiply");
   cov_->multiply(dx1.modelauxincrement(), dx2.modelauxincrement());
   Log::trace() << "ModelAuxCovariance<MODEL>::multiply done" << std::endl;
 }
References oops::ModelAuxIncrement< MODEL >::modelauxincrement().
multiplySqrt()
template<typename MODEL > void oops::ModelAuxCovariance< MODEL >::multiplySqrt (const ModelAuxCtlVec_ & dvin, ModelAuxIncrement_ & dxout) const
\(dx = Q^{1/2} dv \)
Definition at line 154 of file ModelAuxCovariance.h.
{
   Log::trace() << "ModelAuxCovariance<MODEL>::multiplySqrt starting"
                << std::endl;
   util::Timer timer(classname(), "multiplySqrt");
   cov_->multiplySqrt(dvin.modelAuxCtlVec(), dxout.modelauxincrement());
   Log::trace() << "ModelAuxCovariance<MODEL>::multiplySqrt done" << std::endl;
 }
References oops::ModelAuxCtlVec< MODEL >::modelAuxCtlVec(), and oops::ModelAuxIncrement< MODEL >::modelauxincrement().
multiplySqrtTrans()
template<typename MODEL > void oops::ModelAuxCovariance< MODEL >::multiplySqrtTrans (const ModelAuxIncrement_ & dxin, ModelAuxCtlVec_ & dvout) const
\(dv = [Q^{1/2}]^T dx \)
Definition at line 166 of file ModelAuxCovariance.h.
{
   Log::trace() << "ModelAuxCovariance<MODEL>::multiplySqrtTrans starting"
                << std::endl;
   util::Timer timer(classname(), "multiplySqrtTrans");
   cov_->multiplySqrtTrans(dxin.modelauxincrement(), dvout.modelAuxCtlVec());
   Log::trace() << "ModelAuxCovariance<MODEL>::multiplySqrtTrans done"
                << std::endl;
 }
References oops::ModelAuxCtlVec< MODEL >::modelAuxCtlVec(), and oops::ModelAuxIncrement< MODEL >::modelauxincrement().
print()
template<typename MODEL > void oops::ModelAuxCovariance< MODEL >::print (std::ostream & os) const private
Definition at line 189 of file ModelAuxCovariance.h.
{
   Log::trace() << "ModelAuxCovariance<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   os << *cov_;
   Log::trace() << "ModelAuxCovariance<MODEL>::print done" << std::endl;
 }
randomize()
template<typename MODEL > void oops::ModelAuxCovariance< MODEL >::randomize (ModelAuxIncrement_ & dx) const
\(dx = Q^{1/2} dv_{random} \)
Definition at line 179 of file ModelAuxCovariance.h.
{
   Log::trace() << "ModelAuxCovariance<MODEL>::randomize starting" << std::endl;
   util::Timer timer(classname(), "randomize");
   cov_->randomize(dx.modelauxincrement());
   Log::trace() << "ModelAuxCovariance<MODEL>::randomize done" << std::endl;
 }
References oops::ModelAuxIncrement< MODEL >::modelauxincrement().
Member Data Documentation
cov_
template<typename MODEL > std::unique_ptr<ModelAuxCovariance_> oops::ModelAuxCovariance< MODEL >::cov_ private
Pointer to the model specific object.
Definition at line 87 of file ModelAuxCovariance.h.
Referenced by oops::ModelAuxCovariance< MODEL >::config(), oops::ModelAuxCovariance< MODEL >::errorCovariance(), and oops::ModelAuxCovariance< MODEL >::ModelAuxCovariance().
The documentation for this class was generated from the following file:
src/oops/interface/ModelAuxCovariance.h