OOPS Documentation: oops::Model< MODEL > Class Template Reference
oops::Model< MODEL > Class Template Reference
Encapsulates the nonlinear forecast model.
#include <DualConfigState.h>
Public Member Functions
Model (const Geometry_ &, const eckit::Configuration &)
Constructor.
~Model ()
Destructor.
void forecast (State_ &, const ModelAux_ &, const util::Duration &, PostProcessor< State_ > &) const
Run the forecast.
const util::Duration & timeResolution () const
Return the model time step.
const Model_ & model () const
Return a constant reference to the model specific model object.
Static Public Member Functions
static const std::string classname ()
Private Types
using Model_ = typename MODEL::Model
using Geometry_ = Geometry< MODEL >
using ModelAux_ = ModelAuxControl< MODEL >
using State_ = State< MODEL >
Private Member Functions
void initialize (State_ &, const ModelAux_ &) const
Initialize the model (prior to forecast)
void step (State_ &, const ModelAux_ &) const
Model time step.
void finalize (State_ &) const
Finalize the model (after the forecast)
void print (std::ostream &) const
Private Attributes
std::unique_ptr< Model_ > model_
Pointer to the model specific model object.
Friends
class DualConfigModel< MODEL >
Detailed Description
template<typename MODEL>
class oops::Model< MODEL >
Encapsulates the nonlinear forecast model.
Definition at line 37 of file DualConfigState.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::Model< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 48 of file Model.h.
Model_
template<typename MODEL > using oops::Model< MODEL >::Model_ = typename MODEL::Model private
Definition at line 47 of file Model.h.
ModelAux_
template<typename MODEL > using oops::Model< MODEL >::ModelAux_ = ModelAuxControl<MODEL> private
Definition at line 49 of file Model.h.
State_
template<typename MODEL > using oops::Model< MODEL >::State_ = State<MODEL> private
Definition at line 50 of file Model.h.
Constructor & Destructor Documentation
Model()
template<typename MODEL > oops::Model< MODEL >::Model (const Geometry_ & resol, const eckit::Configuration & conf)
Constructor.
Definition at line 93 of file Model.h.
     : model_() {
   Log::trace() << "Model<MODEL>::Model starting" << std::endl;
   util::Timer timer(classname(), "Model");
   model_.reset(new Model_(resol.geometry(), conf));
   Log::trace() << "Model<MODEL>::Model done" << std::endl;
 }
References oops::Model< MODEL >::classname(), oops::Geometry< MODEL >::geometry(), and oops::Model< MODEL >::model_.
~Model()
template<typename MODEL > oops::Model< MODEL >::~Model
Destructor.
Definition at line 104 of file Model.h.
                      {
   Log::trace() << "Model<MODEL>::~Model starting" << std::endl;
   util::Timer timer(classname(), "~Model");
   model_.reset();
   Log::trace() << "Model<MODEL>::~Model done" << std::endl;
 }
Member Function Documentation
classname()
template<typename MODEL > static const std::string oops::Model< MODEL >::classname () inline static
Definition at line 53 of file Model.h.
 { return "oops::Model"; }
Referenced by oops::Model< MODEL >::Model().
finalize()
template<typename MODEL > void oops::Model< MODEL >::finalize (State_ & xx) const private
Finalize the model (after the forecast)
Definition at line 177 of file Model.h.
{
   Log::trace() << "Model<MODEL>::finalize starting" << std::endl;
   util::Timer timer(classname(), "finalize");
   model_->finalize(xx.state());
   Log::trace() << "Model<MODEL>::finalize done" << std::endl;
 }
References oops::State< MODEL >::state().
forecast()
template<typename MODEL > void oops::Model< MODEL >::forecast (State_ & xx, const ModelAux_ & maux, const util::Duration & len, PostProcessor< State_ > & post) const
Run the forecast.
The model forecast receives a PostProcessor, which can be used for post-processing (storing/writing of the State; constructing the linearisation trajectory for the quadratic cost function)
The model error term is handled internally by the model.
Definition at line 116 of file Model.h.
{
   Log::trace() << "Model<MODEL>::forecast starting" << std::endl;
   util::Timer timer(classname(), "forecast");
   util::LogbookWriter<std::string> log("Forecast", "Nonlinear HR trajectory");
   const util::DateTime end(xx.validTime() + len);
   {
     size_t totsteps = len / model_->timeResolution();
     util::LogbookWriter<int> log_totsteps("traj_totsteps", totsteps);
   }
   Log::info() << "Model:forecast: forecast starting: " << xx << std::endl;
   this->initialize(xx, maux);
   post.initialize(xx, end, model_->timeResolution());
   size_t step = 0;
   while (xx.validTime() < end) {
     this->step(xx, maux);
     post.process(xx);
     ++step;
     util::LogbookWriter<int> log_step("traj_step", step);
   }
   post.finalize(xx);
   this->finalize(xx);
   Log::info() << "Model:forecast: forecast finished: " << xx << std::endl;
   ASSERT(xx.validTime() == end);
   Log::trace() << "Model<MODEL>::forecast done" << std::endl;
 }
References oops::PostProcessor< FLDS >::finalize(), oops::PostProcessor< FLDS >::initialize(), oops::PostProcessor< FLDS >::process(), and oops::State< MODEL >::validTime().
Referenced by oops::DualResForecast< MODEL >::execute(), oops::EnsForecast< MODEL >::execute(), oops::Forecast< MODEL >::execute(), oops::ExternalDFI< MODEL >::execute(), oops::GenEnsPertB< MODEL >::execute(), oops::HofX< MODEL >::execute(), oops::MakeObs< MODEL >::execute(), oops::CostFct4DVarTrajHR< MODEL >::linearize(), and oops::CostFct4DVarMF< MODEL >::runNL().
initialize()
template<typename MODEL > void oops::Model< MODEL >::initialize (State_ & xx, const ModelAux_ & maux) const private
Initialize the model (prior to forecast)
Definition at line 157 of file Model.h.
{
   Log::trace() << "Model<MODEL>::initialize starting" << std::endl;
   util::Timer timer(classname(), "initialize");
   model_->initialize(xx.state(), maux.modelauxcontrol());
   Log::trace() << "Model<MODEL>::initialize done" << std::endl;
 }
References oops::ModelAuxControl< MODEL >::modelauxcontrol(), and oops::State< MODEL >::state().
model()
template<typename MODEL > const Model_& oops::Model< MODEL >::model () const inline
Return a constant reference to the model specific model object.
Definition at line 72 of file Model.h.
 { return *model_; }
References oops::Model< MODEL >::model_.
Referenced by oops::ModelAuxControl< MODEL >::ModelAuxControl(), oops::ModelAuxControlEstimator< MODEL >::ModelAuxControlEstimator(), oops::LinearModelBase< L95Traits >::setTrajectory(), and oops::State< MODEL >::State().
print()
template<typename MODEL > void oops::Model< MODEL >::print (std::ostream & os) const private
Definition at line 187 of file Model.h.
{
   Log::trace() << "Model<MODEL>::print starting" << std::endl;
   util::Timer timer(classname(), "print");
   os << *model_;
   Log::trace() << "Model<MODEL>::print done" << std::endl;
 }
step()
template<typename MODEL > void oops::Model< MODEL >::step (State_ & xx, const ModelAux_ & maux) const private
Model time step.
Definition at line 167 of file Model.h.
{
   Log::trace() << "Model<MODEL>::step starting" << std::endl;
   util::Timer timer(classname(), "step");
   model_->step(xx.state(), maux.modelauxcontrol());
   Log::trace() << "Model<MODEL>::step done" << std::endl;
 }
References oops::ModelAuxControl< MODEL >::modelauxcontrol(), and oops::State< MODEL >::state().
timeResolution()
template<typename MODEL > const util::Duration& oops::Model< MODEL >::timeResolution () const inline
Return the model time step.
Definition at line 66 of file Model.h.
{
     return model_->timeResolution();
   }
References oops::Model< MODEL >::model_.
Friends And Related Function Documentation
DualConfigModel< MODEL >
template<typename MODEL > friend class DualConfigModel< MODEL > friend
Definition at line 87 of file Model.h.
Member Data Documentation
model_
template<typename MODEL > std::unique_ptr<Model_> oops::Model< MODEL >::model_ private
Pointer to the model specific model object.
Definition at line 84 of file Model.h.
Referenced by oops::Model< MODEL >::Model(), oops::Model< MODEL >::model(), and oops::Model< MODEL >::timeResolution().
The documentation for this class was generated from the following files:
src/oops/generic/DualConfigState.h
src/oops/interface/Model.h