OOPS Documentation: src/util/dot_product.h File Reference
dot_product.h File Reference
Functions
template<class T >
double dot_product (const T &x, const T &y)
Syntactic sugar to let us use a more mathematical notation for dot products.
Function Documentation
dot_product()
template<class T > double dot_product (const T & x, const T & y) inline
Syntactic sugar to let us use a more mathematical notation for dot products.
Definition at line 17 of file dot_product.h.
{
   return x.dot_product_with(y);
 }
Referenced by oops::Minimizer< MODEL >::adjModelTest(), oops::Minimizer< MODEL >::adjObsTest(), oops::CostJbJq< MODEL >::Bminv(), oops::CostJbJq< MODEL >::Bmult(), oops::SQRTPCGMinimizer< MODEL >::calcQuadCost(), oops::SQRTBPCGMinimizer< MODEL >::calcQuadCost(), oops::SQRTBPFOMMinimizer< MODEL >::calcQuadCost(), oops::SQRTBPLanczosMinimizer< MODEL >::calcQuadCost(), oops::SQRTPLanczosMinimizer< MODEL >::calcQuadCost(), oops::DRMinimizer< MODEL >::checkpoint(), oops::SQRTMinimizer< MODEL >::checkpointDv0(), oops::SQRTMinimizer< MODEL >::checkpointDvh(), oops::SQRTMinimizer< MODEL >::checkpointGradJb(), oops::UtHtRinvHUMatrix< MODEL >::computeDiagnostics(), oops::CostFunction< MODEL >::computeGradientFG(), oops::DualMinimizer< MODEL >::doMinimize(), oops::DRMinimizer< MODEL >::doMinimize(), oops::DualVector< MODEL >::dot_product_with(), oops::SaddlePointVector< MODEL >::dot_product_with(), oops::Increment4D< MODEL >::dot_product_with(), oops::IncrCtlVec4D< MODEL >::dot_product_with(), oops::ControlIncrement< MODEL >::dot_product_with(), oops::Departures< MODEL >::dot_product_with(), oops::ControlVector< MODEL >::dot_product_with(), oops::CostJbTotal< MODEL >::evaluate(), oops::FGMRES(), oops::CostJcDFI< MODEL >::finalize(), oops::CostJcDFI< MODEL >::finalizeTraj(), oops::CostJo< MODEL >::finalizeTraj(), oops::FullGMRES(), oops::GMRESR(), oops::SaddlePointLMPMatrix< MODEL >::Gmultiply(), oops::QNewtonSqrtLMP< MODEL >::inverseMultiply(), oops::SpectralSqrtLMP< MODEL >::inverseMultiply(), oops::QNewtonSqrtLMP< MODEL >::inverseMultiplySqrt(), oops::SpectralSqrtLMP< MODEL >::inverseMultiplySqrt(), oops::IPCG(), oops::MINRES(), oops::HBHtMatrix< MODEL >::multiply(), oops::HessianMatrix< MODEL >::multiply(), oops::HtRinvHMatrix< MODEL >::multiply(), oops::JbMatrix< MODEL >::multiply(), oops::QNewtonLMP< oops::ControlIncrement, oops::BMatrix >::multiply(), oops::SpectralLMP< oops::ControlIncrement >::multiply(), oops::CostJcDFI< MODEL >::multiplyCoInv(), oops::SpectralSqrtLMP< MODEL >::multiplySqrt(), oops::PCG(), oops::PLanczos(), oops::SpectralSqrtLMP< MODEL >::postprocess(), oops::CostJo< MODEL >::printJo(), oops::EnsembleCovsInterpolSDL< MODEL >::randomize(), oops::DRMinimizer< MODEL >::restart(), oops::SQRTMinimizer< MODEL >::restartDv0(), oops::SQRTMinimizer< MODEL >::restartDvh(), oops::SQRTMinimizer< MODEL >::restartGradJb(), oops::SaddlePointLMPMatrix< MODEL >::setup(), oops::SQRTBPLanczosMinimizer< MODEL >::solve(), oops::SQRTBPFOMMinimizer< MODEL >::solve(), oops::SQRTPCGMinimizer< MODEL >::solve(), oops::SQRTBPCGMinimizer< MODEL >::solve(), oops::SQRTPLanczosMinimizer< MODEL >::solve(), oops::DRPFOMMinimizer< MODEL >::solve(), oops::RPCGMinimizer< MODEL >::solve(), oops::RPLanczosMinimizer< MODEL >::solve(), oops::DRPLanczosMinimizer< MODEL >::solve(), oops::DRGMRESRMinimizer< MODEL >::solve(), oops::DRIPCGMinimizer< MODEL >::solve(), oops::DRPCGMinimizer< MODEL >::solve(), test::testErrorCovarianceSym(), test::testIncrementDotProduct(), test::testLinearModelAdjoint(), test::testModelAuxIncrementDotProduct(), test::testObsAuxIncrementDotProduct(), oops::Minimizer< MODEL >::tlmTaylorTest(), oops::QNewtonLMP< oops::ControlIncrement, oops::BMatrix >::tmultiply(), oops::SQRTMinimizer< MODEL >::updateJbCostFunction(), and oops::SQRTMinimizer< MODEL >::warmStartAux().