OOPS Documentation: qg Namespace Reference
qg Namespace Reference
The namespace for the qg model.
Classes
class ErrorCovarianceQG
Background error covariance matrix for QG model.
class FieldsQG
Class to represent a FieldSet for the QG model.
class GenericCtlVecQG
GenericCtlVecQG Class.
class GeometryQG
GeometryQG handles geometry for QG model.
class GomQG
GomQG class to handle local model values for QG model.
class HorizScaleDecompositionQG
HorizScaleDecomposition matrix for QG model.
class IncrementQG
Increment Class: Difference between two states.
class IncrEnsCtlVecQG
IncrEnsCtlVecQG Class.
class IncrModCtlVecQG
IncrModCtlVecQG Class.
class InterpolatorQG
Interpolator matrix for QG model.
class LocalizationMatrixQG
Localization matrix for QG model.
class LocationsQG
LocationsQG class to handle locations for QG model.
class LogbookQG
Connects to the OOPS execution Logbook.
class ModelBias
Model error for the QG model.
class ModelBiasCovariance
class ModelBiasCtlVec
ModelBiasCtlVec Class.
class ModelBiasEstimator
Model error neural network model for the QG model.
class ModelBiasIncrement
class ModelQG
QG model definition.
class ObsBias
Class to handle observation bias parameters.
class ObsBiasCovariance
class ObsBiasCtlVec
ObsBiasCtlVec Class.
class ObsBiasIncrement
class ObsErrStreamQG
Diagonal observation error covariance matrix.
class ObsErrWindQG
Diagonal observation error covariance matrix.
class ObsErrWSpeedQG
Diagonal observation error covariance matrix.
class ObsHelpQG
Observation Data Handler for QG Model.
class ObsSpaceQG
Wrapper around ObsHelpQG, mostly to hide the factory.
class ObsStreamQG
Streamfunction observation for QG model.
class ObsStreamTLAD
Streamfunction TL/AD observation operator for QG model.
class ObsVecQG
ObsVecQG class to handle vectors in observation space for QG model.
class ObsWindQG
Wind observation for QG model.
class ObsWindTLAD
Wind TL/AD observation operator for QG model.
class ObsWSpeedQG
Wind speed observation for QG model.
class ObsWSpeedTLAD
struct QgTraits
class StateQG
QG model state.
class TlmIdQG
QG linear identity model definition.
class TlmQG
QG linear model definition.
class VariablesQG
VariablesQG class to handle variables for QG model.
Typedefs
using F90geom = int
using F90model = int
using F90vars = int
using F90locs = int
using F90goms = int
using F90flds = int
using F90ctlvec = int
using F90traj = int
using F90bmat = int
using F90ovec = int
using F90hop = int
using F90odb = int
using F90lclz = int
Functions
void fft_fwd_f (const int &kk, const double *xx, double *ff)
void fft_inv_f (const int &kk, const double *ff, double *xx)
eckit::Stream & operator<< (eckit::Stream &s, const FieldsQG &rhs)
eckit::Stream & operator>> (eckit::Stream &s, FieldsQG &rhs)
void qg_geo_setup_f90 (F90geom &, const eckit::Configuration *const *)
Interface to Fortran QG model.
void qg_geo_clone_f90 (const F90geom &, F90geom &)
void qg_geo_info_f90 (const F90geom &, int &, int &)
void qg_geo_delete_f90 (F90geom &)
void qg_setup_f90 (const eckit::Configuration *const *, const F90geom &, F90model &)
void qg_delete_f90 (F90model &)
void qg_prepare_integration_f90 (const F90model &, const F90flds &)
void qg_prepare_integration_tl_f90 (const F90model &, const F90flds &)
void qg_prepare_integration_ad_f90 (const F90model &, const F90flds &)
void qg_propagate_f90 (const F90model &, const F90flds &)
void qg_prop_traj_f90 (const F90model &, const F90flds &, F90traj &)
void qg_propagate_tl_f90 (const F90model &, const F90flds &, const F90traj &)
void qg_propagate_ad_f90 (const F90model &, const F90flds &, const F90traj &)
void qg_wipe_traj_f90 (F90traj &)
void qg_traj_minmaxrms_f90 (const F90traj &, double &)
void qg_field_create_f90 (F90flds &, const F90geom &, const F90vars &)
void qg_field_delete_f90 (F90flds &)
void qg_field_copy_f90 (const F90flds &, const F90flds &)
void qg_field_zero_f90 (const F90flds &)
void qg_field_self_add_f90 (const F90flds &, const F90flds &)
void qg_field_self_sub_f90 (const F90flds &, const F90flds &)
void qg_field_self_mul_f90 (const F90flds &, const double &)
void qg_field_axpy_f90 (const F90flds &, const double &, const F90flds &)
void qg_field_dot_prod_f90 (const F90flds &, const F90flds &, double &)
void qg_field_self_schur_f90 (const F90flds &, const F90flds &)
void qg_field_random_f90 (const F90flds &)
void qg_field_add_incr_f90 (const F90flds &, const F90flds &)
void qg_field_diff_incr_f90 (const F90flds &, const F90flds &, const F90flds &)
void qg_field_change_resol_f90 (const F90flds &, const F90flds &)
void qg_field_read_file_f90 (const F90flds &, const eckit::Configuration *const *, util::DateTime *const *)
void qg_field_write_file_f90 (const F90flds &, const eckit::Configuration *const *, const util::DateTime *const *)
void qg_field_interp_f90 (const F90flds &, const F90locs &, const F90goms &)
void qg_field_interp_tl_f90 (const F90flds &, const F90locs &, const F90goms &)
void qg_field_interp_ad_f90 (const F90flds &, const F90locs &, const F90goms &)
void qg_field_gpnorm_f90 (const F90flds &, const int &, double &)
void qg_field_sizes_f90 (const F90flds &, int &, int &, int &, int &)
void qg_field_rms_f90 (const F90flds &, double &)
void qg_field_serialize_f90 (eckit::Stream **, const F90flds &)
void qg_field_deserialize_f90 (eckit::Stream **, const F90flds &)
void qg_generic_ctl_vec_create_f90 (F90ctlvec &, const int &, const int &, const int &)
void qg_generic_ctl_vec_delete_f90 (F90ctlvec &)
void qg_generic_ctl_vec_copy_f90 (const F90ctlvec &, const F90ctlvec &)
void qg_generic_ctl_vec_zero_f90 (const F90ctlvec &)
void qg_generic_ctl_vec_self_add_f90 (const F90ctlvec &, const F90ctlvec &)
void qg_generic_ctl_vec_self_sub_f90 (const F90ctlvec &, const F90ctlvec &)
void qg_generic_ctl_vec_self_mul_f90 (const F90ctlvec &, const double &)
void qg_generic_ctl_vec_axpy_f90 (const F90ctlvec &, const double &, const F90ctlvec &)
void qg_generic_ctl_vec_dot_prod_f90 (const F90ctlvec &, const F90ctlvec &, double &)
void qg_generic_ctl_vec_self_schur_f90 (const F90ctlvec &, const F90ctlvec &)
void qg_generic_ctl_vec_random_f90 (const F90ctlvec &)
void qg_generic_ctl_vec_change_resol_f90 (const F90ctlvec &, const F90ctlvec &)
void qg_generic_ctl_vec_get_section_f90 (const F90ctlvec &, double *, const int &, const int &)
void qg_generic_ctl_vec_set_section_f90 (const F90ctlvec &, const double *, const int &, const int &)
void qg_generic_ctl_vec_read_file_f90 (const F90ctlvec &, const eckit::Configuration *const *)
void qg_generic_ctl_vec_write_file_f90 (const F90ctlvec &, const eckit::Configuration *const *)
void qg_generic_ctl_vec_gpnorm_f90 (const F90ctlvec &, double &)
void qg_generic_ctl_vec_rms_f90 (const F90ctlvec &, double &)
void qg_b_setup_f90 (F90bmat &, const eckit::Configuration *const *, const F90geom &)
void qg_b_delete_f90 (F90bmat &)
void qg_b_linearize_f90 (const F90bmat &, const eckit::Configuration *const *)
void qg_b_mult_f90 (const F90bmat &, const F90flds &, const F90flds &)
void qg_b_invmult_f90 (const F90bmat &, const F90flds &, const F90flds &)
void qg_b_mult_sqrt_f90 (const F90bmat &, const F90ctlvec &, const F90flds &)
void qg_b_mult_sqrt_trans_f90 (const F90bmat &, const F90flds &, const F90ctlvec &)
void qg_b_randomize_f90 (const F90bmat &, const F90flds &)
void qg_b_get_dim_f90 (const F90bmat &, const int &)
void qg_localization_setup_f90 (F90lclz &, const eckit::Configuration *const *, const F90geom &)
void qg_localization_delete_f90 (F90lclz &)
void qg_localization_mult_f90 (const F90lclz &, const F90flds &)
void qg_localization_mult_sqrt_f90 (const F90lclz &, const F90ctlvec &, const F90flds &)
void qg_localization_mult_sqrt_trans_f90 (const F90lclz &, const F90flds &, const F90ctlvec &)
void qg_localization_get_dim_f90 (const F90lclz &, const int &)
void qg_var_create_f90 (F90vars &, const eckit::Configuration *const *)
void qg_var_clone_f90 (const F90vars &, F90vars &)
void qg_var_info_f90 (const F90vars &, int &, int &)
void qg_var_delete_f90 (F90vars &)
void qg_loc_delete_f90 (F90locs &)
void qg_loc_nobs_f90 (const F90locs &, int &)
void qg_gom_create_f90 (F90goms &)
void qg_gom_delete_f90 (F90goms &)
void qg_gom_zero_f90 (const F90goms &)
void qg_gom_random_f90 (const F90goms &)
void qg_gom_dotprod_f90 (const F90goms &, const F90goms &, double &)
void qg_gom_minmaxavg_f90 (const F90goms &, int &, double &, double &, double &)
void qg_gom_read_file_f90 (const F90goms &, const eckit::Configuration *const *)
void qg_gom_write_file_f90 (const F90goms &, const eckit::Configuration *const *)
void qg_obserr_setup_wghts_sqrt_f90 (const F90ovec &, const F90ovec &, const F90ovec &, const double &, const double &)
void qg_stream_setup_f90 (F90hop &, const eckit::Configuration *const *)
void qg_stream_delete_f90 (F90hop &)
void qg_stream_equiv_f90 (const F90goms &, const F90ovec &, const double &)
void qg_stream_equiv_tl_f90 (const F90goms &, const F90ovec &, const double &)
void qg_stream_equiv_ad_f90 (const F90goms &, const F90ovec &, double &)
void qg_wind_setup_f90 (F90hop &, const eckit::Configuration *const *)
void qg_wind_delete_f90 (F90hop &)
void qg_wind_equiv_f90 (const F90goms &, F90ovec &, const double &)
void qg_wind_bias_equiv_f90 (const F90goms &, F90ovec &, const double &)
void qg_wind_equiv_tl_f90 (const F90goms &, const F90ovec &, const double &)
void qg_wind_equiv_ad_f90 (const F90goms &, const F90ovec &, double &)
void qg_wind_bias_equiv_tl_f90 (const F90goms &, const F90ovec &, const double &)
void qg_wind_bias_equiv_ad_f90 (const F90goms &, const F90ovec &, double &)
void qg_wspeed_setup_f90 (F90hop &, const eckit::Configuration *const *)
void qg_wspeed_delete_f90 (F90hop &)
void qg_wspeed_eqv_f90 (const F90goms &, const F90ovec &, const double &)
void qg_wspeed_equiv_tl_f90 (const F90goms &, const F90ovec &, const F90goms &, const double &)
void qg_wspeed_equiv_ad_f90 (const F90goms &, const F90ovec &, const F90goms &, double &)
void qg_wspeed_gettraj_f90 (const F90hop &, const int &, F90goms &)
void qg_wspeed_settraj_f90 (const F90goms &, const F90goms &)
void qg_obsvec_setup_f90 (F90ovec &, const int &, const int &)
void qg_obsvec_clone_f90 (const F90ovec &, F90ovec &)
void qg_obsvec_delete_f90 (F90ovec &)
void qg_obsvec_assign_f90 (const F90ovec &, const F90ovec &)
void qg_obsvec_zero_f90 (const F90ovec &)
void qg_obsvec_mul_scal_f90 (const F90ovec &, const double &)
void qg_obsvec_add_f90 (const F90ovec &, const F90ovec &)
void qg_obsvec_sub_f90 (const F90ovec &, const F90ovec &)
void qg_obsvec_mul_f90 (const F90ovec &, const F90ovec &)
void qg_obsvec_div_f90 (const F90ovec &, const F90ovec &)
void qg_obsvec_axpy_f90 (const F90ovec &, const double &, const F90ovec &)
void qg_obsvec_invert_f90 (const F90ovec &)
void qg_obsvec_random_f90 (const F90ovec &)
void qg_obsvec_dotprod_f90 (const F90ovec &, const F90ovec &, double &)
void qg_obsvec_minmaxavg_f90 (const F90ovec &, double &, double &, double &)
void qg_obsvec_nobs_f90 (const F90ovec &, int &)
void qg_obsdb_setup_f90 (F90odb &, const eckit::Configuration *const *)
void qg_obsdb_screened_setup_f90 (F90odb &, const eckit::Configuration *const *)
void qg_obsdb_delete_f90 (F90odb &)
void qg_obsdb_get_f90 (const F90odb &, const int &, const char *, const int &, const char *, const F90ovec &)
void qg_obsdb_put_f90 (const F90odb &, const int &, const char *, const int &, const char *, const F90ovec &)
void qg_obsdb_locations_f90 (const F90odb &, const int &, const char *, const util::DateTime *const *, const util::DateTime *const *, F90locs &)
void qg_obsdb_getgom_f90 (const F90odb &, const int &, const char *, const F90vars &, const util::DateTime *const *, const util::DateTime *const *, F90goms &)
void qg_obsdb_generate_f90 (const F90odb &, const int &, const char *, const eckit::Configuration *const *, const util::DateTime *const *, const util::Duration *const *, const int &, int &)
void qg_obsdb_seterr_f90 (const F90odb &, const F90hop &, const double &)
void qg_obsdb_setbiaserr_f90 (const F90odb &, const F90hop &, const double &)
void qg_obsdb_nobs_f90 (const F90odb &, const int &, const char *, int &)
void qg_obsoper_inputs_f90 (const F90hop &, F90vars &)
void random_f (const int &nn, double *xx)
Variables
static oops::ObsAuxControlMaker< QgTraits, ObsBias > makesObsBias_ ("ObsBiasQG")
static oops::ObsAuxCovarianceMaker< QgTraits, ObsBiasCovariance > makeObsBiasCovariance_ ("ObsBiasQG")
static oops::ObsAuxCtlVecMaker< QgTraits, ObsBiasCtlVec > makeObsBiasCtlVec_ ("ObsBiasQG")
static oops::ObsAuxIncrementMaker< QgTraits, ObsBiasIncrement > makesObsBiasIncrement_ ("ObsBiasQG")
static oops::ObsErrorMaker< QgTraits, ObsErrStreamQG > makerObsErrStreamIFS_ ("StreamObsError")
static oops::ObsErrorMaker< QgTraits, ObsErrWindQG > makerObsErrStreamIFS_ ("WindObsError")
static oops::ObsErrorMaker< QgTraits, ObsErrWSpeedQG > makerObsErrStreamIFS_ ("WSpeedObsError")
static oops::ObsOperatorMaker< QgTraits, ObsStreamQG > makerStream_ ("Stream")
static oops::LinearObsOpMaker< QgTraits, ObsStreamTLAD > makerStreamTL_ ("Stream")
static oops::ObsOperatorMaker< QgTraits, ObsWindQG > makerWind_ ("Wind")
static oops::LinearObsOpMaker< QgTraits, ObsWindTLAD > makerWindTL_ ("Wind")
static oops::ObsOperatorMaker< QgTraits, ObsWSpeedQG > makerWSpeed_ ("WSpeed")
static oops::LinearObsOpMaker< QgTraits, ObsWSpeedTLAD > makerWSpeedTL_ ("WSpeed")
static oops::LinearModelMaker< QgTraits, TlmIdQG > makerQGIdTLM_ ("QgIdTLM")
static oops::LinearModelMaker< QgTraits, TlmQG > makerQGTLM_ ("QgTLM")
Detailed Description
The namespace for the qg model.
Typedef Documentation
F90bmat
using qg::F90bmat = typedef int
Definition at line 44 of file QgFortran.h.
F90ctlvec
using qg::F90ctlvec = typedef int
Definition at line 40 of file QgFortran.h.
F90flds
using qg::F90flds = typedef int
Definition at line 38 of file QgFortran.h.
F90geom
using qg::F90geom = typedef int
Definition at line 28 of file QgFortran.h.
F90goms
using qg::F90goms = typedef int
Definition at line 36 of file QgFortran.h.
F90hop
using qg::F90hop = typedef int
Definition at line 48 of file QgFortran.h.
F90lclz
using qg::F90lclz = typedef int
Definition at line 52 of file QgFortran.h.
F90locs
using qg::F90locs = typedef int
Definition at line 34 of file QgFortran.h.
F90model
using qg::F90model = typedef int
Definition at line 30 of file QgFortran.h.
F90odb
using qg::F90odb = typedef int
Definition at line 50 of file QgFortran.h.
F90ovec
using qg::F90ovec = typedef int
Definition at line 46 of file QgFortran.h.
F90traj
using qg::F90traj = typedef int
Definition at line 42 of file QgFortran.h.
F90vars
using qg::F90vars = typedef int
Definition at line 32 of file QgFortran.h.
Function Documentation
fft_fwd_f()
void qg::fft_fwd_f (const int & kk, const double * xx, double * ff)
Definition at line 20 of file fft_f.cc.
{
   static Eigen::FFT<double> fft;
   std::vector<double> grid(kk);
   const unsigned int size = kk/2+1;
   std::vector<std::complex<double> > coefs(size);
   for (int jj = 0; jj < kk; ++jj) grid[jj] = xx[jj];
   fft.fwd(coefs, grid);
   for (unsigned int jj = 0; jj < size; ++jj) {
     ff[2*jj]   = coefs[jj].real();
     ff[2*jj+1] = coefs[jj].imag();
   }
 }
fft_inv_f()
void qg::fft_inv_f (const int & kk, const double * ff, double * xx)
Definition at line 38 of file fft_f.cc.
{
   static Eigen::FFT<double> fft;
   std::vector<double> grid(kk);
   std::vector<std::complex<double> > coefs(kk);
   const std::complex<double> zero(0.0, 0.0);
   const int size = kk/2+1;
   for (int jj = 0; jj < size; ++jj) {
     std::complex<double> zz(ff[2*jj], ff[2*jj+1]);
     coefs[jj] = zz;
   }
   for (int jj = size; jj < kk; ++jj) coefs[jj] = zero;
   fft.inv(grid, coefs);
   for (int jj = 0; jj < kk; ++jj) xx[jj] = grid[jj];
 }
operator<<()
eckit::Stream& qg::operator<< (eckit::Stream & s, const FieldsQG & rhs)
Definition at line 194 of file FieldsQG.cc.
{
   eckit::Stream* stream = &s;
   qg_field_serialize_f90(&stream, rhs.keyFlds_);
   return s;
 }
References qg_field_serialize_f90().
operator>>()
eckit::Stream& qg::operator>> (eckit::Stream & s, FieldsQG & rhs)
Definition at line 200 of file FieldsQG.cc.
{
   eckit::Stream* stream = &s;
   qg_field_deserialize_f90(&stream, rhs.keyFlds_);
   return s;
 }
References qg_field_deserialize_f90().
qg_b_delete_f90()
void qg::qg_b_delete_f90 (F90bmat &)
qg_b_get_dim_f90()
void qg::qg_b_get_dim_f90 (const F90bmat & , const int &)
qg_b_invmult_f90()
void qg::qg_b_invmult_f90 (const F90bmat & , const F90flds & , const F90flds &)
qg_b_linearize_f90()
void qg::qg_b_linearize_f90 (const F90bmat & , const eckit::Configuration *const *)
qg_b_mult_f90()
void qg::qg_b_mult_f90 (const F90bmat & , const F90flds & , const F90flds &)
qg_b_mult_sqrt_f90()
void qg::qg_b_mult_sqrt_f90 (const F90bmat & , const F90ctlvec & , const F90flds &)
qg_b_mult_sqrt_trans_f90()
void qg::qg_b_mult_sqrt_trans_f90 (const F90bmat & , const F90flds & , const F90ctlvec &)
qg_b_randomize_f90()
void qg::qg_b_randomize_f90 (const F90bmat & , const F90flds &)
qg_b_setup_f90()
void qg::qg_b_setup_f90 (F90bmat & , const eckit::Configuration *const * , const F90geom &)
qg_delete_f90()
void qg::qg_delete_f90 (F90model &)
qg_field_add_incr_f90()
void qg::qg_field_add_incr_f90 (const F90flds & , const F90flds &)
qg_field_axpy_f90()
void qg::qg_field_axpy_f90 (const F90flds & , const double & , const F90flds &)
qg_field_change_resol_f90()
void qg::qg_field_change_resol_f90 (const F90flds & , const F90flds &)
qg_field_copy_f90()
void qg::qg_field_copy_f90 (const F90flds & , const F90flds &)
qg_field_create_f90()
void qg::qg_field_create_f90 (F90flds & , const F90geom & , const F90vars &)
qg_field_delete_f90()
void qg::qg_field_delete_f90 (F90flds &)
qg_field_deserialize_f90()
void qg::qg_field_deserialize_f90 (eckit::Stream ** , const F90flds &)
Referenced by operator>>().
qg_field_diff_incr_f90()
void qg::qg_field_diff_incr_f90 (const F90flds & , const F90flds & , const F90flds &)
qg_field_dot_prod_f90()
void qg::qg_field_dot_prod_f90 (const F90flds & , const F90flds & , double &)
qg_field_gpnorm_f90()
void qg::qg_field_gpnorm_f90 (const F90flds & , const int & , double &)
qg_field_interp_ad_f90()
void qg::qg_field_interp_ad_f90 (const F90flds & , const F90locs & , const F90goms &)
qg_field_interp_f90()
void qg::qg_field_interp_f90 (const F90flds & , const F90locs & , const F90goms &)
qg_field_interp_tl_f90()
void qg::qg_field_interp_tl_f90 (const F90flds & , const F90locs & , const F90goms &)
qg_field_random_f90()
void qg::qg_field_random_f90 (const F90flds &)
qg_field_read_file_f90()
void qg::qg_field_read_file_f90 (const F90flds & , const eckit::Configuration *const * , util::DateTime *const *)
qg_field_rms_f90()
void qg::qg_field_rms_f90 (const F90flds & , double &)
qg_field_self_add_f90()
void qg::qg_field_self_add_f90 (const F90flds & , const F90flds &)
qg_field_self_mul_f90()
void qg::qg_field_self_mul_f90 (const F90flds & , const double &)
qg_field_self_schur_f90()
void qg::qg_field_self_schur_f90 (const F90flds & , const F90flds &)
qg_field_self_sub_f90()
void qg::qg_field_self_sub_f90 (const F90flds & , const F90flds &)
qg_field_serialize_f90()
void qg::qg_field_serialize_f90 (eckit::Stream ** , const F90flds &)
Referenced by operator<<().
qg_field_sizes_f90()
void qg::qg_field_sizes_f90 (const F90flds & , int & , int & , int & , int &)
qg_field_write_file_f90()
void qg::qg_field_write_file_f90 (const F90flds & , const eckit::Configuration *const * , const util::DateTime *const *)
qg_field_zero_f90()
void qg::qg_field_zero_f90 (const F90flds &)
qg_generic_ctl_vec_axpy_f90()
void qg::qg_generic_ctl_vec_axpy_f90 (const F90ctlvec & , const double & , const F90ctlvec &)
qg_generic_ctl_vec_change_resol_f90()
void qg::qg_generic_ctl_vec_change_resol_f90 (const F90ctlvec & , const F90ctlvec &)
qg_generic_ctl_vec_copy_f90()
void qg::qg_generic_ctl_vec_copy_f90 (const F90ctlvec & , const F90ctlvec &)
qg_generic_ctl_vec_create_f90()
void qg::qg_generic_ctl_vec_create_f90 (F90ctlvec & , const int & , const int & , const int &)
qg_generic_ctl_vec_delete_f90()
void qg::qg_generic_ctl_vec_delete_f90 (F90ctlvec &)
qg_generic_ctl_vec_dot_prod_f90()
void qg::qg_generic_ctl_vec_dot_prod_f90 (const F90ctlvec & , const F90ctlvec & , double &)
qg_generic_ctl_vec_get_section_f90()
void qg::qg_generic_ctl_vec_get_section_f90 (const F90ctlvec & , double * , const int & , const int &)
qg_generic_ctl_vec_gpnorm_f90()
void qg::qg_generic_ctl_vec_gpnorm_f90 (const F90ctlvec & , double &)
qg_generic_ctl_vec_random_f90()
void qg::qg_generic_ctl_vec_random_f90 (const F90ctlvec &)
qg_generic_ctl_vec_read_file_f90()
void qg::qg_generic_ctl_vec_read_file_f90 (const F90ctlvec & , const eckit::Configuration *const *)
qg_generic_ctl_vec_rms_f90()
void qg::qg_generic_ctl_vec_rms_f90 (const F90ctlvec & , double &)
qg_generic_ctl_vec_self_add_f90()
void qg::qg_generic_ctl_vec_self_add_f90 (const F90ctlvec & , const F90ctlvec &)
qg_generic_ctl_vec_self_mul_f90()
void qg::qg_generic_ctl_vec_self_mul_f90 (const F90ctlvec & , const double &)
qg_generic_ctl_vec_self_schur_f90()
void qg::qg_generic_ctl_vec_self_schur_f90 (const F90ctlvec & , const F90ctlvec &)
qg_generic_ctl_vec_self_sub_f90()
void qg::qg_generic_ctl_vec_self_sub_f90 (const F90ctlvec & , const F90ctlvec &)
qg_generic_ctl_vec_set_section_f90()
void qg::qg_generic_ctl_vec_set_section_f90 (const F90ctlvec & , const double * , const int & , const int &)
qg_generic_ctl_vec_write_file_f90()
void qg::qg_generic_ctl_vec_write_file_f90 (const F90ctlvec & , const eckit::Configuration *const *)
qg_generic_ctl_vec_zero_f90()
void qg::qg_generic_ctl_vec_zero_f90 (const F90ctlvec &)
qg_geo_clone_f90()
void qg::qg_geo_clone_f90 (const F90geom & , F90geom &)
qg_geo_delete_f90()
void qg::qg_geo_delete_f90 (F90geom &)
qg_geo_info_f90()
void qg::qg_geo_info_f90 (const F90geom & , int & , int &)
qg_geo_setup_f90()
void qg::qg_geo_setup_f90 (F90geom & , const eckit::Configuration *const *)
Interface to Fortran QG model.
The core of the QG model is coded in Fortran. Here we define the interfaces to the Fortran code.
qg_gom_create_f90()
void qg::qg_gom_create_f90 (F90goms &)
qg_gom_delete_f90()
void qg::qg_gom_delete_f90 (F90goms &)
qg_gom_dotprod_f90()
void qg::qg_gom_dotprod_f90 (const F90goms & , const F90goms & , double &)
qg_gom_minmaxavg_f90()
void qg::qg_gom_minmaxavg_f90 (const F90goms & , int & , double & , double & , double &)
qg_gom_random_f90()
void qg::qg_gom_random_f90 (const F90goms &)
qg_gom_read_file_f90()
void qg::qg_gom_read_file_f90 (const F90goms & , const eckit::Configuration *const *)
qg_gom_write_file_f90()
void qg::qg_gom_write_file_f90 (const F90goms & , const eckit::Configuration *const *)
qg_gom_zero_f90()
void qg::qg_gom_zero_f90 (const F90goms &)
qg_loc_delete_f90()
void qg::qg_loc_delete_f90 (F90locs &)
qg_loc_nobs_f90()
void qg::qg_loc_nobs_f90 (const F90locs & , int &)
qg_localization_delete_f90()
void qg::qg_localization_delete_f90 (F90lclz &)
qg_localization_get_dim_f90()
void qg::qg_localization_get_dim_f90 (const F90lclz & , const int &)
qg_localization_mult_f90()
void qg::qg_localization_mult_f90 (const F90lclz & , const F90flds &)
qg_localization_mult_sqrt_f90()
void qg::qg_localization_mult_sqrt_f90 (const F90lclz & , const F90ctlvec & , const F90flds &)
qg_localization_mult_sqrt_trans_f90()
void qg::qg_localization_mult_sqrt_trans_f90 (const F90lclz & , const F90flds & , const F90ctlvec &)
qg_localization_setup_f90()
void qg::qg_localization_setup_f90 (F90lclz & , const eckit::Configuration *const * , const F90geom &)
qg_obsdb_delete_f90()
void qg::qg_obsdb_delete_f90 (F90odb &)
qg_obsdb_generate_f90()
void qg::qg_obsdb_generate_f90 (const F90odb & , const int & , const char * , const eckit::Configuration *const * , const util::DateTime *const * , const util::Duration *const * , const int & , int &)
qg_obsdb_get_f90()
void qg::qg_obsdb_get_f90 (const F90odb & , const int & , const char * , const int & , const char * , const F90ovec &)
qg_obsdb_getgom_f90()
void qg::qg_obsdb_getgom_f90 (const F90odb & , const int & , const char * , const F90vars & , const util::DateTime *const * , const util::DateTime *const * , F90goms &)
qg_obsdb_locations_f90()
void qg::qg_obsdb_locations_f90 (const F90odb & , const int & , const char * , const util::DateTime *const * , const util::DateTime *const * , F90locs &)
qg_obsdb_nobs_f90()
void qg::qg_obsdb_nobs_f90 (const F90odb & , const int & , const char * , int &)
qg_obsdb_put_f90()
void qg::qg_obsdb_put_f90 (const F90odb & , const int & , const char * , const int & , const char * , const F90ovec &)
qg_obsdb_screened_setup_f90()
void qg::qg_obsdb_screened_setup_f90 (F90odb & , const eckit::Configuration *const *)
qg_obsdb_setbiaserr_f90()
void qg::qg_obsdb_setbiaserr_f90 (const F90odb & , const F90hop & , const double &)
qg_obsdb_seterr_f90()
void qg::qg_obsdb_seterr_f90 (const F90odb & , const F90hop & , const double &)
qg_obsdb_setup_f90()
void qg::qg_obsdb_setup_f90 (F90odb & , const eckit::Configuration *const *)
qg_obserr_setup_wghts_sqrt_f90()
void qg::qg_obserr_setup_wghts_sqrt_f90 (const F90ovec & , const F90ovec & , const F90ovec & , const double & , const double &)
qg_obsoper_inputs_f90()
void qg::qg_obsoper_inputs_f90 (const F90hop & , F90vars &)
qg_obsvec_add_f90()
void qg::qg_obsvec_add_f90 (const F90ovec & , const F90ovec &)
qg_obsvec_assign_f90()
void qg::qg_obsvec_assign_f90 (const F90ovec & , const F90ovec &)
qg_obsvec_axpy_f90()
void qg::qg_obsvec_axpy_f90 (const F90ovec & , const double & , const F90ovec &)
qg_obsvec_clone_f90()
void qg::qg_obsvec_clone_f90 (const F90ovec & , F90ovec &)
qg_obsvec_delete_f90()
void qg::qg_obsvec_delete_f90 (F90ovec &)
qg_obsvec_div_f90()
void qg::qg_obsvec_div_f90 (const F90ovec & , const F90ovec &)
qg_obsvec_dotprod_f90()
void qg::qg_obsvec_dotprod_f90 (const F90ovec & , const F90ovec & , double &)
qg_obsvec_invert_f90()
void qg::qg_obsvec_invert_f90 (const F90ovec &)
qg_obsvec_minmaxavg_f90()
void qg::qg_obsvec_minmaxavg_f90 (const F90ovec & , double & , double & , double &)
qg_obsvec_mul_f90()
void qg::qg_obsvec_mul_f90 (const F90ovec & , const F90ovec &)
qg_obsvec_mul_scal_f90()
void qg::qg_obsvec_mul_scal_f90 (const F90ovec & , const double &)
qg_obsvec_nobs_f90()
void qg::qg_obsvec_nobs_f90 (const F90ovec & , int &)
qg_obsvec_random_f90()
void qg::qg_obsvec_random_f90 (const F90ovec &)
qg_obsvec_setup_f90()
void qg::qg_obsvec_setup_f90 (F90ovec & , const int & , const int &)
qg_obsvec_sub_f90()
void qg::qg_obsvec_sub_f90 (const F90ovec & , const F90ovec &)
qg_obsvec_zero_f90()
void qg::qg_obsvec_zero_f90 (const F90ovec &)
qg_prepare_integration_ad_f90()
void qg::qg_prepare_integration_ad_f90 (const F90model & , const F90flds &)
qg_prepare_integration_f90()
void qg::qg_prepare_integration_f90 (const F90model & , const F90flds &)
qg_prepare_integration_tl_f90()
void qg::qg_prepare_integration_tl_f90 (const F90model & , const F90flds &)
qg_prop_traj_f90()
void qg::qg_prop_traj_f90 (const F90model & , const F90flds & , F90traj &)
qg_propagate_ad_f90()
void qg::qg_propagate_ad_f90 (const F90model & , const F90flds & , const F90traj &)
qg_propagate_f90()
void qg::qg_propagate_f90 (const F90model & , const F90flds &)
qg_propagate_tl_f90()
void qg::qg_propagate_tl_f90 (const F90model & , const F90flds & , const F90traj &)
qg_setup_f90()
void qg::qg_setup_f90 (const eckit::Configuration *const * , const F90geom & , F90model &)
qg_stream_delete_f90()
void qg::qg_stream_delete_f90 (F90hop &)
qg_stream_equiv_ad_f90()
void qg::qg_stream_equiv_ad_f90 (const F90goms & , const F90ovec & , double &)
qg_stream_equiv_f90()
void qg::qg_stream_equiv_f90 (const F90goms & , const F90ovec & , const double &)
qg_stream_equiv_tl_f90()
void qg::qg_stream_equiv_tl_f90 (const F90goms & , const F90ovec & , const double &)
qg_stream_setup_f90()
void qg::qg_stream_setup_f90 (F90hop & , const eckit::Configuration *const *)
qg_traj_minmaxrms_f90()
void qg::qg_traj_minmaxrms_f90 (const F90traj & , double &)
qg_var_clone_f90()
void qg::qg_var_clone_f90 (const F90vars & , F90vars &)
qg_var_create_f90()
void qg::qg_var_create_f90 (F90vars & , const eckit::Configuration *const *)
qg_var_delete_f90()
void qg::qg_var_delete_f90 (F90vars &)
qg_var_info_f90()
void qg::qg_var_info_f90 (const F90vars & , int & , int &)
qg_wind_bias_equiv_ad_f90()
void qg::qg_wind_bias_equiv_ad_f90 (const F90goms & , const F90ovec & , double &)
qg_wind_bias_equiv_f90()
void qg::qg_wind_bias_equiv_f90 (const F90goms & , F90ovec & , const double &)
qg_wind_bias_equiv_tl_f90()
void qg::qg_wind_bias_equiv_tl_f90 (const F90goms & , const F90ovec & , const double &)
qg_wind_delete_f90()
void qg::qg_wind_delete_f90 (F90hop &)
qg_wind_equiv_ad_f90()
void qg::qg_wind_equiv_ad_f90 (const F90goms & , const F90ovec & , double &)
qg_wind_equiv_f90()
void qg::qg_wind_equiv_f90 (const F90goms & , F90ovec & , const double &)
qg_wind_equiv_tl_f90()
void qg::qg_wind_equiv_tl_f90 (const F90goms & , const F90ovec & , const double &)
qg_wind_setup_f90()
void qg::qg_wind_setup_f90 (F90hop & , const eckit::Configuration *const *)
qg_wipe_traj_f90()
void qg::qg_wipe_traj_f90 (F90traj &)
qg_wspeed_delete_f90()
void qg::qg_wspeed_delete_f90 (F90hop &)
qg_wspeed_equiv_ad_f90()
void qg::qg_wspeed_equiv_ad_f90 (const F90goms & , const F90ovec & , const F90goms & , double &)
qg_wspeed_equiv_tl_f90()
void qg::qg_wspeed_equiv_tl_f90 (const F90goms & , const F90ovec & , const F90goms & , const double &)
qg_wspeed_eqv_f90()
void qg::qg_wspeed_eqv_f90 (const F90goms & , const F90ovec & , const double &)
qg_wspeed_gettraj_f90()
void qg::qg_wspeed_gettraj_f90 (const F90hop & , const int & , F90goms &)
qg_wspeed_settraj_f90()
void qg::qg_wspeed_settraj_f90 (const F90goms & , const F90goms &)
qg_wspeed_setup_f90()
void qg::qg_wspeed_setup_f90 (F90hop & , const eckit::Configuration *const *)
random_f()
void qg::random_f (const int & nn, double * xx)
Definition at line 15 of file random_f.cc.
{
   static std::mt19937 generator(7);
   static std::normal_distribution<double> distribution(0.0, 1.0);
   for (int jj = 0; jj < nn; ++jj) xx[jj] = distribution(generator);
 }
Variable Documentation
makeObsBiasCovariance_
oops::ObsAuxCovarianceMaker<QgTraits, ObsBiasCovariance> qg::makeObsBiasCovariance_("ObsBiasQG") static
makeObsBiasCtlVec_
oops::ObsAuxCtlVecMaker<QgTraits, ObsBiasCtlVec> qg::makeObsBiasCtlVec_("ObsBiasQG") static
makerObsErrStreamIFS_ [1/3]
oops::ObsErrorMaker<QgTraits, ObsErrStreamQG> qg::makerObsErrStreamIFS_("StreamObsError") static
makerObsErrStreamIFS_ [2/3]
oops::ObsErrorMaker<QgTraits, ObsErrWindQG> qg::makerObsErrStreamIFS_("WindObsError") static
makerObsErrStreamIFS_ [3/3]
oops::ObsErrorMaker<QgTraits, ObsErrWSpeedQG> qg::makerObsErrStreamIFS_("WSpeedObsError") static
makerQGIdTLM_
oops::LinearModelMaker<QgTraits, TlmIdQG> qg::makerQGIdTLM_("QgIdTLM") static
makerQGTLM_
oops::LinearModelMaker<QgTraits, TlmQG> qg::makerQGTLM_("QgTLM") static
makerStream_
oops::ObsOperatorMaker<QgTraits, ObsStreamQG> qg::makerStream_("Stream") static
makerStreamTL_
oops::LinearObsOpMaker<QgTraits, ObsStreamTLAD> qg::makerStreamTL_("Stream") static
makerWind_
oops::ObsOperatorMaker<QgTraits, ObsWindQG> qg::makerWind_("Wind") static
makerWindTL_
oops::LinearObsOpMaker<QgTraits, ObsWindTLAD> qg::makerWindTL_("Wind") static
makerWSpeed_
oops::ObsOperatorMaker<QgTraits, ObsWSpeedQG> qg::makerWSpeed_("WSpeed") static
makerWSpeedTL_
oops::LinearObsOpMaker<QgTraits, ObsWSpeedTLAD> qg::makerWSpeedTL_("WSpeed") static
makesObsBias_
oops::ObsAuxControlMaker<QgTraits, ObsBias> qg::makesObsBias_("ObsBiasQG") static
makesObsBiasIncrement_
oops::ObsAuxIncrementMaker<QgTraits, ObsBiasIncrement> qg::makesObsBiasIncrement_("ObsBiasQG") static