OOPS Documentation: qg_constants Module Reference
qg_constants Module Reference
Constants for the QG model.
Variables
real(kind=kind_real), parameter domain_zonal =12e6_kind_real
model domain (m) in zonal direction
real(kind=kind_real), parameter domain_meridional =6.3e6_kind_real
meridional model domain (m)
real(kind=kind_real), parameter scale_length = 1e6_kind_real
horizontal length scale (m)
real(kind=kind_real), parameter ubar = 10.0_kind_real
typical verlocity (m/s)
real(kind=kind_real), parameter ubar1 = 40.0_kind_real
mean zonal wind in the top layer (m/s)
real(kind=kind_real), parameter ubar2 = 10.0_kind_real
mean zonal wind in the bottom layer (m/s)
real(kind=kind_real), parameter dlogtheta = 0.1_kind_real
difference in log(pot. T) across boundary
real(kind=kind_real), parameter g =10.0_kind_real
gravity (m^2 s^{-2})
real(kind=kind_real), parameter f0 = 1e-4_kind_real
Coriolis parameter at southern boundary.
real(kind=kind_real), parameter bet0 = 1.5e-11_kind_real
Meridional gradient of f (s^{-1} m^{-1})
real(kind=kind_real), parameter horog = 2000.0_kind_real
height of orography (m)
real(kind=kind_real), parameter worog = 1000e3_kind_real
e-folding width of orography (m)
real(kind=kind_real), parameter u1 = ubar1/ubar
real(kind=kind_real), parameter u2 = ubar2/ubar
real(kind=kind_real), parameter bet = bet0*scale_length*scale_length/ubar
real(kind=kind_real), parameter rossby_number = ubar/(f0*scale_length)
Detailed Description
Constants for the QG model.
Variable Documentation
bet
real(kind=kind_real), parameter qg_constants::bet = bet0*scale_length*scale_length/ubar
Definition at line 35 of file qg_constants.f90.
 real(kind=kind_real),parameter :: bet = bet0*scale_length*scale_length/ubar
Referenced by invent_state(), and propagate().
bet0
real(kind=kind_real), parameter qg_constants::bet0 = 1.5e-11_kind_real
Meridional gradient of f (s^{-1} m^{-1})
Definition at line 27 of file qg_constants.f90.
 real(kind=kind_real),parameter :: bet0 = 1.5e-11_kind_real
dlogtheta
real(kind=kind_real), parameter qg_constants::dlogtheta = 0.1_kind_real
difference in log(pot. T) across boundary
Definition at line 24 of file qg_constants.f90.
 real(kind=kind_real),parameter :: dlogtheta = 0.1_kind_real
Referenced by invent_state().
domain_meridional
real(kind=kind_real), parameter qg_constants::domain_meridional =6.3e6_kind_real
meridional model domain (m)
Definition at line 19 of file qg_constants.f90.
 real(kind=kind_real),parameter :: domain_meridional=6.3e6_kind_real
Referenced by invent_state().
domain_zonal
real(kind=kind_real), parameter qg_constants::domain_zonal =12e6_kind_real
model domain (m) in zonal direction
Definition at line 18 of file qg_constants.f90.
 real(kind=kind_real),parameter :: domain_zonal=12e6_kind_real
Referenced by invent_state().
f0
real(kind=kind_real), parameter qg_constants::f0 = 1e-4_kind_real
Coriolis parameter at southern boundary.
Definition at line 26 of file qg_constants.f90.
 real(kind=kind_real),parameter :: f0 = 1e-4_kind_real
Referenced by invent_state().
g
real(kind=kind_real), parameter qg_constants::g =10.0_kind_real
gravity (m^2 s^{-2})
Definition at line 25 of file qg_constants.f90.
 real(kind=kind_real),parameter :: g=10.0_kind_real
Referenced by invent_state().
horog
real(kind=kind_real), parameter qg_constants::horog = 2000.0_kind_real
height of orography (m)
Definition at line 28 of file qg_constants.f90.
 real(kind=kind_real),parameter :: horog = 2000.0_kind_real
Referenced by invent_state().
rossby_number
real(kind=kind_real), parameter qg_constants::rossby_number = ubar/(f0*scale_length)
Definition at line 36 of file qg_constants.f90.
 real(kind=kind_real),parameter :: rossby_number = ubar/(f0*scale_length)
Referenced by invent_state().
scale_length
real(kind=kind_real), parameter qg_constants::scale_length = 1e6_kind_real
horizontal length scale (m)
Definition at line 20 of file qg_constants.f90.
 real(kind=kind_real),parameter :: scale_length = 1e6_kind_real
Referenced by invent_state().
u1
real(kind=kind_real), parameter qg_constants::u1 = ubar1/ubar
Definition at line 33 of file qg_constants.f90.
 real(kind=kind_real),parameter :: u1 = ubar1/ubar
Referenced by invent_state().
u2
real(kind=kind_real), parameter qg_constants::u2 = ubar2/ubar
Definition at line 34 of file qg_constants.f90.
 real(kind=kind_real),parameter :: u2 = ubar2/ubar
Referenced by invent_state().
ubar
real(kind=kind_real), parameter qg_constants::ubar = 10.0_kind_real
typical verlocity (m/s)
Definition at line 21 of file qg_constants.f90.
 real(kind=kind_real),parameter :: ubar = 10.0_kind_real
ubar1
real(kind=kind_real), parameter qg_constants::ubar1 = 40.0_kind_real
mean zonal wind in the top layer (m/s)
Definition at line 22 of file qg_constants.f90.
 real(kind=kind_real),parameter :: ubar1 = 40.0_kind_real
ubar2
real(kind=kind_real), parameter qg_constants::ubar2 = 10.0_kind_real
mean zonal wind in the bottom layer (m/s)
Definition at line 23 of file qg_constants.f90.
 real(kind=kind_real),parameter :: ubar2 = 10.0_kind_real
worog
real(kind=kind_real), parameter qg_constants::worog = 1000e3_kind_real
e-folding width of orography (m)
Definition at line 29 of file qg_constants.f90.
 real(kind=kind_real),parameter :: worog = 1000e3_kind_real
Referenced by invent_state().