OOPS Documentation: util Namespace Reference
util Namespace Reference
Wraps printing out of the result of an adjoint test.
Classes
class ConfigTestData
class DateTime
This class represents time, and provides methods to manipulate time.
class Duration
This class represents time durations.
class Logbook
Logbook.
class LogbookHelper
LogbookHelper.
class LogbookWriter
LogbookWriter.
class MPIThreadPool
class MPIWrapper
The singleton MPIWrapper handles MPI multiple communicators.
class ObjectCounter
class ObjectCountHelper
class Printable
class PrintAdjTest
class Restart
Restart class.
class RestartHelper
RestartHelper class.
class threaded_bcast
class threaded_send_recv
class Timer
class TimerHelper
Functions
void abor1_cpp (const std::string &cderror)
Print an error message and abort execution.
void abor1_cpp (const std::string &cderror, const std::string &file, int line)
void abor1_cpp_ (const char cderror[])
const eckit::Configuration * config_get_testdata_f ()
bool config_element_exists_f (const eckit::Configuration &d, const char str[])
int config_get_data_as_int_f (const eckit::Configuration &d, const char str[])
double config_get_data_as_double_f (const eckit::Configuration &d, const char str[])
int config_get_data_length_f (const eckit::Configuration &d, const char str[])
void config_get_data_f (const eckit::Configuration &d, const char str[], char output[])
int config_get_data_dimension_f (const eckit::Configuration &d, const char str[])
int config_get_data_element_length_f (const eckit::Configuration &d, const char str[], const int &index)
void config_get_data_element_f (const eckit::Configuration &d, const char str[], const int &index, char output[])
void config_get_double_vector_f (const eckit::Configuration &d, const char str[], const std::size_t &length, double *vec)
void config_get_float_vector_f (const eckit::Configuration &d, const char str[], const std::size_t &length, float *vec)
void config_get_int_vector_f (const eckit::Configuration &d, const char str[], const std::size_t &length, std::int32_t *vec)
std::ostream & operator<< (std::ostream &output, const DateTime &t)
std::istream & operator>> (std::istream &input, DateTime &t)
util::DateTime * datetime_construct_f (const char str[])
void datetime_set_f (const char str[], util::DateTime *dd)
void datetime_destruct_f (util::DateTime *dd)
void datetime_string_f (const util::DateTime *dd, char cstr[21])
void datetime_getints_f (const util::DateTime *dt, int64_t &date, int &time)
void datetime_setints_f (util::DateTime *dt, const int64_t &date, const int &time)
int64_t datetime_diff_f (const util::DateTime *dt1, const util::DateTime *dt2)
void datetime_update_f (util::DateTime *tt, const int64_t &dt)
Duration operator+ (const Duration &d1, const Duration &d2)
Duration operator- (const Duration &d1, const Duration &d2)
Duration operator* (const int kk, const Duration &dd)
Duration operator* (const Duration &dd, const int kk)
Duration operator/ (const Duration &dd, const int kk)
std::ostream & operator<< (std::ostream &output, const Duration &d)
std::istream & operator>> (std::istream &input, Duration &d)
util::Duration * duration_construct_f (const char str[])
void duration_destruct_f (util::Duration *dur)
int64_t duration_str_int_f (const char str[])
int64_t duration_int_f (const util::Duration *dt)
void duration_int_str_f (const int64_t &dt, char str[21])
template<class T >
std::string full_precision (const T &zz)
Formatting numerical types with full precision for output.
template<class T >
std::string full_precision (const std::vector< T > &zz)
void ftn_serialize (eckit::Stream &s, int nb_datas, void *data)
void ftn_deserialize (eckit::Stream &s, int nb_datas, void *data)
float missing_value_flt_f ()
double missing_value_dbl_f ()
const float & missingValue (const float &)
const double & missingValue (const double &)
const int16_t & missingValue (const int16_t &)
const int32_t & missingValue (const int32_t &)
const int64_t & missingValue (const int64_t &)
const DateTime & missingValue (const DateTime &)
void random_uniform_float_f (const std::size_t &, const float &, const float &, std::int32_t &, float *)
void random_uniform_double_f (const std::size_t &, const double &, const double &, std::int32_t &, double *)
void random_uniform_int_f (const std::size_t &, const std::int32_t &, const std::int32_t &, std::int32_t &, std::int32_t *)
void random_uniform_long_f (const std::size_t &, const std::int64_t &, const std::int64_t &, std::int32_t &, std::int64_t *)
void random_normal_float_f (const std::size_t &, const float &, const float &, std::int32_t &, float *)
void random_normal_double_f (const std::size_t &, const double &, const double &, std::int32_t &, double *)
Detailed Description
Wraps printing out of the result of an adjoint test.
The namespace for utilities used by oops (Config, Logger, DateTime, etc.)
Function Documentation
abor1_cpp() [1/2]
void util::abor1_cpp (const std::string & cderror)
Print an error message and abort execution.
If called with a single string argument, the string is printed and execution aborts.
If called with 3 arguments, the first is the error message, the second should be FILE and the third should be LINE. You should not call abor1_cpp directly. Use the ASSERT or ABORT macro.
Definition at line 21 of file abor1_cpp.cc.
{
   Log::error() << cderror << std::endl;
   Log::error().flush();
   exit(EXIT_FAILURE);
 }
Referenced by abor1_cpp_().
abor1_cpp() [2/2]
void util::abor1_cpp (const std::string & cderror, const std::string & file, int line)
Definition at line 27 of file abor1_cpp.cc.
{
   Log::error() << "ABORT: " << cderror << std::endl;
   Log::error() << "       in file '" << file << "', line " << line << std::endl;
   Log::error().flush();
   exit(EXIT_FAILURE);
 }
abor1_cpp_()
void util::abor1_cpp_ (const char cderror[])
Definition at line 34 of file abor1_cpp.cc.
{
   std::string s(cderror);
   util::abor1_cpp(s);
 }
References abor1_cpp().
config_element_exists_f()
bool util::config_element_exists_f (const eckit::Configuration & d, const char str[])
Definition at line 72 of file config_f.cc.
{
   const std::string s(str);
   return d.has(s);
 }
config_get_data_as_double_f()
double util::config_get_data_as_double_f (const eckit::Configuration & d, const char str[])
Definition at line 82 of file config_f.cc.
{
   const std::string s(str);
   return d.getDouble(s);
 }
config_get_data_as_int_f()
int util::config_get_data_as_int_f (const eckit::Configuration & d, const char str[])
Definition at line 77 of file config_f.cc.
{
   const std::string s(str);
   return d.getInt(s);
 }
config_get_data_dimension_f()
int util::config_get_data_dimension_f (const eckit::Configuration & d, const char str[])
Definition at line 102 of file config_f.cc.
{
   const std::string s(str);
   const std::vector<std::string> data(d.getStringVector(s));
   return data.size();
 }
config_get_data_element_f()
void util::config_get_data_element_f (const eckit::Configuration & d, const char str[], const int & index, char output[])
Definition at line 116 of file config_f.cc.
{
   const std::string s(str);
   const std::vector<std::string> data(d.getStringVector(s));
   size_t lendata = data[index - 1].size();
   strncpy(output, data[index - 1].c_str(), lendata);
 }
config_get_data_element_length_f()
int util::config_get_data_element_length_f (const eckit::Configuration & d, const char str[], const int & index)
Definition at line 109 of file config_f.cc.
{
   const std::string s(str);
   const std::vector<std::string> data(d.getStringVector(s));
   return data[index - 1].length();
 }
config_get_data_f()
void util::config_get_data_f (const eckit::Configuration & d, const char str[], char output[])
Definition at line 94 of file config_f.cc.
{
   const std::string s(str);
   const std::string data(d.getString(s));
   size_t lendata = data.size();
   strncpy(output, data.c_str(), lendata);
 }
config_get_data_length_f()
int util::config_get_data_length_f (const eckit::Configuration & d, const char str[])
Definition at line 88 of file config_f.cc.
{
   const std::string s(str);
   const std::string data(d.getString(s));
   return data.length();
 }
config_get_double_vector_f()
void util::config_get_double_vector_f (const eckit::Configuration & d, const char str[], const std::size_t & length, double * vec)
Vector retrival from config file
Warning
It is the responsibility of the calling Fortran routine to allocate these
Definition at line 132 of file config_f.cc.
{
   const std::string s(str);
   std::vector<double> x = d.getDoubleVector(s);
   ASSERT(x.size() == length);
   for (std::size_t jj = 0; jj < length; ++jj) vec[jj] = x[jj];
 }
config_get_float_vector_f()
void util::config_get_float_vector_f (const eckit::Configuration & d, const char str[], const std::size_t & length, float * vec)
Definition at line 140 of file config_f.cc.
{
   const std::string s(str);
   std::vector<float> x = d.getFloatVector(s);
   ASSERT(x.size() == length);
   for (std::size_t jj = 0; jj < length; ++jj) vec[jj] = x[jj];
 }
config_get_int_vector_f()
void util::config_get_int_vector_f (const eckit::Configuration & d, const char str[], const std::size_t & length, std::int32_t * vec)
Definition at line 148 of file config_f.cc.
{
   const std::string s(str);
   std::vector<int> x = d.getIntVector(s);
   ASSERT(x.size() == length);
   for (std::size_t jj = 0; jj < length; ++jj) vec[jj] = x[jj];
 }
config_get_testdata_f()
const eckit::Configuration * util::config_get_testdata_f ()
Definition at line 67 of file config_f.cc.
{
   const eckit::Configuration* cfg = &ConfigTestData::getConfig();
   return cfg;
 }
datetime_construct_f()
util::DateTime * util::datetime_construct_f (const char str[])
Definition at line 29 of file datetime_f.cc.
{
   std::string s(str);
   return new util::DateTime(s);
 }
datetime_destruct_f()
void util::datetime_destruct_f (util::DateTime * dd)
Definition at line 44 of file datetime_f.cc.
 { delete dd; }
datetime_diff_f()
int64_t util::datetime_diff_f (const util::DateTime * dt1, const util::DateTime * dt2)
Definition at line 79 of file datetime_f.cc.
{
   const util::Duration dd = *dt1 - *dt2;
   return dd.toSeconds();
 }
datetime_getints_f()
void util::datetime_getints_f (const util::DateTime * dt, int64_t & date, int & time)
Definition at line 57 of file datetime_f.cc.
{
   int yy, mm, dd, hh, nn, ss;
   dt->toYYYYMMDDhhmmss(yy, mm, dd, hh, nn, ss);
   date = 10000 * yy + 100 * mm + dd;
   time = datefunctions::hmsToSeconds(hh, nn, ss);
 }
datetime_set_f()
void util::datetime_set_f (const char str[], util::DateTime * dd)
Definition at line 36 of file datetime_f.cc.
{
   std::string s(str);
   const util::DateTime dtmp(s);
   *dd = dtmp;
 }
datetime_setints_f()
void util::datetime_setints_f (util::DateTime * dt, const int64_t & date, const int & time)
Definition at line 66 of file datetime_f.cc.
{
   int yy, mm, dd, hh, nn, ss, ii;
   yy = date / 10000;
   ii = date % 10000;
   mm = ii / 100;
   dd = ii % 100;
   datefunctions::secondToHms(time, hh, nn, ss);
   *dt = util::DateTime(yy, mm, dd, hh, nn, ss);
 }
datetime_string_f()
void util::datetime_string_f (const util::DateTime * dd, char cstr[21])
Definition at line 48 of file datetime_f.cc.
{
   const std::string ss(dd->toString());
   ASSERT(ss.length() < 21);
   //  snprintf(cstr, sizeof(cstr), ss.c_str());
   std::strcpy(cstr, ss.c_str());
 }
datetime_update_f()
void util::datetime_update_f (util::DateTime * tt, const int64_t & dt)
Definition at line 86 of file datetime_f.cc.
{
   const util::Duration dd(dt);
   *tt += dd;
 }
duration_construct_f()
util::Duration * util::duration_construct_f (const char str[])
Definition at line 23 of file duration_f.cc.
{
   std::string s(str);
   return new util::Duration(s);
 }
duration_destruct_f()
void util::duration_destruct_f (util::Duration * dur)
Definition at line 30 of file duration_f.cc.
 { delete dur; }
duration_int_f()
int64_t util::duration_int_f (const util::Duration * dt)
Definition at line 42 of file duration_f.cc.
 { return dt->toSeconds(); }
duration_int_str_f()
void util::duration_int_str_f (const int64_t & dt, char str[21])
Definition at line 46 of file duration_f.cc.
{
   util::Duration d(dt);
   std::string s(d.toString());
   ASSERT(s.length() < 21);
   //  snprintf(str, sizeof(str), s.c_str());
   std::strcpy(str, s.c_str());
 }
duration_str_int_f()
int64_t util::duration_str_int_f (const char str[])
Definition at line 34 of file duration_f.cc.
{
   std::string s(str);
   util::Duration d(s);
   return d.toSeconds();
 }
ftn_deserialize()
void util::ftn_deserialize (eckit::Stream & s, int nb_datas, void * data)
Definition at line 27 of file ftn_serializer.cc.
{
   long data_size = nb_datas;
   s.readBlob(data, data_size);
 }
ftn_serialize()
void util::ftn_serialize (eckit::Stream & s, int nb_datas, void * data)
Definition at line 20 of file ftn_serializer.cc.
{
   long data_size = nb_datas;
   s.writeBlob(data, data_size);
 }
full_precision() [1/2]
template<class T > std::string util::full_precision (const std::vector< T > & zz)
Definition at line 35 of file formats.h.
{
   std::stringstream sss;
   sss << std::setprecision(std::numeric_limits<T>::max_digits10) << zz;
   return sss.str();
 }
full_precision() [2/2]
template<class T > std::string util::full_precision (const T & zz)
Formatting numerical types with full precision for output.
Definition at line 26 of file formats.h.
{
   std::stringstream sss;
   sss << std::setprecision(std::numeric_limits<T>::max_digits10) << zz;
   return sss.str();
 }
Referenced by oops::SQRTBPCGMinimizer< MODEL >::calcQuadCost(), oops::DRMinimizer< MODEL >::checkpoint(), oops::SpectralSqrtLMP< MODEL >::checkpoint(), oops::SQRTMinimizer< MODEL >::checkpointAux(), oops::SQRTMinimizer< MODEL >::checkpointDv0(), oops::SQRTMinimizer< MODEL >::checkpointDvh(), oops::SQRTMinimizer< MODEL >::checkpointGradJb(), oops::FGMRES(), oops::FullGMRES(), oops::GMRESR(), oops::IPCG(), oops::MINRES(), oops::PCG(), oops::PLanczos(), oops::SpectralSqrtLMP< MODEL >::postprocess(), oops::SQRTPCGMinimizer< MODEL >::printQuadCost(), oops::SQRTBPCGMinimizer< MODEL >::printQuadCost(), oops::SQRTBPFOMMinimizer< MODEL >::printQuadCost(), oops::SQRTBPLanczosMinimizer< MODEL >::printQuadCost(), oops::SQRTPLanczosMinimizer< MODEL >::printQuadCost(), oops::SQRTBPFOMMinimizer< MODEL >::printRitzInformation(), oops::SQRTBPLanczosMinimizer< MODEL >::printRitzInformation(), oops::SQRTPLanczosMinimizer< MODEL >::printRitzInformation(), oops::DRMinimizer< MODEL >::restart(), oops::SpectralSqrtLMP< MODEL >::restart(), oops::SQRTMinimizer< MODEL >::restartAux(), oops::SQRTMinimizer< MODEL >::restartDv0(), oops::SQRTMinimizer< MODEL >::restartDvh(), oops::SQRTMinimizer< MODEL >::restartGradJb(), oops::SQRTBPFOMMinimizer< MODEL >::solve(), oops::SQRTBPLanczosMinimizer< MODEL >::solve(), oops::SQRTPCGMinimizer< MODEL >::solve(), oops::SQRTBPCGMinimizer< MODEL >::solve(), oops::SQRTPLanczosMinimizer< MODEL >::solve(), oops::DRPFOMMinimizer< MODEL >::solve(), oops::RPCGMinimizer< MODEL >::solve(), oops::RPLanczosMinimizer< MODEL >::solve(), oops::DRPLanczosMinimizer< MODEL >::solve(), oops::DRGMRESRMinimizer< MODEL >::solve(), oops::DRIPCGMinimizer< MODEL >::solve(), oops::DRPCGMinimizer< MODEL >::solve(), oops::Minimizer< MODEL >::tlmTaylorTest(), oops::SpectralSqrtLMP< MODEL >::update(), oops::SQRTMinimizer< MODEL >::updateJbCostFunction(), and oops::SQRTMinimizer< MODEL >::warmStartAux().
missing_value_dbl_f()
double util::missing_value_dbl_f ()
Definition at line 20 of file missing_values_f.cc.
{
   const double miss = util::missingValue(miss);
   return miss;
 }
References missingValue().
missing_value_flt_f()
float util::missing_value_flt_f ()
Definition at line 15 of file missing_values_f.cc.
{
   const float miss = util::missingValue(miss);
   return miss;
 }
References missingValue().
missingValue() [1/6]
const DateTime & util::missingValue (const DateTime &)
Definition at line 45 of file missingValues.cc.
{
   static const DateTime dtmiss(9996, 2, 29, 23, 58, 57);
   return dtmiss;
 }
missingValue() [2/6]
const double & util::missingValue (const double &)
Definition at line 24 of file missingValues.cc.
{
   static const float fmiss = std::numeric_limits<float>::lowest() * 0.99;
   static const double dmiss = static_cast<double>(fmiss);
   return dmiss;
 }
missingValue() [3/6]
const float & util::missingValue (const float &)
Definition at line 19 of file missingValues.cc.
{
   static const float fmiss = std::numeric_limits<float>::lowest() * 0.99;
   return fmiss;
 }
Referenced by missing_value_dbl_f(), and missing_value_flt_f().
missingValue() [4/6]
const int16_t & util::missingValue (const int16_t &)
Definition at line 30 of file missingValues.cc.
{
   static const int16_t imiss = std::numeric_limits<int16_t>::lowest() + 3;
   return imiss;
 }
missingValue() [5/6]
const int32_t & util::missingValue (const int32_t &)
Definition at line 35 of file missingValues.cc.
{
   static const int32_t imiss = std::numeric_limits<int32_t>::lowest() + 5;
   return imiss;
 }
missingValue() [6/6]
const int64_t & util::missingValue (const int64_t &)
Definition at line 40 of file missingValues.cc.
{
   static const int64_t imiss = std::numeric_limits<int64_t>::lowest() + 7;
   return imiss;
 }
operator*() [1/2]
Duration util::operator* (const Duration & dd, const int kk)
Definition at line 314 of file Duration.cc.
{
   Duration res(dd);
   res *= kk;
   return res;
 }
operator*() [2/2]
Duration util::operator* (const int kk, const Duration & dd)
Definition at line 306 of file Duration.cc.
{
   Duration res(dd);
   res *= kk;
   return res;
 }
operator+()
Duration util::operator+ (const Duration & d1, const Duration & d2)
Definition at line 290 of file Duration.cc.
{
   Duration sum(d1);
   sum += d2;
   return sum;
 }
operator-()
Duration util::operator- (const Duration & d1, const Duration & d2)
Definition at line 298 of file Duration.cc.
{
   Duration sum(d1);
   sum -= d2;
   return sum;
 }
operator/()
Duration util::operator/ (const Duration & dd, const int kk)
Definition at line 322 of file Duration.cc.
{
   Duration res(dd);
   res /= kk;
   return res;
 }
operator<<() [1/2]
std::ostream& util::operator<< (std::ostream & output, const DateTime & t) inline
Definition at line 106 of file DateTime.h.
{
   output << t.toString();
   return output;
 }
operator<<() [2/2]
std::ostream& util::operator<< (std::ostream & output, const Duration & d) inline
Definition at line 120 of file Duration.h.
{
   output << d.toString();
   return output;
 }
operator>>() [1/2]
std::istream& util::operator>> (std::istream & input, DateTime & t) inline
Definition at line 113 of file DateTime.h.
{
   std::string time_str;
   input >> time_str;
   t.set(time_str);
   return input;
 }
operator>>() [2/2]
std::istream& util::operator>> (std::istream & input, Duration & d) inline
Definition at line 127 of file Duration.h.
{
   std::string duration;
   input >> duration;
   d.set(duration);
   return input;
 }
random_normal_double_f()
void util::random_normal_double_f (const std::size_t & , const double & , const double & , std::int32_t & , double *)
random_normal_float_f()
void util::random_normal_float_f (const std::size_t & , const float & , const float & , std::int32_t & , float *)
random_uniform_double_f()
void util::random_uniform_double_f (const std::size_t & , const double & , const double & , std::int32_t & , double *)
random_uniform_float_f()
void util::random_uniform_float_f (const std::size_t & , const float & , const float & , std::int32_t & , float *)
These functions provide a Fortran-callable interface to the C++ random number generators
random_uniform_int_f()
void util::random_uniform_int_f (const std::size_t & , const std::int32_t & , const std::int32_t & , std::int32_t & , std::int32_t *)
random_uniform_long_f()
void util::random_uniform_long_f (const std::size_t & , const std::int64_t & , const std::int64_t & , std::int32_t & , std::int64_t *)