OOPS Documentation: oops Namespace Reference
oops Namespace Reference
The namespace for the main oops code.
Classes
class Accumulator
class Advector
Advection operator.
class AdvectorHandler
Advector handler class.
class Application
class AssimEnsemble
class BMatrix
The \(B \) matrix.
class ControlIncrement
Control Increment.
class ControlObsVector
class ControlVariable
Control Variable.
class ControlVector
Control Vector.
class CostFactory
Cost Function Factory.
class CostFct3DVar
3D-Var Cost Function
class CostFct4DEnsVar
4D-Ens-Var Cost Function
class CostFct4DEnVar
4D-Ens-Var Cost Function
class CostFct4DVar
Strong Constraint 4D-Var Cost Function.
class CostFct4DVarHyb4D
4DVarHyb4D Cost Function in the ARPEGE
class CostFct4DVarMF
4D-Var Cost Function in the ARPEGE
class CostFct4DVarTrajHR
4D-Var Cost Function in the ARPEGE
class CostFctWeak
Weak Constraint 4D-Var Cost Function.
class CostFunction
Abstract base class for a cost function.
class CostJb3D
CostJb3D encapsulates the state component of the Jb term of the cost function for a 3 dimensional background (3/4D-Var).
class CostJb4D
4D Jb Cost Function
class CostJbJq
Jb + Jq Cost Function.
class CostJbState
Pure abstract base class for the Jb term state component.
class CostJbTotal
Jb component of the cost function.
class CostJcDFI
Jc DFI Cost Function.
class CostJo
\(J_o \) term of the cost function
class CostMaker
class CostTermBase
Abstract base class for the terms of the cost function (e.g. Jo, Jc).
class Covar4DMaker
class Covariance4DFactory
Covariance Factory.
class CovarianceFactory
Covariance Factory.
class CovarMaker
class Departures
Difference between two observation vectors.
class DFIProcessor
Compute time average of states or increments during model run.
class DiagonalMatrix
Diagonal matrix.
class DolphChebyshev
class DRGMRESRMinimizer
Derber-Rosati GMRESR Minimizer.
class DRIPCGMinimizer
Derber-Rosati IPCG Minimizer.
class DRMinimizer
DR (Derber and Rosati) Minimizers.
class DRPCGMinimizer
DRPCG Minimizer.
class DRPFOMMinimizer
DRPFOM Minimizer.
class DRPLanczosMinimizer
DRPLanczos Minimizer.
class DualConfigForecast
class DualConfigGeometry
class DualConfigModel
Encapsulates the nonlinear dual-config forecast model.
class DualConfigModelAuxControl
class DualConfigPostProcessor
Control model post processing.
class DualConfigState
Encapsulates the model state.
class DualConfigVariables
class DualMinimizer
Dual Minimizer.
class DualResForecast
class DualVector
Container of dual space vectors for all terms of the cost function.
class Ensemble
Ensemble.
class EnsembleCovariance
Generic ensemble based model space error covariance.
class EnsembleCovariance4D
Generic ensemble based model space error covariance.
class EnsembleCovariance4DDistributed
Generic ensemble based model space error covariance.
class EnsembleCovariance4DScaleDependent
Wraps the model space error covariance.
class EnsembleCovariance4DWithChangeOfVariable
class EnsembleCovsInterpol
Generic ensemble based model space error covariance.
class EnsembleCovsInterpol4D
Generic ensemble based model space error covariance.
class EnsemblesCollection
class EnsForecast
class ErrorCovariance
Wrapper for model space error covariances.
class ExternalDFI
class FGMRESMinimizer
FGMRES Minimizer.
class Forecast
class GenEnsPertB
class GeneralizedDepartures
Abstract base class for quantities.
class GenericMatrix
Base class generic matrices.
class GenericMatrixFactory
GenericMatrixFactory Factory.
class GenericMatrixMaker
class Geometry
Wrapper for geometry.
class GeoVaLs
Wrapper for geophysical values at observation locations.
class GMRESRMinimizer
GMRESR Minimizer.
class HBHtMatrix
The \(H B H^T \) matrix.
class HessianMatrix
The Hessian matrix: \(B^{-1} + H^T R^{-1} H \).
class HighToLow
Compute time average of states or increments during model run.
class HMatrix
The \(H \) matrix.
class HofX
class HorizScaleDecomposition
class HtMatrix
The \(H^T \) matrix.
class HtRinvHdxFG
Calculate \(H^T R^{-1} H dx_FG \).
class HtRinvHMatrix
The \(H^T R^{-1} H \) matrix.
class HybridCovariance
Generic hybrid static-ensemble model space error covariance.
class HybridCovariance4D
Generic hybrid static-ensemble model space error covariance.
class HybridCovarianceGeneralCoeff
Generic hybrid static-ensemble model space error covariance.
class IdentityMatrix
Identity matrix.
class IncrCtlVec
IncrCtlVec Class.
class IncrCtlVec4D
IncrCtlVec4D class.
class Increment
Encapsulates model increment.
class Increment4D
Increment4D class.
class IncrementalAssimilation
IncrementalAssimilation implements variational algorithms.
class IncrEnsCtlVec
IncrEnsCtlVec class.
class IncrModCtlVec
IncrModCtlVec class.
class Interpolator
class IPCGMinimizer
IPCG Minimizer.
class JbMatrix
The \(Jb \) matrix.
class JcCovar
JcCovar class.
class JcCovarBase
Base class for encapsulation of the Jc covariances.
class JcCovarFactory
JcCovarFactory Factory.
class JcCovarMaker
class JqTerm
class JqTermAD
class JqTermTL
class LBGMRESRMinimizer
LBGMRESR Minimizer.
class LBHessianMatrix
The Hessian matrix: \(I + B H^T R^{-1} H \).
class LBMinimizer
LB (Left B-preconditioned) Minimizers.
class LibOOPS
class LinearModel
Encapsulates the linear forecast model.
class LinearModelBase
Base class for encapsulation of the linear forecast model.
class LinearModelFactory
LinearModelFactory Factory.
class LinearModelId
Encapsulates the linear forecast model.
class LinearModelMaker
class LinearObsOperator
Encapsulates the linear observation operator.
class LinearObsOperators
A container class storing a vector of LinearObsOpertor objects.
class LinearObsOperBase
Base class for the linear observation operator.
class LinearObsOperFactory
Obs Operator Factory.
class LinearObsOpMaker
class Localization
class Locations
Encapsulates the observation locations.
struct Log
class MakeObs
class MinFactory
Minimizer Factory.
class Minimizer
Abstract base class for minimizers.
class MinMaker
class MINRESMinimizer
MINRES Minimizer.
class MMatrix
The \(M \) matrix.
class Model
Encapsulates the nonlinear forecast model.
class ModelAuxControl
Encapsulates the auxiliary model space component of ControlVariable.
class ModelAuxControlEstimator
class ModelAuxCovariance
Encapsulates covariance for auxiliary model space component of ControlVariable.
class ModelAuxCtlVec
class ModelAuxIncrement
Encapsulates the auxiliary model space component of ControlIncrement.
class ModelAuxNN
class ModelSpaceCovariance4DBase
Abstract base class for model space error covariances.
class ModelSpaceCovarianceBase
Abstract base class for model space error covariances.
class MtMatrix
The \(M^T \) matrix.
class ObsAuxControl
Encapsulates auxiliary observation space components of ControlVariable.
class ObsAuxControlBase
Base class for auxiliary observation space components of ControlVariable.
class ObsAuxControlFactory
ObsAuxControl Factory.
class ObsAuxControlMaker
class ObsAuxControls
Encapsulates a vector of ObsAuxControl objects.
class ObsAuxCovariance
Encapsulates the covariance matrix of auxiliary observation space components of ControlVariable.
class ObsAuxCovarianceBase
Base class for covariance of auxiliary observation space components of ControlVariable.
class ObsAuxCovarianceFactory
ObsAuxCovariance Factory.
class ObsAuxCovarianceMaker
class ObsAuxCovariances
Encapsulates a vector of ObsAuxCovariance objects.
class ObsAuxCtlVec
Encapsulates auxiliary observation space components of ControlVector.
class ObsAuxCtlVecBase
Base class for auxiliary observation space components of ControlVector.
class ObsAuxCtlVecFactory
ObsAuxCtlVec Factory.
class ObsAuxCtlVecMaker
class ObsAuxCtlVecs
Encapsulates a vector of ObsAuxCtlVec objects.
class ObsAuxIncrement
Encapsulates auxiliary observation space components of ControlIncrement.
class ObsAuxIncrementBase
Base class for auxiliary observation space components of ControlIncrement.
class ObsAuxIncrementFactory
ObsAuxIncrement Factory.
class ObsAuxIncrementMaker
class ObsAuxIncrements
Encapsulates a vector of ObsAuxIncrement objects.
class ObsErrorBase
Base class for observation error covariance matrices.
class ObsErrorCovariance
Encapsulates observation and observation bias error covariance matrices.
class ObsErrorDiag
Diagonal observation error covariance matrix.
class ObsErrorFactory
ObsErrorFactory Factory.
class ObsErrorMaker
class ObsErrors
Encapsulates a vector of ObsErrorCovariance objects.
class Observations
Observations Class.
class ObservationSpace
Encapsulates the observation space.
class ObservationSpaces
Wrapper around a vector of observation spaces.
class Observer
Computes \({\cal G}(x) \).
class ObserverAD
Computes observation equivalent AD and AD to/from increments.
class ObserverEnVarAD
Computes observation equivalent AD and AD to/from increments.
class ObserverEnVarTL
Computes observation equivalent TL and AD to/from increments.
class ObserverIAU
Compute time average of states or increments during model run.
class ObserverTL
Computes \(G dx \).
class ObsOperator
Encapsulates the observation operator.
class ObsOperatorBase
Base class for the observation operator.
class ObsOperatorFactory
Obs Operator Factory.
class ObsOperatorMaker
class ObsOperators
A container class storing a vector of ObsOperator objects.
class ObsVector
Encapsulates the observation vector.
class PCGMinimizer
PCG Minimizer.
class PLanczosMinimizer
PLanczos Minimizer.
class PostBase
Handles post-processing of model fields.
class PostBaseAD
Handles post-processing of model fields related to cost function.
class PostBaseTL
Handles post-processing of model fields related to cost function.
class PostProcessor
Control model post processing.
class PostProcessorAD
Control model post processing.
class PostProcessorFactory
The PostProcessorFactory defines and manages a factory to manage PostProcessor for objects.
class PostProcessorMaker
class PostProcessorModel
Compute time average of states or increments during model run.
class PostProcessorTL
Control linear model post processing.
class PostTimer
Handles timing of post-processing and similar actions.
class PrimalMinimizer
Primal Minimizer.
class QNewtonLMP
class QNewtonSqrtLMP
class RinvMatrix
The \(R^{-1} \) matrix.
class RMatrix
The \(R \) matrix.
class RPCGMinimizer
RPCG Minimizer.
class RPLanczosMinimizer
RLanczos Minimizer.
class Run
class SaddlePointLMPMatrix
The preconditioner for the saddle-point minimizer.
class SaddlePointMatrix
The Saddle-point matrix.
class SaddlePointMinimizer
SaddlePoint Minimizer.
class SaddlePointPrecondMatrix
The preconditioner for the saddle-point minimizer.
class SaddlePointVector
Control vector for the saddle point formulation.
class SpectralLMP
The SPECTRAL preconditioner matrix \(P \) for the system matrix \(AB = (I + Ht Rinv H B) \).
class SpectralSqrtLMP
The SPECTRAL preconditioner matrix \(P \) for the system matrix \(A \);.
class SQRTBPCGMinimizer
SQRTBPCG Minimizer.
class SQRTBPFOMMinimizer
SQRTBPFOM Minimizer.
class SQRTBPLanczosMinimizer
SQRTBPLanczos Minimizer.
class SQRTMinimizer
Abstract base class for square root minimizers.
class SQRTPCGMinimizer
SQRTPCG Minimizer.
class SQRTPLanczosMinimizer
SQRTPLanczosMinimizer.
class State
Encapsulates model state.
class State4D
Four dimensional state.
class StateInfo
Handles diagnostic prints of forecast fields.
class StateSaver
Store forecast fields.
class StateWriter
Handles writing-out of forecast fields.
class StaticCovariance4D
Generic ensemble based model space error covariance.
class StaticWithTLModelCovariance4D
Generic ensemble based model space error covariance.
class Test
class TrajectorySaver
class TrajectorySaverFP
class TrajectorySaverMF
class UtHtRinvHUMatrix
The \(U^T H^T R^{-1} H U\) matrix.
class Variables
class Variational
Variational data assimilation application.
class WeightedDiff
Compute time average of states or increments during model run.
class WeightedDiffAD
Compute time average of states or increments during linear model run.
class WeightedDiffTL
Compute time average of states or increments during linear model run.
class WeightedMean
Compute time average of states or increments during model run.
class WeightFactory
Factory.
class WeightingFct
Weighting Function.
class WeightMaker
Functions
void CholDecomp (const std::vector< double > &mat, std::vector< double > &lmat)
template<typename VECTOR , typename AMATRIX , typename PMATRIX >
double FGMRES (VECTOR &x, const VECTOR &b, const AMATRIX &A, const PMATRIX &precond, const int maxiter, const double tolerance)
template<typename VECTOR , typename AMATRIX , typename PMATRIX >
double FullGMRES (VECTOR &xx, const VECTOR &bb, const AMATRIX &A, const PMATRIX &precond, const int maxiter, const double tolerance, std::vector< VECTOR > &pqVEC, std::vector< VECTOR > &xyVEC)
template<typename VECTOR , typename AMATRIX , typename PMATRIX >
double GMRESR (VECTOR &xx, const VECTOR &bb, const AMATRIX &A, const PMATRIX &precond, const int maxiter, const double tolerance)
template<typename MODEL >
void instantiateCostFactory ()
template<typename MODEL >
void instantiateMinFactory ()
template<typename VECTOR , typename AMATRIX , typename PMATRIX >
double IPCG (VECTOR &x, const VECTOR &b, const AMATRIX &A, const PMATRIX &precond, const int maxiter, const double tolerance)
template<typename VECTOR , typename AMATRIX , typename PMATRIX >
double MINRES (VECTOR &x, const VECTOR &b, const AMATRIX &A, const PMATRIX &precond, const int maxiter, const double tolerance)
template<typename VECTOR , typename AMATRIX , typename PMATRIX >
double PCG (VECTOR &x, const VECTOR &b, const AMATRIX &A, const PMATRIX &precond, const int maxiter, const double tolerance)
template<typename VECTOR , typename AMATRIX , typename PMATRIX >
double PLanczos (VECTOR &xx, const VECTOR &bb, const AMATRIX &A, const PMATRIX &precond, const int maxiter, const double tolerance)
void rotmat (const double &a, const double &b, double &c, double &s)
void SymMatSpectrum (const Matrix< double > &m_A, ColVector< double > &cv_U, Matrix< double > &m_L)
void TriDiagSolve (const std::vector< double > &diag, const std::vector< double > &sub, const std::vector< double > &rhs, std::vector< double > &sol)
void TriDiagSpectrum (const std::vector< double > &diag, const std::vector< double > &sub, std::vector< double > &evals, std::vector< std::vector< double > > &evecs)
void UpHessSolve (std::vector< std::vector< double > > &UpHess, const std::vector< double > &rhs, std::vector< double > &sol)
void UpTriSolve (const std::vector< std::vector< double > > &H, const std::vector< double > &rhs, std::vector< double > &sol, const int &dim)
template<typename MODEL >
void instantiateCovarFactory ()
template<typename MODEL >
void instantiatePostProcessorStateFactory ()
template<typename MODEL >
ObsAuxControls< MODEL > & operator+= (ObsAuxControls< MODEL > &xx, const ObsAuxIncrements< MODEL > &dx)
template<typename MODEL >
void instantiateObsErrorFactory ()
template<typename MODEL >
void instantiateTlmFactory ()
template<typename MODEL >
State< MODEL > & operator+= (State< MODEL > &xx, const Increment< MODEL > &dx)
template<typename MODEL >
ModelAuxControl< MODEL > & operator+= (ModelAuxControl< MODEL > &xx, const ModelAuxIncrement< MODEL > &dx)
template<typename MODEL >
ObsAuxControl< MODEL > & operator+= (ObsAuxControl< MODEL > &xx, const ObsAuxIncrement< MODEL > &dx)
template<typename T >
bool is_close (T a, T b, T epsilon)
bool getEnv (const std::string &env, bool default_value)
int getEnv (const std::string &env, int default_value)
void printStackTrace ()
Variables
static WeightMaker< DolphChebyshev > makerDolph_ ("DolphChebyshev")
static LibOOPS liboops
Detailed Description
The namespace for the main oops code.
Author
Baudouin Raoult
Tiago Quintino
Date
December 2016
Function Documentation
CholDecomp()
void oops::CholDecomp (const std::vector< double > & mat, std::vector< double > & lmat)
Definition at line 24 of file CholDecomp.h.
{
   const int nn2 = mat.size();
   const int nn = sqrt(nn2);
   ASSERT(nn * nn == nn2);
   lmat.resize(nn2);
   if (nn > 0) {
     FtnCholDecomp(nn, &mat[0], &lmat[0]);
   }
 }
References FtnCholDecomp().
FGMRES()
template<typename VECTOR , typename AMATRIX , typename PMATRIX > double oops::FGMRES (VECTOR & x, const VECTOR & b, const AMATRIX & A, const PMATRIX & precond, const int maxiter, const double tolerance)
Definition at line 69 of file FGMRES.h.
{
   std::vector<VECTOR> V;
   std::vector<VECTOR> Z;
   std::vector<std::vector<double> > H;
   std::vector<double> cs(maxiter + 1, 0);
   std::vector<double> sn(maxiter + 1, 0);
   std::vector<double> s;
   std::vector<double> y(maxiter + 1, 0);
   VECTOR r(x);
   VECTOR z(x);
   VECTOR work(x);
   VECTOR work2(x);
   VECTOR w(x);
   VECTOR xinit(x);
   r = b;
   double xnrm2 = dot_product(x, x);
   if (xnrm2 != 0) {
     A.multiply(x, work);
     r -= work;  // r = b - Ax
   }
   double bnrm2 = sqrt(dot_product(b, b));
   double rnrm2 = sqrt(dot_product(r, r));
   double normReduction = rnrm2 / bnrm2;
   // Initialiaze (maxiter + 1) by maxiter matrix H
   H.resize(maxiter);
   for (int ii = 0; ii <= maxiter - 1; ii++) {
     H[ii].resize(maxiter + 1);
     for (int jj = 0; jj <= maxiter; jj++) {
       H[ii][jj] = 0;
     }
   }
   work = r;
   work *= 1 / rnrm2;
   V.push_back(work);
   s.push_back(rnrm2);
   int jiter;
   // FGMRES iteration
   Log::info() << std::endl;
   for (jiter = 0; jiter < maxiter; ++jiter) {
     Log::info() << " FGMRES Starting Iteration " << jiter + 1 << std::endl;
     precond.multiply(V[jiter], z);
     Z.push_back(z);
     A.multiply(z, w);
     double avnrm2 = sqrt(dot_product(w, w));
     // Modified Gram-Schmidt
     for (int jj = 0; jj <= jiter; ++jj) {
       H[jiter][jj] = dot_product(V[jj], w);
       w.axpy(-H[jiter][jj], V[jj]);
     }
     H[jiter][jiter + 1] = sqrt(dot_product(w, w));
     double av2nrm2 = H[jiter][jiter + 1];
     // Re-orthogonalize if necessary
     if (avnrm2 + 0.001 * av2nrm2 == avnrm2) {
       for (int jj = 0; jj <= jiter; ++jj) {
         double hr = dot_product(V[jj], w);
         H[jiter][jj] += hr;
         w.axpy(-hr, V[jj]);
       }
       H[jiter][jiter + 1] = sqrt(dot_product(w, w));
     }
     // Check breakdown
     if (H[jiter][jiter + 1] != 0) {
       w *= 1 / H[jiter][jiter + 1];
     }
     V.push_back(w);
     if (jiter > 0) {
       // Apply Givens Rotation
       for (int jj = 0; jj < jiter; ++jj) {
         double temp = cs[jj] * H[jiter][jj] + sn[jj] * H[jiter][jj + 1];
         H[jiter][jj + 1] = -sn[jj] * H[jiter][jj] + cs[jj] * H[jiter][jj + 1];
         H[jiter][jj] = temp;
       }
     }
     // Compute Givens rotation matrix parameters
     rotmat(H[jiter][jiter], H[jiter][jiter + 1], cs[jiter], sn[jiter]);
     H[jiter][jiter] =
         cs[jiter] * H[jiter][jiter] + sn[jiter] * H[jiter][jiter + 1];
     H[jiter][jiter + 1] = 0.0;
     double temp = cs[jiter] * s[jiter];
     s.push_back(-sn[jiter] * s[jiter]);
     s[jiter] = temp;
     // Calculate the solution
     UpTriSolve(H, s, y, jiter);  // H s = y
     x = xinit;
     for (int jj = 0; jj < jiter + 1; ++jj) {
       x.axpy(y[jj], Z[jj]);
     }
     normReduction = std::abs(s[jiter + 1]) / bnrm2;
     Log::info() << "FGMRES end of iteration " << jiter + 1
                 << ". PNorm reduction= " << util::full_precision(normReduction)
                 << std::endl
                 << std::endl;
     if (normReduction <= tolerance) {
       Log::info() << "FGMRES: Achieved required reduction in residual norm."
                   << std::endl;
       jiter += 1;
       break;
     }
   }
   // Calculate the solution
   UpTriSolve(H, s, y, jiter);  // H s = y
   x = xinit;
   for (int jj = 0; jj < jiter; ++jj) {
     x.axpy(y[jj], Z[jj]);
   }
   Log::info() << "FGMRES: end" << std::endl;
   return normReduction;
 }
References dot_product(), util::full_precision(), rotmat(), and UpTriSolve().
Referenced by oops::FGMRESMinimizer< MODEL >::solve().
FullGMRES()
template<typename VECTOR , typename AMATRIX , typename PMATRIX > double oops::FullGMRES (VECTOR & xx, const VECTOR & bb, const AMATRIX & A, const PMATRIX & precond, const int maxiter, const double tolerance, std::vector< VECTOR > & pqVEC, std::vector< VECTOR > & xyVEC)
Definition at line 68 of file FullGMRES.h.
{
   std::vector<VECTOR> VV;
   std::vector<std::vector<double> > H;
   std::vector<double> cs(maxiter + 1, 0);
   std::vector<double> sn(maxiter + 1, 0);
   std::vector<double> ss;
   std::vector<double> yy(maxiter + 1, 0);
   VECTOR ww(xx);
   VECTOR zz(xx);
   VECTOR rr(bb);
   double xnrm2 = dot_product(xx, xx);
   if (xnrm2 != 0) {
     A.multiply(xx, ww);
     rr -= ww;  // r = b - Ax
   }
   precond.multiply(rr, zz);
   double znrm2 = sqrt(dot_product(zz, zz));
   double normReduction = 1.0;
   zz *= 1 / znrm2;
   VV.push_back(zz);
   ss.push_back(znrm2);
   // Initialiaze (maxiter + 1) by maxiter matrix H
   H.resize(maxiter);
   for (int ii = 0; ii <= maxiter - 1; ii++) {
     H[ii].resize(maxiter + 1);
     for (int jj = 0; jj <= maxiter; jj++) {
       H[ii][jj] = 0;
     }
   }
   pqVEC.clear();
   xyVEC.clear();
   int jiter;
   // FullGMRES iteration
   Log::info() << std::endl;
   for (jiter = 0; jiter < maxiter; ++jiter) {
     Log::info() << " FullGMRES Starting Iteration " << jiter + 1 << std::endl;
     A.multiply(VV[jiter], zz);
     precond.multiply(zz, ww);
     if (jiter > 1) {
       xyVEC.push_back(VV[jiter]);
       pqVEC.push_back(zz);
     }
     double avnrm2 = sqrt(dot_product(ww, ww));
     // Modified Gram-Schmidt
     for (int jj = 0; jj <= jiter; ++jj) {
       H[jiter][jj] = dot_product(VV[jj], ww);
       ww.axpy(-H[jiter][jj], VV[jj]);
     }
     H[jiter][jiter + 1] = sqrt(dot_product(ww, ww));
     double av2nrm2 = H[jiter][jiter + 1];
     // Re-orthogonalize if necessary
     if (avnrm2 + 0.001 * av2nrm2 == avnrm2) {
       for (int jj = 0; jj <= jiter; ++jj) {
         double hr = dot_product(VV[jj], ww);
         H[jiter][jj] += hr;
         ww.axpy(-hr, VV[jj]);
       }
       H[jiter][jiter + 1] = sqrt(dot_product(ww, ww));
     }
     // Check breakdown
     if (H[jiter][jiter + 1] != 0.0) {
       ww *= 1 / H[jiter][jiter + 1];
     }
     VV.push_back(ww);
     if (jiter > 0) {
       // Apply Givens Rotation
       for (int jj = 0; jj < jiter; ++jj) {
         double temp = cs[jj] * H[jiter][jj] + sn[jj] * H[jiter][jj + 1];
         H[jiter][jj + 1] = -sn[jj] * H[jiter][jj] + cs[jj] * H[jiter][jj + 1];
         H[jiter][jj] = temp;
       }
     }
     // Compute Givens rotation matrix parameters
     rotmat(H[jiter][jiter], H[jiter][jiter + 1], cs[jiter], sn[jiter]);
     H[jiter][jiter] =
         cs[jiter] * H[jiter][jiter] + sn[jiter] * H[jiter][jiter + 1];
     H[jiter][jiter + 1] = 0.0;
     double temp = cs[jiter] * ss[jiter];
     ss.push_back(-sn[jiter] * ss[jiter]);
     ss[jiter] = temp;
     normReduction = std::abs(ss[jiter + 1]) / znrm2;
     Log::info() << "FullGMRES end of iteration " << jiter + 1
                 << ". PNorm reduction= " << util::full_precision(normReduction)
                 << std::endl
                 << std::endl;
     if (normReduction <= tolerance) {
       Log::info() << "FullGMRES: Achieved required reduction in presidual norm."
                   << std::endl;
       jiter += 1;
       break;
     }
   }
   // Calculate the solution
   UpTriSolve(H, ss, yy, jiter);
   for (int jj = 0; jj < jiter; ++jj) {
     xx.axpy(yy[jj], VV[jj]);
   }
   return normReduction;
 }
References dot_product(), util::full_precision(), rotmat(), and UpTriSolve().
Referenced by oops::SaddlePointMinimizer< MODEL >::doMinimize().
getEnv() [1/2]
bool oops::getEnv (const std::string & env, bool default_value)
Definition at line 31 of file LibOOPS.cc.
{
   if (::getenv(env.c_str())) {
     return eckit::Translator<std::string, bool>()(::getenv(env.c_str()));
   }
   return default_value;
 }
getEnv() [2/2]
int oops::getEnv (const std::string & env, int default_value)
Definition at line 38 of file LibOOPS.cc.
{
   if (::getenv(env.c_str())) {
     return eckit::Translator<std::string, int>()(::getenv(env.c_str()));
   }
   return default_value;
 }
GMRESR()
template<typename VECTOR , typename AMATRIX , typename PMATRIX > double oops::GMRESR (VECTOR & xx, const VECTOR & bb, const AMATRIX & A, const PMATRIX & precond, const int maxiter, const double tolerance)
Definition at line 63 of file GMRESR.h.
{
   const double stagthresh = 1.0e-3;
   const double smallres = 1.0e-6;
   std::vector<VECTOR> cvecs;
   std::vector<VECTOR> zvecs;
   VECTOR cc(xx);
   VECTOR zz(xx);
   VECTOR rr(bb);
   A.multiply(xx, zz);  // zz=Axx
   rr -= zz;
   double normReduction = 1.0;
   double rrnorm = sqrt(dot_product(rr, rr));
   double cdotr = rrnorm;
   const double rrnorm0 = rrnorm;
   if (rrnorm > smallres) {
     Log::info() << std::endl;
     for (int jiter = 0; jiter < maxiter; ++jiter) {
       Log::info() << " GMRESR Starting Iteration " << jiter + 1 << std::endl;
       // test for stagnation
       if (std::abs(cdotr) < stagthresh * rrnorm) {
         Log::info() << "GMRESR stagnated. Doing an LSQR step." << std::endl;
         A.multiply(rr, zz);  // should be A^T, but we assume A is symmetric.
       } else {
         precond.multiply(rr,
                          zz);  // returns zz as approximate solution of Azz=rr
       }
       A.multiply(zz, cc);  // cc=Azz
       for (int jj = 0; jj < jiter; ++jj) {
         double alpha = -dot_product(cvecs[jj], cc);
         cc.axpy(alpha, cvecs[jj]);  // cc = cc - <c[jj],cc>*c[jj];
         zz.axpy(alpha, zvecs[jj]);  // zz = zz - <c[jj],cc>*z[jj];
       }
       double ccnorm = sqrt(dot_product(cc, cc));
       cvecs.push_back(cc);  // c[jiter]=cc
       cvecs[jiter] *= 1.0 / ccnorm;
       zvecs.push_back(zz);  // z[jiter]=zz
       zvecs[jiter] *= 1.0 / ccnorm;
       cdotr = dot_product(cvecs[jiter], rr);
       rr.axpy(-cdotr, cvecs[jiter]);
       xx.axpy(cdotr, zvecs[jiter]);
       rrnorm = sqrt(dot_product(rr, rr));
       normReduction = rrnorm / rrnorm0;
       Log::info() << "GMRESR end of iteration " << jiter + 1
                   << ". Norm reduction= " << util::full_precision(normReduction)
                   << std::endl
                   << std::endl;
       if (normReduction < tolerance) {
         Log::info() << "GMRESR: Achieved required reduction in residual norm."
                     << std::endl;
         break;
       }
     }
   }
   return normReduction;
 }
References dot_product(), and util::full_precision().
Referenced by oops::SaddlePointMinimizer< MODEL >::doMinimize(), oops::HybridCovariance< MODEL >::inverseMultiply(), oops::GMRESRMinimizer< MODEL >::solve(), and oops::LBGMRESRMinimizer< MODEL >::solve().
instantiateCostFactory()
template<typename MODEL > void oops::instantiateCostFactory ()
Definition at line 27 of file instantiateCostFactory.h.
{
   static CostMaker<MODEL, CostFct3DVar<MODEL> > maker3DVar_("3D-Var");
   static CostMaker<MODEL, CostFct4DVar<MODEL> > maker4DVar_("4D-Var");
   static CostMaker<MODEL, CostFct4DVarMF<MODEL> > maker4DVarMF_("4D-Var-MF");
   static CostMaker<MODEL, CostFct4DVarHyb4D<MODEL> >  maker4DVarHyb4D_("4DVarHyb4D");
   static CostMaker<MODEL, CostFct4DVarTrajHR<MODEL> > maker4DVarTrajHR_("4D-Var-TrajHR");
   static CostMaker<MODEL, CostFct4DEnsVar<MODEL> > maker4DEns_("4D-Ens-Var");
   static CostMaker<MODEL, CostFct4DEnVar<MODEL> > maker4DEnVar_(
       "4DEnVar"); /* For Meteo-France EnVars */
   static CostMaker<MODEL, CostFctWeak<MODEL> > maker4Weak_("4D-Weak");
 }
instantiateCovarFactory()
template<typename MODEL > void oops::instantiateCovarFactory ()
Definition at line 32 of file instantiateCovarFactory.h.
{
   static CovarMaker<MODEL, HybridCovariance<MODEL> > makerHybrid_("hybrid");
   static CovarMaker<MODEL, HybridCovarianceGeneralCoeff<MODEL> >
       makerHybridGen_("hybrid_general_coeff");
   static CovarMaker<MODEL, EnsembleCovariance<MODEL> > makerEnsemble_(
       "ensemble");
   static CovarMaker<MODEL, ErrorCovariance<MODEL> > makerModel_("static");
   static CovarMaker<MODEL, EnsembleCovsInterpol<MODEL> > makerEnsCovsInterpol_("ens_interpol");
   static Covar4DMaker<MODEL, StaticCovariance4D<MODEL> > makerStatic4D_(
       "static4D");
   static Covar4DMaker<MODEL, HybridCovariance4D<MODEL> > makerHybrid4D_(
       "hybrid");
   static Covar4DMaker<MODEL, EnsembleCovariance4D<MODEL> > makerEnsemble4D_(
       "ensemble");
   static Covar4DMaker<MODEL, EnsembleCovariance4DWithChangeOfVariable<MODEL> >
       makerEnsemble4DPsiKhi_("ensemble_with_change_of_variable");
   static Covar4DMaker<MODEL, StaticWithTLModelCovariance4D<MODEL> >
       makerStaticTL4D_("static_with_tlmodel");
   static Covar4DMaker<MODEL, EnsembleCovsInterpol4D<MODEL> >
       makerEnsembleInterp4D_("ens_interpol");
   static Covar4DMaker<MODEL, EnsembleCovariance4DScaleDependent<MODEL> >
       makerEnsembleScaleDep4D_("ensemble_scale_dependent");
   static Covar4DMaker<MODEL, EnsembleCovariance4DDistributed<MODEL> >
       makerEnsembleDist4D_("ensemble_distributed");
 }
instantiateMinFactory()
template<typename MODEL > void oops::instantiateMinFactory ()
Definition at line 39 of file instantiateMinFactory.h.
{
   static MinMaker<MODEL, DRGMRESRMinimizer<MODEL> > makerDRGMRESR_("DRGMRESR");
   static MinMaker<MODEL, DRIPCGMinimizer<MODEL> > makerDRIPCG_("DRIPCG");
   static MinMaker<MODEL, GMRESRMinimizer<MODEL> > makerGMRESR_("GMRESR");
   static MinMaker<MODEL, IPCGMinimizer<MODEL> > makerIPCG_("IPCG");
   static MinMaker<MODEL, SaddlePointMinimizer<MODEL> > makerSADDLE_(
       "SaddlePoint");
   static MinMaker<MODEL, RPCGMinimizer<MODEL> > makerRPCG_("RPCG");
   static MinMaker<MODEL, DRPCGMinimizer<MODEL> > makerDRPCG_("DRPCG");
   static MinMaker<MODEL, DRPFOMMinimizer<MODEL> > makerDRPFOM_("DRPFOM");
   static MinMaker<MODEL, LBGMRESRMinimizer<MODEL> > makerBDRPCG_("LBGMRESR");
   static MinMaker<MODEL, DRPLanczosMinimizer<MODEL> > makerDRPLanczos_(
       "DRPLanczos");
   static MinMaker<MODEL, PCGMinimizer<MODEL> > makerPCG_("PCG");
   static MinMaker<MODEL, PLanczosMinimizer<MODEL> > makerPLanczos_("PLanczos");
   static MinMaker<MODEL, RPLanczosMinimizer<MODEL> > makerRPLanczos_(
       "RPLanczos");
   static MinMaker<MODEL, SQRTBPCGMinimizer<MODEL> > makerSQRTBPCG_("SQRTBPCG");
   static MinMaker<MODEL, SQRTBPLanczosMinimizer<MODEL> > makerSQRTBPLanczos_(
       "SQRTBPLanczos");
   static MinMaker<MODEL, SQRTBPFOMMinimizer<MODEL> > makerSQRTBPFOM_(
       "SQRTBPFOM");
   static MinMaker<MODEL, SQRTPCGMinimizer<MODEL> > makerSQRTPCG_("SQRTPCG");
   static MinMaker<MODEL, SQRTPLanczosMinimizer<MODEL> > makerSQRTPLanczos_(
       "SQRTPLanczos");
   static MinMaker<MODEL, MINRESMinimizer<MODEL> > makerMINRES_("MINRES");
   static MinMaker<MODEL, FGMRESMinimizer<MODEL> > makerFGMRES_("FGMRES");
 }
instantiateObsErrorFactory()
template<typename MODEL > void oops::instantiateObsErrorFactory ()
Definition at line 20 of file instantiateObsErrorFactory.h.
{
   static ObsErrorMaker<MODEL, ObsErrorDiag<MODEL> > makerDiag_("diagonal");
 }
instantiatePostProcessorStateFactory()
template<typename MODEL > void oops::instantiatePostProcessorStateFactory ()
Definition at line 26 of file instantiatePostProcessorStateFactory.h.
{
   static PostProcessorMaker<MODEL, State<MODEL>, StateInfo<State<MODEL> > >
       makerStateInfo__("state_info");
   static PostProcessorMaker<MODEL, State<MODEL>, StateWriter<State<MODEL> > >
       makerStateWriter_("state_writer");
   static PostProcessorMaker<MODEL, State<MODEL>, ObserverIAU<MODEL, State<MODEL> > >
       makerIAU_("IAU");
   static PostProcessorMaker<MODEL, State<MODEL>, HighToLow<MODEL, State<MODEL> > >
       makerHTL_("high_to_low");
 }
instantiateTlmFactory()
template<typename MODEL > void oops::instantiateTlmFactory ()
Definition at line 20 of file instantiateTlmFactory.h.
{
   static LinearModelMaker<MODEL, LinearModelId<MODEL> > makerTLMID_("identity");
 }
IPCG()
template<typename VECTOR , typename AMATRIX , typename PMATRIX > double oops::IPCG (VECTOR & x, const VECTOR & b, const AMATRIX & A, const PMATRIX & precond, const int maxiter, const double tolerance)
Definition at line 62 of file IPCG.h.
{
   VECTOR ap(x);
   VECTOR p(x);
   VECTOR r(x);
   VECTOR s(x);
   VECTOR oldr(x);
   VECTOR w(x);
   VECTOR v(x);  // required for re-orthogonalization
   VECTOR z(x);  // required for re-orthogonalization
   std::vector<VECTOR> vVEC;  // required for re-orthogonalization
   std::vector<VECTOR> zVEC;  // required for re-orthogonalization
   // Initial residual r = b - Ax
   r = b;
   double xnrm2 = dot_product(x, x);
   if (xnrm2 != 0) {
     A.multiply(x, s);
     r -= s;
   }
   // s = precond r
   precond.multiply(r, s);
   double dotRr0 = dot_product(r, r);
   double dotSr0 = dot_product(r, s);
   double normReduction = 1.0;
   double rdots_old = dotSr0;
   double rdots = dotSr0;
   v = r;
   v *= 1 / sqrt(dotSr0);
   z = s;
   z *= 1 / sqrt(dotSr0);
   vVEC.push_back(v);
   zVEC.push_back(z);
   Log::info() << std::endl;
   for (int jiter = 0; jiter < maxiter; ++jiter) {
     Log::info() << " IPCG Starting Iteration " << jiter + 1 << std::endl;
     if (jiter == 0) {
       p = s;
     } else {
       w = r;
       w -= oldr;  // w=r-oldr
       double beta = dot_product(s, w) / rdots_old;
       p *= beta;
       p += s;  // p = s + beta*p
     }
     A.multiply(p, ap);  // ap = Ap
     oldr = r;
     double alpha = rdots / dot_product(p, ap);
     x.axpy(alpha, p);    // x = x + alpha*p;
     r.axpy(-alpha, ap);  // r = r - alpha*ap;
     // Re-orthogonalization
     for (int iiter = 0; iiter < jiter; ++iiter) {
       double proj = dot_product(r, zVEC[iiter]);
       r.axpy(-proj, vVEC[iiter]);
     }
     precond.multiply(r, s);  // returns s as approximate solve of As=r
     rdots_old = rdots;
     rdots = dot_product(r, s);
     v = r;
     v *= 1 / sqrt(rdots);
     z = s;
     z *= 1 / sqrt(rdots);
     vVEC.push_back(v);
     zVEC.push_back(z);
     normReduction = sqrt(dot_product(r, r) / dotRr0);
     Log::info() << "IPCG end of iteration " << jiter + 1
                 << ". Norm reduction= " << util::full_precision(normReduction)
                 << std::endl
                 << std::endl;
     if (normReduction < tolerance) {
       Log::info() << "IPCG: Achieved required reduction in residual norm."
                   << std::endl;
       break;
     }
   }
   Log::info() << "IPCG: end" << std::endl;
   return normReduction;
 }
References dot_product(), and util::full_precision().
Referenced by oops::IPCGMinimizer< MODEL >::solve().
is_close()
template<typename T > bool oops::is_close (T a, T b, T epsilon)
Definition at line 89 of file Test.h.
{
   // if nan or inf values, always return false
   if (std::isnan(a) || std::isnan(b) || std::isinf(a) || std::isinf(b))
     return false;
   // otherwise, create a relative tolerance that is of the same type as a and b
   // (which is what is_approximately_equal wants) and call
   // is_approximately_equal.
   T AbsA = fabs(a);
   T AbsB = fabs(b);
   T EpsAB = (AbsA < AbsB ? AbsB : AbsA) *
             epsilon;  // greater of AbsA, AbsB times epsilon
   return eckit::types::is_approximately_equal(a, b, EpsAB);
 }
Referenced by test::CASE(), test::testErrorCovarianceSym(), test::testLinearModelAdjoint(), test::testLinearModelLinearity(), and test::testModelForecast().
MINRES()
template<typename VECTOR , typename AMATRIX , typename PMATRIX > double oops::MINRES (VECTOR & x, const VECTOR & b, const AMATRIX & A, const PMATRIX & precond, const int maxiter, const double tolerance)
Definition at line 66 of file MINRES.h.
{
   VECTOR r(x);
   VECTOR work(x);
   VECTOR v(x);
   r = b;
   double xnrm2 = dot_product(x, x);
   if (xnrm2 != 0) {
     A.multiply(x, work);  // sx = Ax
     r -= work;            // r = b - Ax
   }
   work *= 0;
   VECTOR work2(work);
   VECTOR work1(work);
   VECTOR r1(r);
   VECTOR r2(r);
   VECTOR y(r);
   precond.multiply(r, y);
   double normReduction = 1.0;
   double ynrm2 = sqrt(dot_product(y, y));
   double beta = sqrt(dot_product(y, r));
   double oldb = 0;
   double epsln = 0;
   double cs = -1.0;
   double sn = 0;
   double dbar = 0;
   double phibar = beta;
   int jiter;
   // MINRES iteration
   Log::info() << std::endl;
   for (jiter = 0; jiter < maxiter; ++jiter) {
     Log::info() << " MINRES Starting Iteration " << jiter + 1 << std::endl;
     v = y;
     v *= 1 / beta;
     A.multiply(v, y);
     if (jiter > 0) {
       y.axpy(-beta / oldb, r1);
     }
     double alpha = dot_product(y, v);
     y.axpy(-alpha / beta, r2);
     r1 = r2;
     r2 = y;
     precond.multiply(r2, y);
     oldb = beta;
     beta = sqrt(dot_product(y, r2));
     // Apply Givens Rotation
     double oldeps = epsln;
     double delta = cs * dbar + sn * alpha;
     double gbar = sn * dbar - cs * alpha;
     epsln = sn * beta;
     dbar = -cs * beta;
     // Compute Givens rotation matrix parameters
     double gamma = sqrt(gbar * gbar + beta * beta);  // update this parameter
     cs = gbar / gamma;
     sn = beta / gamma;
     double phi = cs * phibar;
     phibar = sn * phibar;
     // Update x
     double denom = 1 / gamma;
     work1 = work2;
     work2 = work;
     work = v;
     work *= denom;
     work.axpy(-oldeps * denom, work1);
     work.axpy(-delta * denom, work2);
     x.axpy(phi, work);
     normReduction = phibar / ynrm2;
     Log::info() << "MINRES end of iteration " << jiter + 1
                 << ". PNorm reduction= " << util::full_precision(normReduction)
                 << std::endl
                 << std::endl;
     if (normReduction <= tolerance) {
       Log::info() << "MINRES: Achieved required reduction in residual norm."
                   << std::endl;
       jiter += 1;
       break;
     }
   }
   Log::info() << "MINRES: end" << std::endl;
   return normReduction;
 }
References dot_product(), and util::full_precision().
Referenced by oops::MINRESMinimizer< MODEL >::solve().
operator+=() [1/4]
template<typename MODEL > ModelAuxControl<MODEL>& oops::operator+= (ModelAuxControl< MODEL > & xx, const ModelAuxIncrement< MODEL > & dx)
Definition at line 106 of file ModelAuxIncrement.h.
{
   Log::trace() << "operator+=(ModelAuxControl, ModelAuxIncrement) starting"
                << std::endl;
   util::Timer timer("oops::ModelAuxIncrement", "operator+=ModelAuxControl");
   xx.modelauxcontrol() += dx.modelauxincrement();
   Log::trace() << "operator+=(ModelAuxControl, ModelAuxIncrement) done"
                << std::endl;
   return xx;
 }
References oops::ModelAuxControl< MODEL >::modelauxcontrol(), and oops::ModelAuxIncrement< MODEL >::modelauxincrement().
operator+=() [2/4]
template<typename MODEL > ObsAuxControl<MODEL>& oops::operator+= (ObsAuxControl< MODEL > & xx, const ObsAuxIncrement< MODEL > & dx)
Definition at line 136 of file ObsAuxIncrement.h.
{
   Log::trace() << "operator+=(ObsAuxControl, ObsAuxIncrement) starting"
                << std::endl;
   util::Timer timer("oops::ObsAuxIncrement", "operator+=ObsAuxControl");
   using icst = typename std::map<
       std::string, std::unique_ptr<ObsAuxIncrementBase<MODEL>>>::const_iterator;
   for (icst it = dx.obsauxincrement().begin(); it != dx.obsauxincrement().end();
        ++it) {
     xx.obsauxcontrol(it->first) += dx.obsauxincrement(it->first);
   }
   Log::trace() << "operator+=(ObsAuxControl, ObsAuxIncrement) done"
                << std::endl;
   return xx;
 }
References oops::ObsAuxControl< MODEL >::obsauxcontrol(), and oops::ObsAuxIncrement< MODEL >::obsauxincrement().
operator+=() [3/4]
template<typename MODEL > ObsAuxControls<MODEL>& oops::operator+= (ObsAuxControls< MODEL > & xx, const ObsAuxIncrements< MODEL > & dx)
Definition at line 99 of file ObsAuxIncrements.h.
{
   Log::trace() << "operator+=(ObsAuxControls, ObsAuxIncrements) starting"
                << std::endl;
   ASSERT(xx.size() == dx.size());
   for (std::size_t jobs = 0; jobs < xx.size(); ++jobs) {
     xx[jobs] += dx[jobs];
   }
   Log::trace() << "operator+=(ObsAuxControls, ObsAuxIncrements) done"
                << std::endl;
   return xx;
 }
References oops::ObsAuxControls< MODEL >::size(), and oops::ObsAuxIncrements< MODEL >::size().
operator+=() [4/4]
template<typename MODEL > State<MODEL>& oops::operator+= (State< MODEL > & xx, const Increment< MODEL > & dx)
Definition at line 151 of file Increment.h.
{
   Log::trace() << "operator+=(State, Increment) starting" << std::endl;
   util::Timer timer("oops::Increment", "operator+=(State, Increment)");
   xx.state() += dx.increment();
   Log::trace() << "operator+=(State, Increment) done" << std::endl;
   return xx;
 }
References oops::State< MODEL >::state().
PCG()
template<typename VECTOR , typename AMATRIX , typename PMATRIX > double oops::PCG (VECTOR & x, const VECTOR & b, const AMATRIX & A, const PMATRIX & precond, const int maxiter, const double tolerance)
Definition at line 63 of file PCG.h.
{
   VECTOR ap(x);
   VECTOR p(x);
   VECTOR r(x);
   VECTOR s(x);
   VECTOR v(x);
   VECTOR z(x);
   std::vector<VECTOR> vVEC;  // required for re-orthogonalization
   std::vector<VECTOR> zVEC;  // required for re-orthogonalization
   // Initial residual r = b - Ax
   r = b;
   double xnrm2 = dot_product(x, x);
   if (xnrm2 != 0) {
     A.multiply(x, s);
     r -= s;
   }
   // s = precond r
   precond.multiply(r, s);
   double dotRr0 = dot_product(r, s);
   double normReduction = 1.0;
   double rdots = dotRr0;
   double rdots_old = 0.0;
   v = r;
   v *= 1 / sqrt(dotRr0);
   z = s;
   z *= 1 / sqrt(dotRr0);
   vVEC.push_back(v);
   zVEC.push_back(z);
   Log::info() << std::endl;
   for (int jiter = 0; jiter < maxiter; ++jiter) {
     Log::info() << " PCG Starting Iteration " << jiter + 1 << std::endl;
     if (jiter == 0) {
       p = s;
     } else {
       double beta = dot_product(s, r) / rdots_old;
       Log::debug() << "PCG beta = " << beta << std::endl;
       p *= beta;
       p += s;  // p = s + beta*p
     }
     A.multiply(p, ap);  // ap = A*p
     double alpha = rdots / dot_product(p, ap);
     x.axpy(alpha, p);    // x = x + alpha*p
     r.axpy(-alpha, ap);  // r = r - alpha*ap
     // Re-orthogonalization
     for (int iiter = 0; iiter < jiter; ++iiter) {
       double proj = dot_product(r, zVEC[iiter]);
       r.axpy(-proj, vVEC[iiter]);
     }
     precond.multiply(r, s);
     rdots_old = rdots;
     rdots = dot_product(r, s);
     v = r;
     v *= 1 / sqrt(rdots);
     z = s;
     z *= 1 / sqrt(rdots);
     vVEC.push_back(v);
     zVEC.push_back(z);
     normReduction = sqrt(rdots / dotRr0);
     Log::info() << "PCG end of iteration " << jiter + 1
                 << ". Norm reduction= " << util::full_precision(normReduction)
                 << std::endl
                 << std::endl;
     if (normReduction < tolerance) {
       Log::info() << "PCG: Achieved required reduction in residual norm."
                   << std::endl;
       break;
     }
   }
   Log::info() << "PCG: end" << std::endl;
   return normReduction;
 }
References dot_product(), and util::full_precision().
Referenced by oops::PCGMinimizer< MODEL >::solve().
PLanczos()
template<typename VECTOR , typename AMATRIX , typename PMATRIX > double oops::PLanczos (VECTOR & xx, const VECTOR & bb, const AMATRIX & A, const PMATRIX & precond, const int maxiter, const double tolerance)
Definition at line 62 of file PLanczos.h.
{
   VECTOR zz(xx);
   VECTOR ww(xx);
   std::vector<VECTOR> vVEC;
   std::vector<VECTOR> zVEC;
   std::vector<double> alphas;
   std::vector<double> betas;
   std::vector<double> dd;
   std::vector<double> yy;
   // Initial residual r = b - Ax
   VECTOR rr(bb);
   double xnrm2 = dot_product(xx, xx);
   if (xnrm2 != 0) {
     A.multiply(xx, zz);
     rr -= zz;
   }
   // z = precond r
   precond.multiply(rr, zz);
   double normReduction = 1.0;
   double beta0 = sqrt(dot_product(rr, zz));
   double beta = 0.0;
   VECTOR vv(rr);
   vv *= 1 / beta0;
   zz *= 1 / beta0;
   zVEC.push_back(zz);  // zVEC[0] = z_1 ---> required for re-orthogonalization
   vVEC.push_back(vv);  // vVEC[0] = v_1 ---> required for re-orthogonalization
   int jiter;
   Log::info() << std::endl;
   for (jiter = 0; jiter < maxiter; ++jiter) {
     Log::info() << " PLanczos Starting Iteration " << jiter + 1 << std::endl;
     // w = A z - beta * vold
     A.multiply(zz, ww);  // w = A z
     if (jiter > 0) ww.axpy(-beta, vVEC[jiter - 1]);
     double alpha = dot_product(zz, ww);
     ww.axpy(-alpha, vv);  // w = w - alpha * v
     // Re-orthogonalization
     for (int iiter = 0; iiter < jiter; ++iiter) {
       double proj = dot_product(ww, zVEC[iiter]);
       ww.axpy(-proj, vVEC[iiter]);
     }
     precond.multiply(ww, zz);  // z = precond w
     beta = sqrt(dot_product(zz, ww));
     vv = ww;
     vv *= 1 / beta;
     zz *= 1 / beta;
     zVEC.push_back(zz);  // zVEC[jiter+1] = z_jiter
     vVEC.push_back(vv);  // vVEC[jiter+1] = v_jiter
     alphas.push_back(alpha);
     if (jiter == 0) {
       yy.push_back(beta0 / alpha);
       dd.push_back(beta0);
     } else {
       // Solve the tridiagonal system T_jiter y_jiter = beta0 * e_1
       dd.push_back(beta0 * dot_product(zVEC[0], vv));
       TriDiagSolve(alphas, betas, dd, yy);
     }
     // Gradient norm in precond metric --> sqrt(r'z) --> beta * y(jiter)
     double rznorm = beta * std::abs(yy[jiter]);
     normReduction = rznorm / beta0;
     betas.push_back(beta);
     Log::info() << "PLanczos end of iteration " << jiter + 1
                 << ". Norm reduction= " << util::full_precision(normReduction)
                 << std::endl
                 << std::endl;
     if (normReduction < tolerance) {
       Log::info() << "PLanczos: Achieved required reduction in residual norm."
                   << std::endl;
       break;
     }
   }
   // Calculate the solution (xh = Binv x)
   for (int iiter = 0; iiter < jiter; ++iiter) {
     xx.axpy(yy[iiter], zVEC[iiter]);
   }
   Log::info() << "PLanczos: end" << std::endl;
   return normReduction;
 }
References dot_product(), util::full_precision(), and TriDiagSolve().
Referenced by oops::PLanczosMinimizer< MODEL >::solve().
printStackTrace()
void oops::printStackTrace ()
Definition at line 19 of file printStackTrace.h.
 { Log::debug() << "Stack trace not available"; }
rotmat()
void oops::rotmat (const double & a, const double & b, double & c, double & s)
Definition at line 22 of file rotmat.h.
{
   if (b == 0.0) {
     c = 1.0;
     s = 0.0;
   } else if (std::abs(b) > std::abs(a)) {
     double temp = a / b;
     s = 1.0 / sqrt(1.0 + temp * temp);
     c = temp * s;
   } else {
     double temp = b / a;
     c = 1.0 / sqrt(1.0 + temp * temp);
     s = temp * c;
   }
 }
Referenced by FGMRES(), and FullGMRES().
SymMatSpectrum()
void oops::SymMatSpectrum (const Matrix< double > & m_A, ColVector< double > & cv_U, Matrix< double > & m_L)
Definition at line 25 of file SymMatSpectrum.h.
{
   ASSERT(m_A.cols() == m_A.rows());
   const size_t nn = m_A.cols();
   if (nn > 0) {
     cv_U.resize(nn);
     m_L.resize(nn, nn);
     // Call Fortran wrapper to DSYEV
     FtnSymMatSpectrum(nn, m_A.data(), cv_U.data(), m_L.data());
   }
 }
References FtnSymMatSpectrum().
Referenced by oops::SpectralSqrtLMP< MODEL >::postprocess().
TriDiagSolve()
void oops::TriDiagSolve (const std::vector< double > & diag, const std::vector< double > & sub, const std::vector< double > & rhs, std::vector< double > & sol)
Definition at line 18 of file TriDiagSolve.h.
{
   const double n = rhs.size();
   ASSERT(sub.size() == n - 1);
   ASSERT(diag.size() == n);
   sol.resize(n);
   std::vector<double> c(sub);
   std::vector<double> d(rhs);
   // Forward substitution
   c[0] = c[0] / diag[0];
   d[0] = d[0] / diag[0];
   if (n > 2) {
     for (int iiter = 1; iiter <= n - 2; ++iiter) {
       double denom = diag[iiter] - sub[iiter - 1] * c[iiter - 1];
       c[iiter] = c[iiter] / denom;
       d[iiter] = (d[iiter] - sub[iiter - 1] * d[iiter - 1]) / denom;
     }
   }
   d[n - 1] = (d[n - 1] - sub[n - 2] * d[n - 2]) /
              (diag[n - 1] - sub[n - 2] * c[n - 2]);
   // Backward substitution
   sol[n - 1] = d[n - 1];
   for (int iiter = n - 2; iiter >= 0; --iiter) {
     sol[iiter] = (d[iiter] - (c[iiter] * sol[iiter + 1]));
   }
 }
Referenced by PLanczos(), oops::SQRTBPLanczosMinimizer< MODEL >::solve(), oops::SQRTPLanczosMinimizer< MODEL >::solve(), oops::RPLanczosMinimizer< MODEL >::solve(), and oops::DRPLanczosMinimizer< MODEL >::solve().
TriDiagSpectrum()
void oops::TriDiagSpectrum (const std::vector< double > & diag, const std::vector< double > & sub, std::vector< double > & evals, std::vector< std::vector< double > > & evecs)
Definition at line 25 of file TriDiagSpectrum.h.
{
   const unsigned nn = diag.size();
   ASSERT(sub.size() == nn);
   evals.resize(nn);
   evecs.resize(nn);
   if (nn > 0) {
     std::vector<double> ftnev(nn * nn);
     FtnTriDiagSpectrum(nn, &diag[0], &sub[0], &evals[0], &ftnev[0]);
     unsigned ii = 0;
     for (unsigned jv = 0; jv < nn; ++jv) {
       evecs[jv].resize(nn);
       for (unsigned jj = 0; jj < nn; ++jj) {
         evecs[jv][jj] = ftnev[ii];
         ++ii;
       }
     }
   }
 }
References FtnTriDiagSpectrum().
Referenced by oops::SQRTBPFOMMinimizer< MODEL >::calcRitzInformation(), oops::SQRTBPLanczosMinimizer< MODEL >::calcRitzInformation(), oops::SQRTPLanczosMinimizer< MODEL >::calcRitzInformation(), oops::SpectralLMP< oops::ControlIncrement >::update(), and oops::SpectralSqrtLMP< MODEL >::update().
UpHessSolve()
void oops::UpHessSolve (std::vector< std::vector< double > > & UpHess, const std::vector< double > & rhs, std::vector< double > & sol)
Definition at line 29 of file UpHessSolve.h.
{
   const double n = rhs.size();
   ASSERT(UpHess.size() == n);
   sol.resize(n);
   std::vector<double> v(n);
   std::vector<double> y(n);
   // Step 1: Compute the LU factorization
   // Note that L = I + diag(v(2:n),-1)
   v[0] = 0;
   for (int ii = 0; ii <= n - 2; ++ii) {
     v[ii + 1] = UpHess[ii][ii + 1] / UpHess[ii][ii];
     for (int jj = ii; jj <= n - 1; ++jj) {
       UpHess[jj][ii + 1] = UpHess[jj][ii + 1] - v[ii + 1] * UpHess[jj][ii];
     }
   }
   // Extract the upper triangular part (U part)
   for (int ii = 0; ii <= n - 1; ++ii) {
     for (int jj = ii + 1; jj <= n - 1; ++jj) {
       UpHess[ii][jj] = 0;
     }
   }
   // Step 2: Solve the n-by-n unit lower bidiagonal system  L y = rhs
   y[0] = rhs[0];
   for (int ii = 1; ii <= n - 1; ++ii) {
     y[ii] = rhs[ii] - v[ii] * y[ii - 1];
   }
   // Step 3: Solve the upper triangular system U sol = y
   UpTriSolve(UpHess, y, sol, n);
 }
References UpTriSolve().
Referenced by oops::SQRTBPFOMMinimizer< MODEL >::solve(), and oops::DRPFOMMinimizer< MODEL >::solve().
UpTriSolve()
void oops::UpTriSolve (const std::vector< std::vector< double > > & H, const std::vector< double > & rhs, std::vector< double > & sol, const int & dim)
Definition at line 23 of file UpTriSolve.h.
{
   // Backward solve
   for (int iiter = dim - 1; iiter >= 0; iiter--) {
     sol[iiter] = rhs[iiter];
     for (int jiter = iiter + 1; jiter < dim; jiter++) {
       sol[iiter] -= H[jiter][iiter] * sol[jiter];
     }
     sol[iiter] *= 1 / H[iiter][iiter];
   }
 }
Referenced by FGMRES(), FullGMRES(), and UpHessSolve().
Variable Documentation
liboops
LibOOPS oops::liboops static
Definition at line 47 of file LibOOPS.cc.
makerDolph_
WeightMaker<DolphChebyshev> oops::makerDolph_("DolphChebyshev") static