OOPS Documentation: qg/model/pv_operator.f90 File Reference
pv_operator.f90 File Reference
Functions/Subroutines
subroutine pv_operator (x, pv, nx, ny, F1, F2, deltax, deltay)
Potential vorticity operator.
Function/Subroutine Documentation
pv_operator()
subroutine pv_operator (real(kind=kind_real), dimension(nx,ny,2), intent(in) x, real(kind=kind_real), dimension(nx,ny,2), intent(out) pv, integer, intent(in) nx, integer, intent(in) ny, real(kind=kind_real), intent(in) F1, real(kind=kind_real), intent(in) F2, real(kind=kind_real), intent(in) deltax, real(kind=kind_real), intent(in) deltay)
Potential vorticity operator.
Applies the linear operator part of the PV calculation:
\begin{eqnarray*} q_1 &=& \nabla^2 \psi_1 - F_1 (\psi_1 -\psi_2) \\\\ q_2 &=& \nabla^2 \psi_2 - F_2 (\psi_2 -\psi_1) \end{eqnarray*}
(Note: The full potential vorticity calculation is done in calc_pv, and includes additional beta and orography terms.)
Parameters
[in] nx Zonal grid dimension
[in] ny Meridional grid dimension
[in] x Streamfunction
[out] pv Result of applying the operator to x
[in] f1 Parameter in the PV operator
[in] f2 Parameter in the PV operator
[in] deltax Zonal grid spacing (non-dimensional)
[in] deltay Meridional grid spacing (non-dimensional)
Definition at line 21 of file pv_operator.f90.
 !--- The part of the pv calculation that acts on internal streamfunction.
 use kinds
 implicit none
 integer, intent(in) :: nx
 integer, intent(in) :: ny
 real(kind=kind_real), intent(in)  :: x(nx,ny,2)
 real(kind=kind_real), intent(out) :: pv(nx,ny,2)
 real(kind=kind_real), intent(in) :: f1
 real(kind=kind_real), intent(in) :: f2
 real(kind=kind_real), intent(in) :: deltax
 real(kind=kind_real), intent(in) :: deltay
 !--- del-squared of the streamfunction
 call laplacian_2d (x(:,:,1),pv(:,:,1),nx,ny,deltax,deltay)
 call laplacian_2d (x(:,:,2),pv(:,:,2),nx,ny,deltax,deltay)
 !--- vertical differences:
 pv(:,:,1) = pv(:,:,1) -f1*(x(:,:,1)-x(:,:,2))
 pv(:,:,2) = pv(:,:,2) -f2*(x(:,:,2)-x(:,:,1))
References laplacian_2d().
Referenced by calc_pv(), and calc_pv_tl().