OOPS Documentation: qg/model/solve_elliptic_system.f90 File Reference
solve_elliptic_system.f90 File Reference
Functions/Subroutines
subroutine solve_elliptic_system (x, pv, nx, ny, deltax, deltay, F1, F2)
Solves the elliptic system that arises when inverting potential vorticity.
Function/Subroutine Documentation
solve_elliptic_system()
subroutine solve_elliptic_system (real(kind=kind_real), dimension(nx,ny,2), intent(out) x, real(kind=kind_real), dimension(nx,ny,2), intent(in) pv, integer, intent(in) nx, integer, intent(in) ny, real(kind=kind_real), intent(in) deltax, real(kind=kind_real), intent(in) deltay, real(kind=kind_real), intent(in) F1, real(kind=kind_real), intent(in) F2)
Solves the elliptic system that arises when inverting potential vorticity.
Here, we are solving the coupled system:
\begin{eqnarray} \nabla^2 \psi_1 - F_1 (\psi_1 -\psi_2) &=& p_1 \\\\ \nabla^2 \psi_2 - F_2 (\psi_2 -\psi_1) &=& p_2 \nonumber \end{eqnarray}
where the subscript refers to model level, and \(\nabla^2 \) is the 5-point finite-difference two-dimensional Laplacian.
We reduce this to a 2D problem, which we solve for \(\nabla^2 \psi_1 \):
\[ \nabla^2 \left(\nabla^2 \psi_1 \right) - (F_1 + F_2) \nabla^2 \psi_1 = \nabla^2 p_1 - F_2 p_1 - F_1 p_2 \]
Having found \(\nabla^2 \psi_1 \), we invert the Laplacian to determine \(\psi_1 \), and then get \(\psi_2 \) by substitution in equation 1 above.
Parameters
[in] nx Zonal grid dimension
[in] ny Meridional grid dimension
[out] x Streamfunction
[in] pv Right hand side
[in] deltax Zonal grid spacing (non-dimensional)
[in] deltay Meridional grid spacing (non-dimensional)
[in] f1 Coefficient in the PV operator
[in] f2 Coefficient in the PV operator
Definition at line 31 of file solve_elliptic_system.f90.
 !--- invert potential vorticity to get streamfunction
 use kinds
 implicit none
 integer, intent(in) :: nx
 integer, intent(in) :: ny
 real(kind=kind_real), intent(out) :: x(nx,ny,2)
 real(kind=kind_real), intent(in)  :: pv(nx,ny,2)
 real(kind=kind_real), intent(in) :: deltax
 real(kind=kind_real), intent(in) :: deltay
 real(kind=kind_real), intent(in) :: f1
 real(kind=kind_real), intent(in) :: f2
 real(kind=kind_real) :: rhs(nx,ny), del2x1(nx,ny)
 !--- Solve the 2D problem
 call laplacian_2d (pv(:,:,1),rhs,nx,ny,deltax,deltay)
 rhs(:,:) = rhs(:,:) - f2*pv(:,:,1) - f1*pv(:,:,2)
 call solve_helmholz (del2x1,rhs,-(f1+f2),nx,ny,deltax,deltay)
 !--- Invert Laplacian to get x on level 1
 call solve_helmholz (x(:,:,1),del2x1,0.0_kind_real,nx,ny,deltax,deltay)
 !--- Calculate x on level 2
 x(:,:,2) = x(:,:,1) + (pv(:,:,1)-del2x1(:,:))*(1.0_kind_real/f1)
References laplacian_2d(), and solve_helmholz().
Referenced by invert_pv(), invert_pv_ad(), and invert_pv_tl().