OOPS Documentation: qg/model/calc_pv.f90 File Reference
calc_pv.f90 File Reference
Functions/Subroutines
subroutine calc_pv (kx, ky, pv, x, x_north, x_south, f1, f2, deltax, deltay, bet, rs)
Calculate potential vorticity from streamfunction.
Function/Subroutine Documentation
calc_pv()
subroutine calc_pv (integer, intent(in) kx, integer, intent(in) ky, real(kind=kind_real), dimension(kx,ky,2), intent(out) pv, real(kind=kind_real), dimension(kx,ky,2), intent(in) x, real(kind=kind_real), dimension(2), intent(in) x_north, real(kind=kind_real), dimension(2), intent(in) x_south, real(kind=kind_real), intent(in) f1, real(kind=kind_real), intent(in) f2, real(kind=kind_real), intent(in) deltax, real(kind=kind_real), intent(in) deltay, real(kind=kind_real), intent(in) bet, real(kind=kind_real), dimension(kx,ky), intent(in) rs)
Calculate potential vorticity from streamfunction.
Potential vorticity is defined as
\begin{eqnarray*} q_1 &=& \nabla^2 \psi_1 - F_1 (\psi_1 -\psi_2) + \beta y \\\\ q_2 &=& \nabla^2 \psi_2 - F_2 (\psi_2 -\psi_1) + \beta y + R_s \end{eqnarray*}
Parameters
[in] kx Zonal grid dimension
[in] ky Meridional grid dimension
[out] pv Potential vorticity
[in] x Streamfunction
[in] x_north Streamfunction on northern wall
[in] x_south Streamfunction on southern wall
[in] f1 Coefficient in PV operator
[in] f2 Coefficient in PV operator
[in] deltax Zonal grid spacing (non-dimensional)
[in] deltay Meridional grid spacing (non-dimensional)
[in] bet NS Gradient of Coriolis parameter
[in] rs Orography
Definition at line 19 of file calc_pv.f90.
 !--- calculate potential vorticity from streamfunction
 use kinds
 implicit none
 integer, intent(in) :: kx
 integer, intent(in) :: ky
 real(kind=kind_real), intent(out)   :: pv(kx,ky,2)
 real(kind=kind_real), intent(in)    :: x(kx,ky,2)
 real(kind=kind_real), intent(in)    :: x_north(2)
 real(kind=kind_real), intent(in)    :: x_south(2)
 real(kind=kind_real), intent(in)    :: f1
 real(kind=kind_real), intent(in)    :: f2
 real(kind=kind_real), intent(in)    :: deltax
 real(kind=kind_real), intent(in)    :: deltay
 real(kind=kind_real), intent(in)    :: bet
 real(kind=kind_real), intent(in)    :: rs(kx,ky)
 integer :: jj
 real(kind=kind_real) :: y
 !--- apply the linear operator
 call pv_operator(x,pv,kx,ky,f1,f2,deltax,deltay)
 !--- add the contribution from the boundaries
 pv(:,1 ,1) = pv(:,1 ,1) + (1.0_kind_real/(deltay*deltay))*x_south(1)
 pv(:,1 ,2) = pv(:,1 ,2) + (1.0_kind_real/(deltay*deltay))*x_south(2)
 pv(:,ky,1) = pv(:,ky,1) + (1.0_kind_real/(deltay*deltay))*x_north(1)
 pv(:,ky,2) = pv(:,ky,2) + (1.0_kind_real/(deltay*deltay))*x_north(2)
 !--- add the beta term
 do jj=1,ky
   y = real(jj-(ky+1)/2,kind_real)*deltay;
   pv(:,jj,:) = pv(:,jj,:) + bet*y
 enddo
 !--- add the orography/heating term
 pv(:,:,2) = pv(:,:,2) + rs(:,:)
References pv_operator().
Referenced by invent_state(), and propagate().