OOPS Documentation: oops::EnsembleCovariance4D< MODEL > Class Template Reference
oops::EnsembleCovariance4D< MODEL > Class Template Reference
Generic ensemble based model space error covariance.
#include <EnsembleCovariance4D.h>
Public Member Functions
EnsembleCovariance4D (const Geometry_ &, const Variables_ &, const eckit::Configuration &, const State4D_ &)
Constructor, destructor.
~EnsembleCovariance4D ()
void advectedLinearize (const State4D_ &, const Geometry_ &, const eckit::Configuration &)
void advectedMultiply (const Increment4D_ &, Increment4D_ &) const
void advectedMultiplySqrt (const IncrCtlVec_ &, Increment4D_ &) const
void advectedMultiplySqrtTrans (const Increment4D_ &, IncrCtlVec_ &) const
void advectedInverseMultiply (const Increment4D_ &, Increment4D_ &) const
const ModelSpaceCovarianceBase< MODEL > & covar () const
IncrModCtlVec_ * newIncrModCtlVec () const override
IncrEnsCtlVec_ * newIncrEnsCtlVec () const override
Public Member Functions inherited from oops::ModelSpaceCovariance4DBase< MODEL >
ModelSpaceCovariance4DBase (const Geometry_ &, const eckit::Configuration &config)
virtual ~ModelSpaceCovariance4DBase ()
void linearize (const State4D_ &xb, const Geometry_ &resol, const eckit::Configuration &config)
virtual void multiply (const Increment4D_ &dxi, Increment4D_ &dxo) const
virtual void multiplySqrt (const IncrCtlVec_ &dvi, Increment4D_ &dxo) const
virtual void multiplySqrtTrans (const Increment4D_ &dxi, IncrCtlVec_ &dvo) const
void inverseMultiply (const Increment4D_ &dxi, Increment4D_ &dxo) const
virtual void randomize (Increment4D_ &) const
Private Types
using Ensemble_ = Ensemble< MODEL >
using EnsemblePtr_ = std::shared_ptr< Ensemble< MODEL > >
using EnsemblesCollection_ = EnsemblesCollection< MODEL >
using Geometry_ = Geometry< MODEL >
using Increment_ = Increment< MODEL >
using Localization_ = Localization< MODEL >
using State4D_ = State4D< MODEL >
using Increment4D_ = Increment4D< MODEL >
using IncrCtlVec_ = IncrCtlVec< MODEL >
using IncrEnsCtlVec_ = IncrEnsCtlVec< MODEL >
using IncrModCtlVec_ = IncrModCtlVec< MODEL >
using Variables_ = Variables< MODEL >
Private Member Functions
void schur_add (const Increment_ &, const Increment_ &dxi, Increment_ &dxo, Increment_ &tmp) const
Private Attributes
const eckit::LocalConfiguration config_
unsigned nsubwin_
std::unique_ptr< Localization_ > loc_
std::unique_ptr< Geometry_ > geom_
std::unique_ptr< ModelSpaceCovarianceBase< MODEL > > static_
Detailed Description
template<typename MODEL>
class oops::EnsembleCovariance4D< MODEL >
Generic ensemble based model space error covariance.
Definition at line 38 of file EnsembleCovariance4D.h.
Member Typedef Documentation
Ensemble_
template<typename MODEL > using oops::EnsembleCovariance4D< MODEL >::Ensemble_ = Ensemble<MODEL> private
Definition at line 39 of file EnsembleCovariance4D.h.
EnsemblePtr_
template<typename MODEL > using oops::EnsembleCovariance4D< MODEL >::EnsemblePtr_ = std::shared_ptr<Ensemble<MODEL> > private
Definition at line 40 of file EnsembleCovariance4D.h.
EnsemblesCollection_
template<typename MODEL > using oops::EnsembleCovariance4D< MODEL >::EnsemblesCollection_ = EnsemblesCollection<MODEL> private
Definition at line 41 of file EnsembleCovariance4D.h.
Geometry_
template<typename MODEL > using oops::EnsembleCovariance4D< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 42 of file EnsembleCovariance4D.h.
IncrCtlVec_
template<typename MODEL > using oops::EnsembleCovariance4D< MODEL >::IncrCtlVec_ = IncrCtlVec<MODEL> private
Definition at line 47 of file EnsembleCovariance4D.h.
Increment4D_
template<typename MODEL > using oops::EnsembleCovariance4D< MODEL >::Increment4D_ = Increment4D<MODEL> private
Definition at line 46 of file EnsembleCovariance4D.h.
Increment_
template<typename MODEL > using oops::EnsembleCovariance4D< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 43 of file EnsembleCovariance4D.h.
IncrEnsCtlVec_
template<typename MODEL > using oops::EnsembleCovariance4D< MODEL >::IncrEnsCtlVec_ = IncrEnsCtlVec<MODEL> private
Definition at line 48 of file EnsembleCovariance4D.h.
IncrModCtlVec_
template<typename MODEL > using oops::EnsembleCovariance4D< MODEL >::IncrModCtlVec_ = IncrModCtlVec<MODEL> private
Definition at line 49 of file EnsembleCovariance4D.h.
Localization_
template<typename MODEL > using oops::EnsembleCovariance4D< MODEL >::Localization_ = Localization<MODEL> private
Definition at line 44 of file EnsembleCovariance4D.h.
State4D_
template<typename MODEL > using oops::EnsembleCovariance4D< MODEL >::State4D_ = State4D<MODEL> private
Definition at line 45 of file EnsembleCovariance4D.h.
Variables_
template<typename MODEL > using oops::EnsembleCovariance4D< MODEL >::Variables_ = Variables<MODEL> private
Definition at line 50 of file EnsembleCovariance4D.h.
Constructor & Destructor Documentation
EnsembleCovariance4D()
template<typename MODEL > oops::EnsembleCovariance4D< MODEL >::EnsembleCovariance4D (const Geometry_ & resol, const Variables_ & , const eckit::Configuration & config, const State4D_ &)
Constructor, destructor.
Definition at line 88 of file EnsembleCovariance4D.h.
     : ModelSpaceCovariance4DBase<MODEL>::ModelSpaceCovariance4DBase(resol,
                                                                     config),
       config_(config),
       nsubwin_(0),
       loc_(),
       geom_(),
       static_() {
   Log::trace() << "EnsembleCovariance4D created.";
 }
~EnsembleCovariance4D()
template<typename MODEL > oops::EnsembleCovariance4D< MODEL >::~EnsembleCovariance4D
Definition at line 102 of file EnsembleCovariance4D.h.
{
   Log::trace() << "EnsembleCovariance4D destructed.";
 }
Member Function Documentation
advectedInverseMultiply()
template<typename MODEL > void oops::EnsembleCovariance4D< MODEL >::advectedInverseMultiply (const Increment4D_ & dxi, Increment4D_ & dxo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 228 of file EnsembleCovariance4D.h.
{
   dxo.zero();
 }
References oops::Increment4D< MODEL >::zero().
advectedLinearize()
template<typename MODEL > void oops::EnsembleCovariance4D< MODEL >::advectedLinearize (const State4D_ & xb, const Geometry_ & resol, const eckit::Configuration &) virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 107 of file EnsembleCovariance4D.h.
{
   /*
    * Build localization
    */
   geom_.reset(new Geometry_(resol));
   const eckit::LocalConfiguration conf(config_, "localization");
   loc_.reset(new Localization_(*geom_, conf));
   /*
    * Build ensemble
    */
   std::vector<eckit::LocalConfiguration> confEnsemble;
   config_.get("ensemble", confEnsemble);
   nsubwin_ = confEnsemble.size();
   for (unsigned jsub = 0; jsub < nsubwin_; ++jsub) {
     EnsemblePtr_ ens_k(new Ensemble_(xb[jsub].validTime(), confEnsemble[jsub]));
     ens_k->build(xb[jsub], resol);
     EnsemblesCollection_::getInstance().put(xb[jsub].validTime(), ens_k);
   }
   /*
    * Read files
    */
   for (unsigned jsub = 0; jsub < nsubwin_; ++jsub) {
     EnsemblePtr_ ens =
         EnsemblesCollection_::getInstance()[xb[jsub].validTime()];
     ens->read();
   }
   /*
    * Calculate mean
    */
   for (unsigned jsub = 0; jsub < nsubwin_; ++jsub) {
     EnsemblePtr_ ens =
         EnsemblesCollection_::getInstance()[xb[jsub].validTime()];
     ens->to_perturbations();
   }
   Log::trace() << "EnsembleCovariance4D linearized.";
 }
advectedMultiply()
template<typename MODEL > void oops::EnsembleCovariance4D< MODEL >::advectedMultiply (const Increment4D_ & dxi, Increment4D_ & dxo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 151 of file EnsembleCovariance4D.h.
{
   Increment_ dx_loc(dxo[0]);
   Increment_ tmp(dxo[0]);
   EnsemblePtr_ e = EnsemblesCollection_::getInstance()[dxi[0].validTime()];
   dxo.zero();
   for (unsigned l = 0; l < e->size(); ++l) {
     dx_loc.zero();
     for (unsigned k2 = 0; k2 < nsubwin_; ++k2) {
       EnsemblePtr_ e_k2 =
           EnsemblesCollection_::getInstance()[dxi[k2].validTime()];
       schur_add((*e_k2)[l], dxi[k2], dx_loc, tmp);
     }
     loc_->multiply(dx_loc);
     for (unsigned k1 = 0; k1 < nsubwin_; ++k1) {
       EnsemblePtr_ e_k1 =
           EnsemblesCollection_::getInstance()[dxi[k1].validTime()];
       schur_add((*e_k1)[l], dx_loc, dxo[k1], tmp);
     }
   }
 }
References oops::Increment4D< MODEL >::zero(), and oops::Increment< MODEL >::zero().
advectedMultiplySqrt()
template<typename MODEL > void oops::EnsembleCovariance4D< MODEL >::advectedMultiplySqrt (const IncrCtlVec_ & dvi, Increment4D_ & dxo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 178 of file EnsembleCovariance4D.h.
{
   Increment_ dx(dxo[0]);
   Increment_ tmp(dxo[0]);
   EnsemblePtr_ e = EnsemblesCollection_::getInstance()[dxo[0].validTime()];
   dxo.zero();
   for (unsigned l = 0; l < e->size(); ++l) {
     loc_->multiplySqrt(dvi.ensCtlVec(l), dx);
     for (unsigned k1 = 0; k1 < nsubwin_; ++k1) {
       EnsemblePtr_ e_k1 =
           EnsemblesCollection_::getInstance()[dxo[k1].validTime()];
       schur_add((*e_k1)[l], dx, dxo[k1], tmp);
     }
   }
 }
References oops::IncrCtlVec< MODEL >::ensCtlVec(), and oops::Increment4D< MODEL >::zero().
advectedMultiplySqrtTrans()
template<typename MODEL > void oops::EnsembleCovariance4D< MODEL >::advectedMultiplySqrtTrans (const Increment4D_ & dxi, IncrCtlVec_ & dvo) const virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 197 of file EnsembleCovariance4D.h.
{
   Increment_ dx(dxi[0]);
   Increment_ tmp(dxi[0]);
   EnsemblePtr_ e = EnsemblesCollection_::getInstance()[dxi[0].validTime()];
   for (unsigned l = 0; l < e->size(); ++l) {
     dx.zero();
     dvo.ensCtlVec(l).zero();
     for (unsigned k2 = 0; k2 < nsubwin_; ++k2) {
       EnsemblePtr_ e_k2 =
           EnsemblesCollection_::getInstance()[dxi[k2].validTime()];
       schur_add((*e_k2)[l], dxi[k2], dx, tmp);
     }
     loc_->multiplySqrtTrans(dx, dvo.ensCtlVec(l));
   }
 }
References oops::IncrCtlVec< MODEL >::ensCtlVec(), oops::IncrEnsCtlVec< MODEL >::zero(), and oops::Increment< MODEL >::zero().
covar()
template<typename MODEL > const ModelSpaceCovarianceBase<MODEL>& oops::EnsembleCovariance4D< MODEL >::covar () const inline virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 62 of file EnsembleCovariance4D.h.
 { return *static_; }
References oops::EnsembleCovariance4D< MODEL >::static_.
newIncrEnsCtlVec()
template<typename MODEL > IncrEnsCtlVec_* oops::EnsembleCovariance4D< MODEL >::newIncrEnsCtlVec () const inline override virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 68 of file EnsembleCovariance4D.h.
{
     return new IncrEnsCtlVec_(*geom_, *loc_);
   }
References oops::EnsembleCovariance4D< MODEL >::geom_, and oops::EnsembleCovariance4D< MODEL >::loc_.
newIncrModCtlVec()
template<typename MODEL > IncrModCtlVec_* oops::EnsembleCovariance4D< MODEL >::newIncrModCtlVec () const inline override virtual
Implements oops::ModelSpaceCovariance4DBase< MODEL >.
Definition at line 65 of file EnsembleCovariance4D.h.
{
     return new IncrModCtlVec_();
   }
schur_add()
template<typename MODEL > void oops::EnsembleCovariance4D< MODEL >::schur_add (const Increment_ & pert, const Increment_ & dxi, Increment_ & dxo, Increment_ & tmp) const private
Definition at line 217 of file EnsembleCovariance4D.h.
{
   tmp_schur = pert;
   tmp_schur.schur_product_with(dxi);
   dxo.axpy(1.0, tmp_schur, false);
 }
References oops::Increment< MODEL >::axpy(), and oops::Increment< MODEL >::schur_product_with().
Member Data Documentation
config_
template<typename MODEL > const eckit::LocalConfiguration oops::EnsembleCovariance4D< MODEL >::config_ private
Definition at line 76 of file EnsembleCovariance4D.h.
geom_
template<typename MODEL > std::unique_ptr<Geometry_> oops::EnsembleCovariance4D< MODEL >::geom_ private
Definition at line 79 of file EnsembleCovariance4D.h.
Referenced by oops::EnsembleCovariance4D< MODEL >::newIncrEnsCtlVec().
loc_
template<typename MODEL > std::unique_ptr<Localization_> oops::EnsembleCovariance4D< MODEL >::loc_ private
Definition at line 78 of file EnsembleCovariance4D.h.
Referenced by oops::EnsembleCovariance4D< MODEL >::newIncrEnsCtlVec().
nsubwin_
template<typename MODEL > unsigned oops::EnsembleCovariance4D< MODEL >::nsubwin_ private
Definition at line 77 of file EnsembleCovariance4D.h.
static_
template<typename MODEL > std::unique_ptr<ModelSpaceCovarianceBase<MODEL> > oops::EnsembleCovariance4D< MODEL >::static_ private
Definition at line 80 of file EnsembleCovariance4D.h.
Referenced by oops::EnsembleCovariance4D< MODEL >::covar().
The documentation for this class was generated from the following file:
src/oops/base/EnsembleCovariance4D.h