OOPS Documentation: oops::Variational< MODEL > Class Template Reference
oops::Variational< MODEL > Class Template Reference
Variational data assimilation application.
#include <Variational.h>
Public Member Functions
Variational ()
Construct a variational application.
virtual ~Variational ()
Destroy a variational application.
int execute (const eckit::Configuration &fullConfig) const
Execute a variational application.
Public Member Functions inherited from oops::Application
Application ()
virtual ~Application ()
Private Types
using Geometry_ = Geometry< MODEL >
using Model_ = Model< MODEL >
using State_ = State< MODEL >
Private Member Functions
std::string appname () const
Detailed Description
template<typename MODEL>
class oops::Variational< MODEL >
Variational data assimilation application.
Variational is the top-level driver of variational data assimilation algorithms: 3D-Var, 4D-Var, 4D-Ens-Var and Weak Constraint 4D-Var.
Definition at line 49 of file Variational.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::Variational< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 50 of file Variational.h.
Model_
template<typename MODEL > using oops::Variational< MODEL >::Model_ = Model<MODEL> private
Definition at line 51 of file Variational.h.
State_
template<typename MODEL > using oops::Variational< MODEL >::State_ = State<MODEL> private
Definition at line 52 of file Variational.h.
Constructor & Destructor Documentation
Variational()
template<typename MODEL > oops::Variational< MODEL >::Variational () inline
Construct a variational application.
Instantiate various factories
Definition at line 56 of file Variational.h.
                 {
     instantiateCostFactory<MODEL>();
     instantiateCovarFactory<MODEL>();
     instantiateMinFactory<MODEL>();
     instantiateObsErrorFactory<MODEL>();
     instantiateTlmFactory<MODEL>();
   }
~Variational()
template<typename MODEL > virtual oops::Variational< MODEL >::~Variational () inline virtual
Destroy a variational application.
Definition at line 66 of file Variational.h.
 {}
Member Function Documentation
appname()
template<typename MODEL > std::string oops::Variational< MODEL >::appname () const inline private virtual
Implements oops::Application.
Definition at line 128 of file Variational.h.
{
     return "oops::Variational<" + MODEL::name() + ">";
   }
execute()
template<typename MODEL > int oops::Variational< MODEL >::execute (const eckit::Configuration & fullConfig) const inline virtual
Execute a variational application.
Setup the outer-loop geometry
Setup the non-linear model
Setup the cost function; the cost function type (3D-Var, 4D-Var, ..) is selected at run time; the specific cost function object is produced by the cost function factory;
The background is constructed inside the cost function because its valid time within the assimilation window can be different (3D-Var vs. 4D-Var), it can be 3D or 4D (strong vs weak constraint), etc...
Perform incremental variational assimilation
Skip final trajectory (if the late 4D start mechnism is active)
Obtain the analysis
Save the analysis and compute final diagnostics (evaluate cost function)
Implements oops::Application.
Definition at line 69 of file Variational.h.
{
     const eckit::LocalConfiguration resolConfig(fullConfig, "resolution");
     const Geometry_ resol(resolConfig);
     const eckit::LocalConfiguration modelConfig(fullConfig, "model");
     const Model_ model(resol, modelConfig);
     Log::trace() << "Variational: model has been set up" << std::endl;
     const eckit::LocalConfiguration cfConf(fullConfig, "cost_function");
     std::unique_ptr<CostFunction<MODEL> > J(
         CostFactory<MODEL>::create(cfConf, resol, model));
     Log::trace() << "Variational: cost function has been set up" << std::endl;
     IncrementalAssimilation<MODEL> incrementalAssimilation(*J);
     incrementalAssimilation.assimilate(fullConfig);
     Log::trace() << "Variational: incremantal assimilation done" << std::endl;
     if (incrementalAssimilation.skipFinalNonlinearTrajectory()) return 0;
     std::shared_ptr<ControlVariable<MODEL> > xx(
         incrementalAssimilation.getAnalysis());
     PostProcessor<State_> post;
     const util::DateTime winbgn(cfConf.getString("window_begin"));
     if (fullConfig.has("output")) {
       const eckit::LocalConfiguration outConfig(fullConfig, "output");
       post.enrollProcessor(new StateWriter<State_>(winbgn, outConfig));
     }
     const eckit::LocalConfiguration finalConfig(fullConfig, "final");
     if (finalConfig.has("prints")) {
       const eckit::LocalConfiguration prtConfig(finalConfig, "prints");
       post.enrollProcessor(new StateInfo<State_>("final", prtConfig));
     }
     J->evaluate(*xx, finalConfig, post);
     return 0;
   }
References oops::IncrementalAssimilation< MODEL >::assimilate(), oops::PostProcessor< FLDS >::enrollProcessor(), oops::IncrementalAssimilation< MODEL >::getAnalysis(), and oops::IncrementalAssimilation< MODEL >::skipFinalNonlinearTrajectory().
Referenced by oops::AssimEnsemble< MODEL >::execute().
The documentation for this class was generated from the following file:
src/oops/runs/Variational.h