OOPS Documentation: oops::ModelAuxNN< MODEL > Class Template Reference
oops::ModelAuxNN< MODEL > Class Template Reference
#include <ModelAuxNN.h>
Public Member Functions
ModelAuxNN ()
virtual ~ModelAuxNN ()
int execute (const eckit::Configuration &fullConfig) const
Public Member Functions inherited from oops::Application
Application ()
virtual ~Application ()
Private Types
using Geometry_ = Geometry< MODEL >
using Model_ = Model< MODEL >
using ModelAux_ = ModelAuxControl< MODEL >
using ModelAuxEstimator_ = ModelAuxControlEstimator< MODEL >
using State_ = State< MODEL >
Private Member Functions
std::string appname () const
Detailed Description
template<typename MODEL>
class oops::ModelAuxNN< MODEL >
Definition at line 35 of file ModelAuxNN.h.
Member Typedef Documentation
Geometry_
template<typename MODEL > using oops::ModelAuxNN< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 36 of file ModelAuxNN.h.
Model_
template<typename MODEL > using oops::ModelAuxNN< MODEL >::Model_ = Model<MODEL> private
Definition at line 37 of file ModelAuxNN.h.
ModelAux_
template<typename MODEL > using oops::ModelAuxNN< MODEL >::ModelAux_ = ModelAuxControl<MODEL> private
Definition at line 38 of file ModelAuxNN.h.
ModelAuxEstimator_
template<typename MODEL > using oops::ModelAuxNN< MODEL >::ModelAuxEstimator_ = ModelAuxControlEstimator<MODEL> private
Definition at line 39 of file ModelAuxNN.h.
State_
template<typename MODEL > using oops::ModelAuxNN< MODEL >::State_ = State<MODEL> private
Definition at line 40 of file ModelAuxNN.h.
Constructor & Destructor Documentation
ModelAuxNN()
template<typename MODEL > oops::ModelAuxNN< MODEL >::ModelAuxNN () inline
Definition at line 44 of file ModelAuxNN.h.
 {}
~ModelAuxNN()
template<typename MODEL > virtual oops::ModelAuxNN< MODEL >::~ModelAuxNN () inline virtual
Definition at line 46 of file ModelAuxNN.h.
 {}
Member Function Documentation
appname()
template<typename MODEL > std::string oops::ModelAuxNN< MODEL >::appname () const inline private virtual
Implements oops::Application.
Definition at line 84 of file ModelAuxNN.h.
{
     return "oops::ModelAuxNN<" + MODEL::name() + ">";
   }
execute()
template<typename MODEL > int oops::ModelAuxNN< MODEL >::execute (const eckit::Configuration & fullConfig) const inline virtual
Implements oops::Application.
Definition at line 48 of file ModelAuxNN.h.
{
     //  Setup resolution
     const eckit::LocalConfiguration resolConfig(fullConfig, "resolution");
     const Geometry_ resol(resolConfig);
     //  Setup Model
     const eckit::LocalConfiguration modelConfig(fullConfig, "model");
     const Model_ model(resol, modelConfig);
     //  Setup background state
     const eckit::LocalConfiguration initialConfig(fullConfig, "initial");
     const eckit::LocalConfiguration xbConfig(initialConfig, "xb");
     State_ xb(resol, model, xbConfig);
     Log::info() << "Background state: " << xb.norm() << std::endl;
     //  Setup an state
     const eckit::LocalConfiguration anConfig(initialConfig, "an");
     State_ an(resol, model, anConfig);
     Log::info() << "Previous Analysis state: " << an.norm() << std::endl;
     //  Setup model error estimator
     const ModelAuxEstimator_ moderrEstimator(resol, model, initialConfig);
     //  Setup augmented state
     ModelAux_ moderr(resol, model, initialConfig);
     //  Estimate model error
     moderrEstimator.estimate(xb, an, moderr);
     //  Compute the model error norm
     Log::test() << "ModelAuxControl state: " << moderr.norm() << std::endl;
     return 0;
   }
References oops::ModelAuxControlEstimator< MODEL >::estimate(), oops::ModelAuxControl< MODEL >::norm(), and oops::State< MODEL >::norm().
The documentation for this class was generated from the following file:
src/oops/runs/ModelAuxNN.h