OOPS Documentation: oops::CostJo< MODEL > Class Template Reference
oops::CostJo< MODEL > Class Template Reference
\(J_o \) term of the cost function
#include <CostJo.h>
Public Types
enum OS : size_t { NotScreened = 0, Screened = 1, Quadratic = 2 }
Define which ObservationSpace to use.
Public Member Functions
const std::string classname () const override
CostJo (const eckit::Configuration &, const Geometry_ &geom, const util::DateTime &, const util::DateTime &, const util::Duration &, const bool subwindows=false)
Constructor.
virtual ~CostJo ()
Destructor.
std::shared_ptr< PostBase< State_ > > initialize (const CtrlVar_ &, const eckit::Configuration &) const override
Various set ups prior to the integration of the model.
std::shared_ptr< PostBase< State_ > > initializeTraj (const CtrlVar_ &, const Geometry_ &, const eckit::Configuration &) override
Various set ups prior to the linearisation trajectory computation.
double finalize (const eckit::Configuration &) const override
Various computations after the integration of the model.
double finalizeTraj (const eckit::Configuration &) override
Various computations after the linearisation trajectory computation.
void screenObservations (std::unique_ptr< Observations_ > &, const eckit::Configuration &) const
Screen observations.
std::shared_ptr< PostBaseTL< Increment_ > > setupTL (const CtrlInc_ &) const override
Initialize ObserverTL (computes \(G(dx) \)) before starting the TL run.
std::shared_ptr< PostBaseAD< Increment_ > > setupAD (std::shared_ptr< const GeneralizedDepartures >, CtrlInc_ &) const override
Initialize ObserverAD (computes \(G^T y\)) before starting the AD run.
Departures_ * multiplyCovar (const GeneralizedDepartures &) const override
Multiply by \(R\).
Departures_ * multiplyCoInv (const GeneralizedDepartures &) const override
Multiply by \(R^{-1}\).
Departures_ * newDualVector () const override
Provide new (zeroed) departures.
Departures_ * newDepartures () const override
Return departures ie \(y - {\cal G}(x) \).
Departures_ * newGradientFG () const override
Return gradient at first guess ie \(R^{-1}(y - {\cal G}(x))\).
void resetLinearization () override
Reset obs operator trajectory.
double printJo (const Departures_ &, const Departures_ &, const size_t &type) const
Print Jo table.
const ObsSpaces_ & obspaces () const
Access observation spaces.
void checkpoint (eckit::LocalConfiguration &) const
Checkpoint Jo.
void restart (const eckit::Configuration &)
Restart Jo.
void setBackground (const CtrlVar_ &xb) const
Set xb.
Public Member Functions inherited from oops::CostTermBase< MODEL >
virtual ~CostTermBase ()
Destructor.
Private Types
using CtrlVar_ = ControlVariable< MODEL >
using CtrlInc_ = ControlIncrement< MODEL >
using Departures_ = Departures< MODEL >
using Observations_ = Observations< MODEL >
using Geometry_ = Geometry< MODEL >
using GeoVaLs_ = GeoVaLs< MODEL >
using State_ = State< MODEL >
using Increment_ = Increment< MODEL >
using ObsAuxControls_ = ObsAuxControls< MODEL >
using ObsErrors_ = ObsErrors< MODEL >
using ObsOperators_ = ObsOperators< MODEL >
using ObsSpaces_ = ObservationSpaces< MODEL >
using LinearObsOperators_ = LinearObsOperators< MODEL >
Private Attributes
const eckit::LocalConfiguration conf_
Configuration.
const Geometry_ & geom_
Constant reference to geometry.
const util::DateTime winbgn_
Beginning of the window.
const util::DateTime winend_
End of the window.
const util::Duration tslot_
Time slot duration.
const bool subwindows_
Logical controlling if sub-windows are enabled.
bool lsetupOnce_
Logical controlling various set ups.
bool lscreenObservations_
Logical controlling screening of observations.
const CtrlVar_ * xb_
Pointer to background.
const CtrlVar_ * fg_
Pointer to first guess.
std::unique_ptr< ObsSpaces_ > obsSpaces_
Observation spaces.
std::unique_ptr< ObsOperators_ > hop_
Non-linear observation operators.
std::shared_ptr< LinearObsOperators_ > hoptlad_
Linear observation operators.
std::unique_ptr< ObsErrors_ > R_
Observation error covariance matrices.
std::unique_ptr< Observations_ > yobs_
Observations.
std::unique_ptr< Departures_ > ydep_
Departures : \(y_{obs} - {\cal G}(x_{fg}) \).
std::unique_ptr< Departures_ > gradFG_
std::shared_ptr< Observer< MODEL, State_ > > pobs_
Observer attached by \(J_o\) to the model integration.
std::shared_ptr< Observer< MODEL, State_ > > pobstraj_
std::shared_ptr< ObserverTL< MODEL, Increment_ > > pobstl_
ObserverTL attached by \(J_o\) to the linear model integration.
std::shared_ptr< ObserverAD< MODEL, Increment_ > > pobsad_
ObserverAD attached by \(J_o\) to the adjoint model integration.
Detailed Description
template<typename MODEL>
class oops::CostJo< MODEL >
\(J_o \) term of the cost function
The CostJo class encapsulates the \(J_o \) term of the cost function. It inherits from a pure abstract base class CostTermBase which defines a common interface to all the cost function terms except for the \(J_b \) term.
The \(J_o \) term has the following structure:
\[ J_o = \frac{1}{2} [y - {\cal G}(x)]^T R^{-1} [y - {\cal G}(x)] \]
\[ J_o = \sum_l J_o^l = \frac{1}{2} \sum_l [\bar{y}_{l} - {\cal \bar{G}}_{l}(\bar{x}_{l})]^T \bar{R}_{l}^{-1} [\bar{y}_{l} - {\cal \bar{G}}_{l}(\bar{x}_{l})] = \frac{1}{2} \sum_j \sum_k \sum_l [ \bar{y}_{k,l}^j - {\cal \bar{G}}_{k,l}^j (\bar{x}_{k,l}^j)]^T [\bar{R}_{k,l}^j]^{-1} [ \bar{y}_{k,l}^j - {\cal \bar{G}}_{k,l}^j (\bar{x}_{k,l}^j) ] \]
-> Loop over l - loop over observation types;
-> Loop over k - loop over the time steps spanning the assimilation window/sub-window;
-> Loop over j - loop over sub-windows;
Note: the loop over the number of sub-windows is external to CostJo.
Note: that the \(J_o \) class contains objects, which are themselves containers to allow exposing to OOPS multiple observation types (look k above):
-> ObservationSpaces -> a vector of ObservationSpace objects;
-> ObsOperators -> a vector of ObsOperator objects;
-> LinearObsOperators -> a vector of LinearObsOperator objects;
-> ObsErrors -> a vector of ObsErrorCovariance objects;
-> Observations -> a vector of ControlObsVector objects;
-> Departures -> a vector of ControlObsVector objects;
Note:
-> \({\cal G}(x) \) is computed by the Observer post-processor (attached to the non-linear forecast);
-> \(y \) is implemented by Observations class;
-> \(y - {\cal G}(x) \) is stored by Departures class;
-> \(R \) is implemented by ObsErrors class;
In more detail, the \(J_o \) term includes the constrained observation bias component (constrained VarBC); consider \(J_o^l \) corresponding to the l-th observation space (observation type):
\[ J_o^l = \frac{1}{2} (\bar{y}_l - {\cal \bar{G}}_l (\bar{x}_l))^T [\bar{R}_l]^{-1} (\bar{y}_l - {\cal \bar{G}}_l (\bar{x}_l)) = \frac{1}{2} (\begin{bmatrix} \tilde{y}_l \\ \tilde{b}_l \end{bmatrix} - \begin{bmatrix} {\cal \tilde{G}}_l && {\cal \tilde{P}}_l \\ 0 && {\cal \tilde{P}}_l \end{bmatrix} \begin{bmatrix} x \\ \tilde{\beta}_l \end{bmatrix})^T \begin{bmatrix} \tilde{R}_l^{-1} && 0 \\ 0 && \tilde{R}_{\beta,l}^{-1} \end{bmatrix} (\begin{bmatrix} \tilde{y}_l \\ \tilde{b}_l \end{bmatrix} - \begin{bmatrix} {\cal \tilde{G}}_l && {\cal \tilde{P}}_l \\ 0 && {\cal \tilde{P}}_l \end{bmatrix} \begin{bmatrix} x \\ \tilde{\beta}_l \end{bmatrix})^T \]
-> the non-linear observation operator associated with l-th ObservationSpace
\[ \begin{bmatrix} {\cal \tilde{H}}_l && {\cal \tilde{P}}_l \end{bmatrix} \]
is implemented by obsEquiv method of ObsOperator; note that \({\cal \tilde{G}}_l = {\cal \tilde{H}}_l {\cal I} \), where \({\cal I} \) is an interpolation operator
-> the non-linear observation bias opeartor \({\cal \tilde{P}}_l \) associated with l-th Observation space is is implemented by obsBiasEquiv method of ObsOperator;
-> the observation and bias error covariance matrix associated with l-th ObservationSpace:
\[ \begin{bmatrix} \tilde{R}_l^{-1} && 0 \\ 0 && \tilde{R}_{\beta,l}^{-1} \end{bmatrix} \]
is implemented by inverseMultiply method of ObsErrorCovariance class; \(\tilde{R}_l \) is observation error covariance matrix and \(\tilde{R}_{\beta,l}\) is observation bias error covariance matrix;
-> the control observation vector associated with l-th ObservationSpace:
\f[ \begin{bmatrix} \tilde{y}_l \\
                    \tilde{b}_l
    \end{bmatrix}
\f]
is implemented by ControlObsVector class. Observations class contains a
vector of ControlObsVector objects;
-> The departures associated with l-th ObservationSpace:
\f[ \begin{bmatrix} \tilde{d}_l \\
                    \tilde{d}_{c,l}
    \end{bmatrix} =
    \begin{bmatrix} \tilde{y}_l \\
                    \tilde{b}_l
    \end{bmatrix}
  - \begin{bmatrix} {\cal \tilde{G}}_l && {\cal \tilde{P}}_; \\
                      0                && {\cal \tilde{P}}_l
    \end{bmatrix}
    \begin{bmatrix} x \\
                    \beta_l
    \end{bmatrix}
\f]
are implemented by ControlObsVector class. Departures class contains a
vector of ControlObsVector objects.
For details on the implementation of VarQC refere to ObsErrorCovariance documentation.
Consider the quadratic \(J_o \) cost function term:
\[ J_o(dx) = G^T R^{-1} G (dx - d) \]
-> \(G (dx) \) is computed by ObserverTL; ObserverTL is a post processor which is attached to the tangent linear model trajectory (LinearModel::forecastTL). \(G \) has the same structure as \({\cal G} \) and \(dx \) has the same structure as \(x \);
-> \(G^T (dy) \) is computed by ObserverAD; ObserverAD is a post processor which is attached to the adjoint of the tangent linear model trajectory (LinearModel::forecastAD).
Definition at line 218 of file CostJo.h.
Member Typedef Documentation
CtrlInc_
template<typename MODEL > using oops::CostJo< MODEL >::CtrlInc_ = ControlIncrement<MODEL> private
Definition at line 220 of file CostJo.h.
CtrlVar_
template<typename MODEL > using oops::CostJo< MODEL >::CtrlVar_ = ControlVariable<MODEL> private
Definition at line 219 of file CostJo.h.
Departures_
template<typename MODEL > using oops::CostJo< MODEL >::Departures_ = Departures<MODEL> private
Definition at line 221 of file CostJo.h.
Geometry_
template<typename MODEL > using oops::CostJo< MODEL >::Geometry_ = Geometry<MODEL> private
Definition at line 223 of file CostJo.h.
GeoVaLs_
template<typename MODEL > using oops::CostJo< MODEL >::GeoVaLs_ = GeoVaLs<MODEL> private
Definition at line 224 of file CostJo.h.
Increment_
template<typename MODEL > using oops::CostJo< MODEL >::Increment_ = Increment<MODEL> private
Definition at line 226 of file CostJo.h.
LinearObsOperators_
template<typename MODEL > using oops::CostJo< MODEL >::LinearObsOperators_ = LinearObsOperators<MODEL> private
Definition at line 231 of file CostJo.h.
ObsAuxControls_
template<typename MODEL > using oops::CostJo< MODEL >::ObsAuxControls_ = ObsAuxControls<MODEL> private
Definition at line 227 of file CostJo.h.
ObsErrors_
template<typename MODEL > using oops::CostJo< MODEL >::ObsErrors_ = ObsErrors<MODEL> private
Definition at line 228 of file CostJo.h.
Observations_
template<typename MODEL > using oops::CostJo< MODEL >::Observations_ = Observations<MODEL> private
Definition at line 222 of file CostJo.h.
ObsOperators_
template<typename MODEL > using oops::CostJo< MODEL >::ObsOperators_ = ObsOperators<MODEL> private
Definition at line 229 of file CostJo.h.
ObsSpaces_
template<typename MODEL > using oops::CostJo< MODEL >::ObsSpaces_ = ObservationSpaces<MODEL> private
Definition at line 230 of file CostJo.h.
State_
template<typename MODEL > using oops::CostJo< MODEL >::State_ = State<MODEL> private
Definition at line 225 of file CostJo.h.
Member Enumeration Documentation
OS
template<typename MODEL > enum oops::CostJo::OS : size_t
Define which ObservationSpace to use.
Enumerator
NotScreened
Screened
Quadratic
Definition at line 237 of file CostJo.h.
 : size_t { NotScreened = 0, Screened = 1, Quadratic = 2 };
Constructor & Destructor Documentation
CostJo()
template<typename MODEL > oops::CostJo< MODEL >::CostJo (const eckit::Configuration & joConf, const Geometry_ & geom, const util::DateTime & winbgn, const util::DateTime & winend, const util::Duration & ts, const bool subwindows = false)
Constructor.
Depending on the configuration set up either not-screened or screened observation spaces.
Definition at line 362 of file CostJo.h.
     : conf_(joConf),
       geom_(geom),
       winbgn_(winbgn),
       winend_(winend),
       tslot_(ts),
       subwindows_(subwindows),
       lsetupOnce_(true),
       lscreenObservations_(false),
       xb_(),
       fg_(),
       obsSpaces_(),
       hop_(),
       hoptlad_(),
       R_(),
       yobs_(),
       ydep_(),
       gradFG_(),
       pobs_(),
       pobstraj_(),
       pobstl_(),
       pobsad_() {
   // Check if screening block is present
   if (conf_.has("screening")) {
     // Check if screening is requested
     bool lscreen = conf_.getBool("screening");
     Log::info() << "CostJo::CostJo lscreen = " << lscreen << std::endl;
     if (lscreen) {
       // Load un-screened ObservationSpaces if screening is requested
       obsSpaces_.reset(
           new ObsSpaces_(conf_, geom_, winbgn_, winend_, OS::NotScreened));
     } else {
       // Load screened ObservationSpaces if screening is not requested
       obsSpaces_.reset(
           new ObsSpaces_(conf_, geom_, winbgn_, winend_, OS::Screened));
     }
   } else {
     // Load screened ObservationSpaces if screening block is missing
     obsSpaces_.reset(
         new ObsSpaces_(conf_, geom_, winbgn_, winend_, OS::Screened));
   }
   Log::trace() << "CostJo:CostJo done" << std::endl;
 }
References oops::CostJo< MODEL >::conf_, oops::CostJo< MODEL >::geom_, oops::CostJo< MODEL >::obsSpaces_, oops::CostJo< MODEL >::winbgn_, and oops::CostJo< MODEL >::winend_.
~CostJo()
template<typename MODEL > virtual oops::CostJo< MODEL >::~CostJo () inline virtual
Destructor.
Definition at line 245 of file CostJo.h.
 {}
Member Function Documentation
checkpoint()
template<typename MODEL > void oops::CostJo< MODEL >::checkpoint (eckit::LocalConfiguration & conf) const virtual
Checkpoint Jo.
Implements oops::CostTermBase< MODEL >.
Definition at line 804 of file CostJo.h.
{
   if (conf.has("Jo")) {
     Log::info() << "CostJo<MODEL>::checkpoint starting" << std::endl;
     obsSpaces_->saveObservations();
     Log::info() << "CostJo<MODEL>::checkpoint done" << std::endl;
   }
 }
classname()
template<typename MODEL > const std::string oops::CostJo< MODEL >::classname () const inline override virtual
Implements oops::CostTermBase< MODEL >.
Definition at line 234 of file CostJo.h.
 { return "Jo"; }
finalize()
template<typename MODEL > double oops::CostJo< MODEL >::finalize (const eckit::Configuration & conf) const override virtual
Various computations after the integration of the model.
This method is called after the non-linear model integration. Its purpose is to compute departures, perform screening if required, set up the observation error covariance matrix, VarQC weights, print Jo table, perform diagnostics if required. The Jo cost value is returned.
Retrieve observation equivalents \({\cal G}(x) \)
AROME: this is required for radar observations
Calculate departures \(d = y - {\cal G}(x) \)
Write the observation space component of the first guess IFS: this is required to write out the VarBC cycle file
Screen observations
Linearize the observation error covariance matrix R
Setup VarQC weights
Compute FG gradient \(R^{-1}d \)
Print JO table
Diagnostics
Reset the Observer
Implements oops::CostTermBase< MODEL >.
Definition at line 460 of file CostJo.h.
{
   std::unique_ptr<Observations_> yeqv(pobs_->release());
   Log::info() << "Jo Observation Equivalent: " << *yeqv << std::endl;
   // 1.5. Reload observations if H operator change the observation vector
   if (conf.has("reload_observations")) {
     yobs_->read(conf_);
   }
   ydep_.reset(new Departures_(*yobs_ - *yeqv));
   Log::info() << "Jo Departures: " << *ydep_ << std::endl;
   if (conf.has("statesObsAux")) {
     fg_->obsVar().write(conf);
   }
   if (lscreenObservations_) this->screenObservations(yeqv, conf);
   R_->linearize(*yeqv);
   if (conf.getBool("varQC.activate", false)) R_->setupWeights(*ydep_);
   gradFG_.reset(R_->inverseMultiply(*ydep_));
   double zjo = this->printJo(*ydep_, *gradFG_, OS::Screened);
   eckit::LocalConfiguration diagnostics;
   if (conf.has("diagnostics")) {
     diagnostics = eckit::LocalConfiguration(conf, "diagnostics");
     if (diagnostics.has("departures")) {
       const eckit::LocalConfiguration depconf(diagnostics, "departures");
       ydep_->save(depconf);
     }
   }
   pobs_.reset();
   // Reset the first guess pointer
   fg_ = nullptr;
   return zjo;
 }
finalizeTraj()
template<typename MODEL > double oops::CostJo< MODEL >::finalizeTraj (const eckit::Configuration & conf) override virtual
Various computations after the linearisation trajectory computation.
This method is called once the model linearisation trajectory is computed. Its purpose is to compute departures w.r.t. the linearisation trajectory and print the corresponding Jo table if required. The computed Jo cost is returned.
Retrieve observation equivalents
Compute departures w.r.t. the linearisation trajecotry
Print the linearisation trajectory JO-table if required
Store departures w.r.t. the linearisation trajectory if required
Implements oops::CostTermBase< MODEL >.
Definition at line 618 of file CostJo.h.
{
   std::unique_ptr<Observations_> yeqv(pobstraj_->release());
   Log::info() << "Jo Observation Equivalent:" << *yeqv << std::endl;
   Departures_ ydep(*yobs_ - *yeqv);
   Log::info() << "Jo Departures:" << ydep << std::endl;
   std::unique_ptr<Departures_> grad(R_->inverseMultiply(ydep));
   // Check config if the inner loop trajectory Jo needs to be printed
   bool printInnerLoopTrajJo = false;
   if (conf.has("printInnerLoopTrajJo"))
     printInnerLoopTrajJo = conf.getBool("printInnerLoopTrajJo");
   double zjo = 0.0;
   if (printInnerLoopTrajJo) {
     // Print JO table
     Log::info() << "Print inner loop trajectory JO-table" << std::endl;
     zjo = this->printJo(ydep, *grad, OS::Screened);
   } else {
     // Calculate JO
     for (std::size_t jj = 0; jj < ydep.size(); ++jj) {
       const double zz =
           0.5 * dot_product(ydep[jj].obsvector(), (*grad)[jj].obsvector());
       zjo += zz;
     }
   }
   if (conf.has("innerloop_departures")) {
     const eckit::LocalConfiguration depconf(conf, "innerloop_departures");
     ydep.save(depconf);
   }
   pobstraj_.reset();
   return zjo;
 }
References dot_product(), oops::Departures< MODEL >::save(), and oops::Departures< MODEL >::size().
initialize()
template<typename MODEL > std::shared_ptr< PostBase< State< MODEL > > > oops::CostJo< MODEL >::initialize (const CtrlVar_ & fg, const eckit::Configuration & conf) const override virtual
Various set ups prior to the integration of the model.
This method is called prior to the non-linear model integration. Its purpose is to construct the observation operator, observation error covariance matrix, read observations. It returns an Observer to be attached to the non-linear trajectory; the purpose of the Observer is to compute model equivalents at observation locations.
At each outer loop setup a switch to control if screening is on;
Store a reference to the first guess
Reset observation space if required
Construct \(\cal H\), R, y if required
Set up the Observer
Return the Observer
Implements oops::CostTermBase< MODEL >.
Definition at line 416 of file CostJo.h.
{
   ASSERT(lscreenObservations_ == false);
   if (conf.has("screening"))
     lscreenObservations_ = conf.getBool("screening.active");
   fg_ = &fg;
   if (not lsetupOnce_ && lscreenObservations_) {
     // Close ObservationSpaces
     obsSpaces_.reset();
     // Open new ObservationSpaces
     obsSpaces_.reset(
         new ObsSpaces_(conf_, geom_, winbgn_, winend_, OS::NotScreened));
   }
   if (lsetupOnce_ || lscreenObservations_) {
     // Setup once or reset operators if new screening is to be performed
     hop_.reset(new ObsOperators_(*obsSpaces_));
     R_.reset(new ObsErrors_(*obsSpaces_));
     yobs_.reset(new Observations_(*obsSpaces_));
     yobs_->read(conf_);
   }
   pobs_.reset(new Observer<MODEL, State_>(*obsSpaces_, *hop_, fg_->obsVar(),
                                           tslot_, subwindows_));
   return pobs_;
 }
References oops::ControlVariable< MODEL >::read().
initializeTraj()
template<typename MODEL > std::shared_ptr< PostBase< State< MODEL > > > oops::CostJo< MODEL >::initializeTraj (const CtrlVar_ & fg, const Geometry_ & , const eckit::Configuration & conf) override virtual
Various set ups prior to the linearisation trajectory computation.
This method is called prior to the forced model linearisation trajectory computation in the TrajecotrySaver. Its purpose is to construct the linear observation operator and the linearisation trajectory Observer. The method returns the Observer which is subsequently enrolled by the TrajecotrySaver; the purpose of this Observer is to compute the linearisation trajectory for the linear observation operator.
Set up the linear observation operator
Set up the linearisation trajectory observer
Return the linearisation trajectory observer
Implements oops::CostTermBase< MODEL >.
Definition at line 586 of file CostJo.h.
{
   util::Duration tltstep = tslot_;
   if (conf.has("linearmodel"))
     tltstep = util::Duration(conf.getString("linearmodel.tstep"));
   if (conf.has("timeslot"))
     tltstep = util::Duration(conf.getString("timeslot"));
   hoptlad_.reset();
   pobstraj_.reset();
   hoptlad_.reset(new LinearObsOperators_(*obsSpaces_));
   pobstraj_.reset(new Observer<MODEL, State_>(*obsSpaces_, *hop_, fg.obsVar(),
                                               tltstep, subwindows_, hoptlad_));
   return pobstraj_;
 }
References oops::ControlVariable< MODEL >::obsVar().
multiplyCoInv()
template<typename MODEL > Departures< MODEL > * oops::CostJo< MODEL >::multiplyCoInv (const GeneralizedDepartures & v1) const override virtual
Multiply by \(R^{-1}\).
Implements oops::CostTermBase< MODEL >.
Definition at line 717 of file CostJo.h.
{
   const Departures_ &y1 = dynamic_cast<const Departures_ &>(v1);
   return R_->inverseMultiply(y1);
 }
multiplyCovar()
template<typename MODEL > Departures< MODEL > * oops::CostJo< MODEL >::multiplyCovar (const GeneralizedDepartures & v1) const override virtual
Multiply by \(R\).
Implements oops::CostTermBase< MODEL >.
Definition at line 708 of file CostJo.h.
{
   const Departures_ &y1 = dynamic_cast<const Departures_ &>(v1);
   return R_->multiply(y1);
 }
newDepartures()
template<typename MODEL > Departures_* oops::CostJo< MODEL >::newDepartures () const inline override virtual
Return departures ie \(y - {\cal G}(x) \).
Implements oops::CostTermBase< MODEL >.
Definition at line 284 of file CostJo.h.
{
     return new Departures_(*ydep_);
   }
References oops::CostJo< MODEL >::ydep_.
newDualVector()
template<typename MODEL > Departures< MODEL > * oops::CostJo< MODEL >::newDualVector override virtual
Provide new (zeroed) departures.
Implements oops::CostTermBase< MODEL >.
Definition at line 726 of file CostJo.h.
{
   Departures_ *ydep = new Departures_(*obsSpaces_);
   ydep->zero();
   return ydep;
 }
References oops::Departures< MODEL >::zero().
newGradientFG()
template<typename MODEL > Departures_* oops::CostJo< MODEL >::newGradientFG () const inline override virtual
Return gradient at first guess ie \(R^{-1}(y - {\cal G}(x))\).
Implements oops::CostTermBase< MODEL >.
Definition at line 289 of file CostJo.h.
{
     return new Departures_(*gradFG_);
   }
References oops::CostJo< MODEL >::gradFG_.
obspaces()
template<typename MODEL > const ObsSpaces_& oops::CostJo< MODEL >::obspaces () const inline
Access observation spaces.
Definition at line 301 of file CostJo.h.
 { return *obsSpaces_; }
References oops::CostJo< MODEL >::obsSpaces_.
Referenced by oops::CostFunction< MODEL >::setupTerms().
printJo()
template<typename MODEL > double oops::CostJo< MODEL >::printJo (const Departures_ & dy, const Departures_ & grad, const size_t & type) const
Print Jo table.
Definition at line 748 of file CostJo.h.
{
   obsSpaces_->printJo(dy, grad);
   double zjo = 0.0;
   for (std::size_t jj = 0; jj < dy.size(); ++jj) {
     const double zz =
         0.5 * dot_product(dy[jj].obsvector(), grad[jj].obsvector());
     const unsigned nobs = dy[jj].size();
     if (nobs > 0) {
       switch (type) {
         case OS::Screened:
           Log::test() << "CostJo   : Nonlinear Jo = " << zz
                       << ", nobs = " << nobs << ", Jo/n = " << zz / nobs
                       << ", err = " << (*R_)[jj].getRMSE() << std::endl;
           break;
         case OS::NotScreened:
           Log::info() << "CostJo (not screened)   : Nonlinear Jo = " << zz
                       << ", nobs = " << nobs << ", Jo/n = " << zz / nobs
                       << ", err = " << (*R_)[jj].getRMSE() << std::endl;
           break;
         case OS::Quadratic:
           Log::info() << "  CostJo : Quadratic Jo = " << zz
                       << ", nobs = " << nobs << ", Jo/n = " << zz / nobs
                       << std::endl;
           break;
         default:
           Log::info() << "CostJo : wrong settings" << std::endl;
       }
       if (dy[jj].hasBias()) {
         ASSERT(grad[jj].hasBias());
         double zjc =
             0.5 * dot_product(dy[jj].biasvector(), grad[jj].biasvector());
         switch (type) {
           case OS::Screened:
             Log::test() << "CostJo   : Nonlinear JoCVarBC = " << zjc
                         << std::endl;
             break;
           case OS::NotScreened:
             Log::info() << "CostJo (not screened)  : Nonlinear JoCVarBC = "
                         << zjc << std::endl;
             break;
         }
       }
     } else {
       Log::info() << "CostJo --- No Observations" << std::endl;
     }
     zjo += zz;
   }
   return zjo;
 }
References dot_product(), oops::Departures< MODEL >::size(), and type().
Referenced by oops::UtHtRinvHUMatrix< MODEL >::computeDiagnostics().
resetLinearization()
template<typename MODEL > void oops::CostJo< MODEL >::resetLinearization override virtual
Reset obs operator trajectory.
Implements oops::CostTermBase< MODEL >.
Definition at line 735 of file CostJo.h.
{
   hoptlad_.reset();
   pobs_.reset();
   pobstraj_.reset();
   pobstl_.reset();
   pobsad_.reset();
   lsetupOnce_ = false;
   lscreenObservations_ = false;
 }
restart()
template<typename MODEL > void oops::CostJo< MODEL >::restart (const eckit::Configuration & conf) virtual
Restart Jo.
Implements oops::CostTermBase< MODEL >.
Definition at line 815 of file CostJo.h.
 {}
screenObservations()
template<typename MODEL > void oops::CostJo< MODEL >::screenObservations (std::unique_ptr< Observations_ > & yeqv, const eckit::Configuration & conf) const
Screen observations.
This method is called to perform screening of observations. Once the screening is completed, the observation operator, observation error covariance matrix, observations, departures and observation equivalents are reset.
Print unscreened Jo table (set up of observation error covariance matrix and VarQC weights is required)
Save departures in the current ObservationSpace
Get a vector of pointers to GeoVaLs from the Observer
Perform screening - this saves a screened ObservationSpaces
Close the current ObservationSpaces and read in the screened ObservationSpaces
Reset the observation error covariance matrix \(R\)
Reset the non-linear observation operator \(\cal G\)
Reset observations
Reset departures
Compute observation equivalents as \({\cal G}(x) = y - d \)
Reset the observation space component of the first guess
Reset the observation space component of the background
Definition at line 523 of file CostJo.h.
{
   // ---------------------------------------------------------------------------
   // MC: should be implemented as a post-processor in the Observer at some point
   // ---------------------------------------------------------------------------
   R_->linearize(*yeqv);
   if (conf.getBool("varQC.activate", false)) R_->setupWeights(*ydep_);
   std::unique_ptr<Departures_> gradFG(R_->inverseMultiply(*ydep_));
   double zjo = this->printJo(*ydep_, *gradFG, OS::NotScreened);
   Log::debug() << "CostJo (before screening)" << zjo << std::endl;
   const eckit::LocalConfiguration depconf(conf, "screening.departures");
   ydep_->save(depconf);
   const std::vector<std::shared_ptr<GeoVaLs_> > &gvals = pobs_->geovals();
   obsSpaces_->screenObservations(*ydep_, gvals);
   obsSpaces_.reset();
   obsSpaces_.reset(
       new ObsSpaces_(conf_, geom_, winbgn_, winend_, OS::Screened));
   R_.reset(new ObsErrors_(*obsSpaces_));
   hop_.reset(new ObsOperators_(*obsSpaces_));
   yobs_.reset(new Observations_(*obsSpaces_));
   yobs_->read(conf_);
   ydep_.reset(new Departures_(*obsSpaces_));
   ydep_->read(depconf);
   yeqv.reset(new Observations_(*yobs_));
   *yeqv -= *ydep_;
   ObsAuxControls_ &obsvarfg = const_cast<ObsAuxControls_ &>(fg_->obsVar());
   obsvarfg.reset(*obsSpaces_, "fg", conf);
   ObsAuxControls_ &obsvarbg = const_cast<ObsAuxControls_ &>(xb_->obsVar());
   obsvarbg.reset(*obsSpaces_, "xb", conf);
 }
References oops::ObsAuxControls< MODEL >::reset().
setBackground()
template<typename MODEL > void oops::CostJo< MODEL >::setBackground (const CtrlVar_ & xb) const inline
Set xb.
Definition at line 310 of file CostJo.h.
 { xb_ = &xb; }
References oops::CostJo< MODEL >::xb_.
Referenced by oops::CostFunction< MODEL >::setupTerms().
setupAD()
template<typename MODEL > std::shared_ptr< PostBaseAD< Increment< MODEL > > > oops::CostJo< MODEL >::setupAD (std::shared_ptr< const GeneralizedDepartures > pv, CtrlInc_ & dx) const override virtual
Initialize ObserverAD (computes \(G^T y\)) before starting the AD run.
This method sets up the ObserverAD post-processor-ad. ObserverAD is typically attached to the adjoint model integration to compute \(G^T(y) \).
Implements oops::CostTermBase< MODEL >.
Definition at line 687 of file CostJo.h.
{
   ASSERT(hoptlad_);
   std::shared_ptr<const Departures_> dy =
       std::dynamic_pointer_cast<const Departures_>(pv);
   if (pobsad_ == nullptr)
     pobsad_.reset(new ObserverAD<MODEL, Increment_>(
         *obsSpaces_, *hoptlad_, dy, dx.obsVar(), tslot_, subwindows_));
   else {
     pobsad_->setupAD(dy, dx.obsVar());
   }
   return pobsad_;
 }
References oops::ControlIncrement< MODEL >::obsVar().
setupTL()
template<typename MODEL > std::shared_ptr< PostBaseTL< Increment< MODEL > > > oops::CostJo< MODEL >::setupTL (const CtrlInc_ & dx) const override virtual
Initialize ObserverTL (computes \(G(dx) \)) before starting the TL run.
This method sets up the ObserverTL post-processor-tl. ObserverTL is typically attached to the linear model integration to compute \(G(dx) \).
Implements oops::CostTermBase< MODEL >.
Definition at line 668 of file CostJo.h.
{
   ASSERT(hoptlad_);
   if (pobstl_ == nullptr)
     pobstl_.reset(new ObserverTL<MODEL, Increment_>(
         *obsSpaces_, *hoptlad_, dx.obsVar(), tslot_, subwindows_));
   else {
     pobstl_->setupTL(dx.obsVar());
   }
   return pobstl_;
 }
References oops::ControlIncrement< MODEL >::obsVar().
Member Data Documentation
conf_
template<typename MODEL > const eckit::LocalConfiguration oops::CostJo< MODEL >::conf_ private
Configuration.
Definition at line 313 of file CostJo.h.
Referenced by oops::CostJo< MODEL >::CostJo().
fg_
template<typename MODEL > const CtrlVar_* oops::CostJo< MODEL >::fg_ mutable private
Pointer to first guess.
Definition at line 327 of file CostJo.h.
geom_
template<typename MODEL > const Geometry_& oops::CostJo< MODEL >::geom_ private
Constant reference to geometry.
Definition at line 315 of file CostJo.h.
Referenced by oops::CostJo< MODEL >::CostJo().
gradFG_
template<typename MODEL > std::unique_ptr<Departures_> oops::CostJo< MODEL >::gradFG_ mutable private
Gradient at first guess : \(R^{-1} (y_{obs} - {\cal G}(x_{fg})) \)
Definition at line 341 of file CostJo.h.
Referenced by oops::CostJo< MODEL >::newGradientFG().
hop_
template<typename MODEL > std::unique_ptr<ObsOperators_> oops::CostJo< MODEL >::hop_ mutable private
Non-linear observation operators.
Definition at line 332 of file CostJo.h.
hoptlad_
template<typename MODEL > std::shared_ptr<LinearObsOperators_> oops::CostJo< MODEL >::hoptlad_ private
Linear observation operators.
Definition at line 334 of file CostJo.h.
lscreenObservations_
template<typename MODEL > bool oops::CostJo< MODEL >::lscreenObservations_ mutable private
Logical controlling screening of observations.
Definition at line 324 of file CostJo.h.
lsetupOnce_
template<typename MODEL > bool oops::CostJo< MODEL >::lsetupOnce_ mutable private
Logical controlling various set ups.
Definition at line 322 of file CostJo.h.
obsSpaces_
template<typename MODEL > std::unique_ptr<ObsSpaces_> oops::CostJo< MODEL >::obsSpaces_ mutable private
Observation spaces.
Definition at line 329 of file CostJo.h.
Referenced by oops::CostJo< MODEL >::CostJo(), and oops::CostJo< MODEL >::obspaces().
pobs_
template<typename MODEL > std::shared_ptr<Observer<MODEL, State_> > oops::CostJo< MODEL >::pobs_ mutable private
Observer attached by \(J_o\) to the model integration.
Definition at line 346 of file CostJo.h.
pobsad_
template<typename MODEL > std::shared_ptr<ObserverAD<MODEL, Increment_> > oops::CostJo< MODEL >::pobsad_ mutable private
ObserverAD attached by \(J_o\) to the adjoint model integration.
Definition at line 356 of file CostJo.h.
pobstl_
template<typename MODEL > std::shared_ptr<ObserverTL<MODEL, Increment_> > oops::CostJo< MODEL >::pobstl_ mutable private
ObserverTL attached by \(J_o\) to the linear model integration.
Definition at line 353 of file CostJo.h.
pobstraj_
template<typename MODEL > std::shared_ptr<Observer<MODEL, State_> > oops::CostJo< MODEL >::pobstraj_ mutable private
Observer attached by \(J_o\) to the TrajectorySaver for linearisation trajectory computation
Definition at line 350 of file CostJo.h.
R_
template<typename MODEL > std::unique_ptr<ObsErrors_> oops::CostJo< MODEL >::R_ mutable private
Observation error covariance matrices.
Definition at line 336 of file CostJo.h.
subwindows_
template<typename MODEL > const bool oops::CostJo< MODEL >::subwindows_ private
Logical controlling if sub-windows are enabled.
Definition at line 321 of file CostJo.h.
tslot_
template<typename MODEL > const util::Duration oops::CostJo< MODEL >::tslot_ private
Time slot duration.
Definition at line 319 of file CostJo.h.
winbgn_
template<typename MODEL > const util::DateTime oops::CostJo< MODEL >::winbgn_ private
Beginning of the window.
Definition at line 317 of file CostJo.h.
Referenced by oops::CostJo< MODEL >::CostJo().
winend_
template<typename MODEL > const util::DateTime oops::CostJo< MODEL >::winend_ private
End of the window.
Definition at line 318 of file CostJo.h.
Referenced by oops::CostJo< MODEL >::CostJo().
xb_
template<typename MODEL > const CtrlVar_* oops::CostJo< MODEL >::xb_ mutable private
Pointer to background.
Definition at line 326 of file CostJo.h.
Referenced by oops::CostJo< MODEL >::setBackground().
ydep_
template<typename MODEL > std::unique_ptr<Departures_> oops::CostJo< MODEL >::ydep_ mutable private
Departures : \(y_{obs} - {\cal G}(x_{fg}) \).
Definition at line 340 of file CostJo.h.
Referenced by oops::CostJo< MODEL >::newDepartures().
yobs_
template<typename MODEL > std::unique_ptr<Observations_> oops::CostJo< MODEL >::yobs_ mutable private
Observations.
Definition at line 338 of file CostJo.h.
The documentation for this class was generated from the following file:
src/oops/assimilation/CostJo.h